<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<a href="<?php echo $this->getProductUrl() ?>"><strong><?php echo $this->getProductName() ?></strong></a>
<?php if ($_options = $this->getOptionList()): ?>
    <ul>
    <?php foreach ($_options as $option): ?>
        <li><strong><?php echo $this->htmlEscape($option['label']) ?>:</strong><br />
        <? if (!is_array($option['value'])): ?>
            <?php echo $this->htmlEscape($option['value']) ?>
        <? else: ?>
            <?php echo implode('<br />', $option['value']) ?>
        <? endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
