<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var \Magento\Ui\Component\Form $this
 */
?>

<script data-mage-init='{ "Magento_Ui/js/core/app": "" }' type="application/json">
    <?php echo $this->getRenderContext()->getConfigBuilder()->toJsonNew($this->getRenderContext()->getStorage()); ?>
</script>
<script>
    var allowLocalCache = false;
</script>
<form data-bind="scope: '<?php echo $this->getDataScope(); ?>.areas'" class="entry-edit form-inline">
    <!-- ko template: getTemplate() --><!-- /ko -->
</form>
