<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var \Magento\Ui\Component\Form $this
 */

?>

<div class="form">
    <form class="">
        <?php foreach ($this->getProviders() as $provider): ?>
            <fieldset>
                <div>
                    <?php foreach ($provider->getMeta() as $field): ?>
                        <?php echo $this->renderElement($this->getFieldType($field), $field); ?>
                    <?php endforeach; ?>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </form>
</div>