<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var \Magento\Ui\Component\Form $this
 */

?>

<div class="form">
    <form class="">
        <?php foreach ($this->getMeta() as $formProviderKey => $formProviders): ?>
            <div><?php echo $formProviderKey ?>
                <?php foreach ($formProviders as $field): ?>
                    <?php $t = $this->getFieldType($field) ?>
                    <?php echo $this->renderElement($this->getFieldType($field), $field); ?>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </form>
</div>