<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this \Magento\RecurringPayment\Block\Catalog\Product\View\Payment */ ?>
<?php if ($dateHtml = $this->getDateHtml()): ?>
<dl class="payment product options">
    <dt class="title">
        <label for="<?php echo $this->getDateHtmlId() ?>"><?php echo __('Recurring Payment Start Date') ?></label>
    </dt>
    <dd class="content"><?php echo $dateHtml ?></dd>
</dl>
<?php endif; ?>
