<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this Magento_Paypal_Block_Payflow_Advanced_Form
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="form-list">
    <li>
    <?php echo __('You will be required to enter your payment details after you place an order.') ?>
    </li>
</ul>
