<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_System_Config_Fieldset_Hint
 */
?>
<?php
    if ($this->getHelpUrl()):
?>
<div id="<?php echo $this->getHtmlId(); ?>" class="paypal-payment-notice">
    <?php echo Mage::helper('Mage_Paypal_Helper_Data')->__('Not sure what PayPal payment method to use? Click <a href="%s" target="_blank">here</a> to learn more.', $this->getHelpUrl()); ?>
</div>
<?php
    endif;
?>
