<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('General Information') ?></span>
    </div>
    <table class="data-table">
        <tbody>
            <tr>
                <td><strong><?php echo __('Type') ?>:</strong></td>
                <td><?php echo $this->getTypeName() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo __('Event') ?>:</strong></td>
                <td><?php echo $this->getEntityTitle() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo __('Message') ?>:</strong></td>
                <td><?php echo $this->getEntityMessage() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo __('Website') ?>:</strong></td>
                <td><?php echo $this->getWebsiteName() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo __('Owner') ?>:</strong></td>
                <td><a href="<?php echo $this->getOwnerUrl() ?>"><?php echo $this->getOwnerName() ?></a></td>
            </tr>
            <tr>
                <td><strong><?php echo __('Created on') ?>:</strong></td>
                <td><?php echo $this->getCreatedAt() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo __('Recipients') ?>:</strong></td>
                <td><?php echo $this->getRegistrants() ?></td>
            </tr>
        </tbody>
    </table>
    <address>
        <strong><?php echo __('Shipping Address') ?></strong><br/>
        <?php echo $this->getShippingAddressHtml() ?>
    </address>
</div>

<div class="fieldset-wrapper">
    <?php echo $this->getChildHtml('sharing_form'); ?>
</div>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Gift Registry Items') ?></span>
    </div>
    <form id="update_form" method="post" action="<?php echo $this->getActionUrl() ?>">
        <?php echo $this->getBlockHtml('formkey')?>
        <?php echo $this->getChildHtml('entity_items'); ?>
        <div class="grid-actions"><?php echo $this->getChildHtml('update_button'); ?></div>
    </form>
</div>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Shopping Cart Items') ?></span>
    </div>
    <?php echo $this->getChildHtml('cart_items'); ?>
</div>
