<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head"><h4><?php echo __('General Information') ?></h4></div>
        <fieldset>
            <table cellspacing="2" class="box-left">
                <col width="120" />
                <col />
                <tbody>
                    <tr>
                        <td><strong><?php echo __('Type') ?>:</strong></td>
                        <td><?php echo $this->getTypeName() ?></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Event') ?>:</strong></td>
                        <td><?php echo $this->getEntityTitle() ?></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Message') ?>:</strong></td>
                        <td><?php echo $this->getEntityMessage() ?></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Website') ?>:</strong></td>
                        <td><?php echo $this->getWebsiteName() ?></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Owner') ?>:</strong></td>
                        <td><a href="<?php echo $this->getOwnerUrl() ?>"><?php echo $this->getOwnerName() ?></a></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Created on') ?>:</strong></td>
                        <td><?php echo $this->getCreatedAt() ?></td>
                    </tr>
                    <tr>
                        <td><strong><?php echo __('Recipients') ?>:</strong></td>
                        <td><?php echo $this->getRegistrants() ?></td>
                    </tr>
                </tbody>
            </table>
            <address class="box-right">
                <strong><?php echo __('Shipping Address') ?></strong><br/>
                <?php echo $this->getShippingAddressHtml() ?>
            </address>
        </fieldset>
    </div>
</div>

<div class="box-right">
    <?php echo $this->getChildHtml('sharing_form'); ?>
</div>

<div class="clear"></div>

<div class="entry-edit">
    <div class="entry-edit-head"><h4 ><?php echo __('Gift Registry Items') ?></h4></div>
        <fieldset>
            <form id="update_form" method="post" action="<?php echo $this->getActionUrl() ?>">
                <?php echo $this->getBlockHtml('formkey')?>
                <?php echo $this->getChildHtml('entity_items'); ?>
                <div align="right"><?php echo $this->getChildHtml('update_button'); ?></div>
            </form>
        </fieldset>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head"><h4 ><?php echo __('Shopping Cart Items') ?></h4></div>
        <fieldset>
            <?php echo $this->getChildHtml('cart_items'); ?>
        </fieldset>
    </div>
</div>
