<?php
/**
 * {license_notice}
 *
 * @category    Magento
 * @package     Magento_Cardgate
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var Magento_Cardgate_Block_Redirect $this */
?>
<?php echo $this->__('You will be redirected to CardGatePlus to finish your payment.'); ?>
<?php echo $this->getForm(); ?>
<script type="text/javascript">document.getElementById("cardgateplus_checkout").submit();</script>
