<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
            <form action="<?=$this->getUrl('newsletter/subscriber/new')?>" method="post" id="newsletter-validate-detail">
                <fieldset class="newsletter-signup">
                    <h5><?=$this->__('Sign up for our newsletter!')?></h5>
                    <p><?=$this->__('Sign up for our newsletter filled with the latest deals and promotios. Keep saving with Magento Demo!')?></p>
                    <p><input name="email" type="text" id="newsletter" class="required-entry validate-email input-text"/> <input type="submit" class="input-btn" value="<?=$this->__('Subscribe')?>"/></p>
                </fieldset>
            </form>
            <script type="text/javascript">
            <!--
                var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
            //-->
            </script>
