<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Category title template
 *
 * @see Magento_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = Mage::helper('Magento_Catalog_Helper_Output');
    $_category  = $this->getCurrentCategory();
?>
<div class="page-title category-title">
<?php if($this->IsRssCatalogEnable()): ?>
    <a href="<?php echo $this->getRssLink() ?>" title="<?php echo __('Subscribe to RSS Feed') ?>" class="rss-feed"><?php echo __('Subscribe to RSS Feed') ?></a>
<?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $this->getCurrentCategory()->getName(), 'name') ?></h1>
</div>
