<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $this->getItem() ?>
<?php $this->setPriceDataObject($_item) ?>
<tr<?php if ($this->canDisplayGiftmessage()): ?> class="border"<?php endif; ?>>
    <td class="giftmessage-single-item col-product">
        <?php if ($this->canDisplayContainer()): ?>
        <div id="<?php echo $this->getHtmlId() ?>" class="item-container">
        <?php endif; ?>
        <div class="item-text">
            <?php echo $this->getColumnHtml($_item, 'downloadable') ?>
        </div>
        <?php if ($this->canDisplayContainer()): ?>
        </div>
        <?php endif ?>
    </td>
    <td class="col-status"><?php echo $_item->getStatus() ?></td>
    <td class="col-price-original"><?php echo $this->displayPriceAttribute('original_price') ?></td>
    <td class="col-price">
        <?php echo $this->getColumnHtml($_item, 'price')?>
    </td>
    <td class="col-ordered-qty"><?php echo $this->getColumnHtml($_item, 'qty') ?></td>
    <td class="col-subtotal">
        <?php echo $this->getColumnHtml($_item, 'subtotal')?>
    </td>
    <td class="col-tax-amount"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-tax-percent"><?php echo $this->displayTaxPercent($_item) ?></td>
    <td class="col-discont"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?php echo $this->getColumnHtml($_item, 'total')?>
    </td>
</tr>
