<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<form action="<?php echo $this->getActionUrl() ?>" method="get" id="wishlist-search-form" class="form wishlist find">
    <fieldset class="fieldset" data-hasrequired="* <?php echo __('Required Fields') ?>">
        <legend class="legend"><span><?php echo __('Search Options') ?></span></legend><br>
        <div class="field firstname required">
            <label for="params_firstname" class="label"><span><?php echo __('First Name') ?></span></label>
            <div class="control">
                <input name="params[firstname]" id="params_firstname" type="text" value="<?php echo $this->getFormData('firstname') ?>" class="input-text required-entry">
            </div>
        </div>
        <div class="field lastname required">
            <label for="params_lastname" class="label"><span><?php echo __('Last Name') ?></span></label>
            <div class="control">
                <input name="params[lastname]" id="params_lastname" type="text" value="<?php echo $this->getFormData('lastname') ?>" class="input-text required-entry">
            </div>
        </div>
        <div class="actions">
            <input type="hidden" name="params[search]" value="type">
            <button type="submit" class="action search"><span><?php echo __('Search') ?></span></button>
        </div>
    </fieldset>
</form>

<form action="<?php echo $this->getActionUrl() ?>" method="get" id="wishlist-search-email-form" class="form wishlist find">
    <fieldset class="fieldset" data-hasrequired="* <?php echo __('Required Fields') ?>">
        <div class="field email required">
            <label for="params_email" class="label"><span><?php echo __('Owner Email') ?></span></label>
            <div class="control">
                <input name="params[email]" id="params_email" type="text" value="<?php echo $this->getFormData('email') ?>" class="input-text required-entry validate-email">
            </div>
        </div>
        <div class="actions">
            <input type="hidden" name="params[search]" value="email">
            <button type="submit" class="action search"><span><?php echo __('Search') ?></span></button>
        </div>
    </fieldset>
</form>

<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                $('#wishlist-search-form')
                    .add('#wishlist-search-email-form').validation();
            });
    })(jQuery);
</script>


