<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            orderEditDialog: [
                '<?php echo $this->getViewFileUrl('Magento_Sales::order/edit/message.js')?>'
            ]
        });
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>
