<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->getItems()->getSize()):?>
	<div class="box related-items">	
		<div class="head">
			<span class="corner"></span>
			<h3><?=__('Related')?></h3>
		</div>
		<div class="box-container">
			<div class="content">
				<ol>
				<?foreach($this->getItems() as $_item):?>
					<li><div class="product-images">
					<a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getSmallImageUrl()?>" alt="<?=$_item->getName()?>" width="32" height="32"/></a>
					</div>
					<div class="product-details">
						<p><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a><br/>
						<div class="price-box">Price: <?=$_item->getFormatedPrice()?></div>
						<a href="<?=$this->getUrl('checkout/cart/add',array('product_id'=>$_item->getId()))?>">Add to Cart</a><br/><a href="<?=$this->getUrl('wishlist/index/add', array('product'=>$_item->getId()))?>">Add to Wishlist</a></p>
					</div>
				</li>
				<?endforeach?>
				</ol>
			</div>
		</div>
	</div>

<?endif?>