<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getCustomerBalanceAmount()): ?>
    <tr>
        <td class="label">
            <?php echo __('Store Credit') ?>
        </td>
        <td>
            <?php echo $this->displayPrices(-$_source->getBaseCustomerBalanceAmount(), -$_source->getCustomerBalanceAmount()); ?>
        </td>
    </tr>
<?php endif; ?>
