<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php switch($this->getShowPart()): 
    case 'logo': ?>
        <?php /* Temporary tweek to show theme name instead of standard "Magento commerce" title */ ?>
        <?php $storeName = ($this->getLogoAlt() == 'Magento Commerce' && $this->getThemeName()) ? $this->getThemeName() : $this->getLogoAlt();?>
        <?php if ($this->getIsHomePage()):?>
        <strong class="logo">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
            <span><?php echo $storeName ?></span>
        </strong>
        <?php else:?>
        <a class="logo" href="<?php echo $this->getUrl(''); ?>" title="<?php echo $storeName ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $storeName ?>" />
            <span><?php echo $storeName ?></span>
        </a>
        <?php endif?>
    <?php break; ?>

    <?php case 'welcome': ?>
        <p class="welcome"><?php echo $this->getWelcome() ?></p>
    <?php break; ?>

    <?php case 'customer': ?>
        <?php if(Mage::getSingleton('Mage_Customer_Model_Session')->isLoggedIn()): ?>
            <li class="customer menu">
                <div class="customer">
                    <?php echo $this->getWelcome(); ?>
                <?php /*
                <div class="customer"><?php echo Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getName(); ?></p>
                */ ?>
                <button type="button" data-toggle="dropdown" class="action switch">
                    <span><?php echo $this->__('Options')?></span>
                </button>
                <menu data-target="dropdown">
                    <?php echo $this->getChildHtml();?>
                </menu>
            </li>
        <?php endif; ?>
    <?php break; ?>

    <?php case 'other': ?>
        <?php echo $this->getChildHtml(); ?>
    <?php break; ?>

<?php endswitch; ?>
