<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright  {copyright}
 * @license    {license_link}
 */

/**
 * @var $this Mage_Page_Block_Html_Title
 */
$cssClass = $this->getCssClass() ? ' ' . $this->getCssClass() : '';
$prefix = $this->getPrefix() ? '<span class="prefix">' . $this->getPrefix() . '</span>' : '';
$suffix = $this->getSuffix() ? '<span class="suffix">' . $this->getSuffix() . '</span>' : '';
$title = '';
if (trim($this->getPageTitle())) {
    $title = $prefix . '<span class="base">' . $this->getPageTitle() . '</span>' . $suffix;
}
?>
<?php if ($title): ?>
<hgroup class="page title<?php echo $cssClass; ?>">
    <h1 class="title"><?php echo $title ?></h1>
    <?php echo $this->getChildHtml(); ?>
</hgroup>
<?php endif; ?>