<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Page
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top','submenu', 1) ?>
<?php if ($_menu): ?>
<nav class="navigation">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>
<?php endif; ?>
