<?
/**
 * Template for Mage_Adminhtml_Block_Widget_Accordion
 */
?>
<dl id="<?=$this->getHtmlId()?>" class="accordion">
<?foreach ($this->getItems() as $_item):?>
    <?=$this->getChildHtml($_item->getId())?>
<?endforeach?>
</dl>
<script type="text/javascript">
    <?=$this->getHtmlId()?>AccordionJs = new varienAccordion('<?=$this->getHtmlId()?>', '<?=$this->getShowOnlyOne()?>');
</script>