<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this Mage_Core_Block_Template */

$havePriceVariation = array_reduce(
    $attribute['values'],
    function (&$r, $i) {
        return $r || !empty($i['pricing_value']);
    },
    false
);
$id = $this->escapeHtml($attribute['attribute_id']);
?>

<div class="entry-edit
            <?php echo $havePriceVariation ? ' have-price' : '' ?>
            " <?php echo $this->getUiId('attribute-container', $attribute['attribute_code']) ?>>
    <input name="attributes[]" id="configurable_attribute_<?php echo $id ?>"
        value="<?php echo $id; ?>" type="hidden">
    <input value="<?php echo $this->escapeHtml($attribute['id']); ?>" type="hidden"
        name="product[configurable_attributes_data][<?php echo $id ?>][id]"/>
    <input value="<?php echo $this->escapeHtml($attribute['attribute_code']); ?>" type="hidden"
        name="product[configurable_attributes_data][<?php echo $id ?>][code]"/>
    <input value="<?php echo $id; ?>" type="hidden"
        name="product[configurable_attributes_data][<?php echo $id ?>][attribute_id]"/>
    <input value="<?php echo $this->escapeHtml($attribute['position']); ?>" type="hidden"
        name="product[configurable_attributes_data][<?php echo $id ?>][position]"/>

    <div class="fieldset-wrapper collapsable-wrapper" id="<?php echo $id ?>-wrapper">
        <div class="fieldset-wrapper-title">
            <strong class="title" data-toggle="collapse" data-target="#<?php echo $id ?>-content">
                <span><?php echo $this->escapeHtml($attribute['label']); ?></span>
            </strong>
            <div class="actions">
                <button type="button" title="<?php echo $this->__('Delete Variations Group'); ?>" class="action-delete">
                    <span><?php echo $this->__('Delete Variations Group'); ?></span>
                </button>
            </div>
            <div class="draggable-handle" title="<?php echo $this->__('Sort Variations'); ?>"></div>
        </div>
        <div class="fieldset-wrapper-content collapse" id="<?php echo $id ?>-content" data-attribute-id="<?php echo $id ?>">
            <fieldset class="fieldset">
                <div class="field field-variation">
                    <label class="label"><span><?php echo $this->__('Variation Label'); ?></span></label>
                    <div class="control">
                        <input type="text" value="<?php echo $this->escapeHtml($attribute['label']); ?>"
                               name="product[configurable_attributes_data][<?php echo $id ?>][label]"
                               data-store-label="<?php echo $this->escapeHtml($attribute['label']); ?>"
                               class="store-label required-entry"/>
                    </div>
                    <div class="field-service">
                        <label for="attribute-<?php echo $id ?>" class="use-default">
                            <input value="1"
                                   type="checkbox"
                                   class="use-default-control"
                                   name="product[configurable_attributes_data][<?php echo $id ?>][use_default]"
                                   id="attribute-<?php echo $id ?>"/>
                            <span class="use-default-label"><?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Use Default')?></span>
                        </label>
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <table class="data-table">
                            <thead>
                                <tr>
                                    <th class="col-name"><?php echo $this->__('Label'); ?></th>
                                    <th class="col-change-price"><?php echo $this->__('Change Price'); ?></th>
                                    <th class="col-include"><?php echo $this->__('Include'); ?></th>
                                    <th class="col-actions hidden"></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php
                            $namePrefix = 'product[configurable_attributes_data][' . $id . '][values]';
                            foreach ($attribute['options'] as $option) {
                                ?>
                                <tr>
                                    <td class="col-name"><?php echo $this->escapeHtml($option['label']) ?></td>
                                    <td class="col-change-price" data-column="change-price">
                                        <?php
                                        $price_value = '';
                                        $isPercent = false;
                                        $include = false;
                                        $valueIndex = $option['value'];
                                        foreach ($attribute['values'] as $priceValue) {
                                            if ($valueIndex == $priceValue['value_index']) {
                                                $price_value = $priceValue['pricing_value'];
                                                $isPercent = (bool)$priceValue['is_percent'];
                                                $include = true;
                                                if (isset($priceValue['include'])) {
                                                    $include = $include && (bool)$priceValue['include'];
                                                }
                                                break;
                                            }
                                        }
                                        ?>
                                        <input type="hidden"
                                               name="<?php echo $namePrefix ?>[<?php echo $valueIndex ?>][value_index]"
                                               value="<?php echo $this->escapeHtml($valueIndex); ?>">

                                        <div class="field field-change-pricing">
                                            <div class="control">
                                                <div class="fields-group-2">
                                                    <div class="field field-pricing-value">
                                                        <div class="control">
                                                            <input type="text" class="pricing-value"
                                                                   name="<?php echo $namePrefix ?>[<?php echo $valueIndex ?>][pricing_value]"
                                                                   value="<?php echo $this->escapeHtml($price_value); ?>">
                                                        </div>
                                                    </div>
                                                    <div class="field field-pricing-measure">
                                                        <div class="actions-split actions-select" data-field="is-percent">
                                                            <input name="<?php echo $namePrefix ?>[<?php echo $valueIndex ?>][is_percent]" class='no-display' data-role="is-percent-change" value="<?php echo $isPercent ? 1 : 0; ?>"/>
                                                            <button type="button" class="action-toggle" data-toggle="dropdown">
                                                                <span><?php echo $isPercent ? $this->__('%') : Mage::app()->getLocale()->currency(Mage::app()->getBaseCurrencyCode())->getSymbol() ?></span>
                                                            </button>
                                                            <ul class="dropdown-menu" data-role="dropdown-menu"  data-mage-init="{menu: {}}">
                                                                <li data-value="0"><a class="item"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getBaseCurrencyCode())->getSymbol() ?></a></li>
                                                                <li data-value="1"><a class="item"><?php echo $this->__('%')?></a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="col-include">
                                        <input type="hidden"
                                               name="<?php echo $namePrefix ?>[<?php echo $valueIndex ?>][include]"
                                               value="0"/>
                                        <div class="field choice">
                                            <input type="checkbox" class="include"
                                                   name="<?php echo $namePrefix ?>[<?php echo $valueIndex ?>][include]"
                                                   value="1" <?php echo $include ? 'checked="checked"' : ''; ?> />
                                        </div>
                                    </td>
                                    <td class="col-actions hidden">
                                        <button type="button" class="action-delete" title="<?php echo $this->__('Delete'); ?>">
                                            <span><?php echo $this->__('Delete'); ?></span>
                                        </button>
                                    </td>
                                </tr>
                                <?php } ?>
                                <tr class="hidden">
                                    <td class="col-name">
                                        <div class="field">
                                            <div class="control">
                                                <input type="text" value="" placeholder="<?php echo $this->__('begin typing to add value'); ?>" />
                                            </div>
                                        </div>
                                    </td>
                                    <td class="col-change-price">
                                        <input type="hidden"
                                               name="name[]"
                                               value="">

                                        <div class="field field-change-pricing">
                                            <div class="control">
                                                <div class="fields-group-2">
                                                    <div class="field field-pricing-value">
                                                        <div class="control">
                                                            <input type="text" class="pricing-value"
                                                                   name="pricing_value[]"
                                                                   value="">
                                                        </div>
                                                    </div>
                                                    <div class="field field-pricing-measure">
                                                        <div class="control">
                                                            <select name="is_percent[]">
                                                                <option value="0"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getBaseCurrencyCode())->getSymbol() ?></option>
                                                                <option value="1"><?php echo $this->__('%')?></option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="col-include">
                                        <input type="hidden"
                                               name="include[]"
                                               value="0"/>
                                        <div class="field choice">
                                            <input type="checkbox" class="include"
                                                   name="include[]"
                                                   value="1"/>
                                        </div>
                                    </td>
                                    <td class="col-actions">
                                        <button type="button" class="action-delete" title="<?php echo $this->__('Delete'); ?>" disabled>
                                            <span><?php echo $this->__('Delete'); ?></span>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>

