<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="content-header">
<table cellspacing="0">
    <tr>
        <td><h3 class="icon-head head-categories"><?php echo $this->getHeader() ?></h3></td>
        <td class="form-buttons">
            <?php echo $this->getResetButtonHtml() ?>
            <?php if($this->getCategoryId()): ?>
                    <?php echo $this->getDeleteButtonHtml() ?>
            <?php endif; ?>
            <?php echo $this->getSaveButtonHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php if($this->hasStoreRootCategory()): ?>
    <?php echo $this->getTabsHtml() ?>
    <form id="category_edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <input type="hidden" name="category_products" id="in_category_products" value=""/>
    <div id="category_tab_content"></div>
    </form>

<script type="text/javascript">
//<![CDATA[
    categoryForm = new varienForm('category_edit_form');
    function categoryReset(url,useAjax){
        if(useAjax){
            var params = {active_tab_id:false};
            updateContent('<?php echo $this->getDeleteUrl() ?>', params, true);
        }else{
            location.href = '<?php echo $this->getDeleteUrl() ?>'
        }
    }
    function categoryDelete(url,useAjax){
        if(confirm('<?php echo Mage::helper('catalog')->__('Are you sure you want to delete this category?') ?>')){
            if(useAjax){
                updateContent('<?php echo $this->getDeleteUrl() ?>', false, true);
            }else{
                location.href = '<?php echo $this->getDeleteUrl() ?>'
            }
        }

    }
<?php if(($block = $this->getLayout()->getBlock('category.product.grid')) && ($_gridJsObject=$block->getJsObjectName())): ?>
    var categoryProducts = $H(<?php echo $this->getProductsJson() ?>);
    $('in_category_products').value = categoryProducts.toQueryString();

    function registerCategoryProduct(grid, element, checked){
        if(checked){
            if(element.positionElement){
                element.positionElement.disabled = false;
                categoryProducts.set(element.value, element.positionElement.value);
            }
        }
        else{
            if(element.positionElement){
                element.positionElement.disabled = true;
            }
            categoryProducts.unset(element.value);
        }
        $('in_category_products').value = categoryProducts.toQueryString();
        grid.reloadParams = {'selected_products[]':categoryProducts.keys()};
    }
    function categoryProductRowClick(grid, event){
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if(trElement){
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                <?php echo $_gridJsObject ?>.setCheckboxChecked(checkbox[0], checked);
            }
        }
    }
    function positionChange(event){
        var element = Event.element(event);
        if(element && element.checkboxElement && element.checkboxElement.checked){
            categoryProducts.set(element.checkboxElement.value, element.value);
            $('in_category_products').value = categoryProducts.toQueryString();
        }
    }

    var tabIndex = 1000;
    function categoryProductRowInit(grid, row){
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        var position = $(row).getElementsByClassName('input-text')[0];
        if(checkbox && position){
            checkbox.positionElement = position;
            position.checkboxElement = checkbox;
            position.disabled = !checkbox.checked;
            position.tabIndex = tabIndex++;
            Event.observe(position,'keyup',positionChange);
        }
    }
    <?php echo $_gridJsObject ?>.rowClickCallback = categoryProductRowClick;
    <?php echo $_gridJsObject ?>.initRowCallback = categoryProductRowInit;
    <?php echo $_gridJsObject ?>.checkboxCheckCallback = registerCategoryProduct;
    <?php echo $_gridJsObject ?>.rows.each(function(row){categoryProductRowInit(<?php echo $_gridJsObject ?>, row)});
<?php endif; ?>
    function updateContent(url, params, loader){
        var categoryContainer = $('content').getElementsBySelector('.main-col-inner')[0];
        if (!params) {
            var params = {active_tab_id:category_info_tabsJsTabs.activeTab.id};
        }

        new Ajax.Updater(
            categoryContainer,
            url + (url.match(new RegExp('\\?')) ? '&isAjax=true' : '?isAjax=true' ),
            {
               parameters:  params || {},
               method:      'post',
               loaderArea:  loader?categoryContainer:false,
               onComplete:  refreshEditArea.bind(this),
               evalScripts: true
            }
        );
    }

    function refreshEditArea(transport){
        setTimeout(function() {
            category_info_tabsJsTabs.moveTabContentInDest();
        }, 1000);
    }
    function categorySubmit(useAjax){
        var activeTab = document.createElement('INPUT');
        activeTab.type= 'hidden';
        activeTab.name= 'active_tab_id';
        activeTab.value = category_info_tabsJsTabs.activeTab.id;
        categoryForm.validator.form.appendChild(activeTab);
        if (!useAjax) {
            categoryForm.submit();
            return;
        }

        var params = {};
        var fields = $('category_edit_form').getElementsBySelector('input', 'select');
        for(var i=0;i<fields.length;i++){
            if (!fields[i].name) {
                continue;
            }
            params[fields[i].name] = fields[i].getValue();
        }
        updateContent('<?php echo $this->getSaveUrl() ?>', params, true);
        if (tree && tree.storeId==0) {
            var currentNode = tree.getNodeById(tree.currentNodeId);
            if (currentNode) {
                if (params['general[is_active]']) {
                    var oldClass = 'no-active-category';
                    var newClass = 'active-category';
                } else {
                    var oldClass = 'active-category';
                    var newClass = 'no-active-category';
                }
                currentNode.ui.wrap.firstChild.removeClassName(oldClass);
                currentNode.ui.wrap.firstChild.addClassName(newClass);
                var name = currentNode.text;
                if (!name.match(/(\(\d+\))/)) {
                   name = params['general[name]'];
                } else {
                    name = name.replace(/(.+)\(/,params['general[name]']+' (');
                }
                currentNode.setText(name);
            }
        }
    }
//]]>
</script>

<?php else: ?>
<div class="messages warning-msg">
    <?php echo Mage::helper('catalog')->__('Set root category for this store in the <a href="%s">configuration</a>', $this->getStoreConfigurationUrl()) ?>
</div>
<?php endif; ?>
