
<table cellspacing="0" width="100%">
    <tr>
        <td class="content-left-nav">
            <?=$this->getTabsHtml()?>
        </td>
        <td>
            <div class="content-header">
                <table cellspacing="0" class="grid-header"> 
                    <tr>
                        <td style="width:30%;"><h3><?=$this->getHeader()?></h3></td>
                        <td class="a-right">
                            <?=$this->getResetButtonHtml()?>
                            <?if($this->getCategoryId()):?>
                                    <?=$this->getDeleteButtonHtml()?>
                            <?endif;?>
                            <?=$this->getSaveButtonHtml()?>
                        </td>
                    </tr>
                </table>
            </div>
            <form id="category_edit_form" action="<?=$this->getSaveUrl()?>" method="POST">
            <input type="hidden" id="in_category_products" name="products" value="<?=$this->getProductIdsString()?>"/>
            <div id="category_tab_content"></div>
            </form>
        </td>
    </tr>
</table>
<script type="text/javascript" language="javascript">
    var categoryForm = new varienForm('category_edit_form');
    
    function categoryDelete(){
        if(confirm('<?=__('Are you sure?')?>')){
            location.href = '<?=$this->getDeleteUrl()?>'
        }
    }
<?if($_gridJsObject=$this->getLayout()->getBlock('category.product.grid')->getJsObjectName()):?>
    function registerCategoryProduct(grid, element, checked){
        var products = $F('in_category_products');
        if(checked){
            products+=','+element.value;
        }
        else{
            var re = new RegExp('(^|,)'+element.value+'(,|$)', 'g');
            products = products.replace(re, ',')
        }
        products = products.replace(/(^,+|,+$)/, '');
        $('in_category_products').value = products;
        grid.reloadParams = {selected_proudcts:products};
    }
    function categoryProductRowClick(grid, event){
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if(trElement){
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                <?=$_gridJsObject?>.setCheckboxChecked(checkbox[0], checked);
            }
        }
    }
    <?=$_gridJsObject?>.rowClickCallback = categoryProductRowClick;
    <?=$_gridJsObject?>.checkboxCheckCallback = registerCategoryProduct;
<?endif;?>
</script>