<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Permissions tab template
 *
 * @see \Magento\CatalogPermissions\Block\Adminhtml\Catalog\Category\Tab\Permissions
 */
?>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li><?php echo __('Permissions do not depend on store views.') ?></li>
        </ul>
    </li>
</ul>
<div class="entry-edit permissions custom-options" id="category_permissions_<?php echo $this->getCategoryId(); ?>">
    <div class="entry-edit-head">
        <h4><?php echo __('Category Permissions') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>

    <div class="box items">
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
window.categoryPermissionsTab = new Enterprise.CatalogPermissions.CategoryTab('category_permissions_<?php echo $this->getCategoryId(); ?>', <?php echo $this->getConfigJson(); ?>);
//]]>
</script>
