<table cellspacing="0" width="100%">
    <tr>
        <td style="border-right:2px solid #d5dbe1;padding-rigth:20px;width:25%;">
            <label for="set_switcher">Choose Attribute Set:</label>
            <?=$this->getSetsFilterHtml()?>
            <?=$this->getGroupTreeHtml()?>
        </td>
        <td style="border-right:2px solid #d5dbe1;padding-left:20px;padding-rigth:20px;width:30%;">
            <?=$this->getAttributeTreeHtml()?>
        </td>
        <td style="padding-left:20px;padding-rigth:20px;">
            <?=$this->getSetFormHtml();?>
            <?=$this->getGroupFormHtml();?>
            <?=$this->getAttributeFormHtml();?>
        </td>
    </tr>
</table>