<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<button title="<?php echo $this->__('Delete Wishlist') ?>" onclick="return deleteWishlist(<?php echo $this->getWishlistInstance()->getId();?>);" class="button btn-share left"><span><span><?php echo $this->__('Delete Wishlist') ?></span></span></button>
<script type="text/javascript">
//<![CDATA[
    function deleteWishlist(id)
    {
        if (confirm('<?php echo $this->__('You are about to delete your wish list.\nThis action cannot be undone.\nDo you want to proceed?');?>')) {
            var url = '<?php echo $this->getDeleteUrl();?>';
            url = url.gsub('%item%', id);
            new Ajax.Request(url, {
                method: 'post',
                onComplete: function(response){
                    setLocation('<?php echo $this->getRedirectUrl()?>');
                }
            });
        }
        return false;
    }
//]]>
</script>
