<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this \Magento\RecurringPayment\Block\Payment\View */ ?>
<?php if ($this->getIsAddress()): ?>

    <?php foreach ($this->getRenderedInfo() as $row): ?>
        <address><?php echo nl2br($this->escapeHtml($this->getObjectData($row, 'value'))) ?></address>
    <?php endforeach; ?>

<?php else: ?>

    <table class="data table">
        <caption class="table-caption"><?php echo __('Recurring Payment'); ?></caption>
        <tbody>
        <?php foreach ($this->getRenderedInfo() as $row): ?>
            <?php $isAmount = $this->getObjectData($row, 'is_amount'); ?>
            <tr>
                <th class="col label" scope="row"><?php echo $this->escapeHtml($this->getObjectData($row, 'label')) ?>:</th>
                <td class="col value"><?php echo $this->renderRowValue($row) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
