<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\GiftCardAccount\Block\Checkout\Cart\Giftcardaccount
 */
?>
<div class="giftcard">
    <h2><?php echo __('Gift Cards') ?></h2>
    <div id="giftcard_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo __('Data is loading, thanks for waiting . . .') ?>
    </span>
    <form id="giftcard-form" action="<?php echo $this->getUrl('magento_giftcardaccount/cart/add') ?>" method="post">
        <fieldset>
            <label for="giftcard-code"><?php echo __('Enter your gift card code.') ?></label>
            <div class="v-fix"><input class="input-text" id="giftcard-code" name="giftcard_code" data-validate="{required:true}" value="" /></div>
            <button class="button giftcard-btn" type="submit" value="<?php echo __('Add Gift Card') ?>"><span><span><?php echo __('Add Gift Card') ?></span></span></button>
            <button class="button check-gc-status" type="button" value="<?php echo __('Check Gift Card status and balance.') ?>"><span><span><?php echo __('Check Gift Card status and balance.') ?></span></span></button>
        </fieldset>
    </form>

    <script type="text/javascript">
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
                "<?php echo $this->getViewFileUrl('Magento_GiftCardAccount::js/gift-card.js')?>", function() {
                    $('#giftcard-form').giftCard({
                        giftCardCodeSelector: '#giftcard-code',
                        checkStatus: 'button.check-gc-status',
                        giftCardStatusUrl: '<?php echo $this->getUrl('magento_giftcardaccount/cart/quickCheck') ?>',
                        giftCardStatusId: '#giftcard_balance_lookup',
                        giftCardSpinnerId: '#gc-please-wait'
                    }).validation();
                });
        })(jQuery);
    </script>

</div>
