<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\GiftCardAccount\Block\Checkout\Cart\Giftcardaccount
 */
?>
<div class="block giftcard">
    <div class="title"><strong><?php echo __('Gift Cards') ?></strong></div>
    <div class="content">
        <div id="giftcard-balance-lookup"></div>
        <span id="gc-please-wait" class="load indicator" style="display:none;">
            <span><?php echo __('Please wait, loading...') ?></span>
        </span>
        <form class="form giftcard add" id="giftcard-form" action="<?php echo $this->getUrl('magento_giftcardaccount/cart/add') ?>" method="post"
              data-mage-init='{"giftCard": {
                "giftCardCodeSelector": "#giftcard-code",
                "checkStatus": ".action.check",
                "giftCardStatusUrl": "<?php echo $this->getUrl('magento_giftcardaccount/cart/quickCheck',  array('_secure' => true)) ?>",
                "giftCardStatusId": "#giftcard-balance-lookup",
                "giftCardSpinnerId": "#gc-please-wait",
                "messages": ".page.messages .messages"
              }}'>
            <fieldset class="fieldset">
                <div class="field">
                    <label class="label" for="giftcard-code"><span><?php echo __('Enter the gift card code') ?></span></label>
                    <div class="control">
                        <input class="input-text" type="text" id="giftcard-code" name="giftcard_code" data-validate="{required:true}" value="" />
                    </div>
                </div>
                <div class="actions">
                    <div class="primary">
                        <button class="action add" type="submit" value="<?php echo __('Add Gift Card') ?>">
                            <span><?php echo __('Add Gift Card') ?></span>
                        </button>
                    </div>
                    <div class="secondary">
                        <button class="action check" type="button" value="<?php echo __('Check Gift Card status and balance') ?>">
                            <span><?php echo __('Check Gift Card status and balance') ?></span>
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

</div>
