<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="filtered">
    <strong class="subtitle"><?php echo $this->__('Currently Shopping by:') ?></strong>
    <ol class="items">
    <?php foreach ($_filters as $_filter): ?>
        <li class="item">
            <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span>
            <span class="value"><?php echo $this->stripTags($_filter->getLabel()) ?></span>
            <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                if ($clearLinkUrl):
            ?>
                <a  class="action previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                    <span><?php echo $this->__('Previous') ?></span>
                </a>
                <a  class="action remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>">
                    <span><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                </a>
            <?php else: ?>
                <a  class="action remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>">
                    <span><?php echo $this->__('Remove This Item') ?></span>
                </a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
