<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var Magento_Banner_Block_Adminhtml_Banner_Edit_Tab_Promotions
 */
?>
<div class="entry-edit">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Related Shopping Cart Price Rules')?></span></legend>
        <br />
        <?php echo $this->getChildHtml('banner_salesrule_grid'); ?>
        <?php echo $this->getChildHtml('salesrule_grid_serializer'); ?>
    </fieldset>
</div>

<div class="entry-edit">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Related Catalog Price Rules')?></span></legend>
        <br />
        <?php echo $this->getChildHtml('banner_catalogrule_grid'); ?>
         <?php echo $this->getChildHtml('catalogrule_grid_serializer'); ?>
    </fieldset>
</div>
