<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="actions">
    <button <?php $this->getUiId(); ?> class="action-login primary" title="<?php echo Mage::helper('Mage_Backend_Helper_Data')->__('Log in')?>" type="submit">
        <span><?php echo Mage::helper('Mage_Backend_Helper_Data')->__('Log in')?></span>
    </button>
</div>
