<?php
/**
 * {license_notice}
 *
 * @category    Saas
 * @package     Saas_PrintedTemplate
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var Saas_PrintedTemplate_Block_GiftCards $this
 */
?>
<table class="gift_cards">
    <thead>
        <tr>
            <th><?php echo __('Code') ?></th>
            <th><?php echo __('Amount') ?></th>
        </tr>
    </thead>
    <tbody>
<?php
foreach ($this->getCards() as $card) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($card['c']) ?></td>
        <td>
<?php
    if ($this->getUseBaseAmount()) {
        echo $this->getOrder()->formatBasePrice($card['ba']);
    } else {
        echo $this->getOrder()->formatPriceTxt($card['a']);
    }
?>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

