<?php
/**
 * {license_notice}
 *
 * @category    Saas
 * @package     Saas_PrintedTemplate
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var Saas_PrintedTemplate_Block_Adminhtml_Template_Preview $this
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo __('Printed Template Preview'); ?></title>
    <?php if ($this->hasWidth()) : ?>
        <style type="text/css">
            body {width: <?php echo $this->getWidth()?>}
            .printed_template_preview_content {margin-bottom: 5mm; margin-top: 5mm;}
        </style>
    <?php endif; ?>

    <script src="<?php echo $this->getViewFileUrl('prototype/prototype.js') ?>"></script>
    <script>
        /**
         * Update pagination variable containers
         */
        function updatePaginationVars() {
            // compile variable container selectors
            var pageNumberSelector = [
                ".printed_template_preview_header .printed_template_page_number",
                ".printed_template_preview_footer .printed_template_page_number"
            ].join(', ');
            var pageTotalSelector = [
                ".printed_template_preview_header .printed_template_page_total",
                ".printed_template_preview_footer .printed_template_page_total"
            ].join(', ');

            /**
             * Update html tag content
             *
             * @param string value
             * @param HtmlElement container
             */
            var updateContainer = function(value, container) {
                container.innerHTML = value;
            }

            // update variables per page
            var pages = $$('.printed_template_preview_page');
            pages.each(function(page, pageIndex) {
                // update page number variable containers
                page.select(pageNumberSelector).each(updateContainer.curry(pageIndex + 1));
                // update page total variable containers
                page.select(pageTotalSelector).each(updateContainer.curry(pages.length));
            });
        }
    </script>
</head>
<body onload="updatePaginationVars()">
    <div class="printed_template_preview_page">
        <div class="printed_template_preview_header"><?php echo $this->getPreviewConverter()->getHeaderHtml() ?></div>
        <div class="printed_template_preview_content"><?php echo $this->getPreviewConverter()->getContentHtml() ?></div>
        <div class="printed_template_preview_footer"><?php echo $this->getPreviewConverter()->getFooterHtml() ?></div>
    </div>
</body>
</html>

