<?php
/**
 * {license_notice}
 *
 * @category    Saas
 * @package     Saas_PrintedTemplate
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var Saas_PrintedTemplate_Block_ShipmentTrack $this
 */
?>
<table class="shipment_track">
    <thead>
        <tr>
            <th><?php echo __('Title') ?></th>
            <th><?php echo __('Number') ?></th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->getTracks() as $track) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($track->getTitle()) ?></td>
        <td><?php echo $this->escapeHtml($track->getNumber()) ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
