<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Promotestore_Relatedproducts_Drawer */
?>
<form id="drawer-form">
    <article class="entry">
        <ul class="promote-actions">
            <?php $trackerLink = $this->getTrackerLink('adminhtml/targetrule/new'); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('Add Product Rule'); ?></a></li>
            <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'catalog')); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('Edit Product Rules'); ?></a></li>
        </ul>
        <div class="promote-content">
            <div class="promote-content-section">
                <p><?php echo __('Related and cross-sell products are items your customers are likely to buy based on what\'s in their shopping carts.'); ?></p>
            </div>
            <div class="promote-content-section">
                <p><?php echo __('Upsell products are items your customer could buy instead of the product being viewed. and may be more expensive, of higher quality, or more popular, or produce a higher profit margin.'); ?></p>
            </div>
        </div>
    </article>
</form>
