<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this Social_Facebook_Block_Head */
?>
<html>
<head  prefix="og: http://ogp.me/ns# <?php echo $this->getAppName()?>: http://ogp.me/ns/apps/<?php echo $this->getAppName()?>#">
<?php if ($this->getMetaTags() && is_array($this->getMetaTags())): ?>
<?php foreach ($this->getMetaTags() as $tag): ?>
    <meta<?php if (isset($tag['name'])): ?> name="<?php echo $this->escapeHtml($tag['name']) ?>"<?php endif; ?><?php if (isset($tag['property'])): ?> property="<?php echo  $this->escapeHtml($tag['property']) ?>"<?php endif; ?><?php if (isset($tag['content'])): ?> content="<?php echo  $this->escapeHtml($tag['content']) ?>"<?php endif; ?> />
<?php endforeach; ?>
<?php endif; ?>
</head>
<body>
    <script type="text/javascript">
    //<![CDATA[
        window.location = '<?php echo $this->getRedirectUrl()?>';
    //]]>
    </script>
</body>
</html>
