<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this \Magento\Adminhtml\Block\Catalog\Product\Composite\Fieldset\Options */ ?>
<?php $option = $this->getOption(); ?>
<div class="field">
    <label class="label"><?php echo $this->escapeHtml($option->getTitle()) ?></label>
</div>
