<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Paypal\Block\Express\Review */
?>
<fieldset id="shipping-method-container">
<?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()):?>
        <?php if ($groups = $this->getShippingRateGroups()):?>
            <?php $currentRate = $this->getCurrentShippingRate(); ?>
            <select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
            <?php if (!$currentRate):?>
                <option value=""><?php echo __('Please select a shipping method.') ?></option>
            <?php endif;?>
            <?php foreach ($groups as $code => $rates):?>
                <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                <?php foreach ($rates as $rate):?>
                    <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                        <?php echo $this->renderShippingRateOption($rate)?>
                    </option>
                <?php endforeach;?>
                </optgroup>
            <?php endforeach;?>
            </select>
        <?php else: ?>
            <p><strong><?php echo __('Sorry, no quotes are available for this order.') ?></strong></p>
        <?php endif;?>
<?php else: ?>
    <p><strong><?php echo $this->renderShippingRateOption($this->getCurrentShippingRate())?></strong></p>
<?php endif; ?>
</fieldset>
<div style="display:none" id="shipping_method_update"><p><?php echo __('Please update order data to get shipping methods and rates') ?></p></div>
