<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Editor_Tools_Code_Message */ ?>
<div class="vde-message">
    <div class="message-inner">
        <div class="message-content">
            <?php echo $this->getMessageText() ?>
        </div>
        <button class="action-close" title="<?php echo $this->__('Close Message'); ?>">
            <span><?php echo $this->__('Close Message'); ?></span>
        </button>
    </div>
</div>
