<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $this */
/** @var \Magento\Catalog\Pricing\Price\ConfiguredPrice $configuredPrice */
$configuredPrice = $this->getPrice();
$schema = ($this->getZone() == 'item_view') ? true : false;
$priceLabel = ($this->getPriceLabel() !== null)
    ? $this->getPriceLabel()
    : '';
?>
<p class="price-as-configured">
    <?php echo $this->renderAmount($configuredPrice->getAmount(), [
        'display_label'     => $priceLabel,
        'price_id'          => $this->getPriceId('product-price-'),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
</p>
