<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Template for displaying product price at product view page, gift registry and wish-list
 *
 * @var $this \Magento\Catalog\Pricing\Render\PriceBox
 */
?>
<?php

/** @var Magento\Catalog\Pricing\Price\MsrpPriceInterface $priceType */
$priceType = $this->getPrice();

/** @var $product \Magento\Catalog\Model\Product */
$product = $this->getSaleableItem();
$productId = $product->getId();
// @todo: msrp works totally wrong, any excuses not accepted. will be refactored ASAP
$msrpPrice = $this->renderAmount($priceType->getCustomAmount($product->getMsrp()),
    [
        'price_id'  => $this->getPriceId() ? $this->getPriceId() : 'old-price-' . $productId,
        'include_container' => false,
        'skip_adjustments' => true
    ]
);
$priceElementIdPrefix = $this->getPriceElementIdPrefix() ? $this->getPriceElementIdPrefix() : 'product-price-';
$addToCartUrl = '';
if ($product->isSaleable()) {
    $addToCartUrl = $this->helper('\Magento\Checkout\Helper\Cart')
        ->getAddUrl($product);
}
?>

<?php if ($product->getMsrp()): ?>
    <span class="old-price"><?php echo $msrpPrice ?></span>
<?php endif; ?>

<?php if ($priceType->isShowPriceOnGesture()): ?>
    <?php
        $priceElementId = $priceElementIdPrefix . $productId . $this->getIdSuffix();
        $popupId = 'msrp-popup-' . $productId . $this->getRandomString(20);
        $data = ['addToCart' => [
            'cartForm' => '#product_addtocart_form_from_popup',
            'popupId' => '#' . $popupId,
            'productName' => $product->getName(),
            'realPrice' => $this->getRealPriceHtml(),
            'msrpPrice' => $msrpPrice,
            'priceElementId' => $priceElementId,
            'closeButtonId' => '#map-popup-close',
            'popupCartButtonId' => '#map-popup-button',
            'addToCartUrl' => $addToCartUrl,
        ]];
    ?>
    <span id="<?php echo $this->getPriceId() ? $this->getPriceId() : $priceElementId ?>" style="display:none"></span>
    <a href="#"
       id="<?php echo($popupId);?>"
       data-mage-init="<?=$this->escapeHtml($this->helper('Magento\Core\Helper\Data')->jsonEncode($data))?>"><?php echo __('Click for price'); ?>
    </a>
<?php else: ?>
    <span class="msrp message">
     <?php echo $priceType->getMsrpPriceMessage() ?>
    </span>
<?php endif; ?>

<?php if ($this->getZone() == \Magento\Framework\Pricing\Render::ZONE_ITEM_VIEW): ?>
    <?php $helpLinkId = 'msrp-help-' . $productId . $this->getRandomString(20); ?>
    <a href="#"
       id="<?php echo $helpLinkId;?>"
       class="action show map"
       data-mage-init='{"addToCart":{"helpLinkId": "#<?php echo $helpLinkId;?>",
                                     "productName": "<?php echo $product->getName() ?>",
                                     "closeButtonId": "#map-popup-close"}}'><span><?php echo __("What's this?"); ?></span>
    </a>
<?php endif; ?>
