<?php
/**
 * {license_notice}
 *
 * @category    Magento
 * @package     Magento_Pbridge
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<ul class="form-list pbridge no-display" id="payment_form_<?php echo $this->getMethodCode() ?>" data-payment="<?php echo $this->getMethodCode() ?>" data-mage-init="{pbridge: {method: '<?php echo $this->getMethodCode() ?>', reviewUrl: '<?php echo $this->getUrl('magento_pbridge/pbridge/review', array('_current' => true, '_secure' => true)); ?>', frameUrl: '<?php echo $this->getUrl('magento_pbridge/pbridge/iframe', array('_current' => true, '_secure' => true)); ?>'}}">
    <li>
        <?php if ($this->getReloadAllowed()): ?>
        <span class="pbridge-reload"><a href="#">Reload Form</a></span>
        <?php endif; ?>
        <div id="payment_form_<?php echo $this->getMethodCode() ?>_container" data-container="iframe">
            <?php echo $this->getChildHtml('pbridge_iframe'); ?>
        </div>
    </li>
</ul>
