<?php
/**
 * {license_notice}
 *
 * @category    Magento
 * @package     Magento_Pbridge
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
Event.observe(this.document, 'payment-method:switched', function(event){
  if (event.stopped == null) {
      toggleContinueButton(event.target);
      Event.stop(event);
  }
});
if (typeof eventsObserved == 'undefined' && $('use_customer_balance')) {
    Event.observe($('use_customer_balance'), 'click', function(event){
        toggleContinueButton(event.target);
    });
    eventsObserved = true;
}
