<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="box-collateral box-tags">
    <div class="box-title">
        <h2><?php echo __('Product Tags'); ?></h2>
    </div>
    <?php echo $this->getChildHtml('list_before')?>
    <div class="box-content">
        <?php if($this->getCount()): ?>
        <h3><?php echo __('Other people marked this product with these tags:') ?></h3>
        <ul id="<?php echo $this->getUniqueHtmlId('tags-list_'); ?>" class="tags-list">
            <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
        </ul>
        <script type="text/javascript">
            (function($) {$("#<?php echo $this->getUniqueHtmlId('tags-list_'); ?>").find('li').decorate('generic', ['first','last'])})(jQuery)
        </script>
        <?php endif; ?>
        <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
            <div class="form-add-tags">
                <label for="productTagName"><?php echo __('Add Your Tags:') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text" data-validate="{required:true}" name="productTagName" id="productTagName" />
                </div>
                <button type="submit" class="button">
                    <span>
                        <span><?php echo __('Add Tags') ?></span>
                    </span>
                </button>
                <p><?php echo __("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                    $('#addTagForm').validation();
                }
            )
        })(jQuery);
        //]]>
        </script>
    </div>
</div>
