<?php
/**
 * @var \Magento\Ui\ListingContainer\Massaction\View $this
 */
?>
<div data-m2-init='{ "Magento_Ui/js/listing/massaction": "" }'>
    <script type="mage/config">
        <?php echo $this->getConfigurationJson(); ?>
    </script>
</div>
<div data-bind="scope: '<?php echo $this->getParentName(); ?>:<?php echo $this->getName(); ?>'">
    <!-- ko template: 'Magento_Ui.templates.pageactions' --><!-- /ko -->
</div>