<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var \Magento\Ui\ListingContainer\Massaction\View $this
 */
?>
<script data-m2-init='{ "Magento_Ui/js/listing/massaction": "" }' type="application/json">
    <?php echo $this->getConfigurationBuilder()->toJson($this->getConfiguration()); ?>
</script>
<div data-bind="scope: '<?php echo $this->getParentName(); ?>:<?php echo $this->getName(); ?>'">
    <!-- ko template: 'Magento_Ui.templates.pageactions' --><!-- /ko -->
</div>