<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<div class="page-title">
    <h1><?php echo __('Create Gift Registry'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getAddActionUrl(); ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo __('General Information') ?></h2>
        <ul class="form-list">
            <li>
                <label for="type_id"><?php echo __('Gift Registry Type') ?></label>
                <div class="input-box">
                    <select data-validate="{required:true}" name="type_id" id="type_id">
                            <option value=""><?php echo __('Please select a gift registry type.') ?></option>
                        <?php foreach ($this->getTypeList() as $type):?>
                            <option value="<?php echo $type['value']?>"><?php echo $type['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set form-buttons">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
        <button type="submit" id="submit.next" title="<?php echo __('Next') ?>" class="button"><span><span><?php echo __('Next') ?></span></span></button>
    </div>
    <p class="required"><?php echo __('* Required Fields') ?></p>
</form>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                $('#form-validate').validation();
            });
    })(jQuery);
</script>
