<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            paymentAuthentication: [
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/payment-authentication.js') ?>'
            ],
            collapsible: [
				'<?php echo $this->getViewFileUrl('mage/collapsible.js') ?>'
			],
            dropdownDialog: [
                '<?php echo $this->getViewFileUrl('mage/dropdown.js') ?>'
            ],
            accordion: [
                '<?php echo $this->getViewFileUrl('mage/collapsible.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/tabs.js') ?>',
				'<?php echo $this->getViewFileUrl('mage/accordion.js') ?>'
			],
            addToCart: [
                '<?php echo $this->getViewFileUrl('Magento_Catalog::js/msrp.js') ?>'
            ],
            checkoutBalance: [
                '<?php echo $this->getViewFileUrl('Magento_Customer::js/checkout-balance.js')?>'
            ],
            shoppingCart: [
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/shopping-cart.js') ?>'
            ],
            regionUpdater: [
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/region-updater.js') ?>'
            ],
            creditCardType: [
                '<?php echo $this->getViewFileUrl('Magento_Payment::cc-type.js') ?>'
            ],
            loader: [
                '<?php echo $this->getViewFileUrl('jquery/handlebars/handlebars-v1.3.0.js')?>',
                '<?php echo $this->getViewFileUrl('mage/loader.js') ?>'
            ],
            tooltip: [
                '<?php echo $this->getViewFileUrl('mage/tooltip.js') ?>'
            ],
            opcOrderReview: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>',
                '<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>',
                '<?php echo $this->getViewFileUrl('mage/validation.js')?>',
                '<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>',
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/opc-checkout-method.js') ?>',
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/opc-billing-info.js') ?>',
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/opc-shipping-info.js') ?>',
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/opc-shipping-method.js') ?>',
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/opc-payment-info.js') ?>',
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/opc-order-review.js') ?>'

            ],
            sidebar: [
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/sidebar.js') ?>'
            ],
            payment: [
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/payment.js') ?>'
            ]
        });
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>
