<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * Template for displaying product price at catalog and sidebars
 *
 * @var $this Mage_Catalog_Block_Product_Price
 */
?>
<?php
    /** @var $_product Mage_Catalog_Model_Product */
    $_product = $this->getProduct();
    $_msrpPrice = "";
?>
    <div class="price-box map-info">
    <?php $_price = $this->helper('Mage_Tax_Helper_Data')->getPrice($_product, $_product->getMsrp()) ?>
        <?php if ($_product->getMsrp()): ?>
            <?php $_msrpPrice = $this->helper('Mage_Core_Helper_Data')->currency($_product->getMsrp(),true,true) ?>
            <span class="old-price" id="product-price-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>"><?php echo $_msrpPrice ?></span>
        <?php endif; ?>
        <?php $helpLinkId = 'msrp-click-' . $_product->getId() . $this->helper('Mage_Core_Helper_Data')->getRandomString(20); ?>
        <a href="#" id="<?php echo($helpLinkId);?>"><?php echo $this->__('Click for price') ?></a>
        <script type="text/javascript">
            //<![CDATA[
            (function ($) {
            <?php if ($this->helper('Mage_Catalog_Helper_Data')->isShowPriceOnGesture($_product)): ?>
                $.mage.event.observe('mage.price.helplink', function (event, clickForPrice) {
                    var helpLink = {
                        popupId: "#<?php echo($helpLinkId);?>",
                        productName: '<?php echo $_product->getName() ?>',
                        realPrice: '<?php echo $this->getRealPriceJs($_product) ?>',
                        msrpPrice: '<?php echo $_msrpPrice ?>',
                        priceElementId: '<?php echo $priceElementId ?>'
                    };
                    clickForPrice.helpLink.push(helpLink);
                });

                $.mage.event.observe('map.popup.button', function (event, popupCartData) {
                    var initData = {
                        cartButtonId: "#map-popup-button",
                        addToCartUrl: "<?php echo $this->getAddToCartUrl($_product) ?>"
                    };
                    popupCartData.cartData.push(initData);
                });
                $.mage.event.observe('map.popup.close', function (event, initData) {
                    initData.closeButtonId = '#map-popup-close';
                });
                <?php else: ?>

                $.mage.event.observe('mage.price.helplink', function (event, clickForPrice) {
                    var helpLink = {
                        popupId: "#<?php echo($helpLinkId);?>",
                        submitUrl: "<?php echo $_product->getProductUrl() ?>"
                    };
                    clickForPrice.helpLink.push(helpLink);
                });
                <?php endif; ?>

                $.mage.load.js("<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>");
                $.mage.load.js("<?php echo $this->getViewFileUrl('jquery/jquery.hook.js')?>");
                $.mage.load.jsSync("<?php echo $this->getViewFileUrl('Mage_Catalog::js/msrp.js') ?>");

            })(jQuery);
            //]]>
        </script>
    </div>
