<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php 
/**
 * Mustishipping state
 * 
 * @see Magento_Checkout_Block_Multishipping_State
 */
?>
<ul class="checkout-progress" id="checkout-progress-state">
<?php foreach ($this->getSteps() as $_step): ?>
    <li title="<?php echo $_step->getLabel() ?>"<?php if($_step->getIsActive()): ?> class="active"<?php endif; ?>><span><?php echo $_step->getLabel() ?></span></li>
<?php endforeach; ?>
</ul>
<script type="text/javascript">(function($) {$('#checkout-progress-state li').decorate('generic', ['first','last'])})(jQuery)</script>
