<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<form id="search_mini_form" action="<?=$this->getUrl('catalogsearch/result')?>" method="get" onsubmit="if (getElementById('search').value == '<?=__('Search entire store here...')?>' || getElementById('search').value == '') return false;">
    <fieldset class="mini-search">
	<legend><?=__('Search Site')?></legend>
	<input id="search" type="text" class="input-text" name="q" value="<?if(!empty($query)):?><?=$query?><?else:?><?=__('Search entire store here...')?><?endif?>" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;"/> <input type="image" src="<?=$this->getSkinUrl('images/btn_mini_search.gif')?>" alt="Search"/>
    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script type="text/javascript">
        new Ajax.Autocompleter(
            'search', 
            'search_autocomplete', 
            '<?=$this->getUrl('catalogsearch/ajax/suggest')?>', 
            {
                paramName:"query", 
                minChars:2,
                //indicator:"search_indicator", 
                updateElement:getSelectionId
            }
        );
        
        function getSelectionId(li) {
        	if (li.title) {
            	$('search').value = li.title;
        	}
            $('search_mini_form').submit();
        }
    </script>
	</fieldset>
</form>


