<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->getRatingSummary()->getCount()): ?>
    <div class="rating-box">
        <div class="rating" style="width:<?php echo ceil($this->getRatingSummary()->getSum() / ($this->getRatingSummary()->getCount())) ?>%;"></div>
    </div>
<?php else: ?>
    <?php echo __("Rating isn't Available") ?>
<?php endif; ?>
