<?=$this->getFormInitScripts()?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td style="<?=$this->getHeaderWidth()?>"><?=$this->getHeaderHtml()?></td>
            <td class="a-right"><?=$this->getButtonsHtml()?></td>
        </tr>
    </table>
</div>
<?=$this->getFormHtml()?>
<script type="text/javascript" language="javascript">
    var editForm = new varienForm('edit_form', '<?=$this->getValidationUrl()?>');
</script>
<?=$this->getFormScripts()?>