<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<ol id="checkoutSteps" class="one-page-checkout">
<?$_curStep = 1;?>
<?if (!$this->helper('customer')->isLoggedIn()):?>

<!-- CHECKOUT METHOD / LOGIN TAB -->

    <li id="opc-login" class="section allow">
        <div class="head">
            <h3><span class="step-count"><?=$_curStep++?></span> &nbsp;<?=$this->__('Checkout method')?></h3>
        </div>
        <div id="checkout-step-login" class="box a-item" style="display:none;">

            <div class="col2-set">
                <div class="col-1">
                <h4><?=$this->__('Checkout as a Guest or Register')?></h4>

            <p><?=$this->__('You may check out as a guest or register with us for future convenience:')?></p>
            <ul class="form-list">
                <li><input type="radio" name="checkout_method" id="login:guest" value="guest"<?if($this->getCheckoutMethod()=='guest'):?> checked<?endif?>/> <label for="login:guest"><?=$this->__('Checkout as Guest')?></label></li>
                <li><input type="radio" name="checkout_method" id="login:register" value="register"<?if($this->getCheckoutMethod()=='register'):?> checked<?endif?>/> <label for="login:register"><?=$this->__('Register')?></label></li>
            </ul>

            <strong><?=$this->__('Register and save time!')?></strong><br/>
            <ul class="disc">
                <li><?=$this->__('Fast and easy check out')?></li>
                <li><?=$this->__('Easy access to your order history and status')?></li>
            </ul>
            <div class="form-buttons">
                <button class="form-button" onclick="checkout.setMethod();"><span><?=$this->__('Continue')?></span></button>

            </div>
                </div>
            <div class="col-2">
                <h4>Login</h4>
            <?=$this->getMessagesBlock()->getGroupedHtml()?>

                    <form id="login-form" action="<?=$this->getLoginPostAction()?>" method="post">
                            <p><strong><?=$this->__('Already registered?')?></strong><br/>
                            <?=$this->__('Log in below to take advantage of Express Checkout:')?></p>
                            <ul class="form-list">
                                    <li><div class="input-box"><label for="email"><?=$this->__('Email Address')?> <span class="required">*</span></label><br/>
                                        <input type="text" class="input-text required-entry validate-email" id="email" name="login[username]"/></div></li>
                                    <li><div class="input-box"><label for="password"><?=$this->__('Password')?> <span class="required">*</span></label><br/>
                                        <input type="password" class="input-text required-entry" id="password" name="login[password]" /></div></li>
                            </ul>
                            <div class="form-buttons">
                                <p class="required"><?=$this->__('* Required Fields')?></p>
                                    <a href="<?=$this->getUrl('customer/account/forgotpassword')?>" class="left"><?=$this->__('Forgot your password?')?></a><button type="submit" class="form-button"><span><?=$this->__('Login')?></span></button>
                            </div>
                    </form>
                </div>
            </div>
            
        </div>
    </li>
<?endif //if (!$this->helper('customer')->isLoggedIn())?>

<!-- BILLING INFORMATION TAB -->

<?$_address = $this->getBillingAddress()?>
    <li id="opc-billing" class="section <?if ($this->helper('customer')->isLoggedIn()):?>allow<?endif?>">
        <div class="head">
            <h3><span class="step-count"><?=$_curStep++?></span> &nbsp;<?=$this->__('Billing Information')?></h3>
        </div>
        <div id="checkout-step-billing" class="box a-item" style="display:none;">
        
            <form id="co-billing-form">
            <?if ($this->helper('customer')->customerHasAddresses()):?>
                <p><?=$this->__('Select a billing address from your address book or enter a new address.')?></p>
                <ul><li><p><?=$this->getAddressesHtmlSelect($_address, 'billing')?></p></li></ul>

            <?endif?>
                <fieldset class="group-select" id="billing-new-address-form" <?if ($this->helper('customer')->customerHasAddresses()):?>style="display:none"<?endif?>>
                    <input type="hidden" name="billing[address_id]" value="<?=$_address->getId()?>" id="billing:address_id"/>
                    <ul>
                        <li><div class="input-box">
                            <label for="billing:firstname"><?=$this->__('First Name')?> <span class="required">*</span></label><br/>
                            <input type="text" id="billing:firstname" name="billing[firstname]" value="<?=$_address->getFirstname()?>" title="<?=$this->__('First Name')?>" class="required-entry input-text"/></div>
                            <div class="input-box">
                            <label for="billing:lastname"><?=$this->__('Last Name')?> <span class="required">*</span></label><br/>
                            <input type="text" id="billing:lastname" name="billing[lastname]" value="<?=$_address->getLastname()?>" title="<?=$this->__('Last Name')?>" class="required-entry input-text"/></div></li>
                        <li><div class="input-box">
                            <label for="billing:company"><?=$this->__('Company')?></label><br/>
                            <input type="text" id="billing:company" name="billing[company]" value="<?=$_address->getCompany()?>" title="<?=$this->__('Company')?>" class="input-text"/></div>
                <?if(!$this->helper('customer')->isLoggedIn()):?>
                            <div class="input-box">
                            <label for="billing:email"><?=$this->__('Email Address')?> <span class="required">*</span></label><br/>
                            <input type="text" name="billing[email]" id="billing:email" value="<?=$_address->getEmail()?>" title="<?=$this->__('Email Address')?>" class="validate-email required-entry input-text"/></div>
                <?endif?>
                            </li>
                        <li><label for="billing:address"><?=$this->__('Address')?> <span class="required">*</span></label><br/>
                            <input type="text" title="<?=$this->__('Street Address')?>" name="billing[street][1]" id="billing:street1" value="<?=$_address->getStreet(1)?>" class="required-entry input-text"/></li>
                        <li><input type="text" title="<?=$this->__('Street Address 2')?>" name="billing[street][2]" id="billing:street2" value="<?=$_address->getStreet(2)?>" class="input-text"/></li>
                        <li><div class="input-box">
                            <label for="billing:city"><?=$this->__('City')?> <span class="required">*</span></label><br/>
                            <input type="text" title="<?=$this->__('City')?>" name="billing[city]" value="<?=$_address->getCity()?>" class="required-entry input-text" id="billing:city"/></div>
                            <div class="input-box">
                            <label for="billing:region"><?=$this->__('State/Province')?> <span class="required">*</span></label><br/>
                            <select id="billing:region_id" name="billing[region_id]" title="<?=$this->__('State/Province')?>" class="validate-select" style="display:none" defaultValue="<?=$_address->getRegionId()?>">
                                <option value=""><?=$this->__('Please select region, state or province')?></option>
                            </select>
                            <input type="text" id="billing:region" name="billing[region]" value="<?=$_address->getRegion()?>"  title="<?=$this->__('State/Province')?>" class="required-entry  input-text" style="display:none"/>
                            </div></li>
                        <li><div class="input-box">
                            <label for="billing:postcode"><?=$this->__('Zip/Postal Code')?> <span class="required">*</span></label><br/>
                            <input type="text" title="<?=$this->__('Zip/Postal Code')?>" name="billing[postcode]" id="billing:postcode" value="<?=$_address->getPostcode()?>" class="validate-zip-international required-entry input-text"/></div>
                            <div class="input-box">
                                <label for="billing:country_id"><?=$this->__('Country')?> <span class="required">*</span></label><br/>
                                <?=$this->getCountryHtmlSelect($_address, 'billing')?></div></li>
                        <li><div class="input-box">
                            <label for="billing:telephone"><?=$this->__('Telephone')?> <span class="required">*</span></label><br/>
                            <input type="text" name="billing[telephone]" value="<?=$_address->getTelephone()?>" title="<?=$this->__('Telephone')?>" class="required-entry input-text" id="billing:telephone"/></div>
                            <div class="input-box">
                            <label for="billing:fax"><?=$this->__('Fax')?></label><br/>
                            <input type="text" name="billing[fax]" value="<?=$_address->getFax()?>" title="<?=$this->__('Fax')?>" class="input-text" id="billing:fax"/></div></li>
                        <?if(!$this->helper('customer')->isLoggedIn()):?>
                            <li id="register-customer-password">
                            <div class="input-box">
                            <label for="password"><?=$this->__('Password')?> <span class="required">*</span></label><br/>
                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?=$this->__('Password')?>" class="required-entry validate-password input-text"/></div>
                            <div class="input-box">
                            <label for="confirmation"><?=$this->__('Confirm Password')?> <span class="required">*</span></label><br/>
                            <input type="password" name="billing[confirm_password]" title="<?=$this->__('Confirm Password')?>" id="billing:confirm_password" class="required-entry validate-password input-text"/></div></li>
                        <?endif?>
                    </ul>
                </fieldset>

                <p><input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="1" <?if($this->getUseForShipping()):?>checked<?endif?> onclick="billing.setUseForShipping(this.checked)"/> &nbsp;<label for="billing:use_for_shipping"><?=$this->__('Ship to this address')?></label></p>
            </form>
            <div class="form-buttons">
                <p class="required"><?=$this->__('* Required Fields')?></p>
                <span id="billing-buttons-container" >
                    <button class="form-button right" onclick="billing.save()"><span><?=$this->__('Continue')?></span></button>
                    <span id="billing-please-wait" style="display:none;" class="opc-please-wait">
                        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; <?=$this->__('Loading next step...')?> &nbsp; 
                    </span>
                </span>
            </div>
            
        </div>
    </li>
    
<!-- SHIPPING INFORMATION TAB -->

<?$_address = $this->getShippingAddress()?>
    <li id="opc-shipping" class="section">
        <div class="head">
            <h3><span class="step-count"><?=$_curStep++?></span> &nbsp;<?=$this->__('Shipping Information')?></h3>
        </div>
        <div id="checkout-step-shipping>" class="box a-item" style="display:none;">
        
            <form id="co-shipping-form">
            <?if ($this->helper('customer')->customerHasAddresses()):?>
               <p><?=$this->__('Select a shipping address from your address book or enter a new address.')?></p>
               <p><?=$this->getAddressesHtmlSelect($_address, 'shipping')?></p>
            <?endif?>

            <fieldset class="group-select" id="shipping-new-address-form" <?if ($this->helper('customer')->customerHasAddresses()):?>style="display:none"<?endif?>>
                <input type="hidden" name="shipping[address_id]" value="<?=$_address->getId()?>" id="shipping:address_id"/>
                <ul>
                    <li><div class="input-box">
                        <label for="shipping:firstname"><?=$this->__('First Name')?> <span class="required">*</span></label><br/>
                        <input type="text" id="shipping:firstname" name="shipping[firstname]" value="<?=$_address->getFirstname()?>" title="<?=$this->__('First Name')?>" class="required-entry input-text" onchange="shipping.setSameAsBilling(false);"/></div>
                        <div class="input-box">
                        <label for="shipping:lastname"><?=$this->__('Last Name')?> <span class="required">*</span></label><br/>
                        <input type="text" id="shipping:lastname" name="shipping[lastname]" value="<?=$_address->getLastname()?>" title="<?=$this->__('Last Name')?>" class="required-entry input-text" onchange="shipping.setSameAsBilling(false);"/></div></li>
                    <li><div class="input-box">
                        <label for="shipping:company"><?=$this->__('Company')?></label><br/>
                        <input type="text" id="shipping:company" name="shipping[company]" value="<?=$_address->getCompany()?>" title="<?=$this->__('Company')?>" class="input-text" onchange="shipping.setSameAsBilling(false);"/></div>
            <?if(false):?>
                        <div class="input-box">
                        <label for="shipping:email"><?=$this->__('Email Address')?> <span class="required">*</span></label><br/>
                        <input type="text" name="shipping[email]" id="shipping:email" value="<?=$_address->getEmail()?>" title="<?=$this->__('Email Address')?>" class="validate-email required-entry input-text"/></div>
            <?endif?>
                        </li>
                    <li><label for="shipping:address"><?=$this->__('Address')?> <span class="required">*</span></label><br/>
                        <input type="text" title="<?=$this->__('Street Address')?>" name="shipping[street][1]" id="shipping:street1" value="<?=$_address->getStreet(1)?>" class="required-entry input-text" onchange="shipping.setSameAsBilling(false);"/></li>
                    <li><input type="text" title="<?=$this->__('Street Address 2')?>" name="shipping[street][2]" id="shipping:street2" value="<?=$_address->getStreet(2)?>" class="input-text" onchange="shipping.setSameAsBilling(false);"/></li>
                    <li><div class="input-box">
                        <label for="shipping:city"><?=$this->__('City')?> <span class="required">*</span></label><br/>
                        <input type="text" title="<?=$this->__('City')?>" name="shipping[city]" value="<?=$_address->getCity()?>" class="required-entry input-text" id="shipping:city" onchange="shipping.setSameAsBilling(false);"/></div>
                        <div class="input-box">
                        <label for="shipping:region"><?=$this->__('State/Province')?> <span class="required">*</span></label><br/>
                        <select id="shipping:region_id" name="shipping[region_id]" title="<?=$this->__('State/Province')?>" class="validate-select" style="display:none" defaultValue="<?=$_address->getRegionId()?>">
                            <option value=""><?=$this->__('Please select region, state or province')?></option>
                        </select>
                        <input type="text" id="shipping:region" name="shipping[region]" value="<?=$_address->getRegion()?>"  title="<?=$this->__('State/Province')?>" class="required-entry  input-text" style="display:none"/></div></li>
                    <li><div class="input-box">
                        <label for="shipping:postcode"><?=$this->__('Zip/Postal Code')?> <span class="required">*</span></label><br/>
                        <input type="text" title="<?=$this->__('Zip/Postal Code')?>" name="shipping[postcode]" id="shipping:postcode" value="<?=$_address->getPostcode()?>" class="validate-zip-international required-entry input-text" onchange="shipping.setSameAsBilling(false);"/></div>
                        <div class="input-box">
                        <label for="shipping:country_id"><?=$this->__('Country')?> <span class="required">*</span></label><br/>
                        <?=$this->getCountryHtmlSelect($_address, 'shipping')?>
                        </div></li>
                    <li><div class="input-box">
                        <label for="shipping:telephone"><?=$this->__('Telephone')?> <span class="required">*</span></label><br/>
                        <input type="text" name="shipping[telephone]" value="<?=$_address->getTelephone()?>" title="<?=$this->__('Telephone')?>" class="required-entry input-text" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);"/></div>
                        <div class="input-box">
                        <label for="shipping:fax"><?=$this->__('Fax')?></label><br/>
                        <input type="text" name="shipping[fax]" value="<?=$_address->getFax()?>" title="<?=$this->__('Fax')?>" class="input-text" id="shipping:fax" onchange="shipping.setSameAsBilling(false);"/></div></li>
                </ul>
            </fieldset>
                <p><input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1" <?if($_address->getSameAsBilling()):?>checked<?endif?> onclick="shipping.setSameAsBilling(this.checked)"/> &nbsp;<label for="shipping:same_as_billing"><?=$this->__('Use Billing Address')?></label></p>
            </form>
            <div class="form-buttons">
                <p class="required"><?=$this->__('* Required Fields')?></p>
                <span id="shipping-buttons-container">
                    <a href="#" class="back left" onclick="checkout.back()"><?=$this->__('Back')?></a>
                    <button class="form-button right" onclick="shipping.save()"><span><?=$this->__('Continue')?></span></button>
                    <span id="shipping-please-wait" style="display:none;" class="opc-please-wait">
                        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; <?=$this->__('Loading next step...')?> &nbsp; 
                    </span>
                </span>
            </div>

        </div>
    </li>
    
<!-- SHIPPING METHOD TAB -->

    <li id="opc-shipping_method" class="section">
        <div class="head">
            <h3><span class="step-count"><?=$_curStep++?></span> &nbsp;<?=$this->__('Shipping Method')?></h3>
        </div>
        <div id="checkout-step-shipping_method" class="box a-item" style="display:none;">
        
            <div id="checkout-shipping-method-load" class="default-box" style="padding:10px;">
                <?=$this->getChildHtml('shipping')?>
            </div>
                
            <div class="form-buttons">
                <span id="shipping-method-buttons-container">
                    <a href="#" onclick="checkout.back()" class="back left"><?=$this->__('Back')?></a>
                    <button class="form-button right" onclick="shippingMethod.save()"><span><?=$this->__('Continue')?></span></button>
                    <span id="shipping-method-please-wait" style="display:none;" class="opc-please-wait">
                        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; <?=$this->__('Loading next step...')?> &nbsp; 
                    </span>
                </span>
            </div>

        </div>
    </li>
    
<!-- PAYMENT INFORMATION TAB -->

    <li id="opc-payment" class="section">
        <div class="head">
            <h3><span class="step-count"><?=$_curStep++?></span> &nbsp;<?=$this->__('Payment Information')?></h3>
        </div>
        <div id="checkout-step-payment" class="box a-item" style="display:none;">
        
            <form id="co-payment-form">
                <dl class="payment-methods">
                    <?=$this->getChildHtml('payment')?>
                </dl>
                <div class="tool-tip" id="payment-tool-tip" style="left:0;position:absolute;display:none">
                    <a href="#" id="payment-tool-tip-close" class="btn-close"><img src="<?=$this->getSkinUrl('images/btn_window_close.gif')?>" alt="<?=$this->__('Close')?>"/></a>
                    <div class="block-content">
                    <img src="<?=$this->getSkinUrl('images/cvv.gif')?>" alt="<?=$this->__('Card Verification Number Visual Reference')?>"/>
                    </div>
                </div>    
            </form>
            <div class="form-buttons">
                <p class="required"><?=$this->__('* Required Fields')?></p>
                <span id="payment-buttons-container">
                    <a href="#" class="back left" onclick="checkout.back()"><span><?=$this->__('Back')?></span></a>
                    <button class="form-button right" onclick="payment.save()"><span><?=$this->__('Continue')?></span></button>
                    <span id="payment-please-wait" style="display:none;" class="opc-please-wait">
                        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; <?=$this->__('Loading next step...')?> &nbsp; 
                    </span>
                </span>
            </div>

        </div>
    </li>
    
<!-- ORDER REVIEW TAB -->
    <li id="opc-review" class="section">
        <div class="head">
            <h3><span class="step-count"><?=$_curStep++?></span> &nbsp;<?=$this->__('Order Review')?></h3>
        </div>
        <div id="checkout-step-review" class="box a-item" style="display:none;">
        
            <div id="checkout-review-load" class="default-box">
                <?=$this->getChildHtml('review')?>
            </div>

            <div class="content form-buttons">
                <p class="left"><?=$this->__('Forgot an Item?')?> <a href="<?=$this->getUrl('checkout/cart', array('_secure'=>false))?>"><?=$this->__('Edit Your Cart')?></a></p>
                <p>
                    <span id="review-please-wait" style="display:none;" class="opc-please-wait">
                        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; <?=$this->__('Submitting order information...')?> &nbsp;
                    </span>
                    <span id="review-buttons-container">
                        <input type="image" src="<?=$this->getSkinUrl('images/btn_place_order.gif')?>" onclick="review.save();" value="<?=$this->__('Place Order')?>"/>
                    </span>
                </p>
            </div>

        </div>
    </li>
    
</ol>

<script type="text/javascript" src="<?=$this->getJsUrl('varien/accordion.js')?>"></script>
<script type="text/javascript" src="<?=$this->getSkinUrl('js/opcheckout.js')?>"></script>
<script type="text/javascript">countryRegions = <?=$this->helper('directory')->getRegionJson()?></script>

<script type="text/javascript">
// login
    var loginForm = new VarienForm('login-form', true);

// Billing
    var billing = new Billing('co-billing-form', 
        '<?=$this->getUrl('checkout/onepage/getAddress')?>address/', 
        '<?=$this->getUrl('checkout/onepage/saveBilling')?>');
    var billingForm = new VarienForm('co-billing-form');
    
    //billingForm.setElementsRelation('billing:country_id', 'billing:region', 
    //    '<?=$this->getUrl('directory/json/childRegion')?>', 
    //    '<?=$this->__('Select State/Province...')?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
    
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions);

// Shipping
    var shipping = new Shipping('co-shipping-form', 
        '<?=$this->getUrl('checkout/onepage/getAddress')?>address/', 
        '<?=$this->getUrl('checkout/onepage/saveShipping')?>',
        '<?=$this->getUrl('checkout/onepage/shippingMethod')?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', 
    //    '<?=$this->getUrl('directory/json/childRegion')?>', 
    //    '<?=$this->__('Select State/Province...')?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions);
    
// Shipping Method
    var shippingMethod = new ShippingMethod('co-shipping-method-form', 
        "<?=$this->getUrl('checkout/onepage/saveShippingMethod')?>");

// Payment
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-400)+'px',
                left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });
    
    var payment = new Payment('co-payment-form', 
        '<?=$this->getUrl('checkout/onepage/savePayment')?>');
    payment.currentMethod = "<?=$this->getPayment()->getMethod()?>";
    
// Review
    var review = new Review(
        '<?=$this->getUrl('checkout/onepage/saveOrder')?>', 
        '<?=$this->getUrl('checkout/onepage/success', array('_secure'=>false))?>');

// Checkout
    var accordion = new Accordion('checkoutSteps', '.head', true);
    accordion.openSection('opc-<?=$this->helper('customer')->isLoggedIn() ? 'billing' : 'login'?>');

    var checkout = new Checkout(accordion,
        '<?=$this->getUrl('checkout/onepage/progress')?>',
        '<?=$this->getUrl('checkout/onepage/review')?>',
        '<?=$this->getUrl('checkout/onepage/saveMethod')?>');
</script>
