<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

?>
<?php $_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_readonly    = $this->getElement()->getReadonly() ?>
<?php $_multiWebsite= $this->isMultiWebsites(); ?>
<div id="attribute-<?php echo $_htmlId?>-container" data-attribute-code="<?php echo $_htmlId?>" class="field"
     data-apply-to="<?php echo $this->escapeHtml(
         $this->helper('Magento\Core\Helper\Data')->jsonEncode(
             $this->getElement()->hasEntityAttribute() ? $this->getElement()->getEntityAttribute()->getApplyTo() : array()
         )
     )?>">
    <label class="label"><span><?php echo $this->getElement()->getLabel() ?></span></label>
    <div class="control">
        <table class="data-table" id="<?php echo $_htmlId; ?>_table">
            <thead>
                <tr class="headings">
                    <th class="col-website <?php if (!$_multiWebsite): ?>no-display<?php endif; ?>">
                        <?php echo __('Website') ?>
                    </th>
                    <th class="col-amount required-entry">
                        <?php echo __('Amount') ?>
                    </th>
                    <th class="col-actions">
                        <?php echo __('Action') ?>
                    </th>
                </tr>
                <tr id="<?php echo $_htmlId ?>_add_template" class="template no-display">
                    <td class="col-website <?php if (!$_multiWebsite): ?>no-display<?php endif; ?>">
                        <select
                            disabled="no-template"
                            class="<?php echo $_htmlClass ?> required-entry"
                            name="<?php echo $_htmlName ?>[__index__][website_id]"
                            id="#{prefix}_giftcard_amounts_row___index___website">
                            <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
                            <option value="<?php echo $_websiteId ?>"><?php echo $_info['name'] ?><?php if (!empty($_info['currency'])): ?> [<?php echo $_info['currency'] ?>]<?php endif; ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                    <td class="col-amount">
                        <input
                            disabled="no-template"
                            class="<?php echo $_htmlClass ?> required-entry validate-greater-than-zero"
                            type="text"
                            name="<?php echo $_htmlName ?>[__index__][price]"
                            value="'#{price}'" />
                    </td>
                    <td class="col-actions">
                        <input
                            type="hidden"
                            name="<?php echo $_htmlName ?>[__index__][delete]"
                            class="delete"
                            disabled="no-template"
                            value=""
                            id="#{prefix}_giftcard_amounts_row___index___delete" />

                        <button
                            title="<?php echo __('Delete Amount'); ?>"
                            class="action-delete delete-product-option"
                            onclick="giftcardAmountsControl.deleteItem('<?php echo $_htmlId ?>', event);return false">

                            <span><?php echo __('Delete'); ?></span>
                        </button>
                    </td>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="col-actions col-actions-add" colspan="<?php echo $_multiWebsite ? 3 : 2 ?>">
                        <?php echo $this->getAddButtonHtml() ?>
                    </td>
                </tr>
            </tfoot>
            <tbody id="<?php echo $_htmlId ?>_container">
            </tbody>
        </table>
        <input type="hidden" id="giftcard_amounts_total" name="giftcard_amounts_total" value="" <?php if (!$_readonly): ?>class="required-entry"<?php endif; ?>>
    </div>
<script type="text/javascript">
require(['jquery', 'prototype'], function(jQuery){

//<![CDATA[
    if (typeof itemsCount == 'undefined') {
        itemsCount = 0;
    }
    giftcardAmountsControl = {
        deleteButton: false,
        addItem : function () {
            var data = {};
            data.prefix = '';
            data.website_id = 0;
            data.price      = '';
            data.index      = itemsCount++;
            if(arguments.length == 3) {
                data.prefix     = arguments[0];
                data.website_id = arguments[1];
                data.price      = arguments[2];
            } else if (arguments.length == 1) {
                data.prefix     = arguments[0];
            }

            var template = new Template('<tr>' + $(data.prefix + '_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>');
            Element.insert($(data.prefix + '_container'), {'bottom':template.evaluate(data)});

            $(data.prefix + '_giftcard_amounts_row_'+data.index+'_website').value = data.website_id;
            <?php if ($_readonly): ?>
            $('<?php echo $_htmlId ?>_container').select('input', 'select')
                .each(this.disableElement);
            $('<?php echo $_htmlId ?>_container').select('button')
                .each(this.disableElement);
            <?php endif; ?>
            this.updateTotalAmounts();
        },
        disableElement: function(elem) {
            elem.disabled = true;
            $(elem).addClassName('disabled');
        },

        deleteItem : function(prefix, event) {
            var tr = Event.findElement(event, 'tr');
            if (tr) {
                Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                Element.hide(tr);
                Element.addClassName(tr, 'ignore-validate');
            }
            this.updateTotalAmounts();
        },

        updateTotalAmounts: function() {
            var count = $('giftcard_amounts_container').select('tr:not(.ignore-validate)').length;
            $('giftcard_amounts_total').value = count > 0 ? count : '';
        }
    };

    <?php foreach ($this->getValues() as $_item): ?>
    giftcardAmountsControl.addItem('<?php echo $_htmlId ?>', '<?php echo $_item['website_id'] ?>', '<?php echo sprintf('%.2f', $_item['value']) ?>');
    <?php endforeach; ?>

    updatePriceAmountValidation = function() {
        if($('allow_open_amount')) {
            if ($('allow_open_amount').checked) {
                jQuery('#giftcard_amounts_total').trigger('resetElement');
                Element.removeClassName($('giftcard_amounts_total'), 'required-entry');
            } else {
                if (!Element.hasClassName($('giftcard_amounts_total'), 'required-entry')) {
                    Element.addClassName($('giftcard_amounts_total'), 'required-entry');
                }
            }
        }
    }

    setupPriceAmountEvents = function() {
        if ($('allow_open_amount')) {
            Event.observe('allow_open_amount', 'change', updatePriceAmountValidation);
        }
        updatePriceAmountValidation();
    }
    <?php if (!$_readonly): ?>
    Event.observe(window, 'load', setupPriceAmountEvents);
    <?php endif; ?>
//]]>

});
</script>
</div>
