<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/* @var $this Magento_MultipleWishlist_Block_Customer_Wishlist_Management */
?>
<?php if ($this->getCurrentWishlist()): ?>
<div class="wishlist-management">
    <div class="sub-title">
        <div id="wishlists-select" class="split-button">
            <strong>
                <span title="<?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?>"><?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?></span>
                <span class="item-count">(<?php echo $this->getCurrentWishlist()->getVisibility() ? __('Public') : __('Private'); ?>, <?php echo $this->getItemCount($this->getCurrentWishlist()) ?>)</span>
            </strong>
            <a class="change" href="#">(<span><?php echo __('Change') ?></span>)</a>
            <div class="list-container">
                <ul>
                    <?php foreach($this->getWishlists() as $wishlist): ?>
                        <?php if ($wishlist->getId() != $this->getCurrentWishlist()->getId()): ?>
                            <li><a title="<?php echo $this->escapeHtml($wishlist->getName());?>" href="<?php echo $this->getWishlistManagementUrl($wishlist);?>"><?php echo $this->escapeHtml($wishlist->getName());?></a></li>
                        <?php endif; ?>
                    <?php endforeach;?>
                    <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                        <li onclick="Enterprise.Wishlist.create('<?php echo $this->getCreateUrl();?>');" class="new"><span title="<?php echo __('Create New Wishlist')?>"><?php echo __('Create New Wishlist')?></span></li>
                    <?php endif;?>
                </ul>
            </div>
        </div>
        <p><a href="#" onclick="Enterprise.Wishlist.edit('<?php echo $this->getEditUrl($this->getCurrentWishlist()->getId());?>', '<?php echo $this->helper('Magento_Core_Helper_Data')->jsQuoteEscape($this->getCurrentWishlist()->getName());?>', <?php echo $this->getCurrentWishlist()->getVisibility() ? 'true' : 'false';?>); return false;" title="<?php echo __('Edit Wishlist')?>" class="link-edit wishlist-edit"><?php echo __('Edit')?></a></p>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        Enterprise.Wishlist.form = $('wishlist-view-form');
        if (!Enterprise.Wishlist.url) {
            Enterprise.Wishlist.url = {};
        }
        Enterprise.Wishlist.url.copySelected = '<?php echo $this->getCopySelectedUrl();?>';
        Enterprise.Wishlist.url.moveSelected = '<?php echo $this->getMoveSelectedUrl();?>';
        Enterprise.Wishlist.url.copyItem = '<?php echo $this->getCopyItemUrl();?>';
        Enterprise.Wishlist.url.moveItem = '<?php echo $this->getMoveItemUrl();?>';
    //]]>
    </script>
</div>
<?php endif; ?>
