<?
/*
 * Aviable methods
 * getCanDisplayContainer() - container visibility flag
 * getItems()				- comapare items collection
 * getId()					- html id of block
 * getJsObjectName()		- js object name of controller
 * getAddUrlTemplate()		- add url template
 * getRemoveUrlTemplate()	- remove url template
 */
?>
<?if($this->getCanDisplayContainer()):?>
<div class="box mini-compare-products" id="<?=$this->getId()?>" <?if($this->getItems()->getSize()==0):?> style="display:none;"<?endif;?>>
<?endif;?>
<?if($this->getItems()->getSize()>0):?>
	<div class="head"> <!-- Gives room for control buttons -->
		<h3><span><?=('Compare Products')?></span></h3>
	</div>
	<h4><?=('Products for Comparision')?></h4>
	<ul class="widget-selection-list">
		<?foreach($this->getItems() as $_item):?>
		<li class="block-compare-item">
				<input type="hidden" class="compare-item-id" value="<?=$_item->getId()?>"><a href="#" onclick="<?=$this->getJsObjectName()?>.removeItem(this);return false;" class="widget-btn"><img src="<?=$this->getSkinUrl('images/widget_remove_btn.gif')?>" alt="<?=('Remove comparison')?>"/></a><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></li>
		<?endforeach;?>
	</ul>
	<div class="actions">
		<button class="form-button" onclick="window.location.href = '<?=$this->getCompareUrl()?>'"><span>Compare</span></button>
	</div>
<?endif;?>
<?if($this->getCanDisplayContainer()):?>	
</div>
<script type="text/javascript">
<!--
	var <?=$this->getJsObjectName()?> = new Varien.CompareController('<?=$this->getId()?>',{
		updateUrl: '<?=$this->getAddUrlTemplate()?>',
		removeUrl: '<?=$this->getRemoveUrlTemplate()?>',
		successMessage: '<?=__('Product have been successfully added to comparasion list')?>'
	});
//-->
</script>
<?endif;?>