<?
/*
 * Aviable methods
 * getCanDisplayContainer() - container visibility flag
 * getItems()				- comapare items collection
 * getId()					- html id of block
 * getJsObjectName()		- js object name of controller
 * getAddUrlTemplate()		- add url template
 * getRemoveUrlTemplate()	- remove url template
 */
?>
<?if($this->getCanDisplayContainer()):?>
<div class="box mini-compare-products" id="<?=$this->getId()?>">
<?endif;?>
	<div class="head">
			<span class="corner"></span>
			<h3><?=__('Compare Products')?> <span class="count"><?=__('(%d items)', $this->getItems()->getSize())?></span></h3>
	</div>
	<div class="box-container">
	<div class="content">
	<?if($this->getItems()->getSize()>0):?>
		<ul class="widget-list">
			<?$_i=1?>
			<?foreach($this->getItems() as $_index=>$_item):?>
			<li class="block-compare-item <?if($_i==$this->getItems()->getSize()):?>last<?endif;?>">
					<input type="hidden" class="compare-item-id" value="<?=$_item->getId()?>"><a href="#" onclick="<?=$this->getJsObjectName()?>.removeItem(this);return false;"  class="action"><strong><?=__('Remove')?></strong></a><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></li>
			<?$_i++?>
			<?endforeach;?>
		</ul>
		<p class="actions">
		<button class="form-button" onclick="<?=$this->getJsObjectName()?>.openCompare('<?=$this->getCompareUrl()?>')"><span><?=__('Compare')?></span></button>
		<a href="#" onclick="<?=$this->getJsObjectName()?>.removeAll(); return false">Clear All</a>
	<?else:?>
	<?=__('You have not placed any product yet.')?>
	<?endif;?>
	</p>
</div>
</div>
<?if($this->getCanDisplayContainer()):?>
</div>
<script type="text/javascript">
<!--
	var <?=$this->getJsObjectName()?> = new Varien.CompareController('<?=$this->getId()?>',{
		updateUrl: '<?=$this->getAddUrlTemplate()?>',
		removeUrl: '<?=$this->getRemoveUrlTemplate()?>',
		successMessage: '<?=__('Product have been successfully added to comparasion list')?>',
		confirmMessage: '<?=__('Are you sure')?>'
	});
//-->
</script>
<?endif;?>