<?
/*
 * Aviable methods
 * getCanDisplayContainer() - container visibility flag
 * getItems()				- comapare items collection
 * getId()					- html id of block
 * getJsObjectName()		- js object name of controller
 * getAddUrlTemplate()		- add url template
 * getRemoveUrlTemplate()	- remove url template
 */
?>
<?if($this->getCanDisplayContainer()):?>
<div class="box base-mini  mini-compare-products">
<?endif;?>
    <div class="head">
        <h4><?=__('Compare Products')?> <span class="count"><?=__('- %d items', $this->getItems()->getSize())?></span></h4>
    </div>
    <?if($this->getItems()->getSize()>0):?>
        <ol>
            <?$_i=1?>
            <?foreach($this->getItems() as $_index=>$_item):?>
                <li class="block-compare-item <?if($_i==$this->getItems()->getSize()):?>last<?endif;?>">
                    <input type="hidden" class="compare-item-id" value="<?=$_item->getId()?>"><a href="#" onclick="<?=$this->getJsObjectName()?>.removeItem(this);return false;"   class="widget-btn"><img src="<?=$this->getSkinUrl('images/list_remove_btn.gif')?>" alt="Remove this item"/></a><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></li>
                <?$_i++?>
            <?endforeach;?>
        </ol>
        <div class="actions"><a href="#" class="left" onclick="<?=$this->getJsObjectName()?>.removeAll(); return false">Clear All</a>
            <button class="right form-button" onclick="<?=$this->getJsObjectName()?>.openCompare('<?=$this->getCompareUrl()?>')"><span><?=__('Compare')?></span></button></div>
    <?else:?>
        <div class="content"><p><?=__('You have no items to compare.')?></p></div>
    <?endif;?>
<?if($this->getCanDisplayContainer()):?>
</div>
<script type="text/javascript">
<!--
    var <?=$this->getJsObjectName()?> = new Varien.CompareController($$('.mini-compare-products')[0],{
        updateUrl: '<?=$this->getAddUrlTemplate()?>',
        removeUrl: '<?=$this->getRemoveUrlTemplate()?>',
        successMessage: '<?=__('Product have been successfully added to comparasion list')?>',
        confirmMessage: '<?=__('Are you sure')?>'
    });
//-->
</script>
<?endif;?>
<!-- [ends] .mini-compare-products // -->