<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="col2-set">
    <div class="col-1">
        <div class="head bar-head">
            <h5><?=__('Primary Billing Address')?></h5>
            <a href="<?=$baseUrl?>customer/address/edit"><?=__('Edit')?></a>
        </div>
        <address>Minu Oh<br/>
            3402 Motor Ave.,<br/>
            Suite B<br/>
            Los Angeles, CA 90034<br/>
            <strong>T</strong><span class="separator">|</span>(310123-1234</address>
    </div>
    <div class="col-2">
        <div class="head bar-head">
            <h5><?=__('Primary Shipping Address')?></h5>
            <a href="<?=$baseUrl?>customer/address/edit"><?=__('Edit')?></a>
        </div>
        <address>Minu Oh<br/>
            3402 Motor Ave.,<br/>
            Suite B<br/>
            Los Angeles, CA 90034<br/>
            <strong>T</strong><span class="separator">|</span>(310123-1234</address>
    </div>
</div>