<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_order = $this->getOrder() ?>
<?php $_giftMessage; ?>
<table class="data table order items" id="my-orders-table" summary="<?php echo $this->__('Items Ordered') ?>">
    <thead>
        <tr>
            <th class="col name"><?php echo $this->__('Product Name') ?></th>
            <th class="col sku"><?php echo $this->__('SKU') ?></th>
            <th class="col price"><?php echo $this->__('Price') ?></th>
            <th class="col qty"><?php echo $this->__('Qty') ?></th>
            <th class="col subtotal"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
        <?php echo $this->getChildHtml('order_totals') ?>
    </tfoot>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_index = 0; ?>
        <?php $_count = $_items->count(); ?>
        <?php $_giftMessage = ''?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getParentItem()) continue; ?>
        <tbody>
            <?php echo $this->getItemHtml($_item) ?>
            <?php if ($this->helper('Mage_GiftMessage_Helper_Message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
            <tr id="order-item-gift-message-<?php echo $_item->getId() ?>" role="region" aria-expanded="false" tabindex="-1" style="display:none;">
                <?php $_giftMessage = $this->helper('Mage_GiftMessage_Helper_Message')->getGiftMessageForEntity($_item); ?>
                <td class="col message" colspan="7">
                    <div class="gift message details">
                        <a href="#"
                           title="<?php echo $this->__('Close') ?>"
                           aria-controls="order-item-gift-message-<?php echo $_item->getId()?>"
                           data-item-id="<?php echo $_item->getId()?>"
                           class="action close">
                            <?php echo $this->__('Close') ?>
                        </a>
                        <dl class="gift message">
                            <dt class="gift sender"><strong class="label"><?php echo $this->__('From:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dt>
                            <dt class="gift recipient"><strong class="label"><?php echo $this->__('To:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                            <dd class="message text"><?php echo $this->helper('Mage_GiftMessage_Helper_Message')->getEscapedGiftMessage($_item) ?></dd>
                        </dl>
                    </div>
                </td>
            </tr>
            <?php endif ?>
        </tbody>
        <?php endforeach; ?>
</table>
<?php if ($_giftMessage): ?>
    <script type="text/javascript">
        head.js("<?php echo $this->getViewFileUrl('Mage_Sales::gift-message.js')?>", function() {
            jQuery('a.action.show').add('a.action.close').giftMessage();
        });
    </script>
<?php endif; ?>
