<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /* former part of Magento_Data_Form_Element_Abstract::getElementHtml() */ ?>

<?php /** @var $this Magento_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_ColorPicker|Magento_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_Checkbox */ ?>
<?php /** @var $element Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_ColorPicker */ ?>
<?php $element = $this->getElement(); ?>

<?php if ($element->getBeforeElementHtml()): ?>
    <label class="addbefore" for="<?php echo $element->getHtmlId() ?>"><?php echo $element->getBeforeElementHtml() ?></label>
<?php endif; ?>

<?php echo $this->getHtml() ?>

<?php if ($element->getAfterElementHtml()): ?>
    <label class="addafter" for="<?php echo $element->getHtmlId() ?>"><?php echo $element->getAfterElementHtml() ?></label>
<?php endif; ?>



