<div>
    <? $_order = $this->getOrder() ?>
    <input type="hidden" name="order_id" value="<?=$_order->getId()?>"/>
    <div class="box-left">
        <div class="entry-view">
            <h4><?=__('Order Date')?>: <?=$this->getOrderDateFormatted()?></h4>
        </div>
        <div class="entry-view">
            <h4><?=__('Shipping Address')?></h4>
            <div class="box customer-personal-brief">
                <?$_shipping = $_order->getShippingAddress()?>
                <address><?=$_shipping->getFirstname()?> <?=$_shipping->getLastname()?><br/>
                <?=$_shipping->getCompany()?><br/>
                <?=$_shipping->getStreet()?><br/>
                <?=$_shipping->getCity()?>, <?=$_shipping->getRegion()?> <?=$_shipping->getPostcode()?><br/>
                <strong>T</strong> | <?=$_shipping->getTelephone();
                if ($_shipping->getFax()):?><br /><strong>F</strong> | <?=$_shipping->getFax()?><?endif;?>
                </address>
            </div>
        </div>
        <div class="entry-view">
            <h4><?=__('Shipping Method')?></h4>
            <div class="box customer-personal-brief">
                <?=$_order->getShippingDescription()?>
            </div>
        </div>
    </div>
    <div class="box-right">
        <div class="entry-view">
            <h4><?=__('Order Status')?>: <?=$this->getOrderStatus()?></h4>
        </div>
        <div class="entry-view">
            <h4><?=__('Billing Address')?></h4>
            <div class="box customer-personal-brief">
                <?$_billing = $_order->getbillingAddress()?>
                <address><?=$_billing->getFirstname()?> <?=$_billing->getLastname()?><br/>
                <?=$_billing->getCompany()?><br/>
                <?=$_billing->getStreet()?><br/>
                <?=$_billing->getCity()?>, <?=$_billing->getRegion()?> <?=$_billing->getPostcode()?><br/>
                <strong>T</strong> | <?=$_billing->getTelephone();
                if ($_billing->getFax()):?><br /><strong>F</strong> | <?=$_billing->getFax()?><?endif;?></address>
            </div>
        </div>
        <div class="entry-view">
            <h4><?=__('Payment Method')?></h4>
            <div class="box customer-personal-brief">
                <?$_payment = $_order->getPayment()?>
                <?=$this->getPaymentInfo()?>
                <?=$_payment->getMethod()?>: <?=$_payment->getCcType()?> xxxx<?=$_payment->getCcLast4()?>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="entry-view">
        <h4><?=__('Items Ordered')?></h4>
    </div>
    <div>
        <?=$this->getItemsHtml()?>
    </div>
    <div class="box order-totals">
        <table cellspacing="0">
            <tfoot>
                <tr><td class="label"><strong><?=__('Grand Total')?></strong></td><td class="emph"><strong><?=$_order->getOrderCurrency()->format($_order->getGrandTotal())?></strong></td></tr>
                <?/*<tr><td class="label"><strong><?=__('Total Payed')?></strong></td><td class="emph"><strong><?=$_order->getOrderCurrency()->format($_order->getTotalPaid())?></strong></td></tr>
                <tr><td class="label"><strong><?=__('Total Due')?></strong></td><td class="emph"><strong><?=$_order->getOrderCurrency()->format($_order->getTotalDue())?></strong></td></tr>*/?>
            </tfoot>
            <tbody>
                <tr><td><?=__('Subtotal')?></td><td><?=$_order->getOrderCurrency()->format($_order->getSubtotal())?></td></tr>
                <?if ($_order->getTaxAmount()):?><tr><td><?=__('Tax')?></td><td><?=$_order->getOrderCurrency()->format($_order->getTaxAmount())?></td></tr><?endif;?>
                <?if ($_order->getShippingAmount()):?><tr><td><?=__('Shipping')?></td><td><?=$_order->getOrderCurrency()->format($_order->getShippingAmount())?></td></tr><?endif;?>
                <?if ($_order->getDiscountAmount()):?><tr><td><?=__('Discount')?></td><td><?=$_order->getOrderCurrency()->format($_order->getDiscountAmount())?></td></tr><?endif;?>
                <?if ($_order->getGiftcertAmount()):?><tr><td><?=__('Gift Certificate')?></td><td><?=$_order->getOrderCurrency()->format($_order->getGiftcertAmount())?></td></tr><?endif;?>
                <?if ($_order->getCustbalanceAmount()):?><tr><td><?=__('Customer Balance')?></td><td><?=$_order->getOrderCurrency()->format($_order->getCustbalanceAmount())?></td></tr><?endif;?>
            </tbody>
        </table>
    </div>
    <div class="clear"><h4><?=__('Order History')?></h4></div>
    <div class="box-left">
        <div class="grid">
            <table cellspacing="0" class="data" id="invoice_items_grid_table">
                <thead>
                    <tr class="headings">
                        <th class="no-link"><nobr><?=__('Date and Time')?></nobr></th>
                        <th class="no-link"><nobr><?=__('Order Status')?></nobr></th>
                        <th class="no-link"><nobr><?=__('Comment')?></nobr></th>
                    </tr>
                </thead>
                <tbody>
                    <?foreach ($this->getOrder()->getAllStatusHistory() as $_history):?>
                        <tr>
                            <td class="a-center"><nobr><?=$this->formatDate($_history->getCreatedAt())?></nobr></td>
                            <td><?=$_history->getStatus()->getFrontendLabel()?></td>
                            <td><?=$_history->getComments()?></td>
                        </tr>
                    <?endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="clear"></div>
</div>