<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript" src="<?=$this->getSkinUrl('js/giftmessage.js')?>"></script>
<?$_order = $this->getOrder()?>
<div>
    <div id="order:messages">
        <?=$this->getChildHtml('messages')?>
    </div>
    <input type="hidden" name="order_id" value="<?=$_order->getId()?>"/>

    <div class="box-left">
        <!--Order Information-->
        <div class="entry-edit">
            <h4 class="icon-head head-order-date"><?=Mage::helper('sales')->__('Order Information')?></h4>
            <fieldset>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Order Create Date')?></label>
                    <strong><?=$this->formatDate($_order->getCreatedAt(), 'medium', true)?></strong>
                </span>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Order Status')?></label>
                    <strong><span id="order_status"><?=$_order->getStatusLabel()?></span></strong>
                </span>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Purchased From')?></label>
                    <strong><?=$this->getOrderStoreName()?></strong>
                </span>
                <?if($_order->getRelationChildId()):?>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Link to the new order')?></label>
                    <a href="<?=$this->getViewUrl($_order->getRelationChildId())?>">
                        <?=$_order->getRelationChildRealId()?>
                    </a>
                </span>
                <?endif;?>
                <?if($_order->getRelationParentId()):?>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Link to the previous order')?></label>
                    <a href="<?=$this->getViewUrl($_order->getRelationParentId())?>">
                        <?=$_order->getRelationParentRealId()?>
                    </a>
                </span>
                <?endif;?>
            </fieldset>
        </div>
    </div>
    <div class="box-right">
        <!--Account Information-->
        <div class="entry-edit">
            <h4 class="icon-head head-account"><?=Mage::helper('sales')->__('Account Information')?></h4>
            <fieldset>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Email')?></label>
                    <strong><?=$_order->getCustomerEmail()?></strong>
                </span>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Customer Group')?></label>
                    <strong><?=$this->getCustomerGroupName()?></strong>
                </span>
                <span class="field-row">
                    <a href="mailto:<?=$_order->getCustomerEmail()?>"><?=Mage::helper('sales')->__('Send Email to Customer')?></a>
                </span>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>

    <div class="box-left">
        <!--Billing Address-->
        <div class="entry-edit">
            <h4 class="icon-head head-billing-address"><?=Mage::helper('sales')->__('Billing Address')?></h4>
            <fieldset>
                <address><?=$_order->getBillingAddress()->getFormated(true)?></address>
            </fieldset>
        </div>
    </div>
    <div class="box-right">
        <!--Shipping Address-->
        <div class="entry-edit">
            <h4 class="icon-head head-shipping-address"><?=Mage::helper('sales')->__('Shipping Address')?></h4>
            <fieldset>
                <address><?=$_order->getShippingAddress()->getFormated(true)?></address>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>

    <div class="box-left">
        <!--Payment Method-->
        <div class="entry-edit">
            <h4 class="icon-head head-payment-method"><?=Mage::helper('sales')->__('Payment Information')?></h4>
            <fieldset>
                <?=$this->getPaymentHtml()?>
            </fieldset>
        </div>
    </div>
    <div class="box-right">
        <!--Shipping Method-->
        <div class="entry-edit">
            <h4 class="icon-head head-shipping-method"><?=Mage::helper('sales')->__('Shipping Information')?></h4>
            <fieldset>
                <span class="field-row">
                    <label><?=Mage::helper('sales')->__('Shipping Method')?></label>
                    <strong><?=$_order->getShippingDescription()?></strong>
                </span>
                <!--strong><?=$_order->formatPrice($_order->getShippingAmount())?></strong-->
                <div>
                <?=$this->getTrackingHtml()?>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>

    <div class="entry-view">
        <h4 class="icon-head head-products"><?=Mage::helper('sales')->__('Items Ordered')?></h4>
    </div>
    <div>
        <?=$this->getItemsHtml()?>
    </div>
    <div class="clear"></div>
    <br/>
    <?=$this->getGiftmessageHtml()?>

    <div class="box-right">
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td width="60%" style="padding-right:20px">
                    <div><?=$this->getChildHtml('history')?></div>
                </td>
                <td>
                    <div class="box  order-totals">
                        <?=$this->getChildHtml('totals')?>
                    </div>
                </td>
            </tr>
        </table>
        </div>
    </div>
    <div class="clear"></div>
</div>
