<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Options_Option */ ?>
<?php echo $this->getTemplatesHtml() ?>
<script id="custom-option-base-template" type="text/x-jquery-tmpl">
    <div class="fieldset" id="option_${id}">
        <div class="fieldset-wrapper-title">
            <strong class="title" data-toggle="collapse" data-target="#${id}-content">
                <span id="option_${id}_header_title">${title}</span>
            </strong>

            <div id="<?php echo $this->getFieldId() ?>_${id}_move" class="draggable-handle" title="<?php echo $this->__('Sort Custom Options'); ?>"></div>
            <div class="actions">
                <button type="button" title="<?php echo $this->__('Delete Custom Option'); ?>" class="action-delete" id="<?php echo $this->getFieldId() ?>_${id}_delete">
                    <span><?php echo $this->__('Delete Custom Option'); ?></span>
                </button>
            </div>
        </div>
        <table id="<?php echo $this->getFieldId() ?>_${id}" class="data-table" cellspacing="0">
            <input id="<?php echo $this->getFieldId() ?>_${id}_is_delete" name="<?php echo $this->getFieldName() ?>[${id}][is_delete]" type="hidden" value=""/>
            <input id="<?php echo $this->getFieldId() ?>_${id}_previous_type" name="<?php echo $this->getFieldName() ?>[${id}][previous_type]" type="hidden" value="${type}"/>
            <input id="<?php echo $this->getFieldId() ?>_${id}_previous_group" name="<?php echo $this->getFieldName() ?>[${id}][previous_group]" type="hidden" value=""/>
            <input id="<?php echo $this->getFieldId() ?>_${id}_id" name="<?php echo $this->getFieldName() ?>[${id}][id]" type="hidden" value="${id}"/>
            <input id="<?php echo $this->getFieldId() ?>_${id}_option_id" name="<?php echo $this->getFieldName() ?>[${id}][option_id]" type="hidden" value="${option_id}"/>
            <input name="<?php echo $this->getFieldName() ?>[${id}][sort_order]" type="hidden" value="${sort_order}"/>
            <thead>
            <tr>
                <th><?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Title') ?><span class="required">*</span></th>
                <th><?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Input Type') ?><span class="required">*</span></th>
                <th><?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Is Required') ?></th>
            </tr>
            </thead>
            <tr>
                <td class="opt-title">
                    <input id="<?php echo $this->getFieldId() ?>_${id}_title" name="<?php echo $this->getFieldName() ?>[${id}][title]" class="required-entry input-text" type="text" value="${title}" data-store-label="${title}">{{html checkboxScopeTitle}}
                </td>
                <td class="opt-type"><?php echo $this->getTypeSelectHtml() ?></td>
                <td class="opt-required">
                    <input id="<?php echo $this->getFieldId() ?>_${id}_required" class="is-required" type="checkbox" checked="checked"/>
                    <span style="display: none;"><?php echo $this->getRequireSelectHtml() ?></span>
                </td>
            </tr>
        </table>
    </div>
</script>

<div id="import-container" style="display: none;"></div>
<?php if (!$this->isReadonly()): ?>
<div><input type="hidden" name="affect_product_custom_options" value="1"/></div>
<?php endif; ?>

<script type="text/javascript">
jQuery(function ($) {
    $.validator.addMethod(
        'required-option-select', function (value, element) {
            return (value !== '');
        }, <?php echo Mage::helper('Mage_Core_Helper_Data')->jsonEncode(Mage::helper('Mage_Catalog_Helper_Data')->__('Select type of option.')); ?>);
    $.validator.addMethod(
        'required-option-select-type-rows', function (value, element) {
            var optionContainerElm = element.up('div[id*=_type_]');
            var selectTypesFlag = false;
            var selectTypeElements = $('#' + optionContainerElm.id + ' .select-type-title');
            selectTypeElements.each(function () {
                if ($(this).attr('id') && $(this).closest('tr').is(':visible')) {
                    selectTypesFlag = true;
                }
            });
            return selectTypesFlag;
        }, <?php echo Mage::helper('Mage_Core_Helper_Data')->jsonEncode(Mage::helper('Mage_Catalog_Helper_Data')->__('Please add rows to option.')); ?>);
    var fieldSet = $('#Custom_Options');
    fieldSet.customOptions(<?php echo Mage::helper('Mage_Core_Helper_Data')->jsonEncode(
        array(
            'fieldId' => $this->getFieldId(),
            'productGridUrl' => $this->getProductGridUrl(),
            'formKey' => $this->getFormKey(),
            'customOptionsUrl' => $this->getCustomOptionsUrl(),
            'isReadonly' => $this->isReadonly(),
            'itemCount' => $this->getItemCount()
        )
    )?>);
    //adding data to templates
    <?php /** @var $_value Varien_Object */ ?>
    <?php foreach ($this->getOptionValues() as $_value): ?>
        fieldSet.customOptions('addOption', <?php echo $_value->toJson() ?>);
    <?php endforeach; ?>
});
</script>