<div class="head">
    <table cellspacing="0"> 
        <tr>
            <td style="width:30%;"><h3><?=$header?></h3></td>
            <td class="buttons">
                <strong class="button"><span><a href="#" onclick="history.back();return false;"><?=__('back')?></a></span></strong>
                <strong class="button"><span><a href="#" onclick="customerGroupForm.submit();return false;"><?=__('save customer group')?></a></span></strong>
                <?if($this->getEditMode()):?>
                <strong class="button"><span><a href="<?=$this->getDeleteUrl()?>"><?=__('delete customer group')?></a></span></strong>
                <?endif?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="customer_group_edit_form">
<?=$form?>
</form>
<script type="text/javascript" language="javascript">
    var customerGroupForm = new varienForm('customer_group_edit_form');
</script>