<div class="content-header">
    <table cellspacing="0" class="grid-header"> 
        <tr>
            <td style="width:30%;"><h3><?=$header?></h3></td>
            <td class="form-buttons">
							<table cellspacing="0" class="form-button">
								<tr>
									<td class="form-button-left"></td>
									<td class="form-button-right"><a href="#" onclick="customerGroupForm.submit();return false;"><?=__('Save Customer Group')?></a></td>
								</tr>
							</table>
							<table cellspacing="0" class="form-button">
								<tr>
									<td class="form-button-left"></td>
									<td class="form-button-right"><a href="#" onclick="history.back();return false;"><?=__('Back')?></a></td>
								</tr>
							</table>
							<?if($this->getEditMode()):?>
							<table cellspacing="0" class="form-button">
								<tr>
									<td class="form-button-left"></td>
									<td class="form-button-right"><a href="<?=$this->getDeleteUrl()?>"><?=__('Delete Customer Group')?></a></td>
								</tr>
							</table>
							<?endif?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="customer_group_edit_form">
<?=$form?>
</form>
<script type="text/javascript" language="javascript">
    var customerGroupForm = new varienForm('customer_group_edit_form');
</script>