<div class="head">
<table cellspacing="0">	
	<tr>
		<td style="width:50%;"><h2><?=__('customer groups title')?></h2></td>
		<td class="buttons"><strong class="button"><span><a href="<?=$baseUrl?>adminhtml/customer_group/new"><?=__('create customer group');?></a></span></strong></td>
	</tr>
</table>
</div>
<?=$grid;?>
<script type="text/javascript">
<!--
var gridController = {
    onRowClick : function(e) {
        if(e.target.tagName != 'A') {
            var editHrefObjects = $(Event.findElement(e,'tr')).getElementsByClassName('edit-url');
            if(editHrefObjects.length > 0) {
                location.href = editHrefObjects[0].href;
            }
            //location.href = 
        }
    }
};

varienGlobalEvents.attachEventHandler('gridRowClick', gridController.onRowClick);
//-->
</script>