<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="entry-edit" id="import_validation_container" style="display:none;">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend" id="import_validation_container_header"><?php echo $this->__('Validation Results'); ?></h4>
    </div>
    <div id="import_validation_messages" class="fieldset "><!-- --></div>
</div>
<script type="text/javascript">
//<![CDATA[
    $('entity').selectedIndex = 0; // forced resetting entity selector after page refresh
    $('behavior').selectedIndex = 0; // forced resetting behavior selector after page refresh
    $('file_format_version').selectedIndex = 0; // forced resetting file format version selector after page refresh
    $('customer_entity').selectedIndex = 0; // forced resetting customer entity selector after page refresh
//]]>
</script>
