<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General
 */
?>
<script type="text/javascript">
    require(['prototype', 'Magento_Rma/rma'], function() {
        window.rma = new AdminRma();
    });
    require(['Magento_Rma/details-validator']);
</script>

<div class="clearfix">
    <?php if ($this->getChildHtml('shipping_method')): ?>
    <div class="rma-request-details">
    <?php endif; ?>

    <?php echo $this->getChildHtml('request_details') ?>

    <?php if ($this->getChildHtml('shipping_method')): ?>
    </div>
    <?php endif; ?>

    <div class="order-shipping-method">
        <?php echo $this->getChildHtml('shipping_method') ?>
    </div>
</div>
<div class="clearfix">
    <div class="order-shipping-address">
        <?php echo $this->getChildHtml('shipping_address') ?>
    </div>

    <div class="order-return-address">
        <?php echo $this->getChildHtml('return_address') ?>
    </div>
</div>

<div class="clearfix">
    <div class="order-comments-history">
        <?php echo $this->getChildHtml('comments_history') ?>
    </div>
    <div class="rma-confirmation">
        <?php echo $this->getChildHtml('return_confirmation') ?>
    </div>
</div>
