<div class="inner-head">
    <h5>Address Book</h5>
    <a href="<?=$this->getAddressBookUrl()?>">Manage addresses</a>
</div>
<div class="col2-set">
    <div class="col-1">
        <h6><?=__('Primary Billing Address')?></h6>
        <address>
            <?=$this->getPrimaryBillingAddressHtml()?><br/>
            <a href="<?=$this->getPrimaryBillingAddressEditUrl()?>"><?=__('Edit')?></a>
        </address>
    </div>
    <div class="col-2">
        <h6><?=__('Primary Shipping Address')?></h6>
        <address>
            <?=$this->getPrimaryShippingAddressHtml()?><br/>
            <a href="<?=$this->getPrimaryShippingAddressEditUrl()?>"><?=__('Edit')?></a>
        </address>
    </div>
</div><br/>