<div class="account-box">
    <div class="head">
        <h4>Shopping Cart</h4>
    </div>
    <p>You have <a href="#"><strong>3 items</strong></a> in your shopping cart.</p>
</div>


<div class="account-box">
    <div class="head">
        <h4>Wishlist</h4>
        <a href="<?=$baseUrl?>wishlist/">View All</a>
    </div>
    <div class="box-container">
        <div class="content">
            <ol>
                <li>
                    <div class="product-images">
                        <a href="#"><img src="images/ph_product_thumb.jpg" alt="Warm Weather Polyethelene Clogs" width="55" height="55"/></a>
                    </div>
                    <div class="product-details">
                        <a href="#">Warm Weather Polyethelene Clogs</a>
                        <div class="price-box">
                            $109.45
                        </div>
                        <a href="#"><strong>Add to Cart</strong></a>
                    </div>
                </li>
                <li>
                    <div class="product-images">
                        <a href="#"><img src="images/ph_product_thumb.jpg" alt="Warm Weather Polyethelene Clogs" width="55" height="55"/></a>
                    </div>
                    <div class="product-details">
                        <a href="#">Warm Weather Polyethelene Clogs</a>
                        <div class="price-box">
                            $109.45
                        </div>
                        <a href="#"><strong>Add to Cart</strong></a>
                    </div>
                </li>
                <li>
                    <div class="product-images">
                        <a href="#"><img src="images/ph_product_thumb.jpg" alt="Warm Weather Polyethelene Clogs" width="55" height="55"/></a>
                    </div>
                    <div class="product-details">
                        <a href="#">Warm Weather Polyethelene Clogs</a>
                        <div class="price-box">
                            $109.45
                        </div>
                        <a href="#"><strong>Add to Cart</strong></a>
                    </div>
                </li>
            </ol>
        </div>
    </div>
</div>


<div class="account-box">
    <div class="head">
        <h4>Last Viewed Items</h4>
        <a href="#">View All</a>
    </div>
    <div class="box-container">
        <div class="content">
            <ol>
                <li>
                    <div class="product-images">
                        <a href="#"><img src="images/ph_product_thumb.jpg" alt="Warm Weather Polyethelene Clogs" width="55" height="55"/></a>
                    </div>
                    <div class="product-details">
                        <a href="#">Warm Weather Polyethelene Clogs</a>
                        <div class="price-box">
                            $109.45
                        </div>
                        <a href="#"><strong>Add to Cart</strong></a>
                    </div>
                </li>
                <li>
                    <div class="product-images">
                        <a href="#"><img src="images/ph_product_thumb.jpg" alt="Warm Weather Polyethelene Clogs" width="55" height="55"/></a>
                    </div>
                    <div class="product-details">
                        <a href="#">Warm Weather Polyethelene Clogs</a>
                        <div class="price-box">
                            $109.45
                        </div>
                        <a href="#"><strong>Add to Cart</strong></a>
                    </div>
                </li>
                <li>
                    <div class="product-images">
                        <a href="#"><img src="images/ph_product_thumb.jpg" alt="Warm Weather Polyethelene Clogs" width="55" height="55"/></a>
                    </div>
                    <div class="product-details">
                        <a href="#">Warm Weather Polyethelene Clogs</a>
                        <div class="price-box">
                            $109.45
                        </div>
                        <a href="#"><strong>Add to Cart</strong></a>
                    </div>
                </li>
            </ol>
        </div>
    </div>
</div>


<div class="account-box mini-compare-products">
    <div class="head">
        <h4>Compare Products</h4>
        <a href="#">View All</a>
    </div>
    <div class="box-container">
        <div class="content">
            <ul class="widget-list">
                <li><a href="#" class="action"><strong>Remove</strong></a><a href="#">Women's Nike Sports Socks</a></li>
                <li><a href="#" class="action"><strong>Remove</strong></a><a href="#">Women's Nike Sports Socks</a></li>
                <li><a href="#" class="action"><strong>Remove</strong></a><a href="#">Women's Nike Sports Socks</a></li>
                <li class="last"><a href="#" class="action"><strong>Remove</strong></a><a href="#">Women's Nike Sports Socks</a></li>
            </ul>
        </div>
        <p class="actions">
            <button class="form-button"><span>Compare</span></button>
            <a href="#">Clear All</a>
        </p>
    </div>
</div>