<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 */
?>
<div class="block giftcard">
    <div class="title"><strong><?php echo $this->__('Gift Cards') ?></strong></div>
    <div class="content">
        <div id="giftcard_balance_lookup"></div>
        <span id="gc-please-wait" class="load indicator" style="display:none;">
            <span><?php echo $this->__('Please wait, loading...') ?></span>
        </span>
        <form class="form giftcard add" id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
            <fieldset class="fieldset">
                <div class="field">
                    <label class="label" for="giftcard-code"><span><?php echo $this->__('Enter the gift card code') ?></span></label>
                    <div class="control">
                        <input class="input-text" type="text" id="giftcard-code" name="giftcard_code" data-validate="{required:true}" value="" />
                    </div>
                </div>
                <div class="actions">
                    <div class="primary">
                        <button class="action submit" type="submit" value="<?php echo $this->__('Add Gift Card') ?>">
                            <span><?php echo $this->__('Add Gift Card') ?></span>
                        </button>
                    </div>
                    <div class="secondary">
                        <button class="action check" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>">
                            <span><?php echo $this->__('Check Gift Card status and balance') ?></span>
                        </button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

    <script type="text/javascript">
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
                "<?php echo $this->getViewFileUrl('Enterprise_GiftCardAccount::js/gift-card.js')?>", function() {
                    $('#giftcard-form').giftCard({
                        giftCardCodeSelector: '#giftcard-code',
                        checkStatus: 'button.action.check',
                        giftCardStatusUrl: '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
                        giftCardStatusId: '#giftcard_balance_lookup',
                        giftCardSpinnerId: '#gc-please-wait'
                    }).validation();
                });
        })(jQuery);
    </script>
</div>
