<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<p style="font-size:12px; line-height:16px; margin:0 0 16px;">
    <?php echo $this->__("RSS link to %s's wishlist",$this->helper('Magento_Wishlist_Helper_Data')->getCustomerName()) ?>
    <br />
    <a href="<?php echo $this->helper('Magento_Wishlist_Helper_Data')->getRssUrl($this->getWishlistId()); ?>"><?php echo $this->helper('Magento_Wishlist_Helper_Data')->getRssUrl($this->getWishlistId()); ?></a>
</p>
