<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle */
?>
<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
//<![CDATA[
    Enterprise.Bundle.swapReloadPrice();
    var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
//]]>
</script>
<?php endif; ?>
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->helper('Mage_Catalog_Helper_Data')->__('Availability:') ?> <span><?php echo $this->helper('Mage_Catalog_Helper_Data')->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->helper('Mage_Catalog_Helper_Data')->__('Availability:') ?> <span><?php echo $this->helper('Mage_Catalog_Helper_Data')->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>
