<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_Invitation_Block_Customer_List
 */
?>
<div class="page-title">
    <h1><?php echo __('My Invitations'); ?></h1>
</div>

<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<?php echo $this->getChildHtml('list_before')?>

<?php if (count($this->getInvitationCollection())): ?>

<table class="data-table" id="invitations-list-table" cellpadding="0">
    <col />
    <col width="100" />
    <thead>
        <tr>
            <th>
                <?php echo __('Email'); ?>
            </th>
            <th>
                <?php echo __('Status'); ?>
            </th>
        </tr>
    </thead>
    <tbody>

    <?php foreach ($this->getInvitationCollection() as $invitation): ?>
        <tr>
            <td>
                <?php echo $this->escapeHtml($invitation->getEmail()); ?>
            </td>
            <td>
                <?php echo $this->helper('Enterprise_Invitation_Helper_Data')->getInvitationStatusText($invitation);?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">(function($) {$('#invitations-list-table').decorate('table')})(jQuery)</script>

<?php else: ?>

<div id="cookie-notice">
    <ul class="messages"><li class="notice-msg">
        <ul><li><?php echo __('There are no sent invitations.'); ?></li></ul>
    </li></ul>
</div>

<?php endif; ?>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
    <a href="<?php echo $this->helper('Enterprise_Invitation_Helper_Data')->getCustomerInvitationFormUrl(); ?>" class="button"><span><?php echo __('Send Invitations') ?></span></a>
</div>
