<?php
/**
 * Container for editing subscription grid
 *
 * {license_notice}
 *
 * @category    Magento
 * @package     Magento_Webhook
 * @copyright   {copyright}
 * @license     {license_link}
 */
namespace Magento\Webhook\Block\Adminhtml\Subscription;

class Edit extends \Magento\Backend\Block\Widget\Form\Container
{
    /** Key used to store subscription data into the registry */
    const REGISTRY_KEY_CURRENT_SUBSCRIPTION = 'current_subscription';

    /** Keys used to retrieve values from subscription data array */
    const DATA_SUBSCRIPTION_ID = 'subscription_id';

    /** @var array $_subscriptionData */
    protected $_subscriptionData;

    /**
     * @param \Magento\Core\Model\Registry $registry
     * @param \Magento\Backend\Block\Template\Context $context
     * @param array $data
     */
    public function __construct(
        \Magento\Core\Model\Registry $registry,
        \Magento\Backend\Block\Template\Context $context,
        array $data = array()
    ) {
        parent::__construct($context, $data);

        $this->_objectId = 'id';
        $this->_blockGroup = 'Magento_Webhook';
        $this->_controller = 'adminhtml_subscription';
        $this->_subscriptionData = $registry->registry(self::REGISTRY_KEY_CURRENT_SUBSCRIPTION);
        // Don't allow the merchant to delete subscriptions that were generated by config file.
        if ($this->_isCreatedByConfig()) {
            $this->_removeButton('delete');
            $this->_removeButton('reset');
            $this->_removeButton('save');
        }
    }

    /**
     * Gets header text
     *
     * @return string
     */
    public function getHeaderText()
    {
        if ($this->_isExistingSubscription()) {
            return __('Edit Subscription');
        } else {
            return __('Add Subscription');
        }
    }

    /**
     * Returns true is subscription exists
     *
     * @return bool
     */
    protected function _isExistingSubscription()
    {
        return $this->_subscriptionData
            && isset($this->_subscriptionData[self::DATA_SUBSCRIPTION_ID])
            && $this->_subscriptionData[self::DATA_SUBSCRIPTION_ID];
    }

    /**
     * Check whether subscription was generated from configuration.
     * 
     * Return false if subscription created within UI.
     *
     * @return bool
     */
    protected function _isCreatedByConfig()
    {
        return $this->_subscriptionData && isset($this->_subscriptionData['alias']);
    }
}
