<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
// <![CDATA[

function submitApplication() {
  submitUrl = "<?php echo $this->getActionUrl() ?>";
  editForm.submit(submitUrl);
}

// ]]>
</script>
<table border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td valign="top" width="540px"><?php echo $this->getChildHtml('edit_form'); ?></td>
        <td width="20px"> </td>
        <td valign="top" width="360px"><?php echo $this->getChildHtml('app_preview'); ?></td>
    </tr>
</table>
