<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Mage
 * @package    default_default
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="order:gift_message">
<?if($this->helper('giftmessage/message')->getIsMessagesAviable('main', $this->getQuote(), $this->getStoreId())):?>
<div class="clear"></div>
<div class="giftmessage-order-create">
    <div class="entry-edit">
        <div>
        <h4 class="fieldset-legend head-gift-message"><?=$this->__('Gift Message')?></h4>
        <div class="clear"></div>
        </div>
        <fieldset>
        <?if ($_items=$this->getItems()):?>
            <div class="entire-order">
                <div class="section-head"><?=$this->__('Add a gift message for the <b>entire order</b>')?></div>
                <?=$this->getFormHtml($this->getQuote(), 'main')?>
            </div>
            <div class="each-order-item">
                <div class="section-head"><?=$this->__('Add a gift message for <b>each gift item</b>')?></div>
                    <?foreach ($_items as $_item):?>
                        <div class="item-head"><?=$_item->getName()?></div>
                        <?=$this->getFormHtml($_item, 'item');?>
                    <?endforeach;?>
            </div>
        <?else:?>
            <div class="entire-order single">
                <div class="section-head"><?=$this->__('Add a gift message for the <b>entire order</b>')?></div>
                <?=$this->getFormHtml($this->getQuote(), 'main')?>
            </div>
        <?endif?>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
<script type="text/javascript">
if(!window.toogleRequired) {
    var toogleRequired = function (source, objects)
    {
        if(!$(source).value.blank()) {
            objects.each(function(item) {
               $(item).addClassName('required-entry');
            });
        } else {
            objects.each(function(item) {
                if(editForm && editForm.validator) {
                   editForm.validator.reset(item);
                }
                $(item).removeClassName('required-entry');
            });
        }
    }
}
</script>
<?endif;?>
</div>