<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="box order-totals">
    <table cellspacing="0">
        <?$_store = $this->getStore()?>
        <tbody>
            <?$_totals = $this->getTotals();?>
            <?$_count = count($_totals);?>
            <?$_i = 0;?>
            <?foreach ($_totals as $_total):?>
                <?$_i++;?>
                <tr<?=($_i >= $_count ? ' class="last"' : '' )?>>
                    <td class="a-right" style="<?=$_total->getStyle()?>"><?=$_total->getTitle()?></td>
                    <td class="last a-right" style="<?=$_total->getStyle()?>"><nobr><?=$this->formatPrice($_total->getValue())?></nobr></td>
                </tr>
            <?endforeach;?>
        </tbody>
    </table>
</div>