<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <!--<h4 class="icon-head fieldset-legend <?=$this->getHeaderCssClass()?>"><?=$this->getHeaderText()?></h4>-->
    <table cellspacing="5" cellpadding="8" width="100%">
        <?$_store = $this->getStore()?>
        <tbody>
            <?$_totals = $this->getTotals();?>
            <?$_count = count($_totals);?>
            <?$_i = 0;?>
            <?foreach ($_totals as $_total):?>
                <?$_i++;?>
                <tr class="<?=$_total->getCode()?> <?=($_i >= $_count ? ' last' : '' )?>">
                    <td class="a-right" style="<?=$_total->getStyle()?>"><?=$_total->getTitle()?></td>
                    <td class="last a-right" style="<?=$_total->getStyle()?>"><span class="nobr"><?=$this->formatPrice($_total->getValue())?></span></td>
                </tr>
            <?endforeach;?>
        </tbody>
    </table>
	<div class="divider"></div>
	<p class="a-right">
        <label for="notify_customer" class="normal"><?=Mage::helper('sales')->__('Append Comments')?></label>
        <input type="checkbox" id="notify_customer" name="order[comment][customer_note_notify]" value="1" <?if($this->getNoteNotify()):?>checked="true"<?endif;?>/>
    </p>
    <p class="a-right">
        <label for="send_confirmation" class="normal"><?=Mage::helper('sales')->__('Email Order Confirmation')?></label>
        <input type="checkbox" id="send_confirmation" name="order[send_confirmation]" value="1" checked="true"/>
    </p>
    <p class="a-right"><?=$this->getButtonHtml(Mage::helper('sales')->__('Submit Order'),'order.submit()');?></p>