<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward
 */
?>
<?php echo $this->getChildHtml('', true); ?>
<div class="actions toolbar">
    <div class="secondary">
        <a class="action back" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
            <span><?php echo __('Back') ?></span>
        </a>
    </div>
</div>
