<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form id="co-billing-form" action="">
<fieldset>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <li class="form-alt">
            <label for="billing-address-select"><?php echo __('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <div class="fieldset">
            <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            <ul>
                <li class="fields">
                <?php echo $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </li>
                <li>
                    <label for="billing:company"><?php echo __('Company') ?></label>
                    <div class="input-box">
                        <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo __('Company') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('company') ?>" />
                    </div>
                </li>
        <?php if (!$this->isCustomerLoggedIn()): ?>
                <li>
                    <label for="billing:email" class="required"><em>*</em><?php echo __('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo __('Email Address') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </li>
        <?php endif; ?>
        <?php $_streetValidationClass = $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('street'); ?>
                <li>
                    <label for="billing:street1" class="required"><em>*</em><?php echo __('Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo __('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('Magento_Customer_Helper_Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="add-field">
                    <div class="input-box">
                        <input type="text" title="<?php echo __('Street Address %1', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
        <?php endfor; ?>
                <li class="fields">
                    <?php if ($this->helper('Magento_Customer_Helper_Address')->isVatAttributeVisible()) : ?>
                    <div class="field">
                        <label for="billing:vat_id"><?php echo __('VAT Number') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo __('VAT Number') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </div>
                    <?php endif; ?>
                    <div class="field">
                        <label for="billing:city" class="required"><em>*</em><?php echo __('City') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo __('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:region_id" class="required"><em>*</em><?php echo __('State/Province') ?></label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo __('State/Province') ?>" data-validate="{'validate-select':true}" style="display:none;">
                                <option value=""><?php echo __('Please select region, state or province') ?></option>
                            </select>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo __('State/Province') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:postcode" class="required"><em>*</em><?php echo __('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo __('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('postcode') ?>" data-validate="{'validate-zip-international':true}"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:country_id" class="required"><em>*</em><?php echo __('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="billing:telephone" class="required"><em>*</em><?php echo __('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo __('Telephone') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:fax"><?php echo __('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo __('Fax') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                        </div>
                    </div>
                </li>

                <?php $addressAttributes = $this->getChildBlock('customer_form_billing_address_user_defined_attributes');?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntity($this->getAddress())->setEntityType('customer_address');?>
                    <?php $addressAttributes->setFieldIdFormat('billing:%1$s')->setFieldNameFormat('billing[%1$s]');?>
                    <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                <?php endif;?>

                <?php if(!$this->isCustomerLoggedIn()): ?>
                <?php $_dob = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Dob') ?>
                <?php $_taxvat = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Taxvat') ?>
                <?php $_gender = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Gender') ?>
                <?php if ($_dob->isEnabled() || $_taxvat->isEnabled() || $_gender->isEnabled() ): ?>
                <li class="fields">
                    <?php if ($_dob->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())
                            ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    </div>
                    <?php endif; ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                                <div class="field">
                                    <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                                        ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </div>
                    <?php endif ?>
                    <?php if ($_gender->isEnabled()): ?>
                                <div class="field">
                                    <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())
                                        ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </div>
                    <?php endif ?>
                </li>
                <?php endif; ?>
                <?php $customerAttributes = $this->getChildBlock('customer_form_customer_user_defined_attributes');?>
                <?php if ($customerAttributes): ?>
                    <?php $customerAttributes->setEntityModelClass('Magento_Customer_Model_Customer')->setFieldIdFormat('billing:%1$s');?>
                    <?php $customerAttributes->setFieldNameFormat('billing[%1$s]')->setShowContainer(false);?>
                    <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
                <?php endif;?>
                <li class="fields" id="register-customer-password">
                    <div class="field">
                        <label for="billing:customer_password" class="required"><em>*</em><?php echo __('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo __('Password') ?>" class="input-text" data-validate="{required:true, 'validate-password':true}"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:confirm_password" class="required"><em>*</em><?php echo __('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]" title="<?php echo __('Confirm Password') ?>" id="billing:confirm_password" class="input-text" data-validate="{required:true, 'validate-cpassword':true}"/>
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>

                <?php endif; ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <div class="input-box">
                            <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo __('Save in address book') ?>" id="billing:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                        </div>
                        <label for="billing:save_in_address_book"><?php echo __('Save in address book') ?></label>
                    </li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                <?php endif; ?>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
     </li>
    <?php if ($this->canShip()): ?>
        <li class="control">
            <div class="input-box">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> class="radio" />
            </div>
            <label for="billing:use_for_shipping_yes"><?php echo  __('Ship to this address') ?></label>
        </li>
        <li class="control">
            <div class="input-box">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> class="radio" />
            </div>
            <label for="billing:use_for_shipping_no"><?php echo __('Ship to different address') ?></label>
        </li>
    <?php endif; ?>
    </ul>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>
</fieldset>
<div class="buttons-set form-buttons btn-only" id="billing-buttons-container">
    <button type="button" class="button"><span><span><?php echo __('Continue') ?></span></span></button>
    <span id="billing-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo __('Loading next step...') ?>
    </span>
</div>
<p class="required"><?php echo __('* Required Fields') ?></p>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('Magento_Checkout::js/region-updater.js') ?>",
            function() {
                $('#billing\\:country_id').regionUpdater({
                    optionalRegionAllowed: <?php echo ($this->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                    regionListId: '#billing\\:region_id',
                    regionInputId: '#billing\\:region',
                    postcodeId: '#billing\\:postcode',
                    regionJson: <?php echo $this->helper('Magento_Directory_Helper_Data')->getRegionJson() ?>,
                    defaultRegion: "<?php echo $this->getAddress()->getRegionId() ?>",
                    countriesWithOptionalZip: <?php echo $this->helper('Magento_Directory_Helper_Data')->getCountriesWithOptionalZip(true) ?>
                });
            });
    })(jQuery);
</script>

