<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this Enterprise_CustomerBalance_Block_Checkout_Onepage_Payment_Additional */
?>
<?php
/**
 * @see Enterprise_CustomerBalance_Block_Checkout_Onepage_Payment_Additional
 */
?>
<?php if ($this->isDisplayContainer()): ?>
<div class="checkout-onepage-payment-additional-customerbalance" id="customerbalance-placer">
    <input type="hidden" name="payment[use_customer_balance]" value="0"/>
    <input type="checkbox" class="checkbox" name="payment[use_customer_balance]" value="1"
           id="use-customer-balance" <?php echo ($this->isCustomerBalanceUsed() ? 'checked' : '') ?>/>

    <?php $balance = Mage::helper('Mage_Core_Helper_Data')->currency($this->getBalance()); ?>
    <label for="use-customer-balance">
        <strong>
            <?php echo Mage::helper('Enterprise_CustomerBalance_Helper_Data')->__('Use Store Credit'); ?>
            (<span id="customerbalance-available-amount"><?php echo $balance; ?></span>
            <?php echo Mage::helper('Enterprise_CustomerBalance_Helper_Data')->__('available'); ?>)
        </strong>
    </label>
</div>
<script type="text/javascript">
    if (payment) {
        var customerBalanceInit = function() {
            if ($('use-customer-balance')) {
                $('use-customer-balance').disabled = false;
            }
        }
        payment.addAfterInitFunction('customerbalance', customerBalanceInit.bind(payment));
        var customerBalanceValidate = function() {
            if (quoteBaseGrandTotal < 0.0001) {
                return true;
            }
            return false;
        }
        payment.addBeforeValidateFunction('customerbalance', customerBalanceValidate.bind(payment));
    }

    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            "<?php echo $this->getViewFileUrl('Enterprise_CustomerBalance::js/storecredit.js') ?>",
            "<?php echo $this->getViewFileUrl('Enterprise_CustomerBalance::js/onepagestorecredit.js') ?>",
            function() {
                $('body').onepageStoreCredit({
                    customerBalanceCheckBoxSelector: '#use-customer-balance',
                    customerBalanceSubstracted: <?php if ($this->isCustomerBalanceUsed()): ?>true<?php else: ?>false<?php endif; ?>,
                    baseCustomerBalAmountUsed: <?php echo (float)$this->getQuote()->getBaseCustomerBalAmountUsed(); ?>,
                    balance: <?php echo (float)$this->getBalance(); ?>,
                    quoteBaseGrandTotal: <?php echo (float)$this->getQuote()->getBaseGrandTotal(); ?>,
                    customerBalancePaymentSelector: '#customerbalance-hidden-payment',
                    customerBalanceBlockSelector: '#customerbalance-placer',
                    paymentMethodsSelector: '#checkout-payment-method-load',
                    customerBalanceAmountSelector: "#customerbalance-available-amount",
                    payment: payment,
                    paymentForm: '#co-payment-form',
                    formattedBalance: '<?php echo Mage::helper('Mage_Core_Helper_Data')->currency($this->getBalance()); ?>',
                    isAllowed: "<?php echo $this->isAllowed(); ?>"
                });
            });
    })(jQuery);
</script>
<?php endif; ?>
