<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme_Selector_List_Available */?>

<div class="infinite_scroll">
    <ul class="themes" id="available-themes-container"></ul>
    <div class="theme-loader">
        <img src="<?php echo $this->getViewFileUrl('images/ajax-loader-tr.gif') ?>"/>
    </div>
</div>

<script type="text/javascript">
    (function ($) {
        $( document ).ready(function( ) {
            <?php if ($this->getTabId()): ?>
                $('.infinite_scroll').infinite_scroll({
                    url : '<?php echo $this->getUrl('*/*/loadthemelist') ?>',
                    loadDataOnCreate : false
                });
                $('.infinite_scroll').infinite_scroll('setLocked', true);

                $('a[name="<?php echo $this->getTabId() ?>"]').on("click", function(event) {
                    $('.infinite_scroll').infinite_scroll('setLocked', false);
                    $('.infinite_scroll').infinite_scroll('loadDataIsContainerEmpty');
                });
            <?php endif; ?>
        });
    })(jQuery);
</script>

<section class="vde-tools hidden">
    <header class="vde-tools-header">
        <div class="vde-tools-header-inner">
            <button class="action-close" title="<?php echo $this->__('Close Panel'); ?>">
                <span><?php echo $this->__('Close Panel'); ?></span>
            </button>
        </div>
    </header>
    <div class="vde-tools-content">
        <div class="vde-tools-content-inner">
            <div class="vde-tools-handler-container"></div>
            <div class="vde-tab-content tab-panel active" id="vde-tab-design">
                <div class="vde-tab-content-header">
                    <h4 class="vde-tab-content-title"><?php echo $this->__('Design'); ?></h4>

                    <div class="vde-tools-tabs">
                        <ul class="vde-tab-controls">
                            <li class="item active"><a href="#vde-tab-css" data-toggle="tab"><?php echo $this->__('Css'); ?></a></li>
                            <li class="item"><a href="#vde-tab-js" data-toggle="tab"><?php echo $this->__('JS'); ?></a></li>
                            <li class="item"><a href="#vde-tab-custom" data-toggle="tab"><?php echo $this->__('Custom'); ?></a></li>
                        </ul>
                    </div>
                </div>
                <div class="vde-tab-content-inner">
                    <div class="vde-tab-data">
                        <div class="vde-code-tab tab-panel active" id="vde-tab-css">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        </div>
                        <div class="vde-code-tab tab-panel" id="vde-tab-js">js Tab</div>
                        <div class="vde-code-tab tab-panel" id="vde-tab-custom">custom Tab</div>
                    </div>
                </div>
            </div>
            <div class="vde-tab-content tab-panel" id="vde-tab-block">
                <div class="vde-tab-content-header">
                    <h4 class="vde-tab-content-title"><?php echo $this->__('Block'); ?></h4>
                </div>
                <div class="vde-tab-content-inner">
                    <div class="vde-tab-data">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Lorem
                        Design Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Design Lorem isum dolor sit amet, t amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </div>
                </div>
            </div>
            <div class="vde-tab-content tab-panel" id="vde-tab-settings">
                <div class="vde-tab-content-header">
                    <h4 class="vde-tab-content-title"><?php echo $this->__('Settings'); ?></h4>
                </div>
                <div class="vde-tab-content-inner">
                    <div class="vde-tab-data">
                        Design Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Design Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Design rem ipsum dolor sit aet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Design Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        Design Lorem ipsum dolor sit amet, t amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </div>
                </div>
            </div>
            <div class="vde-tab-content tab-panel" id="vde-tab-code">
                <div class="vde-tab-content-header">
                    <h4 class="vde-tab-content-title"><?php echo $this->__('Scripts'); ?></h4>
                </div>
                <div class="vde-tab-content-inner">
                    <div class="vde-tab-data">
                        Design Lorem ipsum dolor sit amet, t amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="vde-tools-footer">
        <div class="vde-tools-tabs">
            <ul class="vde-tab-controls">
                <li class="item item-design active">
                    <a href="#vde-tab-design" data-toggle="tab" title="<?php echo $this->__('Design'); ?>">
                        <span><?php echo $this->__('Design'); ?></span>
                    </a>
                </li>
                <li class="item item-block">
                    <a href="#vde-tab-block" data-toggle="tab" title="<?php echo $this->__('Block'); ?>">
                        <span><?php echo $this->__('Block'); ?></span>
                    </a>
                </li>
                <li class="item item-settings">
                    <a href="#vde-tab-settings" data-toggle="tab" title="<?php echo $this->__('Settings'); ?>">
                        <span><?php echo $this->__('Settings'); ?></span>
                    </a>
                </li>
                <li class="item item-code">
                    <a href="#vde-tab-code" data-toggle="tab" title="<?php echo $this->__('Code'); ?>">
                        <span><?php echo $this->__('Code'); ?></span>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
</section>

<script type="text/javascript">
    (function($) {
        'use strict';

        $.widget('vde.toolsPanel', {
            options: {
                resizableArea: '.vde-tools-content',
                resizableAreaInner: '.vde-tab-content.active .vde-tab-content-inner',
                panelHeader: '.vde-tab-content-header',
                panelTab: 'a[data-toggle="tab"]',
                resizeHandlerControl: '.ui-resizable-handle',
                resizeHandlerControlContainer: '.vde-tools-handler-container',
                scrollExistClass: 'hasScroll'
            },

            _create: function() {
                this.resizableArea = $(this.options.resizableArea);
                this.resizableAreaInner = $(this.options.resizableAreaInner);
                this.panelTab = $(this.options.panelTab);
                this.resizeHandlerControlContainer = $(this.options.resizeHandlerControlContainer);
                this.panelHeaderHeight = $(this.options.panelHeader).height();

                this._events();
            },

            _init: function() {
                $(this.options.resizeHandlerControl).prependTo(this.resizeHandlerControlContainer);
                this._recalcDataHeight();
            },

            _events: function() {
                var self = this;

                this.resizableArea
                    .resizable({
                        handles: 'n',
                        resize: function(event, ui) {
                            self._recalcDataHeight(this, ui.size.height);
                        }
                    }).bind('resize.vdeToolsResize', function () {
                        self._recalcDataHeight(this, $(this).height());
                        $(this).css("top", "auto");
                    });

                this.panelTab
                    .on('shown', function (e) {
                        self.resizableArea.trigger('resize.vdeToolsResize');
                    });
            },

            _checkIsScrollBarExist: function(elem) {
                elem.toggleClass(this.options.scrollExistClass, elem.get(0).scrollHeight > elem.height());
            },

            _recalcDataHeight: function(parent, height) {
                var elem = $('.vde-tab-content.active .vde-tab-content-inner', parent);

                elem.height(height - this.panelHeaderHeight);
                this._checkIsScrollBarExist(elem);
            }
        });

        $('.vde-tools').toolsPanel();

    })(window.jQuery);
</script>