<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme_Selector_List_Available */?>

<div class="entry-edit">
    <div class="infinite_scroll">
        <ul id="theme-container" class="theme-container"></ul>
        <div class="theme-loader">
            <img src="<?php echo $this->getViewFileUrl('images/ajax-loader-tr.gif') ?>"/>
        </div>
    </div>
</div>
<script type="text/javascript">
    (function ($) {
        $( document ).ready(function( ) {
            <?php if ($this->getTabId()): ?>
                $('.infinite_scroll').infinite_scroll({
                    url : '<?php echo $this->getUrl('*/*/loadthemelist') ?>',
                    loadDataOnCreate : false
                });
                $('.infinite_scroll').infinite_scroll('setLocked', true);

                $('a[name="<?php echo $this->getTabId() ?>"]').on("click", function(event) {
                    $('.infinite_scroll').infinite_scroll('setLocked', false);
                    $('.infinite_scroll').infinite_scroll('loadDataIsContainerEmpty');
                });
            <?php endif; ?>

            $( 'body' ).themeSelector(<?php echo $this->getOptionsJson(); ?>);
        });
    })(jQuery);
</script>
