<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme_Selector_List_Available */?>

<div class="entry-edit">
    <div class="infinite_scroll">
        <ul class="theme-container" />
    </div>
</div>

<script type="text/javascript">
    jQuery('.infinite_scroll').infinite_scroll({url :'<?php echo $this->getUrl('*/*/loadthemelist') ?>'});
    (function ($) {
        $( document ).ready(function( ) {
            $( 'body' ).themeSelector(<?php echo $this->getOptionsJson(); ?>);
        });
    })(jQuery);
</script>
