<div id="invoice_items_grid">
    <div class="grid">
        <table cellspacing="0" class="data" id="invoice_items_grid_table">
            <thead>
                <tr class="headings">
                    <th class="no-link"><nobr><?=__('Product ID')?></nobr></th>
                    <th class="no-link"><nobr><?=__('SKU')?></nobr></th>
                    <th class="no-link"><nobr><?=__('Product Name')?></nobr></th>
                    <th class="no-link"><nobr><?=__('Qty Shipped')?></nobr></th>
                </tr>
            </thead>
            <tbody>
                <?$_items = $this->getInvoice()->getItemsCollection()?>
                <?foreach ($_items as $_item):?>
                    <tr>
                        <td class="a-center"><em><small><?=$_item->getId()?> <?=$_item->getOrderItemId()?></small></em> <?=$_item->getProductId()?></td>
                        <td><?=$_item->getSku()?></td>
                        <td><?=$_item->getName()?></td>
                        <td><?=$_item->getQty()?></td>
                    </tr>
                <?endforeach;?>
            </tbody>
        </table>
    </div>
</div>