<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $_item = $this->getItem();
    $canApplyMsrp = Mage::helper('Magento_Catalog_Helper_Data')->canApplyMsrp($_item->getProduct(), Magento_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
    $messages = $this->getMessages();
    $_options = $this->getOptionList();
    $links = $this->getLinks();
?>
<?php if ($messages): ?>
<tr class="messages">
    <td colspan="2">
        <?php foreach ($messages as $message): ?>
        <div class="shopping-cart-item-message <?php echo $message['type'] ?>">
            * <?php echo $this->escapeHtml($message['text']) ?>
        </div>
        <?php endforeach; ?>
    </td>
</tr>
<?php endif; ?>
<tr>
    <td>
        <a href="<?php echo $this->getProductUrl() ?>" class="product-image" title="<?php echo $this->escapeHtml($this->getProductName()) ?>">
            <img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
        </a>

        <a class="link-edit" href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo __('Edit item parameters') ?>"><?php echo __('Edit') ?></a>
    </td>

    <td>
        <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo __('Remove Item')?>" class="btn-remove btn-remove2"><?php echo __('Remove Item') ?></a>

        <h2 class="product-name"><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a></h2>

        <div class="price-box">

            <div class="qty-wrap">
                <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo __('Qty') ?>" class="input-text qty" maxlength="12" />
                <span<?php if ($this->getQty() == 1) echo ' style="display:none;"' ?>>×</span>
            </div>

            <div class="cart-price-box"<?php if ($this->getQty() == 1) echo ' style="display:none;"' ?>>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-price">
                        <span class="cart-msrp-unit"><?php echo __('See price before order confirmation.'); ?></span>
                        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                        <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo __("What's this?"); ?></a>
                        <?php $_product = $_item->getProduct(); ?>
                        <script type="text/javascript">
                            (function ($) {
                                head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/msrp.js') ?>", function () {
                                    $('#<?php echo $helpLinkId ?>').addToCart({
                                        popupId: "#<?php echo $helpLinkId ?>",
                                        productName: '<?php echo $_product->getName() ?>',
                                        realPrice: '<?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getCalculationPrice()) ?>',
                                        msrpPrice: '<?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_product->getMsrp(),true,true) ?>',
                                        closeButtonId: '#map-popup-close',
                                        showAddToCart: false
                                    });
                                });
                            })(jQuery);
                        </script>
                    </span>
                <?php else: ?>

                    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceExclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>

                        <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <?php else: ?>
                            <span class="cart-price">
                        <?php endif; ?>
                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
                            <?php else: ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getCalculationPrice()) ?>
                            <?php endif; ?>

                        </span>


                        <?php if (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>

                            <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>

                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                    <span class="weee"><?php echo __('Total'); ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>

                    <?php endif; ?>
                    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceInclTax()): ?>

                        <?php $_incl = Mage::helper('Magento_Checkout_Helper_Data')->getPriceInclTax($_item); ?>
                        <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <?php else: ?>
                            <span class="cart-price">
                        <?php endif; ?>

                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
                            <?php else: ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                            <?php endif; ?>

                        </span>
                        <?php if (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>

                            <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                        <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>

                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                    <span class="weee"><?php echo __('Total incl. tax'); ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>

                    <?php endif; ?>
                <?php endif; ?>

            </div>

            <div class="cart-price-box">

                <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceExclTax() && !$_item->getNoSubtotal()): ?>

                    <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                    <?php endif; ?>

                        <?php if ($canApplyMsrp): ?>
                            <span class="cart-msrp-subtotal">--</span>
                        <?php else: ?>
                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                            <?php else: ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getRowTotal()) ?>
                            <?php endif; ?>
                        <?php endif; ?>

                    </span>
                    <?php if (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo __('Total'); ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                <?php endif; ?>

                <?php if ((Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceInclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>

                    <?php $_incl = Mage::helper('Magento_Checkout_Helper_Data')->getSubtotalInclTax($_item); ?>
                    <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                    <?php endif; ?>

                        <?php if ($canApplyMsrp): ?>
                            <span class="cart-msrp-subtotal">--</span>
                        <?php else: ?>
                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                            <?php else: ?>
                                <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                            <?php endif; ?>
                        <?php endif; ?>

                    </span>


                    <?php if (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['row_amount'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo __('Total incl. tax'); ?>: <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>

                <?php endif; ?>

            </div>

        </div>

        <!-- downloadable -->
        <?php if ($links): ?>
        <div class="downloadable">
            <dl class="item-options">
                <dt><?php echo $this->getLinksTitle() ?></dt>
                <?php foreach ($links as $link): ?>
                    <dd><?php echo $this->escapeHtml($link->getTitle()); ?></dd>
                <?php endforeach; ?>
            </dl>
        </div>
        <?php endif; ?>
        <!-- EOF downloadable -->

    </td>
</tr>
<?php if ($_options):?>
<tr class="product-options">
    <td colspan="2">
        <span class="toggle" onclick="$(this).next().toggle(); return false;">Show Options</span>
        <div class="product-options" style="display:none;">
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    <?php else: ?>
                        <dd><?php echo $_formatedOptionValue['value'] ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        </div>
    </td>
</tr>
<?php endif;?>
