<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            toggleGiftCard: [
                '<?php echo $this->getViewFileUrl('Magento_GiftCard::toggle-gift-card.js')?>'
            ]
        });
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>
