<div class="head">
    <table cellspacing="0" class="content_table">
        <tr>
            <td style="width:30%;"><h2><?=$header?></h2></td>
            <td class="buttons">
                <strong class="button"><span><a href="#" onclick="customerForm.submit();return false;"><?=__('save page')?></a></span></strong>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="page_form">
</form>
<script type="text/javascript" language="javascript">
    var customerForm = new varienForm('page_form');
</script>