<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Catalog Event category page
 *
 * @see Magento_CatalogEvent_Block_Catalog_Category_Event
 */
?>
<?php $_event = $this->getEvent(); ?>
<?php if ($this->canDisplay()): ?>
<div class="clearer"></div>
<div class="event-container container-<?php echo $_event->getStatus()?>">
<div class="event <?php echo $_event->getStatus()?>">
<strong class="status">
<?php echo $this->getStatusText($_event); ?>
</strong>
<?php switch ($_event->getStatus()):
        case 'upcoming': ?>
        <div class="event-dates">
            <p class="start">
                <strong class="date-part"><?php echo $this->getEventDate('start', $_event); ?></strong>
                <span class="time-part"><?php echo $this->getEventTime('start', $_event, 'hh a zzz'); ?></span>
            </p>
            <p class="end">
                <span class="delimiter-part">-</span>
                <strong class="date-part"><?php echo $this->getEventDate('end', $_event); ?></strong>
                <span class="time-part"><?php echo $this->getEventTime('end', $_event, 'hh a zzz'); ?></span>
            </p>
        </div>
    <?php break;
        case 'open': ?>
        <div class="event-ticker" id="event-ticker-<?php echo $_event->getId()?>" data-mage-init="{ticker: {secondsToClose: <?php echo $this->getSecondsToClose($_event); ?>}}">
            <div class="container">
                <span data-container="days" class="days">00</span><span data-container="delimiter" class="delimiter">:</span><span data-container="hour" class="hour">00</span><span data-container="delimiter" class="delimiter">:</span><span data-container="minute" class="minute">00</span><span data-container="delimiter" class="delimiter">:</span><span data-container="second" class="second">00</span>
            </div>
        </div>
    <?php break;
        case 'closed': ?>
        <div class="event-dates">
            <p class="start">
                <strong class="date-part"><?php echo $this->getEventDate('start', $_event); ?></strong>
                <span class="time-part"><?php echo $this->getEventTime('start', $_event, 'hh a zzz'); ?></span>
            </p>
            <p class="end">
                <span class="delimiter-part">-</span>
                <strong class="date-part"><?php echo $this->getEventDate('end', $_event); ?></strong>
                <span class="time-part"><?php echo $this->getEventTime('end', $_event, 'hh a zzz'); ?></span>
            </p>
        </div>
    <?php break; ?>
<?php endswitch; ?>
</div>
</div>
<?php endif; ?>
