<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var $this \Magento\Tax\Block\Checkout\Tax
 * @see \Magento\Tax\Block\Checkout\Tax
 */
?>
<?php
    $_value = $this->getTotal()->getValue();
    $_style = $this->getTotal()->getStyle();
?>
<?php global $taxIter; $taxIter++; ?>
<?php if ($this->helper('Magento\Tax\Helper\Data')->displayFullSummary() && $_value!=0): ?>
<?php $isTop = 1; ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
        <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
            <td class="a-right" style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->escapeHtml($rate['title']); ?>
                <?php if (!is_null($rate['percent'])): ?>
                    (<?php echo (float)$rate['percent']; ?>%)
                <?php endif; ?>
                <br />
            </td>
            <?php if ($isFirst): ?>
                <td style="<?php echo $_style ?>" class="a-right" rowspan="<?php echo count($rates); ?>">
                    <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($amount); ?>
                </td>
            <?php endif; ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif;?>
<?php
    $attributes = 'class="tax total"';
    if ($this->helper('Magento\Tax\Helper\Data')->displayFullSummary() && $_value!=0) {
        $attributes = 'class="summary-total tax total" onclick="expandDetails(this, \'.summary-details-' . $taxIter . '\')"';
    }
?>

<tr <?php echo $attributes; ?>>
    <td style="<?php echo $_style ?>" class="mark" colspan="<?php echo $this->getColspan(); ?>">
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php endif;?>
    </td>
    <td style="<?php echo $_style ?>" class="amount"><?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_value) ?></td>
</tr>
