<?
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
	"http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <link rel="icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon" ></link>
    <link rel="shortcut icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon" ></link>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>prototype/prototype.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>prototype/validation.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>scriptaculous/scriptaculous.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>varien/js.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>varien/form.js" ></script>

    <link rel="stylesheet" href="<?=$this->getSkinUrl('css/styles.css')?>" type="text/css" media="all" />
	<!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('css/iestyles.css')?>" type="text/css" media="all" /> <![endif]-->
	<!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('css/ie7.css')?>" type="text/css" media="all" /> <![endif]-->
	<!--[if lt IE 7]>
        <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>lib/ds-sleight.js" ></script>
        <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>varien/iehover-fix.js" ></script>
    <![endif]-->
	<script type="text/javascript">
	    function toggleMenu(el, over)
        {
		    if (over) {
			    Element.addClassName(el, 'over');
			}
            else {
			    Element.removeClassName(el, 'over');
			}
		}
	</script>

    <?=$this->getChildHtml('head')?>
		<link rel="stylesheet" href="css/print.css" type="text/css" media="print" />
</head>

<body>
    <!-- [start] container -->
    <div class="container">

        <!-- [start] header -->
        <div class="header">
            <?=$this->getChildHtml('header')?>
        </div>
        <!-- [end] header -->

        <!-- [start] middle -->
        <?=$this->getChildHtml('store')?>

			<div id="main" class="col-2-right-layout">

            <!-- [start] center -->
				<div class="col-main account-main">

                <!-- [start] content -->
                    <?=$this->getChildHtml('content')?>
                <!-- [end] content -->

				</div>
            <!-- [end] center -->

            <!-- [start] right -->
            <div class="col-right side-col account-side">
                <?=$this->getChildHtml('right')?>
            </div>
            <!-- [end] right -->

        </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
        <div class="footer">
            <?=$this->getChildHtml('footer')?>
        </div>
        <!-- [end] footer -->

    </div>
    <!-- [end] container -->

    </body>
</html>