<?
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
	"http://www.w3.org/TR/html4/strict.dtd">
<html lang="EN">
    <head>
        <script type="text/javascript" src="<?=$this->getJsUrl()?>js/prototype.js"></script>
        <script type="text/javascript" src="<?=$this->getJsUrl()?>js/iehover-fix.js"></script>
        <!--[if lt IE 7]><script defer type="text/javascript" src="<?=$this->getJsUrl()?>js/ds-sleight.js"></script><![endif]-->
        <style type="text/css" media="all">
        /*<![CDATA[*/ @import "<?=$this->getSkinUrl('css/styles.css')?>"; /*]]>*/
        </style>
        <!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('css/iestyles.css')?>" type="text/css" media="all" /> <![endif]-->
        <script type="text/javascript" src="<?=$this->getJsUrl()?>js/iehover-fix.js"></script>
        <!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('css/ie7.css')?>" type="text/css" media="all" /> <![endif]-->
        <?=$this->getChildHtml('head')?>
        <link rel="stylesheet" href="<?=$this->getSkinUrl('css/print.css')?>" type="text/css" media="print" />
    </head>
    <body class="page-popup">
        <h1 id="logo"><a href="<?=$this->getBaseUrl()?>"><img src="<?=$this->getSkinUrl('images/logo-print.gif')?>" alt="<?=__('Magento Commerce Demo Store')?>"/></a></h1>
        <div class="clear"></div>
        <?=$this->getChildHtml('content')?>
        <div class="clear"></div>
        <div class="form-buttons">
            <button class="form-button" onclick="window.close();"><span><?=__('Close Window')?></span></button>
        </div>
    </body>
</html>