<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Invitaion view tab status history block template
 *
 * @see Enterprise_Invitation_Block_Adminhtml_Invitation_View_Tab_History
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
            <h4 class="icon-head head-invitation"><?php echo $this->helper('Enterprise_Invitation_Helper_Data')->__('BugsCoverage History') ?></h4>
    </div>
    <div class="fieldset">
        <ul class="note-list">
        <?php foreach ($this->getHistoryCollection() as $_history): ?>
            <li>
                <strong><?php echo $this->formatDate($_history->getInvitationDate(), 'medium') ?></strong>
                <?php echo $this->formatTime($_history->getInvitationDate(), 'medium') ?><span class="separator">|</span>
                <strong><?php echo $_history->getStatusText()?></strong>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<div class="clear"></div>
