<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <script type="text/javascript" src="<?=$baseJsUrl?>extjs/adapter/yui/yui-utilities.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>extjs/adapter/yui/ext-yui-adapter.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>extjs/ext-all.js"></script>
    <script type="text/javascript">

        Ext.BLANK_IMAGE_URL = '<?=$baseJsUrl?>extjs/resources/images/default/s.gif';
        Ext.UpdateManager.defaults.loadScripts = false;
        Ext.UpdateManager.defaults.disableCaching = true;

        top.frames.contentFrame.location.href = '<?=$baseUrl?>adminhtml/index/layoutFrame/';
    </script>
</head>
<body>

</body>
</html>