<div class="page-head">
    <h3><?=__('All Tags')?></h3>
</div>
<div class="box base-mini mini-product-tags">
    <div class="content">
        <?if( sizeof($this->getTags()) > 0 ):?>
        <ul>
            <?foreach ($this->getTags() as $_tag):?>
                <li><a href="<?=$_tag->getTaggedProductsUrl()?>" style="font-size:<?=$_tag->getRatio()*70+75?>%;"><?=$_tag->getName()?></a></li>
            <?endforeach;?>
        </ul>
        <?else:?>
        <center><small><?=__('Tags Not Avaliable')?></small></center>
        <?endif;?>
    </div>
</div>