<div class="page-head">
	<h3>Products tagged with '<?=$query;?>' (<a href="/tag/index/xml?tag=<?=$query;?>">rss</a>)</h3>
</div>
<?php if (!empty($collection)) {?>
<ol>
<?php foreach ($collection as $item) { ?>
	<li>
		<?=$item['name'];?>
		<strong>Tags:</strong>
			<?php foreach ($item['tags'] as $tag) { ?>
				<A href="/tag/index/search?q=<?=$tag['tagname'];?>"><?=$tag['tagname'];?></a> 
			<?php } ?>
	</li>
<?php } ?>
</ol>
<?php } ?>