					<div class="box popular-tags">
						<div class="head">
							<h3><span>Popular tags</span></h3>
						</div>
						<div class="content">
							<ul>
								<li><a href="#" style="font-size:100%;">lorem</a></li>
								<li><a href="#" style="font-size:123.12%;">lorem</a></li>
								<li><a href="#" style="font-size:200.23%;">lorem</a></li>
								<li><a href="#" style="font-size:120%;">lorem</a></li>
								<li><a href="#" style="font-size:50%;">lorem</a></li>
								<li><a href="#" style="font-size:40%;">lorem</a></li>
								<li><a href="#" style="font-size:120%;">lorem</a></li>
								<li><a href="#" style="font-size:110%;">lorem</a></li>
								<li><a href="#" style="font-size:250.12%;">lorem</a></li>
								<li><a href="#" style="font-size:50%%;">lorem</a></li>
								<li><a href="#" style="font-size:100%;">lorem</a></li>
								<li><a href="#" style="font-size:123.12%;">lorem</a></li>
								<li><a href="#" style="font-size:200.23%;">lorem</a></li>
								<li><a href="#" style="font-size:120%;">lorem</a></li>
								<li><a href="#" style="font-size:50%;">lorem</a></li>
								<li><a href="#" style="font-size:40%;">lorem</a></li>
								<li><a href="#" style="font-size:120%;">lorem</a></li>
								<li><a href="#" style="font-size:110%;">lorem</a></li>
								<li><a href="#" style="font-size:250.12%;">lorem</a></li>
								<li><a href="#" style="font-size:50%%;">lorem</a></li>
							</ul>
						</div>
					</div>
<!-- [ends] .popular-tags // -->

