<?if($poll) :?>
<?$_poll = $poll->getPoll();?>
<div class="box mini-poll">
	<div class="head"> <!-- Gives room for control buttons -->
		<h3><span>Today's Poll</span></h3>
	</div>
    <form name="pollForm" action="<?=$action?>" method="post">
	<h4><?=$_poll['poll_title'];?></h4>
    <?if( is_array($poll->getAnswers()) ):?>
	    <table cellspacing="0">
		    <tbody>
            <?foreach( $poll->getAnswers() as $answer ):?>
			    <tr>
				    <td><input type="radio" name="vote" value="<?=$answer['answer_id']?>"/></td>
				    <td><?=$answer['answer_title']?>&nbsp;</td>
			    </tr>
            <?endforeach;?>
		    </tbody>
	    </table>
    <?endif;?>
    </form>
	<div class="actions">
		<button class="form-button" onclick="pollForm.submit()"><span>Vote</span></button>
	</div>
</div>
<?endif;?>
<!-- [ends] .mini-poll // -->

