<?if($poll) :?>
<?$_poll = $poll->getPoll();?>
     <div class="catalog-nav">
        <form name="pollForm" action="<?=$action?>" method="post">
            <h2>Active Poll</h2>
            <?=$_poll['poll_title'];?><br />
            <?if( is_array($poll->getAnswers()) ):?>
                    <?foreach( $poll->getAnswers() as $answer ):?>
                    <label><input type="radio" name="vote" value="<?=$answer['answer_id']?>" />&nbsp;<?=$answer['answer_title']?></label><br />
                    <?endforeach;?>
            <?endif;?>
            <input value="Submit" alt="Subscribe" class="input-button" type="submit">
        </form>
    </div>
<?endif;?>
