<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChildBlock('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
    <?php echo $this->getPriceHtml($product, empty($options));?>
    <div class="box tocart">
        <?php if ($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()): ?>
            <input type="text" class="input-text qty" data-validate="{required:true,'validate-greater-than-zero':true}" name="qty[<?php echo $item->getId() ?>]"
                   value="<?php echo $this->getAddToCartQty($item) * 1 ?>"/>
        <?php endif; ?>
        <?php if ($product->isSaleable()): ?>
            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" data-item-id="<?php echo $item->getId()?>" class="action tocart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
        <?php else: ?>
            <?php if ($product->getIsSalable()): ?>
                <p class="available stock" title="<?php echo $this->__('Availability') ?>"><span><?php echo $this->__('In stock') ?></span></p>
            <?php else: ?>
                <p class="unavailable stock" title="<?php echo $this->__('Availability') ?>"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php foreach ($this->getChildNames() as $childName): ?>
        <?php echo $this->getLayout()->renderElement($childName, false); ?>
    <?php endforeach;?>
    <?php if ($product->isVisibleInSiteVisibility()): ?>
        <p><a class="action edit" href="<?php echo $this->getItemConfigureUrl($item) ?>"><span><?php echo $this->__('Edit') ?></span></a>
    </p>
    <?php endif ?>

