<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$imageBlock =  $this->getLayout()->createBlock('Mage_Catalog_Block_Product_Image');
?>
<a class="product photo" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
    <?php echo $imageBlock->init($product, 'wishlist_thumbnail')->toHtml() ?>
</a>
