<?=$this->getMessagesBlock()->getGroupedHtml()?>
<form action="<?=$this->getSendUrl()?>" id="form-validate" method="POST">
	 <fieldset class="group-select">
     <legend><?=__('Sharing Information')?></legend>
        <h3><?=__('Sharing Information')?></h3>
        <ul>
            <li>
                <label for="email_address"><?=__('Email Addresses, separated by comma')?> <span class="required">*</span></label><br/>
                <textarea name="email" class="validate-emails required-entry input-text"><?=$this->getEnteredData('email')?></textarea>
            </li>
            <li>
                <label for="email_address"><?=__('Message')?></label><br/>
                <textarea name="message" class="input-text"><?=$this->getEnteredData('message')?></textarea>
            </li>
        </ul>

    </fieldset>
    <div class="buttons-container">
            <p class="required"><?=__('* Required Fields')?></p>
            <input type="submit" class="input-button" value="<?=__('Share Wishlist')?>"/>
    </div>
</form>
<script type="text/javascript">
<!--
Validation.addAllThese([
	['validate-emails', '<?=__('Please enter a valid email addresses, separated by comma. For example johndoe@domain.com, johnsmith@domain.com.')?>', function (v) {
                if(Validation.get('IsEmpty').test(v)) {
                	return true;
                }
                
                var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/;
                var emails = v.split(',');
                
                for (var i=0; i<emails.length; i++) {
                	if(!valid_regexp.test(emails[i].strip())) {
                		return false;
                	}
                }
                
                return true;
            }],
]);
var dataForm = new VarienForm('form-validate', true);
//-->
</script>
