<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_DesignEditor_Block_Adminhtml_Editor_Tools_Code_Css_Group */ ?>

<div class="files-list">
    <div class="files-list-header">
        <h5 class="title" title="<?php echo $this->escapeHtml($this->getTitle()) ?>"><?php echo $this->getTitle() ?></h5>
        <?php if ($this->hasAddButton()): ?>
            <a href="#vde-tab-custom" class="action-add" data-toggle="tab" title="<?php echo __('Add Custom'); ?>">
                <span><?php echo __('Add Custom'); ?></span>
            </a>
        <?php endif ?>
    </div>
    <div class="files-list-content">
        <ul class="items">
            <?php foreach ($this->getFiles() as $file): ?>
                <li class="item">
                    <span class="filename" title="<?php echo $file['safePath'] ?>"><?php echo $file['id'] ?></span>
                    <?php if ($this->hasDownloadButton()): ?>
                        <a href="<?php echo $this->getDownloadUrl($file['id'], $this->getThemeId()) ?>" class="action-download" title="<?php echo __('Download file'); ?>">
                            <span><?php echo __('Download file'); ?></span>
                        </a>
                    <?php endif ?>
                    <!--
                    placeholder for "Edit button"
                    <a href="#vde-tab-custom" class="action-edit" title="<?php echo __('Edit Custom CSS'); ?>">
                        <span><?php echo __('Edit Custom CSS'); ?></span>
                    </a>
                    -->
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
