<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var \Magento\Tax\Pricing\Render\Adjustment $this */ ?>
<?php if ($this->displayPriceIncludingTax()): ?>
    <?php echo $this->getDisplayAmount() ?>
<?php elseif ($this->displayPriceExcludingTax()): ?>
    <?php echo $this->getDisplayAmountExclTax() ?><
<?php elseif ($this->displayBothPrices()): ?>
    <?php echo $this->getDisplayAmountExclTax() ?>
    <?php if ($this->getDisplayAmountExclTax() !== $this->getDisplayAmount()): ?>
        (+<?php echo $this->getDisplayAmount() ?> Incl. Tax)
    <?php endif; ?>
<?php endif; ?>
