<script data-mage-init='{ "Magento_Ui/js/initializer/main": "" }' type="application/json">
    {
        "providers": {
            "customer_form_data": {
                "path": "Magento_Ui/js/form/provider/provider",
                "meta": {

                    "customer": {
                        "website": {
                            "index": "website",
                            "data_type": "text",
                            "input_type": "select",
                            "label": "Associate to Website",
                            "caption": "Please select ...",
                            "required": true,
                            "options": [
                                {"label":"Admin Website","value":"0"},
                                {"label":"Main Website","value":"1"}
                            ]
                        },
                        "currencies": {
                            "index": "currencies",
                            "input_type": "multiple_select",
                            "label": "Currencies",
                            "options": [
                                {"value":"dut","label": "Dutch money"},
                                {"value":"ua","label": "Ukraine money"},
                                {"value":"usa","label": "USA money"},
                                {"value":"yo","label": "Yo money"},
                                {"value":"sup","label": "Sup money"},
                                {"value":"wow","label": "Wow money"}
                            ]
                        },
                        "gender": {
                            "index": "gender",
                            "data_type": "text",
                            "input_type": "select",
                            "label": "Gender",
                            "no_caption": true,
                            "required": true,
                            "options": [
                                {"value":"0","label": "Male"},
                                {"value":"1","label": "Female"}
                            ]
                        },
                        "general": {
                            "index": "general",
                            "data_type": "text",
                            "input_type": "select",
                            "options": [
                                {"value":"0","label": "General"},
                                {"value":"1","label": "Wholesale"},
                                {"value":"2","label": "Retailer"}
                            ]
                        },
                        "prefix": {
                            "index": "prefix",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "Prefix",
                            "validation": {
                                "required-entry": true,
                                "no-whitespace": true
                            }
                        },
                        "firstname": {
                            "index": "firstname",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "First Name",
                            "required": true
                        },
                        "middle_name": {
                            "index": "middle_name",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "Middle Name/Initial"
                        },
                        "lastname": {
                            "index": "lastname",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "Last Name",
                            "required": true
                        },
                        "suffix": {
                            "index": "suffix",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "Suffix"
                        },
                        "email": {
                            "index": "email",
                            "data_type": "text",
                            "input_type": "email",
                            "label": "Email Address",
                            "required": true
                        },
                        "taxvat": {
                            "index": "taxvat",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "Tax/VAT Number"
                        },
                        "price": {
                            "index": "price",
                            "type": "price",
                            "data_type": "price",
                            "input_type": "price",
                            "currency_sign": "$",
                            "label": "Price / currency fireld"
                        },
                        "send_email": {
                            "index": "send_email",
                            "data_type": "boolean",
                            "input_type": "checkbox",
                            "label": "Send Welcome Email"
                        },
                        "disable_auto":{
                            "index": "disable_auto",
                            "data_type": "boolean",
                            "input_type": "checkbox",
                            "description": "Disable Automatic Group Change Based on VAT ID"
                        },
                        "comments": {
                            "input_type": "textarea",
                            "label": "Comments",
                            "index": "comments"
                        },
                        "created": {
                            "index": "created",
                            "input_type": "date",
                            "label": "Created",
                            "options": {
                                "dateFormat": "mm\/dd\/yyyy",
                                "showsTime": false,
                                "timeFormat": null,
                                "buttonImage": "/pub/static/adminhtml/Magento/backend/en_US/images/grid/cal.gif",
                                "buttonText": "Select Date"
                            }
                        },
                        "image": {
                            "index": "image",
                            "input_type": "media",
                            "label": "Image"
                        }
                    }
                },
                "data": {
                    "customer": {
                        "prefix": "Mr.",
                        "website": 0,
                        "gender": 0,
                        "currencies": ["dut", "ua"],
                        "price": "123.45",
                        "send_email": true,
                        "disable_auto": false,
                        "general": 0,
                        "comments": "Some commentary",
                        "created": 1412244384313
                    }
                }
            }
        },

        "components": {
            "customer_form_tabs": {
                "name": "customer_form_tabs",
                "path": "Magento_Ui/js/form/components/tab/group",
                "source": "customer_form_data",
                "config": {
                    "some_form_config": "blabla"
                }
            },
            "customer_form_areas": {
                "name": "customer_form_areas",
                "path": "Magento_Ui/js/form/components/area",
                "source": "customer_form_data",
                "config": {
                    "some_form_config": "blabla"
                }
            },
            "customer_form_fieldsets": {
                "name": "customer_form_fieldsets",
                "path": "Magento_Ui/js/form/components/fieldset",
                "source": "customer_form_data",
                "config": {
                    "some_form_config": "blabla"
                }
            },
            "customer_form_groups":{
                "name": "customer_form_groups",
                "path": "Magento_Ui/js/form/components/group",
                "source": "customer_form_data"
            },
            "customer_form_form": {
                "name": "customer_form_form",
                "path": "Magento_Ui/js/form",
                "source": "customer_form_data"
            }
        },

        "layout": { 
            "customer_form_tabs": {
                    "cusomer_info": {
                        "label": "Customer Information",
                        "items": [
                            {
                                "name": "account_info",
                                "active": true,
                                "label": "Account Information"
                            },
                            {
                                "name": "customer_addresses",
                                "label": "Addresses"
                            }
                        ]
                    },
                    "col_group": {
                        "label": "Collapsible group",
                        "collapsible": true,
                        "items": [
                            {
                                "name": "prod_details",
                                "label": "Advanced Pricing"
                            },
                            {
                                "name": "col_options",
                                "label": "Custom Options"
                            }
                        ]
                    }
            },
            "customer_form_areas": {
                    "account_info": {
                        "injections": [
                            "customer_form_fieldsets.account_info"
                        ]
                    },
                    "customer_addresses": {
                        "injections": [
                            "customer_form_fieldsets.customer_addresses"
                        ]
                    }
            },
            "customer_form_groups": {
                    "website": {
                        "injections": [
                            "customer.website"
                        ]
                    },
                    "group": {
                        "breakLine": true,
                        "label": "General",
                        "injections": [
                            "customer.general",
                            "customer.disable_auto"
                        ]
                    },
                    "prefix": {
                        "injections": [
                            "customer.prefix"
                        ]
                    },
                    "firstname": {
                        "injections": [
                            "customer.firstname"
                        ]
                    },
                    "middle_name": {
                        "injections": [
                            "customer.middle_name"
                        ]
                    },
                    "lastname": {
                        "injections": [
                            "customer.lastname"
                        ]
                    },
                    "suffix": {
                        "injections": [
                            "customer.suffix"
                        ]
                    },
                    "email": {
                        "type": "email",
                        "injections": [
                            "customer.email"
                        ]
                    },
                    "taxvat": {
                        "injections": [
                            "customer.taxvat"
                        ]
                    },
                    "gender": {
                        "injections": [
                            "customer.gender"
                        ]
                    },
                    "price": {
                        "type": "price",
                        "injections": [
                            "customer.price"
                        ]
                    },
                    "send_email": {
                        "injections": [
                            "customer.send_email"
                        ]
                    },
                    "currencies": {
                        "injections": [
                            "customer.currencies"
                        ]
                    },
                    "comments": {
                        "injections": [
                            "customer.comments"
                        ]
                    },
                    "created": {
                        "injections": [
                            "customer.created"
                        ]
                    },
                    "image": {
                        "injections": [
                            "customer.image"
                        ]
                    }
            },
            "customer_form_fieldsets": {
                    "account_info": {
                        "label": "Account Information",
                        "collapsible": true,
                        "injections": [
                            "customer_form_groups.website",
                            "customer_form_groups.group",
                            "customer_form_groups.prefix",
                            "customer_form_groups.price",
                            "customer_form_groups.firstname",
                            "customer_form_groups.middle_name",
                            "customer_form_groups.lastname",
                            "customer_form_groups.suffix",
                            "customer_form_groups.email",
                            "customer_form_groups.taxvat",
                            "customer_form_groups.gender",
                            "customer_form_groups.send_email",
                            "customer_form_groups.currencies",
                            "customer_form_groups.comments",
                            "customer_form_groups.created",
                            "customer_form_groups.image"
                        ]
                    },
                    "customer_addresses": {
                        "label": "Customer Addresses",
                        "injections": [
                            "customer_form_groups.firstname",
                            "customer_form_groups.middle_name",
                            "customer_form_groups.lastname",
                            "customer_form_groups.suffix",
                            "customer_form_groups.email",
                            "customer_form_groups.taxvat",
                            "customer_form_groups.gender"
                        ]
                    },
                    "prod_details": {
                        "label": "Product Details",
                        "collapsible": true,
                        "injections": [
                            "customer_form_groups.firstname",
                            "customer_form_groups.email",
                            "customer_form_groups.taxvat",
                            "customer_form_groups.gender",
                            "customer_form_groups.currencies",
                            "customer_form_groups.comments",
                            "customer_form_groups.created"
                        ]
                    },
                    "col_options": {
                        "label": "Custom Options",
                        "injections": [
                            "customer_form_groups.taxvat",
                            "customer_form_groups.gender",
                            "customer_form_groups.currencies"
                        ]
                    }
            }
        }
    }
</script>
<script>
    var allowLocalCache = false;
</script>

    <div data-bind="scope: 'customer_form_areas'" class="entry-edit form-inline">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
