<script data-mage-init='{ "Magento_Ui/js/initializer/main": "" }' type="application/json">
    {
        "providers": {
            "customer_form_data": {
                "path": "Magento_Ui/js/form/provider/provider",
                "meta": {
                    "customer": {
                        "website": {
                            "index": "website",
                            "data_type": "text",
                            "input_type": "select",
                            "label": "Associate to Website",
                            "options": {
                                "0": "Please select ...",
                                "1": "Admin"
                            }
                        },
                        "firstname": {
                            "index": "firstname",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "First Name"
                        },
                        "lastname": {
                            "index": "lastname",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "Last Name"
                        },
                        "addresses": {
                            "meta_ref": "address",
                            "data_type": "collection",
                            "input_type": "",
                            "label": "Addresses",
                            "meta": {
                                "ref": "address"
                            }
                        }
                    },
                    "address": {
                        "prefix": {
                            "index": "prefix",
                            "data_type": "text",
                            "input_type": "input",
                            "label": "Prefix"
                        }
                    }
                },
                "data": {
                    "customer": {
                        "website": 0,
                        "addresses": {
                            "prefix": "Mr.",
                            "suffix": "Sr.",
                            "firstname": "Misha"
                        }
                    }
                }
            }
        },

        "components": {
            "customer_form_tabs": {
                "name": "customer_form_tabs",
                "path": "Magento_Ui/js/tab/group",
                "source": "customer_form_data",
                "config": {
                    "some_form_config": "blabla"
                }
            },
            "customer_form_areas": {
                "name": "customer_form_areas",
                "path": "Magento_Ui/js/area/area",
                "source": "customer_form_data",
                "config": {
                    "some_form_config": "blabla"
                }
            },
            "customer_form_fieldsets": {
                "name": "customer_form_fieldsets",
                "path": "Magento_Ui/js/fieldset/fieldset",
                "source": "customer_form_data",
                "config": {
                    "some_form_config": "blabla"
                }
            }
        },

        "layout": { 
            "customer_form_tabs": {
                "items": {
                    "cusomer_info": {
                        "label": "Customer Information",
                        "items": [
                            {
                                "name": "account_info",
                                "active": true,
                                "label": "Account Information"
                            },
                            {
                                "name": "customer_addresses",
                                "label": "Addresses"
                            }
                        ]
                    },
                    "col_group": {
                        "label": "Collapsible group",
                        "collapsible": true,
                        "items": [
                            {
                                "name": "prod_details",
                                "label": "Advanced Pricing"
                            },
                            {
                                "name": "col_options",
                                "label": "Custom Options"
                            },
                            {
                                "name": "auto_settings",
                                "label": "Autosettings"
                            }
                        ]
                    }
                }
            },
            "customer_form_areas": {
                "items": {
                    "account_info": {
                        "injections": [
                            "customer_form_fieldsets.account_info"
                        ]
                    },
                    "customer_addresses": {
                        "injections": [
                            "customer_form_fieldsets.customer_addresses"
                        ]
                    }
                }
            },
            "customer_form_fieldsets": {
                "items": {
                    "account_info": {
                        "label": "Account Information",
                        "collapsible": false
                    },
                    "customer_addresses": {
                        "label": "Customer Addresses",
                        "collapsible": true
                    }
                }
            }
        }
    }
</script>
<script>
    var allowLocalCache = true;
</script>

<div data-bind="scope: 'customer_form_areas' " class="entry-edit form-inline">
    <form action="" method="post">
        
        <!-- ko foreach: elems -->
        <div data-bind="visible: visible">
            
            <!-- ko foreach: elems -->
                <!-- ko template: template --><!-- /ko -->
            <!-- /ko -->

        </div>
        <!-- /ko -->

    </form>
</div>