<?php echo $this->template('header.phtml') ?>

<h2 class="page-head">Global Install/Upgrade</h2>

<fieldset>
<?php if ($this->controller()->session()->getUserId()): ?>
    <button onclick="upgradeAll()">Upgrade All Available Packages</button>
<?php else: ?>
    <button onclick="installAll()">Install All Magento Core Packages</button>
<?php endif; ?>
</fieldset>
<br/>
<?php echo $this->template('pear/iframe.phtml') ?>
<a name="pear_iframe_result"></a>
<div id="pear_iframe_success" style="display:none">
    <?php $this->set('messages', array('success'=>array('Procedure completed. Please check the output frame for usefull information and refresh the page to see changes.'))) ?>
    <?php echo $this->template('messages.phtml') ?>
</div>
<div id="pear_iframe_failure" style="display:none">
    <?php $this->set('messages', array('error'=>array('There was a problem during downloading of Magento packages. Please check the output frame for errors information and refresh the page to retry again.'))) ?>
    <?php echo $this->template('messages.phtml') ?>
</div>

<script type="text/javascript">
function installAll()
{
    $('pear_iframe').style.display = '';
    $('pear_iframe').src = '<?php echo $this->url('pearInstallAll') ?>';
}

function reinstallAll()
{
    $('pear_iframe').style.display = '';
    $('pear_iframe').src = '<?php echo $this->url('pearInstallAll') ?>&force=1';
}

function upgradeAll()
{
    $('pear_iframe').style.display = '';
    $('pear_iframe').src = '<?php echo $this->url('pearUpgradeAll') ?>';
}
</script>
<?php echo $this->template('footer.phtml') ?>

