<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product additional attributes template
 *
 * @var $this \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <div class="additional attributes table-wrapper">
        <div class="table-wrapper">
            <table class="data table additional attributes" id="product-attribute-specs-table">
                <caption class="table-caption"><?php echo __('Additional Information') ?></caption>
                <tbody>
                <?php foreach ($_additional as $_data): ?>
                    <tr>
                        <th class="col label" scope="row"><?php echo $this->escapeHtml(__($_data['label'])) ?></th>
                        <td class="col data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif;?>
