<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product view template
 *
 * @var $this \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
require([ 'jquery', 'Magento_Catalog/js/price-box' ], function($){
    $(function() {
        $('[data-role=priceBox]').priceBox({'priceConfig': <?php echo $this->getJsonConfig() ?>});
    });
});
</script>

<div class="product-add-form">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?php echo $this->getChildHtml('form_top'); ?>
        <?php if (!$this->hasOptions()):?>
            <?php echo $this->getChildHtml('product_info_form_content'); ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $this->getOptionsContainer() == 'container1'):?>
                <?php echo $this->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getOptionsContainer() == 'container2'):?>
            <?php echo $this->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?php echo $this->getChildHtml('form_bottom'); ?>
    </form>
</div>

<script type="text/javascript">
    require([ 'jquery', 'Magento_Catalog/js/price-box' ], function($){
        $(function() {
            $('[data-role=priceBox]').priceBox({prices:{
                examplePrice: {
                    amount: 89.9999
                }
            }});
        });
    });
</script>
<script type="text/javascript">
    require([ 'jquery', 'Magento_Catalog/js/price-box' ], function($){
        $(function() {
            $('[data-role=priceBox]').priceBox({prices:{
                examplePrice: {
                    adjustments: {
                        gift: -56.01
                    }
                }
            }})
                .trigger('reloadPrice')
            ;
        });
    });
</script>
