<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_product = $this->getProduct() ?>
<?php if ($this->canEmailToFriend()): ?>
    <a title="<?php echo __('Email to a Friend') ?>"
       href="<?php echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
       class="action mailto friend"><span><?php echo __('Email to a Friend') ?></span></a>
<?php endif; ?>
