<?php
/**
 * {license_notice}
 *
 * @copyright {copyright}
 * @license   {license_link}
 */

/** @var $installer \Magento\Core\Model\Resource\Setup */
$installer = $this;

$installer->getConnection()->addColumn(
    $installer->getTable('url_rewrite'),
    'is_autogenerated',
    array(
        'type' => \Magento\Framework\DB\Ddl\Table::TYPE_SMALLINT,
        'unsigned' => true,
        'nullable' => false,
        'comment' => 'Is rewrite generated automatically flag'
    )
);
