<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
/** @var $this \Magento\Wishlist\Block\Customer\Wishlist\Item\Column */
?>
<?php
    $product = $this->getItem()->getProduct();
    $layout = $this->getLayout();
?>
<strong class="product name"><a href="<?php echo $this->getProductUrl($this->getItem()); ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></strong>
<?php if ($product->getShortDescription()): ?>
    <div class="description">
        <?php echo $this->escapeHtml($this->stripTags($product->getShortDescription()));?>
    </div>
<?php endif; ?>
<?php foreach ($this->getChildNames() as $childName):?>
    <?php echo $layout->renderElement($childName, false);?>
<?php endforeach;?>
