<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="design-edit-form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
require([
    "jquery",
    "mage/mage"
], function($){

    $('#design-edit-form').mage('form').mage('validation');

});
</script>
