<?=$breadcrumbs?>
<script src="<?=$baseUrl?>/js/scriptaculous/scriptaculous.js" type="text/javascript"></script>
<script src="<?=$moduleSkinUrl?>/js/product.js" type="text/javascript"></script>
<div class="product-image">
    <div style="position:relative; overflow:hidden; width:245px; height:300px;">
        <img id="image" src="http://www.animationarchive.org/pics/nature03-big.jpg" alt="<?=$product->getName()?>" style="width:100%; position:absolute; top:0; left:0; cursor:move;"/>
    </div>   
    <div style="margin-top:10px; margin-left:20px;">
        <div id="track1" style="width: 200px; height:18px; background:#CCC;">
          <div id="handle1"" style="width: 8px; height: 18px; background:#557;">
            
          </div>
        </div>
        <script type="text/javascript">
            var image = new Draggable('image', {starteffect:false, reverteffect:false, endeffect:false});
            
            var slider = new Control.Slider('handle1','track1', {axis:'horizontal', minimum: 0, maximum:200, alignX: 1, increment: 1, sliderValue: 0});
            slider.options.onSlide = function(value) { scaleIt(value); }
            slider.options.onChange = function(value) { scaleIt(value); }

            var origWidth = 245;
            var origHeight = 300;
            var floorSize = 1.0;
            var ceilingSize = 5.0;
            var lastScale = 1.0;
            
            function scaleIt(v) {
              var image = $('image');
              var diff = lastScale-v;
              lastScale = v;
              
              v = floorSize + (v * (ceilingSize - floorSize));

              //image.style.left = (image.offsetLeft-image.offsetLeft*2)+'px';
              //image.style.top = (image.offsetTop+diff)+'px';
              image.style.width = (v*origWidth)+'px';
            } 
        </script>
    </div>
</div>
<form action="<?=Mage::getBaseUrl('', 'Mage_Checkout');?>/cart/add/" method="POST">
<input type="hidden" name="product_id" value="<?=$product->getProductId()?>">
<div class="product-info">
<h1 class="page-heading"><?=$product->getName()?></h1>
<div class="product-description"><?=$product->getDescription()?></div>
<table cellspacing="0" width="100%" class="qty-list">
	<thead>
		<tr>
			<th style="width:78px;" class="top-left">Quantity</th>
			<th style="width:80px;">Price Each</th>
			<th class="top-right price">Total</th>
		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="3" class="bottom">
			<div><a href="#"><img
				src="<?=$moduleImagesUrl?>/icon_shipping_costs.png"
				alt="View Shipping Costs" class="vmiddle" /></a> <a href="#"><strong>View
			Shipping Costs</strong></a></div>
			</td>
		</tr>
	</tfoot>
	<tbody>
		<tr>
			<td>1</td>
			<td>$<?=$product->getPrice()?></td>
			<td class="price">$<?=$product->getPrice()?></td>
		</tr>
	</tbody>
</table>
<input type="image" src="<?=$moduleImagesUrl?>/btn_add_to_cart.gif"
	alt="Add to Cart" class="float-left" />
<ul class="product-options">
	<li><a href="#" title="Request a Sample"><img
		src="<?=$moduleImagesUrl?>/icon_request_sample.gif"
		alt="Request a Sample" /></a> <a href="#" title="Request a Sample"><strong>Request
	a Sample</strong></a></li>
	<li><a href="#" title="Tell-a-Friend"><img
		src="<?=$moduleImagesUrl?>/icon_tell_friend.gif"
		alt="Request a Sample" /></a> <a href="#" title="Tell-a-Friend"><strong>Tell-a-friend</strong></a></li>
	<li><a href="#"><img src="<?=$moduleImagesUrl?>/icon_add_favorites.gif"
		alt="Add to Favorite" /></a> <a href="#"><strong>Add to Favorites</strong></a>
	</li>
</ul>
<div class="dotted-separator"></div>
<h3 class="red">Satisfaction Guaranteed</h3>
<p>If you are not completely satisfied with your order return it for a
full refund!</p>
<div class="dotted-separator"></div>
<img src="<?=$moduleImagesUrl?>/icon_made_in_america.gif"
	alt="Made in USA" /></div>
</form>
<div class="clearfix" style="height: 20px;">&nbsp;</div>