<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<div class="std">
    <?php echo $this->helper('Mage_Catalog_Helper_Output')->productAttribute($this->getProduct(), $this->getProduct()->getDescription(), 'description') ?>
</div>
