<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Page */
?>

<div class="page-title">
    <h1 class="title"><?php echo $this->__('Store Launcher'); ?></h1>
    <div class="buttons buttons-store-action">
        <a class="button" target="_blank" href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('Preview My Store'); ?></a>
        <button class="button button-special btn-launch-store <?php if (!$this->getPage()->isComplete()): ?>hidden<?php endif; ?>"><?php echo $this->__('Launch My Store'); ?></button>
    </div>
</div>


<section id="store-launcher" class="store-launcher store-launcher-alternative">

<?php foreach($this->getTileBlocks() as $tile):?>
    <?php echo $tile->toHtml() ?>
<?php endforeach;?>

</section>


<div id="drawer" class="drawer">
    <section class="drawer-content">
        <header>
            <div class="header-inner">
                <div class="drawer-header-content">
                    <h1 id="drawer-item-header"></h1>
                </div>
                <span class="btn-close"><?php echo $this->__('Back to Store Launcher'); ?></span>
            </div>
        </header>
        <div class="content">
        </div>
        <footer class="drawer-footer">
            <div class="footer-inner">
                <div id="drawer-item-footer">
                    <button class="button button-special button-save-settins" save-url=""><?php echo $this->__('Save My Settings'); ?></button>
                </div>
            </div>
        </footer>
    </section>
</div>

<script type="text/javascript">
    (function ($) {
        $('.btn-launch-store').click(function() {
            document.location.href = "<?php echo $this->getUrl('*/promotestore_index/index'); ?>";
        });
    })(window.jQuery);
</script>
