<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
namespace Magento\Ui\Component\Form\Element;

/**
 * Class Multiline
 */
class Multiline extends AbstractFormElement
{
    /**
     * @return mixed|string
     */
    public function getType()
    {
        return $this->getData('input_type') ? $this->getData('input_type') : 'text';
    }

    public function prepare()
    {
        parent::prepare(); // TODO: Change the autogenerated stub
    }
}
