<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_readonly    = $this->getElement()->getReadonly() ?>
<?php $_multiWebsite= $this->isMultiWebsites(); ?>
<div class="field" id="attribute-<?php echo $_htmlId?>-container">
    <label class="label"><span><?php echo $this->getElement()->getLabel() ?></span></label>
    <div class="control">
        <table class="data-table" id="<?php echo $_htmlId; ?>_table">
            <thead>
                <tr>
                    <th class="col-name <?php if (!$_multiWebsite): ?>hidden<?php endif; ?>"><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Website') ?></th>
                    <th class="col-amount required-entry"><?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Amount') ?></th>
                    <th class="col-actions"><?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Action') ?></th>
                </tr>
                <tr id="<?php echo $_htmlId ?>_add_template" class="template hidden">
                    <td class="col-name <?php if (!$_multiWebsite): ?>hidden<?php endif; ?>">
                        <div class="field">
                            <div class="control">
                                <select disabled="no-template" class="<?php echo $_htmlClass ?> required-entry" name="<?php echo $_htmlName ?>[__index__][website_id]" id="#{prefix}_giftcard_amounts_row___index___website">
                                    <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
                                    <option value="<?php echo $_websiteId ?>"><?php echo $_info['name'] ?><?php if (!empty($_info['currency'])): ?> [<?php echo $_info['currency'] ?>]<?php endif; ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </td>
                    <td class="col-amount">
                        <div class="field">
                            <div class="control">
                                <input disabled="no-template" class="<?php echo $_htmlClass ?> required-entry validate-greater-than-zero" type="text" name="<?php echo $_htmlName ?>[__index__][price]" value="'#{price}'" />
                            </div>
                        </div>
                    </td>
                    <td class="col-actions">
                        <input type="hidden" name="<?php echo $_htmlName ?>[__index__][delete]" class="delete" disabled="no-template" value=""  id="#{prefix}_giftcard_amounts_row___index___delete" />
                        <button title="<?php echo Mage::helper('Enterprise_GiftCard_Helper_Data')->__('Delete Amount'); ?>"
                                class="action-delete"
                                onclick="giftcardAmountsControl.deleteItem('<?php echo $_htmlId ?>', event); return false;">
                            <span>
                                <?php echo Mage::helper('Enterprise_GiftCard_Helper_Data')->__('Delete'); ?>
                            </span>
                        </button>
                    </td>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="col-name <?php if (!$_multiWebsite): ?>hidden<?php endif; ?>"></td>
                    <td colspan="2" class="col-actions"><?php echo $this->getAddButtonHtml() ?></td>
                </tr>
            </tfoot>
            <tbody id="<?php echo $_htmlId ?>_container"></tbody>
        </table>
        <input type="hidden" id="giftcard_amounts_total" name="giftcard_amounts_total" value="" <?php if (!$_readonly): ?>class="required-entry"<?php endif; ?>>

    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    if (typeof itemsCount == 'undefined') {
        var itemsCount = 0;
    }
    var giftcardAmountsControl = {
        deleteButton: false,
        addItem : function () {
            var data = {};
            data.prefix = '';
            data.website_id = 0;
            data.price      = '';
            data.index      = itemsCount++;
            if(arguments.length == 3) {
                data.prefix     = arguments[0];
                data.website_id = arguments[1];
                data.price      = arguments[2];
            } else if (arguments.length == 1) {
                data.prefix     = arguments[0];
            }

            var template = new Template('<tr>' + $(data.prefix + '_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>');
            Element.insert($(data.prefix + '_container'), {'bottom':template.evaluate(data)});

            $(data.prefix + '_giftcard_amounts_row_'+data.index+'_website').value = data.website_id;
            <?php if ($_readonly): ?>
            $('<?php echo $_htmlId ?>_container').select('input', 'select')
                .each(this.disableElement);
            $('<?php echo $_htmlId ?>_container').select('button')
                .each(this.disableElement);
            <?php endif; ?>
            this.updateTotalAmounts();
        },
        disableElement: function(elem) {
            elem.disabled = true;
            $(elem).addClassName('disabled');
        },

        deleteItem : function(prefix, event) {
            var tr = Event.findElement(event, 'tr');
            if (tr) {
                Element.select(tr, '.action-delete').each(function(elem){elem.value='1'});
                Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                Element.hide(tr);
                Element.addClassName(tr, 'hidden template');
            }
            itemsCount--;
            this.updateTotalAmounts();
        },

        updateTotalAmounts: function() {
            $('giftcard_amounts_total').value = (itemsCount > 0 ? itemsCount : '');
        }
    };

    <?php foreach ($this->getValues() as $_item): ?>
    giftcardAmountsControl.addItem('<?php echo $_htmlId ?>', '<?php echo $_item['website_id'] ?>', '<?php echo sprintf('%.2f', $_item['value']) ?>');
    <?php endforeach; ?>

    function updatePriceAmountValidation() {
        if($('allow_open_amount')) {
            if ($('allow_open_amount').value == 1) {
                jQuery('#giftcard_amounts_total').trigger('resetElement');
                Element.removeClassName($('giftcard_amounts_total'), 'required-entry');
            } else {
                if (!Element.hasClassName($('giftcard_amounts_total'), 'required-entry')) {
                    Element.addClassName($('giftcard_amounts_total'), 'required-entry');
                }
            }
        }
    }

    function setupPriceAmountEvents() {
        if ($('allow_open_amount')) {
            Event.observe('allow_open_amount', 'change', updatePriceAmountValidation);
        }
        updatePriceAmountValidation();
    }
    <?php if (!$_readonly): ?>
    Event.observe(window, 'load', setupPriceAmountEvents);
    <?php endif; ?>
//]]>
</script>
