<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_source  = $this->getSource()?>
<?$_currency= $this->getCurrency()?>
<table cellspacing="0" width="100%">
    <tfoot>
        <tr>
            <td class="label">
                <strong><?=Mage::helper('sales')->__('Grand Total')?></strong>
            </td>
            <td class="emph" class="a-right">
                <strong><?=$_currency->format($_source->getGrandTotal())?></strong>
            </td>
        </tr>
        <!--tr>
            <td class="label"><?=Mage::helper('sales')->__('Total Paid')?></td>
            <td class="emph" align="right"><?=$_currency->format($_source->getTotalPaid())?></td>
        </tr>
        <tr>
            <td class="label"><?=Mage::helper('sales')->__('Total Due')?></td>
            <td class="emph" align="right"><?=$_currency->format($_source->getTotalDue())?></td>
        </tr-->
    </tfoot>
    <tbody>
        <tr>
            <td><?=Mage::helper('sales')->__('Subtotal')?></td>
            <td class="a-right"><?=$_currency->format($_source->getSubtotal())?></td>
        </tr>

        <?if ((float) $_source->getTaxAmount()):?>
        <tr>
            <td><?=Mage::helper('sales')->__('Tax')?></td>
            <td class="a-right"><?=$_currency->format($_source->getTaxAmount())?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_source->getShippingAmount()):?>
        <tr>
            <td><?=Mage::helper('sales')->__('Shipping')?></td>
            <td class="a-right"><?=$_currency->format($_source->getShippingAmount())?></td>
        </tr>
        <?endif;?>
        <?if ((float) $_source->getDiscountAmount()):?>
        <tr>
            <td><?=Mage::helper('sales')->__('Discount')?></td>
            <td class="a-right"><?=$_currency->format($_source->getDiscountAmount())?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_source->getGiftcertAmount()):?>
        <tr>
            <td><?=Mage::helper('sales')->__('Gift Certificate')?></td>
            <td class="a-right"><?=$_currency->format($_source->getGiftcertAmount())?></td>
        </tr>
        <?endif;?>

        <?if ((float) $_source->getCustbalanceAmount()):?>
        <tr>
            <td><?=Mage::helper('sales')->__('Customer Balance')?></td>
            <td class="a-right"><?=$_currency->format($_source->getCustbalanceAmount())?></td>
        </tr>
        <?endif;?>
    </tbody>
</table>
