<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Shopping cart totals template
 * @var $this \Magento\Checkout\Block\Cart\Totals
 */
?>
<div class="cart totals">
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo __('You will see the order total before you submit the order.'); ?></div>
<?php else: ?>
    <table id="shopping-cart-totals-table" class="data table totals">
        <?php echo $this->renderTotals(); ?>
        <tfoot>
            <?php echo $this->renderTotals('footer'); ?>
        </tfoot>
    </table>
<?php endif; ?>
</div>
