<?php
/**
 * Popup container template.
 *
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 *
 * @var \Magento\Backend\Block\Template $this
 */
?>
<script type="text/javascript">
    window.integration = new Integration(
        '<?php echo $this->getUrl('*/*/permissionsDialog', ['id' => ':id']); ?>',
        '<?php echo $this->getUrl('*/*/processTokens', ['id' => ':id']); ?>',
        '', // Not implemented
        '', // Not implemented
        '<?php echo $this->getUrl('*/*/'); ?>'
    );
</script>
<div id="integration-popup-container" style="display:none;"></div>
<div id="integration-delete-container" style="display:none;" title="<?php echo __('Are you sure ?'); ?>">
    <p><?php echo __("Are you sure you want to delete this integration? You can't undo this action."); ?></p>
</div>
