<?php
/**
 * Popup container template.
 *
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 *
 * @var \Magento\Backend\Block\Template $this
 */
?>
<script type="text/javascript">
    window.integration = new Integration(
        '<?php echo $this->getUrl('*/*/permissionsDialog', ['id' => ':id']); ?>',
        '<?php echo $this->getUrl('*/*/tokensDialog', ['id' => ':id']); ?>',
        '', // Not implemented
        '' // Not implemented
    );
</script>
<div id="integration-popup-container" style="display:none;"></div>
