<script type="text/javascript" language="javascript">
if (!Mage.Collection.get('category_tree_context_menu')){
    
    var categoryTreeHandler = new Object();
    categoryTreeHandler.showProducts = function(item,event){
        var contentPanel;
        if (contentPanel=Mage.Collection.get('catalog_main_content_panel')){
            if (item.parentMenu.selectedNode.id){
                contentPanel.setUrl('<?=$this->baseUrl?>/mage_catalog/product/grid/category/'+item.parentMenu.selectedNode.id);
                contentPanel.refresh();
            }
        }
    };
    categoryTreeHandler.editCategory = function(item,event){
        alert('edit category');
    };
    categoryTreeHandler.deleteCategory = function(item,event){
        alert('delete category');
    };
    categoryTreeHandler.clickCategory = function(node,event){
        if (Mage.Collection.get('category_tree_context_menu'))
        {
            Mage.Collection.get('category_tree_context_menu').hide();
        }
    };
    categoryTreeHandler.dblClickCategory = function(node,event){
        
    }
    
    
    var categoryTreeContextMenu = new Ext.menu.Menu({
        id : 'category_context_menu',
        items: [{text: 'Show Category Products',handler:categoryTreeHandler.showProducts}, 
                '-',  
                {text: 'Edit Catecory',handler:categoryTreeHandler.editCategory}, 
                {text: 'Delete Category',handler:categoryTreeHandler.deleteCategory}]
    });
    
    categoryTreeContextMenu.showNodeContextMenu = function(node, event){
        this.selectedNode = node;
        node.select();
        this.showAt(event.getXY(),this.parentMenu,false);
    };
    Mage.Collection.add('category_tree_context_menu', categoryTreeContextMenu);
    Mage.Collection.add('category_tree_handler', categoryTreeHandler);
}

// Add Listeners
Mage.Collection.get('catalog_category_tree').addListener(
    'contextmenu',
    Mage.Collection.get('category_tree_context_menu').showNodeContextMenu,
    Mage.Collection.get('category_tree_context_menu')
);

Mage.Collection.get('catalog_category_tree').addListener(
    'click',
    Mage.Collection.get('category_tree_handler').clickCategory,
    Mage.Collection.get('category_tree_handler')
);

Mage.Collection.get('catalog_category_tree').addListener(
    'dblclick',
    Mage.Collection.get('category_tree_handler').dblClickCategory,
    Mage.Collection.get('category_tree_handler')
);

function moveNode(e) {
    Ext.dump(e.target.id);
    Ext.dump(e.point);
    Ext.dump(e.dropNode.id);
    Ext.dump('===================================');
}
var root = Mage.Collection.get('catalog_tree');
root.addListener('beforenodedrop', moveNode);
</script>
