<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Payments_Tile */
?>
<article class="tile-store-settings tile-payments <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Payment Method') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Choose payment method') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
            data-save-url="<?php echo $this->getUrl('*/storelauncher_payments_drawer/save') ?>"
            data-load-url="<?php echo $this->getUrl('*/storelauncher_payments_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Payment Methods') ?>
        </button>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <button type="button" class="action-configure-payments" onclick="window.location = '<?php echo $this->getUrl('adminhtml/system_config/edit', array('section' => 'payment')); ?>';">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Configure Other Payment Methods'); ?>
        </button>
        <?php endif; ?>
    </div>
</article>
