<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
$_cards = $this->getTotal()->getGiftCards();
if (!$_cards) {
    $_cards = $this->getQuoteGiftCards();
}
?>
<?php if ($this->getTotal()->getValue()): ?>
<?php foreach ($_cards as $_c): ?>
    <tr class="giftcard totals">
        <th colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="mark" scope="row">
            <?php $_title = __('Remove'); ?>
            <?php $_url = $this->getUrl('magento_giftcardaccount/cart/remove', ['code' => $_c['c']]); ?>
            <a href="<?php echo $_url; ?>" title="<?php echo $_title; ?>" class="action delete"><span><?php echo $_title; ?></span></a>
            <?php echo __('Gift Card (%1)', $_c['c']); ?>
        </th>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="amount" data-th="<?php echo $this->escapeHtml(__('Gift Card (%1)', $_c['c'])); ?>">
            <span class="discount">-<?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_c['a']) ?></span>
        </td>
    </tr>
<?php endforeach; ?>
<?php endif; ?>
