<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
if ($this->isThirdPartSearchEngine()) :?>
<script type="text/javascript">
require(['prototype'], function(){

//<![CDATA[
function checkIsSearchWeightVisibility()
{
    if ($F('is_searchable')==1) {
        setRowVisibility('search_weight', true);
    } else {
        setRowVisibility('search_weight', false);
    }
}
checkIsSearchWeightVisibility();

window.checkIsSearchWeightVisibility = checkIsSearchWeightVisibility;

if($('frontend_input')){
    Event.observe($('is_searchable'), 'change', checkIsSearchWeightVisibility);
}
//]]>

});
</script>
<?php endif;?>
