<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Promotestore_Wishlist_Drawer */
?>
<form id="drawer-form">
    <article class="entry">
        <ul class="promote-actions">
            <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'wishlist', '_fragment' => 'wishlist_general-link')); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('Activate Wish List') ?></a></li>
        </ul>
        <div class="promote-content">
            <div class="promote-content-section">
                <p><?php echo __('Online shoppers love keeping wish lists – for gift ideas, deferred purchases, or simply to dream over. Let customers create and share their wish lists to increase loyalty and bring new customers to your site.') ?> </p>
            </div>
            <div class="promote-content-section">
                <p><?php echo __('It\'s easy to activate the wish list feature. Try it now.') ?> </p>
            </div>
        </div>
    </article>
</form>
