<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * Template for displaying product price in RSS feeds
 *
 * @var $this \Magento\Catalog\Block\Product\Price
 */
?>
<?php
$_product = $this->getProduct();
$_id = $_product->getId();
$_minimalPriceValue = $_product->getMinimalPrice();
$_exclTax = $this->helper('Magento\Tax\Helper\Data')->getPrice($_product, $_minimalPriceValue, $includingTax = null);
$_inclTax = $this->helper('Magento\Tax\Helper\Data')->getPrice($_product, $_minimalPriceValue, $includingTax = true);
?>

<?php if ($_product->getCanShowPrice() !== false):?>
    <?php if ($this->getDisplayMinimalPrice() && $_minimalPriceValue): ?>
        <div class="price-box">
            <p class="minimal-price">
                <span class="price-label"><?php echo __('Starting at:') ?></span>
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displayBothPrices()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo __('Excl. Tax:') ?></span>
                        <span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo $this->helper('Magento\Core\Helper\Data')->currency($_exclTax, true, false) ?></span>
                    </span>
                    <span class="price-including-tax">
                        <span class="label"><?php echo __('Incl. Tax:') ?></span>
                        <span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo $this->helper('Magento\Core\Helper\Data')->currency($_inclTax, true, false) ?></span>
                    </span>
                <?php else: ?>
                    <?php
                    $_showPrice = $_inclTax;
                    if (!$this->helper('Magento\Tax\Helper\Data')->displayPriceIncludingTax()) {
                        $_showPrice = $_exclTax;
                    }
                    ?>
                    <span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo $this->helper('Magento\Core\Helper\Data')->currency($_showPrice, true, false) ?></span>
                <?php endif; ?>
            </p>
        </div>
    <?php endif; ?>
<?php endif; ?>
