<?php
/**
 * @var \Magento\Ui\Listing\View $this
 */
?>
<div data-m2-init='{"Magento_Ui/js/grid/listing/component": ""}'>
    <script type="mage/config" data-role="Magento_Ui/js/grid/listing/component">
        <?php echo $this->getConfigurationJson(); ?>
    </script>
</div>
<div data-m2-init='{"Magento_Ui/js/grid/sorting": ""}'>
    <script type="mage/config">
       <?php echo $this->getSortingJson(); ?>
    </script>
</div>
<div data-m2-init='{"Magento_Ui/js/grid/filter": ""}'>
    <script type="mage/config">
        {   
            "config": {
                "name": "cms_page_listing"
            }
        }
    </script>
</div>
<div class="grid">
    <?php echo $this->getChildHtml('listing_before'); ?>
    <div data-bind="scope: '<?php echo $this->getName(); ?>:filter'">
        <!-- ko template: 'Magento_Ui.templates.filter' --><!-- /ko -->
    </div>
    <div data-bind="scope: '<?php echo $this->getName(); ?>:listing'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- ko template: 'Magento_Ui.templates.loader' --><!-- /ko -->
    </div>
    <?php echo $this->getChildHtml('listing_after'); ?>
</div>