<div class="data-form">
<div class="x-box-tl"><div class="x-box-tr"><div class="x-box-tc"></div></div></div>
<div class="x-box-ml"><div class="x-box-mr"><div class="x-box-mc">
<h1>ORDER # <?=$order->getRealOrderId()?></h1><br/>
<h2>
    TEST
</h2><br/>

<form action="<?=$formAction?>" method="post">
    <fieldset>
        <legend>Test</legend>
        <p>
            <?print_r($order->getData())?>
        </p>
    </fieldset>
</form>

</div></div></div>
<div class="x-box-bl"><div class="x-box-br"><div class="x-box-bc"></div></div></div>
</div>
