<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="block giftregistry shared">
    <?php $entity = $this->getEntity() ?>
    <?php if ($entity): ?>

    <div class="table-wrapper">
        <table class="data table giftregistry shared">
            <caption class="table-caption"><?php echo __('Gift Registry'); ?></caption>
            <tbody>
            <?php foreach ($this->getAttributesToDisplay() as $attributeInfo): ?>
                <tr>
                    <th class="col title" scope="col"><?php echo $attributeInfo['title'] ?></th>
                    <td class="col value" scope="col"><?php echo $attributeInfo['value'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php echo $this->getChildHtml('giftregistry_items') ?>
    <?php endif; ?>
    <div class="actions">
        <div class="secondary">
            <a href="<?php echo $this->escapeUrl($this->getSearchBackUrl()) ?>" class="action back"><span><?php echo __('Back') ?></span></a>
        </div>
    </div>
</div>