<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $entity = $this->getEntity() ?>

<?php if ($entity): ?>
    <div class="block block-giftregistry-shared">
        <div class="block-content">
            <dl class="item-options giftregistry-description">
                <?php foreach ($this->getAttributesToDisplay() as $attributeInfo): ?>
                    <dt class="item-title"><?php echo $attributeInfo['title'] ?></dt>
                    <dd class="item-value"><?php echo $attributeInfo['value'] ?></dd>
                <?php endforeach; ?>
            </dl>
        </div>
    </div>
    <?php echo $this->getChildHtml('giftregistry_items') ?>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a href="<?php echo $this->escapeUrl($this->getSearchBackUrl()) ?>" class="action back"><span><?php echo __('Back') ?></span></a>
    </div>
</div>
