<?
/**
 * Multishipping checkout billing information
 * 
 * @see Mage_Checkout_Block_Multishipping_Billing
 */
?>
<div class="page-head">
    <h2>Billing Information</h2>
</div>
<?=$this->getMessagesBlock()->getHtml()?>
<script src="<?=Mage::getBaseUrl(array('_type'=>'js'))?>varien/payment.js" type="text/javascript"></script>
<form action="<?=$this->getPostActionUrl()?>" method="post" id="multishipping-billing-form">
<div class="content-box">
<div class="col2-set">
    <div class="col-1">
        <h3 class="bar-head">
            Billing Address<span class="separator">|</span>
            <small><a href="<?=$this->getSelectAddressUrl()?>">Change</a></small>
        </h3>
        <div class="content">
            <?$_address=$this->getAddress()?>
            <address>
                <?=$_address->getFirstname()?> <?=$_address->getLastname()?><br/>
                <?if($_address->getCompany()):?><?=$_address->getCompany()?><br/><?endif?>
                <?=$_address->getStreet(1)?><br/>
                <?if($_address->getStreet(2)):?><?=$_address->getStreet(2)?><br/><?endif?>
                <?=$_address->getCity()?>, <?=$_address->getRegion()?> <?=$_address->getPostcode()?><br/>
                <?=$_address->getCountry()?>
                <strong>T</strong> | <?=$_address->getTelephone()?>
            </address>
        </div>
    </diV>
    <div class="col-2">
        <h3 class="bar-head">Payment Method</h3>
        <div class="content">
            <dl class="payment-methods">
                <?=$this->getPaymentMethods()?> 
            </dl>
        </div>
    </div>
</div>
</div>
<div class="form-buttons">
    <a href="<?=$this->getBackUrl()?>" class="left">&laquo; Back to Shipping Information</a>
    <button class="form-button" type="submit"><span>Continue</span></button>
</div>
<script type="text/javascript">
    // Need to fix payment JS
    var payment = new paymentForm('multishipping-billing-form');
</script>