<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_processes = $this->getCacheTypesForRefresh()?>
<?php if($_processes):?>
<div class="message message-system">
    <div class="message-inner">
        <div class="message-content">
            <strong><?php echo $this->helper('Mage_Adminhtml_Helper_Data')->__('One or more of the Cache Types are invalidated:') ?></strong>
            <?php echo implode(', ', $_processes)?>.
            <?php echo $this->helper('Mage_Index_Helper_Data')->__('Click here to go to <a href="%s">Cache Management</a> and refresh cache types.', $this->getManageUrl());?>
        </div>
    </div>
</div>
<?php endif;?>
