<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Toolbar_Buttons */ ?>
<div id="vde_toolbar_button_preview" <?php echo $this->getUiId()?> class="vde_toolbar_buttons store-launcher-theme-preview">
    <?php echo $this->getAssignButtonHtml(); ?>
</div>
