<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_modern
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="footer-container">
    <div class="footer">
        <?php echo $this->getChildHtml('bottomContainer') ?>
        <div class="f-right">
            <img src="<?php echo $this->getViewFileUrl('images/media/footer_callout.png');?>" class="footer-callout"
                 alt=""/>
            <?php echo $this->getChildHtml('store_switcher') ?>
        </div>
        <div class="f-left">
            <?php echo $this->getChildHtml('cms_footer_links') ?>
            <?php echo $this->getChildHtml('footer_links') ?>
            <?php echo $this->getChildHtml('newsletter') ?>
            <p class="bugs"><?php echo $this->__('Help Us to Keep Magento Healthy') ?> - <a
                href="http://www.magentocommerce.com/bug-tracking"
                target="_blank"><strong><?php echo $this->__('Report All Bugs') ?></strong></a> <?php echo $this->__('(ver. %1)', Mage::getVersion()) ?>
            </p>
            <address><?php echo $this->getCopyright() ?></address>
        </div>
    </div>
</div>
