<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
/** @var $this \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\History" */
?>
<div class="fieldset-wrapper" id="rma-history-block">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('RMA History') ?></span>
    </div>
    <div id="history_form" class="rma-history-form">
        <label for="history_comment"><?php echo __('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" id="history_comment"></textarea>
        <input name="comment[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php echo __('Visible on Frontend') ?></label>
    </div>
</div>
