<?php
/**
 * Obsolete class attributes
 *
 * Format: array(<attribute_name>[, <class_scope> = ''[, <replacement>]])
 *
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
return array(
    array('_addresses', 'Mage_Customer_Model_Customer'),
    array('_addMinimalPrice', 'Mage_Catalog_Model_Resource_Product_Collection'),
    array('_alias', 'Mage_Core_Block_Abstract'),
    array('_anonSuffix'),
    array('_appMode', 'Mage_Core_Model_ObjectManager_ConfigLoader'),
    array('_baseDirCache', 'Mage_Core_Model_Config'),
    array('_cacheConf'),
    array('_canUseLocalModules'),
    array('_checkedProductsQty', 'Mage_CatalogInventory_Model_Observer'),
    array('_children', 'Mage_Core_Block_Abstract'),
    array('_childrenHtmlCache', 'Mage_Core_Block_Abstract'),
    array('_childGroups', 'Mage_Core_Block_Abstract'),
    array('_combineHistory'),
    array('_config', 'Mage_Core_Model_Design_Package'),
    array('_config', 'Mage_Core_Model_Logger', '_dirs'),
    array('_configModel', 'Mage_Backend_Model_Menu_DirectorAbstract'),
    array('_configuration', 'Mage_Index_Model_Lock_Storage', '_dirs'),
    array('_currency', 'Mage_GoogleCheckout_Model_Api_Xml_Checkout'),
    array('_currencyNameTable'),
    array('_customEtcDir', 'Mage_Core_Model_Config'),
    array('_designProductSettingsApplied'),
    array('_distroServerVars'),
    array('_entityIdsToIncrementIds'),
    array('_entityTypeIdsToTypes'),
    array('_factory', 'Mage_Backend_Model_Menu_Config'),
    array('_factory', 'Mage_Backend_Model_Menu_DirectorAbstract', '_commandFactory'),
    array('_isAnonymous'),
    array('_isFirstTimeProcessRun', 'Mage_SalesRule_Model_Validator'),
    array('_isRuntimeValidated', 'Magento_ObjectManager_Config_Reader_Dom'),
    array('_loadDefault', 'Mage_Core_Model_Resource_Store_Collection'),
    array('_loadDefault', 'Mage_Core_Model_Resource_Store_Group_Collection'),
    array('_loadDefault', 'Mage_Core_Model_Resource_Website_Collection'),
    array('_mapper', 'Magento_ObjectManager_Config_Reader_Dom'),
    array('_menu', 'Mage_Backend_Model_Menu_Builder'),
    array('_modulesReader', 'Mage_Core_Model_ObjectManager_ConfigLoader'),
    array('_moduleReader', 'Mage_Backend_Model_Menu_Config'),
    array('_option', 'Mage_Captcha_Helper_Data', '_dirs'),
    array('_options', 'Mage_Core_Model_Config', 'Mage_Core_Model_Dir'),
    array('_optionsMapping', null, 'Mage::getBaseDir($nodeKey)'),
    array('_order', 'Mage_Checkout_Block_Onepage_Success'),
    array('_order_id'),
    array('_parent', 'Mage_Core_Block_Abstract'),
    array('_parentBlock', 'Mage_Core_Block_Abstract'),
    array('_persistentCustomerGroupId'),
    array('_ratingOptionTable', 'Mage_Rating_Model_Resource_Rating_Option_Collection'),
    array('_readerFactory', 'Mage_Core_Model_ObjectManager_ConfigLoader'),
    array('_saveTemplateFlag', 'Mage_Newsletter_Model_Queue'),
    array('_searchTextFields'),
    array('_setAttributes', 'Mage_Catalog_Model_Product_Type_Abstract'),
    array('_skipFieldsByModel'),
    array('_ship_id'),
    array('_shipTable', 'Mage_Shipping_Model_Resource_Carrier_Tablerate_Collection'),
    array('_sortedChildren'),
    array('_sortInstructions'),
    array('_storeFilter', 'Mage_Catalog_Model_Product_Type_Abstract'),
    array('_substServerVars'),
    array('_track_id'),
    array('_varSubFolders', null, 'Mage_Core_Model_Dir'),
    array('_viewDir', 'Mage_Core_Block_Template', '_dirs'),
    array('decoratedIsFirst', null, 'getDecoratedIsFirst'),
    array('decoratedIsEven', null, 'getDecoratedIsEven'),
    array('decoratedIsOdd', null, 'getDecoratedIsOdd'),
    array('decoratedIsLast', null, 'getDecoratedIsLast'),
    array('static', 'Mage_Core_Model_Email_Template_Filter'),
    array('_useAnalyticFunction'),
);
