<?php
/**
 * {license_notice}
 *
 * @category    tests
 * @package     static
 * @subpackage  Legacy
 * @copyright   {copyright}
 * @license     {license_link}
 */
return array(
    $this->_addClass('Mage_Admin_Model_Acl', 'Magento_Acl'),
    $this->_addClass('Mage_Admin_Model_Acl_Role'),
    $this->_addClass('Mage_Admin_Model_Acl_Resource', 'Magento_Acl_Resource'),
    $this->_addClass('Mage_Admin_Model_Acl_Role_Registry', 'Magento_Acl_Role_Registry'),
    $this->_addClass('Mage_Admin_Model_Acl_Role_Generic', 'Mage_User_Model_Acl_Role_Generic'),
    $this->_addClass('Mage_Admin_Model_Acl_Role_Group', 'Mage_User_Model_Acl_Role_Group'),
    $this->_addClass('Mage_Admin_Model_Acl_Role_User', 'Mage_User_Model_Acl_Role_User'),
    $this->_addClass('Mage_Admin_Model_Resource_Acl', 'Mage_User_Model_Resource_Acl'),
    $this->_addClass('Mage_Admin_Model_Observer'),
    $this->_addClass('Mage_Admin_Model_Session', 'Mage_Backend_Model_Auth_Session'),
    $this->_addClass('Mage_Admin_Model_Resource_Acl_Role'),
    $this->_addClass('Mage_Admin_Model_Resource_Acl_Role_Collection'),
    $this->_addClass('Mage_Admin_Model_User', 'Mage_User_Model_User'),
    $this->_addClass('Mage_Admin_Model_Resource_User', 'Mage_User_Model_Resource_User'),
    $this->_addClass('Mage_Admin_Model_Resource_User_Collection', 'Mage_User_Model_Resource_User_Collection'),
    $this->_addClass('Mage_Admin_Model_Role', 'Mage_User_Model_Role'),
    $this->_addClass('Mage_Admin_Model_Roles', 'Mage_User_Model_Roles'),
    $this->_addClass('Mage_Admin_Model_Rules', 'Mage_User_Model_Rules'),
    $this->_addClass('Mage_Admin_Model_Resource_Role', 'Mage_User_Model_Resource_Role'),
    $this->_addClass('Mage_Admin_Model_Resource_Roles', 'Mage_User_Model_Resource_Roles'),
    $this->_addClass('Mage_Admin_Model_Resource_Rules', 'Mage_User_Model_Resource_Rules'),
    $this->_addClass('Mage_Admin_Model_Resource_Role_Collection', 'Mage_User_Model_Resource_Role_Collection'),
    $this->_addClass('Mage_Admin_Model_Resource_Roles_Collection', 'Mage_User_Model_Resource_Roles_Collection'),
    $this->_addClass('Mage_Admin_Model_Resource_Roles_User_Collection',
        'Mage_User_Model_Resource_Roles_User_Collection'),
    $this->_addClass('Mage_Admin_Model_Resource_Rules_Collection', 'Mage_User_Model_Resource_Rules_Collection'),
    $this->_addClass('Mage_Admin_Model_Resource_Permissions_Collection',
        'Mage_User_Model_Resource_Permissions_Collection'),
    $this->_addClass('Mage_Adminhtml_Block_Api_Edituser'),
    $this->_addClass('Mage_Adminhtml_Block_Api_Tab_Userroles'),
    $this->_addClass('Mage_Adminhtml_Block_Catalog'),
    $this->_addClass('Mage_Adminhtml_Block_Page_Menu', 'Mage_Backend_Block_Menu'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_User'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_User_Grid'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_User_Edit'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_User_Edit_Tabs'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_User_Edit_Tab_Main'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_User_Edit_Tab_Roles'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_User_Edit_Form'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Role'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Buttons'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Role_Grid_User'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Grid_Role'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Grid_User'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Tab_Roleinfo'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Tab_Rolesedit'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Tab_Rolesusers'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Tab_Useredit'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Editroles'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Roles'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Users'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Edituser'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Tab_Userroles'),
    $this->_addClass('Mage_Adminhtml_Block_Permissions_Usernroles'),
    $this->_addClass('Mage_Adminhtml_Permissions_UserController'),
    $this->_addClass('Mage_Adminhtml_Permissions_RoleController'),
    $this->_addClass('Mage_Adminhtml_Block_Report_Product_Ordered'),
    $this->_addClass('Mage_Adminhtml_Block_Report_Product_Ordered_Grid'),
    $this->_addClass('Mage_Adminhtml_Block_Sales'),
    $this->_addClass('Mage_Adminhtml_Block_Sales_Order_Create_Search_Grid_Renderer_Giftmessage'),
    $this->_addClass('Mage_Adminhtml_Block_Tag_Tag_Edit'),
    $this->_addClass('Mage_Adminhtml_Block_Tag_Tag_Edit_Form'),
    $this->_addClass('Mage_Adminhtml_Block_Tree'),
    $this->_addClass('Mage_Adminhtml_Helper_Rss'),
    $this->_addClass('Mage_Adminhtml_Model_System_Config_Source_Shipping_Allowedmethods'),
    $this->_addClass('Mage_Adminhtml_Model_System_Store', 'Mage_Core_Model_System_Store'),
    $this->_addClass('Mage_Adminhtml_Rss_CatalogController'),
    $this->_addClass('Mage_Adminhtml_Rss_OrderController'),
    $this->_addClass('Mage_Bundle_Product_EditController', 'Mage_Bundle_Adminhtml_Bundle_SelectionController'),
    $this->_addClass('Mage_Bundle_SelectionController', 'Mage_Bundle_Adminhtml_Bundle_SelectionController'),
    $this->_addClass('Mage_Catalog_Model_Entity_Product_Attribute_Frontend_Image'),
    $this->_addClass('Mage_Catalog_Model_Resource_Product_Attribute_Frontend_Image'),
    $this->_addClass('Mage_Catalog_Model_Resource_Product_Attribute_Frontend_Tierprice'),
    $this->_addClass('Mage_Core_Block_Flush'),
    $this->_addClass('Mage_Core_Block_Template_Facade'),
    $this->_addClass('Mage_Core_Controller_Varien_Router_Admin', 'Mage_Backend_Controller_Router_Default'),
    $this->_addClass('Mage_Core_Model_Design_Source_Apply'),
    $this->_addClass('Mage_Core_Model_Language'),
    $this->_addClass('Mage_Core_Model_Resource_Language'),
    $this->_addClass('Mage_Core_Model_Resource_Language_Collection'),
    $this->_addClass('Mage_Core_Model_Session_Abstract_Varien'),
    $this->_addClass('Mage_Core_Model_Session_Abstract_Zend'),
    $this->_addClass('Mage_Core_Model_Layout_Data', 'Mage_Core_Model_Layout_Update'),
    $this->_addClass('Mage_Customer_Block_Account'),
    $this->_addClass('Mage_Directory_Model_Resource_Currency_Collection'),
    $this->_addClass('Mage_Downloadable_FileController', 'Mage_Downloadable_Adminhtml_Downloadable_FileController'),
    $this->_addClass('Mage_Downloadable_Product_EditController', 'Mage_Adminhtml_Catalog_ProductController'),
    $this->_addClass('Mage_GiftMessage_Block_Message_Form'),
    $this->_addClass('Mage_GiftMessage_Block_Message_Helper'),
    $this->_addClass('Mage_GiftMessage_IndexController'),
    $this->_addClass('Mage_GiftMessage_Model_Entity_Attribute_Backend_Boolean_Config'),
    $this->_addClass('Mage_GiftMessage_Model_Entity_Attribute_Source_Boolean_Config'),
    $this->_addClass('Mage_GoogleOptimizer_IndexController', 'Mage_GoogleOptimizer_Adminhtml_Googleoptimizer_IndexController'),
    $this->_addClass('Mage_Ogone_Model_Api_Debug'),
    $this->_addClass('Mage_Ogone_Model_Resource_Api_Debug'),
    $this->_addClass('Mage_Page_Block_Html_Toplinks'),
    $this->_addClass('Mage_Page_Block_Html_Wrapper'),
    $this->_addClass('Mage_Poll_Block_Poll'),
    $this->_addClass('Mage_ProductAlert_Block_Price'),
    $this->_addClass('Mage_ProductAlert_Block_Stock'),
    $this->_addClass('Mage_Reports_Model_Resource_Coupons_Collection'),
    $this->_addClass('Mage_Reports_Model_Resource_Invoiced_Collection'),
    $this->_addClass('Mage_Reports_Model_Resource_Product_Ordered_Collection'),
    $this->_addClass('Mage_Reports_Model_Resource_Product_Viewed_Collection',
        'Mage_Reports_Model_Resource_Report_Product_Viewed_Collection'),
    $this->_addClass('Mage_Reports_Model_Resource_Refunded_Collection'),
    $this->_addClass('Mage_Reports_Model_Resource_Shipping_Collection'),
    $this->_addClass('Mage_Rss_Model_Observer'),
    $this->_addClass('Mage_Rss_Model_Session', 'Mage_Backend_Model_Auth and Mage_Backend_Model_Auth_Session'),
    $this->_addClass('Mage_Sales_Block_Order_Details'),
    $this->_addClass('Mage_Sales_Block_Order_Tax'),
    $this->_addClass('Mage_Sales_Model_Entity_Order'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Address'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Address_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Attribute_Backend_Billing'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Attribute_Backend_Child'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Attribute_Backend_Parent'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Attribute_Backend_Shipping'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo_Attribute_Backend_Child'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo_Attribute_Backend_Parent'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo_Comment'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo_Comment_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo_Item'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Creditmemo_Item_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Child'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Item'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Order'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Attribute_Backend_Parent'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Comment'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Comment_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Item'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Invoice_Item_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Item'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Item_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Payment'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Payment_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Attribute_Backend_Child'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Attribute_Backend_Parent'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Comment'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Comment_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Item'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Item_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Track'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Shipment_Track_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Status_History'),
    $this->_addClass('Mage_Sales_Model_Entity_Order_Status_History_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend_Child'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend_Parent'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Backend_Region'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Custbalance'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Discount'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Grand'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Shipping'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Subtotal'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Attribute_Frontend_Tax'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Item'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Item_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Rate'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Address_Rate_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Item'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Item_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Payment'),
    $this->_addClass('Mage_Sales_Model_Entity_Quote_Payment_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Sale_Collection'),
    $this->_addClass('Mage_Sales_Model_Entity_Setup'),
    $this->_addClass('Mage_Shipping_ShippingController'),
    $this->_addClass('Mage_Tag_Block_Customer_Edit'),
    $this->_addClass('Mage_User_Model_Roles'),
    $this->_addClass('Mage_User_Model_Resource_Roles'),
    $this->_addClass('Mage_User_Model_Resource_Roles_Collection'),
    $this->_addClass('Mage_User_Model_Resource_Roles_User_Collection'),
    $this->_addClass('Mage_Wishlist_Model_Resource_Product_Collection'),
    $this->_addClass('Mage_XmlConnect_Helper_Payment'),
    $this->_addClass('Varien_Convert_Action'),
    $this->_addClass('Varien_Convert_Action_Abstract'),
    $this->_addClass('Varien_Convert_Action_Interface'),
    $this->_addClass('Varien_Convert_Adapter_Abstract'),
    $this->_addClass('Varien_Convert_Adapter_Db_Table'),
    $this->_addClass('Varien_Convert_Adapter_Http'),
    $this->_addClass('Varien_Convert_Adapter_Http_Curl'),
    $this->_addClass('Varien_Convert_Adapter_Interface'),
    $this->_addClass('Varien_Convert_Adapter_Io'),
    $this->_addClass('Varien_Convert_Adapter_Soap'),
    $this->_addClass('Varien_Convert_Adapter_Std'),
    $this->_addClass('Varien_Convert_Adapter_Zend_Cache'),
    $this->_addClass('Varien_Convert_Adapter_Zend_Db'),
    $this->_addClass('Varien_Convert_Container_Collection'),
    $this->_addClass('Varien_Convert_Container_Generic'),
    $this->_addClass('Varien_Convert_Container_Interface'),
    $this->_addClass('Varien_Convert_Mapper_Abstract'),
    $this->_addClass('Varien_Convert_Parser_Abstract'),
    $this->_addClass('Varien_Convert_Parser_Csv'),
    $this->_addClass('Varien_Convert_Parser_Interface'),
    $this->_addClass('Varien_Convert_Parser_Serialize'),
    $this->_addClass('Varien_Convert_Parser_Xml_Excel'),
    $this->_addClass('Varien_Convert_Profile'),
    $this->_addClass('Varien_Convert_Profile_Abstract'),
    $this->_addClass('Varien_Convert_Profile_Collection'),
    $this->_addClass('Varien_Convert_Validator_Abstract'),
    $this->_addClass('Varien_Convert_Validator_Column'),
    $this->_addClass('Varien_Convert_Validator_Dryrun'),
    $this->_addClass('Varien_Convert_Validator_Interface'),
    $this->_addClass('Varien_File_Uploader_Image'),
    $this->_addClass('Varien_Profiler', 'Magento_Profiler'),
);
