<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->canShow() && $this->getEvents() && count($this->getEvents())): ?>
    <h2 class="table-caption"><?php echo __('Balance History'); ?></h2>
    <table id="customerbalance-history" class="data-table">
        <col />
        <col width="100" />
        <col width="100" />
        <col width="150" />
        <thead>
            <tr>
                <th><?php echo __('Action'); ?></th>
                <th><?php echo __('Balance Change'); ?></th>
                <th><?php echo __('Balance'); ?></th>
                <th><?php echo __('Date'); ?></th>
            </tr>
        </thead>
        <?php foreach ($this->getEvents() as $event): ?>
        <tbody>
            <tr>
                <td><?php echo $this->getActionLabel($event->getAction()); ?></td>
                <td><?php echo $this->helper('Magento_Core_Helper_Data')->currency($event->getBalanceDelta()); ?></td>
                <td><?php echo $this->helper('Magento_Core_Helper_Data')->currency($event->getBalanceAmount()); ?></td>
                <td><?php echo $this->helper('Magento_Core_Helper_Data')->formatDate($event->getUpdatedAt(), 'short', true); ?></td>
            </tr>
        </tbody>
        <?php endforeach; ?>
    </table>
    <script type="text/javascript">(function($) {$('#customerbalance-history').decorate('table')})(jQuery)</script>
<?php endif; ?>
