<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Order by SKU Failed item info
 *
 * @see Magento_AdvancedCheckout_Block_Sku_Products_Info
 * @var $this Magento_AdvancedCheckout_Block_Sku_Products_Info
 */
$_item = $this->getItem();
$escapedSku = $this->escapeHtml($_item->getSku());
?>
<h3 class="product-name product-sku"><?php echo $escapedSku ?></h3>
<p class="tier-prices"><?php echo $this->getTierPriceHtml(); ?></p>
<p class="item-msg error"><?php echo $this->getMessage(); ?></p>
<p class="item-configure"><?php echo $this->getLink(); ?></p>
<input type="hidden" name="failed[<?php echo $escapedSku; ?>][sku]" value="<?php echo $this->escapeHtml($_item->getSku()); ?>" />
<input type="hidden" name="failed[<?php echo $escapedSku; ?>][code]" value="<?php echo $_item->getCode(); ?>" />
<input type="hidden" name="failed[<?php echo $escapedSku; ?>][qty]" value="<?php echo $_item->getQty(); ?>" class="sku_failed_qty" data-role="sku-failed-qty" />
<?php if (!$this->isItemSkuFailed()): ?>
    <?php if ($_item->getQtyMaxAllowed()): ?>
        <input type="hidden" class="qty_max_allowed" value="<?php echo $_item->getQtyMaxAllowed() ?>"/>
    <?php endif ?>
    <?php if ($_item->getQtyMinAllowed()): ?>
        <input type="hidden" class="qty_min_allowed" value="<?php echo $_item->getQtyMinAllowed() ?>"/>
    <?php endif ?>
    <?php if ($_item->getCode() == Magento_AdvancedCheckout_Helper_Data::ADD_ITEM_STATUS_FAILED_QTY_INCREMENTS): ?>
        <input type="hidden" class="qty_increments" value="<?php echo $_item->getQtyIncrements() ?>"/>
    <?php endif ?>
<?php endif; ?>
