<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Wishlist\Block\Share\Wishlist */
?>
<div class="my-wishlist">
    <div class="page-title">
        <h1><?php echo $this->escapeHtml($this->getHeader()) ?></h1>
    </div>
    <div class="wishlist-view">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php if ($this->hasWishlistItems()): ?>
        <form action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
            <fieldset>
                <table class="data-table" id="wishlist-table">
                <?php foreach($this->getWishlistItems() as $item): ?>
                    <?php
                        $product = $item->getProduct();
                        $isVisibleProduct = $product->isVisibleInSiteVisibility();
                    ?>
                    <tr>
                        <td>
                            <a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><img src="<?php echo $this->helper('\Magento\Catalog\Helper\Image')->init($product, 'small_image')->resize(113, 113); ?>" width="113" height="113" alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a>
                            <h2 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h2>
                            <?php echo $this->getPriceHtml($product) ?>
                            <?php echo $this->getDetailsHtml($item) ?>

                            <?php if ($product->isSaleable()): ?>
                                <?php if ($isVisibleProduct): ?>
                                    <a href="<?php echo $this->getSharedItemAddToCartUrl($item) ?>"><?php echo __('Add to Cart') ?></a>
                                <?php endif ?>
                            <?php endif; ?>
                            <p><a href="<?php echo $this->getAddToWishlistUrl($item) ?>" onclick="setLocation(this.href); return false;" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></p>

                            <div class="comment"><?php echo $this->getEscapedDescription($item) ?></div>
                        </td>
                    </tr>
                <?php endforeach ?>
                </table>
            </fieldset>
            <?php if($this->isSaleable()):?>
                <div class="buttons-set">
                    <button type="button" title="<?php echo __('Add All to Cart') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/allcart', array('_current'=>true)) ?>')" class="button"><?php echo __('Add All to Cart') ?></button>
                </div>
            <?php endif;?>
        </form>
        <?php else: ?>
            <p><?php echo __('Wish List is empty now.') ?></p>
        <?php endif ?>
    </div>
</div>
