<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Wishlist\Block\Customer\Wishlist */
?>
<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <div class="my-wishlist">
        <div class="page-title title-buttons">
            <h1><?php echo $this->getTitle(); ?></h1>
        </div>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

        <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>" method="post">
            <?php echo $this->getChildHtml('top'); ?>
            <fieldset>
                <?php if ($this->hasWishlistItems()): ?>
                    <?php echo $this->getBlockHtml('formkey');?>
                    <?php $this->getChildBlock('items')->setItems($this->getWishlistItems()); ?>
                    <?php echo $this->getChildHtml('items');?>
                <?php else: ?>
                    <p class="wishlist-empty"><?php echo __('You have no items in your wish list.') ?></p>
                <?php endif ?>
                <div class="buttons-set">
                    <?php echo $this->getChildHtml('control_buttons');?>
                </div>
            </fieldset>
        </form>

        <script type="text/javascript">
        //<![CDATA[
        var wishlistForm = new Validation($('wishlist-view-form'));
        function addAllWItemsToCart() {
            var url = '<?php echo $this->getUrl('*/*/allcart', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>';
            var separator = (url.indexOf('?') >= 0) ? '&' : '?';
            $$('#wishlist-view-form .qty').each(
                function (input, index) {
                    url += separator + input.name + '=' + encodeURIComponent(input.value);
                    separator = '&';
                }
            );
            setLocation(url);
        }
        //]]>
        </script>
    </div>
    <?php echo $this->getChildHtml('bottom'); ?>
<?php endif ?>
