<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    Mage
 * @package     Mage_Captcha
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Captcha interface
 *
 * @category   Mage
 * @package    Mage_Captcha
 * @author     Magento Core Team <core@magentocommerce.com>
 */
interface Mage_Captcha_Model_Interface
{
    /**
     * Generates captcha
     *
     * @abstract
     * @return void
     */
    public function generate();

    /**
     * Checks whether word entered by user corresponds to the one generated by generate()
     *
     * @abstract
     * @param string $word
     * @return void
     */
    public function isCorrect($word);


 /**
     * Whether to respect case while checking the answer
     *
     * @return bool
     */
    public function isCaseSensitive();


    /**
     * Get captcha image base URL
     *
     * @return string
     */
    public function getImgUrl();


     /**
     * Return full URL to captcha image
     *
     * @return string
     */
    public function getImgSrc();

    /**
     * Returns session instance
     *
     * @return Captcha_Zend_Model_Session
     */
    public function getSession();

    /**
     * Returns Captcha Width
     *
     * @return string
     */
    public function getWidth();

    /**
     * Returns Captcha Height
     *
     * @return string
     */
    public function getHeight();


    /**
     * Returns Captcha Height
     *
     * @return string
     */
    public function getImgAlt();

    /**
     * Returns Template Path
     *
     * @return string
     */
    public function getTemplatePath();
}
