<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this Enterprise_Staging_Block_Adminhtml_Log_View_Information_Staging
 */
?>
<div class="information-create">
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo Mage::helper('Enterprise_Staging_Helper_Data')->__('Website Mapping') ?></h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                    <tr>
                        <td><?php echo $this->getMasterWebsiteName() ?></td>
                        <td>&nbsp;-&gt;&nbsp;<?php echo $this->getStagingWebsiteName() ?></td>
                    </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo Mage::helper('Enterprise_Staging_Helper_Data')->__('Store View Mapping') ?></h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                    <?php $_map = $this->getCreateStoreViewsMap() ?>
                    <?php if (is_string($_map)): ?>
                    <tr>
                        <td><?php echo $_map ?></td>
                    </tr>
                    <?php else:?>
                    <?php foreach ($_map as $view): ?>
                    <tr>
                        <td><?php echo $view['name'] ?></td>
                    </tr>
                    <?php endforeach; ?>
                    <?php endif; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account"><?php echo Mage::helper('Enterprise_Staging_Helper_Data')->__('Items') ?></h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                    <?php $_items = $this->getItems() ?>
                    <?php if (is_array($_items)) :?>
                    <?php foreach ($this->getItems() as $item): ?>
                    <tr>
                        <td colspan="2"><?php echo $item['label']?></td>
                    </tr>
                    <?php endforeach; ?>
                    <?php else:?>
                    <tr>
                        <td colspan="2"><?php echo $_items?></td>
                    </tr>
                    <?php endif; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
