<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var $this Enterprise_Staging_Block_Adminhtml_Log_View_Information_Staging
 */
?>
<div class="information-rollback">
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo Mage::helper('Enterprise_Staging_Helper_Data')->__('Target') ?></h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                    <?php foreach ($this->getTargetWebsites() as $website): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('Enterprise_Staging_Helper_Data')->__('Website') ?></label></td>
                        <td>
                            <?php echo $website->getName() ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4><?php echo Mage::helper('Enterprise_Staging_Helper_Data')->__('Items') ?></h4>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                    <?php foreach ($this->getItems() as $item): ?>
                    <tr>
                        <td colspan="2">
                            <?php echo $item['label']?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>
