<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_GoogleAnalytics_Block_Ga */ ?>
<?php if (!$this->helper('Magento_Core_Helper_Cookie')->isUserNotAllowSaveCookie()): ?>
<?php $accountId = $this->getConfig(Magento_GoogleAnalytics_Helper_Data::XML_PATH_ACCOUNT) ?>
<!-- BEGIN GOOGLE ANALYTICS CODEs -->
<script type="text/javascript">
//<![CDATA[
    var _gaq = _gaq || [];
    <?php echo $this->getPageTrackingCode($accountId) ?>
    <?php echo $this->getOrdersTrackingCode() ?>

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
//]]>
</script>
<!-- END GOOGLE ANALYTICS CODE -->
<?php endif; ?>
