<?if(!empty($collection)):?>
<table cellspacing="0" class="data">
    <?foreach ($columns as $column):?>
    <col <?=$column->toString('align="{{align}}" width="{{width}}"')?>/>
    <?endforeach;?>
    <thead>
		<tr>
        <?foreach ($columns as $column):?>
            <th><?=$column->getHeader()?></th>
        <?endforeach;?>
		</tr>
	</thead>
	<tbody>
    <?foreach ($collection as $_index=>$_item):?>
        <tr>
        <?foreach ($columns as $column):?>
            <td><?=$this->getRowField($_item, $column)?></td>
        <?endforeach;?>
        </tr>
    <?endforeach;?>
    </tbody>
</table>
<?endif?>