<?if(!empty($collection)):?>
<div id="<?=$this->getId()?>">
<div class="pager">
    Page 
    <select name="<?=$this->getvarNamePage()?>" onchange="<?=$this->getId()?>JsObject.loadByElement(this)">
    <?for($i=1; $i<=$collection->getLastPageNumber(); $i++):?>
        <?$_selected = ($i==$collection->getCurPage()) ? ' selected' : ''?>
        <option value="<?=$i?>"<?=$_selected?>><?=$i?></option>
    <?endfor;?>
    </select>
    of &nbsp;<b><?=$collection->getLastPageNumber()?></b>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    View  
    <select name="<?=$this->getvarNameLimit()?>" onchange="<?=$this->getId()?>JsObject.loadByElement(this)">
        <option value="5"<?if($collection->getPageSize()==5):?> selected<?endif;?>>5</option>
        <option value="20"<?if($collection->getPageSize()==20):?> selected<?endif;?>>20</option>
        <option value="30"<?if($collection->getPageSize()==30):?> selected<?endif;?>>30</option>
        <option value="50"<?if($collection->getPageSize()==50):?> selected<?endif;?>>50</option>
        <option value="100"<?if($collection->getPageSize()==100):?> selected<?endif;?>>100</option>
        <option value="200"<?if($collection->getPageSize()==200):?> selected<?endif;?>>200</option>
    </select>
    per page
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Total <b><?=$collection->getSize()?> records</b> found
</div>
<table cellspacing="0" class="data grid" id="<?=$this->getId()?>_table">
    <?foreach ($columns as $column):?>
    <col <?=$this->getColumnHtmlProperty($column)?>/>
    <?endforeach;?>
    <thead>
		<tr>
        <?foreach ($columns as $column):?>
            <th><?=$this->getColumnHeaderHtml($column)?></th>
        <?endforeach;?>
		</tr>
	</thead>
	<tbody>
    <?foreach ($collection as $_index=>$_item):?>
        <tr>
        <?foreach ($columns as $column):?>
            <td><?=$this->getRowField($_item, $column)?></td>
        <?endforeach;?>
        </tr>
    <?endforeach;?>
    </tbody>
</table>
</div>
<script type="text/javascript" language="javascript">
    <?=$this->getId()?>JsObject = new varienGrid('<?=$this->getId()?>', '<?=$this->getCurrentUrl()?>', '<?=$this->getVarNameSort()?>', '<?=$this->getVarNameDir()?>');
</script>
<?endif?>