<dl id="dl-<?=$id?>" class="accordion">
<?foreach ($sections as $section):?>
    <dt id="dt-<?=$id?>-<?=$section['id']?>">
        <a href="javascript:void(0)" onclick="$('dd-<?=$id?>-<?=$section['id']?>')?>">
            <img src="<?=$baseUrl?>skins/adminhtml/images/accordion_<?=!empty($section['active'])?'open':'closed'?>.png" alt="" class="v-mid"/>
        </a>
        <strong><?=$section['title']?></strong>
    </dt>
    <dd id="dd-<?=$id?>-<?=$section['id']?>" class="<?=!empty($section['active'])?'open':''?>">
        <?=$section['data']?>
    </dd>
<?endforeach?>
</dl>