<?if(!empty($tabs)):?>
<ul id="<?=$this->getId()?>" class="tabs">
<?foreach ($tabs as $_tab):?>
    <li>
        <a href="<?=$_tab->getUrl()?>" id="<?=$this->getTabId($_tab)?>" title="<?=$_tab->getTitle()?>" class="tab-item-link">
            <?=$_tab->getLabel()?>
        </a>
        <div id="<?=$this->getId()?>_<?=$_tab->getId()?>_content"><?=$_tab->getContent()?></div>
    </li>
<?endforeach;?>
</ul>
<script type="text/javascript" language="javascript">
    <?=$this->getId()?>JsTabs = new varienTabs('<?=$this->getId()?>', '<?=$this->getDestElementId()?>', '<?=$this->getActiveTabId()?>');
</script>
<?endif;?>