<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<form id="co-payment-form">
    <dl class="payment-methods">
        <?=$this->getChildHtml('methods')?>
    </dl>
</form>
<div class="form-buttons">
    <p class="required">* Required Fields</p>
    <span id="payment-please-wait" style="display:none;" class="opc-please-wait">
        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; Loading next step... &nbsp; 
    </span>
    <span id="payment-buttons-container">
        <button class="form-button" onclick="checkout.back()"><span><?=__('Back')?></span></button>
        <button class="form-button" onclick="payment.save()"><span><?=__('Continue')?></span></button>
    </span>
</div>

<script type="text/javascript">
    var payment = new Payment('co-payment-form', '<?=$this->getUrl('checkout/onepage/savePayment')?>');
    payment.currentMethod = "<?=$this->getPayment()->getMethod()?>";
</script>
