<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            rememberMePopup: [
                '<?php echo $this->getViewFileUrl('Magento_Persistent::remember-me-popup.js')?>'
            ]
        });
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>
