<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_Theme
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Wysiwyg Images content template
 *
 * @var $this Mage_Theme_Block_Adminhtml_Wysiwyg_Files_Content
 */
?>
<?php echo $this->getChildHtml('editor_files.js') ?>

<div class="content-header skip-header" id="content_header">
    <table cellspacing="0">
        <tr>
            <td><h3 id="content_header_text"><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>

<div id="contents-uploader"><?php echo $this->getChildHtml('editor_files.uploader') ?></div>
<div id="contents"></div>
<div id="contents-newfolder" class="no-display"><?php echo $this->getChildHtml('editor_files.newfolder') ?></div>
