<?php
/**
 * Obsolete methods
 *
 * Format: array(<method_name = ''>[, <class_scope> = ''[, <replacement>]])
 *
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
return array(
    array('__get', 'Magento_Object'),
    array('__set', 'Magento_Object'),
    array('_addItem', 'Magento_Page_Block_Html_Head'),
    array('_addMinimalPrice', 'Magento_Catalog_Model_Resource_Product_Collection'),
    array('_addTaxPercents', 'Magento_Catalog_Model_Resource_Product_Collection'),
    array('_afterSaveCommit', 'Magento_Core_Model_Abstract'),
    array('_afterSetConfig', 'Magento_Eav_Model_Entity_Abstract'),
    array('_aggregateByOrderCreatedAt', 'Magento_SalesRule_Model_Resource_Report_Rule'),
    array('_amountByCookies', 'Magento_Sendfriend_Model_Sendfriend'),
    array('_amountByIp', 'Magento_Sendfriend_Model_Sendfriend'),
    array('_applyClassRewrites', 'Magento_Core_Model_Config'),
    array('_applyCustomDesignSettings'),
    array('_applyCustomizationFiles', 'Magento_Core_Model_Theme'),
    array('_applyDesign', 'Magento_Catalog_Model_Design'),
    array('_applyDesignRecursively', 'Magento_Catalog_Model_Design'),
    array('_avoidDoubleTransactionProcessing'),
    array('_beforeChildToHtml'),
    array('_bytesToMbytes', 'Magento_Catalog_Model_Product_Option_Type_File'),
    array('_calculatePrice', 'Magento_Sales_Model_Quote_Item_Abstract'),
    array('_canBeStoreCodeInUrl', 'Magento_Core_Controller_Request_Http'),
    array('_canShowField', 'Magento_Backend_Block_System_Config_Form'),
    array('_canUseCacheForInit', 'Magento_Core_Model_Config'),
    array('_canUseLocalModules'),
    array('_checkCookieStore', 'Magento_Core_Model_App'),
    array('_checkGetStore', 'Magento_Core_Model_App'),
    array('_checkUrlSettings', 'Magento_Adminhtml_Controller_Action'),
    array('_collectOrigData', 'Magento_Catalog_Model_Resource_Abstract'),
    array('_decodeInput', 'Magento_Adminhtml_Controller_Catalog_Product'),
    array('_emailOrderConfirmation', 'Magento_Checkout_Model_Type_Abstract'),
    array('_escapeValue', 'Magento_Adminhtml_Block_Widget_Grid_Column_Filter_Abstract'),
    array('_extractData', 'Magento_ObjectManager_Config_Reader_Dom'),
    array('_filterPostData', 'Magento_Adminhtml_Controller_Catalog_Product_Attribute'),
    array('_generateCssHtml', 'Magento_Page_Block_Html_Head'),
    array('_generateJsHtml', 'Magento_Page_Block_Html_Head'),
    array('_getAddressTaxRequest', 'Magento_Tax_Model_Sales_Total_Quote_Shipping'),
    array('_getAggregationPerStoreView'),
    array('_getAttributeFilterBlockName'),
    array('_getAttributeFilterBlockName', 'Magento_Catalog_Block_Layer_View'),
    array('_getAttributeFilterBlockName', 'Magento_CatalogSearch_Block_Layer'),
    array('_getAvailable', 'Magento_GiftMessage_Model_Observer'),
    array('_getBytesIniValue', 'Magento_Catalog_Model_Product_Option_Type_File'),
    array('_getCacheId', 'Magento_Core_Model_App'),
    array('_getCacheKey', 'Magento_Catalog_Model_Layer_Filter_Price'),
    array('_getCacheLockId', 'Magento_Core_Model_Config'),
    array('_getCacheTags', 'Magento_Core_Model_App'),
    array('_getChildHtml'),
    array('_getCollapseState', 'Magento_Backend_Block_System_Config_Form_Fieldset', '_isCollapseState'),
    array('_getCollectionNames', 'Magento_Adminhtml_Controller_Report_Sales'),
    array('_getConnenctionType', 'Magento_Install_Model_Installer_Db'),
    array('_getDateFromToHtml', 'Magento_ImportExport_Block_Adminhtml_Export_Filter'),
    array('_getDeclaredModuleFiles', 'Magento_Core_Model_Config'),
    array('_getDom', 'Magento_Backend_Model_Menu_Config'),
    array('_getExistingBasePopularity'),
    array('_getFieldTableAlias', 'Magento_Newsletter_Model_Resource_Subscriber_Collection'),
    array('_getForeignKeyName', 'Magento_DB_Adapter_Pdo_Mysql'),
    array('_getGiftmessageSaveModel', 'Magento_Adminhtml_Block_Sales_Order_Create_Search_Grid'),
    array('_getGlobalAggregation'),
    array('_getGroupByDateFormat', 'Magento_Log_Model_Resource_Visitor_Collection'),
    array('_getIdAttributes', 'Magento_ObjectManager_Config_Reader_Dom'),
    array('_getInitialXml', 'Magento_ObjectManager_Config_Reader_Dom'),
    array('_getInputHtml', 'Magento_ImportExport_Block_Adminhtml_Export_Filter'),
    array('_getLabelForStore', 'Magento_Catalog_Model_Resource_Eav_Attribute'),
    array('_getMultiSelectHtml', 'Magento_ImportExport_Block_Adminhtml_Export_Filter'),
    array('_getNumberFromToHtml', 'Magento_ImportExport_Block_Adminhtml_Export_Filter'),
    array('_getPathInScope', 'Magento_Core_Model_Config'),
    array('_getPriceFilter', 'Magento_Catalog_Block_Layer_View'),
    array('_getProcessor', 'Magento_Core_Model_Cache'),
    array('_getProductQtyForCheck', 'Magento_CatalogInventory_Model_Observer'),
    array('_getPublicFileUrl', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_View_Url::getPublicFileUrl'),
    array('_getRangeByType', 'Magento_Log_Model_Resource_Visitor_Collection'),
    array('_getRecentProductsCollection'),
    array('_getScopeCode', 'Magento_Core_Model_Config'),
    array('_getSectionConfig', 'Magento_Core_Model_Config'),
    array('_getSelectHtml', 'Magento_ImportExport_Block_Adminhtml_Export_Filter'),
    array('_getSetData', 'Magento_Adminhtml_Block_Catalog_Product_Attribute_Set_Main'),
    array('_getSHAInSet', '', 'Magento_Ogone_Model_Api::getHash'),
    array('_getStoreByGroup', 'Magento_Core_Model_App'),
    array('_getStoreByWebsite', 'Magento_Core_Model_App'),
    array('_getStoreTaxRequest', 'Magento_Tax_Model_Sales_Total_Quote_Shipping'),
    array('_getUploadMaxFilesize', 'Magento_Catalog_Model_Product_Option_Type_File'),
    array('_hookQueries', 'Magento_Core_Model_Resource_Setup'),
    array('_importAddress', 'Magento_Paypal_Model_Api_Nvp'),
    array('_inheritDesign', 'Magento_Catalog_Model_Design'),
    array('_initBaseConfig', 'Magento_Core_Model_App'),
    array('_initCache', 'Magento_Core_Model_App'),
    array('_initCurrentStore', 'Magento_Core_Model_App'),
    array('_initFileSystem', 'Magento_Core_Model_App'),
    array('_initLogger', 'Magento_Core_Model_App'),
    array('_initModules', 'Magento_Core_Model_App'),
    array('_initModulesPreNamespaces', 'Magento_Core_Model_Config'),
    array('_initOrder', 'Magento_Shipping_Block_Tracking_Popup'),
    array('_initShipment', 'Magento_Shipping_Block_Tracking_Popup'),
    array('_initStores', 'Magento_Core_Model_App'),
    array('_inludeControllerClass', '', '_includeControllerClass'),
    array('_isApplyDesign', 'Magento_Catalog_Model_Design'),
    array('_isApplyFor', 'Magento_Catalog_Model_Design'),
    array('_isPositiveDecimalNumber', 'Magento_Shipping_Model_Resource_Carrier_Tablerate'),
    array('_isRuntimeValidated', 'Magento_ObjectManager_Config_Reader_Dom'),
    array('_loadCache', 'Magento_Backend_Model_Menu_Config'),
    array('_loadCache', 'Magento_Core_Model_Config'),
    array('_loadDeclaredModules', 'Magento_Core_Model_Config'),
    array('_loadInstallDate', 'Magento_Core_Model_Config'),
    array('_loadLocalConfig', 'Magento_Core_Model_Config'),
    array('_loadOldRates', 'Magento_Tax_Model_Resource_Setup'),
    array('_loadSectionCache', 'Magento_Core_Model_Config'),
    array('_needSubtractShippingTax'),
    array('_needSubtractTax'),
    array('_needToAddDummy'),
    array('_needToAddDummyForShipment'),
    array('_parseDescription', 'Magento_Sales_Model_Order_Pdf_Items_Abstract'),
    array('_parsePackageTheme', 'Magento_Widget_Model_Widget_Instance'),
    array('_parseXmlTrackingResponse', 'Magento_Usa_Model_Shipping_Carrier_Fedex'),
    array('_prepareCondition', 'Magento_CatalogSearch_Model_Advanced'),
    array('_prepareConfigurableProductData', 'Magento_ImportExport_Model_Export_Entity_Product'),
    array('_prepareConfigurableProductPrice', 'Magento_ImportExport_Model_Export_Entity_Product'),
    array('_prepareOptionsForCart', 'Magento_Catalog_Model_Product_Type_Abstract'),
    array('_preparePackageTheme', 'Magento_Widget_Model_Widget_Instance'),
    array('_processItem', 'Magento_Weee_Model_Total_Quote_Weee'),
    array('_processShippingAmount'),
    array('_processValidateCustomer', 'Magento_Checkout_Model_Type_Onepage'),
    array('_putCustomerIntoQuote', 'Magento_Adminhtml_Model_Sales_Order_Create'),
    array('_quoteRow', 'Magento_Backup_Model_Resource_Db'),
    array('_recollectItem', 'Magento_Tax_Model_Sales_Total_Quote_Subtotal'),
    array('_removeCache', 'Magento_Core_Model_Config'),
    array('_resetItemPriceInclTax'),
    array('_saveCache', 'Magento_Backend_Model_Menu_Config'),
    array('_saveCache', 'Magento_Core_Model_Config'),
    array('_saveCustomerAfterOrder', 'Magento_Adminhtml_Model_Sales_Order_Create'),
    array('_saveCustomers', 'Magento_Adminhtml_Model_Sales_Order_Create'),
    array('_saveSectionCache', 'Magento_Core_Model_Config'),
    array('_sendUploadResponse', 'Magento_Adminhtml_Controller_Customer'),
    array('_sendUploadResponse', 'Magento_Adminhtml_Controller_Newsletter_Subscriber'),
    array('_setAttribteValue'),
    array('_shouldSkipProcessUpdates', 'Magento_Core_Model_App'),
    array('_sort', 'Magento_Backend_Model_Config_Structure_Converter'),
    array('_unhookQueries', 'Magento_Core_Model_Resource_Setup'),
    array('_updateMediaPathUseRewrites', 'Magento_Core_Model_Store', '_getMediaScriptUrl'),
    array('_usePriceIncludeTax'),
    array('addAllowedModules', 'Magento_Core_Model_Config'),
    array('addBackupedFilter'),
    array('addCartLink', 'Magento_Checkout_Block_Links'),
    array('addCheckoutLink', 'Magento_Checkout_Block_Links'),
    array('addConfigField', 'Magento_Core_Model_Resource_Setup'),
    array('addConstraint', 'Magento_DB_Adapter_Pdo_Mysql'),
    array('addCss', 'Magento_Page_Block_Html_Head'),
    array('addCssIe', 'Magento_Page_Block_Html_Head'),
    array('addCustomersToAlertQueueAction'),
    array('addCustomerToSegments'),
    array('addHandle', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('addItemRender', 'Magento_Adminhtml_Block_Sales_Items_Abstract'),
    array('addItemRender', 'Magento_Checkout_Block_Cart_Abstract'),
    array('addItemRender', 'Magento_Sales_Block_Items_Abstract'),
    array('addJs', 'Magento_Page_Block_Html_Head'),
    array('addJsIe', 'Magento_Page_Block_Html_Head'),
    array('addKey', 'Magento_DB_Adapter_Pdo_Mysql'),
    array('addLinkRel', 'Magento_Page_Block_Html_Head'),
    array('addModule', 'Magento_Core_Controller_Varien_Router_Base'),
    array('addObserver', 'Mage'),
    array('addRouter', 'Magento_Core_Controller_Varien_Front'),
    array('addOptionRenderer', 'Magento_Catalog_Block_Product_View_Options'),
    array('addPageHandles', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('addPagerLimit', 'Magento_Catalog_Block_Product_List_Toolbar'),
    array('addReviewSummaryTemplate', 'Magento_Catalog_Block_Product_Abstract'),
    array('addRowItemRender', 'Magento_Checkout_Block_Multishipping_Overview'),
    array('addSaleableFilterToCollection'),
    array('addSearchQfFilter'),
    array('addStoresFilter', 'Magento_Poll_Model_Resource_Poll_Collection'),
    array('addTemplateData', 'Magento_Newsletter_Model_Queue'),
    array('addToAlersAction'),
    array('addToChildGroup'),
    array('addUpdate', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('addVisibleFilterToCollection', 'Magento_Catalog_Model_Product_Status'),
    array('addVisibleInCatalogFilterToCollection', '',
        '$collection->setVisibility(Magento_Catalog_Model_Product_Visibility->getVisibleInCatalogIds());'
    ),
    array('addVisibleInSearchFilterToCollection', '',
        '$collection->setVisibility(Magento_Catalog_Model_Product_Visibility->getVisibleInSearchIds());'
    ),
    array('addVisibleInSiteFilterToCollection', '',
        '$collection->setVisibility(Magento_Catalog_Model_Product_Visibility->getVisibleInSiteIds());'
    ),
    array('addWishlistLink', 'Magento_Wishlist_Block_Links'),
    array('addWishListSortOrder', 'Magento_Wishlist_Model_Resource_Item_Collection'),
    array('applyAllDataUpdates', 'Magento_Core_Model_Resource_Setup'),
    array('applyAllUpdates', 'Magento_Core_Model_Resource_Setup'),
    array('applyDesign', 'Magento_Catalog_Model_Design'),
    array('asArray', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('asSimplexml', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('asString', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('authAdmin'),
    array('authFailed', '', 'Magento_Core_Helper_Http::failHttpAuthentication()'),
    array('authFrontend'),
    array('authValidate', '', 'Magento_Core_Helper_Http::getHttpAuthCredentials()'),
    array('baseInit', 'Magento_Core_Model_App'),
    array('bundlesAction', 'Magento_Adminhtml_Controller_Catalog_Product'),
    array('calcTaxAmount', 'Magento_Sales_Model_Quote_Item_Abstract'),
    array('callbackQueryHook', 'Magento_Core_Model_Resource_Setup'),
    array('canCreateUser', 'Magento_User_Model_Resource_User'),
    array('canPrint', 'Magento_Checkout_Block_Onepage_Success'),
    array(
        'canTestHeaders',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::canTestHeaders'
    ),
    array('catalogCategoryChangeProducts', 'Magento_Catalog_Model_Product_Flat_Observer'),
    array('catalogEventProductCollectionAfterLoad', 'Magento_GiftMessage_Model_Observer'),
    array('catalogProductLoadAfter', 'Magento_Bundle_Model_Observer'),
    array('changeLocaleAction', 'Magento_Adminhtml_Controller_Index'),
    array('chechAllowedExtension'),
    array('checkConfigurableProducts', 'Magento_Eav_Model_Resource_Entity_Attribute_Collection'),
    array('checkDatabase', 'Magento_Install_Model_Installer_Db'),
    array('checkDateTime', 'Magento_Core_Model_Date'),
    array('chooseTemplate', 'Mage_Checkout_Block_Cart'),
    array('cleanCache', 'Magento_Core_Model_Config'),
    array('cleanDbRow', 'Magento_Core_Model_Resource'),
    array('cleanMergedJsCss', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_MergeService'),
    array('cleanMergedJsCss', 'Magento_Core_Model_Design_Package_Proxy', 'Magento_Core_Model_Page_Asset_MergeService'),
    array(
        'cleanMergedJsCss',
        'Magento_Core_Model_Design_PackageInterface',
        'Magento_Core_Model_Page_Asset_MergeService'
    ),
    array('cleanVarFolder', '', 'Magento_Io_File::rmdirRecursive()'),
    array('cleanVarSubFolders', '', 'glob() on Mage::getBaseDir(Magento_Core_Model_App_Dir::VAR_DIR)'),
    array('cloneIndexTable', 'Magento_Index_Model_Resource_Abstract'),
    array('collectRoutes', 'Magento_Backend_Controller_Router_Default'),
    array('collectRoutes', 'Magento_Core_Controller_Varien_Router_Base'),
    array('composeLocaleHierarchy', 'Magento_Core_Helper_Translate'),
    array('convertOldTaxData', 'Magento_Tax_Model_Resource_Setup'),
    array('convertOldTreeToNew', 'Magento_Catalog_Model_Resource_Setup'),
    array('countChildren', 'Magento_Core_Block_Abstract'),
    array('crear'),
    array('createDirIfNotExists', '', 'mkdir()'),
    array('createOrderItem', 'Magento_CatalogInventory_Model_Observer'),
    array('debugRequest', 'Magento_Paypal_Model_Api_Standard'),
    array('deleteAction', 'Magento_Adminhtml_Controller_Catalog_Product'),
    array('deleteConfig', 'Magento_Core_Model_Config'),
    array('deleteProductPrices', 'Magento_Catalog_Model_Resource_Product_Attribute_Backend_Tierprice'),
    array('display', 'Magento_Image_Adapter_Abstract', 'getImage()'),
    array('displayFullSummary', 'Magento_Tax_Model_Config'),
    array('displayTaxColumn', 'Magento_Tax_Model_Config'),
    array('displayZeroTax', 'Magento_Tax_Model_Config'),
    array('drawItem', 'Magento_Catalog_Block_Navigation'),
    array('dropKey', 'Magento_DB_Adapter_Pdo_Mysql'),
    array('escapeJs', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config'),
    array('exportOrderedCsvAction'),
    array('exportOrderedExcelAction'),
    array('fetchItemsCount', 'Magento_Wishlist_Model_Resource_Wishlist'),
    array('fetchRuleRatesForCustomerTaxClass'),
    array('fetchUpdatesByHandle', 'Magento_Core_Model_Resource_Layout', 'Magento_Core_Model_Resource_Layout_Update'),
    array('flush', 'Magento_Core_Model_Cache', 'Magento_Cache_FrontendInterface::clean()'),
    array('flush', 'Magento_Core_Model_Cache_Proxy', 'Magento_Cache_FrontendInterface::clean()'),
    array('flush', 'Magento_Core_Model_CacheInterface', 'Magento_Cache_FrontendInterface::clean()'),
    array('forsedSave'),
    array('generateBlocks', '', 'generateElements()'),
    array('getAbsolutePath', '', 'normalizePath'),
    array('getAccount', 'Magento_GoogleAnalytics_Block_Ga'),
    array('getAclAssert', 'Magento_Admin_Model_Config'),
    array('getAclPrivilegeSet', 'Magento_Admin_Model_Config'),
    array('getAclResourceList', 'Magento_Admin_Model_Config'),
    array('getAclResourceTree', 'Magento_Admin_Model_Config'),
    array('getAddNewButtonHtml', 'Magento_Adminhtml_Block_Catalog_Product'),
    array('getAddNewButtonHtml', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('getAddToCartItemUrl', 'Magento_Wishlist_Block_Customer_Sidebar'),
    array('getAddToCartUrlBase64', '', '_getAddToCartUrl'),
    array('getAllEntityIds', 'Magento_Rss_Model_Resource_Order'),
    array('getAllEntityTypeCommentIds', 'Magento_Rss_Model_Resource_Order'),
    array('getAllOrderEntityIds', 'Magento_Rss_Model_Resource_Order'),
    array('getAllOrderEntityTypeIds', 'Magento_Rss_Model_Resource_Order'),
    array('getAnonSuffix'),
    array('getAttributesJson', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config', 'getAttributes'),
    array('getBaseTaxAmount', 'Magento_Sales_Model_Quote_Item_Abstract'),
    array('getBlockClassName', 'Magento_Core_Model_Config'),
    array('getButtonsHtml', 'Magento_Bundle_Block_Adminhtml_Catalog_Product_Edit_Tab_Bundle_Option_Search'),
    array('getCache', 'Magento_Core_Model_Config'),
    array('getCacheBetaTypes'),
    array('getChangeLocaleUrl', 'Magento_Adminhtml_Block_Page_Footer'),
    array('getCheckoutMehod', 'Magento_Checkout_Model_Type_Onepage'),
    array('getChildGroup', '', 'Magento_Core_Block_Abstract::getGroupChildNames()'),
    array('getConfig', 'Magento_Captcha_Helper_Data'),
    array('getConfig', 'Magento_Eav_Model_Entity_Attribute_Abstract'),
    array('getConfigDataModel', 'Magento_Core_Model_Config'),
    array('getContainers', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getControllerInstance', 'Mage'),
    array('getCustomerData', 'Magento_Adminhtml_Block_Sales_Order_Create_Form_Account'),
    array('getDataForSave', 'Magento_Wishlist_Model_Item'),
    array('getDataMaxSize'),
    array('getDataMaxSizeInBytes', 'Magento_Adminhtml_Block_Media_Uploader', 'Magento_File_Size::getMaxFileSize()'),
    array('getDbAdapter', 'Magento_Core_Model_Cache'),
    array('getDbAdapter', 'Magento_Core_Model_Cache_Proxy'),
    array('getDbAdapter', 'Magento_Core_Model_CacheInterface'),
    array(
        'getDbVendorName',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getDbVendorName'
    ),
    array('getDebug', 'Magento_Ogone_Model_Api'),
    array('getDebug', 'Magento_Paypal_Model_Api_Abstract'),
    array('getDefaultBasePath', 'Magento_Core_Model_Store'),
    array('getDeleteUrl', 'Magento_Adminhtml_Block_Catalog_Product_Edit'),
    array('getDesign', 'Mage'),
    array('getDirectOutput', 'Magento_Core_Model_Layout'),
    array('getDistroServerVars', 'Magento_Core_Model_Config', 'getDistroBaseUrl'),
    array('getElementClass', 'Magento_Core_Model_Layout_Update'),
    array('getEntityIdsToIncrementIds', 'Magento_Rss_Model_Resource_Order'),
    array('getEntityTypeIdsToTypes', 'Magento_Rss_Model_Resource_Order'),
    array('getEventConfig', 'Magento_Core_Model_Config'),
    array('getEvents', 'Mage'),
    array('getExtensionsForCheck'),
    array('getFacets'),
    array('getFallbackTheme'),
    array('getFileLayoutUpdatesXml', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getFormated', '', "getFormated(true) -> format('html'), getFormated() -> format('text')"),
    array('getFormObject', 'Magento_Adminhtml_Block_Widget_Form'),
    array('getGiftmessageHtml', 'Magento_Adminhtml_Block_Sales_Order_View_Tab_Info'),
    array('getHandles', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getHeaderCssClass', 'Magento_Bundle_Block_Adminhtml_Catalog_Product_Edit_Tab_Bundle_Option_Search'),
    array('getHeaderText', 'Magento_Bundle_Block_Adminhtml_Catalog_Product_Edit_Tab_Bundle_Option_Search'),
    array('getHelperClassName', 'Magento_Core_Model_Config'),
    array('getHtmlFormat', 'Magento_Customer_Model_Address_Abstract'),
    array('getInitParam', 'Magento_Core_Model_App'),
    array(
        'getInitParams',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getAppInitParams'
    ),
    array('getInstallDate', 'Magento_Core_Model_Config'),
    array(
        'getInstallDir',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getAppInstallDir'
    ),
    array('getInstance', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::getInstance'),
    array('getIsActiveAanalytics', '', 'getOnsubmitJs'),
    array('getIsAjaxRequest', 'Magento_Core_Model_Translate_Inline'),
    array('getIsEngineAvailable'),
    array('getIsGlobal', 'Magento_Eav_Model_Entity_Attribute_Abstract'),
    array('getIsInStock', 'Magento_Checkout_Block_Cart_Item_Renderer'),
    array('getItemRender', 'Magento_Checkout_Block_Cart_Abstract'),
    array('getItemRendererInfo', 'Magento_Checkout_Block_Cart_Abstract'),
    array('getKeyList', 'Magento_DB_Adapter_Pdo_Mysql'),
    array('getLanguages', 'Magento_Install_Block_Begin'),
    array('getLanguageSelect', 'Magento_Adminhtml_Block_Page_Footer'),
    array('getLayoutFilename', '', 'getFilename'),
    array('getLifeTime', 'Magento_Core_Model_Resource_Session'),
    array('getLocaleBaseDir', 'Magento_Core_Model_Design_Package'),
    array('getMail', 'Magento_Newsletter_Model_Template'),
    array('getMaxQueryLenght'),
    array('getMaxUploadSize', 'Magento_ImportExport_Helper_Data', 'getMaxUploadSizeMessage'),
    array('getMenuConfigurationFiles', 'Magento_Backend_Model_Menu_Config'),
    array('getMenuItemLabel', 'Magento_Admin_Model_Config'),
    array('getMergedCssUrl'),
    array('getMergedJsUrl'),
    array('getMessageUserCreationProhibited', 'Magento_User_Model_Resource_User'),
    array('getMinQueryLenght'),
    array('getModelClassName', 'Magento_Core_Model_Config'),
    array('getModuleByName', 'Magento_Core_Controller_Varien_Router_Base'),
    array('getModuleConfigurationFiles', 'Magento_Core_Model_Config'),
    array('getModuleSetup', 'Magento_Core_Model_Config'),
    array('getNeedUsePriceExcludeTax', '', 'Magento_Tax_Model_Config::priceIncludesTax()'),
    array('getOneBalanceTotal'),
    array('getOptimalCssUrls', 'Magento_Core_Model_Design_Package_Proxy', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOptimalJsUrls', 'Magento_Core_Model_Design_Package_Proxy', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOptimalCssUrls', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOptimalJsUrls', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOption', 'Magento_Captcha_Helper_Data', 'Magento_Core_Model_Dir::getDir()'),
    array('getOptions', 'Magento_Core_Model_Config'),
    array(
        'getOptions',
        'Magento_Core_Model_Design_Source_Design',
        'Magento_Core_Model_Theme::getThemeCollectionOptionArray'
    ),
    array('getOptionValues', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('getOrderHtml', 'Magento_GoogleAnalytics_Block_Ga'),
    array('getOrderId', 'Magento_Checkout_Block_Onepage_Success'),
    array('getOrderId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getOriginalHeigh', '', 'getOriginalHeight'),
    array('getOriginalRequest', 'Magento_Core_Controller_Request_Http'),
    array('getPackage', 'Magento_Widget_Model_Widget_Instance'),
    array('getPackageTheme', 'Magento_Widget_Model_Widget_Instance', 'getThemeId'),
    array('getPageHandleLabel', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getPageHandleParents', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getPageHandles', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getPageHandlesHierarchy', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getPageHandleType', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('getPathAsArray', '', 'direct explode by /'),
    array('getPathFromArray', '', 'direct usage of /'),
    array('getPathVars', 'Magento_Core_Model_Config'),
    array('getParentProductIds', 'Magento_Catalog_Model_Resource_Product'),
    array('getPostMaxSize', 'Magento_Adminhtml_Block_Media_Uploader', 'Magento_File_Size::getPostMaxSize()'),
    array('getPriceFormatted', 'Magento_Adminhtml_Block_Customer_Edit_Tab_View_Sales'),
    array('getPrices', 'Magento_Bundle_Model_Product_Price'),
    array('getPricesDependingOnTax', 'Magento_Bundle_Model_Product_Price'),
    array('getPrintUrl', 'Magento_Checkout_Block_Onepage_Success'),
    array('getPrintUrl', 'Magento_Sales_Block_Order_Info'),
    array('getProductCollection', 'Magento_Wishlist_Helper_Data'),
    array('getProductCollection', 'Magento_Wishlist_Model_Wishlist'),
    array('getProductsNotInStoreIds'),
    array('getProfile', 'Magento_Convert_Container_Abstract'),
    array('getQuoteItem', 'Magento_Catalog_Model_Product_Option_Type_Default'),
    array('getQuoteItemOption', 'Magento_Catalog_Model_Product_Option_Type_Default'),
    array('getQuoteOrdersHtml', 'Magento_GoogleAnalytics_Block_Ga'),
    array('getRefererParamName', 'Magento_Adminhtml_Block_Page_Footer'),
    array('getRelativePath', 'Magento_Core_Model_Theme_Files'),
    array('getRemoveItemUrl', 'Magento_Wishlist_Block_Customer_Sidebar'),
    array('getReorderUrl', 'Magento_Sales_Block_Order_Info'),
    array(
        'getResourceConfig',
        'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceConfig'
    ),
    array('getResourceConfig', 'Magento_Core_Model_Config'),
    array('getResourceConnectionConfig', 'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceConnectionConfig'
    ),
    array('getResourceConnectionConfig', 'Magento_Core_Model_Config'),
    array('getResourceConnectionModel', 'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceConnectionModel'
    ),
    array('getResourceConnectionModel', 'Magento_Core_Model_Config'),
    array('getResourceModel', 'Magento_Core_Model_Config'),
    array('getResourceModelClassName', 'Magento_Core_Model_Config'),
    array('getResourceTypeConfig', 'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceTypeConfig'
    ),
    array('getResourceTypeConfig', 'Magento_Core_Model_Config'),
    array('getResTreeJson', 'Magento_User_Block_Role_Tab_Edit', 'getTree'),
    array('getResTreeJson', 'Magento_Adminhtml_Block_Api_Tab_Rolesedit', 'getTree'),
    array(
        'getRouterByRoute',
        'Magento_Core_Controller_Varien_Front',
        'Magento_Core_Model_RouterList::getRouterByFrontName'
    ),
    array('getRouterByFrontName', 'Magento_Core_Controller_Varien_Front',
        'Magento_Core_Model_RouterList::getRouterByFrontName'
    ),
    array('getRouters', 'Magento_Core_Model_Config'),
    array('getRowId', 'Magento_Adminhtml_Block_Sales_Order_Create_Customer_Grid'),
    array('getRowId', 'Magento_Adminhtml_Block_Widget_Grid'),
    array('getSaveTemplateFlag', 'Magento_Newsletter_Model_Queue'),
    array('getSectionNode', 'Magento_Core_Model_Config'),
    array('getSecure', 'Magento_Backend_Model_Url', 'isSecure'),
    array('getSecure', 'Magento_Core_Model_Url', 'isSecure'),
    array('getSelectionFinalPrice', 'Magento_Bundle_Model_Product_Price'),
    array('getShipId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getSortedChildBlocks', '', 'getChildNames() + $this->getLayout()->getBlock($name)'),
    array('getSortedChildren', '', 'getChildNames'),
    array('getSortedElements', 'Magento_Data_Form_Element_Fieldset', 'getElements'),
    array('getStatrupPageUrl'),
    array('getStore', 'Magento_Captcha_Helper_Data'),
    array('getStoreButtonsHtml', 'Magento_Backend_Block_System_Config_Tabs'),
    array('getStoreCodeFromPath', 'Magento_Core_Controller_Request_Http'),
    array('getStoreCurrency', 'Magento_Sales_Model_Order'),
    array('getStoreSelectOptions', 'Magento_Backend_Block_System_Config_Tabs'),
    array('getStores', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('getSuggestedZeroDate'),
    array('getSuggestionsByQuery'),
    array('getSysTmpDir'),
    array('getTablePrefix', 'Magento_Core_Model_Config'),
    array('getTagsByType', 'Magento_Core_Model_Cache', 'Magento_Cache_Frontend_Decorator_TagScope::getTag()'),
    array('getTagsByType', 'Magento_Core_Model_Cache_Proxy', 'Magento_Cache_Frontend_Decorator_TagScope::getTag()'),
    array('getTagsByType', 'Magento_Core_Model_CacheInterface', 'Magento_Cache_Frontend_Decorator_TagScope::getTag()'),
    array('getTaxAmount', 'Magento_Sales_Model_Quote_Item_Abstract'),
    array('getTaxRatesByProductClass', '', '_getAllRatesByProductClass'),
    array('getTemplateFilename', '', 'getFilename'),
    array('getTempVarDir', 'Magento_Core_Model_Config', 'Magento_Core_Model_Dir::getDir()'),
    array('getTestsDir', 'Magento_TestFramework_Bootstrap'),
    array('getTheme', 'Magento_Widget_Model_Widget_Instance'),
    array('getThemeOptions', 'Magento_Core_Model_Design_Source_Design',
        'Magento_Core_Model_Theme::getThemeCollectionOptionArray'
    ),
    array('getTotalModels', 'Magento_Sales_Model_Quote_Address'),
    array('getTrackId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getTrackingInfoByOrder', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getTrackingInfoByShip', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getTrackingInfoByTrackId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getTrackingPopUpUrlByOrderId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getTrackingPopUpUrlByShipId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getTrackingPopUpUrlByTrackId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getUnixProcessMemoryUsage', 'Magento_TestFramework_Helper_Memory', 'getRealMemoryUsage'),
    array('getUnprocessedEvents', 'Magento_Index_Model_Resource_Event',
        'Magento_Index_Model_EventRepository::getUnprocessed()'
    ),
    array('getUnprocessedEventsCollection', 'Magento_Index_Model_Process',
        'Magento_Index_Model_EventRepository::getUnprocessed()'
    ),
    array('getUploadMaxSize', 'Magento_Adminhtml_Block_Media_Uploader', 'Magento_File_Size::getUploadMaxSize()'),
    array('getUrlForReferer', 'Magento_Adminhtml_Block_Page_Footer'),
    array('getUseCacheFilename', 'Magento_Core_Model_App'),
    array('getValidator', 'Magento_SalesRule_Model_Observer'),
    array('getValidatorData', 'Magento_Core_Model_Session_Abstract', 'use _getSessionEnvironment method'),
    array('getValueTable'),
    array('getVarDir', 'Magento_Core_Model_Config', 'Magento_Core_Model_Dir::getDir()'),
    array('getViewOrderUrl', 'Magento_Checkout_Block_Onepage_Success'),
    array('getWatermarkHeigth', '', 'getWatermarkHeight'),
    array('getWebsite', 'Magento_Captcha_Helper_Data'),
    array('getWidgetSupportedBlocks', 'Magento_Widget_Model_Widget_Instance'),
    array('getWidgetSupportedTemplatesByBlock', 'Magento_Widget_Model_Widget_Instance'),
    array('getWinProcessMemoryUsage', 'Magento_TestFramework_Helper_Memory', 'getRealMemoryUsage'),
    array('hasItems', 'Magento_Wishlist_Helper_Data'),
    array('htmlEscape', '', 'escapeHtml'),
    array('imageAction', 'Magento_Catalog_Controller_Product'),
    array('implodeStreetAddress', 'Magento_Customer_Model_Address_Abstract'),
    array('importFromTextArray'),
    array('init', 'Mage'),
    array('init', 'Magento_Core_Controller_Varien_Front'),
    array('init', 'Magento_Core_Model_App'),
    array('init', 'Magento_Core_Model_Config'),
    array('init', 'Magento_Webapi_Controller_Front'),
    array('initCache'),
    array('initControllerRouters', 'Magento_Cms_Controller_Router'),
    array('initLabels', 'Magento_Catalog_Model_Resource_Eav_Attribute'),
    array('initSpecified', 'Magento_Core_Model_App'),
    array('insertProductPrice', 'Magento_Catalog_Model_Resource_Product_Attribute_Backend_Tierprice'),
    array('isAbsolutePath'),
    array('isAllowedGuestCheckout', 'Magento_Sales_Model_Quote'),
    array('isAutomaticCleaningAvailable', 'Magento_Cache_Backend_Eaccelerator'),
    array('isCheckoutAvailable', 'Magento_Checkout_Model_Type_Multishipping'),
    array('isFulAmountCovered'),
    array('isInstalled', 'Magento_Core_Model_App'),
    array('isLeyeredNavigationAllowed'),
    array('isLocalConfigLoaded', 'Magento_Core_Model_Config'),
    array('isModuleEnabled', 'Magento_Core_Model_Config', 'Magento_Core_Model_ModuleManager::isEnabled'),
    array('isReadablePopupObject'),
    array('isStaticFilesSigned', 'Magento_Core_Helper_Data'),
    array('isTemplateAllowedForApplication'),
    array('isThemeCompatible', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Theme::isThemeCompatible'),
    array('isUserSavingAllowed', 'Magento_User_Model_Resource_User'),
    array('isVerbose', 'Magento_Shell'),
    array('isWindowsOs', 'Magento_TestFramework_Helper_Memory'),
    array('load', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('loadBase', 'Magento_Core_Model_Config'),
    array('loadDb', 'Magento_Core_Model_Config'),
    array('loadDiConfiguration', 'Magento_Core_Model_Config'),
    array('loadEventObservers', 'Magento_Core_Model_Config'),
    array('loadLabel', 'Magento_Catalog_Model_Resource_Product_Type_Configurable_Attribute'),
    array('loadModules', 'Magento_Core_Model_Config'),
    array('loadModulesCache', 'Magento_Core_Model_Config'),
    array('loadModulesConfiguration', 'Magento_Core_Model_Config'),
    array('loadParentProductIds', 'Magento_Catalog_Model_Product'),
    array('loadPrices', 'Magento_Catalog_Model_Resource_Product_Type_Configurable_Attribute'),
    array('loadProductPrices', 'Magento_Catalog_Model_Resource_Product_Attribute_Backend_Tierprice'),
    array('lockOrderInventoryData', 'Magento_CatalogInventory_Model_Observer'),
    array('logEncryptionKeySave'),
    array('logInvitationSave'),
    array('map', 'Magento_ObjectManager_Config_Mapper_Dom', 'Magento_ObjectManager_Config_Mapper_Dom::convert'),
    array('mergeFiles', 'Magento_Core_Helper_Data', 'Magento_Core_Model_Page_Asset_MergeStrategyInterface'),
    array('mergeFiles', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_MergeStrategyInterface'),
    array(
        'mergeFiles',
        'Magento_Core_Model_Design_Package_Proxy',
        'Magento_Core_Model_Page_Asset_MergeStrategyInterface'
    ),
    array(
        'mergeFiles',
        'Magento_Core_Model_Design_PackageInterface',
        'Magento_Core_Model_Page_Asset_MergeStrategyInterface'
    ),
    array('order_success_page_view', 'Magento_GoogleAnalytics_Model_Observer'),
    array('orderedAction', 'Magento_Adminhtml_Controller_Report_Product'),
    array('output', 'Magento_Shell'),
    array('pageHandleExists', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('parseDateTime', 'Magento_Core_Model_Date'),
    array('postDispatchMyAccountSave'),
    array('postDispatchSystemImportExportRun'),
    array('prepareAddressInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareAttributesForSave', 'Magento_ImportExport_Model_Import_Entity_Product'),
    array('prepareCacheId', 'Magento_Core_Model_App'),
    array('prepareFeesInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareGoogleOptimizerScripts'),
    array('prepareRedirect', 'Magento_Core_Controller_Varien_Exception'),
    array('prepareItemInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('preparePriceAlertData', 'Magento_ProductAlert_Block_Product_View'),
    array('prepareProfilesGrid', 'Magento_Sales_Block_Recurring_Profiles'),
    array('prepareReferenceInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareRelatedOrdersFrontendGrid', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareScheduleInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareStockAlertData', 'Magento_ProductAlert_Block_Product_View'),
    array('prepareViewData', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('preprocess', 'Magento_Newsletter_Model_Template'),
    array('processBeacon'),
    array('processBeforeVoid', 'Magento_Payment_Model_Method_Abstract'),
    array('processRequest', 'Magento_Core_Model_Cache'),
    array('processSubst', 'Magento_Core_Model_Store'),
    array('productEventAggregate'),
    array('push', 'Magento_Catalog_Model_Product_Image'),
    array('rebuildCategoryLevels', 'Magento_Catalog_Model_Resource_Setup'),
    array('refundOrderItem', 'Magento_CatalogInventory_Model_Observer'),
    array('regenerateSessionId', 'Magento_Core_Model_Session_Abstract'),
    array('reinitialize', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::reinitialize'),
    array('removeItem', 'Magento_Page_Block_Html_Head'),
    array('removeCustomerFromSegments'),
    array('removeHandle', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('removeParentCartLink', 'Magento_Checkout_Block_Links'),
    array('renderView', '', 'Magento_Core_Block_Template::_toHtml()'),
    array('revalidateCookie', 'Magento_Core_Model_Session_Abstract_Varien'),
    array('run', 'Mage'),
    array('runApp', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::runApp'),
    array('sales_order_afterPlace'),
    array('sales_quote_address_discount_item'),
    array('salesOrderPaymentPlaceEnd'),
    array('saveCache', 'Magento_Core_Model_Config'),
    array('saveConfig', 'Magento_Core_Model_Config'),
    array('saveOptions', 'Magento_Core_Model_Cache'),
    array('saveOptions', 'Magento_Core_Model_Cache_Proxy'),
    array('saveOptions', 'Magento_Core_Model_CacheInterface'),
    array('saveRow__OLD'),
    array('saveSegmentCustomersFromSelect'),
    array('saveUseCache'),
    array('send', 'Magento_Newsletter_Model_Template'),
    array('sendNewPasswordEmail'),
    array('setAnonSuffix'),
    array('setApplyFilters'),
    array('setAttributeSetExcludeFilter', 'Magento_Eav_Model_Resource_Entity_Attribute_Collection'),
    array('setBlockAlias'),
    array('setConfig', 'Magento_Captcha_Helper_Data'),
    array('setCurrentArea', 'Mage'),
    array('setCustomerId', 'Magento_Customer_Model_Resource_Address'),
    array('setInstance', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::setInstance'),
    array('setIsAjaxRequest', 'Magento_Core_Model_Translate_Inline'),
    array('setIsDeveloperMode', 'Mage', 'Initialization parameter of the application'),
    array('setNeedUsePriceExcludeTax', '', 'Magento_Tax_Model_Config::setPriceIncludesTax()'),
    array('setOption', 'Magento_Captcha_Helper_Data'),
    array('setOptions', 'Magento_Core_Model_Config'),
    array('setOrderId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('setPackageTheme', 'Magento_Widget_Model_Widget_Instance', 'setThemeId'),
    array('setParentBlock'),
    array('setProfile', 'Magento_Convert_Container_Abstract'),
    array('setSaveTemplateFlag', 'Magento_Newsletter_Model_Queue'),
    array('setScriptPath'),
    array('setScriptPath', 'Magento_Core_Block_Template'),
    array('setShipId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('setSortElementsByAttribute', 'Magento_Data_Form_Element_Fieldset'),
    array('setStore', 'Magento_Captcha_Helper_Data'),
    array('setTaxGroupFilter'),
    array('setTrackId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('setVarSubFolders'),
    array('setVerbose', 'Magento_Shell'),
    array('setWatermarkHeigth', '', 'setWatermarkHeight'),
    array('setWebsite', 'Magento_Captcha_Helper_Data'),
    array('shaCrypt', '', 'Magento_Ogone_Model_Api::getHash'),
    array('shaCryptValidation', '', 'Magento_Ogone_Model_Api::getHash'),
    array('shouldCustomerHaveOneBalance'),
    array('shouldShowOneBalance'),
    array('sortChildren'),
    array('substDistroServerVars', 'Magento_Core_Model_Config'),
    array('superGroupGridOnlyAction', 'Magento_Adminhtml_Controller_Catalog_Product'),
    array('toOptionArray', 'Magento_Cms_Model_Resource_Page_Collection'),
    array('toOptionArray', 'Magento_Sendfriend_Model_Sendfriend'),
    array('truncate', 'Magento_DB_Adapter_Pdo_Mysql'),
    array('unsetBlock'),
    array('updateCofigurableProductOptions', 'Magento_Weee_Model_Observer', 'updateConfigurableProductOptions'),
    array('updateTable', 'Magento_Core_Model_Resource_Setup'),
    array('urlEscape', '', 'escapeUrl'),
    array('useValidateHttpUserAgent', 'Magento_Core_Model_Session_Abstract'),
    array('useValidateHttpVia', 'Magento_Core_Model_Session_Abstract'),
    array('useValidateHttpXForwardedFor', 'Magento_Core_Model_Session_Abstract'),
    array('useValidateRemoteAddr', 'Magento_Core_Model_Session_Abstract'),
    array('validateDataArray', 'Magento_Convert_Container_Abstract'),
    array('validateFile', 'Magento_Core_Model_Design_Package'),
    array('validateOrder', 'Magento_Checkout_Model_Type_Onepage'),
    array('_prepareOptionValues', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('_getOptionValuesCollection', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array(' _prepareSystemAttributeOptionValues', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('_prepareUserDefinedAttributeOptionValues', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('getLabelValues', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('getStoreOptionValues', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('getAttributeObject', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('substractQtyFromQuotes', 'Magento_Sales_Model_Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogProductQuote::subtractQtyFromQuotes'
    ),
    array('markQuotesRecollectOnCatalogRules', 'Magento_Sales_Model_Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogPriceRule::dispatch'
    ),
    array(
        'catalogProductSaveAfter', 'Magento_Sales_Model_Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogProductQuote::catalogProductSaveAfter'
    ),
    array(
        'catalogProductStatusUpdate', 'Magento_Sales_Model_Observer',
        'Magento_Sales_Model_Observer_Backend_CatalogProductQuote::catalogProductStatusUpdate'
    ),
    array(
        'prepareProductEditFormRecurringProfile', 'Magento_Sales_Model_Observer',
        'Magento_Sales_Model_Observer_Backend_RecurringProfile_FormRenderer::render'
    ),
    array(
        'restrictAdminBillingAgreementUsage', 'Magento_Sales_Model_Observer',
        'Magento_Sales_Model_Observer_Backend_BillingAgreement::dispatch'
    ),
    array(
        'customerSaveAfter', 'Magento_Sales_Model_Observer',
        'Magento_Sales_Model_Observer_Backend_CustomerQuote::dispatch'
    ),
    array('_getUsers', 'Magento_Adminhtml_Block_Api_Role_Grid_User', 'getUsers'),
    array('_getGridHtml', 'Magento_Adminhtml_Block_Api_Tab_Rolesusers', 'getGridHtml'),
    array('_getSelectedRoles', 'Magento_Adminhtml_Block_Api_User_Edit_Tab_Roles', 'getSelectedRoles'),
    array('_getProduct', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config_Matrix', 'getProduct'),
    array('_getImageUploadUrl', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config_Matrix',
        'getImageUploadUrl'),
    array('_getProduct', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config_Simple', 'getProduct'),
    array('_getProduct', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config', 'getProduct'),
    array('_getProduct', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Settings', 'getProduct'),
    array('_getProduct', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Crosssell', 'getProduct'),
    array('_getProduct', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Related', 'getProduct'),
    array('_getProduct', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Upsell', 'getProduct'),
    array('_renderCellTemplate', 'Magento_Backend_Block_System_Config_Form_Field_Array_Abstract', 'renderCellTemplate'),
    array('_showSingle', 'Magento_Bundle_Block_Catalog_Product_View_Type_Bundle_Option', 'showSingle'),
    array('_getDefaultValues', 'Magento_Bundle_Block_Catalog_Product_View_Type_Bundle_Option', 'getDefaultValues'),
    array('_isSelected', 'Magento_Bundle_Block_Catalog_Product_View_Type_Bundle_Option', 'isSelected'),
    array('_getProduct', 'Magento_Catalog_Block_Product_Configurable_AssociatedSelector_Backend_Grid_ColumnSet',
        'getProduct'),
    array('_getProduct', 'Magento_CatalogInventory_Block_Stockqty_Abstract', 'getProduct'),
    array('_getProduct', 'Magento_CatalogInventory_Block_Qtyincrements', 'getProduct'),
    array('_getPageTrackingCode', 'Magento_GoogleAnalytics_Block_Ga', 'getPageTrackingCode'),
    array('_getOrdersTrackingCode', 'Magento_GoogleAnalytics_Block_Ga', 'getOrdersTrackingCode'),
    array('_toJson', 'Magento_GoogleShopping_Block_Adminhtml_Types_Edit_Attributes', 'jsonFormat'),
    array('_getUsers', 'Magento_User_Block_Role_Grid_User', 'getUsers'),
    array('_getGridHtml', 'Magento_User_Block_Role_Tab_Users', 'getGridHtml'),
    array('_getSelectedRoles', 'Magento_User_Block_User_Edit_Tab_Roles', 'getSelectedRoles'),
    array('_prepareSelect', 'Magento_Core_Model_Resource_Db_Collection_Abstract'),
    array('_prepareSelect', 'Varien_Data_Collection_Db'),
    array('castField', 'Magento_Core_Model_Resource_Helper_Mysql4'),
    array('getQueryUsingAnalyticFunction', 'Magento_Core_Model_Resource_Helper_Mysql4'),
    array('limitUnion', 'Magento_Core_Model_Resource_Helper_Mysql4'),
    array('_addLoadAttributesSelectFields', 'Magento_Catalog_Model_Resource_Abstract'),
    array('attributeSelectFields', 'Magento_Catalog_Model_Resource_Helper_Mysql4'),
    array('_addLoadAttributesSelectFields', 'Magento_Eav_Model_Entity_Abstract'),
    array('attributeSelectFields', 'Magento_Eav_Model_Resource_Helper_Mysql4'),
    array('prepareEavAttributeValue', 'Magento_Eav_Model_Resource_Helper_Mysql4'),
    array('prepareColumn', 'Magento_Eav_Model_Resource_Helper_Mysql4'),
    array('getInsertFromSelectUsingAnalytic', 'Magento_Eav_Model_Resource_Helper_Mysql4'),
    array('setOneRowLimit', 'Magento_Eav_Model_Resource_Helper_Mysql4'),
    array('getCastToIntExpression', 'Magento_Eav_Model_Resource_Helper_Mysql4'),
    array('_initMetaTags', 'Magento_Page_Block_Html_Head'),
    array('addMetaTag', 'Magento_Page_Block_Html_Head'),
    array('getDefaultMetaTags', 'Magento_Page_Block_Html_Head'),
    array('getMetaTags', 'Magento_Page_Block_Html_Head'),
    array('getMetaTagHtml', 'Magento_Page_Block_Html_Head'),
    array('addLink', 'Magento_Sales_Block_Order_Info'),
    array('checkLinks', 'Magento_Sales_Block_Order_Info'),
    array('getLinks', 'Magento_Sales_Block_Order_Info'),
    array('resetRegistry', 'Mage', 'use Magento_Core_Model_Registry'),
    array('register', 'Mage', 'use Magento_Core_Model_Registry'),
    array('unregister', 'Mage', 'use Magento_Core_Model_Registry'),
    array('registry', 'Mage', 'use Magento_Core_Model_Registry'),
);
