<?php
/**
 * Obsolete class attributes
 *
 * Format: array(<attribute_name>[, <class_scope> = ''[, <replacement>]])
 *
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
return array(
    array('_addresses', '\Magento\Customer\Model\Customer'),
    array('_addMinimalPrice', '\Magento\Catalog\Model\Resource\Product\Collection'),
    array('_alias', '\Magento\Core\Block\AbstractBlock'),
    array('_anonSuffix'),
    array('_appMode', '\Magento\Core\Model\ObjectManager\ConfigLoader'),
    array('_baseDirCache', '\Magento\Core\Model\Config'),
    array('_cacheConf'),
    array('_canUseLocalModules'),
    array('_checkedProductsQty', '\Magento\CatalogInventory\Model\Observer'),
    array('_children', '\Magento\Core\Block\AbstractBlock'),
    array('_childrenHtmlCache', '\Magento\Core\Block\AbstractBlock'),
    array('_childGroups', '\Magento\Core\Block\AbstractBlock'),
    array('_combineHistory'),
    array('_config', 'Magento_Core_Model_Design_Package'),
    array('_config', '\Magento\Core\Model\Logger', '_dirs'),
    array('_configModel', '\Magento\Backend\Model\Menu\DirectorAbstract'),
    array('_configuration', '\Magento\Index\Model\Lock\Storage', '_dirs'),
    array('_currency', '\Magento\GoogleCheckout\Model\Api\Xml\Checkout'),
    array('_currencyNameTable'),
    array('_customEtcDir', '\Magento\Core\Model\Config'),
    array('_designProductSettingsApplied'),
    array('_distroServerVars'),
    array('_entityIdsToIncrementIds'),
    array('_entityTypeIdsToTypes'),
    array('_factory', '\Magento\Backend\Model\Menu\Config'),
    array('_factory', '\Magento\Backend\Model\Menu\DirectorAbstract', '_commandFactory'),
    array('_isAnonymous'),
    array('_isFirstTimeProcessRun', '\Magento\SalesRule\Model\Validator'),
    array('_isRuntimeValidated', '\Magento\ObjectManager\Config\Reader\Dom'),
    array('_loadDefault', '\Magento\Core\Model\Resource\Store\Collection'),
    array('_loadDefault', '\Magento\Core\Model\Resource\Store\Group\Collection'),
    array('_loadDefault', '\Magento\Core\Model\Resource\Website\Collection'),
    array('_mapper', '\Magento\ObjectManager\Config\Reader\Dom'),
    array('_menu', '\Magento\Backend\Model\Menu\Builder'),
    array('_modulesReader', '\Magento\Core\Model\ObjectManager\ConfigLoader'),
    array('_moduleReader', '\Magento\Backend\Model\Menu\Config'),
    array('_option', '\Magento\Captcha\Helper\Data', '_dirs'),
    array('_options', '\Magento\Core\Model\Config', '\Magento\Core\Model\Dir'),
    array('_optionsMapping', null, 'Mage::getBaseDir($nodeKey)'),
    array('_order', '\Magento\Checkout\Block\Onepage\Success'),
    array('_order_id'),
    array('_parent', '\Magento\Core\Block\AbstractBlock'),
    array('_parentBlock', '\Magento\Core\Block\AbstractBlock'),
    array('_persistentCustomerGroupId'),
    array('_ratingOptionTable', '\Magento\Rating\Model\Resource\Rating\Option\Collection'),
    array('_readerFactory', '\Magento\Core\Model\ObjectManager\ConfigLoader'),
    array('_saveTemplateFlag', '\Magento\Newsletter\Model\Queue'),
    array('_searchTextFields'),
    array('_setAttributes', '\Magento\Catalog\Model\Product\Type\AbstractType'),
    array('_skipFieldsByModel'),
    array('_ship_id'),
    array('_shipTable', '\Magento\Shipping\Model\Resource\Carrier\Tablerate\Collection'),
    array('_sortedChildren'),
    array('_sortInstructions'),
    array('_storeFilter', '\Magento\Catalog\Model\Product\Type\AbstractType'),
    array('_substServerVars'),
    array('_track_id'),
    array('_varSubFolders', null, '\Magento\Core\Model\Dir'),
    array('_viewDir', '\Magento\Core\Block\Template', '_dirs'),
    array('decoratedIsFirst', null, 'getDecoratedIsFirst'),
    array('decoratedIsEven', null, 'getDecoratedIsEven'),
    array('decoratedIsOdd', null, 'getDecoratedIsOdd'),
    array('decoratedIsLast', null, 'getDecoratedIsLast'),
    array('static', '\Magento\Core\Model\Email\Template\Filter'),
    array('_useAnalyticFunction'),
);
