<?php
/**
 * Obsolete methods
 *
 * Format: array(<method_name = ''>[, <class_scope> = ''[, <replacement>[, <is_deprecated>]]])
 *
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
return array(
    array('__get', 'Magento\Object'),
    array('__set', 'Magento\Object'),
    array('_addItem', 'Magento\Page\Block\Html\Head'),
    array('_addLink', 'Magento_Customer_Block_Account_Link'),
    array('_addMinimalPrice', 'Magento\Catalog\Model\Resource\Product\Collection'),
    array('_addTaxPercents', 'Magento\Catalog\Model\Resource\Product\Collection'),
    array('_afterSaveCommit', 'Magento\Core\Model\AbstractModel'),
    array('_afterSetConfig', 'Magento\Eav\Model\Entity\AbstractEntity'),
    array('_aggregateByOrderCreatedAt', 'Magento\SalesRule\Model\Resource\Report\Rule'),
    array('_amountByCookies', 'Magento\Sendfriend\Model\Sendfriend'),
    array('_amountByIp', 'Magento\Sendfriend\Model\Sendfriend'),
    array('_applyClassRewrites', 'Magento\Core\Model\Config'),
    array('_applyCustomDesignSettings'),
    array('_applyCustomizationFiles', 'Magento\Core\Model\Theme'),
    array('_applyDesign', 'Magento\Catalog\Model\Design'),
    array('_applyDesignRecursively', 'Magento\Catalog\Model\Design'),
    array('_avoidDoubleTransactionProcessing'),
    array('_beforeChildToHtml'),
    array('_beforeMove', 'Magento_Catalog_Model_Resource_Category_Tree'),
    array('_bytesToMbytes', 'Magento\Catalog\Model\Product\Option\Type\File'),
    array('_calculatePrice', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('_canBeStoreCodeInUrl', 'Magento\Core\Controller\Request\Http'),
    array('_canShowField', 'Magento\Backend\Block\System\Config\Form'),
    array('_canUseCacheForInit', 'Magento\Core\Model\Config'),
    array('_canUseLocalModules'),
    array('_checkCookieStore', 'Magento\Core\Model\App'),
    array('_checkGetStore', 'Magento\Core\Model\App'),
    array('_checkUrlSettings', 'Magento\Adminhtml\Controller\Action'),
    array('_collectOrigData', 'Magento\Catalog\Model\Resource\AbstractResource'),
    array('_decodeInput', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('_emailOrderConfirmation', 'Magento\Checkout\Model\Type\AbstractType'),
    array('_escapeValue', 'Magento\Adminhtml\Block\Widget\Grid\Column\Filter\AbstractFilter'),
    array('_extractData', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_filterPostData', 'Magento\Adminhtml\Controller\Catalog\Product\Attribute'),
    array('_generateCssHtml', 'Magento\Page\Block\Html\Head'),
    array('_generateJsHtml', 'Magento\Page\Block\Html\Head'),
    array('_getAddressTaxRequest', 'Magento\Tax\Model\Sales\Total\Quote\Shipping'),
    array('_getAggregationPerStoreView'),
    array('_getAttributeFilterBlockName'),
    array('_getAttributeFilterBlockName', 'Magento\Catalog\Block\Layer\View'),
    array('_getAttributeFilterBlockName', 'Magento\CatalogSearch\Block\Layer'),
    array('_getAvailable', 'Magento\GiftMessage\Model\Observer'),
    array('_getBytesIniValue', 'Magento\Catalog\Model\Product\Option\Type\File'),
    array('_getCacheId', 'Magento\Core\Model\App'),
    array('_getCacheKey', 'Magento\Catalog\Model\Layer\Filter\Price'),
    array('_getCacheLockId', 'Magento\Core\Model\Config'),
    array('_getCacheTags', 'Magento\Core\Model\App'),
    array('_getChildHtml'),
    array('_getCollapseState', 'Magento\Backend\Block\System\Config\Form\Fieldset', '_isCollapseState'),
    array('_getCollectionNames', 'Magento\Adminhtml\Controller\Report\Sales'),
    array('_getConnenctionType', 'Magento\Install\Model\Installer\Db'),
    array('_getDateFromToHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getDeclaredModuleFiles', 'Magento\Core\Model\Config'),
    array('_getDom', 'Magento\Backend\Model\Menu\Config'),
    array('_getExistingBasePopularity'),
    array('_getFieldTableAlias', 'Magento\Newsletter\Model\Resource\Subscriber\Collection'),
    array('_getForeignKeyName', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('_getGiftmessageSaveModel', 'Magento\Adminhtml\Block\Sales\Order\Create\Search\Grid'),
    array('_getGlobalAggregation'),
    array('_getGroupByDateFormat', 'Magento\Log\Model\Resource\Visitor\Collection'),
    array('_getIdAttributes', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_getInitialXml', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_getInputHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getLabelForStore', 'Magento\Catalog\Model\Resource\Eav\Attribute'),
    array('_getMultiSelectHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getNumberFromToHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getPathInScope', 'Magento\Core\Model\Config'),
    array('_getPriceFilter', 'Magento\Catalog\Block\Layer\View'),
    array('_getProcessor', 'Magento\Core\Model\Cache'),
    array('_getProductQtyForCheck', 'Magento\CatalogInventory\Model\Observer'),
    array('_getPublicFileUrl', 'Magento_Core_Model_Design_Package', 'Magento\Core\Model\View\Url::getPublicFileUrl'),
    array('_getRangeByType', 'Magento\Log\Model\Resource\Visitor\Collection'),
    array('_getRecentProductsCollection'),
    array('_getScopeCode', 'Magento\Core\Model\Config'),
    array('_getSectionConfig', 'Magento\Core\Model\Config'),
    array('_getSelectHtml', 'Magento\ImportExport\Block\Adminhtml\Export\Filter'),
    array('_getSetData', 'Magento\Adminhtml\Block\Catalog\Product\Attribute\Set\Main'),
    array('_getSHAInSet', '', 'Magento\Ogone\Model\Api::getHash'),
    array('_getStoreByGroup', 'Magento\Core\Model\App'),
    array('_getStoreByWebsite', 'Magento\Core\Model\App'),
    array('_getStoreTaxRequest', 'Magento\Tax\Model\Sales\Total\Quote\Shipping'),
    array('_getUploadMaxFilesize', 'Magento\Catalog\Model\Product\Option\Type\File'),
    array('_hookQueries', 'Magento\Core\Model\Resource\Setup'),
    array('_importAddress', 'Magento\Paypal\Model\Api\Nvp'),
    array('_inheritDesign', 'Magento\Catalog\Model\Design'),
    array('_initBaseConfig', 'Magento\Core\Model\App'),
    array('_initCache', 'Magento\Core\Model\App'),
    array('_initCurrentStore', 'Magento\Core\Model\App'),
    array('_initFileSystem', 'Magento\Core\Model\App'),
    array('_initLogger', 'Magento\Core\Model\App'),
    array('_initModules', 'Magento\Core\Model\App'),
    array('_initModulesPreNamespaces', 'Magento\Core\Model\Config'),
    array('_initOrder', 'Magento\Shipping\Block\Tracking\Popup'),
    array('_initShipment', 'Magento\Shipping\Block\Tracking\Popup'),
    array('_initStores', 'Magento\Core\Model\App'),
    array('_inludeControllerClass', '', '_includeControllerClass'),
    array('_isApplyDesign', 'Magento\Catalog\Model\Design'),
    array('_isApplyFor', 'Magento\Catalog\Model\Design'),
    array('_isPositiveDecimalNumber', 'Magento\Shipping\Model\Resource\Carrier\Tablerate'),
    array('_isRuntimeValidated', 'Magento\ObjectManager\Config\Reader\Dom'),
    array('_loadCache', 'Magento\Backend\Model\Menu\Config'),
    array('_loadCache', 'Magento\Core\Model\Config'),
    array('_loadDeclaredModules', 'Magento\Core\Model\Config'),
    array('_loadInstallDate', 'Magento\Core\Model\Config'),
    array('_loadLocalConfig', 'Magento\Core\Model\Config'),
    array('_loadOldRates', 'Magento\Tax\Model\Resource\Setup'),
    array('_loadSectionCache', 'Magento\Core\Model\Config'),
    array('_needSubtractShippingTax'),
    array('_needSubtractTax'),
    array('_needToAddDummy'),
    array('_needToAddDummyForShipment'),
    array('_parseDescription', 'Magento\Sales\Model\Order\Pdf\Items\AbstractItems'),
    array('_parsePackageTheme', 'Magento\Widget\Model\Widget\Instance'),
    array('_parseXmlTrackingResponse', 'Magento\Usa\Model\Shipping\Carrier\Fedex'),
    array('_prepareCondition', 'Magento\CatalogSearch\Model\Advanced'),
    array('_prepareConfigurableProductData', 'Magento\ImportExport\Model\Export\Entity\Product'),
    array('_prepareConfigurableProductPrice', 'Magento\ImportExport\Model\Export\Entity\Product'),
    array('_prepareOptionsForCart', 'Magento\Catalog\Model\Product\Type\AbstractType'),
    array('_preparePackageTheme', 'Magento\Widget\Model\Widget\Instance'),
    array('_processItem', 'Magento\Weee\Model\Total\Quote\Weee'),
    array('_processShippingAmount'),
    array('_processValidateCustomer', 'Magento\Checkout\Model\Type\Onepage'),
    array('_putCustomerIntoQuote', 'Magento\Adminhtml\Model\Sales\Order\Create'),
    array('_quoteRow', 'Magento\Backup\Model\Resource\Db'),
    array('_recollectItem', 'Magento\Tax\Model\Sales\Total\Quote\Subtotal'),
    array('_removeCache', 'Magento\Core\Model\Config'),
    array('_removeLink', 'Magento_Customer_Block_Account_Link'),
    array('_resetItemPriceInclTax'),
    array('_saveCache', 'Magento\Backend\Model\Menu\Config'),
    array('_saveCache', 'Magento\Core\Model\Config'),
    array('_saveCustomerAfterOrder', 'Magento\Adminhtml\Model\Sales\Order\Create'),
    array('_saveCustomers', 'Magento\Adminhtml\Model\Sales\Order\Create'),
    array('_saveSectionCache', 'Magento\Core\Model\Config'),
    array('_sendUploadResponse', 'Magento\Adminhtml\Controller\Customer'),
    array('_sendUploadResponse', 'Magento\Adminhtml\Controller\Newsletter\Subscriber'),
    array('_setAttribteValue'),
    array('_shouldSkipProcessUpdates', 'Magento\Core\Model\App'),
    array('_sort', 'Magento\Backend\Model\Config\Structure\Converter'),
    array('_toHtml', 'Magento_Backend_Block_Widget_Container'),
    array('_unhookQueries', 'Magento\Core\Model\Resource\Setup'),
    array('_updateMediaPathUseRewrites', 'Magento\Core\Model\Store', '_getMediaScriptUrl'),
    array('_usePriceIncludeTax'),
    array('addAccountLink', 'Magento_Customer_Block_Account_Link'),
    array('addAllowedModules', 'Magento\Core\Model\Config'),
    array('addAuthLink', 'Magento_Customer_Block_Account_Link'),
    array('addBackupedFilter'),
    array('addCartLink', 'Magento_Checkout_Block_Links'),
    array('addCheckoutLink', 'Magento_Checkout_Block_Links'),
    array('addColumnInputName', 'Magento_Backend_Block_Widget_Grid_Serializer'),
    array('addConfigField', 'Magento\Core\Model\Resource\Setup'),
    array('addConstraint', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('addCss', 'Magento_Page_Block_Html_Head'),
    array('addCssIe', 'Magento_Page_Block_Html_Head'),
    array('addCustomersToAlertQueueAction'),
    array('addCustomerToSegments'),
    array('addHandle', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('addItemRender', 'Magento_Adminhtml_Block_Sales_Items_Abstract'),
    array('addItemRender', 'Magento_Checkout_Block_Cart_Abstract'),
    array('addItemRender', 'Magento_Sales_Block_Items_Abstract'),
    array('addJs', 'Magento_Page_Block_Html_Head'),
    array('addJsIe', 'Magento_Page_Block_Html_Head'),
    array('addKey', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('addLinkRel', 'Magento_Page_Block_Html_Head'),
    array('addLogInLink', 'Magento_Customer_Block_Account_Link'),
    array('addModule', 'Magento_Core_Controller_Varien_Router_Base'),
    array('addObserver', 'Mage'),
    array('addRouter', 'Magento_Core_Controller_Varien_Front'),
    array('addOptionRenderer', 'Magento_Catalog_Block_Product_View_Options'),
    array('addPageHandles', 'Magento_Core_Model_Layout_Update', 'Magento_Core_Model_Layout_Merge'),
    array('addPagerLimit', 'Magento_Catalog_Block_Product_List_Toolbar'),
    array('addRegisterLink', 'Magento_Customer_Block_Account_Link'),
    array('addReviewSummaryTemplate', 'Magento_Catalog_Block_Product_Abstract'),
    array('addRowItemRender', 'Magento_Checkout_Block_Multishipping_Overview'),
    array('addSaleableFilterToCollection'),
    array('addSearchQfFilter'),
    array('addStoresFilter', 'Magento\Poll\Model\Resource\Poll\Collection'),
    array('addTemplateData', 'Magento\Newsletter\Model\Queue'),
    array('addToAlersAction'),
    array('addToChildGroup'),
    array('addUpdate', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('addVisibleFilterToCollection', 'Magento\Catalog\Model\Product\Status'),
    array('addVisibleInCatalogFilterToCollection', '',
        '$collection->setVisibility(\Magento\Catalog\Model\Product\Visibility->getVisibleInCatalogIds());'
    ),
    array('addVisibleInSearchFilterToCollection', '',
        '$collection->setVisibility(\Magento\Catalog\Model\Product\Visibility->getVisibleInSearchIds());'
    ),
    array('addVisibleInSiteFilterToCollection', '',
        '$collection->setVisibility(\Magento\Catalog\Model\Product\Visibility->getVisibleInSiteIds());'
    ),
    array('addWishListSortOrder', 'Magento\Wishlist\Model\Resource\Item\Collection'),
    array('appendBundleSelectionData', 'Magento_Bundle_Model_Observer'),
    array('appendGiftcardAdditionalData', 'Magento_GiftCard_Model_Observer'),
    array('applyAllDataUpdates', 'Magento\Core\Model\Resource\Setup'),
    array('applyAllUpdates', 'Magento\Core\Model\Resource\Setup'),
    array('applyDesign', 'Magento\Catalog\Model\Design'),
    array('applyIndexChanges', 'Magento_Search_Model_Observer'),
    array('asArray', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('asSimplexml', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('asString', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('authAdmin'),
    array('authFailed', '', 'Magento\Core\Helper\Http::failHttpAuthentication()'),
    array('authFrontend'),
    array('authValidate', '', 'Magento\Core\Helper\Http::getHttpAuthCredentials()'),
    array('baseInit', 'Magento\Core\Model\App'),
    array('bundlesAction', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('calcTaxAmount', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('callbackQueryHook', 'Magento\Core\Model\Resource\Setup'),
    array('canCreateUser', 'Magento\User\Model\Resource\User'),
    array('canPrint', 'Magento\Checkout\Block\Onepage\Success'),
    array(
        'canTestHeaders',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::canTestHeaders'
    ),
    array('catalogCategoryChangeProducts', 'Magento\Catalog\Model\Product\Flat\Observer'),
    array('catalogEventProductCollectionAfterLoad', 'Magento\GiftMessage\Model\Observer'),
    array('catalogProductCompareClean', 'Magento_Catalog_Model_Observer'),
    array('catalogProductLoadAfter', 'Magento\Bundle\Model\Observer'),
    array('changeLocaleAction', 'Magento\Adminhtml\Controller\Index'),
    array('chechAllowedExtension'),
    array('checkConfigurableProducts', 'Magento_Eav_Model_Resource_Entity_Attribute_Collection'),
    array('checkDatabase', 'Magento_Install_Model_Installer_Db'),
    array('checkDateTime', 'Magento\Core\Model\Date'),
    array('chooseTemplate', 'Magento_Checkout_Block_Cart'),
    array('cleanCache', 'Magento_Core_Model_Config'),
    array('cleanDbRow', 'Magento_Core_Model_Resource'),
    array('cleanMergedJsCss', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_MergeService'),
    array('cleanMergedJsCss', 'Magento_Core_Model_Design_Package_Proxy', 'Magento_Core_Model_Page_Asset_MergeService'),
    array(
        'cleanMergedJsCss',
        'Magento_Core_Model_Design_PackageInterface',
        'Magento_Core_Model_Page_Asset_MergeService'
    ),
    array('cleanVarFolder', '', 'Magento_Io_File::rmdirRecursive()'),
    array('cleanVarSubFolders', '', 'glob() on Mage::getBaseDir(Magento_Core_Model_App_Dir::VAR_DIR)'),
    array('cloneIndexTable', 'Magento_Index_Model_Resource_Abstract'),
    array('collectRoutes', 'Magento_Backend_Controller_Router_Default'),
    array('collectRoutes', 'Magento_Core_Controller_Varien_Router_Base'),
    array('composeLocaleHierarchy', 'Magento_Core_Helper_Translate'),
    array('convertOldTaxData', 'Magento_Tax_Model_Resource_Setup'),
    array('convertOldTreeToNew', 'Magento_Catalog_Model_Resource_Setup'),
    array('copyFieldset', 'Magento_Core_Helper_Data', 'copyFieldsetToTarget'),
    array('copyQuoteFilesToOrderFiles', 'Magento_Catalog_Model_Product_Option_Observer'),
    array('countChildren', 'Magento_Core_Block_Abstract'),
    array('crear'),
    array('createDirIfNotExists', '', 'mkdir()'),
    array('createOrderItem', 'Magento\CatalogInventory\Model\Observer'),
    array('debugRequest', 'Magento\Paypal\Model\Api\Standard'),
    array('deleteAction', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('deleteConfig', 'Magento\Core\Model\Config'),
    array('deleteProductPrices', 'Magento\Catalog\Model\Resource\Product\Attribute\Backend\Tierprice'),
    array('display', 'Magento\Image\Adapter\AbstractAdapter', 'getImage()'),
    array('displayFullSummary', 'Magento\Tax\Model\Config'),
    array('displayTaxColumn', 'Magento\Tax\Model\Config'),
    array('displayZeroTax', 'Magento\Tax\Model\Config'),
    array('drawItem', 'Magento\Catalog\Block\Navigation'),
    array('dropKey', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('escapeJs', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config'),
    array('eventClean', 'Magento_Reports_Model_Event_Observer'),
    array('exportOrderedCsvAction'),
    array('exportOrderedExcelAction'),
    array('fetchItemsCount', 'Magento\Wishlist\Model\Resource\Wishlist'),
    array('fetchRuleRatesForCustomerTaxClass'),
    array('fetchUpdatesByHandle', 'Magento_Core_Model_Resource_Layout', 'Magento\Core\Model\Resource\Layout\Update'),
    array('flush', 'Magento\Core\Model\Cache', 'Magento\Cache\FrontendInterface::clean()'),
    array('flush', 'Magento\Core\Model\Cache\Proxy', 'Magento\Cache\FrontendInterface::clean()'),
    array('flush', 'Magento\Core\Model\CacheInterface', 'Magento\Cache\FrontendInterface::clean()'),
    array('forsedSave'),
    array('generateBlocks', '', 'generateElements()'),
    array('getAbsolutePath', '', 'normalizePath'),
    array('getAccount', 'Magento\GoogleAnalytics\Block\Ga'),
    array('getAclAssert', 'Magento_Admin_Model_Config'),
    array('getAclPrivilegeSet', 'Magento_Admin_Model_Config'),
    array('getAclResourceList', 'Magento_Admin_Model_Config'),
    array('getAclResourceTree', 'Magento_Admin_Model_Config'),
    array('getAddNewButtonHtml', 'Magento\Adminhtml\Block\Catalog\Product'),
    array('getAddNewButtonHtml', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getAddToCartItemUrl', 'Magento\Wishlist\Block\Customer\Sidebar'),
    array('getAddToCartUrlBase64', '', '_getAddToCartUrl'),
    array('getAllEntityIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAllEntityTypeCommentIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAllOrderEntityIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAllOrderEntityTypeIds', 'Magento\Rss\Model\Resource\Order'),
    array('getAnonSuffix'),
    array('getAttributesJson', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config', 'getAttributes'),
    array('getBaseTaxAmount', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('getBlockClassName', 'Magento\Core\Model\Config'),
    array('getButtonsHtml', 'Magento\Bundle\Block\Adminhtml\Catalog\Product\Edit\Tab\Bundle\Option\Search'),
    array('getCache', 'Magento\Core\Model\Config'),
    array('getCacheBetaTypes'),
    array('getChangeLocaleUrl', 'Magento\Adminhtml\Block\Page\Footer'),
    array('getCheckoutMehod', 'Magento\Checkout\Model\Type\Onepage'),
    array('getChildGroup', '', 'Magento\Core\Block\AbstractBlock::getGroupChildNames()'),
    array('getConfig', 'Magento\Captcha\Helper\Data'),
    array('getConfig', 'Magento\Eav\Model\Entity\Attribute\AbstractAttribute'),
    array('getConfigAsXml','Magento_Widget_Model_Widget'),
    array('getConfigDataModel', 'Magento\Core\Model\Config'),
    array('getContainers', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getControllerInstance', 'Mage'),
    array('getCustomerData', 'Magento\Adminhtml\Block\Sales\Order\Create\Form\Account'),
    array('getDataForSave', 'Magento\Wishlist\Model\Item'),
    array('getDataMaxSize'),
    array('getDataMaxSizeInBytes', 'Magento\Adminhtml\Block\Media\Uploader', 'Magento\File\Size::getMaxFileSize()'),
    array('getDbAdapter', 'Magento\Core\Model\Cache'),
    array('getDbAdapter', 'Magento\Core\Model\Cache\Proxy'),
    array('getDbAdapter', 'Magento\Core\Model\CacheInterface'),
    array(
        'getDbVendorName',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getDbVendorName'
    ),
    array('getDebug', 'Magento\Ogone\Model\Api'),
    array('getDebug', 'Magento\Paypal\Model\Api\AbstractApi'),
    array('getDefaultBasePath', 'Magento\Core\Model\Store'),
    array('getDeleteUrl', 'Magento\Adminhtml\Block\Catalog\Product\Edit'),
    array('getDesign', 'Mage'),
    array('getDirectOutput', 'Magento\Core\Model\Layout'),
    array('getDistroServerVars', 'Magento\Core\Model\Config', 'getDistroBaseUrl'),
    array('getElementClass', 'Magento\Core\Model\Layout\Update'),
    array('getEntityIdsToIncrementIds', 'Magento\Rss\Model\Resource\Order'),
    array('getEntityTypeIdsToTypes', 'Magento\Rss\Model\Resource\Order'),
    array('getEventConfig', 'Magento\Core\Model\Config'),
    array('getEvents', 'Mage'),
    array('getExtensionsForCheck'),
    array('getFacets'),
    array('getFallbackTheme'),
    array('getFileLayoutUpdatesXml', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getFormated', '', "getFormated(true) -> format('html'), getFormated() -> format('text')"),
    array('getFormObject', 'Magento\Adminhtml\Block\Widget\Form'),
    array('getGiftmessageHtml', 'Magento\Adminhtml\Block\Sales\Order\View\Tab\Info'),
    array('getHandles', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getHeaderCssClass', 'Magento\Bundle\Block\Adminhtml\Catalog\Product\Edit\Tab\Bundle\Option\Search'),
    array('getHeaderText', 'Magento\Bundle\Block\Adminhtml\Catalog\Product\Edit\Tab\Bundle\Option\Search'),
    array('getHelperClassName', 'Magento\Core\Model\Config'),
    array('getHtmlFormat', 'Magento\Customer\Model\Address\AbstractAddress'),
    array('getInitParam', 'Magento\Core\Model\App'),
    array(
        'getInitParams',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getAppInitParams'
    ),
    array('getInstallDate', 'Magento\Core\Model\Config'),
    array(
        'getInstallDir',
        'Magento_TestFramework_Bootstrap',
        'Magento_TestFramework_Helper_Bootstrap::getAppInstallDir'
    ),
    array('getInstance', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::getInstance'),
    array('getIsActiveAanalytics', '', 'getOnsubmitJs'),
    array('getIsAjaxRequest', 'Magento\Core\Model\Translate\Inline'),
    array('getIsEngineAvailable'),
    array('getIsGlobal', 'Magento\Eav\Model\Entity\Attribute\AbstractAttribute'),
    array('getIsInStock', 'Magento\Checkout\Block\Cart\Item\Renderer'),
    array('getItemRender', 'Magento\Checkout\Block\Cart\AbstractCart'),
    array('getItemRendererInfo', 'Magento_Checkout_Block_Cart_Abstract'),
    array('getKeyList', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('getLanguages', 'Magento\Install\Block\Begin'),
    array('getLanguageSelect', 'Magento\Adminhtml\Block\Page\Footer'),
    array('getLayoutFilename', '', 'getFilename'),
    array('getLifeTime', 'Magento\Core\Model\Resource\Session'),
    array('getLocaleBaseDir', 'Magento_Core_Model_Design_Package'),
    array('getMail', 'Magento\Newsletter\Model\Template'),
    array('getMaxQueryLenght'),
    array('getMaxUploadSize', 'Magento\ImportExport\Helper\Data', 'getMaxUploadSizeMessage'),
    array('getMenuConfigurationFiles', 'Magento\Backend\Model\Menu\Config'),
    array('getMenuItemLabel', 'Magento_Admin_Model_Config'),
    array('getMergedCssUrl'),
    array('getMergedJsUrl'),
    array('getMessageUserCreationProhibited', 'Magento\User\Model\Resource\User'),
    array('getMinQueryLenght'),
    array('getModelClassName', 'Magento_Core_Model_Config'),
    array('getModuleByName', 'Magento_Core_Controller_Varien_Router_Base'),
    array('getModuleConfigurationFiles', 'Magento_Core_Model_Config'),
    array('getModuleSetup', 'Magento_Core_Model_Config'),
    array('getNeedUsePriceExcludeTax', '', 'Magento_Tax_Model_Config::priceIncludesTax()'),
    array('getNode', 'Magento_Logging_Model_Config'),
    array('getOneBalanceTotal'),
    array('getOptimalCssUrls', 'Magento_Core_Model_Design_Package_Proxy', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOptimalJsUrls', 'Magento_Core_Model_Design_Package_Proxy', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOptimalCssUrls', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOptimalJsUrls', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_Merged'),
    array('getOption', 'Magento_Captcha_Helper_Data', 'Magento_Core_Model_Dir::getDir()'),
    array('getOptions', 'Magento_Core_Model_Config'),
    array(
        'getOptions',
        'Magento_Core_Model_Design_Source_Design',
        'Magento_Core_Model_Theme::getThemeCollectionOptionArray'
    ),
    array('getOptionValues', 'Magento_Eav_Block_Adminhtml_Attribute_Edit_Options_Abstract'),
    array('getOrderHtml', 'Magento_GoogleAnalytics_Block_Ga'),
    array('getOrderId', 'Magento_Checkout_Block_Onepage_Success'),
    array('getOrderId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getOriginalHeigh', '', 'getOriginalHeight'),
    array('getOriginalRequest', 'Magento\Core\Controller\Request\Http'),
    array('getPackage', 'Magento\Widget\Model\Widget\Instance'),
    array('getPackageTheme', 'Magento\Widget\Model\Widget\Instance', 'getThemeId'),
    array('getPageHandleLabel', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandleParents', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandles', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandlesHierarchy', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPageHandleType', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('getPathAsArray', '', 'direct explode by /'),
    array('getPathFromArray', '', 'direct usage of /'),
    array('getPathVars', 'Magento\Core\Model\Config'),
    array('getParentProductIds', 'Magento\Catalog\Model\Resource\Product'),
    array('getPostMaxSize', 'Magento\Adminhtml\Block\Media\Uploader', 'Magento\File\Size::getPostMaxSize()'),
    array('getPriceFormatted', 'Magento\Adminhtml\Block\Customer\Edit\Tab\View\Sales'),
    array('getPrices', 'Magento\Bundle\Model\Product\Price'),
    array('getPricesDependingOnTax', 'Magento\Bundle\Model\Product\Price'),
    array('getPrintUrl', 'Magento\Checkout\Block\Onepage\Success'),
    array('getPrintUrl', 'Magento\Sales\Block\Order\Info'),
    array('getProductCollection', 'Magento\Wishlist\Helper\Data'),
    array('getProductCollection', 'Magento\Wishlist\Model\Wishlist'),
    array('getProductsNotInStoreIds'),
    array('getProfile', 'Magento_Convert_Container_Abstract'),
    array('getQuoteItem', 'Magento_Catalog_Model_Product_Option_Type_Default'),
    array('getQuoteItemOption', 'Magento_Catalog_Model_Product_Option_Type_Default'),
    array('getQuoteOrdersHtml', 'Magento_GoogleAnalytics_Block_Ga'),
    array('getRefererParamName', 'Magento_Adminhtml_Block_Page_Footer'),
    array('getRelativePath', 'Magento_Core_Model_Theme_Files'),
    array('getRemoveItemUrl', 'Magento_Wishlist_Block_Customer_Sidebar'),
    array('getReorderUrl', 'Magento_Sales_Block_Order_Info'),
    array(
        'getResourceConfig',
        'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceConfig'
    ),
    array('getResourceConfig', 'Magento\Core\Model\Config'),
    array('getResourceConnectionConfig', 'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceConnectionConfig'
    ),
    array('getResourceConnectionConfig', 'Magento\Core\Model\Config'),
    array('getResourceConnectionModel', 'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceConnectionModel'
    ),
    array('getResourceConnectionModel', 'Magento\Core\Model\Config'),
    array('getResourceModel', 'Magento\Core\Model\Config'),
    array('getResourceModelClassName', 'Magento\Core\Model\Config'),
    array('getResourceTypeConfig', 'Magento_Config_Model_Config',
        'Magento_Config_Model_Config_Resource::getResourceTypeConfig'
    ),
    array('getResourceTypeConfig', 'Magento_Core_Model_Config'),
    array('getResTreeJson', 'Magento_User_Block_Role_Tab_Edit', 'getTree'),
    array('getResTreeJson', 'Magento_Adminhtml_Block_Api_Tab_Rolesedit', 'getTree'),
    array(
        'getRouterByRoute',
        'Magento_Core_Controller_Varien_Front',
        'Magento_Core_Model_RouterList::getRouterByFrontName'
    ),
    array('getRouterByFrontName', 'Magento_Core_Controller_Varien_Front',
        'Magento_Core_Model_RouterList::getRouterByFrontName'
    ),
    array('getRouters', 'Magento_Core_Model_Config'),
    array('getRowId', 'Magento_Adminhtml_Block_Sales_Order_Create_Customer_Grid'),
    array('getRowId', 'Magento_Adminhtml_Block_Widget_Grid'),
    array('getSaveTemplateFlag', 'Magento_Newsletter_Model_Queue'),
    array('getSectionNode', 'Magento_Core_Model_Config'),
    array('getSecure', 'Magento_Backend_Model_Url', 'isSecure'),
    array('getSecure', 'Magento_Core_Model_Url', 'isSecure'),
    array('getSelectionFinalPrice', 'Magento_Bundle_Model_Product_Price'),
    array('getShipId', 'Magento_Shipping_Block_Tracking_Popup'),
    array('getSortedChildBlocks', '', 'getChildNames() + $this->getLayout()->getBlock($name)'),
    array('getSortedChildren', '', 'getChildNames'),
    array('getSortedElements', 'Magento\Data\Form\Element\Fieldset', 'getElements'),
    array('getStatrupPageUrl'),
    array('getStore', 'Magento\Captcha\Helper\Data'),
    array('getStoreButtonsHtml', 'Magento\Backend\Block\System\Config\Tabs'),
    array('getStoreCodeFromPath', 'Magento\Core\Controller\Request\Http'),
    array('getStoreCurrency', 'Magento\Sales\Model\Order'),
    array('getStoreSelectOptions', 'Magento\Backend\Block\System\Config\Tabs'),
    array('getStores', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getSuggestedZeroDate'),
    array('getSuggestionsByQuery'),
    array('getSysTmpDir'),
    array('getTablePrefix', 'Magento\Core\Model\Config'),
    array('getTagsByType', 'Magento\Core\Model\Cache', 'Magento\Cache\Frontend\Decorator\TagScope::getTag()'),
    array('getTagsByType', 'Magento\Core\Model\Cache\Proxy', 'Magento\Cache\Frontend\Decorator\TagScope::getTag()'),
    array('getTagsByType', 'Magento\Core\Model\CacheInterface', 'Magento\Cache\Frontend\Decorator\TagScope::getTag()'),
    array('getTaxAmount', 'Magento\Sales\Model\Quote\Item\AbstractItem'),
    array('getTaxRatesByProductClass', '', '_getAllRatesByProductClass'),
    array('getTemplateFilename', '', 'getFilename'),
    array('getTempVarDir', 'Magento\Core\Model\Config', 'Magento\Core\Model\Dir::getDir()'),
    array('getTestsDir', 'Magento_TestFramework_Bootstrap'),
    array('getTheme', 'Magento\Widget\Model\Widget\Instance'),
    array('getThemeOptions', 'Magento\Core\Model\Design\Source\Design',
        'Magento\Core\Model\Theme::getThemeCollectionOptionArray'
    ),
    array('getTotalModels', 'Magento\Sales\Model\Quote\Address'),
    array('getTrackId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingInfoByOrder', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingInfoByShip', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingInfoByTrackId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('getTrackingPopUpUrlByOrderId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getTrackingPopUpUrlByShipId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getTrackingPopUpUrlByTrackId', '', 'getTrackingPopupUrlBySalesModel'),
    array('getUnixProcessMemoryUsage', 'Magento_TestFramework_Helper_Memory', 'getRealMemoryUsage'),
    array('getUnprocessedEvents', 'Magento\Index\Model\Resource\Event',
        'Magento\Index\Model\EventRepository::getUnprocessed()'
    ),
    array('getUnprocessedEventsCollection', 'Magento\Index\Model\Process',
        'Magento\Index\Model\EventRepository::getUnprocessed()'
    ),
    array('getUploadMaxSize', 'Magento\Adminhtml\Block\Media\Uploader', 'Magento\File\Size::getUploadMaxSize()'),
    array('getUrlForReferer', 'Magento\Adminhtml\Block\Page\Footer'),
    array('getUseCacheFilename', 'Magento\Core\Model\App'),
    array('getValidator', 'Magento\SalesRule\Model\Observer'),
    array('getValidatorData', 'Magento\Core\Model\Session\AbstractSession', 'use _getSessionEnvironment method'),
    array('getValueTable'),
    array('getVarDir', 'Magento\Core\Model\Config', 'Magento\Core\Model\Dir::getDir()'),
    array('getViewOrderUrl', 'Magento\Checkout\Block\Onepage\Success'),
    array('getWatermarkHeigth', '', 'getWatermarkHeight'),
    array('getWebsite', 'Magento\Captcha\Helper\Data'),
    array('getWidgetConfig', 'Magento_Widget_Model_Widget_Instance', 'getWidgetConfigAsArray'),
    array('getWidgetsRequiredJsFiles','Magento_Widget_Model_Widget'),
    array('getWidgetsXml','Magento_Widget_Model_Widget', 'getWidgets'),
    array('getWidgetSupportedBlocks', 'Magento_Widget_Model_Widget_Instance'),
    array('getWidgetSupportedTemplatesByBlock', 'Magento_Widget_Model_Widget_Instance'),
    array('getWinProcessMemoryUsage', 'Magento_Test_Helper_Memory', 'getRealMemoryUsage'),
    array('getXmlConfig','Magento_Widget_Model_Widget', 'getWidgets'),
    array('getXmlElementByType','Magento_Widget_Model_Widget', 'getWidgetByClassType'),
    array('hasItems', 'Magento\Wishlist\Helper\Data'),
    array('holdCommit', 'Magento_Search_Model_Observer'),
    array('htmlEscape', '', 'escapeHtml'),
    array('imageAction', 'Magento\Catalog\Controller\Product'),
    array('implodeStreetAddress', 'Magento\Customer\Model\Address\AbstractAddress'),
    array('importFromTextArray'),
    array('init', 'Mage'),
    array('init', 'Magento_Core_Controller_Varien_Front'),
    array('init', 'Magento_Core_Model_App'),
    array('init', 'Magento_Core_Model_Config'),
    array('init', 'Magento_Webapi_Controller_Front'),
    array('initCache'),
    array('initControllerRouters', 'Magento_Cms_Controller_Router'),
    array('initLabels', 'Magento_Catalog_Model_Resource_Eav_Attribute'),
    array('initSerializerBlock', 'Magento_Adminhtml_Block_Catalog_Product_Edit_Tab_Ajax_Serializer'),
    array('initSerializerBlock', 'Magento_Backend_Block_Widget_Grid_Serializer'),
    array('initSpecified', 'Magento_Core_Model_App'),
    array('insertProductPrice', 'Magento_Catalog_Model_Resource_Product_Attribute_Backend_Tierprice'),
    array('isAbsolutePath'),
    array('isActive', 'Magento_Logging_Model_Config'),
    array('isAllowedGuestCheckout', 'Magento\Sales\Model\Quote'),
    array('isAutomaticCleaningAvailable', 'Magento\Cache\Backend\Eaccelerator'),
    array('isCheckoutAvailable', 'Magento\Checkout\Model\Type\Multishipping'),
    array('isFulAmountCovered'),
    array('isInstalled', 'Magento\Core\Model\App'),
    array('isLeyeredNavigationAllowed'),
    array('isLocalConfigLoaded', 'Magento\Core\Model\Config'),
    array('isModuleEnabled', 'Magento\Core\Model\Config', 'Magento\Core\Model\ModuleManager::isEnabled'),
    array('isReadablePopupObject'),
    array('isStaticFilesSigned', 'Magento\Core\Helper\Data'),
    array('isTemplateAllowedForApplication'),
    array('isThemeCompatible', 'Magento_Core_Model_Design_Package', 'Magento\Core\Model\Theme::isThemeCompatible'),
    array('isUserSavingAllowed', 'Magento\User\Model\Resource\User'),
    array('isVerbose', 'Magento\Shell'),
    array('isWindowsOs', 'Magento_TestFramework_Helper_Memory'),
    array('load', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('loadBase', 'Magento\Core\Model\Config'),
    array('loadDb', 'Magento\Core\Model\Config'),
    array('loadDiConfiguration', 'Magento\Core\Model\Config'),
    array('loadEventObservers', 'Magento\Core\Model\Config'),
    array('loadLabel', 'Magento\Catalog\Model\Resource\Product\Type\Configurable\Attribute'),
    array('loadModules', 'Magento\Core\Model\Config'),
    array('loadModulesCache', 'Magento\Core\Model\Config'),
    array('loadModulesConfiguration', 'Magento\Core\Model\Config'),
    array('loadParentProductIds', 'Magento\Catalog\Model\Product'),
    array('loadPrices', 'Magento\Catalog\Model\Resource\Product\Type\Configurable\Attribute'),
    array('loadProductPrices', 'Magento\Catalog\Model\Resource\Product\Attribute\Backend\Tierprice'),
    array('lockOrderInventoryData', 'Magento\CatalogInventory\Model\Observer'),
    array('logEncryptionKeySave'),
    array('logInvitationSave'),
    array('map', 'Magento_ObjectManager_Config_Mapper_Dom', 'Magento_ObjectManager_Config_Mapper_Dom::convert'),
    array('mergeFiles', 'Magento\Core\Helper\Data', 'Magento_Core_Model_Page_Asset_MergeStrategyInterface'),
    array('mergeFiles', 'Magento_Core_Model_Design_Package', 'Magento_Core_Model_Page_Asset_MergeStrategyInterface'),
    array(
        'mergeFiles',
        'Magento_Core_Model_Design_Package_Proxy',
        'Magento_Core_Model_Page_Asset_MergeStrategyInterface'
    ),
    array(
        'mergeFiles',
        'Magento_Core_Model_Design_PackageInterface',
        'Magento_Core_Model_Page_Asset_MergeStrategyInterface'
    ),
    array('order_success_page_view', 'Magento\GoogleAnalytics\Model\Observer'),
    array('orderedAction', 'Magento\Adminhtml\Controller\Report\Product'),
    array('output', 'Magento\Shell'),
    array('pageHandleExists', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('parseDateTime', 'Magento\Core\Model\Date'),
    array('postDispatchMyAccountSave'),
    array('postDispatchSystemImportExportRun'),
    array('prepareAddressInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareAttributesForSave', 'Magento\ImportExport\Model\Import\Entity\Product'),
    array('prepareCacheId', 'Magento\Core\Model\App'),
    array('prepareFeesInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareGoogleOptimizerScripts'),
    array('prepareRedirect', 'Magento\Core\Controller\Varien\Exception'),
    array('prepareItemInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('preparePriceAlertData', 'Magento_ProductAlert_Block_Product_View'),
    array('prepareProfilesGrid', 'Magento_Sales_Block_Recurring_Profiles'),
    array('prepareReferenceInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareRelatedOrdersFrontendGrid', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareScheduleInfo', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('prepareStockAlertData', 'Magento_ProductAlert_Block_Product_View'),
    array('prepareViewData', 'Magento_Sales_Block_Recurring_Profile_View'),
    array('preprocess', 'Magento\Newsletter\Model\Template'),
    array('processBeacon'),
    array('processBeforeVoid', 'Magento\Payment\Model\Method\AbstractMethod'),
    array('processRequest', 'Magento\Core\Model\Cache'),
    array('processSubst', 'Magento\Core\Model\Store'),
    array('productEventAggregate'),
    array('publishRelatedViewFile', 'Magento_Core_Model_View_Publisher', '_publishRelatedViewFile'),
    array('push', 'Magento_Catalog_Model_Product_Image'),
    array('rebuildCategoryLevels', 'Magento\Catalog\Model\Resource\Setup'),
    array('refundOrderItem', 'Magento\CatalogInventory\Model\Observer'),
    array('regenerateSessionId', 'Magento\Core\Model\Session\AbstractSession'),
    array('reinitialize', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::reinitialize'),
    array('removeAuthLink', 'Magento_Customer_Block_Account_Link'),
    array('removeItem', 'Magento_Page_Block_Html_Head'),
    array('removeCustomerFromSegments'),
    array('removeHandle', 'Magento\Core\Model\Layout\Update', 'Magento\Core\Model\Layout\Merge'),
    array('removeParentCartLink', 'Magento_Checkout_Block_Links'),
    array('removeRegisterLink', 'Magento_Customer_Block_Account_Link'),
    array('renderView', '', 'Magento\Core\Block\Template::_toHtml()'),
    array('revalidateCookie', 'Magento_Core_Model_Session_Abstract_Varien'),
    array('run', 'Mage'),
    array('runApp', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::runApp'),
    array('sales_order_afterPlace'),
    array('sales_quote_address_discount_item'),
    array('salesEventConvertQuoteItemToOrderItem', 'Magento_GiftMessage_Model_Observer'),
    array('salesOrderPaymentPlaceEnd'),
    array('saveCache', 'Magento\Core\Model\Config'),
    array('saveConfig', 'Magento\Core\Model\Config'),
    array('saveOptions', 'Magento\Core\Model\Cache'),
    array('saveOptions', 'Magento\Core\Model\Cache\Proxy'),
    array('saveOptions', 'Magento\Core\Model\CacheInterface'),
    array('saveRow__OLD'),
    array('saveSegmentCustomersFromSelect'),
    array('saveUseCache'),
    array('send', 'Magento\Newsletter\Model\Template'),
    array('sendNewPasswordEmail'),
    array('setAnonSuffix'),
    array('setApplyFilters'),
    array('setAttributeSetExcludeFilter', 'Magento\Eav\Model\Resource\Entity\Attribute\Collection'),
    array('setBlockAlias'),
    array('setConfig', 'Magento\Captcha\Helper\Data'),
    array('setCurrentArea', 'Mage'),
    array('setCustomerId', 'Magento\Customer\Model\Resource\Address'),
    array('setInstance', 'Magento_TestFramework_Bootstrap', 'Magento_TestFramework_Helper_Bootstrap::setInstance'),
    array('setIsAjaxRequest', 'Magento\Core\Model\Translate\Inline'),
    array('setIsDeveloperMode', 'Mage', 'Initialization parameter of the application'),
    array('setNeedUsePriceExcludeTax', '', 'Magento\Tax\Model\Config::setPriceIncludesTax()'),
    array('setOption', 'Magento\Captcha\Helper\Data'),
    array('setOptions', 'Magento\Core\Model\Config'),
    array('setOrderId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('setPackageTheme', 'Magento\Widget\Model\Widget\Instance', 'setThemeId'),
    array('setParentBlock'),
    array('setProfile', 'Magento\Convert\Container\AbstractContainer'),
    array('setSaveTemplateFlag', 'Magento\Newsletter\Model\Queue'),
    array('setScriptPath'),
    array('setScriptPath', 'Magento\Core\Block\Template'),
    array('setShipId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('setSortElementsByAttribute', 'Magento\Data\Form\Element\Fieldset'),
    array('setStore', 'Magento\Captcha\Helper\Data'),
    array('setTaxGroupFilter'),
    array('setTrackId', 'Magento\Shipping\Block\Tracking\Popup'),
    array('setVarSubFolders'),
    array('setVerbose', 'Magento\Shell'),
    array('setWatermarkHeigth', '', 'setWatermarkHeight'),
    array('setWebsite', 'Magento\Captcha\Helper\Data'),
    array('shaCrypt', '', 'Magento\Ogone\Model\Api::getHash'),
    array('shaCryptValidation', '', 'Magento\Ogone\Model\Api::getHash'),
    array('shouldCustomerHaveOneBalance'),
    array('shouldShowOneBalance'),
    array('sortChildren'),
    array('substDistroServerVars', 'Magento\Core\Model\Config'),
    array('superGroupGridOnlyAction', 'Magento\Adminhtml\Controller\Catalog\Product'),
    array('toOptionArray', 'Magento\Cms\Model\Resource\Page\Collection'),
    array('toOptionArray', 'Magento\Sendfriend\Model\Sendfriend'),
    array('truncate', 'Magento\DB\Adapter\Pdo\Mysql'),
    array('unsetBlock'),
    array('updateCofigurableProductOptions', 'Magento\Weee\Model\Observer', 'updateConfigurableProductOptions'),
    array('updateTable', 'Magento\Core\Model\Resource\Setup'),
    array('urlEscape', '', 'escapeUrl'),
    array('useValidateHttpUserAgent', 'Magento\Core\Model\Session\AbstractSession'),
    array('useValidateHttpVia', 'Magento\Core\Model\Session\AbstractSession'),
    array('useValidateHttpXForwardedFor', 'Magento\Core\Model\Session\AbstractSession'),
    array('useValidateRemoteAddr', 'Magento\Core\Model\Session\AbstractSession'),
    array('validateDataArray', 'Magento\Convert\Container\AbstractContainer'),
    array('validateFile', 'Magento_Core_Model_Design_Package'),
    array('validateOrder', 'Magento\Checkout\Model\Type\Onepage'),
    array('_prepareOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('_getOptionValuesCollection', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array(' _prepareSystemAttributeOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('_prepareUserDefinedAttributeOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getLabelValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getStoreOptionValues', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('getAttributeObject', 'Magento\Eav\Block\Adminhtml\Attribute\Edit\Options\AbstractOptions'),
    array('substractQtyFromQuotes', 'Magento\Sales\Model\Observer',
        'Magento\Sales\Model\Observer\Backend\CatalogProductQuote::subtractQtyFromQuotes'
    ),
    array('markQuotesRecollectOnCatalogRules', 'Magento\Sales\Model\Observer',
        'Magento\Sales\Model\Observer\Backend\CatalogPriceRule::dispatch'
    ),
    array(
        'catalogProductSaveAfter', 'Magento\Sales\Model\Observer',
        'Magento\Sales\Model\Observer\Backend\CatalogProductQuote::catalogProductSaveAfter'
    ),
    array(
        'catalogProductStatusUpdate', 'Magento\Sales\Model\Observer',
        'Magento\Sales\Model\Observer\Backend\CatalogProductQuote::catalogProductStatusUpdate'
    ),
    array(
        'prepareProductEditFormRecurringProfile', 'Magento\Sales\Model\Observer',
        'Magento\Sales\Model\Observer\Backend\RecurringProfile\FormRenderer::render'
    ),
    array(
        'restrictAdminBillingAgreementUsage', 'Magento\Sales\Model\Observer',
        'Magento\Sales\Model\Observer\Backend\BillingAgreement::dispatch'
    ),
    array(
        'customerSaveAfter', 'Magento\Sales\Model\Observer',
        'Magento\Sales\Model\Observer\Backend\CustomerQuote::dispatch'
    ),
    array('_getUsers', 'Magento\Adminhtml\Block\Api\Role\Grid\User', 'getUsers'),
    array('_getGridHtml', 'Magento\Adminhtml\Block\Api\Tab\Rolesusers', 'getGridHtml'),
    array('_getSelectedRoles', 'Magento\Adminhtml\Block\Api\User\Edit\Tab\Roles', 'getSelectedRoles'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config\Matrix', 'getProduct'),
    array('_getImageUploadUrl', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config\Matrix',
        'getImageUploadUrl'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config\Simple', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Config', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Super\Settings', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Crosssell', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Related', 'getProduct'),
    array('_getProduct', 'Magento\Adminhtml\Block\Catalog\Product\Edit\Tab\Upsell', 'getProduct'),
    array('_renderCellTemplate', 'Magento\Backend\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray', 'renderCellTemplate'),
    array('_showSingle', 'Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option', 'showSingle'),
    array('_getDefaultValues', 'Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option', 'getDefaultValues'),
    array('_isSelected', 'Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option', 'isSelected'),
    array('_getProduct', 'Magento\Catalog\Block\Product\Configurable\AssociatedSelector\Backend\Grid\ColumnSet',
        'getProduct'),
    array('_getProduct', 'Magento\CatalogInventory\Block\Stockqty\AbstractStockqty', 'getProduct'),
    array('_getProduct', 'Magento\CatalogInventory\Block\Qtyincrements', 'getProduct'),
    array('_getPageTrackingCode', 'Magento\GoogleAnalytics\Block\Ga', 'getPageTrackingCode'),
    array('_getOrdersTrackingCode', 'Magento\GoogleAnalytics\Block\Ga', 'getOrdersTrackingCode'),
    array('_toJson', 'Magento\GoogleShopping\Block\Adminhtml\Types\Edit\Attributes', 'jsonFormat'),
    array('_getUsers', 'Magento\User\Block\Role\Grid\User', 'getUsers'),
    array('_getGridHtml', 'Magento\User\Block\Role\Tab\Users', 'getGridHtml'),
    array('_getSelectedRoles', 'Magento\User\Block\User\Edit\Tab\Roles', 'getSelectedRoles'),
    array('_prepareSelect', 'Magento\Core\Model\Resource\Db\Collection\AbstractCollection'),
    array('_prepareSelect', 'Varien_Data_Collection_Db'),
    array('castField', 'Magento\Core\Model\Resource\Helper\Mysql4'),
    array('getQueryUsingAnalyticFunction', 'Magento\Core\Model\Resource\Helper\Mysql4'),
    array('limitUnion', 'Magento\Core\Model\Resource\Helper\Mysql4'),
    array('_addLoadAttributesSelectFields', 'Magento\Catalog\Model\Resource\AbstractResource'),
    array('attributeSelectFields', 'Magento\Catalog\Model\Resource\Helper\Mysql4'),
    array('_addLoadAttributesSelectFields', 'Magento\Eav\Model\Entity\AbstractEntity'),
    array('attributeSelectFields', 'Magento\Eav\Model\Resource\Helper\Mysql4'),
    array('prepareEavAttributeValue', 'Magento\Eav\Model\Resource\Helper\Mysql4'),
    array('prepareColumn', 'Magento\Eav\Model\Resource\Helper\Mysql4'),
    array('getInsertFromSelectUsingAnalytic', 'Magento\Eav\Model\Resource\Helper\Mysql4'),
    array('setOneRowLimit', 'Magento\Eav\Model\Resource\Helper\Mysql4'),
    array('getCastToIntExpression', 'Magento\Eav\Model\Resource\Helper\Mysql4'),
    array('_initMetaTags', 'Magento_Page_Block_Html_Head'),
    array('addMetaTag', 'Magento_Page_Block_Html_Head'),
    array('getDefaultMetaTags', 'Magento_Page_Block_Html_Head'),
    array('getMetaTags', 'Magento_Page_Block_Html_Head'),
    array('getMetaTagHtml', 'Magento_Page_Block_Html_Head'),
    array('addLink', 'Magento_Sales_Block_Order_Info'),
    array('checkLinks', 'Magento_Sales_Block_Order_Info'),
    array('getLinks', 'Magento_Sales_Block_Order_Info'),
    array('addProductAttributes', 'Magento_SalesRule_Model_Observer'),
    array('_helper', 'Magento_Catalog_Model_Product_Type_Abstract'),
    array('getHelper', 'Magento_Catalog_Model_Resource_Product_Type_Configurable_Attribute_Collection'),
    array('getHelper', 'Magento_Cms_Model_Wysiwyg_Images_Storage'),
    array('getHelper', 'Magento_Core_Model_AppProxy'),
    array('getHelper', 'Magento_Core_Model_App'),
    array('helper', 'Mage'),
    array('dispatchEvent', 'Mage'),
    array('getConfig', 'Mage', 'Magento_Core_Model_Config'),
    array('getStoreConfig', 'Mage', 'Magento_Core_Model_Store_Config'),
    array('getStoreConfigFlag', 'Mage', 'Magento_Core_Model_Store_Config'),
    array('resetRegistry', 'Mage', 'use \Magento\Core\Model\Registry'),
    array('register', 'Mage', 'use \Magento\Core\Model\Registry'),
    array('unregister', 'Mage', 'use \Magento\Core\Model\Registry'),
    array('registry', 'Mage', 'use \Magento\Core\Model\Registry'),
    array('getObjectManager', 'Mage'),
    array('getCatalogHelper', 'Magento_Adminhtml_Block_Catalog_Category_Tabs'),
);
