<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var $this Mage_Backend_Block_Widget_Form_Container
 */
 ?>
<?php echo $this->getFormInitScripts() ?>
<div class="content-header" <?php echo $this->getUiId('content-header') ?>>
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>
<?php echo $this->getFormHtml() ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
<script type="text/javascript">
    jQuery('#edit_form').form().validation({validationUrl: '<?php echo $this->getValidationUrl() ?>'});
</script>
<?php echo $this->getFormScripts() ?>
