<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
    <div class="form-subscribe">
        <div class="form-subscribe-header">
            <label for="newsletter"><?php echo __('Sign Up for Our Newsletter:') ?></label>
        </div>
        <div class="v-fix"><input name="email" type="text" id="newsletter"
                                  value="<?php echo __('Enter your email address') ?>"
                                  class="input-text" data-validate="{required:true, 'validate-email':true}"/></div>
        <button type="submit" class="button" title="<?php echo __('Subscribe') ?>">
            <span><span><?php echo __('Subscribe') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
            "<?php echo $this->getViewFileUrl('Magento_Newsletter::newsletter.js')?>", function() {
                $('#newsletter').newsletter({
                    formSelector: '#newsletter-validate-detail',
                    placeholder: '<?php echo __('Enter your email address') ?>'
                });
            });
    })(jQuery);
    //]]>
</script>
