<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Promotestore_Seo_Tile */
?>
<article class="tile-store-settings tile-seo <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>" tabindex="0">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('SEO') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('We recommend that you configure these pages on your new site.') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/promotestore_seo_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/promotestore_seo_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Confirm Info') ?>
        </button>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <p><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('We recommend that you configure these pages on your new site.') ?></p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/promotestore_seo_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/promotestore_seo_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Edit Content Pages') ?>
        </button>
        <?php endif; ?>
    </div>
</article>