<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     pro_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this Enterprise_CustomerBalance_Block_Checkout_Onepage_Payment_Additional */
?>
<?php
/**
 * @see Enterprise_CustomerBalance_Block_Checkout_Onepage_Payment_Additional
 */
?>
<?php if ($this->isAllowed()): ?>
isFullyPaidAfterCustomerBalanceApplication = <?php echo ($this->isFullyPaidAfterApplication() ? 'true' : 'false'); ?>;
quoteBaseGrandTotal = <?php echo (float)$this->getQuote()->getBaseGrandTotal(); ?>;
function setCustomerBalanceAvailable(balance, formattedBalance) {
    if ($('customerbalance_placer')) {
        if (balance == 0) {
            $('use_customer_balance').checked = false;
            $('use_customer_balance').disabled = true;
            $('customerbalance_placer').hide();
        } else {
            $('use_customer_balance').disabled = false;
            $('customerbalance_placer').show();
        }
    }

    if ($('customerbalance_available_amount')) {
        $('customerbalance_available_amount').innerHTML = formattedBalance;
    }
}

setCustomerBalanceAvailable('<?php echo $this->getBalance(); ?>', '<?php echo Mage::helper('Mage_Core_Helper_Data')->currency($this->getBalance()); ?>');
<?php endif;?>
