<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Wishlist\Block\Share\Wishlist */
$imageBlock =  $this->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
?>

<?php if ($this->hasWishlistItems()): ?>
    <form class="form shared wishlist" action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
        <div class="wishlist table wrapper">
            <table class="table data wishlist" id="wishlist-table">
                <thead>
                <tr>
                    <th class="col product"><?php echo __('Product') ?></th>
                    <th class="col comment"><?php echo __('Comment') ?></th>
                    <th class="col actions"><?php echo __('Add to Cart') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->getWishlistItems() as $item): ?>
                    <?php
                    $product = $item->getProduct();
                    $isVisibleProduct = $product->isVisibleInSiteVisibility();
                    ?>
                    <tr>
                        <td class="col product">
                            <a class="product photo" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
                                <?php echo $imageBlock->init($product, 'customer_shared_wishlist')->toHtml() ?>
                            </a>
                            <strong class="product name">
                                <a href="<?php echo $this->getProductUrl($item) ?>">
                                    <?php echo $this->escapeHtml($product->getName()) ?>
                                </a>
                            </strong>
                            <?php echo $this->getPriceHtml($product) ?>
                            <?php echo $this->getDetailsHtml($item) ?>
                        </td>
                        <td class="col comment"><?php echo $this->getEscapedDescription($item) ?></td>
                        <td class="col actions" data-role="add-to-links">
                            <?php if ($product->isSaleable()): ?>
                                <?php if ($isVisibleProduct): ?>
                                    <button type="button" title="<?php echo __('Add to Cart') ?>" onclick="setLocation('<?php echo $this->getSharedItemAddToCartUrl($item) ?>')" class="action tocart">
                                        <span><?php echo __('Add to Cart') ?></span>
                                    </button>
                                <?php endif ?>
                            <?php endif; ?>
                            <a href="#" data-post='<?php echo $this->getAddToWishlistParams($item); ?>'  onclick="setLocation(this.href); return false;" class="action towishlist" data-action="add-to-wishlist">
                                <span><?php echo __('Add to Wishlist') ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>

        <div class="actions">
            <?php if($this->isSaleable()):?>
                <div class="primary">
                    <button type="button" title="<?php echo __('Add All to Cart') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/allcart', array('_current'=>true)) ?>')" class="action tocart">
                        <span><?php echo __('Add All to Cart') ?></span>
                    </button>
                </div>
            <?php endif;?>
            <div class="secondary">
                <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="action back">
                    <span><?php echo __('Back') ?></span>
                </a>
            </div>
        </div>
    </form>
<?php else: ?>
    <p><?php echo __('Wish List is empty now.') ?></p>
<?php endif ?>
