<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_options = $this->helper('Magento\Core\Helper\Data')->decorateArray($this->getOptions()); ?>
<?php if ($_product->isSaleable()):?>
    <?php if (count($_options)): ?>
    <script type="text/javascript">
        (function ($) {
            head.js("<?php echo $this->getViewFileUrl('Magento_Bundle::bundle.js') ?>", function () {
                $('#product_addtocart_form').bundleOption({'optionConfig':<?php echo $this->getJsonConfig()?>}).trigger('changeSelection');
            });
        })(jQuery);
    </script>
        <dl>
        <?php foreach ($_options as $_option): ?>
            <?php if (!$_option->getSelections()): ?>
                <?php continue; ?>
            <?php endif; ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach; ?>
        </dl>
    <?php else: ?>
        <p><?php echo __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
