<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this Mage_Core_Block_Template */
?>
<script type="text/javascript">//<[CDATA[
(function($, window, document) {
    "use strict";
    $(function() {
        $('#product_edit_form').bind('product:changeAttributeSet', function(event, attributeSetId) {
            var $form = $(this);
            var uri = document.location.href.replace(/(\/|&)?set(\/|=)\d+/g, '');
            uri += /\?/.test(uri) ? '&' : '?';
            uri += 'set=' + window.encodeURIComponent(attributeSetId);
            $form.attr('action', uri).submit();
        });

        $('#attribute-set-info').dialog({
            title: '<?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Select Attribute Set'); ?>',
            autoOpen: false,
            id: '<?php echo strtolower($this->getNameInLayout()) ?>',
            minWidth: 560,
            modal: true,
            resizable: false,
            buttons: [{
                text: '<?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Cancel'); ?>',
                id: '<?php echo strtolower($this->getNameInLayout()) . '-close-button' ?>',
                click: function() {
                    $(this).dialog("close");
                }
            }, {
                text: '<?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Apply'); ?>',
                id: '<?php echo strtolower($this->getNameInLayout()) . '-apply-button' ?>',
                click: function() {
                    var $attibuteSetId = $(this).find('#attribute_set_id');
                    $('#product_edit_form').trigger('product:changeAttributeSet', [$attibuteSetId.val()]);
                }
            }]
        });
    });
})(jQuery, window, document);
//]]>
</script>