<?php
/**
* {license_notice}
*
* @category    Mage
* @package     Mage_Adminhtml
* @copyright   {copyright}
* @license     {license_link}
*/
/* @var $this Mage_Core_Block_Template */
?>
<script type="text/javascript">//<[CDATA[
(function($, window, document) {
    "use strict";

    $(function(){
        $('#attribute-set-info').dialog({
            title: 'Select Attribute Set',
            autoOpen: false,
            id: '<?php echo strtolower($this->getNameInLayout()) ?>',
            minWidth: 560,
            modal: true,
            resizable: false,
            buttons: [{
                text: "Close",
                id: '<?php echo strtolower($this->getNameInLayout()) . '-close-button' ?>',
                click: function() {
                    $(this).dialog("close");
                }
            },{
                text: "Apply",
                id: '<?php echo strtolower($this->getNameInLayout()) . '-apply-button' ?>',
                click: function() {
                    var $attibuteSetId = $(this).find('#attribute_set_id');
                    var $form = $('#product_edit_form');
                    var uri = document.location.href.replace(/(\/|&)?set(\/|=)\d+/g, '');
                    uri += (/\?/.test(uri)? '&' : '?');
                    uri += 'set=' + window.encodeURIComponent($attibuteSetId.val());
                    $form.attr('action', uri).submit();
                }
            }]
        });
    });
})(jQuery, window, document);
//]]>
</script>