<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if( $this->getCollection() && $this->count()): ?>
    <div class="toolbar reviews">
        <?php echo $this->getToolbarHtml() ?>
    </div>
    <table class="data table reviews" id="my-reviews-table">
        <thead>
            <tr>
                <th class="col date"><?php echo __('Created') ?></th>
                <th class="col item"><?php echo __('Product Name') ?></th>
                <th class="col summary"><?php echo __('Summary') ?></th>
                <th class="col description"><?php echo __('Description') ?></th>
                <th class="col actions">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getCollection() as $_review): ?>
            <tr>
                <td class="col date"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></td>
                <td class="col item">
                    <strong class="product name">
                        <a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a>
                    </strong>
                </td>
                <td class="col summary">
                <?php if($_review->getSum()): ?>
                    <div class="rating">
                        <span style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></span>
                    </div>
                <?php endif; ?>
                </td>
                <td class="col description">
                    <div class="text">
                        <?php echo $this->helper('Magento\Review\Helper\Data')->getDetailHtml($_review->getDetail()) ?>
                    </div>
                </td>
                <td class="col actions">
                    <a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="action more">
                        <span><?php echo __('View Details') ?></span>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="toolbar reviews bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
<?php else: ?>
    <p class="empty"><?php echo __('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="actions">
    <div class="secondary">
        <a class="action back" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>">
            <span><?php echo __('Back') ?></span>
        </a>
    </div>
</div>
