<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if( $this->getCollection() && $this->count()): ?>
<div class="block reviews dashboard">
    <div class="title">
        <strong><?php echo __('My Recent Reviews') ?></strong>
        <a class="action view" href="<?php echo $this->getAllReviewsUrl() ?>"><span><?php echo __('View All Reviews') ?></span></a>
    </div>
    <div class="content">
        <ol class="items">
        <?php foreach ($this->getCollection() as $_review): ?>
            <li class="item">
                <strong class="product name"><a href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a></strong>
                <?php if($_review->getSum()): ?>
                <?php $rating = $_review->getSum() / $_review->getCount() ?>
                    <div class="rating" title="<?php echo $rating; ?>%">
                        <span style="width:<?php echo $rating; ?>%">
                            <?php echo $rating; ?>
                        </span>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
