<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->getEnabled() && $this->getItems()) :?>
<script id="address-option-tmpl" type="text/x-jQuery-tmpl">
    <option value="${_value_}">${_text_}</option>
</script>
<script type="text/javascript">
    <?php $selectedGrAddressesIndexes = $this->getGiftregistrySelectedAddressesIndexes(); ?>
    <?php $selectedGrAddressesIndexesJson = '[' . implode(',', $selectedGrAddressesIndexes) . ']'; ?>
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_GiftRegistry::address-option.js') ?>", function() {
            var registryItems = [];
            <?php foreach ($this->getItems() as $itemId => $registryItem): ?>
                registryItems.push({"item": <?php echo $itemId ?>, "address": <?php echo $registryItem['item_id'] ?>});
            <?php endforeach ?>
            $('#multiship-addresses-table').addressOption({
                registryItems: registryItems,
                addressItemPrefix: '<?php echo $this->getAddressIdPrefix(); ?>',
                selectedAddressIndices: <?php echo $selectedGrAddressesIndexesJson ?>
            });
        });
    })(jQuery);
</script>
<?php endif; ?>
