<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title">
    <h1><?php echo $this->getFormHeader() ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form action="<?php echo $this->getActionUrl() ?>" method="get" id="wishlist-search-form">
    <div class="fieldset">
        <h2 class="legend"><?php echo __('Search Options') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="params_firstname" class="required"><em>*</em><?php echo __('First Name') ?></label>
                     <div class="input-box">
                        <input name="params[firstname]" id="params_firstname" type="text" value="<?php echo $this->getFormData('firstname') ?>" class="input-text required-entry" />
                    </div>
                </div>
                <div class="field">
                    <label for="params_lastname" class="required"><em>*</em><?php echo __('Last Name') ?></label>
                    <div class="input-box">
                        <input name="params[lastname]" id="params_lastname" type="text" value="<?php echo $this->getFormData('lastname') ?>" class="input-text required-entry" />
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="buttons-set form-buttons">
        <input type="hidden" name="params[search]" value="type" />
        <button type="submit" class="button"><span><span><?php echo __('Search') ?></span></span></button>
    </div>
    <p class="required"><?php echo __('* Required Fields') ?></p>
</form>

<div class="divider"></div>

<form action="<?php echo $this->getActionUrl() ?>" method="get" id="wishlist-search-email-form">
    <div class="fieldset">
        <ul class="form-list">
            <li>
                 <label for="params_email" class="required"><em>*</em><?php echo __('Owner Email') ?></label>
                 <div class="input-box">
                     <input name="params[email]" id="params_email" type="text" value="<?php echo $this->getFormData('email') ?>" class="input-text required-entry validate-email" />
                 </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set form-buttons">
        <input type="hidden" name="params[search]" value="email" />
        <button type="submit" class="button"><span><span><?php echo __('Search') ?></span></span></button>
    </div>
    <p class="required"><?php echo __('* Required Fields') ?></p>
</form>

<div class="divider"></div>

<script type="text/javascript">
                (function($) {
                    head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
                        "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
                        "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                        "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                            $('#wishlist-search-form')
                                .add('#wishlist-search-email-form').validation();
                        });
                })(jQuery);
</script>


