<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if( $this->getCount() ): ?>
<div class="collateral-box">
    <div class="head"><h4><?php echo $this->__('Product Tags') ?></h4></div>
    <?php echo $this->getChildHtml('list_before')?>
    <div class="tags-list">
        <?php echo $this->renderTags('<a href="%1$s">%2$s</a> <span>(%3$s)</span>') ?>
    </div>

    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
        <div class="form-add">
            <label for="productTagName"><?php echo $this->__('Add Your Tags:') ?></label>
            <div class="input-box">
                <input type="text" class="input-text required-entry" name="productTagName" id="productTagName" />
            </div>
            <button type="button" title="<?php echo $this->__('Add Tags') ?>" class="button" onclick="submitTagForm()">
                <span>
                    <span><?php echo $this->__('Add Tags') ?></span>
                </span>
            </button>
        </div>
    </form>
    <p class="note"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
    <script type="text/javascript">
    //<![CDATA[
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm(){
            if(addTagFormJs.validator.validate()) {
                addTagFormJs.form.submit();
            }
        }
    //]]>
    </script>
</div>
<?php endif; ?>
