<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Create account form template
 */
/* @var $this \Magento\CustomAttribute\Block\Form\Renderer\Text */
?>
<div id="reason_other${_index_}" class="field <?php echo $this->getHtmlId()?> <?php echo $this->getHtmlId()?>${_index_}<?php if ($this->isRequired()) echo ' required' ?>">
    <label for="items:<?php echo $this->getHtmlId()?>${_index_}" class="label"><span><?php echo $this->getLabel() ?></span></label>
    <div class="control">
        <input type="text" id="items:<?php echo $this->getHtmlId()?>${_index_}" name="items[${_index_}][<?php echo $this->getFieldName()?>]" value="<?php echo $this->getEscapedValue() ?>" class="input-text<?php echo $this->getHtmlClass(); ?><?php echo  ($this->getFieldName() == 'qty_requested') ? ' check-count' : ''?>">
    </div>
</div>
