#!/bin/sh
if [ -z "$PHP" ]; then
   PHP=`which php`
fi
(exec $PHP -C -q -d output_buffering=1 "$0" "$@") 2>/dev/null
if [ "$?" -ne "0" ]; then
	echo "FAILED:  Bad environment variable \$PHP (set to \"$PHP\")"
	exit 1
fi
exit 0
<?php
/**
 * @package phpDocumentorCustom
 */

@ob_end_clean(); // make output from autofind php code disapear

// Redefine $_phpDocumentor_install_dir
// so we can load phpDocumentor.ini from current folder
$GLOBALS['_phpDocumentor_install_dir'] = dirname(__FILE__);

$phpDocumentor_dir = 'PhpDocumentor/phpDocumentor';
$classes_dir       = dirname(__FILE__) . '/classes';

// Load custom classes
require_once($phpDocumentor_dir . "/Setup.inc.php");
require_once($classes_dir . '/phpDocumentor_setupCustom.php');
require_once($classes_dir . '/parserTagCustom.php');

// Load settings
$phpdoc = new phpDocumentor_setupCustom($classes_dir . '\tags');

// Point $_phpDocumentor_install_dir to phpDocumentor 
// for correct loading of converters
$GLOBALS['_phpDocumentor_install_dir'] = 'PhpDocumentor/phpDocumentor';

$phpdoc->readCommandLineSettings();
$phpdoc->setupConverters();
$phpdoc->createDocs();
?>