<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/*
    <!--<h2 class="page-head"><?=$category->getData('name')?></h2>-->
    <!--<p><?=$category->getData('description')?></p>-->
		<div class="page-head-alt">
			<h2><?=$this-><?=$this->getHeaderTitle()?></h2>
		</div>

*/
?>
<?if($this->getCanShowName()):?>
<div class="page-head-alt">
	<h2><?=$this->getCurrentCategory()->getName()?></h2>
</div>
<?endif;?>

<?if($this->getCurrentCategory()->getImage()):?>
    <p><img src="<?=/*TOFIX*/Mage::getSingleton('core/store')->getConfig('web/url/upload').$this->getCurrentCategory()->getImage()?>" alt="<?=$this->getCurrentCategory()->getName()?>" width="512"/></p>
<?endif;?>

<?=$this->getPagerHtml()?>

<?$productCollection=$this->getLoadedProductCollection()?>
<?if($this->getMode()=='list'):?>
<!-- [starts] .listing-type-list // -->
<div class="listing-type-list"> <!-- the class name will change to .listing-type-cell if viewing in list mode -->

    <?$i=0; foreach ($productCollection as $product):?>
	    <div class="listing-item <?if (sizeof($productCollection->getItems())<$i+3):?> class="last"<?endif?>">
		    <div class="product-image">
			    <a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><img src="<?=$product->getSmallImageUrl()?>" width="125" height="125" alt="<?=$product->getName()?>"/></a>
					<div class="ratings">
						<div class="rating-box">
							<div class="rating" style="width:70%;">
							</div>
						</div>
						<a href="#" class="no-wrap"><small>3 Reviews</small></a>
					</div>
		    </div>
		    <div class="product-info">
			    <h5><a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><?=$product->getName()?></a></h5>
					<div class="description"><?=$product->getDescription()?> <a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><small>Learn More</small></a></div>
					<p class="price-box">
							<span class="special-price"><span class="label">Special:</span> <?=$product->getFormatedPrice()?></span><br/>
							<span class="old-price"><span class="label">Price:</span> <?=$product->getFormatedPrice()?></span>
					</p>
					<div class="actions">
						<button class="form-button" onclick="top.location.href='<?=$this->getUrl('checkout/cart/add',array('product'=>$product->getId()))?>'"><span>Add to Cart</span></button><br/>
						<ul class="add-to">
							<li><a href="<?=$this->getUrl('wishlist/index/add',array('product'=>$product->getId()))?>">Add to My Wishlist</a></li>
							<?if($this->getCompareJsObjectName()):?><li><a href="#" onclick="<?=$this->getCompareJsObjectName()?>.addItem(<?=$product->getId()?>);return false;">Add to Compare</a></li><?endif;?>
						</ul>
					</div>
				</div>
			</div>
    <?endforeach;?>









</div>
<!-- [ends] .listing-type-list // -->




<?else:?>

<!-- [starts] .listing-type-grid // -->
	<div class="listing-type-grid"> <!-- the class name will change to .listing-type-cell if viewing in list mode -->
	    <table cellspacing="0" class="generic-product-grid">
		    <?$i=0; foreach ($productCollection as $product):?>
			<?if ($i++%3==0):?><tr<?if (sizeof($productCollection->getItems())<$i+3):?> class="last"<?endif?>><?endif?>
								<td<?if ($i%3==0):?> class="last"<?endif?>>
				    <p class="product-image"><a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><img src="<?=$product->getSmallImageUrl()?>" width="135" alt="<?=$product->getName()?>"></a></p>
					<h5><a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><?=$product->getName()?></a></h5>
					<div class="price-box">
										<span class="regular-price"><?=$product->getFormatedPrice()?></span>
									</div>
					<div class="ratings">
					    <div class="rating-box">
						    <div class="rating" style="width:75%;"></div>
						</div>
						<a href="#"><small>(3)</small></a>
					</div>
					<p class="actions">
					<button class="form-button" onclick="top.location.href='<?=$this->getUrl('checkout/cart/add',array('product'=>$product->getId()))?>'"><span>Add to Cart</span></button><br/>
					<?if($this->getCompareJsObjectName()):?>
					<a href="#" onclick="<?=$this->getCompareJsObjectName()?>.addItem(<?=$product->getId()?>);return false;"><small>Add to Compare</small></a><br/>
					<?endif;?>
					<a href="<?=$this->getUrl('wishlist/index/add',array('product'=>$product->getId()))?>"><small>Add to Wishlist</small></a></p>
				</td>

			<?if ($i%3==0):?></tr><?endif?>
			<?endforeach?>
            <?for($i;$i%3!=0;$i++):?>
            <td class="empty-product"></td>
            <?endfor?>
		</table>
	</div>
<!-- [ends] .listing-type-grid // -->
<?endif;?>
<?=$this->getPagerHtml()?>

