<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Language switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */

?>
<?if($this->getLanguageCount()>1):?>
<div class="language-switcher">
    <label for="select-language"><?=$this->__('Your Language')?>: </label>
    <select id="select-language" onchange="setLanguageCode(this.value)">
    <?foreach ($this->getLanguages() as $_store):?>
        <?$_selected = ($_store->getId()==$this->getCurrentStoreId()) ? 'selected="selected"' : ''?>
        <option value="<?=$_store->getCode()?>" <?=$_selected?>><?=$_store->getName()?></option>
    <?endforeach;?>
    </select>
</div>
<?endif;?>