<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<div class="page-title">
    <h1><?php echo __('Gift Registry'); ?></h1>
</div>
<?php $entityCollection = $this->getEntityCollection(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml();?>

<?php if ($entityCollection->getSize()):?>
    <?php echo $this->getChildHtml('pager') ?>
    <table class="data-table" id="giftregistry-table">
        <col />
        <col width="1" />
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo __('Event'); ?></th>
                <th><span class="nobr"><?php echo __('Created On'); ?></span></th>
                <th><?php echo __('Message'); ?></th>
                <th><?php echo __('Action'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($entityCollection as $item): ?>
                <tr>
                    <td title="<?php echo $this->getEscapedTitle($item)?>"><?php echo $this->helper('Magento\Core\Helper\String')->truncate($this->getEscapedTitle($item), 70)?></td>
                    <td><span class="nobr"><?php echo $this->getFormattedDate($item) ?></span></td>
                    <td><?php echo $this->getEscapedMessage($item)?></td>
                    <td>
                        <span class="nobr">
                            <a href="<?php echo $this->getItemsUrl($item)?>"><?php echo __('Manage Items') ?></a> <span class="separator">|</span>
                            <a href="<?php echo $this->getShareUrl($item)?>"><?php echo __('Share') ?></a> <span class="separator">|</span>
                            <a href="<?php echo $this->getEditUrl($item)?>"><?php echo __('Edit') ?></a> <span class="separator">|</span>
                            <a href="<?php echo $this->getDeleteUrl($item)?>" onclick="return confirm('<?php echo __('Are you sure you want to delete this gift registry?'); ?>');"><?php echo __('Delete') ?></a>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">(function($) {$('#giftregistry-table').decorate('table')})(jQuery)</script>
    <?php echo $this->getChildHtml('pager') ?>
<?php else:?>
    <p><?php echo __('No gift registries have been created.'); ?></p>
<?php endif;?>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
    <?php if ($this->canAddNewEntity()):?>
        <a class="button" href="<?php echo $this->escapeUrl($this->getAddUrl()) ?>"><span><?php echo __('Add New') ?></span></a>
    <?php endif;?>
</div>
