<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 ?>
<div class="fieldset-wrapper-title <?php echo $this->getHeaderCssClass() ?>">
	<span class="title"><?php echo $this->getHeaderText() ?></span>
	<div class="actions"></div>
</div>
<div class="form-inline" id="customer_account_fieds">
    <?php echo $this->getForm()->getHtml() ?>
</div>
<script type="text/javascript">order.accountFieldsBind($('customer_account_fieds'))</script>
