<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see Mage_Authorizenet_Block_Directpost_Form
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
    <?php echo $this->__('You will be required to enter your payment details before you place an order.') ?>
    </li>
</ul>
