<table width="100%" cellpadding="1" border="0">
    <tr>
        <td> Order # </td>
        <td>order date</td>
        <td>product name - link title (as link).</td>
        <td>Status</td>
        <td>remaining downloads</td>
    </tr>
     <tr>
        <td> <a href="#">00001</a> </td>
        <td>01.01.2008</td>
        <td><a href="#">product 1</a></td>
        <td>Pending</td>
        <td>0111</td>
    </tr>
     <tr>
        <td> <a href="#">00002</a> </td>
        <td>02.01.2008</td>
        <td><a href="#">product 2</a></td>
        <td>Pending</td>
        <td>0112</td>
    </tr>

</table>