<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this Enterprise_Checkout_Block_Adminhtml_Sku_Errors_Grid_Description */ ?>
<?php $_item = $this->getItem() ?>
<?php $_product = $this->getItem()->getProduct() ?>
<?php $_sku = $this->escapeHtml($_item->getSku()) ?>
<div id="<?php echo 'sku_' . $_sku ?>" class="sku-failed-item">
    <div class="sku-configure-button"><?php echo $this->getConfigureButtonHtml() ?></div>
    <?php if ($_product->getName()): ?>
        <strong><?php echo $this->escapeHtml($_product->getName()) ?></strong><br/>
    <?php endif ?>
    <strong><?php echo __('SKU: ') ?></strong> <?php echo $_sku ?><br/>
    <div class="notice">
        <div style="font-size: 95%"><?php echo $this->getErrorMessage($_item) ?></div>
    </div>

    <?php if ($_item->getQtyMaxAllowed()): ?>
        <?php echo __('Only <span id="%1_max_allowed">%2</span> in stock', $_sku, $_item->getQtyMaxAllowed()) ?>
    <?php endif ?>
    <input type="hidden" name="sku" value="<?php echo $_sku ?>"/>
    <input type="checkbox" name="<?php echo $this->getSourceId() ?>" value="<?php echo $_sku ?>" checked="checked" style="display:none"/>
</div>
