<script type="text/javascript">
function editTag(id, name) {
	var new_name = prompt('Please type new tag name', name)
	if (new_name) {
		var req = new Ajax.Request('/catalog/product/updatetag', { 
			method:'post',
			parameters: {
				tag_name: new_name, 
				tag_id: id
			},
			onSuccess: function(req, json){
				eval('var json = ' + req.responseText);
				if (1 === json.error) {				
					alert(json.error_message);
				}
			}
		});	
	}
}

function deleteTag(id) {
	if (confirm('Do tou realy want to delete the Tag?')) {
		var req = new Ajax.Request('/catalog/product/deletetag', { 
			method:'post',
			parameters: {
				tag_id: id
			},
			onSuccess: function(req, json){
				eval('var json = ' + req.responseText);
				if (1 === json.error) {				
					alert(json.error_message);
				}
			}
		});	
	}
}
</script>

<h1 class="page-heading">My Tags</h1>
<?php
foreach ($tags['data'] as $tag) { ?>
	<span>
		<a style="font-size:<?=$tag['size'];?>" href="/taggedproducts/?tag=<?=$tag['tag_name'];?>">
			<?=$tag['tag_name'];?>
		</a> 
		<span>
			<a href="#" title="edit tag" onclick="editTag(<?=$tag['id'];?>, '<?=$tag['tag_name'];?>'); return false;">e</a> 
			<a href="#" title="delete tag" onclick="deleteTag(<?=$tag['id'];?>); return false;">d</a>
		</span>
	</span>
<?php } ?>