
<h1 class="page-heading">Wishlist</h1>
<?if($wishlist->getSize()):?>
<form action="<?=$this->getUrl('customer/wishlist/updatePost')?>" method="post">
    <table cellspacing="0" width="100%" class="data-table">
        <tr>
            <th class="align-left">Product</th>
            <th style="width:60px;" class="align-center">Status</th>
            <th style="width:60px;" class="align-center">To cart</th>
            <th style="width:60px;" class="align-center">Remove</th>
        </tr>
        <?foreach($wishlist as $item):?>
        <tr>
            <td>
                <input type="hidden" value="1" name="wishlist[<?=$item->getItemId()?>]"/>
                <a href="<?=$this->getUrl('catalog/product/view/id/'.$item->getProduct()->getId())?>"><?=$item->getProduct()->getName()?></a>
            </td>
            <td class="align-center"><?=$item->getStatus()?></td>
            <td class="align-center"><input type="checkbox" value="1" name="to_cart[<?=$item->getItemId()?>]"/></td>
            <td class="align-center"><input type="checkbox" value="1" name="remove[<?=$item->getItemId()?>]"/></td>
        </tr>
        <?endforeach?>
    </table>
    <div class="buttons-container">
        <a href="<?=Mage::getBaseUrl()?>" class="float-left">&laquo; Continue Shopping</a>
        <input type="submit" value="Update" class="input-button" name="do"/>
    </div>
</form>
<?else:?>
    <p>You have not placed any product yet.</p>
<?endif?>