
    <?php $numColumns = sizeof($this->getColumns());?>
    <?php if($this->getCollection()): ?>
    <?php foreach ($this->getColumns() as $_column): ?>
        <col <?php echo $_column->getHtmlProperty() ?> />
        <?php endforeach; ?>
    <?php if ($this->isHeaderVisible() || $this->isFilterVisible()): ?>
        <thead>
            <?php if ($this->isHeaderVisible()): ?>
        <tr class="headings">
            <?php foreach ($this->getColumns() as $_column): ?>
            <th<?php echo $_column->getHeaderHtmlProperty() ?>><span class="nobr"><?php echo $_column->getHeaderHtml() ?></span></th>
            <?php endforeach; ?>
        </tr>
            <?php endif; ?>
            <?php if ($this->isFilterVisible()): ?>
        <tr class="filter">
            <?php $i=0;foreach ($this->getColumns() as $_column): ?>
            <th<?php echo $_column->getHeaderHtmlProperty() ?>><?php echo $_column->getFilterHtml() ?></th>
            <?php endforeach; ?>
        </tr>
            <?php endif ?>
        </thead>
        <?php endif; ?>
    <?php endif ?>
    <tbody>
    <?php if ($this->getCollection()->getSize()): ?>
        <?php foreach ($this->getCollection()->getIntervals() as $_index => $_item): ?>
                    <tr>
                    <?php $report=$this->getCollection()->getReport($_item['start'], $_item['end']) ?>
            <?php $rows=count($report) ?>
            <?php if ($rows > 0 ): ?>
                <td rowspan="<?php echo $rows + ($this->getCountTotals() && $this->getSubtotalVisibility()?1:0) ?>"><?php echo $_index ?></td>
                <?php $i=0;foreach ($report as $_subIndex=>$_subItem): ?>
                    <?php if($i>0): ?>
                            <tr>
                            <?php endif; ?>
                    <?php $i++;?>
                    <?php $j=0;foreach ($this->getColumns() as $index=>$_column): ?>
                        <?php if ($index == 'period_text') continue; ?>
                        <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$j==$numColumns?'last':'' ?>">
                            <?php echo (($_html = $_column->getRowField($_subItem)) != '' ? $_html : '&nbsp;') ?>
                        </td>
                        <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                <?php if($this->getCountTotals() && $rows > 0 && $this->getSubtotalVisibility()): ?>
                <tr>
                    <?php $j=0;foreach ($this->getColumns() as $_column): ?>
                    <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$j==$numColumns?'last':'' ?> subtotal">
                        <?php echo ($j==1)?$this->getSubtotalText():$_column->getRowField($this->getTotals()) ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
                    <?php endif; ?>
                <?php else: ?>
            <td><?php echo $_index ?></td>
            <td colspan="<?php echo $numColumns ?>" class="empty-text <?php echo $this->getEmptyTextClass() ?> last"><?php echo $this->getEmptyText() ?></td>
                <?php endif; ?>
        </tr>
            <?php endforeach; ?>
        <?php elseif ($this->getEmptyText()): ?>
    <tr>
        <td class="empty-text <?php echo $this->getEmptyTextClass() ?>" colspan="<?php echo $numColumns + 1 ?>"><?php echo $this->getEmptyText() ?></td>
    </tr>
        <?php endif; ?>
    </tbody>
    <?php if ($this->getCountTotals() && $this->getCollection()->getSize()): ?>
    <tfoot>
    <tr><th><?php echo $this->getTotalText() ?></th>
        <?php $j=0;foreach ($this->getColumns() as $_column): ?>
            <th class="<?php echo $_column->getCssProperty() ?> <?php echo ++$j==$numColumns?'last':'' ?>"><?php echo $_column->getRowField($this->getGrandTotals()) ?></th>
            <?php endforeach; ?>
    </tr>
    </tfoot>
    <?php endif; ?>
