<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * @var $this Magento_Page_Block_Js_Translate
 */
?>
<?php
$_data = array(
    'Please select an option.' => $this->__('Please select an option.'),
    'This is a required field.' => $this->__('This is a required field.'),
    'Please enter a valid number in this field.' => $this->__('Please enter a valid number in this field.'),
    'Please enter only numbers (1-9) into this field. Do not use spaces, commas, or any other characters.' => $this->__('Please enter only numbers (1-9) into this field. Do not use spaces, commas, or any other characters.'),
    'Please enter only letters (a-z) into this field.' => $this->__('Please enter only letters (a-z) into this field.'),
    'Please enter only numbers (0-9) or letters (a-z) into this field.' => $this->__('Please enter only numbers (0-9) or letters (a-z) into this field.'),
    'Please enter only numbers or letters into this field. Do not use spaces, commas, or any other characters.' => $this->__('Please enter only numbers or letters into this field. Do not use spaces, commas, or any other characters.'),
    'Please enter only letters (a-z), numbers (0-9), spaces and the "#" character into this field.' => $this->__('Please enter only letters (a-z), numbers (0-9), spaces and the "#" character into this field.'),
    'Please enter a valid phone number (for example, (123) 456-7890 or 123-456-7890).' => $this->__('Please enter a valid phone number (for example, (123) 456-7890 or 123-456-7890).'),
    'Please enter a valid date.' => $this->__('Please enter a valid date.'),
    'Please enter a valid email address(for example johndoe@domain.com.).' => $this->__('Please enter a valid email address(for example johndoe@domain.com.).'),
    'Please enter 6 or more characters.' => $this->__('Please enter 6 or more characters.'),
    'Please make sure your passwords match.' => $this->__('Please make sure your passwords match.'),
    'Please enter a valid URL (for example, the URL must begin with "http://").' => $this->__('Please enter a valid URL (for example, the URL must begin with "http://").'),
    'Please enter a valid URL (for examples, http://www.example.com or www.example.com).' => $this->__('Please enter a valid URL (for examples, http://www.example.com or www.example.com).'),
    'Please enter a valid social security number (for example, 123-45-6789).' => $this->__('Please enter a valid social security number (for example, 123-45-6789).'),
    'Please enter a valid zip code (for example, 90602 or 90602-1234).' => $this->__('Please enter a valid zip code (for example, 90602 or 90602-1234).'),
    'Please enter a valid zip code.' => $this->__('Please enter a valid zip code.'),
    'Please use this date format: dd/mm/yyyy. For example, enter "17/03/2006" to represent March 17, 2006.' => $this->__('Please use this date format: dd/mm/yyyy. For example, enter "17/03/2006" to represent March 17, 2006.'),
    'Please enter a valid dollar amount (for example, $100.00).' => $this->__('Please enter a valid dollar amount (for example, $100.00).'),
    'Please select one of these options.' => $this->__('Please select one of these options.'),
    'Please select an option.' => $this->__('Please select an option.'),
    'Please enter a valid URL (for example, the URL must begin with "http://").' => $this->__('Please enter a valid URL (for example, the URL must begin with "http://").'),
    'Please select State/Province.' => $this->__('Please select State/Province.'),
    'Please enter a valid password.' => $this->__('Please enter a valid password.'),
    'Please enter a number greater than 0 in this field.' => $this->__('Please enter a number greater than 0 in this field.'),
    'Please enter a valid credit card number.' => $this->__('Please enter a valid credit card number.'),
    'Please wait, loading...' => $this->__('Please wait, loading...')
);
?>
<script type="text/javascript">
    (function($) {
        $.mage.translate.add(<?php echo Zend_Json::encode($_data) ?>)
    })(jQuery);
</script>
