<?=$breadcrumbs?>
<div class="content">
    <h1><?=$category->getData('name')?></h1>
    <p><?=$category->getData('description')?></p>
    <div class="catalog-spacer">&nbsp;</div>
    <?include $moduleViewsDir.'/product/pager.phtml'?>
    <?include $moduleViewsDir.'/category/filters.phtml'?>
    <div class="catalog-collection">
        <?foreach ($productCollection as $product):?>
        <div class="item">
            <div class="item-image">
                <a href="<?=$product->getLink()?>"><img src="<?=$baseSkinUrl?>catalog/images/placeholder_product_small.jpg" alt="product name" width="115"/></a>
            </div>
            <div class="item-info">
                <div class="product-name"><a href="<?=$product->getLink()?>" title="<?=$product->getName()?>"><?=$product->getName()?></a></div>
                <div class="product-price"><?=$product->getFormatedPrice()?></div>
            </div>
        </div>
        <?endforeach?>
        <div class="clearfix"></div>
    </div>
    <?include $moduleViewsDir.'/product/pager.phtml'?>
    <div class="catalog-spacer">&nbsp;</div>
</div>