<?php echo'<?xml version="1.0"?>';?>

<rss version="2.0">
   <channel>
      <title><?=$channel_data->getTitle();?></title>
      <link><?=$baseUrl?>catalog/category/view/id/<?=$channel_data->getCategoryId();?></link>
      <description><?=$channel_data->getDescription();?></description>
      <pubDate><?=$channel_data->getPubDate();?></pubDate>

      <?foreach( $data as $item):?>

      <item>
         <title><?=htmlentities($item->getName());?></title>
         <link><?=$baseUrl?>catalog/product/view/id/<?=$item->getProductId();?></link>
         <description><?=htmlentities($item->getDescription());?></description>
         <pubDate><?=$item->getCreateDate();?></pubDate>
      </item>

      <?endforeach?>

   </channel>
</rss>
