<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
if ($exist = $this->getRecentlyComparedProducts()) {
    $type = 'widget-compared';
    $mode = 'list';

    $type = $type . '-' . $mode;

    $class = 'widget viewed' . ' ' . $mode;

    $imageBlock =  $this->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    $image = 'recently_compared_products_images_names_widget';
    $title = __('Recently Compared');
    $items = $exist;

    $showWishlist = false;
    $showCompare = false;
    $showCart = false;
    $rating = false;
    $description = false;
}
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="block <?php echo $class; ?>">
    <div class="title">
        <strong><?php echo $title; ?></strong>
    </div>
    <?php $suffix = $this->getNameInLayout(); ?>
    <ol class="mini products list items" id="widget-compared-<?php echo $suffix; ?>">
        <?php $iterator = 1; ?>
        <?php foreach($_products as $_product): ?>
        <?php echo ($iterator++==1) ? '<li class="item product">' : '</li><li class="item product">' ?>
                <a class="product photo" href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $imageBlock->init($_product, $image)->toHtml() ?>
                </a>
                <div class="product details">
                    <strong class="product name">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)">
                            <?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </strong>
                    <?php echo $this->getPriceHtml($_product, true, '-widget-compared-'.$suffix) ?>
                    <?php if($_product->isSaleable()): ?>
                        <div class="actions">
                            <a href="<?php echo $this->getAddToCartUrl($_product) ?>"
                               class="action tocart"><span><?php echo __('Add to Cart') ?></span></a>
                        </div>
                    <?php else: ?>
                        <?php if ($_product->getIsSalable()): ?>
                            <p class="stock available"><span><?php echo __('In stock') ?></span></p>
                        <?php else: ?>
                            <p class="stock unavailable"><span><?php echo __('Out of stock') ?></span></p>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php echo ($iterator==count($_products)+1) ? '</li>' : '' ?>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
