<div class="data-form">
<div class="x-box-tl"><div class="x-box-tr"><div class="x-box-tc"></div></div></div>
<div class="x-box-ml"><div class="x-box-mr"><div class="x-box-mc">
<h1><?=$product->getName()?></h1><br/>
<h2>
    Price: <?=$product->getPrice()?>
</h2><br/>
<p>
    <?=$product->getDescription()?>
</p>
</div></div></div>
<div class="x-box-bl"><div class="x-box-br"><div class="x-box-bc"></div></div></div>
</div>
