<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\GiftCardAccount\Block\Adminhtml\Giftcardaccount\Edit\Tab\Info */ ?>
<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>
</div>
<?php if (!$this->isSingleStoreMode()): ?>
<script type="text/javascript">
require(['prototype'], function(){
    var currencies = <?php echo $this->getCurrencyJson(); ?>;

    var updateCurrency = function()
    {
        var val = $('_infowebsite_id').options[$('_infowebsite_id').selectedIndex].value;
        if (currencies[val]) {
            $('balance_currency').innerHTML = '<b>[' + currencies[val] + ']</b>';
        }
    };

    Event.observe(window, 'load', updateCurrency);
    Event.observe($('_infowebsite_id'), 'change', updateCurrency);
});
</script>
<?php endif; ?>
