<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\Reports\Block\Product\Viewed
 */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="widget widget-viewed">
    <div class="block block-products">
        <div class="block-title">
            <strong><span><?php echo __('Recently Viewed') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-list" id="widget-viewed-<?php echo $suffix; ?>">
            <?php foreach ($_products as $_product): ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->getThumbnailSidebarUrl($_product); ?>" width="<?php echo $this->getThumbnailSidebarSize()?>" height="<?php echo $this->getThumbnailSidebarSize()?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-details">
                        <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('\Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                        <?php echo $this->getPriceHtml($_product, true, '-widget-viewed-'.$suffix) ?>
                        <?php if($_product->isSaleable()): ?>
                            <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart"><?php echo __('Add to Cart') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo __('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">(function($) {$('#widget-viewed-<?php echo $suffix; ?>').decorate('list', false)})(jQuery)</script>
        </div>
    </div>
</div>
<?php endif; ?>
