<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Template for displaying grouped product price
 */
?>
<?php
$minProduct = $this->getSaleableItem()
    ->getPriceInfo()
    ->getPrice(\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE)
    ->getMinProduct();
$amountRender = $this->getRendererPool()
    ->createAmountRender(
        $minProduct->getPriceInfo()->getPrice('final_price')->getAmount(),
        $minProduct,
        $minProduct->getPriceInfo()->getPrice('final_price'),
        []
    );
?>
<div class="price-box" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
    <?php if (\Magento\Pricing\Render::ZONE_ITEM_VIEW != $this->getZone()): ?>
    <p class="minimal-price">
        <span class="price-label"><?php echo __('Starting at:') . $amountRender->toHtml();?></span>
    </p>
    <?php endif ?>
</div>
