<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->getEnabled() && $this->getItems()) :?>
<script type="text/javascript">
//<![CDATA[
    function addGiftregistryAddressOption(item, address, selectedIndexes) {
        Form.getElements('checkout_multishipping_form').each(function(element) {
            if (element.type == 'select-one') {
                arr = element.id.split('_');

                if (arr[2] && arr[2] == item) {
                    var option = document.createElement('OPTION');
                    option.value = '<?php echo $this->getAddressIdPrefix(); ?>' + address;
                    option.text = '<?php echo $this->__('Use gift registry shipping address') ?>';

                    for (var i = 0; i < selectedIndexes.length; i++) {
                        if (selectedIndexes[i] == arr[1]) {
                            option.selected = 'selected';
                            break;
                        }
                    }

                    if (element.options.add) {
                        element.options.add(option);
                    } else {
                        element.appendChild(option);
                    }
                    var qtyElement = element.up('tr').down('input[type="text"]');
                    Event.observe(qtyElement, 'change', function(){
                        qtyElement.value = qtyElement.defaultValue;
                        alert('<?php echo $this->jsQuoteEscape($this->__('Changing quantity for gift registry items is not allowed during checkout. You can change item quantity on the Gift Registry Info page or directly in your shopping cart.')) ?>')
                    });
                }
            }
        });
    }

    <?php $selectedGrAddressesIndexes = $this->getGiftregistrySelectedAddressesIndexes(); ?>
    <?php $selectedGrAddressesIndexesJson = '[' . implode(',', $selectedGrAddressesIndexes) . ']'; ?>
    <?php foreach ($this->getItems() as $itemId => $registryItem) : ?>
        addGiftregistryAddressOption(
            <?php echo $itemId; ?>,
            <?php echo $registryItem['item_id']; ?>,
            <?php echo $selectedGrAddressesIndexesJson; ?>
        );
    <?php endforeach; ?>
//]]>
</script>
<?php endif; ?>
