<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Storelauncher_Payments_Drawer */

$saveActionUrl = $this->getUrl('*/storelauncher_payments_drawer/savePayment');
?>
<form action="" class="payments-setup-form ignore-validate" id="drawer-form" method="post">
<?php echo $this->getBlockHtml('formkey')?>
<ul class="payments-tabs-nav">
    <li class="active">
        <a href="#non-merchant-account" data-toggle="tab"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Solutions for Everyone'); ?></a>
    </li>
    <li>
        <a href="#merchant-account" data-toggle="tab"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Solutions for Merchant Bank Accounts'); ?></a>
    </li>
</ul>

<h2 class="title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose a payment method that fits your business.'); ?></h2>

<div class="payments-tiles">

    <div class="payment-method <?php if ($this->getConfigValue('payment/paypal_express/active')): ?> configured <?php endif; ?> active" data-payment-method="express-checkout">
        <img class="payment-logo" src="<?php echo $this->getViewFileUrl('Saas_Launcher::page/images/paypal-logo.png');?>" alt="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('PayPal Logo'); ?>"/>
        <h3 class="payment-title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Express Checkout'); ?></h3>
        <p class="payment-tagline"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Help boost sales with PayPal button'); ?></p>
        <ul class="payment-features">
            <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Add PayPal to increase your sales 18% on average'); ?></li>
            <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Add an Express Checkout button for a quick and easy way to pay'); ?></li>
            <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customer uses information stored in their PayPal accounts to check out quickly.'); ?></li>
        </ul>
        <a class="learn-more" href="<?php echo $this->getMoreUrl('payment/paypal_payments/express_checkout'); ?>" target="_blank">
            <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Learn more'); ?>
        </a>
        <footer class="payment-method-footer">
            <span class="price-plan"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Free'); ?></span>
            <div class="actions">
                <button type="button" class="action-configure-payment-method" data-payment-config="express-checkout">
                    <span data-text-default="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose PayPal Express'); ?>"
                          data-text-active="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Selected'); ?>"
                          data-text-edit="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit'); ?>">
                    </span>
                </button>
            </div>
        </footer>
    </div>

    <div class="payments-tab-content">
        <div class="tab-pane active" id="non-merchant-account">
            <div class="payment-method <?php if ($this->getConfigValue('payment/paypal_standard/active')): ?> configured <?php endif; ?>" data-payment-method="paypal-standard">
                <img class="payment-logo" src="<?php echo $this->getViewFileUrl('Saas_Launcher::page/images/paypal-logo.png');?>" alt="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('PayPal Logo'); ?>"/>
                <h3 class="payment-title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Standard'); ?></h3>
                <p class="payment-tagline"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('The fast and easy way to pay online'); ?></p>
                <ul class="payment-features">
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Simple setup, no programming required'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__("Customers don't need a PayPal account"); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Easiest way to accept credit cards, PayPal, and Bill Me Later&reg;.'); ?></li>
                </ul>
                <footer class="payment-method-footer">
                    <span class="price-plan"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Free'); ?></span>
                    <div class="actions">
                        <button type="button" class="action-configure-payment-method" data-payment-config="paypal-standard">
                            <span data-text-default="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose Standard'); ?>"
                                  data-text-active="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Selected'); ?>"
                                  data-text-edit="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit'); ?>">
                            </span>
                        </button>
                    </div>
                </footer>
            </div>
            <div class="payment-method <?php if ($this->getConfigValue('payment/payflow_advanced/active')): ?> configured <?php endif; ?>" data-payment-method="payments-advanced">
                <img class="payment-logo" src="<?php echo $this->getViewFileUrl('Saas_Launcher::page/images/paypal-logo.png');?>" alt="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('PayPal Logo'); ?>"/>
                <h3 class="payment-title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Payments Advanced'); ?></h3>
                <p class="payment-tagline"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers pay without leaving your site'); ?></p>
                <ul class="payment-features">
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers check out and pay on your website'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Simplifies PCI compliance'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers can pay by credit card, PayPal, or Bill Me Later&reg;.'); ?></li>
                </ul>
                <footer class="payment-method-footer">
                    <span class="price-plan"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('$5/month'); ?></span>
                    <div class="actions">
                        <button type="button" class="action-configure-payment-method" data-payment-config="payments-advanced">
                            <span data-text-default="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose Payments Advanced'); ?>"
                                  data-text-active="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Selected'); ?>"
                                  data-text-edit="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit'); ?>">
                            </span>
                        </button>
                    </div>
                </footer>
            </div>
            <div class="payment-method <?php if ($this->getConfigValue('payment/paypal_direct/active')): ?> configured <?php endif; ?>" data-payment-method="payments-pro">
                <img class="payment-logo" src="<?php echo $this->getViewFileUrl('Saas_Launcher::page/images/paypal-logo.png');?>" alt="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('PayPal Logo'); ?>"/>
                <h3 class="payment-title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Payments Pro'); ?></h3>
                <p class="payment-tagline"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__("You control your customers' checkout experience"); ?></p>
                <ul class="payment-features">
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers check out and pay without leaving your website'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Design and host your checkout pages for full control'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Accept credit cards by phone, fax, or mail'); ?></li>
                </ul>
                <footer class="payment-method-footer">
                    <span class="price-plan"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('$30/month'); ?></span>
                    <div class="actions">
                        <button type="button" class="action-configure-payment-method" data-payment-config="payments-pro">
                            <span data-text-default="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose Payments Pro'); ?>"
                                  data-text-active="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Selected'); ?>"
                                  data-text-edit="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit'); ?>">
                            </span>
                        </button>
                    </div>
                </footer>
            </div>
        </div>
        <div class="tab-pane" id="merchant-account">
            <div class="payment-method <?php if ($this->getConfigValue('payment/payflow_link/active')): ?> configured <?php endif; ?>" data-payment-method="payflow-link">
                <img class="payment-logo" src="<?php echo $this->getViewFileUrl('Saas_Launcher::page/images/paypal-logo.png');?>" alt="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('PayPal Logo'); ?>"/>
                <h3 class="payment-title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Payflow Link'); ?></h3>
                <p class="payment-tagline"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers pay without leaving your site'); ?></p>
                <ul class="payment-features">
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers check out and pay on your website'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Simplifies PCI compliance'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers can pay by credit card, PayPal, or Bill Me Later&reg;.'); ?></li>
                </ul>
                <p class="note-required"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Requires a merchant banking account.'); ?></p>
                <footer class="payment-method-footer">
                    <span class="price-plan"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Free'); ?></span>
                    <div class="actions">
                        <button type="button" class="action-configure-payment-method" data-payment-config="payflow-link">
                            <span data-text-default="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose Payflow Link'); ?>"
                                  data-text-active="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Selected'); ?>"
                                  data-text-edit="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit'); ?>">
                            </span>
                        </button>
                    </div>
                </footer>
            </div>
            <div class="payment-method <?php if ($this->getConfigValue('payment/verisign/active')): ?> configured <?php endif; ?>" data-payment-method="payflow-pro">
                <img class="payment-logo" src="<?php echo $this->getViewFileUrl('Saas_Launcher::page/images/paypal-logo.png');?>" alt="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('PayPal Logo'); ?>"/>
                <h3 class="payment-title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Payflow Pro'); ?></h3>
                <p class="payment-tagline"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__("You control your customers' checkout experience"); ?></p>
                <ul class="payment-features">
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Customers check out and pay without leaving your website'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Design and host your checkout pages for full control'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Accept credit cards by phone, fax, or mail.'); ?></li>
                </ul>
                <p class="note-required"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Requires a merchant banking account.'); ?></p>
                <footer class="payment-method-footer">
                    <span class="price-plan"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('$25/month'); ?></span>
                    <div class="actions">
                        <button type="button" class="action-configure-payment-method" data-payment-config="payflow-pro">
                            <span data-text-default="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose Payflow Pro'); ?>"
                                  data-text-active="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Selected'); ?>"
                                  data-text-edit="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit'); ?>">
                            </span>
                        </button>
                    </div>
                </footer>
            </div>
            <div class="payment-method <?php if ($this->getConfigValue('payment/authorizenet/active')): ?> configured <?php endif; ?>" data-payment-method="authorize">
                <img class="payment-logo" src="<?php echo $this->getViewFileUrl('Saas_Launcher::page/images/authorizenet-logo.png');?>" alt="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Authorize.net Logo'); ?>"/>
                <h3 class="payment-title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Authorize.net'); ?></h3>
                <p class="payment-tagline"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Flexible, reliable and secure web transactions'); ?></p>
                <ul class="payment-features">
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Accept a variety of payment methods'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Safe and secure (PCI-DSS compliant)'); ?></li>
                    <li><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Automatic deposit of funds into your bank account.'); ?></li>
                </ul>
                <p class="note-required"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Requires a merchant banking account.'); ?></p>
                <footer class="payment-method-footer">
                    <span class="price-plan"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('$20/month'); ?></span>
                    <div class="actions">
                        <button type="button" class="action-configure-payment-method" data-payment-config="authorize">
                            <span data-text-default="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose Authorize.net'); ?>"
                                  data-text-active="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Selected'); ?>"
                                  data-text-edit="<?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit'); ?>">
                            </span>
                        </button>
                    </div>
                </footer>
            </div>
        </div>
    </div>
</div>
    <div class="payments-config-data">
        <div class="payment-config" id="express-checkout" data-payment-method="express-checkout">
            <p class="payment-info"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('With Paypal Express Checkout, you can accept payments now, and set up your payments account later'); ?><p>
            <fieldset class="fieldset">
                <legend class="legend"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('PayPal payments will be sent to your email address at:'); ?></legend>
                <input type="hidden" name="groups[global][fields][express][value]" value="1">
                <input type="hidden" name="payment_method" value="paypal_express_checkout">
                <div class="field field-store-paypal-express-email with-note">
                    <div class="control">
                        <input type="text" name="groups[account][fields][business_account][value]" class="input-text  validate-email required-entry" value="<?php echo $this->getConfigValue('paypal/general/business_account'); ?>" id="store-paypal-express-email">
                    </div>
                    <button type="button" class="action-save-method primary" data-save-url="<?php echo $saveActionUrl; ?>">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Confirm'); ?></span>
                    </button>
                </div>
            </fieldset>

            <p class="payment-info"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('For your convenience, we have automatically enabled PayPal Express Checkout.'); ?><p>
        </div>

        <div class="payment-config" id="paypal-standard">
            <fieldset class="fieldset">
                <legend class="legend"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Please email address associated with the PayPal account'); ?></legend>
                <input type="hidden" name="groups[global][fields][wps][value]" value="1">
                <input type="hidden" name="payment_method" value="paypal_payments_standard">
                <div class="field field-store-paypal-standard-email with-note required">
                    <label for="store-paypal-standard-email" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Email'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="groups[account][fields][business_account][value]" class="input-text validate-email required-entry" value="<?php echo $this->getConfigValue('paypal/general/business_account'); ?>" id="store-paypal-standard-email">
                        <div class="note"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Payments will be sent to this address'); ?></div>
                    </div>
                </div>
                <div class="actions">
                    <button type="button" class="action-save-method primary" data-save-url="<?php echo $saveActionUrl; ?>">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Confirm'); ?></span>
                    </button>
                </div>
            </fieldset>
        </div>

        <div class="payment-config" id="payments-advanced">
            <fieldset class="fieldset">
                <legend class="legend"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Please enter your account credentials'); ?></legend>
                <input type="hidden" name="groups[global][fields][payflow_advanced][value]" value="1">
                <input type="hidden" name="payment_method" value="paypal_payments_advanced">
                <div class="field field-advanced-partner required">
                    <label for="advanced-partner" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Partner'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="groups[payflow_advanced][fields][partner][value]" value="<?php echo $this->getConfigValue('payment/payflow_advanced/partner'); ?>" class="input-text required-entry" id="advanced-partner">
                    </div>
                </div>
                <div class="field field-advanced-vendor required">
                    <label for="advanced-vendor" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Vendor / Merchant Login'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="groups[payflow_advanced][fields][vendor][value]" value="<?php echo $this->getConfigValue('payment/payflow_advanced/vendor'); ?>" class="input-text required-entry" id="advanced-vendor">
                    </div>
                </div>
                <div class="field field-advanced-user required">
                    <label for="advanced-user" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('User'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="groups[payflow_advanced][fields][user][value]" value="<?php echo $this->getConfigValue('payment/payflow_advanced/user'); ?>" class="input-text required-entry" id="advanced-user">
                    </div>
                </div>
                <div class="field field-advanced-password required">
                    <label for="advanced-password" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Password'); ?></span>
                    </label>
                    <div class="control">
                        <input type="password" name="groups[payflow_advanced][fields][pwd][value]" value="<?php echo $this->getObscuredConfigValue('payment/payflow_advanced/pwd'); ?>" class="input-text required-entry" id="advanced-password">
                    </div>
                </div>
                <div class="actions">
                    <button type="button" class="action-save-method primary" data-save-url="<?php echo $saveActionUrl; ?>">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Confirm'); ?></span>
                    </button>
                </div>
            </fieldset>
        </div>

        <div class="payment-config" id="payments-pro">
            <fieldset class="fieldset">
                <legend class="legend"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Please enter your account credentials'); ?></legend>
                <input type="hidden" name="groups[global][fields][express][value]" value="1">
                <input type="hidden" name="groups[global][fields][wpp][value]" value="1">
                <input type="hidden" name="payment_method" value="paypal_payments_pro">
                <div class="field field-payments-pro-email required">
                    <label for="payments-pro-email" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Email'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" name="groups[account][fields][business_account][value]" class="input-text validate-email required-entry" value="<?php echo $this->getConfigValue('paypal/general/business_account'); ?>" id="payments-pro-email">
                    </div>
                </div>
                <div class="actions">
                    <button type="button" class="action-save-method primary" data-save-url="<?php echo $saveActionUrl; ?>">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Confirm'); ?></span>
                    </button>
                </div>
            </fieldset>
        </div>

        <div class="payment-config" id="payflow-link">
            <fieldset class="fieldset">
                <legend class="legend"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Please enter your account credentials'); ?></legend>
                <input type="hidden" name="groups[global][fields][payflow_link][value]" value="1">
                <input type="hidden" name="payment_method" value="paypal_payflow_link">
                <div class="field field-payflow-link-partner required">
                    <label for="payflow-link-partner" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Partner'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text required-entry" id="payflow-link-partner" name="groups[payflow_link][fields][partner][value]" value="<?php echo $this->getConfigValue('payment/payflow_link/partner'); ?>">
                    </div>
                </div>
                <div class="field field-payflow-link-vendor required">
                    <label for="payflow-link-vendor" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Vendor / Merchant Login'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text required-entry" id="payflow-link-vendor" name="groups[payflow_link][fields][vendor][value]" value="<?php echo $this->getConfigValue('payment/payflow_link/vendor'); ?>">
                    </div>
                </div>
                <div class="field field-payflow-link-user required">
                    <label for="payflow-link-user" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('User'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text required-entry" id="payflow-link-user" name="groups[payflow_link][fields][user][value]" value="<?php echo $this->getConfigValue('payment/payflow_link/user'); ?>">
                    </div>
                </div>
                <div class="field field-payflow-link-password required">
                    <label for="payflow-link-password" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Password'); ?></span>
                    </label>
                    <div class="control">
                        <input type="password" class="input-text required-entry" id="payflow-link-password" name="groups[payflow_link][fields][pwd][value]" value="<?php echo $this->getObscuredConfigValue('payment/payflow_link/pwd'); ?>">
                    </div>
                </div>

                <div class="actions">
                    <button type="button" class="action-save-method primary" data-save-url="<?php echo $saveActionUrl; ?>">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Confirm'); ?></span>
                    </button>
                </div>
            </fieldset>
        </div>

        <div class="payment-config" id="payflow-pro">
            <fieldset class="fieldset">
                <legend class="legend"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Please enter your account credentials'); ?></legend>
                <input type="hidden" name="groups[global][fields][verisign][value]" value="1">
                <input type="hidden" name="payment_method" value="paypal_payflow_pro">
                <div class="field field-payflow-pro-partner required">
                    <label for="payflow-pro-partner" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Partner'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text required-entry" id="payflow-pro-partner" name="groups[verisign][fields][partner][value]" value="<?php echo $this->getConfigValue('payment/verisign/partner'); ?>">
                    </div>
                </div>
                <div class="field field-payflow-pro-partner-vendor required">
                    <label for="payflow-pro-partner-vendor" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Vendor / Merchant Login'); ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text required-entry" id="payflow-pro-partner-vendor" name="groups[verisign][fields][vendor][value]" value="<?php echo $this->getConfigValue('payment/verisign/vendor'); ?>">
                    </div>
                </div>
                <div class="field field-payflow-pro-partner-user required">
                    <label for="payflow-pro-user" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('User'); ?></span>
                    </label>
                    <div class="control">
                        <input type="password" class="input-text required-entry" id="payflow-pro-user" name="groups[verisign][fields][user][value]" value="<?php echo $this->getObscuredConfigValue('payment/verisign/user'); ?>">
                    </div>
                </div>
                <div class="field field-payflow-pro-password required">
                    <label for="payflow-pro-password" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Password'); ?></span>
                    </label>
                    <div class="control">
                        <input type="password" class="input-text required-entry" id="payflow-pro-password" name="groups[verisign][fields][pwd][value]" value="<?php echo $this->getObscuredConfigValue('payment/verisign/pwd'); ?>">
                    </div>
                </div>
                <div class="actions">
                    <button type="button" class="action-save-method primary" data-save-url="<?php echo $saveActionUrl; ?>">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Confirm'); ?></span>
                    </button>
                </div>
            </fieldset>
        </div>

        <div class="payment-config" id="authorize">
            <fieldset class="fieldset">
                <legend class="legend"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Please enter your account credentials'); ?></legend>
                <input type="hidden" name="groups[authorizenet][fields][active][value]" value="1">
                <input type="hidden" name="payment_method" value="authorize_net">
                <div class="field field-authorize-login required">
                    <label for="authorize-login" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('API Login ID'); ?></span>
                    </label>
                    <div class="control">
                        <input type="password" class="input-text required-entry" id="authorize-login" name="groups[authorizenet][fields][login][value]" value="<?php echo $this->getObscuredConfigValue('payment/authorizenet/login'); ?>">
                    </div>
                </div>
                <div class="field field-authorize-key required">
                    <label for="authorize-key" class="label">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Transaction Key'); ?></span>
                    </label>
                    <div class="control">
                        <input type="password" class="input-text required-entry" id="authorize-key" name="groups[authorizenet][fields][trans_key][value]" value="<?php echo $this->getObscuredConfigValue('payment/authorizenet/trans_key'); ?>">
                    </div>
                </div>
                <div class="actions">
                    <button type="button" class="action-save-method primary" data-save-url="<?php echo $saveActionUrl; ?>">
                        <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Confirm'); ?></span>
                    </button>
                </div>
            </fieldset>
        </div>
    </div>
</form>

<script type="text/javascript">
jQuery(function ($) {
    'use strict';

    $('.payment-method')
        .on('click.configurePaymentMethod', function () {
            var elem = $(this),
                activePaymentTile = $('.payment-method').filter('.active'),
                paymentMethod = elem.attr('data-payment-method');

            activePaymentTile.removeClass('active');
            elem.addClass('active');

            $('#' + paymentMethod)
                .show()
                .siblings()
                .hide();
        });

    $('.action-save-method').partiallyValidateDrawer({'currentSection': '.payments-tiles'});
});
</script>
