<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="sidebar-block" id="sidebar_data_<?=$this->getDataId()?>">
    <table class="caption" width="100%">
    <tr>
        <td class="text"><strong><?=$this->getHeaderText()?></strong> (<?=$this->getItemCount()?>)</td>
        <td class="icons">
        <a href="#" title="<?=__('Refresh')?>" onclick="order.loadArea('sidebar_<?=$this->getDataId()?>', 'sidebar_data_<?=$this->getDataId()?>');return false;">
            <img src="<?=$this->getSkinUrl('images/fam_refresh.gif')?>" alt="<?=__('Refresh')?>" width="16" height="16"/>
        </a>
        </td>
    </tr>
    </table>
    <div class="auto-scroll">
    <ul>
        <?foreach ($this->getItems() as $_item):?>
        <li>
            <span><?=$_item->getName()?></span><br/>
            <span><?=$this->formatPrice($_item->getPrice())?></span><br/>
            <?if($this->canRemoveItems()):?>
            <a href="#" onclick="order.removeSidebarItem ('<?=$this->getItemId($_item)?>', '<?=$this->getDataId()?>');return false;">
                <?=__('Remove')?></a> | 
            <?endif;?>
            <a href="#" onclick="order.addProduct('<?=$this->getProductId($_item)?>');return false;"><?=__('Add to Order')?></a>
        </li>
        <?endforeach;?>
    </ul>
    </div>
</div>