<?if(!empty($collection) && $collection->getSize()):?>
	<div class="head">
		<h4><?=__('Customer Reviews')?></h4>
		<?if($reviewCount):?>
			<?if( $this->getUseBackLink() ):?>
			&laquo; <a href="<?=$backLink?>"><?=__('Back')?></a>
			<?else:?>
			<a href="<?=$reviewLink?>"><?=__('View all')?></a>
			<?endif;?>
		<?endif;?>
	</div>
    <?if( $this->getUseBackLink() ):?>
    <?=$this->getToolbarHtml()?>
    <?endif;?>
	<ol id="customer-reviews">
    <?foreach ($this->getCollection() as $_review):?>
        <li>
        <?if( is_array($_review->getRatingVotes()->getItems()) ):?>
            <?$avarage = 0;?>
            <?foreach( $_review->getRatingVotes()->getItems() as $_vote ):?>
            <?$avarage+= $_vote->getPercent();?>
            <?endforeach;?>
            <?if($_review->getRatingVotes()->getSize()):?>
            <?$avarage = ceil($avarage / $_review->getRatingVotes()->getSize())?>
            <div class="rating-box">
                <div class="rating" style="width:<?=$avarage?>%;"></div>
            </div>
            <?endif;?>
        <?endif;?>
            <a href="<?=$_review->getReviewUrl()?>" name="<?=$_review->getTitle()?>"><strong><?=$_review->getTitle()?></strong></a> by <em><?=$_review->getNickname()?></em>
            <p class="no-padding"><?=nl2br($_review->getDetail())?></p>
        </li>
    <?endforeach;?>
	</ol>
	<?if( $this->getUseBackLink() ):?>
	<?=$this->getToolbarHtml()?>
	<?endif;?>
<?else:?>
	<div class="head">
		<h4><?=__('Customer Reviews')?></h4>
	</div>
	<p><a href="<?=$reviewLink?>#review-form"><?=__('Be the first to review this product')?></a></p>
<?endif;?>
