<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Language switcher template
 *
 * @var $this \Magento\Page\Block\Switcher
 */
?>

<?php if(count($this->getStores())>1): ?>
<div class="switch switcher-language">
    <label><?php echo __('Language') ?>:</label>
    <div class="switch-wrapper" id="language-select" tabindex="-1">
        <strong class="current language-<?php echo $this->escapeHtml($this->getStoreCode()) ?>">
            <?php echo $this->escapeHtml($this->getStoreName()) ?>
        </strong>
        <span class="switcher-holder">(<span class="switcher"><?php echo __('Change')?></span>)</span>
        <ul style="display:none" id="popup-language-select">
            <?php foreach ($this->getStores() as $_lang): ?>
                <?php if($_lang->getId()!=$this->getCurrentStoreId()): ?>
                    <li class="language-<?php echo $this->escapeHtml($_lang->getCode()); ?>">
                        <a href="<?php echo $_lang->getCurrentUrl() ?>"><?php echo $this->escapeHtml($_lang->getName()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_Page::js/popup-menu.js')?>", function() {
            $('#language-select').popUpMenu({menu: '#popup-language-select'});
        });
    })(jQuery);
</script>
<?php endif; ?>

