<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Tax_Tile */
?>
<article class="tile-store-settings tile-tax <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>" tabindex="0">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Tax Rules') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('You can upload your current tax rules, create new ones, or we can recommend them based on your business location.') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/load') ?>">
            <span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Set Tax Rules') ?></span>
        </button>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) : ?>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode(); ?>"
                data-save-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/save'); ?>"
                data-load-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/load'); ?>">
            <span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Set Tax Rules'); ?></span>
        </button>
        <p class="tile-more-info">
            <?php echo $this->escapeHtml($this->__('You can find more settings on System -> Manage Tax Rules page')); ?>
            (<a href="<?php echo $this->getUrl('adminhtml/tax_rule/index'); ?>"><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('direct link'); ?></a>)
        </p>
        <?php endif; ?>
    </div>
</article>
