<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var \Magento\Page\Block\Html\Header $this
 */
?>

<?php switch($this->getShowPart()):
    case 'logo': ?>
        <?php $storeName = $this->getThemeName() ? $this->getThemeName() : $this->getLogoAlt();?>
        <?php if ($this->getIsHomePage()):?>
        <strong class="logo">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
        </strong>
        <?php else:?>
        <a class="logo" href="<?php echo $this->getUrl(''); ?>" title="<?php echo $storeName ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $storeName ?>" />
        </a>
        <?php endif?>
    <?php break; ?>

    <?php case 'welcome': ?>
        <p class="welcome"><?php echo $this->getWelcome() ?></p>
    <?php break; ?>

    <?php case 'other': ?>
        <?php echo $this->getChildHtml(); ?>
    <?php break; ?>

<?php endswitch; ?>
