<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Magento_GiftWrapping_Block_Product_Info */
?>

<?php if ($this->getGiftWrappingInfo()) : ?>
<dl class="item-options">
    <dt><?php echo $this->__('Gift Wrapping'); ?></dt>
    <dd><?php echo $this->__('Design'); ?> : <?php echo $this->escapeHtml($this->getGiftWrappingInfo()->getDesign()); ?></dd>
</dl>
<?php endif; ?>
