<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php foreach ($this->getValues() as $label => $value):?>
<tr class="total gift wrapping">
    <td class="mark" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $label; ?>
    </td>
    <td class="amount last">
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($value) ?>
    </td>
</tr>
<?php endforeach; ?>
