<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<p><strong><?php echo __('Please stand by. In a moment, this page will transfer your data to the Ogone payment gateway.'); ?></strong></p>
<form name="ogone" id="ogone-review-form" action="<?php echo $this->getFormAction();?>" method="post" accept-charset="ISO-8859-1">
    <?php if ($formData = $this->getFormData()): ?>
    <fieldset>
        <?php foreach ($formData as $name => $value) { ?>
            <input type="hidden" name="<?php echo $this->escapeHtml($name); ?>" value="<?php echo $this->escapeHtml($value); ?>" />
        <?php }?>
    </fieldset>
    <?php endif; ?>
</form>
<script type="text/javascript">
    // submit the form as soon as it is displayed to transfer over to the ogone website
    window.onload = function() {
        jQuery("#ogone-review-form").submit();
    };
</script>
