<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
?>
<?php if ($_source->getCustomerBalTotalRefunded()): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo __('Refunded to Store Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>><?php echo $_order->formatPrice($_source->getCustomerBalTotalRefunded()) ?></td>
</tr>
<?php endif; ?>
