<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $_product = $this->getProduct() ?>
<?php $_options = $this->getOptions() ?>

<?php echo $this->getPriceHtml($_product) ?>



<script type="text/javascript">
var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
</script>
<style>
<!--
    table#super-product-table select.bundle-option-select{
        width: 100%;
    }
-->
</style>
<?php if($_product->isSaleable()): ?>
    <table cellspacing="0" class="data-table" id="super-product-table">
        <thead>
            <tr>
                <th><?php echo $this->__('Option') ?></th>
                <th><?php echo $this->__('Selection') ?></th>
                <th class="a-center"><?php echo $this->__('Qty') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php if (count($_options)): ?>
        <?php foreach ($_options as $_option): ?>
            <?php if (!$_option->getSelections()): ?>
                <?php continue; ?>
            <?php endif; ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="<?php if ($_product->isSaleable()): ?>3<?php else: ?>2<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
    <p><small><?php echo $this->__('Availability: In stock.') ?></small></p>

    <span class="regular-price" id="bundle-price-<?php echo $_product->getId() ?>">
        <?php echo Mage::helper('core')->currency($_product->getPrice()) ?>
    </span>
    <br />
    <br />
<?php else: ?>
    <p><small><?php echo $this->__('Availability: Out of stock.') ?></small></p>
<?php endif; ?>

<?php if($_product->isSaleable()): ?>
    <fieldset class="add-to-cart-box">
        <legend><?php echo $this->__('Add Items to Cart') ?></legend>
        <span class="qty-box"><label for="qty"><?php echo $this->__('Qty') ?>:</label>
        <input name="qty" type="text" class="input-text qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" /></span>
        <button class="form-button" onclick="productAddToCartForm.submit()"><span><?php echo $this->__('Add to Cart') ?></span></button>
        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
            <strong><?php echo $this->__('OR') ?></strong>
        <?php endif; ?>
    </fieldset>
<?php endif; ?>

<div class="add-to-box">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a><br/>
<?php endif; ?>

<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
    <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
<?php endif; ?>
</div>

<script type="text/javascript">decorateTable('super-product-table')</script>