<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this \Magento\GiftCard\Block\Catalog\Product\View\Type\Giftcard */?>
<?php $_product = $this->getProduct(); ?>
<?php $_id = $_product->getId(); ?>
<div class="giftcard form" data-container-for="giftcard_info">
    <?php echo $this->getChildHtml('product_type_data_extra') ?>

    <?php if ($_product->isSaleable() && $this->isConfigured($_product)): ?>
        <fieldset class="fieldset giftcard send">
            <legend class="legend"><span><?php echo __('Gift Card Information'); ?></span></legend>
            <div class="field sender required">
                <label for="giftcard_sender_name" class="label"><span><?php echo __('Sender Name'); ?></span></label>
                <div class="control">
                    <input type="text"
                           id="giftcard_sender_name"
                           name="giftcard_sender_name"
                           class="required-entry input-text"
                           value="<?php echo $this->escapeHtml($this->getDefaultSenderName()) ?>" />
                </div>
            </div>
            <?php if ($this->isEmailAvailable($_product)): ?>
                <div class="field sender email required">
                    <label for="giftcard_sender_email" class="label"><span><?php echo __('Sender Email'); ?></span></label>
                    <div class="control">
                        <input type="text"
                               id="giftcard_sender_email"
                               name="giftcard_sender_email"
                               class="validate-email required-entry input-text"
                               value="<?php echo $this->escapeHtml($this->getDefaultSenderEmail()) ?>"/>
                    </div>
                </div>
            <?php endif; ?>

            <div class="field recipient required">
                <label for="giftcard_recipient_name" class="label"><span><?php echo __('Recipient Name'); ?></span></label>
                <div class="control">
                    <input type="text"
                           id="giftcard_recipient_name"
                           name="giftcard_recipient_name"
                           class="required-entry input-text"
                           value="<?php echo $this->escapeHtml($this->getDefaultValue('giftcard_recipient_name')) ?>" />
                </div>
            </div>
            <?php if ($this->isEmailAvailable($_product)): ?>
                <div class="field recipient email required">
                    <label for="giftcard_recipient_email" class="label"><span><?php echo __('Recipient Email'); ?></span></label>
                    <div class="control">
                        <input type="text"
                               id="giftcard_recipient_email"
                               name="giftcard_recipient_email"
                               class="validate-email required-entry input-text"
                               value="<?php echo $this->escapeHtml($this->getDefaultValue('giftcard_recipient_email')) ?>" />
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($this->isMessageAvailable($_product)): ?>
                <div class="field text">
                    <label for="giftcard-message" class="label"><span><?php echo __('Message'); ?></span></label>
                    <div class="control">
                        <textarea name="giftcard_message" id="giftcard-message" class="input-text giftcard-message-max-length"
                            <?php if ($this->getMessageMaxLength()) {
                                $errorMessage="'". __('Maximum length of the message is %1 characters.', $this->getMessageMaxLength())."'";
                                echo 'data-validate="{maxlength:' . $this->getMessageMaxLength() . ',messages:{maxlength:'.$errorMessage.'}}"';
                            } ?>
                            cols="5" rows="3"><?php echo $this->escapeHtml($this->getDefaultValue('giftcard_message')) ?></textarea>
                    </div>
                </div>
            <?php endif; ?>
        </fieldset>
    <?php elseif ($_product->isAvailable() && $this->isConfigured($_product)): ?>
        <?php echo $this->getProductPrice($_product);?>
    <?php endif; ?>
</div>
<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ], function($){

        $.mage.addToWishlist.prototype.options.giftcardInfo = '[id^=giftcard]';

    });
</script>