<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Promotestore_Customercommunication_Drawer */
?>
<div class="drawer-header-content">
    <form id="drawer-form">
        <h2 class="title"><?php echo $this->__('Guidelines and Best Practices') ?> </h2>
        <article class="entry">
            <p><?php echo $this->__('Every customer touchpoint deserves careful thought and planning, no matter what size your business. Since emails are often your primary way to communicate with customers, pay special attention to this channel. A consistent, positive voice and tone boosts loyalty and bonds customers to your brand. Use these links to set up addresses and titles and customize content of emails to your customers.') ?> </p>
        </article>
        <div class="go-do">
            <h2 class="title-checklist"><?php echo $this->__('Go Do') ?> </h2>
            <ul class="checklist">
                <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'trans_email', '_fragment' => 'trans_email_ident_general-link')); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create Email Addresses'); ?></a></li>

                <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'design', '_fragment' => 'design_email-link')); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create Email Logo'); ?></a></li>

                <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'sales_email', '_fragment' => 'sales_email_order-link')); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create Sales Emails'); ?></a></li>

                <?php $trackerLink = $this->getTrackerLink('adminhtml/system_email_template'); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create Transactional Email'); ?></a></li>
            </ul>
        </div>
    </form>
</div>



