<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="dashboard-diagram">
    <div class="store-switcher">
        <label><?php echo __('Select Range') ?>:
            <select name="period" id="order_<?php echo $this->getHtmlId() ?>_period" onchange="changeDiagramsPeriod(this);">
                <?php foreach ($this->helper('Magento\Adminhtml\Helper\Dashboard\Data')->getDatePeriods() as $value => $label): ?>
                    <?php if(in_array($value, array('custom'))) continue; ?>
                    <option value="<?php echo $value ?>" <?php if ($this->getRequest()->getParam('period') == $value): ?> selected="selected"<?php endif; ?>><?php echo $label ?></option>
                <?php endforeach; ?>
            </select>
        </label>
    </div>
<?php
    $containerStyle = "width:{$this->getWidth()}px;height:{$this->getHeight()}px; margin:0 auto;";
?>
    <?php if($this->getCount()): ?>
    <div style="<?php echo $containerStyle?>"><img src="<?php echo $this->getChartUrl(false) ?>" alt="chart" title="chart" /></div>
    <?php else: ?>
    <div class="dashboard-diagram-nodata"><?php echo __('No Data Found') ?></div>
    <?php endif; ?>
</div>
