<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>

<?php
/* @var $this \Magento\Cms\Block\Adminhtml\Page\Edit\Form */
?>

<div class="form-inline">
    <?php echo $this->getFormHtml() ?>
</div>

<div id="version_fieldset" class="fieldset-wrapper version-fieldset">
    <div class="fieldset-wrapper-title">
        <span class="title">
            <?php echo __('Version Revisions') ?>
        </span>
    </div>
    <?php echo $this->getParentBlock()->getChildHtml('cms_page_version_edit_revisions_grid') ?>
</div>
