<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <button class="action- add default" onclick="window.location='<?php echo $this->getCreateUrl() ?>'">
        <span><?php echo Mage::helper('Magento_Newsletter_Helper_Data')->__('Add New Template'); ?></span>
    </button>
</div>
<?php echo $this->getChildHtml('grid') ?>
