<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->getTotal()->getValue()): ?>
    <tr class="totals ballance">
        <th colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="mark" scope="row">
            <?php $_title = __('Remove'); ?>
            <?php $_url = $this->getUrl('magento_customerbalance/cart/remove'); ?>
            <a href="<?php echo $_url; ?>" title="<?php echo $_title; ?>" class="action delete"><span><?php echo $_title; ?></span></a>

            <?php echo $this->getTotal()->getTitle(); ?>
        </th>
        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="amount"
            data-th="<?php echo $this->escapeHtml($this->getTotal()->getTitle()); ?>">
            <span class="discount"><?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getTotal()->getValue()) ?></span>
        </td>
    </tr>
<?php endif; ?>
