<div class="content">
<h1 class="page-heading">Wishlist</h1>
<?if($wishlist->getSize()):?>
<form action="<?=Mage::getUrl('customer', array('controller'=>'wishlist', 'action'=>'updatePost'))?>" method="post">
    <table cellspacing="2" width="100%" class="data-table">
        <tr>
            <th class="align-left">Product</th>
            <th style="width:60px;" class="align-center">To cart</th>
        </tr>
        <?foreach($wishlist as $item):?>
        <tr>
            <td>
                <a href="<?=Mage::getUrl('catalog', array('controller'=>'product', 'action'=>'view', 'id'=>$item->getProduct()->getId()))?>"><?=$item->getProduct()->getName()?></a></td>
            <td class="align-center"><input type="checkbox" value="<?=$item->getItemId()?>" name="to_cart[]"/></td>
        </tr>
        <?endforeach?>
    </table>
    <div class="buttons-container">
        <div class="input-left">
            <input type="button" value="Continue Shopping" onclick="location.href='<?=Mage::getBaseUrl()?>'" class="input-button"/>
        </div>
        <div class="input-right align-right">
            <input type="submit" value="Update" class="input-button" name="do"/>
        </div>
        <div class="clearfix"></div>
    </div>
</form>
<?else:?>
    <p>You have not placed any product yet.</p>
<?endif?>
</div>