<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3>
                  <?php if($this->getUser()->getUserId()): ?>
                  <?php $_userName = $this->getUser()->getFirstname() . ' ' . $this->getUser()->getLastname() ?>
                  <?php echo __("Edit User '%1'", $_userName) ?>
                  <?php else: ?>
                  <?php echo __('Add New User') ?>
                  <?php endif; ?>
                </h3>
            </td>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getResetButtonHtml() ?>
            <?php echo $this->getDeleteButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
   </table>
</div>
<form action="<?php echo $this->getUrl('*/*/saveuser') ?>" method="post" id="user-edit-form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    jQuery('#user-edit-form').form().validation();
</script>
