<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $this \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use \Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="limiter">
    <label for="limiter">
        <strong class="limiter-label"><?php echo __('Show') ?></strong>
    </label>
    <select id="limiter" data-role="limiter" class="limiter-options">
        <?php foreach ($this->getAvailableLimit() as $_key => $_limit): ?>
            <option value="<?php echo $_key ?>"<?php if ($this->isLimitCurrent($_key)): ?>
                selected="selected"<?php endif ?>>
                <?php echo $_limit ?>
            </option>
        <?php endforeach; ?>
    </select>
    <span class="limiter-text"><?php echo __('per page') ?></span>
</div>
