<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_Composite */ ?>
<?php
/** @var $element Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_Composite_Abstract|Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_Logo|Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_Background */
$element = $this->getElement();
?>

<?php /** @var $child Magento_Data_Form_Element_Abstract */ ?>
<?php foreach ($element->getElements() as $child): ?>
    <?php echo $child->toHtml(); ?>
<?php endforeach; ?>

