<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_Composite */ ?>
<?php
/** @var $element Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_Composite_Abstract|Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_Logo|Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_Background */
$element = $this->getElement();

$containerId = $element->getFieldsetContainerId();
$id = $element->getHtmlId();
$isCollapsable = $element->getCollapsable();
$isWrapped = $containerId || $element->getHeaderBar() || $isCollapsable;
$titleActions = $element->getHeaderBar() ? '<div class="actions">' . $element->getHeaderBar() . '</div>' : '';
?>

<?php if ($isWrapped): ?>
    <div class="fieldset-wrapper" id="<?php echo $containerId ? $containerId : $id . '-wrapper';?>">
        <div class="fieldset-wrapper-title">
            <strong class="title"<?php echo ($isCollapsable) ? ' data-toggle="collapse" data-target="#' . $id . '-content"' : ''; ?>>
                <span><?php echo $element->getLegend() ?></span>
            </strong>
            <?php echo $titleActions; ?>
        </div>
        <div class="fieldset-wrapper-content<?php echo ($isCollapsable) ? ' collapse' : ''; ?>" id="<?php echo $id ?>-content">
<?php endif; ?>

<?php echo $this->getHtml() ?>

<?php if ($isWrapped): ?>
        </div>
    </div>
<?php endif; ?>

