<?
/**
 * Multishipping checkout billing information
 * 
 * @see Mage_Checkout_Block_Multishipping_Billing
 */
?>
<div class="page-head">
    <h3>Billing Information</h3>
</div>
<?=$this->getMessagesBlock()->getHtml()?>
<script src="<?=Mage::getBaseUrl(array('_type'=>'js'))?>varien/payment.js" type="text/javascript"></script>
<form action="<?=$this->getPostActionUrl()?>" method="post" id="multishipping-billing-form">
<div class="multi-address-checkout-box">
    <div class="box">
        <div class="content col2-set">
            <div class="col-1">
                <div class="head">
                    <h5>
                        Billing Address<span class="pipe">|</span><a href="<?=$this->getSelectAddressUrl()?>">Change</a>
                    </h5>
                 </div>
                <?$_address=$this->getAddress()?>
                <address>
                    <?=$_address->getFirstname()?> <?=$_address->getLastname()?><br/>
                    <?if($_address->getCompany()):?><?=$_address->getCompany()?><br/><?endif?>
                    <?=$_address->getStreet(1)?><br/>
                    <?if($_address->getStreet(2)):?><?=$_address->getStreet(2)?><br/><?endif?>
                    <?=$_address->getCity()?>, <?=$_address->getRegion()?> <?=$_address->getPostcode()?><br/>
                    <?=$_address->getCountry()?><br/>
                    <strong>T</strong> | <?=$_address->getTelephone()?>
                </address>
            </diV>
            <div class="col-2">
                <div class="head">
                    <h5>Payment Method</h5>
                </div>
                <dl class="payment-methods">
                    <?=$this->getPaymentMethods()?>
                    <!-- ERASE THIS DT AND DD - THIS IS CREATED FOR TESTING PURPOSE ONLY
                    <dt>&nbsp;</dt>
                    <dd style="position:relative; ">
                       <a href="#">what is this?</a>
                        <div class="tool-tip" style="top:-270px; left:0; ">
                            <a href="#" class="btn-close"><img src="<?=$this->getSkinUrl('images/btn_window_close.gif')?>" alt="Close"/></a>
                            <div class="block-content">
                            <img src="<?=$this->getSkinUrl('images/cvv.gif')?>" alt="Card Verification Number visual reference"/>
                            </div>
                        </div>
                    </dd>
                    ERASE THIS DT AND DD - THIS IS CREATED FOR TESTING PURPOSE ONLY -->
                </dl>
            </div>
        </div>
      </div>
</div>
<div class="form-buttons">
    <a href="<?=$this->getBackUrl()?>" class="left">&laquo; Back to Shipping Information</a>
    <button class="form-button" type="submit"><span>Continue to Place Order</span></button>
</div>
<script type="text/javascript">
    // Need to fix payment JS
    var payment = new paymentForm('multishipping-billing-form');
</script>