<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head">
    <h3><?=__('Review Order')?></h3>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<div class="multi-address-checkout-box">
<form action="<?=$this->getPostActionUrl()?>" method="post">
    <div class="box">
        <h4 class="legend"><?=__('Billing Information')?></h4>
        <div class="clear"></div>
        <div class="content col2-set">
            <div class="col-1">
                <?$_address=$this->getBillingAddress()?>
                <div class="head">
                    <h4><?=__('Billing Address')?><span class="separator">|</span><a href="<?=$this->getEditBillingAddressUrl($_address)?>"><?=__('Edit')?></a></h4>
                </div>
                <address>
                    <?=$_address->getFormated(true)?>
                </address>
            </div>
            <div class="col-2">
                <div class="head">
                    <h4><?=__('Payment Method')?><span class="separator">|</span><a href="<?=$this->getEditBillingUrl()?>"><?=__('Edit')?></a></h4>
                </div>
                <?=$this->getPaymentHtml()?>
            </div>
        </div>
     </div>

    <div class="box">
        <h4 class="legend"><?=__('Shipping Information')?></h4>
        <div class="clear"></div>
<?foreach ($this->getShippingAddresses() as $_index => $_address):?>
    <div class="content col2-alt-set"><h4><?=__('Address')?> <span class="shipment-count"><?=($_index+1)?></span> <?=__('of')?> <?=$this->getShippingAddressCount()?></h4>
        <div class="col-1">
            <div class="head">
                <h4><?=__('Shipping to')?><span class="separator">|</span><a href="<?=$this->getEditShippingAddressUrl($_address)?>"><?=__('Edit')?></a></h4>
            </div>
            <address>
                <?=$_address->getFormated(true)?>
            </address>
            <br/>
            <div class="head">
                <h4><?=__('Shipping Method')?><span class="separator">|</span><a href="<?=$this->getEditShippingUrl()?>"><?=__('Edit')?></a></h4>
            </div>
            <?if($_rate=$this->getShippingAddressRate($_address)):?>
            <p><?=$_rate->getCarrierTitle()?> (<?=$_rate->getMethodDescription()?>) - <?=$_rate->getPrice()?></p>
            <?endif;?>
        </div>
        <div class="col-2">
            <div class="head">
                <h4><?=__('Items')?><span class="separator">|</span><a href="<?=$this->getAddressesEditUrl()?>"><?=__('Edit')?></a></h4>
            </div>
            <table cellspacing="0" id="overview-table-<?=$_address->getId()?>" class="data-table nested-data-table">
                <col/>
                <col width="70"/>
                <col width="30"/>
                <col width="70"/>
                <thead>
                    <tr>
                        <th><?=__('Product Name')?></th>
                        <th class="a-right"><?=__('Price')?></th>
                        <th class="a-center"><?=__('Qty')?></th>
                        <th class="a-right"><?=__('Subtotal')?></th>
                    </tr>
                </thead>
                <tbody>
                <?foreach ($this->getShippingAddressItems($_address) as $_item):?>
                    <tr>
                        <td>
                            <?=$this->getHelper('checkout/item')->getItemName($_item)?>
                            <?=$this->getHelper('checkout/item')->getItemDescription($_item)?>
                        </td>
                        <td class="a-right"><?=$_item->getPrice()?></td>
                        <td class="a-center"><?=$_item->getQty()?></td>
                        <td class="a-right"><?=$_item->getRowTotal()?></td>
                    </tr>
                <?endforeach;?>
                </tbody>
                <tfoot>
                <?foreach ($this->getShippingAddressTotals($_address) as $_total):?>
                    <tr>
                        <td colspan="3" class="a-right"><?=$_total->getTitle()?></td>
                        <td class="a-right"><?=$_total->getValue()?></td>
                    </tr>
                <?endforeach;?>
                </tfoot>
            </table>
            <script type="text/javascript">decorateTable('overview-table-<?=$_address->getId()?>')</script>
        </div>
    </div>
    <?if($this->getShippingAddressCount()!=$_index+1):?>
    <div class="divider"></div>
    <?endif;?>
<?endforeach;?>
</div>
</div>
<table class="place-order-box" cellspacing="0">
    <tr>
        <td class="left-radius">&nbsp;</td>
        <td class="main-radius"><big class="grand-total"><span class="label"><?=__('Grand Total')?>:</span> <span class="price"><?=$this->getTotal()?></span></big>
            <input type="image" src="<?=$this->getSkinUrl('images/btn_place_order.gif')?>" value="<?=__('Place Order')?>"/></td>
    </tr>
</table>
<div class="clear"></div>
<div class="form-buttons">
    <a href="<?=$this->getBackUrl()?>" class="left"><?=__('&laquo; Back to Billing Information')?></a>
</div>
</form>
</div>
