<div class="content">
    <h1 class="page-heading">Change Account Password</h1>
    <form action="<?=$moduleBaseUrl?>/account/changepassword/" method="post" id="form-validate">
    <fieldset class="group-single">
        <legend>Change Account Password</legend>
        <ul class="input-list">
            <li><div class="input-left"><label for="password_current">Current Password <span class="required">*</span></label><br/><input type="password" class="required-entry input-text" name="password_current" id="password_current" onfocus="fieldset_highlight(this,true)" onblur="fieldset_highlight(this,false)"/></div><div class="clearfix"></div></li>
            <li><div class="input-left"><label for="password_new">New Password <span class="required">*</span></label><br/><input type="password" class="required-entry validate-password input-text" name="password_new" id="password_new" onfocus="fieldset_highlight(this,true)" onblur="fieldset_highlight(this,false)"/></div>
            <div class="input-right"><label for="password_confirmation">Confirm New Password <span class="required">*</span></label><br/><input type="password" class="required-entry validate-cpassword input-text" name="password_confirmation" id="password_confirmation" onfocus="fieldset_highlight(this,true)" onblur="fieldset_highlight(this,false)"/></div><div class="clearfix"></div></li>
        </ul>
    </fieldset>
    <div class="clearfix"></div>
    <div class="buttons-container">
        <p class="required">* Required Fields</p>
        <input type="button" onclick="window.location='<?=$moduleBaseUrl?>/account/';" value="Back" class="input-button float-left"/>
        <input type="submit" class="input-button float-right" value="Continue"/>
        <div class="clearfix"></div>
    </div>
    </form>
    <script type="text/javascript">
        new Validation('form-validate');
    </script>
</div>