<div class="content">
    <h1 class="page-heading">Password Forgotteen</h1>
    <form action="<?=$moduleBaseUrl?>/account/forgotpassword/" method="post" id="form-validate">
    <fieldset class="group-single">
        <legend>Retrieve your password here</legend>
        <p>Please enter your email below and we'll send you a new password.</p>
        <ul class="input-list">
            <li>
                <div class="input-left"><label for="email_address">Email Address <span class="required">*</span></label><br/>
                <input name="email_address" alt="email"  type="text" id="email_address" class="required-entry input-text"></div>
                <div class="clearfix"></div></li>
        </ul>
        <div class="buttons-container">
            <p class="required">* Required Fields</p>
            <input type="button" onclick="window.location='<?=$moduleBaseUrl?>/account/';" value="Back" class="input-button float-left"/>
            <input type="submit" class="input-button float-right" value="Continue"/>
            <div class="clearfix"></div>
        </div>
    </fieldset>
    </form>
</div>