<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if($this->getItems()->getSize()): ?>
<div class="block related">
    <div class="block title"><strong class="title"><?php echo $this->__('Related Products') ?></strong></div>
    <div class="content">
        <div class="actions">
            <p class="text">
                <?php echo $this->__('Check items to add to the cart or') ?>
                <button type="button" class="action select" role="select-all"><span><?php echo $this->__('select all') ?></span></button>
            </p>
        </div>
        <ol class="items products">
            <?php $i=0; foreach($this->getItems() as $_item): ?>
            <li class="item">
                <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                    <?php endif; ?>
                <?php endif; ?>
                <div class="item-info">
                    <a href="<?php echo $_item->getProductUrl() ?>" class="product-image"><img src="<?php echo $this->getSmallImageSidebarUrl($_item) ?>" width="<?php echo $this->getSmallImageSidebarSize()?>" height="1<?php echo $this->getSmallImageSidebarSize()?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
                    <div class="product-details">
                        <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        <?php if ($this->helper('Mage_Wishlist_Helper_Data')->isAllow()) : ?>
                            <p><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></p>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ol>
    </div>
</div>
<script>
    head.js("<?php echo $this->getViewFileUrl('Mage_Catalog::js/related-products.js'); ?>", function() {
        jQuery(".block.related [role='select-all']").relatedProducts();
    });
</script>
<?php endif ?>
