<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/** @var $this Saas_ImportExport_Block_Adminhtml_Import_Edit_Image */
?>
<?php
/** It is hot fix. Now we have not strong solutions because of problems with quality of code in Mage_ImportExport. */
?>
<script type="text/javascript">
//<![CDATA[
    (function($) {
        $(function() {
            var Saas_ImportExport_Image = {
                /**
                 * @type {string}
                 */
                typeCode: '<?php echo $this->getTypeCode() ?>',

                /**
                 * @type {Object}
                 */
                uniqueBehaviors: <?php echo $this->getUniqueBehaviorsAsJson() ?>,

                /**
                 * @type {Element}
                 */
                button: $('#upload_button'),

                /**
                 * @type {string}
                 */
                defaultButtonTitle: '',

                /**
                 * @type {string}
                 */
                imageButtonTitle: '<?php echo $this->jsQuoteEscape($this->__('Upload Image Archive')) ?>',

                /**
                 * @type {Element}
                 */
                form: $('#edit_form'),

                /**
                 * @type {string}
                 */
                defaultFormAction: '',

                /**
                 * @type {string}
                 */
                imageFormAction: '<?php echo $this->getFormAction()?>',

                /**
                 * @type {Element}
                 */
                defaultFileField: $('.field-import_file'),

                /**
                 * @type {Element}
                 */
                imageFileField: $('.field-import_file_image'),

                /**
                 * Init
                 */
                init: function() {
                    this.defaultButtonTitle = this.button.attr('title');
                    this.defaultFormAction = this.form.attr('action');
                    this.imageFileField.hide();

                    var self = this;
                    $('#entity').bind('change', function() {
                        if (self.typeCode == $(this).val()) {
                            // Hide import behaviors blocks
                            for (i = 0; i < self.uniqueBehaviors.length; i++) {
                                $('#' + self.uniqueBehaviors[i] + '_fieldset').hide();
                                $('#' + self.uniqueBehaviors[i]).attr('disabled', 'disabled')
                                    .removeClass('required-entry');
                            }
                            // Update submit button
                            self.button.attr('title', self.imageButtonTitle).text(self.imageButtonTitle);
                            // Update form 'action'
                            self.form.attr('action', self.imageFormAction);
                            // Toggle file field
                            self.defaultFileField.hide().find('input').removeClass('required-entry');
                            self.imageFileField.show().find('input').addClass('required-entry');
                        } else {
                            // Rollback
                            self.button.attr('title', self.defaultButtonTitle).text(self.defaultButtonTitle);
                            self.form.attr('action', self.defaultFormAction);
                            self.imageFileField.hide().find('input').removeClass('required-entry');
                            self.defaultFileField.show().find('input').addClass('required-entry');
                        }
                    });
                }
            };
            Saas_ImportExport_Image.init();
        });
    })(jQuery);
//]]>
</script>
