<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Template for displaying product price at rss feeds pages
 *
 * @var $this Mage_Catalog_Block_Product_Price
 */

/** @var $_product Mage_Catalog_Model_Product */
$_product = $this->getProduct();
?>
<div class="price-box map-info">

    <?php if ($this->helper('Mage_Catalog_Helper_Data')->canApplyMsrp($_product)): ?>
        <a href="<?php echo $_product->getProductUrl() ?>"><?php echo __('Click for price'); ?></a>
    <?php endif; ?>
</div>
