<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ], function($){
        'use strict';
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            fileElement: 'Magento_CustomerCustomAttributes/file-element',
            validation: 'mage/validation/dob-rule'
        });
    });
</script>
<?php echo $this->getChildHtml() ?>
