<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_Theme
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Theme_Block_Adminhtml_System_Design_Theme_Edit_Tab_Js */ ?>
<?php echo $this->getFormHtml(); ?>

<script type="text/javascript">
    (function ($) {

        $('#js_files_uploader').fileupload({
            dataType: 'json',
            replaceFileInput: false,
            //sequentialUploads: true,
            url : '<?php echo $this->getJsUploadUrl(); ?>',
            acceptFileTypes: /(.|\/)(js)$/i,

            /**
             * Add data
             * @param e
             * @param data
             */
            add: function (e, data) {
                var uploadButton = $('#js_uploader_button');
                uploadButton.removeAttr('disabled');

                uploadButton.click(function () {
                    $('#messages').html('');
                    $(this).attr('disabled', 'disabled');

                    data.submit();
                });
            },

            /**
             * On done event
             * @param e
             * @param data
             */
            done: function (e, data) {
                var contentArea = $('.js-files-container');
                $(this).val('');

                if (!data.result.error) {
                    contentArea.html(data.result.content);
                }

                $('.ui-sortable').sortable('initButtons');
            },

            /**
             * Fail event
             * @param e
             * @param data
             */
            fail: function(e, data) {
                $(this).val('');
                alert($.mage.__('File extension not known or unsupported type.'));
            }
        });

        $('#js_files_uploader').click(function () {
            /** Unbind click event on file change */
            $('#js_uploader_button').unbind('click');
        });

    })(jQuery);
</script>
