<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Storelauncher_Design_Tile */
?>

<article class="tile-store-settings tile-design <?php echo $this->getTileStateStyle(); ?>"
         id="tile-<?php echo $this->getTileCode()?>"
         tabindex="0">
    <h2><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Store Design') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Choose how you want your store to look.') ?>
        </p>
        <div class="actions">
            <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                    data-save-url="<?php echo $this->getUrl('*/storelauncher_design_drawer/save') ?>"
                    data-load-url="<?php echo $this->getUrl('*/storelauncher_design_drawer/load') ?>">
                <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Open Store Design') ?></span>
            </button>
        </div>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Saas_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <ul class="checklist">
        <?php $themeName = $this->getThemeName(); ?>
        <?php if (!empty($themeName)) :?>
            <li class="completed">
                "<?php echo $this->escapeHtml($themeName); ?>" <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('theme is applied') ?>
            </li>
        <?php endif; ?>
        <?php if ($this->isLogoUploaded()) :?>
            <li class="completed">
                <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Logo is uploaded') ?>
            </li>
        <?php endif; ?>
        </ul>
        <div class="actions">
            <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                    data-save-url="<?php echo $this->getUrl('*/storelauncher_design_drawer/save') ?>"
                    data-load-url="<?php echo $this->getUrl('*/storelauncher_design_drawer/load') ?>">
                <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Edit Design') ?></span>
            </button>
        </div>
        <footer class="tile-more-info">
            <p class="tile-more-info-label"><?php echo $this->escapeHtml($this->__('Customize your store even more:')); ?></p>
            <p class="tile-more-info-breadcrumbs">
                <span><?php echo $this->escapeHtml($this->__('Content')); ?></span>
                <span><?php echo $this->escapeHtml($this->__('Design')); ?></span>
                <a href="<?php echo $this->getUrl('adminhtml/system_design_editor/index') ?>"><?php echo $this->__('The Designer'); ?></a>.
            </p>
        </footer>
        <?php endif; ?>
    </div>
</article>
<script type="text/javascript">
jQuery(function ($) {
    head.js(
        "<?php echo $this->getViewFileUrl('jquery/jquery.ba-hashchange.min.js') ?>",
        "<?php echo $this->getViewFileUrl('Saas_Launcher::page/launcher.js') ?>",
        function () {
            $('#drawer').drawer();
            $('#drawer').drawer('setDependencies',
                '<?php echo $this->getTileCode() ?>',
                [
                    "<?php echo $this->getViewFileUrl('jquery/fileUploader/jquery.iframe-transport.js') ?>",
                    "<?php echo $this->getViewFileUrl('jquery/fileUploader/jquery.fileupload.js') ?>",
                    "<?php echo $this->getViewFileUrl('jquery/fileUploader/load-image.min.js') ?>",
                    "<?php echo $this->getViewFileUrl('jquery/fileUploader/canvas-to-blob.min.js') ?>",
                    "<?php echo $this->getViewFileUrl('jquery/fileUploader/jquery.fileupload-fp.js') ?>"
                ]
            );
        }
    );
});
</script>
