<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Document content
 *
 * @var $this \Magento\Doc\Ui\Element\Document
 */
/** @var $this \Magento\Doc\Ui\Widget\Document */
?>
<div class="document" id="document">
    <?php echo $this->renderDocumentHtml() ?>
    <div data-role="dictionary"><?php echo $this->getDictionaryJson() ?></div>
</div>
<script src="<?php echo $this->getViewFileUrl('Magento_Doc::js/mage.doc.js') ?>"></script>
