<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Document content
 *
 * @var $this \Magento\Doc\Ui\Element\Document
 */
?>
<style>
    .document .label {
        text-align: left;
        font-weight: bold;
        color: #df3B02;
        line-height: 4em;
    }

    .document *[data-role="doc-item-content"],
    .document *[data-role="doc-item-content-src"] {
        border: 1px solid #eeeeee;
    }

    .document *[data-role="doc-item-content-src"] {
        display: none;
        line-height: 1.45em;
    }

    .document *[data-role="doc-item-content-src"] br {
        margin-bottom: 3px;
    }

    .document [data-role="doc-item"] h1 ~ [data-role="doc-item"] {
        font-size: .9em;
    }

    .document div[data-role="doc-item"] {
        padding: 0 20px;
        position: relative;
    }

    .document div[data-role="doc-item"].required:after {
        content: "Element is required!";
    }

    .document [data-type="article"] {
        text-align: left;

    }

    .document div[data-role="doc-item"].denoted {
        background-color: #f7eed0;
    }

    .document div[contenteditable="true"].denoted {
        background-color: #ece3c7;
    }

    .document .outdated {
        text-decoration: line-through;
    }

    .modified:before {
        content: 'Modified';
        color: #ff0000;
        position: absolute;
        top: 20px;
        left: -70px;
    }
    .hasChanges:after {
        background-color: red;
    }
    .hasActivated:after {
        background-color: orange;
    }
</style>
<div class="document" id="document">
    <div id="toolbar">
        <header>
            <ul class="commands">
                <li data-wysihtml5-command="bold" title="Make text bold (CTRL + B)" class="command"></li>
                <li data-wysihtml5-command="italic" title="Make text italic (CTRL + I)" class="command"></li>
                <li data-wysihtml5-command="insertUnorderedList" title="Insert an unordered list" class="command"></li>
                <li data-wysihtml5-command="insertOrderedList" title="Insert an ordered list" class="command"></li>
                <li data-wysihtml5-command="createLink" title="Insert a link" class="command"></li>
                <li data-wysihtml5-command="insertImage" title="Insert an image" class="command"></li>
                <li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1" title="Insert headline 1" class="command"></li>
                <li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2" title="Insert headline 2" class="command"></li>
                <li data-wysihtml5-command-group="foreColor" class="fore-color command" title="Color the selected text">
                    <ul>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="silver"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="gray"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="maroon"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="red"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="purple"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="green"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="olive"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="navy"></li>
                        <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="blue"></li>
                    </ul>
                </li>
                <li data-wysihtml5-command="insertSpeech" title="Insert speech" class="command"></li>
                <li data-wysihtml5-action="change_view" title="Show HTML" class="action"></li>
                <li data-wysihtml5-command="save" id="toolbar-save"  title="Save" class="action"></li>
            </ul>
        </header>
        <div data-wysihtml5-dialog="createLink" style="display: none;">
            <label>
                Link:
                <input data-wysihtml5-dialog-field="href" value="http://">
            </label>
            <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
        </div>

        <div data-wysihtml5-dialog="insertImage" style="display: none;">
            <label>
                Image:
                <input data-wysihtml5-dialog-field="src" value="http://">
            </label>
            <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
        </div>
    </div>
    <?php echo $this->renderDocumentHtml() ?>
</div>
<script>
    var items = [];
    var requiredHtml = 'Element %s is required!';
    var saveElement = function (item) {
        var view = jQuery(item.find('*[data-role="doc-item-content"]')[0]);
        var source = jQuery(item.find('*[data-role="doc-item-content-src"]')[0]);
        var content = source.val(),
            type = source.attr('content-type'),
            module = source.attr('module'),
            scheme = source.attr('scheme'),
            name = source.attr('doc-name');
        jQuery.ajax({
            url: '/doc/index',
            method: 'POST',
            data: {
                action: 'save',
                content: content,
                type: type,
                module: module,
                scheme: scheme,
                name: name
            },
            success: function (response) {
                view.html(response);
                view.show();
                jQuery('#toolbar-save').removeClass('hasChanges').removeClass('hasActivated');
                if (item.editor) {
                    item.editor.currentView.hide();
                } else {
                    view.html(content);
                    jQuery(source).hide();
                    JUMLY.scan(view, {});
                }
                ensureIsNotEmpty(view);
            }
        });
    };
    var ensureIsNotEmpty = function(jEl) {
        var content = jEl.html().trim();
        if (!content && !jEl.attr('optional')) {
            jEl.html(requiredHtml.replace(/%s/g, jEl.attr('data-type')));
        }
    };
    var init = {
        article: function(item) {
            var srcContent = jQuery(item.find('*[data-role="doc-item-content-src"]')[0]);
            srcContent.data('orig', srcContent.val());
            item.on('click', function (event) {
                initToolbar(item);
                event.stopPropagation();
            });
            items.push(item);
        },
        diagram: function(item) {
            var content = jQuery(item.find('*[data-role="doc-item-content"]')[0]);
            var script = jQuery(item.find('script[type="text/jumly+sequence"]')[0]);
            var srcContent = jQuery(item.find('*[data-role="doc-item-content-src"]')[0]);
            srcContent.data('orig', srcContent.val());
            item.on('click', function (event) {
                content.hide();
                srcContent.show();
                srcContent.css('min-height', content.height() + 100);
                srcContent[0].addEventListener("keyup", function() {
                    if (srcContent.data('orig')) {
                        if (srcContent.data('orig') !== srcContent.val()) {
                            jQuery('#toolbar-save').addClass('hasChanges');
                        } else {
                            jQuery('#toolbar-save').removeClass('hasChanges');
                        }
                    }
                });
                event.stopPropagation();
            });
            items.push(item);
        }
    };
    jQuery.each(jQuery.find('div[data-role="doc-item"]'), function (id, el) {
        var item = jQuery(el);
        var dataType = item.attr('data-type');
        if (init[dataType]) {
            init[dataType](item);
        }
    });
    function initToolbar(element) {
        var content = jQuery(element.find('*[data-role="doc-item-content"]')[0]);
        var srcContent = jQuery(element.find('*[data-role="doc-item-content-src"]')[0]);

        content.hide();
        srcContent.show();
        srcContent.css('min-height', content.height() + 100);

        if (!element.editor) {
            var editor = new wysihtml5.Editor(srcContent[0], {
                toolbar:      "toolbar",
                stylesheets: ["<?php echo $this->getViewFileUrl('Magento_Doc::wysihtml/css/editor.css') ?>"],
                parserRules:  wysihtml5ParserRules
            });
            element.editor = editor;
            editor.observe("change", function() {
                if (srcContent.data('orig')) {
                    if (srcContent.data('orig') !== srcContent.val()) {
                        jQuery('#toolbar-save').addClass('hasChanges');
                    } else {
                        jQuery('#toolbar-save').removeClass('hasChanges');
                    }
                }
            });
            editor.focus();
        } else {
            srcContent.hide();
            element.editor.currentView.show();
            element.editor.focus();
        }
    }
    document.getElementById('toolbar-save').addEventListener('click', function (event) {
        jQuery.each(items, function (id, item) {
            saveElement(item);
        });
    });
    jQuery.each(jQuery.find('*[data-role="doc-item-content"]'), function (id, el) {
        var jEl = jQuery(el);
        ensureIsNotEmpty(jEl);
    });
</script>
