<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Document toolbar
 *
 * @var $this \Magento\Doc\Ui\Widget\Toolbar
 */
?>
<div id="toolbar" >
    <ul class="commands">
        <li data-wysihtml5-command="save" id="toolbar-save"  title="Save" class="command"></li>
        <li data-wysihtml5-command="speech" id="toolbar-speech"  title="Speech" class="command"></li>
        <li data-wysihtml5-command="bold" title="Make text bold (CTRL + B)" class="command"></li>
        <li data-wysihtml5-command="italic" title="Make text italic (CTRL + I)" class="command"></li>
        <li data-wysihtml5-command="insertUnorderedList" title="Insert an unordered list" class="command"></li>
        <li data-wysihtml5-command="insertOrderedList" title="Insert an ordered list" class="command"></li>
        <li data-wysihtml5-command="createLink" title="Insert a link" class="command"></li>
        <li data-wysihtml5-command="insertImage" title="Insert an image" class="command"></li>
        <li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1" title="Insert headline 1" class="command"></li>
        <li data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2" title="Insert headline 2" class="command"></li>
        <li data-wysihtml5-command-group="foreColor" class="fore-color command" title="Color the selected text">
            <ul>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="silver"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="gray"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="maroon"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="red"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="purple"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="green"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="olive"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="navy"></li>
                <li data-wysihtml5-command="foreColor" data-wysihtml5-command-value="blue"></li>
            </ul>
        </li>
        <li data-wysihtml5-action="change_view" title="Show HTML" class="action"></li>
    </ul>
    <div data-wysihtml5-dialog="createLink" style="display: none;">
        <label>
            Link:
            <input data-wysihtml5-dialog-field="href" value="http://">
        </label>
        <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
    <div data-wysihtml5-dialog="insertImage" style="display: none;">
        <label>
            Image:
            <input data-wysihtml5-dialog-field="src" value="http://">
        </label>
        <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
    <textarea id="speech-buffer" data-wysihtml5-dialog="speech" style="display: none;"></textarea>
</div>
<script>
    var actions = {
        approve: function(element) {
            if (selected) {
                selected.removeClass('denoted');
            }
        },
        denote: function(element) {
            if (selected) {
                selected.addClass('denoted');
            }
        },
        save: function(element) {
            var content = jQuery('#document').html();
            jQuery.ajax({
                url: '/doc/wiki',
                method: 'POST',
                data: {
                    action: 'save',
                    content: content
                },
                success: function() {}
            });
        },
        toggle: function(element) {
            jQuery.each(jQuery.find('div[outdated="true"]'), function(id, el){
                jQuery(el).toggle();
            });
        }
    };
    function executeAction(event) {
        var button = event.srcElement || event.target;
        var action = button.getAttribute('action');
        if (actions[action]) {
            actions[action](button);
        }
    }
    jQuery('.toolbar button').each(function(id, button) {
        button.addEventListener('click', executeAction);
    });
</script>
