<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Document toolbar
 *
 * @var $this \Magento\Doc\Ui\Element\Toolbar
 */
?>
<style>
    .toolbar {
        position: fixed; top: 50px; left: 0; z-index: 100;
        padding: 5px;
        width: 100%;
        text-align: center;
        background-color: #ffffff;
    }
    .buttons {
        list-style: none;
        background-color: #ffffff;
    }
    .buttons > li {
        display: inline;
    }
    .buttons > li > button {
        width: 150px;
    }
</style>
<div class="toolbar">
    <ul class="buttons">
        <?php foreach ($this->getItems() as $item): ?>
            <?php echo $this->renderItemHtml($item) ?>
        <?php endforeach; ?>
    </ul>
</div>
<script>
    var actions = {
        approve: function(element) {
            if (selected) {
                selected.removeClass('denoted');
            }
        },
        denote: function(element) {
            if (selected) {
                selected.addClass('denoted');
            }
        },
        save: function(element) {
            var content = jQuery('#document').html();
            jQuery.ajax({
                url: '/doc/wiki',
                method: 'POST',
                data: {
                    action: 'save',
                    content: content
                },
                success: function() {}
            });
        },
        toggle: function(element) {
            jQuery.each(jQuery.find('div[outdated="true"]'), function(id, el){
                jQuery(el).toggle();
            });
        }
    };
    function executeAction(event) {
        var button = event.srcElement || event.target;
        var action = button.getAttribute('action');
        if (actions[action]) {
            actions[action](button);
        }
    }
    jQuery('.toolbar button').each(function(id, button) {
        button.addEventListener('click', executeAction);
    });
</script>
