<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Catalog_Block_Product_Image */ ?>

<img class="photo image" style="width:<?php echo $this->getProductImageView()->getWidth()?>px;
     height:<?php echo $this->getProductImageView()->getHeight()?>px;"
     src="<?php echo $this->getProductImageView()->getUrl() ?>"
     alt="<?php echo $this->stripTags($this->getProductImageView()->getLabel(), null, true) ?>"/>
