<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php echo $this->getCaptchaHtml() ?>

<?php echo $this->getStoreSwitcherHtml() ?>
<div class="grid-title">
    <span class="title"><?php echo __('Google Content Items') ?></span>
</div>
<?php echo $this->getChildHtml('item') ?>

<div class="grid-title">
    <div class="page-actions"><?php echo $this->getAddButtonHtml() ?></div>
    <span class="title"><?php echo __('Available Products') ?></span>
</div>
<?php echo $this->getChildHtml('product') ?>

<script type="text/javascript">
//<![CDATA[
Mage.GoogleShopping.isProcessRunning = <?php echo $this->isProcessRunning() ? 'true' : 'false'; ?>;
Mage.GoogleShopping.statusUrl = '<?php echo $this->getStatusUrl(); ?>';
Mage.GoogleShopping.runningMessage = '<?php echo __('Google Shopping synchronization process is running');?>';
//]]>
</script>
