<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Captcha
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $captcha = $this->getCaptchaModel() ?>
<?php /* @var $this Mage_Core_Block_Captcha_Zend */ ?>
<div class="input-box" style="padding:8px 0 0; overflow:hidden; width:467px;">
    <label for="captcha"><?php echo $this->__('Please type the letters from the image:') ?></label><br />
    <div class="captcha-input" style="float:left;">
        <input type="text" name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" id="captcha" style="margin-right:5px; width:226px;" class="required-entry input-text validation-failed"/>
    </div>
    <div class="captcha-image" style="padding:0; float:left; border: 1px solid #ccc; position: relative;">
        <img id="<?php echo $this->getFormId() ?>" width="<?php echo $this->getImgWidth() ?>" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>" />
        <script type="text/javascript">
        //<![CDATA[
        var captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');
        //]]>
        </script>
        <img class="captcha-reload"
            src="<?php echo $this->getSkinUrl('Mage_Captcha::reload.png') ?>"
            alt="<?php echo $this->__('Reload captcha') ?>"
            onclick="captcha.refresh()"
            style="position: absolute; top: 2px; right: 2px;">
    </div>
</div>
<?php if ($captcha->isCaseSensitive()) :?>
<div class="captcha-note">
    <p><?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?></p>
</div>
<?php endif; ?>

<div class="clear"></div>
