<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Downloadable\Block\Sales\Order\Item\Renderer\Downloadable */
?>
<?php $_item = $this->getItem() ?>
<tr id="order-item-row-<?php echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $this->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $this->escapeHtml($_item->getName()) ?></strong>
        <?php if($_options = $this->getItemOptions()): ?>
            <dl class="item-options links">
                <?php foreach ($_options as $_option) : ?>
                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$this->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                        <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                            <?php echo $_formatedOptionValue['value'] ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd>
                            <?php echo nl2br($this->escapeHtml( (isset($_option['print_value']) ? $_option['print_value'] : $_option['value']) )) ?>
                        </dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php /* downloadable */ ?>
        <?php if ($links = $this->getLinks()): ?>
            <dl class="item-options links">
                <dt><?php echo $this->getLinksTitle() ?></dt>
                <?php foreach ($links->getPurchasedItems() as $link): ?>
                    <dd><?php echo $this->escapeHtml($link->getLinkTitle()); ?></dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php /* EOF downloadable */ ?>
        <?php $addtInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $this->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $this->escapeHtml(__('SKU')); ?>"><?php echo $this->prepareSku($this->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $this->escapeHtml(__('Price')); ?>">
        <?php echo $this->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?php echo $this->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
            <?php if ($this->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="title"><?php echo __('Ordered'); ?></span>
                    <span class="content"><?php echo $this->getItem()->getQtyOrdered()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($this->getItem()->getQtyShipped() > 0): ?>
                <li class="item">
                    <span class="title"><?php echo __('Shipped'); ?></span>
                    <span class="content"><?php echo $this->getItem()->getQtyShipped() * 1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($this->getItem()->getQtyCanceled() > 0): ?>
                <li class="item">
                    <span class="title"><?php echo __('Canceled'); ?></span>
                    <span class="content"><?php echo $this->getItem()->getQtyCanceled()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($this->getItem()->getQtyRefunded() > 0): ?>
                <li class="item">
                    <span class="title"><?php echo __('Refunded'); ?></span>
                    <span class="content"><?php echo $this->getItem()->getQtyRefunded()*1 ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?php echo $this->escapeHtml(__('Subtotal')); ?>">
        <?php echo $this->getItemRowTotalHtml(); ?>
    </td>
</tr>

<?php if ($this->helper('Magento\GiftMessage\Helper\Message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
<tr>
    <td class="col options" colspan="5">
        <a href="#"
           id="order-item-gift-message-link-<?php echo $_item->getId() ?>"
           class="action show"
           aria-controls="order-item-gift-message-<?php echo $_item->getId()?>"
           data-item-id="<?php echo $_item->getId()?>"><?php echo __('Gift Message') ?></a>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_item); ?>
        <div class="order-gift-message" id="order-item-gift-message-<?php echo $_item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
            <a href="#"
               title="<?php echo __('Close') ?>"
               aria-controls="order-item-gift-message-<?php echo $_item->getId()?>"
               data-item-id="<?php echo $_item->getId()?>"
               class="action close">
                <?php echo __('Close') ?>
            </a>
            <dl class="item-options">
                <dt class="item-sender"><strong class="label"><?php echo __('From') ?></strong><?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dt>
                <dt class="item-recipient"><strong class="label"><?php echo __('To') ?></strong><?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                <dd class="item-message"><?php echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($_item) ?></dd>
            </dl>
        </div>
    </td>
</tr>
<?php endif; ?>
