<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <?php if ($this->getMethod()->getPayableTo()): ?>
                <?php echo __('<label>Make Check payable to:</label> %1', $this->escapeHtml($this->getMethod()->getPayableTo())) ?><br />
            <?php endif; ?>
            <?php if ($this->getMethod()->getMailingAddress()): ?>
                <label><?php echo __('Send Check to:') ?></label>
                <div class="checkmo-mailing-address">
                    <?php echo nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
                </div>
            <?php endif; ?>
        </div>
    </li>
</ul>
