<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <?php echo $this->getBackButtonHtml(); ?>
    <?php echo $this->getResetButtonHtml(); ?>
    <?php echo $this->getDeleteButtonHtml(); ?>
    <?php echo $this->getSaveButtonHtml(); ?>
</div>
<?php if( $form ): ?>
<?php echo $form->toHtml();?>

<script type="text/javascript">
    jQuery('#<?php echo $form->getForm()->getId() ?>').mage('form').mage('validation');

    (function ($) {
        $(document).ready(function () {
            'use strict';

            $('.field-zip_from').addClass('ignore-validate');
            $('.field-zip_to').addClass('ignore-validate');

            $('#zip_is_range').on('change.zipRange', function(){

                var elem = $(this),
                    zipFrom =$('.field-zip_from'),
                    zipTo =$('.field-zip_to'),
                    zipCode =$('.field-tax_postcode');

                if (elem.is(':checked')) {
                    zipCode.addClass('hidden').addClass('ignore-validate');
                    zipFrom.removeClass('hidden').removeClass('ignore-validate');
                    zipTo.removeClass('hidden').removeClass('ignore-validate');

                } else {
                    zipCode.removeClass('hidden').removeClass('ignore-validate');
                    zipFrom.addClass('hidden').addClass('ignore-validate');
                    zipTo.addClass('hidden').addClass('ignore-validate');
                }

            });
        });
    })(jQuery);
</script>
<?php endif; ?>
