<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Tools_Code_Custom */ ?>
<div id="vde-tab-custom-messages-placeholder">
    <?php echo $this->getChildHtml('messages') ?>
</div>
<div class="custom-code-description">
    <h5 class="title"><?php echo $this->__('Custom CSS'); ?></h5>
    <p><?php echo $this->__('Update the custom.css file to right in order to overwrite the default styles.'); ?></p>
    <p><?php echo $this->__('Or, replace, delete or download the file:'); ?></p>
    <div class="custom-file">
        <span class="filename"><?php echo $this->getCustomFileName() ?></span>

        <button onclick="document.location='<?php echo $this->getDownloadCustomCssUrl($this->getTheme()) ?>'" class="action-download" title="<?php echo $this->__('Download file'); ?>">
            <span><?php echo $this->__('Download file'); ?></span>
        </button>
        <span class="action-add" title="<?php echo $this->__('Upload File'); ?>">
            <span><?php echo $this->__('Upload File'); ?></span>
            <?php echo $this->getFormHtml() ?>
        </span>
    </div>
</div>
<div class="custom-code">
    <div class="textarea-container">
        <textarea name="custom_code" id="custom_code" cols="30" rows="10"><?php echo $this->getCustomCssContent($this->getTheme()) ?></textarea>
    </div>
    <button class="action-update" title="<?php echo $this->__('Update'); ?>"><?php echo $this->__('Update'); ?></button>
</div>


<script type="text/javascript">
    (function ($) {
        $('#vde-tab-custom').customCssPanel({
            saveCustomCssUrl: '<?php echo $this->getSaveCustomCssUrl($this->getTheme()) ?>'
        });

        $( '#' + '<?php echo $this->getFileElementName() ?>' ).fileupload({
            dataType: 'json',
            replaceFileInput: false,
            url : '<?php echo $this->getUrl('*/system_design_editor_tools/upload', array('theme' => $this->getTheme()->getThemeId())) ?>',

            /**
             * Handler of "file selected" event
             * @param e
             * @param data
             */
            add: function (e, data) {
                data.submit();
            },

            /**
             * Handler on "upload ajax request done" event
             * @param e
             * @param data
             */
            done: function (e, data) {
                var contentArea = $('#custom_code');
                contentArea.val('');
                $('#css_uploader_button').attr('disabled', 'disabled');
                if (!data.result.error) {
                    contentArea.val(data.result.content);
                    $('#vde-tab-custom').customCssPanel('updateButtons');
                    $('#vde-tab-custom').trigger('refreshIframe');
                }

                if (data.result.message_html) {
                    $('#vde-tab-custom-messages-placeholder').append(data.result.message_html);
                }
            }
        });
    })(jQuery);
</script>
