<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Tools_Code_ImageSizing */ ?>
<div class="vde-tools-image-settings">
    <div id="vde-tab-imagesizing-messages-placeholder"></div>
</div>
<div class="form-inline vde-image-sizing">
<?php echo $this->getFormHtml(); ?>
</div>
<script type="text/javascript">
    (function ($) {
        $('#product_image_sizing_form').vdeImageSizing({
            formId: '#product_image_sizing_form',
            imageRatioClass: '.image-ratio',
            imageWidthClass: '.image-width',
            imageHeightClass: '.image-height',
            formUrl: '<?php echo $this->getUrl('*/system_design_editor_tools/saveImageSizing', array('id' => $this->getTheme()->getId())) ?>',
            maxSizeValue: <?php echo Mage_DesignEditor_Model_Editor_Tools_ImageSizing_Validator::MAX_SIZE_VALUE ?>,
            messagesContainer: '#vde-tab-imagesizing-messages-placeholder'
        });
        $(document).ready(function() {
            var eventData = {
                elements: {
                    focus: ['#product_image_sizing_form input[id!="add_white_borders"]'],
                    click: [
                        '#product_image_sizing_form .action-connect',
                        '#add_white_borders'                    //works in Chrome and FF
                    ],
                    mousedown: ['#product_image_sizing_form button', '#product_image_sizing_form select']
                }
            };
            $('body').trigger('registerElements', eventData);
        });
    })(jQuery);
</script>
