<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Language switcher template
 */
?>

<?php if(count($this->getStores())>1): ?>
<div class="switcher language" data-ui-id="language-switcher">
    <strong class="label"><span><?php echo __('Language') ?></span></strong>
    <div class="actions dropdown options">
        <div class="action toggle" id="language-switcher">
            <strong class="view-<?php echo $this->escapeHtml($this->getCurrentStoreCode()) ?>">
                <span><?php echo $this->escapeHtml($this->getStoreName()) ?></span>
            </strong>
        </div>
        <ul class="dropdown"
            data-mage-init='{"dropdownDialog":{"appendTo":".switcher.language > .options", "triggerTarget":"#language-switcher", "closeOnMouseLeave": false, "triggerClass":"active", "parentClass":"active", "buttons":null}}'>
            <?php foreach ($this->getStores() as $_lang): ?>
                <?php if($_lang->getId()!=$this->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $this->escapeHtml($_lang->getCode()); ?>">
                        <a href="#" data-post='<?php echo $this->getTargetStorePostData($_lang); ?>'>
                            <?php echo $this->escapeHtml($_lang->getName()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
