<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="grid">
    <table cellspacing="0" class="data">
        <thead>
            <tr class="headings">
                <th class="col-product"><span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Product') ?></span></th>
                <th class="col-qty last"><span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Qty Shipped') ?></span></th>
            </tr>
        </thead>
        <tbody>
        <?php $_items = $this->getShipment()->getAllItems() ?>
        <?php $_i=0;foreach ($_items as $_item): if ($_item->getOrderItem()->getIsVirtual() || $_item->getOrderItem()->getParentItem()): continue; endif; $_i++ ?>
            <?php echo $this->getItemHtml($_item) ?>
            <?php echo $this->getItemExtraInfoHtml($_item->getOrderItem()) ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
