<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Store switcher template
 *
 * @see \Magento\Core\Block\Store\Switcher
 */
?>
<?php if(count($this->getGroups())>1): ?>
<div class="switcher-store">
    <label><?php echo __('Select Store') ?>:</label>
    <ul id="select-store">
    <?php foreach ($this->getGroups() as $_group): ?>
        <?php if ($_group->getId()==$this->getCurrentGroupId()): ?>
        <li class="current"><strong><?php echo $this->escapeHtml($_group->getName()) ?></strong></li>
        <?php else: ?>
        <li><a href="<?php echo $_group->getHomeUrl() ?>"><?php echo $this->escapeHtml($_group->getName()) ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
