<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Manage Tax Rates') ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getChildHtml('addButton') ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getChildhtml('grid') ?>