<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?php echo $header ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml(); ?>
                <?php echo $this->getResetButtonHtml(); ?>
                <?php echo $this->getDeleteButtonHtml(); ?>
                <?php echo $this->getSaveButtonHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<?php if( $form ): ?>
<?php echo $form->toHtml(); ?>
<script type="text/javascript">
    //var wigetForm = new varienForm('<?php echo $form->getForm()->getId() ?>');
    jQuery('<?php echo $form->getForm()->getId() ?>').form().validation();
</script>
<?php endif; ?>
