<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Promotestore_Ebay_Drawer */
?>
<div class="drawer-header-content">
    <form id="drawer-form">
        <h2 class="title"><?php echo $this->__('Guidelines and Best Practices') ?></h2>
        <article class="entry">
            <p><?php echo $this->__('Magento-to-eBay (M2E) lets you list your Magento products in the eBay marketplace. It\'s the ideal way to attract new business and extend your products to millions of eBay shoppers worldwide. Best of all, it\'s free – including support and updates. Link your store and start selling on eBay today! Click a link to begin.'); ?></p>
        </article>
        <div class="go-do">
            <h2 class="title-checklist"><?php echo $this->__('Go Do'); ?></h2>
            <ul class="checklist">
                <li class="uncompleted"><a href="#" target="_blank"><?php echo $this->__('M2E in Magento Connect'); ?></a></li>
                <li class="uncompleted"><a href="#" target="_blank"><?php echo $this->__('M2E in Magento Go'); ?></a></li>
            </ul>
        </div>
    </form>
</div>
