<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?=__('Select from existing customer addresses:')?><br/>
<select id="shipping_address:address_id" onchange="sc_addressSelect('shipping',this.options[this.selectedIndex].value);sc_addressChange(this);" style="width: 324px;"<?=($this->getSameAsBilling() ? ' disabled' : '')?>>
    <option value=""><?=__('Add New Address')?></option>
    <?foreach ($this->getAddresses() as $_address):?>
        <option value="<?=$_address->getId()?>"<?=$this->getIsSelected($_address)?>><?=$_address->getFirstname()?> <?=$_address->getLastname()?>, <?=$_address->getStreet(-1)?>, <?=$_address->getCity()?>,<?=$_address->getRegion()?> <?=$_address->getPostcode()?></option>
    <?endforeach;?>
</select>