<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Cookie settings initialization script
 *
 * @see \Magento\Framework\View\Element\Js\Cookie
 */
?>

<script type="text/javascript">
	require([
		"jquery",
		"jquery/jquery.cookie",
		"mage/mage",
		"mage/cookies"
	], function($){
	    
	    $.extend($.mage.cookies.defaults, {
	        expires: null,
	        path: '<?php echo $this->getPath()?>',
	        domain: '<?php echo $this->getDomain()?>',
	        secure: false
	    });
	    
	    $.extend($.cookie.defaults, $.mage.cookies.defaults);
	});
</script>
