<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php  foreach ($types as $type) {
     if ($messages = $this->getMessages($type)) {
         if (!$html) {
             $html .= '<div class="messages">';
         }
         $html .= '<div class="message ' . $type . '">';

         foreach ($messages as $message) {
             $html .= '<div>';
             $html .= $message->getText();
             $html .= '</div>';
         }
         $html .= '</div>';
     }
 }
if ($html) {
    $html .= '</div>';
}
?>
