<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Weee\Block\Item\Price\Renderer */

$_item = $this->getItem();
/** @var $_weeeHelper \Magento\Weee\Helper\Data */
$_weeeHelper = $this->helper('Magento\Weee\Helper\Data');
?>
<?php $_incl = $_item->getPriceInclTax(); ?>
<?php if ($this->displayPriceWithWeeeDetails()): ?>
    <span class="cart tax total" data-tax-toggle='{"itemTaxId" : "#unit-item-tax-details<?php echo $_item->getId(); ?>"}'>
<?php else: ?>
    <span class="cart price">
<?php endif; ?>

<?php echo $this->formatPrice($this->getUnitDisplayPriceInclTax()); ?>
    </span>

<?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
    <div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
        <?php if ($this->displayPriceWithWeeeDetails()): ?>
            <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                <span class="weee"><?php echo $tax['title']; ?>: <?php echo $this->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <?php if ($this->displayFinalPrice()): ?>
        <div class="cart tax total" data-tax-toggle='{"itemTaxId" : "#unit-item-tax-details<?php echo $_item->getId(); ?>"}'>
            <span class="weee"><?php echo __('Total incl. tax'); ?>:<br />
                <?php echo $this->formatPrice($this->getFinalUnitDisplayPriceInclTax()); ?>
            </span>
        </div>
    <?php endif; ?>
<?php endif; ?>