<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * Template for displaying product price at catalog and sidebars
 *
 * @var $this \Magento\Catalog\Block\Product\Price
 */
?>
<?php
    /** @var $_product \Magento\Catalog\Model\Product */
    $_product = $this->getProduct();
    $_msrpPrice = "";
?>
    <div class="price-box map-info">
    <?php $_price = $this->helper('Magento\Tax\Helper\Data')->getPrice($_product, $_product->getMsrp()) ?>
        <?php if ($_product->getMsrp()): ?>
            <?php $_msrpPrice = $this->helper('Magento\Core\Helper\Data')->currency($_product->getMsrp(),true,true) ?>
            <span class="old-price" id="product-price-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>"><?php echo $_msrpPrice ?></span>
        <?php endif; ?>
        <?php echo __('Click for price') ?>
    </div>
