<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Catalog advanced search form
 *
 * @see \Magento\CatalogSearch\Block\Advanced\Form
 */
?>
<?php $maxQueryLength= $this->helper('Magento\CatalogSearch\Helper\Data')->getMaxQueryLength();?>
<form class="form search advanced" action="<?php echo $this->getSearchPostUrl() ?>" method="get" id="form-validate">
<fieldset class="fieldset">
    <legend class="legend"><span><?php echo __('Search Settings') ?></span></legend><br />
    <?php foreach ($this->getSearchableAttributes() as $_attribute): ?>
    <?php $_code = $_attribute->getAttributeCode() ?>
        <div class="field <?php echo $_code ?>">
            <label class="label" for="<?php echo $_code ?>"><span><?php echo $this->getAttributeLabel($_attribute) ?></span></label>
            <div class="control">
            <?php switch($this->getAttributeInputType($_attribute)):
                case 'number': ?>
                <div class="range fields group group-2">
                    <div class="field no-label">
                        <div class="control">
                            <input type="text" name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text" maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'less-than-equals-to':'#<?php echo $_code ?>_to'}" />
                        </div>
                    </div>
                    <div class="field no-label">
                        <div class="control">
                            <input type="text" name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text"  maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'greater-than-equals-to':'#<?php echo $_code ?>'}" />
                        </div>
                    </div>
                </div>
                <?php break;
                case 'price': ?>
                <div class="range price fields group group-2">
                    <div class="field no-label">
                        <div class="control">
                            <input name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text" type="text"  maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'less-than-equals-to':'#<?php echo $_code ?>_to'}" />
                        </div>
                    </div>
                    <div class="field with-addon no-label">
                        <div class="control">
                            <div class="addon">
                            <input name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text" type="text"  maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'greater-than-equals-to':'#<?php echo $_code ?>'}" />
                            <label class="addafter" for="<?php echo $_code ?>_to"><?php echo $this->getCurrency($_attribute); ?></label>
                            </div>
                        </div>
                    </div>
                </div>
                <?php break;
                case 'select': ?>
                    <?php echo $this->getAttributeSelectElement($_attribute) ?>
                <?php break;
                case 'yesno': ?>
                    <?php echo $this->getAttributeYesNoElement($_attribute) ?>
                <?php break;
                case 'date': ?>
                <div class="range dates fields group group-2">
                    <div class="field date no-label">
                        <div class="control">
                            <?php echo $this->getDateInput($_attribute, 'from') ?>
                        </div>
                    </div>
                    <div class="field date no-label">
                        <div class="control">
                            <?php echo $this->getDateInput($_attribute, 'to') ?>
                        </div>
                    </div>
                </div>
                <?php break;
                default: ?>
                <input type="text" name="<?php echo $_code ?>" id="<?php echo $_code ?>" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute)) ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text <?php echo $this->getAttributeValidationClass($_attribute) ?>"  maxlength="<?php echo $maxQueryLength;?>" />
            <?php endswitch; ?>
            </div>
        </div>
    <?php endforeach; ?>
</fieldset>
<div class="actions">
    <button type="submit" class="action search" title="<?php echo __('Search') ?>"><span><?php echo __('Search') ?></span></button>
</div>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#form-validate').validation({
                    errorPlacement: function (error, element) {
                        var parent = element.parent();
                        if (parent.hasClass('range')) {
                            parent.find(this.errorElement + '.' + this.errorClass).remove().end().append(error);
                        } else {
                            error.insertAfter(element);
                        }
                    },
                    messages: {
                        'price[to]': {'greater-than-equals-to': 'Please enter a valid price range.'},
                        'price[from]': {'less-than-equals-to': 'Please enter a valid price range.'}
                    }
                });
            });
    })(jQuery);
</script>
