<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Promotestore_Contentpages_Drawer */
?>
<div class="drawer-header-content">
    <form id="drawer-form">
        <h2 class="title"><?php echo $this->__('Guidelines and Best Practices') ?> </h2>
        <article class="entry">
            <p><?php echo $this->__('After your home page is configured, set up the other important pages on your site. Start with “About Us” – it’s the perfect place to tell new customers more about your store and what they can expect to find. You also need pages for your sales terms and conditions, privacy policy, and customer service.') ?> </p>
        </article>
        <div class="go-do">
            <h2 class="title-checklist"><?php echo $this->__('Go Do') ?> </h2>
            <ul class="checklist">
                <?php $trackerLink = $this->getTrackerLink('adminhtml/cms_page/edit', array('page_id' => 3)); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create About Us page') ?></a></li>

                <?php $trackerLink = $this->getTrackerLink('adminhtml/cms_page/edit', array('page_id' => 4)); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create Customer Service page') ?></a></li>

                <?php $trackerLink = $this->getTrackerLink('adminhtml/cms_page/edit', array('page_id' => 6)); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create Privacy Policy page') ?></a></li>

                <?php $trackerLink = $this->getTrackerLink('adminhtml/checkout_agreement/new'); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create Terms and Conditions page') ?></a></li>

                <?php $trackerLink = $this->getTrackerLink('adminhtml/cms_page/edit', array('page_id' => 1)); ?>
                <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo $this->__('Create “Page not found” page') ?></a></li>
            </ul>
        </div>
    </form>
</div>
