<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\Downloadable\Block\Customer\Products\ListProducts
 */
?>
<?php $_items = $this->getItems(); ?>
<div class="downloadable products toolbar">
    <?php echo $this->getChildHtml('pager'); ?>
</div>
<?php if(count($_items)): ?>
    <table id="my-downloadable-products-table" class="data table downloadable products">
        <thead>
            <tr>
                <th class="col id"><?php echo __('Order #') ?></th>
                <th class="col date"><?php echo __('Date') ?></th>
                <th class="col title"><?php echo __('Title') ?></th>
                <th class="col status"><?php echo __('Status') ?></th>
                <th class="col remaining"><?php echo __('Remaining Downloads') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_items as $_item): ?>
                <tr>
                    <td class="col id">
                        <a href="<?php echo $this->getOrderViewUrl($_item->getPurchased()->getOrderId()) ?>" title="<?php echo __('View Order') ?>">
                            <?php echo $_item->getPurchased()->getOrderIncrementId() ?>
                        </a>
                    </td>
                    <td class="col date"><?php echo $this->formatDate($_item->getPurchased()->getCreatedAt()) ?></td>
                    <td class="col title">
                        <?php echo $this->escapeHtml($_item->getPurchased()->getProductName()) ?> - <a href="<?php echo $this->getDownloadUrl($_item) ?>" title="<?php echo __('Start Download') ?>" <?php echo $this->getIsOpenInNewWindow()?'onclick="this.target=\'_blank\'"':''; ?>><?php echo $this->escapeHtml($_item->getLinkTitle()) ?></a>
                    </td>
                    <td class="col status"><?php echo __(ucfirst($_item->getStatus())) ?></td>
                    <td class="col remaining"><?php echo $this->getRemainingDownloads($_item) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p class="empty"><?php echo __('You have not purchased any downloadable products yet.'); ?></p>
<?php endif; ?>
<div class="downloadable products toolbar">
    <?php echo $this->getChildHtml('pager'); ?>
</div>

<div class="actions">
    <div class="secondary">
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="action back"><span><?php echo __('Back') ?></span></a>
    </div>
</div>