<?php
/**
 * {license_notice}
 *
 * @category    Saas
 * @package     Saas_PrintedTemplate
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * @var Saas_PrintedTemplate_Block_Widget_TaxGrid_Editor $this
 */
?>
<script type="text/javascript">
//<![CDATA[
    if (window.printedTemplateType !== 'invoice' && window.printedTemplateType !== 'creditmemo') {
        $('widget_options_saas_printedtemplate_widget_taxGrid').innerHTML =
            '<ul id="printedtemplate_widget_warning" class="messages"><li class="error-msg"><ul><li><?php echo $this->jsQuoteEscape(__("This widget is available only for printed templates.")) ?></li></ul></li></ul>';
    } else {
        $('parameter_type').value = '$' + printedTemplateType;
    }
//]]>
</script>

<input type="hidden" name="parameters[entity]" id="parameter_type" value=""/>

