<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="checkout-onepage-payment-additional-giftcardaccount">
<p class="note">
    <?php $_url = Mage::getUrl('checkout/cart'); ?>
    <?php echo $this->helper('Enterprise_GiftCardAccount_Helper_Data')->__('To add or remove gift cards, <a href="%s">click here</a>.', $_url); ?><br />

    <?php if ((float)$this->getAppliedGiftCardAmount()): ?>
        <?php $amount = $this->helper('Mage_Core_Helper_Data')->currency($this->getAppliedGiftCardAmount(), true); ?>
        <?php echo $this->helper('Enterprise_GiftCardAccount_Helper_Data')->__('Gift Card amount applied to order: %s', $amount); ?>
    <?php endif; ?>
</p>
</div>
