<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title><?=$product->getName()?></title>
</head>
<body>
    <center>
    <img src="<?=$this->getSkinUrl('catalog/images/placeholder_product_main.jpg')?>" alt="<?=$product->getName()?>" width="330"/>
    </center>
</body>
</html>
