<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_pro
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div>
    <h2 style="font-size:1.4em; margin:0;"><strong><?php echo __('Installation') ?></strong></h2>

    <div class="content">
        <ol>
            <?php foreach ($this->getDownloaderSteps() as $step): ?>
            <li><?php echo $step ?></li>
            <?php endforeach; ?>
            <?php if ($this->isDownloaderInstall()) : ?>
            <li><?php echo __('Channel Server Authorization')?></li>
            <?php endif; ?>
            <li><?php echo __('Download')?></li>
            <?php foreach ($steps as $_step): ?>
            <li <?php if ($_step->getActive()): ?>style="color:#f15d22; font-weight:bold; "<?php endif ?>><?php echo __($_step->getCode()) ?></li>
            <?php endforeach ?>
        </ol>
        <br/>

        <p>
            <?php echo __('Having trouble installing Magento?') ?>
            <?php echo __('Check out our') ?> <a href="http://www.magentocommerce.com/install"
                                                        target="installation_guide"><?php echo __('Installation Guide') ?></a>
        </p>
    </div>
</div>
