<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\AbstractSidebar */
?>
<div class="create-order-sidebar-block" id="sidebar_data_<?php echo $this->getDataId() ?>">
    <div class="head">
        <a href="#" class="action-refresh" title="<?php echo __('Refresh') ?>" onclick="order.loadArea('sidebar_<?php echo $this->getDataId() ?>', 'sidebar_data_<?php echo $this->getDataId() ?>');return false;">Refresh</a>
        <h5><?php echo $this->getHeaderText() ?> <span class="normal">(<?php echo $this->getItemCount() ?>)</span></h5>
        <select class="sidebar-selector">
            <option value="all">- <?php echo __('All Wish Lists');?> -</option>
            <?php foreach($this->getWishlists() as $id => $name) :?>
                <option value="<?php echo $id;?>"><?php echo $this->escapeHtml($name);?></option>
            <?php endforeach;?>
        </select>
    </div>
    <div class="content">
        <div class="auto-scroll">
            <?php if($this->getItemCount()): ?>
            <table class="data-table" cellspacing="0">
                <col />
                <?php if ($this->canDisplayItemQty()): ?>
                <col width="20" />
                <?php endif; ?>
                <?php if($this->canDisplayPrice()): ?>
                <col width="60" />
                <?php endif; ?>
                <?php if($this->canRemoveItems()): ?>
                <col width="16" />
                <?php endif; ?>
                <col width="16" />
                <thead>
                    <tr>
                        <th><?php echo __('Item') ?></th>
                        <?php if ($this->canDisplayItemQty()): ?>
                        <th class="a-center"><?php echo __('Qty') ?></th>
                        <?php endif; ?>
                        <?php if($this->canDisplayPrice()): ?>
                        <th><?php echo __('Price') ?></th>
                        <?php endif; ?>
                        <?php if($this->canRemoveItems()): ?>
                        <th class="a-center">
                            <span class="icon icon-remove"><?php echo __('Remove') ?></span>
                        </th>
                        <?php endif; ?>
                        <th class="a-center">
                            <span class="icon icon-add"><?php echo __('Add To Order') ?></span>
                        </th>
                    </tr>
                </thead>
                <?php foreach ($this->getItems() as $_item): ?>
                <tbody>
                    <tr class="row wishlist-<?php echo $_item->getWishlistId();?>">
                        <td><?php echo $this->escapeHtml($_item->getName()) ?></td>
                        <?php if ($this->canDisplayItemQty()): ?>
                        <td class="a-center">
                            <?php echo $this->getItemQty($_item); ?>
                        </td>
                        <?php endif; ?>
                        <?php if($this->canDisplayPrice()): ?>
                        <td><?php echo $this->convertPrice($_item->getPrice()) ?></td>
                        <?php endif; ?>
                        <?php if($this->canRemoveItems()): ?>
                        <td class="a-center"><input type="checkbox" name="sidebar[remove][<?php echo $this->getItemId($_item) ?>]" value="<?php echo $this->getDataId() ?>" title="<?php echo __('Remove') ?>"/></td>
                        <?php endif; ?>
                        <td class="a-center">
                            <?php if ($this->isConfigurationRequired($_item->getTypeId()) && $this->getDataId() == 'wishlist'): ?>
                            <a href="#" onclick="order.sidebarConfigureProduct('<?php echo 'sidebar_wishlist' ?>', <?php echo $this->getProductId($_item) ?>, <?php echo $this->getItemId($_item) ?>); return false;"><img src="<?php echo $this->getViewFileUrl('images/grouped_to_order_icon.png') ?>" class="v-middle" alt="<?php echo __('Configure and Add to Order') ?>" title="<?php echo __('Configure and Add to Order') ?>" width="16" height="16"/></a>
                            <?php elseif ($this->isConfigurationRequired($_item->getTypeId())): ?>
                            <a href="#" onclick="order.sidebarConfigureProduct('<?php echo 'sidebar' ?>', <?php echo $this->getProductId($_item) ?>); return false;"><img src="<?php echo $this->getViewFileUrl('images/grouped_to_order_icon.png') ?>" class="v-middle" alt="<?php echo __('Configure and Add to Order') ?>" title="<?php echo __('Configure and Add to Order') ?>" width="16" height="16"/></a>
                            <?php else: ?>
                            <input type="checkbox" name="sidebar[<?php echo $this->getSidebarStorageAction() ?>][<?php echo $this->getIdentifierId($_item) ?>]" value="<?php echo $this->canDisplayItemQty() ? $_item->getQty()*1 : 1 ?>" title="<?php echo __('Add To Order') ?>"/>
                            <?php endif; ?>
                        </td>
                    </tr>
                </tbody>
                <?php endforeach; ?>
            </table>
            <?php else: ?>
                <?php echo __('No items') ?>
            <?php endif ?>
        </div>
        <?php if ($this->getItemCount() && $this->canRemoveItems()): ?>
        <?php echo $this->getChildHtml('empty_customer_cart_button'); ?>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
require(['prototype'], function(){

//<![CDATA[
    wishlistBlockId = 'sidebar_data_<?php echo $this->escapeJsQuote($this->getDataId()); ?>';
    wishlistBlock = {
        table : $(wishlistBlockId).down('.content table'),
        selector : $(wishlistBlockId).down('.head select'),
        init : function() {
            Event.observe(this.selector, 'change', this.filter.bind(this))
        },
        filter : function() {
            if (this.selector.value) {
                $(this.table).select('tr.row').each((function(row) {
                    var wishlistId = $(row).className.split('-')[1];
                    $(row).setStyle({
                        'display': (this.selector.value == 'all' || wishlistId == this.selector.value) ? '' : 'none'
                    });
                }).bind(this));
            }
        }
    };
    wishlistBlock.init();
//]]>

});
</script>
