<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php  $_order = $this->getOrder() ?>
<?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order)) : ?>
    <a href="<?php echo $this->getReorderUrl($_order) ?>"><?php echo __('Reorder') ?></a>
    <span class="separator">|</span>
<?php endif ?>
<a href="<?php echo $this->getPrintUrl($_order) ?>" onclick="this.target='_blank';"><?php echo __('Print Order') ?></a>
<?php if($this->helper('Magento\Rss\Helper\Order')->isStatusNotificationAllow()): ?>
    <span class="separator">|</span>
    <a href="<?php echo $this->helper('Magento\Rss\Helper\Order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss f-none"><?php echo __('Subscribe to Order Status') ?></a>
<?php endif; ?>
<?php echo $this->getChildHtml(); ?>
