<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    /* @var $this \Magento\MultipleWishlist\Block\Behaviour */
?>
<script id="form-tmpl" type="text/x-jQuery-tmpl">
    <form id="wishlist-hidden-form" method="post" action="${url}" class="no-display">
        {{if itemId}}<input name="item_id" value="${itemId}">{{/if}}
        {{if wishlistId}}<input name="wishlist_id" value="${wishlistId}">{{/if}}
        {{if qty}}<input name="qty" value="${qty}">{{/if}}
        {{if item}}<input name="item" value="${item}">{{/if}}
        {{if entity}}<input name="entity" value="${entity}">{{/if}}
    </form>
</script>
<script id="popup-tmpl" type="text/x-jQuery-tmpl">
    <div class="window overlay active" style="height: ${$('body').height()}px;"></div>
    <div id="${popupWishlistBlockId}" class="popup active">
        <div class="title">
            {{if isEdit}}${$.mage.__('Edit Wish List')}{{else}}${$.mage.__('Create New Wish List')}{{/if}}
        </div>
        <span class="action ${btnCloseClass}" title="${$.mage.__('Close')}"><span>${$.mage.__('Close')}</span></span>
        <div class="content">
            <form id="${popupWishlistFormId}" method="post" action="${url}" class="form wishlist">
                <fieldset class="fieldset">
                    <div class="field name">
                        <label for="wishlist-name" class="label"><span>${$.mage.__('Wish List Name')}</span></label>
                        <div class="control">
                            <input id="wishlist-name" class="input-text" data-validate="{required:true}" type="text" name="name" maxlength="255" value="${name}">
                        </div>
                    </div>
                    <div class="field choice">
                        <div class="control">
                            <input id="wishlist-public" type="checkbox" name="visibility"{{if isPublic}} checked=true{{/if}}">
                        </div>
                        <label for="wishlist-public" class="label"><span>${$.mage.__('Make This Wish List Public')}</span></label>
                    </div>
                    <div class="actions">
                        <button class="action save" type="submit" title="${$.mage.__('Save')}">
                            <span>${$.mage.__('Save')}</span>
                        </button>
                        <button class="action cancel ${btnCloseClass}" type="button" title="${$.mage.__('Cancel')}">
                            <span>${$.mage.__('Cancel')}</span>
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</script>
<script id="split-btn-tmpl" type="text/x-jQuery-tmpl">
    <div class="split button">
        <span data-post='${JSON.stringify(generalParams)}' data-action="add-to-wishlist" class="label">${buttonName}</span>
        <span class="action change" title="${$.mage.__('Add to:')}" data-toggle="dropdown"><span>${$.mage.__('Add to:')}</span></span>
        <ul class="items" data-target="dropdown">
            {{each wishlists}}
            <li class="item">
                {{if newClass}}
                    <span class="action ${newClass}" data-post-new-wishlist='${JSON.stringify(params)}' data-action="add-to-wishlist" title="${name}"><span>${name}</span></span>
                {{else}}
                    <span data-post='${JSON.stringify(params)}' data-action="add-to-wishlist" title="${name}">${name}</span>
                {{/if}}
            </li>
            {{/each}}
        </ul>
    </div>
</script>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            "<?php echo $this->getViewFileUrl('Magento_MultipleWishlist::js/multiple-wishlist.js') ?>",
            function() {
                $('body').multipleWishlist({
                    canCreate: <?php echo $this->canCreateWishlists($this->getWishlists()) ? 'true' : 'false';?>,
                    createUrl: '<?php echo $this->getCreateUrl();?>',
                    wishlists: <?php echo $this->helper('Magento\Core\Helper\Data')->jsonEncode($this->getWishlistShortList());?>,
                    wishlistLink: '.action.towishlist'
                });
                $('.products.list [data-toggle=dropdown]')
                    .add('.cart.items.data [data-toggle=dropdown]')
                    .add('.product.addto.links [data-toggle=dropdown]')
                    .add('.secondary.addto.links [data-toggle="dropdown"]')
                    .dropdown({
                        events: [{
                            'name': 'mouseleave',
                            'selector': '.item.product',
                            'action': function() {
                                var triggerElem = $('[data-toggle=dropdown]', this);
                                triggerElem.hasClass('active') && triggerElem.trigger('click.toggleDropdown');
                            }
                        }]
                    });
            });
    })(jQuery);
</script>
