<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $wishlistItems = $this->getWishlistItems();
?>
<div class="block wishlist info">
    <div class="actions">
        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isRssAllow() && count($this->getWishlistItems())): ?>
            <a href="<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getRssUrl($this->getWishlistInstance()->getId()); ?>" class="action rss"><span><?php echo __('RSS Feed') ?></span></a>
        <?php endif; ?>
    </div>
    <table class="data table wishlist info">
        <tbody>
        <tr>
            <th class="col owner"><?php echo __('Owner');?></th>
            <td class="col owner"><?php echo $this->escapeHtml($this->getWishlistOwner()->getName());?></td>
        </tr>
        <tr>
            <th class="col name"><?php echo __('Name');?></th>
            <td class="col name"><?php echo $this->escapeHtml($this->getWishlistInstance()->getName());?></td>
        </tr>
        <tr>
            <th class="col updated"><?php echo __('Updated at');?></th>
            <td class="col updated">
                <?php echo $this->formatDate($this->getWishlistInstance()->getUpdatedAt(), Magento\LocaleInterface::FORMAT_TYPE_MEDIUM);?>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="title">
        <strong><?php echo __('Wish List Items') ?></strong>
    </div>
    <form method="post" action="<?php echo $this->getToCartUrl();?>" id="wishlist-info-form" class="form wishlist">
        <?php $this->getChildBlock('items')->setItems($this->getWishlistItems()); ?>
        <?php echo $this->getChildHtml('items');?>
        <?php if (count($wishlistItems) && $this->isSaleable()): ?>
            <div class="actions">
                <div class="primary">
                    <button type="submit" title="<?php echo __('Add to Cart') ?>" class="action tocart"><span><?php echo __('Add to Cart') ?></span></button>
                </div>
                <div class="secondary">
                    <a href="<?php echo $this->getBackUrl() ?>" class="action back"><span><?php echo __('Back') ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </form>
</div>
<script>
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
            "<?php echo $this->getViewFileUrl('Magento_Wishlist::wishlist.js')?>", function() {
                $('#wishlist-info-form').wishlist({
                    infoList: true,
                    checkBoxValidationMessage: '<?php echo __('You must select items to add to the cart.');?>'
                });
            });
    })(jQuery);
</script>
