<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_modern
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<div class="c pr" data-mage-init="{tabs: []}">
    <ul>
        <?php foreach ($this->getTabs() as $_index => $_tab): ?>
            <?php if($this->getChildHtml($_tab['alias'])): ?>
                <li><a href="#pt-<?php echo $_tab['alias'] ?>"><?php echo $_tab['title']?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <?php foreach ($this->getTabs() as $_index => $_tab): ?>
        <?php if($this->getChildHtml($_tab['alias'])): ?>
            <div id="pt-<?php echo $_tab['alias'] ?>">
                <?php if ($_tab['header']): ?>
                    <h2><?php echo $this->escapeHtml($_tab['header']); ?></h2>
                <?php endif;?>
                <?php echo $this->getChildHtml($_tab['alias']) ?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
