<div class="content">
<h1 class="page-heading">Shopping Cart</h1>
<form action="<?=Mage::getUrl('checkout', array('controller'=>'cart', 'action'=>'updatePost'))?>" method="post">
    <table cellspacing="6" width="100%" class="data-table">
        <tr>
            <th class="align-left">Product Name</th>
            <th style="width:68px;" class="align-center">Remove</th>
            <th style="width:88px;" class="align-center">Unit Price</th>
            <th style="width:45px;" class="align-center">Qty</th>
            <th style="width:70px;" class="align-center">Total</th>
        </tr>
        <?foreach($data['cart']['items'] as $item):?>
        <tr>
            <td><a href="<?=Mage::getUrl('catalog', array('controller'=>'product', 'action'=>'view', 'id'=>$item['product_id']))?>"><?=$item['name']?></a></td>
            <td class="align-center"><input type="checkbox" value="1" name="cart[<?=$item['entity_id']?>][remove]"/></td>
            <td class="align-center"><?=$item['price']?></td>
            <td class="align-center"><input name="cart[<?=$item['entity_id']?>][qty]" value="<?=$item['qty']?>" size="2" class="input-text qty"/></td>
            <td class="align-right"><?=$item['row_total']?></td>
        </tr>
        <?endforeach?>
        <?foreach($data['cart']['totals'] as $total):?>
        <tr>
            <th colspan=4 class="align-right"><?=$total['title']?>:</th><td class="align-right" style="<?=isset($total['style'])?$total['style']:''?>"><?=$total['value']?></td>
        </tr>
        <?endforeach?>
    </table>
    <div class="buttons-container">
        <div class="input-left">
            <input type="button" value="Continue Shopping" onclick="location.href='<?=Mage::getBaseUrl()?>'" class="input-button"/>
        </div>
        <div class="input-right align-right">
            <input type="submit" value="Update" class="input-button" name="do"/>
            <input type="button" value="Checkout" onclick="location.href='<?=Mage::getUrl('checkout')?>'" class="input-button"/>
        </div>
        <div class="clearfix"></div>
    </div>
</form>
<br />
<ul class="input-list">
    <li>
        <div class="input-left">
            <h2>Estimate</h2>
            <form action="<?=Mage::getUrl('checkout', array('controller'=>'cart', 'action'=>'estimatePost'))?>" method="post">
                <label for="">Zipcode:</label><br />
                <input class="input-text" name="estimate_postcode" value="<?=$data['cart']['estimate_postcode']?>"/> <input type="submit" value="Estimate" class="input-button" name="do"/>
            </form>
            <?if (!empty($data['cart']['estimate_methods'])):?>
                <br><br>
                <form action="<?=Mage::getUrl('checkout', array('controller'=>'cart', 'action'=>'estimateUpdatePost'))?>" method="post">
                	<fieldset>
                    	<ul>
            	        <?foreach ($data['cart']['estimate_methods'] as $method):?>
            	           <?if (!isset($method['vendor'])) continue; ?>
                    		<li>
                    		    <input id="estimate_method_<?=$method['code']?>" name="estimate_method" type="radio" value="<?=$method['code']?>" <?if($method['code']===$data['cart']['estimate_method'])echo"checked"?> />
                    		    <label for="estimate_method_<?=$method['code']?>"><?=$method['vendor']?>: <?=$method['service_description']?></label>:
                    		    <strong><?=$method['amount']?></strong>
                    		</li>
                		<?endforeach?>
    	   	           </ul>
    	   	           <br>
    	   	           <input type="submit" value="Update totals" class="input-button" name="do"/>
    	   	        </fieldset>
    	        </form>
            <?endif?>
        </div>
        <div class="input-right">
            <h2>Discounts</h2>
            <form action="<?=Mage::getUrl('checkout', array('controller'=>'cart', 'action'=>'couponPost'))?>couponPost/" method="post">
                <label for="coupon_code">Coupon code:</label><br />
                <input class="input-text" id="coupon_code" name="coupon_code" value="<?=$data['cart']['coupon_code']?>"/> <input type="submit" value="Apply" class="input-button" name="do"/> <input type="submit" value="Clear" class="input-button" name="do"/>
            </form>
            <br>
            <form action="<?=Mage::getUrl('checkout', array('controller'=>'cart', 'action'=>'giftCertPost'))?>" method="post">
                <label for="giftcert_code">Gift certificate:</label><br />
                <input class="input-text" id="giftcert_code" name="giftcert_code" value="<?=$data['cart']['giftcert_code']?>"/> <input type="submit" value="Apply" class="input-button" name="do"/> <input type="submit" value="Clear" class="input-button" name="do"/>
            </form>
        </div>
        <div class="clearfix"></div>
    </li>
</ul>
</div>