<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->canRefundToCustomerBalance()): ?>
    <div class="field choice field-refund-store-credit">
        <input type="hidden" name="creditmemo[refund_customerbalance_return_enable]" value="0">
        <input type="checkbox" name="creditmemo[refund_customerbalance_return_enable]" value="1" id="creditmemo_customerbalance_return_enable"<?php if ($this->helper('Magento\CustomerBalance\Helper\Data')->isAutoRefundEnabled()): ?> checked="checked"<?php endif ?>>
        <label for="creditmemo_customerbalance_return_enable"><span><?php echo __('Refund to Store Credit') ?></span></label>
        <input type="text" name="creditmemo[refund_customerbalance_return]" value="<?php echo $this->getReturnValue(); ?>" id="creditmemo_customerbalance_return" class="input-text not-negative-amount">
        <script type="text/javascript">
require(['jquery'], function($){

        $(function ($) {
            var toggleCustomerBalanceRefundAmount = function (e) {
                var refundReturn = $('#creditmemo_customerbalance_return');
                if ($(e.target).prop('checked')) {
                    refundReturn.prop('disabled', false);
                    disableElements('refund');
                } else {
                    refundReturn.prop('disabled', true);
                    enableElements('refund');
                }
            };
            var refundCustomerBalanceEnable = $('#creditmemo_customerbalance_return_enable');
            refundCustomerBalanceEnable.change(toggleCustomerBalanceRefundAmount);
            toggleCustomerBalanceRefundAmount({target:refundCustomerBalanceEnable});
        });
});
</script>
    </div>
<?php endif; ?>
