<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see \Magento\Authorizenet\Block\Directpost\Form
 */
?>
<fieldset id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="fieldset items">
    <div class="message notice">
        <div><?php echo __('You\'ll be asked for your payment details before placing an order.') ?></div>
    </div>
</fieldset>
