<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * @see \Magento\AdvancedCheckout\Block\Adminhtml\Manage
 */
?>
<?php
/**
 * @var $this \Magento\AdvancedCheckout\Block\Adminhtml\Manage
 */
?>

<?php echo $this->getChildHtml('checkout.js') ?>
<script type="text/javascript">
    require([
        "Magento_AdvancedCheckout/shopping_cart"
    ], function(){
        checkoutObj = new AdminCheckout(<?php echo $this->getOrderDataJson() ?>);
        checkoutObj.setLoadBaseUrl('<?php echo $this->getLoadBlockUrl() ?>');
        checkoutObj.setCurrencySymbol('<?php echo $this->getCurrencySymbol($this->getCurrentCurrencyCode()) ?>');
    });
</script>

<?php echo $this->getChildHtml('checkout.store.switcher'); ?>

<div id="checkout_message">
    <?php echo $this->getChildHtml('checkout.message') ?>
</div>

<div class="fieldset-wrapper shopping-cart-items">
    <div class="fieldset-wrapper-title">
        <strong class="title"><?php echo __('Shopping Cart Items') ?></strong>
    </div>

    <div id="checkout_items" class="checkout-items">
        <?php echo $this->getChildHtml('checkout.items') ?>
    </div>
    <div class="actions">
        <?php echo $this->getChildHtml('update_button') ?>
        <?php echo $this->getChildHtml('empty_customer_cart_button'); ?>
    </div>

    <div id="coupon_container" class="coupon">
        <?php echo $this->getChildHtml('checkout.form_coupon') ?>
    </div>
</div>


<div id="checkout_errors" class="checkout-errors">
    <?php echo $this->getChildHtml('errors') ?>
</div>

<div id="products_search" class="products-search">
    <div class="actions">
        <?php echo $this->getChildHtml('addto_cart_button') ?>
    </div>
    <div id="products_search_accordion">
        <?php echo $this->getChildHtml('checkout.accordion') ?>
    </div>
    <div class="actions">
        <?php echo $this->getChildHtml('addto_cart_button') ?>
    </div>
</div>
