<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>
</div>
<?php echo $this->getChildHtml('form_after');?>
<script type="text/javascript">
var updater = new RegionUpdater('tax_country_id', 'tax_region', 'tax_region_id', <?php echo $this->helper('Mage_Directory_Helper_Data')->getRegionJson() ?>, 'disable');
</script>
