<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Storelauncher_Design_Drawer_Theme */
$theme = $this->getTheme();
?>
<li class="theme" id="theme-id-<?php echo $this->getTheme()->getId() ?>">
    <div class="theme-content">
        <img src="<?php echo $theme->getThemeImage()->getPreviewImageUrl() ?>" alt="<?php echo $theme->getThemeTitle() ?>">
        <article class="theme-data">
            <h4 class="theme-title" title="<?php echo $theme->getThemeTitle() ?>"><?php echo $theme->getThemeTitle() ?></h4>
            <!-- TODO: placeholder for theme description -->
            <p><?php echo __('Our responsive theme designed by Magento pros to be best in breed for Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis'); ?></p>
            <div class="actions">
                <a class="action-theme-preview" target="_blank" href="<?php echo $this->getPreviewUrl($theme->getId())?>"><?php echo __('Preview Theme'); ?></a>
                <button type="button"
                        class="action-theme-assign primary"
                        data-theme-id="<?php echo $this->getTheme()->getId() ?>"
                        data-theme-img-src="<?php echo $theme->getThemeImage()->getPreviewImageUrl() ?>">
                    <span><?php echo __('Choose Theme'); ?></span>
                </button>
            </div>
        </article>
    </div>
</li>
