<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Product list template
 *
 * @see Magento_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('Magento_Catalog_Helper_Output');
?>
<?php if (!$_productCollection->count()): ?>
<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php echo $this->getToolbarHtml() ?>
<?php echo $this->getAdditionalHtml() ?>
<div class="category-products">
    <?php // List mode ?>
    <?php if ($this->getMode() != 'grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
        <?php $_imageSize = $this->getVar('product_list_image_size', 'Magento_Catalog');?>
        <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>"
               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
               class="product-image"><img
                src="<?php echo $this->helper('Magento_Catalog_Helper_Image')->init($_product, 'small_image')->resize($_imageSize); ?>"
                width="<?php echo $_imageSize?>" height="<?php echo $_imageSize?>"
                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                    </h2>
                    <?php if ($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                           class="link-learn"><?php echo __('Learn More') ?></a>
                    </div>
                    <?php if ($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo __('Add to Cart') ?>" class="button btn-cart"
                            data-mage-init="{redirectUrl: {url: '<?php echo $this->getAddToCartUrl($_product) ?>'}}">
                        <span><span><?php echo __('Add to Cart') ?></span></span></button>

                    <?php else: ?>
                    <?php if ($_product->getIsSalable()): ?>
                        <p class="availability in-stock"><span><?php echo __('In stock') ?></span></p>
                        <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo __('Out of stock') ?></span></p>
                        <?php endif; ?>
                    <?php endif; ?>
                    <ul class="add-to-links" data-role="add-to-links">
                        <?php if ($this->helper('Magento_Wishlist_Helper_Data')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('Magento_Wishlist_Helper_Data')->getAddUrl($_product) ?>"
                               class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                        <li><a href="<?php echo $_compareUrl ?>"
                               class="link-compare"><?php echo __('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
        <?php endforeach; ?>
    </ol>
    <script type="text/javascript">
        jQuery('#products-list').decorate('list');
    </script>
    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i = 0;
    foreach ($_productCollection as $_product): ?>
        <?php if ($i++ % $_columnCount == 0): ?>
    <ul class="products-grid">
    <?php endif ?>
        <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
            <a href="<?php echo $_product->getProductUrl() ?>"
               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"

               class="product-image"><?php echo $this->getLayout()->createBlock('Magento_Catalog_Block_Product_Image')->init($_product, 'category_page_grid')->toHtml(); ?></a>

            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                        title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
            </h2>
            <?php if ($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php endif; ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="actions">
                <?php if ($_product->isSaleable()): ?>
                <button type="button" title="<?php echo __('Add to Cart') ?>" class="button btn-cart"
                        data-mage-init="{redirectUrl: {url: '<?php echo $this->getAddToCartUrl($_product) ?>'}}">
                    <span><span><?php echo __('Add to Cart') ?></span></span></button>
                <?php else: ?>
                <?php if ($_product->getIsSalable()): ?>
                    <p class="availability in-stock"><span><?php echo __('In stock') ?></span></p>
                    <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo __('Out of stock') ?></span></p>
                    <?php endif; ?>
                <?php endif; ?>
                <ul class="add-to-links" data-role="add-to-links">
                    <?php if ($this->helper('Magento_Wishlist_Helper_Data')->isAllow()) : ?>
                    <li><a href="<?php echo $this->helper('Magento_Wishlist_Helper_Data')->getAddUrl($_product) ?>"
                           class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                    <li><a href="<?php echo $_compareUrl ?>"
                           class="link-compare"><?php echo __('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </li>
        <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
    </ul>
    <?php endif ?>
        <?php endforeach ?>
    <script type="text/javascript">
        jQuery('ul.products-grid > li').decorate('generic', ['odd', 'even', 'first', 'last']);
    </script>
    <?php endif; ?>
</div>
<div class="toolbar-bottom">
    <?php echo $this->getToolbarHtml() ?>
</div>
<?php endif; ?>
