<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product view template
 *
 * @see Magento_Catalog_Block_Product_View
 * @see Magento_Review_Block_Product_View
 * @var $this Magento_Catalog_Block_Product_View
 */
?>
<?php $_helper = $this->helper('Magento_Catalog_Helper_Output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php $this->getMessagesBlock()->setEscapeMessageFlag(true); ?>
<script type="text/javascript">
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/price-option.js') ?>", function () {
            $('#product_addtocart_form').priceOption({"priceConfig":<?php echo $this->getJsonConfig() ?>});
        });
    })(jQuery);
</script>

<div id="messages_product_view"><?php echo $this->getLayout()->renderElement('messages'); ?></div>
<div class="product-view">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div class="product-essential">

                <div class="product-shop">
                    <div class="product-main-info">
                        <div class="product-name">
                            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                        </div>
                        <p class="product-ids"><?php echo __('SKU# %1', $this->escapeHtml($_product->getSku())); ?></p>
                        <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                        <?php echo $this->getChildHtml('alert_urls') ?>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                    </div>
                    <?php echo ($_product->getCanShowPrice() === false) ? '' : $this->getChildHtml('tierprices'); ?>
                    <?php echo $this->getChildHtml('extrahint') ?>

                    <?php if (!$this->hasOptions()):?>
                        <div class="add-to-box">
                            <?php if($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                            <?php endif; ?>
                            <?php echo $this->getChildHtml('addto') ?>
                        </div>
                    <?php else:?>
                        <?php if ($_product->isSaleable() && $this->getOptionsContainer() == 'container1'):?>
                            <div class="options-container-small">
                                <?php echo $this->getChildChildHtml('options_container') ?>
                            </div>
                        <?php else: ?>
                            <?php echo $this->getChildHtml('addto') ?>
                        <?php endif;?>
                    <?php endif; ?>

                    <?php if ($_product->getShortDescription()):?>
                        <div class="short-description std">
                            <h2><?php echo __('Quick Overview') ?></h2>
                            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                        </div>
                    <?php endif;?>

                    <?php echo $this->getChildHtml('other');?>
                </div>

                <div class="product-img-box">
                    <?php echo $this->getChildHtml('media') ?>
                </div>

        </div>
        <div class="product-collateral">
            <?php if ($detailedInfoGroup = $this->getGroupChildNames('detailed_info', 'getChildHtml')):?>
                <div class="c pr" data-mage-init="{tabs: []}">
                    <?php $layout = $this->getLayout(); ?>
                    <ul>
                        <?php foreach ($detailedInfoGroup as $name):?>
                            <?php
                                $html = $layout->renderElement($name);
                                if (!$html) continue;
                                $alias = $layout->getElementAlias($name);
                                $label = $this->escapeHtml($this->getChildData($alias, 'title'));
                            ?>
                            <li><a href="#<?php echo $name; ?>"><?php echo $label; ?></a></li>
                        <?php endforeach;?>
                    </ul>
                    <?php foreach ($detailedInfoGroup as $name):?>
                        <?php
                            $html = $layout->renderElement($name);
                            if (!$html) continue;
                        ?>
                        <div id="<?php echo $name; ?>"><?php echo $html; ?></div>
                    <?php endforeach;?>
                </div>
            <?php endif; ?>
            <?php if ($this->canEmailToFriend()): ?>
                <p class="emailto-link"><a href="<?php echo $this->helper('Magento_Catalog_Helper_Product')->getEmailToFriendUrl($_product) ?>"><?php echo __('Email to a Friend') ?></a></p>
            <?php endif; ?>
        </div>
        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getOptionsContainer() == 'container2'):?>
            <div class="options-container-big">
                <?php echo $this->getChildChildHtml('options_container') ?>
            </div>
        <?php endif;?>
    </form>
        <?php echo $this->getChildHtml('relatedProducts') ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
