<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>

<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getGiftCardsAmount()): ?>
    <?php $_giftCards = $this->helper('Magento\GiftCardAccount\Helper\Data')->getCards($_source); ?>
    <?php foreach ($_giftCards as $_card): ?>
        <?php $_baseAmount = $_card['ba']; ?>
        <?php $_amount = $_card['a']; ?>
        <?php $_code = $_card['c']; ?>

        <tr>
            <td class="label"><?php echo __('Gift Card (%1)', $_code) ?></td>
            <td>
                <?php echo $this->displayPrices(-$_baseAmount, -$_amount); ?>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
