<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 /** @var $this Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config */
?>
<div class="entry-edit" id="<?php echo $this->getId() ?>">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">

        <?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Variation') ?>
        </h4>
        <div style="float:right">
            <input type="checkbox" id="<?php echo $this->getId()?>-checkbox" name="attributes"
                value=""
                <?php if ($this->_getProduct()->isConfigurable() || $this->getRequest()->has('attributes')) {
                    echo ' checked="checked" ';
                }?>
            />
            <label for="<?php echo $this->getId()?>-checkbox">
                <?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Does this product have variations?') ?>
            </label>
        </div>
    </div>
    <fieldset>
        <input id="attribute-selector"
            placeholder="start typing to search attribute"
            title="Select Attribute" type="text"
            style="width: 100%; margin: 0px 0px 20px; padding: 5px; box-sizing: border-box; font-size: 1.5em;"
            class="input-text" autocomplete="off">
        <div id="attributes-container">
        <?php echo $this->getChildHtml('template'); ?>
        <?php
        foreach ($this->getAttributes() as $attribute) {
            echo $this->getChildBlock('attribute-renderer')->render(array(
                'attribute' => $attribute,
            ));
        } ?>
        </div>
        <?php  echo $this->getChildHtml('generate'); ?>
        <?php
        if (count($this->getSelectedAttributes())) {
            echo $this->getChildHtml('matrix');
        ?>
            <div id="associated-products-container"
                data-used-attributes="<?php echo $this->escapeHtml($this->helper('Mage_Core_Helper_Data')->jsonEncode($this->getAttributes())); ?>"
                style="display: none;">
                <?php echo $this->getGridHtml(); ?>
            </div>

            <div><input type="hidden" name="affect_configurable_product_attributes" value="1" /></div>
        <?php } ?>

</fieldset>

<script type="text/javascript">
jQuery(function($) {
    var usedAttributes = jQuery('#associated-products-container').data('usedAttributes') || [];
    $('#attributes-container').configarableAttributes();

    $("#<?php echo $this->getId()?>-checkbox").on('click change', function() {
        var $fieldset = $("#<?php echo $this->getId()?> > fieldset");
        if ($(this).is(':checked')) {
            $fieldset.show();
            $("#<?php echo $this->getId()?> input[name='attributes[]']").removeAttr('disabled');
            $('#qty').attr('disabled', true);
            $.each(usedAttributes, function() {
                $('#attribute-' + this.attribute_code + '-container select').attr('disabled', true);
            });
        } else {
            $('#qty').removeAttr('disabled');
            $("#<?php echo $this->getId()?> input[name='attributes[]']").attr('disabled', true);
            $.each(usedAttributes, function() {
                $('#attribute-' + this.attribute_code + '-container select').removeAttr('disabled');
            });
            $fieldset.hide();
        }
    }).trigger('change');

    var $gridDialog = $('#associated-products-container').dialog({
        title:'Select Associated Product',
        autoOpen:false,
        minWidth:980,
        modal:true,
        resizable:true
    });

    $.each($('#product-variations-matrix input[type!="checkbox"][type!="hidden"]'), function(key, input) {
        var $input = $(input),
            name = $input.attr('name'),
            $parentInput = $('#' + name.match(/\[(\w+)\]$/)[1]),
            classes = $parentInput.attr('class');
        if (classes) {
            $.each(classes.split(/\s+/), function (k, v) {
                if (v.indexOf('validate-') === 0) {
                    $input.addClass(v);
                }
            });
        }
    });

    $('#product-variations-matrix').on('click', 'input.associated-matrix-product-id', function() {
        $(this).closest('tr').find('input[type!=checkbox]').prop('disabled', !$(this).is(':checked'));
    });

    $('#product-variations-matrix').on('click', '.choose-product', function(event) {
        event.preventDefault();
        var grid = window.<?php echo $this->getGridJsObject() ?>;
        var $button = $(this);
        grid.reloadParams = {
            'filter': $button.data('attributes'),
            'attributes[]': Object.values(usedAttributes).map(function(el) { return el.attribute_id; })
        };
        grid.reload(null, function() {
            $gridDialog.dialog('open')
        });

        grid.rowClickCallback = function(grid, event) {
            if (!this.rows || !this.rows.length) {
                return;
            }
            var $matrixRow = $button.parents('tr');
            var $gridRow = $(event.target).parents('tr');
            var matrixClass = '.associated-matrix-product-';
            var associatedClass = '.associated-product-';
            var productFields = ['name', 'sku', 'qty', 'weight', 'id'];

            if ($gridRow.find(associatedClass + 'id').length) {
                $.each(productFields, function () {
                    var target = $matrixRow.find(matrixClass + this),
                        value = $.trim($gridRow.find(associatedClass + this).text()),
                        button = target.find('button.choose-product');
                    target[target.is('input[type=checkbox]') ? 'val' : 'html'](value).append(button);
                });
                $matrixRow.find(matrixClass + 'id').attr('checked', true).removeAttr('disabled');
            }
            $gridDialog.dialog('close');
        };
    });
});
</script>
</div>
