<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 /** @var $this Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config_Matrix */
?>
<?php
$variations = $this->getVariations();
if (count($variations)) {
$usedProductAttributes = $this->getUsedAttributes();
$productByUsedAttributes = $this->getUsedProducts();
?>
<table cellspacing="0">
    <thead>
    <tr class="headings">
        <th width="180" class="name <?php echo $this->getAttributeClassName('name'); ?>">
            <?php echo $this->__('Product Name'); ?>
        </th>
        <th width="180">
            <?php echo $this->__('Price'); ?> <span class="required">*</span>
        </th>
        <th width="220" class="sku <?php echo $this->getAttributeClassName('sku'); ?>">
             <?php echo $this->__('SKU'); ?>
        </th>
        <th width="180" class="qty">
            <?php echo $this->__('Quantity'); ?>
        </th>
        <th width="180" class="weight <?php echo $this->getAttributeClassName('weight'); ?>">
            <?php echo $this->__('Weight'); ?>
        </th>
        <?php
        foreach ($usedProductAttributes as $attribute) {
            /** @var $attribute Mage_Catalog_Model_Resource_Eav_Attribute */
            echo '<th class="' . $attribute->getAttributeCode() . '">', $attribute->getStoreLabel(), '</th>', PHP_EOL;
        }
        ?>
        <th class="a-center include" width="55">
            <?php echo $this->__('Include'); ?>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php
    if (count($variations) === 0) {
        echo '<tr><td colspan="' . (6 + count($usedProductAttributes)) . '">'
        . $this->__('No variations generated')
        . '</td></tr>';
    }
    $isEven = true;
    $productPrice = (float)$this->_getProduct()->getPrice();

    foreach ($variations as $variation) {
        $attributeValues = array();
        $attributeLabels = array();
        $price = $productPrice;
        foreach ($usedProductAttributes as $attribute) {
            /** @var $attribute Mage_Catalog_Model_Resource_Eav_Attribute */
            $attributeValues[$attribute->getAttributeCode()] = $variation[$attribute->getId()]['value'];
            $attributeLabels[$attribute->getAttributeCode()] = $variation[$attribute->getId()]['label'];
            if (isset($variation[$attribute->getId()]['price'])) {
                $priceInfo = $variation[$attribute->getId()]['price'];
                $price += ($priceInfo['is_percent'] ? $productPrice / 100.0 : 1.0) * $priceInfo['pricing_value'];
            }
        }
        $attributeLabels = $this->escapeHtml($attributeLabels);
        $key = implode('-', $attributeValues);
        if (isset($productByUsedAttributes[$key])) {
            $product = $productByUsedAttributes[$key];
            ?>
            <tr class="<?php echo $isEven ? 'even' : '' ?>">
                <td class="associated-matrix-product-name"><a
                        href="<?php echo $this->getEditProductUrl($product->getId())?>"
                        target="_blank"><?php echo $this->escapeHtml($product->getName())?></a></td>
                <td class="associated-matrix-product-price"><?php echo $price ?></td>
                <td><span class="associated-matrix-product-sku"><?php echo $this->escapeHtml($product->getSku())?></span>
                    <button class="choose-product"
                        data-attributes="<?php echo $this->escapeHtml($this->helper('Mage_Core_Helper_Data')->jsonEncode($attributeValues)); ?>"
                        style="float:right">
                        Choose
                    </button>
                </td>
                <td class="associated-matrix-product-qty"><?php echo $product->getStockItem()->getQty()?></td>
                <td class="associated-matrix-product-weight"><?php echo $product->getWeight()?></td>
                <td><?php echo implode('</td><td>', $attributeLabels)?></td>
                <td class="a-center"><input type="checkbox" name="associated_product_ids[]"
                        value="<?php echo $product->getId()?>" class="checkbox associated-matrix-product-id"
                        checked="checked"></td>
            </tr>
        <?php
        } else {
            $checked = $this->_getProduct()->getId() && !$this->_getProduct()->dataHasChangedFor('type_id') ? '' : ' checked="checked"';
            $disabled = $this->_getProduct()->getId() && !$this->_getProduct()->dataHasChangedFor('type_id') ? ' disabled="disabled"' : '';
            ?>
            <tr class="<?php echo $isEven ? 'even' : '' ?>">
                <td class="associated-matrix-product-name">
                    <input id="variations-matrix-<?php echo $key?>-name"
                        name="variations-matrix[<?php echo $key?>][name]"
                        value="<?php echo $this->escapeHtml($this->_getProduct()->getName()), '-', implode('-', $attributeLabels)?>"
                        class="<?php echo $this->getAttributeClassName('name'); ?>"<?php echo $disabled?>/>
                    <input type="hidden" name="variations-matrix[<?php echo $key?>][configurable_attribute]"
                        value="<?php echo $this->escapeHtml($this->helper('Mage_Core_Helper_Data')->jsonEncode($attributeValues)); ?>"<?php echo $disabled?>/>
                </td>
                <td class="associated-matrix-product-price">
                    <?php echo $price ?>
                </td>
                <td class="associated-matrix-product-sku">
                    <input id="variations-matrix-<?php echo $key?>-sku"
                        name="variations-matrix[<?php echo $key?>][sku]"
                        value="<?php echo $this->escapeHtml($this->_getProduct()->getSku()), '-', implode('-', $attributeLabels)?>"
                        class="<?php echo $this->getAttributeClassName('sku'); ?>"<?php echo $disabled?>/>
                    <button class="choose-product"
                        data-attributes="<?php echo $this->escapeHtml($this->helper('Mage_Core_Helper_Data')->jsonEncode($attributeValues)); ?>"
                        style="float:right">
                        Choose
                    </button>
                </td>
                <td class="associated-matrix-product-qty">
                    <input id="variations-matrix-<?php echo $key?>-qty"
                        name="variations-matrix[<?php echo $key?>][quantity_and_stock_status][qty]"
                        class="validate-number"
                        value=""<?php echo $disabled?>>
                </td>
                <td class="associated-matrix-product-weight">
                    <input id="variations-matrix-<?php echo $key?>-weight"
                        name="variations-matrix[<?php echo $key?>][weight]"
                        class="<?php echo $this->getAttributeClassName('weight'); ?>"
                        value="<?php echo $this->_getProduct()->getWeight()?>"<?php echo $disabled?>>
                </td>
                <td><?php echo implode('</td><td>', $attributeLabels)?></td>
                <td class="a-center">
                    <input type="checkbox" name="associated_product_ids[]" value=""
                        class="checkbox associated-matrix-product-id"<?php echo $checked?>>
                </td>
            </tr>
        <?php
        }
        $isEven = !$isEven;
    }
    ?>
    </tbody>
</table>
<?php } ?>