<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Storelauncher_Product_Drawer */
?>
<form action="" id="drawer-form" class="add-product-form" method="post">
    <div class="add-product">
        <h2 class="title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Add a Product') ?></h2>
        <?php  echo $this->getGeneralTabContent();?>
        <?php echo $this->getChildBlock('wysiwyg-editor')->toHtml();?>
        <?php echo $this->getChildBlock('product_edit')->setUseContainer(false)->toHtml();?>
    </div>
    <div class="import-products">
        <h2 class="title"><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Import Products to Catalog') ?></h2>
        <ul class="import-options">
            <li>
                <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Create the relevant product') ?>
                <a target="_blank" href="<?php echo $this->getUrl('adminhtml/catalog_category'); ?>"><?php echo $this->__('categories'); ?></a>
                <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('for your products') ?>
            </li>
            <li>
                <a target="_blank" href="<?php echo $this->getUrl('adminhtml/export'); ?>"><?php echo $this->__('Export the guideline'); ?></a>
                <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('for products') ?>
            </li>
            <li>
                <a target="_blank" href="<?php echo $this->getUrl('adminhtml/import'); ?>"><?php echo $this->__('Import the products'); ?></a>
                <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('to the system') ?>
            </li>
        </ul>
    </div>
</form>
<?php echo $this->getChildBlock('new-category')->toHtml(); ?>
<script type="text/javascript">
jQuery(function ($) {
    'use strict';
    var drawer = $('#drawer');

    $('#image-container').baseImage();
    $('#media_gallery_content').productGallery({'template': '#media_gallery_content-template'});

    drawer.bind('drawerClose.drawer', function() {
        drawer.find('.wysiwyg-editor').each(function(index, element) {
            tinyMCE.execCommand('mceRemoveControl', false, $(element).attr('id'));
        });
    });

    drawer.on({
        'drawerBeforeSave.drawer': function() {
            var description = $('#drawer').find('[name="product[description]"]');
            description.val(tinyMCE.get(description.attr('id')).getContent()).trigger('change');
        }
    });

    drawer.on({
        'drawerRefresh.drawer': function() {
            drawer.off('drawerBeforeSave.drawer');
        }
    });
});
</script>
