<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Storelauncher_Product_Tile */
?>
<article class="tile-store-settings tile-product <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>" tabindex="0">
    <h2><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Products') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Add a product or upload your catalog.') ?>
        </p>
        <div class="actions">
            <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/storelauncher_product_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/storelauncher_product_drawer/load') ?>">
                <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Open Products') ?></span>
            </button>
        </div>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Saas_Launcher_Model_Tile::STATE_COMPLETE) : ?>
        <ul class="checklist">
            <li class="completed">
                <?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('You have %s product(s)', $this->getProductCount()); ?>
            </li>
        </ul>
        <div class="actions">
            <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode(); ?>"
                    data-save-url="<?php echo $this->getUrl('*/storelauncher_product_drawer/save'); ?>"
                    data-load-url="<?php echo $this->getUrl('*/storelauncher_product_drawer/load'); ?>">
                <span><?php echo Mage::helper('Saas_Launcher_Helper_Data')->__('Add Products'); ?></span>
            </button>
        </div>
        <footer class="tile-more-info">
            <p class="tile-more-info-label"><?php echo $this->escapeHtml($this->__('Add or manage all your products:')); ?></p>
            <p class="tile-more-info-breadcrumbs">
                <span><?php echo $this->escapeHtml($this->__('Products')); ?></span>
                <span><?php echo $this->escapeHtml($this->__('Inventory')); ?></span>
                <a href="<?php echo $this->getUrl('adminhtml/catalog_product/index'); ?>"><?php echo $this->__('Catalog'); ?></a>.
            </p>
        </footer>
        <?php endif; ?>
    </div>
    <script type="text/javascript">
    jQuery(function ($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.ba-hashchange.min.js') ?>",
            "<?php echo $this->getViewFileUrl('Saas_Launcher::page/launcher.js') ?>",
            function () {
                $('#drawer').drawer();
                $('#drawer').drawer('setDependencies',
                    '<?php echo $this->getTileCode() ?>',
                    [
                        "<?php echo $this->getViewFileUrl('jquery/fileUploader/jquery.iframe-transport.js') ?>",
                        "<?php echo $this->getViewFileUrl('jquery/fileUploader/jquery.fileupload.js') ?>",
                        "<?php echo $this->getViewFileUrl('jquery/fileUploader/load-image.min.js') ?>",
                        "<?php echo $this->getViewFileUrl('jquery/fileUploader/canvas-to-blob.min.js') ?>",
                        "<?php echo $this->getViewFileUrl('jquery/fileUploader/jquery.fileupload-fp.js') ?>",
                        "<?php echo $this->getViewFileUrl('Mage_Adminhtml::catalog/base-image-uploader.js') ?>",
                        "<?php echo $this->getViewFileUrl('jquery/jstree/jquery.hotkeys.js') ?>",
                        "<?php echo $this->getViewFileUrl('jquery/jstree/jquery.jstree.js') ?>",
                        "<?php echo $this->getViewFileUrl('Mage_Adminhtml::catalog/type-switcher.js') ?>",
                        "<?php echo $this->getViewFileUrl('Mage_Catalog::js/product-gallery.js') ?>",
                        "<?php echo $this->getViewFileUrl('mage/adminhtml/browser.js') ?>",
                        "<?php echo $this->getViewFileUrl('mage/proxy-event.js') ?>"
                    ]
                );
            }
        );
    });
    </script>
</article>
