<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="block block-list">
        <div class="block-title">
            <strong><span><?php echo __('New Products') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getPagerHtml() ?>
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol id="widget-new-products-<?php echo $suffix; ?>">
            <?php foreach ($_products->getItems() as $_product): ?>
                <li class="item">
                    <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo Mage::helper('Magento_Catalog_Helper_Output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
                </li>
            <?php endforeach; ?>
            </ol>
            <script type="text/javascript">(function($) {$('#widget-new-products-<?php echo $suffix; ?>').decorate('list', false)})(jQuery)</script>
        </div>
    </div>
</div>
<?php endif; ?>
