<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @see Mage_AdminNotification_Block_Adminhtml_Baseurl
 */
?>
<div class="message message-system">
    <div class="message-inner">
        <div class="message-content">
            <?php echo $this->helper('Mage_Adminhtml_Helper_Data')->__('Your web server is configured incorrectly. As a result, configuration files with sensitive information are accessible from the outside. Please contact your hosting provider.')?>
        </div>
    </div>
</div>
