<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * Create account form template
 *
 * @see \Magento\CustomerCustomAttributes\Block\Form
 */
/* @var $this \Magento\CustomerCustomAttributes\Block\Form */
?>
<?php if ($this->hasUserDefinedAttributes()): ?>
    <?php if ($this->isShowContainer()): ?>
    <fieldset class="fieldset">
    <?php endif;?>
    <?php foreach ($this->getUserDefinedAttributes() as $attribute):?>
        <?php $attributeContent = $this->getAttributeHtml($attribute);?>
        <?php if ($attributeContent): ?>
            <?php echo $attributeContent;?>
        <?php endif;?>
    <?php endforeach;?>
    <?php if ($this->isShowContainer()): ?>
    </fieldset>
    <?php endif;?>
<?php endif; ?>
