<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this Magento_Rma_Block_Order_Button */
?>
<?php if($this->helper('Magento_Rma_Helper_Data')->canCreateRma($this->getOrder())): ?>
    <span class="separator">|</span>
    <a href="<?php echo $this->helper('Magento_Rma_Helper_Data')->getReturnCreateUrl($this->getOrder()) ?>"><?php echo __('Return') ?></a>
<?php endif;?>
