<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $this \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use \Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($this->getCollection()->getSize()): ?>
<div class="toolbar products" data-mage-init='<?php echo $this->getWidgetOptionsJson(); ?>'>
    <?php if ($this->isExpanded()): ?>
    <div class="settings">
        <?php include($this->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php include($this->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
    </div>
    <?php endif; ?>
    <?php echo $this->getPagerHtml() ?>
    <div class="pager">
        <?php include($this->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
        <?php include($this->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
    </div>
</div>
<?php endif ?>
