<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Reports\Block\Product\Compared */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="block compared links">
    <div class="title">
        <strong><?php echo __('Recently Compared Products') ?></strong>
    </div>
    <div class="content">
        <ol class="items compared">
        <?php foreach ($_products as $_item): ?>
            <li class="item">
                <strong class="product name">
                    <a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_item, $_item->getName() , 'name') ?></a>
                </strong>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
