<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->canDisplayGiftWrappingForItem()): ?>
<div class="gift-options-tooltip-content no-display">
    <?php if ($this->getDesign()): ?>
        <div><strong><?php echo $this->helper('Magento_GiftWrapping_Helper_Data')->__('Gift Wrapping Design')?></strong>:</div>
        <div><?php echo $this->getDesign() ?></div>
    <?php endif; ?>
</div>
<?php endif; ?>
