<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo __('My Orders') ?></h1>
</div>
<div class="recent-orders">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('info');?>
    <?php echo $this->getPagerHtml(); ?>
    <?php if($_orders->getSize()): ?>
    <table class="data-table" id="my-orders-table">
        <thead>
            <tr>
                <th><?php echo __('Order #') ?></th>
                <th><?php echo __('Date') ?></th>
                <th><span class="nobr"><?php echo __('Total') ?></span></th>
                <th><span class="nobr"><?php echo __('Status') ?></span></th>
            </tr>
        </thead>
        <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($_orders as $_order): ?>
            <tr>
                <td><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getRealOrderId() ?></a></td>
                <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                <td><em><?php echo $_order->getStatusLabel() ?></em></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
        <p><?php echo __('You have placed no orders.'); ?></p>
    <?php endif ?>
</div>
