<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Template for \Magento\Theme\Block\Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><?php echo __('Magento Installation Wizard') ?></title>

    <link rel="icon" href="<?php echo $this->getViewFileUrl('Magento_Theme::favicon.ico') ?>" type="image/x-icon"/>
    <link rel="shortcut icon" href="<?php echo $this->getViewFileUrl('Magento_Theme::favicon.ico') ?>" type="image/x-icon"/>
    <script src="<?php echo $this->getViewFileUrl('requirejs/require.js') ?>"></script>
    <script src="<?php echo $this->getViewFileUrl('jquery/jquery.js') ?>"></script>
    <script src="<?php echo $this->getViewFileUrl('app-config.js') ?>"></script>

    <link rel="stylesheet" href="<?php echo $this->getViewFileUrl('Magento_Install::css/mage-js-style.css') ?>" type="text/css"
          media="all"/>
    <link rel="stylesheet" href="<?php echo $this->getViewFileUrl('Magento_Install::css/validate.css') ?>" type="text/css"
          media="all"/>
    <link rel="stylesheet" href="<?php echo $this->getViewFileUrl('css/reset.css') ?>" type="text/css" media="all"/>
    <link rel="stylesheet" href="<?php echo $this->getViewFileUrl('css/boxes.css') ?>" type="text/css" media="all"/>
    <link rel="stylesheet" href="<?php echo $this->getViewFileUrl('css/clears.css') ?>" type="text/css" media="all"/>
</head>

<body>
<!-- [start] header -->
    <div class="header">
        <div class="header-top-container">
            <div class="header-top">
                <h1 id="logo">
                    <a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getViewFileUrl('images/logo.gif') ?>" title="<?php echo __('Magento') ?>" alt="<?php echo __('Magento') ?>" /></a>
                </h1>

                <?php echo $this->getChildHtml('topSearch') ?>

                <div class="quick-access">
                    <div class="account-access">
                       <strong>&nbsp;<?php echo $this->getWelcome() ?></strong> <?php echo $this->getChildHtml('topLeftLinks') ?>
                    </div>
                    <div class="shop-access">
                        <?php echo $this->getChildHtml('topRightLinks') ?>
                    </div>
                </div>

            </div>
        </div>
        <?php echo $this->getChildHtml('topMenu') ?>
    </div>
<!-- [end] header -->

        <!-- [start] middle -->
       <?php echo $this->getChildHtml('store') ?>
    <div class="middle-container">
        <div class="middle col-2-left-layout">
            <?php echo $this->getChildHtml('breadcrumbs') ?>

            <!-- [start] left -->
            <div class="col-left side-col">
                <?php echo $this->getChildHtml('left') ?>
            </div>
            <div id="main" class="col-main">
            <!-- [start] global messages -->
                <?php echo $this->getChildHtml('global_messages') ?>
            <!-- [end] global messages -->
            <!-- [start] content -->
                <?php echo $this->getChildHtml('content') ?>
            <!-- [end] content -->
            </div>
        </div>
            <!-- [end] center -->
    </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
    <div class="footer-container">
        <div class="footer">
        <p class="legality">
            <?php echo __('Help Us to Keep Magento Healthy') ?> - <a
            href="https://support.varien.com/"
            target="varien_external"><strong><?php echo __('Report All Bugs') ?></strong></a> <?php echo __('(ver. %1)', \Magento\Framework\AppInterface::VERSION) ?>
            <br/>
            <?php echo $this->getChildHtml('copyright');?>
        </p>
        </div>
    </div>
        <!-- [end] footer -->
    </body>
</html>
