<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Cookie settings initialization script
 *
 * @see Mage_Page_Block_Js_Cookie
 */
?>

<script type="text/javascript">
    //<![CDATA[
    (function($) {
        head.js("<?php echo $this->getSkinUrl('jquery/jquery.cookie.js') ?>",
            "<?php echo $this->getSkinUrl('Mage_Page::js/cookie.js') ?>", function() {
                $.mage.cookieInit({
                    path: '<?php echo $this->getPath()?>',
                    domain: '<?php echo $this->getDomain()?>'
                });
            });
    })(jQuery);
    //]]>
</script>
