<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * Template for displaying product price at catalog and sidebars
 *
 * @var $this \Magento\Catalog\Block\Product\Price
 */
?>
<?php
    /** @var $_product \Magento\Catalog\Model\Product */
    $_product = $this->getProduct();
    $_msrpPrice = "";
    $priceElementIdPrefix = $this->getPriceElementIdPrefix() ? $this->getPriceElementIdPrefix() : 'product-price-';
    $priceElementId = $priceElementIdPrefix . $_product->getId() . $this->getIdSuffix();
?>
    <div class="price-box map info">
    <?php $_price = $this->helper('Magento\Tax\Helper\Data')->getPrice($_product, $_product->getMsrp()) ?>
        <?php if ($_product->getMsrp()): ?>
            <?php $_msrpPrice = $this->helper('Magento\Core\Helper\Data')->currency($_product->getMsrp(),true,true) ?>
            <span class="old price" id="product-price-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>"><?php echo $_msrpPrice ?></span>
        <?php endif; ?>
        <?php $popupId = 'msrp-click-' . $_product->getId() . $this->getRandomString(20); ?>
        <?php if ($this->helper('Magento\Catalog\Helper\Data')->isShowPriceOnGesture($_product)): ?>
            <a href="#"
               id="<?php echo($popupId); ?>"
               data-mage-init='{"addToCart":{"popupId": "#<?php echo($popupId); ?>",
                                             "productName": "<?php echo $_product->getName() ?>",
                                             "realPrice": <?php echo $this->getRealPriceJs($_product) ?>,
                                             "msrpPrice": "<?php echo $_msrpPrice ?>",
                                             "priceElementId":"<?php echo $priceElementId ?>",
                                             "popupCartButtonId": "#map-popup-button",
                                             "addToCartUrl": "<?php echo $this->getAddToCartUrl($_product) ?>"}}'><?php echo __('Click for price') ?>
            </a>
        <?php else: ?>
            <a href="#" id="<?php echo($popupId);?>" data-mage-init='{"addToCart":{"popupId": "#<?php echo($popupId);?>", "submitUrl": "<?php echo $_product->getProductUrl() ?>"}}'><?php echo __('Click for price') ?></a>
        <?php endif; ?>
    </div>
