<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * Template for displaying product price at product view page, gift registry and wishlist
 *
 * @var $this Magento_Catalog_Block_Product_Price
 */
?>
<?php
/** @var $_coreHelper Magento_Core_Helper_Data */
$_coreHelper = $this->helper('Magento_Core_Helper_Data');
/** @var $_catalogHelper Magento_Catalog_Helper_Data */
$_catalogHelper = $this->helper('Magento_Catalog_Helper_Data');

/** @var $_product Magento_Catalog_Model_Product */
$_product = $this->getProduct();
$_id = $_product->getId();
$_msrpPrice = '';
$priceElementIdPrefix = $this->getPriceElementIdPrefix() ? $this->getPriceElementIdPrefix() : 'product-price-';
?>
<div class="price-box map-info">
    <?php $_price = $this->helper('Magento_Tax_Helper_Data')->getPrice($_product, $_product->getMsrp()) ?>
    <?php if ($_product->getMsrp()): ?>
    <?php $_msrpPrice = $_coreHelper->currency($_product->getMsrp(), true, true) ?>
    <span class="old-price"><?php echo $_msrpPrice ?></span>
    <?php endif; ?>

    <?php if ($_catalogHelper->isShowPriceOnGesture($_product)): ?>
    <?php $priceElementId = $priceElementIdPrefix . $_id . $this->getIdSuffix(); ?>
    <span id="<?php echo $priceElementId ?>" style="display:none"></span>
    <?php $popupId = 'msrp-popup-' . $_id . $_coreHelper->getRandomString(20); ?>
    <a href="#" id="<?php echo($popupId);?>"><?php echo __('Click for price'); ?></a>

    <?php else: ?>
    <span class="msrp-price-hide-message">
         <?php echo $_catalogHelper->getMsrpPriceMessage($_product) ?>
    </span>
    <?php endif; ?>

    <?php $helpLinkId = 'msrp-help-' . $_id . $_coreHelper->getRandomString(20); ?>
    <a href="#" id="<?php echo($helpLinkId);?>"><?php echo __("What's this?"); ?></a>
</div>

<script type="text/javascript">
    //<![CDATA[
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/msrp.js') ?>",
            function () {
            <?php if ($this->helper('Magento_Catalog_Helper_Data')->isShowPriceOnGesture($_product)): ?>
                $('#<?php echo($popupId);?>').addToCart({
                    cartForm: "#product_addtocart_form",
                    popupId: "#<?php echo($popupId);?>",
                    productName: '<?php echo $_product->getName() ?>',
                    realPrice: '<?php echo $this->getRealPriceJs($_product) ?>',
                    msrpPrice: '<?php echo $_msrpPrice ?>',
                    priceElementId: '<?php echo $priceElementId ?>',
                    closeButtonId: '#map-popup-close',
                    popupCartButtonId: "#map-popup-button"
                });
            <?php endif; ?>
                $("#<?php echo($helpLinkId);?>").addToCart({
                    helpLinkId: "#<?php echo($helpLinkId);?>",
                    productName: '<?php echo $_product->getName() ?>'
                });
            });
    })(jQuery);
    //]]>
</script>


