<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if($this->getCount()): ?>
<div class="box-collateral box-tags">
    <div class="box-title">
        <h2><?php echo __('Product Tags'); ?></h2>
    </div>
    <?php echo $this->getChildHtml('list_before')?>
    <div class="box-content">
        <ul id="<?php echo $this->getUniqueHtmlId('tags-list_'); ?>" class="tags-list">
            <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
        </ul>
    </div>
</div>
<?php endif; ?>
