<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Api2
 * @copyright  {copyright}
 * @license    {license_link}
 */

/**
 * API2 Abstarct Validator
 *
 * This is an object to which we encapsulate all business logic of validation and different invariants.
 * But instead of different validators, we group all logic in one class but in different methods.
 *
 * If fails validation, then validation method returns false, and
 * getErrors() will return an array of errors that explain why the
 * validation failed.
 *
 * @category   Mage
 * @package    Mage_Api2
 * @author     Magento Core Team <core@magentocommerce.com>
 */
abstract class Mage_Api2_Model_Resource_Validator
{
    /**
     * Array of validation failure errors.
     *
     * @var array
     */
    protected $_errors = array();

    /**
     * List of fields that already have related error messages.
     * Can be used to prevent similar error messages for the same field generated by independent validators
     *
     * @var array
     */
    protected $_invalidFields = array();

    /**
     * Set an array of errors
     *
     * @param array $data
     * @return Mage_Api2_Model_Resource_Validator
     */
    protected function _setErrors(array $data)
    {
        $this->_errors = array_values($data);
        return $this;
    }

    /**
     * Add errors
     *
     * @param array $errors
     * @return Mage_Api2_Model_Resource_Validator
     */
    protected function _addErrors($errors)
    {
        foreach ($errors as $error) {
            $this->_addError($error);
        }
        return $this;
    }

    /**
     * Add error
     *
     * @param string $error
     * @return Mage_Api2_Model_Resource_Validator
     */
    protected function _addError($error)
    {
        $this->_errors[] = $error;
        return $this;
    }

    /**
     * Check if validation failed or not
     *
     * @return bool
     */
    public function isValid()
    {
        return empty($this->_errors);
    }

    /**
     * Returns an array of errors that explain why the most recent isValidData()
     * call returned false. The array keys are validation failure error identifiers,
     * and the array values are the corresponding human-readable error strings.
     *
     * If isValidData() was never called or if the most recent isValidData() call
     * returned true, then this method returns an empty array.
     *
     * @return array
     */
    public function getErrors()
    {
        return $this->_errors;
    }

    /**
     * Mark field as invalid
     *
     * @param string $field
     */
    protected function _addInvalidField($field)
    {
        $this->_invalidFields[] = $field;
    }

    /**
     * Check if some validation of $field has already failed
     *
     * @param string $field
     * @return bool
     */
    protected function _isFieldInvalid($field)
    {
        return in_array($field, $this->_invalidFields);
    }

    /**
     * Throw API2 validation exception
     *
     * @param string $message
     * @throws Mage_Api2_Model_Resource_Validator_Exception
     */
    protected function _critical($message)
    {
        throw new Mage_Api2_Model_Resource_Validator_Exception($message);
    }
}
