<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Toolbar_Buttons */ ?>
<div id="vde_toolbar_buttons" <?php echo $this->getUiId()?>>
    <a href="<?php echo $this->getViewLayoutUrl(); ?>" title="<?php echo $this->__('View Layout'); ?>" class="vde_button view-layout">
        <?php echo $this->__('View Layout'); ?>
    </a>
    <a href="<?php echo $this->getBackUrl(); ?>" title="<?php echo $this->__('Back'); ?>" class="vde_button">
        <?php echo $this->__('Back'); ?>
    </a>
</div>
