<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Toolbar_Buttons */ ?>
<div id="vde_toolbar_buttons" <?php echo $this->getUiId()?>>
    <?php echo $this->getAssignButtonHtml(); ?>
    <a href="#" onclick="window.close();" title="<?php echo $this->__('Quit'); ?>" class="vde_button">
        <?php echo $this->__('Quit'); ?>
    </a>
</div>

<script type="text/javascript">
    (function($) {
        $(document).ready(function() {
            $.vde.themeSelector.prototype.assignSaveThemeSuccess = function (response) {
                if (response.error) {
                    alert($.mage.__('Error') + ': "' + response.message + '".');
                }
            };
        });
    })(jQuery);
</script>
