<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $_categories = $this->getRssCatalogFeeds();
    $_misc = $this->getRssMiscFeeds();
?>
<?php if ($_categories || $_misc): ?>
<?php if($_misc): ?>
<table class="data table rss">
    <thead>
        <tr>
            <th colspan="2"><?php echo __('Miscellaneous Feeds') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_misc as $_feed): ?>
        <tr>
            <td class="col feed"><?php echo $_feed->getLabel() ?></td>
            <td class="col action"><a href="<?php echo $_feed->getUrl() ?>" class="action get"><span><?php echo __('Get Feed'); ?></span></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
<?php if($_categories): ?>
<table class="data table category rss">
    <thead>
        <tr>
            <th colspan="2"><?php echo __('Category Feeds') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_categories as $_category): ?>
        <tr>
            <td class="col feed"><?php echo $this->escapeHtml($_category->getLabel()) ?></td>
            <td class="col action"><a href="<?php echo $_category->getUrl() ?>" class="action get"><span><?php echo __('Get Feed'); ?></span></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
<?php else: ?>
    <p><?php echo __('There are no Rss Feeds.'); ?></p>
<?php endif; ?>
