<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Shipping_Tile */
?>
<article class="tile-store-settings tile-shipping <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>" tabindex="0">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Shipping') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Choose Flat Rate, No Shipping or from one of the many shipping vendors that Magento supports') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode() ?>"
                data-save-url="<?php echo $this->getUrl('*/storelauncher_shipping_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/storelauncher_shipping_drawer/load') ?>">
            <span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Confirm Info') ?></span>
        </button>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <p><strong><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('You have set up Shipping') ?></strong></p>
        <?php $configuredMethods = $this->getConfiguredShippingMethods(); ?>
        <?php if (!empty($configuredMethods)) :?>
            <p><strong><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Next shipping methods have been configured:') ?></strong></p>
            <ul class="configured-shipping-methods">
                <?php foreach ($configuredMethods as $shippingCode => $shippingName): ?>
                    <li class="configured-shipping-methods-<?php echo $shippingCode; ?>"><?php echo $this->escapeHtml($shippingName); ?></li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p><strong><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('No Shipping') ?></strong></p>
        <?php endif; ?>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/storelauncher_shipping_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/storelauncher_shipping_drawer/load') ?>">
            <span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Edit Shipping') ?></span>
        </button>
        <p>
            <a href="<?php echo $this->getUrl('adminhtml/system_config/edit', array('section' => 'carriers')); ?>"><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Set Up More Shipping Options') ?></a>
        </p>
        <?php endif; ?>
    </div>
</article>
