<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table cellspacing="0" class="data-table" id="super-product-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php if ($this->getItems()->getSize()): ?>
    <?php foreach ($this->getItems() as $_item): ?>
        <tr>
            <td><?php echo $_item->getName() ?></td>
            <td><?php echo $_item->getSku() ?></td>
            <td class="a-right"><?php echo $_item->getFormatedPrice() ?></td>
            <td class="a-center"><input type="text" class="input-text qty" name="super_group[<?php echo $_item->getLinkedProductId() ?>]" value="<?php echo $this->filterQty($_item->getQty()) ?>"/></td>
        </tr>
    <?php endforeach; ?>
    <?php else: ?>
       <tr>
           <td colspan="4"><?php echo $this->__('No options of this product are available.') ?></td>
       </tr>
    <?php endif; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('super-product-table')</script>
