<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($_products = $this->getProducts()): ?>
<p><?php echo __('You are receiving this notification because you subscribed to receive alerts when the prices for the following products changed:') ?></p>
<table>
<?php foreach ($_products as $_product): ?>
    <tr>
        <td><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><img src="<?php echo $_product->getThumbnailUrl() ?>" border="0" align="left" height="75" width="75" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" /></a></td>
        <td>
            <p><a href="<?php echo $_product->getProductUrl() ?>"><strong><?php echo $this->escapeHtml($_product->getName()) ?></strong></a></p>
            <?php if ($shortDescription = $this->escapeHtml($_product->getShortDescription())): ?>
            <p><small><?php echo $shortDescription ?></small></p>
            <?php endif; ?>
            <p><?php if ($_product->getPrice() != $_product->getFinalPrice()): ?>
                <?php echo __('Regular Price:') ?> <strong style="text-decoration:line-through;"><?php echo $this->helper('Magento_Core_Helper_Data')->currency($_product->getPrice()) ?></strong><br />
                <strong><?php echo __('Special price:') ?> <span style="color:#FF0000;"><?php echo $this->helper('Magento_Core_Helper_Data')->currency($_product->getFinalPrice()) ?></span></strong>
            <?php else: ?>
                <strong><?php echo __('Price:') ?></strong> <?php echo $this->helper('Magento_Core_Helper_Data')->currency($_product->getPrice()) ?>
            <?php endif; ?></p>
            <p><small><a href="<?php echo $this->getProductUnsubscribeUrl($_product->getId()) ?>"><?php echo __('Click here not to receive alerts for this product.') ?></a></small></p>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<p><a href="<?php echo $this->getUnsubscribeUrl() ?>"><?php echo __('Unsubscribe from all price alerts') ?></a></p>
<?php endif; ?>
