<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('Mage_Catalog_Helper_Output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('Mage_Catalog::js/price-option.js') ?>", function () {
            $('#product_addtocart_form').priceOption({"priceConfig":<?php echo $this->getJsonConfig() ?>});
        });
    })(jQuery);
</script>
<div class="product add form">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?php echo $this->getChildHtml('form_top'); ?>
        <?php if (!$this->hasOptions()):?>
            <?php echo $this->getChildHtml('product_info_form_content'); ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $this->getOptionsContainer() == 'container1'):?>
                <?php echo $this->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getOptionsContainer() == 'container2'):?>
            <?php echo $this->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?php echo $this->getChildHtml('form_bottom'); ?>
    </form>
</div>
