<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_product = $this->getProduct() ?>
<?php if ($this->canEmailToFriend()): ?>
    <a title="<?php echo $this->__('Email to a Friend') ?>" class="action mailto" href="<?php echo $this->helper('Mage_Catalog_Helper_Product')->getEmailToFriendUrl($_product) ?>">
        <span><?php echo $this->__('Email to a Friend') ?></span>
    </a>
<?php endif; ?>
