<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this Mage_Catalog_Block_Product_View_Options */
?>

<?php $_options = Mage::helper('Mage_Core_Helper_Data')->decorateArray($this->getOptions()) ?>
<?php if (count($_options)):?>
    <script type="text/javascript">
        (function ($) {
            head.js("<?php echo $this->getViewFileUrl('Mage_Catalog::js/price-option.js') ?>", function () {
                $('#product_addtocart_form').priceOption({'optionConfig':<?php echo $this->getJsonConfig()?>}).trigger('reloadPrice');
            });
        })(jQuery);
    </script>
    <?php foreach($_options as $_option): ?>
        <?php echo $this->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>
