<?php if ($this->getPreviewScreen() == 1): ?>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/mobile-home.css" media="all" />
<div class="main-block" style="background: <?php echo $this->getData('conf/body/backgroundColor'); ?>;">
	<div class="top-header" style="background: #000;">
		<div class="volume" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/1.gif') bottom left no-repeat;"></div>		
		<div class="header-sign-1">Carrier</div>		
		<div class="antenna" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/3.gif') bottom right no-repeat;"></div>
		<div class="time"><?php echo date('g:i A') ?></div>
		<div class="battery" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/2.gif') bottom right no-repeat;"></div>
	</div>
	<div class="main-header"  style="background: <?php echo $this->getData('conf/navigationBar/tintColor'); ?>;  color: #f3f3f3;">
		<div class="info"><img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/info.png" width="20" height="20" alt="" /></div>
		<div class="logo-small">
			<img src="<?php echo $this->getData('conf/navigationBar/icon'); ?>" alt="" >
		</div>
		<div class="login-btn">
			<div class="login-left">&nbsp;</div>
			<div class="login-body"><span>Log In</span></div>
			<div class="login-right">&nbsp;</div>
		</div>
	</div>
	<div class="clearB"></div>
	<div class="big-logo" style="background: <?php echo $this->getData('conf/body/backgroundColor'); ?>;">
		<img src="<?php echo $this->getData('conf/body/bannerImage'); ?>" />
	</div>
	<div class="catalog" style="background: #<?php echo $this->getData('conf/body/backgroundColor'); ?>">
		<div class="item">
			<div class="item-image" style="background: <?php echo $this->getData('conf/categoryItem/backgroundColor'); ?>">
				<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/men.png" width="63" height="74" alt="" />
			</div>
			<div class="item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title9/size'); ?>px <?php echo $this->getData('conf/fonts/Title9/name'); ?> Helvetica Arial; 	color:<?php echo $this->getData('conf/fonts/Title9/color'); ?>; background: <?php echo $this->getData('conf/categoryItem/tintColor'); ?>;">
				<div style="background: url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/imageFrame.php?color=<?php echo substr($this->getData('conf/body/backgroundColor'),1); ?>') no-repeat; height: 18px; padding-top: 3px;">
					MEN
				</div>							
			</div>
		</div>
		<div class="item">
			<div class="item-image" style="background: <?php echo $this->getData('conf/categoryItem/backgroundColor'); ?>">
				<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/women.png" width="63" height="74" alt="" />
			</div>
			<div class="item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title9/size'); ?>px <?php echo $this->getData('conf/fonts/Title9/name'); ?> Helvetica Arial; 	color:<?php echo $this->getData('conf/fonts/Title9/color'); ?>; background: <?php echo $this->getData('conf/categoryItem/tintColor'); ?>;">
				<div style="background: url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/imageFrame.php?color=<?php echo substr($this->getData('conf/body/backgroundColor'),1); ?>') no-repeat; height: 18px; padding-top: 3px;">
					WOMEN
				</div>							
			</div>
		</div>
		<div class="item">
			<div class="item-image" style="background: <?php echo $this->getData('conf/categoryItem/backgroundColor'); ?>">
				<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/youth.png" style=-moz-opacity:0.6" width="63" height="74" alt="" />
			</div>
			<div class="item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title9/size'); ?>px <?php echo $this->getData('conf/fonts/Title9/name'); ?> Helvetica Arial; 	color:<?php echo $this->getData('conf/fonts/Title9/color'); ?>; background: <?php echo $this->getData('conf/categoryItem/tintColor'); ?>;">
				<div style="background: url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/imageFrame.php?color=<?php echo substr($this->getData('conf/body/backgroundColor'),1); ?>') no-repeat; height: 18px; padding-top: 3px;">
					YOUTH
				</div>							
			</div>
		</div>
	</div>
    <div class="clearB"></div>
	<div class="bottom-buttons"  style="background: #363d40;">
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Home/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Home/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Shop/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Shop/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Search/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Search/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Cart/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Cart/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Account/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Account/label'); ?></p>
		</div>	
	</div>
</div>
<?php else: ?>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/mobile-catalog.css" />
<div class="main-block" style="background: #000;">
	<div class="top-header" style="background: #000;">
		<div class="volume" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/1.gif') bottom left no-repeat;"></div>		
		<div class="header-sign-1">Carrier</div>		
		<div class="antenna" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/3.gif') bottom right no-repeat;"></div>
		<div class="time"><?php echo date('g:i A') ?></div>
		<div class="battery" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/2.gif') bottom right no-repeat;"></div>
	</div>
	<div class="main-header"  style="background: <?php echo $this->getData('conf/navigationBar/tintColor'); ?>;">
		<div class="btn-l"><div class="btn-txt">Back</div></div>
		<div class="main-header-text">
		
			    <img src="<?php echo $this->getData('conf/navigationBar/icon'); ?>" style="margin-top: 10px"/>
				<span class="title" style="font: bold <?php echo $this->getData('conf/fonts/Title1/size'); ?>px <?php echo $this->getData('conf/fonts/Title1/name'); ?> Helvetica Arial; color: #e9e9e9; padding-left: 10px">T-Shirt</span>
		</div>
		<div class="btn-r"><div class="btn-txt">Edit Filter</div></div>
	</div>
	<div class="filter-header" style="background: <?php echo $this->getData('conf/appliedFilters/backgroundColor'); ?>;">
		<div style="background: url('<?php echo $this->getData('conf/appliedFilters/backgroundImage'); ?>') center center no-repeat; width: 320px;height: 100%;">
	        <div class="filter-lines">&nbsp;</div>
			<div class="filter-applied" style="font: bold 13px arial; color: #e9e9e9;">
				<span class="filter-circle" style="width: 30px">&nbsp;&nbsp;3&nbsp;&nbsp;</span>
				<span class="filter-text">FILTERS APPLIED</span>
			</div>
		</div>	
	</div>
	<div class="sort-block" style="background: <?php echo $this->getData('conf/body/primaryColor'); ?>;">
		<div class="sort-block-inner" style="background: <?php echo $this->getData('conf/body/primaryColor'); ?>;">
			<div class="sort-block-inner-txt" style="font: bold <?php echo $this->getData('conf/fonts/Title3/size'); ?>px <?php echo $this->getData('conf/fonts/Title3/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title3/color'); ?>;">
				SORT BY:
			</div>
			<div  style="float: left;">
				<table class="sort-buttons" style="background:  url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/buttons.php?color=<?php echo substr($this->getData('conf/itemActions/relatedProductBackgroundColor'),1); ?>') center center no-repeat; width: 234px; height: 25px; margin-top: 10px">
					<tr>
						<td style="background: url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/grid.png') center center repeat-x;" width="64px">
							<b>Price</b>
						</td>
						<td><b>Reviews</b></td>
						<td><b>Popularity</b></td>
					</tr>
				</table>	
			</div>
		</div>
	</div>	
	<div class="items-list" style="background: <?php echo $this->getData('conf/body/backgroundColor'); ?>">
		<div class="item" style="background:  <?php echo $this->getData('conf/body/primaryColor'); ?>">
			<div class="lines-v" >&nbsp;</div>
			<div class="item-image"><img width="72" height="72" src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/t-shirt.gif"  /></div>
			<div class="item-info">
				<div class="item-title" style="font: bold <?php echo $this->getData('conf/fonts/Title2/size'); ?>px <?php echo $this->getData('conf/fonts/Title2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title2/color'); ?>;">Product Name Goes Here</div>
				<div class="item-price-block">
					<span class="item-price" style="font: bold <?php echo $this->getData('conf/fonts/Title5/size'); ?>px <?php echo $this->getData('conf/fonts/Title5/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title5/color'); ?>;">$39.99</span>
					<span class="item-status" style="font: bold <?php echo $this->getData('conf/fonts/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/Text2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Text2/color'); ?>;">In Stock</span>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">			
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="13" height="13"/>
				</div>
				<span style="font: bold <?php echo $this->getData('conf/fonts/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/Text2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Text2/color'); ?>;">(4)</span>
			</div>
			<div class="arrow">&nbsp;</div>
		</div>
		<div class="item" style="background:  <?php echo $this->getData('conf/body/primaryColor'); ?>">
			<div class="lines-v" >&nbsp;</div>
			<div class="item-image"><img width="72" height="72" src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/t-shirt.gif"  /></div>
			<div class="item-info">
				<div class="item-title" style="font: bold <?php echo $this->getData('conf/fonts/Title2/size'); ?>px <?php echo $this->getData('conf/fonts/Title2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title2/color'); ?>;">Product Name Goes Here</div>
				<div class="item-price-block">
					<span class="item-price" style="font: bold <?php echo $this->getData('conf/fonts/Title5/size'); ?>px <?php echo $this->getData('conf/fonts/Title5/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title5/color'); ?>;">$39.99</span>
					<span class="item-status" style="font: bold <?php echo $this->getData('conf/fonts/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/Text2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Text2/color'); ?>;">In Stock</span>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">			
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="13" height="13"/>
				</div>
				<span style="font: bold <?php echo $this->getData('conf/fonts/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/Text2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Text2/color'); ?>;">(4)</span>
			</div>
			<div class="arrow">&nbsp;</div>
		</div>
		<div class="slider-item" style="display: table; width: 320px; height: 91px; background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>">
	    		<div class="slider-item">      				
			        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/viewGallery.png"  class="slider-image"/>
			        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/Title8/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title8/color'); ?>;" class="slider-item-text" >
						View Gallery
					</div>
	    		</div>
	    		<div class="slider-item"">      				
			        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/tellAFriend.png" class="slider-image"/>
			        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/Title8/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title8/color'); ?>;" class="slider-item-text" >
						Tell a Friend
					</div>
	    		</div>
	    		<div class="slider-item">      				
			        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/addToWishlist.png" class="slider-image"/>
			        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/Title8/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title8/color'); ?>;" class="slider-item-text" >
						Add to Wishlist
					</div>
	    		</div>
	    		<div class="slider-item">      				
			        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/addToCart.png" class="slider-image"/>
			        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/Title8/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title8/color'); ?>;" class="slider-item-text" >
						Add to Cart
					</div>
	    		</div>
	    		<div class="slider-item">      				
			        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/viewDetails.png" class="slider-image"/>
			        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/Title8/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title8/color'); ?>;" class="slider-item-text" >
						View Details
					</div>
	    		</div>
		</div>	
		<br clear="all"/>
		<div class="item" style="background:  <?php echo $this->getData('conf/body/primaryColor'); ?>">
			<div class="lines-v" >&nbsp;</div>
			<div class="item-image"><img width="72" height="72" src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/t-shirt.gif"  /></div>
			<div class="item-info">
				<div class="item-title" style="font: bold <?php echo $this->getData('conf/fonts/Title2/size'); ?>px <?php echo $this->getData('conf/fonts/Title2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title2/color'); ?>;">Product Name Goes Here</div>
				<div class="item-price-block">
					<span class="item-price" style="font: bold <?php echo $this->getData('conf/fonts/Title5/size'); ?>px <?php echo $this->getData('conf/fonts/Title5/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Title5/color'); ?>;">$39.99</span>
					<span class="item-status" style="font: bold <?php echo $this->getData('conf/fonts/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/Text2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Text2/color'); ?>;">In Stock</span>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">					
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="14" height="13" style="background: <?php echo $this->getData('conf/itemActions/relatedProductBackgroundColor'); ?>;"/>
				</div>
				<div class="item-rate">			
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/lightStar.php?color=<?php echo substr($this->getData('conf/body/primaryColor'),1); ?>" width="13" height="13"/>
				</div>
				<span style="font: bold <?php echo $this->getData('conf/fonts/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/Text2/name'); ?> Helvetica Arial; color: <?php echo $this->getData('conf/fonts/Text2/color'); ?>;">(4)</span>
			</div>
			<div class="arrow">&nbsp;</div>
		</div>
	</div>
</div>
<div class="bottom-buttons"  style="background: #363d40;">
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Home/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Home/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Shop/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Shop/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Search/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Search/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Cart/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Cart/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Account/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Account/label'); ?></p>
		</div>	
</div>
<?php endif; ?>
