<?php if ($this->getPreviewScreen() == 1): ?>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/mobile-home.css" media="all" />
<div class="main-block" style="background: #000;">
	<div class="top-header" style="background: #000;">
		<div class="volume" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/1.gif') bottom left no-repeat;"></div>		
		<div class="header-sign-1">Carrier</div>		
		<div class="antenna" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/3.gif') bottom right no-repeat;"></div>
		<div class="time"><?php echo $this->getData('conf/Time'); ?></div>
		<div class="battery" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/2.gif') bottom right no-repeat;"></div>
	</div>
	<div class="clearB"></div>
	<div class="main-header"  style="background: <?php echo $this->getData('conf/navigationBar/tintColor'); ?>;  color: #f3f3f3;">
		<div class="info"><img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/info.png" width="20" height="20" alt="" /></div>
		<div class="logo-small">
			<img src="<?php echo $this->getData('conf/navigationBar/icon'); ?>" height="30" alt="" >
		</div>
		<div class="login-btn">
			<div class="login-left">&nbsp;</div>
			<div class="login-body"><span>Log In</span></div>
			<div class="login-right">&nbsp;</div>
		</div>
	</div>
	<div class="clearB"></div>
	<div class="big-logo" style="background: #2b434e;">
		<img src="<?php echo $this->getData('conf/body/bannerImage'); ?>" />
	</div>
	<div class="catalog" style="background: #f3f3f3">
		<div class="item">
			<div class="item-image" style="background: <?php echo $this->getData('conf/categoryItem/backgroundColor'); ?>">
				<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/men.png" width="63" height="74" alt="" />
			</div>
			<div class="item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title9/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title9/name'); ?>; 	color:<?php echo $this->getData('conf/fonts/font/Title9/color'); ?>; background: <?php echo $this->getData('conf/categoryItem/tintColor'); ?>">MEN</div>
		</div>
		<div class="item">
			<div class="item-image" style="background: <?php echo $this->getData('conf/categoryItem/backgroundColor'); ?>">
				<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/women.png" width="63" height="74" alt="" />
			</div>
			<div class="item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title9/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title9/name'); ?>; 	color:<?php echo $this->getData('conf/fonts/font/Title9/color'); ?>; background: <?php echo $this->getData('conf/categoryItem/tintColor'); ?>">WOMEN</div>
		</div>
		<div class="item">
			<div class="item-image" style="background: <?php echo $this->getData('conf/categoryItem/backgroundColor'); ?>">
				<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/youth.png" style=-moz-opacity:0.6" width="63" height="74" alt="" />
			</div>
			<div class="item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title9/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title9/name'); ?>; 	color:<?php echo $this->getData('conf/fonts/font/Title9/color'); ?>; background: <?php echo $this->getData('conf/categoryItem/tintColor'); ?>">YOUTH</div>
		</div>
	</div>
    <div class="clearB"></div>
	<div class="bottom-buttons" style="background: #363d40;">
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/home.png') top center no-repeat;">
			<p>Home</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/page.png') top center no-repeat;">
			<p>Shop</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/search.png') top center no-repeat;">
			<p>Search</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/more.png') top center no-repeat;">
			<p>Cart</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/account.png') top center no-repeat;">
			<p>Account</p>
		</div>	
	</div>
	<!--<div class="bottom-buttons"  style="background: #363d40;">
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Home/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Home/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('[tabBar-tab-About Us-image]') top center no-repeat;">
			<p>[tabBar-tab-About Us-label]</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Search/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Home/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Cart/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Cart/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Account/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Account/label'); ?></p>
		</div>	
	</div>-->
</div>
<?php else: ?>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/mobile-catalog.css" />
<div class="main-block" style="background: #000;">
	<div class="top-header" style="background: #000;">
		<div class="volume" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/1.gif') bottom left no-repeat;"></div>		
		<div class="header-sign-1">Carrier</div>		
		<div class="antenna" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/3.gif') bottom right no-repeat;"></div>
		<div class="time"><?php echo $this->getData('conf/Time'); ?></div>
		<div class="battery" style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/2.gif') bottom right no-repeat;"></div>
	</div>
	<div class="clearB"></div>
	<div class="main-header"  style="display: table; width: 100%; background: <?php echo $this->getData('conf/navigationBar/tintColor'); ?>;  color: #f3f3f3;">
		<div class="btn-l" style="display: table-cell;  align: center; vertical-align: middle; width: 85px"><div class="btn-txt">Back</div></div>
		<span class="main-header-text" style="display: table-cell;  vertical-align: middle;">
			<img src="<?php echo $this->getData('conf/navigationBar/icon'); ?>" height="30" />
			<span class="title" style="font: bold <?php echo $this->getData('conf/fonts/font/Title1/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title1/name'); ?>; color: #e9e9e9;">T-Shirt</span>
		</span>
		<div class="btn-r" style="display: table-cell; align: center; vertical-align: middle; width: 92px"><div class="btn-txt">Edit Filter</div></div>
	</div>
	<div class="clearB"></div>
	<div class="filter-header" style="background: <?php echo $this->getData('conf/appliedFilters/backgroundColor'); ?>;">
		<div style="background: url('<?php echo $this->getData('conf/appliedFilters/backgroundImage'); ?>') center center no-repeat; width: 320px;height: 100%;">
	        <div class="filter-lines">&nbsp;</div>
			<div class="filter-applied" style="font: bold 13px arial; color: #e9e9e9;">
				<span class="filter-circle" style="width: 30px">&nbsp;&nbsp;3&nbsp;&nbsp;</span>
				<span class="filter-text">FILTERS APPLIED</span>
			</div>
		</div>	
	</div>
	<div class="clearB"></div>
	<div class="sort-block" style="background: #fefefe;">
		<div class="sort-block-inner">
			<div class="sort-block-inner-txt" style="font: bold <?php echo $this->getData('conf/fonts/font/Title2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title2/color'); ?>;">
				SORT BY:
			</div>
			<div class="sort-buttons">
				<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/sort-buttons/buttons.gif" width="234" height="25" />
			</div>
		</div>
	</div>	
	<div class="items-list" style="background: <?php echo $this->getData('conf/body/backgroundColor'); ?>">
		<div class="item" style="background:url('<?php echo $this->getData('conf/body/backgroundColor'); ?>') center center no-repeat;">
			<div class="lines-v" >&nbsp;</div>
			<div class="item-image"><img width="72" height="72" src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/t-shirt.gif"  /></div>
			<div class="item-info">
				<div class="item-title" style="font: bold <?php echo $this->getData('conf/fonts/font/Title2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title2/color'); ?>;">Product Name Goes Here</div>
				<div class="item-price-block">
					<span class="item-price" style="font: bold <?php echo $this->getData('conf/fonts/font/Title5/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title5/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title5/color'); ?>;">$39.99</span>
					<span class="item-status" style="font: bold <?php echo $this->getData('conf/fonts/font/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Text2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Text2/color'); ?>;">In Stock</span>
				</div>
				<div class="item-rate">
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-inactive.png" width="13" height="13"/>
					<span style="font: bold <?php echo $this->getData('conf/fonts/font/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Text2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Text2/color'); ?>;">(4)</span>
				</div>
			</div>
			<div class="arrow">&nbsp;</div>
		</div>
		<div class="item" style="background:url('<?php echo $this->getData('conf/body/backgroundColor'); ?>') center center no-repeat;">
			<div class="lines-v" >&nbsp;</div>
			<div class="item-image"><img width="72" height="72" src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/t-shirt.gif"  /></div>
			<div class="item-info">
				<div class="item-title" style="font: bold <?php echo $this->getData('conf/fonts/font/Title2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title2/color'); ?>;">Product Name Goes Here</div>
				<div class="item-price-block">
					<span class="item-price" style="font: bold <?php echo $this->getData('conf/fonts/font/Title5/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title5/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title5/color'); ?>;">$39.99</span>
					<span class="item-status" style="font: bold <?php echo $this->getData('conf/fonts/font/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Text2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Text2/color'); ?>;">In Stock</span>
				</div>
				<div class="item-rate">
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-inactive.png" width="13" height="13"/>
					<span style="font: bold <?php echo $this->getData('conf/fonts/font/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Text2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Text2/color'); ?>;">(4)</span>
				</div>
			</div>
			<div class="arrow">&nbsp;</div>
		</div>
		<div class="slider-item" style="display: table; width: 320px; height: 91px; background:url('<?php echo $this->getData('conf/itemActions/backgroundImage'); ?>') center center no-repeat;">
    		<div style="display: table-cell; vertical-align: middle;">      				
		        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/viewGallery.png"/>
		        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title8/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title8/color'); ?>;" class="slider-item-text" >
					View Gallery
				</div>
    		</div>
    		<div style="display: table-cell; vertical-align: middle;">      				
		        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/tellAFriend.png"/>
		        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title8/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title8/color'); ?>;" class="slider-item-text" >
					Tell a Friend
				</div>
    		</div>
    		<div style="display: table-cell; vertical-align: middle;">      				
		        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/addToWishlist.png"/>
		        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title8/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title8/color'); ?>;" class="slider-item-text" >
					Add to Wishlist
				</div>
    		</div>
    		<div style="display: table-cell; vertical-align: middle;">      				
		        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/addToCart.png"/>
		        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title8/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title8/color'); ?>;" class="slider-item-text" >
					Add to Cart
				</div>
    		</div>
    		<div style="display: table-cell; vertical-align: middle;">      				
		        <img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/slider/viewDetails.png"/>
		        <div class="slider-item-text" style="font: bold <?php echo $this->getData('conf/fonts/font/Title8/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title8/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title8/color'); ?>;" class="slider-item-text" >
					View Details
				</div>
    		</div>
		</div>	
		<br clear="all"/>
		<div class="item" style="background:url('<?php echo $this->getData('conf/body/backgroundColor'); ?>') center center no-repeat;">
			<div class="lines-v" >&nbsp;</div>
			<div class="item-image"><img width="72" height="72" src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/t-shirt.gif"  /></div>
			<div class="item-info">
				<div class="item-title" style="font: bold <?php echo $this->getData('conf/fonts/font/Title2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title2/color'); ?>;">Product Name Goes Here</div>
				<div class="item-price-block">
					<span class="item-price" style="font: bold <?php echo $this->getData('conf/fonts/font/Title5/size'); ?>px <?php echo $this->getData('conf/fonts/font/Title5/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Title5/color'); ?>;">$39.99</span>
					<span class="item-status" style="font: bold <?php echo $this->getData('conf/fonts/font/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Text2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Text2/color'); ?>;">In Stock</span>
				</div>
				<div class="item-rate">
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-active.png" width="13" height="13"/>
					<img src="<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/star-inactive.png" width="13" height="13"/>
					<span style="font: bold <?php echo $this->getData('conf/fonts/font/Text2/size'); ?>px <?php echo $this->getData('conf/fonts/font/Text2/name'); ?>; color: <?php echo $this->getData('conf/fonts/font/Text2/color'); ?>;">(4)</span>
				</div>
			</div>
			<div class="arrow">&nbsp;</div>
		</div>
	</div>
    <div class="clearB"></div>
	<div class="bottom-buttons" style="background: #363d40;">
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/home.png') top center no-repeat;">
			<p>Home</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/page.png') top center no-repeat;">
			<p>Shop</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/search.png') top center no-repeat;">
			<p>Search</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/more.png') top center no-repeat;">
			<p>Cart</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo Mage::getBaseUrl('skin') ?>xmlconnect/mobile-preview/icons/account.png') top center no-repeat;">
			<p>Account</p>
		</div>	
	</div>
	<!--<div class="bottom-buttons"  style="background: #363d40;">
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Home/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Home/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('[tabBar-tab-About Us-image]') top center no-repeat;">
			<p>[tabBar-tab-About Us-label]</p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Search/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Home/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Cart/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Cart/label'); ?></p>
		</div>
		<div class="bottom-button"	style="background:url('<?php echo $this->getData('conf/tabBar/tab/Account/image'); ?>') top center no-repeat;">
			<p><?php echo $this->getData('conf/tabBar/tab/Account/label'); ?></p>
		</div>	
	</div>-->
</div>
</div>
<?php endif; ?>
