<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */

/**
 * Catalog Event category page
 *
 * @see \Magento\CatalogEvent\Block\Event\Lister
 */
?>
<div id="<?php echo $this->getHtmlId(); ?>" data-mage-init='{"carousel":{"pageSize": <?php echo $this->getPageSize(); ?>,scrollSize: <?php echo $this->getScrollSize() ?> }}'
     class="events-slider"<?php if ($this->hasWidth()): ?> style="width:<?php echo (int)$this->getWidth()?>px !important;" <?php endif;?>>
    <div data-slide-button="slide-button" class="slide-button backward">&laquo;</div>
    <div data-slider-panel="slider-panel"
         class="slider-panel"<?php if ($this->hasWidth()): ?> style="width:<?php echo (int)$this->getWidth()?>px !important;" <?php endif;?>>
        <ul data-slider="slider" class="slider">
            <?php foreach ($this->getEvents() as $_event): ?>
                <?php $_category = $_event->getCategory(); ?>
                <li data-slider-item="slider-item" class="slider-item">
                    <div class="event <?php echo $_event->getStatus()?>">
                        <strong class="status">
                            <?php echo $this->getStatusText($_event); ?>
                        </strong>
                        <?php switch ($_event->getStatus()):
                            case 'upcoming': ?>
                                <div class="event-dates">
                                    <p class="start">
                                        <strong class="date-part"><?php echo $this->getEventDate('start', $_event); ?></strong>
                                        <span class="time-part"><?php echo $this->getEventTime('start', $_event, 'hh a zzz'); ?></span>
                                    </p>
                                    <p class="end">
                                        <span class="delimiter-part">-</span>
                                        <strong class="date-part"><?php echo $this->getEventDate('end', $_event); ?></strong>
                                        <span class="time-part"><?php echo $this->getEventTime('end', $_event, 'hh a zzz'); ?></span>
                                    </p>
                                </div>
                                <a class="event-button button" href="<?php echo $this->getCategoryUrl($_category); ?>"><span><?php echo __('Preview Sale') ?></span></a>


                                <?php break;
                            case 'open': ?>
                                <div class="event-ticker" id="<?php echo $this->getHtmlId(); ?>-event-ticker-<?php echo $_event->getId()?>" data-mage-init='{"ticker":{"secondsToClose": <?php echo $this->getSecondsToClose($_event); ?>}}'>
                                    <div class="container">
                                        <span data-container="days" class="days">00</span><span data-container="delimiter" class="delimiter">:</span><span data-container="hour" class="hour">00</span><span data-container="delimiter" class="delimiter">:</span><span data-container="minute" class="minute">00</span><span data-container="delimiter" class="delimiter">:</span><span data-container="second" class="second">00</span>
                                    </div>
                                </div>
                                <a class="event-button button" href="<?php echo $this->getCategoryUrl($_category); ?>"><span><?php echo __('Go To Sale') ?></span></a>


                                <?php break;
                            case 'closed': ?>
                                <div class="event-dates">
                                    <p class="start">
                                        <strong class="date-part"><?php echo $this->getEventDate('start', $_event); ?></strong>
                                        <span class="time-part"><?php echo $this->getEventTime('start', $_event, 'hh a zzz'); ?></span>
                                    </p>
                                    <p class="end">
                                        <span class="delimiter-part">-</span>
                                        <strong class="date-part"><?php echo $this->getEventDate('end', $_event); ?></strong>
                                        <span class="time-part"><?php echo $this->getEventTime('end', $_event, 'hh a zzz'); ?></span>
                                    </p>
                                </div>
                                <a class="event-button" href="<?php echo $this->getCategoryUrl($_category); ?>"><span><?php echo __('View Sale') ?></span></a>


                                <?php break; ?>
                            <?php endswitch; ?>
                        <div class="event-bottom"></div>
                    </div>
                    <div class="category-info">
                        <a class="category-show" href="<?php echo $this->getCategoryUrl($_category); ?>" title="<?php echo $this->escapeHtml($_category->getName()) ?>">
                            <?php if ($this->getEventImageUrl($_event)): ?>
                                <img src="<?php echo $this->getEventImageUrl($_event); ?>" title="<?php echo $this->escapeHtml($_category->getName()) ?>" alt="<?php echo $this->escapeHtml($_category->getName()) ?>" />
                            <?php else: ?>
                                <span class="category-name"><?php echo $this->escapeHtml($_category->getName()) ?></span>
                            <?php endif; ?>
                        </a>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div data-slide-button="slide-button" class="slide-button inactive forward">&raquo;</div>
</div>
