<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_product = $this->getProduct() ?>
<?php $_finalPrice = $_product->getFinalPrice() ?>
<?php $_finalPriceInclTax = $_product->getFinalPrice() ?>
<?php $_weeeTaxAmount = 0; ?>
<?php
if ($_product->getPriceType() == 1) {
    $_weeeTaxAmount = Mage::helper('Magento_Weee_Helper_Data')->getAmount($_product);
    if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, array(1,2,4))) {
        $_weeeTaxAttributes = Mage::helper('Magento_Weee_Helper_Data')->getProductWeeeAttributesForDisplay($_product);
    }
}
$isMAPTypeOnGesture = Mage::helper('Magento_Catalog_Helper_Data')->isShowPriceOnGesture($_product);
$canApplyMAP  = Mage::helper('Magento_Catalog_Helper_Data')->canApplyMsrp($_product);
?>
<?php if ($_product->getCanShowPrice() !== false):?>
<div class="price-box">
    <p class="price-as-configured">
        <span class="price-label"><?php echo __('Price as configured') ?>:</span>
        <?php if (!$this->getWithoutPrice()): ?>
        <span<?php if (!$isMAPTypeOnGesture && $canApplyMAP): ?> style="display:none"<?php endif ?> class="full-product-price">
        <?php if ($this->helper('Magento_Tax_Helper_Data')->displayBothPrices()): ?>
        <span class="price-tax">
            <span class="price-excluding-tax">
                <span class="label"><?php echo __('Excl. Tax:') ?></span>
                <span class="price" id="price-excluding-tax-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>">
                <?php if (!$canApplyMAP): ?>
                    <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_finalPrice,true,false) ?>
                <?php endif ?>
                </span>
            </span>
            <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                <span class="weee">(<small>
                    <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                        <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, array(2, 4))): ?>
                            <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                        <?php else: ?>
                            <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                        <?php endif; ?>

                        <?php echo $_weeeSeparator; ?>
                        <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($amount, true, true); ?>
                        <?php $_weeeSeparator = ' + '; ?>
                    <?php endforeach; ?>
                </small>)</span>
            <?php endif; ?>
            <span class="price-including-tax">
                <span class="label"><?php echo __('Incl. Tax:') ?></span>
                <span class="price" id="price-including-tax-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>">
                <?php if (!$canApplyMAP): ?>
                    <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_finalPriceInclTax,true,false) ?>
                <?php endif ?>
                </span>
            </span>
        </span>
        <?php else: ?>
        <span class="price" id="product-price-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>">
            <?php if (!$canApplyMAP): ?>
                <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_finalPrice,true,false) ?>
            <?php endif ?>
        </span>
        <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
            <span class="weee">(<small>
                <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                    <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, array(2, 4))): ?>
                        <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                    <?php else: ?>
                        <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                    <?php endif; ?>

                    <?php echo $_weeeSeparator; ?>
                    <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($amount, true, true); ?>
                    <?php $_weeeSeparator = ' + '; ?>
                <?php endforeach; ?>
            </small>)</span>
        <?php endif; ?>
    <?php endif; ?>
    </span>
    <?php endif ?>
    </p>
</div>
<?php endif; ?>
