<div data-m2-init='{"Magento_Ui/js/grid/listing/component": ""}'>
    <script type="mage/config">
            {                    
                "config": {
                    "namespace": "cms.pages",

                    "client": {
                        "root": "sad"
                    }
                },
                
                "meta": {
                    "fields": [
                        {
                            "title": "Title",
                            "id": "title",
                            "sortable": true,
                            "filterable": true,
                            "filter_type": "input",
                            "input_type": "input",
                            "data_type": "text"
                        },
                        {
                            "title": "URL Key",
                            "id": "url",
                            "sortable": true,
                            "filter_type": "input",
                            "input_type": "input",
                            "data_type": "text"
                        },
                        {
                            "title": "Layout",
                            "id": "layout",
                            "sortable": true,
                            "filter_type": "select",
                            "input_type": "select",
                            "data_type": "text",
                            "options": [
                                { "0": "1 column" },
                                { "1": "2 columns with left bar" },
                                { "2": "2 columns with right bar" },
                                { "3": "3 columns" },
                                { "4": "Empty" }
                            ]
                        },
                        {
                            "title": "Store View",
                            "id": "store_id",
                            "sortable": true,
                            "filter_type": "select",
                            "input_type": "select",
                            "data_type": "text"
                        },
                        {
                            "title": "Status",
                            "id": "status",
                            "sortable": true,
                            "filter_type": "select",
                            "input_type": "select",
                            "data_type": "boolean",
                            "options": [
                                { "0": "Disabled" },
                                { "1": "Enabled" }
                            ]
                        },
                        {
                            "title": "Created",
                            "id": "Created",
                            "sortable": true,
                            "filter_type": "date",
                            "input_type": "date",
                            "data_type": "text"
                        },
                        {
                            "title": "Modified",
                            "id": "modified",
                            "sortable": true,
                            "filter_type": "date",
                            "input_type": "date",
                            "data_type": "text"
                        },
                        {
                            "title": "Action",
                            "id": "action",
                            "data_type": "text",
                            "filterable": false
                        }
                    ]
                },

                "data": {

                    "items": [
                        {
                            "id": "0",
                            "title": "UPDATED Enable Cookies",
                            "url": "enable-cookies",
                            "layout": "1 column",
                            "store_id": "All Store Views",
                            "status": "Disabled",
                            "created": "Aug 8, 2014 1:48:32 AM",
                            "modified": "Aug 8, 2014 1:48:32 AM",
                            "action": {
                                "href": "/enable-cookies/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "1",
                            "title": "UPDATED Home page",
                            "url": "home",
                            "layout": "1 column",
                            "store_id": "All Store Views",
                            "status": "Disabled",
                            "created": "Aug 8, 2014 1:48:32 AM",
                            "modified": "Aug 8, 2014 1:48:32 AM",
                            "action": {
                                "href": "/home/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "2",
                            "title": "404 Not Found 1",
                            "url": "no-route",
                            "layout": "2 columns right",
                            "store_id": "All Store Views",
                            "status": "Disabled",
                            "created": "Aug 8, 2014 1:48:32 AM",
                            "modified": "Aug 8, 2014 1:48:32 AM",
                            "action": {
                                "href": "/no-route/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "3",
                            "title": "UPDATED Privacy Policy",
                            "url": "privacy-policy-cookie-restriction-mode",
                            "layout": "1 column",
                            "store_id": "All Store Views",
                            "status": "Disabled",
                            "created": "Aug 8, 2014 1:48:32 AM",
                            "modified": "Aug 8, 2014 1:48:32 AM",
                            "action": {
                                "href": "/privacy-policy-cookie-restriction-mode/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "4",
                            "title": "NEW Another Page",
                            "url": "privacy-policy-cookie-restriction-mode",
                            "layout": "2 columns right",
                            "store_id": "All Store Views",
                            "status": "Disabled",
                            "created": "Aug 8, 2014 1:48:32 AM",
                            "modified": "Aug 8, 2014 1:48:32 AM",
                            "action": {
                                "href": "/privacy-policy-cookie-restriction-mode/?___store=default",
                                "title": "Preview"
                            }
                        }
                    ],

                    "pages": 8,

                    "totalCount": 38
                }
            }
    </script>
</div>
<div data-m2-init='{"Magento_Ui/js/grid/paging" : ""}'>
    <script type="mage/config">
       {   
            "config": {
                "namespace": "cms.pages",
                
                "sizes": [5, 10, 20, 30, 50, 100, 200],
                
                "params": {
                    "pageSize": 5,
                
                    "current": 1
                }
            }
        }
    </script>
</div>
<div data-m2-init='{"Magento_Ui/js/grid/sorting": ""}'>
    <script type="mage/config">
       {   
            "config": {
                "namespace": "cms.pages",

                "params": {

                    "direction": "desc",
                    
                    "field": "url"   
                }
            }
        }
    </script>
</div>
<div data-m2-init='{"Magento_Ui/js/grid/filter": ""}'>
    <script type="mage/config">
        {   
            "config": {
                "namespace": "cms.pages"
            }
        }
    </script>
</div>

<div class="grid">
    <div data-bind="scope: 'cms.pages:paging'" class="pager">
        <!-- ko template: 'Magento_Ui.templates.pagination.toolbar' --><!-- /ko -->
    </div>
    <div data-bind="scope: 'cms.pages:filter'">
        <!-- ko template: 'Magento_Ui.templates.filter' --><!-- /ko -->
    </div>
    <div data-bind="scope: 'cms.pages:listing'">
        <!-- ko template: 'Magento_Ui.templates.listing.grid' --><!-- /ko -->
        <!-- ko template: 'Magento_Ui.templates.loader' --><!-- /ko -->
    </div>
</div>
