<div data-m2-init='{"m2/listing/component": ""}'>
  <h1>Listing</h1>

  <script type="mage/initial">
    {
      "items": [
        {
          "title": "Enable Cookies",
          "url": "enable-cookies",
          "layout": "1 column",
          "store_id": "all",
          "status": true,
          "created": "03/04/2014",
          "modified": "03/04/2014",
          "action": {
            "type": "href",
            "template": "preview"
          }
        },
        {
          "title": "Bla Cookies",
          "url": "yo-cookies",
          "layout": "2 column",
          "store_id": "all",
          "status": false,
          "created": "04/04/2014",
          "modified": "04/04/2014",
          "action": {
            "type": "href",
            "template": "preview"
          }
        }
      ]
    }
  </script>
</div>