<div data-m2-init='{"Magento_Ui/js/grid/listing/component": ""}'>
    <script type="mage/config" data-role="Magento_Ui/js/grid/listing/component">
            {                    
                "config": {
                    "namespace": "cms.pages",

                    "client": {
                        "api": {
                            "read": "path/to/read",
                            "update": "path/to/update",
                            "delete": "path/to/delete"
                        },

                        "useAjax": true
                    }
                },
                
                "meta": {
                    "fields": [
                        {
                            "title": "Title",
                            "id": "title"
                        },
                        {
                            "title": "URL Key",
                            "id": "url"
                        },
                        {
                            "title": "Layout",
                            "id": "layout"
                        },
                        {
                            "title": "Store View",
                            "id": "store_id"
                        },
                        {
                            "title": "Status",
                            "id": "status"
                        },
                        {
                            "title": "Created",
                            "id": "Created"
                        },
                        {
                            "title": "Modified",
                            "id": "modified"
                        },
                        {
                            "title": "Action",
                            "id": "action"
                        }
                    ]
                },

                "data": {

                    "items": [
                        {
                            "id": "0",
                            "title": "UPDATED Enable Cookies",
                            "url": "enable-cookies",
                            "layout": "1 column",
                            "store_id": "All Store Views",
                            "status": true,
                            "created": 1407758413000,
                            "modified": 1407758413000,
                            "action": {
                                "href": "/enable-cookies/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "1",
                            "title": "UPDATED Home page",
                            "url": "home",
                            "layout": "1 column",
                            "store_id": "All Store Views",
                            "status": false,
                            "created": 1407848473000,
                            "modified": 1407848473000,
                            "action": {
                                "href": "/home/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "2",
                            "title": "404 Not Found 1",
                            "url": "no-route",
                            "layout": "2 columns right",
                            "store_id": "All Store Views",
                            "status": false,
                            "created": 1407848473000,
                            "modified": 1407848473000,
                            "action": {
                                "href": "/no-route/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "3",
                            "title": "UPDATED Privacy Policy",
                            "url": "privacy-policy-cookie-restriction-mode",
                            "layout": "1 column",
                            "store_id": "All Store Views",
                            "status": true,
                            "created": 1407848473000,
                            "modified": 1407848473000,
                            "action": {
                                "href": "/privacy-policy-cookie-restriction-mode/?___store=default",
                                "title": "Preview"
                            }
                        },
                        {
                            "id": "4",
                            "title": "NEW Another Page",
                            "url": "privacy-policy-cookie-restriction-mode",
                            "layout": "2 columns right",
                            "store_id": "All Store Views",
                            "status": true,
                            "created": 1407848473000,
                            "modified": 1407848473000,
                            "action": {
                                "href": "/privacy-policy-cookie-restriction-mode/?___store=default",
                                "title": "Preview"
                            }
                        }
                    ],

                    "pages": 8,

                    "totalCount": 38
                }
            }
        </script>
</div>
<div data-m2-init='{"Magento_Ui/js/grid/paging/component" : ""}'>
    <script type="mage/config" data-role="Magento_Ui/js/grid/paging/component">
       {   
            "config": {
                "namespace": "cms.pages",
                
                "sizes": [5, 10, 20, 30, 50, 100, 200],
                
                "size": 5,
                
                "current": 1
            }
        }
    </script>
</div>

<div class="grid">
    <div data-bind="scope: 'cms.pages:listing'">
        <!-- ko template: 'Magento_Cms.templates.grid' --><!-- /ko -->
        <!-- ko template: 'Magento_Cms.templates.loader' --><!-- /ko -->
    </div>
    <div data-bind="scope: 'cms.pages:paging'" class="pager">
        <!-- ko template: 'Magento_Ui.templates.pagination.toolbar' --><!-- /ko -->
    </div>
</div>