<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>

<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getGiftCardsAmount()): ?>
    <tr>
        <td class="label">
            <?php echo __('Gift Cards') ?>
        </td>
        <td>
            <?php echo $this->displayPrices(-$_source->getBaseGiftCardsAmount(), -$_source->getGiftCardsAmount()); ?>
        </td>
    </tr>
<?php endif; ?>
