<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\PayPal\Block\Express\Form
 * @see \Magento\PayPal\Block\Standard\Form
 */
?>
<div class="paypal choice field items" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <p><?php echo $this->getRedirectMessage(); ?></p>
    <?php $code = $this->getBillingAgreementcode(); ?>
    <?php if ($code): ?>
        <input type="checkbox" id="<?php echo $code ?>" value="1" name="payment[<?php echo $code ?>]" class="checkbox">
        <label for="<?php echo $code ?>" class="label">
            <span><?php echo __('Sign a billing agreement to streamline further purchases with PayPal.') ?></span>
        </label>
    <?php endif; ?>
</div>
