<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this Enterprise_CustomerSegment_Block_Adminhtml_Report_Customer_Segment_Detail
 */
?>
<div class="page-actions">
    <?php echo $this->getButtonsHtml() ?>
</div>

<?php echo $this->getGridHtml() ?>

<script type="text/javascript">
    function setFilterValue(obj) {
        <?php echo $this->getChildBlock('grid')->getJsObjectName() ?>.addVarToUrl("website_ids", obj);
    }

    function refreshValues(obj) {
        var elements = $('websites').select('input');
        var serialized = Form.serializeElements(elements, true);
        if (!serialized.website_ids) {
            serialized.website_ids = [];
        }
        setFilterValue(serialized.website_ids);
    }
</script>

<?php if ($websites = $this->getWebsites()): ?>
    <div class="fieldset-wrapper">
        <div class="fieldset-wrapper-title">
            <span class="title"><?php echo __('Website Filter values') ?></span>
        </div>
        <ul id="websites" class="filter-segments">
            <?php foreach ($websites as $website): ?>
                <li>
                    <input type="checkbox" id="website_<?php echo $website->getId() ?>" name="website_ids" value="<?php echo $website->getId() ?>" onchange="return refreshValues(this)" />
                    <label for="website_<?php echo $website->getId() ?>"><?php echo $website->getName() ?></label>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
