<?php echo $this->doctype(); ?>

<html lang="en" ng-app="magentoSetup">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headTitle($this->translate('Magento Setup Tool'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/pub/bootstrap/bootstrap.min.css') ?>

    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/pub/angular/angular.js')
        ->appendFile($this->basePath() . '/pub/angular-ui-router/angular-ui-router.min.js')
        ->appendFile($this->basePath() . '/pub/magento/setup/app.js');
    ?>

</head>
<body>
<div class="container">
    <?php echo $this->content; ?>

</div>
</body>
</html>
