<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var Magento_Page_Block_Html_Header $this
 */
?>
<?php $_cartItems = Mage::helper('Magento_Checkout_Helper_Cart')->getSummaryCount(); ?>
<div class="header-bg">
    <a class="header-logo" href="<?php echo $this->getUrl('') ?>"></a>
</div>
<header>
    <div class="menu-wrapper">
        <dl id="menu">
            <dt class="menu dropdown"><a href="#">Menu</a></dt>
            <dd class="menu-box">
                <?php echo $this->getChildHtml('topLinks') ?>
                <?php echo $this->getChildHtml('checkoutLinks') ?>
                <?php echo $this->getChildHtml('accountLinks') ?>
            </dd>
            <dt class="cart-icon <?php echo $this->getInCart() ? 'active' : '' ?>">
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>">Cart</a>
                <?php echo $_cartItems > 0 ? '<span>'.$_cartItems.'</span>' : ''; ?>
            </dt>
            <dd></dd>
        </dl>
        <div class="search"><?php echo $this->getChildHtml('topSearch') ?></div>
    </div>
</header>
<?php echo $this->getChildHtml('topCart') ?>
