<script type="text/javascript">
var Review = Class.create();
Review.prototype = {
    initialize: function(){
        this.onSave = this.nextStep.bindAsEventListener(this);
    },
    
    save: function(){
        var request = new Ajax.Request(
            '<?=$baseSecureUrl?>checkout/onepage/saveOrder/',
            {
                method:'post',
                parameters:{save:true},
                onSuccess: this.onSave
            }
        );
    },

    nextStep: function(transport){
        if (transport && transport.responseText) {
            try{
                responce = eval('(' + transport.responseText + ')');
            }
            catch (e) { 
                responce = {};
            }
            if (responce.success) {
                window.location='<?=$baseUrl?>checkout/onepage/success/';
            }
            else{
                alert('error');
            }
        }
    }
}
</script>

<div class="step-body" id="co-review-cont">
    <div id="checkout-review-load" class="default-box">
        <?=$this->getChildHtml('reviewInformation')?>
    </div>
    
    <div class="note-box">
        <a href="javascript:checkout.back();" class="float-left">&laquo; Back</a>
			<a href="javascript:review.save();" class="float-right"><img src="<?=$baseSkinUrl?>images/btn_submit_order.gif" alt="Continue"/></a>
        <div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var review = new Review();
</script>
