<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>
<?php if ($this->getInList()): ?>
    <li data-block="minicart" class="minicart wrapper">
<?php else:  ?>
    <div data-block="minicart" class="minicart wrapper">
<?php endif; ?>
<?php $_cartQty = $this->getSummaryCount() ?>
<?php if (!$this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()): ?>
    <a data-toggle="dropdown" class="action showcart" href="<?php echo $this->getUrl('checkout/cart'); ?>">
        <span class="text"><?php echo $this->__('My Cart'); ?></span>
        <span class="qty<?php echo ($_cartQty > 0) ? '' : ' empty'; ?>">
            <?php echo $_cartQty ?>
        </span>
    </a>
    <div data-target="dropdown" class="block minicart<?php echo ($_cartQty > 0) ? '' : ' empty'; ?>">
        <button title="<?php echo $this->__('Close'); ?>" type="button" class="action close" data-toggle="dropdown">
            <span><?php echo $this->__('Close'); ?></span>
        </button>
        <div class="title">
            <strong>
                <span class="text"><?php echo $this->__('My Cart'); ?></span>
                <span title="<?php echo $this->__('Items in Cart'); ?>" class="qty<?php echo ($_cartQty > 0) ? '' : ' empty'; ?>">
                    <?php echo $_cartQty ?>
                </span>
            </strong>
        </div>
        <div class="content">
            <?php $_items = $this->getRecentItems() ?>
            <?php if (count($_items)): ?>
                <strong class="subtitle"><?php echo $this->__('Recently added item(s)') ?></strong>
                <div data-action="scroll" class="products minilist">
                    <ol id="mini-cart" class="minilist items">
                        <?php foreach ($_items as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
            <?php else: ?>
                <strong class="subtitle empty">
                    <?php echo $this->__('You have no items in your shopping cart.') ?>
                </strong>
                <?php if ($this->getCartEmptyMessage()): ?>
                    <p class="minicart empty text"><?php echo $this->getCartEmptyMessage(); ?></p>
                <?php endif; ?>
            <?php endif ?>

            <?php if ($_cartQty || $this->getAllowCartLink()): ?>
                <?php $isPossibleOnepageCheckout = $_cartQty && $this->isPossibleOnepageCheckout() ?>
                <?php if ($isPossibleOnepageCheckout): ?>
                    <div class="subtotal">
                        <?php if ($this->canApplyMsrp()): ?>
                        <span class="mark msrp">
                            <?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?>
                        </span>
                        <?php else: ?>
                            <span class="mark">
                                <?php echo $this->__('Cart Subtotal') ?>
                            </span>
                            <div class="amount">
                                <?php echo Mage::helper('Mage_Checkout_Helper_Data')->formatPrice($this->getSubtotal()) ?>
                                <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                                    <span class="amount incl tax">
                                        <?php echo Mage::helper('Mage_Checkout_Helper_Data')->formatPrice($_subtotalInclTax) ?>
                                        <?php echo Mage::helper('Mage_Tax_Helper_Data')->getIncExcText(true) ?>
                                    </span>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php endif ?>
                <?php echo $this->getChildHtml('minicart_info') ?>
                <div class="actions">
                    <div class="primary">
                        <?php if ($isPossibleOnepageCheckout): ?>
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <button id="top-cart-btn-checkout" type="button" class="action checkout" title="<?php echo $this->__('Checkout') ?>">
                                <span><?php echo $this->__('Checkout') ?></span>
                            </button>
                        <?php endif; ?>
                    </div>
                    <div class="secondary">
                        <a class="action viewcart" href="<?php echo $this->getUrl('checkout/cart'); ?>">
                            <span><?php echo $this->__('View cart') ?></span>
                        </a>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('Mage_Checkout::js/sidebar.js') ?>", function() {
                $('[data-block="minicart"]').sidebar({
                    checkoutUrl: '<?php echo $this->getCheckoutUrl();?>',
                    checkoutButton: '#top-cart-btn-checkout',
                    removeButton: '#mini-cart a.action.delete',
                    confirmMessage: '<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>'
                });
            });
    })(jQuery);
</script>
<?php if ($this->getInList()): ?>
    </li>
<?php else:  ?>
    </div>
<?php endif; ?>

<?php /*
<div class="minicart wrapper">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <?php if ($_cartQty > 0): ?>
    <?php $_myCart = $this->__('My Cart %s)', '<span class="qty">' . $_cartQty . '</span>') ?>
    <?php else: ?>
    <?php $_myCart = $this->__('My Cart %s', '<span class="qty empty">0</span>') ?>
    <?php endif ?>
    <?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()): ?>
        <a class="action showcart" href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $_myCart ?></a>
    <?php else: ?>
    <div class="block-title<?php if (!$_cartQty) {
        echo (' no-items');
    } ?>">
        <strong id="cartHeader"><?php echo $_myCart ?></strong>
    </div>
    <div id="topCartContent" class="block-content" style="display:none">
        <div class="inner-wrapper"><?php // extra div to smooth slideUp and slideDown ?>
            <?php $_items = $this->getRecentItems() ?>
            <?php if (count($_items)): ?>
                <p class="block-subtitle">
                    <span class="close-btn"><?php echo $this->__('Close'); ?></span>
                    <?php echo $this->__('Recently added item(s)') ?>
                </p>
                <ol id="mini-cart" class="mini-products-list">
                    <?php foreach ($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach; ?>
                </ol>

                <?php else: ?>
                <p class="block-subtitle">
                    <span class="close-btn"><?php echo $this->__('Close'); ?></span>
                    <?php echo $this->__('Recently added item(s)') ?>
                </p>
                <p class="cart-empty">
                    <?php echo $this->__('You have no items in your shopping cart.') ?>
                </p>
                <?php if ($this->getCartEmptyMessage()): ?>
                    <p class="cart-empty cart-empty-message"><?php echo $this->getCartEmptyMessage(); ?></p>
                    <?php endif; ?>
            <?php endif ?>
            <?php if ($_cartQty || $this->getAllowCartLink()): ?>
                <?php $isPossibleOnepageCheckout = $_cartQty && $this->isPossibleOnepageCheckout() ?>
                <?php if ($isPossibleOnepageCheckout): ?>
                    <p class="subtotal">
                        <?php if ($this->canApplyMsrp()): ?>
                        <span
                            class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                        <?php else: ?>
                        <span
                            class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('Mage_Checkout_Helper_Data')->formatPrice($this->getSubtotal()) ?><?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                            / <?php echo Mage::helper('Mage_Checkout_Helper_Data')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('Mage_Tax_Helper_Data')->getIncExcText(true) ?><?php endif; ?>
                        <?php endif; ?>
                    </p>
                    <?php endif ?>
                <div class="actions">
                    <?php if ($isPossibleOnepageCheckout): ?>
                    <?php echo $this->getChildHtml('extra_actions') ?>
                    <button id="top-cart-btn-checkout" class="button" type="button" title="<?php echo $this->__('Checkout') ?>">
                        <span><span><?php echo $this->__('Checkout') ?></span></span></button>
                    <?php endif ?>
                    <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('Go to Shopping Cart') ?></span></a>
                </div>
            <?php endif ?>
        </div>
    </div>
    <script type="text/javascript">
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('Mage_Checkout::js/sidebar.js') ?>",
                "<?php echo $this->getViewFileUrl('Mage_Checkout::js/checkout-topcart.js') ?>", function() {
                    $('#mini-cart').sidebar({
                        checkoutUrl: '<?php echo $this->getCheckoutUrl();?>',
                        checkoutButton: '#top-cart-btn-checkout',
                        removeButton: 'a[title=\'' + '<?php echo $this->__('Remove item')?>' + '\']',
                        confirmMessage: '<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>'
                    });
                    $('#topCartContent').topCart({closeSelector: '.close-btn'});
                });
        })(jQuery);
    </script>
    <?php endif;?>
</div>
*/ ?>
