<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="cart empty">
    <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php echo __('You have no items in your shopping cart.') ?></p>
    <p><?php echo __('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
</div>
