<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="" id="co-payment-form" class="form payments">
    <fieldset class="fieldset">
        <?php echo $this->getChildChildHtml('methods_additional') ?>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
    <?php echo $this->getChildChildHtml('additional') ?>
    <div class="buttons-set actions" id="payment-buttons-container">
        <div class="primary">
            <button type="button" class="button action continue"><span><?php echo $this->__('Continue') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="#"><span><?php echo $this->__('Back') ?></span></a>
        </div>
        <span id="payment-please-wait" class="please-wait" style="display:none">
            <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
