<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>

    <h4 class="icon-head head-edit-form"><?php echo $this->__("Maintainers") ?></h4>
    <fieldset id="maintainers_fieldset">
        <legend><?php echo $this->__("Maintainers") ?></legend>
        <table class="table-editable" cellspacing="0">
            <thead>
                <tr>
                    <th><?php echo $this->__("Level") ?></th>
                    <th><?php echo $this->__("Name") ?></th>
                    <th><?php echo $this->__("User") ?></th>
                    <th><?php echo $this->__("Email") ?></th>
                    <th><?php echo $this->__("Status") ?></th>
                    <th>&nbsp;</th>
                </tr>
                <tr id="maintainers_template" style="display:none">
<?php function showMaintainersTemplate($self, $_i=0) { ?>
                    <td class="field-row">
                        <select name="maintainers[role][]">
                        <?php foreach ($self->getMaintainerRoles() as $_value=>$_label): ?>
                            <option value="<?php echo $_value ?>" <?php echo $self->getSelected('maintainers/role/'.$_i, $_value) ?>><?php echo $_label ?></option>
                        <?php endforeach ?>
                        </select>
                    </td><td class="field-row">
                        <input class="input-text" style="width:150px;" name="maintainers[name][]" value="<?php echo $self->getValue('maintainers/name/'.$_i) ?>"/>
                    </td><td class="field-row">
                        <input class="input-text" style="width:100px;" name="maintainers[handle][]" value="<?php echo $self->getValue('maintainers/handle/'.$_i) ?>"/>
                    </td><td class="field-row">
                        <input class="input-text" style="width:150px;" name="maintainers[email][]" value="<?php echo $self->getValue('maintainers/email/'.$_i) ?>"/>
                    </td><td class="field-row">
                        <select name="maintainers[active][]"/>
                            <option value="1" <?php echo $self->getSelected('maintainers/active/'.$_i, 1) ?>><?php echo $self->__("Active") ?></option>
                            <option value="0" <?php echo $self->getSelected('maintainers/active/'.$_i, 0) ?>><?php echo $self->__("Inactive") ?></option>
                        </select>
                    </td><td class="field-row">
                        <?php echo $self->getRemoveRowButtonHtml('tr') ?>
                    </td>
<?} ?>
<?showMaintainersTemplate($this) ?>
                </tr>
            </thead>
            <tbody id="maintainers_container">
            <?php if ($this->getData('maintainers/role')): ?>
            <?php foreach ($this->getData('maintainers/role') as $_i=>$_dbField): ?>
                <?php if (0===$_i) continue; ?>
                <tr>
<?showMaintainersTemplate($this, $_i) ?>
                </tr>
            <?php endforeach ?>
            <?php endif ?>
            </tbody>
        </table>
        <?php echo $this->getAddRowButtonHtml('maintainers_container', 'maintainers_template', 'Add Maintainer') ?>
    </fieldset>
</div>
