<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
/** @var $this \Magento\Logging\Block\Adminhtml\Details */
?>

<?php
$event = $this->getCurrentEvent();
?>

<div class="entry-edit form-inline">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?php echo __('Admin User Data'); ?></span>
        </legend><br />

        <div id="log_details_fieldset" class="field log-details">
            <table cellspacing="0" class="data-table">
                <col width="25%" />
                <col />
                <tbody>
                <tr>
                    <th><?php echo __('Aggregated Information'); ?></th>
                    <td>
                        <?php
                        $eventInfo = $this->getEventInfo();
                        if (is_bool($eventInfo)) {
                            echo($dataArray ? 'true' : 'false');
                        } elseif (is_array($eventInfo)) {
                            if (isset($eventInfo['general'])) {
                                if (!is_array($eventInfo['general'])) {
                                    $eventInfo['general'] = [$eventInfo['general']];
                                }
                                echo $this->escapeHtml(implode(', ', $eventInfo['general']));
                            }
                            ?>
                            <?php if (isset($eventInfo['additional'])): ?><br /><?php endif;
                            ?>
                            <?php
                            if (isset($eventInfo['additional'])) {
                                foreach ($eventInfo['additional'] as $modelName => $modelsData) {
                                    foreach ($modelsData as $mdoelId => $data) {
                                        echo $this->escapeHtml(implode(', ', $data));
                                    }
                                }
                            }
                        } else {
                            echo $this->escapeHtml($eventInfo);
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <th><?php echo __('Admin User ID'); ?></th>
                    <td>
                        <?php if ($this->getEventUser()) {
    ?>
                        #<?php echo $event->getUserId();
    ?>
                        <?php 
} else {
    ?>
                        N/A
                        <?php 
} ?>
                    </td>
                </tr>
                <tr>
                    <th><?php echo __('Admin User Name'); ?></th>
                    <td>
                        <?php if ($this->getEventUser()) {
    ?>
                        <a href="<?php echo $this->getUrl('adminhtml/user/edit', ['user_id' => $event->getUserId()]);
    ?>"><?php echo $this->escapeHtml($event->getUser());
    ?></a>
                        <?php 
} else {
    ?>
                        <?php echo $this->escapeHtml($event->getUser());
    ?>
                        <?php 
} ?>
                    </td>
                </tr>
                <tr>
                    <th><?php echo __('IP-Address'); ?></th>
                    <td><?php echo $this->getEventIp(); ?></td>
                </tr>
                <?php if ($this->getEventXForwardedIp()) {
    ?>
                <tr>
                    <th><?php echo __('X-Forwarded For');
    ?></th>
                    <td><?php echo $this->getEventXForwardedIp();
    ?></td>
                </tr>
                    <?php 
} ?>
                <?php if ($this->getEventError()) {
    ?>
                <tr>
                    <th><?php echo __('Error Message');
    ?></th>
                    <td><?php echo $this->getEventError();
    ?></td>
                </tr>
                    <?php 
} ?>
                </tbody>
            </table>
        </div>
    </fieldset>

    <?php if ($event->hasChanges()) {
    ?>
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?php echo __('Related Changes');
    ?></span>
        </legend><br />

        <div class="field log-details-grid">
            <?php echo $this->getChildHtml('details_grid') ?>
        </div>
    </fieldset>
    <?php 
} ?>
</div>
