<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="block <?php echo $this->getBlockCss(); ?>">
    <div class="block-title <?php echo $this->getBlockCss(); ?>-title"><strong><?php echo $this->getBlockTitle(); ?></strong></div>
    <div class="block-content <?php echo $this->getBlockCss(); ?>-content">
        <?php echo $this->getChildHtml(); ?>
    </div>
</div>
