<?
/**
 * Template for block Mage_Adminhtml_Block_Customer_Edit_Tab_View
 */
?>
<div class="box-left">
	<h4 class="icon-head head-customer-view">Personal Information</h4>
	<div class="box">
		<p><strong>Last Logged in:</strong> <?=$this->getLastLoginDate()?> ( Currently <strong><?=$this->getCurrentStatus()?></strong> )<br/>
		<strong>Account Created on:</strong> <?=$this->getCreateDate()?><br/>
		<strong>Account Created in:</strong> <?=$this->getCreatedInStore()?></p>
		<address>
		<strong>Primary Billing Address</strong><br/>
		<?=$this->getBillingAddressHtml()?>
	</div>
</div>
<div class="box-right">
    <?=$this->getSalesAccordionHtml()?>
</div>
<div class="clear"></div>
<br/>
<?=$this->getAccordionHtml()?>