<?
/**
 * Template for block Mage_Adminhtml_Block_Customer_Edit_Tab_View
 */
?>
<div class="box-left">
	<h4 class="icon-head head-customer-view">Personal Information</h4>
	<div class="box">
		<p><strong>Last Logged in:</strong> <?=$this->getLastLoginData()?> ( Currently <strong><?=$this->getCurrentStatus()?></strong> )<br/>
		<strong>Account Created on:</strong> <?=$this->getCreateDate()?><br/>
		<strong>Account Created in:</strong> <?=$this->getCreatedInStore()?></p>
		<address>
		<strong>Primary Billing Address</strong><br/>
		<?=$this->getBillingAddressHtml()?>
	</div>
</div>
<div class="box-right">
	<dl class="grid accordion">
		<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_close.gif" alt="" class="accordion-btn"/></a><strong>Sales Statistics</strong></dt>
		<dd class="open grid">
			<table cellspacing="0" class="data">
				<thead>
					<tr>
						<th>Store</th>
						<th>Lifetime Sale</th>
						<th>Average Sale</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td class="label"><strong><big>Total</big></strong></td>
						<td class="emph"><strong><big>$2076.97</big></strong></td>
						<td class="emph"><strong><big>$116.74</big></strong></td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td class="label">Magento Store (EN)</td>
						<td>$1875.99</td>
						<td>$89.99</td>
					</tr>
					<tr class="even">
						<td class="label">Varien Store (EN)</td>
						<td>$200.98</td>
						<td>$26.75</td>
					</tr>
				</tbody>
			</table>
		</dd>
	</dl>
</div>
		<div class="clear"></div>
		<br/>
		<dl class="accordion">
			<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_close.gif" alt="" class="accordion-btn"/></a><strong>Last 5 Orders</strong></dt>
			<dd class="grid open">
				<table cellspacing="0" class="data">
					<thead>
						<tr>
							<th>Order #</th>
							<th>Date</th>
							<th>Ship To</th>
							<th>Order Total</th>
							<th>Bought From</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>2DRF234</td>
							<td>06/15/2007</td>
							<td>Yoav Kutner</td>
							<td>$65.50</td>
							<td>Magento Store (EN)</td>
							<td><a href="#">View</a></td>
						</tr>
						<tr class="even">
							<td>Z12341247</td>
							<td>01/12/2007</td>
							<td>Yoav Kutner</td>
							<td>$98.75</td>
							<td>Varien Store (EN)</td>
							<td><a href="#">View</a></td>
						</tr>
						<tr>
							<td>Z9876145</td>
							<td>07/30/2006</td>
							<td>Yoav Kutner</td>
							<td>$124.99</td>
							<td>Magento Store (EN)</td>
							<td><a href="#">View</a></td>
						</tr>
						<tr class="even">
							<td>Z0123123</td>
							<td>03/26/2006</td>
							<td>Yoav Kutner</td>
							<td>$70.99</td>
							<td>Magento Store (EN)</td>
							<td><a href="#">View</a></td>
						</tr>
						<tr>
							<td>S1230K89</td>
							<td>01/17/2006</td>
							<td>Yoav Kutner</td>
							<td>$54.65</td>
							<td>Magento Store (EN)</td>
							<td><a href="#">View</a></td>
						</tr>
					</tbody>
				</table></dd>
			<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.gif" alt="" class="accordion-btn"/></a><strong>Shopping Cart</strong> (3 items)</dt>
			<dd></dd>
			<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.gif" alt="" class="accordion-btn"/></a><strong>Wishlist</strong> (1 item)</dt>
			<dd></dd>
		</dl>