<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

?>
<div id="iframe-warning" class="warning-message">
    <?php echo __('Please do not refresh the page until you complete payment.') ?>
</div>
<iframe id="hss-iframe" data-container="paypal-iframe" class="no-display" scrolling="no" frameborder="0" border="0" src="<?php echo $this->getFrameActionUrl() ?>" height="610" width="570"></iframe>
