<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Cms Hierarchy Context Menu
 *
 * @see Magento_VersionsCms_Block_Hierarchy_Menu
 */
?>
<?php
    $_tree = $this->getTree();
    $_menu = $this->drawMenu($_tree);
?>
<?php if($this->geMenuNodesQty() > 1): ?>
    <?php echo $_menu; ?>
<?php endif; ?>
