<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_Reward_Block_Customer_Reward
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Reward Points') ?></h1>
</div>
<div class="my-rewards">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('', true); ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo Mage::helper('Magento_Customer_Helper_Data')->__('Back') ?></a></p>
    </div>
</div>
