<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Businessinfo_Tile */
?>
<article class="tile-store-settings tile-store-info <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>" tabindex="0">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Store Info') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Confirm your business address and set the Store Emails that you want to use for customer communications.') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/load') ?>">
            <span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Confirm Info') ?></span>
        </button>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <p><strong><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Business Address') ?></strong></p>
            <?php foreach ($this->getAddress() as $addressKey => $addressValue): ?>
            <?php if (!empty($addressValue)) :?>
                <li class="store-address-<?php echo $addressKey ?>">
                <span><?php echo $this->escapeHtml($addressValue); ?></span>
                </li>
                <?php endif; ?>
            <?php endforeach; ?>

        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/load') ?>">
            <span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Edit Store Info') ?></span>
        </button>

        <li class="manage-store-info"><a href="<?php echo $this->getUrl('adminhtml/system_config/edit', array('section' => 'general', '_fragment' => 'general_store_information-link'))?>"><?php echo $this->__('Manage Store Info'); ?> </a></li>
        <?php endif; ?>
    </div>
</article>
