<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="box-title">
    <h2><?php echo __('Write Your Own Review') ?></h2>
</div>
<?php if ($this->getAllowWriteReviewFlag()): ?>
<form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
    <?php echo $this->getChildHtml('form_fields_before')?>
    <div class="box-content">
        <h3 class="product-name"><?php echo __("You're reviewing:"); ?> <span><?php echo $this->escapeHtml($this->getProductInfo()->getName()) ?></span></h3>
        <?php if ($this->getRatings() && $this->getRatings()->getSize()): ?>
            <span id="input-message-box"></span>
            <ul class="form-list">
                <li>
                    <label class="required"><em>*</em><?php echo __('How do you rate this product?') ?></label>
                    <div class="input-box">
                        <table class="data-table review-summary-table" id="product-review-table">
                            <col />
                            <col width="1" />
                            <col width="1" />
                            <col width="1" />
                            <col width="1" />
                            <col width="1" />
                            <thead>
                                <tr>
                                    <th>&nbsp;</th>
                                    <th><div class="rating-box"><span class="rating nobr" style="width:20%" title="<?php echo __('1 star') ?>"><?php echo __('1 star') ?></span></div></th>
                                    <th><div class="rating-box"><span class="rating nobr" style="width:40%" title="<?php echo __('2 stars') ?>"><?php echo __('2 stars') ?></span></div></th>
                                    <th><div class="rating-box"><span class="rating nobr" style="width:60%" title="<?php echo __('3 stars') ?>"><?php echo __('3 stars') ?></span></div></th>
                                    <th><div class="rating-box"><span class="rating nobr" style="width:80%" title="<?php echo __('4 stars') ?>"><?php echo __('4 stars') ?></span></div></th>
                                    <th><div class="rating-box"><span class="rating nobr" style="width:100%" title="<?php echo __('5 stars') ?>"><?php echo __('5 stars') ?></span></div></th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($this->getRatings() as $_rating): ?>
                                <tr>
                                    <td class="label"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></td>
                                <?php foreach ($_rating->getOptions() as $_option): ?>
                                    <td class="value"><input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}" /></td>
                                <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        <script type="text/javascript">(function($) {$('#product-review-table').decorate('table')})(jQuery)</script>
                    </div>
                </li>
            </ul>
        <?php endif ?>
        <ul class="form-list">
            <li>
                <label for="nickname_field" class="required"><em>*</em><?php echo __('Nickname') ?></label>
                <div class="input-box"><input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" /></div>
            </li>
            <li>
                <label for="summary_field" class="required"><em>*</em><?php echo __('Summary of Your Review') ?></label>
                <div class="input-box"><input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" /></div>
            </li>
            <li>
                <label for="review_field" class="required"><em>*</em><?php echo __('Review') ?></label>
                <div class="input-box"><textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea></div>
            </li>
        </ul>
        <div class="buttons-set form-buttons btn-only">
            <button type="submit" class="button"><span><span><?php echo __('Submit Review') ?></span></span></button>
        </div>
        <p class="required"><?php echo __('* Required Fields') ?></p>
    </div>
</form>
<script>
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
            function() {
                $('#review-form').validation({
                    errorPlacement: function (error, element) {
                        if (element.parents('#product-review-table').length) {
                            $('#product-review-table').siblings(this.errorElement + '.' + this.errorClass).remove();
                            $('#product-review-table').after(error);
                        } else {
                            element.after(error);
                        }
                    }
                });
            });
    })(jQuery);
</script>
<?php else: ?>
<div class="box-content">
    <p class="review-nologged" id="review-form">
        <?php echo __('Only registered users can write reviews. Please, <a href="%1">log in</a> or <a href="%2">register</a>', $this->getLoginLink(), Mage::helper('Magento_Customer_Helper_Data')->getRegisterUrl()) ?>
    </p>
</div>
<?php endif ?>
