<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
//<![CDATA[
function setSettings(urlTemplate, typeElement, packageThemeElement) {
    if (!editForm.validate()) {
        return false;
    }
    typeElement = $F(typeElement);
    packageThemeElement = $F(packageThemeElement).replace(/\//g, "-");

    setLocation(new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/).evaluate({
        'type': typeElement,
        'package_theme': packageThemeElement
    }));
}
function saveAndContinueEdit(){
    editForm.submit($('edit_form').action + 'back/edit/');
}
//]]>
</script>
