<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <h2 class="subtitle"><?php echo __('Thank you for your purchase!') ?>
        <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
            <span class="print">
            <?php echo __('<a href="%1" onclick="this.target=\'_blank\'">Print receipt</a>', $this->getPrintUrl()) ?>
            <?php echo $this->getChildHtml() ?>
        </span>
        <?php endif;?>
    </h2>
    <?php if ($this->getOrderId()):?>
        <?php if ($this->getCanViewOrder()) :?>
            <p><?php echo __('Your order # is: %1.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: %1.', $this->escapeHtml($this->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php echo __('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
    <?php endif;?>

    <?php echo $this->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" title="<?php echo __('Continue Shopping') ?>" href="<?php echo $this->getUrl() ?>"><span><?php echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
