<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Adminhtml\Block\Urlrewrite\Catalog\Category\Tree */
?>
<fieldset class="fieldset">
    <legend class="legend"><span><?php echo __('Select Category') ?></span></legend>
    <div class="content" style="clear: both;">
        <input type="hidden" name="categories" id="product_categories" value="" />
        <?php if ($this->getRoot()): ?>
        <div data-mage-init="<?php
            echo $this->escapeHtml($this->helper('\Magento\Core\Helper\Data')->jsonEncode(array(
                "categoryTree" => array(
                    "data" => $this->getTreeArray(null),
                    "url" => $this->getLoadTreeUrl(),
                )
            )));
        ?>"  class="jstree-default"></div>
        <?php endif; ?>
    </div>
</fieldset>
