<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Urlrewrites edit container
 *
 * @see Magento_Adminhtml_Block_Urlrewrite_Edit
 */
?>
<div class="page-actions"><?php echo $this->getButtonsHtml() ?></div>
<?php echo $this->getChildHtml() ?>

<?php if ($this->getChildBlock('form')): ?>
<script type="text/javascript">
    jQuery('#edit_form').mage('form')
        .mage('validation', {validationUrl: '<?php echo $this->getValidationUrl() ?>'});
</script>
<?php endif; ?>
