<?php
/**
 * {license_notice}
 *
 * @category    Magento
 * @package     Magento_Pbridge
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<button id="btn-pay-now" type="submit" title="<?php echo Mage::helper('Magento_Pbridge_Helper_Data')->quoteEscape(__('Pay Now')) ?>" class="button btn-checkout" data-role="review-save" data-action="pbridge-pay-now"><span><span><?php echo __('Pay Now') ?></span></span></button>
