<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div id="order_history_block">
    <?php if ($this->canAddComment()):?>
    <div id="history_form">
        <div><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Add Order Comments') ?></div>
        <div>
            <label for="history_status"><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Status') ?></label>
            <select name="history[status]" id="history_status">
            <?php foreach ($this->getStatuses() as $_code=>$_label): ?>
                <option value="<?php echo $_code ?>"<?php if($_code==$this->getOrder()->getStatus()): ?> selected="selected"<?php endif; ?>><?php echo $_label ?></option>
            <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label for="history_comment"><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Comment') ?></label>
            <textarea name="history[comment]" rows="3" cols="5" id="history_comment"></textarea>
        </div>
        <div class="clearfix">
            <div class="order-history-comments-options">
                <?php if ($this->canSendCommentEmail()): ?>
                <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1" /><label for="history_notify"> <?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Notify Customer by Email') ?></label><br />
                <?php endif; ?>
                <input name="history[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label for="history_visible"> <?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Visible on Frontend') ?></label>
            </div>
            <div class="actions">
                <?php echo $this->getChildHtml('submit_button') ?>
            </div>
        </div>
    </div>
    <?php endif;?>
    <ul class="note-list">
    <?php foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
        <li>
            <strong><?php echo $this->helper('Mage_Core_Helper_Data')->formatDate($_item->getCreatedAtDate(), 'medium') ?></strong>
            <?php echo $this->helper('Mage_Core_Helper_Data')->formatTime($_item->getCreatedAtDate(), 'medium') ?>
            <strong><?php echo $_item->getStatusLabel() ?></strong>
            <div>
                <?php echo $this->helper('Mage_Sales_Helper_Data')->__('Customer') ?>
                <strong>
                    <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                    <?php echo $this->helper('Mage_Sales_Helper_Data')->__('Notification Not Applicable') ?>
                    <?php elseif ($_item->getIsCustomerNotified()): ?>
                    <?php echo $this->helper('Mage_Sales_Helper_Data')->__('Notified') ?>
                    <img src="<?php echo $this->getViewFileUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                    <?php else: ?>
                    <?php echo $this->helper('Mage_Sales_Helper_Data')->__('Not Notified') ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_item->getComment()): ?>
                    <br/><?php echo $this->escapeHtml($_item->getComment(), array('b','br','strong','i','u')) ?>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">
        if($('order_status'))$('order_status').update('<?php echo $this->getOrder()->getStatusLabel() ?>');
    </script>
</div>
