<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_order = $this->getOrder() ?>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Product') ?></th>
                <th><span class="nobr"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Item BugsCoverage') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Original Price') ?></span></th>
                <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Price') ?></th>
                <th class="a-center"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Qty') ?></th>
                <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Subtotal') ?></th>
                <th><span class="nobr"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Tax Amount') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Tax Percent') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Discount Amount') ?></span></th>
                <th class="last"><span class="nobr"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>
<br />
