<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Create account form template
 *
 * @see Magento_CustomerCustomAttributes_Block_Form_Renderer_Multiselect
 */
/* @var $this Magento_CustomerCustomAttributes_Block_Form_Renderer_Multiselect */
?>
<label for="<?php echo $this->getHtmlId()?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
<div class="input-box">
    <select multiple="multiple" id="<?php echo $this->getHtmlId()?>" name="<?php echo $this->getFieldName('')?>"<?php if($this->getHtmlClass()):?> class="<?php echo $this->getHtmlClass();?>"<?php endif;?>>
    <?php foreach ($this->getOptions() as $option):?>
    <option value="<?php echo $option['value']?>"<?php if ($this->isValueSelected($option['value'])):?> selected="selected"<?php endif;?>><?php echo $this->escapeHtml($option['label'])?></option>
    <?php endforeach;?>
    </select>
    <?php if ($_message = $this->getAdditionalDescription()) : ?>
    <div class="validation-advice"><?php echo $_message; ?></div>
    <?php endif; ?>
</div>
