<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Create account form template
 *
 * @see \Magento\CustomerCustomAttributes\Block\Form\Renderer\Textarea
 */
/* @var $this \Magento\CustomerCustomAttributes\Block\Form\Renderer\Textarea */
?>
<label for="<?php echo $this->getHtmlId()?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
<div class="input-box">
    <textarea id="<?php echo $this->getHtmlId()?>" name="<?php echo $this->getFieldName()?>" rows="5" cols="25" class="input-text<?php echo $this->getHtmlClass(); ?>"><?php echo $this->getEscapedValue() ?></textarea>
    <?php if ($_message = $this->getAdditionalDescription()) : ?>
    <div class="validation-advice"><?php echo $_message; ?></div>
    <?php endif; ?>    
</div>
