<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_Rma_Block_Adminhtml_Rma_Create_Order */ ?>
<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></span>
    </div>
    <?php echo $this->getChildHtml('', true) ?>
</div>
