<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Invitaion view tab general block template
 *
 * @see \Magento\Invitation\Block\Adminhtml\Invitation\View\Tab\General
 */
?>
    <div class="fieldset-wrapper invitation_information">
         <div class="fieldset-wrapper-title">
            <span class="title"><?php echo __('Invitation Information') ?></span>
        </div>
        <fieldset class="fieldset">
            <table class="data-table">
            <tr>
                <th><?php  echo __('Send At'); ?></th>
                <td><?php echo $this->formatDate($this->getInvitation()->getInvitationDate(), 'medium', true) ?></td>
            </tr>
            <tr>
                <th>
                    <?php if ($this->canEditMessage()): ?><label for="message"><?php endif; ?>
                    <?php  echo __('Invitation Message'); ?>
                    <?php if ($this->canEditMessage()): ?></label><?php endif; ?>
                </th>
                <td>
                    <?php if ($this->canEditMessage()): ?>
                        <textarea name="message" rows="5" id="message"><?php echo $this->escapeHtml($this->getInvitation()->getMessage());?></textarea>
                        <?php echo $this->getSaveMessageButtonHtml(); ?>
                    <?php else: ?>
                        <?php if ($this->getInvitation()->getMessage()): ?>
                            <?php echo $this->escapeHtml($this->getInvitation()->getMessage());?>
                        <?php else: ?>
                            <?php echo __('N/A'); ?>
                        <?php endif; ?>
                        <textarea style="height:1px; visibility: hidden"><?php echo $this->escapeHtml($this->getInvitation()->getMessage());?></textarea>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th>
                    <?php if ($this->canEditMessage()): ?><label for="email"><?php endif; ?>
                        <?php echo __('Email'); ?><?php if ($this->canEditMessage()): ?><span class="required">*</span><?php endif; ?>
                    <?php if ($this->canEditMessage()): ?></label><?php endif; ?>
                </th>
                <td>
                <?php if ($this->canEditMessage()): ?>
                    <input type="text" id="email" class="required-entry input-text validate-email" name="email" value="<?php echo $this->getInvitation()->getEmail() ?>" />
                <?php else: ?>
                    <?php echo $this->escapeHtml($this->getInvitation()->getEmail()) ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Status'); ?></th>
                <td><?php echo $this->helper('Magento\Invitation\Helper\Data')->getInvitationStatusText($this->getInvitation()) ?></td>
            </tr>
            <tr>
                <th><?php  echo __('Website'); ?></th>
                <td><?php echo $this->getWebsiteName() ?></td>
            </tr>
            <tr>
                <th><?php  echo __('Store View'); ?></th>
                <td><?php echo $this->getStoreName() ?></td>
            </tr>
            <tr>
                <th><?php  echo __('Invitee Group'); ?></th>
                <td><?php echo $this->getCustomerGroupCode($this->getInvitation()->getGroupId(), true) ?></td>
            </tr>
            <tr>
                <th><?php  echo __('Signed Up At'); ?></th>
                <td>
                <?php if ($this->getInvitation()->getSignupDate()): ?>
                    <?php echo $this->formatDate($this->getInvitation()->getSignupDate(), 'medium', true) ?>
                <?php else: ?>
                    <?php  echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Invitation URL'); ?></th>
                <td>
                    <?php if ($url = $this->getInvitationUrl()): ?>
                        <a href="<?php echo $url ?>" target="_blank"><?php  echo __('Link'); ?></a>
                    <?php else: echo __('N/A'); endif; ?>
                </td>
            </tr>
            </table>
        </fieldset>
    </div>

    <div class="invitee_information">
        <div class="fieldset-wrapper">
             <div class="fieldset-wrapper-title">
                <span class="title"><?php echo __('Invitee Information') ?></span>
            </div>
            <table class="data-table">
            <tr>
                <th><?php  echo __('Customer ID'); ?></th>
                <td>
                <?php if ($this->getInvitation()->getReferralId()): ?>
                    <?php if ($this->canShowReferralLink()) :?>
                        <a target="_blank" href="<?php echo $this->getUrl('customer/index/edit', ['id' => $this->getInvitation()->getReferralId()]);?>"><?php echo $this->getInvitation()->getReferralId()?></a>
                    <?php else : ?>
                        <?php echo $this->getInvitation()->getReferralId()?>
                    <?php endif; ?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Customer Group'); ?></th>
                <td>
                <?php if ($this->getReferral()): ?>
                    <?php echo $this->getCustomerGroupCode($this->getReferral()->getGroupId())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('First Name'); ?></th>
                <td>
                <?php if ($this->getReferral()): ?>
                    <?php echo $this->escapeHtml($this->getReferral()->getFirstname())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Last Name'); ?></th>
                <td>
                <?php if ($this->getReferral()): ?>
                    <?php echo $this->escapeHtml($this->getReferral()->getLastname())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Email'); ?></th>
                <td>
                <?php if ($this->getReferral()): ?>
                    <?php echo $this->escapeHtml($this->getReferral()->getEmail())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Sign Up At'); ?></th>
                <td>
                <?php if ($this->getReferral()): ?>
                    <?php echo $this->formatDate($this->getReferral()->getCreatedAt(), 'medium', true)?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            </table>
        </div>
    </div>

    <div class="inviter_information">
        <div class="fieldset-wrapper">
            <div class="fieldset-wrapper-title">
                <span class="title"><?php echo __('Inviter Information') ?></span>
            </div>
            <table class="data-table">
            <?php if ($this->isInvitedByAdmin()): ?>
            <tr>
                <td><?php echo __('Admin'); ?><td>
            </tr>
            <?php else: ?>
            <tr>
                <th><?php  echo __('Customer ID'); ?></th>
                <td>
                <?php if ($this->getInvitation()->getCustomerId()): ?>
                    <a target="_blank" href="<?php echo $this->getUrl('customer/index/edit', ['id' => $this->getInvitation()->getCustomerId()]);?>"><?php echo $this->getInvitation()->getCustomerId()?></a>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Customer Group'); ?></th>
                <td>
                <?php if ($this->getCustomer()): ?>
                    <?php echo $this->getCustomerGroupCode($this->getCustomer()->getGroupId())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('First Name'); ?></th>
                <td>
                <?php if ($this->getCustomer()): ?>
                    <?php echo $this->escapeHtml($this->getCustomer()->getFirstname())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Last Name'); ?></th>
                <td>
                <?php if ($this->getCustomer()): ?>
                    <?php echo $this->escapeHtml($this->getCustomer()->getLastname())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Email'); ?></th>
                <td>
                <?php if ($this->getCustomer()): ?>
                    <?php echo $this->escapeHtml($this->getCustomer()->getEmail())?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <th><?php  echo __('Sign Up At'); ?></th>
                <td>
                <?php if ($this->getCustomer()): ?>
                    <?php echo $this->formatDate($this->getCustomer()->getCreatedAt(), 'medium', true)?>
                <?php else:  ?>
                    <?php echo __('N/A'); ?>
                <?php endif; ?>
                </td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
    </div>
