<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>"/>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon"/>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('jquery/jquery.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('jquery/head.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('mage/mage.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('mage/translate.js')?>"></script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('jquery/ui/css/jquery-ui.css')?>" type="text/css"
      media="all"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('Mage_Page::css/validate.css') ?>" type="text/css"
      media="all"/>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->getIncludes() ?>
<?php echo $this->helper('Mage_Core_Helper_Js')->getTranslatorScript() ?>