<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Page
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top') ?>
<?php if ($_menu): ?>
<div class="nav-container">
    <ul id="nav">
        <?php echo $_menu ?>
    </ul>
</div>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('Mage_Page::js/menu.js') ?>", function() {
            $('#nav .parent').menu();
        });
    })(jQuery);
</script>
<?php endif ?>
