<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Promotestore_Catalogpricerule_Drawer */
?>
<form id="drawer-form">
    <article class="entry">
        <ul class="promote-actions">
            <?php $trackerLink = $this->getTrackerLink('adminhtml/promo_catalog/new'); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('Add Catalog Rule'); ?></a></li>
        </ul>
        <div class="promote-content">
            <div class="promote-content-section">
                <p><?php echo __('Catalog Price Rules are applied to products before they\'re added to the shopping cart. You can offer discounts and special pricing for any products and attributes you choose (15% off blue glassware, for instance). Catalog price rules are easy and important tools for attracting and keeping customers. Set up your first rule right away.') ?> </p>
            </div>
            <div class="promote-content-section">
                <p><?php echo __('Catalog Price Rules are applied to products before they\'re added to the shopping cart. You can offer discounts and special pricing for any products and attributes you choose (15% off blue glassware, for instance). Catalog price rules are easy and important tools for attracting and keeping customers. Set up your first rule right away.') ?> </p>
            </div>
        </div>
    </article>
</form>
