<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Customer_Block_Account_Navigation */ ?>
<div class="block account nav">
    <div class="title">
        <strong><?php echo __('My Account'); ?></strong>
    </div>
    <div class="content">
        <navigation class="account nav">
        <ul class="nav items">
            <?php $_links = $this->getLinks(); ?>
            <?php foreach ($_links as $_link): ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="nav item current"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li class="nav item"><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        </navigation>
    </div>
</div>
