<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Order by SKU Failed Items renderer
 */

/** @var $this Mage_Checkout_Block_Cart_Item_Renderer */
$_item = $this->getItem();
$displayBothPrices = $this->helper('Mage_Tax_Helper_Data')->displayCartBothPrices();
$additionalInfoBlock = $this->getProductAdditionalInformationBlock();
?>
<tr>
    <td>
        <div class="product-image">
            <img src="<?php echo $this->getProductThumbnail()->resize(90); ?>" width="45" height="45" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
        </div>
    </td>
    <td>
        <?php if ($additionalInfoBlock):?>
            <?php echo $additionalInfoBlock->setItem($_item)->toHtml() ?>
        <?php else :?>
            <h3 class="product-name"><?php echo $this->escapeHtml($this->getProductName()) ?></h3>
        <?php endif; ?>
    </td>
    <td class="a-center"></td>
    <?php if ($this->helper('Mage_Wishlist_Helper_Data')->isAllowInCart()) : ?><td class="a-center"></td><?php endif ?>
    <td class="a-right"<?php if ($displayBothPrices): ?> colspan="2"<?php endif; ?>></td>
    <td class="a-center">
        <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty disabled" maxlength="12" disabled="disabled" />
    </td>
    <td class="a-center last"><a href="<?php echo $this->getDeleteUrl()?>" class="item-remove"><img src="<?php echo $this->getSkinUrl('images/btn_trash.png') ?>" width="10" height="10" alt="<?php echo $this->__('Remove item')?>" /></a></td>
</tr>
