<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\Rma\Block\Adminhtml\Product\Bundle\Items */ ?>
<?php $_items = $this->getItems(); ?>
<?php $_bundle = ''; ?>
<?php foreach ($_items as $_item): ?>
    <?php if ($_item->getId() == $this->getParentId()): ?>
        <?php $_bundle = $_item->getName() ?>
        <?php break; ?>
    <?php endif; ?>
<?php endforeach; ?>
<div id="bundle_div_<?php echo $this->getParentId() ?>">
    <div class="popup-window-wrapper">
        <div class="popup-window-title">
            <span class="title"><?php echo $this->escapeHtml($_bundle) ?></span>
            <div class="form-buttons"></div>
        </div>
        <div class="popup-window-content">
            <ul>
                <li>
                    <input type="radio" name="items_selector" id="all_items_<?php echo $this->getParentId() ?>">
                    <label for="all_items_<?php echo $this->getParentId() ?>"><?php echo __('All Items') ?></label>
                </li>
                <li>
                    <input type="radio" name="items_selector" id="individual_items_<?php echo $this->getParentId() ?>">
                    <label for="individual_items_<?php echo $this->getParentId() ?>"><?php echo __('Individual Items') ?></label>
                </li>
            </ul>
            <ul>
                <?php foreach ($_items as $_item): ?>
                    <?php if ($_item->getId() == $this->getParentId()): ?>
                    <?php continue; ?>
                    <?php endif; ?>
                    <li>
                        <?php if (!$_item->getIsOrdered()): ?>
                        <?php
                        if ($_item->getIsQtyDecimal()) {
                            $availableQty = sprintf("%01.4f", $_item->getAvailableQty());
                        } else {
                            $availableQty = intval($_item->getAvailableQty());
                        }
                        ?>
                        <input id="checkbox_rma_bundle_item_id_<?php echo $this->getParentId() ?>_<?php echo $_item->getId() ?>" type="checkbox" value="<?php echo $_item->getId() ?>" class="checkbox_rma_bundle_item_<?php echo $this->getParentId() ?>" />
                        <input id="checkbox_rma_bundle_item_name_<?php echo $this->getParentId() ?>_<?php echo $_item->getId() ?>" type="hidden" value="<?php echo $this->escapeHtml($_item->getName()) ?>"/>
                        <input id="checkbox_rma_bundle_item_sku_<?php echo $this->getParentId() ?>_<?php echo $_item->getId() ?>" type="hidden" value="<?php echo $this->escapeHtml($_item->getSku()) ?>"/>
                        <input id="checkbox_rma_bundle_item_qty_<?php echo $this->getParentId() ?>_<?php echo $_item->getId() ?>" type="hidden" value="<?php echo $availableQty ?>"/>
                        <?php else: ?>
                        <input type="checkbox" disabled="disabled" />
                        <?php endif; ?>
                        <label for="checkbox_rma_bundle_item_id_<?php echo $this->getParentId() ?>_<?php echo $_item->getId() ?>" <?php echo($_item->getIsOrdered()) ? 'style="color:#999999"' : ''?>><?php echo $_item->getName() ?></label>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="popup-window-buttons-set">
            <button id="rma_bundle_ok_button_<?php echo $this->getParentId() ?>" onclick="rma.hidePopups()" class="scalable " type="button"><span><?php echo __('OK') ?></span></button>
            <button id="rma_bundle_cancel_button_<?php echo $this->getParentId() ?>" onclick="rma.hidePopups()" class="scalable " type="button"><span><?php echo __('Cancel') ?></span></button>
        </div>
    </div>
</div>
