<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Magento\Tax\Block\Checkout\Cart\Sidebar\Totals */
?>

<div class="amount">
    <?php if ($this->getDisplaySubtotalExclTax()): ?>
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getSubtotalExclTax()); ?>
    <?php elseif ($this->getDisplaySubtotalInclTax()): ?>
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getSubtotalInclTax()); ?>
    <?php else: ?>
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getSubtotalExclTax()); ?>
        <span class="amount incl tax">
            <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getSubtotalInclTax()) ?>
            <?php echo $this->getIncExcTaxLabel(true) ?>
        </span>
    <?php endif; ?>
</div>
