<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?/*{

}*/?>
<?if (empty($_level)):?>
<!-- menu start -->
<script type="text/javascript">
function toggleMenu(el, over) {
    if (over) {
        Element.addClassName(el, 'over');
    } else {
        Element.removeClassName(el, 'over');
    }
}
</script>
<ul id="nav">
<?  $_level = 0; ?>
<?endif?>

<?foreach ($menu as $_item):?>
    <li <?if(!empty($_item['children'])):?>onmouseover="toggleMenu(this,1)" onmouseout="toggleMenu(this,0)"<?endif?> class="<?=($_level===0 && !empty($_item['active']))?'active':''?> <?=!empty($_item['children'])?' parent':''?><?=(!empty($_level) && !empty($_item['last']))?' last':''?> level<?=$_level?>"><a href="<?=$_item['url']?>" title="<?=$_item['title']?>" <?if(!empty($_item['click'])):?> onclick="<?=$_item['click'];?>"<?endif?> class="<?=($_level===0 && !empty($_item['active']))?'active':''?>">
            <span><?=$_item['label']?>
            <?if(empty($_level)):?><em></em><?endif?></span>
       </a>
<?if(!empty($_item['children'])):?><ul>
        <?
            $_menuData[$_level] = array('menu'=>$menu);
            $menu = $_item['children'];
            $_level++;
            include __FILE__;
            $_level--;
            extract($_menuData[$_level]);
        ?>
        </ul><?endif;?></li>
<?endforeach;?>

<?if (empty($_level)):?>
</ul>
<!-- menu end -->
<?endif?>