<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Magento_Sales_Block_Order_Email_Items_Order_Default */

/** @var $_item Magento_Sales_Model_Order_Item */
$_item = $this->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
        <strong style="font-size:11px;"><?php echo $this->escapeHtml($_item->getName()) ?></strong>
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;">
                <?php echo nl2br($option['value']) ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $this->escapeHtml($_item->getDescription()) ?>
    </td>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $this->escapeHtml($this->getSku($_item)) ?></td>
    <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $_item->getQtyOrdered()*1 ?></td>
    <td align="right" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
        <?php if ($this->helper('Magento_Tax_Helper_Data')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('Magento_Tax_Helper_Data')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('Magento_Tax_Helper_Data')->displaySalesBothPrices($_order->getStore())): ?>
                <span class="label"><?php echo __('Excl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php if ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>


            <?php if ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>
                <br />
                <?php if ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <br />
                    <span class="nobr"><?php echo __('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>


        <?php if ($this->helper('Magento_Tax_Helper_Data')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('Magento_Tax_Helper_Data')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('Magento_Tax_Helper_Data')->displaySalesBothPrices($_order->getStore())): ?>
                <br /><span class="label"><?php echo __('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('Magento_Checkout_Helper_Data')->getSubtotalInclTax($_item); ?>
                <?php if ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                    <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            <?php if ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>
                <br />
                <?php if ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach ($this->helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if ($this->helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <span class="nobr"><?php echo __('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento_GiftMessage_Helper_Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="4" style=" border-bottom:2px solid #CCCCCC; padding:3px 9px;">
        <strong style="color:#444444; font-size:11px;"><?php echo __('Gift Message') ?></strong>
        <?php echo __('From:'); ?> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?><br />
        <?php echo __('To:'); ?> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?><br />
        <strong><?php echo __('Message:'); ?></strong><br /><?php echo $this->escapeHtml($_giftMessage->getMessage()) ?>
    </td>
</tr>
<?php endif; ?>
