<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script data-template="item-content-tmpl" type="text/x-jquery-tmpl">
    ${prefix} ${firstname} ${middlename} ${lastname} ${suffix}<br/>
    ${company}<br/>
    ${street0}<br/>
    ${street1}<br/>
    ${street2}<br/>
    ${street3}<br/>
    ${city}, ${region}, ${postcode}<br/>
    ${country_id}<br/>
    T: ${telephone}<br/>
    F: ${fax}<br/>
    VAT: ${vat_id}
</script>

<!-- Addresses list -->
<fieldset class="fieldset">
    <legend class="legend">
        <span><?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Customer Addresses') ?></span>
    </legend>
    <br />

    <div id="address-tabs" data-mage-init='{addressTabs:{itemCount: <?php echo count($addressCollection) ?>,
            deleteConfirmPrompt: "<?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Are you sure you want to delete this address?') ?>",
            regionsUrl: "<?php echo $this->getRegionsUrl(); ?>",
            optionalZipCountries: <?php echo $this->helper("Mage_Directory_Helper_Data")->getCountriesWithOptionalZip(true) ?>,
            requiredStateForCountries: <?php echo $this->helper('Mage_Directory_Helper_Data')->getCountriesWithStatesRequired(true) ?>,
            showAllRegions: <?php echo (string)$this->helper('Mage_Directory_Helper_Data')->getShowNonRequiredState() ? 1 : 0; ?>,
            defaultCountries: <?php echo $this->getDefaultCountriesJson(); ?> }}'>
        <ul class="address-list" id="address_list">
            <?php $_iterator = 0; ?>
            <?php if(count($addressCollection)): ?>
                <?php foreach ($addressCollection as $_address): ?>

                <li class="address-list-item" id="address_item_<?php echo $_address->getId() ?>" data-item="<?php echo $_address->getId() ?>">
                    <a href="#form_address_item_<?php echo $_address->getId() ?>" data-mage-init="{dataItemDeleteButton: {}}">
                        <?php if (!$this->isReadonly()): ?>
                        <div class="address-list-item-actions">
                            <button class="action-delete" type="button" title="Remove address" id="delete_button<?php echo ++$_iterator ?>" data-role="delete">
                                <span>Remove address</span>
                            </button>
                            <button class="action-edit" type="button" title="Edit address" id="select_button_<?php echo $_address->getId() ?>">
                                <span>Edit address</span>
                            </button>
                        </div>
                        <?php endif;?>

                        <address>
                            <?php echo $_address->format('html') ?>
                        </address>
                    </a>
                    <div class="field field-address-item-billing choice">
                        <input type="checkbox" <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif;?> value="<?php echo $_address->getId() ?>" id="address_item_billing<?php echo $_address->getId() ?>" name="account[default_billing]" title="<?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Set as Default Billing Address') ?>"<?php if($_address->getId()==$customer->getDefaultBilling()): ?> checked="checked"<?php endif; ?> />
                        <label class="label" for="address_item_billing<?php echo $_address->getId() ?>">
                            <span><?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Default Billing Address') ?></span>
                        </label>
                    </div>
                    <div class="field field-address-item-shipping choice">
                        <input type="checkbox" <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif;?> value="<?php echo $_address->getId() ?>" id="address_item_shipping<?php echo $_address->getId() ?>" name="account[default_shipping]" title="<?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Set as Default Shipping Address') ?>"<?php if($_address->getId()==$customer->getDefaultShipping()): ?> checked="checked"<?php endif; ?> />
                        <label class="label" for="address_item_shipping<?php echo $_address->getId() ?>">
                            <span><?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Default Shipping Address') ?></span>
                        </label>
                    </div>
                </li>
                <?php endforeach; ?>
            <?php endif; ?>
            <li class="address-list-actions last"><?php echo $this->getAddNewButtonHtml() ?></li>
        </ul>

        <!-- Template for adding address item to list -->
        <?php $_templatePrefix = $this->getTemplatePrefix() ?>
        <div id="address_item_template" class="hidden template" data-template="address_item">
            <li class="address-list-item" id="address_item_" data-item="data_item_value_">
                <a href="#form_new_item" data-mage-init="{dataItemDeleteButton: {}}">
                    <?php if (!$this->isReadonly()): ?>
                    <div class="address-list-item-actions">
                        <button class="action-delete" type="button" title="Remove address" id="delete_button<?php echo ++$_iterator ?>" data-role="delete">
                            <span>Remove address</span>
                        </button>
                        <button class="action-edit" type="button" title="Edit address">
                            <span>Edit address</span>
                        </button>
                    </div>
                    <?php endif;?>

                    <address>
                        <?php echo Mage::helper('Mage_Customer_Helper_Data')->__('New Customer Address') ?>
                    </address>
                </a>
                <div class="field choice field-address-item-billing">
                        <input type="checkbox" <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif;?> value="<?php echo $_templatePrefix ?>" id="address_item_billing<?php echo $_templatePrefix ?>" name="account[default_billing]" title="<?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Set as Default Billing Address') ?>" />
                    <label class="label" for="address_item_billing<?php echo $_templatePrefix ?>">
                        <span><?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Default Billing Address') ?></span>
                    </label>
                </div>
                <div class="field choice field-address-item-shipping">
                        <input type="checkbox" <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif;?> value="<?php echo $_templatePrefix ?>" id="address_item_shipping<?php echo $_templatePrefix ?>" name="account[default_shipping]" title="<?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Set as Default Shipping Address') ?>"/>
                    <label class="label" for="address_item_shipping<?php echo $_templatePrefix ?>">
                        <span><?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Default Shipping Address') ?></span>
                    </label>
                </div>
            </li>
        </div>

        <!-- Address form template -->
        <div id="address_form_template" class="no-display template" data-template="address_form"><!-- Don`t delete class no-display, save customer stops work  -->
            <?php
                // Set form template elements prefix
                $this->getForm()->setHtmlIdPrefix($_templatePrefix)
                        ->setFieldNameSuffix('address['.$_templatePrefix.']');
            ?>
            <?php echo $this->getForm()->getHtml() ?>
        </div>

        <!-- Addresses forms -->
        <div class="address-item-edit" id="address_form_container">
            <?php if(count($addressCollection)): ?>
                <?php foreach ($addressCollection as $_address): ?>
                <div class="address-item-edit-content" id="form_address_item_<?php echo $_address->getId() ?>" data-item="<?php echo $_address->getId() ?>" style="display:none" data-mage-init="{observableInputs: {'name': 'address_item_<?php echo $_address->getId() ?>'}}">
                <?php
                        $this->getForm()->addValues($_address->getData())
                                ->setHtmlIdPrefix("_item{$_address->getId()}")
                                ->setFieldNameSuffix('address['.$_address->getId().']');
                        $this->addValuesToNamePrefixElement($_address->getPrefix())
                            ->addValuesToNameSuffixElement($_address->getSuffix());
                ?>
                <?php echo $this->getForm()->getHtml() ?>
                <input type="hidden" name="address[<?php echo $_address->getId() ?>][_deleted]" id="deleted_address_item_<?php echo $_address->getId() ?>" />
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</fieldset>
