<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Magento_Page_Block_Html_Head */
?>
<meta http-equiv="X-UA-Compatible" content="IE=edge" >
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" href="<?php echo $this->getViewFileUrl('Magento_Page::favicon.ico') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getViewFileUrl('Magento_Page::favicon.ico') ?>" type="image/x-icon"/>

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getViewFileUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->getViewFileUrl('spacer.gif') ?>';
    var BASE_URL = '<?php echo $this->getUrl('*') ?>';
    var FORM_KEY = '<?php echo $this->getFormKey() ?>';
</script>

<?php echo $this->getCssJsHtml() ?>

<?php if($this->getCanLoadExtJs()): ?>
<script type="text/javascript">
    Ext.BLANK_IMAGE_URL = BLANK_IMG;
    Ext.UpdateManager.defaults.loadScripts = false;
    Ext.UpdateManager.defaults.disableCaching = true;
</script>
<?php endif; ?>

<?php if($this->getCanLoadTinyMce()): // TinyMCE is broken when loaded through index.php ?>
<script type="text/javascript" src="<?php echo $this->getViewFileUrl('tiny_mce/tiny_mce_src.js') ?>"></script>
<?php endif; ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?php echo $this->helper('Magento_Adminhtml_Helper_Data')->getCurrentUserId() ?>);
</script>

<?php echo $this->getChildHtml('components'); ?>
<?php echo $this->getChildHtml('calendar'); ?>
<?php echo $this->getChildHtml('optional_zip_countries'); ?>

<?php
$translations = array(
    //flexuploader.js
    'Complete' => __('Complete'),
    'Upload Security Error' => __('Upload Security Error'),
    'Upload HTTP Error' => __('Upload HTTP Error'),
    'Upload I/O Error' => __('Upload I/O Error'),
    'SSL Error: Invalid or self-signed certificate' => __('SSL Error: Invalid or self-signed certificate'),
    'TB' => __('TB'),
    'GB' => __('GB'),
    'MB' => __('MB'),
    'kB' => __('kB'),
    'B' => __('B'),
    'Add Products' => __('Add Products'),
    //addbysku.js
    'Add Products By SKU' => __('Add Products By SKU'),
    'Insert Widget...' => __('Insert Widget...'),
    //rules.js
    'Please wait, loading...' => __('Please wait, loading...'),
    //validation.js
    'HTML tags are not allowed' => __('HTML tags are not allowed'),
    'Please select an option.' => __('Please select an option.'),
    'This is a required field.' => __('This is a required field.'),
    'Please enter a valid number in this field.' => __('Please enter a valid number in this field.'),
    'The value is not within the specified range.' => __('The value is not within the specified range.'),
    'Please use numbers only in this field. Please avoid spaces or other characters such as dots or commas.' => __('Please use numbers only in this field. Please avoid spaces or other characters such as dots or commas.'),
    'The value is not within the specified range.' => __('The value is not within the specified range.'),
    'Please use letters only (a-z or A-Z) in this field.' => __('Please use letters only (a-z or A-Z) in this field.'),
    'Please use only letters (a-z), numbers (0-9) or underscore(_) in this field, first character should be a letter.' => __('Please use only letters (a-z), numbers (0-9) or underscore(_) in this field, first character should be a letter.'),
    'Please use only letters (a-z or A-Z) or numbers (0-9) only in this field. No spaces or other characters are allowed.' => __('Please use only letters (a-z or A-Z) or numbers (0-9) only in this field. No spaces or other characters are allowed.'),
    'Please use only letters (a-z or A-Z) or numbers (0-9) or spaces and # only in this field.' => __('Please use only letters (a-z or A-Z) or numbers (0-9) or spaces and # only in this field.'),
    'Please enter a valid fax number. For example (123) 456-7890 or 123-456-7890.' => __('Please enter a valid fax number. For example (123) 456-7890 or 123-456-7890.'),
    'Please enter a valid date.' => __('Please enter a valid date.'),
    'The From Date value should be less than or equal to the To Date value.' => __('The From Date value should be less than or equal to the To Date value.'),
    'Please enter a valid email address. For example johndoe@domain.com.' => __('Please enter a valid email address. For example johndoe@domain.com.'),
    'Please use only visible characters and spaces.' => __('Please use only visible characters and spaces.'),
    'Please enter 6 or more characters. Leading or trailing spaces will be ignored.' => __('Please enter 6 or more characters. Leading or trailing spaces will be ignored.'),
    'Please enter 7 or more characters. Password should contain both numeric and alphabetic characters.' => __('Please enter 7 or more characters. Password should contain both numeric and alphabetic characters.'),
    'Please make sure your passwords match.' => __('Please make sure your passwords match.'),
    'Please enter a valid URL. Protocol is required (http://, https:// or ftp://)' => __('Please enter a valid URL. Protocol is required (http://, https:// or ftp://)'),
    'Please enter a valid URL Key. For example "example-page", "example-page.html" or "anotherlevel/example-page".' => __('Please enter a valid URL Key. For example "example-page", "example-page.html" or "anotherlevel/example-page".'),
    'Please enter a valid XML-identifier. For example something_1, block5, id-4.' => __('Please enter a valid XML-identifier. For example something_1, block5, id-4.'),
    'Please enter a valid social security number. For example 123-45-6789.' => __('Please enter a valid social security number. For example 123-45-6789.'),
    'Please enter a valid zip code. For example 90602 or 90602-1234.' => __('Please enter a valid zip code. For example 90602 or 90602-1234.'),
    'Please enter a valid zip code.' => __('Please enter a valid zip code.'),
    'Please use this date format: dd/mm/yyyy. For example 17/03/2006 for the 17th of March, 2006.' => __('Please use this date format: dd/mm/yyyy. For example 17/03/2006 for the 17th of March, 2006.'),
    'Please select one of the above options.' => __('Please select one of the above options.'),
    'Please select one of the options.' => __('Please select one of the options.'),
    'Please enter a valid number in this field.' => __('Please enter a valid number in this field.'),
    'Please select State/Province.' => __('Please select State/Province.'),
    'Please enter 6 or more characters. Leading or trailing spaces will be ignored.' => __('Please enter 6 or more characters. Leading or trailing spaces will be ignored.'),
    'Please enter a number greater than 0 in this field.' => __('Please enter a number greater than 0 in this field.'),
    'Please enter a number 0 or greater in this field.' => __('Please enter a number 0 or greater in this field.'),
    'Please enter a valid credit card number.' => __('Please enter a valid credit card number.'),
    'Credit card number does not match credit card type.' => __('Credit card number does not match credit card type.'),
    'Card type does not match credit card number.' => __('Card type does not match credit card number.'),
    'Incorrect credit card expiration date.' => __('Incorrect credit card expiration date.'),
    'Please enter a valid credit card verification number.' => __('Please enter a valid credit card verification number.'),
    'Please use only letters (a-z or A-Z), numbers (0-9) or underscore(_) in this field, first character should be a letter.' => __('Please use only letters (a-z or A-Z), numbers (0-9) or underscore(_) in this field, first character should be a letter.'),
    'Please input a valid CSS-length. For example 100px or 77pt or 20em or .5ex or 50%.' => __('Please input a valid CSS-length. For example 100px or 77pt or 20em or .5ex or 50%.'),
    'Text length does not satisfy specified text range.' => __('Text length does not satisfy specified text range.'),
    'Please enter a number lower than 100.' => __('Please enter a number lower than 100.'),
    'Please select a file' => __('Please select a file'),
    'Please enter issue number or start date for switch/solo card type.' => __('Please enter issue number or start date for switch/solo card type.'),
    //js.js
    'This date is a required value.' => __('This date is a required value.'),
    'Please enter a valid day (1-%d).' => __('Please enter a valid day (1-%d).'),
    'Please enter a valid month (1-12).' => __('Please enter a valid month (1-12).'),
    'Please enter a valid year (1900-%d).' => __('Please enter a valid year (1900-%d).'),
    'Please enter a valid full date' => __('Please enter a valid full date'),
    //various files
    'Cancel' => __('Cancel'),
    'Save' => __('Save'),
); ?>
<script type="text/javascript"><![CDATA[
    (function($) {$.mage.translate.add(<?php echo json_encode($translations) ?>)})(jQuery);
]]></script>
