<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Editor\Tools\Tabs\Body */ ?>
<div class="tab-panel<?php echo $this->getIsActive() ? ' active' : '' ?>" id="<?php echo $this->getTabId() ?>">
    <?php echo $this->getContent() ?>
</div>
