<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright  {copyright}
 * @license    {license_link}
 */

/** @var $this Magento_Oauth_Block_Customer_Token_List */
?>
<?php echo $this->getLayout()->renderElement('messages') ?>
<div class="page-title">
    <h1><?php echo __('My Applications') ?></h1>
</div>
<?php if ($this->getCollection() && $this->count()): ?>
    <?php echo $this->getToolbarHtml() ?>
        <table class="data-table" id="my-apps-table">
            <col />
            <col width="100" align="right" />
            <col width="110" align="right" />
            <thead>
                <tr>
                    <th><?php echo __('App Name') ?></th>
                    <th><?php echo __('Status') ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php /** @var $item Magento_Oauth_Model_Token */ ?>
                <?php foreach ($this->getCollection() as $item) : ?>
                <tr>
                    <td><span class="app-name">
                        <?php echo $this->escapeHtml($item->getName()); ?></span></td>
                    <td><em><?php echo $this->getStatusLabel($item->getRevoked()) ?></em></td>
                    <td align="right">
                        <a href="<?php echo $this->getUpdateRevokeLink($item)?>" class="nobr"
                            onclick="return confirm('<?php echo $this->getChangeStatusConfirmMessage($item->getRevoked()) ?>')">
                            <?php echo $this->getChangeStatusLabel($item->getRevoked()) ?></a>
                        <span class="separator">|</span> <a href="<?php echo $this->getDeleteLink($item)?>" class="nobr"
                            onclick="return confirm('<?php echo __('Are you sure you want to delete this application?') ?>')">
                        <?php echo __('Delete') ?></a></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">
        //<![CDATA[
            (function($) {$('#my-apps-table').decorate('table')})(jQuery)
        //]]>
        </script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo __('You have no applications.'); ?></p>
<?php endif; ?>
