<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="head">
    <h4><?=__('My Recent Reviews')?></h4>
    <a href="<?=$this->getAllReviewsUrl()?>"><?=__('View All')?></a>
</div>
<?if( $this->getCollection() && $this->count()):?>
    <?$iterator = 0?>
    <?foreach ($this->getCollection() as $_review):?>
    <ol class="recent-reviews">
        <li class="odd">
            <div class="count"><?=++$iterator?></div>
            <div class="content">
                <a href="<?=$this->getReviewUrl($_review->getId())?>"><?=$_review->getName()?></a>
                <div class="ratings">
                    <small><?=__('RATING')?>:</small>
                    <?if($_review->getSum()):?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?=( $_review->getSum() / $_review->getCount() )?>%;"></div>
                        </div>
                    <?endif;?>
                 </div>
            </div>
        </li>
    </ol>
    <?endforeach;?>
<?endif;?>