<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->getRating()):?>
    <div class="page-head">
        <h2><?=__('My Product Reviews')?></h2>
    </div>

    <div class="my-review-detail">
        <div class="product-image">
            <p><a href="<?=$this->getProductData()->getProductUrl()?>"><img src="<?=$this->getProductData()->getImageUrl()?>" alt="<?=$this->getProductData()->getName()?>" height="100" width="100"></a><br>
            <small><?=__('Average Customer Rating')?>:</small></p>

            <div class="rating-box">
                <div class="rating" style="width: <?=ceil($this->getRatingSummary()->getSum() / ($this->getRatingSummary()->getCount()))?>%;"></div>
            </div>
        <span class="no-wrap">( <a href="<?=$this->getProductData()->getProductUrl()?>#customer-reviews"><?=__('%d Reviews', $this->getTotalReviews())?></a> )</span>
    </div>
    <div class="details">
        <h3><?=$this->getProductData()->getName()?></h3>
        <strong><?=__('YOUR RATING:')?></strong>
        <?if( $this->getRating() && $this->getRating()->getSize()):?>
            <?foreach ($this->getRating() as $_rating):?>
            <?if($_rating->getPercent()):?>
            	<div class="ratings">
            	   <?=__($_rating->getRatingCode())?>
            		<div class="rating-box">
            			<div class="rating" style="width:<?=ceil($_rating->getPercent())?>%;"></div>
            		</div>
            	</div>
            <?endif;?>
            <?endforeach;?>
        <?endif;?>
        <div class="clear"></div>
        <strong><?=__('YOUR REVIEW')?></strong> ( <?=__('submitted on')?> <?=$this->dateFormat($this->getReviewData()->getCreatedAt())?>):
            <div class="description">
                <p><?=nl2br($this->getReviewData()->getDetail())?></p>
            </div>
        </div>
    </div>
    <div class="form-buttons"><a href="<?=$this->getBackUrl()?>" class="left">&laquo; <?=__('Back to My Reviews')?></a></div><br />
<?endif;?>