<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td style="width:50%;"><h3><?=__('Problem Title')?></h3></td>
			<td class="form-buttons">
			
			</td>
		</tr>
	</table>
</div>
<div>
    <?=$this->getChildHtml('grid')?>
</div>
<div class="form-buttons">
	<?=$this->getUnsubscribeButtonHtml();?>
	<?=$this->getDeleteButtonHtml();?>
</div>
<script type="text/javascript">
<!--
	var problemController = {
		checkCheckboxes: function(controlCheckbox) {
			var elements = $('problemGrid').getElementsByClassName('problemCheckbox');
			elements.each(function(obj){
				obj.checked = controlCheckbox.checked;
			});
		},
		rowClick: function (e) {
			if(!Event.element(e).hasClassName('problemCheckbox')) {
				var elements = Event.findElement(e, 'tr').getElementsByClassName('problemCheckbox');
				if(elements.length != 1) {
					return;
				}
				elements[0].checked = !elements[0].checked;
			}
		},
		
		unsubscribe: function () {
			var elements = $('problemGrid').getElementsByClassName('problemCheckbox');
			var serializedElements = Form.serializeElements(elements, true);
			serializedElements._unsubscribe = '1';
			var url = problemGridJsObject.url;
			
			new Ajax.Updater('problemGrid', url + '?ajax=1',
							 {parameters:  serializedElements,
							  evalScripts: true,
							  onComplete:problemGridJsObject.initGrid.bind(problemGridJsObject)});
		},
		
		deleteSelected: function () {
			var elements = $('problemGrid').getElementsByClassName('problemCheckbox');
			var serializedElements = Form.serializeElements(elements, true);
			serializedElements._delete = '1';
			var url = problemGridJsObject.url;
			
			new Ajax.Updater('problemGrid', url + '?ajax=1',
							 {parameters:  serializedElements,
							  evalScripts: true,
							  onComplete:problemGridJsObject.initGrid.bind(problemGridJsObject)});
		}
	}
	
	varienGlobalEvents.attachEventHandler('gridRowClick', problemController.rowClick.bind(problemController));
//-->
</script>