<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\History
 */
?>
<div class="box">
    <h2 class="sub-title"><?php echo __('Balance History'); ?></h2>

    <?php if ($history = $this->getHistory()):?>

    <?php echo $this->getChildHtml('pager') ?>

    <table id="reward-history" class="data-table">
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo __('Balance'); ?></th>
                <th><?php echo __('Amount'); ?></th>
                <th><?php echo __('Points'); ?></th>
                <th><?php echo __('Reason'); ?></th>
                <th><?php echo __('Date'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($history as $item): ?>
            <tr>
                <td class="a-right"><?php echo $this->getPointsBalance($item)?></td>
                <td class="a-right"><?php echo $this->getCurrencyBalance($item)?></td>
                <td class="a-right"><?php echo $this->getPointsDelta($item)?></td>
                <td>
                    <?php echo $this->escapeHtml($this->getMessage($item))?>
                    <?php if ($explanation = $this->getExplanation($item)):?><br /><small><?php echo $this->escapeHtml($explanation);?></small><?php endif;?>
                </td>
                <td>
                    <span class="nobr"><?php echo $this->getDate($item)?></span>
                    <?php if ($expirationDate = $this->getExpirationDate($item)):?>
                    <small class="nobr"><?php echo __('Expires on %1', $expirationDate);?></small>
                    <?php endif;?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">(function($) {$('#reward-history').decorate('table')})(jQuery)</script>

    <?php echo $this->getChildHtml('pager') ?>

    <?php else:?>

    <p><?php echo __('There is no balance history.')?></p>

    <?php endif;?>
</div>
