<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->canDisplayGiftWrapping()): ?>

<?php if ($this->getDesignCollectionCount() && ($this->getAllowForOrder() || $this->getAllowForItems() || $this->_giftWrappingAvailable)): ?>
    <script id="gift-wrapping-container" type="text/x-jQuery-tmpl">
        <div class="gift-wrapping-form">
            <label><?php echo $this->__('Gift Wrapping Design') ?></label><?php echo $this->getDesignSelectHtml() ?>
            <div class="gift-wrapping-design no-display">
                <img class="image-box" id="image-box-${_id_}" height="75" width="75" alt="" src="<?php echo $this->getViewFileUrl('images/spacer.gif')?>" />
                <div class="price-box" id="price-box-${_id_}">
                    <?php if ($this->getDisplayWrappingBothPrices()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo $this->__('Price Excl. Tax') ?>:</span>
                        <span class="price" id="price-excluding-tax-${_id_}"></span>
                    </span>
                    <span class="price-including-tax">
                        <span class="label"><?php echo $this->__('Price Incl. Tax') ?>:</span>
                        <span class="price" id="price-including-tax-${_id_}"></span>
                    </span>
                    <?php else: ?>
                    <span class="regular-price">
                        <span class="label"><?php echo $this->__('Price') ?>:</span>
                        <span class="price" id="regular-price-${_id_}"></span>
                    </span>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </script>
<?php endif;?>

<script id="gift-options-container" type="text/x-jQuery-tmpl">
    <?php if ($this->getAllowGiftReceipt()): ?>
    <p>
        <input type="checkbox" name="giftwrapping[${_id_}][allow_gift_receipt]" id="allow-gift-receipt-${_id_}" value="1" class="checkbox" />
        <label for="allow-gift-receipt-${_id_}"><?php echo $this->__('Send Gift Receipt') ?></label>
    </p>
    <?php endif;?>
    <?php if ($this->getAllowPrintedCard()): ?>
    <p>
        <input type="checkbox" name="giftwrapping[${_id_}][add_printed_card]" id="add-printed-card-${_id_}" value="1" onclick="" class="checkbox" />
        <label for="add-printed-card-${_id_}"><?php echo $this->__('Add Printed Card') ?></label>
    </p>
    <p class="price-box no-display" id="price-options-box-${_id_}">
        <?php if ($this->getDisplayCardBothPrices()): ?>
        <span class="price-excluding-tax">
                    <span class="label"><?php echo $this->__('Price Excl. Tax') ?>:</span>
                    <span class="price" id="price-card-excluding-tax-${_id_}">${price_excl_tax}</span>
                </span>
        <span class="price-including-tax">
                    <span class="label"><?php echo $this->__('Price Incl. Tax') ?>:</span>
                    <span class="price" id="price-card-including-tax-${_id_}">${price_incl_tax}</span>
                </span>
        <?php else: ?>
        <span class="regular-price">
                    <span class="label"><?php echo $this->__('Price') ?>:</span>
                    <span class="price" id="regular-card-price-${_id_}">${price}</span>
                </span>
        <?php endif;?>
    </p>
    <?php endif;?>
</script>

<script type="text/javascript">
    head.js("<?php echo $this->getViewFileUrl('jquery/jquery.tmpl.min.js')?>",
        "<?php echo $this->getViewFileUrl('Enterprise_GiftWrapping::gift-wrapping.js') ?>",
        function() {
            jQuery('#shipping_method_form').giftWrapping({
                designsInfo: <?php echo $this->getDesignsInfo()->toJson() ?>,
                itemsInfo: <?php echo $this->getItemsInfo()->toJson() ?>,
                cardInfo: <?php echo $this->getCardInfo()->toJson() ?>,
                allowForOrder: <?php echo (int)$this->getAllowForOrder() ?>,
                allowGiftReceipt: <?php echo (int)$this->getAllowGiftReceipt() ?>,
                allowPrintedCard: <?php echo (int)$this->getAllowPrintedCard() ?>,
                imgBoxSrc: '<?php echo $this->getViewFileUrl('images/spacer.gif')?>'
            });
        });
</script>
<?php endif; ?>