<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="add-by-sku">
    <div class="form-inline">
        <div class="field">
            <label class="label"><span><?php echo __('SKU\'s')?></span></label>
            <div class="control">
                <table class="data-table" id="sku_table" cellspacing="0">
                    <colgroup>
                        <col class="col-sku" />
                        <col class="col-qty" />
                        <col />
                    </colgroup>
                    <thead>
                        <tr class="headings">
                            <th><?php echo __('SKU') ?></th>
                            <th class="last"><?php echo __('Qty') ?></th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody id="sku_container">
                        <tr>
                            <td>
                                <input id="sku_0" type="text" name="sku" value="" class="input-text">
                            </td>
                            <td>
                                <div class="input-box"><input id="sku_qty_0" type="text" name="qty" value="" class="input-text qty"></div>
                            </td>
                            <td><?php echo $this->getAddButtonHtml(); ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="field add-sku-csv">
            <label class="label" for="sku_upload"><?php echo __('File') ?></label>
            <div class="control">
                <input type="file" id="sku_upload" name="<?php echo \Magento\AdvancedCheckout\Model\Import::FIELD_NAME_SOURCE_FILE ?>" value="" class="input-file" />
                <div class="note"><span><?php echo __('Your csv file must include "sku" and "qty" columns.') ?></span></div>
                <button type="button" onclick="resetUploadField()" class="button btn-reset"><span><span><span><?php echo __('Reset')?></span></span></span></button>
            </div>
            <script type="text/javascript">
                function resetUploadField() {
                    $('sku_upload').replace('<input type="file" id="sku_upload" name="<?php echo \Magento\AdvancedCheckout\Model\Import::FIELD_NAME_SOURCE_FILE ?>" value=""/>')
                }
            </script>
        </div>
    </div>
</div>
<script type="text/javascript">
require([
    "prototype",
    "Magento_AdvancedCheckout/addbysku",
    "Magento_Sales/order/create/form"
], function(){

    function initSku() {
        addBySku = new AddBySku(<?php echo $this->getJsOrderObject() ?>, <?php echo $this->getAddBySkuDataJson() ?>);
        AddBySku.prototype.add = function() {
            var id = ++this.lastId;
            $(this.dataContainerId).insert(
                '<td><input id="sku_' + id + '" type="text" value="" name="sku" class="input-text"></td>'
                    + '<td class="last"><div class="input-box"><input id="sku_qty_' + id  +'" type="text" value="" name="qty" class="input-text qty"></div></td><td>'
                    + this.deleteButtonHtml + '</td>'
            );
            var fields = $$(
                '#' + this.dataContainerId + ' #sku_' + id,
                '#' + this.dataContainerId + ' #sku_qty_' + id
            );
            for (var i = 0; i < fields.length; i++) {
                Event.observe(fields[i], 'keypress', this.formKeyPress.bind(this));
            }
        };
        <?php echo $this->getAdditionalJavascript() ?>
    }

    window.initSku = initSku;

    <?php echo $this->getContextSpecificJs(); ?>

});
</script>
