<?php
/**
 * {license_notice}
 *
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_Core_Block_Template */ ?>
<?php
/** @var $this->design Mage_Core_Model_Design_Package */
$design = $this->getDesign();
?>
<script type="text/javascript" src="<?php echo $design->getViewFileUrl('prototype/window.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $design->getViewFileUrl('prototype/windows/themes/default.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $design->getViewFileUrl('Mage_Core::prototype/magento.css') ?>"/>
<script type="text/javascript" src="<?php echo $design->getViewFileUrl('mage/edit-trigger.js') ?>"></script>
<script type="text/javascript" src="<?php echo $design->getViewFileUrl('mage/translate-inline-vde.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $design->getViewFileUrl('mage/translate-inline-vde.css') ?>"/>

<script id="translate-inline-dialog-form-template" type="text/x-jQuery-tmpl">
    <form id="${data.id}">
        {{each(i, item) data.items}}
        <input id="perstore_${i}" name="translate[${i}][perstore]" type="hidden" value="0"/>
        <input name="translate[${i}][original]" type="hidden" value="${item.scope}::${escape(item.original)}"/>
        <input id="custom_${i}" name="translate[${i}][custom]" value="${escape(item.translated)}" data-translate-input-index="${i}"/>
        {{/each}}
    </form>
</script>

<script id="translate-inline-icon" type="text/x-jQuery-tmpl">
  <img src="${img}" height="16" width="16" alt="Click to translate text." class="translate-edit-icon">
</script>

<script id="translate-inline-icon-wrapper" type="text/x-jQuery-tmpl">
  <div class="translate-edit-icon-container">
  </div>
</script>

<div id="translate-dialog"></div>

<script type="text/javascript">
    (function($){
        $(window).load(function() {
            $('body').addClass('trnslate-inline-area');

            $('body').translateInlineDialogVde({
                ajaxUrl: '<?php echo $this->getAjaxUrl() ?>',
                area: '<?php echo $design->getArea() ?>',
                onSubmitComplete: function() {
                    $('body').addClass('trnslate-inline-area');
                    $('[data-translate][translate-mode="text"]').translateInlineVde('show');
                    $('[data-translate][translate-mode="alt"]').translateInlineImageVde('show');
                },

                onCancel: function() {
                    $('body').addClass('trnslate-inline-area');
                    $('[data-translate][translate-mode="text"]').translateInlineVde('show');
                    $('[data-translate][translate-mode="alt"]').translateInlineImageVde('show');
                }
            });

            $('[data-translate][translate-mode="text"]').translateInlineVde({
                img: '<?php echo $design->getViewFileUrl('Mage_Core::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $design->getViewFileUrl('Mage_Core::translate_edit_icon_hover.png') ?>',
                onClick: function(widget) {
                    var translateData = $(widget.element).data(widget.options.dataAttrName);
                    $('body').removeClass('trnslate-inline-area');
                    $('[data-translate][translate-mode="text"]').translateInlineVde('hide');
                    $('[data-translate][translate-mode="alt"]').translateInlineImageVde('hide');
                    $('body').translateInlineDialogVde(
                        'open',
                        translateData,
                        $.proxy(widget.replaceText, widget),
                        function(translateDialog) {
                            translateDialog.dialog("option", {
                                position: { of : widget.element, my: "left top", at: "left-3 top-9" },
                                width: $(widget.element).width()
                            });
                        }
                    );
                }
            });

            $('[data-translate][translate-mode="alt"]').translateInlineImageVde({
                img: '<?php echo $design->getViewFileUrl('Mage_Core::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $design->getViewFileUrl('Mage_Core::translate_edit_icon_hover.png') ?>',
                onClick: function(widget) {
                    var translateData = $(widget.element).data(widget.options.dataAttrName);
                    $('body').removeClass('trnslate-inline-area');
                    $('[data-translate][translate-mode="text"]').translateInlineVde('hide');
                    $('[data-translate][translate-mode="alt"]').translateInlineImageVde('hide');
                    $('body').translateInlineDialogVde(
                        'open',
                        translateData,
                        $.proxy(widget.replaceText, widget),
                        function(translateDialog) {
                            translateDialog.dialog("option", {
                                position: { my: "center", at: "center", of: window },
                                width: $(widget.element).width()
                            });
                        }
                    );
                }
            });

            parent.jQuery('[vde-translate]').translateInlineToggle({});

            parent.jQuery('[translate-selected]').translateInlineToggleMode({
                frameUrl: '<?php echo $this->getFrameUrl() ?>',
                refreshVdeCanvas: <?php if ($this->getRefreshCanvas()): ?>false<?php else: ?>true<?php endif; ?>
            });
        });
    })(jQuery);
</script>
