<?php
/**
 * {license_notice}
 *
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_Core_Block_Template */ ?>
<script type="text/javascript" src="<?php echo $this->getViewFileUrl('prototype/window.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getViewFileUrl('prototype/windows/themes/default.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getViewFileUrl('Mage_Core::prototype/magento.css') ?>"/>
<script type="text/javascript" src="<?php echo $this->getViewFileUrl('mage/edit-trigger.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getViewFileUrl('mage/translate-inline-vde.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getViewFileUrl('mage/translate-inline-vde.css') ?>"/>

<script data-template="translate-inline-dialog-form-template" type="text/x-jQuery-tmpl">
    <form data-form="translate-inline-dialog-form">
        {{each(i, item) data.items}}
        <input id="perstore_${i}" name="translate[${i}][perstore]" type="hidden" value="0"/>
        <input name="translate[${i}][original]" type="hidden" value="${item.scope}::${escape(item.original)}"/>
        <textarea id="custom_${i}" name="translate[${i}][custom]" data-translate-input-index="${i}">${escape(item.translated)}</textarea>
        {{/each}}
    </form>
</script>

<script data-template="translate-inline-icon" type="text/x-jQuery-tmpl">
  <img src="${img}" height="16" width="16" class="translate-edit-icon">
</script>

<div id="translate-dialog"></div>

<div data-container="spinner" class="translate-dialog-form-submit-loader hidden">
    <img src="<?php echo $this->getViewFileUrl('images/ajax-loader-tr.gif', array('area' => 'adminhtml')) ?>"/>
</div>

<script type="text/javascript">
    (function($){
        $(window).load(function() {
            var $body = $('body');
            var $textTranslations = $('[data-translate-mode="text"]');
            var $imageTranslations = $('[data-translate-mode="alt"]');
            var $scriptTranslations = $('[data-translate-mode="script"]');

            <?php if($this->getTranslateMode()): ?>
                $body.addClass('<?php echo 'trnslate-inline-' . $this->getTranslateMode() . '-area' ?>');
            <?php endif; ?>

            /** @todo temporary fix to add data- attribute to body. */
            $body.attr("data-container", "body");

            $body.translateInlineDialogVde({
                ajaxUrl: '<?php echo $this->getAjaxUrl() ?>',
                area: '<?php echo $this->getArea() ?>',
                translateMode: '<?php echo $this->getTranslateMode() ?>',
                textTranslations: $textTranslations,
                imageTranslations: $imageTranslations,
                scriptTranslations: $scriptTranslations
            });

            $textTranslations.translateInlineVde({
                img: '<?php echo $this->getViewFileUrl('Mage_Core::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $this->getViewFileUrl('Mage_Core::translate_edit_icon_hover.png') ?>',
                translateMode: '<?php echo $this->getTranslateMode() ?>',
                onClick: function(widget) {
                    var translateData = $(widget.element).data(widget.options.dataAttrName);
                    $body.removeClass('trnslate-inline-' + widget.options.translateMode + '-area');
                    $textTranslations.translateInlineVde('hide');
                    $body.translateInlineDialogVde(
                        'open',
                        translateData,
                        $.proxy(widget.replaceText, widget),
                        function(translateDialog) {
                            translateDialog.dialog("option", {
                                position: { of : widget.element, my: "left top", at: "left-3 top-9" },
                                width: $(widget.element).width()
                            });
                        }
                    );
                }
            });

            $imageTranslations.translateInlineImageVde({
                img: '<?php echo $this->getViewFileUrl('Mage_Core::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $this->getViewFileUrl('Mage_Core::translate_edit_icon_hover.png') ?>',
                translateMode: '<?php echo $this->getTranslateMode() ?>',
                onClick: function(widget) {
                    var translateData = $(widget.element).data(widget.options.dataAttrName);
                    $body.removeClass('trnslate-inline-' + widget.options.translateMode + '-area');
                    $imageTranslations.translateInlineImageVde('hide');
                    $body.translateInlineDialogVde(
                        'open',
                        translateData,
                        $.proxy(widget.replaceText, widget),
                        function(translateDialog) {
                            translateDialog.dialog("option", {
                                position: { of : widget.element, my: "left top", at: "left-3 top-9" },
                                width: $(widget.element).width()
                            });
                        }
                    );
                }
            });

            $scriptTranslations.translateInlineScriptVde({
                img: '<?php echo $this->getViewFileUrl('Mage_Core::translate_edit_icon.png') ?>',
                imgHover: '<?php echo $this->getViewFileUrl('Mage_Core::translate_edit_icon_hover.png') ?>',
                translateMode: '<?php echo $this->getTranslateMode() ?>',
                onClick: function(widget) {
                    var translateData = $(widget.element).data(widget.options.dataAttrName);
                    $body.removeClass('trnslate-inline-' + widget.options.translateMode + '-area');
                    $scriptTranslations.translateInlineScriptVde('hide');
                    $body.translateInlineDialogVde(
                        'open',
                        translateData,
                        $.proxy(widget.replaceText, widget),
                        function(translateDialog) {
                            translateDialog.dialog("option", {
                                position: { of : widget.element, my: "left top", at: "left-3 top-9" },
                                width: $(widget.element).width()
                            });
                        }
                    );
                }
            });

            parent.jQuery('[data-translate-container]').translateInlineToggle({
                frameUrl: '<?php echo $this->getFrameUrl() ?>',
                refreshVdeCanvas: <?php if ($this->getRefreshCanvas()): ?>false<?php else: ?>true<?php endif; ?>,
                frameBody: $body
            });
        });
    })(jQuery);
</script>
