<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Directories tree template
 *
 * @see Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content
 */
?>
<script type="text/javascript">
//<![CDATA[
MediabrowserInstance = new Mediabrowser(<?php echo $this->getFilebrowserSetupObject() ?>);
MediabrowserInstance.storeId = '<?php echo $this->getStoreId() ?>';
//]]>
</script>
