<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $action ?>" method="post" id="form-validate">
<div class="fieldset">
    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label for="current_password" class="required"><em>*</em><?php echo __('Current Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text" name="current_password" id="current_password" data-validate="{required:true, 'validate-password':true}"/>
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="password" class="required"><em>*</em><?php echo __('New Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text" name="password" id="password" data-validate="{required:true, 'validate-password':true}"/>
                </div>
            </div>
            <div class="field">
                <label for="confirmation" class="required"><em>*</em><?php echo __('Confirm New Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text" name="confirmation" id="confirmation" data-validate="{required:true, equalTo:'#password'}"/>
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set form-buttons">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
    <button type="submit" class="button"><span><span><?php echo __('Save Password') ?></span></span></button>
</div>
<p class="required"><?php echo __('* Required Fields') ?></p>
</form>
<script type="text/javascript">
    head.js(
        "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
        "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
        "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
        "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>", function() {
            jQuery('#form-validate').validation();
    });
</script>
