<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form class="form password forget" action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <fieldset class="fieldset" data-hasrequired="<?php echo __('* Required Fields') ?>">
        <p class="field note"><?php echo __('Please enter your email address below. You will receive a link to reset your password.'); ?></p>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php echo __('Email Address') ?></span></label>
            <div class="control">
                <input type="text" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <?php echo $this->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions">
        <div class="primary">
            <button type="submit" class="action submit"><span><?php echo __('Submit') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $this->helper('Magento\Customer\Helper\Data')->getLoginUrl() ?>"><span><?php echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#form-validate').validation();
            });
    })(jQuery);
</script>
