<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Shopping cart totals template
 *
 * @see \Magento\Checkout\Block\Cart\Totals
 * @var $this \Magento\Checkout\Block\Cart\Totals
 */
?>
<?php if ($this->canApplyMsrp()): ?>
    <div class="cart-msrp-totals"><?php echo __('You will see the order total before you submit the order.'); ?></div>
<?php else: ?>
    <table id="shopping-cart-totals-table">
        <col />
        <col width="1" />
        <tfoot>
            <?php echo $this->renderTotals('footer'); ?>
        </tfoot>
        <tbody>
            <?php echo $this->renderTotals(); ?>
        </tbody>
    </table>
<?php endif; ?>
