<?php
/**
 * {license_notice}
 *
 * @category    Enterprise
 * @package     Enterprise_Pbridge
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<script type="text/javascript">
//<![CDATA[
    function reloadIframe(method) {
        var iframeContainer = $('payment_form_' + method + '_container');
        if (iframeContainer) {
            var hiddenElms = iframeContainer.up('li').select('input');
            if (hiddenElms) {
                hiddenElms.each(function(elm){
                    if (elm) elm.remove();
                });
            }
            new Ajax.Updater(
                iframeContainer,
                "<?php echo $this->getUrl('enterprise_pbridge/pbridge/iframe', array('_current' => true, '_secure' => true)); ?>",
                {parameters : {method_code : method},
                 onSuccess: function(transport) {
                         if (iframeContainer.previous('span.pbridge-reload') && iframeContainer.previous('span.pbridge-reload').down('a')) {
                             iframeContainer.previous('span.pbridge-reload').down('a').show();
                         }
                         toggleContinueButton(iframeContainer.up('ul'));
                     }
                }
            );
        }
    }
    function toggleContinueButton(target) {
        var buttonsContainer = $('payment-buttons-container');
        if (buttonsContainer && buttonsContainer.down('button.button')) {
            var continueButton = buttonsContainer.down('button.button');
            if (target.type != 'checkbox' || ! target.checked) {
                var checkedRadio = $$('#co-payment-form input[type="radio"][name="payment[method]"]:checked');
                if (checkedRadio.length) {
                    var iframeContainer = $('payment_form_' + checkedRadio[0].value + '_container');
                    // check whether it is Bridge payment method
                    if (iframeContainer && iframeContainer.previous('span.pbridge-reload')) {
                        return continueButton.setStyle({display:'none'});
                    }
                }
            }
            continueButton.setStyle({display:'block'});
        }
    }
//]]>
</script>
