<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="block tags">
    <div class="title">
        <strong><?php echo __('Popular Tags'); ?></strong>
    </div>
    <div class="content">
        <ul class="tags items cloud">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li class="tag item">
                    <a class="tag text" href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;" <?php echo $this->getUiId('item', $_tag->getName()) ?>><?php echo $this->escapeHtml($_tag->getName()) ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="actions">
            <a class="action view" href="<?php echo $this->getUrl('tag/list') ?>"<?php echo $this->getUiId('view','all','link') ?>><span><?php echo __('View All Tags') ?></span></a>
        </div>
    </div>
</div>
