<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if($this->customerLoggedIn()): ?>
    <li class="customer welcome">
        <strong class="customer name" data-toggle="dropdown">
            <span><?php echo $this->getCustomerName(); ?></span>
        </strong>
        <?php if($this->getChildHtml()):?>
        <nav class="menu" data-target="dropdown">
            <?php echo $this->getChildHtml();?>
        </nav>
        <?php endif; ?>
    </li>
<?php endif; ?>
