<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */

?>
<div id="iframe-warning" class="notice-msg">
    <span><?php echo __('Please do not refresh the page until you complete payment.') ?></span>
</div>
<iframe id="hss-iframe" data-container="paypal-iframe" class="paypal iframe" scrolling="no" frameborder="0" border="0"
        src="<?php echo $this->getFrameActionUrl() ?>" height="610" width="570"></iframe>
