<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Promotestore_Seo_Drawer */
?>
<form id="drawer-form">
    <article class="entry">
        <ul class="promote-actions">
            <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'sitemap', '_fragment' => 'sitemap_category-link')); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('Configure Site Map') ?></a></li>
            <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'catalog', '_fragment' => 'catalog_seo-link')); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('Search Engine Optimization') ?></a></li>
            <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'web', '_fragment' => 'web_url-link')); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('URL Redirects') ?></a></li>
        </ul>
        <div class="promote-content">
            <div class="promote-content-section">
                <p><?php echo __('There\'s no such thing as too much traffic, right? But not enough traffic is a big problem. If you\'re serious about increasing visits to your site, you need to enhance your search engine optimization (SEO).') ?> </p>
            </div>
            <div class="promote-content-section">
                <p><?php echo __('Customers are much more likely to discover your store after you add search terms and configure your site map to show up on search engines. Don\'t let competitors "out-SEO" you. Get started right here, right now.') ?> </p>
            </div>
        </div>
    </article>
</form>
