<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var \Magento\Ui\Component\Form\Element\Select $this
 */
?>
<select name="<?php echo $this->getData('index'); ?>">
    <?php foreach ($this->getData('options') as $option): ?>
        <?php if (is_array($option['value'])): ?>
            <optgroup label="<?php echo $option['label']; ?>">
                <?php foreach ($option['value'] as $subOption): ?>
                    <?php if (is_array($subOption['value'])): ?>
                        <optgroup label="<?php echo $subOption['label']; ?>">
                            <?php foreach ($subOption['value'] as $subSubOption): ?>
                                <?php if (!is_array($subSubOption['value'])): ?>
                                    <option value="<?php echo
                                        $subSubOption['value']; ?>" <?php if ($this->getIsSelected($subSubOption['value'])):?>selected="selected"<?php endif;?>><?php echo $subSubOption['label']; ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </optgroup>
                    <?php else: ?>
                        <option value="<?php echo $subOption['value']; ?>" <?php if ($this->getIsSelected($subOption['value'])):?>selected="selected"<?php endif;?>><?php echo $subOption['label']; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </optgroup>
        <?php else: ?>
            <option value="<?php echo $option['value']; ?>" <?php if ($this->getIsSelected($option['value'])):?>selected="selected"<?php endif;?>>
                <?php echo $option['label']; ?>
            </option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
<?php if ($this->getData('description')): ?>
    <label class="label" data-bind="checked: value, attr: { for: uid }">
        <span data-bind="text: description"><?php echo $this->getData('description') ?></span>
    </label>
<?php endif; ?>
<?php if ($this->getData('notice')): ?>
    <div class="note" data-bind="attr: {id: 'notice-' + uid}"><span data-bind="text: notice"><?php echo $this->getData('notice') ?></span></div>
<?php endif; ?>