<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<form class="form-horizontal" role="form">
    <div class="bs-callout bs-callout-warning col-sm-12">
        <h4><?php echo $this->translate('Did you want to use an existing or create a new database?'); ?></h4>
        <div class="radio col-sm-6">
            <label for="useExisting">
                <input type="radio" name="useExistingDb" value="0" checked>
                <?php echo $this->translate('Use my existing database'); ?>
            </label>
        </div>
        <div class="radio col-sm-6">
            <label for="useExisting">
                <input type="radio" name="useExistingDb" value="1">
                <?php echo $this->translate('Create a database for me'); ?>
            </label>
        </div>
    </div>

    <div class="form-group">
        <label for="dbHost" class="col-sm-3 control-label"><?php echo $this->translate('Database Server Host*'); ?></label>
        <div class="col-sm-9">
            <input popover-placement="right"
                popover="<?php echo $this->translate('Name and location of the server that hosts your store\'s database.'); ?>"
                popover-trigger="focus"
                class="form-control"
                style="width: 60%;"
                type="text"
                name="dbHost"
                ng-model="dbHost"
                required>
        </div>
    </div>

    <div class="form-group">
        <label for="dbUser" class="col-sm-3 control-label"><?php echo $this->translate('Database Server Username*'); ?></label>
        <div class="col-sm-9">
            <input popover-placement="right"
                   popover="<?php echo $this->translate('Sign-in credentials for your store\'s database on the database server (does not need to be admin-level credentials).'); ?>"
                   popover-trigger="focus"
                   class="form-control"
                   style="width: 60%;"
                   type="text"
                   name="dbUser"
                   ng-model="dbUser"
                   required>
        </div>
    </div>

    <div class="form-group">
        <label for="dbPassword" class="col-sm-3 control-label"><?php echo $this->translate('Database Server Password'); ?></label>
        <div class="col-sm-9">
            <input popover-placement="right"
                   popover="<?php echo $this->translate('Sign-in credentials for your store\'s database on the database server (does not need to be admin-level credentials).'); ?>"
                   popover-trigger="focus"
                   class="form-control"
                   style="width: 60%;"
                   type="text"
                   name="dbPassword"
                   ng-model="dbPassword"
                   placeholder="<?php echo $this->translate('(not always necessary)'); ?>"
                   required>
        </div>
    </div>

    <div class="form-group">
        <label for="dbName" class="col-sm-3 control-label"><?php echo $this->translate('Database Name*'); ?></label>
        <div class="col-sm-9">
            <input popover-placement="right"
                   popover="<?php echo $this->translate('Enter the name of your store\'s database.'); ?>"
                   popover-trigger="focus"
                   class="form-control"
                   style="width: 60%;"
                   type="text"
                   name="dbName"
                   ng-model="dbName"
                   required>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-5">
            <button class="btn btn-default btn-sm">
                <?php echo $this->translate('Test Connection and Authentication'); ?>
            </button>
        </div>
        <div class="col-sm-4">{{testConnection.result}}</div>
    </div>

    <div class="form-group">
        <label for="dbTablePrefix" class="col-sm-3 control-label"><?php echo $this->translate('Table prefix'); ?></label>
        <div class="col-sm-9">
            <input popover-placement="right"
                   popover="<?php echo $this->translate('Enter a tracking prefix to be used for database tables created for this Magento installation. (ex: \'mg1_\' )'); ?>"
                   popover-trigger="focus"
                   class="form-control"
                   style="width: 60%;"
                   type="text"
                   name="dbTablePrefix"
                   ng-model="dbTablePrefix"
                   placeholder="<?php echo $this->translate('(optional)'); ?>"
                   required>
        </div>
    </div>
</form>
