<?php
$passwordWizard = sprintf(
    '<p><b>%s</b> {{admin.passwordStatus.label}}</p>
        <div class=\'col-sm-12 password-strength password-strength-{{admin.passwordStatus.class}}\'>
            <div class=\'col-sm-2\'></div>
            <div class=\'col-sm-2\'></div>
            <div class=\'col-sm-2\'></div>
            <div class=\'col-sm-2\'></div>
        </div>
    <p>%s</p>',
    $this->translate('Password Strength:'),
    $this->translate('Must be a mix of at least 7 alpha and numeric characters.(Ex.: BuyIt54).')
);
?>
<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<p><?php echo $this->translate('Create a new Admin account to manage you store.'); ?></p>

<form class="form-horizontal" role="form" style="padding-top: 20px;">
    <div class="form-group">
        <label class="col-sm-3 control-label"><?php echo $this->translate('New Username'); ?><span class="required">*</span></label>
        <div class="col-sm-9">
            <input tooltip-placement="right"
                   tooltip="<?php echo $this->translate('Must be 1 to 40 characters'); ?>"
                   tooltip-trigger="focus"
                   class="form-control"
                   style="width: 60%;"
                   type="text"
                   name="adminUsername"
                   ng-model="admin.username"
                   required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label"><?php echo $this->translate('New Password'); ?><span class="required">*</span></label>
        <div class="col-sm-9">
            <input ng-change="passwordStatusChange()"
                   tooltip-placement="right"
                   tooltip-html-unsafe="<?php echo $passwordWizard; ?>"
                   tooltip-trigger="focus"
                   tooltip-append-to-body="true"
                   class="form-control"
                   style="width: 60%;"
                   type="password"
                   name="adminPassword"
                   ng-model="admin.password"
                   required>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label"><?php echo $this->translate('Confirm Password'); ?><span class="required">*</span></label>
        <div class="col-sm-9">
            <input tooltip-placement="right"
                   tooltip="<?php echo $this->translate('Please re-enter your password'); ?>"
                   tooltip-trigger="focus"
                   class="form-control"
                   style="width: 60%;"
                   type="password"
                   name="adminConfirm"
                   ng-model="admin.confirm"
                   required>
        </div>
    </div>
</form>
