<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
$passwordWizard = sprintf(
    '<p><b>%s</b> {{admin.passwordStatus.label}}</p>
        <div class=\'col-sm-12 password-strength password-strength-{{admin.passwordStatus.class}}\'>
            <div class=\'col-sm-2\'></div>
            <div class=\'col-sm-2\'></div>
            <div class=\'col-sm-2\'></div>
            <div class=\'col-sm-2\'></div>
        </div>
    <p>%s</p>',
    'Password Strength:',
    'Must be a mix of at least 7 alpha and numeric characters.(Ex.: BuyIt54).'
);
?>
<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-click="previousState()"><?php echo 'Previous'; ?></a>
    <a href="#" class="btn btn-primary" ng-click="nextState()"><?php echo 'Next'; ?></a>
</div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<p><?php echo 'Create a new Admin account to manage you store.'; ?></p>

<form novalidate name="account" class="form-horizontal" role="form" style="padding-top: 20px;">
    <div class="form-group" ng-class="{'has-error': account.adminUsername.$invalid && account.submitted}">
        <label class="col-sm-3 control-label"><?php echo 'New Username'; ?>&nbsp;<span class="required">*</span></label>
        <div class="col-sm-4">
            <input tooltip-placement="right"
                   tooltip="<?php echo 'Must be 1 to 40 characters'; ?>"
                   tooltip-trigger="focus"
                   tooltip-append-to-body="true"
                   class="form-control"
                   type="text"
                   name="adminUsername"
                   ng-model="admin.username"
                   ng-maxlength="40"
                   required />
        </div>
        <div class="col-sm-offset-3 col-sm-4" ng-show="account.adminUsername.$invalid && account.submitted">
            <div class="error-container">
                <span ng-show="account.adminUsername.$error.required"><?php echo 'Please enter your new username.'; ?></span>
                <span ng-show="account.adminUsername.$error.maxlength"><?php echo 'Please enter a username between 1 and 40 characters.'; ?></span>
            </div>
        </div>
    </div>
    <div class="form-group" ng-class="{'has-error': account.adminEmail.$invalid && account.submitted}">
        <label class="col-sm-3 control-label"><?php echo 'New E-Mail'; ?>&nbsp;<span class="required">*</span></label>
        <div class="col-sm-4">
            <input tooltip-placement="right"
                   tooltip="<?php echo 'Must be a correct e-mail'; ?>"
                   tooltip-trigger="focus"
                   tooltip-append-to-body="true"
                   class="form-control"
                   type="email"
                   name="adminEmail"
                   ng-model="admin.email"
                   required />
        </div>
        <div class="col-sm-offset-3 col-sm-4" ng-show="account.adminEmail.$invalid && account.submitted">
            <div class="error-container">
                <span ng-show="account.adminEmail.$error.required"><?php echo 'Please enter your new e-mail.'; ?></span>
                <span ng-show="account.adminEmail.$error.email"><?php echo 'Please enter a correct e-mail.'; ?></span>
            </div>
        </div>
    </div>
    <div class="form-group" ng-class="{'has-error': account.adminPassword.$invalid && account.submitted}">
        <label class="col-sm-3 control-label"><?php echo 'New Password'; ?>&nbsp;<span class="required">*</span></label>
        <div class="col-sm-4">
            <input ng-change="passwordStatusChange()"
                   tooltip-placement="right"
                   tooltip-html-unsafe="<?php echo $passwordWizard; ?>"
                   tooltip-trigger="focus"
                   tooltip-append-to-body="true"
                   class="form-control"
                   type="password"
                   name="adminPassword"
                   ng-model="admin.password"
                   required />
        </div>
        <div class="col-sm-offset-3 col-sm-4" ng-show="account.adminPassword.$invalid && account.submitted">
            <div class="error-container">
                <span ng-show="account.adminPassword.$error.required"><?php echo 'Please enter your new password.'; ?></span>
            </div>
        </div>
    </div>
    <div class="form-group" ng-class="{'has-error': account.adminConfirm.$invalid && account.submitted}">
        <label class="col-sm-3 control-label"><?php echo 'Confirm Password'; ?>&nbsp;<span class="required">*</span></label>
        <div class="col-sm-4">
            <input tooltip-placement="right"
                   tooltip="<?php echo 'Please re-enter your password'; ?>"
                   tooltip-trigger="focus"
                   tooltip-append-to-body="true"
                   class="form-control"
                   type="password"
                   name="adminConfirm"
                   ng-model="admin.confirm"
                   confirm-password="admin.password"
                   required />
        </div>
        <div class="col-sm-offset-3 col-sm-4" ng-show="account.adminConfirm.$invalid && account.submitted">
            <div class="error-container">
                <span ng-show="account.adminConfirm.$error.required"><?php echo 'Please re-enter your password.'; ?></span>
                <span ng-show="account.adminConfirm.$error.confirmPassword"><?php echo 'Please make sure your passwords match.'; ?></span>
            </div>
        </div>
    </div>
</form>

<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-click="previousState()"><?php echo 'Previous'; ?></a>
    <a href="#" class="btn btn-primary" ng-click="nextState()"><?php echo 'Next'; ?></a>
</div>
