<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-click="previousState()"><?php echo $this->translate('Previous'); ?></a>
    <a href="#" class="btn btn-primary" ng-click="nextState()"><?php echo $this->translate('Next'); ?></a>
</div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<form class="form-horizontal" role="form">
    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->translate('Sample Data'); ?></label>
        <div class="col-md-6">
            <p class="form-control-static text-muted"><?php echo $this->translate('Using sample of "fake" data can be helpful, letting you automatically build your store with fictious products, tax, and payment settings. But it also creates a lot of extra data you need to remove later. Learn the pros and cons in out <a href="#">Guide to Using Sample Data</a>.'); ?></p>
        </div>
    </div>

    <div class="form-group">
        <div class="checkbox col-md-4 col-md-offset-3">
            <label>
                <input type="checkbox" ng-model="store.useSampleData" disabled>&nbsp;<span class="text-muted"><?php echo $this->translate('Use Sample Data'); ?></span>
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->translate('Store Default Time Zone'); ?>&nbsp;<span class="required">*</span></label>
        <div class="col-md-6">
            <select class="form-control"
                    ng-model="store.timezone"
                    tooltip-placement="right"
                    tooltip-html-unsafe="<?php echo $this->translate('The time zone in which your online store operates. You can change this later in Magento Admin.'); ?>"
                    tooltip-trigger="focus"
                    tooltip-append-to-body="true">
            <?php foreach ($this->timezone as $value => $label): ?>
                <?php echo "<option value=\"" . $value . "\">" . $label . "</option>"; ?>
            <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->translate('Store Default Currency'); ?>&nbsp;<span class="required">*</span></label>
        <div class="col-md-5">
            <select class="form-control"
                    ng-model="store.currency"
                    tooltip-placement="right"
                    tooltip-html-unsafe="<?php echo $this->translate('The currency your store uses for price labeling, checkout, returns, credit and gift cards. You can change this later in Magento Admin.'); ?>"
                    tooltip-trigger="focus"
                    tooltip-append-to-body="true">
            <?php foreach ($this->currency as $value => $label): ?>
                <?php echo "<option value=\"" . $value . "\">" . $label . "</option>"; ?>
            <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-3 control-label"><?php echo $this->translate('Store Default Language'); ?>&nbsp;<span class="required">*</span></label>
        <div class="col-md-4">
            <select class="form-control"
                    ng-model="store.language"
                    tooltip-placement="right"
                    tooltip-html-unsafe="<?php echo $this->translate('The language customers will see in your store. You can change this later in Magento Set Up Tool.'); ?>"
                    tooltip-trigger="focus"
                    tooltip-append-to-body="true">
            <?php foreach ($this->language as $value => $label): ?>
                <?php echo "<option value=\"" . $value . "\">" . $label . "</option>"; ?>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
</form>

<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-click="previousState()"><?php echo $this->translate('Previous'); ?></a>
    <a href="#" class="btn btn-primary" ng-click="nextState()"><?php echo $this->translate('Next'); ?></a>
</div>
