<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-disabled="disabled" ng-click="previousState()"><?php echo $this->translate('Previous'); ?></a>
    <a href="#" class="btn btn-primary" ng-disabled="disabled" ng-click="start()" ng-show="isStart"><?php echo $this->translate('Try Again'); ?></a>
</div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<div ng-show="!isStart" class="text-center" style="padding-top: 50px; padding-bottom: 50px;">
    <p><?php echo $this->translate('You\'re ready!'); ?></p>
    <button ng-click="start()" class="btn btn-primary">Install Now</button>
</div>

<div ng-show="isStart" ng-init="errorStatus='<?php echo $this->translate('Sorry we can not install Magento right now.'); ?>'">
    <div class="progress"><div class="progress-bar progress-bar-striped" role="progressbar" aria-valuenow="{{progress}}" aria-valuemin="0" aria-valuemax="100" style="width: {{progress}}%;">{{progressText}}</div></div>
    <div ng-show="error" class="error-container">
        <span class="glyphicon glyphicon-remove-sign "></span>
        <span><?php echo $this->translate('We don\'t know the exact reason. Check the console log for errors before trying again.'); ?></span>
    </div>
    <div class="collapsed-options">
        <a href="#" class="collapsed-options" ng-click="toggleConsole()"><?php echo $this->translate('Console Log'); ?></a>
        <span class="caret"></span>
    </div>
    <div ng-show="console" id="console">
        <div class="highlight" style="background-color: #000000;"><pre ng-bind-html="log"></pre></div>
    </div>
</div>

<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-disabled="disabled" ng-click="previousState()"><?php echo $this->translate('Previous'); ?></a>
    <a href="#" class="btn btn-primary" ng-disabled="disabled" ng-click="start()" ng-show="isStart"><?php echo $this->translate('Try Again'); ?></a>
</div>