<div class="text-center">
    <h1>Magento</h1>
    <br/>
    <p>Version x.x.x</p>
    <br/>
    <br/>
    <br/>
    <p>Welcome to Magento Admin, your online store headquarters.
    Click 'Agree and Set Up Magento' or read <a href="#/getting-start">Getting Start</a> to learn more.</p>
    <br/>
    <br/>
    <br/>
    <label>Choose a language:</label>
    <select style="width: 250px; margin: 0 auto;" class="form-control"
            ng-model="language" ng-options="language.title for language in languages">
    </select>
    <br/>
    <br/>
    <br/>
    <div>
        <a href="#/terms-and-agreement">Terms & Agreement</a>
    </div>
    <br/>
    <button type="button" class="btn-lg btn-default" ng-click="nextState()">Agree and Set Up Magento</button>
</div>
