<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="col-xs-9">
    <br/>
    <a href="#" class="btn btn-primary" ng-click="nextState()"> <?php echo $this->translate('Go Back'); ?></a>
    <br/><br/>
    <?php echo nl2br(htmlspecialchars($this->license, ENT_COMPAT, 'UTF-8')); ?>
    <br/><br/><br/>
    <a href="#" class="btn btn-primary" ng-click="nextState()"> <?php echo $this->translate('Go Back'); ?></a>
    <br/><br/>
</div>
