<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="col-xs-9">
    <br/>
    <a href="#" class="btn btn-primary" ng-click="nextState()"> <?php echo $this->translate('Go Back'); ?></a>
    <br/><br/>
    <?php echo $this->license; ?>
    <br/><br/><br/>
    <a href="#" class="btn btn-primary" ng-click="nextState()"> <?php echo $this->translate('Go Back'); ?></a>
    <br/><br/>
</div>
