<div class="step-controls" ng-hide="$state.is('root.readiness-check')">
    <a href="#" class="btn btn-primary" ng-click="$state.forceReload()">Try Again</a>
    <a href="#" class="btn btn-primary" ng-click="nextState()">Next</a>
</div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<div ng-show="$state.is('root.readiness-check')" class="readiness-check-landing">
    <p><?php echo $this->translate('Let\'s check your environment for the corrent PHP version, PHP extensions, file permissions and compatibility.'); ?></p>
    <div>
        <a href="#" ng-click="$state.go('.progress')" class="btn btn-primary"><?php echo $this->translate('Start Readiness Check'); ?></a>
    </div>
</div>

<div ui-view></div>

<div class="step-controls" ng-hide="$state.is('root.readiness-check')">
    <a href="#" class="btn btn-primary" ng-click="$state.forceReload()">Try Again</a>
    <a href="#" class="btn btn-primary" ng-click="nextState()">Next</a>
</div>