<div ng-include="'controls/navbar'" ng-hide="$state.is('root.readiness-check')"></div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<div ng-show="$state.is('root.readiness-check')" >
    <p>Let's check your environment for the corrent PHP version, PHP extensions, file permissions and compatibility.</p>
    <div>
        <a href="#" ng-click="$state.go('.progress')" class="btn btn-default">Start Readiness Check</a>
    </div>
</div>

<div ui-view></div>

<div ng-include="'controls/navbar'" ng-hide="$state.is('root.readiness-check')"></div>