<style>
    .step-controls {
        padding: 10px;
        margin: 20px;
        text-align: right;
    }
    .web-conf-control {
        width: 200px;
        display: inline;
        margin-left: 20px;
    }
    .required {
        color: red;
    }
    .web-config > div.row > div {
        padding: 10px;
    }
</style>

<?php
$hints = [
    'address_web' => sprintf(
        '<div><p>%s</p><p>%s</p><p><a href=\'#\'>%s</a></p></div>',
        $this->translate('Enter the base URL that brings shoppers to your store (Ex. http://example.com/).'),
        $this->translate('We recommend not using your actual IP address when your store goes live, otherwise all your shoppers will see it.'),
        $this->translate('Detect IP Address')
    ),
    'encrypt_key' => sprintf(
        '<p>%s</p>',
        $this->translate('Key to encrypt sensitive data such as passwords and personally identifiable customer informaton in the Magento database. The encryption key is stored in [your Magento install dir]/app/etc/local.xml/')
    ),
];
?>

<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-click="previousState()"><?php echo $this->translate('Previous'); ?></a>
    <a href="#" class="btn btn-primary" ng-click="nextState()"><?php echo $this->translate('Next'); ?></a>
</div>

<div class="page-header">
    <h1>{{$state.current.header}}</h1>
</div>

<div ng-controller="webConfigurationController">
    <form role="form" class="web-config">

        <div class="row">
            <div class="col-md-3">Your Store Address<span class="required">*</span></div>
            <div class="col-md-9">
                <input type="text"
                       ng-model="address.web"
                       class="form-control web-conf-control"
                       tooltip-placement="right"
                       tooltip-html-unsafe="<?php echo $hints['address_web']; ?>"
                       tooltip-trigger="focus"
                       required />
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">Magento Admin Address<span class="required">*</span></div>
            <div class="col-md-9">
                <span>{{address.web}}</span>
                <input type="text"
                       class="form-control web-conf-control"
                       ng-model="address.admin"
                       required />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div>
                    <a href="#" ng-click="updateOnExpand(advanced)">Advanced Options</a>
                    <span class="caret"></span>
                </div>
                <div ng-show="advanced.expanded">
                    <div class="row">
                        <div class="col-md-3">HTTPS Options</div>
                        <div class="col-md-9">
                            <div class="checkbox">
                                <label for="https-options-front">Use HTTPS for Magento Storefront</label>
                                <input type="checkbox" ng-model="https.front" id="https-options-front" />
                            </div>
                            <div class="checkbox">
                                <label for="https-options-admin">Use HTTPS for Magento Admin</label>
                                <input type="checkbox" ng-model="https.admin" id="https-options-admin" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Apache Rewrites</div>
                        <div class="col-md-9">
                            <div class="checkbox">
                                <label for="rewrites-allowed">Use Web Server Apache Rewrites</label>
                                <input type="checkbox" ng-model="rewrites.allowed" id="rewrites-allowed" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Encryption Key<span class="required">*</span></div>
                        <div class="col-md-9">
                            <div class="radio">
                                <label for="enc-key-magento">I want to use a Magento generated key.</label>
                                <input type="radio" id="enc-key-magento" value="magento" ng-model="encrypt.type" value="magento" />
                            </div>
                            <div class="radio">
                                <label for="enc-key-user">I want to use my own encryption key.</label>
                                <input type="radio" id="enc-key-user" ng-model="encrypt.type" value="user" />
                            </div>
                            <div ng-show="showEncryptKey()">
                                <input type="text"
                                       class="form-control web-conf-control"
                                       ng-model="encrypt.key"
                                       tooltip-placement="right"
                                       tooltip-html-unsafe="<?php echo $hints['encrypt_key']; ?>"
                                       tooltip-trigger="focus"
                                       required />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>

<div class="step-controls">
    <a href="#" class="btn btn-primary" ng-click="previousState()"><?php echo $this->translate('Previous'); ?></a>
    <a href="#" class="btn btn-primary" ng-click="nextState()"><?php echo $this->translate('Next'); ?></a>
</div>
