<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
submittedPayments = {};
Event.observe(this.document, 'payment-method:switched', function(event){
  if (event.stopped == null) {
      toggleContinueButton(event.target);
      Event.stop(event);
  }
});
if (typeof eventsObserved == 'undefined' && $('use_customer_balance')) {
    Event.observe($('use_customer_balance'), 'click', function(event){
        toggleContinueButton(event.target);
    if (isPaymentSubmitted(payment.currentMethod)) {
        reloadIframe(payment.currentMethod);
    }
    });
    eventsObserved = true;
}
