<?if( sizeof($this->getTotals()) > 0 ):?>
    <div class="box">
        <div class="entry-edit">
            <table border="0" cellpadding="0" cellspacing="0" class="bar">
                <tr>
                <?foreach( $this->getTotals() as $_total ):?>
                    <td><div><?=$_total['label']?><br /><?=$_total['value']?></div></td>
                <?endforeach;?>
                <?if( $_grandTotal = $this->getGrandTotal() ) :?>
                    <td><div style="color:#de7011;font-weight:bold;"><?=$_grandTotal['label']?><br /><?=$_grandTotal['value']?></div></td>
                <?endif;?>
                </tr>
            </table>
        </div>
    </div>

    <div class="clear">&nbsp;</div>
<?endif;?>