<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\GiftRegistry\Block\Product\View */
?>
<?php $_product = $this->getProduct() ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart giftregisty">
    <?php if ($this->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label for="qty" class="label"><span><?php echo __('Qty:') ?></span></label>
            <div class="control">
                <input type="number" name="qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" title="<?php echo __('Qty') ?>" class="input-text qty">
            </div>
        </div>
    <?php endif; ?>
    <div class="actions">
        <button type="submit" title="<?php echo __('Add to Gift Registry') ?>" class="action primary tocart">
            <span><?php echo __('Add to Gift Registry') ?></span>
        </button>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
require(['jquery'], function($){

    $.mage.extend('validation', 'validation', 'Magento_Catalog/product/view/validation';
    
    $('#product_addtocart_form')
        .mage('validation')
        .prop('action', '<?php echo $this->getAddToGiftregistryUrl() ?>');

});
</script>

