<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_product = $this->getProduct() ?>
<?php if ($_product->isSaleable() && $this->hasOptions()):?>
<div class="bundle-actions giftregisty">
    <button id="bundle-slide" class="action primary customize" type="button"><span><?php echo __('Customize and Add to Gift Registry'); ?></span></button>
</div>
<?php endif;?>
