<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/** @var $previewModel Mage_XmlConnect_Model_Preview_Ipad */
$previewModel = Mage::helper('Mage_XmlConnect_Helper_Data')->getPreviewModel();

$title1color = $previewModel->getConfigFontInfo('Title1/color');
$categoryItemTintColor = $previewModel->getCategoryItemTintColor();
$categoryItemBackgroundColor = $previewModel->getData('conf/categoryItem/backgroundColor');

$productImage = $previewModel->getPreviewImagesUrl('ipad/product_image.jpg');
$backgroundIpadLandscapeImage = $previewModel->setOrientation(Mage_XmlConnect_Helper_Ipad::ORIENTATION_LANDSCAPE)->getBackgroundImage();
$bannerImageIpad = $previewModel->getBannerImage();
?>
<div class="ipad ipad-landscape" style="background: <?php echo $previewModel->getData('conf/body/backgroundColor'); ?>;">
    <div class="status-bar"></div>
    <div class="header-wrap" style="background-color:<?php echo $previewModel->getData('conf/navigationBar/tintColor'); ?>;">
        <div class="app-header">
            <?php echo $this->getChildHtml('tab_items'); ?>
        </div>
    </div>
    <div class="shadow"></div>
    <div class="content" style="background-image:url(<?php echo $backgroundIpadLandscapeImage; ?>)">
        <div class="app-logo" style="background-image:url(<?php echo $bannerImageIpad; ?>)"></div>
        <div class="products-list-wrap">
            <ul class="products-list">
                <li style="background-color:<?php echo $categoryItemBackgroundColor; ?>">
                    <div class="product-image"><img src="<?php echo $productImage; ?>" alt="" /></div>
                    <h4>CLOTHING</h4>
                </li>
                <li style="background-color:<?php echo $categoryItemBackgroundColor; ?>">
                    <div class="product-image"><img src="<?php echo $productImage; ?>" alt="" /></div>
                    <h4>CLOTHING</h4>
                </li>
                <li style="background-color:<?php echo $categoryItemBackgroundColor; ?>">
                    <div class="product-image"><img src="<?php echo $productImage; ?>" alt="" /></div>
                    <h4>CLOTHING</h4>
                </li>
            </ul>
        </div>
    </div>
</div>
<?php if ($this->getJsErrorMessage()) : ?>
<script type="text/javascript">
    alert('<?php echo $this->getJsErrorMessage(); ?>');
</script>
<?php endif; ?>
