<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title">
    <h1><?php echo __('Gift Registry Items') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if (count($this->getItems()) > 0): ?>
<form action="<?php echo $this->getActionUpdateUrl() ?>" method="post" id="gift-registry-items-form">
    <fieldset>
        <?php echo $this->getBlockHtml('formkey')?>
        <table id="shopping-cart-table" class="data-table">
            <col width="1" />
            <col />
            <col width="210" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
                <tr>
                    <th><span class="nobr"><?php echo __('Product') ?></span></th>
                    <th><span class="nobr"><?php echo __('Product Name') ?></span></th>
                    <th><span class="nobr"><?php echo __('Note') ?></span></th>
                    <th><span class="nobr"><?php echo __('Added On') ?></span></th>
                    <th class="a-center"><span class="nobr"><?php echo __('Qty') ?></span></th>
                    <th class="a-center"><span class="nobr"><?php echo __('Qty Fulfilled') ?></span></th>
                    <th class="a-center"><?php echo __('Delete') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">(function($) {$('#shopping-cart-table').decorate('table')})(jQuery)</script>
        <div class="buttons-set2">
            <button type="submit" class="button btn-update"><span><span><?php echo __('Update Gift Registry') ?></span></span></button>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                $('#gift-registry-items-form').validation();
            });
    })(jQuery);
</script>
<?php else: ?>
    <p><?php echo __('This gift registry has no items.') ?></p>
<?php endif ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
</div>
