<div class="content-header">
<table cellspacing="0" class="grid-header">
	<tr>
		<td style="width:50%;"><h3 class="icon-head head-customer-groups"><?=__('Customer Groups')?></h3></td>
		<td class="form-buttons">
	<button class="scalable add" onclick="window.location='<?=$createUrl?>'">
		<table cellspacing="0">
			<tr>
				<td class="tl"></td>
				<td class="tr"></td>
			</tr>
			<tr>
				<td class="ml"><span><?=__('Add New Customer Group')?></span></td>
				<td class="mr"></td>
			</tr>
			<tr>
				<td class="bl"></td>
				<td class="br"></td>
			</tr>
		</table>
	</button>
	</tr>
</table>
</div>
<div>
	<?=$this->getChildHtml('grid')?>
</div>
<script type="text/javascript">
<!--
var gridController = {
    onRowClick : function(e) {

        if( (e.srcElement && e.srcElement.tagName != 'A')
            ||
            (e.target && e.target.tagName != 'A')
           ) {
            var editHrefObjects = $(Event.findElement(e,'tr')).getElementsByClassName('edit-url');
            if(editHrefObjects.length > 0) {
                location.href = editHrefObjects[0].href;
            }
            //location.href =
        }
    }
};

varienGlobalEvents.attachEventHandler('gridRowClick', gridController.onRowClick);
//-->
</script>