<table cellspacing="0" class="data-table" id="super-product-table">
	<thead>
		<tr>

			<th>Product Name</th>
			<th>SKU</th>
			<th class="a-right">Price</th>
			<th class="a-center">Qty</th>
		</tr>
	</thead>
	<tbody>
	<?foreach ($this->getItems() as $_item):?>
		<tr>
			<td><?=$_item->getName()?></td>
			<td><?=$_item->getSku()?></td>
			<td class="a-right"><?=$_item->getFormatedPrice()?></td>
			<td class="a-center"><input type="text" class="input-text qty" name="super_group[<?=$_item->getLinkedProductId()?>]" value="<?=$this->filterQty($_item->getQty())?>"/></td>
		</tr>
	<?endforeach;?>
	</tbody>
</table>
<script type="text/javascript">decorateTable('super-product-table')</script>