<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 ?>

<?php /* @var $this \Magento\Catalog\Block\Product\Grouped\AssociatedProducts  */ ?>
<div class="entry-edit" id="<?php echo $this->getId() ?>">
    <div class="fieldset-wrapper collapsable-wrapper" id="<?php echo $this->getId() ?>-wrapper">
        <div class="fieldset-wrapper-title">
            <strong class="title" data-toggle="collapse" data-target="#<?php echo $this->getId() ?>-content">
                <span><?php echo $this->getTabLabel() ?></span>
            </strong>
        </div>
        <div class="fieldset-wrapper-content in collapse" id="<?php echo $this->getId() ?>-content">
            <fieldset class="fieldset">
                <?php echo $this->getChildHtml()?>
            </fieldset>
        </div>
    </div>
</div>
