<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Core\Block\Template */

/** @var $this \Magento\Core\Block\Template */
$_gridPopupBlock = $this->getChildBlock('catalog.product.group.grid.popup.container')->getChildBlock(
        'catalog.product.group.grid.popup'
    );
$_gridPopupBlock->setRowClickCallback('function(){}');
/** @var $_helper \Magento\Core\Helper\Data */
$_helper = $this->helper('\Magento\Core\Helper\Data');
?>
<div id="grouped-product-container">
    <div class="no-products-message">
        <?php echo __('There are no grouped products.')?>
    </div>
    <?php echo $this->getChildHtml('list'); ?>
    <div data-role="add-product-dialog" class="no-display">
        <?php echo $this->getChildBlock('catalog.product.group.grid.popup.container')->getChildHtml('catalog.product.group.grid.popup');?>
    </div>
    <button type="button" data-role="add-product">Add Products to Group</button>
    <script type="text/javascript">
        jQuery(function($) {
            head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/grouped-product.js') ?>", function() {
                $('#grouped-product-container').mage('groupedProduct', {
                    gridPopup: window.<?php echo $_gridPopupBlock->getJsObjectName() ?>
                });
            });
        });
    </script>
</div>
