<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Urlrewrites edit container
 *
 * @see \Magento\Backend\Block\Urlrewrite\Edit
 */
?>
<?php echo $this->getChildHtml() ?>

<?php if ($this->getChildBlock('form')): ?>
<script type="text/javascript">
require([
    'jquery',
    'mage/backend/form',
    'mage/backend/validation'
], function($){

    $('#edit_form').form()
        .validation({validationUrl: '<?php echo $this->getValidationUrl() ?>'});

});
</script>
<?php endif; ?>
