<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<script type="text/javascript">
//<![CDATA[
OptionTemplateCountry =
'<table cellpadding="0" cellspacing="0" class="option-header">'+
    '<thead>'+
    '<tr>'+
        '<th><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Show Region') ?></th>'+
    '</tr>'+
    '</thead>'+
    '<tr>'+
        '<td><?php echo $this->getRegionShowSelectHtml() ?></td>'+
    '</tr>'+
'</table>';

selectCountryType = {
    add : function(data) {
        if (data.show_region) {
            $A($(data.prefix+'_attribute_'+data.id+'_show_region').options).each(function(option){
                if (option.value==data.show_region) option.selected = true;
           });
        }
    }
}
//]]>
</script>
