<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     pro_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see Enterprise_GiftCardAccount_Block_Account_Redeem
 */
?>
<?php if ($this->canRedeem()): ?>
<div class="box-account">
    <div class="box-head">
        <h2><?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('Redeem Gift Card'); ?></h2>
    </div>
    <p><?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('Have a gift card? <a href="%1">Click here</a> to redeem it.', Mage::getUrl('enterprise_giftcardaccount/customer')); ?></p>
</div>
<?php endif; ?>
