<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Cardgate
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var Mage_Cardgate_Block_Redirect $this */
?>
<?php echo __('You will be redirected to CardGatePlus to finish your payment.'); ?>
<?php echo $this->getForm(); ?>
<script type="text/javascript">document.getElementById("cardgateplus_checkout").submit();</script>
