<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\RecurringPayment\Block\Checkout\Onepage\Success */ ?>
<?php if ($payments = $this->getRecurringPayments()): ?>
    <p><?php echo __('Your recurring payments:'); ?></p>
    <ul>
    <?php foreach ($payments as $payment): ?>
        <?php $paymentIdHtml = $this->getCanViewPayments()
            ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getPaymentUrl($payment)), $this->escapeHtml($this->getObjectData($payment, 'reference_id')))
            : $this->escapeHtml($this->getObjectData($payment, 'reference_id')); ?>
        <li><?php echo __('Payment # %1: "%2".', $paymentIdHtml, $this->escapeHtml($this->getObjectData($payment, 'schedule_description'))) ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
