<?php
/**
 * {license_notice}
 *
 * @category    Enterprise
 * @package     Enterprise_Pbridge
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<button id="btn-pay-now" type="submit" title="<?php echo Mage::helper('Enterprise_Pbridge_Helper_Data')->quoteEscape($this->__('Pay Now')) ?>" class="button btn-checkout" onclick="preLoadReviewIframe();"><span><span><?php echo $this->__('Pay Now') ?></span></span></button>
