<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * Invitaion view block template
 *
 * @see \Magento\Invitation\Block\Adminhtml\Invitation\View
 */
?>
<form id="invitation-elements" action="<?php echo $this->getSaveMessageUrl(); ?>" method="POST">
<?php echo $this->getBlockHtml('formkey')?>
</form>

<script type="text/javascript">
require(['jquery', 'mage/mage'], function(jQuery){

    jQuery('#invitation-elements').mage('form').mage('validation');

});
</script>
