<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h1>Magneto Setup Tool</h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked" ng-controller="navigation">
            <li><a href="#">License</a></li>
            <li><a href="#">Check environment</a></li>
            <li><a href="#">Access to Database</a></li>
            <li><a href="#">Configuration Magento</a></li>
            <li><a href="#">Add admin user</a></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div ng-controller="main" class="well">
            <div style="height:600px; overflow-y: scroll;" ng-bind-html="content"></div>
        </div>
        <div ng-controller="continue" class="page-bottm">
            <div class="col-sm-offset-10 col-sm-12">
                <button class="btn btn-default">{{text}}</button>
            </div>
        </div>
    </div>
</div>
