<?php

$this->inlineScript()->appendScript(
    "app.config(function (\$stateProvider) { " . $this->stateProvider . " });",
    'text/javascript'
);
?>

<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <h1>Magento Setup Tool</h1>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-3" id="menu">
        <nav ng-controller="navigationController">
            <div>
                <ul class="nav nav-pills nav-stacked">
                    <?php foreach ($this->nav as $item): ?>
                    <li id="<?php echo $item['id']; ?>">
                        <a ui-sref="<?php echo $item['id']; ?>" href="#/<?php echo $item['url']; ?>"><?php echo $item['title']; ?></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container col-md-9" ng-controller="mainController" id="main">
        <div ui-view></div>
    </div>
</div>

