<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
    <div class="form-subscribe">
    <div class="form-subscribe-header">
        <label for="newsletter"><?php echo __('Sign Up for Our Newsletter:') ?></label>
    </div>
        <div class="v-fix"><input name="email" type="text" id="newsletter" class="input-text required-entry validate-email" placeholder="Enter your email" /></div>
        <button type="submit" class="button" title="<?php echo __('Subscribe') ?>"><span><span><?php echo __('Subscribe') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
//]]>
</script>
