    <?=$this->getMessagesBlock()->getHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend>Change Account Password</legend>
        <ul>
            <li>
                <div class="input-box">
                    <label for="current_password">Current Password <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry input-text" name="current_password" id="current_password"/>
                </div>
                        </li>
            <li>
                <div class="input-box">
                    <label for="password">New Password <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry validate-password input-text" name="password" id="password"/>
                </div>
                <div class="input-box">
                    <label for="confirmation">Confirm New Password <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry validate-cpassword input-text" name="confirmation" id="confirmation"/>
                </div>
            </li>
        </ul>
    </fieldset>
    <div class="form-buttons">
        <p class="required">* Required Fields</p>
        <a href="<?=$baseUrl?>customer/account/" class="float-left">&laquo; Back</a>
        <button class="form-button" type="submit"><span>Save Password</span></button>
    </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate');
    </script>