    <div class="page-head">
			<h3>Forgot your password?</h3>
		</div><?=$this->getMessagesBlock()->getGroupedHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
        <fieldset>
				<legend>Retrieve your password here</legend>
        <p>Please enter your email below and we'll send you a new password.</p>
        <ul class="form-list">
            <li>
                <div class="input-box"><label for="email_address">Email Address <span class="required">*</span></label><br/>
                <input name="email" alt="email"  type="text" id="email_address" class="required-entry validate-email input-text"></div></li>
        </ul>
    <div class="form-buttons">
        <p class="required">* Required Fields</p>
        <a href="<?=$baseUrl?>customer/account/" class="left">&laquo; Back to Login</a>
        <button class="form-button right"><span>Submit</span></button>
    </div>        
		</fieldset>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
    </script>