<?
/**
 * Customer login form template
 * 
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="page-head">
    <h3>Login or Create an Account</h3>
</div>
<?=$this->getMessagesBlock()->getHtml()?>
<form action="<?=$this->getPostActionUrl()?>" method="post" id="login-form">
<div class="col2-set login-box">
	<div class="col-1 new-users">
		<div class="content">
			<h4>New Customers</h4>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas gravida augue eget ipsum. Nulla facilisi. Nulla nulla mauris, placerat nec, gravida iaculis, feugiat eget, sapien. Nulla magna erat, gravida at, egestas ut, sodales vitae, ante. Vestibulum ut turpis sit amet ante fermentum scelerisque.</p>
		</div>
		<div class="form-buttons">
			<a class="form-button right" onclick="window.location='<?=$this->getCreateAccountUrl()?>';" type="button"><span>Create an Account</span></a>
		</div>
	</div>
	<div class="col-2 registered-users">
		<div class="content">
			<h4>Registered Customers</h4>
			<p>If you have an account with us, please log in.</p>
			<ul class="form-list">
					<li>
                        <label for="email">Your Email Address <span class="required">*</span></label><br/>
                        <input name="login[username]" value="<?=$this->getUsername()?>" title="email" id="email" type="text" class="input-text required-entry" style="width:250px;"/>
                    </li>
                    <li>
                        <label for="pass">Your Password <span class="required">*</span></label><br/>
                        <input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" style="width:250px;"/>
                    </li>
				</ul>
                <p class="required">* Required Fields</p>
	</div>
	<div class="form-buttons">
		<a href="<?=$this->getForgotPasswordUrl()?>" class="left">Forgot your password?</a>
		<a class="form-button" name="send" id="send2"><span>Login</span></a>
	</div>
</div>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('login-form', true);
</script>