	<fieldset class="newsletter">
		<h2 class="accent"><?=__('Newsletter')?></h2>
		<form action="<?=$baseUrl?>newsletter/subscriber/new" method="post" id="newsletter-validate">
				<fieldset>
						<legend><?=__('Newsletter')?></legend>
						<label for="newsletter">Sign up for our newsletter:</label>
						<input name="email" id="newsletter" type="text" class="required-entry validate-email input-text"/>
						<input type="submit" value="Submit" alt="Subscribe" class="input-button"/>
				</fieldset>
		</form>
        <script type="text/javascript">
        <!--
            var newsletterSubscriberForm = new VarienForm('newsletter-validate');
        //-->
        </script>
	</fieldset>