<div class="page-head">
	<h3>Newsletter Subscription</h3>
</div>
<?=$this->getMessagesBlock()->getHtml()?>
<form action="<?=$this->getAction()?>" method="post" id="form-validate">
	<p><input type="checkbox" name="is_subscribed" value="1" title="<?=__('General Subscription')?>"  <?if($this->getIsSubscribed()):?> checked<?endif?>/> <label for="subscription"><?=__('General Subscription')?></label></p>
<div class="form-buttons">
    <a href="<?=$baseUrl?>customer/account/" class="left">&laquo; Back</a>
    <button type="submit" class="form-button"><span>Save</span></button>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>
