<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<button data-role="review-save" type="submit" title="<?php echo Mage::helper('Magento_Checkout_Helper_Data')->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo Mage::helper('Magento_Checkout_Helper_Data')->__('Place Order') ?></span></span></button>
