<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see \Magento\Checkout\Block\Cart\Totals
 */
?>
<?php if ($this->getTotals()): ?>
    <?php $_colspan = $this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 5 : 3; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr class="totals charge">
        <td class="mark" colspan="<?php echo $_colspan; ?>">
            <?php echo __('Your credit card will be charged for') ?>
        </td>
        <td class="amount">
            <?php echo $this->displayBaseGrandtotal() ?>
        </td>
    </tr>
    <?php endif?>
<?php endif; ?>
