<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * New Customer block template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<?php if ($this->helper('Mage_Customer_Helper_Data')->isRegistrationAllowed()): ?>
<div class="block new customer">
    <div class="title"><strong><?php echo __('New Customers') ?></strong></div>
    <div class="content">
        <p><?php echo __('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
        <div class="actions">
            <a href="<?php echo $this->getCreateAccountUrl() ?>" class="action create"><span><?php echo __('Register') ?></span></a>
        </div>
    </div>
</div>
<?php endif; ?>

