<?/*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <title><?=__('Magento Admin')?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf8"/>
    <script type="text/javascript" src="<?=$baseJsUrl?>prototype/prototype.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>scriptaculous/scriptaculous.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>prototype/validation.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/hash.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/events.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/loader.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/grid.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/tabs.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/form.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/accordion.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/tools.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/iehover-fix.js"></script>

    <script type="text/javascript">
        var BASE_URL = '<?=$baseUrl?>adminhtml/';
        var SKIN_URL = '<?=$this->getSkinUrl()?>';
    </script>

    <style type="text/css" media="all">
        /*<![CDATA[*/ @import "<?=$this->getSkinUrl('styles.css')?>"; /*]]>*/
    </style>
    <!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('iestyles.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('ie7.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]><script defer type="text/javascript" src="<?=$baseUrl?>js/lib/ds-sleight.js"></script><![endif]-->

    <link rel="stylesheet" type="text/css" media="screen, projection" href="<?=$this->getSkinUrl('menu.css')?>"/>
<?//if($this->getCanLoadCalendarJs()):?>
    <link rel="stylesheet" type="text/css" media="all" href="<?=$baseJsUrl?>calendar/calendar-win2k-1.css" title="win2k-1" />
    <script type="text/javascript" src="<?=$baseJsUrl?>calendar/calendar.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>calendar/lang/calendar-en.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>calendar/calendar-setup.js"></script>
<?//endif;?>

<?if($this->getCanLoadExtJs()):?>
    <script type="text/javascript" src="<?=$baseJsUrl?>extjs/ext-tree.js" ></script>
    <link rel="stylesheet" type="text/css" href="<?=$baseJsUrl?>extjs/resources/css/ext-all.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$baseJsUrl?>extjs/resources/css/ytheme-magento.css"/>
    <script type="text/javascript">
        Ext.BLANK_IMAGE_URL = '<?=$baseJsUrl?>extjs/resources/images/default/s.gif';
        Ext.UpdateManager.defaults.loadScripts = false;
        Ext.UpdateManager.defaults.disableCaching = true;
    </script>
<?endif;?>
</head>
<body>
<table cellspacing="0" width="100%">
    <tr>
        <td class="header">
        <?=$this->getChildHtml('header')?>
        <div class="clear"></div>
        <?=$this->getChildHtml('menu')?>
        </td>
    </tr>
    <tr>
        <td class="middle">
            <?=$this->getChildHtml('breadcrumbs')?>
                <?if($this->getChildHtml('left')):?>
                <div class="container">
                    <div class="main">
                        <div class="content-container">
                            <div class="content" id="content">
                                <?=$this->getMessagesBlock()->getHtml()?>
                                <?=$this->getChildHtml('content')?>
                            </div>
                        </div>
                        <div class="section-menu">
                            <?=$this->getChildHtml('left')?>
                            <div class="bottom"></div>
                        </div>
                    </div>
                </div>
                <?else:?>
                <div class="simple-container">
                    <?=$this->getMessagesBlock()->getHtml()?>
                    <?=$this->getChildHtml('content')?>
                </div>
                <?endif;?>
        </td>
    </tr>
    <tr>
        <td class="footer">
            <?=$this->getChildHtml('footer')?>
        </td>
    </tr>
<table>
<?//=$this->getChildHtml('profiler')?>
<div id="loading-process" style="display:none"><img src="<?=$this->getSkinUrl('images/ajax-loader-tr.gif')?>" alt="Loading..." align="absmiddle" height="16"/></div>
</body>
</html>
