<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php if ($this->canUseCustomerBalance()): ?>
    <input id="p_method_use_customerbalance" value="1" name="payment[use_customer_balance]" type="checkbox" title="<?php echo __('Store Credit') ?>" onclick="" <?php if ($this->getUseCustomerBalance()): ?>checked<?php endif; ?> />
    <label for="p_method_use_customerbalance"><?php echo __('Use Store Credit (%1 available)', $this->formatPrice($this->getBalance(true))) ?></label>
    <script type="text/javascript">
        function toggleUseCustomerBalance()
        {
            value = ($('p_method_use_customerbalance').checked ? 1 : 0);
            var data = {};
            data['payment[use_customer_balance]'] = value;

            order.loadArea(['totals', 'billing_method'], true, data);
        }
        Event.observe($('p_method_use_customerbalance'), 'click', toggleUseCustomerBalance);
        Event.observe(document, 'dom:loaded', toggleUseCustomerBalance);
    </script>
<?php endif; ?>
