<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo $this->escapeHtml($this->getDescription())?>"/>
<meta name="keywords" content="<?php echo $this->escapeHtml($this->getKeywords())?>"/>
<meta name="robots" content="<?php echo $this->escapeHtml($this->getRobots())?>"/>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon"/>

<script src="<?php echo $this->getViewFileUrl('jquery/jquery.js') ?>"></script>
<script src="<?php echo $this->getViewFileUrl('Magento_Doc::jumly/coffee-script.js') ?>"></script>
<script src="<?php echo $this->getViewFileUrl('Magento_Doc::jumly/jumly.min.js') ?>"></script>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->getIncludes() ?>
<?php echo $this->getTranslatorScript(); ?>
