<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td style="width:50%;"><h3><?=__('Newsletter Templates')?></h3></td>
			<td class="form-buttons">
				<button class="scalable" onclick="window.location='<?=$baseUrl?>adminhtml/newsletter_template/new'">
					<table cellspacing="0">
						<tr>
							<td class="tl"></td>
							<td class="tr"></td>
						</tr>
						<tr>
							<td class="ml"><?=__('Create Template');?></td>
							<td class="mr"></td>
						</tr>
						<tr>
							<td class="bl"></td>
							<td class="br"></td>
						</tr>
					</table>
				</button>
			</td>
		</tr>
	</table>
</div>
<div>
    <?=$this->getChildHtml('grid')?>
</div>