<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>



<!--// Order/Create/Form/Addresses -->
<?if($this->getIsShipping()):
    $_fieldsContainerId = 'order:shipping_address_fields';
    ?>
    <script type="text/javascript">
    order.shippingAddressContainer = '<?=$_fieldsContainerId?>';
    order.setAddresses(<?=$this->getAddressCollectionJson()?>);
    </script>
    <?
else:
    $_fieldsContainerId = 'order:billing_address_fields';
    ?>
    <script type="text/javascript">
    order.billingAddressContainer = '<?=$_fieldsContainerId?>';
    </script>
    <?
endif;?>
<div class="entry-edit">
    <h4 class="icon-head <?=$this->getHeaderCssClass()?>"><?=$this->getHeaderText()?></h4>

    <fieldset class="np">
    <div class="order-choose-address">
        <?//if($this->getAddressCollection()->getSize()):?>
        <p><?=Mage::helper('sales')->__('Select from existing customer addresses:')?><br/>
        <?$_id = $this->getForm()->getHtmlIdPrefix() . 'customer_address_id'?>
        <select id="<?=$_id?>" style="width:95%;" onchange="order.selectAddress(this.value, '<?=$_fieldsContainerId?>')">
            <option value=""><?=Mage::helper('sales')->__('Add New Address')?></option>
            <?foreach ($this->getAddressCollection() as $_address):?>
            <option value="<?=$_address->getId()?>"<?if($_address->getId()==$this->getAddressId()):?> selected<?endif?>>
                <?=$this->getAddressAsString($_address)?>
            </option>
            <?endforeach;?>
        </select>
        </p>
        <?//endif;?>
        <?if($this->getIsShipping()):?>
            <input type="checkbox" id="order:shipping_same_as_billing" name="shipping_same_as_billing" onchange="order.setShippingAsBilling(this.checked)" <?if($this->getIsAsBilling()):?>checked<?endif;?>/>
            <label for="order:shipping_same_as_billing" class="no-float"><?=Mage::helper('sales')->__('Same As Billing Address')?></label>
        <?else:?>
            &nbsp;
        <?endif;?>
    </div>

    <div class="content order-address" id="<?=$_fieldsContainerId?>">
        <?=$this->getForm()->toHtml()?>
    </div>
    <script type="text/javascript">
        order.bindAddressFields('<?=$_fieldsContainerId?>')
        <?if($this->getIsShipping() && $this->getIsAsBilling()):?>
        order.disableShippingAddress(true);
        <?endif;?>
    </script>
    </fieldset>
</div>

<!--// [close] Order/Create/Form/Addresses -->