<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>



<!--// Order/Create/Form/Addresses -->
<?php if($this->getIsShipping()):
    $_fieldsContainerId = 'order:shipping_address_fields';
    ?>
    <script type="text/javascript">
    order.shippingAddressContainer = '<?php echo $_fieldsContainerId ?>';
    order.setAddresses(<?php echo $this->getAddressCollectionJson() ?>);
    </script>
    <?php 
else:
    $_fieldsContainerId = 'order:billing_address_fields';
    ?>
    <script type="text/javascript">
    order.billingAddressContainer = '<?php echo $_fieldsContainerId ?>';
    </script>
    <?php 
endif; ?>
<div class="entry-edit">
    <h4 class="icon-head <?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderText() ?></h4>

    <fieldset class="np">
    <div class="order-choose-address">
        <?php //if($this->getAddressCollection()->getSize()): ?>
        <p><?php echo Mage::helper('sales')->__('Select from existing customer addresses:') ?><br/>
        <?php $_id = $this->getForm()->getHtmlIdPrefix() . 'customer_address_id' ?>
        <select id="<?php echo $_id ?>" style="width:95%;" onchange="order.selectAddress(this.value, '<?php echo $_fieldsContainerId ?>')">
            <option value=""><?php echo Mage::helper('sales')->__('Add New Address') ?></option>
            <?php foreach ($this->getAddressCollection() as $_address): ?>
            <option value="<?php echo $_address->getId() ?>"<?php if($_address->getId()==$this->getAddressId()): ?> selected<?php endif ?>>
                <?php echo $this->getAddressAsString($_address) ?>
            </option>
            <?php endforeach; ?>
        </select>
        </p>
        <?php //endif; ?>
        <?php if($this->getIsShipping()): ?>
            <input type="checkbox" id="order:shipping_same_as_billing" name="shipping_same_as_billing" onchange="order.setShippingAsBilling(this.checked)" <?php if($this->getIsAsBilling()): ?>checked<?php endif; ?>/>
            <label for="order:shipping_same_as_billing" class="no-float"><?php echo Mage::helper('sales')->__('Same As Billing Address') ?></label>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </div>

    <div class="content order-address" id="<?php echo $_fieldsContainerId ?>">
        <?php echo $this->getForm()->toHtml() ?>
    </div>
    <script type="text/javascript">
        order.bindAddressFields('<?php echo $_fieldsContainerId ?>')
        <?php if($this->getIsShipping() && $this->getIsAsBilling()): ?>
        order.disableShippingAddress(true);
        <?php endif; ?>
    </script>
    </fieldset>
</div>

<!--// [close] Order/Create/Form/Addresses -->