<div class="box mini-product-tags">
    <div class="head">
        <span class="corner"></span>
        <h3><span><?=__('Popular tags');?></span></h3>
    </div>
    <div class="box-container">
        <div class="content">
            <ul>
                <?foreach ($this->getTags() as $_tag):?>
                    <li><a href="<?=$baseUrl?>" style="font-size:<?=$_tag->getRatio()*210+40?>%;"><?=$_tag->getName()?></a></li>
                <?endforeach;?>
            </ul>
        </div>
    </div>
</div>