<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <?php echo $this->getBackButtonHtml() ?>
    <?php echo $this->getResetButtonHtml() ?>
    <span class="hidden" id="formButtons">
        <?php echo $this->getSaveButtonHtml() ?>
    </span>
</div>
<div class="hidden" id="formContainer">
    <?php echo $this->getFormHtml() ?>
</div>
<script type="text/javascript">
   jQuery('#edit_form').mage('form').mage('validation');
</script>
