<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this Magento_Catalog_Block_Product_View_Options_Type_Select */ ?>
<?php $_option = $this->getOption(); ?>
<div class="field<?php if ($_option->getIsRequire()) echo ' required' ?>">
	<label class="label"><?php echo  $this->escapeHtml($_option->getTitle()) ?></label>
	<div class="control">
        <?php echo $this->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == Magento_Catalog_Model_Product_Option::OPTION_TYPE_RADIO || $_option->getType() == Magento_Catalog_Model_Product_Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
	</div>
</div>
