<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php if ($this->getEnabled()): ?>
<div class="gift-registry-name">
    <span class="gift-registry-name-label">Gift Registry</span>
    <a href="<?php echo $this->getGiftregistryUrl() ?>" title="<?php echo $this->getGiftregistryTitle() ?>" class="action gift registry"><span><?php echo $this->truncateString($this->getGiftregistryTitle(), 50) ?></span></a>
</div>
<?php endif; ?>
