<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Template for Mage_Adminhtml_Block_Widget_Accordion
 */
?>
<dl id="<?php echo $this->getHtmlId() ?>" class="accordion">
<?php foreach ($this->getItems() as $_item): ?>
    <?php echo $this->getChildHtml($_item->getId()) ?>
<?php endforeach ?>
</dl>
<script type="text/javascript">
    <?php echo $this->getHtmlId() ?>AccordionJs = new varienAccordion('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getShowOnlyOne() ?>');
</script>
