<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Shoping cart sidebar
 *
 * @see \Magento\Checkout\Block\Cart\Sidebar
 */
?>

<div class="top-cart">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <?php if ($_cartQty > 0): ?>
    <?php $_myCart = __('My Cart (%1)', '<span>' . $_cartQty . '</span>') ?>
    <?php else: ?>
    <?php $_myCart = __('My Cart (%1)', '<span>0</span>') ?>
    <?php endif ?>
    <?php if ($this->getIsLinkMode() || !$this->getIsNeedToDisplaySideBar()): ?>
    <div class="block-title no-items">
        <ul class="links cart-link">
            <li><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $_myCart ?></a></li>
        </ul>
    </div>
    <?php else: ?>
    <div class="block-title<?php if (!$_cartQty) {
        echo (' no-items');
    } ?>">
        <strong id="cartHeader"><?php echo $_myCart ?></strong>
    </div>
    <div id="topCartContent" class="block-content" style="display:none">
        <div class="inner-wrapper"><?php // extra div to smooth slideUp and slideDown ?>
            <?php $_items = $this->getRecentItems() ?>
            <?php if (count($_items)): ?>
                <p class="block-subtitle">
                    <span class="close-btn"><?php echo __('Close'); ?></span>
                    <?php echo __('Recently added item(s)') ?>
                </p>
                <ol id="mini-cart" class="mini-products-list">
                    <?php foreach ($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach; ?>
                </ol>

                <?php else: ?>
                <p class="block-subtitle">
                    <span class="close-btn"><?php echo __('Close'); ?></span>
                    <?php echo __('Recently added item(s)') ?>
                </p>
                <p class="cart-empty">
                    <?php echo __('You have no items in your shopping cart.') ?>
                </p>
                <?php if ($this->getCartEmptyMessage()): ?>
                    <p class="cart-empty cart-empty-message"><?php echo $this->getCartEmptyMessage(); ?></p>
                    <?php endif; ?>
                <?php endif ?>
            <?php if ($_cartQty || $this->getAllowCartLink()): ?>
                <?php $isPossibleOnepageCheckout = $_cartQty && $this->isPossibleOnepageCheckout() ?>
                <?php if ($isPossibleOnepageCheckout): ?>
                    <p class="subtotal">
                        <?php if ($this->canApplyMsrp()): ?>
                        <span
                            class="map-cart-sidebar-total"><?php echo __('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                        <?php else: ?>
                        <span
                            class="label"><?php echo __('Cart Subtotal:') ?></span> <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($this->getSubtotal()) ?><?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                            / <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_subtotalInclTax) ?> <?php echo $this->helper('Magento\Tax\Helper\Data')->getIncExcText(true) ?><?php endif; ?>
                        <?php endif; ?>
                    </p>
                    <?php endif ?>
                <div class="actions">
                    <?php if ($isPossibleOnepageCheckout): ?>
                    <?php echo $this->getChildHtml('extra_actions') ?>
                    <button id="top-cart-btn-checkout" class="button" type="button" title="<?php echo __('Checkout') ?>">
                        <span><span><?php echo __('Checkout') ?></span></span></button>
                    <?php endif ?>
                    <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo __('Go to Shopping Cart') ?></span></a>
                </div>
                <?php endif ?>
        </div>
    </div>
    <script type="text/javascript">
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('Magento_Checkout::js/sidebar.js') ?>",
                "<?php echo $this->getViewFileUrl('js/checkout-topcart.js') ?>", function() {
                    $('#mini-cart').sidebar({
                        checkoutUrl: '<?php echo $this->getCheckoutUrl();?>',
                        checkoutButton: '#top-cart-btn-checkout',
                        removeButton: 'a[title=\'' + '<?php echo __('Remove item')?>' + '\']',
                        confirmMessage: '<?php echo __('Are you sure you would like to remove this item from the shopping cart?') ?>'
                    });
                    $('#topCartContent').topCart({closeSelector: '.close-btn'});
                });
        })(jQuery);
    </script>
    <?php endif;?>
</div>
