<?=$this->getGridParentHtml()?>
<?if($this->canDisplayContainer()):?>
<script type="text/javascript">
var cartControl = {
	removeItem: function (itemId) {
		if(!confirm('<?=__('Are You Sure?')?>')) {
			return false;
		}
		<?=$this->getJsObjectName()?>.reloadParams = {delete:itemId}
		<?=$this->getJsObjectName()?>.reload();
		<?=$this->getJsObjectName()?>.reloadParams = {};
        return false;
	}
}
</script>
<?endif?>