<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<footer>
    <?php echo $this->getChildHtml() ?>
</footer>
<address class="copyright"><span class="logo"><img src="<?php echo $this->getViewFileUrl($this->getConfig('design/header/logo_src'))?>" width="21" alt=""/></span><?php echo $this->getCopyright() ?></address>
