<span data-m2-init='{"Magento_Cms/js/filter/component": ""}' data-part="search">
    <form>
        <input type="text" class="filter-search" placeholder="Search"
               data-bind="autocomplete: { data: suggestions, writeTo: query }, value: rawQuery, valueUpdate: 'afterkeydown'"/>
        <button class="action-search" type="submit" data-bind="click: search"><span>Search</span></button>
    </form>
</span>
