<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Downloadable product type
 *
 * @see Magento_Downloadable_Block_Catalog_Product_View_Type
 */
?>
<?php $_product = $this->getProduct() ?>

<?php if($_product->getIsSalable()): ?>
    <p class="availability in-stock"><?php echo __('Availability') ?>: <span><?php echo __('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo __('Availability') ?>: <span><?php echo __('Out of stock') ?></span></p>
<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php echo $this->getPriceHtml($_product) ?>
<?php echo $this->getChildHtml('samples') ?>
