<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <?php echo $this->getBackButtonHtml() ?>
    <?php echo $this->getResetButtonHtml() ?>
    <?php echo $this->getSaveButtonHtml() ?>
</div>
<?php if ($form): ?>
<?php echo $form->toHtml(); ?>
<script type="text/javascript">
    jQuery('#<?php echo $form->getForm()->getId() ?>').mage('form').mage('validation');
</script>
<?php endif; ?>
