<ul>
    <li><a href="<?=$baseUrl?>">About Magento Store</a></li>
	<li><a href="<?=$baseUrl?>">Careers</a></li>
	<li><a href="<?=$baseUrl?>">Privacy and Security</a></li>
	<li><a href="<?=$baseUrl?>">Returns and Shipping</a></li>
	<li><a href="<?=$baseUrl?>">Terms and Conditions</a></li>
    <li><a href="<?=$baseUrl?>">Customer Service</a></li>
    <li><a href="<?=$baseUrl?>sitemap/">Site Map</a></li>
    <li><a href="<?=$baseUrl?>catalog/search/advanced/">Advanced Search</a></li>
</ul>

