<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
				<h1 id="logo"><a href="<?=$baseUrl?>"><img src="<?=$this->getLogoSrc()?>" alt="<?=$this->getLogoAlt()?>"/></a></h1>
				<p class="this-is-a-demo"><strong>This is a demo store. Any orders placed through this store will not be logged or fulfilled.</strong></p>
				<p class="no-show"><a href="#main"><strong>Skip to main content &raquo;</strong></a></p>
<!-- // .quick-access -->
				<div class="quick-access">
					<div class="account-access">
						<p><strong><?=$this->getWelcome()?></strong></p>
                        <?=$this->getChildHtml('topLeftLinks')?>
					</div>
					<div class="shop-access">
						<p class="cart-count">These are currently <strong>3 items</strong> in your cart.</p>
                        <?=$this->getChildHtml('topRightLinks')?>
					</div>
				</div>
				<div class="clear"></div>
<!-- [ends] .quick-access // -->
                <?=$this->getChildHtml('topMenu')?>
				<div class="header-sub">
                <!-- [start] breadcrumbs -->
                    <?=$this->getChildHtml('breadcrumbs')?>
                <!-- [end] breadcrumbs -->
                    <?=$this->getChildHtml('topSearch')?>
				</div>


