<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<a class="action multicheckout" href="<?php echo $this->getCheckoutUrl()?>" title="<?php echo Mage::helper('Mage_Checkout_Helper_Data')->__('Checkout with Multiple Addresses');?>"><?php echo Mage::helper('Mage_Checkout_Helper_Data')->__('Checkout with Multiple Addresses');?></a>
