<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $test \Magento\Customer\Block\Address\Book
 */
?>
<div class="block addresses default">
    <div class="title"><strong><?php echo __('Default Addresses') ?></strong></div>
    <div class="content">
        <?php if($_pAddsses = $this->getDefaultBilling()): ?>
            <div class="box address billing">
                <strong class="subtitle">
                    <span><?php echo __('Default Billing Address') ?></span>
                    <a class="action edit" href="<?php echo $this->getAddressEditUrl($this->getAddressById($_pAddsses)) ?>">
                        <span><?php echo __('Change Billing Address') ?></span>
                    </a>
                </strong>
                <address>
                <?php echo $this->getAddressHtml($this->getAddressById($_pAddsses)) ?>
                </address>
           </div>
        <?php else: ?>
            <div class="box address no billing">
                <strong class="box-title"><span><?php echo __('Default Billing Address') ?></span></strong>
                <p><?php echo __('You have no default billing address in your address book.') ?></p>
            </div>
        <?php endif ?>

        <?php if($_pAddsses = $this->getDefaultShipping()): ?>
            <div class="box address shipping">
                <strong class="subtitle">
                    <span><?php echo __('Default Shipping Address') ?></span>
                    <a class="action edit" href="<?php echo $this->getAddressEditUrl($this->getAddressById($_pAddsses)) ?>">
                        <span><?php echo __('Change Shipping Address') ?></span>
                    </a>
                </strong>
                <address>
                    <?php echo $this->getAddressHtml($this->getAddressById($_pAddsses)) ?>
                </address>
            </div>
        <?php else: ?>
            <div class="box address shipping">
                <strong class="subtitle"><span><?php echo __('Default Shipping Address') ?></span></strong>
                <p><?php echo __('You have no default shipping address in your address book.') ?></p>
            </div>
        <?php endif ?>
    </div>
</div>

<div class="block addresses list">
    <div class="title"><strong><?php echo __('Additional Address Entries') ?></strong></div>
    <div class="content">
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
        <ol class="items addresses">
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <address>
                    <?php echo $this->getAddressHtml($_address) ?><br />
                </address>
                <div class="item actions">
                    <a class="action edit" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><span><?php echo __('Edit Address') ?></span></a>
                    <a class="action delete" href="#" role="delete-address" data-address="<?php echo $_address->getId() ?>"><span><?php echo __('Delete Address') ?></span></a>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
        <?php else: ?>
        <p><?php echo __('You have no additional address entries in your address book.') ?></p>
        <?php endif ?>
    </div>
</div>

<div class="actions">
    <div class="secondary"><a class="action back" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><span><?php echo __('Back') ?></span></a></div>
</div>
<script type="text/javascript">
    head.js("<?php echo $this->getViewFileUrl('Magento_Customer::address.js'); ?>", function() {
        jQuery('hgroup.page.title').address({
            deleteAddress: "li.item a[role='delete-address']",
            deleteUrlPrefix: '<?php echo $this->getDeleteUrl() ?>id/',
            addAddress: "button[role='add-address']",
            addAddressLocation: '<?php echo $this->getAddAddressUrl() ?>'
        });
    });
</script>