<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $test \Magento\Customer\Block\Address\Book
 */
?>
<button type="button" role="add-address" title="<?php echo __('Add New Address') ?>" class="action add"><span><?php echo __('Add New Address') ?></span></button>