<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('Magento_Core_Helper_Data')->decorateArray($this->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl>
    <?php foreach($_attributes as $_attribute): ?>
        <dt><label class="required"><em>*</em><?php echo $this->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></label></dt>
        <dd<?php if ($_attribute->getDecoratedIsLast()):?> class="last"<?php endif; ?>>
            <div class="input-box">
                <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" data-validate="{required:true}" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="super-attribute-select">
                    <option><?php echo __('Choose an Option...') ?></option>
                  </select>
              </div>
        </dd>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        (function ($) {
            head.js("<?php echo $this->getViewFileUrl('jquery/jquery.parsequery.js') ?>",
                "<?php echo $this->getViewFileUrl('Magento_Catalog::js/configurable.js') ?>", function () {
                $('#product_addtocart_form').configurable({"spConfig":<?php echo $this->getJsonConfig() ?>});
            })
        })(jQuery);
    </script>
<?php endif;?>
