<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?if($this->getCanDisplayWishlist()):?>
<div class="box base-mini mini-wishlist">
    <div class="head">
        <h4><?=$this->__('My Wishlist - <a href="%s">%d Item(s)</a>', $this->getUrl('wishlist'), $this->getWishlistItems()->getSize())?></h4>
        <h5><?=$this->__('Last Added Items')?></h5>
    </div>
    <?if($this->getWishlistItems()->getSize()>0):?>
    <ol id="wishlist-sidebar">
     <?foreach($this->getWishlistItems() as $_item):?>
        <li>
            <div class="product-images">
                <a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getThumbnailUrl()?>" alt="<?=$_item->getName()?>" width="50"/></a>
            </div>
            <div class="product-details">
                <a href="<?=$this->getRemoveItemUrl($_item)?>" onclick="return confirm('<?=$this->__('Are You sure?')?>');" class="widget-btn"><img src="<?=$this->getSkinUrl('images/list_remove_btn.gif')?>" alt="<?=$this->__('Remove Item')?>"/></a>
                <a href="#"><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a>
                <?=$this->getHelper('catalog/product')->getPriceHtml($_item)?>
                <?if($_item->isSaleable()):?>
                <a href="<?=$this->getAddToCartItemUrl($_item)?>" class="link-cart"><?=$this->__('Add to Cart')?></a>
                <?endif;?>
            </div>
        </li>
    <?endforeach;?>
    </ol>
    <script type="text/javascript">decorateList('wishlist-sidebar')</script>
    <?else:?>
    <div class="content"><p><?=$this->__('You have no items in your wishlist.')?></p></div>
    <?endif?>
    <div class="actions"><a href="<?=$this->getUrl('wishlist')?>"><?=$this->__('Go to Wishlist')?></a></div>
</div>
<?endif?>
<!-- [ends] .mini-wishlist // -->
