<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Backend_Block_Template */
?>

<script type="text/javascript">
(function($) {
    // Launch store
    $('#action-launch-store')
        .on('click.launchStore', function(event) {
            var startSuccess = false,
                launchUrl = '<?php echo $this->getUrl('*/storelauncher_index/launch'); ?>',
                ajaxOptions = {
                    type: 'get',
                    showLoader: true,
                    dataType: 'json',
                    async: false,
                    context: $('.store-launcher-popup > div'),
                    url: launchUrl,
                    success: function(result, status) {
                        if (result.success) {
                            startSuccess = true;
                            setTimeout(function() {
                                document.location.href = "<?php echo $this->getUrl('*/promotestore_index/index'); ?>";
                            }, 100);
                        } else {
                            alert(result.error_message);
                        }
                    }
                };
            $.ajax(ajaxOptions);
            if (!startSuccess) {
                event.preventDefault();
            }
        });

    // Run final checks
    $('#action-final-checks')
        .on('click.runFinalChecks', function() {
            var elem = $(this);

            elem
                .closest('.store-launcher-popup')
                .find('.action-close-store-launcher-popup')
                .trigger('click.closeStoreLauncherPopup');
        });

    // Show storelauncher popup
    $('[data-show-popup]')
        .on('click.showPopup', function() {
            var elem = $(this),
                popupData = elem.data('show-popup'),
                popupElem = $('.' + popupData + '-popup');

            popupElem
                .closest('.fade')
                .fadeIn(400, function() {
                    popupElem.animate({
                        top: '50%'
                    });
                });
        });

    // Close storelauncher popup
    $('.action-close-store-launcher-popup')
        .on('click.closeStoreLauncherPopup', function(e) {
            var elem = $(this);

            e.preventDefault();
            elem
                .closest('.store-launcher-popup')
                .animate({
                    top: '-100%'
                })
                .closest('.fade')
                .fadeOut();
        });
})(jQuery);
</script>

