<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_WelcomeScreen */
?>

<div class="welcome-screen" id="welcome-screen">
    <div class="fade welcome-screen-wrapper" id="welcome-screen-wrapper">
        <div class="store-launcher-popup welcome-screen-welcome-popup" id="welcome-screen-welcome-popup">
            <header class="store-launcher-popup-header">
                <button type="button"
                        title="<?php echo $this->__('Close'); ?>"
                        class="action-close-store-launcher-popup"
                        id="action-close-welcome-screen-wellcome-popup">

                    <span><?php echo $this->__('Close'); ?></span>
                </button>
            </header>
            <div class="store-launcher-popup-content">
                <h2 class="title"><?php echo $this->__('Welcome'); ?>&nbsp;<?php echo $this->escapeHtml($this->getUserName()); ?></h2>
                <h2 class="title"><?php echo $this->__('Getting Started'); ?></h2>
                <p><?php echo $this->__('Great job! You made it to Magento Go Admin. From here, just use Store Launcher to set up your new online store.'); ?></p>
                <p><?php echo $this->__('Then add more products, edit your settings, or test your new shopping cart before going live!'); ?></p>
                <button type="button"
                        class="action-store-launcher-popup-primary"
                        id="action-start-welcome-screen">

                    <span><?php echo $this->__('Take a Tour'); ?></span>
                </button>
            </div>
            <footer class="store-launcher-popup-footer">
                <button type="button"
                        id="welcome-screen-action-back-to-storelauncher"
                        class="action-store-launcher-popup-secondary">

                    <span><?php echo $this->__('Take me to Store Launcher'); ?></span>
                </button>
            </footer>
        </div>

        <div class="welcome-screen-content" id="welcome-screen-content">
            <div class="welcome-screen-content-inner">
                <ul class="welcome-screen-tags" id="welcome-screen-tags">
                    <li class="welcome-screen-tag-main-menu"
                        data-tour-element="main-menu"
                        data-tour-selector=".navigation">
                        <span><?php echo $this->__('Main Menu'); ?></span>
                    </li>
                    <li class="welcome-screen-tag-top-menu"
                        data-tour-element="top-menu"
                        data-tour-selector=".header-panel">
                        <span><?php echo $this->__('Top Menu'); ?></span>
                    </li>
                    <li class="welcome-screen-tag-store-launcher"
                        data-tour-element="launcher"
                        data-tour-selector=".store-launcher-content-inner">
                        <span><?php echo $this->__('Store Launcher'); ?></span>
                    </li>
                </ul>
                <div class="welcome-screen-hint" id="welcome-screen-hint">
                    <p><?php echo $this->__('Click the icons to learn about Magento and the Store Launcher.'); ?></p>
                </div>

                <div class="welcome-screen-data-launcher">
                    <div class="welcome-screen-description-launcher">
                        <button type="button"
                                title="<?php echo $this->__('Close'); ?>"
                                class="action-close-welcome-screen-description"
                                id="action-close-welcome-screen-launcher-description">

                            <span><?php echo $this->__('Close'); ?></span>
                        </button>
                        <h2 class="title"><?php echo $this->__('Store Launcher'); ?></h2>
                        <p><?php echo $this->__('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'); ?></p>
                    </div>
                    <div class="welcome-screen-overlay"></div>
                </div>
                <div class="welcome-screen-data-top-menu">
                    <div class="welcome-screen-description-top-menu">
                        <button type="button"
                                title="<?php echo $this->__('Close'); ?>"
                                class="action-close-welcome-screen-description"
                                id="action-close-welcome-screen-top-menu-description">

                            <span><?php echo $this->__('Close'); ?></span>
                        </button>
                        <h2 class="title"><?php echo $this->__('Top Menu'); ?></h2>
                        <p><?php echo $this->__('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'); ?></p>
                    </div>
                    <div class="welcome-screen-overlay"></div>
                </div>
                <div class="welcome-screen-data-main-menu">
                    <div class="welcome-screen-description-main-menu">
                        <button type="button"
                                title="<?php echo $this->__('Close'); ?>"
                                class="action-close-welcome-screen-description"
                                id="action-close-welcome-screen-main-menu-description">

                            <span><?php echo $this->__('Close'); ?></span>
                        </button>
                        <h2 class="title"><?php echo $this->__('Main Menu'); ?></h2>
                        <p><?php echo $this->__('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'); ?></p>
                    </div>
                    <div class="welcome-screen-overlay"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="welcome-screen-actions">
        <button type="button"
                class="action-toggle-welcome-screen-mode"
                id="action-toggle-welcome-screen-mode"
                title="<?php echo $this->__('Start Tour'); ?>">

            <span><?php echo $this->__('Exit Tour'); ?></span>
        </button>
    </div>
</div>
