<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
//<![CDATA[
if (window['export_filter_gridJsObject'] != undefined) {
    export_filter_gridJsObject.resetFilter = function () {
        return varienGrid.prototype.resetFilter.call(this, varienExport.modifyFilterGrid);
    };
    export_filter_gridJsObject.doFilter = function () {
        return varienGrid.prototype.doFilter.call(this, varienExport.modifyFilterGrid);
    };
}
</script>
