<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <title><?=__('Log into Magento Admin Page')?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf8" ></meta>
    <style type="text/css" media="all">
        /*<![CDATA[*/ @import "<?=$this->getSkinUrl('styles.css')?>"; /*]]>*/
    </style>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/prototype.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/validation.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/form.js"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('iestyles.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('below_ie7.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('ie7.css')?>" type="text/css" media="all" /> <![endif]-->
</head>
<body id="page-login">
	<div class="login-container">
		<div class="login-box">
			<form method="post" action="" id="loginForm">
                
				<fieldset class="login-form">
					<legend>Log in to Admin Panel</legend>
					<h2><em>Log in</em> to Admin Panel</h2>
                    <div id="messages">
                        <?=$this->getMessagesBlock()->getGroupedHtml(true)?>
                    </div>
					<p class="input-box"><label for="#">User Name:</label><br/>
						<input type="text" name="login[username]" value="<?=$username?>" class="required-entry input-text"/></p>
					<p class="input-box"><label for="#">Password</label><br/>
						<input type="password" name="login[password]" type="password" class="required-entry input-text" value="" /></p>
					<div class="clear"></div>
					<div class="form-buttons">
						<a href="#" class="left">Forgot your password?</a>
						<button type="submit" onclick="loginForm.submit()" class="form-button"><span>Login</span></button>
					</div>
				</fieldset>
				<p class="legal">&copy; Copyright 2007 <a href="http://www.varien.com" target="varien-external">Varien</a>. Magento is a trademark of Irubin Consulting Inc</p>
			</form>
			<div class="bottom"></div>
			<script type="text/javascript">
			     var loginForm = new varienForm('loginForm');
			</script>
		</div>
	</div>
</body>
</html>

