<?/*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <title><?=__('Magento Admin')?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf8"/>
    
    <link rel="icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon">
    
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/prototype.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>scriptaculous/scriptaculous.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>prototype/validation.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/hash.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/events.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/loader.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/grid.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/tabs.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/form.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/accordion.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/tools.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/bundle.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/uploader.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>firebug/firebug.js"></script>

    <script type="text/javascript">
        var BASE_URL = '<?=$this->getUrl('adminhtml')?>';
        var SKIN_URL = '<?=$this->getSkinUrl()?>';
    </script>

    <style type="text/css" media="all">
        /*<![CDATA[*/ @import "<?=$this->getSkinUrl('styles.css')?>"; /*]]>*/
    </style>
    <!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('iestyles.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('below_ie7.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('ie7.css')?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]>
    	<script defer type="text/javascript" src="<?=$this->getJsUrl()?>js/lib/ds-sleight.js"></script>
    	<script type="text/javascript" src="<?=$this->getJsUrl()?>varien/iehover-fix.js"></script>
    <![endif]-->

    <link rel="stylesheet" type="text/css" media="screen, projection" href="<?=$this->getSkinUrl('menu.css')?>"/>
<?//if($this->getCanLoadCalendarJs()):?>
    <link rel="stylesheet" type="text/css" media="all" href="<?=$this->getJsUrl()?>calendar/calendar-win2k-1.css" title="win2k-1" />
    <script type="text/javascript" src="<?=$this->getJsUrl()?>calendar/calendar.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>calendar/lang/calendar-en.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>calendar/calendar-setup.js"></script>
<?//endif;?>

<?if($this->getCanLoadExtJs()):?>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>extjs/ext-tree.js"></script>
    <script type="text/javascript" src="<?=$this->getJsUrl()?>extjs/ext-tree-checkbox.js"></script>
    <link rel="stylesheet" type="text/css" href="<?=$this->getJsUrl()?>extjs/resources/css/ext-all.css"/>
    <link rel="stylesheet" type="text/css" href="<?=$this->getJsUrl()?>extjs/resources/css/ytheme-magento.css"/>
    <script type="text/javascript">
        Ext.BLANK_IMAGE_URL = '<?=$this->getJsUrl()?>extjs/resources/images/default/s.gif';
        Ext.UpdateManager.defaults.loadScripts = false;
        Ext.UpdateManager.defaults.disableCaching = true;
    </script>
<?endif;?>

<?if($this->getCanLoadRulesJs()):?>
	<script type="text/javascript" src="<?=$this->getJsUrl()?>adminhtml/rules.js" ></script>
<?endif?>
</head>
<body>
    <table style="width: 100%;"><tr><td>
        <div class="header">
        <?=$this->getChildHtml('header')?>
        <div class="clear"></div>
        <?=$this->getChildHtml('menu')?>
        </div>
        <div class="middle">
            <?=$this->getChildHtml('breadcrumbs')?>
                <?if($this->getChildHtml('left')):?>
                <div class="simple-container-left">
					<div class="container">
							<div class="main">
									<div class="content-container">
											<div class="content" id="content">
												<?=$this->getMessagesBlock()->getGroupedHtml()?>
												<?=$this->getChildHtml('content')?>
											</div>
									</div>
									<div class="section-menu">
										<?=$this->getChildHtml('left')?>
										<div class="bottom"></div>
									</div>
							</div>
					</div>
				</div>
                <?else:?>
                <div class="simple-container">
                    <?=$this->getMessagesBlock()->getGroupedHtml()?>
                    <?=$this->getChildHtml('content')?>
                </div>
                <?endif;?>
        </div>
        <div class="footer">
            <?=$this->getChildHtml('footer')?>
        </div>
    </td></tr></table>
<?=$this->getChildHtml('profiler')?>
<div id="loading-process" style="display:none"><img src="<?=$this->getSkinUrl('images/ajax-loader-tr.gif')?>" alt="Loading..." align="absmiddle" height="16"/></div>
</body>
</html>
