<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Wishlist\Block\Share\Wishlist */
?>
<div class="my-wishlist">
    <div class="page-title">
        <h1><?php echo $this->escapeHtml($this->getHeader()) ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if ($this->hasWishlistItems()): ?>
    <form action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
        <fieldset>
            <table class="data-table" id="wishlist-table">
            <col width="1" />
            <col />
            <col width="1" />
            <thead>
                <tr>
                    <th><?php echo __('Product') ?></th>
                    <th><?php echo __('Comment') ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->getWishlistItems() as $item): ?>
                <?php
                    $product = $item->getProduct();
                    $isVisibleProduct = $product->isVisibleInSiteVisibility();
                ?>
                <tr>
                    <td>
                        <a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><img src="<?php echo $this->getImageUrl($product); ?>" width="<?php echo $this->getImageSize()?>" height="<?php echo $this->getImageSize()?>" alt="<?php echo $this->escapeHtml($item->getName()) ?>" /></a>
                        <h2 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h2>
                        <?php echo $this->getPriceHtml($product) ?>
                        <?php echo $this->getDetailsHtml($item) ?>
                    </td>
                    <td><?php echo $this->getEscapedDescription($item) ?></td>
                    <td class="a-center">
                    <?php if ($product->isSaleable()): ?>
                        <?php if ($isVisibleProduct): ?>
                            <button type="button" title="<?php echo __('Add to Cart') ?>" onclick="setLocation('<?php echo $this->getSharedItemAddToCartUrl($item) ?>')" class="button btn-cart"><span><span><?php echo __('Add to Cart') ?></span></span></button>
                        <?php endif ?>
                    <?php endif; ?>
                        <p><a href="<?php echo $this->getAddToWishlistUrl($item) ?>" onclick="setLocation(this.href); return false;" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></p>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
            </table>
            <script type="text/javascript">(function($) {$('#wishlist-table').decorate('table')})(jQuery)</script>
        </fieldset>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
            <?php if($this->isSaleable()):?>
                <button type="button" title="<?php echo __('Add All to Cart') ?>" onclick="setLocation('<?php echo $this->getUrl('*/*/allcart', array('_current'=>true)) ?>')" class="button"><span><span><?php echo __('Add All to Cart') ?></span></span></button>
            <?php endif;?>
        </div>
    </form>
    <?php else: ?>
        <p><?php echo __('Wish List is empty now.') ?></p>
    <?php endif ?>
</div>
