<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Wishlist\Block\Customer\Sharing */
?>
<div class="page-title">
    <h1><?php echo __('Share Your Wish List') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo __('Sharing Information') ?></h2>
        <ul class="form-list">
            <li class="wide">
                <label for="email_address" class="required"><em>*</em><?php echo __('Email addresses, separated by commas (max %1 addresses)', $this->getEmailSharingLimit()); ?></label>
                <div class="input-box">
                    <textarea name="emails" cols="60" rows="5" id="email_address" data-validate="{required:true,'validate-emails':true}"><?php echo $this->getEnteredData('emails') ?></textarea>
                </div>
            </li>
            <li class="wide">
                <label for="message"><?php echo __('Message') ?></label>
                <div class="input-box">
                    <textarea id="message" name="message" cols="60" rows="5" class="validate-length maximum-length-<?php echo $this->getTextSharingLimit();?>"><?php echo $this->getEnteredData('message') ?></textarea>
                </div>
            </li>
            <?php if($this->helper('Magento\Wishlist\Helper\Data')->isRssAllow()): ?>
            <li class="control">
                <div class="input-box">
                    <input type="checkbox" name="rss_url" id="rss_url" value="1" title="<?php echo __('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?>" class="checkbox" />
                </div>
                <label for="rss_url"><?php echo __('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?></label>
            </li>
            <?php endif; ?>
        </ul>
    </div>
    <div class="buttons-set form-buttons">
        <p class="required"><?php echo __('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getBackUrl(); ?>"><small>&laquo; </small><?php echo __('Back')?></a></p>
        <button type="submit" title="<?php echo __('Share Wish List') ?>" class="button"><span><span><?php echo __('Share Wish List') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                $('#form-validate').validation();
            })
    })(jQuery);
</script>
