<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Tools_Code */ ?>
<div class="vde-tab-content tab-panel" id="vde-tab-code">
    <div class="vde-tab-content-header">
        <h4 class="vde-tab-content-title"><?php echo $this->__('Scripts'); ?></h4>

        <div class="vde-tools-tabs">
            <ul class="vde-tab-controls">
                <li class="item active"><a href="#vde-tab-css" data-toggle="tab"><?php echo $this->__('Css'); ?></a></li>
                <li class="item"><a href="#vde-tab-js" data-toggle="tab"><?php echo $this->__('JS'); ?></a></li>
                <li class="item"><a href="#vde-tab-custom" data-toggle="tab"><?php echo $this->__('Custom CSS'); ?></a></li>
            </ul>
        </div>
    </div>
    <div class="vde-tab-content-inner">
        <div class="vde-tab-data">
            <?php echo join('', $this->getTabs()) ?>
        </div>
    </div>
</div>


