<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Rma\Block\Returns\Create */
?>
<?php $_order =  $this->getOrder(); ?>
<?php $_data = $this->getFormData(); ?>
<?php $_items = $this->getItems(); ?>
<div id="template-registrant" class="template" style="display: none">
    <div class="actions-toolbar">
        <div class="secondary" id="delete${_index_}">
            <button type="button" class="action remove delete"><span><?php echo __('Remove') ?></span></button>
        </div>
    </div>
    <fieldset class="fieldset">
        <div class="field item required">
            <label for="items:item${_index_}" class="label"><span><?php echo __('Item') ?></span></label>
            <div class="control">
                <?php $bundleID     = 0; ?>
                <?php $firstItemId = $i = $productType = $availableQty = 0; ?>
                <?php $html         = array(); ?>
                <select name="items[${_index_}][order_item_id]" class="select" id="items:item${_index_}" data-args='{"index":${_index_}}'>
                    <?php foreach($_items as $_item): ?>
                    <?php if ($i == 0): ?>
                        <?php
                        $firstItemId = $_item->getId();
                        $productType = $_item->getProductType();
                        $availableQty = $this->getAvailableQty($_item);
                        $i = 1;
                        ?>
                        <?php endif; ?>
                    <?php if ($_item->getProductType() == \Magento\Catalog\Model\Product\Type::TYPE_BUNDLE): ?>
                        <?php $bundleID = $_item->getId(); ?>
                        <?php endif; ?>
                    <?php if (!$_item->getParentItemId() || $_item->getParentItemId() != $bundleID): ?>
                        <option value="<?php echo $_item->getId()?>" id="item:order_item_id${_index_}_<?php echo $_item->getId() ?>" rel="<?php echo $_item->getProductType()?>_<?php echo $this->getAvailableQty($_item); ?>"><?php echo $this->escapeHtml($_item->getName())?></option>
                        <?php endif; ?>
                    <?php if ($_item->getParentItemId()!= null && $_item->getParentItemId() == $bundleID): ?>
                        <?php if ($_item->getIsOrdered()): ?>
                            <?php
                            $html[$bundleID][] = array(
                                $_item->getId(),
                                $this->escapeHtml($_item->getName()),
                                $this->getAvailableQty($_item),
                                1
                            );
                            ?>
                            <?php else: ?>
                            <?php
                            $html[$bundleID][] = array(
                                $_item->getId(),
                                $this->escapeHtml($_item->getName()),
                                $this->getAvailableQty($_item),
                                0
                            );
                            ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <?php if(!empty($html)): ?>
            <?php foreach($html as $bundleID=>$node): ?>
                <div class="nested">
                    <div id="radio:item${_index_}_<?php echo $bundleID?>">
                        <div class="table-wrapper">
                            <table class="data table" id="return-items-table-<?php echo $bundleID?>">
                                <caption class="table-caption"><?php echo __('Return items'); ?></caption>
                                <thead>
                                    <tr>
                                        <th colspan="2" class="col subitems" scope="col"><?php echo __('Sub-items') ?></th>
                                        <th class="col remaining qty" scope="col"><?php echo __('Remaining Qty') ?></th>
                                        <th class="col qty" scope="col"><?php echo __('Qty') ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                <?php foreach($node as $item): ?>
                                    <tr>
                                        <td class="col">
                                            <?php if ($item[3]): ?>
                                                <input type="checkbox" disabled>
                                            <?php else: ?>
                                                <input id="items[${_index_}][<?php echo $bundleID ?>][checkbox][item][<?php echo $item[0]?>]" data-validate="{'validate-one-required-by-name':true}"  data-args='{"item" :<?php echo $item[0]?>, "bundleId" : <?php echo $bundleID?>, "index" :${_index_}}' type="checkbox" value="<?php echo $item[0]?>" class="checkbox change-container-classname" name="validate-one-checkbox-<?php echo $bundleID ?>-${_index_}" />
                                            <?php endif; ?>
                                        </td>
                                        <td class="col product">
                                            <label for="items[${_index_}][<?php echo $bundleID ?>][checkbox][item][<?php echo $item[0]?>]" class="label <?php echo ($item[3]) ? 'disabled' : ''?>"><?php echo $item[1]?></label>
                                        </td>
                                        <td class="col remaining qty"><?php echo $item[2] ?></td>
                                        <td class="col qty">
                                            <?php if (!$item[3]): ?>
                                                <input id="items[${_index_}][<?php echo $bundleID ?>][checkbox][qty][<?php echo $item[0]?>]" name="items[${_index_}][items][<?php echo $item[0]?>]" size="7" data-validate="{'validate-greater-than-zero':true,required:true}" type="number" style="display:none" disabled class="input-text">
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            <?php endif; ?>
            </div>
        </div>
        <div class="field qty required" id="qty_requested_block_${_index_}">
            <label for="items:qty_requested${_index_}" class="label"><span><?php echo __('Quantity To Return') ?></span></label>
            <div class="control">
                <input type="number" class="input-text" data-validate="{'validate-greater-than-zero':true,required:true}" value="" name="items[${_index_}][qty_requested]" id="items:qty_requested${_index_}">
                <div class="note" id="remaining_quantity_block_${_index_}">
                    <?php echo __('Remaining quantity: ') ?><span id="remaining_quantity_${_index_}" class="qty remaining"></span>
                </div>
            </div>

        </div>

        <?php foreach ($this->getAttributes() as $attribute):?>
        <?php $attributeContent = $this->getAttributeHtml($attribute);?>
        <?php if ($attributeContent): ?>
            <?php echo $attributeContent;?>
        <?php endif;?>
        <?php endforeach;?>
    </fieldset>
</div>

<form id="rma_create_form" method="post" enctype="multipart/form-data" class="form form-create-return">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?php echo __('New Return for Order %1', $_order->getIncrementId()) ?></span>
        </legend>
        <br>
        <div class="field id">
            <span class="label"><span><?php echo __('Order ID') ?></span></span>
            <div class="control"><span><?php echo $_order->getIncrementId() ?></span></div>
        </div>
        <div class="field name">
            <span class="label"><span><?php echo __('Customer Name') ?></span></span>
            <div class="control"><span><?php echo $this->escapeHtml($_order->getCustomerName()) ?></span></div>
        </div>
        <div class="field email">
            <span class="label"><span><?php echo __('Email Address') ?></span></span>
            <div class="control"><span><?php echo $_order->getCustomerEmail()?></span></div>
        </div>
        <div class="field contact email">
            <label class="label" for="email"><span><?php echo $this->helper('Magento\Rma\Helper\Data')->getContactEmailLabel() ?></span></label>
            <div class="control">
                <input type="text" name="customer_custom_email" id="email" title="Contact Email Address" class="input-text" data-validate="{'validate-email':true}" value="<?php echo $this->getContactEmail()?>">
            </div>
        </div>
        <div class="field address shipping">
            <span class="label"><span><?php echo __('Order Shipping Address') ?></span></span>
            <address class="control"><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>
    </fieldset>

    <script type="text/javascript">
require(["jquery", "mage/mage"], function($){

    var formDataPost;
    <?php $i = 0; ?>
    <?php if ($_data): ?>
        <?php $formDataPost = $_data->getItems(); ?>
        <?php if (is_array($formDataPost)): ?>
            formDataPost = <?php echo json_encode($formDataPost); ?>;
        <?php endif; ?>
    <?php endif; ?>
    $('#rma_create_form').mage('fileElement').mage('rmaCreate', {
        formDataPost: formDataPost,
        templateRegistrant: '#template-registrant',
        registrantOptions: '#registrant-options',
        addItemToReturn: 'add-item-to-return',
        btnRemove: 'delete',
        row: '#row',
        addRow: 'additional row',
        qtyReqBlock: '#qty_requested_block',
        remQtyBlock: '#remaining_quantity_block',
        remQty: '#remaining_quantity',
        reasonOtherRow: '#reason_other',
        reasonOtherInput: '#items:reason_other',
        radioItem: '#radio:item',
        orderItemId: '#item:order_item_id',
        itemsItem: 'items:item',
        itemsReason: 'items:reason',
        firstItemId: '<?php echo $firstItemId; ?>',
        productType: '<?php echo $productType?>',
        availableQuantity: '<?php echo ($availableQty) ? $availableQty : 0 ?>',
        prodTypeBundle: '<?php echo \Magento\Catalog\Model\Product\Type::TYPE_BUNDLE ?>'
    }).mage('validation', {ignore: ':hidden:not(input[id$="_value"])'});
    
});
</script>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Return Items Information') ?></span></legend>
        <br>
        <div id="registrant-options"></div> <?php /* fields of the form are inserted here */ ?>
        <div class="actions-toolbar">
            <div class="secondary">
                <button type="button" id="add-item-to-return" class="action add">
                    <span><?php echo __('Add Item To Return') ?></span>
                </button>
            </div>
        </div>
        <div class="field comment">
            <label for="rma_comment" class="label"><span><?php echo __('Comments') ?></span></label>
            <div class="control">
                <textarea id="rma_comment" cols="5" rows="3" name="rma_comment" class="input-text"><?php if ($_data): ?><?php echo $_data->getRmaComment(); ?><?php endif; ?></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" id="submit.save" title="<?php echo __('Save') ?>"><span><?php echo __('Submit') ?></span></button>
        </div>
        <div class="secondary">
            <a href="<?php echo $this->getBackUrl() ?>" class="action back"><span><?php echo __('Back') ?></span></a>
        </div>
    </div>
</form>
