<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Rma\Block\Returns\Returns */
?>
<?php $_returns = $this->getReturns(); ?>
<?php if($_returns->getSize()): ?>
<div class="order-details-items">
    <?php echo $this->getChildHtml('info');?>
    <div class="order-title"><strong><?php echo __('My Returns') ?></strong></div>
    <div class="toolbar">
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <?php echo $this->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('info');?>
    <div class="table-wrapper order-items returns">
        <table class="data table table-order-items returns" id="my-returns-table">
            <thead>
                <tr>
                    <th class="col id"><?php echo __('Return #') ?></th>
                    <th class="col date"><?php echo __('Date') ?></th>
                    <th class="col shipping"><?php echo __('Ship From') ?></th>
                    <th class="col status"><?php echo __('Return Status') ?></th>
                    <th class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php $_odd = ''; ?>
                <?php foreach ($_returns as $_return): ?>
                <tr>
                    <td class="col id" data-th="<?php echo $this->escapeHtml(__('Return #')); ?>"><?php echo $_return->getIncrementId() ?></td>
                    <td class="col date" data-th="<?php echo $this->escapeHtml(__('Date')); ?>"><?php echo $this->helper('Magento\Rma\Helper\Data')->getFormatedDate($_return->getDateRequested()) ?></td>
                    <td class="col shipping" data-th="<?php echo $this->escapeHtml(__('Ship From')); ?>"><?php echo $this->escapeHtml($_return->getCustomerName()) ?></td>
                    <td class="col status" data-th="<?php echo $this->escapeHtml(__('Return Status')); ?>"><?php echo $this->escapeHtml($_return->getStatusLabel()) ?></td>
                    <td class="col actions" data-th="<?php echo $this->escapeHtml(__('Actions')); ?>">
                        <a href="<?php echo $this->getViewUrl($_return) ?>" class="cation view"><span><?php echo __('View Return') ?></span></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="toolbar">
        <?php echo $this->getPagerHtml(); ?>
    </div>
</div>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have placed no returns.'); ?></span></div>
<?php endif ?>
