<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Rma\Block\Returns\Tracking */
?>

<?php if ($this->getErrorMessage()): ?>
<tr>
    <td colspan="3">
        <div class="message error">
             <div><?php echo $this->escapeHtml($this->getErrorMessage()) ?></div>
        </div>
    </td>
</tr>
<?php endif ?>
<?php foreach ($this->getTrackingNumbers() as $number): ?>
<tr>
    <td class="col carrier"><?php echo $this->escapeHtml($number->getCarrierTitle()) ?></td>
    <td class="col id">
        <a href="#" data-mage-init='{"popupWindow": {
            "windowURL":"<?php echo $this->helper('Magento\Rma\Helper\Data')->getTrackingPopupUrlBySalesModel($number) ?>",
            "windowName":"trackshipment",
            "width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1
        }}' title="<?php echo $this->escapeHtml($number->getTrackNumber()) ?>" class="action tracking">
            <span><?php echo $this->escapeHtml($number->getTrackNumber()) ?></span>
        </a>
    </td>
    <td class="col actions">
        <?php if(!$number->getIsAdmin() && $this->isPrintShippingLabelAllowed()): ?>
            <a href="#" data-entity-id="<?php echo $number->getEntityId()?>" class="action delete" title="<?php echo __('Delete') ?>">
                <span><?php echo __('Delete') ?></span>
            </a>
        <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>
<?php if ($this->isPrintShippingLabelAllowed()): ?>
<script type="text/javascript">
require(['jquery'], function($){

        $('#rma_track_info').on('mage.setUpRmaOptions', function(e, rmaTrackInfo) {
            rmaTrackInfo.options.deleteLabelUrl = '<?php echo $this->getDeleteLabelUrl() ?>';
            rmaTrackInfo.options.deleteMsg = '<?php echo __('Are you sure you want to delete this tracking information?') ?>';
        });

});
</script>
<?php endif; ?>
