<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Rma\Block\Returns\View */
?>

<?php
    $_rma = $this->getRma();
    $_order = $this->getOrder();
    $additionalData = $this->getAdditionalData();
?>

<div class="returns details view">
    <strong class="returns status"><?php echo $this->escapeHtml($_rma->getStatusLabel()) ?></strong>
    <div class="block returns requested">
        <div class="title"><strong><?php echo __('Request Information') ?></strong></div>
        <div class="content">
            <?php echo __('ID') ?>: <?php echo $this->escapeHtml($_rma->getIncrementId()) ?><br>
            <?php echo __('Order ID') ?>: <a href="<?php echo $this->getOrderUrl($_rma) ?>"><?php echo $this->escapeHtml($_rma->getOrderIncrementId()) ?></a><br>
            <?php echo __('Date Requested') ?>: <?php echo $this->helper('Magento\Rma\Helper\Data')->getFormatedDate($_rma->getDateRequested()) ?><br>
            <?php echo __('Email Address') ?>: <?php echo $this->escapeHtml($_order->getCustomerEmail()) ?><br>
            <?php echo __('Contact Email Address') ?>: <?php echo $this->escapeHtml($_rma->getCustomerCustomEmail()) ?>
        </div>
    </div>
    <div class="block returns shipping">
        <div class="title"><strong><?php echo __('Shipping Address') ?></strong></div>
        <div class="content">
            <address>
                <?php echo $this->getAddress() ?>
            </address>
        </div>
    </div>
</div>

<div class="returns details items">
    <span id="rma-please-wait" class="please-wait load indicator" style="display: none;" data-text="<?php echo __('Please wait, loading...') ?>">
        <span><?php echo __('Please wait, loading...') ?></span>
    </span>

    <?php $trackingNumbers = $this->getTrackingNumbers() ?>
    <?php if ($this->isPrintShippingLabelAllowed() || $trackingNumbers->count()): ?>
        <div class="block returns tracking">
            <div class="title">
                <strong><?php echo __('Shipping and Tracking Information') ?></strong>
                <?php if ($trackingNumbers->count()): ?>
                    <a class="action track" href="#" data-mage-init='{"popupWindow": {
                        "windowURL":"<?php echo $this->helper('Magento\Rma\Helper\Data')->getTrackingPopupUrlBySalesModel($this->getRma()) ?>",
                        "windowName":"trackshipment",
                        "width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1
                    }}' title="<?php echo __('Track this shipment') ?>">
                        <span><?php echo __('Track this shipment') ?></span>
                    </a>
                <?php endif ?>
                <?php if ($this->canShowButtons()): ?>
                    <?php echo $this->getPrintShippingLabelButton() ?>
                    <?php echo $this->getShowPackagesButton() ?>
                <?php endif; ?>
            </div>
            <form method="post"
                  id="rma_track_info"
                  class="form tracking"
                  data-mage-init='{"rmaTrackInfo":{"addLabelUrl": "<?php echo $this->getAddLabelUrl() ?>"}, "validation":{}}'>
                <table class="data table" id="track-info-table">
                    <thead>
                        <tr>
                            <th scope="col" class="col carrier"><?php echo __('Carrier') ?></th>
                            <th scope="col" class="col id"><?php echo __('Number') ?></th>
                            <th scope="col" class="col actions"><?php echo __('Action') ?></th>
                        </tr>
                    </thead>
                    <?php if ($this->isPrintShippingLabelAllowed()): ?>
                    <tfoot>
                        <tr>
                            <td class="col carrier">
                                <select name="tracking_carrier_select" id="tracking_carrier_select" class="select" data-validate="{required:true}">
                                    <option value=""></option>
                                    <?php foreach($this->getCarriers() as $key => $value): ?>
                                        <option value="<?php echo $key ?>"><?php echo $this->escapeHtml($value) ?></option>
                                    <?php endforeach ?>
                                </select>
                            </td>
                            <td class="col id">
                                <input type="text" class="input-text" value="" name="tracking_number_input" id="tracking_number_input" data-validate="{required:true}">
                            </td>
                            <td class="col actions">
                                <button type="button" class="action add" id="btn-add-track-number" title="<?php echo __('Add') ?>"><span><?php echo __('Add') ?></span></button>
                            </td>
                        </tr>
                    </tfoot>
                    <?php endif ?>
                    <tbody id="track-info-tbody">
                        <?php echo $this->getTrackingInfo('tracking') ?>
                    </tbody>
                </table>
            </form>
        </div>
    <?php endif ?>

    <div class="returns subtitle caption">
        <strong><?php echo __('Items Return Requested For') ?></strong>
    </div>
    <div class="returns table-wrapper">
        <table class="data table returns items" id="my-returns-items-table">
            <thead>
                <tr>
                    <th class="col id"><?php echo __('Product Name') ?></th>
                    <th class="col sku"><?php echo __('SKU') ?></th>
                    <th class="col condition"><?php echo __('Condition') ?></th>
                    <th class="col resolution"><?php echo __('Resolution') ?></th>
                    <th class="col request qty"><?php echo __('Request Qty') ?></th>
                    <th class="col qty"><?php echo __('Qty') ?></th>
                    <th class="col status"><?php echo __('Status') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getItems() as $key=>$item): ?>
                    <?php foreach($this->getRealValueAttributes($item->getId()) as $code=>$attribute) {
                        $_qna = NULL;
                        if (!in_array($code, $this->getAttributeFilter()) && !empty($attribute['value']) && $this->getAttributeLabel($item->getId(), $code)) {
                            $_qna = '
                                <tr><td class="col questions">' .$this->getAttributeLabel($item->getId(), $code) . '</td>
                                <td class="col answers">' . $this->getAttributeValue($item->getId(), $code) . '</td></tr>
                            ';
                        }
                    } ?>
                <tr>
                    <td class="col id">
                        <?php echo $this->escapeHtml($item->getProductName()) ?>
                        <?php if($_options = $this->getItemOptions($item)): ?>
                        <dl class="item options">
                        <?php foreach ($_options as $_option) : ?>
                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                            <dd><?php echo $_option['value'] ?></dd>
                        <?php endforeach; ?>
                        </dl>
                        <?php endif; ?>
                        <?php if ($_qna) : ?>
                            <button class="action details" type="button" data-mage-init='{"toggleAdvanced": {"newLabel": "<?php echo __('Hide Details') ?>", "toggleContainers": "#shf_<?php echo $key; ?>"}}'>
                                <span><?php echo __('Show Details') ?></span>
                            </button>
                        <?php endif; ?>
                    </td>
                    <td class="col sku"><?php echo $this->escapeHtml($item->getProductSku()) ?></span></td>
                    <td class="col condition"><?php echo $this->escapeHtml($this->getAttributeValue($item->getId(), 'condition')) ?></td>
                    <td class="col resolution"><?php echo $this->escapeHtml($this->getAttributeValue($item->getId(), 'resolution')) ?></td>
                    <td class="col request qty"><?php echo $this->escapeHtml($this->helper('Magento\Rma\Helper\Data')->parseQuantity($item->getQtyRequested(), $item)); ?></td>
                    <td class="col qty"><?php echo $this->escapeHtml($this->helper('Magento\Rma\Helper\Data')->getQty($item));?></td>
                    <td class="col status"><?php echo $this->escapeHtml($item->getStatusLabel()) ?></td>
                </tr>
                <?php if ($_qna) : ?>
                    <tr id="shf_<?php echo $key ?>" class="hidden">
                        <td colspan="7">
                            <table class="data table">
                                <thead>
                                    <tr>
                                        <th class="col questions"><?php echo __('Questions') ?></th>
                                        <th class="col answers"><?php echo __('Answers') ?></th>
                                    </tr>
                                </thead>
                                <?php echo $_qna; ?>
                            </table>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="block returns comments">
        <div class="title"><span><?php echo __('Leave Comment') ?></span></div>
        <div class="content">
            <form method="post"
                  id="rma_comment"
                  action="<?php echo $this->getSubmitUrl() ?>"
                  class="form"
                  data-mage-init='{"validation":{}}'>
                <div class="field comment">
                    <label class="label"><span><?php echo __('Comment Text') ?></span></label>
                    <div class="control">
                        <textarea id="rma_comment_text" cols="5" rows="3" name="comment" data-validate="{required:true}"></textarea>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit" class="action submit" id="submit.save"><span><?php echo __('Submit Comment')?></span></button>
                </div>
            </form>
            <dl class="returns comments">
                <?php $_comments = $this->getComments(); ?>
                <?php if (!empty($_comments)): ?>
                    <?php foreach($_comments as $_comment): ?>
                        <?php if ($_comment->getIsVisibleOnFront()): ?>
                            <dt class="comment date">
                                <?php echo $this->formatDate($_comment->getCreatedAt()) ?> <?php echo $this->formatTime($_comment->getCreatedAt()) ?>
                                <strong class="comment autor">
                                    <?php if ($_comment->getIsAdmin()): ?>
                                        <?php echo __('Customer Service')?>
                                    <?php else: ?>
                                        <?php echo $this->escapeHtml($this->getCustomerName())?>
                                    <?php endif; ?>
                                </strong>
                            </dt>
                            <dd class="comment text">
                                <?php echo nl2br($this->escapeHtml($_comment->getComment())); ?>
                            </dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </dl>
        </div>
    </div>
</div>
