<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Installation end page
 *
 * @see Magento_Install_Block_End
 */
?>
<div class="page-head">
    <h3><?php echo __("You're All Set") ?>!</h3>
</div>
<?php if ($this->getIframeSourceUrl()): ?>
    <iframe id="iframe_box" src="<?php echo $this->getIframeSourceUrl() ?>" frameborder="0" width="650" height="600"></iframe>
<?php endif; ?>
<p><?php echo __('Get ready to experience Open-Source eCommerce Evolved.') ?></p>
<?php if($this->getEncryptionKey()): ?>
<p><?php echo __('Before you continue to your store, please make a note of your encryption key (Magento uses it to encrypt passwords, credit cards and more).') ?></p>
<p><strong><big><?php echo $this->getEncryptionKey() ?></big></strong></p>
<p><?php echo __('(Make sure you keep it in a safe place.)') ?></p>
<?php endif; ?>
<div class="button-set">
    <button class="form-button" onclick="window.open('<?php echo $this->getUrl('') ?>')" type="button"><?php echo __('Go to Frontend') ?></button>&nbsp;&nbsp;
    <button class="form-button" onclick="window.open('<?php echo Mage::helper('Magento_Backend_Helper_Data')->getHomePageUrl() ?>')" type="button"><?php echo __('Go to Backend') ?></button>
</div>
