<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title">
    <h1><?php echo __('Send confirmation link') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="" method="post" id="form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo __('Retrieve your confirmation link here') ?></h2>
        <p><?php echo __('Please enter your email below and we\'ll send you confirmation link for it.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?php echo __('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email_address" title="<?php echo __('Email Address') ?>" class="input-text" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo __('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo Mage::helper('Magento_Customer_Helper_Data')->getLoginUrl() ?>"><small>&laquo; </small><?php echo __('Back to Login') ?></a></p>
        <button type="submit" title="<?php echo __('Submit') ?>" class="button"><span><span><?php echo __('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#form-validate').validation();
            });
    })(jQuery);
</script>
