<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <?php echo $this->getBackButtonHtml() ?>
    <?php echo $this->getSaveButtonHtml() ?>
</div>
<?php echo $this->getFormHtml() ?>
<script type="text/javascript">
    jQuery('#<?php echo $this->getFormId();?>').mage('form').mage('validation');
</script>
