<?switch ($element->getType()){
    case 'fieldset':?>
    <h3><?=$element->getLegend()?></h3>
    <fieldset>
        <legend><?=$element->getLegend()?></legend>
        <?foreach ($element->getElements() as $_element):?>
            <?=$formBlock->drawElement($_element)?>
        <?endforeach;?>
    </fieldset>
      <?break;
    case 'column':?>
      <?break;
    case 'hidden':?>
    <input type="<?=$element->getType()?>" name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" value="<?=$element->getValue()?>">
      <?break;
    case 'select':?>
    <span>
        <label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label>
        <select name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" class="<?=$element->getClass()?>" title="<?=$element->getTitle()?>">
        <?foreach ($element->getValues() as $_value):?>
            <option value="<?=$_value['value']?>"><?=$_value['label']?></option>
        <?endforeach;?>
        </select>
    </span>
      <?break;
    case 'text':
    case 'password':?>
    <span>
        <label for="<?=$element->getHtmlId()?>"><?=$element->getLabel()?>:</label>
        <input type="<?=$element->getType()?>" name="<?=$element->getName()?>" id="<?=$element->getHtmlId()?>" value="<?=$element->getValue()?>" class="input-text <?=$element->getClass()?>" title="<?=$element->getTitle()?>">
    </span>
      <?break;
}?>
<?if($element->getScript()):?>
<script type="text/javascript">
    <?=$element->getScript()?>
</script>
<?endif;?>