<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>

<script type="text/javascript">
require(['prototype'], function(){

//<![CDATA[
OptionTemplateCountry =
    '<div class="field field-region">'+
        '<label class="label" for=""><span><?php echo __('Show Region') ?></label>'+
        '<div class="control"><?php echo $this->getRegionShowSelectHtml() ?></div>'+
    '</div>';

selectCountryType = {
    add : function(data) {
        if (data.show_region) {
            $A($(data.prefix+'_attribute_'+data.id+'_show_region').options).each(function(option){
                if (option.value==data.show_region) option.selected = true;
           });
        }
    }
}
//]]>

});
</script>
