<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<script type="text/javascript">
require(['prototype'], function(){

//<![CDATA[
OptionTemplateDate =
    '<div class="field field-date">'+
        '<label class="label" for=""><span><?php echo __('Date Format') ?></label>'+
        '<div class="control"><?php echo $this->getDateFormatSelectHtml() ?></div>'+
    '</div>';

selectDateType = {
    add : function(data) {
        if (data.date_format) {
            $A($(data.prefix+'_attribute_'+data.id+'_date_format').options).each(function(option){
                if (option.value==data.date_format) option.selected = true;
            });
        }
    }
}
//]]>

});
</script>
