<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <?php echo $this->getBackButtonHtml() ?>
    <?php echo $this->getResetButtonHtml() ?>
    <?php echo $this->getDeleteButtonHtml() ?>
    <?php echo $this->getSaveButtonHtml() ?>
</div>
<form action="<?php echo $this->getUrl('*/*/saverole') ?>" method="post" id="role-edit-form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#role-edit-form').mage('form').mage('validation');
    });
</script>
