<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Top menu for store
 * 
 * @see Mage_Catalog_Block_Navigation
 */
?>
<h4 class="no-show">Category Navigation:</h4>
<ul id="nav">
<?foreach ($this->getStoreCategories(2) as $_category):?>
    <?if($_category->getIsActive()):?>
    <li onmouseover="toggleMenu(this,1)" onmouseout="toggleMenu(this,0)"<?if ($this->isCategoryActive($_category)):?> class="active"<?endif?>>
        <a href="<?=$this->getCategoryUrl($_category)?>"><span><?=$_category->getName()?></span></a>
        <?if (($_children = $_category->getChildren()) && $_children->count()):?>
        <ul>
            <?foreach ($_children as $_child):?>
                <?if($_child->getIsActive()):?>
                <li><a href="<?=$this->getCategoryUrl($_child)?>"><?=$_child->getName()?></a></li>
                <?endif;?>
            <?endforeach?>
        </ul>
        <?endif?>
    </li>
    <?endif;?>
<?endforeach?>
</ul>
