<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="box" style="margin:20px;">
    <p class="a-center">
        <?php echo $this->helper('Mage_Adminhtml_Helper_Data')->__('Chart is disabled. If you want to enable chart, click <a href="%s">here</a>.', $this->getConfigUrl())?>
    </p>
</div>
