<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_Backend
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="design-edit-form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    jQuery('#design-edit-form').mage('form').mage('validation');
</script>
