<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->getEnabled() && $this->getTypesCollection()->getSize()) : ?>
<div class="widget">
    <div class="block block-gr-search">
        <div class="block-title">
            <strong><span><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Gift Registry Search') ?></span></strong>
        </div>
        <div class="block-content">
            <?php if ($this->useSearchFormSelect()) : ?>
            <ul class="form-alt">
                <li>
                    <label for="search_by" class="required"><strong><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Search By'); ?></strong> <em>*</em></label>
                    <div class="input-box">
                        <?php echo $this->getSearchFormSelect() ?>
                    </div>
                </li>
            </ul>
            <?php endif;?>

            <?php if ($this->useNameForm()) : ?>
            <form id="gr-quick-search-widget-name-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" <?php if ($this->useSearchFormSelect()) : ?>style="display:none;"<?php endif;?>>
                <ul class="form-alt">
                    <li>
                        <?php echo $this->getBlockHtml('formkey')?>
                        <label for="quick_search_firstname" class="required"><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('First Name') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="text" data-validate="{required:true,'validate-name-length':true}" id="quick_search_firstname" name="params[firstname]" />
                        </div>
                    </li>
                    <li>
                        <label for="quick_search_lastname" class="required"><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Last Name') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="text" class="input-text" data-validate="{required:true,'validate-name-length':true}" id="quick_search_lastname" name="params[lastname]" />
                        </div>
                    </li>
                    <li>
                        <label class="required"><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Type') ?></label>
                        <div class="input-box"><?php echo $this->getTypeSelectHtml() ?></div>
                    </li>
                </ul>
                <div class="actions">
                    <input type="hidden" name="params[search]" value="type" />
                    <p class="note"><em>*</em> <?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Enter at least two letters') ?></p>
                    <button type="submit" title="<?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Go') ?>" class="button"><span><span><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Search') ?></span></span></button>
                </div>
            </form>
            <?php endif; ?>

            <?php if ($this->useEmailForm()) : ?>
            <form id="gr-quick-search-widget-email-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" <?php if ($this->useSearchFormSelect()) : ?>style="display:none;"<?php endif;?>>
                <ul class="form-alt">
                    <li>
                        <?php echo $this->getBlockHtml('formkey')?>
                        <label for="quick_search_email" class="required"><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Recipient Email') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="text" class="input-text" data-validate="{required:true,'validate-name-length':true}" id="quick_search_email" name="params[email]" />
                        </div>
                    </li>
                </ul>
                <div class="actions">
                    <input type="hidden" name="params[search]" value="email" />
                    <button type="submit" title="<?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Go') ?>" class="button"><span><span><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Search') ?></span></span></button>
                </div>
            </form>
            <?php endif; ?>

            <?php if ($this->useIdForm()) : ?>
            <form id="gr-quick-search-widget-id-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" <?php if ($this->useSearchFormSelect()) : ?>style="display:none;"<?php endif;?>>
                <ul class="form-alt">
                    <li>
                        <?php echo $this->getBlockHtml('formkey')?>
                        <label for="quick_search_id" class="required"><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Gift Registry ID') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="text" class="input-text" data-validate="{required:true}" id="quick_search_id" name="params[id]" />
                        </div>
                    </li>
                </ul>
                <div class="actions">
                    <input type="hidden" name="params[search]" value="id" />
                    <button type="submit" title="<?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Go') ?>" class="button"><span><span><?php echo Mage::helper('Enterprise_GiftRegistry_Helper_Data')->__('Search') ?></span></span></button>
                </div>
            </form>
            <?php endif; ?>
        </div>
    </div>
    <script type="text/javascript">
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                    var forms = $('form[id^="gr-quick-search-widget"]');
                    forms.validation();
                    $('#search_by').on('change', function() {
                        forms.hide();
                        $('#gr-quick-search-widget-' + this.value + '-form').show();
                    });
                });
        })(jQuery);
    </script>
</div>
<?php endif; ?>
