<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this Magento_Authorizenet_Block_Directpost_Iframe
 */
?>
<?php
$_params = $this->getParams();
/* @var $_helper Magento_Authorizenet_Helper_Data  */
$_helper = Mage::helper('Magento_Authorizenet_Helper_Data');
?>
<html>
<head>
<script type="text/javascript">
    <?php if (isset($_params['redirect'])): ?>
        window.location="<?php echo $this->escapeUrl($_params['redirect']) ?>";
    <?php endif; ?>
    <?php if (isset($_params['redirect_parent'])): ?>
        window.top.location="<?php echo $this->escapeUrl($_params['redirect_parent']) ?>";
    <?php endif; ?>
    <?php if (isset($_params['error_msg'])): ?>
        alert(<?php echo Mage::helper('Magento_Core_Helper_Data')->jsonEncode($_params['error_msg']) ?>);
        <?php if (isset($_params['x_invoice_num'])): ?>
            window.top.location = "<?php echo $_helper->getSuccessOrderUrl($_params) ?>";
        <?php endif; ?>
    <?php endif; ?>
</script>
</head>
<body>
</body>
</html>
