<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            rmaTrackInfo: [
                "<?php echo $this->getViewFileUrl('Magento_Rma::rma-track-info.js');?>"
            ],
            fileElement: [
                "<?php echo $this->getViewFileUrl('Magento_CustomerCustomAttributes::file-element.js')?>"
            ],
            rmaCreate: [
                "<?php echo $this->getViewFileUrl('Magento_Rma::rma-create.js') ?>"
            ]
        });
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>