<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ], function($){
        'use strict';
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            rmaTrackInfo: 'Magento_Rma/rma-track-info',
            rmaCreate: 'Magento_Rma/rma-create'
        });
    });
</script>
<?php echo $this->getChildHtml() ?>