<?if($this->getItems()->getSize()):?>
<div class="box base-mini mini-related-items"> 
    <div class="head">
        <h4><?=__('Related Products')?></h4>
    </div>
    <div class="content">
        <p><strong>Check items to add to cart or <a href="#" onclick="selectAllRelated();return false;">select all</a>.</strong></p>
        <ol>
        <?foreach($this->getItems() as $_item):?>
        <li>
            <div class="product-images">
            <?if(!$_item->isSuper()):?>
                <input type="checkbox" class="related-checkbox left" id="related-checkbox<?=$_item->getId()?>" name="related_products[]" value="<?=$_item->getId()?>"/> 
            <?endif;?>
                <a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getThumbnailUrl()?>" alt="<?=$_item->getName()?>" width="50" height="50"/></a>
            </div>
            <div class="product-details">
                <p>
                    <a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a><br/>
                    <?=$this->getHelper('catalog/product')->getPriceHtml($_item)?>
                    <?if($_item->isSuper()):?>
                        <a href="<?=$_item->getProductUrl()?>">View Details</a><br/>
                    <?else:?>
                        <a href="<?=$this->getAddToWishlistUrl($_item)?>" class="link-cart">Add to Wishlist</a>
                    <?endif;?>
                </p>
            </div>
        </li>
        <?endforeach?>
        </ol>
    </div>
</div>
<script type="text/javascript">
$$('.related-checkbox').each(function(elem){
    Event.observe(elem, 'click', addRelatedToProduct)
});

function selectAllRelated(){
    $$('.related-checkbox').each(function(elem){
        elem.checked = true;
    });
    addRelatedToProduct();
}

function addRelatedToProduct(){
    var checkboxes = $$('.related-checkbox');
    var values = [];
    for(var i=0;i<checkboxes.length;i++){
        if(checkboxes[i].checked) values.push(checkboxes[i].value);
    }
    if($('related-products-field')){
        $('related-products-field').value = values.join(',');
    }
}
</script>
<?endif?>