<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this Magento_Sales_Block_Widget_Guest_Form */
?>
<?php if ($this->isEnable()): ?>
    <div class="widget">
        <div class="block block-gr-search">
            <div class="block-title">
                <h2><?php echo __('Orders and Returns') ?></h2>
            </div>
            <div class="block-content">
               <form id="oar-widget-orders-and-returns-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
                   <ul class="form-alt">
                       <li>
                           <label class="required"><?php echo __('Find Order By:') ?></label>
                           <div class="input-box">
                               <select name="oar_type" id="quick-search-type-id" class="select" title="">
                                   <option value="email"><?php echo __('Email Address') ?></option>
                                   <option value="zip"><?php echo __('ZIP Code') ?></option>
                               </select>
                           </div>
                       </li>
                       <li>
                           <label for="oar-order-id" class="required"><?php echo __('Order ID') ?> <em>*</em></label>
                           <div class="input-box">
                               <input type="text" class="input-text" id="oar-order-id" name="oar_order_id"  autocomplete="off" data-validate="{required:true}"/>
                           </div>
                       </li>
                       <li>
                           <label for="oar-billing-lastname" class="required"><?php echo __('Billing Last Name') ?> <em>*</em></label>
                           <div class="input-box">
                               <input type="text" class="input-text" id="oar-billing-lastname" name="oar_billing_lastname" autocomplete="off" data-validate="{required:true}"/>
                           </div>
                       </li>
                       <li id="oar-email">
                           <label for="oar_email" class="required"><?php echo __('Email Address') ?> <em>*</em></label>
                           <div class="input-box">
                               <input type="text" class="input-text" id="oar_email" name="oar_email" autocomplete="off" data-validate="{required:true, 'validate-email':true}"/>
                           </div>
                       </li>
                       <li id="oar-zip" style="display:none;">
                           <label for="oar_zip" class="required"><?php echo __('Billing ZIP Code') ?> <em>*</em></label>
                           <div class="input-box">
                               <input type="text" class="input-text" id="oar_zip" name="oar_zip" data-validate="{required:true}"/>
                           </div>
                       </li>
                   </ul>
                   <div class="actions">
                       <button type="submit" title="Continue" class="button"><span><span><?php echo __('Continue') ?></span></span></button>
                   </div>
               </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
    head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
        "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
        "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
        "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
        "<?php echo $this->getViewFileUrl('Magento_Sales::orders-returns.js');?>", function() {
            jQuery('#oar-widget-orders-and-returns-form').ordersReturns().validation();
        });
</script>
<?php endif; ?>
