<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Customer login form template
 *
 * @var $this \Magento\Customer\Block\Form\Login
 * @see app/design/frontend/enterprise/default/template/customer/form/login.phtml
 */
?>
<div class="account-login<?php if (!$this->helper('\Magento\Customer\Helper\Data')->isRegistrationAllowed()) echo ' login-only' ?>">
    <div class="page-title">
        <h1><?php if ($this->helper('\Magento\Customer\Helper\Data')->isRegistrationAllowed()): ?>
            <?php echo __('Login or Create an Account') ?>
            <?php else: ?>
            <?php echo __('Login'); ?>
            <?php endif; ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <div class="fieldset">
            <div class="col2-set">
                <div class="col-1 registered-users">
                    <h2 class="legend"><?php echo __('Registered Customers') ?></h2>
                    <p><?php echo __('If you have an account with us, log in using your email address.') ?></p>
                    <ul class="form-list">
                        <li>
                            <label for="email" class="required"><em>*</em><?php echo __('Email Address') ?></label>
                            <div class="input-box">
                                <input name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" type="text" class="input-text" title="<?php echo __('Email Address') ?>" data-validate="{required:true, 'validate-email':true}" />
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="required"><em>*</em><?php echo __('Password') ?></label>
                            <div class="input-box">
                                <input name="login[password]" type="password" class="input-text" id="pass" title="<?php echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" />
                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <li class="note">
                            <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo __('Forgot Your Password?') ?></a>
                        </li>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        <li class="buttons-set">
                            <button type="submit" class="button" name="send" id="send2"><span><span><?php echo __('Login') ?></span></span></button>
                        </li>
                    </ul>
                    <p class="required"><?php echo __('* Required Fields') ?></p>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                </div>
                <?php if ($this->helper('\Magento\Customer\Helper\Data')->isRegistrationAllowed()): ?>
                <div class="col-2 new-users">
                    <h2 class="legend"><?php echo __('New Customers') ?></h2>
                    <p><?php echo __('Create an account with us for faster checkout, multiple shipping addresses, your own shopping history file and more.') ?></p>
                    <div class="buttons-set">
                        <button type="button" class="button"><span><span><?php echo __('Register') ?></span></span></button>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
        <?php if ($this->helper('\Magento\Checkout\Helper\Data')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
        (function($) {
            head.js(
                "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
                function() {
                    $('#login-form .new-users button').on('click', function() {window.location='<?php echo $this->helper('\Magento\Persistent\Helper\Data')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';});
                    $('#login-form').validation();
                });
        })(jQuery);
    </script>
</div>
