<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Editor_Tools_Code_Custom */ ?>
<div class="tab-panel" id="vde-tab-custom">
    <div class="custom-code-description">
        <h5 class="title">Custom CSS</h5>
        <p>Update the custom.css file to right in order to overwrite the default styles.</p>
        <p>Or, replace, delete or download the file:</p>
        <div class="custom-file">
            <span class="filename">custom.css</span>

            <button class="action-download" title="<?php echo $this->__('Download file'); ?>">
                <span><?php echo $this->__('Download file'); ?></span>
            </button>
            <button class="action-delete" title="<?php echo $this->__('Delete file'); ?>">
                <span><?php echo $this->__('Delete file'); ?></span>
            </button>

            <form action="#" method="post">
                <input type="file" class="action-add" />
            </form>
        </div>
    </div>
    <div class="custom-code">
        <form action="#" method="post">
            <div class="textarea-container">
                <textarea name="custom_code" id="custom_code" cols="30" rows="10">.files-list-header > .action-add { display: inline-block; float: right; margin: 6px 0 0 0; width: 16px; height: 16px; line-height: 16px; text-align: center; color: #000; background: #9f978b; border-radius: 4px; text-decoration: none; -moz-transition: background .5s ease; -webkit-transition: background .5s ease; transition: background .5s ease; }</textarea>
            </div>
            <button class="action-update" title="<?php echo $this->__('Update'); ?>"><?php echo $this->__('Update'); ?></button>
        </form>
    </div>
</div>
