<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Language switcher template
 *
 * @see \Magento\Page\Block\Switch
 */
?>

<?php if(count($this->getStores())>1): ?>
<div class="switcher language">
    <strong class="label"><span><?php echo __('Language') ?></span></strong>
    <div class="options">
        <strong class="view-<?php echo $this->escapeHtml($this->getCurrentStoreCode()) ?>">
            <span><?php echo $this->escapeHtml($this->getStoreName()) ?></span>
        </strong>
        <button type="button" data-toggle="dropdown" class="action switch"><span><?php echo __('Change')?></span></button>
        <ul data-target="dropdown">
            <?php foreach ($this->getStores() as $_lang): ?>
                <?php if($_lang->getId()!=$this->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $this->escapeHtml($_lang->getCode()); ?>">
                        <a href="<?php echo $_lang->getCurrentUrl() ?>"><?php echo $this->escapeHtml($_lang->getName()) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>

