<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $this->setPriceDataObject($this->getSource()) ?>

<?php if ((float) $this->getSource()->getRewardCurrencyAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('Magento_Reward_Helper_Data')->formatReward($this->getSource()->getRewardPointsBalance()) ?></td>
        <td>
            <?php echo $this->displayPrices(-$this->getSource()->getBaseRewardCurrencyAmount(), -$this->getSource()->getRewardCurrencyAmount()); ?>
        </td>
    </tr>
<?php endif; ?>
