<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<div class="field field-rate">
    <label class="label" for="rate_value"><span><?php echo $this->getElement()->getLabel(); ?></span></label>
    <div class="control">
        <input type="text" class="input-text" id="rate_value" style="width:125px" name="rate[value]" value="<?php echo $this->getValue(); ?>"/>
        <label for="rate_equal_value">&nbsp;&raquo;&nbsp;</label>
        <input type="text" class="input-text" id="rate_equal_value" style="width:125px" name="rate[equal_value]" value="<?php echo $this->getEqualValue(); ?>"/>
    </div>
</div>
