<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Calendar localization script. Should be put into page header.
 *
 * @see Magento_Core_Block_Html_Calendar
 */
?>

<script type="text/javascript">
//<![CDATA[
(function($) {
    $.extend(true, $, {
        calendarConfig: {
            dayNames: <?php echo $days['wide']?>,
            dayNamesMin: <?php echo $days['abbreviated']?>,
            monthNames: <?php echo $months['wide']?>,
            monthNamesShort: <?php echo $months['abbreviated']?>,
            infoTitle: "<?php echo $this->__('About the calendar');?>",
            firstDay: <?php echo $firstDay?>,
            closeText: "<?php echo $this->__('Close');?>",
            currentText: "<?php echo $this->__('Go Today'); ?>",
            prevText: "<?php echo $this->__('Previous');?>",
            nextText: "<?php echo $this->__('Next');?>",
            weekHeader: "<?php echo $this->__('WK'); ?>",
            timeText: "<?php echo $this->__('Time');?>",
            hourText: "<?php echo $this->__('Hour');?>",
            minuteText: "<?php echo $this->__('Minute');?>",
            dateFormat: $.datepicker.RFC_2822,
            showOn: "button",
            showAnim: "",
            changeMonth: true,
            changeYear: true,
            buttonImageOnly: true,
            showButtonPanel: true,
            showWeek: true,
            timeFormat: '',
            showTime: false,
            showHour: false,
            showMinute: false
        }
    });
})(jQuery);
enUS = <?php echo $enUS?>; // en_US locale reference
//]]>
</script>
