<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
	<script type="text/javascript" language="Javascript">
    	var BASE_URL = '<?=$this->baseUrl?>';
    	var SKIN_URL = '<?=$this->baseSkinUrl?>';
    </script>

    <?=$this->head?>

    <script type="text/javascript" language="Javascript">
        Ext.UpdateManager.defaults.loadScripts  = true;
        Ext.UpdateManager.defaults.disableCaching  = true;

        Ext.Mage = {};
        Ext.Mage.Collection = {};
    </script>
</head>
<body>
    <?=$this->layout?>
</body>
</html>