<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this Magento_Sales_Block_Recurring_Profiles */ ?>
<div class="page-title">
    <h1><?php echo __('Recurring Billing Profiles') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="recurring-profiles">

    <?php echo $this->getChildHtml('grid')?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
    </div>
</div>
