
	<div class="page-head">
		<h3>Shipping Information</h3>
	</div>
	<h4>Shipping Address | <a href="">Change Address</a></h4>
	<address>
			<strong><?=$address->getFirstname()?> <?=$address->getLastname()?></strong><br/>
			<?=$address->getCompany()?><br/>
			<?=$address->getPostcode()?>, <?=$address->getCity()?><br/>
			<?=$address->getStreet()?><br/>
			<?if($address->getTelephone()):?>T| <?=$address->getTelephone()?><br/><?endif?>
			<?if($address->getFax()):?>F| <?=$address->getFax()?><br/><?endif?>
	</address>
	<h4>Shipping Method</h4>
	<form action="<?=$action?>" method="post">
			<fieldset>
					<legend>Shipping Method</legend>
			</fieldset>
			<div class="form-buttons">
					<a href="#" onclick="window.location='<?=$baseUrl?>checkout/cart/'" class="left">&laquo;<a>
					<button class="form-button"><span>Continue</span></button>
			</div>
	</form>