<h4 class="icon-head head-edit-form fieldset-legend">Roles resources</h4>
<?$level = 0;?>
<?php foreach ($resources as $resource => $val):?>
  <? $margin = $val['level'] * 20;?>
    <div style="margin-left:<?=$margin?>px;">
	<input type="checkbox" value="<?=$resource?>" title="<?=$val['name']?>" name="resource[]" <? if( isset($val['checked']) && $val['checked'] === true ) echo 'checked="true"';?> />
	<?=$val['name'];?>
	</div>
<?php endforeach; ?>