<div class="entry-edit">
	<h4 class="icon-head head-edit-form fieldset-legend"><?=__('Roles Resources')?></h4>
	<fieldset id="role_resources">
		<?$_level = 0;?>
		<?foreach ($resources as $_resource => $val):?>
		<?
		  	$_next = next($resources);
		  	if( $_next['level'] < $val['level'] ) {
				$_class = 'tree_item_last';
			} else {
				$_class = 'tree_item';
			}
			$_margin = $val['level'] * 20;
			$_lineWidht = ( $_margin == 0 ) ? 25 : $_margin ;
		?>
			<div id="_<?=$_resource?>" style="position:relative;">
				<div style="width:<?=$_lineWidht?>px;" class="tree_line">&nbsp;</div>
				<div class="<?=$_class?>" style="margin-left:<?=$_margin?>px;">
					<input type="checkbox" value="<?=$_resource?>" id="<?=str_replace('/', '_', rtrim($_resource, '/'))?>" title="<?=$val['name']?>" name="resource[]" <? if( isset($val['checked']) && $val['checked'] === true ) echo 'checked="true"';?> onchange="resource._toggle(this)" />
					<label for="<?=str_replace('/', '_', rtrim($_resource, '/'))?>" class="normal <? if( isset($val['checked']) && $val['checked'] === true ) echo 'bold';?>"><?=$val['name'];?></label>
				</div>
			</div>
		<?php endforeach; ?>
	</fieldset>
</div>
<script type="text/javascript">
    var resource = function () {
    	return {
    		_getCheckboxes: function (obj) {
                checkboxes = document.getElementsByTagName('input');
                children = new Array();
                for( i in checkboxes ) {
                    if( checkboxes[i].type == 'checkbox' && checkboxes[i].id.match(obj.id+'_') ) {
                        children.unshift(checkboxes[i])
                    }
                }
                return children;
       		},

       		_toggle: function(obj) {
       		    objState = obj.checked;
       		    checkboxes = this._getCheckboxes(obj);
       		    for( i in checkboxes ) {
       		        checkboxes[i].checked = objState;
       		    }
       		}
    	}
    }();
</script>
