<div class="entry-edit">
    <h4 class="icon-head head-edit-form fieldset-legend"><?=__('User roles')?></h4>
    <fieldset id="user_roles">
    <?php foreach ($roles as $role):?>
    <?
        $checked = false;
        foreach( $user_roles->getItems() as $user_role )
        {
            if( $user_role->getParentId() == $role->getRoleId() ) {
                $checked = true;
            }
        }
    ?>
        <input type="checkbox" value="<?=$role->getRoleId();?>" <?=($checked ? "checked" : "");?> name="roles[]" id="_<?=$role->getRoleId();?>" /> <label for="_<?=$role->getRoleId();?>" class="normal"><?=$role->getRoleName();?></label><br />
    <?php endforeach;?>
	</fieldset>
</div>