<div class="content-header">
<table cellspacing="0" class="grid-header">
    <tr>
        <td style="width:50%;"><h3><?=__('Users')?></h3></td>
        <td class="a-right">
            <span class="form-button right">
                <span><a href="<?=$this->getAddNewUrl()?>"><?=__('Add new user')?></a></span>
            </span>
        </td>
    </tr>
</table>
</div>
<div>
    <?=$this->getGridHtml()?>
</div>

