<div class="head">
    <table cellspacing="0"> 
        <tr>
            <td style="width:50%;"><h2></h2></td>
            <td class="buttons">
                <strong class="button"><span><a href="#" onclick="customerForm.submit();return false;"><?=__('save')?></a></span></strong>
                <strong class="button"><span><a href="/adminhtml/permissions/deleteuser?uid=<?=$uid;?>"><?=__('delete')?></a></span></strong>
            </td>
        </tr>
    </table>
</div>
<form action="/adminhtml/permissions/saveuser" method="POST" id="customer_edit_form">
</form>
<script type="text/javascript" language="javascript">
    var customerForm = new varienForm('customer_edit_form');
</script>