<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    require(['prototype', 'Magento_Rma/rma'], function() {
        window.rma = new AdminRma();
    });
    require(['Magento_Rma/details-validator']);
</script>

<?php
/**
 * @see \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General
 */
?>
<div class="clearfix">
    <div class="rma-request-details">
        <?php echo $this->getChildHtml('request_details') ?>
    </div>
    <div class="order-shipping-method">
        <?php echo $this->getChildHtml('shipping_method') ?>
    </div>
</div>
<div class="clearfix">
    <div class="order-shipping-address">
        <?php echo $this->getChildHtml('shipping_address') ?>
    </div>
    <div class="order-return-address">
        <?php echo $this->getChildHtml('return_address') ?>
    </div>

</div>
<?php echo $this->getChildHtml('comments_history') ?>
