<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<div id="rma_reason_container" class="rma-popup" style="display:none">
    <div class="popup-window-wrapper">
        <div class="popup-window-title">
            <div class="title">
                <?php echo __('Reason to Return') ?>
            </div>
        </div>
        <div id="rma_reason_content" class="popup-window-content"></div>
        <div class="popup-window-buttons-set">
            <button class="action-ok ok_button" type="button">
                <span><?php echo __('OK') ?></span>
            </button>
        </div>
    </div>
</div>
