<div class="content">
<h1 class="page-heading"><?if($data->getAddressId()):?>Edit<?else:?>New<?endif?> Address Entry</h1>
<?=$messages->__toHtml()?>
<form action="<?=$action?>" method="post" id="form-validate">
<input type="hidden" name="address_id" value="<?=$data->getAddressId()?>">
<input type="hidden" name="customer_id" id="address_id" value="<?=$data->getCustomerId()?>">
    <fieldset class="group-single">
        <legend>Personal Information</legend>
        <h3>Personal Information</h3>
        <ul class="input-list">
            <li>
                <div class="input-left">
                    <label for="firstname">First Name <span class="required">*</span></label><br/>
                    <input type="text" name="firstname" id="firstname" title="First Name" value="<?=$data->getFirstname()?>" class="required-entry input-text"/>
                </div>
                <div class="input-right">
                    <label for="lastname">Last Name <span class="required">*</span></label><br/>
                    <input type="text" name="lastname" id="lastname" title="Last Name" value="<?=$data->getLastname()?>" class="required-entry input-text"/>
                </div>
                <div class="clearfix"></div>
            </li>
            <li>
                <div class="input-left">
                    <label for="company">Company</label><br/>
                    <input type="text" name="company" id="company" title="Company" value="<?=$data->getCompany()?>" class="input-text"/>
                </div>
                <div class="clearfix"></div>
            </li>
        </ul>
    </fieldset>
    <fieldset class="group-single">
        <legend>Address</legend>
        <h3>Address</h3>
        <ul class="input-list">
            <li>
                <label for="street_1">Street Address <span class="required">*</span></label><br/>
                <input type="text" name="street[1]" value="<?=$data->getStreet(1)?>" title="Street Address" id="street_1" class="required-entry input-text"/>
            </li>
            <li>
                <input type="text" name="street[2]" value="<?=$data->getStreet(2)?>" title="Street Address 2" id="street_2" class="input-text"/>
            </li>
            <li>
                <label for="city">City <span class="required">*</span></label><br/>
                <input type="text" name="city" value="<?=$data->getCity()?>"  title="City" class="required-entry input-text" id="city"/></li>
            <li>
                <div class="input-left">
                    <label for="state">State / Province <span class="required">*</span></label><br/>
                <?if($regions->getSize()):?>
                    <select name="region" value="" title="State/Province" id="state"  class="input-text required-entry"/>
                        <option value="">Select State/Province...</option>
                        <?=$regions->toHtmlOptions($data->getRegionId())?>
                    </select>
                <?else:?>
                    <input type="text" name="region" value="<?=$data->getRegion()?>"  title="State/Province" id="state" class="required-entry input-text"/>
                <?endif?>
                </div>
                <div class="input-right">
                    <label for="zip">Zip/Post Code <span class="required">*</span></label><br/>
                    <input type="text" name="postcode" value="<?=$data->getPostcode()?>" title="ZIP/Post Code" id="zip" class="validate-zip required-entry input-text"/>
                </div>
                <div class="clearfix"></div>
            </li>
            <li>
                <label for="country">Country <span class="required">*</span></label><br/>
                <select name="country_id" id="country" title="Country" class="validate-select" onchange="">
                    <?=$countries->toHtmlOptions($data->getCountryId())?>
                </select>
            </li>
            <li>
                <div class="input-left">
                    <label for="telephone">Telephone <span class="required">*</span></label><br/>
                    <input type="text" name="telephone" value="<?=$data->getTelephone()?>" title="Telephone" class="required-entry validate-phoneStrict input-text" id="telephone"/></div>
                <div class="input-right">
                    <label for="fax">Fax</label><br/>
                    <input type="text" name="fax" value="<?=$data->getFax()?>" title="Fax" class="validate-fax input-text" id="fax"/>
                </div>
                <div class="clearfix"></div>
            </li>
            <?foreach ($primaryTypes as $code=>$type):?>
                <li>
                <?if ($address->isPrimary($type['address_type_id'])):?>
                    <?=__("This is my primary <strong>%s</strong> address", $type['name'])?>
                <?else:?>
                    <input type="checkbox" id="primary_<?=$code?>" name="primary_types[]" value="<?=$type['address_type_id']?>"/>&nbsp;
                    <label for="primary_<?=$code?>"><?=__("Use as my primary <strong>%s</strong> address", $type['name'])?></label>
                <?endif?>
                </li>
            <?endforeach?>
        </ul>
    </fieldset>
    <div class="buttons-container">
        <p class="required">* Required Fields</p>
        <input type="button" onclick="window.location='<?=$baseUrl?>customer/address/';" value="Back" class="input-button float-left"/>
        <input type="submit" value="Submit" class="input-button float-right"/>
        <div class="clearfix"></div>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
    dataForm.setElementsRelation('country', 'state', '<?=$baseUrl?>directory/json/childRegion/');
</script>
</div>