<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Downloadable product links
 *
 * @var $this \Magento\Downloadable\Block\Catalog\Product\Samples
 */
?>

<?php if ($this->hasSamples()): ?>
    <dl class="downloadable samples">
        <dt><?php echo $this->getSamplesTitle() ?></dt>
        <?php $_samples = $this->getSamples() ?>
        <?php foreach ($_samples as $_sample): ?>
            <dd>
                <a href="<?php echo $this->getSampleUrl($_sample) ?>" <?php echo $this->getIsOpenInNewWindow()?'onclick="this.target=\'_blank\'"':''; ?>
                   class="sample">
                    <?php echo $this->escapeHtml($_sample->getTitle()) ?>
                </a>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
