<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<select id="<?php echo $this->getSelectRegionId() ?>" name="<?php echo $this->getSelectRegionName() ?>" title="<?php echo $this->__('State/Province') ?>" class="<?php echo $this->getSelectRegionClass(); ?>" <?php echo  $this->getSelectRegionParams() ?>>
     <option value=""><?php echo $this->getSelectRegionDefault() ?></option>
</select>
<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded", function() {
    $('<?php echo $this->getSelectRegionId() ?>').setValue("<?php echo $this->getSelectRegionValue() ?>");
})

//]]>
</script>
