<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="box-account box-tags">
    <div class="box-head">
        <h2><?php echo __('My Recent Tags') ?></h2>
        <a href="<?php echo $this->getAllTagsUrl() ?>"><?php echo __('View All Tags') ?></a>
    </div>
    <ol id="my_recent_tags">
        <?php $iterator = 0; ?>
        <?php foreach( $this->getCollection()->getItems() as $_item ): ?>
            <li class="item">
                <span class="number"><?php echo ++$iterator ?></span>
                <div class="details">
                    <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                    <div class="tags">
                        <strong><?php echo __('Tags:') ?></strong>
                        <?php $_i = 0; ?>
                        <ul>
                        <?php foreach( $_item->getProductTags() as $_tag ): ?>
                            <li><a href="<?php echo $_tag->getViewTagUrl() ?>"><?php echo $this->escapeHtml($_tag->getName()) ?></a><?php if(++$_i != sizeof($_item->getProductTags()->getItems())): ?>,<?php endif; ?></li>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
    <script type="text/javascript">(function($) {$('#my_recent_tags').decorate('list', false)})(jQuery)</script>
</div>
