<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<?php echo $this->htmlEscape($_item->getName()) ?>
<?php if($_options = $this->getItemOptions()): ?>
<ul>
<?php foreach ($_options as $_option): ?>
    <li><strong><?php echo $this->htmlEscape($_option['label']) ?>:</strong>
    <?php if (is_array($_option['value'])): ?>
        <?php foreach ($_option['value'] as $item): ?>
        <br /><?php echo $this->getValueHtml($item) ?>
        <?php endforeach; ?>
    <?php else: ?>
        <?php echo $this->htmlEscape($_option['value']); ?>
    <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<?php echo $_item->getDescription() ?>
<?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
    <br /><a href="#" id="order-item-gift-message-link-<?php echo $_item->getId() ?>" class="giftmessage-preview-link expand" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>')"><?php echo $this->__('Gift Message') ?></a>
<?php endif; ?>