<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
//<![CDATA[
Event.observe(window, 'load', recalculateTax);
Event.observe(window, 'load', registerTaxRecalcs);

function registerTaxRecalcs()
{
    if (typeof dynamicTaxes == 'undefined') {
        return;
    }

    for (var i=0; i<dynamicTaxes.length; i++) {
        Event.observe($(dynamicTaxes[i]), 'change', recalculateTax);
    }
    Event.observe($('tax_class_id'), 'change', recalculateTax);
}

var priceFormat = <?php echo Mage::helper('Magento_Tax_Helper_Data')->getPriceFormat($this->getStore()); ?>;
var taxRates = <?php echo Mage::helper('Magento_Tax_Helper_Data')->getAllRatesByProductClass($this->getStore()); ?>;

function recalculateTax()
{
    if (typeof dynamicTaxes == 'undefined') {
        return;
    }

    for (var i=0; i<dynamicTaxes.length; i++) {
        var code = dynamicTaxes[i];
        var span = $('dynamic-tax-' + code);
        var input = $(code);

        if (!input.value) {
            span.innerHTML = '';
            continue;
        }

        var rate = 0;
        var taxClass = $('tax_class_id').options[$('tax_class_id').selectedIndex].value;
        eval('var value = taxRates.value_' + taxClass);

        if (value != undefined) {
            rate = value;
        }

        var spanValue = '';
        if (rate != 0) {
            spanValue = ' ' + formatCurrency(input.value/(100+rate)*rate, priceFormat);
        }
        span.innerHTML = spanValue;
    }
}

// Bind tab changes
function bindActiveProductTab(event, ui) {
    var anchor = jQuery(ui.newTab).find('a');
    if (anchor && anchor.name && $('store_switcher')) {
        $('store_switcher').switchParams = 'active_tab/'+anchor.name+'/';
    }
}
//varienGlobalEvents.attachEventHandler('showTab', bindActiveProductTab);
jQuery(document).on('tabsactivate', bindActiveProductTab);

// bind active tab
<?php if($tabsBlock = $this->getLayout()->getBlock('product_tabs')): ?>
jQuery(document).ready(function(){
    if (jQuery('#<?php echo $tabsBlock->getId() ?>').length && jQuery('#<?php echo $tabsBlock->getId() ?>').is(':mage-tabs')) {
        var activeAnchor = jQuery('#<?php echo $tabsBlock->getId() ?>').tabs('activeAnchor');
        if (activeAnchor && $('store_switcher')) {
            $('store_switcher').switchParams = 'active_tab/' + activeAnchor.prop('name') + '/';
        }
    }
});
<?php endif; ?>
//]]>
</script>
