<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
?>
<?php if ($_source->getCustomerBalanceAmount()): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?> class="col name">
        <?php echo __('Store Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?> class="col price"><span class="balance discount">-<?php echo $_order->formatPrice($_source->getCustomerBalanceAmount()) ?></span></td>
</tr>
<?php endif; ?>
