<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
?>
<?php if ($_source->getCustomerBalTotalRefunded()): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?> class="col name">
        <?php echo __('Refunded to Store Credit'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?> class="col price"><?php echo $_order->formatPrice($_source->getCustomerBalTotalRefunded()) ?></td>
</tr>
<?php endif; ?>
