<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     pro_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="checkout-multishipping-payment-giftcardaccount">
<p class="note">
    <?php $_url = Mage::getUrl('checkout/cart'); ?>
    <?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('To add or remove gift cards, <a href="%s">click here</a>.', $_url); ?><br />

    <?php if ((float)$this->getAppliedGiftCardAmount()): ?>
        <?php $amount = Mage::helper('Mage_Core_Helper_Data')->currency($this->getAppliedGiftCardAmount(), true); ?>
        <?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('Gift Card amount applied to order: %s', $amount); ?>
    <?php endif; ?>

    <?php if ($this->isFullyPaidAfterApplication()): ?>
        <script type="text/javascript">
        //<![CDATA[
            Form.getElements('multishipping-billing-form').each(function(elem){
                if (elem.name == 'payment[method]' && elem.value == 'free') {
                    elem.checked = true;
                    elem.disabled = false;
                    elem.parentNode.show();
                } else {
                    elem.parentNode.disabled = true;
                    elem.parentNode.hide();
                }
            });
        //]]>
        </script>
        <input type="hidden" name="payment[method]" value="free" />
    <?php endif; ?>
</p>
</div>
