<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>
<?php $_product = $this->getProduct() ?>
<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_Bundle::/bundle.js') ?>", function() {
            $('#product_addtocart_form').bundleOption({
                bundleConfig: <?php echo $this->getJsonConfig() ?>,
                bundleOptionQtyPrefix: "#bundle-option-",
                bundleOptionQtySuffix: "-qty-input",
                priceSelectors: {
                    "product-price": "#product-price-<?php echo $_product->getId()?>",
                    "bundle-price": "#bundle-price-<?php echo $_product->getId()?>",
                    "price-including-tax": "#price-including-tax-<?php echo $_product->getId()?>",
                    "price-excluding-tax": "#price-excluding-tax-<?php echo $_product->getId()?>"
                }
            });
        });
    })(jQuery);
</script>
<?php endif; ?>
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="stock available" title="<?php echo __('Availability:') ?>">
            <span><?php echo __('In stock') ?></span>
        </p>
    <?php else: ?>
        <p class="stock unavailable" title="<?php echo __('Availability:') ?>">
            <span><?php echo __('Out of stock') ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>
<?php echo $this->getChildHtml('bundle_prices') ?>
