<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_product     = $this->getProduct() ?>
<?php $_priceModel  = $_product->getPriceModel() ?>
<?php list($_minimalPriceTax, $_maximalPriceTax) = $_priceModel->getTotalPrices($_product, null, null, false) ?>
<?php list($_minimalPriceInclTax, $_maximalPriceInclTax) = $_priceModel->getTotalPrices($_product, null, true, false) ?>
<?php $_id = $_product->getId() ?>

<?php $_weeeTaxAmount = 0; ?>

<?php
if ($_product->getPriceType() == 1) {
    $_weeeTaxAmount = $this->helper('\Magento\Weee\Helper\Data')->getAmount($_product);
    $_weeeTaxAmountInclTaxes = $_weeeTaxAmount;
    if ($this->helper('\Magento\Weee\Helper\Data')->isTaxable()) {
        $_attributes = $this->helper('\Magento\Weee\Helper\Data')->getProductWeeeAttributesForRenderer($_product, null, null, null, true);
        $_weeeTaxAmountInclTaxes = $this->helper('\Magento\Weee\Helper\Data')->getAmountInclTaxes($_attributes);
    }
    if ($_weeeTaxAmount && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(0, 1, 4))) {
        $_minimalPriceTax += $_weeeTaxAmount;
        $_minimalPriceInclTax += $_weeeTaxAmountInclTaxes;
    }
    if ($_weeeTaxAmount && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, 2)) {
        $_minimalPriceInclTax += $_weeeTaxAmountInclTaxes;
    }

    if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(1, 2, 4))) {
        $_weeeTaxAttributes = $this->helper('\Magento\Weee\Helper\Data')->getProductWeeeAttributesForDisplay($_product);
    }
}
?>

<div class="price-box">
        <?php if ($_product->getPriceView()): ?>
            <p class="minimal-price">
                <span class="price-label"><?php echo __('As low as') ?>:</span>
                <?php if ($this->displayBothPrices()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo __('Excl. Tax:') ?></span>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceTax) ?>
                    </span>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <span class="price-including-tax">
                        <span class="label"><?php echo __('Incl. Tax:') ?></span>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceInclTax) ?>
                    </span>
            <?php else: ?>
                <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceTax) ?>
                <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                    <span class="weee">(<small>
                        <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                            <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                            <?php else: ?>
                                <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                            <?php endif; ?>

                            <?php echo $_weeeSeparator; ?>
                            <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                            <?php $_weeeSeparator = ' + '; ?>
                        <?php endforeach; ?>
                    </small>)</span>
                <?php endif; ?>
                <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                    <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceInclTax) ?>
                <?php endif; ?>
            <?php endif; ?>
            </p>
        <?php else: ?>
            <?php if ($_minimalPriceTax <> $_maximalPriceTax): ?>
            <p class="price-from">
                <span class="price-label"><?php echo __('From') ?>:</span>
                <?php if ($this->displayBothPrices()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo __('Excl. Tax:') ?></span>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceTax) ?>
                    </span>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <span class="price-including-tax">
                        <span class="label"><?php echo __('Incl. Tax:') ?></span>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceInclTax) ?>
                    </span>
                <?php else: ?>
                    <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceTax) ?>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceInclTax) ?>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
                <?php
                    if ($_product->getPriceType() == 1) {
                        if ($_weeeTaxAmount && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(0, 1, 4))) {
                            $_maximalPriceTax += $_weeeTaxAmount;
                            $_maximalPriceInclTax += $_weeeTaxAmountInclTaxes;
                        }
                        if ($_weeeTaxAmount && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, 2)) {
                            $_maximalPriceInclTax += $_weeeTaxAmountInclTaxes;
                        }
                    }
                ?>
                <p class="price-to">
                    <span class="price-label"><?php echo __('To') ?>:</span>
                    <?php if ($this->displayBothPrices()): ?>
                        <span class="price-excluding-tax">
                            <span class="label"><?php echo __('Excl. Tax:') ?></span>
                            <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_maximalPriceTax) ?>
                        </span>
                        <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                            <span class="weee">(<small>
                                <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                    <?php else: ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                    <?php endif; ?>

                                    <?php echo $_weeeSeparator; ?>
                                    <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                                    <?php $_weeeSeparator = ' + '; ?>
                                <?php endforeach; ?>
                            </small>)</span>
                        <?php endif; ?>
                        <span class="price-including-tax">
                            <span class="label"><?php echo __('Incl. Tax') ?></span>
                            <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_maximalPriceInclTax) ?>
                        </span>
                    <?php else: ?>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_maximalPriceTax) ?>
                        <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                            <span class="weee">(<small>
                                <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                    <?php else: ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                    <?php endif; ?>

                                    <?php echo $_weeeSeparator; ?>
                                    <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                                    <?php $_weeeSeparator = ' + '; ?>
                                <?php endforeach; ?>
                            </small>)</span>
                        <?php endif; ?>
                        <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                            <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_maximalPriceInclTax) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
            <?php else: ?>
                <?php if ($this->displayBothPrices()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo __('Excl. Tax:') ?></span>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceTax) ?>
                    </span>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <span class="price-including-tax">
                        <span class="label"><?php echo __('Incl. Tax:') ?></span>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceInclTax) ?>
                    </span>
                <?php else: ?>
                    <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceTax) ?>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && $this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                        <?php echo $this->helper('\Magento\Core\Helper\Data')->currency($_minimalPriceInclTax) ?>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
</div>
