<?php
/**
 * {license_notice}
 *
 * @category    Magento
 * @package     Mage_Backend
 * @subpackage  unit_tests
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php return array(
    array (
        'type' => 'item',
        'id' => 'elem_one',
        'title' => null,
        'module' => null,
        'sortOrder' => null,
        'action' => null,
        'parent' => null,
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'add',
        'id' => 'elem_one_zero',
        'title' => 'Title one.zero',
        'module' => 'Module_One',
        'sortOrder' => null,
        'action' => 'adminhtml/system',
        'parent' => 'elem_one',
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'add',
        'id' => 'elem_one_one',
        'title' => 'Title one.one',
        'module' => 'Module_One',
        'sortOrder' => null,
        'action' => 'adminhtml/system',
        'parent' => 'elem_one',
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'update',
        'id' => 'elem_one_zero',
        'title' => 'Title one.zero update',
        'module' => 'Module_One_Update',
        'sortOrder' => null,
        'action' => 'adminhtml/system',
        'parent' => 'elem_one',
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'remove',
        'id' => 'elem_one_one',
        'title' => null,
        'module' => null,
        'sortOrder' => null,
        'action' => null,
        'parent' => null,
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'item',
        'id' => 'elem_two',
        'title' => null,
        'module' => null,
        'sortOrder' => null,
        'action' => null,
        'parent' => null,
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'add',
        'id' => 'elem_two_zero',
        'title' => 'Title two.zero',
        'module' => 'Module_Two',
        'sortOrder' => null,
        'action' => 'adminhtml/system',
        'parent' => 'elem_two',
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'add',
        'id' => 'elem_two_two',
        'title' => 'Title two.two',
        'module' => 'Module_Two',
        'sortOrder' => null,
        'action' => 'adminhtml/system',
        'parent' => 'elem_two',
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'update',
        'id' => 'elem_two_zero',
        'title' => 'Title two.zero update',
        'module' => 'Module_Two_Update',
        'sortOrder' => null,
        'action' => 'adminhtml/system',
        'parent' => 'elem_two',
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
    array (
        'type' => 'remove',
        'id' => 'elem_two_two',
        'title' => null,
        'module' => null,
        'sortOrder' => null,
        'action' => null,
        'parent' => null,
        'resource' => null,
        'dependsOnModule' => null,
        'dependsOnConfig' => null,
        ),
);
