<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/* @var $this \Magento\MultipleWishlist\Block\Customer\Wishlist\Management */
?>
<?php if ($this->getCurrentWishlist()): ?>
    <div class="block wishlist management">
        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
            <button type="button" id="wishlist-create-button" data-wishlist-create='{"url":"<?php echo $this->getCreateUrl();?>"}' title="<?php echo __('Create New Wish List') ?>" class="action add"><span><?php echo __('Create New Wish List') ?></span></button>
        <?php endif;?>
        <div class="title">
            <strong>
                <?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?><a href="#" data-wishlist-edit='{"url":"<?php echo $this->getEditUrl($this->getCurrentWishlist()->getId());?>", "name":"<?php echo $this->escapeQuote($this->getCurrentWishlist()->getName(), true);?>", "isPublic":<?php echo $this->getCurrentWishlist()->getVisibility() ? 'true' : 'false';?>}' title="<?php echo __('Edit Wish List')?>" class="action edit"><?php echo __('Edit')?></a> <span class="counter qty"><?php echo $this->getItemCount($this->getCurrentWishlist());?></span>
            </strong>
        </div>
        <?php if ($this->getCurrentWishlist()->getVisibility()): ?>
            <div class="note-msg msg-public"><div><?php echo __('This wishlist is publicly visible.'); ?></div></div>
        <?php else: ?>
            <div class="note-msg msg-private"><div><?php echo __('This wishlist is private. Only you can view this wishlist.');?></div></div>
        <?php endif; ?>
        <div class="content">
            <div class="subtitle">
                <span><?php echo __('Wish List:'); ?></span>
                <div id="wishlists-select" class="split button actions change">
                    <span class="label" title="<?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?>"><?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?></span>
                    <span class="action change" title="<?php echo __('Change') ?>" data-toggle="dropdown"><span><?php echo __('Change') ?></span></span>
                    <ul class="items" data-target="dropdown">
                        <?php foreach($this->getWishlists() as $wishlist): ?>
                            <?php if ($wishlist->getId() != $this->getCurrentWishlist()->getId()): ?>
                                <li class="item"><a title="<?php echo $this->escapeHtml($wishlist->getName());?>" href="<?php echo $this->getWishlistManagementUrl($wishlist);?>"><?php echo $this->escapeHtml($wishlist->getName());?></a></li>
                            <?php endif; ?>
                        <?php endforeach;?>
                        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                            <li class="item"><span class="action new" data-wishlist-create='{"url":"<?php echo $this->getCreateUrl();?>"}' title="<?php echo __('Create New Wish List')?>"><span><?php echo __('Create New Wish List')?></span></span></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
            <?php if($this->getCurrentWishlist()->getItemsCount()): ?>
                <div id="wishlists-move" class="split button actions move" data-wishlist-move='{"moveSelectedUrl":"<?php echo $this->getMoveSelectedUrl();?>", "moveItemUrl":"<?php echo $this->getMoveItemUrl();?>"}'>
                    <span class="label" <?php if ($this->getCurrentWishlist()->getId() != $this->getDefaultWishlist()->getId()): ?>data-wishlist-move-selected='{"wishlistId":"<?php echo $this->getDefaultWishlist()->getId();?>"}'<?php endif;?>><?php echo __('Move to Wish List');?></span>
                    <span class="action change" data-toggle="dropdown"><span><?php echo __('Move To:') ?></span></span>
                    <ul class="items" data-target="dropdown">
                        <?php foreach ($this->getWishlists() as $wishlist): ?>
                            <?php if ($wishlist->getId() !== $this->getCurrentWishlist()->getId()): ?>
                                <li class="item"><span data-wishlist-move-selected='{"wishlistId":"<?php echo $wishlist->getId();?>"}' title="<?php echo $this->escapeHtml($wishlist->getName());?>"><?php echo $this->escapeHtml($wishlist->getName());?></span></li>
                            <?php endif; ?>
                        <?php endforeach;?>
                        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                            <li class="item"><span class="action new" data-wishlist-move-selected='{"new":true}' title="<?php echo __('Create New Wish List')?>" ><span><?php echo __('Create New Wish List')?></span></span></li>
                        <?php endif;?>
                    </ul>
                </div>
                <div id="wishlists-copy" class="split button actions copy" data-wishlist-copy='{"copySelectedUrl":"<?php echo $this->getCopySelectedUrl();?>", "copyItemUrl":"<?php echo $this->getCopyItemUrl();?>"}'>
                    <span class="label" <?php if ($this->getCurrentWishlist()->getId() != $this->getDefaultWishlist()->getId()): ?>data-wishlist-copy-selected='{"wishlistId":"<?php echo $this->getDefaultWishlist()->getId();?>"}'<?php endif;?>><?php echo __('Copy to Wish List');?></span>
                    <span class="action change" data-toggle="dropdown"><span><?php echo __('Copy To:') ?></span></span>
                    <ul class="items" data-target="dropdown">
                        <?php foreach ($this->getWishlists() as $wishlist): ?>
                            <?php if ($wishlist->getId() !== $this->getCurrentWishlist()->getId()): ?>
                                <li class="item"><span data-wishlist-copy-selected='{"wishlistId":"<?php echo $wishlist->getId();?>"}' title="<?php echo $this->escapeHtml($wishlist->getName());?>"><?php echo $this->escapeHtml($wishlist->getName());?></span></li>
                            <?php endif;?>
                        <?php endforeach;?>
                        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                            <li class="item"><span class="action new" data-wishlist-copy-selected='{"new":true}' title="<?php echo __('Create New Wish List')?>"><span><?php echo __('Create New Wish List')?></span></span></li>
                        <?php endif;?>
                    </ul>
                </div>
            <?php endif;?>
        </div>
    </div>
<?php endif; ?>
