<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="home main slider">
    <div class="banner main">
        <img class="banner image" alt="plushe" src="<?php echo $this->getViewFileUrl('images/main_banner.jpg') ?>" />
        <div class="banner content">
            <a class="action banner" href="#"><span>Shop now</span></a>
        </div>
    </div>
</div>

<div class="home banners">
    <a href="#" class="banner link">
        <img class="banner image" alt="plushe" src="<?php echo $this->getViewFileUrl('images/bottom_banners.jpg') ?>" />
    </a>
</div>