<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php echo $this->getItem()->getName() ?>
<div><strong><?php echo __('SKU') ?>:</strong> <?php echo implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($this->escapeHtml($this->getItem()->getSku()))); ?></div>
<?php if ($this->getOrderOptions()): ?>
    <ul class="item-options">
    <?php foreach ($this->getOrderOptions() as $option): ?>
        <li><strong><?php echo $option['label'] ?>:</strong><br />
        <?php if (is_array($option['value'])): ?>
        <?php foreach ($option['value'] as $item): ?>
            <?php echo $this->getValueHtml($item) ?><br />
            <?php endforeach; ?>
        <?php else: ?>
            <?php echo $this->escapeHtml($option['value']); ?>
        <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?php echo $this->escapeHtml($this->getItem()->getDescription()) ?>
