<div class="page-head">
    <h3>Config Variables</h3>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<form action="<?=$postAction?>" method="post" id="form-validate">
<fieldset class="group-select wide">
 <legend>Connection</legend>
    <h4 class="legend">Database connection</h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="host">Host<span class="required">*</span></label><br/>
                <input type="text" name="config[db_host]" id="host" value="<?=$data->getDbHost()?>" title="Database host" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="dbname">Database name<span class="required">*</span></label><br/>
                <input type="text" name="config[db_name]" id="dbname" value="<?=$data->getDbName()?>" title="Database name" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="user">User name<span class="required">*</span></label><br/>
                <input type="text" name="config[db_user]" id="user" value="<?=$data->getDbUser()?>" title="Database user name" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="password">User password<span class="required"></span></label><br/>
                <input type="password" name="config[db_pass]" id="password" value="<?=$data->getDbPass()?>" title="Database user password" class="input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
<!--fieldset class="group-select">
<legend>Path configuration</legend>
    <h3>Path configuration</h3>
    <ul>
        <li>
            <label for="server_path">Server Root:<span class="required">*</span></label><br/>
            <input type="text" name="config[server_path]" id="host" value="<?=$data->getServerPath()?>" title="Server root path" class="required-entry input-text"/>
        </li>
    </ul>
</fieldset-->
<fieldset class="group-select wide">
 <legend>Default store</legend>
    <h4 class="legend">Default store</h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="host">Host:<span class="required">*</span></label><br/>
                <input type="text" name="config[host]" id="host" value="<?=$data->getHost()?>" title="Host name" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="basepath">Base path:<span class="required">*</span></label><br/>
                <input type="text" name="config[base_path]" id="basepath" value="<?=$data->getBasePath()?>" title="WWW base path" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="protocol">Protocol:<span class="required">*</span></label><br/>
                <select name="config[protocol]" id="protocol" title="Protocol" class="required-entry">
                    <option value="http" selected>http</option>
                    <!--option value="https">https</option-->
                </select>
            </div>
            <div class="input-box">
                <label for="port">Port:<span class="required">*</span></label><br/>
                <input type="text" name="config[port]" id="port" value="<?=$data->getPort()?>" title="Port" class="required-entry input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
<fieldset class="group-select wide">
 <legend>Secure connection</legend>
    <h4 class="legend">Secure connection</h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="secure_host">Secure Host:<span class="required">*</span></label><br/>
                <input type="text" name="config[secure_host]" id="secure_host" value="<?=$data->getSecureHost()?>" title="Secure host name" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="secure_basepath">Secure base path:<span class="required">*</span></label><br/>
                <input type="text" name="config[secure_base_path]" id="secure_basepath" value="<?=$data->getSecureBasePath()?>" title="Secure www base path" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="secure_protocol">Secure protocol:<span class="required">*</span></label><br/>
                <select name="config[secure_protocol]" id="secure_protocol" title="Secure protocol" class="required-entry">
                    <option value="http">http</option>
                    <option value="https" selected>https</option>
                </select>
            </div>
            <div class="input-box">
                <label for="secure_port">Secure port:<span class="required">*</span></label><br/>
                <input type="text" name="config[secure_port]" id="secure_port" value="<?=$data->getSecurePort()?>" title="Secure port" class="required-entry input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
<div class="form-buttons">
    <p class="required">* Required Fields</p>
    <button class="form-button" type="submit"/><span>Continue</span></button>
</div>

</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
</script>