<div class="page-head">
    <h3>Administrator account</h3>
</div>
<form action="<?=$postAction?>" method="post" id="form-validate">
<fieldset class="group-select wide">
 <legend>Personal Information</legend>
    <h4 class="legend">Personal Information</h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="firstname">First Name <span class="required">*</span></label><br/>
                <input type="text" name="firstname" id="firstname" value="<?=$data->getFirstname()?>" title="First Name" class="required-entry input-text"/>
            </div>
            <div class="input-box">
                <label for="lastname">Last Name <span class="required">*</span></label><br/>
                <input type="text" name="lastname" id="lastname" value="<?=$data->getLastname()?>" title="Last Name" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <label for="email_address">Email <span class="required">*</span></label><br/>
            <input type="text" name="email" id="email_address" value="<?=$data->getEmail()?>" title="Email Address" class="validate-email required-entry input-text"/>
        </li>
    </ul>
</fieldset>
<fieldset class="group-select wide">
    <legend>Login Information</legend>
    <h4 class="legend">Login Information</h4>
    <ul>
        <li>
            <label for="username">Username <span class="required">*</span></label><br/>
            <input type="text" name="username" id="username" value="<?=$data->getUsername()?>" title="User name" class="required-entry input-text"/>
        </li>
        <li>
            <div class="input-box">
                <label for="password">Password <span class="required">*</span></label><br/>
                <input type="password" name="password" id="password" title="Password"  class="required-entry validate-password input-text"/>
            </div>
            <div class="input-box">
                <label for="confirmation">Confirm Password <span class="required">*</span></label><br/>
                <input type="password" name="confirmation" title="Password Confirmation" id="confirmation" class="required-entry validate-cpassword input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
<div class="form-buttons">
    <p class="required">* Required Fields</p>
    <button class="form-button" type="submit"/><span>Continue</span></button>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
</script>