<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head">
    <h3>You're All Set!</h3>
</div>
<p>Get ready to experience Open-Source eCommerce Evolved.</p>
<p>Before you continue onto your store, make note of your encryption key (Magento uses it to encrypt passwords, credit cards and more).</p>
<p><strong><big><?=$encrypt_key?></big></strong></p>
<p>(Make sure you keep it in a safe place.)</p>
<div class="form-buttons">
    <button class="form-button" onclick="window.location='<?=Mage::getBaseUrl()?>'">Go to Frontend</button>&nbsp;&nbsp;
    <button class="form-button" onclick="window.location='<?=$this->getUrl('admin')?>'">Go to Backend</button>
</div>
