<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\Catalog\Block\Product\Image */ ?>

<span class="img photo container" style="width:<?php echo $this->getProductImageView()->getWidth()?>px;
    height:<?php echo $this->getProductImageView()->getHeight()?>px; display: block; position: relative;
    overflow: hidden"><img class="photo image" style="display: block; position: absolute; top: 0; bottom: 0; left: 0; right: 0;
    margin: auto;" src="<?php echo $this->getProductImageView()->getUrl() ?>"
    alt="<?php echo $this->stripTags($this->getProductImageView()->getLabel(), null, true) ?>"/></span>
