<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/code/Magento/Checkout/view/frontend/onepage/login.phtml
 */
/** @var $this Magento_Checkout_Block_Onepage_Login */
?>
<div class="col2-set">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="col-1">
        <h3><?php if( $this->isAllowedGuestCheckout() ): ?><?php echo __('Checkout as a Guest or Register') ?><?php else: ?><?php echo __('Register to Create an Account') ?><?php endif; ?></h3>
        <?php if( $this->isAllowedGuestCheckout() ): ?>
            <p><?php echo __('Sign up with us to save time on your next checkout:') ?></p>
        <?php else: ?>
            <p><strong><?php echo __('Register and save time!') ?></strong><br />
            <?php echo __('Sign up with us to save time on your next checkout:') ?></p>
            <ul>
                <li><?php echo __('Fast and easy check out') ?></li>
                <li><?php echo __('Get easy access to your order history and status.') ?></li>
            </ul>
        <?php endif; ?>
        <?php if( $this->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if( $this->isAllowedGuestCheckout() ): ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Magento_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo __('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Magento_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo __('Register') ?></label>
                </li>
            </ul>
            <h4><?php echo __('Register and save time!') ?></h4>
            <p><?php echo __('Sign up with us to save time on your next checkout:') ?></p>
            <ul class="ul">
                <li><?php echo __('Fast and easy check out') ?></li>
                <li><?php echo __('Get easy access to your order history and status.') ?></li>
            </ul>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
    </div>
    <div class="col-2">
        <h3><?php echo __('Login') ?></h3>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <h4><?php echo __('Already registered?') ?></h4>
            <p><?php echo __('Please log in below:') ?></p>
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><em>*</em><?php echo __('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text" id="login-email" name="login[username]" data-validate="{required:true, 'validate-email':true}" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo __('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text" id="login-password" name="login[password]" data-validate="{required:true}"/>
                    </div>
                </li>
                <?php echo $this->getChildHtml('login.form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <input name="context" type="hidden" value="checkout" />
        </fieldset>
        </form>
    </div>
</div>
<div class="col2-set">
    <div class="col-1">
        <div class="buttons-set">
            <p class="required">&nbsp;</p>
            <?php if ($this->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="button" data-checkout='{"isGuestCheckoutAllowed":true}'><span><span><?php echo __('Continue') ?></span></span></button>
            <?php elseif ($this->helper('Magento_Checkout_Helper_Data')->isCustomerMustBeLogged()): ?>
                <button id="onepage-guest-register-button" type="button" class="button" data-checkout='{"isGuestCheckoutAllowed":false, "registrationUrl":"<?php echo $this->helper('Magento_Checkout_Helper_Url')->getRegistrationUrl();?>"}'><span><span><?php echo __('Register') ?></span></span></button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="button"><span><span><?php echo __('Register') ?></span></span></button>
                </form>
            <?php endif; ?>
            <span class="please-wait" style="display:none;">
                <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo __('Loading next step...') ?>
            </span>
        </div>
    </div>
    <div class="col-2">
        <div class="buttons-set">
            <p class="required"><?php echo __('* Required Fields') ?></p>
            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo __('Forgot your password?') ?></a>
            <button type="submit" class="button" data-action='login-form-submit'><span><span><?php echo __('Login') ?></span></span></button>
        </div>
    </div>
</div>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#login-form').validation();
            }
        )}
    )(jQuery);
</script>
