<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<h1 class="page-heading">Administrator account</h1>
<form action="<?=$postAction?>" method="post" id="form-validate">
<fieldset class="group-select">
 <legend>Personal Information</legend>
    <h3>Personal Information</h3>
    <ul>
        <li>
            <div class="input-left">
                <label for="firstname">First Name <span class="required">*</span></label><br/>
                <input type="text" name="firstname" id="firstname" value="<?=$data->getFirstname()?>" title="First Name" class="required-entry input-text"/>
            </div>
            <div class="input-left">
                <label for="lastname">Last Name <span class="required">*</span></label><br/>
                <input type="text" name="lastname" id="lastname" value="<?=$data->getLastname()?>" title="Last Name" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <label for="email_address">Email <span class="required">*</span></label><br/>
            <input type="text" name="email" id="email_address" value="<?=$data->getEmail()?>" title="Email Address" class="validate-email required-entry input-text"/>
        </li>
    </ul>
</fieldset>
<fieldset class="group-select">
    <legend>Login Information</legend>
    <h3>Login Information</h3>
    <ul>
        <li>
            <label for="username">Username <span class="required">*</span></label><br/>
            <input type="text" name="username" id="username" value="<?=$data->getUsername()?>" title="User name" class="required-entry input-text"/>
        </li>
        <li>
            <div class="input-left">
                <label for="password">Password <span class="required">*</span></label><br/>
                <input type="password" name="password" id="password" title="Password"  class="required-entry validate-password input-text"/>
            </div>
            <div class="input-right">
                <label for="confirmation">Confirm Password <span class="required">*</span></label><br/>
                <input type="password" name="confirmation" title="Password Confirmation" id="confirmation" class="required-entry validate-cpassword input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
    <div class="buttons-container">
        <p class="required">* Required Fields</p>
        <input type="submit" class="input-button" value="Continue"/>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
</script>