<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_pro
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Installation start page
 *
 * @see Mage_Install_Block_Begin
 */
?>
<div class="page-head">
    <h3><?php echo $this->__("Welcome to Magento's Installation Wizard") ?>!</h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if(count($this->getMessagesBlock()->getMessages())==0): ?>
<form action="<?php echo $this->getPostUrl() ?>" method="post">
<div style="height:20em; border:1px solid #ccc; margin-bottom:8px; padding:5px; background:#fff; overflow: auto; overflow-x:hidden; overflow-y:scroll;">
<?php echo $this->getLicenseHtml() ?>
</div>

<script type="text/javascript">
//<![CDATA[
function changeSubmitStatus(obj) {
    $('submitButton').disabled = !obj.checked;
    if(obj.checked){
        $('submitButton').removeClassName("disabled");
    }
    else{
        $('submitButton').addClassName("disabled");
    }
}
//]]>
</script>
    <p>
        <input type="checkbox" name="agree" value="1" id="agree" onclick="changeSubmitStatus(this)" class="checkbox" />
        <label for="agree"><?php echo $this->__('I\'ve reviewed and executed the Magento Commercial License Agreement and agree to the terms in full.') ?></label>
    </p>
    <div class="button-set">
        <button class="form-button disabled" type="submit" id="submitButton" disabled="disabled"><span><?php echo $this->__('Continue') ?></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded", function() {
  changeSubmitStatus($('agree'));
});
//]]>
</script>
<?php endif ?>
