<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_order=$this->getOrder() ?>
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th class="a-left" bgcolor="#d9e5ee" style="padding:3px 9px">Item</th>
            <th class="a-center" bgcolor="#d9e5ee" style="padding:3px 9px">Qty</th>
            <th class="a-right" bgcolor="#d9e5ee" style="padding:3px 9px">Subtotal</th>
        </tr>
    </thead>

    <tbody>
<?php $i=0; foreach ($_order->getAllItems() as $_item): $i++ ?>
        <tr <?php echo $i%2?'bgcolor="#eeeded"':'' ?>>
            <td align="left" valign="top" style="padding:3px 9px"><?php echo $_item->getName() ?></td>
            <td align="center" valign="top" style="padding:3px 9px"><?php echo sprintf('%s', $_item->getQtyOrdered()) ?></td>
            <td align="right" valign="top" style="padding:3px 9px">
            <?php if ($this->helper('\Magento\Tax\Helper\Data')->displayCartPriceExclTax() || $this->helper('\Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
                <?php if ($this->helper('\Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
                    <span class="label"><?php echo __('Excl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                    <?php echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                <?php else: ?>
                    <?php echo $_order->formatPrice($_item->getRowTotal()) ?>
                <?php endif; ?>

                <?php if ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item)): ?>
                    <br />
                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                        <small>
                        <?php foreach ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                        <?php endforeach; ?>
                        </small>
                    <?php elseif ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                        <?php foreach ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                        <?php endforeach; ?>
                    <?php elseif ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                        <small>
                        <?php foreach ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>

                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                        <br />
                        <span class="nobr"><?php echo __('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>


            <?php if ($this->helper('\Magento\Tax\Helper\Data')->displayCartPriceInclTax() || $this->helper('\Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
                <?php if ($this->helper('\Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
                    <br /><span class="label"><?php echo __('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('\Magento\Checkout\Helper\Data')->getSubtotalInclTax($_item); ?>
                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                        <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                    <?php else: ?>
                        <?php echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                    <?php endif; ?>
                <?php if ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item)): ?>
                    <br />
                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                        <small>
                        <?php foreach ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                        <?php endforeach; ?>
                        </small>
                    <?php elseif ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                        <?php foreach ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                        <?php endforeach; ?>
                    <?php elseif ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                        <small>
                        <?php foreach ($this->helper('\Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                            <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                        <?php endforeach; ?>
                        </small>
                    <?php endif; ?>
        
                    <?php if ($this->helper('\Magento\Weee\Helper\Data')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                        <span class="nobr"><?php echo __('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
            </td>
        </tr>
<?php endforeach ?>
    </tbody>

    <tfoot>
        <tr>
            <td colspan="2" align="right" style="padding:3px 9px"><?php echo __('Subtotal') ?></td>
            <td align="right" style="padding:3px 9px"><?php echo $_order->formatPrice($_order->getSubtotal()) ?></td>
        </tr>
        <?php if ($_order->getDiscountAmount()): ?>
            <tr>
                <td colspan="2" align="right" style="padding:3px 9px"><?php echo __('Discount') ?></td>
                <td align="right" style="padding:3px 9px"><?php echo $_order->formatPrice($_order->getDiscountAmount()) ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_order->getShippingAmount()): ?>
            <tr>
                <td colspan="2" align="right" style="padding:3px 9px"><?php echo __('Shipping Amount') ?></td>
                <td align="right" style="padding:3px 9px"><?php echo $_order->formatPrice($_order->getShippingAmount()) ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_order->getTaxAmount()): ?>
            <tr>
                <td colspan="2" align="right" style="padding:3px 9px"><?php echo __('Tax Amount') ?></td>
                <td align="right" style="padding:3px 9px"><?php echo $_order->formatPrice($_order->getTaxAmount()) ?></td>
            </tr>
        <?php endif; ?>
        <tr bgcolor="#DEE5E8">
            <td colspan="2" align="right" style="padding:3px 9px"><strong><big><?php echo __('Grand Total') ?></big></strong></td>
            <td align="right" style="padding:6px 9px"><strong><big><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></big></strong></td>
        </tr>
    </tfoot>

</table>
