<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Businessinfo_Tile */
?>
<article class="sl-step <?php echo $this->getTileStateStyle(); ?>" id="article-<?php echo $this->getTileCode()?>">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Store Info') ?></h2>
    <div class="create">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Confirm your business address and set the Store Emails that you want to use for customer communications.') ?>
        </p>
        <button class="button drawer-open" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
            save-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/save') ?>"
            load-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Confirm Info') ?>
        </button>
    </div>

    <div class="completed">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <p><strong><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Business Address') ?></strong></p>
        <?php foreach ($this->getAddress() as $addressValue): ?>
            <p><?php echo $addressValue; ?></p>
        <?php endforeach; ?>
        <button class="button drawer-open" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
            save-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/save') ?>"
            load-url="<?php echo $this->getUrl('*/storelauncher_businessinfo_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Edit Store Info') ?>
        </button>
        <?php endif;?>
    </div>
</article>
