<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Tax_Tile*/
?>
<article class="sl-step <?php echo $this->getTileStateStyle(); ?>" id="article-<?php echo $this->getTileCode()?>">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Tax Rules') ?></h2>
    <div class="create">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('You can upload your current tax rules, create new ones, or we can recommend them based on your business location.') ?>
        </p>
        <button class="button drawer-open" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
            save-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/save') ?>"
            load-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Set Tax Rules') ?>
        </button>
    </div>

    <div class="completed">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <button class="button" onclick="window.location = '<?php echo $this->getUrl('adminhtml/tax_rule/index'); ?>';">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Set Additional Tax Rules') ?>
        </button>
        <?php endif; ?>
    </div>
</article>
