<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this \Magento\Adminhtml\Block\Page\System\Config\Robots\Reset
 * @var $coreHelper \Magento\Core\Helper\Data
 */
$coreHelper = $this->helper('\Magento\Core\Helper\Data');
?>

<script type="text/javascript">
    function resetRobotsToDefault()
    {
        $('design_search_engine_robots_custom_instructions').value = <?php
            echo $coreHelper->jsonEncode($this->getRobotsDefaultCustomInstructions())
        ?>;
    }
</script>

<?php echo $this->getButtonHtml() ?>
