<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this Magento_Adminhtml_Block_Page_System_Config_Robots_Reset
 * @var $coreHelper Mage_Core_Helper_Data
 */
$coreHelper = Mage::helper('Mage_Core_Helper_Data');
?>

<script type="text/javascript">
    function resetRobotsToDefault()
    {
        $('design_search_engine_robots_custom_instructions').value = <?php
            echo $coreHelper->jsonEncode($this->getRobotsDefaultCustomInstructions())
        ?>;
    }
</script>

<?php echo $this->getButtonHtml() ?>
