<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form class="form orders search" id="oar-widget-orders-and-returns-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Order Information') ?></span></legend><br />
        <div class="field required">
            <label class="label" for="oar-order-id"><span><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Order ID') ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="oar-order-id" name="oar_order_id" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field required">
            <label class="label" for="oar-billing-lastname"><span><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Billing Last Name') ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="oar-billing-lastname" name="oar_billing_lastname" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field required">
            <label class="label" for="quick-search-type-id"><span><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Find Order By:') ?></span></label>
            <div class="control">
                <select name="oar_type" id="quick-search-type-id" class="select">
                   <option value="email"><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Email Address'); ?></option>
                   <option value="zip"><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('ZIP Code'); ?></option>
                </select>
            </div>
        </div>
        <div id="oar-email" class="field required">
            <label class="label" for="oar_email"><span><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Email Address') ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="oar_email" name="oar_email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div id="oar-zip" class="field required">
            <label class="label" for="oar_zip"><span><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Billing ZIP Code') ?></span></label>
            <div class="control">
                <input type="text" class="input-text" id="oar_zip" name="oar_zip" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions">
        <button type="submit" title="<?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Continue') ?>" class="action submit"><span><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Continue') ?></span></button>
    </div>
</form>
<script type="text/javascript">
    head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
        "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
        "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
        "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
        "<?php echo $this->getViewFileUrl('Mage_Sales::orders-returns.js');?>", function() {
            jQuery('#oar-widget-orders-and-returns-form').ordersReturns().validation();
    });
</script>
