<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var \Magento\Framework\Pricing\Render\Amount $this */ ?>

<span class="price-container <?php echo $this->getAdjustmentCssClasses() ?>"
        <?php echo $this->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <?php if ($this->getDisplayLabel()): ?>
        <span class="price-label"><?php echo $this->getDisplayLabel(); ?></span>
    <?php endif; ?>
    <span<?php if ($this->getPriceId()): ?> id="<?php echo $this->getPriceId() ?>"<?php endif;?>
        <?php echo ($this->getPriceDisplayLabel()) ? 'data-label="' . $this->getPriceDisplayLabel() . $this->getPriceDisplayInclExclTaxes() . '"' : '' ?>
        class="price-wrapper <?php echo $this->getPriceWrapperCss(); ?>"
        <?php echo $this->getSchema() ? ' itemprop="price"' : '' ?>>
        <?php echo $this->convertAndFormatCurrency($this->getDisplayValue(), (bool)$this->getIncludeContainer()) ?>
    </span>
    <?php if ($this->hasAdjustmentsHtml()): ?>
        <?php echo $this->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($this->getSchema()): ?>
        <meta itemprop="priceCurrency" content="<?php echo $this->getDisplayCurrencyCode()?>" />
    <?php endif; ?>
</span>
