<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var \Magento\Framework\Pricing\Render\Amount $this */ ?>

<span class="price-container <?php echo $this->getAdjustmentCssClasses() ?>">
<?php if ($this->getPriceDisplayLabel()): ?>
    <?php if ($this->getDisplayLabel()): ?>
        <span class="price-label"><?php echo $this->getDisplayLabel(); ?></span>
    <?php endif; ?>
    <?php if ($this->hasAdjustmentsHtml()): ?>
        <?php echo $this->getAdjustmentsHtml() ?>
    <?php endif; ?>
        <span id="<?php echo $this->getPriceId() ?>"
            <?php echo ($this->getPriceDisplayLabel()) ? 'data-label="' . $this->getPriceDisplayLabel() . $this->getPriceDisplayInclExclTaxes() . '"' : '' ?>
              class="price-wrapper <?php echo $this->getPriceWrapperCss(); ?>">
        <?php echo $this->convertAndFormatCurrency($this->getDisplayValue(), (bool)$this->getIncludeContainer()) ?>
    </span>
<?php else: ?>
    <?php if ($this->getDisplayLabel()): ?>
        <span class="price-label"><?php echo $this->getDisplayLabel(); ?></span>
    <?php endif; ?>
    <span id="<?php echo $this->getPriceId() ?>"
        <?php echo ($this->getPriceDisplayLabel()) ? 'data-label="' . $this->getPriceDisplayLabel() . $this->getPriceDisplayInclExclTaxes() . '"' : '' ?>
      class="price-wrapper <?php echo $this->getPriceWrapperCss(); ?>">
        <?php echo $this->convertAndFormatCurrency($this->getDisplayValue(), (bool)$this->getIncludeContainer()) ?>
    </span>
    <?php if ($this->hasAdjustmentsHtml()): ?>
        <?php echo $this->getAdjustmentsHtml() ?>
    <?php endif; ?>
<?php endif; ?>
</span>
