<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Magento_Paypal_Block_System_Config_Fieldset_Store
 */
?>
<script type="text/javascript">

Event.observe(window, 'load', function () {
    var pConfigDisabler = new PaypalConfigDisabler;
    var disabledMethods = <?php echo $this->helper('Magento\Core\Helper\Data')->jsonEncode($this->getPaypalDisabledMethods()); ?>;
    pConfigDisabler.disableMethods(disabledMethods);
});

PaypalConfigDisabler = Class.create();
PaypalConfigDisabler.prototype = {
    initialize: function () {
        this.methods = $H({
            express: $H({fieldset: 'express'}),
            wps: $H({fieldset: 'wps'}),
            wpp: $H({fieldset: 'wpp'}),
            wpppe: $H({fieldset: 'wpp_pe'}),
            expresspe: $H({fieldset: 'express_pe'}),
            verisign: $H({fieldset: 'verisign'}),
            wpppl: $H({fieldset: 'payflow_link'}),
            hosted_pro: $H({fieldset: 'hosted_pro'})
        });
    },

    getMethods: function ()
    {
        return this.methods;
    },

    getMethod: function (method)
    {
        return this.methods.get(method);
    },

    getMethodFieldset: function (method)
    {
        var fieldsetId = 'paypal_' + this.getMethod(method).get('fieldset');
        return $(fieldsetId);
    },

    disableMethod: function (method)
    {
        this.hideFieldset(this.getMethodFieldset(method));
    },

    disableMethods: function (methods)
    {
        for(var methodId in methods) {
            this.disableMethod(methodId);
        }
    },

    hideFieldset: function (fieldset)
    {
        this.disableValueElements(fieldset);
        fieldset.hide();
        var heading = fieldset.previous('div');
        var headingLink = heading.down('a');
        heading.addClassName('disabled');
        headingLink.onclick = "return false;";
        headingLink.href = "javascript:void(0)";
    },

    disableValueElements: function (container)
    {
        $(container).select('select', 'input', 'textarea', 'button').each(function (elem) {
            elem.addClassName('disabled');
        });
    }
}
</script>
