<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     pro_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Check
 */
?>
<div class="giftcard-status">
    <div class="page-title">
        <h1><?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('Gift Card status'); ?></h1>
    </div>
<?php if ($this->getCode()): ?>
    <?php echo $this->getChildHtml('check_result') ?>
<?php endif; ?>
    <form method="post" id="codeForm">
        <fieldset>
            <ul class="form-list">
                <li>
                    <label for="code"><?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('Enter Gift Card code'); ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry" name="giftcard_code" id="code" value="<?php echo $this->escapeHtml($this->getCode()) ?>" />
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="buttons-set">
             <button type="button" title="<?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('Check'); ?>" class="button" onclick="cForm.submit()"><span><span><?php echo Mage::helper('Enterprise_GiftCardAccount_Helper_Data')->__('Check'); ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    var cForm = new VarienForm('codeForm');
    </script>
</div>
