<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * Declare a list of components and its dependencies to resources
 * @var $this Mage_Core_Block_Template
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        $.mage.isDevMode(<?php echo Mage::getIsDeveloperMode() ?>);

        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            form: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.tmpl.min.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/backend/form.js') ?>'
            ],
            button: [
                '<?php echo $this->getViewFileUrl('mage/backend/button.js') ?>'
            ],
            validation: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/translate.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/validation.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/backend/validation.js') ?>'
            ],
            notification: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.tmpl.min.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/backend/notification.js') ?>'
            ],
            loader: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.tmpl.min.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/translate.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/loader.js') ?>'
            ],
            floatingHeader: [
                '<?php echo $this->getViewFileUrl('mage/backend/floating-header.js') ?>',
            ],
            suggest: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.tmpl.min.js') ?>',
                '<?php echo $this->getViewFileUrl('json2.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/backend/suggest.js') ?>'
            ]
        })
        /**
         * Declaration of resources for components (based on previously defined components)
         */
        .extend('multisuggest', 'suggest',
            '<?php echo $this->getViewFileUrl('mage/backend/multisuggest.js') ?>'
        )
        .extend('treeSuggest', 'multisuggest', [
            '<?php echo $this->getViewFileUrl('jquery/jstree/jquery.hotkeys.js') ?>',
            '<?php echo $this->getViewFileUrl('jquery/jstree/jquery.jstree.js') ?>',
            '<?php echo $this->getViewFileUrl('mage/backend/tree-suggest.js') ?>'
        ])
        /**
         * Load resources in advance for components which needed to be instantiated without delay.
         */
        .load('loader');
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>
