<div class="page-head">
    <h3><?=__('My Account')?></h3>
</div>
<?=$this->getChildHtml('hello')?>
<?=$this->getChildHtml('top')?>
<div class="account-box">
    <div class="head">
        <h4><?=__('Account Information')?></h4>
    </div>
    <?=$this->getChildHtml('info')?>
    <?=$this->getChildHtml('address')?>
</div>

<div class="account-box">
    <div class="col2-set">
        <div class="col-1">
            <?=$this->getChildHtml('info1')?>
        </div>
        <div class="col-2">
            <?=$this->getChildHtml('info2')?>
        </div>
    </div>
</div>