<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div id="rma_reason_container" class="rma-popup" style="display:none">
    <div class="popup-window-wrapper">
        <div class="popup-window-title">
            <div class="title">
                <?php echo __('Reason to Return') ?>
            </div>
        </div>
        <div id="rma_reason_content" class="popup-window-content"></div>
        <div class="popup-window-buttons-set">
            <div class="f-right">
                <button class="action-ok ok_button" type="button">
                    <span><?php echo __('OK') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    document.observe('dom:loaded', function () {
        $('edit_form').insert({
            bottom: $('rma_reason_container')
        });
    });
//]]>
</script>
