<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $params = array(
        'url' => $this->getUrl('page_cache/block/render/'),
        'handles' => $this->getLayout()->getUpdate()->getHandles(),
        'versionCookieName' => \Magento\PageCache\Model\Version::COOKIE_NAME
    );
?>
<script type="text/javascript">
    //<![CDATA[
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_PageCache::js/page-cache.js')?>", function () {
            $('body').pageCache(<?php echo json_encode($params); ?>);
        });
    })(jQuery);
    //]]>
</script>