<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<span>
<label for="shipping_address:email">Email</label>
<input id="shipping_address:email" name="email" value="" class="input-text" type="text">
</span>
<span>
<label for="shipping_address:firstname">First Name</label>
<input id="shipping_address:firstname" name="firstname" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:lastname">Last Name</label>
<input id="shipping_address:lastname" name="lastname" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:company">Company</label>
<input id="shipping_address:company" name="company" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:street">Street Address</label>
<input id="shipping_address:street" name="street" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:city">City</label>
<input id="shipping_address:city" name="city" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:region">State/Province</label>
<input id="shipping_address:region" name="region" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:postcode">Zip/Post Code</label>
<input id="shipping_address:postcode" name="postcode" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:telephone">Telephone</label>
<input id="shipping_address:telephone" name="telephone" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:fax">Fax</label>
<input id="shipping_address:fax" name="fax" value="" class="input-text" type="text">
</span>
<span class="field-row">
<label for="shipping_address:customer_notes">Customer Notes</label>
<input id="shipping_address:customer_notes" name="customer_notes" value="" class="input-text" type="text">
</span>
