<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_Backend
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var $this \Magento\Backend\Block\Widget\Button
 */
?>
<?php echo $this->getBeforeHtml(); ?>
<button <?php echo $this->getAttributesHtml(), $this->getUiId(); ?>>
    <span><?php echo $this->getLabel(); ?></span>
</button>
<?php echo $this->getAfterHtml(); ?>
