<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<div class="order-page">
<div class="page-title title-buttons">
    <h1><?php echo __('Order #%1 - %2', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo __('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul>
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><strong><?php echo $_link->getLabel() ?></strong></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </dd>
</dl>
<p class="order-date"><?php echo __('Order Date: %1', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set">
    <div class="col-1">
        <div class="info-box">
            <h2 class="box-title"><?php echo __('Shipping Address') ?></h2>
            <address class="box-content"><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>
    </div>
    <div class="col-2">
        <div class="info-box">
            <h2 class="box-title"><?php echo __('Shipping Method') ?></h2>
            <div class="box-content">
        <?php if ($_order->getShippingDescription()): ?>
            <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
        <?php else: ?>
            <?php echo __('No shipping information available'); ?>
        <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set">
    <div class="col-1">
        <div class="info-box">
            <h2 class="box-title"><?php echo __('Billing Address') ?></h2>
            <address class="box-content"><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
    </div>
    <div class="col-2">
        <div class="info-box">
            <h2 class="box-title"><?php echo __('Payment Method') ?></h2>
            <div class="box-content"><?php echo $this->getPaymentInfoHtml() ?></div>
        </div>
    </div>
</div>
</div>
