<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var \Magento\Ui\Component\Layout\Tabs $this
 */
?>
<?php echo $this->begin(); ?>
    <div class="tab-switcher" style="float: left; width: 20%;">
        <h3>
            <span>Basic Settings</span>
        </h3>
        <ul>
            <?php for($i = 10; --$i;): ?>
                <h4>Product Details</h4>
            <?php endfor; ?>
        </ul>
    </div>
    <div class="tabs-content" style="width: 80%; float: right;">
        <?php for($i = 10; --$i;): ?>
            <div class="fieldset-wrapper customer-information">
                <p>Tabs content</p>
            </div>
        <?php endfor; ?>
    </div>
<div style="clear: both"></div>
<?php echo $this->begin(); ?>