<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/*
 * Aviable methods
 * getCanDisplayContainer() - container visibility flag
 * getItems()				- comapare items collection
 * getId()					- html id of block
 * getJsObjectName()		- js object name of controller
 * getAddUrlTemplate()		- add url template
 * getRemoveUrlTemplate()	- remove url template
 */
?>
<?if($this->getCanDisplayContainer()):?>
<div class="box mini-compare-products" id="<?=$this->getId()?>" <?if($this->getItems()->getSize()==0):?> style="display:none;"<?endif;?>>
<?endif;?>
<?if($this->getItems()->getSize()>0):?>
	<div class="head">
			<span class="corner"></span>
			<h3><?=__('Compare Products')?> <span class="count"><?=__('(%d items)', $this->getItems()->getSize())?></span></h3>
	</div>
	<div class="box-container">
	<div class="content">
		<ul class="widget-list">
			<?$_i=1?>
			<?foreach($this->getItems() as $_index=>$_item):?>
			<li class="block-compare-item <?if($_i==$this->getItems()->getSize()):?>last<?endif;?>">
					<input type="hidden" class="compare-item-id" value="<?=$_item->getId()?>"><a href="#" onclick="<?=$this->getJsObjectName()?>.removeItem(this);return false;"  class="action"><strong><?=__('Remove')?></strong></a><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></li>
			<?$_i++?>
			<?endforeach;?>
		</ul>
		<p class="actions">
		<button class="form-button" onclick="window.location.href = '<?=$this->getCompareUrl()?>'"><span><?=__('Compare')?></span></button>
		<a href="#" onclick="<?=$this->getJsObjectName()?>.removeAll(); return false">Clear All</a>
	</p>
</div>
</div>
<?endif;?>
</div>
<?if($this->getCanDisplayContainer()):?>	
<script type="text/javascript">
<!--
	var <?=$this->getJsObjectName()?> = new Varien.CompareController('<?=$this->getId()?>',{
		updateUrl: '<?=$this->getAddUrlTemplate()?>',
		removeUrl: '<?=$this->getRemoveUrlTemplate()?>',
		successMessage: '<?=__('Product have been successfully added to comparasion list')?>',
		confirmMessage: '<?=__('Are you sure')?>'
	});
//-->
</script>
<?endif;?>