<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
		<head>
			<title>Magento Commerce - Administrative Panel</title>
			<style type="text/css" media="all">
				/*<![CDATA[*/ @import "<?=$baseUrl?>skins/adminhtml/styles.css"; /*]]>*/
			</style>
			<link rel="stylesheet" type="text/css" media="screen, projection" href="<?=$baseUrl?>skins/adminhtml/menu-top.css" />
			<!--[if IE]> <link rel="stylesheet" href="<?=$baseUrl?>skins/adminhtml/iestyles.css" type="text/css" media="all" /> <![endif]-->
			<!--[if lt IE 7]><script defer type="text/javascript" src="<?=$baseUrl?>js/lib/ds-sleight.js"></script><![endif]-->
			<script type="text/javascript" src="<?=$baseUrl?>js/lib/dropdown.js"></script>
		</head>
		<body>
			<div class="header">
				<a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/logo.gif" alt="Magento logo" class="logo"/></a>
				<div class="header-right">
					<p><strong>Minu Oh</strong> (Administrator)<span class="separator">|</span><a href="#">Logout</a></p>
					<fieldset>
						<input type="text" class="input-text" value="Search by Keyword"/>
					</fieldset>
				</div>
				<div class="clear"></div>

				<?=$this->getLayout()->createBlock('adminhtml/page_menu')->toHtml()?>

			</div>
			<div class="middle">
				<ul class="breadcrumbs">
					<li><a href="#">Home</a> &raquo;</li>
					<li><a href="#">Customer</a> &raquo;</li>
					<li>#0011234</li>
				</ul>
				<div class="container"><!-- accomodates the section-menu by border width (for IE bug) -->
					<div class="main">
						<div class="content-container"><!-- content positioning -->
							<div class="content"><!-- content presentation -->
								<div class="head">
									<table cellspacing="0">	
										<tr>
											<td style="width:50%;"><h2>Minu Oh - Customer View</h2></td>
											<td class="buttons"><strong class="button"><span>Save</span></strong></td>
										</tr>
									</table>
								</div>
								<div class="box-left customer-personal">
									<h3>Personal Information</h3>
									<div class="box">
										<p><strong>Last Logged in:</strong> June, 16, 2007 ( Currently <strong>OFFLINE</strong> )</p>
										<p><strong>Account Created:</strong> April 1, 2001</p>
										<address>
										<strong>Contact Information</strong><br/>Minu Oh ( <a href="mailto:minu@varien.com">minu@varien.com</a>)<br/>
										3402  Motor Ave Suite B<br/>
										Los Angeles, CA 90034<br/>
										United States<br/>
										<small><strong>T</strong> |</small> (310) 123-1234</address>
									</div>
								</div>
								<div class="box-right sales-tally">
									<h3>Sales Tally</h3>
									<div class="box">
										<table cellspacing="0" class="data">
											<thead>
												<tr>
													<th>&nbsp;</th>
													<th>Lifetime Sales</th>
													<th>Average Sale</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td class="label">Site 1</td>
													<td>$1899.82</td>
													<td>$82.99</td>
												</tr>
												<tr class="even">
													<td class="label">Site 1</td>
													<td>$1899.82</td>
													<td>$82.99</td>
												</tr>
												<tr>
													<td class="label">Site 1</td>
													<td>$1899.82</td>
													<td>$82.99</td>
												</tr>
												<tr class="even">
													<td class="label">Site 1</td>
													<td>$1899.82</td>
													<td>$82.99</td>
												</tr>
												<tr>
													<td class="label">Site 1</td>
													<td>$1899.82</td>
													<td>$82.99</td>
												</tr>
												<tr class="even">
													<td class="label">Site 1</td>
													<td>$1899.82</td>
													<td>$82.99</td>
												</tr>
											</tbody>
											<tfoot>
												<tr>
													<td class="label"><big>Total</big></td>
													<td><big>$9000.82</big></td>
													<td><big>$400.99</big></td>
												</tr>
											</tfoot>
										</table>
									</div>
								</div>
								<div class="clear"></div>
								<br/>
								<h3>Sales Stat</h3>
								<dl class="accordion">
									<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Last 5 Orders</strong></dt>
									<dd></dd>
									<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Wishlist</strong> (5 items)</dt>
									<dd class="grid open">
										<table cellspacing="0" class="data">
											<thead>
												<tr>
													<th>Product ID</th>
													<th>Product Name</th>
													<th>Price</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>00212</td>
													<td>Some sort of product name goes here</td>
													<td class="price">$82.99</td>
												</tr>
												<tr class="even">
													<td>00212</td>
													<td>Some sort of product name goes here</td>
													<td class="price">$82.99</td>
												</tr>
												<tr>
													<td>00212</td>
													<td>Some sort of product name goes here</td>
													<td class="price">$82.99</td>
												</tr>
												<tr class="even">
													<td>00212</td>
													<td>Some sort of product name goes here</td>
													<td class="price">$82.99</td>
												</tr>
												<tr>
													<td>00212</td>
													<td>Some sort of product name goes here</td>
													<td class="price">$82.99</td>
												</tr>
												<tr class="even">
													<td>00212</td>
													<td>Some sort of product name goes here</td>
													<td class="price">$82.99</td>
												</tr>
											</tbody>
											<tfoot>
												<tr>
													<td colspan="2" class="a-right"><strong>Total</strong></td>
													<td><strong>$400.99</strong></td>
												</tr>
											</tfoot>
										</table></dd>
									<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Gift Registries</strong> (0 items)</dt>
									<dd></dd>
									<dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Shopping Cart</strong> (1 item)</dt>
									<dd></dd>
								</dl>
							</div>
						</div>
	<!--[ends] .content -->
						<div class="section-menu">
							<h2>Customer Insight</h2>
							<ul>
								<li><a href="#">Customer View</a></li>
								<li><a href="#">Account Information</a></li>
								<li><a href="#">Addresses</a></li>
								<li><a href="#">Orders</a></li>
								<li><a href="#">Gift Registries</a></li>
								<li><a href="#">Product Reviews</a></li>
								<li><a href="#">Wishlist</a></li>
								<li><a href="#">Shopping Cart</a></li>
								<li><a href="#">Newsletter</a></li>
							</ul>
						</div>
<!--[ends] .section-menu -->
					</div>
				</div>
			</div>
<!--[ends] .middle -->

			<div class="footer">
				<p>Copyright &copy; 2007 Magento Commerce. All Right Reserved.<br/>
				<strong>Version 1.0</strong> | Powered by <a href="#">Varien</a></p>
			</div>
    </body>
</html>