<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <script type="text/javascript" language="Javascript">
            Ext = top.jsFrame.Ext;
            top.location.href = '#/test';
            var BASE_URL = '<?=$baseUrl?>admin/';
            var SKIN_URL = '<?=$baseUrl?>skins/admin/';
        </script>
    </head>
    <body>
        <div class="header">
        </div>
        <?include 'topmenu.phtml'?>
    </body>
</html>