<?/*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <title>Magento Admin</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
    <script type="text/javascript" src="<?=$baseJsUrl?>prototype/prototype.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>scriptaculous/scriptaculous.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>prototype/validation.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/events.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/grid.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/tabs.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/form.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>adminhtml/loader.js"></script>

    <script type="text/javascript">
        var BASE_URL = '<?=$baseUrl?>adminhtml/';
        var SKIN_URL = '<?=$baseUrl?>skins/adminhtml/';
    </script>

	<style type="text/css" media="all">
		/*<![CDATA[*/ @import "<?=$baseUrl?>skins/adminhtml/styles.css"; /*]]>*/
	</style>
	<!--[if IE]> <link rel="stylesheet" href="<?=$baseUrl?>skins/adminhtml/iestyles.css" type="text/css" media="all" /> <![endif]-->
	<!--[if lt IE 7]><script defer type="text/javascript" src="<?=$baseUrl?>js/lib/ds-sleight.js"></script><![endif]-->

    <link rel="stylesheet" type="text/css" media="screen, projection" href="<?=$baseUrl?>skins/adminhtml/menu-top.css" />
	<script type="text/javascript" src="<?=$baseJsUrl?>listmenu/menu.js"></script>

	<link rel="stylesheet" type="text/css" media="all" href="<?=$baseJsUrl?>calendar/calendar-win2k-1.css" title="win2k-1" />
    <script type="text/javascript" src="<?=$baseJsUrl?>calendar/calendar.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>calendar/lang/calendar-en.js"></script>
    <script type="text/javascript" src="<?=$baseJsUrl?>calendar/calendar-setup.js"></script>
</head>
<body>
	<table cellspacing="0" width="100%">
		<tr>
			<td class="header">
        <?=$this->getChildHtml('header')?>
        <div class="clear"></div>
        <?=$this->getChildHtml('menu')?>
    </td></tr>
		<tr>
		<td class="middle">
        <?=$this->getChildHtml('breadcrumbs')?>
        <?if($this->getChildHtml('left')):?>
        <div class="container">
            <div class="main">
                <div class="content-container">
                    <div class="content" id="content">
                    <?=$this->getChildHtml('content')?>
                    </div>
<!--[ends] .content -->
                </div>
                <div class="section-menu">
                <?=$this->getChildHtml('left')?>
									<div class="bottom">
									</div>
                </div>
<!--[ends] .section-menu -->
            </div>
        </div>
        <?else:?>
        <div class="simple-container">
            <?=$this->getChildHtml('content')?>
        </div>
        <?endif;?>
    </td>
		</tr>
<!--[ends] .middle -->
    <tr>
			<td class="footer">
        <?=$this->getChildHtml('footer')?>
    </td>
		</tr>
	<table>
    <?//=$this->getChildHtml('profiler')?>
</body>
</html>