<?/*{
    "children":{
        "header":"Header",
        "menu":"Top navigation",
        "breadcrumbs":"Breadcrumbs",
        "content":"Content block",
        "left":"Left navigation",
        "footer":"Footer"
    }
}*/?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <title>Magento Admin</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
        <script type="text/javascript" src="<?=$baseJsUrl?>prototype/prototype.js"></script>
        <script type="text/javascript" src="<?=$baseJsUrl?>prototype/validation.js"></script>
<?/*
        <link rel="stylesheet" type="text/css" media="all" href="<?=$baseJsUrl?>extjs/resources/css/ext-all.css"/>
        <link rel="stylesheet" type="text/css" media="all" href="<?=$baseJsUrl?>extjs/resources/css/ytheme-default.css" id="theme_stylesheet"/>
    
        <script type="text/javascript" src="<?=$baseJsUrl?>extjs/adapter/yui/yui-utilities.js"></script>
        <script type="text/javascript" src="<?=$baseJsUrl?>extjs/adapter/yui/ext-yui-adapter.js"></script>
        <script type="text/javascript" src="<?=$baseJsUrl?>extjs/ext-all.js"></script>
        <script type="text/javascript">
    
            Ext.BLANK_IMAGE_URL = '<?=$baseJsUrl?>extjs/resources/images/default/s.gif';
            Ext.UpdateManager.defaults.loadScripts = false;
            Ext.UpdateManager.defaults.disableCaching = true;
            //top.location.href = '<?=$baseUrl?>adminhtml/#controller/action/id/123';
            //top.document.title = 'Testing dynamic title';
            var BASE_URL = '<?=$baseUrl?>admin/';
            var SKIN_URL = '<?=$baseUrl?>skins/admin/';
        </script>
*/?>        
        <style type="text/css" media="all">
            /*<![CDATA[*/ @import "<?=$baseUrl?>skins/adminhtml/styles.css"; /*]]>*/
        </style>
    </head>
    <body>
        <div class="header">
            <?=$header?>
            <div class="clear"></div>
            <?=$menu?>
        </div>
        <div class="middle">
            <?=$breadcrumbs?>
            <div class="container">
                <div class="main">
                    <div class="content-container">
                        <div class="content">
                        <?=$content?>
                        </div>
<!--[ends] .content -->

                    </div>
                    <div class="section-menu">
                    <?=$left?>
                    </div>
<!--[ends] .section-menu -->                    
                </div>
            </div>
        </div>
<!--[ends] .middle -->
        <div class="footer">
            <?=$footer?>
        </div>
    </body>
</html>