SET NAMES utf8;

SET SQL_MODE='';

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';





ALTER TABLE `poll_vote` ADD `ip_address` BIGINT NULL ,
ADD `customer_id` INT NULL ;

ALTER TABLE `poll` ADD `website_id` SMALLINT NOT NULL ;

ALTER TABLE `poll` ADD `date_posted` DATETIME NOT NULL ,
ADD `date_closed` DATETIME NULL ,
ADD `status` SMALLINT NOT NULL DEFAULT '0';





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
