<div class="content-header">
	<table cellspacing="0" class="grid-header">
		<tr>
			<td style="width:50%;"><h3 class="icon-head head-newsletter-list"><?=$this->getHeaderText()?></h3></td>
			<td class="form-buttons">
				<button class="scalable add" onclick="window.location='<?=$this->getCreateUrl()?>'">
					<table cellspacing="0">
						<tr>
							<td class="tl"></td>
							<td class="tr"></td>
						</tr>
						<tr>
							<td class="ml"><span><?=__('Add New Template');?></span></td>
							<td class="mr"></td>
						</tr>
						<tr>
							<td class="bl"></td>
							<td class="br"></td>
						</tr>
					</table>
				</button>
			</td>
		</tr>
	</table>
</div>
<div>
    <?=$this->getChildHtml('grid')?>
</div>