<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<script type="text/javascript">
//<![CDATA[
    document.observe('dom:loaded', function () {
        var rma = new AdminRma(<?php ///*echo $this->getOrderDataJson()*/ ?>);
        rma.setLoadAttributesUrl('<?php echo $this->getLoadAttributesUrl() ?>');
        rma.setLoadSplitLineUrl('<?php echo $this->getLoadSplitLineUrl() ?>');
        rma.setDeleteLineLabel('<?php echo __('Delete Line') ?>');
        $$('a.item_details').each(function(obj) {
            obj.observe('click', rma.itemDetailsRowClick.bind(rma))
        });
        $$('a.item_split_line').each(function(obj) {
            obj.observe('click', rma.itemSplitLineRowClick.bind(rma))
        });
        $$('a.item_reason_other').each(function(obj) {
            obj.observe('click', rma.itemReasonOtherRowClick.bind(rma))
        });
        rma.setLoadShippingMethodsUrl('<?php echo $this->getLoadShippingMethodsUrl() ?>');
        rma.setLoadPslUrl('<?php echo $this->getLoadPslUrl() ?>');
        if ($('get-shipping-method-and-rates')) {
            $('get-shipping-method-and-rates').observe('click', rma.showShippingMethods.bind(rma));
        }
    });
//]]>
</script>
