<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button"
            title="<?php echo __('Proceed to Checkout') ?>"
            class="action primary checkout<?php echo($this->isDisabled()) ? ' disabled' : ''; ?>"
            <?php if ($this->isDisabled()):?>disabled="disabled"<?php endif; ?>
            onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
                <span><?php echo __('Proceed to Checkout') ?></span>
    </button>
<?php endif?>
