<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form id="co-payment-form" class="form payments">
    <?php echo $this->getBlockHtml('formkey') ?>
    <fieldset class="fieldset">
        <?php echo $this->getChildChildHtml('methods_additional') ?>
        <div id="checkout-payment-method-load"><?php echo $this->getChildHtml('methods') ?></div>
    </fieldset>
    <?php echo $this->getChildChildHtml('additional') ?>
    <div class="actions" id="payment-buttons-container">
        <div class="primary">
            <button type="button" class="button action continue"><span><?php echo __('Continue') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="#"><span><?php echo __('Back') ?></span></a>
        </div>
        <span id="payment-please-wait" class="please-wait load indicator" style="display:none">
            <span><?php echo __('Loading next step...') ?></span>
        </span>
    </div>
</form>
