<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Checkout\Block\Onepage\Progress */
?>
<div class="opc-block-progress<?php if ($this->isStepComplete('billing')): ?> active<?php endif; ?>">
    <div class="title">
        <strong><?php echo __('Your Checkout Progress') ?></strong>
    </div>
    <div class="content">
        <dl class="items">
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <?php if ($this->isStepComplete('billing')): ?>
            <dt class="item-title complete">
                <span><?php echo __('Billing Address') ?></span>
                <a href="#billing" data-goto-section="billing" class="action billing"><?php echo __('Change') ?></a>
            </dt>
            <dd class="item-content complete">
                <address><?php echo $this->getBilling()->format('html') ?></address>
            </dd>
        <?php else: ?>
            <dt class="item-title">
                <?php echo __('Billing Address') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
        <?php if ($this->isStepComplete('shipping')): ?>
            <dt class="item-title complete">
                <span><?php echo __('Shipping Address') ?></span>
                <a href="#payment" data-goto-section="shipping" class="action shipping address"><?php echo __('Change') ?></a>
            </dt>
            <dd class="item-content complete">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </dd>
        <?php else: ?>
            <dt class="item-title">
                <span><?php echo __('Shipping Address') ?></span>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <?php if ($this->isStepComplete('shipping_method')): ?>
            <dt class="item-title complete">
                <span><?php echo __('Shipping Method') ?></span>
                <a href="#shipping_method" data-goto-section="shipping_method" class="action shipping method"><?php echo __('Change') ?></a>
            </dt>
            <dd class="item-content complete">
                <?php if ($this->getShippingMethod()): ?>
                    <?php echo $this->escapeHtml($this->getShippingDescription()) ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo __('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo __('Shipping method has not been selected yet') ?>
                <?php endif; ?>
            </dd>
        <?php else: ?>
            <dt class="item-title">
                <span><?php echo __('Shipping Method') ?></span>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if ($this->isStepComplete('payment')): ?>
            <dt class="item-title complete">
                <span><?php echo __('Payment Method') ?></span>
                <a href="#payment" data-goto-section="payment" class="action payment method"><?php echo __('Change') ?></a>
            </dt>
            <dd class="item-content complete">
                <?php echo $this->getPaymentHtml() ?>
            </dd>
        <?php else: ?>
            <dt class="item-title">
                <span><?php echo __('Payment Method') ?></span>
            </dt>
        <?php endif; ?>
        <?php endif; ?>
        </dl>
    </div>
</div>
