<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product description template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php $_description = $this->getProduct()->getDescription(); ?>
<?php if ($_description): ?>
    <div class="std">
        <?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($this->getProduct(), $_description, 'description') ?>
    </div>
<?php endif; ?>
