<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var $this Magento_Page_Block_Links
 */
?>
<?php if ($links = $this->getLinks()): ?>
<ul <?php if ($this->hasCssClass()): echo 'class="' . $this->escapeHtml($this->getCssClass()) . '"'; endif; ?>>
<?php foreach ($links as $link): ?>
    <?php echo $this->renderLink($link) ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>
