<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Template for \Magento\Page\Block\Html
 */
$bodyCss = $this->getBodyClass() ? $this->getBodyClass() : '';
?>
<!doctype html>
<html lang="<?php echo $this->getLang() ?>" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <?php echo $this->getChildHtml('head') ?>
</head>
<body class="page popup<?php echo $bodyCss ?>">
    <?php echo $this->getChildHtml('after_body_start') ?>
    <div class="page wrapper">
        <?php echo $this->getChildHtml('main') ?>
    </div>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
