<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Template for Magento_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-print<?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
<?php echo $this->getChildHtml('after_body_start') ?>
<div>
    <div class="print-head">
        <img src="<?php echo $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getViewFileUrl('images/logo_print.gif') ?>" class="logo" alt="" />
        <?php if ($this->getPrintLogoText()):?>
            <address><?php echo nl2br($this->escapeHtml($this->getPrintLogoText())) ?></address>
        <?php endif;?>
    </div>
    <?php echo $this->getChildHtml('content') ?>
    <div class="buttons-set">
        <button type="button" title="<?php echo __('Close Window') ?>" class="button" onclick="window.close();"><span><span><?php echo __('Close Window') ?></span></span></button>
    </div>
    <?php echo $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
