<meta http-equiv="Content-Type" content="<?=$this->getContentType()?>"/>
<meta name="description" content="<?=$this->getDescription()?>"/>
<meta name="keywords" content="<?=$this->getKeywords()?>"/>
<meta name="robots" content="<?=$this->getRobots()?>"/>
<?=$this->getAdditionalCssJs()?>
<?=$this->getChildHtml()?>

<link rel="icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon"/>
<?=$this->helper('core/js')->includeScript('varien/js.js')?>
<?=$this->helper('core/js')->includeScript('varien/form.js')?>
<?=$this->helper('core/js')->includeScript('varien/menu.js')?>
<?=$this->helper('core/js')->includeScript('mage/translate.js')?>
<?=$this->helper('core/js')->includeScript('mage/cookies.js')?>
<?=$this->helper('core/js')->getTranslatorScript()?>
<script type="text/javascript">
    var BLANK_URL = '<?=$this->getJsUrl()?>blank.html';
</script>
<link rel="stylesheet" href="<?=$this->getSkinUrl('css/styles.css')?>" type="text/css" media="all"/>
<!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('css/iestyles.css')?>" type="text/css" media="all"/> <![endif]-->
<!--[if IE 7]> <link rel="stylesheet" href="<?=$this->getSkinUrl('css/ie7.css')?>" type="text/css" media="all"/> <![endif]-->
<!--[if lt IE 7]>
    <link rel="stylesheet" href="<?=$this->getSkinUrl('css/ie7minus.css')?>" type="text/css" media="all"/>
    <?=$this->helper('core/js')->includeScript('lib/ds-sleight.js')?>
    <?=$this->helper('core/js')->includeScript('varien/iehover-fix.js')?>
<![endif]-->

<link rel="stylesheet" href="<?=$this->getSkinUrl('css/print.css')?>" type="text/css" media="print" />