<!-- [starts] pager // -->
<?if($this->getCollection()->getSize()):?>
    <div class="pager">
	    <div class="pages">
		    Skip to Page:
			<ol>
            <?if ($this->getCollection()->getCurPage() != 1):?>
                <li><a href="<?=$this->getPreviousPageUrl()?>">Previous Page</a></li>
            <?endif?>
            <?for($i=$this->getCollection()->getCurPage(-3); $i <= $this->getCollection()->getCurPage(+3); $i++):?>
                <?if ($i == $this->getCollection()->getCurPage()):?>
				    <li><span class="on"><?=$i?></span></li>
                <?else:?>
				    <li><a href="<?=$this->getPageUrl($i)?>"><?=$i?></a></li>
                <?endif?>
            <?endfor?>
            <?if ($this->getCollection()->getCurPage() < $this->getCollection()->getLastPageNumber()):?>
                <li><a href="<?=$this->getNextPageUrl()?>">Next Page</a></li>
            <?endif?>
			</ol>
		</div>
		<p class="currently-viewing">Items <strong><?=$this->getFirstItemNum()?></strong> to <strong><?=$this->getLastItemNum()?></strong> of <strong><?=$this->getCollection()->getSize()?> total</strong></p>
	</div>
    <?if($this->getViewBy()):?>
	<div class="view-by">
        <?if($this->getIsViewBy('mode')):?>
	    <p class="listing-type">View products as 
            <?if($this->getIsViewBy('mode','grid')):?>
                <a href="<?=$this->getFeaturedPagerUrl(array('mode'=>'grid'))?>"><img src="<?=$this->getSkinUrl('images/listing_type_grid.gif')?>" alt="View listings in grid format" class="v-middle"/></a>
            <?endif?>
            <?if($this->getIsViewBy('mode','list')):?>
                <a href="<?=$this->getFeaturedPagerUrl(array('mode'=>'list'))?>"><img src="<?=$this->getSkinUrl('images/listing_type_list.gif')?>" alt="View listings in list format" class="v-middle"/></a>
            <?endif?>
        </p>
        <?endif?>
        <?if($this->getIsViewBy('limit')):?>
		<p class="data-per-page">Show <select name="" onChange="location.href=this.value">
            <?for($i=3; $i <= 27; $i+=3):?>
                <option value="<?=$this->getFeaturedPagerUrl(array('limit'=>$i))?>"<?if($i == $this->getCollection()->getPageSize()):?> selected<?endif?>><?=$i?></option>
            <?endfor?>
            </select> per page</p>
        <?endif?>
        <?if($this->getIsViewBy('order')):?>
		<p class="sort-by">Sort by <select name="" onChange="location.href=this.value">
            <?foreach($this->getViewBy('order') as $val):?>
                <option value="<?=$this->getFeaturedPagerUrl(array('order'=>$val,'dir'=>'asc'))?>"<?if($val == $this->getRequest()->getParam('order')):?> selected<?endif;?>><?=ucfirst($val)?></option>
            <?endforeach;?>
            </select></p>
        <?endif?>
	</div>
    <?endif?>
<?endif?>
<!-- [ends] pager // -->

