<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this \Magento\Sales\Block\Recurring\Profile\View */ ?>

<div class="order-page">

<!-- title 'n' actions -->
<div class="page-title title-buttons">
    <h1><?php echo __('Recurring Profile # %1', $this->escapeHtml($this->getReferenceId())) ?></h1>
    <?php if ($this->getCanCancel()): ?>
        <button type="button" title="<?php echo __('Cancel') ?>" class="button" onclick="if( confirm('<?php echo $this->getConfirmationMessage() ?>') ) { window.location.href = '<?php echo $this->getCancelUrl() ?>'; } return false;"><span><span><?php echo __('Cancel') ?></span></span></button>
    <?php endif; ?>
    <?php if ($this->getCanSuspend()): ?>
        <button type="button" title="<?php echo __('Suspend') ?>" class="button" onclick="if( confirm('<?php echo $this->getConfirmationMessage() ?>') ) { window.location.href = '<?php echo $this->getSuspendUrl() ?>'; } return false;"><span><span><?php echo __('Suspend') ?></span></span></button>
    <?php endif; ?>
    <?php if ($this->getCanActivate()): ?>
        <button type="button" title="<?php echo __('Activate') ?>" class="button" onclick="if( confirm('<?php echo $this->getConfirmationMessage() ?>') ) { window.location.href = '<?php echo $this->getActivateUrl() ?>'; } return false;"><span><span><?php echo __('Activate') ?></span></span></button>
    <?php endif; ?>
    <?php if ($this->getCanUpdate()):?>
        <button type="button" title="<?php echo __('Get Update') ?>" class="button" onclick="if( confirm('<?php echo $this->getConfirmationMessage() ?>') ) { window.location.href = '<?php echo $this->getUpdateUrl() ?>'; } return false;"><span><span><?php echo __('Get Update') ?></span></span></button>
    <?php endif;?>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<!-- info tabs -->
<?php $layout = $this->getLayout(); ?>
<?php $infoTabs = $this->getGroupChildNames('info_tabs'); ?>
<dl class="order-info">
    <dt><?php echo __('About This Profile:') ?></dt>
    <dd>
        <ul id="order-info-tabs">
        <?php foreach ($infoTabs as $elementName): ?>
            <?php $block = $layout->getBlock($elementName); ?>
            <?php if (!$block) continue; ?>
            <?php if ($this->getObjectData($block, 'is_view_current')): ?>
                <li class="current"><strong><?php echo $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></strong></li>
            <?php else: ?>
                <li><a href="<?php echo $this->escapeHtml($this->getObjectData($block, 'view_url')) ?>"><?php echo $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </dd>
</dl>

<!-- info blocks in 2 columns -->
<?php for ($i = 1; $i <= 5; $i++):?>
    <?php $infoBlocks = $this->getGroupChildNames("info_blocks_row_{$i}"); ?>
    <?php if ($infoBlocks):?>
<div class="col2-set order-info-box">
        <?php for ($j = 1; $j <= 2; $j++):?>
            <?php foreach ($infoBlocks as $elementName):?>
        <?php $block = $layout->getBlock($elementName); ?>
        <?php if (!$block) continue; ?>
<?php if ($j == $this->getObjectData($block, 'view_column')):?>
    <div class="col-<?php echo $j?>">
        <div class="info-box">
            <div class="box-title">
                <h2><?php echo $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></h2>
            </div>
            <div class="box-content">
                <?php $html = $layout->renderElement($elementName); ?>
                <?php echo ($html ? $html : __('No information available.')) ; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
            <?php endforeach;?>
        <?php endfor;?>
</div>
    <?php endif; ?>
<?php endfor;?>

<!-- table data block -->
<?php $table = $this->getChildBlock('table') ?>
<?php if ($table):?>
<div>
    <h2 class="table-caption"><?php echo $this->escapeHtml($this->getObjectData($table, 'view_label')) ?></h2>
    <?php echo $this->getChildHtml('table') ?>
</div>
<?php endif;?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo __('Back to Recurring Billing Profiles') ?></a></p>
    </div>
</div>
