<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Category title template
 *
 * @see \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $this->getCurrentCategory();
?>
<hgroup class="page category title yyy">
    <h1 class="title"><?php echo $_helper->categoryAttribute($_category, $this->getCurrentCategory()->getName(), 'name') ?></h1>
    <?php if($this->IsRssCatalogEnable()): ?>
        <a href="<?php echo $this->getRssLink() ?>" title="<?php echo __('Subscribe to RSS Feed') ?>" class="action rss"><?php echo __('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
</hgroup>
