<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme */?>

<li id="theme-id-<?php echo $this->getTheme()->getId() ?>" style="margin:20px; float:left;">
    <ul class="theme-element-customizations">
        <li class="theme-header">
            <span class="theme-title">
                <?php echo $this->getTheme()->getThemeTitle() ?>
            </span>
            <?php if ($this->getTheme()->getAssignedStores()): ?>
                <?php echo $this->__('Store View applied to:') . ' ' . implode(', ', $this->getStoresTitles()) ?>
            <?php endif; ?>
        </li>
        <li class="theme-front-customizations">
            <div style="margin:0 auto; height:350px; width:350px; border:1px solid black;">
                <img src="<?php echo $this->getTheme()->getPreviewImageUrl() ?>" style="display:block; height:350px; width:350px;" alt="" />
                <div class="theme-buttons">
                    <?php echo $this->getButtonsHtml() ?>
                </div>
            </div>
        </li>
    </ul>
</li>
