<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_Weee_Block_Renderer_Weee_Tax */?>
<div id="attribute-<?php echo $this->getElement()->getHtmlId(); ?>-container" class="field"
     data-element-id="<?php echo $this->getElement()->getHtmlId(); ?>"
     data-mage-init="{fptAttribute:{
        region: <?php echo $this->escapeHtml($this->helper('Magento_Directory_Helper_Data')->getRegionJson()) ?>,
        itemsData: <?php echo $this->escapeHtml($this->helper('Magento_Core_Helper_Data')->jsonEncode($this->getValues())); ?>,
        bundlePriceType: '#price_type'
        }}">
    <label class="label"><span><?php echo $this->getElement()->getLabel() ?></span></label>

    <div class="control">
        <table class="data-table" cellspacing="0">
            <thead>
            <tr class="headings">
                <th <?php if (!$this->isMultiWebsites()): ?>style="display:none"<?php endif; ?>><?php echo __('Website') ?></th>
                <th><?php echo __('Country/State') ?><span class="required">*</span></th>
                <th><?php echo __('Tax') ?><span class="required">*</span></th>
                <th><?php echo __('Action') ?></th>
            </tr>
            </thead>
            <tbody data-role="fpt-item-container">
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
    <script data-role="row-template" type="text/x-jquery-tmpl">
        <tr id="<?php echo $this->getElement()->getHtmlId() ?>_weee_tax_row_${index}" data-role="fpt-item-row">
            <td <?php if (!$this->isMultiWebsites()): ?>style="display: none"<?php endif; ?>>
                <select name="<?php echo $this->getElement()->getName() ?>[${index}][website_id]"
                        class="<?php echo $this->getElement()->getClass() ?> website required-entry" data-role="select-website">
                    <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
                    <option value="<?php echo $_websiteId ?>"><?php echo $_info['name'] ?><?php if (!empty($_info['currency'])): ?>[<?php echo $_info['currency'] ?>]<?php endif; ?></option>
                    <?php endforeach ?>
                </select>
            </td>
            <td>
                <select id="<?php echo $this->getElement()->getName() ?>_weee_tax_row_${index}_country"
                        name="<?php echo $this->getElement()->getName() ?>[${index}][country]"
                        class="<?php echo $this->getElement()->getClass() ?> country required-entry" data-role="select-country">
                    <?php foreach ($this->getCountries() as $_country): ?>
                    <option value="<?php echo $_country['value'] ?>"><?php echo htmlspecialchars($_country['label']) ?></option>
                    <?php endforeach ?>
                </select>
                <select id="<?php echo $this->getElement()->getName() ?>_weee_tax_row_${index}_state"
                        name="<?php echo $this->getElement()->getName() ?>[${index}][state]"
                        class="<?php echo $this->getElement()->getClass() ?> state" disabled="" data-role="select-state">
                    <option value="0">*</option>
                </select>
            </td>
            <td>
                <input name="<?php echo $this->getElement()->getName() ?>[${index}][price]"
                       class="<?php echo $this->getElement()->getClass() ?> required-entry validate-greater-than-zero"
                       type="text" value="${value}"/>
            </td>
            <td>
                <input name="<?php echo $this->getElement()->getName() ?>[${index}][delete]" class="delete" type="hidden" value="" data-role="delete-fpt-item"/>
                <?php echo $this->getChildHtml('delete_button') ?>
            </td>
        </tr>
    </script>
</div>
