<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form class="form wishlist share" action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post" data-hasrequired="<?php echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php echo __('Sharing Information') ?></span></legend><br />
        <div class="field emails required">
            <label class="label" for="email_address"><span><?php echo __('Email addresses, separated by commas') ?></span></label>
            <div class="control">
                <textarea name="emails" cols="60" rows="5" id="email_address" data-validate="{required:true,'validate-emails':true}"><?php echo $this->getEnteredData('emails') ?></textarea>
            </div>
        </div>
        <div class="field text">
            <label class="label" for="message"><span><?php echo __('Message') ?></span></label>
            <div class="control">
                <textarea id="message" name="message" cols="60" rows="5"><?php echo $this->getEnteredData('message') ?></textarea>
            </div>
        </div>
        <?php if($this->helper('Magento\Wishlist\Helper\Data')->isRssAllow()): ?>
        <div class="field choice rss">
            <input type="checkbox" name="rss_url" id="rss_url" value="1" title="<?php echo __('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?>" class="checkbox" />
            <label class="label" for="rss_url"><span><?php echo __('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?></span></label>
        </div>
        <?php endif; ?>
    </fieldset>
    <div class="actions">
        <div class="primary">
            <button type="submit" title="<?php echo __('Share Wishlist') ?>" class="action submit"><span><?php echo __('Share Wishlist') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $this->getBackUrl(); ?>"><span><?php echo __('Back')?></span></a></p>
        </div>
    </div>
</form>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                $('#form-validate').validation();
            })
    })(jQuery);
</script>
