<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Wishlist\Block\Customer\Sidebar */
?>
<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
<?php $imageBlock =  $this->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');?>
<div class="block wishlist">
    <div class="title">
        <strong><?php echo $this->getTitle(); ?></strong>
    </div>
    <div class="content">
    <strong class="subtitle"><?php echo __('Last Added Items') ?></strong>
    <?php if ($this->hasWishlistItems()): ?>
    <ol class="items minilist products" id="wishlist-sidebar">
    <?php $iterator = 1; ?>
    <?php foreach ($this->getWishlistItems() as $_item): ?>
        <?php $product = $_item->getProduct(); ?>
        <?php echo ($iterator++==1) ? '<li class="item product">' : '</li><li class="item product">' ?>
            <div class="product">
                <a class="product photo" href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
                    <?php echo $imageBlock->init($product, 'wishlist_sidebar_block')->toHtml() ?>
                </a>
                <div class="product details">
                    <strong class="product name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></strong>
                    <?php echo $this->getPriceHtml($product, false, '-wishlist') ?>
                    <div class="product actions">
                        <?php if ($product->isSaleable() && $product->isVisibleInSiteVisibility()): ?>
                            <div class="primary"><a href="<?php echo $this->getItemAddToCartUrl($_item) ?>" class="action tocart"><span><?php echo __('Add to Cart') ?></span></a></div>
                        <?php endif; ?>
                        <div class="secondary">
                            <a href="<?php echo $this->getItemRemoveUrl($_item) ?>" title="<?php echo __('Remove This Item') ?>" onclick="return confirm('<?php echo __('Are you sure you would like to remove this item from the wishlist?') ?>');" class="action delete">
                                <span><?php echo __('Remove This Item') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php echo ($iterator==count($this->getWishlistItems())+1) ? '</li>' : '' ?>
    <?php endforeach; ?>
    </ol>
    <div class="actions">
        <a class="action details" href="<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getListUrl() ?>"><span><?php echo __('Go to Wish List') ?></span></a>
    </div>
    <?php else: ?>
        <p class="empty"><?php echo __('You have no items in your wish list.') ?></p>
    <?php endif ?>
    </div>
</div>
<?php endif ?>
