<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->canShowButton()): ?>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanExternalCacheUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('Magento_PageCache_Helper_Data')->__('Flush External Page Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('Magento_PageCache_Helper_Data')->__('External full page cache.')?>
        </td>
    </tr>
</table>
<?php endif;?>
