<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="add-to-cart">
    <?php if (!$_product->isGrouped()): ?>
    <label for="qty"><?php echo $this->__('Qty:') ?></label>
    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>"
           title="<?php echo $this->__('Qty') ?>" class="input-text qty" data-validate="{required:true,digits:true}"/>
    <?php endif; ?>
    <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" id="product-addtocart-button">
        <span><span><?php echo $buttonTitle ?></span></span></button>
    <?php echo $this->getChildHtml('', true) ?>
</div>
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[
    (function ($) {
        $.mage.event.observe('product.addtocart.button', function (event, cartData) {
            var initData = {
                cartButtonId: "#product-addtocart-button",
                cartForm: "#product_addtocart_form"
            };
            cartData.cartFormData.push(initData);
        });
        $.mage.load.js("<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>");
        $.mage.load.js("<?php echo $this->getViewFileUrl('jquery/jquery.hook.js')?>");
        $.mage.load.jsSync("<?php echo $this->getViewFileUrl('Mage_Catalog::js/msrp.js') ?>");
    })(jQuery);
    //]]>
</script>
