<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="add-to-cart">
    <?php if (!$_product->isGrouped()): ?>
    <label for="qty"><?php echo $this->__('Qty:') ?></label>
    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>"
           title="<?php echo $this->__('Qty') ?>" class="input-text qty" data-validate="{required:true,digits:true}"/>
    <?php endif; ?>
    <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" id="product-addtocart-button">
        <span><span><?php echo $buttonTitle ?></span></span></button>
    <?php echo $this->getChildHtml('', true) ?>
</div>
<?php endif; ?>

<script type="text/javascript">
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
            "<?php echo $this->getViewFileUrl('Mage_Catalog::js/msrp.js') ?>", function () {
            $('#product_addtocart_form').addToCart({
                cartButtonId: "#product-addtocart-button",
                cartForm: "#product_addtocart_form"
            }).validation({
                    errorPlacement: function (error, element) {
                        if (element.hasClass("validate-one-checkbox-required-by-name")) {
                            error.appendTo('#links-advice-container');
                        } else if (element.is(':radio, :checkbox')) {
                            element.closest('ul').after(error);
                        } else {
                            element.after(error);
                        }
                    },
                    highlight: function (element, errorClass) {
                        if ($(element).is(':radio, :checkbox')) {
                            $(element).closest('ul').addClass(errorClass);
                        } else {
                            $(element).addClass(errorClass);
                        }
                    },
                    unhighlight: function (element, errorClass) {
                        if ($(element).is(':radio, :checkbox')) {
                            $(element).closest('ul').removeClass(errorClass);
                        } else {
                            $(element).removeClass(errorClass);
                        }
                    }
                });
        });
    })(jQuery);
</script>
