<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="block dashboard addresses">
    <div class="title">
        <strong><?php echo $this->__('Address Book') ?></strong> 
        <a class="action edit" href="<?php echo $this->getAddressBookUrl() ?>"><span><?php echo $this->__('Manage Addresses') ?></span></a>
    </div>
    <div class="content">
        <div class="box address billing">
            <strong class="subtitle">
                <span><?php echo $this->__('Default Billing Address') ?></span>
                <a class="action edit" href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><span><?php echo $this->__('Edit Address') ?></span></a>
            </strong>
            <address>
                <?php echo $this->getPrimaryBillingAddressHtml() ?>
            </address>
        </div>
        <div class="box address shipping">
            <strong class="subtitle">
                <span><?php echo $this->__('Default Shipping Address') ?></span>
                <a class="action edit" href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><span><?php echo $this->__('Edit Address') ?></span></a>
            </strong>
            <address>
                <?php echo $this->getPrimaryShippingAddressHtml() ?>
            </address>
        </div>
    </div>
</div>
