<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_Rma_Block_Adminhtml_Rma_Edit_Tab_General_Details
 */

$customerLink = $this->getCustomerLink();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Request Details') ?></h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('ID') ?></label></td>
                    <td class="value"><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('#') . $this->getRmaData('increment_id') ?></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Order ID') ?></label></td>
                    <td class="value"><a href="<?php echo $this->getOrderLink() ?>"><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('#') . $this->getOrderIncrementId() ?></a></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Customer Name') ?></label></td>
                    <td class="value">
                        <?php
                            if ($customerLink) {
                                echo '<a href="' . $customerLink . '">';
                            }
                            echo $this->getCustomerName();
                            if ($customerLink) {
                                echo '</a>';
                            }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Email Address') ?></label></td>
                    <td class="value"><a href="mailto:<?php echo $this->getCustomerEmail() ?>"><?php echo $this->getCustomerEmail() ?></a></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Contact Email Address') ?></label></td>
                    <td class="value"><a href="mailto:<?php echo $this->getCustomerContactEmail() ?>"><?php echo $this->getCustomerContactEmail() ?></a></td>
                </tr>
            </table>
        </div>
    </div>
</div>
