<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this Enterprise_Rma_Block_Adminhtml_Rma_Edit_Tab_General_History" */
?>
<div class="order-comments-history rma-comments-history">
<div class="fieldset-wrapper" id="rma-history-block">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('RMA History') ?></span>
    </div>
    <div id="history_form" class="rma-history-form">
        <div>
            <label class="normal" for="history_comment"><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Comment Text') ?></label>
            <textarea name="comment[comment]" rows="3" cols="5" id="history_comment"></textarea>
        </div>
        <div class="clearfix">
            <div class="actions">
                <?php echo $this->getChildHtml('submit_button') ?>
            </div>
            <div class="order-history-comments-options">
                <?php if ($this->canSendCommentEmail()): ?>
                    <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1" /><label class="normal" for="history_notify"><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Notify Customer by Email') ?></label><br />
                <?php endif; ?>
                <input name="comment[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Visible on Frontend') ?></label>
            </div>
        </div>
        <?php if($this->getComments()): ?>
            <ul class="note-list">
            <?php foreach ($this->getComments() as $_item): ?>
                <li>
                    <strong><?php echo $this->helper('Mage_Core_Helper_Data')->formatDate($_item->getCreatedAt(), 'medium') ?></strong>
                    <strong><?php echo $this->helper('Mage_Core_Helper_Data')->formatTime($_item->getCreatedAt(), 'medium') ?></strong>
                    <strong>
                        <?php if ($_item->getIsAdmin()): ?>
                            <?php echo $this->__('Customer Service')?>
                        <?php else: ?>
                            <?php echo $this->escapeHtml($this->getCustomerName())?>
                        <?php endif; ?>
                    </strong>
                    <div>
                    <?php echo $this->helper('Enterprise_Rma_Helper_Data')->__('Customer') ?>
                    <strong class="subdue">
                        <?php if ($_item->getIsCustomerNotified()): ?>
                        <?php echo $this->helper('Enterprise_Rma_Helper_Data')->__('Notified') ?>
                        <img src="<?php echo $this->getViewFileUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                        <?php else: ?>
                        <?php echo $this->helper('Enterprise_Rma_Helper_Data')->__('Not Notified') ?>
                        <?php endif; ?>
                    </strong>
                    <?php if ($_item->getComment()): ?>
                        <br/><?php echo $this->escapeHtml($_item->getComment(), array('b','br','strong','i','u')) ?>
                    <?php endif; ?>
                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php endif ?>
    </div>
</div>
</div>