<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_Rma_Block_Adminhtml_Rma_Edit_Tab_General_Shippingaddress
 */
?>
<?php if ($this->getOrderShippingAddress()) : ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('Enterprise_Rma_Helper_Data')->__('Order Shipping Address') ?></h4>
        </div>
        <fieldset>
            <br />
            <address><?php echo $this->getOrderShippingAddress() ?></address>
        </fieldset>
    </div>
<?php endif ?>
