<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/** @var $this Mage_Backend_Block_Widget_Button_Split */
/** @var $_helper Mage_Core_Helper_Data */
$_helper = $this->helper('Mage_Core_Helper_Data');
?>

<div id="<?php echo $this->getId(); ?>" class="actions-split <?php echo $this->getButtonClass() ?: '' ?>">
    <button class="action-default primary <?php echo $this->getClass() ?: '' ?>" <?php echo $this->getUiId(); ?>>
        <span><?php echo $this->escapeHtml($this->getLabel()); ?></span>
    </button>
    <button class="action-toggle primary" data-toggle="dropdown" <?php echo $this->getUiId('dropdown'); ?>>
        <span>Select</span>
    </button>
    <ul class="dropdown-menu" <?php echo $this->getUiId("dropdown-menu"); ?>>
        <?php foreach ($this->getOptions() as $key => $option): ?>
        <li>
            <span class="item<?php if (!empty($option['default'])):?> item-default<?php endif; ?>"
                <?php
                echo isset($option['id']) ? ' id="' . $this->getId() . '-' . $option['id'] . '"' : '',
                isset($option['onclick']) ? 'onclick="' . $option['onclick'] . '"' : '',
                $this->getUiId(isset($option['id']) ? $option['id'] : 'item' . '-' . $key);
                if (isset($option['data_attribute'])) {
                    foreach ($option['data_attribute'] as $dataKey => $data) {
                        echo ' data-', $dataKey, '="', $_helper->escapeHtml($_helper->jsonEncode($data)), '"';
                    }
                }
                ?>>
                <?php echo $this->escapeHtml($option['label']); ?>
            </span>
            <?php if (isset($option['hint'])): ?>
            <div class="tooltip" <?php echo $this->getUiId('item', $key, 'tooltip'); ?>>
                <a href="<?php echo $this->escapeHtml($option['hint']['href']) ?>" class="help">
                    <?php echo $this->escapeHtml($option['hint']['label']) ?>
                </a>
            </div>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    (function($) {
        'use strict';

        $('.actions-split')
            .on('click.splitDefault', '.action-default', function() {
                $(this).siblings('.dropdown-menu').find('.item-default').trigger('click');
            });
    })(window.jQuery);
</script>
