<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Toolbar */ ?>
<div id="vde_toolbar">
    <?php $messages = $this->getMessages(); ?>
    <?php foreach ($messages as $message): ?>
        <p class="item-msg <?php echo $message->getType() ?>"><?php echo $this->escapeHtml($message->getCode()) ?></p>
    <?php endforeach; ?>
    <?php echo $this->getChildHtml(); ?>
</div>

<script type="text/javascript">
(function ($) {
    $(document).ready(function () {
        designEditor = new DesignEditor();

        $('.vde_toolbar_cell_title').click(function(){
            var cellElement = $(this).parents('.vde_toolbar_cell');
            var active = cellElement.hasClass('active');
            $('.vde_toolbar_cell').removeClass('active');
            if (!active) {
                cellElement.addClass('active');
            }
        });
    });
})(jQuery);
</script>
