<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Toolbar */ ?>
<div id="vde_toolbar">
    <?php $messages = $this->getMessages(); ?>
    <?php foreach ($messages as $message): ?>
        <p class="item-msg <?php echo $message->getType() ?>"><?php echo $this->escapeHtml($message->getCode()) ?></p>
    <?php endforeach; ?>
    <?php echo $this->getChildHtml(); ?>
</div>

<script type="text/javascript">
(function ($) {
    $( document ).ready(function( ){
        $( window ).vde_page(<?php echo $this->getOptionsJson(); ?>);
    });
})(jQuery);
</script>
