<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Toolbar */ ?>
<div id="vde_toolbar">
    <?php $messages = $this->getMessages(); ?>
    <?php foreach ($messages as $message): ?>
        <p class="item-msg <?php echo $message->getType() ?>"><?php echo $this->escapeHtml($message->getCode()) ?></p>
    <?php endforeach; ?>
    <?php echo $this->getChildHtml(); ?>
</div>

<script type="text/javascript">
jQuery(document).ready(function () {
    designEditor = new DesignEditor();

    jQuery('.vde_toolbar_cell_title').click(function(){
        var active = jQuery(this).hasClass('active');
        jQuery('.vde_toolbar_cell_title').removeClass('active');
        jQuery('.vde_toolbar_cell_content').hide();
        if (!active) {
            jQuery(this).addClass('active');
            jQuery(this).next('.vde_toolbar_cell_content').show();
        }
    });
});
</script>
