<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Template */ ?>
<?php
$elementId = $this->getElementId();
$elementHtml = $this->getElementHtml();
$cssClass = 'vde_element_wrapper'
    . ($this->getIsManipulationAllowed() ? ' vde_draggable vde_removable' : '')
    . ($this->getIsContainer() ? ' vde_container' : '');
?>
<div id="<?php echo $elementId; ?>" class="<?php echo $cssClass; ?>" data-name="<?php echo $this->getElementName() ?>">
    <?php if ($this->getIsManipulationAllowed()): ?>
        <?php echo $this->getRemoveButton($elementId) ?>
    <?php endif; ?>
    <div class="vde_element_title"><?php echo $this->getElementTitle() ?></div>
    <!--start_<?php echo $elementId; ?>-->
    <?php if ($elementHtml) : ?>
        <div><?php echo $elementHtml ?></div>
    <?php elseif (!$this->getIsContainer()) : ?>
        <div class="vde_placeholder_content">
            <img src="<?php echo $this->getViewFileUrl('Mage_DesignEditor::images/block-placeholder.png') ?>"
                 alt="<?php echo $this->__('Placeholder')?>" />
        </div>
    <?php endif ?>
    <!--end_<?php echo $elementId; ?>-->
</div>
