<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Wrapping */ ?>
<br class="vde_marker" block_name="<?php echo $this->escapeHtml($this->getWrappedBlock()->getNameInLayout()) ?>"
    marker_type="start"/>
<?php echo $this->getWrappedHtml(); ?>
<br class="vde_marker" marker_type="end"/>
