<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Core_Block_Template */ ?>
<?php
$elementId = $this->getElementId();
$elementHtml = $this->getElementHtml();
$hideWrapping = !Mage::getSingleton('Mage_DesignEditor_Model_Session')->isHighlightingEnabled();
$cssClass = 'vde_element_wrapper'
    . ($this->getIsDraggable() ? ' vde_draggable' : '')
    . ($this->getIsContainer() ? ' vde_container' : '')
    . ($hideWrapping ? ' vde_wrapper_hidden' : '');
?>
<div id="<?php echo $elementId; ?>" class="<?php echo $cssClass; ?>">
    <div class="vde_element_title"><?php echo $this->getElementTitle() ?></div>
    <?php if (!$hideWrapping) : ?>
        <?php echo $elementHtml; ?>
    <?php endif; ?>
</div>
<?php if ($hideWrapping && $elementHtml) : ?>
    <!--start_<?php echo $elementId; ?>-->
    <?php echo $elementHtml; ?>
    <!--end_<?php echo $elementId; ?>-->
<?php endif; ?>
