<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Renderer template for gift registry edit form
 *
 * @see Enterprise_GiftWrapping_Block_Adminhtml_Giftwrapping_Form_Renderer_Element
 */
?>

<?php $_element = $this->getElement() ?>
<?php $this->checkFieldDisable() ?>

<div class="field">
    <?php if ($_element->getType()=='hidden'): ?>
        <?php echo trim($_element->getElementHtml()) ?>
    <?php else: ?>
        <?php echo $this->getElementLabelHtml() ?>

        <div class="control">
            <?php echo $this->getElementHtml() ?>
        </div>

        <?php if ($this->getScopeLabel()): ?>
            <div class="field-service" value-scope="<?php echo $this->getScopeLabel()?>"></div>
        <?php endif;?>

        <?php if ($this->canDisplayUseDefault()): ?>
        <div class="value use-default">
            <input type="checkbox" name="wrapping[is_default][<?php echo $_element->getHtmlId() ?>]" id="<?php echo $_element->getHtmlId() ?>_default"<?php if ($this->usedDefault()): ?> checked="checked"<?php endif; ?> onclick="toggleValueElements(this, this.parentNode.parentNode)" value="1" />
            <label for="<?php echo $_element->getHtmlId() ?>_default" class="normal"><?php echo $this->__('Use Default Value') ?></label>
        </div>
        <?php endif; ?>
    <?php endif; ?>
</div>