<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="box-collateral box-tags">
    <div class="box-title">
        <h2><?php echo $this->__('Product Tags'); ?></h2>
    </div>
    <?php echo $this->getChildHtml('list_before')?>
    <div class="box-content">
        <?php if($this->getCount()): ?>
        <h3><?php echo $this->__('Other people marked this product with these tags:') ?></h3>
        <ul id="<?php echo $this->getUniqueHtmlId('tags-list_'); ?>" class="tags-list">
            <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
        </ul>
        <script type="text/javascript">
            decorateGeneric($("<?php echo $this->getUniqueHtmlId('tags-list_'); ?>").select('li'), ['first', 'last']);
        </script>
        <?php endif; ?>
        <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
            <div class="form-add-tags">
                <label for="productTagName"><?php echo $this->__('Add Your Tags:') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry" name="productTagName" id="productTagName" />
                </div>
                <button type="button" class="button" onclick="submitTagForm()">
                    <span>
                        <span><?php echo $this->__('Add Tags') ?></span>
                    </span>
                </button>
                <p><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var addTagFormJs = new VarienForm('addTagForm');
            function submitTagForm(){
                if(addTagFormJs.validator.validate()) {
                    addTagFormJs.form.submit();
                }
            }
        //]]>
        </script>
    </div>
</div>
