<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this \Magento\Adminhtml\Block\Catalog\Product\Composite\Fieldset\Qty */ ?>

<div class="giftcard-qty-form">
    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label><?php echo __('Quantity'); ?></label>
                <div class="input-box">
                    <input id="product_composite_configure_input_qty" class="input-text" type="text" name="qty" value="<?php echo $this->getQtyValue() * 1 ?>">
                </div>
            </div>
        </li>
    </ul>
</div>
