<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Customer onepage checkout login form template
 *
 */
/** @var $this \Magento\Checkout\Block\Onepage\Login */
?>
<div class="step login wrapper">
<?php echo $this->getChildHtml('login_before')?>
<div class="block customer login">
    <div class="title"><strong><?php echo __('Login') ?></strong></div>
    <div class="content">
        <form class="form login" id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <fieldset class="fieldset login" data-hasrequired="<?php echo __('* Required Fields') ?>">
                <p class="field note"><?php echo __('Already registered?') ?> <?php echo __('Please log in below:') ?></p>
                <div class="field email required">
                    <label class="label" for="login-email"><span><?php echo __('Email Address') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="login-email" name="login[username]" data-validate="{required:true, 'validate-email':true}" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                    </div>
                </div>
                <div class="field password required">
                    <label for="login-password" class="label"><span><?php echo __('Password') ?></span></label>
                    <div class="control">
                        <input type="password" class="input-text" id="login-password" name="login[password]" data-validate="{required:true, 'validate-password':true}"/>
                    </div>
                </div>
                <?php echo $this->getChildHtml('form_additional_info'); ?>
                <div class="actions">
                    <input name="context" type="hidden" value="checkout" />
                    <div class="primary">
                        <button type="submit" class="action login"><span><?php echo __('Login') ?></span></button>
                    </div>
                    <div class="secondary">
                        <a class="action remind" href="<?php echo $this->helper('Magento\Customer\Helper\Data')->getForgotPasswordUrl()?>">
                            <span><?php echo __('Forgot Your Password?') ?></span>
                        </a>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <script type="text/javascript">
        (function($) {
            head.js(
                "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
                function() {
                    $('#login-form').validation();
                });
        })(jQuery);
    </script>
</div>
<?php if ( $this->isAllowedGuestCheckout() || $this->helper('Magento\Customer\Helper\Data')->isRegistrationAllowed() ): ?>
<div class="block guest">
    <div class="title">
        <strong>
        <?php if( $this->isAllowedGuestCheckout() && $this->helper('Magento\Customer\Helper\Data')->isRegistrationAllowed() ): ?>
            <?php echo __('Checkout as a Guest or Register') ?>
        <?php elseif ( $this->isAllowedGuestCheckout() && !$this->helper('Magento\Customer\Helper\Data')->isRegistrationAllowed() ): ?>
            <?php echo __('Checkout as a Guest') ?>
        <?php else: ?>
            <?php echo __('Register to Create an Account') ?>
        <?php endif; ?>
        </strong>
    </div>
    <div class="content">
        <?php if( !$this->isAllowedGuestCheckout() && $this->helper('Magento\Customer\Helper\Data')->isRegistrationAllowed() ): ?>
            <p><strong><?php echo __('Register and save time!') ?></strong><br />
            <?php echo __('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo __('Fast and easy check out') ?></li>
                <li><?php echo __('Easy access to your order history and status') ?></li>
            </ul>
        <?php elseif( $this->isAllowedGuestCheckout() && $this->helper('Magento\Customer\Helper\Data')->isRegistrationAllowed() ): ?>
            <p class="note"><?php echo __('Register with us for future convenience:') ?></p>
        <?php endif ?>

        <?php if( $this->isAllowedGuestCheckout() ): ?>
            <fieldset class="fieldset guest">
                <?php if( $this->isAllowedGuestCheckout() ): ?>
                <div class="field choice">
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Magento\Checkout\Model\Type\Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
                    <label class="label" for="login:guest"><span><?php echo __('Checkout as Guest') ?></span></label>
                </div>
                <?php endif; ?>
                <?php if( $this->helper('Magento\Customer\Helper\Data')->isRegistrationAllowed() ): ?>
                <div class="field choice">
                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Magento\Checkout\Model\Type\Onepage::METHOD_REGISTER || !$this->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                    <label class="label" for="login:register"><span><?php echo __('Register') ?></span></label>
                </div>
                <?php endif; ?>
            </fieldset>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
        <div class="actions">
            <span class="please-wait load indicator" style="display:none;">
                <span><?php echo __('Loading next step...') ?></span>
            </span>
            <?php if ($this->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="action continue" data-checkout='{"isGuestCheckoutAllowed":true}'><span><?php echo __('Continue') ?></span></button>
            <?php elseif ($this->helper('Magento\Checkout\Helper\Data')->isCustomerMustBeLogged()): ?>
                <button id="onepage-guest-register-button" type="button" class="action register" data-checkout='{"isGuestCheckoutAllowed":false, "registrationUrl":"<?php echo $this->helper('Magento\Checkout\Helper\Url')->getRegistrationUrl();?>"}'><span><?php echo __('Register') ?></span></button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="action register"><span><?php echo __('Register') ?></span></button>
                </form>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endif; ?>
</div>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#login-form').validation();
            }
        )}
    )(jQuery);
</script>
