<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $this->getOrder() ?>
<div class="order details view">
    <strong class="order status"><?php echo $_order->getStatusLabel() ?></strong>
    <div class="order toolbar">
        <?php echo $this->getChildHtml('buttons') ?>
        <?php echo $this->getStatusHistoryRssUrl($_order) ?>
    </div>
    <dl class="order info">
        <dt><?php echo __('About This Order:') ?></dt>
        <dd>
            <?php echo $this->getChildHtml('links') ?>
        </dd>
    </dl>
    <p class="order date"><?php echo __('<span class="label">Order Date:</span> %1', '<date>' . $this->formatDate($_order->getCreatedAtStoreDate(), 'long') . '</date>' ) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
    <div class="block order shipping address">
        <div class="title"><strong><?php echo __('Shipping Address') ?></strong></div>
        <div class="content">
            <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>
    </div>

    <div class="block order shipping method">
        <div class="title"><strong><?php echo __('Shipping Method') ?></strong></div>
        <div class="content">
        <?php if ($_order->getShippingDescription()): ?>
            <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
        <?php else: ?>
            <?php echo __('No shipping information available'); ?>
        <?php endif; ?>
        </div>
    </div>

<?php endif; ?>
    <div class="block order billing address">
        <div class="title">
            <strong><?php echo __('Billing Address') ?></strong>
        </div>
        <div class="content">
            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
    </div>
    <div class="block order billing method">
        <div class="title">
            <strong><?php echo __('Payment Method') ?></strong>
        </div>
        <div class="content">
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
    </div>
</div>