<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_order = $this->getOrder() ?>
<?php $_giftMessage; ?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?php echo __('Items Ordered') ?>">
        <caption class="table caption"><?php echo __('Items Ordered') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?php echo __('Product Name') ?></th>
                <th class="col sku"><?php echo __('SKU') ?></th>
                <th class="col price"><?php echo __('Price') ?></th>
                <th class="col qty"><?php echo __('Qty') ?></th>
                <th class="col subtotal"><?php echo __('Subtotal') ?></th>
            </tr>
        </thead>
        <tfoot>
            <?php echo $this->getChildHtml('order_totals') ?>
        </tfoot>
            <?php $_items = $_order->getItemsCollection(); ?>
            <?php $_index = 0; ?>
            <?php $_count = $_items->count(); ?>
            <?php $_giftMessage = ''?>
            <?php foreach ($_items as $_item): ?>
            <?php if ($_item->getParentItem()) continue; ?>
            <tbody>
                <?php echo $this->getItemHtml($_item) ?>
                <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
                    <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_item); ?>
                <?php endif ?>
            </tbody>
            <?php endforeach; ?>
    </table>
</div>
<?php if ($_giftMessage): ?>
    <script type="text/javascript">
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('a.action.show').add('a.action.close').mage('giftMessage', {});

});
</script>
<?php endif; ?>
