<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this Magento_Backend_Block_Widget_Form_Container */
 ?>
<?php echo $this->getFormInitScripts() ?>
<div class="page-actions" <?php echo $this->getUiId('content-header') ?>><?php echo $this->getButtonsHtml('header') ?></div>
<?php echo $this->getFormHtml() ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
<script type="text/javascript">
    jQuery('#edit_form').mage('form')
        .mage('validation', {
            validationUrl: '<?php echo $this->getValidationUrl() ?>',
            highlight: function(element) {
                var detailsElement = jQuery(element).closest('details');
                if (detailsElement.length && detailsElement.is('.details')) {
                    var summaryElement = detailsElement.find('summary');
                    if (summaryElement.length && summaryElement.attr('aria-expanded') === "false") {
                        summaryElement.trigger('click');
                    }
                }
            }
        });
</script>
<?php echo $this->getFormScripts() ?>
