<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_fixed
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="block addresses default">
    <div class="title"><strong><?php echo __('Default Addresses') ?></strong></div>
    <div class="content">
        <?php if($_pAddsses = Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getDefaultBilling()): ?>
            <div class="box address billing">
                <strong class="subtitle">
                    <span><?php echo __('Default Billing Address') ?></span>
                    <a class="action edit" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>">
                        <span><?php echo __('Change Billing Address') ?></span>
                    </a>
                </strong>
                <address>
                <?php echo $this->getAddressHtml(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
           </div>
        <?php else: ?>
            <div class="box address no billing">
                <strong class="box-title"><span><?php echo __('Default Billing Address') ?></span></strong>
                <p><?php echo __('You have no default billing address in your address book.') ?></p>
            </div>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getDefaultShipping()): ?>
            <div class="box address shipping">
                <strong class="subtitle">
                    <span><?php echo __('Default Shipping Address') ?></span>
                    <a class="action edit" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>">
                        <span><?php echo __('Change Shipping Address') ?></span>
                    </a>
                </strong>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
            </div>
        <?php else: ?>
            <div class="box address shipping">
                <strong class="subtitle"><span><?php echo __('Default Shipping Address') ?></span></strong>
                <p><?php echo __('You have no default shipping address in your address book.') ?></p>
            </div>
        <?php endif ?>
    </div>
</div>

<div class="block addresses list">
    <div class="title"><strong><?php echo __('Additional Address Entries') ?></strong></div>
    <div class="content">
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
        <ol class="items addresses">
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <address>
                    <?php echo $this->getAddressHtml($_address) ?><br />
                </address>
                <div class="item actions">
                    <a class="action edit" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><span><?php echo __('Edit Address') ?></span></a>
                    <a class="action delete" href="#" role="delete-address" data-address="<?php echo $_address->getId() ?>"><span><?php echo __('Delete Address') ?></span></a>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
        <?php else: ?>
        <p><?php echo __('You have no additional address entries in your address book.') ?></p>
        <?php endif ?>
    </div>
</div>

<div class="actions">
    <div class="secondary"><a class="action back" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><span><?php echo __('Back') ?></span></a></div>
</div>
<script type="text/javascript">
    head.js("<?php echo $this->getViewFileUrl('Mage_Customer::address.js'); ?>", function() {
        jQuery('hgroup.page.title').address({
            deleteAddress: "li.item a[role='delete-address']",
            deleteUrlPrefix: '<?php echo $this->getDeleteUrl() ?>id/',
            addAddress: "button[role='add-address']",
            addAddressLocation: '<?php echo $this->getAddAddressUrl() ?>'
        });
    });
</script>

<?php /*
<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <h2 class="sub-title"></h2>
        <ol>
        <?php if($_pAddsses = Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getDefaultBilling()): ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo __('Default Billing Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo __('Change Billing Address') ?></a></h3>
                <address class="box-content">
                <?php echo $this->getAddressHtml(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
           </li>
        <?php else: ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo __('Default Billing Address') ?></h3>
                <p class="box-content"><?php echo __('You have no default billing address in your address book.') ?></p>
            </li>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getDefaultShipping()): ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo __('Default Shipping Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo __('Change Shipping Address') ?></a></h3>
                <address class="box-content">
                    <?php echo $this->getAddressHtml(Mage::getSingleton('Mage_Customer_Model_Session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
            </li>
        <?php else: ?>
            <li class="info-box">
                <h3 class="box-title"><?php echo __('Default Shipping Address') ?></h3>
                <p class="box-content"><?php echo __('You have no default shipping address in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
    <div class="col-2 addresses-additional">
        <h2 class="sub-title"><?php echo __('Additional Address Entries') ?></h2>
        <ol>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <li class="item">
                <address>
                    <?php echo $this->getAddressHtml($_address) ?><br />
                </address>
                <p class="actions">
                    <a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo __('Edit Address') ?></a>
                    <span class="separator">|</span>
                    <a href="#" role="delete-address" data-address="<?php echo $_address->getId() ?>"><?php echo __('Delete Address') ?></a>
                </p>
            </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class="item empty">
                <p><?php echo __('You have no additional address entries in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
</div>

*/ ?>