<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table cellspacing="6" width="100%" class="data-table">
    <thead>
        <tr>
            <th style="width:50%;"><?=__('Items Order')?></th>
            <th class="align-center" style="width:10%;"><?=__('Qty')?></th>
            <th class="align-center" style="width:20%;"><?=__('Price')?></th>
            <th class="align-right" style="width:20%;"><?=__('Ext. Price')?></th>
        </tr>
    </thead>
    <tbody>
        <?foreach($order->getAllItems() as $_item):?>     
        <tr>
            <td><?=$_item->getName()?></td>
            <td class="align-center"><?=$_item->getQty()?></td>
            <td class="align-center"><?=$_item->getPrice()?></td>
            <td class="align-right"><?=$_item->getRowTotal()?></td>
        </tr>   
        <?endforeach?> 
    </tbody>
</table>