<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    /* @var $this Enterprise_Wishlist_Block_Behaviour */
?>
<script type="text/javascript">
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('Enterprise_Persistent::splitbutton.js') ?>", function() {
            $('#wishlist-view-form').splitButton();
        });
    })(jQuery);
</script>