<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3 class="icon-head head-online-visitors"><?=__('Wishlist Report')?></h3></td>
        </tr>
    </table>
</div>
<?=$this->getChildHtml('grid')?>

<div class="switcher" style="float: left; margin: 10px 10px 10px 0px; padding:15px;">
Customers that have wishlist: <?=$this->customer_with_wishlist?>%
</div>

<div class="switcher" style="float: right; margin: 10px 0px 10px 10px; padding:15px;">
    Number of wishlists: <?=$this->wishlists_count?><br />
    Number of items bought from a wishlist: <?=$this->items_bought?><br />
    Number of times wishlists have been shared (emailed): <?=$this->shared_count?><br />
    Number of wishlist referrals: <?=$this->referrals_count?><br />
    Number of wishlist conversions: <?=$this->conversions_count?><br />
</div>