<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php echo $this->getChildHtml('grid') ?>

<div class="switcher f-left" style="margin: 10px 10px 10px 0px; padding:15px;">
<?php 
    echo __('Customers that have wish list: %s%', $this->getCustomerWithWishlist()) 
?>
</div>

<div class="switcher" style="float: right; margin: 10px 0px 10px 10px; padding:15px;">
    <?php 
        echo __('Number of wish lists: %s', $this->getWishlistsCount()) 
    ?><br />
    <?php 
        echo __('Number of items bought from a wish list: %s', $this->getItemsBought()) 
    ?><br />
    <?php echo __('Number of times wish lists have been shared (emailed): %s', $this->getSharedCount()) 
    ?><br />
    <?php echo __('Number of wish list referrals: %s', $this->getReferralsCount()) 
    ?><br />
    <?php echo __('Number of wish list conversions: %s', $this->getConversionsCount()) 
    ?><br />
</div>
