<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\CustomerBalance\Block\Adminhtml\Customer\Edit\Tab\Customerbalance\Balance
 */
?>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Store Credit Balance')?></span>
    </div>
    <?php echo $this->getChildHtml('grid')?>
    <?php echo $this->getDeleteOrphanBalancesButton() ?>
</div>
