<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * @see \Magento\CustomerBalance\Block\Adminhtml\Customer\Edit\Tab\Customerbalance\Balance
 */
?>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Store Credit Balance')?></span>
    </div>
    <?php echo $this->getChildHtml('grid')?>
    <?php echo $this->getDeleteOrphanBalancesButton() ?>
</div>
