<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this \Magento\Paypal\Block\Payflow\Advanced\Form
 */
?>
<div id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="payflowadvanced items">
    <?php echo __('You will be required to enter your payment details after you place an order.') ?>
</div>
