<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->canRefundToCustomerBalance()): ?>
    <div>
        <label for="creditmemo_customerbalance_return_enable"><?php echo Mage::helper('Enterprise_CustomerBalance_Helper_Data')->__('Refund to Store Credit') ?></label>
        <input type="hidden" name="creditmemo[refund_customerbalance_return_enable]" value="0">
        <input type="checkbox" name="creditmemo[refund_customerbalance_return_enable]" value="1" id="creditmemo_customerbalance_return_enable"<?php if (Mage::helper('Enterprise_CustomerBalance_Helper_Data')->isAutoRefundEnabled()): ?> checked="checked"<?php endif ?>>
        <input type="text" name="creditmemo[refund_customerbalance_return]" value="<?php echo $this->getReturnValue(); ?>" id="creditmemo_customerbalance_return" class="input-text not-negative-amount" style="width: 60px; text-align: right;">
        <script type="text/javascript">
        //<![CDATA[
            function toggleCustomerBalanceRefundAmount() {
                if ($('creditmemo_customerbalance_return_enable').checked) {
                    $('creditmemo_customerbalance_return').disabled = false;
                    disableElements('refund');
                } else {
                    $('creditmemo_customerbalance_return').disabled = true;
                    enableElements('refund');
                }
            }

            Event.observe($('creditmemo_customerbalance_return_enable'), 'change', toggleCustomerBalanceRefundAmount);
            toggleCustomerBalanceRefundAmount();
        //]]>
        </script>
    </div>
<?php endif; ?>
