<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="switcher-nav">
    <?php if($this->getTitle()): ?>
        <div class="content-header">
            <h3><?php echo $this->getTitle() ?></h3>
        </div>
    <?php endif ?>
    <div class="switcher">
        <label for="store_switcher"><?php echo $this->__('Current Configuration Scope:') ?></label>
        <select id="store_switcher" class="system-config-store-switcher" onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
        <?php foreach ($this->getStoreSelectOptions() as $_value=>$_option): ?>
          <option value="<?php echo $_value ?>" url="<?php echo $_option['url'] ?>" <?php echo $_option['selected']?'selected':'' ?> style="<?php echo $_option['style'] ?>">
              <?php echo $_option['label'] ?>
          </option>
        <?php endforeach ?>
        </select>
        <div style="margin-top:10px;">
            <?php echo $this->getStoreButtonsHtml() ?>
        </div>
    </div>


    <?php if(!empty($tabs)): ?>
    <ul id="<?php echo $this->getId() ?>" class="tabs">
    
    <?php $count=0; ?>
    <?php foreach ($tabs as $_tab): ?>
        <li <?php if(!$count): ?>class="first"<?php endif ?>>
            <a href="<?php echo $_tab->getUrl() ?>" id="<?php echo $this->getTabId($_tab) ?>" title="<?php echo $_tab->getTitle() ?>" class="tab-item-link <?php echo $_tab->getClass() ?>">
                <span><div class="changed" title="<?php echo $this->__('The information in this tab has been changed.') ?>"></div><div class="error" title="<?php echo $this->__('This tab contains invalid data. Please solve the problem before saving.') ?>"></div><?php echo $_tab->getLabel() ?></span>
            </a>
            <div id="<?php echo $this->getId() ?>_<?php echo $_tab->getId() ?>_content" style="display:none"><?php echo $_tab->getContent() ?></div>
        </li>
    <?php $count++; ?>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript" language="javascript">
        <?php echo $this->getId() ?>JsTabs = new varienTabs('<?php echo $this->getId() ?>', '<?php echo $this->getDestElementId() ?>', '<?php echo $this->getActiveTabId() ?>');
    </script>
    <?php endif; ?>
</div>
