<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->helper('Mage_GiftMessage_Helper_Message')->getIsMessagesAvailable('main', $this->getQuote(), $this->getStoreId())): ?>
<?php $_items = $this->getItems(); ?>
<div id="order-giftmessage">
    <div class="giftmessage-order-create box-left">
        <fieldset>
            <legend><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Gift Message for the Entire Order') ?></legend>
            <br />
            <?php if($this->helper('Mage_GiftMessage_Helper_Message')->getIsMessagesAvailable('main', $this->getQuote(), $this->getStoreId())): ?>
                <div class="giftmessage-entire-order">
                    <p><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('You can leave a box blank if you don\'t wish to add a gift message for whole order') ?></p>
                    <?php echo $this->getFormHtml($this->getQuote(), 'main') ?>
                </div>
            <?php endif; ?>
        </fieldset>
    </div>
    <script type="text/javascript">
        order.giftmessage-FieldsBind('order-giftmessage');
    </script>
</div>
<?php endif; ?>
