<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var $this Mage_Page_Block_Link
 */
?>
<li>
    <a href="<?php echo $this->escapeHtml($this->getHref())?>"
        <?php if ($title = $this->getTitle()):?> title="<?php echo $this->escapeHtml($this->__($title))?>"<?php endif;?>
    >
        <?php echo $this->escapeHtml($this->__($this->getLabel()))?>
    </a>
</li>
