<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>

<?php
/**
 * @var $this \Magento\VersionsCms\Block\Adminhtml\Cms\Page\Revision\Edit\Info
 */
?>
<div class="cms-revision-info">
    <div class="fieldset-wrapper">
        <?php if ($this->getRevisionNumber()): ?>
        <div class="fieldset-wrapper-title">
            <span class="title">
                <?php echo __('Revision #') ?> <?php echo $this->getRevisionNumber() ?>
            <?php else: ?>
                <?php echo __('New Revision') ?>
            </span>
        </div>
        <?php endif; ?>
        <table class="data-table">
            <tr>
                <th><?php echo __('Author:') ?></th>
                <td><?php echo $this->getAuthor() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Created:') ?></th>
                <td><?php echo $this->getCreatedAt() ?></td>
            </tr>
            <tr>
                <th><?php echo __('Version:') ?></th>
                <td><?php echo $this->escapeHtml($this->getVersionLabel()) ?></td>
            </tr>
        </table>
    </div>
</div>
