<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Catalog Event product page
 *
 * @var $this \Magento\CatalogEvent\Block\Catalog\Product\Event
 */
?>
<?php $_event = $this->getEvent(); ?>
<?php if ($this->canDisplay()): ?>
<div class="block category event <?php echo $_event->getStatus()?>">
    <div class="content">
        <strong class="subtitle">
            <span><?php echo $this->getStatusText($_event); ?></span>
        </strong>
        <?php switch ($_event->getStatus()):
            case 'upcoming': ?>
            <div class="dates">
                <div class="start">
                    <span class="date"><?php echo $this->getEventDate('start', $_event); ?></span>
                    <span class="time"><?php echo $this->getEventTime('start', $_event, 'hh a zzz'); ?></span>
                </div>
                <div class="end">
                    <span class="date"><?php echo $this->getEventDate('end', $_event); ?></span>
                    <span class="time"><?php echo $this->getEventTime('end', $_event, 'hh a zzz'); ?></span>
                </div>
            </div>
        <?php break;
            case 'open': ?>
            <ul class="ticker" id="event-ticker-<?php echo $_event->getId() ?>"
                data-mage-init='{"ticker":{"secondsToClose": <?php echo $this->getSecondsToClose($_event); ?>}}'>
                <li class="days">
                    <span data-container="days" class="value">&nbsp;</span>
                    <span class="label"><?php echo __('Days') ?></span>
                </li>
                <li class="hour">
                    <span data-container="hour" class="value">&nbsp;</span>
                    <span class="label"><?php echo __('Hrs') ?></span>
                </li>
                <li class="minute">
                    <span data-container="minute" class="value">&nbsp;</span>
                    <span class="label"><?php echo __('Mins') ?></span>
                </li>
                <li class="second">
                    <span data-container="second" class="value">&nbsp;</span>
                    <span class="label"><?php echo __('Sec') ?></span>
                </li>
            </ul>
        <?php break;
            case 'closed': ?>
            <div class="dates">
            <div class="start">
                <span class="date"><?php echo $this->getEventDate('start', $_event); ?></span>
                <span class="time"><?php echo $this->getEventTime('start', $_event, 'hh a zzz'); ?></span>
            </div>
            <div class="end">
                <span class="date"><?php echo $this->getEventDate('end', $_event); ?></span>
                <span class="time"><?php echo $this->getEventTime('end', $_event, 'hh a zzz'); ?></span>
            </div>
            </div>
        <?php break; ?>
    <?php endswitch; ?>
    </div>
</div>
<?php endif; ?>
