<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\GiftWrapping\Block\Product\Info */
?>
<?php if ($this->getGiftWrappingInfo()) : ?>
    <dl class="gift-wrapping">
        <dt class="title"><?php echo __('Gift Wrapping'); ?></dt>
        <dd class="content">
            <?php if ($this->getGiftWrappingInfo()->getImageUrl()): ?>
            <img src="<?php echo $this->getGiftWrappingInfo()->getImageUrl() ?>"
                 alt="<?php echo $this->escapeHtml($this->getGiftWrappingInfo()->getDesign()); ?>"
                title="<?php echo $this->escapeHtml($this->getGiftWrappingInfo()->getDesign()); ?>" />
            <?php endif ?>
            <?php echo $this->escapeHtml($this->getGiftWrappingInfo()->getDesign()); ?>
        </dd>
    </dl>
<?php endif; ?>
