<?
/**
 * Currency switcher
 * 
 * @see Mage_Directory_Block_Currency
 */
?>
<?if($this->getCurrencyCount()):?>
<div class="box currency-switcher">
    <div class="head">
        <span class="corner"></span>
        <h3>Select Currency</h3>
    </div>
    <div class="box-container">
        <select name="currency" onchange="changeCurrency(this)">
        <?foreach ($this->getCurrencies() as $_currency):?>
            <option value="<?=$_currency->getCurrencyCode()?>"<?if($_currency->getCurrencyCode()==$this->getCurrentCurrencyCode()):?>selected="selected"<?endif;?>>
                <?=$_currency->getCurrencyName()?> - <?=$_currency->getCurrencyCode()?>
            </option>
        <?endforeach;?>
        </select>
    </div>
</div>
<script type="text/javascript">
function changeCurrency(sObject){
    if(sObject.value){
        setLocation('<?=$this->getSwitchUrl()?>currency/'+sObject.value+'/');
    }
}
</script>
<?endif;?>