<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_option = $this->getOption(); ?>
<?php $_fileInfo = $this->getFileInfo(); ?>
<?php $_fileExists = $_fileInfo->hasData(); ?>
<?php $_fileName = 'options_' . $_option->getId() . '_file'; ?>
<?php $_fieldNameAction = $_fileName . '_action'; ?>
<?php $_fieldValueAction = $_fileExists ? 'save_old' : 'save_new'; ?>
<?php $_fileNamed = $_fileName . '_name'; ?>

<script type="text/javascript">
//<![CDATA[
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/file-option.js')?>", function() {
            $('#input-box-<?php echo $_fileName ?>').fileOption({
                fileName: '<?php echo $_fileName ?>',
                fileNamed: '<?php echo $_fileNamed ?>',
                fieldNameAction: '<?php echo $_fieldNameAction ?>',
                changeFileSelector: '#change-<?php echo $_fileName ?>',
                deleteFileSelector: '#delete-<?php echo $_fileName ?>'
            });
        });
    })(jQuery);
//]]>
</script>

<dt><label <?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?php echo  $this->escapeHtml($_option->getTitle()) ?></label>
    <?php echo $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->getDecoratedIsLast()):?> class="last"<?php endif; ?>>
    <?php if ($_fileExists): ?>
        <span class="<?php echo $_fileNamed ?>"><?php echo $_fileInfo->getTitle(); ?></span>
        <a href="javascript:void(0)" class="label" id="change-<?php echo $_fileName ?>" >
            <?php echo __('Change') ?>
        </a>&nbsp;
        <?php if (! $_option->getIsRequire()): ?>
           <input type="checkbox" id="delete-<?php echo $_fileName ?>" />
           <span class="label"><?php echo __('Delete') ?></span>
        <?php endif; ?>
    <?php endif; ?>
    <div id="input-box-<?php echo $_fileName ?>" <?php echo $_fileExists ? 'style="display:none"' : '' ?>>
        <input type="file" name="<?php echo $_fileName; ?>" class="product-custom-option<?php echo $_option->getIsRequire() ? ' required' : '' ?>" <?php echo $_fileExists ? 'disabled="disabled"' : '' ?> />
        <input type="hidden" name="<?php echo $_fieldNameAction; ?>" value="<?php echo $_fieldValueAction; ?>" />
        <?php if ($_option->getFileExtension()): ?>
        <p class="no-margin"><?php echo __('Allowed file extensions to upload')?>: <strong><?php echo $_option->getFileExtension() ?></strong></p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeX() > 0): ?>
        <p class="no-margin"><?php echo __('Maximum image width')?>: <strong><?php echo $_option->getImageSizeX() ?> <?php echo __('px.')?></strong></p>
        <?php endif; ?>
        <?php if ($_option->getImageSizeY() > 0): ?>
        <p class="no-margin"><?php echo __('Maximum image height')?>: <strong><?php echo $_option->getImageSizeY() ?> <?php echo __('px.')?></strong></p>
        <?php endif; ?>
    </div>
</dd>
