<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="grid">
    <table cellspacing="0" id="invoice_items_grid_table">
        <col width="80"/>
        <col/>
        <col width="100"/>
        <col width="60"/>
        <col width="60"/>
        <col width="60"/>
        <col width="60"/>
        <col width="60"/>
        <col width="80"/>
        <thead>
            <tr class="headings">
                <th rowspan="2"><span class="nobr"><?=Mage::helper('sales')->__('SKU')?></span></th>
                <th rowspan="2"><span class="nobr"><?=Mage::helper('sales')->__('Product Name')?></span></th>
                <th rowspan="2"><span class="nobr"><?=Mage::helper('sales')->__('Item Status')?></span></th>
                <th colspan="6" class="a-center last"><?=Mage::helper('sales')->__('Qty')?></th>
            </tr>
            <tr>
                <th><span class="nobr"><?=Mage::helper('sales')->__('Ordered')?></span></th>
                <th><span class="nobr"><?=Mage::helper('sales')->__('Canceled')?></span></th>
                <th><span class="nobr"><?=Mage::helper('sales')->__('Returned')?></span></th>
                <th><span class="nobr"><?=Mage::helper('sales')->__('Shipped')?></span></th>
                <th><span class="nobr"><?=Mage::helper('sales')->__('Invoiced')?></span></th>
                <th class="last"><span class="nobr"><?=Mage::helper('sales')->__('Invoice')?></span></th>
            </tr>
        </thead>
        <tbody>
            <?$_items = $this->getOrder()->getItemsCollection()?>
            <?$_i=0;foreach ($_items as $_item):$_i++?>
                <tr class="<?=$_i%2?'odd':'even'?>">
                    <td><?=$_item->getSku()?></td>
                    <td><?=$_item->getName()?></td>
                    <td><?=$_item->getStatus()?></td>
                    <td><?=$_item->getQtyOrdered()*1?></td>
                    <td><?=$_item->getQtyCanceled()*1?></td>
                    <td><?=$_item->getQtyRefunded()*1?></td>
                    <td><?=$_item->getQtyShipped()*1?></td>
                    <td><?=$_item->getQtyInvoiced()*1?></td>
                    <td class="last">
                        <?if($_item->canInvoice()):?>
                        <input type="text" class="input-text" name="invoice[items][<?=$_item->getId()?>]" value="<?=$this->getInvoiceQty($_item)?>"/>
                        <?else:?>
                        -
                        <?endif;?>
                    </td>
                </tr>
            <?endforeach;?>
        </tbody>
    </table>
</div>