<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('Mage_Customer_Block_Widget_Dob')
   ->setDate($this->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $this->getLayout()->createBlock('Mage_Customer_Block_Widget_Dob')
   ->setDate($this->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/

/**
 * @see Mage_Customer_Block_Widget_Dob
 */
?>
<div class="field dob<?php if ($this->isRequired()) echo ' required' ?>">
    <label class="label" for="<?php echo $this->getFieldId('month')?>"><span><?php echo $this->__('Date of Birth') ?></span></label>
    <div class="control customer-dob">
        <div class="fields group group-3">
        <?php
            $this->setDateInput('d',
                '<div class="field dob-day day">
                     <label class="label" for="' . $this->getFieldId('day') . '"><span>' . $this->__('Day (DD)') . '</span></label>
                     <div class="control"><input type="text" id="' . $this->getFieldId('day') . '" name="' . $this->getFieldName('day') . '" value="' . $this->getDay() . '" title="' . $this->__('Day') . '" class="input-text validate-custom" ' . $this->getFieldParams() . ' /></div>
                 </div>'
            );

            $this->setDateInput('m',
                '<div class="field dob-month month">
                     <label class="label" for="' . $this->getFieldId('month') . '"><span>' . $this->__('Month (MM)')  . '</span></label>
                     <div class="control"><input type="text" id="' . $this->getFieldId('month') . '" name="' . $this->getFieldName('month') . '" value="' . $this->getMonth()  . '" title="' . $this->__('Month')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' /></div>
                 </div>'
            );

            $this->setDateInput('y',
                '<div class="field dob-year year">
                     <label class="label" for="' . $this->getFieldId('year') . '"><span>' . $this->__('Year (YYYY)')  . '</span></label>
                     <div class="control"><input type="text" id="' . $this->getFieldId('year') . '" name="' . $this->getFieldName('year') . '" value="' . $this->getYear()  . '" title="' . $this->__('Year')  . '" class="input-text validate-custom" ' . $this->getFieldParams()  . ' /></div>
                 </div>'
            );
        ?>
        <?php echo $this->getSortedDateInputs() ?>
        </div>
        <span class="dob-full" style="display:none;">
            <input type="hidden" id="<?php echo $this->getFieldId('full')?>" name="<?php echo $this->getFieldName('dob')?>" data-validate="{'validate-dob': ['.dob-day', '.dob-month', '.dob-year', <?php echo $this->isRequired() ? 'true' : 'false' ?>]<?php if ($this->getMinDateRange() && $this->getMaxDateRange()):?>, 'validate-date-between':['<?php echo $this->getMinDateRange()?>', '<?php echo $this->getMaxDateRange()?>']<?php endif;?>}"/>
        </span>
        <div class="validation-advice" id="<?php echo $this->getFieldId('date-advice')?>" style="opacity:0.999999; display:none;"></div>
    </div>
</div>
