<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this Enterprise_Reward_Block_Checkout_Payment_Additional */
?>
<?php if ($this->getCanUseRewardPoints()): ?>
    <dl class="sp-methods checkout-reward checkout-onepage-payment-additional-reward" id="reward_placer">
        <dt>
            <input type="checkbox" name="payment[use_reward_points]" value="1" id="use-reward-points"<?php echo $this->useRewardPoints()?' checked="checked"':'' ?> class="checkbox" />
            <label for="use-reward-points"><?php echo Mage::helper('Enterprise_Reward_Helper_Data')->__('Use my reward points, %s available', Mage::helper('Enterprise_Reward_Helper_Data')->formatReward($this->getPointsBalance(), $this->getCurrencyAmount())); ?></label>
        </dt>
    </dl>

<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('Enterprise_Reward::checkout/js/customerrewards.js') ?>",
            function() {
                $('#opc-payment').customerReqards({
                    rewardPointsSubstracted: <?php if ($this->useRewardPoints()): ?>true<?php else: ?>false<?php endif; ?>,
                    baseRewardCurrencyAmount: <?php echo (float)$this->getQuote()->getBaseRewardCurrencyAmount(); ?>,
                    balance: <?php echo (float)$this->getCurrencyAmount(); ?>,
                    quoteBaseGrandTotal: <?php echo (float)$this->getQuote()->getBaseRewardCurrencyAmount(); ?>,
                    rewardPointsBlockSelector: '#customerbalance-placer',
                    paymentMethodsSelector: '#checkout-payment-method-load',
                    payment: payment,
                    paymentForm: '#co-payment-form'
                });
            });
    })(jQuery);
</script>
<?php endif; ?>
