<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $_disabled = '';
    if ($this->getElement()->getDisabled()) {
        $_disabled = ' disabled="disabled"';
    }
?>
<?php
    foreach ($this->getStoreViews() as $_store) {
?>
<tr>
    <td class="label">
        <label for="conversion_url_<?php echo $_store->getCode() ?>"><?php echo Mage::helper('Mage_GoogleOptimizer_Helper_Data')->__('Conversion Page URL') ?> (<?php echo $_store->getName() ?>)</label>
    </td>
    <td class="value">
        <input type="text" class="input-text googleoptimizer conversion_urls" readonly="readonly" name="conversion_url_<?php echo $_store->getCode() ?>" id="conversion_url_<?php echo $_store->getCode() ?>"<?php echo $_disabled ?>/>
    </td>
    <td class="note"><small><?php echo Mage::helper('Mage_GoogleOptimizer_Helper_Data')->__('Please copy and paste this value to experiment edit form.') ?></small></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php
    }
?>
<script type="text/javascript">
//<![CDATA[
    function googleOptimizerConversionCmsPageAction(elm) {
        var urls = <?php echo $this->getJsonConversionPagesUrl() ?>;
        var storeViews = <?php echo $this->getJsonStoreViews() ?>;
        if (elm) {
            if (elm.value == '' || elm.value == 'other') {
                $$('.conversion_urls').each(function(elm){
                    elm.value = '';
                });
                return;
            } else {
                for (var i=0; i<=storeViews.length; i++) {
                    if ($('conversion_url_'+storeViews[i]) && urls[storeViews[i]][elm.value]) {
                        $('conversion_url_'+storeViews[i]).value = urls[storeViews[i]][elm.value];
                    }
                }
            }
        }
        return;
    }
//]]>
</script>
