<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->getAuthenticationStart()):?>
    <div class="centinel" id="centinel-authenticate-block" data-mage-init="{centinelAuthenticate: {frameUrl: '<?php echo $this->getFrameUrl() ?>'}}">
        <h3><?php echo __('Card Verification')?></h3>
        <p><?php echo __('Please verify the card with the issuer bank:') ?></p>
        <div class="authentication">
            <iframe id="centinel-authenticate-iframe" frameborder="0" border="0" src="" data-container="iframe"></iframe>
        </div>
    </div>
<?php else:?>
    <script type="text/javascript">
        jQuery('[data-container="body"]').trigger("paymentAuthentication", {state: "cancel"});
    </script>
<?php endif;?>
