<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Promotestore_Rss_Drawer */
?>
<form id="drawer-form">
    <article class="entry">
        <ul class="promote-actions">
            <?php $trackerLink = $this->getTrackerLink('adminhtml/system_config/edit', array('section' => 'rss', '_fragment' => 'rss_config-link')); ?>
            <li class="<?php echo $trackerLink->getIsVisited() ? "completed" : "uncompleted"?>"><a href="<?php echo $trackerLink->renderUrl(); ?>" target="_blank"><?php echo __('Create RSS Feeds') ?></a></li>
        </ul>
        <div class="promote-content">
            <div class="promote-content-section">
                <p><?php echo __('Really Simple Syndication (RSS) is exactly that: an easy-to-use technology that automatically sends messages to customers. RSS is the hassle-free way to alert customers to secret sales, new products, special events and more.') ?> </p>
            </div>
            <div class="promote-content-section">
                <p><?php echo __('Use RSS to build loyalty with subscribers by sending daily store deals, blog feeds and free "insider" info such as brand new cart rules. It\'s a cost-free contact strategy your store can\'t afford to skip. Stay close to your customers – set up your RSS feed today.') ?> </p>
            </div>
        </div>
    </article>
</form>
