<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Saas_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Saas_Launcher_Block_Adminhtml_Tile */
?>
<article class="tile-store-settings tile-rss <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>" tabindex="0">
    <h2><?php echo $this->helper('Saas_Launcher_Helper_Data')->__('RSS') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo $this->helper('Saas_Launcher_Helper_Data')->__('Give customers an easy way to get the latest store news.') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/promotestore_rss_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/promotestore_rss_drawer/load') ?>">
            <?php echo $this->helper('Saas_Launcher_Helper_Data')->__('Configure RSS Feed') ?>
        </button>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Saas_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <p><?php echo $this->helper('Saas_Launcher_Helper_Data')->__('Give customers an easy way to get the latest store news.') ?></p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/promotestore_rss_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/promotestore_rss_drawer/load') ?>">
            <?php echo $this->helper('Saas_Launcher_Helper_Data')->__('Configure RSS Feed') ?>
        </button>
        <?php endif; ?>
    </div>
</article>
