<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Magento_CustomerBalance_Block_Adminhtml_Customer_Edit_Tab_Customerbalance_Balance
 */
?>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo $this->helper('Magento_CustomerBalance_Helper_Data')->__('Store Credit Balance')?></span>
    </div>
    <?php echo $this->getChildHtml('grid')?>
    <?php echo $this->getDeleteOrphanBalancesButton() ?>
</div>
