<div class="home-spot">
	<img src="<?=$baseSkinUrl?>images/ph_home_spot.jpg" alt=""/>
</div>
<ul class="home-callout">
	<li><img src="<?=$baseSkinUrl?>images/home_callout_left.jpg" alt=""/></li>
	<li class="last"><img src="<?=$baseSkinUrl?>images/home_callout_right.jpg" alt=""/></li>
</ul>
<div class="home-left">
	<h2 class="accent">Recent News</h2>
	<p><strong>Magento on the Road: Meet Us at the Internet Retailer Conference</strong><br/>Varien is going north to visit the Internet Retailer Conference this June and if you'll be 
	there we would love to meet up.  We'll be available on the main conference days of June 5 and 6th, so if you  would like to learn more about Magento, contact us!</a>.</p>
</div>
<div class="home-right">
	<h2 class="accent">About Us</h2>
	<p>Magento is the <strong>open-source eCommerce</strong> platform that promises to revolutionize the industry. It's modular architecture and unprecedented flexibility means your 
	business is no longer constrained by your eCommerce platform. <strong>Magento is total control.</strong></p>
</div>
<div class="clear"></div>