<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Promotestore_Wishlist_Tile */
?>
<article class="tile-store-settings tile-wishlist <?php echo $this->getTileStateStyle(); ?>" id="tile-<?php echo $this->getTileCode()?>" tabindex="0">
    <h2><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Wish List') ?></h2>
    <div class="tile-teaser">
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Activate the wishlist feature for your customers.') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/promotestore_wishlist_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/promotestore_wishlist_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Configure') ?>
        </button>
    </div>

    <div class="tile-done">
        <?php if ($this->getTileState() == Mage_Launcher_Model_Tile::STATE_COMPLETE) :?>
        <p>
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Activate the wishlist feature for your customers.') ?>
        </p>
        <button type="button" class="action-open-drawer" data-drawer="open-drawer-<?php echo $this->getTileCode()?>"
                data-save-url="<?php echo $this->getUrl('*/promotestore_wishlist_drawer/save') ?>"
                data-load-url="<?php echo $this->getUrl('*/promotestore_wishlist_drawer/load') ?>">
            <?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Configure') ?>
        </button>
        <?php endif; ?>
    </div>
</article>
