<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_code=$this->getMethodCode() ?>
<fieldset class="fieldset items" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <div class="message notice">
        <div><?php echo __('You will be redirected to Ogone website when you place an order.') ?></div>
    </div>
</fieldset>
