<div id="answers_container">
<?if( !$answers ):?>
<h4><?=__('Please, add new questions.')?></h4>
<?else:?>
    <h4 class="icon-head head-edit-form fieldset-legend"><?=__('Assigned Answers')?></h4>
    <?foreach($answers->getItems() as $_item):?>
        <fieldset id="poll_answer_fieldset_<?=$_item->getId()?>">
        <span class="field-row">
            <label for="answer_<?=$_item->getId()?>">Answer Title: <span class="required">*</span></label>
            <input id="answer_<?=$_item->getId()?>" name="answer[<?=$_item->getId()?>][title]" value="<?=$_item->getAnswerTitle()?>" class="required-entry input-text" type="text" />
        </span>
        <?=$this->getDeleteButtonHtml()?>
        <span class="field-row">
            <label for="answer_votes_<?=$_item->getId()?>">Votes Count: <span class="required">*</span></label>
            <input id="answer_votes_<?=$_item->getId()?>" name="answer[<?=$_item->getId()?>][votes]" value="<?=$_item->getVotesCount()?>" class="required-entry validate-not-negative-number input-text" type="text" />
        </span>
        <input type="hidden" id="id_poll_answer_fieldset_<?=$_item->getId()?>" value="<?=$_item->getId()?>" />
        </fieldset>
    <?endforeach;?>
<?endif;?>
</div>
<?=$this->getAddButtonHtml();?>

<script type="text/javascript">
    var lastId = 0;
    var answer = function() {
        return {
            del : function(obj) {
                if( confirm('<?=__('Are you sure you want to do this?')?>') ) {
                    if( $('id_' + obj.parentNode.id) ) {
                        var itemId = $('id_' + obj.parentNode.id).value;
                        var newElement = document.createElement('input');
                        newElement.type = 'hidden';
                        newElement.value = itemId;
                        newElement.name = 'deleteAnswer[]';
                        $('answers_container').appendChild(newElement);
                    }
                    obj.parentNode.remove();
                }
            },

            add : function(obj) {
                var newElement = document.createElement('div');
                newElement.innerHTML = this.getTemplate();
                $('answers_container').appendChild(newElement);
            },

            getTemplate : function() {
                var id = this.createId();
                return  '<fieldset id="poll_answer_fieldset_' + id + '">'
                       +'<span class="field-row">'
                       +    '<label for="answer_' + id + '">Answer Title: <span class="required">*</span></label>'
                       +    '<input id="answer_' + id + '" name="answer[' + id + '][title]" value="" class="required-entry input-text" type="text" />'
                       +'</span>'
                       +'<?=$this->getDeleteButtonHtml()?>'
                       +'<span class="field-row">'
                       +    '<label for="answer_votes_' + id + '">Votes Count: <span class="required">*</span></label>'
                       +    '<input id="answer_votes_' + id + '" name="answer[' + id + '][votes]" value="0" class="required-entry validate-not-negative-number input-text" type="text" />'
                       +'</span>'
                       +'</fieldset>';
            },

            createId : function () {
                return --lastId;
            }
        }
    }();
</script>