<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo __('Your account balance is: %1', $customer->getStoreBalance()) ?> 
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
</div>
