<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Installation start page
 *
 * @see \Magento\Install\Block\Begin
 */
?>
<div class="page-head">
    <h3><?php echo __("Welcome to Magento's Installation Wizard") ?>!</h3>
</div>
<?php echo $this->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<?php if (count($this->getLayout()->getMessagesBlock()->getMessages()) == 0): ?>
<form action="<?php echo $this->getPostUrl() ?>" method="post">
    <div
        style="height:20em; border:1px solid #ccc; margin-bottom:8px; padding:5px; background:#fff; overflow: auto; overflow-x:hidden; overflow-y:scroll;">
        <?php echo $this->getLicenseHtml() ?>
    </div>
    <p>
        <input type="checkbox" name="agree" value="1" id="agree" class="checkbox"/>
        <label for="agree"><?php echo __('I agree to the above terms and conditions.') ?></label>
    </p>

    <div class="button-set">
        <button class="form-button mage-disabled" type="submit" id="submitButton" disabled="disabled">
            <span><?php echo __('Continue') ?></span></button>
    </div>
</form>
<script type="text/javascript">
require([
    "jquery",
    "Magento_Install/js/install"
], function($){

//<![CDATA[
    $.mage.install.begin('#agree', '#submitButton');
//]]>

});
</script>
<?php endif ?>
