<script type="text/javascript">
function mark(index) {
	var sels = document.getElementById('tags').getElementsByTagName('select');
	for (var i = 0; i < sels.length; i++) {
		sels[i].selectedIndex = index - 1;
	}
}
</script>
<h1>Peding tags</h1>
<? if (count($collection->getItems()) > 0) { ?>
<form id="tags" action="/adminhtml/tag/approve">
	<ol>
	<? foreach ($collection->getItems() as $tag) { $tag = $tag->getData();?>
		<li>		
			<select name="tags['<?=$tag['tag_id'];?>']">
				<option value="1"><?=__('Pending')?></option>
				<option value="2"><?=__('Approved')?></option>
				<option value="4"><?=__('Unapproved')?></option>
			</select> 
			<?=$tag['tagname'];?>
		</li>	
	<? } ?>
	</ol>
	
	<ul>
		<li><a href="#" onclick="mark(1)"><?=__('Mark All as Pending')?></a></li>
		<li><a href="#" onclick="mark(2)"><?=__('Mark All as Approved')?></a></li>
		<li><a href="#" onclick="mark(3)"><?=__('Mark All as Unapproved')?></a></li>
	</ul>
	
	<input type="submit" value="<?=__('Update Tags Statuses')?>" />
</form>
<? } else { ?>
	<?=__('There are no pending tags.')?>
<? } ?>
