<h1>Tagged Products</h1>
<form action="">
	<input type="text" name="q" value="<?=@$query;?>" /> <input type="submit" value="Search" />
</form>

<?php if (!empty($collection)) {?>
<ol>
<?php foreach ($collection as $item) { ?>
	<li>
		<?=$item['name'];?>
		<div style="font-color:999; font-size:12px">Tags: 
			<?php foreach ($item['tags'] as $tag) { ?>
				<A href="#"><?=$tag['tagname'];?></a> 
			<?php } ?>
		</div>
	</li>
<?php } ?>
</ol>
<?php } ?>