<?php echo $this->template('install/header.phtml') ?>

<div class="page-head">
    <h3>Welcome to Magento's Installation Wizard!</h3>
</div>

<fieldset>
<?php if (!$this->controller()->isDownloaded()): ?>
    <p>You are now ready to download the complete and most up to date Magento ecommerce</p>
    <button class="form-button" type="button" onclick="installAll(false)">Click here to start the download process</button>
<?php else: ?>
    <button class="form-button" type="button" onclick="installAll(true)">Re-Install All Magento Core Packages</button>
<?php endif; ?>
</fieldset>

<br/>
<?php echo $this->template('pear/iframe.phtml') ?>

<a name="pear_iframe_result"></a>
<div id="pear_iframe_success" style="display:none">
    <?php $this->set('messages', array('success'=>array(
       'Download completed. You can proceed with intallation',
    ))) ?>
    <?php echo $this->template('messages.phtml') ?>

    <button class="form-button" type="button" onclick="location.href='<?php echo $this->mageUrl() ?>'"><span>Continue Magento installation</span></button>
</div>

<div id="pear_iframe_failure" style="display:none">
    <?php $this->set('messages', array('error'=>array('There was a problem during downloading of Magento packages. Please check the output frame for errors information and refresh the page to retry again.'))) ?>
    <?php echo $this->template('messages.phtml') ?>
    <button class="form-button" type="button" onclick="location.reload()"><span>Refresh</span></button>
</div>

<script type="text/javascript">
function installAll(force)
{
    if (force) {
        if (!confirm("This will delete all files from core packages.\n\nAre you sure you wish to force re-install all Magento files?")) {
            return;
        }
    }

    onSubmit();
    $('pear_iframe').src = '<?php echo $this->url('pearInstallAll') ?>'
        +(force ? '&force=1' : '');
}
</script>

<?php echo $this->template('install/footer.phtml') ?>