<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
            <!-- [end] content -->
            </div>
        </div>

            <!-- [end] center -->
    </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
    <div class="footer-container">
        <div class="footer">
        <p class="legality">
            Help Us to Keep Magento Healthy - <a href="http://www.magentocommerce.com/bug-tracking" id="bug_tracking_link"><strong>Report All Bugs</strong></a> (Downloader ver. <?php echo \Magento\Downloader\Controller::getVersion();?>)<br/>

<script type="text/javascript">
    $('bug_tracking_link').target = "varien_external";
</script>
            Magento&reg is a trademark of X.commerce, Inc. Copyright &copy; 2012 X.commerce, Inc.</p>
        </div>
    </div>
        <!-- [end] footer -->
    </body>
</html>
