<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title title-buttons">
    <h1><?php echo __('Compare Products') ?></h1>
    <a href="#" class="link-print"><?php echo __('Print This Page') ?></a>
</div>
<?php $_total=$this->getItems()->getSize() ?>
<?php if($_total): ?>
    <table class="data-table" id="product-comparison">
    <?php $_i=0 ?>
    <?php foreach($this->getItems() as $_item): ?>
        <?php if($_i++%10==0): ?>
            <col width="1" />
        <?php endif; ?>
            <col width="<?php echo floor(100/$_total); ?>%" />
    <?php endforeach; ?>
<?php if ($_total>2): ?>
        <thead>
            <tr>
            <?php $_i=0 ?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                    <th>&nbsp;</th>
                <?php endif; ?>
                <td class="a-right"><a href="#" title="<?php echo __('Remove Product') ?>"><img class="btn-remove" data-url='<?php echo $this->helper('\Magento\Catalog\Helper\Product\Compare')->getRemoveUrl($_item) ?>' src="<?php echo $this->getViewFileUrl('images/list_remove_btn.gif') ?>" alt="<?php echo __('Remove Product') ?>" /></a></td>
            <?php endforeach; ?>
            </tr>
        </thead>
<?php endif ?>
        <tbody>
            <tr>
            <?php $_i = 0; ?>
            <?php $_helper = $this->helper('\Magento\Catalog\Helper\Output'); ?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                    <th class="label">&nbsp;</th>
                <?php endif; ?>
                <td>
                    <a class="product-image" href="#" data-url="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><img src="<?php echo $this->getSmallImageUrl($_item); ?>" width="<?php echo $this->getSmallImageSize()?>" height="<?php echo $this->getSmallImageSize()?>" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" /></a>
                    <h3 class="product-name"><a href="#" data-url="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?></a></h3>
                    <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                    <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
                    <?php if($_item->isSaleable()): ?>
                        <p><button type="button" class="button btn-cart" data-url="<?php echo $this->helper('\Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item) ?>"><span><span><?php echo __('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <?php if ($_item->getIsSalable()): ?>
                            <p class="availability in-stock"><span><?php echo __('In stock') ?></span></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo __('Out of stock') ?></span></p>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('\Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                        <p><a href="#" data-url="<?php echo $this->helper('\Magento\Catalog\Helper\Product\Compare')->getAddToWishlistUrl($_item) ?>" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></p>
                    <?php endif; ?>
                </td>
            <?php endforeach; ?>
            </tr>
        </tbody>
        <tbody>
        <?php foreach ($this->getAttributes() as $_attribute): ?>
            <tr>
                <?php $_i = 0 ?>
                <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                <th class="label"><span class="nobr"><?php echo $_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel()) ?></span></th>
                <?php endif; ?>
                <td>
                    <?php switch ($_attribute->getAttributeCode()) {
                        case "price": ?>
                            <?php echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode()) ?>
                            <?php break;
                        case "small_image": ?>
                            <img src="<?php echo $this->getSmallImageUrl($_item); ?>" width="<?php echo $this->getSmallImageSize()?>" height="<?php echo $this->getSmallImageSize()?>" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                            <?php break;
                        default: ?>
                            <div class="std">
                                <?php echo $_helper->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                            </div>
                            <?php break;
                    } ?>
                </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
        <tbody>
                <tr>
                <?php $_i=0 ?>
                <?php foreach($this->getItems() as $_item): ?>
                <?php if($_i++%10==0): ?>
                 <th class="label">&nbsp;</th>
                <?php endif; ?>
                <td class="data">
                    <?php echo $this->getPriceHtml($_item, true, '-compare-list-bottom') ?>
                    <?php if($_item->isSaleable()): ?>
                        <p><button type="button" class="button btn-cart" data-url="<?php echo $this->helper('\Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item) ?>"><span><span><?php echo __('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <?php if ($_item->getIsSalable()): ?>
                            <p class="availability in-stock"><span><?php echo __('In stock') ?></span></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo __('Out of stock') ?></span></p>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('\Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                        <p><a href="#" data-url="<?php echo $this->helper('\Magento\Catalog\Helper\Product\Compare')->getAddToWishlistUrl($_item) ?>" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></p>
                    <?php endif; ?>
                </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
    <div class="buttons-set">
        <button id="window-close" type="button" class="button"><span><span><?php echo __('Close Window') ?></span></span></button>
        <span class="please-wait" id="compare-list-please-wait" style="display:none;">
            <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo __('Please wait...') ?>" title="<?php echo __('Please wait...') ?>" class="v-middle" /> <?php echo __('Please wait...') ?>
        </span>
    </div>
<?php endif; ?>
<script type="text/javascript">
    (function($, window) {
    <?php if ($_total): ?>
        head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/list.js')?>", function() {
            $('#product-comparison').compareList({
                productRemoveSelector: 'img.btn-remove',
                ajaxSpinner: '#compare-list-please-wait',
                windowCloseSelector: '#window-close',
                windowPrintSelector: 'a.link-print',
                selectors: {
                    productSelector: 'h3.product-name > a',
                    productImageSelector: 'a.product-image',
                    productAddToCartSelector: 'button.btn-cart',
                    productWishListSelector: 'a.link-wishlist'
                }
            });
        });
    <?php else: ?>
        window.close();
    <?php endif; ?>
    })(jQuery, window);
</script>

