<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var $this Magento_CurrencySymbol_Block_Adminhtml_System_Currency
 */
?>
<div class="page-actions clearfix">
    <form action="<?php echo $this->getImportFormAction() ?>" method="post" class="import-service">
        <?php echo $this->getBlockHtml('formkey')?>
        <?php echo $this->getServicesHtml() ?>
        <?php echo $this->getImportButtonHtml() ?>
    </form>
    <?php echo $this->getResetButtonHtml() ?>
    <?php echo $this->getSaveButtonHtml() ?>
</div>

<?php echo $this->getRatesMatrixHtml() ?>
