<label for="store_switcher"><?=__('Choose Store')?>:</label>
<select name="store_switcher" id="store_switcher" class="left-col-block" onchange="return switchStore(this);">
    <option value=""><?=__('All stores')?></option>
    <?foreach ($this->getWebsiteCollection() as $_website):?>
        <optgroup label="<?=$_website->getName()?>">
        <?foreach ($_website->getStoreCollection() as $_store):?>
            <option value="<?=$_store->getId()?>"<?if($this->getStoreId() == $_store->getId()):?> selected<?endif;?>><?=$_store->getName()?></option>
        <?endforeach;?>
        </optgroup>
    <?endforeach;?>
</select>
<script type="text/javascript">
    function switchStore(obj){
        var storeParam = obj.value ? 'store/'+obj.value : '';
    <?if($this->getUseConfirm()):?>
        if(confirm('<?=__('Please, confirm site switching...')?>')){
            setLocation('<?=$this->getSwitchUrl()?>'+storeParam);
            return true;
        }
        else {
            obj.value = '<?=$this->getStoreId()?>';
        }
        return false;
    <?else:?>
        setLocation('<?=$this->getSwitchUrl()?>'+storeParam);
    <?endif;?>
    }
</script>