<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Category layered navigation
 *
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="filters-block">
    <?php echo $this->getStateHtml() ?>
    <?php if ($this->getLayer()->getState()->getFilters()): ?>
        <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo __('Clear All') ?></a></div>
    <?php endif; ?>
    <div class="block-content">
    <?php if($this->canShowOptions()): ?>
            <h3><?php echo __('Shop By') ?></h3>
            <?php $_filters = $this->getFilters() ?>
            <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                <dl>
                    <dt><?php echo __($_filter->getName()) ?></dt>
                    <dd><?php echo $_filter->getHtml() ?></dd>
                </dl>
                <?php endif; ?>
            <?php endforeach; ?>
    <?php endif; ?>
    </div>
</div>
<?php endif; ?>
