<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/**
 * @var \Magento\Ui\Component\Filter $this
 */
?>
<strong class="item-label" data-bind-="text: $t(filter.title)"><?php echo $this->getData('label') ?></strong>
<span class="item-value" data-bind-="text: $t(filter.output)"><?php echo $this->getData('current_display_value') ?></span>
<button data-bind-="click: $parent.onClear(filter)" type="button" class="action action-remove"><span data-bind-="text: $t('Remove')"></span></button>