<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<?php $_option = $this->getOption() ?>
<?php $_selections = $_option->getSelections() ?>

<dt>
	<span class="bundle-option"><?php echo $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getRequired()) echo '<span class="required">&nbsp;*</span>' ?></span>
	<span class="qty-holder">
        <?php if ($_default = $_option->getDefaultSelection()): ?>
            <?php $_defaultQty = $_default->getSelectionQty()*1 ?>
            <?php $_canChangeQty = $_default->getSelectionCanChangeQty() ?>
        <?php else: ?>
            <?php $_defaultQty = '' ?>
            <?php $_canChangeQty = false ?>
        <?php endif; ?>
        <label><?php echo $this->__('Qty:') ?>&nbsp;</label><input onkeyup="bundle.changeOptionQty(this)" style="display:<?php echo $_canChangeQty?'block':'none' ?>" id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty" type="text" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>" />
		<span style="display:<?php echo $_canChangeQty?'none':'block' ?>" id="bundle-option-<?php echo $_option->getId() ?>-qty-label"><?php echo $_defaultQty ?></span>	
	</span>
</dt>
<dd>
	<?php if (count($_selections) == 1 && $_selections[0]->getDefault()): ?>
		<?php echo $_selections[0]->getName() ?>
		<input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>" />
	<?php else:?>
		<?php if(!$_option->getRequired()): ?>
		<label><input onclick="bundle.changeSelection(this)" class="validate-one-required form-radio" id="bundle-option-<?php echo $_option->getId() ?>" type="radio" name="bundle_option[<?php echo $_option->getId() ?>]"<?php echo ($_option->getDefaultSelection())?'':' checked="checked" ' ?> value="none" /><?php echo $this->__('None') ?></label>
		<?php endif; ?>
		<?php foreach($_selections as $_selection): ?>
		<label><input onclick="bundle.changeSelection(this)" class="validate-one-required form-radio" id="bundle-option-<?php echo $_option->getId() ?>" type="radio" name="bundle_option[<?php echo $_option->getId() ?>]"<?php echo ($_selection->getIsDefault() && $_selection->isSaleable())?' checked="checked" ':'' ?><?php echo !$_selection->isSaleable()?' disabled="disabled" ':'' ?> value="<?php echo $_selection->getSelectionId() ?>" /><?php echo $this->getSelectionTitlePrice($_selection) ?></label>
		<?php endforeach;?>
	<?php endif; ?>
</dd>
