<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <table cellspacing="0" width="100%">
        <?foreach($this->getWishlist() as $item):?>
        <tr>
            <td>
                <div><a href="<?=$item->getProductUrl()?>"><img src="<?=$item->getSmallImageUrl()?>" alt="<?=htmlspecialchars($item->getName())?>" width="113"/></a></div>
            	<div><a href="<?=$item->getProductUrl()?>" title="<?=$item->getName()?>"><?=$item->getName()?></a></div>
            	<?=$this->getHelper('catalog/product')->getPriceHtml($item)?>
            </td>
            <td class="align-center">
            	<a href="<?=$this->getUrl('checkout/cart/add',array('product'=>$item->getProductId()))?>" ><?=__('Add to cart')?></a><br/>
            	<a href="<?=$item->getProductUrl()?>" ><?=__('See info')?></a><br/>
            </td>
        </tr>
        <?endforeach?>
    </table>