<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title">
    <h1><?php echo __('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data">
<div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
    <h2 class="legend"><?php echo __('Account Information') ?></h2>
    <ul class="form-list">
        <li class="fields">
            <?php echo $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Name')->setObject($this->getCustomer())->toHtml() ?>
        </li>
        <li>
            <label for="email" class="required"><em>*</em><?php echo __('Email Address') ?></label>
            <div class="input-box">
                <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo __('Email Address') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </li>
        <?php $_dob = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Dob') ?>
        <?php $_taxvat = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Taxvat') ?>
        <?php $_gender = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Gender') ?>
        <?php if($_dob->isEnabled() || $_taxvat->isEnabled() || $_gender->isEnabled()): ?>
        <li class="fields">
            <?php if ($_dob->isEnabled()): ?>
            <div class="field"><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></div>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
            <div class="field"><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></div>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
            <div class="field"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></div>
            <?php endif ?>
        </li>
        <?php endif ?>
        <li class="control">
            <div class="input-box">
                <input type="checkbox" name="change_password" id="change-password" value="1" title="<?php echo __('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
            </div>
            <label for="change-password"><?php echo __('Change Password') ?></label>
        </li>
    </ul>
</div>
<?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
<?php if ($userDefinedAttributes):?>
    <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
<?php endif;?>
<div class="fieldset" style="display:none;">
    <h2 class="legend"><?php echo __('Change Password') ?></h2>
    <ul class="form-list">
        <li class="fields">
            <div class="field">
                <label for="current-password"><?php echo __('Current Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text" name="current_password" id="current-password" />
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="password"><?php echo __('New Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text" name="password" id="password" />
                </div>
            </div>
            <div class="field">
                <label for="confirmation"><?php echo __('Confirm New Password') ?></label>
                <div class="input-box">
                    <input type="password" class="input-text" name="confirmation" id="confirmation" />
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set form-buttons">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Go back') ?></a></p>
    <button type="submit" class="button" title="<?php echo __('Save') ?>"><span><span><?php echo __('Save') ?></span></span></button>
</div>
<p class="required"><?php echo __('* Required Fields') ?></p>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            "<?php echo $this->getViewFileUrl('Magento_Customer::set-password.js') ?>",
            <?php if ($userDefinedAttributes->hasUserDefinedAttributes()): ?>
                "<?php echo $this->getViewFileUrl('Enterprise_Customer::file-element.js')?>",
            <?php endif ?>
            <?php if ($_dob->isEnabled()): ?>
                "<?php echo $this->getViewFileUrl('mage/validation/dob-rule.js') ?>",
            <?php endif ?>
            function() {
                $('#change-password').setPassword({
                    currentPasswordId: '#current-password',
                    passwordId: '#password',
                    confirmationId: '#confirmation',
                    passwordContainer: 'div.fieldset',
                    showOnDefault: <?php echo $this->getCustomer()->getChangePassword() ? 'true' : 'false' ?>
                });
                var dataForm = $('#form-validate'), ignore;
                <?php if ($_dob->isEnabled()): ?>
                    ignore = '#full';
                <?php endif ?>
                <?php if ($userDefinedAttributes->hasUserDefinedAttributes()): ?>
                    dataForm = dataForm.fileElement();
                    ignore = ignore ? ignore + ', ' + 'input[id$="_value"]' : 'input[id$="_value"]';
                <?php endif ?>
                dataForm.validation({
                <?php if ($_dob->isEnabled()): ?>
                    errorPlacement: function(error, element) {
                        if (element.prop('id') === 'full') {
                            var dobElement = $('.customer-dob'),
                                errorClass = error.prop('class');
                            error.insertAfter(element.parent());
                            dobElement.find('.validate-custom').addClass(errorClass)
                                .after('<div class="' + errorClass + '"></div>');
                        }
                        else {
                            error.insertAfter(element);
                        }
                    },
                    ignore: ':hidden:not(' + ignore + ')'
                <?php else: ?>
                    ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                <?php endif ?>
                });
            });
    })(jQuery);
</script>
