<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Create account form template
 *
 * @see Magento_Customer_Block_Form_Register
 */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo __('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo __('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                <?php echo $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo __('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo __('Email Address') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo __('Sign Up for Newsletter') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                </li>
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            <?php $customerAttributes = $this->getChildBlock('customer_form_user_attributes');?>
            <?php if ($customerAttributes): ?>
                <?php $customerAttributes->setShowContainer(false);?>
                <?php $this->restoreSessionData($customerAttributes->getForm());?>
                <?php echo $customerAttributes->toHtml()?>
            <?php endif;?>
            </ul>
        </div>
        <div class="divider"></div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo __('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo __('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo __('Company') ?>" class="input-text <?php echo Mage::helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo __('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo __('Telephone') ?>" class="input-text <?php echo Mage::helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = Mage::helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo __('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo __('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = Mage::helper('Magento_Customer_Helper_Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="add-field">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo __('Street Address %1', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo __('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo __('City') ?>" class="input-text <?php echo Mage::helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo __('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo __('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo __('Please select region, state or province') ?></option>
                            </select>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo __('State/Province') ?>" class="input-text <?php echo Mage::helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo __('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo Mage::helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo __('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
                <?php $addressAttributes = $this->getChildBlock('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntity($this->getAddress());?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $this->restoreSessionData($addressAttributes->getForm(), 'address');?>
                    <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                <?php endif;?>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
        <div class="divider"></div>
    <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo __('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo __('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo __('Password') ?>" class="input-text" data-validate="{required:true, 'validate-password':true}" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo __('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo __('Confirm Password') ?>" id="confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" />
                        </div>
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        <div class="buttons-set form-buttons">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo __('Back') ?></a></p>
            <button type="submit" class="button" title="<?php echo __('Submit') ?>"><span><span><?php echo __('Submit') ?></span></span></button>
        </div>
        <p class="required"><?php echo __('* Required Fields') ?></p>
    </form>
    <script type="text/javascript">
        (function($) {
            head.js(
                "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
                <?php if ($this->getShowAddressFields()): ?>
                    "<?php echo $this->getViewFileUrl('Magento_Checkout::js/region-updater.js') ?>",
                <?php endif ?>
                <?php if ($customerAttributes->hasUserDefinedAttributes()): ?>
                    "<?php echo $this->getViewFileUrl('Enterprise_Customer::file-element.js') ?>",
                <?php endif ?>
                <?php if ($_dob->isEnabled()): ?>
                    "<?php echo $this->getViewFileUrl('mage/validation/dob-rule.js') ?>",
                <?php endif ?>
                function() {
                    var dataForm = $('#form-validate'), ignore;
                    <?php if ($_dob->isEnabled()): ?>
                        ignore = '#full';
                    <?php endif ?>
                    <?php if ($customerAttributes->hasUserDefinedAttributes()): ?>
                        dataForm = dataForm.fileElement();
                        ignore = ignore ? ignore + ', ' + 'input[id$="_value"]' : 'input[id$="_value"]';
                    <?php endif ?>
                    dataForm.validation({
                    <?php if ($_dob->isEnabled()): ?>
                        errorPlacement: function(error, element) {
                            if (element.prop('id') === 'full') {
                                var dobElement = $('.customer-dob'),
                                    errorClass = error.prop('class');
                                error.insertAfter(element.parent());
                                dobElement.find('.validate-custom').addClass(errorClass)
                                    .after('<div class="' + errorClass + '"></div>');
                            }
                            else {
                                error.insertAfter(element);
                            }
                        },
                        ignore: ':hidden:not(' + ignore + ')'
                    <?php else: ?>
                        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                    <?php endif ?>
                    }).find('input:text').attr('autocomplete', 'off');
                    <?php if ($this->getShowAddressFields()): ?>
                        $('#country').regionUpdater({
                            optionalRegionAllowed: <?php echo (Mage::getStoreConfig('general/region/display_all')? 'true' : 'false'); ?>,
                            regionListId: '#region_id',
                            regionInputId: '#region',
                            postcodeId: '#zip',
                            form: dataForm,
                            regionJson: <?php echo Mage::helper('Magento_Directory_Helper_Data')->getRegionJson() ?>,
                            defaultRegion: "<?php echo $this->getFormData()->getRegionId() ?>",
                            countriesWithOptionalZip: <?php echo Mage::helper('Magento_Directory_Helper_Data')->getCountriesWithOptionalZip(true) ?>
                        });
                    <?php endif; ?>
                });
        })(jQuery);
    </script>
</div>
