<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title">
    <h1><?php echo __('Create a new password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
    <div class="fieldset" style="margin-top: 70px;">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo __('New Password'); ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text" name="password" id="password" data-validate="{required:true, 'validate-password':true}"/>
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo __('Confirm New Password'); ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text" name="confirmation" id="confirmation" data-validate="{required:true, 'validate-cpassword':true}"/>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set form-buttons">
        <button type="submit" class="button"><span><span><?php echo __('Submit'); ?></span></span></button>
    </div>
    <p class="required"><?php echo __('* Required Fields'); ?></p>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#form-validate').validation();
            });
    })(jQuery);
</script>
