<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\RecurringProfile\Block\Catalog\Product\View\Profile
 */
?>
<dl class="payment product schedule">
<?php foreach($this->getScheduleInfo() as $term => $definitions): ?>
    <dt class="title"><?php echo $this->escapeHtml($term); ?></dt>
    <?php foreach ($definitions as $definition):?>
        <dd class="content"><?php echo $this->escapeHtml($definition)?></dd>
    <?php endforeach;?>
<?php endforeach;?>
</dl>
