<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see Magento_CatalogInventory_Block_Stockqty_Default
 */
?>
<?php if($this->isMsgVisible()): ?>
    <p class="availability-only">
        <span title="<?php echo __('Only %1 left', ($this->getStockQty())) ?>"><?php echo __('Only %1 left', "<strong>{$this->getStockQty()}</strong>") ?></span>
    </p>
<?php endif ?>
