<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Reports\Block\Product\Viewed */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="block block-list block-viewed">
    <div class="block-title">
        <strong><span><?php echo __('Recently Viewed Products') ?></span></strong>
    </div>
    <div class="block-content">
        <ol id="recently-viewed-items">
            <?php foreach ($_products as $_item): ?>
            <li class="item">
                <p class="product-name"><a
                    href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('\Magento\Catalog\Helper\Output')->productAttribute($_item, $_item->getName(), 'name') ?></a>
                </p>
            </li>
            <?php endforeach; ?>
        </ol>
        <script type="text/javascript">(function($) {$('#recently-viewed-items').decorate('list', false)})(jQuery)</script>
    </div>
</div>
<?php endif; ?>
