<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var \Magento\GiftCard\Pricing\Render\FinalPriceBox $this */ ?>
<?php $productId = $this->getSaleableItem()->getId(); ?>

<?php if ($this->getCanShowPrice() !== false):?>
    <div class="price-box">
        <?php if ($this->isMinEqualToMax()): ?>
            <span class="price" id="product-price-<?php echo $productId ?><?php echo $this->getIdSuffix() ?>">
            <?php echo $this->convertAndFormatCurrency($this->getMinValue(), false) ?>
        </span>
        <?php elseif ($this->getMinValue() !== 0): ?>
            <span class="price-label"><?php echo __('From') ?></span>
            <span class="price" id="min-product-price-<?php echo $productId ?><?php echo $this->getIdSuffix() ?>">
            <?php echo $this->convertAndFormatCurrency($this->getMinValue(), false) ?>
        </span>
        <?php endif; ?>
    </div>
<?php endif; ?>

<?php if ($this->getRenderForm()): ?>
    <?php if ($this->isRegularPrice()): ?>
        <div class="price-box">
            <span class="regular-price">
                <span class="price" id="product-price-<?php echo $productId ?><?php echo $this->getIdSuffix() ?>">
                    <?php echo $this->convertAndFormatCurrency($this->getRegularPrice(), false) ?>
                </span>
            </span>
        </div>
    <?php else: ?>
        <fieldset class="fieldset giftcard amount">
            <div class="field required amount">
                <?php if ($this->isAmountAvailable()): ?>
                    <label for="giftcard-amount" id="amount-label-select" class="label">
                        <span><?php echo __('Amount'); ?></span>
                    </label>
                <?php endif; ?>
                <?php if ($this->isOpenAmountAvailable()): ?>
                    <label for="giftcard-amount-input" id="amount-label-input" class="label">
                        <span><?php echo __('Amount in %1', $this->getCurrentCurrency()); ?></span>
                    </label>
                <?php endif; ?>

                <div class="control">
                    <?php if ($this->isOpenAmountAvailable()): ?>
                        <div id="giftcard-amount-box" class="nested custom">
                            <div class="control">
                                <input type="text" id="giftcard-amount-input" name="custom_giftcard_amount" class="input-text"
                                       data-validate="{number: true,required: true
                                        <?php if ($this->getOpenAmountMin()) {
                                           echo ',min: ';
                                           echo $this->convertAndFormatCurrency($this->getOpenAmountMin(), false);
                                       }
                                       if ($this->getOpenAmountMax()) {
                                           echo ',max: ';
                                           echo $this->convertCurrency($this->getOpenAmountMin());
                                       }
                                       ?>
                                        }" value="<?php echo $this->escapeHtml($this->getDefaultValue('custom_giftcard_amount')) ?>" />

                                <?php if ($this->getOpenAmountMin() || $this->getOpenAmountMax()): ?>
                                    <?php $min = $this->convertAndFormatCurrency($this->getOpenAmountMin(), false); ?>
                                    <?php $max = $this->convertAndFormatCurrency($this->getOpenAmountMax(), false); ?>
                                    <p class="note">
                                        <?php if ($this->getOpenAmountMax() && $this->getOpenAmountMin()): ?>
                                            <span><?php echo __('Minimum: %1', $min); ?></span>
                                            <span><?php echo __('Maximum: %1', $max); ?></span>
                                        <?php elseif ($this->getOpenAmountMin()): ?>
                                            <span><?php echo __('Minimum: %1', $min); ?></span>
                                        <?php elseif ($this->getOpenAmountMax()): ?>
                                            <span><?php echo __('Maximum: %1', $max); ?></span>
                                        <?php endif; ?>
                                    </p>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>

                    <?php if ($this->isAmountAvailable()): ?>
                        <?php $configValue = $this->getDefaultValue('giftcard_amount'); ?>
                        <div class="nested amounts">
                            <div class="control">
                                <select name="giftcard_amount" id="giftcard-amount" class="required-entry giftcard-amount-entry">
                                    <option value=""><?php echo __('Choose an Amount...') ?></option>
                                    <?php foreach ($this->getAmounts() as $value): ?>
                                        <option value="<?php echo $value; ?>" <?php echo (($configValue == $value) ? 'selected' : '')?>>
                                            <?php echo $this->convertAndFormatCurrency($value, false); ?>
                                        </option>
                                    <?php endforeach; ?>

                                    <?php if ($this->isOpenAmountAvailable()): ?>
                                        <option value="custom" <?php echo (($configValue == 'custom') ? 'selected' : '')?>><?php echo __('Other Amount...') ?></option>
                                    <?php endif; ?>
                                </select>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </fieldset>
        <script type="text/javascript">
            (function($) {
                head.js("<?php echo $this->getViewFileUrl('Magento_GiftCard::toggle-gift-card.js')?>", function() {
                    $('#giftcard-amount').toggleGiftCard();
                });
            })(jQuery);
        </script>
    <?php endif; ?>
<?php endif; ?>
