<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * Create account form template
 */
/* @var $this \Magento\CustomAttributeManagement\Block\Form\Renderer\Image */
?>
<?php
$fieldCssClass = 'field field-' . $this->getHtmlId();
$fieldCssClass .= $this->isRequired() ? ' required' : '';
?>
<div class="<?php echo $fieldCssClass; ?>">
    <label class="label" for="<?php echo $this->getHtmlId()?>"><span><?php echo $this->getLabel() ?></span></label>
    <div class="control">
        <input type="file" id="<?php echo $this->getHtmlId()?>" name="<?php echo $this->getFieldName()?>" value="" class="input-file">
        <input type="hidden" id="<?php echo $this->getHtmlId()?>_value" name="<?php echo $this->getFieldName()?>_value" value="<?php echo $this->getEscapedValue()?>" <?php if ($this->isRequired()): ?>data-validate="{required:true}" <?php endif;?>/>
        <?php if ($_message = $this->getAdditionalDescription()) : ?>
        <div class="note"><?php echo $_message; ?></div>
        <?php endif; ?>
    </div>
</div>
