<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Rss\Block\Order\Info\Buttons\Rss */
?>
<?php if($this->getOrderHelper()->isStatusNotificationAllow()): ?>
    <a href="<?php echo $this->getOrderHelper()->getStatusHistoryRssUrl($this->getOrder()) ?>"
       class="action rss">
        <span><?php echo __('Subscribe to Order Status') ?></span>
    </a>
<?php endif; ?>
