<form id="co-payment-form">
    <dl class="payment-methods">
        <?=$this->getChildHtml('methods')?>
    </dl>
</form>
<div class="form-buttons">
    <p class="required">* Required Fields</p>
    <button class="form-button" onclick="checkout.back()"><span><?=__('Back')?></span></button>
    <button class="form-button" onclick="payment.save()"><span><?=__('Continue')?></span></button>
</div>

<script type="text/javascript">
    var payment = new Payment('co-payment-form', '<?=$this->getUrl('checkout/onepage/savePayment')?>');
    payment.currentMethod = "<?=$this->getPayment()->getMethod()?>";
</script>
