<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="box one-page-checkout-progress">
		<h3>Your Checkout Progress</h3>
	<ol>
	
<?if($this->getCheckout()->getStepData('billing', 'complete')):?>
		<li>
			<h4 class="complete">Billing Address<span class="separator">|</span><a href="#billing" onclick="checkout.accordion.openSection('opc-billing');return false;">Edit</a></h4>

			<div class="content">
				<address>
				<?=$this->getBilling()->getFormated(true)?></address></div></li>
<?else:?>
		<li>
			<h4>Billing Address</h4>
        </li>
<?endif?>
				
<?if($this->getCheckout()->getStepData('shipping', 'complete')):?>
		<li><h4 class="complete">Shipping Address<span class="separator">|</span><a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;">Edit</a></h4>	
			<div class="content">
				<address><?=$this->getShipping()->getFormated(true)?></address></div></li>
<?else:?>
		<li>
			<h4>Shipping Address</h4>
        </li>
<?endif?>

<?if($this->getCheckout()->getStepData('shipping_method', 'complete')):?>
        <li><h4 class="complete">Shipping Method<span class="separator">|</span><a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method');return false;">Edit</a></h4>	
			<div class="content"><?if ($this->getShippingMethod()):?>
				<?=$this->getShippingDescription()?>: <?=$this->getShippingAmount()?>
			<?else:?>
				<?=__('Shipping method was not selected yet')?>
			<?endif?>
			</div></li>
<?else:?>
		<li>
			<h4>Shipping Method</h4>
        </li>
<?endif?>
				
<?if($this->getCheckout()->getStepData('payment', 'complete')):?>
		<li><h4 class="complete">Payment<span class="separator">|</span><a href="#payment" onclick="checkout.accordion.openSection('opc-payment');return false;">Edit</a></h4>	
			<div class="content">
			    <?=$this->getPaymentHtml()?>
			</div>
		</li>
<?else:?>
		<li>
			<h4>Payment</h4>
        </li>
<?endif?>
	</ol>
</div>


