<div id="checkout-review-load" class="default-box">
    <?=$this->getChildHtml('info')?>
</div>

<div class="content">
	<div class="form-buttons">
		<p class="left">Forgot an item in the cart? <a href="javascript:checkout.back();">Edit your cart</a></p>
		<p><button class="form-button" onclick="review.save();"><span>Place Order</span></button></p>
</div>

<script type="text/javascript">
    var review = new Review();
</script>
