<div id="checkout-review-load" class="default-box">
    <?=$this->getChildHtml('info')?>
</div>

<div class="content form-buttons">
	<p class="left"><?=__('Forgot an item in the cart?')?> <a href="<?=$this->getUrl('checkout/cart', array('_secure'=>false))?>"><?=__('Edit your cart')?></a></p>
	<p>
	    <span id="review-please-wait" style="display:none;" class="opc-please-wait">
	        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; Submitting order information... &nbsp; 
	    </span>
	    <span id="review-buttons-container">
			<input type="image" src="<?=$this->getSkinUrl('images/btn_place_order.gif')?>" onclick="review.save();" value="<?=__('Place Order')?>"/>
		</span>
	</p>
</div>

<script type="text/javascript">
    var review = new Review('<?=$this->getUrl('checkout/onepage/saveOrder')?>', '<?=$this->getUrl('checkout/onepage/success', array('_secure'=>false))?>');
</script>
