<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="checkout-shipping-method-load" class="default-box" style="padding:10px;">
    <?=$this->getChildHtml('available')?>
</div>
  	
<div class="form-buttons">
    <span id="shipping-method-buttons-container">
		<a href="#" onclick="checkout.back()" class="back left"><?=__('Back')?></a>
        <button class="form-button right" onclick="shippingMethod.save()"><span><?=__('Continue')?></span></button>
	    <span id="shipping-method-please-wait" style="display:none;" class="opc-please-wait">
	        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; Loading next step... &nbsp; 
	    </span>
    </span>
</div>
<script type="text/javascript">
    var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?=$this->getUrl('checkout/onepage/saveShippingMethod')?>");
</script>
