<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Framework\View\Element\Template */

/** @var $this \Magento\Framework\View\Element\Template */
$_gridPopupBlock = $this->getChildBlock('catalog.product.group.grid.popup.container')->getChildBlock('grid');
$_gridPopupBlock->setRowClickCallback('function(){}');
/** @var $_helper \Magento\Core\Helper\Data */
$_helper = $this->helper('Magento\Core\Helper\Data');
?>
<div id="grouped-product-container" data-mage-init='{"groupedProduct":{"gridPopup":"window.<?php echo $_gridPopupBlock->getJsObjectName() ?>"}}'>
    <div class="no-products-message">
        <?php echo __('There are no grouped products.')?>
    </div>
    <?php echo $this->getChildHtml('list'); ?>
    <div data-role="add-product-dialog" class="no-display">
        <?php echo $this->getChildBlock('catalog.product.group.grid.popup.container')->getChildHtml('grid');?>
    </div>
    <button type="button" data-role="add-product">Add Products to Group</button>
</div>
