<div class="catalog-nav">
    <h2 id="title-department"><span>Shop by department</span></h2>
    <div class="category-nav">
        <ul class="categories">
            <?foreach ($categories as $_item):?>
                <li><a href="<?=$baseUrl?>/catalog/category/view/id/<?=$_item['id']?>/" <?if (!empty($currentCategoryId) && $_item['id']==$currentCategoryId):?> class="active"<?endif?>><?=$_item['title']?></a></li>
            <?endforeach?>
        </ul>
    </div>
    <?if(!empty($manufacturers)):?>
    <h2 id="title-brand"><span>Shop by brand</span></h2>
        <select name="manufacturer" onchange="productBy('manufacturer',this)">
            <option>Choose brand</option>
        <?foreach($manufacturers as $_item):?>
            <option value="<?=$_item['value']?>"><?=$_item['label']?></option>
        <?endforeach?>
        </select>
    <?endif?>
    <?if(!empty($types)):?>
    <h2 id="title-shoe-type"><span>Shop by shoe type</span></h2>
        <select name="type" onchange="productBy('type',this)">
            <option>Choose shoe type</option>
        <?foreach($types as $_item):?>
            <option value="<?=$_item['value']?>"><?=$_item['label']?></option>
        <?endforeach?>
        </select>
    <?endif?>
</div>
<script type="text/javascript">
function productBy(attribute, element){
    location.href = '<?=$baseUrl?>/catalog/search/by/attr/'+attribute+'/value/'+element.value+'/';
}
</script>