<?php
/**
 * {license_notice}
 *
 * @category    tests
 * @package     static
 * @subpackage  Integrity
 * @copyright   {copyright}
 * @license     {license_link}
 */

return array(
    // Blocks
    'Block/Admin',
    'Block/Backup',
    'Block/Cache',
    'Block/Checkout',
    'Block/Cms',
    'Block/Customer',
    'Block/Dashboard',
    'Block/Denied',
    'Block/Html',
    'Block/Media',
    'Block/Messages',
    'Block/Newsletter',
    'Block/Page',
    'Block/Promo',
    'Block/Rating',
    'Block/Report',
    'Block/Review',
    'Block/Sales',
    'Block/Shipping',
    'Block/Sitemap',
    'Block/System',
    'Block/Tax',
    'Block/Template',
    'Block/Text',
    'Block/Urlrewrite',
    'Block/Widget',
    'Block/Tax',

    // Controllers
    'Controller/Checkout',
    'Controller/Cms',
    'Controller/Customer',
    'Controller/Newsletter',
    'Controller/Promo',
    'Controller/Report',
    'Controller/System',
    'Controller/Tax',
    'Controller/Customer',
    'Controller/Promo',
    'Controller/Report',
    'Controller/Urlrewrite',

    // Helpers
    'Helper/Addresses',
    'Helper/Dashboard',
    'Helper/Media',
    'Helper/Data',
    'Helper/Js',
    'Helper/Sales',

    // Models
    'Model/Customer',
    'Model/Email',
    'Model/Giftmessage',
    'Model/LayoutUpdate',
    'Model/Newsletter',
    'Model/Observer',
    'Model/Report',
    'Model/Sales',
    'Model/Search',
    'Model/Session',

    // Views
    'view/adminhtml/admin',
    'view/adminhtml/backup',
    'view/adminhtml/cms',
    'view/adminhtml/customer',
    'view/adminhtml/dashboard',
    'view/adminhtml/email',
    'view/adminhtml/images',
    'view/adminhtml/media',
    'view/adminhtml/newsletter',
    'view/adminhtml/page',
    'view/adminhtml/promo',
    'view/adminhtml/rating',
    'view/adminhtml/report',
    'view/adminhtml/review',
    'view/adminhtml/sales',
    'view/adminhtml/store',
    'view/adminhtml/system',
    'view/adminhtml/tax',
    'view/adminhtml/urlrewrite',
    'view/adminhtml/widget',
    'view/adminhtml/validation-rules.js',
    'view/adminhtml/variables.js',

    // Layouts
    'layout/adminhtml_cache',
    'layout/adminhtml_cms',
    'layout/adminhtml_customer',
    'layout/adminhtml_dashboard',
    'layout/adminhtml_denied',
    'layout/adminhtml_newsletter',
    'layout/adminhtml_noroute',
    'layout/adminhtml_promo',
    'layout/adminhtml_rating',
    'layout/adminhtml_report',
    'layout/sales',
    'layout/adminhtml_system',
    'layout/adminhtml_tax',
    'layout/adminhtml_urlrewrite',
    'layout/default',
    'layout/editor',
    'layout/empty',
    'layout/formkey',
    'layout/newsletter',
    'layout/overlay_popup',
    'layout/popup',
    'layout/preview',
    'layout/report_sales',
    'layout/systemPreview',
);