<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/default/iphone/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="breadcrumbs">
    <ul>
        <li class="home">
            <a href="#" onclick="javascript:history.back(1); return false;" title="Continue Shopping">Back</a>
        </li>
        <li><strong>Log In</strong></li>
    </ul>
</div>
<div class="login-box">
    <div class="registered-users">
        <h1><?php echo $this->__('Log In') ?></h1>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <h2><?php echo $this->__('Registered Users') ?></h2>
            <ul class="form-list">
                <li>
                    <label for="email" class="required"><?php echo $this->__('Email Address') ?></label>
                    <input type="email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                </li>
                <li>
                    <label for="pass" class="required"><?php echo $this->__('Password') ?></label>
                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?><a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot your password?') ?></a>
            <div class="login-button">
                <input type="submit" value="<?php echo $this->__('Log In') ?>" />
            </div>
            <?php if (Mage::helper('Mage_Checkout_Helper_Data')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout" />
            <?php endif; ?>
        </form>
    </div>
    <div class="new-users">
        <div class="new-users-box">
            <h2><?php echo $this->__('New Customers') ?></h2>
            <a href="<?php echo Mage::helper('Mage_Persistent_Helper_Data')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>"><input type="submit" value="<?php echo $this->__('Create an Account') ?>" /></a>
            <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
        </div>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
