<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->getChildHtml()): ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Gift Options') ?></h4>
    </div>
    <fieldset>
        <?php echo $this->getChildHtml() ?>
    </fieldset>
</div>
<?php endif ?>
