<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Backend_Block_Template */?>

<div class="themes-assigned"><?php echo $this->getChildHtml('assigned.theme.list') ?></div>
<div class="themes-unassigned"><?php echo $this->getChildHtml('unassigned.theme.list') ?></div>

<script type="text/javascript">
    <?php if ($this->getTabId()): ?>
        (function ($) {
            $('a[name="<?php echo $this->getTabId() ?>"]').on("click", function(event) {
                $('.infinite_scroll').infinite_scroll('setLocked', true)
            })
        })(jQuery);
    <?php endif; ?>
</script>
