<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme_Selector_StoreView */?>


<div class="fade" id="store-view-window">
    <div class="popup">
        <header class="popup-header">
            <strong class="popup-title"><?php echo $this->__('Select store views to make your changes live:') ?></strong>
        </header>
        <div class="popup-content">
            <form method="post" action="">
                <ul class="websites">
                    <?php foreach ($this->getWebsiteStructure() as $website => $stores): ?>
                    <li class="website">
                        <h3 class="website-title"><?php echo $website; ?></h3>
                        <ul class="stores">
                            <?php foreach ($stores as $store => $storeViews): ?>
                            <li class="store">
                                <h4 class="store-title"><?php echo $store; ?></h4>
                                <ul class="storeviews">
                                    <?php foreach ($storeViews as $storeView => $id): ?>
                                    <li class="storeview">
                                        <input type="hidden" name="storeviews[<?php echo $id; ?>]" value="0" />
                                        <label for="storeview_<?php echo $id ?>">
                                            <input type="checkbox" id="storeview_<?php echo $id ?>" class="storeview-selector-control" name="storeviews[<?php echo $id; ?>]" value="1" />
                                            <span class="storeview-name"><?php echo $storeView; ?></span>
                                        </label>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </form>
        </div>
        <footer class="popup-footer">
            <div class="actions">
                <?php echo $this->getAssignNextButtonHtml(); ?>
                <span class="action-close" title="<?php echo $this->__('Close Popup') ?>"><?php echo $this->__('Close') ?></span>
            </div>
        </footer>
        <span class="action-close-popup" data-hide="popup" title="<?php echo $this->__('Close Popup') ?>"><?php echo $this->__('Close Popup') ?></span>
    </div>
</div>

<script type="text/javascript">
    (function($) {
        $(document).ready(function() {
            $('body').themeAssign(<?php echo $this->getOptionsJson(); ?>);
        });
    })(jQuery);
</script>
