<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme_Selector_StoreView */?>

<div id="dialog-message-assign-ssm" title="<?php echo $this->__('Assign theme to your live store-view:') ?>">
    <div class="dialog-message-assign-ssm messages"></div>
    <p class="confirm_message"></p>
</div>

<div id="dialog-message-assign" title="<?php echo $this->__('Select Storeviews to make your changes live:') ?>">
    <div class="dialog-message-assign messages"></div>
    <p class="confirm_message"></p>
    <form method="post" action="">
        <ul class="websites">
            <?php foreach ($this->getWebsiteStructure() as $website => $stores): ?>
            <li class="website">
                <h3 class="website-title"><?php echo $website; ?></h3>
                <ul class="stores">
                    <?php foreach ($stores as $store => $storeViews): ?>
                    <li class="store">
                        <h4 class="store-title"><?php echo $store; ?></h4>
                        <ul class="storeviews">
                            <?php foreach ($storeViews as $storeView => $id): ?>
                            <li class="storeview">
                                <input type="hidden" name="storeviews[<?php echo $id; ?>]" value="0" />
                                <label for="storeview_<?php echo $id ?>">
                                    <input type="checkbox" id="storeview_<?php echo $id ?>" class="storeview-selector-control" name="storeviews[<?php echo $id; ?>]" value="1" />
                                    <span class="storeview-name"><?php echo $storeView; ?></span>
                                </label>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php endforeach; ?>
        </ul>
    </form>
</div>

<!--
<div id="dialog-message-save" title="<?php echo $this->__('Save changes:') ?>">
    <div class="messages"></div>
    <p class="confirm_message"></p>
</div>
-->

<div id="dialog-message-confirm">
    <div class="dialog-message-confirm messages"></div>
    <p class="confirm_message"></p>
</div>

<script type="text/javascript">
    (function ($) {
        $( document ).ready(function() {
            $('body').themeAssign(<?php echo $this->getOptionsJson(); ?>);
            var options = {
                autoOpen:    false,
                modal:       true,
                width:       570,
                dialogClass: 'vde-dialog'
            };
            $('#dialog-message-assign-ssm').dialog(options);
            $('#dialog-message-assign').dialog(options);
            /*$('#dialog-message-save').dialog({
                autoOpen:    false,
                modal:       true,
                width:       570,
                dialogClass: 'vde-dialog'
            });*/
            $('#dialog-message-confirm').dialog({
                autoOpen:    false,
                modal:       true,
                width:       570,
                dialogClass: 'vde-dialog'
            });
        });
    })(jQuery);
</script>
