<script type="text/javascript">
function runProfile(popup)
{
    var url = '<?=$this->getUrl('*/*/run', array('id'=>$this->getProfileId()))?>';
    if (!popup) {
        $('run_iframe').style.display = 'block';
        $('run_iframe').src = url;
    } else {
        window.open(url);
    }
}
</script>
<h4><?=$this->__('Please make sure that your changes were saved before running the profile.')?></h4>
<?=$this->getRunButtonHtml()?><br/>
<iframe id="run_iframe" src="<?=$this->getJsUrl()?>blank.html" frameborder=0 style="display:none; width:100%; height:400px;"></iframe>