<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->getHeader()?></h3></td>
            <td class="a-right">
                <?if($this->getTagId()):?>
                    <?=$this->getDeleteButtonHtml()?>
                <?endif;?>
                <?=$this->getSaveButtonHtml()?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="tag_edit_form">
    <?=$this->getChildHtml('tagForm');?>
</form>
<script type="text/javascript" language="javascript">
    var tagForm = new varienForm('tag_edit_form');

    function tagDelete(){
        if(confirm('<?=__('Are you sure?')?>')){
            location.href = '<?=$this->getDeleteUrl()?>'
        }
    }
</script>