<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Magento_Review_Block_Product_View_Other */ ?>
<?php $_product = $this->getProduct(); ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $_product->getProductUrl() ?>"><small>&laquo; </small><?php echo __('Back to Main Product Info') ?></a></p>
</div>
