<div class="step-body">
    <?if(!empty($addresses)):?>
    <div class="note-box" style="display:block;">
        <p class="option">
            Select a billing address from your address book or enter a &nbsp;
            <a href="javascript:void(null);" onclick="">new address</a>
        </p>
        <select id="sel-billing" name="" style="width:100%;">
        <?foreach($addresses as $_addressId=>$_address):?>
            <option value="<?=$_addressId?>"><?=$_address->getFirstname()?> <?=$_address->getLastname()?> [<?=$_address->getPostcode()?>, <?=$_address->getCity()?>, <?=$_address->getStreet()?>] [<?=$_address->getTelephone()?>]</option>
        <?endforeach?>
        </select>
    </div>
    <?endif?>
    <div id="co-billing-db" class="default-box" style="display:block;">
        <p class="option">Enter billing information</p>
        <form id="co-billing-form">
            <fieldset>
            <ul class="input-list">
                <li>
                    <div class="input-left">
                        <label for="billing:firstname">First Name <span class="required">*</span></label><br/>
                        <input type="text" id="billing:firstname" title="First Name" class="required-entry input-text"/>
                    </div>
                    <div class="input-right">
                        <label for="billing:lastname">Last Name <span class="required">*</span></label><br/>
                        <input type="text" id="billing:lastname" title="Last Name" class="required-entry input-text"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <div class="input-left">
                        <label for="billing:company">Company</label><br/>
                        <input type="text" id="billing:company" title="Company" class="input-text"/>
                    </div>
                    <div class="input-right">
                        <label for="billing:email_address">Email <span class="required">*</span></label><br/>
                        <input type="text" id="billing:email_address" title="Email Address" class="validate-email required-entry input-text"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <label for="billing:street_address">Street Address <span class="required">*</span></label><br/>
                    <input type="text" title="Street Address" id="billing:street_address" class="required-entry input-text"/>
                </li>
                <li>
                    <input type="text" title="Street Address 2" id="billing:street_address2" class="input-text"/>
                </li>
                <li>
                    <label for="billing:city">City <span class="required">*</span></label><br/>
                    <input type="text" title="City" class="required-entry input-text" id="billing:city"/>
                </li>
                <li>
                    <div class="input-left">
                        <label for="billing:zone_id">State / Province <span class="required">*</span></label><br/>
                        <select title="State/Province" id="billing:zone_id" class="validate-select required-entry">
                            <option value="1">LA</option>
                        </select></div>
                    <div class="input-right">
                        <label for="billing:postcode">Zip <span class="required">*</span></label><br/>
                        <input type="text" title="ZIP/Post Code" id="billing:postcode" class="validate-zip required-entry input-text"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <label for="billing:country_id">Country <span class="required">*</span></label><br/>
                    <select id="billing:country_id" title="Country">
                        <option value="223" selected="selected">USA</option>
                    </select>
                </li>
                <li>
                    <div class="input-left">
                        <label for="billing:telephone">Telephone <span class="required">*</span></label><br/>
                        <input type="text" name="billing:telephone" value="" title="Telephone" class="required-entry validate-phoneStrict input-text" id="billing:telephone"/></div>
                    <div class="input-right">
                        <label for="billing:fax">Fax</label><br/>
                        <input type="text" name="billing:fax" value="" title="Fax" class="validate-fax input-text" id="billing:fax"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
            </ul>
        </fieldset>
        </form>
    </div>
    <div id="co-billing-nb2" class="note-box" style="padding-top:0;">
        <input type="checkbox" id="ship2bill" /><label for="ship2bill"><strong>Ship to this address</strong></label>
        <p class="a-right"><span class="required">* Required Fields</span></p>
        <input type="button" onclick="checkout.back();" value="Back" class="input-button float-left"/>
        <input type="button" onclick="checkout.setBilling();" class="input-button float-right" value="Continue"/>
        <div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    val_billing = new Validation('co-billing-form');
</script>
