<div class="page-checkout-left">
    <h3>Checkout Process</h3>
    <ol>
        <li id="cp-billing">
            <h4 id="cp-billing-h4">Billing Address</h4>
            <div id="cp-billing-sb" class="step-body"></div>
        </li>
        <li id="cp-shipping">
            <h4 id="cp-shipping-h4">Shipping Address</h4>
            <div id="cp-shipping-sb" class="step-body"></div>
        </li>
        <li id="cp-payment">
            <h4 id="cp-payment-h4">Payment Info</h4>
            <div id="cp-payment-sb" class="step-body"></div>
        </li>
    </ol>
</div>