<script type="text/javascript">
var Review = Class.create();
Review.prototype = {
    initialize: function(form){
        this.form = form;
        this.onSave = this.continue.bindAsEventListener(this);
    },
    
    save: function(){
        var validator = new Validation(this.form);
        if (validator.validate()) {
            var request = new Ajax.Request(
                '<?=$baseUrl?>checkout/onepage/saveOrder/',
                {
                    method:'post',
                    onSuccess: this.onSave,
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    continue: function(){
        checkout.setBilling();
    }
}
</script>

<div class="step-body" id="co-review-cont">
    <div class="default-box">
        <?=$status?>
    </div>
    
    <div class="note-box">
        <input type="button" onclick="checkout.back();" value="Back" class="input-button float-left"/>
        <input type="button" onclick="review.save();" class="input-button float-right" value="Submit Order"/>
        <div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var review = new Review('co-billing-form');
</script>
