<div class="page-checkout-left">
    <h3>Checkout Status</h3>
    <ol>
    <?if($billing):?>
        <li class="complete">
            <h4>Billing Address</h4>
            <div class="step-body">
            <?=$billing['firstname']?> <?=$billing['lastname']?>
            </div>
            <a href="#" onclick="checkout.accordion.openSection('billing');return false;">edit</a>
        </li>
    <?else:?>
        <li class="complete">
            <h4>Billing Address</h4>
        </li>
    <?endif?>
        <li<?if($payment):?> class="complete"<?endif?>>
            <h4>Payment Method</h4>
        </li>
        <li<?if($shipping):?> class="complete"<?endif?>>
            <h4>Shipping Address</h4>
        </li>
        <li<?if($shipping_method):?> class="complete"<?endif?>>
            <h4>Shipping Method</h4>
        </li>
    </ol>
</div>