<div class="page-checkout-left">
    <h3>Checkout Status</h3>
    <ol>
    <?if($checkout->getCompletedBilling()):?>
        <li class="complete">
            <h4>Billing Address</h4>
            <div class="step-body">
                <?=$billing['firstname']?> <?=$billing['lastname']?><br>
                <?if (!empty($billing['company'])):?><?=$billing['company']?><?endif?><br>
                <?=nl2br($billing['street'])?><br>
                <?=$billing['city']?>, <?=$billing['region_id']?> <?=$billing['postcode']?>
                <br><a href="#billing" onclick="checkout.accordion.openSection('billing');return false;">EDIT</a>
            </div>
        </li>
    <?else:?>
        <li>
            <h4>Billing Address</h4>
        </li>
    <?endif?>
    <?if($checkout->getCompletedPayment()):?>
        <li class="complete">
            <h4>Payment Method</h4>
            <div class="step-body">
                <?=$payment?>
                <br><a href="#payment" onclick="checkout.accordion.openSection('payment');return false;">EDIT</a>
            </div>
        </li>
    <?else:?>
        <li>
            <h4>Payment Method</h4>
        </li>
    <?endif?>
    <?if($checkout->getCompletedShipping()):?>
        <li class="complete">
            <h4>Shipping Address</h4>
            <div class="step-body">
                <?=$shipping['firstname']?> <?=$shipping['lastname']?><br>
                <?if (!empty($shipping['company'])):?><?=$shipping['company']?><?endif?><br>
                <?=nl2br($shipping['street'])?><br>
                <?=$shipping['city']?>, <?=$shipping['region_id']?> <?=$shipping['postcode']?>
                <br><a href="#shipping" onclick="checkout.accordion.openSection('shipping');return false;">EDIT</a>
            </div>
        </li>
    <?else:?>
        <li>
            <h4>Shipping Address</h4>
        </li>
    <?endif?>
    <?if($checkout->getCompletedShippingMethod()):?>
        <li class="complete">
            <h4>Shipping Method</h4>
            <div class="step-body">
                <?=print_r($shippingMethod,1)?>
                <br><a href="#shipping_method" onclick="checkout.accordion.openSection('shipping_method');return false;">EDIT</a>
            </div>
        </li>
    <?else:?>
        <li>
            <h4>Shipping Method</h4>
        </li>
    <?endif?>
    </ol>
</div>