<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */

/**
 * @see \Magento\GiftCardAccount\Block\Account\Redeem
 */
?>
<?php if ($this->canRedeem()): ?>
    <div class="block block-balance-giftcard">
        <div class="block-title"><strong><?php echo __('Redeem Gift Card'); ?></strong></div>
        <div class="block-content">
          <p><?php echo __('Have a gift card? <a href="%1">Click here</a> to redeem it.', $this->getUrl('magento_giftcardaccount/customer')); ?></p>
        </div>
    </div>
<?php endif; ?>
