<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Container */ ?>
<?php echo $this->getChildHtml('design_editor_toolbar'); ?>
<?php echo $this->getChildHtml('theme.selector.storeview'); ?>
<iframe name="vde_container_frame" id="vde_container_frame" class="vde_container_frame" src="<?php echo $this->getFrameUrl(); ?>"></iframe>
<?php echo $this->getChildHtml('design_editor_tools'); ?>
<script type="text/javascript">
    (function ($) {
        $('body').vdeThemeInit({
            isPhysicalTheme: '<?php echo (int)$this->getTheme()->getType() == Mage_Core_Model_Theme::TYPE_PHYSICAL ?>',
            createVirtualThemeUrl: '<?php echo $this->getVirtualThemeCreationUrl() ?>'
        });
    })(jQuery);
</script>
