<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Tools */ ?>
<section class="vde-tools">
    <header class="vde-tools-header">
        <div class="vde-tools-header-inner">
            <button class="action-close" title="<?php echo $this->__('Close Panel'); ?>">
                <span><?php echo $this->__('Close Panel'); ?></span>
            </button>
        </div>
    </header>
    <div class="vde-tools-content">
        <div class="vde-tools-content-inner">
            <div class="vde-tools-handler-container"></div>
            <?php echo join('', $this->getTabs()) ?>
        </div>
    </div>
    <footer class="vde-tools-footer">
        <div class="vde-tools-footer-inner">
            <div class="vde-tools-tabs">
                <ul class="vde-tab-controls">
                    <li class="item item-design">
                        <a href="#vde-tab-quick-styles" data-toggle="tab" title="<?php echo $this->__('Quick Styles'); ?>">
                            <span><?php echo $this->__('Quick Styles'); ?></span>
                        </a>
                    </li>
                    <li class="item item-block">
                        <a href="#vde-tab-block" data-toggle="tab" title="<?php echo $this->__('Block'); ?>">
                            <span><?php echo $this->__('Block'); ?></span>
                        </a>
                    </li>
                    <li class="item item-settings">
                        <a href="#vde-tab-settings" data-toggle="tab" title="<?php echo $this->__('Settings'); ?>">
                            <span><?php echo $this->__('Settings'); ?></span>
                        </a>
                    </li>
                    <li class="item item-code">
                        <a href="#vde-tab-code" data-toggle="tab" title="<?php echo $this->__('Code'); ?>">
                            <span><?php echo $this->__('Code'); ?></span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="vde-tools-button">
                <div id="vde-translate-menu" class="text-menu-hide">
                    <div id="vde-translate-text" class="text-menu-div">
                        <span id="vde-translate-text-img" class="text-menu-text-off"></span>
                        <span class="text-menu-label"><?php echo $this->__('Page Text'); ?></span>
                    </div>

                    <div id="vde-translate-script" class="text-menu-div">
                        <span id="vde-translate-script-img" class="text-menu-script-off"></span>
                        <span class="text-menu-label"><?php echo $this->__('Variable Text'); ?></span>
                    </div>

                    <div id="vde-translate-alt" class="text-menu-div">
                        <span id="vde-translate-alt-img" class="text-menu-alt-off"></span>
                        <span class="text-menu-label"><?php echo $this->__('Alternative Text'); ?></span>
                    </div>
                </div>
                <ul class="vde-tab-controls">
                    <li id="vde-translate-edit" class="item-text-edit text-edit-text-off">
                        <a id="vde-translate" title="<?php echo $this->__('Edit Text'); ?>">
                            <span><?php echo $this->__('Edit Text'); ?></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
</section>

<script type="text/javascript">
(function($) {
    'use strict';

    $('.vde-tools').toolsPanel();
    $(
        '#vde-tab-quick-styles .element-font-picker select,' +
        '#vde-tab-quick-styles .element-color-picker input,' +
        //'#vde-tab-quick-styles .element-image-uploader' +   // Uploaders are special case
        '#vde-tab-quick-styles .element-background .element-checkbox'
    ).quickStyleElement({
        saveQuickStylesUrl: '<?php echo $this->getSaveUrl(); ?>'
    });

    $('[class^="action-"][href="#vde-tab-custom"]').on('click.activateCustomCodeTab', function() {
        $('.vde-tab-controls a[href="#vde-tab-custom"]').trigger('click');
    });

    $('.action-edit[href="#vde-tab-custom"]').on('click.focusOnCustomCodeTextarea', function() {
        $('#custom_code').focus();
    });

    $.widget("mage.translateInlineToggle", {
        options: {
            frameUrl: null,
            refreshVdeCanvas: false,
            disableInlineTranslation: false
        },

        _create: function() {
            this.element.on('click', $.proxy(this.options.onClick, this));
        },

        /**
         * This method displays the translate menu and defaults the currently selected mode.
         */
        toggleTranslationInline: function() {
            parent.jQuery('#vde-translate-menu').toggleClass('text-menu-hide');
            parent.jQuery('#vde-translate-menu').toggleClass('text-menu-show');
        },

        /**
         * This method will only enable editing for the translation mode specified.
         *
         * If this is the first time a mode is selected, the contents of the iframe will be wrapped with the appropriate
         * attributes where applicable (translate-mode, either 'text', 'script' or 'alt').
         *
         * @param mode
         */
        toggleTranslationMode: function(mode) {
            // Hide menu.
            parent.jQuery('#vde-translate-menu').toggleClass('text-menu-hide');
            parent.jQuery('#vde-translate-menu').toggleClass('text-menu-show');

            // Change menu to reflect what was selected, so will display correctly when displayed again.
            this._updateMenu(mode);

            // Refresh iframe with new url
            this._refresh(mode);
        },

        _refresh: function (mode) {
            var url = this.options.frameUrl;
            if (this.options.disableInlineTranslation) {
                parent.jQuery('#vde_container_frame').attr('translation-mode', '');
            }
            else {
                url = url + "translation_mode/" + mode;
                parent.jQuery('#vde_container_frame').attr('translation-mode', mode);
            }

            // If this is the first time selecting a mode, refresh the iframe to wrap all the applicable content.
            // Or, if disabling inline translation, refresh minus the translation mode on the url.
            if (this.options.refreshVdeCanvas || this.options.disableInlineTranslation)
                parent.jQuery('#vde_container_frame').get(0).contentWindow.location.href = url;

            /**
             * Since the url is being modified to support inline translation, the window is not reloaded since it
             * is using the url from the cache to display.
             */
        },

        /**
         *
         * @param mode
         * @private
         */
        _updateMenu: function (mode) {
            this.options.disableInlineTranslation = false;

            var TEXT_MENU_BACKGROUND_ON = 'text-menu-background-on';
            var TEXT_MENU_BACKGROUND_OFF = 'text-menu-background-off';

            var disable_one = "text";
            var disable_two = "script";

            if (mode === 'text') {
                disable_one = "script";
                disable_two = "alt";
            }
            else if (mode === 'script') {
                disable_one = "text";
                disable_two = "alt";
            }

            // Check to see if turning off (selecting the already highlighted option).
            if (parent.jQuery('#vde-translate-' + mode).hasClass(TEXT_MENU_BACKGROUND_ON)) {
                parent.jQuery('#vde-translate-' + mode).removeClass(TEXT_MENU_BACKGROUND_ON).addClass(TEXT_MENU_BACKGROUND_OFF);
                parent.jQuery('#vde-translate-' + mode + '-img').removeClass('text-menu-' + mode + '-on').addClass('text-menu-' + mode + '-off');

                // Update toolbar button.
                parent.jQuery('#vde-translate-edit').removeClass('text-edit-' + mode + '-on').addClass('text-edit-' + mode + '-off');

                // Refresh iframe minus the translation mode on the url.
                this.options.disableInlineTranslation = true;
            }
            else {
                // Enable selected option
                parent.jQuery('#vde-translate-' + mode).removeClass(TEXT_MENU_BACKGROUND_OFF).addClass(TEXT_MENU_BACKGROUND_ON);
                parent.jQuery('#vde-translate-' + mode + '-img').removeClass('text-menu-' + mode + '-off').addClass('text-menu-' + mode + '-on');

                // Update toolbar button.
                parent.jQuery('#vde-translate-edit').addClass('text-edit-' + mode + '-on');

                // Disable other two options.
                parent.jQuery('#vde-translate-' + disable_one + '').removeClass(TEXT_MENU_BACKGROUND_ON).addClass(TEXT_MENU_BACKGROUND_OFF);
                parent.jQuery('#vde-translate-' + disable_one + '-img').removeClass('text-menu-' + disable_one + '-on').addClass('text-menu-'+ disable_one + '-off');
                // Update toolbar button.
                parent.jQuery('#vde-translate-edit').removeClass('text-edit-' + disable_one + '-on');

                parent.jQuery('#vde-translate-' + disable_two + '').removeClass(TEXT_MENU_BACKGROUND_ON).addClass(TEXT_MENU_BACKGROUND_OFF);
                parent.jQuery('#vde-translate-' + disable_two + '-img').removeClass('text-menu-' + disable_two + '-on').addClass('text-menu-' + disable_two + '-off');
                // Update toolbar button.
                parent.jQuery('#vde-translate-edit').removeClass('text-edit-' + disable_two + '-on');
            }
        }
    });

})(window.jQuery);
</script>
