<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var \Magento\Pricing\Render\Amount $this */ ?>

<?php if ($this->getDisplayLabel()): ?>
<span class="price-label"><?php echo $this->getDisplayLabel(); ?></span>
<?php endif; ?>
<span class="price" id="<?php echo $this->getPriceId() ?>">
    <?php echo $this->convertAndFormatCurrency($this->getAmount(), (bool) $this->getIncludeContainer()) ?>
</span>
