<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this Mage_Core_Block_Template */
?>
<div id="<?php echo $this->getNameInLayout() ?>" style="display:none">
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li>Attribute set comprising all selected configurable attributes need to be in order to save generated variations.</li>
            </ul>
        </li>
        <li class="error-msg" style="display:none">
        </li>
    </ul>
    <div id="affected-attribute-set-current-container">
        <label>
            <input type="radio" name="affected-attribute-set" value="current" checked="checked" />
            <?php echo $this->helper('Mage_Catalog_Helper_Data')->__('Add configurable attributes to the current set ("%s")', $this->getLayout()->getBlock('product_edit')->getAttributeSetName())?>
        </label>
    </div>
    <div id="affected-attribute-set-new-container">
        <label>
            <input type="radio" name="affected-attribute-set" value="new" />
            <?php echo $this->helper('Mage_Catalog_Helper_Data')->__('Add configurable attributes to the new set based on current')?>
        </label>
    </div>
    <div id="affected-attribute-set-new-name-container">
        <label for="affected-attribute-set-new-name">
            <?php echo $this->helper('Mage_Catalog_Helper_Data')->__('New attribute set name')?>
        </label>
        <input id="affected-attribute-set-new-name" name="new-attribute-set-name" type="text" class="input-text required-entry" />
    </div>
</div>
