<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
    <script type="text/javascript">
        (function($) {
            "use strict";
            /**
             * Declaration of resources needed for defined components
             */
            $.mage.component({
                sticky: [
                    '<?php echo $this->getViewFileUrl('mage/sticky.js') ?>'
                ],
                bundleOption: [
                    '<?php echo $this->getViewFileUrl('Magento_Bundle::bundle.js') ?>'
                ],
                slide: [
                    '<?php echo $this->getViewFileUrl('Magento_Bundle::js/slide.js') ?>'
                ]
            });
        })(jQuery);
    </script>
<?php echo $this->getChildHtml() ?>