<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<div class="nav-bar">
<!-- menu start -->
<?php
    $menu = $this->getMenuModel();
    echo $this->getMenuLevelHtml($menu[0]->getChildren()); ?>
<!-- menu end -->

    <a id="page-help-link" href="<?php echo Mage::helper('Mage_Backend_Helper_Data')->getPageHelpUrl() ?>"><?php echo $this->__('Get help for this page') ?></a>
    <script type="text/javascript">$('page-help-link').target = 'magento_page_help'</script>

</div>
