<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Social_Facebook_Block_Box */
$actions = $this->getAllActions();
?>
<?php if (!empty($actions)): ?>
    <?php foreach ($actions as $action): ?>
        <?php if ($action['box'] == 0 || count($this->getFriendBox($action['action'])) < 1): ?>
            <?php continue; ?>
        <?php endif; ?>
        <div class="facebookFriendsBox">
            <div>
                <?php if ($this->getCountOfUsers($action['action']) == 1): ?>
                    <?php echo __('1 user %1s this product', $this->escapeHtml($action['action'])); ?>
                <?php else: ?>
                    <?php echo __('%1 users %2 this product', $this->getCountOfUsers($action['action']), $this->escapeHtml($action['action'])) ?>
                <?php endif; ?>
            </div>
            <div style="clear:both;"></div>
            <?php foreach($this->getFriendBox($action['action']) as $facebookId => $facebookName): ?>
                <div class="facebookUser">
                    <img border="0" src="http://graph.facebook.com/<?php echo $facebookId?>/picture" alt="<?php $this->escapeHtml($facebookName)?>" title="<?php $this->escapeHtml($facebookName)?>">
                    <span title="<?php echo $this->escapeHtml($facebookName)?>"><?php echo $this->escapeHtml($facebookName)?></span>
                </div>
            <?php endforeach; ?>
            <div style="clear:both;"></div>
        </div>
        <div class="facebookZeroBox"></div>
    <?php endforeach; ?>
    <div style="clear:both;"></div>
<?php endif; ?>
