<?
/**
 * Sopping cart template
 * 
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="page-head-alt">
    <h2><?=__('Shopping Cart')?></h2>
</div>
<form action="<?=$this->getUrl('checkout/cart/updatePost')?>" method="post">
<table cellspacing="0" id="shoping-cart-table" class="data-table box-table shopping-cart">
    <col width="75"/>
    <col/>
    <col width="80"/>
    <col width="140"/>
    <col width="120"/>
    <col width="140"/>
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th><?=__('Product Name')?></th>
            <th class="a-center"><?=__('Remove')?></th>
<?if($this->isWishlistActive()):?> 
            <th class="a-center"><?=__('Wishlist')?></th>
<?endif?>
            <th class="a-right"><?=__('Unit Price')?></th>

            <th class="a-center"><?=__('Qty')?></th>
            <th class="a-right"><?=__('Subtotal')?></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
<?if($this->isWishlistActive()):?> 
            <td>&nbsp;</td>
<?endif?>
            <td>&nbsp;</td>
            <td class="a-center"><button class="form-button-alt"><span><?=__('Update')?></span></button></td>
            <td></td>
        </tr>
    </tfoot>
    <tbody>
<?foreach($this->getItems() as $_item):?>
        <tr>
            <td>
                <a href="#"><img src="<?=$_item->getProduct()->getSmallImageUrl()?><?//=$this->getSkinUrl('images/ph_product_thumb.jpg')?>" alt="" width="75"/>
            </td>
            <td class="attributes-col">
                <a href="<?=$this->getUrl('catalog/product/view/id/'.$_item->getProductId())?>"><strong><?=$_item->getName()?></strong></a>
                <?=$_item->getDescription();?>                
            </td>
            <td class="a-center"><input type="checkbox" value="1" name="cart[<?=$_item->getId()?>][remove]"/><!--<a href="#"><img src="<?=$this->getSkinUrl('images/btn_trash.gif')?>" alt="Remove item"/>--></td>
<?if($this->isWishlistActive()):?>            
            <td class="a-center"><input type="checkbox" value="1" name="cart[<?=$_item->getId()?>][wishlist]"/></td>
<?endif?>
            <td class="a-right"><?=$_item->getPrice()?></td>
            <td class="a-center"><input name="cart[<?=$_item->getId()?>][qty]" value="<?=$_item->getQty()?>" size="2" class="input-text qty"/></td>
            <td class="a-right"><?=$_item->getRowTotal()?></td>
        </tr>
<?endforeach?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('shoping-cart-table')</script>
</form>

<div class="shopping-cart-collaterals">
    <div class="col2-set">
        <div class="col-1">
            <?=$this->getChildHtml('coupon')?>
        </div>

        <div class="col-2">
            <?=$this->getChildHtml('shipping')?>
        </div>
    </div>
</div>

<div class="shopping-cart-totals">
    <table cellspacing="0">
        <tbody>
<?$l=sizeof($this->getTotals()); $i=0; foreach($this->getTotals() as $total): $i++?>
    <?if(!$total->getArea()):?>
            <tr class="<?=$i==$l?'last':''?>">
                <td style="<?=$total->getStyle()?>"><?=$total->getTitle()?></td>
                <td style="<?=$total->getStyle()?>"><?=$total->getValue()?></td>
            </tr>
    <?endif?>
<?endforeach?>
        </tbody>
        <tfoot>
<?foreach($this->getTotals() as $total):?>
    <?if($total->getArea()=='footer'):?>
            <tr>
                <td><strong><?=$total->getTitle()?></strong></td>
                <td class="nowrap"><strong><?=$total->getValue()?></strong></td>
            </tr>
    <?endif?>
<?endforeach?>
        </tfoot>
    </table>
    <ul class="checkout-types">
        <li><a href="<?=$this->getCheckoutUrl()?>"><img src="<?=$this->getSkinUrl('images/btn_proceed_to_checkout.png')?>" alt="Proceed to Checkout"/></a></li>
        <li><a href="<?=$this->getMultiShippingUrl()?>"><big>Checkout with Multiple Addresses</big></a></li>

        <li><a href="<?=$this->getPaypalUrl()?>"><img src="<?=$this->getSkinUrl('images/btn_paypal_checkout.gif')?>" alt="Paypal Checkout"/></a></li>
        <li><a href="<?=$this->getGoogleUrl()?>"><img src="<?=$this->getSkinUrl('images/btn_google_checkout.gif')?>" alt="Google Checkout"/></a></li>
    </ul>
</div>
<div class="clear"></div>
