<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="page-head-alt button-level">
    <h3><?=__('Shopping Cart')?></h3>
    <a href="<?=$this->getCheckoutUrl()?>"><img src="<?=$this->getSkinUrl('images/btn_proceed_to_checkout.gif')?>" alt="<?=__('Proceed to Checkout')?>"/></a>
</div>
<?=$this->getMessagesBlock()->getGroupedHtml()?>
<form action="<?=$this->getUrl('checkout/cart/updatePost')?>" method="post">
<table cellspacing="0" id="shopping-cart-table" class="data-table box-table shopping-cart">
    <col width="75"/>
    <col/>
    <col width="80"/>
    <col width="140"/>
    <col width="120"/>
    <col width="140"/>
    <thead>
        <tr>
            <th>&nbsp;</th>
            <th><?=__('Product Name')?></th>
            <th class="a-center"><?=__('Remove')?></th>
            <?if($this->isWishlistActive()):?>
            <th class="a-center"><?=__('Move to Wishlist')?></th>
            <?endif?>
            <th class="a-right"><?=__('Unit Price')?></th>
            <th class="a-center"><?=__('Qty')?></th>
            <th class="a-right"><?=__('Subtotal')?></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="<?if($this->isWishlistActive()):?>7<?else:?>6<?endif?>" class="a-right">
                <button class="form-button-alt" type="submit"><span><?=__('Update Shopping Cart')?></span></button>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <?foreach($this->getItems() as $_item):?>
        <tr <?if(!$this->getItemIsInStock($_item)):?> class="out-of-stock"<?endif;?>>
            <td>
                <a href="<?=$this->getItemUrl($_item)?>"><img src="<?=$this->getItemImageUrl($_item)?>" alt="<?=$this->htmlEscape($this->getItemName($_item))?>" width="75"/></a>
            </td>
            <td class="attributes-col">
                <a href="<?=$this->getItemUrl($_item)?>"><strong><?=$this->getItemName($_item)?></strong></a>
                <?=$this->getItemDescription($_item)?>
            </td>
            <td class="a-center"><a href="<?=$this->getItemDeleteUrl($_item)?>"><img src="<?=$this->getSkinUrl('images/btn_trash.gif')?>" width="16" height="16" alt="Remove item"/></td>
            <?if($this->isWishlistActive()):?>
            <td class="a-center"><input type="checkbox" value="1" name="cart[<?=$_item->getId()?>][wishlist]"/></td>
            <?endif?>
            <td class="a-right"><?=$_item->getPrice()?></td>
            <td class="a-center"><input name="cart[<?=$_item->getId()?>][qty]" value="<?=$this->getItemQty($_item)?>" size="2" class="input-text qty"/></td>
            <td class="a-right"><?=$_item->getRowTotal()?></td>
        </tr>
    <?endforeach?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('shopping-cart-table')</script>
</form>

<div class="shopping-cart-collaterals">
    <div class="col2-set">
        <?=$this->getChildHtml('crosssell')?>
        <div class="col-2">
            <?=$this->getChildHtml('coupon')?>
            <?=$this->getChildHtml('shipping')?>
        </div>
    </div>
</div>

<div class="shopping-cart-totals">
    <table cellspacing="0" id="shoping-cart-totals-table">
        <tbody>
        <?foreach($this->getTotals() as $total):?>
            <?if(!$total->getArea()):?>
            <tr>
                <td style="<?=$total->getStyle()?>"><?=$total->getTitle()?></td>
                <td style="<?=$total->getStyle()?>"><?=$total->getValue()?></td>
            </tr>
            <?endif?>
        <?endforeach?>
        </tbody>
        <tfoot>
        <?foreach($this->getTotals() as $total):?>
            <?if($total->getArea()=='footer'):?>
            <tr>
                <td><strong><?=$total->getTitle()?></strong></td>
                <td class="nowrap"><strong><?=$total->getValue()?></strong></td>
            </tr>
            <?endif?>
        <?endforeach?>
        </tfoot>
    </table>
    <script type="text/javascript">decorateTable('shoping-cart-totals-table')</script>
    <ul class="checkout-types">
        <li><a href="<?=$this->getCheckoutUrl()?>"><img src="<?=$this->getSkinUrl('images/btn_proceed_to_checkout.gif')?>" alt="<?=__('Proceed to Checkout')?>"/></a></li>
        <?if($this->getCanDoMultishipping()):?>
        <li><a href="<?=$this->getMultiShippingUrl()?>"><big><?=__('Checkout with Multiple Addresses')?></big></a></li>
        <?endif;?>
        <?/*<li><a href="<?=$this->getUrl('paypal/express/shortcut')?>"><img src="<?=$this->getSkinUrl('images/btn_paypal_checkout.gif')?>" alt="<?=__('Paypal Checkout')?>"/></a></li>*/?>
        <?/*<li><a href="<?=$this->getGoogleUrl()?>"><img src="<?=$this->getSkinUrl('images/btn_google_checkout.gif')?>" alt="<?=__('Google Checkout')?>"/></a></li>*/?>
    </ul>
</div>
<div class="clear"></div>
