<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Catalog_Block_Product_Configurable_AttributeSelector */
?>
<script type="text/javascript">
(function($) {
    'use strict';
    $(function() {
        var self = $('#attribute-selector')
            .bind('ajaxSend ajaxComplete', function(e) {
                e.stopPropagation();
            })
            .autocomplete({
                minLength: 0,
                appendTo: '#config_super_product',
                source: function(request, response) {
                    $.ajax({
                        url: '<?php echo $this->getSuggestUrl()?>',
                        data: {label_part: request.term},
                        dataType: 'json',
                        context: self
                    })
                    .success(function(data) {
                        var list = [];
                        $.each(data, function(id, item) {
                            if (!$('#configurable_attribute_' + id ).length) {
                                list.push(item);
                            }
                        });
                        response(list);
                    });
                },
                focus: function(event, ui) {
                    return false;
                },
                select: function(event, ui) {
                    var attribute = ui.item;
                    if (attribute.id) {
                        $('#attribute-template').tmpl({attribute: attribute}).appendTo('#attributes-container');
                    }

                    $(this).val('');
                    return false;
                }
            })
            .on('click focus', function () {
                $(this).autocomplete('search');
            });
    });
})(jQuery);
</script>
