
replace  into `core_config_data`(`scope`,`scope_id`,`path`,`value`,`old_value`,`inherit`) values 
('default',0,'general/currency/base','USD','',0),
('default',0,'general/currency/allow','CAD,RUB,UAH,USD','USD,CAD,UAH,RUB',0),
('default',0,'general/currency/default','USD','',0),
('default',0,'general/local/language','en','',0),
('default',0,'system/filesystem/layout','{{app_dir}}/design/frontend/default/layout/default','',0),
('default',0,'system/filesystem/template','{{app_dir}}/design/frontend/default/template/default','',0),
('default',0,'system/filesystem/translate','{{app_dir}}/design/frontend/default/translate','',0),
('default',0,'system/filesystem/base','{{root_dir}}','',0),
('default',0,'system/filesystem/media','{{root_dir}}/media','',0),
('default',0,'web/unsecure/protocol','{{protocol}}','{{protocol}}',0),
('default',0,'web/unsecure/host','{{host}}','',0),
('default',0,'web/unsecure/port','{{port}}','{{port}}',0),
('default',0,'web/unsecure/base_path','{{base_path}}','',0),
('default',0,'web/secure/protocol','{{protocol}}','https',0),
('default',0,'web/secure/host','{{host}}','',0),
('default',0,'web/secure/port','{{port}}','444',0),
('default',0,'web/secure/base_path','{{base_path}}','',0),
('default',0,'web/url/media','{{base_path}}media/','',0),
('default',0,'web/url/js','{{base_path}}js/','',0),
('default',0,'system/filesystem/etc','{{app_dir}}/etc','{{app_dir}}/etc/',0),
('default',0,'system/filesystem/code','{{app_dir}}/code','{{app_dir}}/code/',0),
('default',0,'system/filesystem/upload','{{root_dir}}/media/upload','{{root_dir}}/media/upload/',0),
('default',0,'system/filesystem/var','{{var_dir}}','',0),
('default',0,'system/filesystem/session','{{var_dir}}/session','{{var_dir}}/session/',0),
('default',0,'system/filesystem/cache_config','{{var_dir}}/cache/config','{{var_dir}}/cache/config/',0),
('default',0,'system/filesystem/cache_layout','{{var_dir}}/cache/layout','{{var_dir}}/cache/layout/',0),
('default',0,'web/default/front','catalog','',0),
('default',0,'web/default/no_route','core/index/noRoute','',0),
('default',0,'general/country/default','223','US',0),
('default',0,'general/country/allow','38,220,223','US,CA,UA',0),
('default',0,'advanced/datashare/customer','1','',1),
('default',0,'advanced/datashare/customer_address','1','',1),
('default',0,'advanced/datashare/quote','1','',1),
('default',0,'advanced/datashare/quote_address','1','',1),
('default',0,'advanced/datashare/order','1','',1),
('default',0,'advanced/datashare/order_address','1','',1),
('default',0,'advanced/datashare/order_payment','1','',1),
('default',0,'advanced/datashare/wishlist','1','',1),
('default',0,'general/local/date_format_short','%m/%d/%y','',0),
('default',0,'general/local/date_format_medium','%a, %b %e %Y','',0),
('default',0,'general/local/date_format_long','%A, %B %e %Y','',0),
('default',0,'general/local/datetime_format_short','%m/%d/%y [%I:%M %p]','',0),
('default',0,'general/local/datetime_format_medium','%a, %b %e %Y [%I:%M %p]','',0),
('default',0,'general/local/datetime_format_long','%A, %B %e %Y [%I:%M %p]','',0),
('default',0,'payment/authorizenet/test','1','0',0),
('default',0,'system/filesystem/design','{{app_dir}}/design','',0),
('default',0,'system/filesystem/skin','{{base_dir}}/skin','',0),
('default',0,'design/package/name','default','',0),
('default',0,'design/package/area','frontend','',0),
('default',0,'design/package/theme','default','',0),
('default',0,'web/url/skin','{{base_path}}skin/','',0),
('default',0,'web/url/upload','{{base_path}}media/upload/','',0),
('default',0,'catalog/category/root_id','158','47',0),
('default',0,'payment/authorizenet/active','1','0',0),
('default',0,'payment/authorizenet/cgi_url','https://secure.authorize.net:433/gateway/transact.dll','',0),
('default',0,'payment/authorizenet/login','irub782','',0),
('default',0,'payment/authorizenet/order_status','','',0),
('default',0,'payment/authorizenet/trans_key','','',0),
('default',0,'payment/paypal/active','1','0',0),
('default',0,'payment/paypal/order_status','','',0),
('default',0,'payment/verisign/active','1','0',0),
('default',0,'payment/verisign/order_status','','',0),
('default',0,'carriers/tablerate/active','0','',0),
('default',0,'carriers/tablerate/title','','',0),
('default',0,'carriers/pickup/active','0','',0),
('default',0,'carriers/pickup/title','','',0),
('default',0,'carriers/ups/active','1','0',0),
('default',0,'carriers/ups/gateway_url','http://www.ups.com:80/using/services/rave/qcostcgi.cgi','',0),
('default',0,'carriers/ups/title','United Parcel Service','',0),
('default',0,'carriers/ups/container','CP','',0),
('default',0,'carriers/ups/dest_type','RES','',0),
('default',0,'carriers/ups/handling','0','',0),
('default',0,'carriers/ups/pickup','CC','',0),
('default',0,'carriers/usps/active','0','',0),
('default',0,'carriers/usps/gateway_url','','',0),
('default',0,'carriers/usps/title','','',0),
('default',0,'carriers/fedex/active','0','',0),
('default',0,'carriers/fedex/gateway_url','','',0),
('default',0,'carriers/fedex/title','','',0),
('default',0,'carriers/dhl/active','0','',0),
('default',0,'carriers/dhl/gateway_url','','',0),
('default',0,'carriers/dhl/title','','',0),
('default',0,'shipping/origin/country_id','223','',0),
('default',0,'shipping/origin/region_id','1','',0),
('default',0,'shipping/origin/postcode','90034','',0),
('default',0,'shipping/option/checkout_multiple','0','',0),
('default',0,'wishlist/general/active','1','',0),
('default',0,'payment/authorizenet/email_customer','0','',0),
('default',0,'payment/authorizenet/merchant_email','moshe@varien.com','',0),
('default',0,'payment/ccsave/model','payment/ccsave','',0),
('default',0,'payment/checkmo/model','payment/checkmo','',0),
('default',0,'payment/purchaseorder/model','payment/purchaseorder','',0),
('default',0,'payment/authorizenet/model','paygate/authorizenet','',0),
('default',0,'payment/paypal/model','paygate/paypal','',0),
('default',0,'payment/verisign/model','paygate/verisign','',0),
('default',0,'payment/ccsave/active','1','',0),
('default',0,'payment/checkmo/active','1','',0),
('default',0,'payment/purchaseorder/active','1','',0);


replace  into `core_config_field`(`level`,`path`,`frontend_label`,`frontend_type`,`frontend_class`,`frontend_model`,`backend_model`,`source_model`,`sort_order`,`show_in_default`,`show_in_website`,`show_in_store`,`module_name`) values 
(3,'advanced/datashare/customer','Customer','text','','','','',1,1,1,1,''),
(3,'advanced/datashare/customer_address','Customer Address','text','','','','',2,1,1,1,''),
(3,'advanced/datashare/order','Order','text','','','','',3,1,1,1,''),
(3,'advanced/datashare/order_address','Order Address','text','','','','',4,1,1,1,''),
(3,'advanced/datashare/order_payment','Order Payment','text','','','','',5,1,1,1,''),
(3,'advanced/datashare/quote','Shopping cart / Quote','text','','','','',6,1,1,1,''),
(3,'advanced/datashare/quote_address','Shopping cart / Quote Address','text','','','','',7,1,1,1,''),
(3,'advanced/datashare/wishlist','Wishlist','text','','','','',8,1,1,1,''),
(3,'general/country/allow','Allow countries','multiselect','','','','adminhtml/system_config_source_country',2,1,1,1,''),
(3,'general/country/default','Default country','select','','','','adminhtml/system_config_source_country',1,1,1,1,''),
(3,'general/currency/allow','Allow currencies','multiselect','','','','adminhtml/system_config_source_currency',3,1,1,1,''),
(3,'general/currency/base','Base currency','select','','','','adminhtml/system_config_source_currency',1,1,1,1,''),
(3,'general/currency/default','Default currency','select','','','','adminhtml/system_config_source_currency',2,1,1,1,''),
(3,'general/local/date_format_short','Date format (short)','select','','','','adminhtml/system_config_source_date_short',6,1,1,1,''),
(3,'general/local/date_format_medium','Date format (medium)','text','','','','',5,1,1,1,''),
(3,'general/local/language','Language','select','','','','adminhtml/system_config_source_language',7,1,1,1,''),
(3,'system/filesystem/base','Base directory','text','','','','',1,1,1,1,''),
(3,'system/filesystem/cache_config','Config cache directory','text','','','','',2,1,1,1,''),
(3,'system/filesystem/cache_layout','Layout cache directory','text','','','','',3,1,1,1,''),
(3,'system/filesystem/code','Code pools root directory','text','','','','',4,1,1,1,''),
(3,'system/filesystem/etc','Configuration directory','text','','','','',5,1,1,1,''),
(3,'system/filesystem/layout','Layout files directory','text','','','','',6,1,1,1,''),
(3,'system/filesystem/media','Media files directory','text','','','','',7,1,1,1,''),
(3,'system/filesystem/session','Session files directory','text','','','','',8,1,1,1,''),
(3,'system/filesystem/skin','Skin directory','text','','','','',9,1,1,1,''),
(3,'system/filesystem/template','Template directory','text','','','','',10,1,1,1,''),
(3,'system/filesystem/translate','Translactions directory','text','','','','',11,1,1,1,''),
(3,'system/filesystem/upload','Upload directory','text','','','','',12,1,1,1,''),
(3,'system/filesystem/var','Var (temporary files) directory','text','','','','',13,1,1,1,''),
(3,'web/default/front','Default web url','text','','','','',1,1,1,1,''),
(3,'web/default/no_route','Default no-route url','text','','','','',2,1,1,1,''),
(3,'web/secure/base_path','Base url','text','','','','',4,1,1,1,''),
(3,'web/secure/host','Host','text','','','','',2,1,1,1,''),
(3,'web/secure/port','Port','text','','','','',3,1,1,1,''),
(3,'web/secure/protocol','Protocol','text','','','','',1,1,1,1,''),
(3,'web/unsecure/base_path','Base url','text','','','','',4,1,1,1,''),
(3,'web/unsecure/host','Host','text','','','','',2,1,1,1,''),
(3,'web/unsecure/port','Port','text','','','','',3,1,1,1,''),
(3,'web/unsecure/protocol','Protocol','text','','','','',1,1,1,1,''),
(3,'web/url/js','Js base url','text','','','','',1,1,1,1,''),
(3,'web/url/media','Media base url','text','','','','',2,1,1,1,''),
(3,'web/url/skin','Skin base url','text','','','','',3,1,1,1,''),
(1,'general','General','text','','','','',1,1,1,1,''),
(1,'web','Web','text','','','','',20,1,1,1,''),
(1,'system','System','text','','','','',80,1,1,1,''),
(1,'advanced','Advanced','text','','','','',100,1,1,1,''),
(2,'web/default','Default URLs','text','','','','',1,1,1,1,''),
(2,'web/secure','Secure','text','','','','',3,1,1,1,''),
(2,'web/unsecure','Unsecure','text','','','','',2,1,1,1,''),
(2,'web/url','URLs','text','','','','',1,1,1,1,''),
(2,'system/filesystem','Filesystem','text','','','','',1,1,1,1,''),
(2,'general/currency','Currency options','text','','','','',2,1,1,1,''),
(2,'general/local','Local options','text','','','','',3,1,1,1,''),
(2,'general/country','Countries options','text','','','','',1,1,1,1,''),
(2,'advanced/datashare','Datasharing','text','','','','',1,1,1,1,''),
(3,'general/local/date_format_long','Date format (long)','text','','','','',4,1,1,1,''),
(3,'general/local/datetime_format_short','Date format (short with time)','text','','','','',3,1,1,1,''),
(3,'general/local/datetime_format_medium','Date format (medium with time)','text','','','','',2,1,1,1,''),
(3,'general/local/datetime_format_long','Date format (long with time)','text','','','','',1,1,1,1,''),
(1,'payment','Payment gateways','text','','','','',70,1,1,1,''),
(2,'payment/authorizenet','Authorize.net','text','','','','',10,1,1,1,''),
(3,'payment/authorizenet/test','Test mode','select','','','','adminhtml/system_config_source_yesno',5,1,1,1,''),
(1,'catalog','Catalog','text','','','','',40,1,1,1,''),
(2,'catalog/category','Category','text','','','','',1,1,1,1,''),
(3,'catalog/category/root_id','Root category','select','','','adminhtml/system_config_backend_category','adminhtml/system_config_source_category',1,1,1,1,''),
(1,'email','Email','text','','','','',60,1,1,1,''),
(2,'email/templates','System Templates','text','','','','',1,1,1,1,''),
(3,'email/templates/subscription_confirm','Confirmation subscription message','select','','','','adminhtml/system_config_source_email_template',1,1,1,1,''),
(3,'email/templates/wishlist_share_message','Wishlist sharing message','select','','','','adminhtml/system_config_source_email_template',2,1,1,1,''),
(3,'web/url/upload','Upload files URL','text','','','','',4,1,1,1,''),
(3,'payment/authorizenet/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'payment/authorizenet/order_status','New order status','select','','','','',4,1,1,1,''),
(3,'payment/authorizenet/login','Login','text','','','','',2,1,1,1,''),
(3,'payment/authorizenet/trans_key','Transaction key','password','','','','',3,1,1,1,''),
(2,'payment/paypal','Paypal','text','','','','',20,1,1,1,''),
(3,'payment/paypal/order_status','New order status','select','','','','',2,1,1,1,''),
(3,'payment/paypal/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(2,'payment/verisign','Verisign','text','','','','',30,1,1,1,''),
(3,'payment/verisign/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'payment/verisign/order_status','New order status','select','','','','',2,1,1,1,''),
(1,'shipping','Shipping','text','','','','',50,1,1,1,''),
(2,'shipping/origin','Origin','text','','','','',1,1,1,1,''),
(3,'shipping/origin/country_id','Country','select','','','','adminhtml/system_config_source_country',1,1,1,1,''),
(3,'shipping/origin/region_id','Region','text','','','','',2,1,1,1,''),
(3,'shipping/origin/postcode','Postcode','text','','','','',3,1,1,1,''),
(2,'carriers/ups','UPS','text','','','','',10,1,1,1,''),
(2,'carriers/usps','USPS','text','','','','',11,1,1,1,''),
(2,'carriers/fedex','FedEx','text','','','','',12,1,1,1,''),
(2,'carriers/dhl','DHL','text','','','','',13,1,1,1,''),
(3,'carriers/ups/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/usps/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/fedex/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/dhl/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(2,'carriers/tablerate','Table rates','text','','','','',2,1,1,1,''),
(3,'carriers/tablerate/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(1,'carriers','Shipping Carriers','text','','','','',51,1,1,1,''),
(2,'shipping/option','Options','text','','','','',2,1,1,1,''),
(3,'shipping/option/checkout_multiple','Allow Shipping to multiple addresses','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(1,'wishlist','Wishlist','text','','','','',45,1,1,1,''),
(2,'wishlist/general','General Options','text','','','','',1,1,1,1,''),
(3,'wishlist/general/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/ups/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/usps/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/fedex/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/dhl/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/tablerate/title','Title','text','','','','',2,1,1,1,''),
(2,'carriers/pickup','Pick Up','text','','','','',3,1,1,1,''),
(3,'carriers/pickup/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/pickup/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/ups/pickup','Pickup method','select','','','','usa/shipping_carrier_ups_source_pickup',6,1,1,1,''),
(3,'carriers/ups/container','Container','select','','','','usa/shipping_carrier_ups_source_container',3,1,1,1,''),
(3,'carriers/ups/dest_type','Destination type','select','','','','usa/shipping_carrier_ups_source_destType',4,1,1,1,''),
(3,'carriers/ups/handling','Handling fee','text','','','','',5,1,1,1,''),
(3,'payment/authorizenet/email_customer','Email customer','select','','','','adminhtml/system_config_source_yesno',10,1,1,1,''),
(3,'payment/authorizenet/merchant_email','Merchant\'s email','text','','','','',11,1,1,1,''),
(2,'payment/checkmo','Check / Money order','text','','','','',5,1,1,1,''),
(3,'payment/checkmo/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'payment/checkmo/order_status','New order status','select','','','','',2,1,1,1,''),
(2,'payment/purchaseorder','Purchase order','text','','','','',7,1,1,1,''),
(3,'payment/purchaseorder/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'payment/purchaseorder/order_status','New order status','select','','','','',2,1,1,1,''),
(2,'payment/ccsave','Saved CC','text','','','','',1,1,1,1,''),
(3,'payment/ccsave/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'payment/ccsave/order_status','New order status','select','','','','',2,1,1,1,''),
(2,'catalog/frontend','Frontend','text','','','','',2,1,1,1,''),
(3,'catalog/frontend/product_per_page','Product per page','text','required-entry validate-number','','','',1,1,1,1,'');

