<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <title><?=__('Magento Admin')?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
    <link rel="shortcut icon" href="<?=$baseUrl?>favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="<?=$baseUrl?>skins/admin/styles.css" type="text/css"/>
    <link rel="stylesheet" type="text/css" media="all" href="<?=$baseUrl?>js/extjs/resources/css/ext-all.css"/>
    <link rel="stylesheet" type="text/css" media="all" href="<?=$baseUrl?>js/extjs/resources/css/ytheme-default.css" id="theme_stylesheet"/>
</head>
<body>
    <div id="loading">
        <div class="loading-indicator"><?=__('Magento Office Loading...')?></div>
    </div>
    <script type="text/javascript" language="Javascript">
        var BASE_URL = '<?=$baseUrl?>admin/';
        var SKIN_URL = '<?=$baseUrl?>skins/admin/';
    </script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/extjs/adapter/yui/yui-utilities.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/extjs/adapter/yui/ext-yui-adapter.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/extjs/ext-all.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/Ext.InfoPanel.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/filteredViewGrid.js" ></script>
    
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/cookies.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/mage.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/Wizard.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/FlexObject.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/FlexUpload.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/search.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/form.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/form/jsonform.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/form/FileField.js" ></script>
    
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/form/VTypes.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/tasks.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/menu.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/blocks.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/config.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/media.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/itemcard.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/panel.js" ></script>
    
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/panel/form.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/panel/view.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/panel/related.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/panel/images.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/panel/categories.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/core/panel/address.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/acl/PermissionPanel.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/acl/menu.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/product/productselect.js" ></script>
    
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/product.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/product/attributes.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/product/link.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/category/attributes.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/category.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/medialibrary.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/category/createform.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/tree.js" ></script>
    
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/catalog/menu.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/customer.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/customer/menu.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/sales.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/sales/menu.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseUrl?>js/magenta/sales/rules.js" ></script>    
    <script type="text/javascript" language="Javascript">
        Ext.BLANK_IMAGE_URL = '<?=$baseUrl?>js/extjs/resources/images/default/s.gif';
        Ext.UpdateManager.defaults.loadScripts = false;
        Ext.UpdateManager.defaults.disableCaching = true;
    </script>
</body>
</html>