<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="error-msg">
    <h4>Warning: Your Magento folder does not have sufficient write permissions.</h4>
</div>

<p>
    If you wish to proceed downloading Magento packages online, please set all Magento folders to
have writable permission for the web server user (example: apache) or set up FTP Connection on the 
Magento Connect Manager <a href="<?php echo $this->url('settings')?>">Settings</a> tab.
</p>
