<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this Mage_Adminhtml_Block_Catalog_Product_Attribute_New_Product_Created */
?>
<script type="text/javascript">
(function ($) {
    var data = <?php echo $this->getAttributesBlockJson() ?>;
    var set = data.set || { id:$('#attribute_set_id').val()};
    $('#create_new_attribute').dialog('close');
    $('#product-edit-form').trigger('changeAttributeSet', set);
    if (data.tab == '_variation') {
        $('#configurable-attributes-container').trigger('add', data.attribute);
    }
})(window.parent.jQuery);
</script>
<div class="a-center">
    <?php echo $this->getCloseButtonHtml() ?>
</div>