<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this \Magento\Catalog\Block\Product\Compare\Sidebar */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<div class="block block-list block-compare">
    <div class="block-title">
        <strong><span><?php echo __('Compare Products') ?>
            <?php if($_helper->getItemCount() > 0): ?>
                <small><?php echo __('(%1)', $_helper->getItemCount()) ?></small>
                <?php endif; ?>
        </span></strong>
    </div>
    <div class="block-content">
        <?php if($_helper->getItemCount() > 0): ?>
        <ol id="compare-items">
            <?php foreach($_items as $_index => $_item): ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo __('Remove This Item') ?>" class="btn-remove"><?php echo __('Remove This Item') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
            </li>
            <?php endforeach; ?>
        </ol>
        <div class="actions">
            <a id='compare-clear-all' href="<?php echo $_helper->getClearListUrl() ?>" ><?php echo __('Clear All') ?></a>
            <button type="button" title="<?php echo __('Compare') ?>" class="button" data-mage-init="{popupWindow: {windowURL:'<?php echo $_helper->getListUrl() ?>',windowName:'compare',centerScreen:1,resizable:1,scrollbars:1,width:820,height:600}}"><span><span><?php echo __('Compare') ?></span></span></button>
        </div>
        <script type="text/javascript">
            (function($) {
                head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/compare.js') ?>", function() {
                    $('#compare-items').compareItems({
                        removeConfirmMessage: '<?php echo __('Are you sure you want to remove this item from the compared products?') ?>',
                        removeSelector: '#compare-items a.btn-remove',
                        clearAllConfirmMessage: '<?php echo __('Are you sure you want to remove all products from your comparison?') ?>',
                        clearAllSelector: '#compare-clear-all'
                    });
                });
            })(jQuery);
        </script>
        <?php else: ?>
        <p class="empty"><?php echo __('You have no items to compare.') ?></p>
        <?php endif; ?>
    </div>
</div>
