insert  into `core_config_field` (`level`,`path`,`frontend_label`,`frontend_type`,`frontend_class`,`frontend_model`,`backend_model`,`source_model`,`sort_order`,`show_in_default`,`show_in_website`,`show_in_store`,`module_name`) values 
(1,'carriers','Shipping Carriers','text','','','','',51,1,1,1,''),
(2,'carriers/dhl','DHL','text','','','','',13,0,0,0,''),
(3,'carriers/dhl/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/dhl/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/dhl/gateway_url','Gateway URL','text','','','','',2,1,1,1,''),
(3,'carriers/dhl/sort_order','Sort order','text',100),
(3,'carriers/dhl/id','Access ID','text','','','','',5,1,1,1,''),
(3,'carriers/dhl/password','Password','text','','','','',6,1,1,1,''),
(3,'carriers/dhl/account','Account number','text','','','','',7,1,1,1,''),
(3,'carriers/dhl/shipping_key','Shipping key','text','','','','',8,1,1,1,''),
(3,'carriers/dhl/shipment_type','Shipment type','select','','','','usa/shipping_carrier_dhl_source_shipmenttype',9,1,1,1,''), 
(3,'carriers/dhl/handling','Handling fee','text','','','','',10,1,1,1,''),
(3,'carriers/dhl/cutoff_cost','Minimum order amount for free shipping','text','','','','',21,1,1,1,''),
(3,'carriers/dhl/free_method','Free method','select','free-method','','','usa/shipping_carrier_dhl_source_freemethod',20,1,1,1,''),
(3,'carriers/dhl/allowed_methods','Allowed methods','multiselect','','','','usa/shipping_carrier_dhl_source_method',17,1,1,1,''),
(2,'carriers/fedex','FedEx','text','','','','',12,1,1,1,''),
(3,'carriers/fedex/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/fedex/gateway_url','Gateway URL','text','','','','',2,1,1,1,''),
(3,'carriers/fedex/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/fedex/packaging','Packaging','select','','','','usa/shipping_carrier_fedex_source_packaging',3,1,1,1,''),
(3,'carriers/fedex/account','Account ID','text','','','','',3,1,1,1,''),
(3,'carriers/fedex/packaging','Packaging','select','','','','usa/shipping_carrier_fedex_source_packaging',4,1,1,1,''),
(3,'carriers/fedex/dropoff','Dropoff','select','','','','usa/shipping_carrier_fedex_source_dropoff',5,1,1,1,''),
(3,'carriers/fedex/handling','Handling fee','text','','','','',6,1,1,1,''),
(3,'carriers/fedex/allowed_methods','Allowed methods','multiselect','','','','usa/shipping_carrier_fedex_source_method',17,1,1,1,''),
(3,'carriers/fedex/free_method','Free method','select','free-method','','','usa/shipping_carrier_fedex_source_freemethod',20,1,1,1,''),
(3,'carriers/fedex/cutoff_cost','Minimum order amount for free shipping','text','','','','',21,1,1,1,''),
(3,'carriers/fedex/sort_order','Sort order','text',100),
(2,'carriers/ups','UPS','text','','','','',10,1,1,1,''),
(3,'carriers/ups/gateway_url','Gateway URL','text','','','','',2,1,1,1,''),
(3,'carriers/ups/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/ups/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/ups/pickup','Pickup method','select','','','','usa/shipping_carrier_ups_source_pickup',6,1,1,1,''),
(3,'carriers/ups/container','Container','select','','','','usa/shipping_carrier_ups_source_container',3,1,1,1,''),
(3,'carriers/ups/dest_type','Destination type','select','','','','usa/shipping_carrier_ups_source_destType',4,1,1,1,''),
(3,'carriers/ups/handling','Handling fee','text','','','','',5,1,1,1,''),
(3,'carriers/ups/sort_order','Sort order','text',100),
(3,'carriers/ups/cutoff_cost','Minimum order amount for free shipping','text','','','','',21,1,1,1,''),
(3,'carriers/ups/free_method','Free method','select','free-method','','','usa/shipping_carrier_ups_source_freemethod',20,1,1,1,''),
(3,'carriers/ups/allowed_methods','Allowed methods','multiselect','','','','usa/shipping_carrier_ups_source_method',17,1,1,1,''),
(2,'carriers/usps','USPS','text','','','','',11,1,1,1,''),
(3,'carriers/usps/gateway_url','Gateway URL','text','','','','',2,1,1,1,''),
(3,'carriers/usps/active','Enabled','select','','','','adminhtml/system_config_source_yesno',1,1,1,1,''),
(3,'carriers/usps/title','Title','text','','','','',2,1,1,1,''),
(3,'carriers/usps/sort_order','Sort order','text',100),
(3,'carriers/usps/userid','User ID','text','','','','',3,1,1,1,''),
(3,'carriers/usps/container','Container','select','','','','usa/shipping_carrier_usps_source_container',4,1,1,1,''),
(3,'carriers/usps/size','Size','select','','','','usa/shipping_carrier_usps_source_size',5,1,1,1,''),
(3,'carriers/usps/machinable','Machinable','select','','','','usa/shipping_carrier_usps_source_machinable',6,1,1,1,''),
(3,'carriers/usps/handling','Handling fee','text','','','','',7,1,1,1,''),
(3,'carriers/usps/cutoff_cost','Minimum order amount for free shipping','text','','','','',21,1,1,1,''),
(3,'carriers/usps/free_method','Free method','select','free-method','','','usa/shipping_carrier_usps_source_freemethod',20,1,1,1,''),
(3,'carriers/usps/allowed_methods','Allowed methods','multiselect','','','','usa/shipping_carrier_usps_source_method',17,1,1,1,'')
ON DUPLICATE KEY UPDATE field_id=field_id;

update `core_config_field` set `show_in_default` = '0', `show_in_website` = '0', `show_in_store` = '0' where `path` = 'carriers/dhl';

--

insert  into `core_config_data`(`scope`,`scope_id`,`path`,`value`,`old_value`,`inherit`) values 
('default',0,'carriers/ups/active','1','0',0),
('default',0,'carriers/ups/gateway_url','http://www.ups.com:80/using/services/rave/qcostcgi.cgi','',0),
('default',0,'carriers/ups/title','United Parcel Service','',0),
('default',0,'carriers/ups/container','CP','',0),
('default',0,'carriers/ups/dest_type','RES','',0),
('default',0,'carriers/ups/handling','0','',0),
('default',0,'carriers/ups/pickup','CC','',0),
('default',0,'carriers/fedex/active','1','0',0),
('default',0,'carriers/fedex/gateway_url','https://gateway.fedex.com/GatewayDC','',0),
('default',0,'carriers/fedex/title','Federal Express','',0),
('default',0,'carriers/fedex/packaging','YOURPACKAGING','',0),
('default',0,'carriers/fedex/dropoff','REGULARPICKUP','',0),
('default',0,'carriers/fedex/account','329311708','',0),
('default',0,'carriers/usps/userid','652VARIE8323','',0),
('default',0,'carriers/usps/active','1','0',0),
('default',0,'carriers/usps/gateway_url','http://Production.ShippingAPIs.com/ShippingAPI.dll','',0),
('default',0,'carriers/usps/title','United States Postal Service','',0),
('default',0,'carriers/usps/container','VARIABLE','',0),
('default',0,'carriers/usps/size','REGULAR','',0),
('default',0,'carriers/usps/machinable','false','',0),
('default',0,'carriers/dhl/id','MAGENTO','',0), 
('default',0,'carriers/dhl/password','123123','',0),
('default',0,'carriers/dhl/account','MAGENTO','',0),
('default',0,'carriers/dhl/shipping_key','','',0),
('default',0,'carriers/dhl/shipment_type','P','',0),
('default',0,'carriers/dhl/active','0,'0',0),
('default',0,'carriers/dhl/gateway_url','https://eCommerce.airborne.com/ApiLandingTest.asp','',0),
('default',0,'carriers/dhl/title','DHL','',0),
('default',0,'carriers/dhl/free_method','','',0),
('default',0,'carriers/dhl/cutoff_cost','','',0),
('default',0,'carriers/fedex/free_method','','',0),
('default',0,'carriers/fedex/cutoff_cost','','',0),
('default',0,'carriers/ups/free_method','','',0),
('default',0,'carriers/ups/cutoff_cost','','',0),
('default',0,'carriers/usps/free_method','','',0),
('default',0,'carriers/usps/cutoff_cost','','',0),
('default',0,'carriers/ups/model','usa/shipping_carrier_ups','',0),
('default',0,'carriers/dhl/model','usa/shipping_carrier_dhl','',0),
('default',0,'carriers/usps/model','usa/shipping_carrier_usps','',0),
('default',0,'carriers/fedex/model','usa/shipping_carrier_fedex','',0),
('default',0,'carriers/dhl/allowed_methods','E,N,S,G','',0),
('default',0,'carriers/fedex/allowed_methods','PRIORITYOVERNIGHT,STANDARDOVERNIGHT,FIRSTOVERNIGHT,FEDEX2DAY,FEDEXEXPRESSSAVER,INTERNATIONALPRIORITY,INTERNATIONALECONOMY,INTERNATIONALFIRST,FEDEX1DAYFREIGHT,FEDEX2DAYFREIGHT,FEDEX3DAYFREIGHT,FEDEXGROUND,GROUNDHOMEDELIVERY,INTERNATIONALPRIORITY FREIGHT,INTERNATIONALECONOMY FREIGHT,EUROPEFIRSTINTERNATIONALPRIORITY','',0),
('default',0,'carriers/ups/allowed_methods','1DM,1DML,1DA,1DAL,1DAPI,1DP,1DPL,2DM,2DML,2DA,2DAL,3DS,GND,GNDCOM,GNDRES,STD,XPR,WXS,XPRL,XDM,XDML,XPD','',0),
('default',0,'carriers/usps/allowed_methods','FIRST CLASS,PRIORITY,EXPRESS,BPM,PARCEL,MEDIA,LIBRARY','',0)
ON DUPLICATE KEY UPDATE config_id=config_id;

update `core_config_data` set `value` = '0', `inherit` = '1' where `path` = 'carriers/dhl/active';
update `core_config_data` set `inherit` = '0' where `scope` = 'default' and `path` = 'carriers/dhl/active';

