<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product); ?>

<a href="#" data-post='<?php echo $_wishlistSubmitParams; ?>' class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a>
<script type="text/javascript">
    jQuery('body').mage('addToWishlist',
        <?php echo $this->helper('Magento\Core\Helper\Data')->jsonEncode(array('productType' => $_product->getTypeId()))?>
    );
</script>
