<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Customer "Remember Me" template
 *
 * @var $this \Magento\Persistent\Block\Form\Remember
 */
?>
<div id="remember-me-box" class="field choice persistent">
    <?php $rememberMeId = 'remember_me' . $this->getRandomString(10); ?>
    <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php echo $rememberMeId; ?>"<?php if ($this->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php echo __('Remember Me') ?>" />
    <label for="<?php echo $rememberMeId; ?>" class="label"><span><?php echo __('Remember Me') ?></span></label>
    <a class="link tip" href="#"><?php echo __('What\'s this?') ?></a>
</div>

