<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * "Remember Me" popup template (when click on "What's this?")
 *
 */
/** @var $this \Magento\Framework\View\Element\Template */
?>
<script type="text/javascript">
    (function($) {
        $('#remember-me-box').mage("rememberMePopup", {
            title: '<?php echo __('What is this?');?>',
            close: '<?php echo __('Close');?>',
            content: '<?php echo __('Check &quot;Remember Me&quot; to access your shopping cart on this computer when you are logged out')?>'
        });
    })(jQuery);
</script>
