<?
/**
 * Cart cross sell items template
 * 
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?if($this->getItemCount()):?>
<div class="col-1 upsell">
    <h4>Based on your selection(s), you may be interested in the following items:</h4>
    <ul class="generic-product-list">
    <?foreach ($this->getItems() as $_item):?>
        <li>
            <a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getThumbnailUrl()?>" width="75" alt="<?=$this->htmlEscape($_item->getName())?>" class="product-image"/>
            <div class="product-shop">
                <h5><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></h5>
                <?=$this->getHelper('catalog/product')->getPriceHtml($_item)?>
                <button class="form-button" onclick="setLocation('<?=$this->getAddToCartUrl($_item)?>')" type="button"><span>Add to Cart</span></button><br/>
                <small><a href="<?=$this->getAddToWishlistUrl($_item)?>" class="link-cart">Add to Wishlist</a></small>
            </div>
        </li>
    <?endforeach;?>
    </ul>
</div>
<?endif;?>