<div class="shipping-estimate box">
<h4><?=__('Estimate Shipping and Tax')?></h4>
<form action="<?=$this->getUrl('checkout/cart/estimatePost')?>" method="post" id="shipping-zip-form">
	<p><label for="estimate_postcode"><?=__('Enter your zip code to get a shipping quote.')?></label></p>
	<input class="input-text left" id="shipping-zip-code" name="estimate_postcode" value="<?=$this->getEstimatePostcode()?>"/>
	<button type="submit" class="form-button-alt"><span><?=__('Get Quote')?></span></button>
    <input type="hidden" id="shipping-zip-code" class="validate-zip-code" />
	<div class="clear"></div>
</form>
<?if (!($_shippingRateGroups = $this->getEstimateRates())):?>
    <p><br/><strong><?=__('Sorry, no quotes are available for this order at this time.')?></strong></p>
<?else:?>
<form id="co-shipping-method-form" action="<?=$this->getUrl('checkout/cart/estimateUpdatePost')?>">
    <dl class="shipment-methods">
        <?foreach ($_shippingRateGroups as $code => $_rates):?>
            <dt><?=$this->getCarrierName($code)?></dt>
            <dd>
                <ul>
                <?foreach ($_rates as $_rate):?>
                    <li>
                       <?if ($_rate->getErrorMessage()):?>
                            <strong><?=$_rate->getErrorMessage()?></strong>
                       <?else:?>
                            <input name="estimate_method" type="radio" value="<?=$_rate->getCode()?>" id="s_method_<?=$_rate->getCode()?>"<?if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked'?>/>
                            <label for="s_method_<?=$_rate->getCode()?>"><?=$_rate->getMethodDescription()?> - <strong><?=$_rate->getPrice()?></strong></label>
                       <?endif?>
                    </li>
                <?endforeach;?>
                </ul>
            </dd>
        <?endforeach;?>
    </dl>
    <button type="submit" class="form-button-alt" name="do" value="<?=__('Update')?>"><span><?=__('Update total')?></span></button>
</form>
<script type="text/javascript">
    var coShippingMethodForm = new VarienForm('shipping-zip-form');
	Validation.addAllThese(
    [
	       ['validate-zip-code', 'Please enter a valid zip code. For example 90602 or 90602-1234.', function(v) {
                if( $('shipping-zip-code').value.match(/(^[A-z0-9]{2,10}([\s]{0,2}|[\-]{0,2})[A-z0-9]{2,10}$)/ ) {
                    return true;
                } else {
                    return false;
                }
           }]
    ]
    );
</script>
<?endif;?>
</div>
