<?if($this->getCanDisplayCart()):?>
<div class="box base-mini mini-cart">
	<div class="head">
		<h4>My Cart <span class="count">- <a href="<?=$this->getUrl('checkout/cart')?>"><?=__('%d item(s)', sizeof($this->getCartItems()))?></a></span></h4>
		<!--<h5>Last added items</h5>-->
	</div>
	<?if(sizeof($this->getCartItems())>0):?>
	<ol id="cart-sidebar">
	 <?foreach($this->getCartItems() as $_item):?>
        <li>
			<div class="product-images">
				<a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getProduct()->getSmallImageUrl()?>" alt="<?=$_item->getName()?>" width="38" height="38"/></a>
			</div>
			<div class="product-details">
				<a href="<?=$this->getRemoveItemUrl($_item)?>" onclick="return confirm('<?=__('Are You sure?')?>');" class="widget-btn"><img src="<?=$this->getSkinUrl('images/list_remove_btn.gif')?>" alt="Remove"/></a>
				<a href="#"><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a>
				<br/><strong>Qty: <?=1*$_item->getQty()?></strong>
				<?=$this->getHelper('catalog/product')->getPriceHtml($_item)?>
			</div>
		</li>
	<?endforeach;?>
	</ol>
	<script type="text/javascript">decorateList('cart-sidebar')</script>
	<?else:?>
 	<div class="content"><p><?=__('You have no items in your cart.')?></p></div>
 	<?endif?>
    <div class="actions">
        <div class="subtotal">
            <span class="label">Subtotal:</span><br/>
            <span class="price">$49.99</span>
        </div>
        <button class="form-button"><span>Checkout</span></button><br/>
        <a href="<?=$this->getUrl('checkout/cart')?>">Go to Cart</a></div>
</div>
<!-- [ends] .cart-sidebar // -->
<?endif?>