<p>
    <span class="powered-by">Magento powered by <a href="http://www.varien.com" target="varien_external">Varien</a></span>
		Copyright &copy; 2007 <a href="http://www.magentocommerce.com" target="http://www.magentocommerce.com">Magento</a>. All Rights Reserved.<br/>
		<div class="clear"></div>
</p>
<?if($this->getShowProfiler()):?>
<div style="text-align:left">
    <?=$this->getProfiler()?>
</div>
<?endif;?>