<p>
    <span class="powered-by">Magento powered by <a href="http://www.varien.com" target="varien_external">Varien</a></span>
		Copyright &copy; 2007 <a href="http://www.magentocommerce.com" target="http://www.magentocommerce.com">Magento</a>. All Rights Reserved.<br/>
		<div class="clear"></div>
</p>
<?if($this->getShowProfiler()):?>
<?$_sum=0?>
<table border="1" cellpadding="2" cellspacing="0">
    <tr>
        <th>Code</th>
        <th>Count</th>
        <th>Time</th>
    </tr>
<?foreach ($this->getProfilerTimers() as $_code => $_info):?>
    <?if($_info['sum']):?>
    <?$_sum+=$_info['sum']?>
    <tr>
        <td><?=$_code?></td>
        <td><?=$_info['count']?></td>
        <td><?=$this->formatTime($_info['sum'])?></td>
    </tr>
    <?endif;?>
<?endforeach;?>
    <tr>
        <td align="right" colspan="2">Total:</td>
        <td><?=$this->formatTime($_sum)?></td>
    </tr>
</table>
<?endif;?>