<a href="<?=$homeLink?>">
    <img src="<?=$baseUrl?>skins/adminhtml/images/logo.gif" alt="Magento logo" class="logo"/>
</a>
<div class="header-right">
    <p class="super">
        <strong><?=__("Welcome, %s", $user->getName())?></strong>
        <span class="separator">|</span>
        <strong><?=__("Today is %s", date("l, F dS, Y"))?></strong>
        <span class="separator">|</span>
        <a href="<?=$logoutLink?>"><?=__('Logout')?></a>
    </p>
    <fieldset>
        <span id="global_search_indicator" class="autocomplete-indicator" style="display: none">
            <img src="<?=$baseUrl?>skins/adminhtml/images/ajax-loader.gif" alt="Working..." align="absmiddle" height="20"/>
        </span>
        <?$defSearch = __('Global record search')?>
        <input id="global_search" name="query" type="text" class="input-text" 
            value="<?if(!empty($query)):?><?=$query?><?else:?><?=$defSearch?><?endif?>" 
            onfocus="if(this.value=='<?=$defSearch?>')this.value=''; " 
            onblur="if(this.value=='')this.value='<?=$defSearch?>';"
        />
        <div id="global_search_autocomplete" class="autocomplete"></div>
        <script type="text/javascript">
            new Ajax.Autocompleter(
                'global_search', 
                'global_search_autocomplete', 
                '<?=$baseUrl?>adminhtml/index/globalSearch/', 
                {
                    paramName:"query", 
                    minChars:2,
                    indicator:"global_search_indicator", 
                    updateElement:getSelectionId
                }
            );
            
            function getSelectionId(li) {
                console.log(li);
            }
        </script>
    </fieldset>
</div>