<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_wishlistItem = $this->getWishlistItem(); ?>
<?php $_wishlistSubmitUrl = $this->helper('Mage_Wishlist_Helper_Data')->getUpdateUrl($_wishlistItem); ?>
<ul class="add-to-links" data-role="add-to-links">
<?php if ($this->helper('Mage_Wishlist_Helper_Data')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" class="link-compare"><?php echo $this->__('Update Wishlist') ?></a></li>
<?php endif; ?>
<?php $_product = $this->getProduct(); ?>
<?php $_compareUrl = $this->helper('Mage_Catalog_Helper_Product_Compare')->getAddUrl($_product); ?>
<?php if ($_compareUrl) : ?>
    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
<?php endif; ?>
</ul>
