<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Denied
 */
?>
<h1 class="page-heading"><?php echo $this->helper('Mage_Adminhtml_Helper_Data')->__('Access denied') ?></h1>
<?php if (!$this->hasAvailableResources()): ?>
<p>
<?php echo $this->helper('Mage_Adminhtml_Helper_Data')->__('Please try to logout and sign in again.') ?><br/>
<?php echo $this->helper('Mage_Adminhtml_Helper_Data')->__('If this message persists, please contact the store owner.') ?>
</p>
<?php else: ?>
<p><?php echo $this->helper('Mage_Adminhtml_Helper_Data')->__('Access denied.') ?></p>
<?php endif?>
