<?php
/**
 * {license_notice}
 *
 * @category    Saas
 * @package     Saas_UnitPrice
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
if (
    !Mage::helper('Saas_UnitPrice_Helper_Data')->moduleActive()
    || Mage::helper('Saas_UnitPrice_Helper_Data')->inAdmin()
) {
    return;
}
?>

<?php $_product = $this->getProduct(); ?>
<?php if ($_product->getData('unit_price_use')) : ?>
<div class="unitprice-box">
    <span class="uint-label-<?php echo $_product->getId() ?>">
        <?php echo Mage::helper('Saas_UnitPrice_Helper_Data')->getUnitPriceLabel($_product); ?>
    </span>
</div>
<?php endif; ?>

