<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo'<?xml version="1.0"?>';?>

<rss version="2.0">
   <channel>
      <title><?=$channel_data->getTitle();?></title>
      <link><?=$baseUrl?></link>
      <description><?=$channel_data->getDescription();?></description>
      <pubDate><?=$channel_data->getPubDate();?></pubDate>

      <?foreach( $data as $item):?>

      <item>
         <title><?=htmlentities($item->getName());?></title>
         <link><?=$baseUrl?>catalog/category/view/id/<?=$item->getCategoryId();?></link>
         <description><?=htmlentities($item->getDescription());?></description>
      </item>

      <?endforeach?>

   </channel>
</rss>
