<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getShippingAmount() || $_source->getShippingDescription()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Shipping &amp; Handling') ?></td>
        <td><?php echo $this->displayPriceAttribute('shipping_amount') ?></td>
    </tr>
<?php endif; ?>
