<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <button class="scalable add" onclick="window.location='<?php echo $this->getCreateUrl() ?>'">
        <?php echo Mage::helper('Mage_Newsletter_Helper_Data')->__('Add New Template'); ?>
    </button>
</div>
<?php echo $this->getChildHtml('grid') ?>
