<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * @see \Magento\AdvancedCheckout\Block\Adminhtml\Manage\Form\Coupon
 */
?>
<div class="box-left">
    <h4><?php echo __('Apply Coupon Code') ?></h4>
     <fieldset>
         <div class="content">
            <p><input type="text" class="input-text" id="coupon_code" name="ccode" style="width:200px" /> <?php echo $this->getApplyButtonHtml() ?></p>
            <?php if ($this->getCouponCode()): ?>
                <p id="cc_info"><strong><?php echo $this->getCouponCode(); ?></strong> [<a href="#" onclick="checkoutObj.applyCoupon();return false;" title="<?php echo __('Remove Coupon Code') ?>"><?php echo __('Remove') ?></a>]</p>
            <?php elseif ($invalid = $this->getInvalidCouponCode()): ?>
                <p id="cc_info"><strong><?php echo __('The coupon code "%1" is not valid.', $invalid) ?></strong></p>
            <?php endif; ?>
        </div>
    </fieldset>
</div>
