<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<? if($this->helper('customer')->isLoggedIn()): ?>
    <script type="text/javascript" language="javascript">
        url = '<?=$this->helper("customerAlert")->getSaveAlertsUrl()?>';
        function alertError(message){
            $('alerts-error').show(); 
            $('alerts-please-wait').hide();
            $('alerts-success').hide();
            $('alerts-error').update(message);
        }
        
        function alertSuccess(message){
            $('alerts-error').hide(); 
            $('alerts-please-wait').hide();
            $('alerts-success').show();
            $('alerts-success').update(message);
        }
        
        function saveAlerts(){
            $('alerts-please-wait').show();
            $('alerts-error').hide();
            $('alerts-success').hide();
            elem = $$('.alert_input');
            param = new Object();
            for(a=0;a<elem.length;a++){
                param[elem[a].id] = elem[a].checked;
            }
            param['_product_id'] = <?=$this->helper('customerAlert')->getProductId();?>;
            new Ajax.Request( url, {
                parameters : param,
                onSuccess : function(req) 
                        {
                            request = req.responseText.evalJSON();
                            if(request.error){
                                alertError(request.message);
                            } else {
                                alertSuccess(request.message);
                            }
                        },
                onFailure : function()
                        {
                           alertError("<?=$this->__('Alert subscription(s) were not saved. Please try again')?>");
                        }
                       
            });
        }
        
    </script>
        <div class="collateral-box attribute-specs">
            <div class="head">
                <h4><?=$this->__('Product Alerts')?></h4>
            </div>
            <ul>
                <li>
                    <span id="alerts-please-wait" style="display:none;" class="opc-please-wait">
                        <img src="<?=$this->getSkinUrl('images/opc-ajax-loader.gif')?>" align="absmiddle"> &nbsp; <?=$this->__('Saving, please wait...')?> &nbsp; 
                    </span>
                    <span id="alerts-error" style="display:none;" class="error"></span>
                    <span id="alerts-success" style="display:none;" class="success"></span>
                </li>
            <? foreach ($this->helper('customerAlert')->getAlerts() as $key => $val): ?>
                <li>
                    <input name="alerts[<?=$key?>]" value="1" id="<?=$key?>" type="checkbox" class="alert_input" <?=$val['checked']?'checked="checked"':''?> />&nbsp;
                    <label for="<?=$key?>"><?=$val['label']?></label>
                </li>
            <? endforeach;?>
                <li>
                    <button class="form-button-alt" onclick="saveAlerts()">
                        <span><?=$this->__('Save alerts')?></span>
                    </button>       
                </li>
            </ul>
        </div>
    <? endif; ?>