<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_BackgroundUploader */ ?>
<?php
/** @var $element Mage_DesignEditor_Block_Adminhtml_Editor_Form_Element_BackgroundUploader */
$element = $this->getElement();
?>

<div style="padding:8px; border-radius:5px; background:#32312c;">
    <div id="<?php echo $element->getHtmlId(); ?>-uploader">
        <div  class="no-display" id="<?php echo $element->getHtmlId(); ?>-container">
            <?php echo $element->getImageUploaderElement()->toHtml() ?>
        </div>

        <div class="no-display" id="<?php echo $element->getHtmlId(); ?>-template">
            <div class="file-row">
                <span class="label">{{name}}</span>
                <span id="{{remove-id}}">remove</span>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        (function($) {
            $(document.getElementById('<?php echo $element->getHtmlId(); ?>-uploader')).quickStyleUploader({
                uploader_id: '<?php echo $element->getHtmlId(); ?>',
                container:   '<?php echo $element->getHtmlId(); ?>-uploader',
                event:       '<?php echo $this->getEvent(); ?>:uploaded',
                value:       '<?php echo $element->getValue(); ?>',
                url:         '<?php echo $this->getImageUploadUrl(); ?>',
                remove_url:  '<?php echo $this->getImageRemoveUrl(); ?>'
            });
        })(jQuery);
    </script>

    <hr />

    <?php echo $element->getCheckboxElement()->toHtml() ?>
</div>
