<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_BackgroundUploader */ ?>
<?php
/** @var $element Mage_DesignEditor_Block_Adminhtml_Editor_Form_Element_BackgroundUploader */
$element = $this->getElement();
?>

<div style="padding:8px; border-radius:5px; background:#32312c;">
    <?php echo $element->getImageUploaderElement()->toHtml() ?>
    <hr />
    <?php echo $element->getCheckboxElement()->toHtml() ?>
</div>
