<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_BackgroundUploader */ ?>
<?php
/** @var $element Mage_DesignEditor_Block_Adminhtml_Editor_Form_Element_BackgroundUploader */
$element = $this->getElement();
?>

<div style="border:1px solid gray;">
    <?php echo $this->getHtml() ?>
    <fieldset class="<?php echo join(' ', $this->getClasses()) ?>" id="<?php echo $element->getHtmlId() ?>">
        <?php /** @var $child Varien_Data_Form_Element_Abstract */ ?>
        <?php /*foreach ($element->getSortedElements() as $child): ?>
            <?php echo $child->toHtml(); ?>
        <?php endforeach;*/ ?>
    </fieldset>
</div>

