<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_Uploader */ ?>
<?php
/** @var $element Mage_DesignEditor_Block_Adminhtml_Editor_Form_Element_Uploader */
$element = $this->getElement();
?>

<div style="border:1px solid gray; padding:10px 5px;">
    <?php echo $this->getHtml(); ?>
</div>
