<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->getEnabled() && $this->getItem()) : ?>
<script id="gift-registry-billing" type="text/x-jQuery-tmpl">
    <li class="control">
        <div class="input-box">
            <input name="billing[use_for_shipping]" id="billing:use_gift_registry_address" value="2"  class="radio" type="radio">
        </div>
        <label for="billing:use_gift_registry_address"><?php echo __("Ship to recipient's address") ?></label>
    </li>
</script>

<script id="gift-registry-shipping" type="text/x-jQuery-tmpl">
    <li class="form-alt">
        <input type="checkbox" title="<?php echo __('Use the gift registry shipping address') ?>" class="checkbox"  value="<?php echo $this->getAddressIdPrefix(); ?><?php echo $this->getItem(); ?>" id="use_gr_address" name="shipping_address_id" />
        <label for="use_gr_address"><?php echo __('Use the gift registry shipping address') ?></label>
    </li>
</script>
<?php endif; ?>
