<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_AdminNotification_Block_ToolbarEntry */ ?>
<?php $notificationCount = $this->getUnreadNotificationCount(); ?>
<div class="notifications" data-notification-count="<?php echo $this->escapeHtml($notificationCount); ?>">
    <?php if ($notificationCount > 0) : ?>
        <a href="<?php echo $this->getUrl('adminhtml/notification/index'); ?>" class="notifications-icon" title="<?php echo $this->__('Notifications'); ?>" data-toggle="dropdown">
            <span class="value"><?php echo $this->escapeHtml($notificationCount); ?></span>
        </a>
        <ul class="dropdown-menu" data-mark-as-read-url="<?php echo $this->getUrl('adminhtml/notification/ajaxMarkAsRead'); ?>">
            <?php foreach ($this->getLatestUnreadNotifications() as $notification) : ?>
            <?php /** @var $notification Mage_AdminNotification_Model_Inbox*/ ?>
            <li class="notification-entry<?php if ($notification->getSeverity() == 1): ?> notification-critical<?php endif; ?>"
                data-notification-id="<?php echo $this->escapeHtml($notification->getId()); ?>"
                data-notification-severity="<?php if ($notification->getSeverity() == 1): ?>1<?php endif; ?>">
                <strong><?php echo $this->escapeHtml($notification->getTitle()); ?></strong>
                <span class="notification-description"><?php echo $this->escapeHtml($notification->getDescription()); ?></span>
                <time><?php echo $this->escapeHtml($this->formatNotificationDate($notification->getDateAdded())); ?></time>
                <button class="action-close"><?php echo $this->__('Close'); ?></button>
                <div class="notification-dialog-content" data-title="<?php echo $this->__('Notification'); ?>" data-cancel-caption="<?php echo  $this->__('Cancel'); ?>" data-acknowledge-caption="<?php echo $this->__('Acknowledge'); ?>">
                    <strong><?php echo $this->escapeHtml($notification->getTitle()); ?></strong>
                    <span class="notification-description"><?php echo $this->escapeHtml($notification->getDescription()); ?></span>
                    <div class="actions">
                        <a class="notification-url" href="<?php echo $this->escapeUrl($notification->getUrl()); ?>" target="_blank"><?php echo $this->__('Read Details'); ?></a>
                    </div>
                    <time><?php echo $this->escapeHtml($this->formatNotificationDate($notification->getDateAdded())); ?></time>
                </div>
            </li>
            <?php endforeach; ?>
            <li class="last">
                <a href="<?php echo $this->getUrl('adminhtml/notification/index'); ?>" class="action-more"><?php echo $this->__('See All (%d unread)', $notificationCount); ?></a>
            </li>
        </ul>
    <?php else : ?>
        <a href="<?php echo $this->getUrl('adminhtml/notification/index'); ?>" class="notifications-icon" title="<?php echo $this->__('Notifications'); ?>">
            <span class="value"></span>
        </a>
    <?php endif; ?>
</div>
