<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;" summary="<?php echo __('Gift Registry Items Updated') ?>">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo __('Product Name') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo __('Requested Quantity') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo __('Fulfilled Quantity') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo __('Total Fulfilled Quantity') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo __('Remaining Quantity') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php $i = 0; foreach ($this->getItems() as $item): ?>
    <tr<?php echo $i%2 ? ' bgcolor="#F6F6F6"' : '' ?>>
        <td align="left" style="font-size:11px; padding:3px 9px"><strong><?php echo $item->getProductName() ?></strong></td>
        <td align="center" style="font-size:11px; padding:3px 9px"><?php echo $this->getQty($item) ?></td>
        <td align="center" style="font-size:11px; padding:3px 9px"><?php echo $this->getQtyOrdered($item) ?></td>
        <td align="center" style="font-size:11px; padding:3px 9px"><?php echo $this->getQtyFulfilled($item) ?></td>
        <td align="center" style="font-size:11px; padding:3px 9px"><?php echo $this->getRemainedQty($item) ?></td>
    </tr>
    <?php $i++; endforeach; ?>
    </tbody>
</table>
