<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright  {copyright}
 * @license    {license_link}
 */
?>
<?php
/**
 * "Grant Access" button
 *
 * @var $this Magento_Oauth_Block_Authorize_ButtonBaseAbstract
 */
$logo = $this->getViewFileUrl('images/logo-large.gif', array('area' => 'adminhtml', 'package' => 'default'));
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?php echo __('Authorize application') ?></h1>
        </div>
        <div class="form-box">
            <div>
                <div id="messages">
                    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                </div>
                <?php if (!$this->getHasException()) : ?>
                    <h2><?php echo __('<strong>%1</strong> requests access to your account', $this->escapeHtml($this->getConsumer()->getName())); ?></h2>
                    <p><?php echo __('After authorization application will have access to you account.'); ?></p>
                    <form id="oauth_authorize_confirm" action="<?php echo $this->getConfirmUrl() ?>" method="get">
                        <input type="hidden" name="oauth_token" value="<?php echo $this->escapeHtml($this->getToken()) ?>">
                        <button type="submit" class="button" title="<?php echo __('Authorize') ?>">
                            <span><span><?php echo __('Authorize') ?></span></span></button>
                    </form>
                    <form id="oauth_authorize_reject" action="<?php echo $this->getRejectUrl() ?>" method="get">
                        <input type="hidden" name="oauth_token" value="<?php echo $this->escapeHtml($this->getToken()) ?>">
                        <button type="submit" class="button" title="<?php echo __('Reject') ?>">
                            <span><span><?php echo __('Reject') ?></span></span></button>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
