<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright  {copyright}
 * @license    {license_link}
 */

/**
 * "Grant Access" button
 *
 * @var $this Magento_Oauth_Block_Authorize
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <h1><?php echo __('Confirmation Of Authorization') ?></h1>
            <?php echo $this->getLayout()->renderElement('messages') ?>
            <?php if (!$this->getHasException()): ?>
                <p><?php echo __('Give the verifier code to application administrator') ?></p>
                <p style="font-size: 14px;"><?php echo __('Verifier code: %1', $this->getVerifier()) ?></p>
            <?php endif; ?>
        </div>
        <p class="legal"><?php echo __('Magento&reg is a trademark of X.commerce, Inc. Copyright &copy; %1 X.commerce, Inc.', date('Y')) ?></p>
        <div class="bottom"></div>
    </div>
</div>
