<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
namespace Magento\CatalogUrlRewrite\Model;

use Magento\Store\Model\Store;
use Magento\TestFramework\Helper\ObjectManager;

class CategoryUrlRewriteGeneratorTest extends \PHPUnit_Framework_TestCase
{
    /** @var \Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator */
    protected $categoryUrlRewriteGenerator;

    /** @var \PHPUnit_Framework_MockObject_MockObject */
    protected $filterMock;

    /** @var \Magento\UrlRewrite\Service\V1\UrlMatcherInterface|\PHPUnit_Framework_MockObject_MockObject */
    protected $urlMatcherMock;

    /** @var \Magento\CatalogUrlRewrite\Service\V1\StoreViewService|\PHPUnit_Framework_MockObject_MockObject */
    protected $storeViewServiceMock;

    /** @var \Magento\UrlRewrite\Service\V1\Data\UrlRewrite\Converter|\PHPUnit_Framework_MockObject_MockObject */
    protected $converterMock;

    /** @var \Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator|\PHPUnit_Framework_MockObject_MockObject */
    protected $categoryUrlPathGeneratorMock;

    /** @var \Magento\Catalog\Model\Category|\PHPUnit_Framework_MockObject_MockObject */
    protected $categoryMock;

    /** @var \Magento\Catalog\Model\Resource\Category\Collection|\PHPUnit_Framework_MockObject_MockObject */
    protected $categoriesCollectionMock;

    protected function setUp()
    {
        $this->categoryMock = $this->getMockBuilder('Magento\Catalog\Model\Category')
            ->disableOriginalConstructor()->getMock();
        $this->categoriesCollectionMock = $this->getMockBuilder('Magento\Catalog\Model\Resource\Category\Collection')
            ->disableOriginalConstructor()->getMock();
        $this->filterMock = $this->getMock('Magento\UrlRewrite\Service\V1\Data\Filter');
        $this->filterMock->expects($this->any())->method('setStoreId')->will($this->returnSelf());
        $this->filterMock->expects($this->any())->method('setEntityId')->will($this->returnSelf());
        $filterFactoryMock = $this->getMock('Magento\UrlRewrite\Service\V1\Data\FilterFactory', ['create']);
        $filterFactoryMock->expects($this->any())->method('create')->will($this->returnValue($this->filterMock));
        $this->urlMatcherMock = $this->getMock('Magento\UrlRewrite\Service\V1\UrlMatcherInterface');
        $this->storeViewServiceMock = $this->getMockBuilder('Magento\CatalogUrlRewrite\Service\V1\StoreViewService')
            ->disableOriginalConstructor()->getMock();
        $this->converterMock = $this->getMockBuilder('Magento\UrlRewrite\Service\V1\Data\UrlRewrite\Converter')
            ->disableOriginalConstructor()->getMock();
        $this->converterMock->expects($this->any())->method('convertArrayToObject')->will($this->returnArgument(0));
        $this->categoryUrlPathGeneratorMock = $this->getMockBuilder(
            'Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator'
        )->disableOriginalConstructor()->getMock();

        $this->categoryUrlRewriteGenerator = (new ObjectManager($this))->getObject(
            'Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator',
            [
                'filterFactory' => $filterFactoryMock,
                'urlMatcher' => $this->urlMatcherMock,
                'storeViewService' => $this->storeViewServiceMock,
                'converter' => $this->converterMock,
                'categoryUrlPathGenerator' => $this->categoryUrlPathGeneratorMock
            ]
        );
    }

    /**
     * @return array
     */
    public function globalScopeDataProvider()
    {
        return [
            [1, 'category.html', [
                [
                    'entity_type' => CategoryUrlRewriteGenerator::ENTITY_TYPE,
                    'entity_id' => 1,
                    'store_id' => 1,
                    'request_path' => 'category.html',
                    'target_path' => 'catalog/category/view/id/1',
                    'redirect_type' => 0,
                    'is_autogenerated' => true,
                    'metadata' => null
                ],
                [
                    'entity_type' => CategoryUrlRewriteGenerator::ENTITY_TYPE,
                    'entity_id' => 1,
                    'store_id' => 2,
                    'request_path' => 'category.html',
                    'target_path' => 'catalog/category/view/id/1',
                    'redirect_type' => 0,
                    'is_autogenerated' => true,
                    'metadata' => null
                ],
            ]],
        ];
    }

    /**
     * @dataProvider globalScopeDataProvider
     */
    public function testGorGlobalScope($categoryId, $urlPath, $results)
    {
        $this->categoryMock->expects($this->once())->method('getStoreIds')->will($this->returnValue([0, 1, 2]));
        $this->storeViewServiceMock->expects($this->exactly(2))->method('doesEntityHaveOverriddenUrlKeyForStore')
            ->will($this->returnValue(false));
        $canonicalUrlPath = 'catalog/category/view/id/' . $categoryId;
        $this->categoryMock->expects($this->any())->method('getId')->will($this->returnValue($categoryId));
        $this->categoryMock->expects($this->any())->method('getStoreId')->will($this->returnValue(null));
        $this->categoryUrlPathGeneratorMock->expects($this->any())->method('getUrlPathWithSuffix')
            ->will($this->returnValue($urlPath));
        $this->categoryUrlPathGeneratorMock->expects($this->any())->method('getCanonicalUrlPath')
            ->with($this->categoryMock)->will($this->returnValue($canonicalUrlPath));
        $this->urlMatcherMock->expects($this->any())->method('findAllByFilter')
            ->will($this->returnValue([]));
        $this->categoryMock->expects($this->any())->method('getData')->with('save_rewrites_history')
            ->will($this->returnValue(true));
        $this->categoryMock->expects($this->any())->method('getChildrenCategories')
            ->will($this->returnValue($this->categoriesCollectionMock));
        $this->categoriesCollectionMock->expects($this->any())->method('getIterator')
            ->will($this->returnValue(new \ArrayIterator([])));

        $this->assertEquals($results, $this->categoryUrlRewriteGenerator->generate($this->categoryMock));
    }

    /**
     * @return array
     */
    public function urlRewritesDataProvider()
    {
        return include __DIR__ . '/_files/categoryUrlRewritesDataProvider.php';
    }

    /**
     * @dataProvider urlRewritesDataProvider
     */
    public function testGeneratePerStoreView($storeId, $categoryId, $urlPath, $currentRewrites, $results)
    {
        $canonicalUrlPath = 'catalog/category/view/id/' . $categoryId;
        $this->categoryMock->expects($this->any())->method('getId')->will($this->returnValue($categoryId));
        $this->categoryMock->expects($this->any())->method('getStoreId')->will($this->returnValue($storeId));
        $this->categoryUrlPathGeneratorMock->expects($this->any())->method('getUrlPathWithSuffix')
            ->will($this->returnValue($urlPath));
        $this->categoryUrlPathGeneratorMock->expects($this->any())->method('getCanonicalUrlPath')
            ->with($this->categoryMock)->will($this->returnValue($canonicalUrlPath));
        $this->urlMatcherMock->expects($this->any())->method('findAllByFilter')
            ->will($this->returnValue($this->buildCurrentRewrites($currentRewrites)));
        $this->categoryMock->expects($this->any())->method('getData')->with('save_rewrites_history')
            ->will($this->returnValue(true));
        $this->categoryMock->expects($this->any())->method('getChildrenCategories')
            ->will($this->returnValue($this->categoriesCollectionMock));
        $this->categoriesCollectionMock->expects($this->any())->method('getIterator')
            ->will($this->returnValue(new \ArrayIterator([])));

        $this->assertEquals($results, $this->categoryUrlRewriteGenerator->generate($this->categoryMock));
    }

    /**
     * @return array
     */
    public function generationWithChildrenDataProvider()
    {
        return [
            [1, 1, 2, 'category.html', 'category/category-2.html', [
                [
                    'entity_type' => CategoryUrlRewriteGenerator::ENTITY_TYPE,
                    'entity_id' => 1,
                    'store_id' => 1,
                    'request_path' => 'category.html',
                    'target_path' => 'catalog/category/view/id/1',
                    'redirect_type' => 0,
                    'is_autogenerated' => true,
                    'metadata' => null
                ],
                [
                    'entity_type' => CategoryUrlRewriteGenerator::ENTITY_TYPE,
                    'entity_id' => 2,
                    'store_id' => 1,
                    'request_path' => 'category/category-2.html',
                    'target_path' => 'catalog/category/view/id/2',
                    'redirect_type' => 0,
                    'is_autogenerated' => true,
                    'metadata' => null
                ],
            ]],
        ];
    }

    /**
     * @dataProvider generationWithChildrenDataProvider
     */
    public function testGeneratePerStoreViewWithChildrenCategories(
        $storeId,
        $categoryId,
        $childCategoryId,
        $urlPath,
        $childUrlPath,
        $results
    ) {
        $this->categoryMock->expects($this->any())->method('getId')->will($this->returnValue($categoryId));
        $this->categoryMock->expects($this->any())->method('getStoreId')->will($this->returnValue($storeId));
        $this->categoryUrlPathGeneratorMock->expects($this->any())->method('getUrlPathWithSuffix')
            ->will($this->returnCallback(
                function ($category) use ($categoryId, $childCategoryId, $urlPath, $childUrlPath) {
                    return $category->getId() == $categoryId
                        ? $urlPath : ($category->getId() == $childCategoryId ? $childUrlPath : '');
                }));
        $this->categoryUrlPathGeneratorMock->expects($this->any())->method('getCanonicalUrlPath')
            ->will($this->returnCallback(
                function ($category) use ($categoryId, $childCategoryId) {
                    $path = 'catalog/category/view/id/';
                    return $category->getId() == $categoryId
                        ? $path . $categoryId : ($category->getId() == $childCategoryId ? $path . $childCategoryId : '');
                }));
        $this->urlMatcherMock->expects($this->any())->method('findAllByFilter')
            ->will($this->returnValue([]));
        $this->categoryMock->expects($this->any())->method('getData')->with('save_rewrites_history')
            ->will($this->returnValue(true));
        $this->categoryMock->expects($this->any())->method('getChildrenCategories')
            ->will($this->returnValue($this->categoriesCollectionMock));
        $childCategoryMock = $this->getMock('Magento\Catalog\Model\Category', [], [], '', false);
        $childCategoryMock->expects($this->any())->method('getId')->will($this->returnValue($childCategoryId));
        $childCategoryMock->expects($this->any())->method('getStoreId')->will($this->returnValue($storeId));
        $childCategoriesCollectionMock = $this->getMockBuilder('Magento\Catalog\Model\Resource\Category\Collection')
            ->disableOriginalConstructor()->getMock();
        $childCategoryMock->expects($this->any())->method('getChildrenCategories')
            ->will($this->returnValue($childCategoriesCollectionMock));
        $childCategoriesCollectionMock->expects($this->any())->method('getIterator')
            ->will($this->returnValue(new \ArrayIterator([])));
        $categoriesIterator = new \ArrayIterator([$childCategoryMock]);
        $this->categoriesCollectionMock->expects($this->any())->method('getIterator')
            ->will($this->returnValue($categoriesIterator));

        $this->assertEquals($results, $this->categoryUrlRewriteGenerator->generate($this->categoryMock));
    }

    /**
     * @param array $currentRewrites
     * @return array
     */
    protected function buildCurrentRewrites($currentRewrites)
    {
        $rewrites = [];
        if ($currentRewrites) {
            foreach ($currentRewrites as $urlRewrite) {
                /** @var \PHPUnit_Framework_MockObject_MockObject */
                $urlMock = $this->getMock('Magento\UrlRewrite\Service\V1\Data\UrlRewrite', [], [], '', false);
                foreach ($urlRewrite as $key => $value) {
                    $urlMock->expects($this->any())
                        ->method('get' . str_replace(' ', '', ucwords(str_replace('_', ' ', $key))))
                        ->will($this->returnValue($value));
                }
                $rewrites[] = $urlMock;
            }
        }
        return $rewrites;
    }
}
