<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Document content item template
 *
 * @var $this \Magento\Doc\Ui\Widget\Document\Content
 */
?>
<div data-role="doc-item" class="{{data.class}}" data-type="{{var data.type}}" module="{{var data.module}}"
     readmode="{{var data.readonly}}">
    <span class="label">{{var data.label}}</span>

    <div data-type="{{var data.type}}" data-role="doc-item-content" module="{{var data.module}}">
        {{var content}}
    </div>
    <textarea data-role="doc-item-content-src" spellcheck="false" wrap="off" scheme="{{var data.scheme}}"
              doc-name="{{var name}}"
              module="{{var data.module}}">{{var content}}</textarea>

    <div class="items">{{var render.renderItemsHtml()}}</div>
</div>
