<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php  $_order = $this->getOrder() ?>
<div class="order toolbar">
    <div class="actions">
        <?php  if ($_order->getTracksCollection()->count()) : ?>
            <a href="#"
               data-mage-init="{popupWindow: {windowURL:'<?php echo $this->helper('Mage_Shipping_Helper_Data')->getTrackingPopupUrlBySalesModel($_order) ?>',windowName:'trackorder',width:800,height:600,top:0,left:0,resizable:1,scrollbars:1}}" title="<?php echo $this->__('Track all shipment(s)') ?>"
               class="action track">
                <span><?php echo $this->__('Track all shipments') ?></span>
            </a>
        <?php endif; ?>
        <a href="<?php echo $this->getPrintAllShipmentsUrl($_order) ?>"
           onclick="this.target='_blank'"
           class="action print">
            <span><?php echo $this->__('Print All Shipments') ?></span>
        </a>
    </div>
</div>
<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
<div class="order title">
    <strong><?php echo $this->__('Shipment #') ?><?php echo $_shipment->getIncrementId(); ?></strong>
    <a href="<?php echo $this->getPrintShipmentUrl($_shipment) ?>"
       onclick="this.target='_blank'"
       class="action print">
        <span><?php echo $this->__('Print Shipment') ?></span
    </a>
    <a href="#"
       data-mage-init="{popupWindow: {windowURL:'<?php echo $this->helper('Mage_Shipping_Helper_Data')->getTrackingPopupUrlBySalesModel($_shipment) ?>',windowName:'trackshipment',width:800,height:600,top:0,left:0,resizable:1,scrollbars:1}}"
       title="<?php echo $this->__('Track this shipment') ?>"
       class="action track">
        <span><?php echo $this->__('Track this shipment') ?></span>
    </a>
</div>
<?php $tracks = $_shipment->getTracksCollection(); ?>
<?php  if ($tracks->count()): ?>
    <table class="data table order tracking" id="my-tracking-table-<?php echo $_shipment->getId(); ?>">
        <tbody>
            <tr>
                <th class="label"><?php echo $this->__('Tracking Number(s):') ?></th>
                <td>&nbsp;
                <?php
                $i = 1;
                $_size = $tracks->count();
                foreach($tracks as $track): ?>
                <?php if($track->isCustom()): ?>
                    <?php echo $this->escapeHtml($track->getNumber()) ?>
                <?php else: ?>
                    <a href="#"
                       data-mage-init="{popupWindow: {windowURL:'<?php echo $this->helper('Mage_Shipping_Helper_Data')->getTrackingPopupUrlBySalesModel($track) ?>',windowName:'trackorder',width:800,height:600,left:0,top:0,resizable:1,scrollbars:1}}"
                       class="action track">
                        <span><?php echo $this->escapeHtml($track->getNumber()) ?></span>
                    </a>
                <?php endif; ?>
                <?php if($i!=$_size): ?>, <?php endif; ?>
                <?php $i++;
                endforeach; ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php  endif; ?>
<h3 class="order subtitle caption"><?php echo $this->__('Items Shipped') ?></h3>
<table class="data table order shipment" id="my-shipment-table-<?php echo $_shipment->getId(); ?>">
    <thead>
        <tr>
            <th class="col name"><?php echo $this->__('Product Name') ?></th>
            <th class="col sku"><?php echo $this->__('SKU') ?></th>
            <th class="col qty"><?php echo $this->__('Qty Shipped') ?></th>
        </tr>
    </thead>
    <?php $_items = $_shipment->getAllItems(); ?>
    <?php $_count = count($_items) ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>
</table>
<?php echo $this->getCommentsHtml($_shipment)?>
<?php endforeach; ?>
