<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="message message-info">
    <div class="message-inner">
        <div class="message-content"><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Changing address information will not recalculate shipping, tax or other order amount.') ?></div>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getForm()->toHtml() ?>
    </div>
</div>
