<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_item = $this->getItem() ?>
<?php $canApplyMsrp = Mage::helper('Magento_Catalog_Helper_Data')->canApplyMsrp($_item->getProduct(), Magento_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM); ?>
<li class="item">
    <?php if ($this->hasProductUrl()): ?>
        <a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnailSidebarUrl() ?>" width="<?php echo $this->getThumbnailSidebarSize()?>" height="<?php echo $this->getThumbnailSidebarSize()?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></a>
    <?php else: ?>
        <span class="product-image">
            <img src="<?php echo $this->getProductThumbnailSidebarUrl() ?>" width="<?php echo $this->getThumbnailSidebarSize()?>" height="<?php echo $this->getThumbnailSidebarSize()?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" />
        </span>
    <?php endif; ?>

    <div class="product-details">
        <p class="product-name">
            <?php if ($this->hasProductUrl()): ?>
                <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
            <?php else: ?>
                <?php echo $this->escapeHtml($this->getProductName()) ?>
            <?php endif; ?>
        </p>
        <table cellpadding="0">

        <?php if ($canApplyMsrp): ?>

            <tr><th><?php echo __('Price'); ?></th><td><span class="map-cart-sidebar-item"><?php echo __('See price before order confirmation.'); ?></span></td></tr>

        <?php else: ?>

        <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceExclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
            <tr>
            <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
                <th><?php echo __('Excl. Tax'); ?></th>
            <?php else: ?>
                <th><?php echo __('Price'); ?></th>
            <?php endif; ?>
            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                <td><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></td>
            <?php else: ?>
                <td><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getCalculationPrice()) ?></td>
            <?php endif; ?>
            </tr>

            <?php if (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>
                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales')): ?>

                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <tr>
                            <th><small><?php echo $tax['title']; ?>:</small></th>
                            <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount'],true,true); ?></small></td>
                        </tr>
                    <?php endforeach; ?>

                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <tr>
                            <th><small><?php echo $tax['title']; ?></small></th>
                            <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></td>
                        </tr>
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'sales')): ?>

                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <tr>
                            <th><small><?php echo $tax['title']; ?></small></th>
                            <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></td>
                        </tr>
                    <?php endforeach; ?>

                <?php endif; ?>
                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales')): ?>
                        <tr>
                            <th><small><?php echo __('Total:'); ?></small></th>
                            <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></small></td>
                        </tr>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>



        <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceInclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
            <?php $_incl = Mage::helper('Magento_Checkout_Helper_Data')->getPriceInclTax($_item); ?>
            <tr>
            <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
                <th><?php echo __('Incl. Tax'); ?></th>
            <?php else: ?>
                <th><?php echo __('Price'); ?></th>
            <?php endif; ?>
            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                <td><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></td>
            <?php else: ?>
                <td><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?></td>
            <?php endif; ?>
            </tr>
            <?php if (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item)): ?>

                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales')): ?>
                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <tr>
                            <th><small><?php echo $tax['title']; ?></small></th>
                            <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount'],true,true); ?></small></td>
                        </tr>
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <tr>
                            <th><small><?php echo $tax['title']; ?></small></th>
                            <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></td>
                        </tr>
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 4, 'sales')): ?>
                    <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                        <tr>
                            <th><small><?php echo $tax['title']; ?></small></th>
                            <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <tr>
                        <th><small><?php echo __('Total incl. tax'); ?></small></th>
                        <td><small><?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></small></td>
                    </tr>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php endif; //Can apply MSRP ?>
            <tr>
                <th><?php echo __('Qty'); ?></th>
                <td><?php echo $this->getQty() ?></td>
            </tr>
        </table>
        <?php if ($_options = $this->getOptionList()):?>
        <div class="truncated" data-mage-init="{truncateOptions:[]}">
            <div class="truncated_full_value">
                <div class="item-options">
                    <p><?php echo __('Options Details'); ?></p>
                    <dl>
                        <?php foreach ($_options as $_option) : ?>
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (is_array($_option['value'])): ?>
                            <?php echo nl2br(implode("\n", $_option['value'])) ?>
                            <?php else: ?>
                            <?php echo $_option['value'] ?>
                            <?php endif; ?>
                        </dd>
                        <?php endforeach; ?>
                    </dl>
                </div>
            </div>
            <a href="#" onclick="return false;" class="details"><?php echo __('View Details') ?></a>
        </div>
        <?php endif; ?>
        <?php if ($_item->getProduct()->isVisibleInSiteVisibility()):?>
        <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo __('Edit item') ?>" class="btn-edit"><?php echo __('Edit item')?></a>
        |
        <?php endif ?>
        <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo __('Remove item') ?>" class="btn-remove"><?php echo __('Remove item')?></a>
    </div>
</li>
