<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Template for Mage_Backend_Block_Widget_Button
 */
?>
<?php echo $this->getBeforeHtml(); ?>
<button <?php echo $this->getAttributesHtml(); ?>>
    <span><span><span><?php echo $this->getLabel(); ?></span></span></span>
</button>
<?php echo $this->getAfterHtml(); ?>
