<?
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <link rel="icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon" ></link>
    <link rel="shortcut icon" href="<?=$this->getBaseUrl()?>favicon.ico" type="image/x-icon" ></link>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>prototype/prototype.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>prototype/validation.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>scriptaculous/scriptaculous.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$this->getJsUrl()?>varien/js.js" ></script>
    <script language="javascript" type="text/javascript" src="<?=$baseJsUrl?>varien/form.js" ></script>
    <link rel="stylesheet" type="text/css" media="all" href="<?=$this->getSkinUrl('css/styles.css')?>" ></link>
    <!--[if IE]> <link rel="stylesheet" href="<?=$this->getSkinUrl('css/iestyles.css')?>" type="text/css" media="all" /> <![endif]-->
    <?=$this->getChildHtml('head')?>
</head>
<body>
    <div class="loading-process" id="loading-process" style="display:none">
        <img src="<?=$this->getSkinUrl('images/loading.gif')?>" alt="Loading..." width="32" height="32" border="0"/>
    </div>

    <!-- [start] container -->
    <div class="container">
    
        <!-- [start] header -->
        <div class="header">
            <?=$this->getChildHtml('header')?>
        </div>
        <!-- [end] header -->

        <!-- [start] middle -->
        <div class="middle">

            <!-- [start] left -->
            <div class="left">
                <?=$this->getChildHtml('store')?>
                <?=$this->getChildHtml('left')?>
            </div>
            <!-- [end] left -->

            <!-- [start] center -->
            <div class="center">

                <!-- [start] breadcrumbs -->
                    <?=$this->getChildHtml('breadcrumbs')?>
                <!-- [end] breadcrumbs -->

                <!-- [start] content -->
                <div class="content">
                    <?=$this->getChildHtml('content')?>
                </div>
                <!-- [end] content -->

            </div>
            <!-- [end] center -->

            <!-- [start] right -->
            <div class="right">
                <?=$this->getChildHtml('right')?>
            </div>
            <!-- [end] right -->

        </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
        <div class="footer">
            <?=$this->getChildHtml('footer')?>
        </div>
        <!-- [end] footer -->

    </div>
    <!-- [end] container -->

    </body>
</html>