<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_Theme
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/** @var $this Magento_Theme_Block_Adminhtml_Wysiwyg_Files_Content_Files */
?>

<?php if ($this->getFilesCount() > 0): ?>
    <?php foreach ($this->getFiles() as $file): ?>
        <div class="filecnt file-font" id="<?php echo $file['id'] ?>">
            <p class="nm">
                <?php echo $file['text'] ?>
                <?php if (isset($file['thumbnailParams'])): ?>
                    <img src="<?php echo $this->getUrl('*/*/previewImage', $file['thumbnailParams']) ?>">
                <?php endif; ?>
            </p>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <?php echo __('We found no files.') ?>
<?php endif; ?>
