<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Create account form template
 *
 * @see Magento_CustomerCustomAttributes_Block_Form
 */
/* @var $this Magento_CustomerCustomAttributes_Block_Form */
?>
<?php if ($this->hasUserDefinedAttributes()): ?>
    <?php if ($this->isShowContainer()): ?>
<div>
    <ul class="form-list">
    <?php endif;?>
    <?php foreach ($this->getUserDefinedAttributes() as $attribute):?>
        <?php $attributeContent = $this->getAttributeHtml($attribute);?>
        <?php if ($attributeContent): ?>
        <li><?php echo $attributeContent;?></li>
        <?php endif;?>
    <?php endforeach;?>
    <?php if ($this->isShowContainer()): ?>
    </ul>
</div>
    <?php endif;?>
<?php endif; ?>
