<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 /** @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Tree $this */
?>
<div class="tree-panel" >
    <div class="categories-side-col">
        <div class="tree-actions">
            <a onclick="jQuery('[data-role=tree]').jstree('close_all');"><?php echo $this->helper('Mage_Cms_Helper_Data')->__('Collapse All'); ?></a>
            <span class="separator">|</span>
            <a onclick="jQuery('[data-role=tree]').jstree('open_all');"><?php echo $this->helper('Mage_Cms_Helper_Data')->__('Expand All'); ?></a>
        </div>
    </div>
    <div data-role="tree" data-mage-init="<?php echo $this->escapeHtml($this->helper('Mage_Core_Helper_Data')->jsonEncode($this->getTreeWidgetOptions())); ?>">
    </div>
    <script type="text/javascript">
    (function($) {
        $.widget("mage.folderTree", {
            options: {
                root: 'root',
                rootName: 'Root',
                url: '',
                currentPath: ['root'],
                tree: {
                    "plugins": ["themes", "json_data", "ui", "hotkeys"],
                    "themes": {
                        "theme": "default",
                        "dots": false,
                        "icons": true
                    }
                }
            },
            _create: function() {
                var options = this.options;
                var treeOptions = $.extend(
                    true,
                    {},
                    options.tree,
                    {
                        json_data: {
                            data: {
                                data: options.rootName,
                                state: "closed",
                                metadata: {node: {id: options.root, text: options.rootName}},
                                attr: { "data-id": options.root, id: options.root}
                            },
                            ajax: {
                                url: options.url,
                                data: function(node) {
                                    return {
                                        node: node.data('id'),
                                        form_key: window.FORM_KEY
                                    };
                                },
                                success: this._convertData
                            }
                        }
                    }
                );
                this.element.jstree(treeOptions).on('loaded.jstree', $.proxy(this.treeLoaded, this));
            },

            treeLoaded: function(event) {
                var path = this.options.currentPath;
                var tree = this.element;
                var recursiveOpen = function() {
                    if (path.length > 1) {
                        var el = $("[data-id=\"" + path.pop() + "\"]");
                        tree.jstree('open_node', el, recursiveOpen);
                    } else {
                        var el = $("[data-id=\"" + path.pop() + "\"]");
                        tree.jstree('open_node', el, function() {
                            tree.jstree('select_node', el)
                        });
                    }
                };
                recursiveOpen();
            },

            _convertData: function(data) {
                return  $.map(data, function(node) {
                    var codeCopy = $.extend({}, node);
                    return {
                        data: node.text,
                        attr: {"data-id": node.id, id: node.id},
                        metadata: {node: codeCopy},
                        state: "closed"
                    };
                });
            }
        });
    })(jQuery);
    </script>
</div>