<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div>
    <form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
        <?php  $_order = $this->getOrder() ?>
        <div class="box-left">
            <div class="entry-view">
                <h4 class="icon-head head-order-date"><?php echo Mage::helper('sales')->__('Order Date: %s', $this->getOrderDateFormatted()) ?></h4>
            </div>
            <div class="entry-view">
                <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
                <div class="box customer-personal-brief">
                    <?php $_shipping = $_order->getShippingAddress() ?>
                    <address><?php echo $_shipping->getFirstname() ?> <?php echo $_shipping->getLastname() ?><br/>
                    <?php echo $_shipping->getCompany() ?><br/>
                    <?php echo $_shipping->getStreet() ?><br/>
                    <?php echo $_shipping->getCity() ?>, <?php echo $_shipping->getRegion() ?> <?php echo $_shipping->getPostcode() ?><br/>
                    <strong>T</strong> | <?php echo $_shipping->getTelephone();
                    if ($_shipping->getFax()): ?><br /><strong>F</strong> | <?php echo $_shipping->getFax() ?><?php endif; ?>
                    </address>
                </div>
            </div>
            <div class="entry-view">
                <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping Method') ?></h4>
                <div class="box customer-personal-brief">
                    <?php echo $_order->getShippingMethod() ?> <?php echo $_order->getShippingDescription() ?>
                </div>
            </div>
        </div>
        <div class="box-right">
            <div class="entry-view">
                <h4 class="icon-head head-customer-view"><?php echo Mage::helper('sales')->__('Order Status: %s', $_order->getStatus()->getFrontendLabel()) ?></h4>
            </div>
            <div class="entry-view">
                <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
                <div class="box customer-personal-brief">
                    <?php $_billing = $_order->getbillingAddress() ?>
                    <address><?php echo $_billing->getFirstname() ?> <?php echo $_billing->getLastname() ?><br/>
                    <?php echo $_billing->getCompany() ?><br/>
                    <?php echo $_billing->getStreet() ?><br/>
                    <?php echo $_billing->getCity() ?>, <?php echo $_billing->getRegion() ?> <?php echo $_billing->getPostcode() ?><br/>
                    <strong>T</strong> | <?php echo $_billing->getTelephone();
                    if ($_billing->getFax()): ?><br /><strong>F</strong> | <?php echo $_billing->getFax() ?><?php endif; ?></address>
                </div>
            </div>
            <div class="entry-view">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Method') ?></h4>
                <div class="box customer-personal-brief">
                    <?php $_payment = $_order->getPayment() ?>
                    <?php echo $_payment->getMethod() ?>: <?php echo $_payment->getCcType() ?> xxxx<?php echo $_payment->getCcLast4() ?>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="entry-view">
            <h4 class="icon-head head-order-items"><?php echo Mage::helper('sales')->__('Items Ordered') ?></h4>
        </div>
        <div>
            <?php echo $this->getItemsHtml() ?>
        </div>
        <div class="box order-totals">
            <table cellspacing="0">
                <tfoot>
                    <tr><td class="label"><strong><?php echo Mage::helper('sales')->__('Grand Total') ?></strong></td><td class="emph"><strong><?php echo $_order->getOrderCurrency()->format($_order->getGrandTotal()) ?></strong></td></tr>
                    <tr><td class="label"><strong><?php echo Mage::helper('sales')->__('Total Paid') ?></strong></td><td class="emph"><strong><?php echo $_order->getOrderCurrency()->format($_order->getTotalPaid()) ?></strong></td></tr>
                    <tr><td class="label"><strong><?php echo Mage::helper('sales')->__('Total Due') ?></strong></td><td class="emph"><strong><?php echo $_order->getOrderCurrency()->format($_order->getTotalDue()) ?></strong></td></tr>
                </tfoot>
                <tbody>
                    <tr><td><?php echo Mage::helper('sales')->__('Subtotal') ?></td><td><?php echo $_order->getOrderCurrency()->format($_order->getSubtotal()) ?></td></tr>
                    <?php if ($_order->getTaxAmount()): ?><tr><td><?php echo Mage::helper('sales')->__('Tax') ?></td><td><?php echo $_order->getOrderCurrency()->format($_order->getTaxAmount()) ?></td></tr><?php endif; ?>
                    <?php if ($_order->getShippingAmount()): ?><tr><td><?php echo Mage::helper('sales')->__('Shipping') ?></td><td><?php echo $_order->getOrderCurrency()->format($_order->getShippingAmount()) ?></td></tr><?php endif; ?>
                    <?php if ($_order->getDiscountAmount()): ?><tr><td><?php echo Mage::helper('sales')->__('Discount') ?></td><td><?php echo $_order->getOrderCurrency()->format($_order->getDiscountAmount()) ?></td></tr><?php endif; ?>
                    <?php if ($_order->getGiftcertAmount()): ?><tr><td><?php echo Mage::helper('sales')->__('Gift Certificate') ?></td><td><?php echo $_order->getOrderCurrency()->format($_order->getGiftcertAmount()) ?></td></tr><?php endif; ?>
                    <?php if ($_order->getCustbalanceAmount()): ?><tr><td><?php echo Mage::helper('sales')->__('Customer Balance') ?></td><td><?php echo $_order->getOrderCurrency()->format($_order->getCustbalanceAmount()) ?></td></tr><?php endif; ?>
                </tbody>
            </table>
        </div>
    </form>
    <?php echo $this->getFormScripts() ?>
</div>
