<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_option = $this->getOption() ?>
<?php $_optionId = $_option->getId() ?>
<dt><label<?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?php echo  $this->escapeHtml($_option->getTitle()) ?></label>
    <?php echo $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->getDecoratedIsLast()):?> class="last"<?php endif; ?>>

<?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME
    || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE): ?>

    <?php echo $this->getDateHtml() ?>

    <?php if (!$this->useCalendar()): ?>
    <script type="text/javascript">
    //<![CDATA[
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('Mage_Catalog::js/date-option.js') ?>", function() {
                $.mage.dateOption({
                    priceOptionInstance: priceOptionInstance,
                    datepickerFieldSelector: 'select.datetime-picker',
                    monthSelector: '#options_<?php echo $_optionId ?>_month',
                    yearSelector: '#options_<?php echo $_optionId ?>_year'
                });
            });
        })(jQuery);
    //]]>
    </script>
    <?php endif; ?>

<?php endif; ?>

<?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME
    || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_TIME): ?>
    <span class="time-picker"><?php echo $this->getTimeHtml() ?></span>
<?php endif; ?>

    <input type="hidden" name="validate_datetime_<?php echo $_optionId ?>" class="validate-datetime-<?php echo $_optionId ?>" value="" data-validate="{validateDatetime<?php echo $_optionId?>:true}"/>
    <script type="text/javascript">
    //<![CDATA[
<?php if (!$_option->getIsRequire()): ?>
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('Mage_Catalog::js/date-option-validator.js')?>", function() {
                $.mage.dateOptionValidator({
                    dateOptionId: <?php echo $_optionId ?>,
                    inputFieldNamePrefix: 'validate_datetime_',
                    validationMessage: '<?php echo $this->jsQuoteEscape( Mage::helper('Mage_Catalog_Helper_Data')->__('Field is not complete') )?>'
                });
            });
    })(jQuery);
<?php endif; ?>
    //]]>
    </script>
</dd>
