<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>



<!--// Order/Create/Totals -->
    <table cellspacing="5" cellpadding="8" width="100%">
        <?php $_store = $this->getStore() ?>
        <tbody>
            <?php $_totals = $this->getTotals(); ?>
            <?php $_count = count($_totals); ?>
            <?php $_i = 0; ?>
            <?php foreach ($_totals as $_total): ?>
                <?php $_i++; ?>
                <tr class="<?php echo $_total->getCode() ?> <?php echo ($_i >= $_count ? ' last' : '' ) ?>">
                    <td class="a-left" style="<?php echo $_total->getStyle() ?>"><?php echo $_total->getTitle() ?></td>
                    <td class="last a-right" style="<?php echo $_total->getStyle() ?>"><span class="nobr"><?php echo $this->formatPrice($_total->getValue()) ?></span></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
	<div class="divider"></div>
    <p class="a-right">
        <input type="checkbox" id="send_confirmation" name="order[send_confirmation]" value="1" checked="true"/>
        <label for="send_confirmation" class="normal"><?php echo Mage::helper('sales')->__('Send Order Confirmation Email') ?></label>
    </p>
    <p class="a-right"><?php echo $this->getButtonHtml(Mage::helper('sales')->__('Submit Order'),'order.submit()'); ?></p>
<!--// [close] Order/Create/Totals -->