<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_item = $this->getItem() ?>
<?php $this->setPriceDataObject($_item)?>
<tr class="border">
    <td class="col-product"><?php echo $this->getColumnHtml($_item, 'downloadable') ?></td>
    <td class="col-price">
    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceExclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
        <span class="price-excl-tax">
                    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
              <span class="label"><?php echo __('Excl. Tax'); ?>:</span>
          <?php endif; ?>
          <?php echo $this->displayPriceAttribute('price') ?>
        </span>
    <?php endif; ?>
    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceInclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
        <span class="price-incl-tax">
          <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
              <span class="label"><?php echo __('Incl. Tax'); ?>:</span>
          <?php endif; ?>
          <?php if ($_item->getWeeeTaxAppliedAmount() && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 0, 'sales')): // including ?>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getPriceInclTax($_item)+$_item->getWeeeTaxAppliedAmount()); ?>
          <?php elseif ($_item->getWeeeTaxAppliedAmount() && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales')): // incl. + weee ?>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getPriceInclTax($_item)+$_item->getWeeeTaxAppliedAmount()); ?>
              <br />
              <small>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getPriceInclTax($_item)); ?>
              <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                  <span class="nobr">+ <?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($tax['amount'],true,true); ?></span><br />
              <?php endforeach; ?>
              </small>
          <?php elseif ($_item->getWeeeTaxAppliedAmount() && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales')): // excl. + weee + final ?>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getPriceInclTax($_item)); ?>
              <br />
              <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                  <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($tax['amount'],true,true); ?></small></span><br />
              <?php endforeach; ?>
              <span class="nobr">
              <?php echo __('Total'); ?>:
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getPriceInclTax($_item)+$_item->getWeeeTaxAppliedAmount()); ?>
              </span>
          <?php else: // excl. ?>
              <?php echo $this->displayPriceInclTax($_item); ?>
          <?php endif; ?>
        </span>
    <?php endif; ?>
    </td>
    <td class="col-qty"><?php echo $this->getColumnHtml($_item, 'qty') ?></td>
    <td class="col-qty-invoice">
    <?php if ($this->canEditQty()) : ?>
        <input type="text" class="input-text qty-input" name="invoice[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty()*1 ?>"/>
    <?php else : ?>
        <?php echo $_item->getQty()*1 ?>
    <?php endif; ?>
    </td>
    <td class="col-subtotal">
    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceExclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
        <span class="price-excl-tax">
                    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
              <span class="label"><?php echo __('Excl. Tax'); ?>:</span>
          <?php endif; ?>
          <?php echo $this->displayPriceAttribute('row_total') ?>
        </span>
    <?php endif; ?>
    <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartPriceInclTax() || Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
        <span class="price-incl-tax">
          <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayCartBothPrices()): ?>
              <span class="label"><?php echo __('Incl. Tax'); ?>:</span>
          <?php endif; ?>

          <?php if ($_item->getWeeeTaxAppliedRowAmount() && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 0, 'sales')): // including ?>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getSubtotalInclTax($_item)+$_item->getWeeeTaxAppliedRowAmount()); ?>
          <?php elseif ($_item->getWeeeTaxAppliedRowAmount() && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 1, 'sales')): // incl. + weee ?>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getSubtotalInclTax($_item)+$_item->getWeeeTaxAppliedRowAmount()); ?>
              <br />
              <small>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getSubtotalInclTax($_item)); ?>
              <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                  <span class="nobr">+ <?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($tax['row_amount'],true,true); ?></span><br />
              <?php endforeach; ?>
              </small>
          <?php elseif ($_item->getWeeeTaxAppliedRowAmount() && Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_item, 2, 'sales')): // excl. + weee + final ?>
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getSubtotalInclTax($_item)); ?>
              <br />
              <?php foreach (Mage::helper('Magento_Weee_Helper_Data')->getApplied($_item) as $tax): ?>
                  <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($tax['row_amount'],true,true); ?></small></span><br />
              <?php endforeach; ?>
              <span class="nobr">
              <?php echo __('Total'); ?>:
              <?php echo Mage::helper('Magento_Checkout_Helper_Data')->formatPrice(Mage::helper('Magento_Checkout_Helper_Data')->getSubtotalInclTax($_item)+$_item->getWeeeTaxAppliedRowAmount()); ?>
              </span>
          <?php else: // excl. ?>
              <?php echo $this->displaySubtotalInclTax($_item); ?>
          <?php endif; ?>
        </span>
    <?php endif; ?>
    </td>
    <td class="col-tax"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discount"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?php echo $this->displayPrices(
            $_item->getBaseRowTotal()+$_item->getBaseTaxAmount()-$_item->getBaseDiscountAmount(),
            $_item->getRowTotal()+$_item->getTaxAmount()-$_item->getDiscountAmount()+$_item->getWeeeTaxAppliedRowAmount()
        ) ?>
    </td>
</tr>
