<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this Magento_Reward_Block_Checkout_Payment_Additional */
?>
<?php if ($this->getCanUseRewardPoints()): ?>
<dl class="sp-methods checkout-reward checkout-multishipping-payment-reward" id="reward-block">
    <dt>
        <input type="checkbox" name="payment[use_reward_points]" value="1" id="use-reward-points"<?php echo $this->useRewardPoints()?' checked="checked"':'' ?> class="checkbox" />
        <label for="use-reward-points"><?php echo __('Use my reward points; %1 are available.', Mage::helper('Magento_Reward_Helper_Data')->formatReward($this->getPointsBalance(), $this->getCurrencyAmount())); ?></label>
    </dt>
</dl>

<script type="text/javascript">
    head.js(
        "<?php echo $this->getViewFileUrl('Magento_Customer::js/checkout-balance.js') ?>",
        function() {
            jQuery('#use-reward-points').checkoutBalance({
                amountSubstracted: <?php if ($this->useRewardPoints()): ?>true<?php else: ?>false<?php endif; ?>,
                usedAmount: <?php echo (float)$this->getQuote()->getBaseRewardCurrencyAmount(); ?>,
                balance: <?php echo (float)$this->getCurrencyAmount(); ?>
            });
        });
</script>
<?php endif; ?>
