<table cellpadding="0" cellspacing="0" border="0" id="<?=$this->getHtmlId()?>">
<tr>
	<td align="center" valign="middle"><?=$this->getHeader()?></td>
	<?foreach ( $data['analytics']['gValues'] as $gKey => $gVal ) { ?>
	<td class="g" rowspan="<?=$data['analytics']['yCount']?>">
		<div class="bottom-bg" style="height:<?=($gVal[0] > $gVal[1] ? $gVal[0] : $gVal[1] )?>px;">
			<?if( $data['analytics']['gType'] == 2 ){?>
			<dl class="gr1">
				<dt style="height:<?=$gVal[0]?>px;margin-top:<?=($gVal[0] > $gVal[1] ? 0 : ($gVal[1] - $gVal[0]) )?>px;">&nbsp;</dt>
				<dd style="height:<?=$gVal[1]?>px;margin-top:<?=($gVal[1] > $gVal[0] ? 0 : ($gVal[0] - $gVal[1]) )?>px;">&nbsp;</dd>
			</dl>
			<?}?>
		</div>
	</td>
	<?}?>
</tr>
<?foreach ( $data['analytics']['yValues'] as $yKey => $yVal ) {?>
<tr>
	<td class="y"><?=$yVal?></td>
</tr>
<?}?>
<tr>
	<td>&nbsp;</td>
	<?foreach ( $data['analytics']['xValues'] as $xKey => $xVal ) { ?>
	<td class="x"><?=$xVal?></td>
	<?}?>
	<td valign="bottom">&nbsp;&nbsp;<?=$data['analytics']['xHeading']?></td>
</tr>
</table>