<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="opc-wrapper">
    <div class="page-title">
        <?php echo $this->getChildHtml('checkoutCallout') ?>
        <h1><?php echo $this->__('Checkout') ?></h1>
    </div>
    <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Mage_Checkout::onepage/accordion.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getViewFileUrl('Mage_Checkout::opcheckout.js') ?>"></script>
    <div class="opc-progress-container" id="col-right-opcheckout">
        <?php echo $this->getChildHtml('checkoutProgress') ?>
    </div>
    <ol class="opc" id="checkoutSteps">
    <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
    <?php if (!$this->getChildBlock($_stepId) || !$this->getChildBlock($_stepId)->isShow()): continue; endif; $i++ ?>
        <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
            <div class="step-title">
                <span class="number"><?php echo $i ?></span>
                <h2><?php echo $_stepInfo['label'] ?></h2>
                <!--<a href="#"><?php echo $this->__('Edit') ?></a>-->
            </div>
            <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
                <?php echo $this->getChildHtml($_stepId) ?>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
    <script type="text/javascript">
    //<![CDATA[
        var accordion = new Accordion('checkoutSteps', '.step-title', true);
        <?php if($this->getActiveStep()): ?>
        accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
        <?php endif ?>
        var checkout = new Checkout(accordion,{
            progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
            review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
            saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
            failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
        );
    //]]>
    </script>
</div>
