<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /**  @var $this Mage_Adminhtml_Block_Catalog_Product_Attribute_New_Product_Created */ ?>
<script type="text/javascript">
var data = <?php echo $this->getAttributesBlockJson() ?>,
    attributeSet = (data.newAttributeSetId) ? {id:[data.newAttributeSetId]} : {id:$('#attribute_set_id').val()};
(function ($) {
    $('#product-edit-form').trigger('changeAttributeSet', attributeSet);
})(window.parent.jQuery);
</script>
<div class="a-center">
    <?php echo $this->getCloseButtonHtml() ?>
</div>