<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
        var data = <?php echo $this->getAttributesBlockJson() ?>;
        if (data.newAttributeSetId) {
            (function($) {
                $('#product-edit-form').trigger('changeAttributeSet', [data.newAttributeSetId]);
            })(window.opener.jQuery);
        } else {
            (function($) {
                $('#product-edit-form').trigger('addField', data);
            })(window.opener.jQuery);

            window.opener.Product.AttributesBridge.addAttributeRow(data);
            added = true;
        }
    }
</script>
<div class="a-center">
<?php echo $this->getCloseButtonHtml() ?>
</div>
