<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * "Remember Me" popup template (when click on "What's this?")
 *
 */
/** @var $this \Magento\Core\Block\Template */
?>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('Magento_Persistent::remember-me-popup.js') ?>",
            function() {
                $('#remember-me-box').rememberMePopup({
                    title: '<?php echo __('What is this?');?>',
                    content: '<?php echo __('Check &quot;Remember Me&quot; to access your shopping cart on this computer when you are logged out')?>'
                });
            });
    })(jQuery);
</script>
