<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Template for displaying wishlist item price at rss feeds pages
 *
 * @var $this \Magento\Catalog\Block\Product\Price
 */
?>
<div class="price-box map-info">
    <?php if ($this->helper('Magento\Catalog\Helper\Data')->canApplyMsrp($this->getProduct())): ?>
        <a href="<?php echo $this->getProduct()->getProductUrl() ?>"><?php echo __('Click for price'); ?></a>
    <?php endif; ?>
</div>
