<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright  {copyright}
 * @license    {license_link}
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @deprecated since 1.12.0.0
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="block filter">
    <div class="title">
        <strong><?php echo __('Shop By') ?></strong>
    </div>
    <div class="content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
        <div class="actions">
            <a href="<?php echo $this->getClearUrl() ?>" class="action reset"><?php echo __('Clear All') ?></a>
        </div>
        <?php endif; ?>
        <strong class="subtitle"><?php echo __('Shopping Options') ?></strong>
        <dl class="options" id="narrow-by-list">
            <?php $_filters = $this->getFilters() ?>
            <?php foreach ($_filters as $_filter): ?>
            <?php if($_filter->getItemsCount()): ?>
                <dt><?php echo __($_filter->getName()) ?></dt>
                <dd><?php echo $_filter->getHtml() ?></dd>
            <?php endif; ?>
            <?php endforeach; ?>
        </dl>
    </div>
</div>
<?php endif; ?>
