<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var $this \Magento\Reports\Block\Product\Viewed
 */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="block widget viewed links">
    <div class="title">
        <strong><?php echo __('Recently Viewed') ?></strong>
    </div>
    <div class="content">
        <?php $suffix = $this->getNameInLayout(); ?>
        <ol id="widget-viewed-<?php echo $suffix; ?>" class="items">
        <?php foreach ($_products as $_product): ?>
            <li class="item">
                <strong class="product name">
                    <a href="<?php echo $_product->getProductUrl() ?>">
                        <?php echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </strong>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
