<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            giftCard: [
                "<?php echo $this->getViewFileUrl('Magento_GiftCardAccount::js/gift-card.js') ?>"
            ],
            paymentMethod: [
                "<?php echo $this->getViewFileUrl('Magento_GiftCardAccount::js/payment-method.js') ?>"
            ]
        });
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>
