<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('Mage_Catalog_Helper_Output');
    $_nativeZoom = false;

?>


<?php if (!$_nativeZoom): ?>
<?php
/* --------- jqZoom --------- */
    $_zoomSize = $this->getVar('product_zoom_image_size', 'Mage_Catalog');
?>
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <?php list($_imgWidth, $_imgHeight) = $this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image')->getOriginalSizeArray(); ?>
        <?php if ($_imgWidth > $_zoomSize+10 && $_imgHeight > $_zoomSize+10):?>
            <div data-role="main-image-parent">
                <a class="product-image image-zoom" id="main-image" data-role="main-image-anchor" title="<?php echo $this->escapeHtml($_product->getImageLabel()); ?>" href="<?php echo $this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image'); ?>">
                    <?php
                    $_img = '<img data-role="base-image" src="'.$this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image')->resize($_zoomSize).'" height="'.$_zoomSize.'" width="'.$_zoomSize.'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                    ?>
                </a>
            </div>
            <script data-container="image-tmpl" type="text/x-jQuery-tmpl">
                <a class="product-image image-zoom" id="main-image"  data-role="main-image-anchor" title="<?php echo $this->escapeHtml($_product->getImageLabel()); ?>" href="<?php echo $this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image'); ?>">
                    <?php
                    $_img = '<img data-role="main-image" src="'.$this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image')->resize($_zoomSize).'" height="'.$_zoomSize.'" width="'.$_zoomSize.'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                    ?>
                </a>
                <img data-role="hidden-true-img" class="no-display" src="#"/>
            </script>
            <script type="text/javascript">
                jQuery(document).ready(function(){
                    var imgSize = <?php echo $_zoomSize?>;
                    var options = {
                        zoomType: 'reverse',//Values: standard, reverse
                        zoomWidth: 374,
                        zoomHeight: 327,
                        xOffset: 0,
                        yOffset: 50,
                        imageOpacity: 0.6,
                        title : false
                    };
                    jQuery('[data-role="main-image-anchor"]').jqzoom(options);
                    /* On these events, need to remove all elements associated with jqzoom
                    * add back the original element using jQuery template
                    * update image source and attach jqzoom
                    */
                    jQuery('[data-role="main-image-parent"]').on('imageChanged', function(event, data) {
                        jQuery('[data-role="main-image-anchor"]').remove();
                        jQuery('[data-container="image-tmpl"]').tmpl().appendTo('[data-role="main-image-parent"]');
                        jQuery('[data-role="main-image-anchor"]').attr('href', data).find('[data-role="main-image"]').attr('src', data);
                        // Hidden image element to get actual image size
                        jQuery('[data-role="hidden-true-img"]').attr('src', data).load(function() {
                            if (jQuery(this).height() <= imgSize && jQuery(this).width() <= imgSize) {
                                return;
                            }
                            jQuery('[data-role="main-image-anchor"]').jqzoom(options);
                        });
                    });
                    jQuery('[data-role="main-image-parent"]').on('loadOriginalImage', function(event, data) {
                        jQuery('[data-role="main-image-anchor"]').remove();
                        jQuery('[data-container="image-tmpl"]').tmpl().appendTo('[data-role="main-image-parent"]');
                        jQuery('[data-role="main-image-anchor"]').jqzoom(options);
                    });
                });
            </script>
            <p class="notice"><?php echo $this->__('Roll over image to zoom'); ?></p>
        <?php else: ?>
            <p class="product-image">
                <?php
                    $_img = '<img data-role="base-image" src="'.$this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image')->resize($_zoomSize).'" height="'.$_zoomSize.'" width="'.$_zoomSize.'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
            </p>
        <?php endif; ?>

    <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img data-role="base-image" src="'.$this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image')->resize($_zoomSize).'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>

<?php else: ?>

<?php /* --------- native magento zoom --------- */ ?>

    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <?php
                $_img = '<img data-role="base-image" id="image" src="'.$this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image').'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
        <p class="zoom-notice" id="track-hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
        <div class="zoom">
            <img id="zoom-out" src="<?php echo $this->getViewFileUrl('Mage_Catalog::images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
            <div id="slider"></div>
            <img id="zoom-in" src="<?php echo $this->getViewFileUrl('Mage_Catalog::images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
        </div>
    <script type="text/javascript">
        //<![CDATA[
        (function ($) {
            head.js("<?php echo $this->getViewFileUrl('Mage_Catalog::js/zoom.js')?>", function() {
                $('#image').zoom({
                    sliderSelector: '#slider',
                    zoomNoticeSelector: '#track-hint',
                    zoomInSelector: '#zoom-in',
                    zoomOutSelector: '#zoom-out'
                });
            });
        })(jQuery);
        //]]>
    </script>
    <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img data-role="base-image" src="'.$this->getBaseImageUrl($_product).'" alt="'.$this->escapeHtml($_product->getImageLabel()).'" title="'.$this->escapeHtml($_product->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>

<?php /* --------- /native magento zoom --------- */ ?>
<?php endif; ?>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
    <?php $_size = $this->getVar('product_base_image_icon_size', 'Mage_Catalog'); ?>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="#" data-mage-init="{popupWindow: {windowURL:'<?php echo $this->getGalleryUrl($_image) ?>',windowName:'gallery',width:300,height:300,status:1,scrollbars:1,resizable:1}}" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"><img src="<?php echo $this->helper('Mage_Catalog_Helper_Image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_size); ?>" width="<?php echo $_size?>" height="<?php echo $_size?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
