<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
var id = 0;
var authorTemplate =
    '<tr>'+
        '<td>'+
            '<input type="text" class="input-text required-entry" name="authors[name][]" id="authors_name_{{id}}" value="{{name}}"/>'+
        '</td>'+
        '<td>'+
            '<input type="text" class="input-text required-entry" name="authors[user][]" id="authors_user_{{id}}" value="{{user}}"/>'+
        '</td>'+
        '<td>'+
            '<input type="text" class="input-text required-entry validate-email" name="authors[email][]" id="authors_email_{{id}}" value="{{email}}"/>'+
        '</td>'+
        '<td class="col-delete">'+
            <?php echo $this->helper('\Magento\Core\Helper\Data')->jsonEncode($this->getRemoveRowButtonHtml('tr')) ?> +
        '</td>'+
    '</tr>';

function addAuthor(data)
{
    if (data == undefined) {
        data = {};
    }
    data.id = id++;

    var template = new Template(authorTemplate, /(^|.|\r|\n)({{(\w+)}})/);
    Element.insert($('authors_container'), {bottom: template.evaluate(data)});
}
</script>

<fieldset class="fieldset">
    <?php echo $this->getFormHtml() ?>
    <legend class="legend"><span><?php echo __("Authors") ?></span></legend>
    <br>
    <div id="authors_fieldset">
        <table class="data-table" cellspacing="0">
            <thead>
                <tr>
                    <th><?php echo __("Name") ?><span class="required">*</span></th>
                    <th><?php echo __("User") ?><span class="required">*</span></th>
                    <th><?php echo __("Email") ?><span class="required">*</span></th>
                    <th class="col-delete"><?php echo __("Remove") ?><span class="required">*</span></th>
                </tr>
            </thead>
            <tbody id="authors_container">
                <script type="text/javascript">
                <?php if (count($this->getAuthors())): ?>
                    <?php foreach ($this->getAuthors() as $author): ?>
                        addAuthor(<?php echo $author ?>);
                    <?php endforeach ?>
                <?php else: ?>
                    addAuthor();
                <?php endif;?>
                </script>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4"><?php echo $this->getAddAuthorButtonHtml() ?></td>
                </tr>
            </tfoot>
        </table>
    </div>
</fieldset>
