<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<div id="packed_window" style="display:none;" class="packed-window">
    <div class="popup-window-wrapper">
        <div class="popup-window-title">
            <span class="title"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Packages') ?></span>
        </div>
        <div class="packed-content">
            <div class="popup-window-content">
            <?php foreach ($this->getPackages() as $packageId => $package): ?>
                <div class="package">
                    <?php $package = new Magento_Object($package) ?>
                    <?php $params = new Magento_Object($package->getParams()) ?>
                    <div class="package-number popup-fieldset-title">
                        <div class="title"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Package') . ' ' . $packageId ?></div>
                    </div>
                    <div class="package-info">
                        <table class="package-options" cellspacing="0">
                            <tbody>
                                <tr>
                                    <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Type') ?></th>
                                    <td><?php echo $this->getContainerTypeByCode($params->getContainer()) ?></td>
                                    <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Length') ?></th>
                                    <td>
                                        <?php if ($params->getLength() != null): ?>
                                            <?php echo $params->getLength() .' '. $this->helper('Mage_Usa_Helper_Data')->getMeasureDimensionName($params->getDimensionUnits()) ?>
                                        <?php else: ?>
                                            --
                                        <?php endif; ?>
                                    </td>
                                    <?php if ($params->getDeliveryConfirmation() != null): ?>
                                        <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Signature Confirmation') ?></th>
                                        <td><?php echo $this->getDeliveryConfirmationTypeByCode($params->getDeliveryConfirmation()) ?></td>
                                    <?php else: ?>
                                        <th>&nbsp;</th>
                                        <td>&nbsp;</td>
                                    <?php endif; ?>
                                </tr>
                                <tr>
                                    <?php if ($this->displayCustomsValue()): ?>
                                        <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Customs Value') ?></th>
                                        <td><?php echo $this->displayCustomsPrice($params->getCustomsValue()) ?></td>
                                    <?php else: ?>
                                        <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Total Weight') ?></th>
                                        <td><?php echo $params->getWeight() .' '. $this->helper('Mage_Usa_Helper_Data')->getMeasureWeightName($params->getWeightUnits()) ?></td>
                                    <?php endif; ?>
                                    <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Width') ?></th>
                                    <td>
                                        <?php if ($params->getWidth() != null): ?>
                                            <?php echo $params->getWidth() .' '. $this->helper('Mage_Usa_Helper_Data')->getMeasureDimensionName($params->getDimensionUnits()) ?>
                                        <?php else: ?>
                                            --
                                        <?php endif; ?>
                                    </td>
                                    <?php if ($params->getContentType() != null): ?>
                                        <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Contents') ?></th>
                                        <?php if ($params->getContentType() == 'OTHER'): ?>
                                            <td><?php echo $this->escapeHtml($params->getContentTypeOther()) ?></td>
                                        <?php else: ?>
                                            <td><?php echo $this->getContentTypeByCode($params->getContentType()) ?></td>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <th>&nbsp;</th>
                                        <td>&nbsp;</td>
                                    <?php endif; ?>
                                </tr>
                                <tr>
                                    <?php if ($this->displayCustomsValue()): ?>
                                        <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Total Weight') ?></th>
                                        <td><?php echo $params->getWeight() .' '. $this->helper('Mage_Usa_Helper_Data')->getMeasureWeightName($params->getWeightUnits()) ?></td>
                                    <?php else: ?>
                                        <th>&nbsp;</th>
                                        <td>&nbsp;</td>
                                    <?php endif; ?>
                                    <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Height') ?></th>
                                    <td>
                                        <?php if ($params->getHeight() != null): ?>
                                            <?php echo $params->getHeight() .' '. $this->helper('Mage_Usa_Helper_Data')->getMeasureDimensionName($params->getDimensionUnits()) ?>
                                        <?php else: ?>
                                            --
                                        <?php endif; ?>
                                    <td>
                                    <th>&nbsp;</th>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr>
                                    <?php if ($params->getSize()): ?>
                                        <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Size') ?></th>
                                        <td><?php echo ucfirst(strtolower($params->getSize())) ?></td>
                                    <?php else: ?>
                                        <th>&nbsp;</th>
                                        <td>&nbsp;</td>
                                    <?php endif; ?>
                                    <?php if ($params->getGirth()): ?>
                                        <th><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Girth') ?></th>
                                        <td><?php echo $params->getGirth() .' '. $this->helper('Mage_Usa_Helper_Data')->getMeasureDimensionName($params->getGirthDimensionUnits()) ?></td>
                                    <?php else: ?>
                                        <th>&nbsp;</th>
                                        <td>&nbsp;</td>
                                    <?php endif; ?>
                                    <th>&nbsp;</th>
                                    <td>&nbsp;</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="package-number popup-fieldset-title">
                        <div class="title"><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Items in the Package') ?></div>
                    </div>
                    <div class="grid">
                        <table cellspacing="0" class="data">
                            <thead>
                            <tr class="headings">
                                <th class="col-product no-link"><span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Product') ?></span></th>
                                <th class="col-weight no-link"><span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Weight') ?></span></th>
                                <?php if ($this->displayCustomsValue()): ?>
                                    <th class="col-custom no-link"><span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Customs Value') ?></span></th>
                                <?php endif; ?>
                                <th class="col-qty_ordered no-link"><span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Qty Ordered') ?></span></th>
                                <th class="col-qty no-link last"><span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('Qty') ?></span></th>
                            </tr>
                            </thead>
                            <tbody id="">
                            <?php foreach($package->getItems() as $itemId => $item) : ?>
                                <?php $item = new Magento_Object($item) ?>
                                <tr title="#" id="" class="">
                                    <td class="col-product name">
                                        <?php echo $item->getName(); ?>
                                    </td>
                                    <td class="col-weight weight ">
                                        <?php echo $item->getWeight(); ?>
                                    </td>
                                    <?php if ($this->displayCustomsValue()): ?>
                                        <td class="col-custom "><?php echo $this->displayCustomsPrice($item->getCustomsValue()) ?></td>
                                    <?php endif; ?>
                                    <td class="col-qty_ordered">
                                        <?php echo $this->getQtyOrderedItem($item->getOrderItemId()); ?>
                                    </td>
                                    <td class="col-qty last">
                                        <?php echo $item->getQty()*1; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
        <div class="popup-window-buttons-set">
            <?php echo $this->getPrintButton() ?>
            <button type="button" class="action-ok SavePackagesBtn save" onclick="hidePackedWindow();" title="<?php echo $this->helper('Mage_Sales_Helper_Data')->__('Products should be added to package(s)')?>">
                <span><?php echo $this->helper('Mage_Sales_Helper_Data')->__('OK') ?></span>
            </button>
        </div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    function showPackedWindow() {
        var window = $('packed_window');
        window.show().setStyle({
            'marginLeft': -window.getDimensions().width/2 + 'px'
        });
        $('popup-window-mask').setStyle({
            height: $('html-body').getHeight() + 'px'
        }).show();
    }
    function hidePackedWindow() {
        $('packed_window').hide();
        $('popup-window-mask').hide();
    }
//]]>
</script>
