<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var \Magento\PageCache\Block\System\Config\Form\Field\Export $this */
?>
<script type="text/javascript">
    //<![CDATA[
    (function ($) {
        var fieldset = $('#system_full_page_cache_varnish'),
            fields = fieldset.find(':input:not(:hidden, button)');
        fields.each(function (e) {
            $(this).data('previous-value', $(this).val());
        });
        fieldset.on('change', function (e) {
            var invalidFields = fields.filter(function () {
                return ($(this).val().length == 0 || ($(this).val() != $(this).data('previous-value')));
            });
            $('#system_full_page_cache_varnish_export_button').prop('disabled', (invalidFields.length > 0));
        });
        $('#system_full_page_cache_ttl').on('change', function (e) {
            if ($(this).val() == '') {
                $(this).val('<?php echo $this->getTtlValue(); ?>');
            }
        });
    })(jQuery);
    //]]>
</script>