<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var \Magento\PageCache\Block\System\Config\Form\Field\Export $this */
?>
<script type="text/javascript">
    //<![CDATA[
    (function ($) {
        $('#system_full_page_cache_varnish').find(':input:not(:hidden, button)').on('focus', function(e) {
            $(this).attr('previous-data', $(this).val());
        });
        $('#system_full_page_cache_varnish').on('change', function(e) {
            var fields = $(this).find(':input:not(:hidden, button)').filter(function() {
                var input = $(this);
                var newValue = function(input) {
                    return input.val() !== input.attr('previous-data');
                };
                return (!$(this).val().length || newValue(input));
            });
            $('#system_full_page_cache_varnish_export_button').prop('disabled', fields);
        });
        $('#system_full_page_cache_ttl').on('change', function(e) {
            if(!$(this).val().length)
                $(this).val('<?php echo $this->getTtlValue(); ?>');
        });
    })(jQuery);
    //]]>
</script>