<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see Enterprise_GiftCardAccount_Block_Account_Redeem
 */
?>
<?php if ($this->canRedeem()): ?>
    <div class="account-balance">
        <h2 class="sub-title"><?php echo __('Redeem Gift Card'); ?></h2>
        <p><?php echo __('Have a gift card? <a href="%1">Click here</a> to redeem it.', Mage::getUrl('enterprise_giftcardaccount/customer')); ?></p>
    </div>
<?php endif; ?>
