<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/** @var \Magento\Bundle\Pricing\Render\FinalPriceBox $this */
$productId = $this->getSaleableItem()->getId();
/** @var \Magento\Bundle\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $this->getPrice();
?>
<?php if ($this->getSaleableItem()->getPriceView()): ?>
    <p class="minimal-price">
        <?php echo $this->renderAmount($finalPriceModel->getMinimalPrice(), [
            'display_label'     => __('As low as'),
            'price_id'          => $this->getPriceId('from-'),
            'include_container' => true
        ]); ?>
    </p>
<?php else: ?>
    <?php if ($this->showRangePrice()): ?>
        <p class="price-from">
            <?php echo $this->renderAmount($finalPriceModel->getMinimalPrice(), [
                'display_label'     => __('From'),
                'price_id'          => $this->getPriceId('from-'),
                'include_container' => true
            ]); ?>
        </p>
        <p class="price-to">
            <?php echo $this->renderAmount($finalPriceModel->getMaximalPrice(), [
                'display_label'     => __('To'),
                'price_id'          => $this->getPriceId('to-'),
                'include_container' => true
            ]); ?>
        </p>
    <?php else: ?>
        <?php echo $this->renderAmount($finalPriceModel->getMinimalPrice(), [
            'price_id'          => $this->getPriceId('product-price-'),
            'include_container' => true
        ]); ?>
    <?php endif ?>
<?php endif ?>
