<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Shipping_Drawer_OriginAddress */

$address = $this->getAddress();
?>
<h1><?php echo $this->helper('Mage_Launcher_Helper_Data')->__('Your Business Address'); ?></h1>
<div id="shipping-origin-address-view" style="<?php if ($address['show_form']): ?>display:none;<?php endif; ?>">
    <div class="entry-edit">
        <?php foreach ($address['data'] as $addressValue): ?>
            <?php if (!empty($addressValue)) :?>
                <p><?php echo $this->escapeHtml($addressValue); ?></p>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <a href="" id="shipping-origin-address-edit"><?php echo $this->helper('Mage_Launcher_Helper_Data')->__('Edit'); ?></a>
</div>
<div id="shipping-origin-address-form" style="<?php if (!$address['show_form']): ?>display:none;<?php endif; ?>">
    <div class="entry-edit">
        <?php echo $this->getFormHtml(); ?>
    </div>
    <?php echo $this->getChildHtml('form_after'); ?>
    <button type="button" id="button-origin-address-save" class="button"
        data-save-url="<?php echo $this->getUrl('*/storelauncher_shipping_drawer/saveOriginAddress') ?>">
        <?php echo $this->helper('Mage_Launcher_Helper_Data')->__('Save'); ?>
    </button>
    <button type="button" id="button-origin-address-cancel" class="button">
        <?php echo $this->helper('Mage_Launcher_Helper_Data')->__('Cancel'); ?>
    </button>
</div>
<script id="addressTemplate" type="text/x-jquery-tmpl">
    <p>${street_line1}</p>
    <p>${street_line2}</p>
    <p>${city}</p>
    <p>${postcode}</p>
    <p>${country}</p>
    <p>${region}</p>
</script>
<script type="text/javascript">
    (function ($) {
        var originAddressView = $('#shipping-origin-address-view'),
            originAddressForm = $('#shipping-origin-address-form'),
            originAddressLink = $('#shipping-origin-address-edit'),
            originAddressEditSwitchOff = function () {
                originAddressForm.hide();
                originAddressView.show();
            },
            originAddressEditSwitchOn = function () {
                    originAddressView.hide();
                    originAddressForm.show();
            };
        $('#button-origin-address-save').on('click.OriginAddressSave', function (event) {
            event.preventDefault();
            var drawerForm = $('#drawer-form').validation();

            if (!drawerForm.valid()) {
                return;
            }

            $.ajax({
                type: 'POST',
                data: drawerForm.serializeArray(),
                dataType: 'json',
                showLoader: true,
                context: originAddressForm,
                url: $(this).attr('data-save-url')
            }).success(function(result, status) {
                if (result && result.error_message) {
                    alert(result.error_message);
                } else {
                    var address = [{
                        street_line1: $('#street_line1').val(),
                        street_line2: $('#street_line2').val(),
                        city: $('#city').val(),
                        postcode: $('#postcode').val(),
                        country: $('#country_id option:selected').text(),
                        region: $('#region_id option:selected').text()
                    }];
                    originAddressView.children('div').html($("#addressTemplate").tmpl(address));
                    originAddressEditSwitchOff();
                }
            });
        });
        $('#button-origin-address-cancel').on('click.OriginAddressCancel', function (event) {
            event.preventDefault();
            originAddressEditSwitchOff();
        });
        originAddressLink.on('click.OriginAddressEdit', function (event) {
            event.preventDefault();
            originAddressEditSwitchOn();
        });
    })(jQuery);
</script>