<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Launcher
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Launcher_Block_Adminhtml_Storelauncher_Tax_Drawer */
?>
<form action="" id="drawer-form" method="post">
    <?php echo $this->getBlockHtml('formkey')?>
    <fieldset class="fieldset active">

        <div id="field-mange-tax" class="field choice">
            <input id="mange-tax" name="use_tax" type="radio" checked="checked" value="1">
            <label class="label" for="mange-tax"><span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('Manage Tax Rules') ?></span></label>
        </div>

        <?php echo $this->getChildHtml('tax-rule-edit');?>
        <?php echo $this->getChildBlock('tax-rule-form')->setUseContainer(false)->toHtml();?>

        <div id="field-import-tax-rates" class="field choice">
            <input id="import-tax-rates" type="checkbox">
            <label class="label" for="import-tax-rates"><span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('I want to upload an existing file with Tax rates (CSV Format)') ?></span></label>
        </div>

        <?php echo $this->getChildBlock('tax-rate-importExport')->setUseContainer(false)->toHtml();?>

    </fieldset>

    <fieldset class="fieldset">
        <div class="tax-rule">
            <div id="field-no-tax" class="field choice">
                <input id="no-tax" name="use_tax" type="radio" value="0">
                <label class="label" for="no-tax"><span><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('No Tax') ?></span></label>
            </div>
        </div>
        <div class="tax-rules-config">
            <p><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__("I don't require tax rules. (Consult your local laws regarding taxes)") ?></p>
        </div>
    </fieldset>
</form>

<?php echo $this->getChildHtml('tax-rate-form'); ?>

<script type="text/javascript">
    (function ($) {
        $(document).ready(function () {
            'use strict';
            var drawerForm = $('form#drawer-form'),
                importForm = $('#import-tax-rates')
                .on('click.importTaxRates', function () {
                    var elem = $(this),
                        importForm = elem.parent().next();
                    elem.is(':checked') ? importForm.fadeIn(200) : importForm.fadeOut(200);
                });
            importForm.is(':checked') ? importForm.parent().next().show() : importForm.parent().next().hide();
            $('form#drawer-form input[name="use_tax"]').on('change.use_tax', function (el) {
                $('form#drawer-form input[name="use_tax"]:checked').each(function (radio) {
                    $(radio).parent().parent().parent().removeClass('active');
                });
                $(el).parent().parent().parent().addClass('active');
                if ($('#no-tax').is(':checked')) {
                    drawerForm.addClass('ignore-validate');
                } else {
                    drawerForm.removeClass('ignore-validate');
                }
            });
        });
    })(window.jQuery);
</script>
