<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="entry-edit">
    <!-- Import Tax Rates -->
    <?php if (!$this->getIsReadonly()): ?>

    <div class="box-left">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Import Tax Rates'); ?></h4>
        </div>
        <fieldset>
            <legend><?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Import Tax Rates'); ?></legend>
            <ul class="messages" style="display: none;">
                <li class="error-msg" id="import-rate-errors"></li>
            </ul>
            <span class="fileinput-button">
                <span><?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Import CSV File'); ?></span>
                <input type="file" id="import_rates_file" name="import_rates_file" class="input-file" data-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/importTaxRates'); ?>" />
            </span>
        </fieldset>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        (function ($) {
            $('#import_rates_file').fileupload({
                dataType: 'json',
                formData: {
                    isAjax: 'true',
                    form_key: FORM_KEY
                },
                sequentialUploads: false,
                done: function(e, data) {
                    if (data.result.success == true) {
                        updateTaxRateMultiselect(data.result);
                    } else {
                        showTaxRateImportMessage(data.result.error_message);
                    }
                    return;
                },
                fail: function(e, data) {
                    showTaxRateImportMessage('<?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('There was an error processing your request.'); ?>');
                    return;
                },
                add: function(e, data) {
                    $('#import-rate-errors').parent().hide();
                    $(this).fileupload('process', data).done(function () {
                        data.submit();
                    });
                    return;
                }
            });

            /**
             * Show tax rate import error message
             *
             * @param message
             */
            var showTaxRateImportMessage = function(message)
            {
                var messageContainer = $('#import-rate-errors');
                messageContainer.text(message);
                messageContainer.parent().show();
                return;
            }

            /**
             * Refresh tax Rate Field
             *
             * @param Array import rates request result
             */
            var updateTaxRateMultiselect = function(result) {
                var taxSection = $('#tax_rate').parent().parent(),
                    previousSection = taxSection.prev();
                taxSection.remove();
                // Next variable is global for tax rule page and is used in edit tax rate pop-up
                taxRateCollection = result.tax_rate_collection;
                previousSection.after(result.tax_rate_field);
                return;
            }
        }(jQuery));
    //]]>
    </script>



    <!-- Export Tax Rates -->
    <div class="box-right">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Export Tax Rates'); ?></h4>
        </div>
        <fieldset>
            <legend><?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Export Tax Rates'); ?></legend>
            <a href="<?php echo $this->getUrl('adminhtml/tax_rate/exportPost'); ?>"><?php echo Mage::helper('Mage_Launcher_Helper_Data')->__('CSV Format Guidelines'); ?></a>
        </fieldset>
    </div>
    <div class="clear"></div>

    <?php endif; ?>
</div>
