<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('Mage_Catalog_Helper_Data')->__('Update attributes') ?></h3></td>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getCancelButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="attributes_edit_form" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    jQuery('#attributes_edit_form').form().validation({validationUrl: '<?php echo $this->getValidationUrl() ?>'});
//var attributesForm = new varienForm('attributes_edit_form', '<?php echo $this->getValidationUrl() ?>');
/*attributesForm._processValidationResult = function(transport) {
    var response = transport.responseText.evalJSON();

    if (response.error){
        if (response.attribute && $(response.attribute)) {
            $(response.attribute).setHasError(true, attributesForm);
            Validation.ajaxError($(response.attribute), response.message);
            if (!Prototype.Browser.IE){
                $(response.attribute).focus();
            }
        } else if ($('messages')) {
            $('messages').innerHTML = '<ul class="messages"><li class="error-msg"><ul><li>' + response.message + '</li></ul></li></ul>';
        }
    } else {
        attributesForm._submit();
    }
};*/
</script>
