<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product additional attributes template
 *
 * @see \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
<table class="data table product attributes" id="product-attribute-specs-table">
    <tbody>
    <?php foreach ($_additional as $_data): ?>
        <tr>
            <th class="col label"><?php echo $this->escapeHtml(__($_data['label'])) ?></th>
            <td class="col data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>
