<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product media data template
 *
 * @see \Magento\Catalog\Block\Product\View\Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');

    //list($_imgWidth, $_imgHeight) = $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image')->getOriginalSizeArray();

    $image = 'product_page_main_image';

    $_resizedWidth = $this->getVar("{$image}:width");
    $_resizedHeight = $this->getVar("{$image}:height") ?: $_resizedWidth ;

    $_hasImage = ($_product->getImage() && $_product->getImage() != "no_selection") ? true : false;

    //$_isOldDisplayMode = $this->getOldDisplayMode() || 0;
    $_isOldDisplayMode = 0;
    $whiteBorders =  $this->getVar("product_image_white_borders");
?>
<?php //if($whiteBorders == 0): ?>
    <style scoped>
    .magento-zoom > .img > img {
        position:absolute;
        top:0; bottom:0; left:0; right:0; margin:auto; max-height: 100%; max-width: 100%;
    }
    </style>
<?php //endif; ?>
<div class="product photo main">
    <a class="product photo magento-zoom<?php echo (!$_hasImage) ? ' isPlaceholder' : ''; ?>"
       id="base-image" data-role="base-image-zoom"
       href="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image'); ?>" >
        <?php echo $this->getChildBlock('product.image.main')->init($_product, $image)->toHtml() ?>
    </a>
<?php  ?>
    <script type="text/javascript">
        jQuery('[data-role=base-image-zoom]').attr('rel', '<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image'); ?>');
    </script>

    <p class="notice"></p>

    <script type="text/javascript">
        jQuery(function(){
            <?php if ($_isOldDisplayMode): ?>
                jQuery('.magento-zoom').magentoZoom({
                    useGallery: false,
                    swapNotices: false,
                    isOldMode: <?php print $_isOldDisplayMode; ?>,
                    messages: {
                        noticeDefault: '<?php echo $this->jsQuoteEscape(__("Click on image to zoom")) ?>',
                        loadingMessage: '<?php echo $this->jsQuoteEscape(__("Loading...")) ?>'
                    }
                });
            <?php else: ?>
                jQuery('.magento-zoom').magentoZoom({
                    useLens: true,
                    enlarged: {
                        adjustment: 20,
                        width: 500,
                        height: <?php echo $_resizedHeight ?>
                    },
                    useGallery: true,
                    swapNotices: true,
                    isOldMode: <?php print $_isOldDisplayMode; ?>,
                    messages: {
                        noticeDefault: '<?php echo $this->jsQuoteEscape(__("Click on image to zoom")) ?>',
                        noticeLightBox: '<?php echo $this->jsQuoteEscape(__("Click on image to view it full sized")) ?>', loadingMessage: '<?php echo $this->jsQuoteEscape(__("Loading...")) ?>'
                    }
                });
            <?php endif; ?>
        });
    </script>
<?php  ?>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>

<?php
    $thumbWidth =  $this->getVar("product_page_more_views:width");
    $thumbHeight =  $this->getVar("product_page_more_views:height") ? : $thumbWidth;
?>
<div class="product photo thumbs">
    <strong class="title"><?php echo __('More Views') ?></strong>
    <ul class="items thumbs">
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <?php if ($_isOldDisplayMode) {
                $attributes = ' href="#" data-mage-popwin="{windowURL:'
                    . $this->getGalleryUrl($_image)
                    . ',windowName:\'gallery\',width:300,height:300,status:1,scrollbars:1,resizable:1}"';
            } else {
                $attributes = ' href="'
                    . $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image', $_image->getFile())
                    . '" rel="';
                if ($whiteBorders) {
                    $attributes .= $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image', $_image->getFile())->resize($_resizedWidth,$_resizedHeight) . '"';
                } else {
                    $attributes .= $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image', $_image->getFile())->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($_resizedWidth,$_resizedHeight) . '"';
                }
        };?>
        <li class="item thumb">
            <a<?php echo $attributes; ?> class="magento-zoom" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
            <?php if ($whiteBorders): ?>
                <span class="img" style="position:relative; z-index:1; display:block; width:<?php echo $thumbHeight;?>px; height:<?php echo $thumbHeight;?>px;">
                <img src="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'thumbnail', $_image->getFile())->resize($thumbWidth,$thumbHeight); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                </span>
            <?php else: ?>
                <span class="img" style="position:relative; z-index:1; display:block; width:<?php echo $thumbHeight;?>px; height:<?php echo $thumbHeight;?>px;">
                    <img src="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'thumbnail', $_image->getFile())->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($thumbWidth,$thumbHeight); ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                </span>
            <?php endif; ?>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
    <?php if ($_isOldDisplayMode): ?>
    <script type="text/javascript">
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('jquery/jquery.popupwindow.js')?>",
                "<?php echo $this->getViewFileUrl('mage/popup-window.js')?>"
            );
        })(jQuery);
    </script>
    <?php endif; ?>
<?php endif; ?>
