<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright  {copyright}
 * @license    {license_link}
 */

/**
 * @var $this \Magento\Page\Block\Html\Title
 */
$titleId = ($this->getTitleId()) ? ' id="' . $this->getTitleId() . '"' : '';
$titleClass = ($this->getTitleClass()) ? ' ' . $this->getTitleClass() : '';
$titlePrefix = ($this->getTitlePrefix()) ? '<span class="page-title-prefix">' . $this->getTitlePrefix() . '</span>' : '';
$titleSuffix = ($this->getTitleSuffix()) ? '<span class="page-title-suffix">' . $this->getTitleSuffix() . '</span>' : '';
$title = $titlePrefix . $this->escapeHtml($this->getPageTitle()) . $titleSuffix;
?>
<div class="page-title<?php echo $titleClass; ?>">
    <div class="page-title-inner">
        <h1 class="title"<?php echo $titleId?>><?php echo $title ?></h1>
        <?php echo $this->getChildHtml(); ?>
    </div>
</div>
