<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/* @var $this Magento_MultipleWishlist_Block_Customer_Wishlist_Item_Column_Management  */
/* @var $item Magento_Wishlist_Model_Item  */
$item = $this->getItem();
?>
<div class="split button">
    <span class="label" <?php if ($this->getDefaultWishlist()->getId() != $this->getCurrentWishlist()->getId()): ?> data-wishlist-move-item='{"itemId":"<?php echo $item->getId();?>", "wishlistId":"<?php echo $this->getDefaultWishlist()->getId();?>"}'<?php endif;?>><?php echo __('Move to Wish List');?></span>
    <span class="action change" title="<?php echo __('Move to:') ?>" data-toggle="dropdown"><span><?php echo __('Move to:') ?></span></span>
    <ul class="items" data-target="dropdown">
        <?php foreach ($this->getWishlists() as $wishlist): ?>
            <?php if ($wishlist->getId() !== $this->getWishlistInstance()->getId()): ?>
                <li class="item"><span data-wishlist-move-item='{"itemId":"<?php echo $item->getId();?>", "wishlistId":"<?php echo $wishlist->getId();?>"}' title="<?php echo $this->escapeHtml($wishlist->getName());?>"><?php echo $this->escapeHtml($wishlist->getName());?></span></li>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
            <li class="item new"><span data-wishlist-move-item='{"itemId":"<?php echo $item->getId();?>", "new":true}' title="<?php echo __('Create New Wish List')?>"><?php echo __('Create New Wish List')?></span></li>
        <?php endif;?>
    </ul>
</div>
<div class="split button">
    <span class="label" <?php if ($this->getDefaultWishlist()->getId() != $this->getCurrentWishlist()->getId()): ?> data-wishlist-copy-item='{"itemId":"<?php echo $item->getId();?>", "wishlistId":"<?php echo $this->getDefaultWishlist()->getId();?>"}'<?php endif;?>><?php echo __('Copy to Wish List');?></span>
    <span class="action change" title="<?php echo __('Copy to:') ?>" data-toggle="dropdown"><span><?php echo __('Copy to:') ?></span></span>
    <ul class="items" data-target="dropdown">
        <?php foreach ($this->getWishlists() as $wishlist): ?>
            <?php if ($wishlist->getId() !== $this->getWishlistInstance()->getId()): ?>
                <li class="item"><span  data-wishlist-copy-item='{"itemId":"<?php echo $item->getId();?>", "wishlistId":"<?php echo $wishlist->getId();?>"}' title="<?php echo $this->escapeHtml($wishlist->getName());?>"><?php echo $this->escapeHtml($wishlist->getName());?></span></li>
            <?php endif; ?>
        <?php endforeach;?>
        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
            <li class="item new"><span data-wishlist-copy-item='{"itemId":"<?php echo $item->getId();?>", "new":true}' title="<?php echo __('Create New Wish List')?>"><?php echo __('Create New Wish List')?></span></li>
        <?php endif;?>
    </ul>
</div>
