<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    /* @var $this \Magento\MultipleWishlist\Block\Behaviour */
?>
<script id="form-tmpl-multiple" type="text/x-jQuery-tmpl">
    <form id="wishlist-hidden-form" method="post" action="${url}" class="no-display">
        {{if itemId}}<input name="item_id" value="${itemId}">{{/if}}
        {{if wishlistId}}<input name="wishlist_id" value="${wishlistId}">{{/if}}
        {{if qty}}<input name="qty" value="${qty}">{{/if}}
        {{if item}}<input name="item" value="${item}">{{/if}}
        {{if entity}}<input name="entity" value="${entity}">{{/if}}
    </form>
</script>
<script id="popup-tmpl" type="text/x-jQuery-tmpl">
    <div class="window wishlist overlay active"></div>
    <div id="${popupWishlistBlockId}" class="window wishlist popup active">
        <div class="popup-actions">
            <div class="secondary">
                <button type="button" title="${$.mage.__('Close')}" class="action close ${btnCloseClass}" data-dismiss="popup"><span>${$.mage.__('Close')}</span></button>
            </div>
        </div>
        <div class="popup-header">
             <strong class="title" id="popup-title"><span>{{if isEdit}}${$.mage.__('Edit Wish List')}{{else}}${$.mage.__('Create New Wish List')}{{/if}}</span></strong>
        </div>
        <div class="popup-content" id="popup-content">
            <form id="${popupWishlistFormId}" method="post" action="${url}" class="form wishlist">
                <fieldset class="fieldset">
                    <div class="field name">
                        <label for="wishlist-name" class="label"><span>${$.mage.__('Wish List Name')}</span></label>
                        <div class="control">
                            <input id="wishlist-name" class="input-text" data-validate="{required:true}" type="text" name="name" maxlength="255" value="${name}">
                        </div>
                    </div>
                    <div class="field choice">
                        <input id="wishlist-public" type="checkbox" name="visibility"{{if isPublic}} checked=true{{/if}}">
                        <label for="wishlist-public" class="label"><span>${$.mage.__('Public Wish List')}</span></label>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button class="action save primary" type="submit" title="${$.mage.__('Save')}">
                                <span>${$.mage.__('Save')}</span>
                            </button>
                        </div>
                        <div class="secondary">
                            <button class="action cancel ${btnCloseClass}" type="button" title="${$.mage.__('Cancel')}">
                                <span>${$.mage.__('Cancel')}</span>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</script>
<script id="split-btn-tmpl" type="text/x-jQuery-tmpl">
    <div class="split button wishlist">
        <button data-post='${JSON.stringify(generalParams)}' data-action="add-to-wishlist" class="label action split">
            <span>${buttonName}</span>
        </button>
        <button class="action toggle change" title="${$.mage.__('Add to:')}" data-toggle="dropdown" aria-haspopup="true">
            <span>${$.mage.__('Add to:')}</span>
        </button>
        <ul class="items" data-target="dropdown">
            {{each wishlists}}
            <li class="item">
                {{if newClass}}
                    <span class="action ${newClass}" data-post-new-wishlist='${JSON.stringify(params)}' data-action="add-to-wishlist" title="${name}"><span>${name}</span></span>
                {{else}}
                    <span data-post='${JSON.stringify(params)}' data-action="add-to-wishlist" title="${name}">${name}</span>
                {{/if}}
            </li>
            {{/each}}
        </ul>
    </div>
</script>
<?php
    $canCreateWishlist = $this->canCreateWishlists($this->getWishlists());
    $shortWishList = $this->getWishlistShortList();
    if ($canCreateWishlist || !empty($shortWishList)):
?>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage',
    'mage/dropdowns'
], function(jQuery){

    <?php if (count($this->getWishlistShortList()) > 0): ?>
    (function($) {
        $('body').mage('multipleWishlist', {
            'canCreate': <?php echo $this->canCreateWishlists($this->getWishlists()) ? 'true' : 'false';?>,
            'createUrl': '<?php echo $this->getCreateUrl();?>',
            'wishlists': <?php echo $this->helper('Magento\Core\Helper\Data')->jsonEncode($shortWishList);?>,
            'wishlistLink': '.action.towishlist'
        });
        $('.products.list [data-toggle=dropdown]')
            .add('.cart.items.data [data-toggle=dropdown]')
            .add('.product-addto-links [data-toggle=dropdown]')
            .add('.secondary-addto-links.actions-secondary [data-toggle=dropdown]')
            .dropdown({
                events: [{
                    'name': 'mouseleave',
                    'selector': '.item.product',
                    'action': function() {
                        var triggerElem = $('[data-toggle=dropdown]', this);
                        triggerElem.hasClass('active') && triggerElem.trigger('click.toggleDropdown');
                    }
                }]
            });
    }(jQuery));
    <?php endif; ?>

});
</script>
<?php endif; ?>
