<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright  {copyright}
 * @license    {license_link}
 */
?>
<?php /** @var $this Mage_Adminhtml_Block_Api_Tab_Roleinfo */ ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-permissions-role">
                    <?php echo $this->getCaption() ?>
                </h3>
            </td>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getResetButtonHtml() ?>
            <?php echo $this->getDeleteButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="role-edit-form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    jQuery('#role-edit-form').form().validation();
</script>
