<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var \Magento\Search\Block\Suggestions $this
 */
?>
<?php
/** @var \Magento\Search\Model\QueryResult[] $suggestions */
$suggestions = $this->getSuggestions();
if (count($suggestions)): ?>
    <dl class="block recommendations">
        <dt class="title"><?php echo __('Did you mean'); ?></dt>
        <?php foreach ($suggestions as $suggestion) : ?>
            <dd class="item">
                <a href="<?php echo $this->getLink($suggestion->getQueryText()) ?>"
                    ><?php echo $suggestion->getQueryText() ?></a>
                <?php if ($this->isCountResultsEnabled()): ?>
                    <span class="count"><?php echo $suggestion->getResultsCount() ?></span>
                <?php endif; ?>
            </dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>
