<div class="content-header">
    <table cellspacing="0" class="grid-header"> 
        <tr>
            <td style="width:30%;"><h3><?=$this->getHeader()?></h3></td>
            <td class="a-right">
            <?if($this->getCategoryId()):?>
            <button class="scalable" onclick="categoryDelete();return false;">
                <table cellspacing="0">
                    <tr>
                        <td class="tl"></td>
                        <td class="tr"></td>
                    </tr>
                    <tr>
                        <td class="ml"><?=__('Delete Category')?></td>
                        <td class="mr"></td>
                    </tr>
                    <tr>
                        <td class="bl"></td>
                        <td class="br"></td>
                    </tr>
                </table>
            </button>
            <?endif;?>
            <button class="scalable" onclick="categoryForm.submit();return false;">
                <table cellspacing="0">
                    <tr>
                        <td class="tl"></td>
                        <td class="tr"></td>
                    </tr>
                    <tr>
                        <td class="ml"><?=__('Save Category')?></td>
                        <td class="mr"></td>
                    </tr>
                    <tr>
                        <td class="bl"></td>
                        <td class="br"></td>
                    </tr>
                </table>
            </button>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="post" id="category_edit_form">
<div class="content-left-nav">
    <?=$this->getChildHtml('tabs')?>
</div>
<div class="entry-edit" id="category_tab_content">
</div>
</form>
<script type="text/javascript" language="javascript">
    var categoryForm = new varienForm('category_edit_form');
    
    function categoryDelete(){
        if(confirm('<?=__('Are you sure?')?>')){
            location.href = '<?=$this->getDeleteUrl()?>'
        }
    }
</script>
