<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this \Magento\Downloadable\Block\Catalog\Product\Links */ ?>
<?php $_linksPurchasedSeparately = $this->getLinksPurchasedSeparately(); ?>
<?php if ($this->getProduct()->isSaleable() && $this->hasLinks()):?>
    <?php $_links = $this->getLinks(); ?>
    <?php $_isRequired = $this->getLinkSelectionRequired(); ?>
    <div class="field downloads<?php if ($_isRequired) echo ' required' ?>">
        <label class="label"><span><?php echo $this->getLinksTitle() ?></span></label>
        <div class="control" id="downloadable-links-list">
            <?php foreach ($_links as $_link): ?>
            <div class="field choice">
                <?php if ($_linksPurchasedSeparately): ?>
                <input type="checkbox" <?php if ($_isRequired): ?>data-validate="{'validate-one-checkbox-required-by-name':'downloadable-links-list'}" <?php endif; ?>
                       name="links[]" id="links_<?php echo $_link->getId() ?>"
                       value="<?php echo $_link->getId(); ?>" <?php echo $this->getLinkCheckedValue($_link); ?> />
                <?php endif; ?>
                <label class="label" for="links_<?php echo $_link->getId() ?>">
                    <span><?php echo $this->escapeHtml($_link->getTitle()); ?></span>
                    <?php if ($_link->getSampleFile() || $_link->getSampleUrl()): ?>
                        <a class="sample" href="<?php echo $this->getLinkSamlpeUrl($_link) ?>" <?php echo $this->getIsOpenInNewWindow() ? 'target="_blank"' : ''; ?>><?php echo __('sample') ?></a>
                    <?php endif; ?>
                    <?php if ($_linksPurchasedSeparately): ?>
                    <?php echo $this->getFormattedLinkPrice($_link); ?>
                    <?php endif; ?>
                </label>
            </div>
            <?php endforeach; ?>
        </div>
        <?php if ($_isRequired): ?>
            <span id="links-advice-container"></span>
        <?php endif;?>
    </div>
    <script type="text/javascript">
        (function ($) {
            head.js("<?php echo $this->getViewFileUrl('Magento_Downloadable::downloadable.js') ?>", function () {
                $('#downloadable-links-list').downloadable({
                    linkElement: 'input:checkbox',
                    config: <?php echo $this->getJsonConfig() ?>
                });
            });
    })(jQuery);
</script>
<?php endif; ?>
