<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Store switcher template
 *
 * @see Magento_Core_Block_Store_Switcher
 */
?>
<?php if(count($this->getGroups())>1): ?>
    <li id="store-switcher">
        <a href="#"><?php echo __('Selected Store') ?>: <span id="current-store"></span></a>
        <ol class="switcher-options" style="display:none;">
            <?php foreach ($this->getGroups() as $_group): ?>
            <?php $_selected = ($_group->getId() == $this->getCurrentGroupId()) ? ' class="selected"' : '' ?>
            <li<?php echo $_selected ?>>
                <a href="<?php echo $_group->getCurrentUrl() ?>"><?php echo $this->escapeHtml($_group->getName()) ?></a>
            </li>
            <?php endforeach; ?>
        </ol>
    </li>
<?php endif; ?>
