<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this Magento_Checkout_Block_Onepage_Progress */
?>
<div class="block block-progress opc-block-progress">
    <div class="block-title">
        <strong><span><?php echo __('Your Checkout Progress') ?></span></strong>
    </div>
    <div class="block-content">
        <dl>
        <?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
        <?php if ($this->isStepComplete('billing')): ?>
            <dt class="complete">
                <?php echo __('Billing Address') ?> <span class="separator">|</span>
                <a href="#billing" data-goto-section="billing"><?php echo __('Change') ?></a>
            </dt>
            <dd class="complete">
                <address><?php echo $this->getBilling()->format('html') ?></address>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo __('Billing Address') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
        <?php if ($this->isStepComplete('shipping')): ?>
            <dt class="complete">
                <?php echo __('Shipping Address') ?> <span class="separator">|</span>
                <a href="#payment" data-goto-section="shipping"><?php echo __('Change') ?></a>
            </dt>
            <dd class="complete">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo __('Shipping Address') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
        <?php if ($this->isStepComplete('shipping_method')): ?>
            <dt class="complete">
                <?php echo __('Shipping Method') ?> <span class="separator">|</span>
                <a href="#shipping_method" data-goto-section="shipping_method"><?php echo __('Change') ?></a>
            </dt>
            <dd class="complete">
                <?php if ($this->getShippingMethod()): ?>
                    <?php echo $this->escapeHtml($this->getShippingDescription()) ?>

                    <?php $_excl = $this->getShippingPriceExclTax(); ?>
                    <?php $_incl = $this->getShippingPriceInclTax(); ?>
                    <?php if ($this->helper('Magento_Tax_Helper_Data')->displayShippingPriceIncludingTax()): ?>
                        <?php echo $_incl; ?>
                    <?php else: ?>
                        <?php echo $_excl; ?>
                    <?php endif; ?>
                    <?php if ($this->helper('Magento_Tax_Helper_Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo __('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo __('Shipping method has not been selected yet') ?>
                <?php endif; ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo __('Shipping Method') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
        <?php if ($this->isStepComplete('payment')): ?>
            <dt class="complete">
                <?php echo __('Payment Method') ?> <span class="separator">|</span>
                <a href="#payment" data-goto-section="payment"><?php echo __('Change') ?></a>
            </dt>
            <dd class="complete">
                <?php echo $this->getPaymentHtml() ?>
            </dd>
        <?php else: ?>
            <dt>
                <?php echo __('Payment Method') ?>
            </dt>
        <?php endif; ?>
        <?php endif; ?>
        </dl>
    </div>
</div>
