<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Invitaion view block template
 *
 * @see Enterprise_Invitation_Block_Adminhtml_Invitation_View
 */
?>
<div class="content-header">
    <?php echo $this->getHeaderHtml(); ?>
    <p class="content-buttons form-buttons">
        <?php echo $this->getButtonsHtml(); ?>
    </p>
</div>
<form id="invitation_elements" action="<?php echo $this->getSaveMessageUrl(); ?>" method="POST">
<?php echo $this->getBlockHtml('formkey')?>
</form>

<script type="text/javascript">
//<![CDATA[
    jQuery('#invitation_elements').form().validation();
    //var invitationForm = new varienForm('invitation_elements');
//]]>
</script>
