<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="box-right">
    <h4><?php echo __('Gift Cards'); ?></h4>
    <fieldset>
        <div class="content">
            <input id="giftcardaccount_add_input" type="text" class="input-text" />
            <button onclick="applyGiftCard()" type="button" value="" class="action- scalable"><span><?php echo __('Add Gift Card'); ?></span></button>
            <?php foreach ($this->getGiftCards() as $_card): ?>
                <p><strong><?php echo $_card; ?></strong> [<a href="#" onclick="removeGiftCard('<?php echo $_card; ?>'); return false;" title="<?php echo __('Remove'); ?>"><?php echo __('Remove'); ?></a>]</p>
            <?php endforeach; ?>
        </div>
    </fieldset>
</div>
