<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
require(['prototype'], function(){

//<![CDATA[
    removeGiftCard = function(code) {
        var data = {};
        data['giftcard_remove'] = code;
        order.loadArea(['totals', 'billing_method', 'items'], true, data);
    }

    applyGiftCard = function() {
        var code = $('giftcardaccount_add_input').value;
        var data = {};
        data['giftcard_add'] = code;
        order.loadArea(['totals', 'billing_method', 'items'], true, data);
    }
//]]>

});
</script>
