<?php
/**
 * Created by JetBrains PhpStorm.
 * User: anton
 * Date: 4/1/13
 * Time: 9:35 AM
 * To change this template use File | Settings | File Templates.
 */

class Collection extends Mage_Core_Model_Resource_Db_Collection_Abstract
{
    protected function _init($model, $resourceModel)
    {
        return parent::_init($model, $resourceModel); // TODO: Change the autogenerated stub
    }

}
