<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<fieldset class="product-options" id="product-options-wrapper">
    <?php echo $this->getChildHtml('', true);?>
</fieldset>
<script type="text/javascript">(function($) {$.mage.decorator.general($('#product-options-wrapper dl'), ['last']);})(jQuery);</script>
