<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\Checkout\Block\Onepage\Success */ ?>

<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <?php echo __('<a href="%1" onclick="this.target=\'_blank\'" class="print">Print receipt</a>', $this->getPrintUrl()) ?>
    <?php echo $this->getChildHtml() ?>
<?php endif;?>
