<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Tax\Block\Item\Price\Renderer */

$_item = $this->getItem();
?>

<?php if ($this->displayPriceInclTax() || $this->displayBothPrices()): ?>
    <span class="incl tax" data-th="<?php echo $this->escapeHtml(__('Incl. Tax')); ?>">
        <?php $_incl = $this->helper('Magento\Checkout\Helper\Data')->getPriceInclTax($_item); ?>
        <span class="cart price">
            <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_incl) ?>
        </span>
    </span>
<?php endif; ?>

<?php if ($this->displayPriceExclTax() || $this->displayBothPrices()): ?>
    <span class="excl tax" data-th="<?php echo $this->escapeHtml(__('Excl. Tax')); ?>">
        <span class="cart price">
            <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_item->getCalculationPrice()) ?>
        </span>
    </span>
<?php endif; ?>
