<?if($currencies->getSize()>1):?>
<div class="catalog-nav">
    <h2>You Currency</h2>
    <select name="currency" onchange="changeCurrency(this)">
    <?foreach ($currencies as $_currency):?>
        <option value="<?=$_currency->getCurrencyCode()?>"<?if($currentCurrencyCode==$_currency->getCurrencyCode()):?> selected<?endif;?>>
            <?=$_currency->getCurrencyName()?>
        </option>
    <?endforeach;?>
    </select>
</div>
<script type="text/javascript">
function changeCurrency(sObject){
    if(sObject.value){
        location.href = '<?=$baseUrl?>directory/currency/switch/currency/'+sObject.value+'/';
    }
}
</script>
<?endif;?>