<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\GiftWrapping\Block\Checkout\Options */
?>
<?php if ($this->canDisplayGiftWrapping()): ?>

<?php if ($this->getDesignCollectionCount() && ($this->getAllowForOrder() || $this->getAllowForItems() || $this->getGiftWrappingAvailable())): ?>
    <script id="gift-wrapping-container" type="text/x-jQuery-tmpl">
        <div class="field gift-wrapping">
            <label class="label"><span><?php echo __('Gift Wrapping Design') ?></span></label>
            <div class="control">
                <?php echo $this->getDesignSelectHtml() ?>
                <div class="nested design no-display">
                    <img id="image-box-${_id_}" alt="<?php echo __('Preview')?>" src="<?php echo $this->getViewFileUrl('images/spacer.gif')?>" />
                    <div class="price-box" id="price-box-${_id_}">
                    <?php if ($this->getDisplayWrappingBothPrices()): ?>
                        <span class="price-including-tax" data-label="<?php echo __('Price Incl. Tax') ?>">
                            <span class="price" id="price-including-tax-${_id_}"></span>
                        </span>
                        <span class="price-excluding-tax" data-label="<?php echo __('Price Excl. Tax') ?>">
                            <span class="price" id="price-excluding-tax-${_id_}"></span>
                        </span>
                    <?php else: ?>
                        <span class="regular-price" data-label="<?php echo __('Price') ?>">
                            <span class="price" id="regular-price-${_id_}"></span>
                        </span>
                    <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    </script>
<?php endif;?>

<script id="gift-options-container" type="text/x-jQuery-tmpl">
    <?php if ($this->getAllowGiftReceipt()): ?>
    <div class="field choice receipt">
        <input type="checkbox" name="giftwrapping[${type}][${id}][allow_gift_receipt]" id="allow-gift-receipt-${id}" value="1" class="checkbox" />
        <label for="allow-gift-receipt-${id}" class="label"><span><?php echo __('Send Gift Receipt') ?></span></label>
    </div>
    <?php endif;?>
    <?php if ($this->getAllowPrintedCard()): ?>
    <div class="field choice card">
        <input type="checkbox" name="giftwrapping[${type}][${id}][add_printed_card]" id="add-printed-card-${id}" value="1" onclick="" class="checkbox" />
        <label for="add-printed-card-${id}" class="label"><span><?php echo __('Add Printed Card') ?></span></label>
    </div>
    <div class="price-box no-display" id="price-options-box-${id}">
        <?php if ($this->getDisplayCardBothPrices()): ?>
        <span class="price-including-tax" data-label="<?php echo __('Price Incl. Tax') ?>">
            <span class="price" id="price-card-including-tax-${id}">${price_incl_tax}</span>
        </span>
        <span class="price-excluding-tax" data-label="<?php echo __('Price Excl. Tax') ?>">
            <span class="price" id="price-card-excluding-tax-${id}">${price_excl_tax}</span>
        </span>
        <?php else: ?>
        <span class="regular-price" data-label="<?php echo __('Price') ?>">
            <span class="price" id="regular-card-price-${id}">${price}</span>
        </span>
        <?php endif;?>
    </div>
    <?php endif;?>
</script>

<script type="text/javascript">
require(['jquery', 'mage/mage'], function(jQuery){

    jQuery('#checkoutSteps, #shipping_method_form').mage('giftWrapping', {
        designsInfo: <?php echo $this->getDesignsInfo()->toJson() ?>,
        itemsInfo: <?php echo $this->getItemsInfo()->toJson() ?>,
        cardInfo: <?php echo $this->getCardInfo()->toJson() ?>,
        allowForOrder: <?php echo (int)$this->getAllowForOrder() ?>,
        allowGiftReceipt: <?php echo (int)$this->getAllowGiftReceipt() ?>,
        allowPrintedCard: <?php echo (int)$this->getAllowPrintedCard() ?>,
        orderLevelType: "<?php echo $this->getCheckoutTypeVariable('order_level') ?>",
        orderItemType: "<?php echo $this->getCheckoutTypeVariable('item_level') ?>"
    });

});
</script>
<?php endif; ?>
