<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php foreach ($this->getValues() as $label => $value):?>
<tr class="totals giftwrapping">
    <th class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <span><?php echo $label; ?></span>
    </th>
    <td class="amount" data-th="<?php echo $this->escapeHtml($label); ?>">
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($value) ?>
    </td>
</tr>
<?php endforeach; ?>
