<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php foreach ($this->getValues() as $label => $value):?>
<tr class="totals giftwrapping">
    <th class="mark" colspan="<?php echo $this->getColspan(); ?>" scope="row">
        <span><?php echo $label; ?></span>
    </th>
    <td class="amount" data-th="<?php echo $this->escapeHtml($label); ?>">
        <?php echo $this->helper('Magento\Checkout\Helper\Data')->formatPrice($value) ?>
    </td>
</tr>
<?php endforeach; ?>
