<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    if (!$('export_filter_grid') && $('export_filter_container')) {
        $('export_filter_container').hide();
    }
    var serverType = $('server_type'),
        onChangeCallback = function(e) {
            var serverTypeValue = $(this).value;
            $(this.form).getElementsBySelector('.server-dependent').each(function(e){
                if (!e.parentNode.parentNode)alert(e.nodeName);
                var s = e.parentNode.parentNode.style;
                if ($(e).hasClassName(serverTypeValue + '-server')) {
                    s.display = '';
                    e.disabled = false;
                } else {
                    s.display = 'none';
                    e.disabled = true;
                }
            });
        };
    serverType.observe('change', onChangeCallback);
    onChangeCallback.call(serverType, {type: 'change'});
</script>
