<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $exportVersionTwo = (int) Mage_ImportExport_Model_Source_Format_Version::VERSION_2;
?>
<script type="text/javascript">
//<![CDATA[
    /**#@+
     * Behavior version constants
     *
     * @type string
     */
    varienForm.prototype.BEHAVIOR_VERSION_1 = 'behaviour_v1';
    varienForm.prototype.BEHAVIOR_VERSION_2_CUSTOMER = 'behaviour_v2_customer';
    /**#@-*/

    /**
     * Show and activate row
     *
     * @param string elementId
     */
    varienForm.prototype.activateRow = function(elementId)
    {
        $(elementId).up('tr').show();
        $(elementId).enable();
        $(elementId).addClassName('required-entry');
    };

    /**
     * Hide and deactivate row
     *
     * @param string elementId
     */
    varienForm.prototype.deactivateRow = function(elementId)
    {
        $(elementId).up('tr').hide();
        $(elementId).selectedIndex = 0;
        $(elementId).disable();
        $(elementId).removeClassName('required-entry');
    };

    /**
     * Show behavior selector
     *
     * @param string|boolean behaviorVersion If false, then hide both behavior selectors
     * @return void
     */
    varienForm.prototype.showBehavior = function(behaviorVersion)
    {
        if (behaviorVersion == this.BEHAVIOR_VERSION_1) {
            this.activateRow('behavior_v1');
            this.deactivateRow('behavior_v2_customer');
        } else if (behaviorVersion == this.BEHAVIOR_VERSION_2_CUSTOMER) {
            this.deactivateRow('behavior_v1');
            this.activateRow('behavior_v2_customer');
        } else {
            this.deactivateRow('behavior_v1');
            this.deactivateRow('behavior_v2_customer');
        }
    };

    /**
     * Show import format version selector
     *
     * @param boolean isShow
     * @return void
     */
    varienForm.prototype.showFormatVersion = function(isShow)
    {
        if (isShow == true) {
            this.activateRow('file_format_version');
        } else {
            this.deactivateRow('file_format_version');
        }
    };

    /**
     * Show customer entity selector
     *
     * @param boolean isShow
     * @return void
     */
    varienForm.prototype.showCustomerEntity = function(isShow)
    {
        if (isShow == true) {
            this.activateRow('entity_subtype');
        } else {
            this.deactivateRow('entity_subtype');
        }
    };

    /**
     * Handle value change in entity type selector for export
     *
     * @return void
     */
    varienForm.prototype.handleExportEntityTypeSelector = function()
    {
        if ($('entity') && $F('entity')) {
            this.showFormatVersion(false);
            this.showCustomerEntity(false);

            switch ($F('entity')) {
                case 'customer':
                    this.showFormatVersion(true);
                    $('export_filter_grid_container').update();
                    $('export_filter_container').hide();
                    break;
                default:
                    this.getFilter();
                    break;
            }
        } else {
            this.showFormatVersion(false);
            this.showCustomerEntity(false);
            $('export_filter_container').hide();
        }
    };

    /**
     * Handle value change in entity type selector for import
     *
     * @return void
     */
    varienForm.prototype.handleImportEntityTypeSelector = function()
    {
        if ($('entity') && $F('entity')) {
            this.showFormatVersion(false);
            this.showBehavior(false);
            this.showCustomerEntity(false);
            switch ($F('entity')) {
                case 'customer':
                    this.showFormatVersion(true);
                    break;
                case 'catalog_product':
                    this.showBehavior(this.BEHAVIOR_VERSION_1);
                    break;
                default:
                    break;
            }
        } else {
            this.showFormatVersion(false);
            this.showBehavior(false);
            this.showCustomerEntity(false);
        }
    };

    /**
     * Handle value change in export format version selector
     *
     * @return void
     */
    varienForm.prototype.handleExportFormatVersionSelector = function()
    {
        if ($('file_format_version') && $F('file_format_version')) {
            switch ($F('file_format_version')) {
                case '<?php echo Mage_ImportExport_Model_Source_Format_Version::VERSION_1 ?>':
                    this.showCustomerEntity(false);
                    this.getFilter();
                    break;
                case '<?php echo Mage_ImportExport_Model_Source_Format_Version::VERSION_2 ?>':
                    this.showCustomerEntity(true);
                    this.getCustomerFilter();
                    break;
                default:
                    break;
            }
        } else {
            this.showCustomerEntity(false);
            $('export_filter_container').hide();
        }
    };

    /**
     * Handle value change in import format version selector
     *
     * @return void
     */
    varienForm.prototype.handleImportFormatVersionSelector = function()
    {
        if ($('file_format_version') && $F('file_format_version')) {
            switch ($F('file_format_version')) {
                case '<?php echo Mage_ImportExport_Model_Source_Format_Version::VERSION_1 ?>':
                    this.showBehavior(this.BEHAVIOR_VERSION_1);
                    this.showCustomerEntity(false);
                    break;
                case '<?php echo Mage_ImportExport_Model_Source_Format_Version::VERSION_2 ?>':
                    this.showBehavior(this.BEHAVIOR_VERSION_2_CUSTOMER);
                    this.showCustomerEntity(true);
                    break;
                default:
                    break;
            }
        } else {
            this.showBehavior(false);
            this.showCustomerEntity(false);
        }
    };

    /**
     *  Handle value change in entity type selector
     *
     * @return void
     */
    varienForm.prototype.handleCustomerEntityTypeSelector = function()
    {
        if (!$('entity_subtype') || $F('entity_subtype') == 'customer') {
            $$('col:first-child').each(function(el) {
                el.show();
            });
            $$('th.no-link:first-child').each(function(el) {
                el.show();
            });
            $$('td.a-center').each(function(el) {
                el.show();
            });
        } else {
            $$('col:first-child').each(function(el) {
                el.hide();
            });
            $$('th.no-link:first-child').each(function(el) {
                el.hide();
            });
            $$('td.a-center').each(function(el) {
                el.hide();
            });
        }
    };

    /**
     * Post form data and process response via AJAX
     *
     * @return void
     */
    varienForm.prototype.getFilter = function()
    {
        if ($('entity') && $F('entity')) {
            var url = "<?php echo $this->getUrl('*/*/getFilter') ?>";
            url += ((url.slice(-1) != '/') ? '/' : '') + 'entity/' + $F('entity');

            new Ajax.Request(url, {
                method:      'post',
                evalScripts: true,
                onComplete:  function(transport) {
                    var responseText = transport.responseText.replace(/>\s+</g, '><');
                    $('export_filter_grid_container').update(responseText);
                    $('export_filter_container').show();
                }
            });
        } else {
            $('export_filter_container').hide();
        }
    };

    /**
     * Post form data and process response via AJAX.
     *
     * @return void
     */
    varienForm.prototype.getCustomerFilter = function()
    {
        if ($('entity') && $F('entity')) {
            var url = "<?php echo $this->getUrl('*/*/getFilter') ?>";
            url += ((url.slice(-1) != '/') ? '/' : '') + 'entity/' + $F('entity');
            // because we didn't get instructions from UX team, we will use filter by customer attributes
            // for all customer entity types for now
            url += '/' + 'customer_entity/customer';

            new Ajax.Request(url, {
                method:      'post',
                evalScripts: true,
                onComplete:  function(transport) {
                    var responseText = transport.responseText.replace(/>\s+</g, '><');
                    $('export_filter_grid_container').update(responseText);
                    $('export_filter_container').show();
                }
            });
        } else {
            $('export_filter_container').hide();
        }
    };
//]]>
</script>
