<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $exportVersionTwo = (int) Mage_ImportExport_Model_Source_Format_Version::VERSION_2;
?>
<script type="text/javascript">
//<![CDATA[

    /**
     * Show import format version selector
     *
     * @param boolean isShow
     * @return void
     */
    varienForm.prototype.showFormatVersion = function(isShow)
    {
        if (isShow == true) {
            $('file_format_version').up('tr').show();
            $('file_format_version').enable();
            $('file_format_version').addClassName('required-entry');
        } else {
            $('file_format_version').up('tr').hide();
            $('file_format_version').disable();
            $('file_format_version').selectedIndex = 0;
            $('file_format_version').removeClassName('required-entry');
        }
    };

    /**
     * Show customer entity selector
     *
     * @param boolean isShow
     * @return void
     */
    varienForm.prototype.showCustomerEntity = function(isShow)
    {
        if (isShow == true) {
            $('entity_subtype').up('tr').show();
            $('entity_subtype').enable();
            $('entity_subtype').addClassName('required-entry');
        } else {
            $('entity_subtype').up('tr').hide();
            $('entity_subtype').disable();
            $('entity_subtype').selectedIndex = 0;
            $('entity_subtype').removeClassName('required-entry');
        }
    };

    /**
     * Handle value change in entity type selector
     *
     * @return void
     */
    varienForm.prototype.handleExportEntityTypeSelector = function()
    {
        if ($('entity') && $F('entity')) {
            this.showFormatVersion(false);
            this.showCustomerEntity(false);

            switch ($F('entity')) {
                case 'customer':
                    this.showFormatVersion(true);
                    $('export_filter_grid_container').update();
                    $('export_filter_container').hide();
                    break;
                default:
                    this.getFilter();
                    break;
            }
        } else {
            this.showFormatVersion(false);
            this.showCustomerEntity(false);
            $('export_filter_container').hide();
        }
    };

    /**
     * Handle value change in export format version selector
     *
     * @return void
     */
    varienForm.prototype.handleExportFormatVersionSelector = function()
    {
        if ($('file_format_version') && $F('file_format_version')) {
            switch ($F('file_format_version')) {
                case '<?php echo Mage_ImportExport_Model_Source_Format_Version::VERSION_1 ?>':
                    this.showCustomerEntity(false);
                    this.getFilter();
                    break;
                case '<?php echo Mage_ImportExport_Model_Source_Format_Version::VERSION_2 ?>':
                    this.showCustomerEntity(true);
                    this.getCustomerFilter();
                    break;
                default:
                    break;
            }
        } else {
            this.showCustomerEntity(false);
            $('export_filter_container').hide();
        }
    };

    /**
     *  Handle value change in entity type selector
     *
     * @return void
     */
    varienForm.prototype.handleCustomerEntityTypeSelector = function()
    {
        if (!$('entity_subtype') || $F('entity_subtype') == 'customer') {
            $$('col:first-child').each(function(el) {
                el.show();
            });
            $$('th.no-link:first-child').each(function(el) {
                el.show();
            });
            $$('td.a-center').each(function(el) {
                el.show();
            });
        } else {
            $$('col:first-child').each(function(el) {
                el.hide();
            });
            $$('th.no-link:first-child').each(function(el) {
                el.hide();
            });
            $$('td.a-center').each(function(el) {
                el.hide();
            });
        }
    };

    /**
     * Post form data and process response via AJAX
     *
     * @return void
     */
    varienForm.prototype.getFilter = function()
    {
        if ($('entity') && $F('entity')) {
            var url = "<?php echo $this->getUrl('*/*/getFilter') ?>";
            url += ((url.slice(-1) != '/') ? '/' : '') + 'entity/' + $F('entity');

            new Ajax.Request(url, {
                method:      'post',
                evalScripts: true,
                onComplete:  function(transport) {
                    var responseText = transport.responseText.replace(/>\s+</g, '><');
                    $('export_filter_grid_container').update(responseText);
                    $('export_filter_container').show();
                }
            });
        } else {
            $('export_filter_container').hide();
        }
    };

    /**
     * Post form data and process response via AJAX.
     *
     * @return void
     */
    varienForm.prototype.getCustomerFilter = function()
    {
        if ($('entity') && $F('entity')) {
            var url = "<?php echo $this->getUrl('*/*/getFilter') ?>";
            url += ((url.slice(-1) != '/') ? '/' : '') + 'entity/' + $F('entity');
            // because we didn't get instructions from UX team, we will use filter by customer attributes
            // for all customer entity types for now
            url += '/' + 'customer_entity/customer';

            new Ajax.Request(url, {
                method:      'post',
                evalScripts: true,
                onComplete:  function(transport) {
                    var responseText = transport.responseText.replace(/>\s+</g, '><');
                    $('export_filter_grid_container').update(responseText);
                    $('export_filter_container').show();
                }
            });
        } else {
            $('export_filter_container').hide();
        }
    };
//]]>
</script>
