<?
/**
 * Category layered navigation state
 * 
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<h4>Currently Shopping By</h4>
<div class="content">
    <ul class="widget-list">
        <li><a href="#" class="action"/>Remove</a><span class="label">Price:</span><br/><a 
            href="#">$10-$99</a> (3)</span></li>
        <li><a href="#" class="action">Remove</a><span class="label">Manufacturer:</span><br/><a 
            href="#">Kennwood</a> (4)</span></li>
    </ul>
    <p class="actions"><a href="#">Clear All</a></p>
</div>
