<?
/**
 * Category layered navigation
 * 
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?if($this->canShowBlock()):?>
<div class="box layered-nav">
  <div class="head">
							<h3><?=__('Shop by')?></h3>
						</div>

   
			<div class="border-creator">
        <?=$this->getStateHtml()?>
        <?if($this->canShowOptions()):?>

        <div class="narrow-by">
            <h4>Shopping options</h4>
            <dl id="narrow-by-list">
            <?$_filters = $this->getFilters()?>
            <?foreach ($_filters as $_filter):?>
            <?if($_filter->getItemsCount()):?>
                <dt><?=$_filter->getName()?></dt>
                <dd>
                    <?=$_filter->getHtml()?>
                </dd>
            <?endif;?>
            <?endforeach;?>
            </dl><script type="text/javascript">decorateDataList('narrow-by-list')</script>
        </div>
        <?endif;?>
    </div>
</div>
<?endif;?>
<!-- [ends] .browse-by // -->





