<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Gift registry items template
 *
 * @see Enterprise_GiftRegistry_Block_Items
 */
?>
<?php
    $_itemsCount = count($this->getItems());
?>
<!--<h2 class="subtitle"><?php echo __('Gift Registry Items') ?></h2>-->
<form action="<?php echo $this->getActionUrl() ?>" method="post">
    <fieldset>
        <ul class="list">
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
        </ul>
        <?php if ($_itemsCount): ?>
        <div class="buttons-set">
            <button type="submit" title="<?php echo __('Add to Cart') ?>" class="button btn-update"><span><span><?php echo __('Add to Cart') ?></span></span></button>
        </div>
        <?php endif; ?>
    </fieldset>
</form>
<?php if (!$_itemsCount): ?>
    <p><?php echo __('Gift Registry has no items.') ?></p>
<?php endif; ?>
