<?if (empty($methods)):?>
	<b>Sorry, no quotes are available for this order at this time.</b>
<?else:?>
    <form id="co-shipping-method-form">
    	<fieldset>
    	   <ul>
	        <?foreach ($methods as $method):?>
	           <?if (!isset($method['vendor'])) continue; ?>
        		<li>
        		    <input id="shipping_method_<?=$method['code']?>" name="shipping_method" type="radio" value="<?=$method['code']?>" <?if($method['code']===$selectedMethod)echo"checked"?> />
        		    <label for="shipping_method_<?=$method['code']?>"><?=$method['vendor']?>: <?=$method['service_description']?></label>:
        		    <strong><?=$method['amount']?></strong>
        		</li>
    		<?endforeach?>
    		</ul>
    	</fieldset>
	</form>
<?endif?>


