<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $this */
$columns = $this->getColumns();
?>

<div class="products-grid wishlist">
    <ol class="product-items">
        <?php $iterator = 1; ?>
        <?php if (count($this->getItems())): ?>
            <?php foreach ($this->getItems() as $item): ?>
            <?php echo ($iterator++==1) ? '<li class="product-item" id="item_<?php echo $item->getId();?>">' : '</li><li class="product-item" id="item_<?php echo $item->getId();?>">' ?>
                <div class="product-item-info">
                    <?php foreach ($columns as $column): ?>
                        <?php $column->setItem($item); echo $column->toHtml($item);?>
                    <?php endforeach; ?>
                </div>
            <?php echo ($iterator==count($this->getItems())+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        <?php else: ?>
            <?php echo __('This Wish List has no Items');?>
        <?php endif; ?>
    </ol>
</div>

<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
