<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php echo $this->getCaptchaHtml() ?>

<?php echo $this->getStoreSwitcherHtml() ?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"></div>
        <h4 class="fieldset-legend"><?php echo $this->__('Google Content Items') ?></h4>
    </div>
    <?php echo $this->getChildHtml('item') ?>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"><?php echo $this->getAddButtonHtml() ?></div>
        <h4 class="fieldset-legend"><?php echo $this->__('Available Products') ?></h4>
    </div>
    <?php echo $this->getChildHtml('product') ?>
</div>


<script type="text/javascript">
//<![CDATA[
var productsGridElement = $('<?php echo $this->getChild('product')->getId() ?>');
productsGridElement.hide();
$('products_grid_button').observe('click', function (event) {
    var element = event.element();
    productsGridElement.visible() ? productsGridElement.hide() : productsGridElement.show();
});
//]]>
</script>
