<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php
/**
 * @see \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Shippingaddress
 */
?>
<?php if ($this->getOrderShippingAddress()) : ?>
    <div class="fieldset-wrapper">
        <div class="fieldset-wrapper-title">
            <span class="title"><?php echo __('Order Shipping Address') ?></span>
        </div>
        <address><?php echo $this->getOrderShippingAddress() ?></address>
    </div>
<?php endif ?>
