<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_order = $this->getOrder() ?>
<p class="order-links"><a href="<?php echo $this->getPrintAllCreditmemosUrl($_order) ?>" onclick="this.target='_blank'" class="link-print"><?php echo __('Print All Refunds') ?></a></p>
<?php foreach ($_order->getCreditmemosCollection() as $_creditmemo): ?>
<h2 class="sub-title"><?php echo __('Refund #') ?><?php echo $_creditmemo->getIncrementId(); ?> <span class="separator">|</span> <a href="<?php echo $this->getPrintCreditmemoUrl($_creditmemo) ?>" onclick="this.target='_blank'" class="link-print"><?php echo __('Print Refund') ?></a></h2>
<h3 class="table-caption"><?php echo __('Items Refunded') ?></h3>
<table class="data-table" id="my-refund-table-<?php echo $_creditmemo->getId(); ?>">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo __('Product Name') ?></th>
            <th><?php echo __('SKU') ?></th>
            <th class="a-right"><?php echo __('Price') ?></th>
            <th class="a-center"><?php echo __('Qty') ?></th>
            <th class="a-right"><?php echo __('Subtotal') ?></th>
            <th class="a-center wrap"><?php echo __('Discount Amount') ?></th>
            <th class="a-right wrap"><?php echo __('Row Total') ?></th>
        </tr>
    </thead>
    <tfoot>
       <?php echo $this->getTotalsHtml($_creditmemo);?>
    </tfoot>
    <?php $_items = $_creditmemo->getAllItems(); ?>
    <?php $_count = count($_items) ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>
</table>
<script type="text/javascript">(function($) {$('#my-refund-table-<?php echo $_creditmemo->getId(); ?>').decorate('table', {'tbody': ['odd','even'], 'tbody tr': ['first','last']})})(jQuery)</script>
<?php echo $this->getCommentsHtml($_creditmemo)?>
<?php endforeach; ?>
