<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="" method="post" id="form-validate" class="form send confirmation">
    <fieldset class="fieldset" data-hasrequired="<?php echo __('* Required Fields') ?>">
        <p class="field note"><?php echo __('Please enter your email below and we will send you the confirmation link for it.') ?></p>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php echo __('Email Address') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" class="input-text" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
    </fieldset>
    <div class="actions">
        <div class="primary">
            <button type="submit" class="action send"><span><?php echo __('Send confirmation link') ?></span></button>
        </div>
        <div class="secondary">
            <a href="<?php echo $this->helper('Magento\Customer\Helper\Data')->getLoginUrl() ?>" class="action back"><span><?php echo __('Back to Login') ?></span></a>
        </div>
    </div>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#form-validate').validation();
            });
    })(jQuery);
</script>
