<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */?>
<?php $_product = $this->getProduct() ?>

<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="stock available" title="<?php echo $this->__('Availability') ?>">
            <span><?php echo $this->__('In stock') ?></span>
        </p>
    <?php else: ?>
        <p class="stock unavailable" title="<?php echo $this->__('Availability') ?>">
            <span><?php echo $this->__('Out of stock') ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>
