<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**http://localhost:8983/solr/admin/ping
 * @see Magento_Paypal_Block_Adminhtml_System_Config_ApiWizard
 */
?>
<script type="text/javascript">
    function testConnection() {
        var elem = $('<?php echo $this->getHtmlId() ?>');

        params = {
            host: $('catalog_search_solr_server_hostname').value,
            port: $('catalog_search_solr_server_port').value,
            timeout: $('catalog_search_solr_server_timeout').value,
            path: $('catalog_search_solr_server_path').value
        };

        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                result = '<?php echo __('Connection failed! Test again?') ?>';
                try {
                    response = response.responseText;
                    if (response == 1) {
                        result = '<?php echo __('Successful! Test again?') ?>';
                        elem.removeClassName('fail').addClassName('success')
                    } else {
                        elem.removeClassName('success').addClassName('fail')
                    }
                } catch (e) {
                    elem.removeClassName('success').addClassName('fail')
                }
                $('connection_test_result').update(result);
            }
        });
    }
</script>
<button onclick="javascript:testConnection(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span><span><span id="connection_test_result"><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span></span></span>
</button>
