<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright  {copyright}
 * @license    {license_link}
 */

/**
 * Admin login form template
 *
 * @var $this Mage_Oauth_Block_Adminhtml_Oauth_Authorize
 * @see Mage_Oauth_Block_Adminhtml_Oauth_Authorize
 */

 ?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <?php echo $this->getLayout()->renderElement('messages') ?>
            <?php if (!$this->getHasException()): ?>
                <form method="post" action="<?php echo $this->getPostActionUrl() ?>" id="login-form">
                    <fieldset>
                        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                        <h2><?php echo $this->__('Log in to Admin Panel'); ?></h2>
                        <p class="description"><?php echo $this->__('Log in to use <strong>%s</strong>', $this->getConsumer()->getName()) ?></p>
                        <div class="input-box input-left"><label for="username"><?php echo $this->__('User Name:') ?></label><br/>
                            <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" /></div>
                        <div class="input-box input-right"><label for="login"><?php echo $this->__('Password:') ?></label><br />
                            <input type="password" id="login" name="login[password]" class="required-entry input-text" value="" /></div>
                        <div class="clear"></div>
                        <div class="form-buttons">
                            <button type="submit" class="form-button" title="<?php echo $this->__('Login') ?>" ><?php echo $this->__('Login') ?></button>
                            <button onclick="document.location.href='<?php echo $this->getRejectUrl() ?>'; return false;" title="<?php echo $this->__('Reject') ?>"><?php echo $this->__('Reject') ?></button>
                        </div>
                        <input type="hidden" name="oauth_token" value="<?php echo $this->escapeHtml($this->getToken()) ?>"/>
                    </fieldset>
                </form>
                <script type="text/javascript">
                     jQuery('#login-form').mage('form').mage('validation');
                </script>
            <?php endif; ?>
        </div>
        <p class="legal"><?php echo $this->__('Magento&reg is a trademark of X.commerce, Inc. Copyright &copy; %s X.commerce, Inc.', date('Y')) ?></p>
        <div class="bottom"></div>
    </div>
</div>
