<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/* @var $this Mage_Catalog_Block_Product_Grouped_AssociatedProducts_List */
?>
<script type="text/jqury-template" id="group-product-template">
<tr title="#" class="pointer">
    <td data-column="info" class="col-draggable col-info">
        <span class="draggable-handle"></span>
        <input type="hidden" name="links[grouped][${id}][id]" value="${id}" data-role="id" />
        <input type="hidden" name="links[grouped][${id}][sku]" value="${sku}" data-role="sku" />
        <input type="hidden" name="links[grouped][${id}][position]" value="${position}" data-role="position" />
    </td>
    <td data-column="name" class="editable col-name">
        ${name}
    </td>
    <td data-column="sku" class=" col-sku ">
        ${sku}
    </td>
    <td data-column="price" class=" col-price a-right ">
        ${price}
    </td>
    <td data-column="qty" class="editable col-qty col-number">
        <input type="text" class="input-text " name="links[grouped][${id}][qty]" value="${qty}">
    </td>
    <td data-column="actions" class="col-actions">
        <button type="button" class="action- delete" data-role="delete"></button>
    </td>
</tr>
</script>
<div class="grid-container" class="no-display">
    <table class="data-table" id="grouped_grid_table"
        data-products="<?php echo $this->escapeHtml($this->helper('Mage_Core_Helper_Data')->jsonEncode(
                $this->getAssociatedProducts()
        )); ?>">
        <thead>
            <tr class="headings">
                <th data-column="info" class="col-draggable no-link col-info">
                    <span></span>
                </th>
                <th data-column="name" class=" no-link col-name">
                    <span>Name</span>
                </th>
                <th data-column="sku" class=" no-link col-sku">
                    <span>SKU</span>
                </th>
                <th data-column="price" class=" no-link col-price">
                    <span>Price</span>
                </th>
                <th data-column="qty" class=" no-link col-qty">
                    <span>Default Qty</span>
                </th>
                <th data-column="actions" class="last no-link col-actions">
                    <span class="nobr"></span>
                </th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
