<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Rma\Block\Order\Button */
?>
<?php if($this->helper('Magento\Rma\Helper\Data')->canCreateRma($this->getOrder())): ?>
    <span class="separator">|</span>
    <a href="<?php echo $this->helper('Magento\Rma\Helper\Data')->getReturnCreateUrl($this->getOrder()) ?>"><?php echo __('Return') ?></a>
<?php endif;?>
