<?
/*
    <!--<h2 class="page-head"><?=$category->getData('name')?></h2>-->
    <!--<p><?=$category->getData('description')?></p>-->
		<h2 class="category-head"><?=$this-><?=$this->getHeaderTitle()?></h2>

*/
?>
<?if($this->getCanShowName()):?>
<h2 class="category-head"><?=$this->getCurrentCategory()->getName()?></h2>
<?endif;?>




<?if($this->getCurrentCategory()->getImage()):?>
    <p><img src="<?=/*TOFIX*/Mage::getSingleton('core/store')->getConfig('web/url/upload').$this->getCurrentCategory()->getImage()?>" alt="<?=$this->getCurrentCategory()->getName()?>" width="512"/></p>
<?endif;?>

<?=$this->getPagerHtml()?>

<?$productCollection=$this->getLoadedProductCollection()?>
<?if($this->getMode()!='grid'):?>
<!-- [starts] .listing-type-list // -->
<div class="listing-type-list catalog-listing"> <!-- the class name will change to .listing-type-cell if viewing in list mode -->

    <?$i=0; foreach ($productCollection as $product):?>
						<div class="listing-item" <?if (sizeof($productCollection->getItems())<$i+3):?> class="last"<?endif?>">
							<div class="product-image">
								<a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><img src="<?=$product->getSmallImageUrl()?>" width="125" height="125" alt="<?=$product->getName()?>"/></a>
							</div>

							<div class="product-shop">
								<h5><a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><?=$product->getName()?></a></h5>

								<div class="ratings">
									<div class="rating-box">
										<div class="rating" style="width:70%;">
										</div>
									</div>
									<a href="#"><small class="count">3 Reviews</small></a>
								</div>
								<div class="price-box">
									<span class="special-price"><span class="label">Special:</span> <?=Mage::currency($product->getFinalPrice())?></span><br/>
									<span class="old-price"><span class="label">Price:</span> <?=Mage::currency($product->getPrice())?></span>
								</div>
								<a href="#" class="form-button" onclick="top.location.href='<?=$this->getUrl('checkout/cart/add',array('product'=>$product->getId()))?>'"><span>Add to Cart</span></a>
								<div class="clear"></div>
								<div class="description"><?=$product->getDescription()?> <a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><small>Learn More</small></a></div>
								<p class="add-to"><a href="<?=$this->getUrl('wishlist/index/add',array('product'=>$product->getId()))?>" class="link-cart">Add to Wishlist</a>
								<?if($this->getCompareJsObjectName()):?><span class="pipe">|</span><a href="#" onclick="<?=$this->getCompareJsObjectName()?>.addItem(<?=$product->getId()?>);return false;">Add to Compare</a><?endif;?>
								</p>
							</div>
						</div>
    <?endforeach;?>








</div>
<!-- [ends] .listing-type-list // -->




<?else:?>

<!-- [starts] .listing-type-grid // -->
	<div class="listing-type-grid  catalog-listing"> <!-- the class name will change to .listing-type-cell if viewing in list mode -->
	    <table cellspacing="0" class="generic-product-grid">
		    <?$i=0; foreach ($productCollection as $product):?>
			<?if ($i++%3==0):?><tr<?if (sizeof($productCollection->getItems())<$i+3):?> class="last"<?endif?>><?endif?>
								<td<?if ($i%3==0):?> class="last"<?endif?>>
									<p class="product-image"><a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><img src="<?=$product->getSmallImageUrl()?>" width="135" alt="<?=$product->getName()?>"></a></p>
									<h5><a href="<?=$product->getProductUrl()?>" title="<?=$product->getName()?>"><?=$product->getName()?></a></h5>
									<div class="ratings">
										<div class="rating-box">
											<div class="rating" style="width:75%;"></div>
										</div>
										<a href="#"><small>(3)</small></a>
									</div>
									<div class="price-box">
										<!--<span class="special-price"><img src="images/icon_special_price.gif" alt="special price" class="v-middle"/> $29.95</span>
										<span class="old-price">Regular price: $39.95</span>-->
										<span class="regular-price"><?=$product->getFormatedPrice()?></span>
									</div>
									<a class="form-button" onclick="top.location.href='<?=$this->getUrl('checkout/cart/add',array('product'=>$product->getId()))?>'"><span>Add to Cart</span></a>
									<div class="clear"></div>
									<p class="add-to">
										<?if($this->getCompareJsObjectName()):?>
											<strong>Add to:</strong><br/><a href="<?=$this->getUrl('wishlist/index/add',array('product'=>$product->getId()))?>">Wishlist</a><span class="pipe">|</span><a href="#" onclick="<?=$this->getCompareJsObjectName()?>.addItem(<?=$product->getId()?>);return false;">Compare</a>
										<?else:?>
											<a href="<?=$this->getUrl('wishlist/index/add',array('product'=>$product->getId()))?>">Add to Wishlist</a>
										<?endif;?>
									</p>
								</td>

			<?if ($i%3==0):?></tr><?endif?>
			<?endforeach?>
            <?for($i;$i%3!=0;$i++):?>
            <td class="empty-product"></td>
            <?endfor?>
		</table>
	</div>
<!-- [ends] .listing-type-grid // -->
<?endif;?>
<?=$this->getPagerHtml()?>

