<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
$required = '';
if ($this->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . $this->__('* Required Fields') . '"';
}
?>
<div class="product options wrapper" id="product-options-wrapper"<?php echo $required; ?>>
    <?php echo $this->getChildHtml('', true);?>
</div>
