<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="tax-rule-import">
    <!-- Import Tax Rates -->
<?php if (!$this->getIsReadonly()): ?>

    <h4 class="title"><?php echo __('Import Tax Rates'); ?></h4>
    <p class="import-tax-rates-tagline" id="import-tax-rates-tagline"><?php echo __('You can upload your existing Tax Rates in CSV format.'); ?></p>
    <span class="fileinput-button">
        <span class="action-import"><?php echo __('Import Tax Rates'); ?></span>
        <input type="file" id="import_rates_file" name="import_rates_file" class="input-file" data-url="<?php echo $this->getUrl('*/storelauncher_tax_drawer/importTaxRates'); ?>"/>
    </span>
    <a href="<?php echo $this->getUrl('adminhtml/tax_rate/exportPost'); ?>" class="import-example-file"><?php echo __('Example CSV File'); ?></a>

</div>

<script type="text/javascript">
jQuery(function ($) {
    $('#import_rates_file').fileupload({
        dataType: 'json',
        formData: {
            isAjax: 'true',
            form_key: FORM_KEY
        },
        sequentialUploads: false,
        done: function(e, data) {
            if (data.result.success == true) {
                updateTaxRateMultiselect(data.result);
                insertValidationMessage('<?php echo __('The tax rate has been imported.'); ?>', 'success');
            } else {
                insertValidationMessage('<?php echo __('Invalid file format.'); ?>', 'error')
            }
        },
        fail: function(e, data) {
            insertValidationMessage('<?php echo __('Invalid file format.'); ?>', 'error')
        },
        add: function(e, data) {
            $(this).fileupload('process', data).done(function() {
                data.submit();
            });
        }
    });

    /**
     * Show tax rate import error message
     *
     * @param message
     */
    var messagePlaceholder = $('#import-tax-rates-tagline'),
            insertValidationMessage = function(messageText, messageType) {
                $('<div class="message-validation ' + messageType + '">' + messageText + '</div>')
                        .insertAfter(messagePlaceholder);
                delay && clearTimeout(delay);
                var delay = setTimeout(function() {
                    $('.message-validation').slideUp(400);
                }, 3000);
            };

    /**
     * Refresh tax Rate Field
     *
     * @param result array import rates request result
     */
    var updateTaxRateMultiselect = function(result) {
        var taxSection = $('#tax_rate').parent().parent(),
            previousSection = taxSection.prev();
        taxSection.remove();
        // Next variable is global for tax rule page and is used in edit tax rate pop-up
        taxRateCollection = result.tax_rate_collection;
        previousSection.after(result.tax_rate_field);
    }
});
</script>
<?php endif; ?>

