<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
namespace Magento\CatalogSearch\Model\Layer\Filter;

/**
 * Layer price filter based on Search API
 *
 */
class Price extends \Magento\Catalog\Model\Layer\Filter\Price
{
    /**
     * Get data array for building attribute filter items
     *
     * @return array
     */
    protected function _getItemsData()
    {
        $attribute = $this->getAttributeModel();
        $this->_requestVar = $attribute->getAttributeCode();

        $productCollection = $this->getLayer()->getProductCollection();
        $facets = $productCollection->getFacetedData($attribute->getAttributeCode());

        $data = [];
        if (!empty($facets)) {

            $i = 0;
            $maxIntervalsNumber = $this->getMaxIntervalsNumber();
            $lastSeparator = null;
            foreach ($facets as $key => $aggregation) {
                $count = $aggregation['count'];
                $separator = explode('_', '_' . $key);

                ++$i;
                $label = null;
                $value = null;
                if (isset($this->_facets[$separator[1] . '_' . $separator[2]])) {
                    $separatorLabelValues = $this->_facets[$separator[1] . '_' . $separator[2]];
                    if ($i <= max(1, $maxIntervalsNumber)) {
                        $lastSeparator = $separatorLabelValues[0];
                    }
                    $label = $this->_renderRangeLabel($separatorLabelValues[0], $separatorLabelValues[1]);
                    $value = (empty($separatorLabelValues[0]) ? '' : $separatorLabelValues[0]) .
                        '-' .
                        $separatorLabelValues[1];
                }

                if ($separator[1] == '*') {
                    $separator[1] = '';
                }
                if ($separator[2] == '*') {
                    $separator[2] = '';
                }


                $data[$i - 1] = [
                    'label' => is_null(
                        $label
                    ) ? $this->_renderRangeLabel(
                        empty($separator[1]) ? 0 : $separator[1] * $this->getCurrencyRate(),
                        empty($separator[2]) ? $separator[2] : $separator[2] * $this->getCurrencyRate()
                    ) : $label,
                    'value' => (is_null(
                            $value
                        ) ? $separator[1] . '-' . $separator[2] : $value) . $this->_getAdditionalRequestData(),
                    'count' => $count,
                    'from' => $separator[1],
                    'to' => $separator[2]
                ];
            }

        }

        return $data;
    }

    /**
     * Prepare price range to be added to facet conditions
     *
     * @param string|float $from
     * @param string|float $to
     * @return array
     */
    protected function _prepareFacetRange($from, $to)
    {
        if (empty($from)) {
            $from = '*';
        }

        if ($to === '') {
            $to = '*';
        } else {
            if ($to == $from || $to == 0 && $from == '*') {
                $to = $this->_prepareFacetedValue($to, false);
            } else {
                $to = $this->_prepareFacetedValue($to);
            }
        }

        if ($from != '*') {
            $from = $this->_prepareFacetedValue($from);
        }
        return ['from' => $from, 'to' => $to];
    }

    /**
     * Add params to faceted search generated by algorithm
     *
     * @return void
     */
    protected function _addCalculatedFacetCondition()
    {
        $priceFacets = [];
        $this->_facets = [];
        foreach ($this->_getSeparators() as $separator) {
            $facetedRange = $this->_prepareFacetRange($separator[0], $separator[1]);
            $this->_facets[$facetedRange['from'] . '_' . $facetedRange['to']] = $separator;
            $priceFacets[] = $facetedRange;
        }
        $this->getLayer()->getProductCollection()->setFacetCondition($this->_getFilterField(), $priceFacets);
    }
}
