<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 /* @var $this Mage_Adminhtml_Block_Catalog_Product_Edit_AttributeSet */
?>
<script id="product-template-selector-template" type="text/x-jquery-tmpl">
{{if !term && items.length && !$data.allShown()}}
<h2>Recent Items</h2>
{{/if}}
<ul data-mage-init="{&quot;menu&quot;:[]}">
    {{each items}}
    <li {{html optionData($value)}}><a href="#">${$value.label}</a></li>
    {{/each}}
</ul>
{{if !term && items.length && !$data.allShown()}}
<div data-mage-init="{&quot;actionLink&quot;:{&quot;event&quot;:&quot;showAll&quot;}}" class="show-all">Show all...</div>
{{/if}}
</script>
<script>
    jQuery(function ($) {
        $('#attribute-set-suggest-container .current-set-container').toggle(function () {
            $(this).next('div').show();
        }, function () {
            $(this).next('div').hide();
        });
        $('#attribute-set-suggest').suggest(<?php echo $this->getSelectorOptions()?>)
            .on('suggestselect', function (e, selectedItem) {
                if (selectedItem.id) {
                    var uri = document.location.href.replace(/(\/|&|\?)?\bset(\/|=)\d+/g, '').replace('#', '');
                    uri += /\?/.test(uri) ? '&' : '?';
                    uri += 'set=' + window.encodeURIComponent(selectedItem.id);
                    var $form = $('#product-edit-form');
                    $form.attr('action', uri).addClass('ignore-validate').submit();
                }
            });
    });
</script>
