<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<script type="text/javascript">
    (function($) {
        "use strict";
        /**
         * Declaration of resources needed for defined components
         */
        $.mage.component({
            catalogSearch: [
                '<?php echo $this->getViewFileUrl('Magento_CatalogSearch::form-mini.js')?>'
            ],
            compareItems: [
                '<?php echo $this->getViewFileUrl('Magento_Catalog::js/compare.js')?>'
            ],
            compareList: [
                '<?php echo $this->getViewFileUrl('Magento_Catalog::js/list.js')?>'
            ],
            fileOption: [
                '<?php echo $this->getViewFileUrl('Magento_Catalog::js/file-option.js')?>'
            ],
            relatedProducts: [
                '<?php echo $this->getViewFileUrl('Magento_Catalog::js/related-products.js')?>'
            ],
            upsellProducts: [
                '<?php echo $this->getViewFileUrl('Magento_Catalog::js/upsell-products.js')?>'
            ],
            giftOptions: [
                '<?php echo $this->getViewFileUrl('Magento_GiftMessage::gift-options.js') ?>'
            ],
            discountCode: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>',
                '<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>',
                '<?php echo $this->getViewFileUrl('mage/validation.js')?>',
                '<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>',
                '<?php echo $this->getViewFileUrl('Magento_Checkout::js/discount-codes.js')?>'
            ],
            gallery: [
                '<?php echo $this->getViewFileUrl('Magento_Catalog::js/gallery.js')?>'
            ],
            wishlist: [
                '<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>',
                '<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>',
                '<?php echo $this->getViewFileUrl('mage/validation.js')?>',
                '<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>',
                '<?php echo $this->getViewFileUrl('Magento_Wishlist::wishlist.js')?>'
            ],
            downloadable: [
                '<?php echo $this->getViewFileUrl('Magento_Downloadable::downloadable.js')?>'
            ],
            toggleGiftCard: [
                '<?php echo $this->getViewFileUrl('Magento_GiftCard::toggle-gift-card.js')?>'
            ]
        });
    })(jQuery);
</script>
<?php echo $this->getChildHtml() ?>