<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Authorize confirmation simple template
 *
 * @var $this Magento_Oauth_Block_AuthorizeBaseAbstract
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?php echo __('Confirmation Of Authorization') ?></h1>
        </div>
        <div class="form-box">
            <?php echo $this->getLayout()->renderElement('messages') ?>
            <?php if ($this->getVerifier()): ?>
                <h2><?php echo __('Authorization confirmed') ?></h2>
                <p><?php echo __('Give the verifier code to application administrator') ?></p>
                <p style="font-size: 14px;"><?php echo __('Verifier code: %1', $this->getVerifier()) ?></p>
            <?php endif; ?>
            <button type="submit" class="button"
                    onclick="window.close();"
                    title="<?php echo __('Close') ?>">
                <span><span><?php echo __('Close') ?></span></span>
            </button>
        </div>
    </div>
</div>
