<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see Mage_CatalogInventory_Block_Qtyincrements
 */
?>
<?php if ($this->getProductQtyIncrements()) : ?>
    <div class="product-pricing">
        <?php echo __('%s is available for purchase in increments of %s', $this->getProductName(), $this->getProductQtyIncrements()) ?>
    </div>
<?php endif ?>
