<?if($this->getCanDisplayWishlist()):?>
<div class="box base-mini mini-wishlist">
	<div class="head">
		<h4>My Wishlist <span class="count"><?=__('- %d items', $this->getWishlistItems()->getSize())?></span></h4>
	</div>
	<ul class="tabs">
		<li class="active"><a href="#">Last added item</a></li>
		<li><a href="<?=$this->getUrl('wishlist')?>">View all</a></li>
	</ul>
	<?if($this->getWishlistItems()->getSize()>0):?>
	<ol id="wishlist-sidebar">
	 <?foreach($this->getWishlistItems() as $_item):?>
        <li>
			<div class="product-images">
				<a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getSmallImageUrl()?>" alt="<?=$_item->getName()?>" width="38" height="38"/></a>
			</div>
			<div class="product-details">
				<a href="<?=$this->getRemoveItemUrl($_item)?>" onclick="return confirm('<?=__('Are You sure?')?>');" class="widget-btn"><img src="<?=$this->getSkinUrl('images/list_remove_btn.gif')?>" alt="Remove"/></a>
				<a href="#"><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a>
				<?=$this->getHelper('catalog/product')->getPriceHtml($_item)?>
				<a href="<?=$this->getAddToCartItemUrl($_item)?>" class="link-cart">Add to Cart</a>
			</div>
		</li>
	<?endforeach;?>
	</ol>
	<script type="text/javascript">decorateList('wishlist-sidebar')</script>
	<?else:?>
 	<div class="content"><p><?=__('You have no items in your wishlist.')?></p></div>
 	<?endif?>
    <div class="actions"><a href="<?=$this->getUrl('wishlist')?>">Go to Wishlist</a></div>
</div>
<?endif?>
<!-- [ends] .mini-wishlist // -->


