<?if($this->getCanDisplayWishlist()):?>
<div class="box mini-wishlist">
	<div class="head">
		<span class="corner"></span>
		<h3>My Wishlist <span class="count"><?=__('(%d items)', $this->getWishlistItems()->getSize())?></span></h3>
		<a href="#"><img src="<?=$this->getSkinUrl('images/widget_collapse_btn.gif')?>" alt="Close box" class="widget-btn"/></a>
	</div>
	<div class="box-container">
				<div class="content">
					<?if($this->getWishlistItems()->getSize()>0):?>
					<ol>
					 <?$_i=1?>
					 <?$_total=sizeof($this->getWishlistItems()->getItems())?>
					 <?foreach($this->getWishlistItems() as $_item):?>
					 				<li <?if($_i==$_total):?> class="last"<?endif;?>>
										<p class="price-box"><strong><?=$_item->getFormatedPrice()?></strong></p>
										<p><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a></p>
										<div class="clear"></div>
										<a href="<?=$this->getUrl('wishlist/index/cart',array('item'=>$_item->getId()))?>"><strong>Add to Cart</strong></a> <a href="<?=$this->getUrl('wishlist/index/remove',array('item'=>$_item->getId()))?>" onclick="return confirm('<?=__('Are You sure?')?>');"><strong>Remove</strong></a>
									</li>
					<?$_i++?>
					<?endforeach;?>
					</ol>
					<?else:?>
				 	<?=__('You have not placed any product yet.')?>
				 	<?endif?>
				</div>
				<p class="actions"><a href="<?=$this->getUrl('wishlist')?>">View My Wishlist</a></p>
			</div>
		</div>
<?endif?>
<!-- [ends] .mini-wishlist // -->

