<div class="page-head">
	<h3><?=__('My Wishlist')?></h3>
</div>

<?=$this->getMessagesBlock()->getHtml()?>
<?if($this->getWishlist()->getSize()):?>
<form action="<?=$this->getUrl('*/*/update')?>" method="post">
    <table cellspacing="0" width="100%" class="data-table" id="wishlist-table">
			<thead>
        <tr>
            <th><?=__('Product')?></th>

            <th><?=__('Comment')?></th>
            <th><?=__('Added At')?></th>
            <th class="a-center">&nbsp;</th>

        </tr>
			</thead>
			<tbody>
        <?foreach($this->getWishlist() as $item):?>
        <tr>
            <td>
                <div><a href="<?=$item->getProductUrl()?>"><img src="<?=$item->getSmallImageUrl()?>" alt="<?=htmlspecialchars($item->getName())?>" width="113"/></a></div>
            	<div><a href="<?=$item->getProductUrl()?>" title="<?=$item->getName()?>"><?=$item->getName()?></a></div>
            	<?=$this->getHelper('catalog/product')->getPriceHtml($item)?>
            </td>
            <td><textarea name="description[<?=$item->getWishlistItemId()?>]" rows="4"><?=$this->getEscapedDescription($item)?></textarea></td>
            <td><?=$this->getFormatedDate($item->getAddedAt())?></td>
            <td class="a-center">
            	<a href="#" onclick="wishlistControl.navigateToUrl('<?=$this->getUrl('*/*/cart',array('item'=>$item->getId()))?>')" class="link-cart"><?=__('Add to cart')?></a><br/>
            	<a href="#" onclick="wishlistControl.navigateToUrlConfirm('<?=$this->getUrl('*/*/remove',array('item'=>$item->getWishlistItemId()))?>')" class="link-remove" /><?=__('Remove')?></a>
            </td>
        </tr>
        <?endforeach?>
				</tbody>
    </table>
<script type="text/javascript">decorateTable('wishlist-table')</script>
    <div class="form-buttons">

			<button onclick="wishlistControl.navigateToUrl('<?=$this->getUrl('*/*/share')?>')" class="form-button-alt" /><span><?=__('Share Wishlist')?></span></button>&nbsp;
			<button onclick="wishlistControl.navigateToUrl('<?=$this->getUrl('*/*/allcart')?>')" class="form-button-alt" /><span><?=__('Add all to cart')?></span></button>&nbsp;
			<button type="submit" class="form-button" name="do"><span><?=__('Update Wishlist')?></span></button>
    </div>
</form>
<?else:?>
    <p><?=__('You have no items in your wishlist.')?></p>
<?endif?>
<script type="text/javascript">
var wishlistControl = {
	navigateToUrl: function (url) {
		window.location.href = url;
	},
	navigateToUrlConfirm: function (url) {
		if(confirm('<?=__('Are you sure?')?>')) {
			this.navigateToUrl(url);
		}
	}

}
</script>