<div class="page-head">
	<h3><?=__('My Wishlist')?></h3>
</div>

<?=$this->getMessagesBlock()->getHtml()?>
<?if($this->getWishlist()->getSize()):?>
<form action="<?=$this->getUrl('*/*/update')?>" method="post">
    <table cellspacing="0" width="100%" class="data-table box-table" id="wishlist-table">
        <thead>
            <tr>
                <th><?=__('Product')?></th>
                <th><?=__('Comment')?></th>
                <th><?=__('Added At')?></th>
                <th class="a-center">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?foreach($this->getWishlist() as $item):?>
            <tr>
                <td>
                    <div><a href="<?=$item->getProductUrl()?>"><img src="<?=$item->getSmallImageUrl()?>" alt="<?=$this->htmlEscape($item->getName())?>" width="113"/></a></div>
                    <div><a href="<?=$item->getProductUrl()?>" title="<?=$this->htmlEscape($item->getName())?>"><?=$item->getName()?></a></div>
                    <?=$this->getHelper('catalog/product')->getPriceHtml($item)?>
                </td>
                <td align="center">
                    <textarea name="description[<?=$item->getWishlistItemId()?>]" style="width:95%;height:160px;" onfocus="focusComment(this)" onblur="focusComment(this)"><?=( $this->getEscapedDescription($item) ) ? __($this->getEscapedDescription($item)) : __('Please enter your comments...') ?></textarea>
                </td>
                <td>
                    <?=$this->getFormatedDate($item->getAddedAt())?>
                </td>
                <td class="a-center">
                    <a href="#" onclick="setLocation('<?=$this->getItemAddToCartUrl($item)?>')" class="link-cart"><?=__('Add to cart')?></a><br/>
                    <a href="#" onclick="confirmRemoveWishlistItem('<?=$this->getItemRemoveUrl($item)?>')" class="link-remove" /><?=__('Remove')?></a>
                </td>
            </tr>
        <?endforeach?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('wishlist-table')</script>
    <div class="form-buttons">
        <button onclick="setLocation('<?=$this->getUrl('*/*/share')?>')" class="form-button-alt" type="button"><span><?=__('Share Wishlist')?></span></button>&nbsp;
        <button onclick="setLocation('<?=$this->getUrl('*/*/allcart')?>')" class="form-button-alt"  type="button"><span><?=__('Add all to cart')?></span></button>&nbsp;
        <button type="submit" class="form-button" name="do"><span><?=__('Update Wishlist')?></span></button>
    </div>
</form>
<?else:?>
    <p><?=__('You have no items in your wishlist.')?></p>
<?endif?>
<script type="text/javascript">
function confirmRemoveWishlistItem(url){
    if(confirm('<?=__('Are you sure?')?>')) {
        setLocation(url);
    }
}

function focusComment(obj) {
    if( obj.value == '<?=__('Please enter your comments...')?>' ) {
        obj.value = '';
    } else if( obj.value == '' ) {
        obj.value = '<?=__('Please enter your comments...')?>';
    }
}
</script>