<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<tr>
    <td class="label">
        <strong><big>
        <?php if ($this->getGrandTotalTitle()): ?>
            <?php echo $this->getGrandTotalTitle() ?>
        <?php else: ?>
            <?php echo __('Grand Total') ?>
        <?php endif; ?>
        </big></strong>
    </td>
    <td class="emph"><big><?php echo $this->displayPriceAttribute('grand_total', true) ?></big></td>
</tr>
