<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->helper('Mage_GiftMessage_Helper_Message')->getIsMessagesAvailable('main', $this->getQuote(), $this->getStoreId())): ?>
<?php $_items = $this->getItems(); ?>
<div id="order-giftmessage">
<div class="clear"></div>
<div class="giftmessage-order-create box-left">
    <div class="entry-edit">
        <div><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('Gift Message for the Entire Order') ?></div><br />
        <div class="fieldset">
            <div>
                <?php if($this->helper('Mage_GiftMessage_Helper_Message')->getIsMessagesAvailable('main', $this->getQuote(), $this->getStoreId())): ?>
                    <div class="entire-order">
                        <h5><?php echo Mage::helper('Mage_Sales_Helper_Data')->__('You can leave a box blank if you don\'t wish to add a gift message for whole order') ?></h5>
                        <?php echo $this->getFormHtml($this->getQuote(), 'main') ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    order.giftmessageFieldsBind('order-giftmessage');
</script>
</div>
<?php endif; ?>
