<a name="pear_iframe"></a>

<div id="pear_iframe_container" style="display:none;">
    <input id="pear_iframe_scroll" type="checkbox" checked="checked"/> <label for="pear_iframe_scroll">Auto-scroll console contents</label><br/>
    <iframe id="pear_iframe" name="pear_iframe" src="<?php echo $this->url('empty') ?>" style="width:100%; height:300px;" frameborder="no"></iframe>
</div>

<script type="text/javascript">
function disableInputs(flag)
{
    top.$$('input, select, button').each(function(el){
        if (el.id!='pear_iframe_scroll') el.disabled = flag;
    });
    if (flag) {
        window.onbeforeunload = confirmExit;
    } else {
        window.onbeforeunload = null;
    }
}

function confirmExit()
{
    return "There are PEAR processes running.\nIf you will close the window or navigate away from the page, installation will be interrupted.";
}

function onSubmit()
{
    top.$('pear_iframe_success').style.display = 'none';
    top.$('pear_iframe_failure').style.display = 'none';
    top.$('pear_iframe_container').style.display = '';
    top.location.href = '#pear_iframe';
    return true;
}

function onSuccess()
{
    var div = top.$('pear_iframe_success');
    if (div) {
        top.location.href = top.location.href.replace(/#.*$/, '')+'#pear_iframe_result';
        div.style.display = '';
    }
}

function onFailure()
{
    var div = top.$('pear_iframe_failure');
    if (div) {
        top.location.href = top.location.href.replace(/#.*$/, '')+'#pear_iframe_result';
        div.style.display = '';
    }
}
</script>
