<?php echo $this->template('header.phtml') ?>

<a href="http://connect.magentocommerce.com/" target="Magento_Connect"><img src="<?php echo $this->baseUrl()?>/skin/images/Magento_Connect.jpg" border="0"/></a>

<form action="<?php echo $this->url('pearPackageUriPost')?>" method="POST" target="pear_iframe" onsubmit="onSubmit()">
    <fieldset>
        <label for="uri">Paste here Install extension URL:</label> <input id="uri" name="uri" style="width:300px"/>
        <button type="submit">Install</button>
    </fieldset>
</form>

<br/>

<form id="pear_packages" class="pear-packages" action="<?php echo $this->url('pearPackagesPost')?>" method="POST" target="pear_iframe" onsubmit="return onSubmit()">
    <select id="clean_sessions" name="clean_sessions">
        <option value="">No</option>
        <option value="1">Yes</option>
    </select>
    <button type="button" onclick="upgradeAll()">Select all upgradable extensions</button>
<script type="text/javascript">
function upgradeAll()
{
    var i, upgrade=false;

    $$('#pear_packages select').each(function(el) {
        for (i=0; i<el.options.length; i++) {
            if (el.options[i].value=='upgrade') {
                el.value = 'upgrade';
                upgrade = true;
            }
        }
    });
    if (upgrade) {
        alert('All available upgrades has been selected. Please click "Commit Changes" button to proceed.');
    } else {
        alert('No upgrades were found');
    }
}

</script>
<?php foreach ($this->get('pear')->getAllPackages() as $channel=>$pkgs): ?>

    <button type="submit" class="f-right">Commit Changes</button>
    <h2 class="page-head">Channel: <?php echo $channel ?></h2>
    <table cellspacing="0">
        <thead>
            <tr>
                <th class="first">Package Name</th>
                <th>Installed</th>
                <th>Available</th>
                <th>State</th>
                <th>Actions</th>
                <th class="last">Summary</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($pkgs as $pkgName=>$pkg): ?>
            <tr class="<?php echo $pkg['status']?>">
                <td class="first"><?php echo $pkgName?></td>
                <td><?php echo $pkg['local_version']?>&nbsp;</td>
                <td><?php echo $pkg['remote_version']?>&nbsp;</td>
                <td><?php echo $pkg['state']?>&nbsp;</td>
                <td><select name="actions[<?php echo $channel.'|'.$pkgName.'|'.$pkg['remote_version'] ?>]" style="width:100%">
                    <option selected="selected"></option>
                    <?php foreach ($pkg['actions'] as $k=>$v): ?>
                    <option value="<?php echo $k ?>"><?php echo $v ?></option>
                    <?php endforeach; ?>
                </select></td>
                <td class="last"><?php echo $pkg['summary']?>&nbsp;</td>
            </tr>
        <?php endforeach; /*channel*/ ?>
        </tbody>
    </table>

<?php endforeach; /*all packages*/ ?>
    <div class="form-btn-set">
        <p class="f-left a-left">
        <span style="background:#f6f6f6;padding:0 5px;">&nbsp;</span> &nbsp;Installed<br/>
        <span style="background:#fcfbbb;padding:0 5px;">&nbsp;</span> &nbsp;Upgrade Available<br/>
        <span style="background:#cbe8fb;padding:0 5px;">&nbsp;</span> &nbsp;3rd party</p>
        <button type="submit">Commit Changes</button>
    </div>
</form>

<?php echo $this->template('pear/iframe.phtml') ?>

<a name="pear_iframe_result"></a>
<div id="pear_iframe_success" style="display:none">
    <?php $this->set('messages', array('success'=>array('Procedure completed. Please check the output frame for useful information and refresh the page to see changes.'))) ?>
    <?php echo $this->template('messages.phtml') ?>
    <button onclick="location.reload()">Refresh</button>
</div>
<div id="pear_iframe_failure" style="display:none">
    <?php $this->set('messages', array('error'=>array('Please check the output frame for errors and refresh the page to retry changes.'))) ?>
    <?php echo $this->template('messages.phtml') ?>
    <button onclick="location.reload()">Refresh</button>
</div>

<?php echo $this->template('footer.phtml') ?>

