<div class="step-body">
    <?if(!empty($addresses)):?>
    <div class="note-box" style="display:block;">
        <p class="option">
            Select a billing address from your address book or enter a &nbsp;
            <a href="#" onclick="billing.setAddress(false); return false;">new address</a>
        </p>
        <select id="billing-address-select" name="billing_address_id" style="width:100%;" onchange="billing.setAddress(this.value);">
            <option value="">New address</option>
        <?foreach($addresses as $_addressId=>$_address):?>
            <option value="<?=$_address->getAddressId()?>" <?if($_address->getAddressId() == $address->getAddressId()):?> selected<?endif?>>
                <?=$_address->getFirstname()?> <?=$_address->getLastname()?> [<?=$_address->getPostcode()?>, <?=$_address->getCity()?>, <?=$_address->getStreet(-1)?>] [<?=$_address->getTelephone()?>]
            </option>
        <?endforeach?>
        </select>
    </div>
    <?endif?>
    <div class="default-box" style="display:block;">
        <form id="co-billing-form">
            <input type="hidden" name="billing[address_id]" value="<?=$address->getAddressId()?>" id="billing:address_id"/>
            <fieldset>
            <ul class="input-list">
                <li>
                    <div class="input-left">
                        <label for="billing:firstname">First Name <span class="required">*</span></label><br/>
                        <input type="text" id="billing:firstname" name="billing[firstname]" value="<?=$address->getFirstname()?>" title="First Name" class="required-entry input-text"/>
                    </div>
                    <div class="input-right">
                        <label for="billing:lastname">Last Name <span class="required">*</span></label><br/>
                        <input type="text" id="billing:lastname" name="billing[lastname]" value="<?=$address->getLastname()?>" title="Last Name" class="required-entry input-text"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <div class="input-left">
                        <label for="billing:company">Company</label><br/>
                        <input type="text" id="billing:company" name="billing[company]" value="<?=$address->getCompany()?>" title="Company" class="input-text"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <label for="billing:street_address">Street Address <span class="required">*</span></label><br/>
                    <input type="text" title="Street Address" name="billing[street][1]" id="billing:street1" value="<?=$address->getStreet(1)?>" class="required-entry input-text"/>
                </li>
                <li>
                    <input type="text" title="Street Address 2" name="billing[street][2]" id="billing:street2" value="<?=$address->getStreet(2)?>" class="input-text"/>
                </li>
                <li>
                    <label for="billing:city">City <span class="required">*</span></label><br/>
                    <input type="text" title="City" name="billing[city]" value="<?=$address->getCity()?>" class="required-entry input-text" id="billing:city"/>
                </li>
                <li>
                    <div class="input-left">
                        <label for="billing:zone_id">State / Province <span class="required">*</span></label><br/>
                        <?if($regions->getSize()):?>
                            <select title="State/Province" id="billing:region" name="billing[region]" class="input-text required-entry">
                                <option value="">Select State/Province...</option>
                                <?=$regions->toHtmlOptions($address->getRegionId())?>
                            </select>
                        <?else:?>
                            <input type="text" id="billing:region" name="billing[region]" value="<?=$address->getRegion()?>"  title="State/Province" class="required-entry input-text"/>
                        <?endif?>
                    </div>
                    <div class="input-right">
                        <label for="billing:postcode">Zip <span class="required">*</span></label><br/>
                        <input type="text" title="ZIP/Post Code" name="billing[postcode]" id="billing:postcode" value="<?=$address->getPostcode()?>" class="validate-zip required-entry input-text"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
                <li>
                    <label for="billing:country_id">Country <span class="required">*</span></label><br/>
                    <select id="billing:country_id" name="billing[country_id]" title="Country">
                        <?=$countries->toHtmlOptions($address->getCountryId())?>
                    </select>
                </li>
                <li>
                    <div class="input-left">
                        <label for="billing:telephone">Telephone <span class="required">*</span></label><br/>
                        <input type="text" name="billing[telephone]" value="<?=$address->getTelephone()?>" title="Telephone" class="required-entry validate-phoneStrict input-text" id="billing:telephone"/></div>
                    <div class="input-right">
                        <label for="billing:fax">Fax</label><br/>
                        <input type="text" name="billing[fax]" value="<?=$address->getFax()?>" title="Fax" class="validate-fax input-text" id="billing:fax"/>
                    </div>
                    <div class="clearfix"></div>
                </li>
            </ul>
        </fieldset>
        </form>
    </div>
    <div class="note-box">
        <p class="a-right"><span class="required">* Required Fields</span></p>
        <input type="button" onclick="checkout.back();" value="Back" class="input-button float-left"/>
        <input type="button" onclick="billing.save();" class="input-button float-right" value="Continue"/>
        <div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var billing = new Billing('co-billing-form', '<?=$baseSecureUrl?>checkout/onepage/getAddress/address/', '<?=$baseSecureUrl?>checkout/onepage/saveBilling/');
    var billingForm = new VarienForm('co-billing-form');
    billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?=$baseSecureUrl?>directory/json/childRegion/');
</script>
