<div class="step-body">
    <div class="default-box">
        <form id="co-payment-form">
            <?=$paymentMethods?>
            <span class="required">* <?=__("Required Fields")?></span>
        </form>
    </div>
    <div class="note-box buttons">
        <input type="button" onclick="checkout.back();" value="Back" class="input-button float-left"/>
        <input type="button" onclick="payment.save();" class="input-button float-right" value="Continue"/>
        <div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var payment = new Payment('co-payment-form', '<?=$baseSecureUrl?>checkout/onepage/savePayment/');
    payment.currentMethod = "<?=$payment->getMethod()?>";
</script>
