<script type="text/javascript">
var Payment = Class.create();
Payment.prototype = {
    initialize: function(form){
        this.form = form;
        this.onSave = this.continue.bindAsEventListener(this);
        var elements = Form.getElements(form);
        var method = null;
        for (var i=0; i<elements.length; i++) {
            if (elements[i].name=='payment[method]') {
                if (elements[i].checked) {
                    method = elements[i].value;
                }
            } else {
                elements[i].disabled = true;
            }
        }
        this.switchMethod(method);
    },
    
    switchMethod: function(method){
        if (this.currentMethod) {
            var form = $('payment_form_'+this.currentMethod);
            form.style.display = 'none';
            var elements = form.getElementsByTagName('input');
            for (var i=0; i<elements.length; i++) elements[i].disabled = true;
            var elements = form.getElementsByTagName('select');
            for (var i=0; i<elements.length; i++) elements[i].disabled = true;

        }
        var form = $('payment_form_'+method);
        form.style.display = '';
        var elements = form.getElementsByTagName('input');
        for (var i=0; i<elements.length; i++) elements[i].disabled = false;
        var elements = form.getElementsByTagName('select');
        for (var i=0; i<elements.length; i++) elements[i].disabled = false;
        this.currentMethod = method;
    },

    save: function(){
        var validator = new Validation(this.form);
        if (validator.validate()) {
            var request = new Ajax.Request(
                '<?=$baseSecureUrl?>checkout/onepage/savePayment/',
                {
                    method:'post',
                    onSuccess: this.onSave,
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    continue: function(){
        checkout.setShipping();
    }
}
</script>

<div class="step-body">
    <div class="default-box">
        <form id="co-payment-form">
            <?=$paymentMethods?>
            <span class="required">* <?=__("Required Fields")?></span>
        </form>
    </div>
    <div class="note-box buttons">
        <input type="button" onclick="checkout.back();" value="Back" class="input-button float-left"/>
        <input type="button" onclick="payment.save();" class="input-button float-right" value="Continue"/>
        <div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var payment = new Payment('co-payment-form');
    payment.currentMethod = "<?=$payment->getMethod()?>";
</script>
