<script type="text/javascript">
var Payment = Class.create();
Payment.prototype = {
    initialize: function(form){
        this.form = form;
        this.onSave = this.continue.bindAsEventListener(this);
    },

    save: function(){
        var validator = new Validation(this.form);
        if (validator.validate()) {
            var request = new Ajax.Request(
                '<?=$baseUrl?>checkout/onepage/savePayment/',
                {
                    method:'post',
                    onSuccess: this.onSave,
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    continue: function(){
        checkout.setShipping();
    }
}
</script>

<div class="step-body">
    <div class="default-box">
        <form id="co-payment-form">
            <?=$paymentMethods?>
        </form>
    </div>
    <div class="note-box buttons">
        <input type="button" onclick="checkout.back();" value="Back" class="input-button float-left"/>
        <input type="button" onclick="payment.save();" class="input-button float-right" value="Continue"/>
        <div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var payment = new Payment('co-payment-form');
</script>
