<div id="checkout-shipping-method" class="step-body">
  	<div id="checkout-shipping-method-load" class="default-box" style="padding:10px;">
  	    <?=$availableMethods?>
  	</div>

    <div class="note-box buttons">
    	<a href="javascript:checkout.back();" class="float-left">&laquo; Back</a>
    	<a href="javascript:shippingMethod.save();" class="float-right"><img src="<?=$baseSkinUrl?>images/btn_continue.gif" alt="Continue"/></a>
    	<div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var shippingMethod = new ShippingMethod('co-shipping-method-form', '<?=$baseSecureUrl?>checkout/onepage/saveShippingMethod/');
</script>
