<div id="checkout-shipping-method" class="step-body">
  	<div id="checkout-shipping-method-load" class="default-box">
  	    <?=$availableMethods?>
  	</div>

    <div class="note-box buttons">
    	<input type="button" onclick="checkout.back();" value="Back" class="input-button float-left" />
    	<input type="button" onclick="shippingMethod.save();" class="input-button float-right" value="Continue" />
    	<div class="clearfix"></div>
    </div>
</div>
<script type="text/javascript">
    var shippingMethod = new ShippingMethod('co-shipping-method-form', '<?=$baseSecureUrl?>checkout/onepage/saveShippingMethod/');
</script>
