<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this \Magento\Reward\Block\Checkout\Payment\Additional */
?>
<?php if ($this->getCanUseRewardPoints()): ?>
    <div class="opc-payment-additional rewardpoints" id="reward_placer">
        <div class="field choice payment">
            <input type="checkbox" name="payment[use_reward_points]" value="1"
                id="use-reward-points"
                data-mage-init='{"checkoutBalance":{
                    "balance":<?php echo (float)$this->getCurrencyAmount(); ?>,
                    "amountSubstracted":<?php if ($this->useRewardPoints()): ?>true<?php else: ?>false<?php endif; ?>,
                    "usedAmount":<?php echo (float)$this->getQuote()->getBaseRewardCurrencyAmount(); ?>
                }}'
                <?php echo $this->useRewardPoints()?' checked="checked"':'' ?> class="checkbox" />
            <label for="use-reward-points" class="label">
                <span>
                    <?php echo __('Use my reward points; %1 are available.', $this->helper('Magento\Reward\Helper\Data')->formatReward($this->getPointsBalance(), $this->getCurrencyAmount())); ?>
                </span>
            </label>
        </div>
    </div>
<?php endif; ?>
