<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\Paypal\Block\Logo
 */
?>
<div class="paypal acceptance">
    <a href="#" title="<?php echo __('Additional Options') ?>"
       onclick="javascript:window.open('<?php echo $this->getAboutPaypalPageUrl() ?>','paypal','width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"
       class="action paypal additional"><img src="<?php echo $this->escapeHtml($this->getLogoImageUrl()) ?>"
                                             alt="<?php echo __('Additional Options') ?>"
                                             title="<?php echo __('Additional Options') ?>"/></a>
</div>
