<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="invoice_items_grid">
    <div class="grid">
        <table cellspacing="0" id="invoice_items_grid_table">
            <thead>
                <tr class="headings">
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('sales')->__('Product ID') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('sales')->__('SKU') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('sales')->__('Product Name') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('sales')->__('Item Status') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('sales')->__('Qty Ordered') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('sales')->__('Qty Backordered') ?></span></th>
                    <th class="no-link" colspan="2"><span class="nobr"><?php echo Mage::helper('sales')->__('Qty Shipped') ?></span></th>
                    <th class="no-link"><span class="nobr"><?php echo Mage::helper('sales')->__('Qty Returned') ?></span></th>
                    <th class="no-link last"><span class="nobr"><?php echo Mage::helper('sales')->__('Qty Cancelled') ?></span></th>
                </tr>
            </thead>
            <tbody>
                <?php $_items = $this->getOrder()->getItemsCollection() ?>
                <?php foreach ($_items as $_item): ?>
                    <tr>
                        <td class="a-center"><?php echo $_item->getProductId() ?></td>
                        <td><?php echo $_item->getSku() ?></td>
                        <td><?php echo $_item->getName() ?></td>
                        <td><?php echo $_item->getStatus() ?></td>
                        <td><?php echo $_item->getQtyOrdered() ?></td>
                        <td><?php echo $_item->getQtyBackordered() ?></td>
                        <td><?php echo $_item->getQtyShipped() ?></td>
                        <td><?php if ($_item->getQtyToShip()): ?><input type="text" class="input-text validate-number" name="items[<?php echo $_item->getId() ?>]" value="<?php echo (!is_null($this->getItemData($_item->getId())) ? $this->getItemData($_item->getId()) : $_item->getQtyToShip()) ?>" style="width: 40px;"/><?php endif; ?></td>
                        <td><?php echo $_item->getQtyReturned() ?></td>
                        <td class="last"><?php echo $_item->getQtyCanceled() ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>