<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\TargetRule\Block\Catalog\Product\Item */
$_item = $this->getItem();
if ($_item):
?>
    <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
        <?php if (!$_item->getRequiredOptions()): ?>
            <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
        <?php endif; ?>
    <?php endif; ?>
    <div class="item-info">
        <a href="<?php echo $this->getProductUrl($_item) ?>" class="product-image"><img src="<?php echo $this->getSmallImageSidebarUrl($_item) ?>" width="<?php echo $this->getSmallImageSidebarSize()?>" height="<?php echo $this->getSmallImageSidebarSize()?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
        <div class="product-details">
            <h3 class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
            <?php echo $this->getPriceHtml($_item, true, '-related') ?>
            <?php if ($this->helper('\Magento\Wishlist\Helper\Data')->isAllow()) : ?>
            <p><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></p>
            <?php endif; ?>
        </div>
    </div>
<?php endif;?>
