<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->canRefundRewardPoints()): ?>
    <p>
        <label for="creditmemo_refund_reward_points_enable"><?php echo __('Refund Reward Points') ?></label>
        <input type="checkbox" name="creditmemo[refund_reward_points_enable]" value="1" <?php if ($this->isAutoRefundEnabled()): ?>checked="checked"<?php endif; ?> id="creditmemo_refund_reward_points_enable">
        <input type="text" name="creditmemo[refund_reward_points]" value="<?php echo $this->getRefundRewardPointsBalance() ?>" id="creditmemo_refund_reward_points" class="input-text not-negative-amount" style="width: 60px; text-align: right;">
        <script type="text/javascript">
require(['prototype'], function(){

        //<![CDATA[
            toggleRewardPointsRefundAmount = function() {
                if ($('creditmemo_refund_reward_points_enable').checked) {
                    $('creditmemo_refund_reward_points').disabled = false;
                } else {
                    $('creditmemo_refund_reward_points').disabled = true;
                }
            }
            Event.observe($('creditmemo_refund_reward_points_enable'), 'change', toggleRewardPointsRefundAmount);
            toggleRewardPointsRefundAmount();
        //]]>
        
});
</script>
    </p>
<?php endif; ?>
