<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Order by SKU widget template
 *
 * @var $this \Magento\AdvancedCheckout\Block\Widget\Sku
 */
$uniqueSuffix = '_' . $this->getRandomString(20);
$skuFormId = 'skuForm' . $uniqueSuffix;
$qtyValidationClasses = 'required-entry validate-number validate-greater-than-zero'
    . ' validate-number-range number-range-0.0001-99999999.9999';
?>
<div class="widget block addbysku" data-mage-init='{"itemTable":{"addBlockData":{"uniqueSuffix":"<?php echo $uniqueSuffix; ?>"}}}'>
    <?php if (!$this->getIsTitleHidden()): ?>
        <div class="title"><strong><?php echo __('Order by SKU') ?></strong></div>
    <?php endif ?>
    <div class="content">
        <form id="<?php echo $skuFormId; ?>" class="form addbysku" action="<?php echo $this->getFormAction(); ?>" method="post"
            data-mage-init='{"validation":{}}'
            <?php if ($this->getIsMultipart()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <fieldset class="fieldset" data-container="items"></fieldset>

            <?php echo $this->getChildHtml(); ?>

            <div class="actions">
                <div class="primary">
                    <button id="sku-submit-button<?php echo $uniqueSuffix; ?>" type="submit"
                            title="<?php echo __('Add to Cart') ?>" class="action tocart">
                        <span><?php echo __('Add to Cart') ?></span>
                    </button>
                </div>
                <div class="secondary">
                    <button type="button" id="add_new_item_button<?php echo $uniqueSuffix; ?>"
                            title="<?php echo __('Add Row') ?>" class="action add" data-role="add">
                        <span><?php echo __('Add Row') ?></span>
                    </button>
                </div>
            </div>
            <?php if ($this->getLink()): ?>
                <?php echo $this->getLink(); ?>
            <?php endif; ?>
        </form>
        <script data-template="add-block" type="text/x-jQuery-tmpl">
            <div class="fields" data-mage-init='{"deletableItem":{}}'>
                <div class="field sku required">
                    <label for="id-items[${rowIndex}${uniqueSuffix}][sku]" class="label"><span><?php echo __('Sku') ?></span></label>
                    <div class="control">
                        <input type="text"
                               name="items[${rowIndex}${uniqueSuffix}][sku]"
                               id="id-items[${rowIndex}${uniqueSuffix}][sku]"
                               data-id="${rowIndex}${uniqueSuffix}sku"
                               data-validate="{'required-if-not-specified': '#customer_sku_csv'}"/>
                    </div>
                </div>
                <div class="field qty required">
                    <label class="label" for="id-items[${rowIndex}${uniqueSuffix}][qty]"><span><?php echo __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="items[${rowIndex}${uniqueSuffix}][qty]"
                               id="id-items[${rowIndex}${uniqueSuffix}][qty]"
                               class="qty"
                               maxlength="13"
                               data-validate="{'required-if-specified': '[data-id=${rowIndex}${uniqueSuffix}sku]', 'validate-greater-than-zero': true}"/>
                    </div>
                </div>
                <button class="action remove" title="<?php echo __('Remove Row') ?>" data-role="delete"><span><?php echo __('Remove Row') ?></span></button>
            </div>
        </script>
    </div>
</div>
