<table style="width:100%;">
    <tr>
        <td style="width:20%;padding-right:5px;">
            <?=$this->_getRenameFormHtml();?>
            <?=$this->_getAddFormHtml();?>
            <script type="text/javascript" language="javascript">
                var renameForm = new varienForm('<?=$this->_getRenameFormId()?>');
                var addForm = new varienForm('<?=$this->_getAddFormId()?>');
            </script>
        </td>
        <td style="border-left:1px solid #dfdfdf;padding-left:8px;">
            <?=$this->_getGridHtml()?>
        </td>
    </tr>
</table>