<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<a href="<?php echo $this->getCheckoutUrl()?>" title="<?php echo $this->helper('Mage_Checkout_Helper_Data')->__('Checkout with Multiple Addresses');?>"><?php echo $this->helper('Mage_Checkout_Helper_Data')->__('Checkout with Multiple Addresses');?></a>
