<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
namespace Magento\Framework\App\Filesystem;

/**
 * Class DirectoryList
 */
class DirectoryList extends \Magento\Framework\Filesystem\DirectoryList
{
    /**
     * Directory for dynamically generated public view files, relative to STATIC_VIEW_DIR
     */
    const CACHE_VIEW_REL_DIR = '_cache';

    /**
     * Custom application dirs
     */
    const INIT_PARAM_PATHS = 'MAGE_DIR_PATHS';

    /**
     * Custom application urls
     */
    const INIT_PARAM_URLS = 'MAGE_DIR_URLS';

    /**
     * Code base root
     */
    const ROOT_DIR = 'base';

    /**
     * Most of entire application
     */
    const APP_DIR = 'app';

    /**
     * Modules
     */
    const MODULES_DIR = 'code';

    /**
     * Themes
     */
    const THEMES_DIR = 'design';

    /**
     * Initial configuration of the application
     */
    const CONFIG_DIR = 'etc';

    /**
     * Libraries or third-party components
     */
    const LIB_INTERNAL = 'lib_internal';

    /**
     * Libraries/components that need to be accessible publicly through web-server (such as various DHTML components)
     */
    const LIB_WEB = 'lib_web';

    /**
     * Language packages
     */
    const LOCALE_DIR = 'i18n';

    /**
     * \Directory within document root of a web-server to access static view files publicly
     */
    const PUB_DIR = 'pub';

    /**
     * Storage of files entered or generated by the end-user
     */
    const MEDIA_DIR = 'media';

    /**
     * Storage of static view files that are needed on HTML-pages, emails or similar content
     */
    const STATIC_VIEW_DIR = 'static';

    /**
     * Various files generated by the system in runtime
     */
    const VAR_DIR = 'var';

    /**
     * Temporary files
     */
    const TMP_DIR = 'tmp';

    /**
     * File system caching directory (if file system caching is used)
     */
    const CACHE_DIR = 'cache';

    /**
     * Logs of system messages and errors
     */
    const LOG_DIR = 'log';

    /**
     * File system session directory (if file system session storage is used)
     */
    const SESSION_DIR = 'session';

    /**
     * Dependency injection related file directory
     *
     */
    const DI_DIR = 'di';

    /**
     * Relative directory key for generated code
     */
    const GENERATION_DIR = 'generation';

    /**
     * Temporary directory for uploading files by end-user
     */
    const UPLOAD_DIR = 'upload';

    /**
     * System base temporary folder
     */
    const SYS_TMP_DIR = 'sys_tmp';

    /**
     * 'figure out default value for this const'
     */
    const HTTP = '';

    /**
     * Directories configurations
     *
     * @var array
     */
    protected $directories = array(
        self::ROOT_DIR => array('path' => ''),
        self::APP_DIR => array('path' => 'app'),
        self::MODULES_DIR => array('path' => 'app/code'),
        self::CONFIG_DIR => array('path' => 'app/etc'),
        self::LIB_INTERNAL => array('path' => 'lib/internal'),
        self::VAR_DIR => array(
            'path' => 'var',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::CACHE_DIR => array(
            'path' => 'var/cache',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::LOG_DIR => array(
            'path' => 'var/log',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::DI_DIR => array('path' => 'var/di'),
        self::GENERATION_DIR => array('path' => 'var/generation'),
        self::HTTP => array('path' => ''),
        self::LOCALE_DIR => array('path' => 'app/i18n'),
        self::SYS_TMP_DIR => array(
            'path' => '',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::SESSION_DIR => array(
            'path' => 'var/session',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        )
    );

    /**
     * @param string $root
     * @param array $directories
     */
    public function __construct($root, array $directories = array())
    {
        $this->directories[self::SYS_TMP_DIR]['path'] = sys_get_temp_dir();
        parent::__construct($root, $directories);
    }
}
