<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
namespace Magento\Framework\App\Filesystem;

/**
 * Class DirectoryList
 */
class DirectoryList extends \Magento\Framework\Filesystem\DirectoryList
{
    /**
     * Custom application dirs
     */
    const INIT_PARAM_PATHS = 'MAGE_DIRS';

    /**
     * Custom application urls
     */
    const INIT_PARAM_URLS = 'MAGE_URLS';

    /**
     * Code base root
     */
    const ROOT = 'base';

    /**
     * Most of entire application
     */
    const APP = 'app';

    /**
     * Modules
     */
    const MODULES = 'code';

    /**
     * Themes
     */
    const THEMES = 'design';

    /**
     * Initial configuration of the application
     */
    const CONFIG = 'etc';

    /**
     * Libraries or third-party components
     */
    const LIB_INTERNAL = 'lib_internal';

    /**
     * Libraries/components that need to be accessible publicly through web-server (such as various DHTML components)
     */
    const LIB_WEB = 'lib_web';

    /**
     * Language packages
     */
    const LOCALE = 'i18n';

    /**
     * \Directory within document root of a web-server to access static view files publicly
     */
    const PUB = 'pub';

    /**
     * Storage of files entered or generated by the end-user
     */
    const MEDIA = 'media';

    /**
     * Storage of static view files that are needed on HTML-pages, emails or similar content
     */
    const STATIC_VIEW = 'static';

    /**
     * Various files generated by the system in runtime
     */
    const VAR_DIR = 'var';

    /**
     * Temporary files
     */
    const TMP = 'tmp';

    /**
     * File system caching directory (if file system caching is used)
     */
    const CACHE = 'cache';

    /**
     * Logs of system messages and errors
     */
    const LOG = 'log';

    /**
     * File system session directory (if file system session storage is used)
     */
    const SESSION = 'session';

    /**
     * Dependency injection related file directory
     */
    const DI = 'di';

    /**
     * Relative directory key for generated code
     */
    const GENERATION = 'generation';

    /**
     * Temporary directory for uploading files by end-user
     */
    const UPLOAD = 'upload';

    /**
     * System base temporary folder
     */
    const SYS_TMP = 'sys_tmp';

    /**
     * Directories configurations
     *
     * @var array
     */
    protected $directories = array(
        self::ROOT => array('path' => ''),
        self::APP => array('path' => 'app'),
        self::MODULES => array('path' => 'app/code'),
        self::CONFIG => array('path' => 'app/etc'),
        self::LIB_INTERNAL => array('path' => 'lib/internal'),
        self::VAR_DIR => array(
            'path' => 'var',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::CACHE => array(
            'path' => 'var/cache',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::LOG => array(
            'path' => 'var/log',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::DI => array('path' => 'var/di'),
        self::GENERATION => array('path' => 'var/generation'),
        self::LOCALE => array('path' => 'app/i18n'),
        self::SYS_TMP => array(
            'path' => '',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        ),
        self::SESSION => array(
            'path' => 'var/session',
            'read_only' => false,
            'allow_create_dirs' => true,
            'permissions' => 0777
        )
    );

    /**
     * @param string $root
     * @param array $directories
     */
    public function __construct($root, array $directories = array())
    {
        $this->directories[self::SYS_TMP]['path'] = sys_get_temp_dir();
        parent::__construct($root, $directories);
    }
}
