<script type="text/javascript" src="<?=$baseUrl?>/js/varien/telephone.js"></script>
<script type="text/javascript" src="<?=$baseUrl?>/js/varien/accordion.js"></script>
<script type="text/javascript">
var Checkout = Class.create();
Checkout.prototype = {
    initialize: function(accordion){
        this.accordion = accordion;
        this.type = '';
        this.billing = '';
        this.payment = '';
        this.shipping= '';
    }, 
    
    reloadStatusBlock: function(){
        var updater = new Ajax.Updater('column-left', '<?=$moduleBaseUrl?>/onepage/status/', {method: 'get'});
    },
    
    reloadShippingMethodBlock: function(){
    	var updater = new Ajax.Updater('checkout-shipping-method-load', '<?=$moduleBaseUrl?>/onepage/shippingMethod/', {method: 'get'});
    },

    setType: function(){
        if ($('checkout_type:guest') && $('checkout_type:guest').checked) {
            //alert('guest');
        }
        else if($('checkout_type:register') && $('checkout_type:register').checked) {
            //alert('register');
        }

        this.accordion.openNextSection(true);
    },

    setBilling: function() {
        this.reloadStatusBlock();
        this.accordion.openNextSection(true);
    },

    setPayment: function() {
        this.reloadStatusBlock();
        this.accordion.openNextSection(true);
    },

    setShipping: function() {
        this.reloadShippingMethodBlock();
        this.reloadStatusBlock();
        this.accordion.openNextSection(true);
    },
        
    setShippingMethod: function() {
        this.reloadStatusBlock();
        this.accordion.openNextSection(true);
    },
    
    setReview: function() {
        this.reloadStatusBlock();
    	this.accordion.openNextSection(true);
    },
    
    back: function(){
        this.accordion.openPrevSection(true);
    }
}
</script>
<div class="content page-checkout">
    <div id="checkoutSteps" class="page-checkout">
    <?foreach($steps as $_stepId => $_stepInfo):?>
        <div class="section<?if(!empty($_stepInfo['allow'])):?> allow<?endif?>" id="<?=$_stepId?>">
            <h3><?=$_stepInfo['label']?></h3>
            <div class="a-item" style="display:none;" id="checkout-step-<?=$_stepId?>">
            <?=$$_stepId?>
            </div>
        </div>
    <?endforeach?>
    </div>
    <script>
        var accordion = new Accordion('checkoutSteps','h3',true);
        <?if($_activeStep=$currentBlock->getLastAllowStep()):?>
        accordion.openSection('<?=$_activeStep?>');
        <?endif?>
        
        var checkout = new Checkout(accordion);
    </script>
</div>