<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_modern2
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="home main">
    <div class="banner main">
        <img class="banner image" alt="modern2" src="<?php echo $this->getViewFileUrl('images/main_image1.jpg') ?>" />
        <div class="banner content">
            <span class="banner title">Irresistable</span>
            <span class="banner text">home collection</span>
            <a class="action banner" href="#"><span>Shop now</span></a>
        </div>
    </div>
</div>

<div class="home banners">
    <a href="#" class="banner link style1">
        <img class="banner image" alt="modern2" src="<?php echo $this->getViewFileUrl('images/banner1.jpg') ?>" />
    </a>
    <a href="#" class="banner link style2">
        <img class="banner image" alt="modern2" src="<?php echo $this->getViewFileUrl('images/banner2.jpg') ?>" />
    </a>
    <a href="#" class="banner link style2">
        <img class="banner image" alt="modern2" src="<?php echo $this->getViewFileUrl('images/banner3.jpg') ?>" />
    </a>
    <a href="#" class="banner link style4">
        <img class="banner image" alt="modern2" src="<?php echo $this->getViewFileUrl('images/banner4.jpg') ?>" />
    </a>
</div>