<?$_orders = $this->getOrders();?>
<div class="page-head">
    <h3><?=__('My Orders')?></h3>
</div>
<?=$this->getPagerHtml();?>
<?if($_orders->getSize()):?>
<table cellspacing="0" class="data-table" id="my-orders-table">
    <thead>
        <tr>
            <th><?=__('Order #')?></th>
            <th><?=__('Date')?></th>
            <th><?=__('Ship to')?></th>
            <th><?=__('Order Total')?></th>
            <th><?=__('Status')?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?$_odd = '';?>
        <?foreach ($_orders as $_order):?>
            <tr>
                <td><?=$_order->getRealOrderId()?></td>
                <td><?=$this->formatDate($_order->getCreatedAt())?></td>
                <td><?=$_order->getShippingAddress()->getFirstname()?> <?=$_order->getShippingAddress()->getLastname()?></td>
                <td><?=$_order->getOrderCurrency()->format($_order->getGrandTotal())?></td>
                <td><em><?=$_order->getStatus($_order->getStatusId())->getFrontendLabel()?></em></td>
                <td class="a-center"><a href="<?=$this->getViewUrl($_order)?>"><?=__('View')?></a><?/*<span class="separator">|</span><a href="<?=$this->getTrackUrl($_order)?>"><?=__('Track')?></a>*/?></td>
            </tr>
        <?endforeach;?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?=$this->getPagerHtml();?>
<?else:?>
    <p><?=__('You have not placed any orders.');?></p>
<?endif?>