<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="account-box ad-orders">
<?$_orders = $this->getOrders();?>
    <div class="head">
        <h4><?=__('Recent Orders')?></h4>
        <?if( sizeof($_orders->getItems()) > 0 ):?><a href="<?=$baseUrl?>sales/order/history/"><?=__('View All')?></a><?endif;?>
    </div>
<?if( sizeof($_orders->getItems()) > 0 ):?>
    <table cellspacing="0" class="data-table" id="my-orders-table">
        <thead>
            <tr>
                <th><?=__('Order #')?></th>
                <th><?=__('Date')?></th>
                <th><?=__('Ship to')?></th>
                <th><?=__('Order Total')?></th>
                <th><?=__('Status')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?$_odd = '';?>
			<?foreach ($_orders as $_order):?>
				<tr class="<?=($_odd = ($_odd ? 'odd' : ''))?>">
					<td><?=$_order->getRealOrderId()?>&nbsp;</td>
					<td><?=$this->formatDate($_order->getCreatedAt())?> </td>
					<td><?=$_order->getShippingAddress()->getFirstname()?> <?=$_order->getShippingAddress()->getLastname()?>&nbsp;</td>
					<td><?=$_order->getOrderCurrency()->format($_order->getGrandTotal())?>&nbsp;</td>
					<td><em><?=$_order->getStatus($_order->getStatusId())->getFrontendLabel()?></em>&nbsp;</td>
					<td class="last a-center"><a href="<?=$this->getViewUrl($_order)?>"><?=__('View')?></a><?/*<span class="separator">|</span><a href="<?=$this->getTrackUrl($_order)?>"><?=__('Track')?></a>*/?>&nbsp;</td>
				</tr>
			<?endforeach;?>
        </tbody>
    </table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?else:?>
    <p><?=__('You have not placed any orders.');?></p>
<?endif;?>
</div>