<?$_orders = $this->getOrders();?>
<div class="account-box">
    <div class="head">
        <h4><?=__('Recent Orders')?></h4>
        <a href="<?=$baseUrl?>sales/order/history/"><?=__('View All')?></a>
    </div>
    <table cellspacing="0" class="data-table">
        <thead>
            <tr>
                <th><?=__('Order #')?></th>
                <th><?=__('Date')?></th>
                <th><?=__('Ship to')?></th>
                <th><?=__('Order Total')?></th>
                <th><?=__('Status')?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?$_odd = '';?>
        <?foreach ($_orders as $_order):?>
            <tr class="<?=($_odd = ($_odd ? 'odd' : ''))?>">
                <td><?=$_order->getRealOrderId()?></td>
                <td><?=$this->getOrderDateFormatted($_order)?></td>
                <td><?=$_order->getShippingAddress()->getFirstname()?> <?=$_order->getShippingAddress()->getLastname()?></td>
                <td><?=$_order->getOrderCurrency()->format($_order->getGrandTotal())?></td>
                <td><em><?=$_order->getStatus($_order->getStatusId())->getFrontendLabel()?></em></td>
                <td class="last a-center"><a href="<?=$this->getViewUrl($_order)?>"><?=__('View')?></a><span class="separator">|</span><a href="<?=$this->getTrackUrl($_order)?>"><?=__('Track')?></a></td>
            </tr>
        <?endforeach;?>
        </tbody>
    </table>
</div>