<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="account balance">
<h2 class="subtitle"><?php echo Mage::helper('Enterprise_CustomerBalance_Helper_Data')->__('Balance'); ?></h2>
<?php echo Mage::helper('Enterprise_CustomerBalance_Helper_Data')->__('Your current balance is:'); ?>

<?php echo Mage::helper('Mage_Core_Helper_Data')->currency($this->getBalance()); ?>
</div>
