<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this \Magento\GiftRegistry\Block\Search\Advanced  */ ?>

<?php foreach ($this->getAttributes() as $code => $attribute): ?>
    <div class="field">
        <label for="<?php echo $this->getFieldIdPrefix().$code ?>" class="label"><span><?php echo $attribute['label'] ?></span></label>
        <div class="control">
            <?php echo $this->renderField($code) ?>
        </div>
    </div>
<?php endforeach; ?>

<script type="text/javascript">
require(['jquery', 'mage/mage'], function(jQuery){

    (function($) {
        $('#gr-type-specific-fieldset').toggle(<?php echo ($this->getAttributes() ? "true" : "false");?>);
    <?php if ($this->getRegionJsVisible()): ?>
        $('#<?php echo $this->getFieldIdPrefix() . $this->getElementCountry()?>').mage('regionUpdater', {
            optionalRegionAllowed: <?php echo ($this->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
            regionListId: '#<?php echo $this->getFieldIdPrefix() . $this->getElementRegion()?>',
            regionInputId: '#<?php echo $this->getFieldIdPrefix() . $this->getElementRegionText()?>',
            regionJson: <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson(); ?>,
            isRegionRequired: false,
            isZipRequired: false,
            isCountryRequired: false
        });
    <?php endif; ?>
    })(jQuery)

});
</script>
