<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<span id="gr-please-wait" class="please-wait load indicator" style="display: none;" daat-text="<?php echo __('Please wait, loading...') ?>">
    <span><?php echo __('Please wait, loading...') ?></span>
</span>
<form action="<?php echo $this->getActionUrl() ?>" method="post" id="gr-search-form" class="form giftregistry search" data-hasrequired="* <?php echo __('Required Fields') ?>">
    <fieldset class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php echo __('Search Options') ?></span></legend><br>
        <div class="field type">
            <label for="params-type-id" class="label"><span><?php echo __('Gift Registry Type') ?></span></label>
            <div class="control">
                <?php echo $this->getTypeSelectHtml() ?>
                <div class="note"><?php echo __('For better search results, first choose a gift registry type. By default, we search all registry types.') ?></div>
            </div>
        </div>
        <div class="field name required">
            <label for="params_firstname" class="label"><span><?php echo __('First Name') ?></span></label>
             <div class="control">
                <input name="params[firstname]" id="params_firstname" type="text" value="<?php echo $this->getFormData('firstname') ?>" class="input-text required-entry" />
            </div>
        </div>
        <div class="field lastname required">
            <label for="params_lastname" class="label"><span><?php echo __('Last Name') ?></span></label>
            <div class="control">
                <input name="params[lastname]" id="params_lastname" type="text" value="<?php echo $this->getFormData('lastname') ?>" class="input-text required-entry" />
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset" id="gr-type-specific-fieldset" style="display:none;">
        <legend class="legend"><span><?php echo __('Type Specific Options') ?></span></legend><br>
        <div class="field" id="gr-type-specific-options"></div>
    </fieldset>

    <div class="actions">
        <input type="hidden" name="params[search]" value="type" />
        <button type="submit" class="action search"><span><?php echo __('Search') ?></span></button>
    </div>
</form>

<form action="<?php echo $this->getActionUrl() ?>" method="post" id="gr-search-email-form" class="form giftregistry search" data-hasrequired="* <?php echo __('Required Fields') ?>">
    <fieldset class="fieldset">
        <div class="field email required">
             <label for="params_email" class="label"><span><?php echo __('Recipient Email') ?></span></label>
             <div class="control">
                 <input name="params[email]" id="params_email" type="text" value="<?php echo $this->getFormData('email') ?>" class="input-text required-entry validate-email" />
             </div>
        </div>
    </fieldset>
    <div class="actions">
        <input type="hidden" name="params[search]" value="email" />
        <button type="submit" class="action search"><span><?php echo __('Search') ?></span></button>
    </div>
</form>

<form action="<?php echo $this->getActionUrl() ?>" method="post" id="gr-search-id-form" class="form giftregistry search" data-hasrequired="* <?php echo __('Required Fields') ?>">
    <fieldset class="fieldset">
        <div class="field id required">
             <label for="params_id" class="label"><span><?php echo __('Gift Registry ID') ?></span></label>
             <div class="control">
                 <input name="params[id]" id="params_id" type="text" value="<?php echo $this->getFormData('id') ?>" class="input-text required-entry" />
             </div>
        </div>
    </fieldset>
    <div class="actions">
        <input type="hidden" name="params[search]" value="id" />
        <button type="submit" class="action search"><span><?php echo __('Search') ?></span></button>
    </div>
</form>

<script type="text/javascript">
require(['jquery', "mage/mage"], function($){

    $('form[id^="gr-search"]').mage('validation');
    
    $('#params-type-id').mage('advancedSearch', {
        url: '<?php echo $this->getAdvancedUrl() ?>',
        selectedOption: '<?php echo ($this->getFormData('type_id') ? $this->getFormData('type_id') : null); ?>'
    });

});
</script>

<?php if ($this->getSearchResults() && $this->getSearchResults()->getSize()): ?>
<div class="block giftregistry results">
    <div class="title"><strong><?php echo __('Search Results') ?></strong></div>
    <div class="content">
        <div class="toolbar"><?php echo $this->getChildHtml('pager') ?></div>
        <table class="data table" id="giftregistry-search-results">
            <thead>
                <tr>
                    <th class="col name"><?php echo __('Name') ?></th>
                    <th class="col location"><?php echo __('Location') ?></th>
                    <th class="col event"><?php echo __('Event') ?></th>
                    <th class="col type"><?php echo __('Type') ?></th>
                    <th class="col date"><?php echo __('Event Date') ?></th>
                    <th class="col actions"></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->getSearchResults() as $item): ?>
                <tr>
                    <td class="col name"><?php echo $this->escapeHtml($item->getRegistrant()) ?></td>
                    <td class="col location"><?php echo $this->escapeHtml($item->getEventLocation()) ?></td>
                    <td class="col event"><?php echo $this->escapeHtml($item->getTitle()) ?></td>
                    <td class="col type"><?php echo $this->escapeHtml($item->getType()) ?></td>
                    <td class="col date"><?php echo $this->getFormattedDate($item) ?></td>
                    <td class="col actions"><a href="<?php echo $this->getRegistryLink($item) ?>" class="action view"><span><?php echo __('View') ?></span></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class="toolbar"><?php echo $this->getChildHtml('pager') ?></div>
    </div>
</div>
<?php elseif ($this->getSearchResults()): ?>
    <?php echo __('Your search returned no results.') ?>
<?php endif; ?>
