<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->getEnabled() && $this->getTypesCollection()->getSize()) : ?>
<div class="block giftregistry search">
    <div class="title"> <strong><?php echo __('Gift Registry Search') ?></strong></div>
    <div class="content">
        <form id="gr-quick-search-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="form giftregistry search">
            <div class="field name required">
                <?php echo $this->getBlockHtml('formkey')?>
                <label for="params-firstname" class="label"><span><?php echo __('First Name') ?></span></label>
                <div class="control">
                    <input type="text" class="input-text" data-validate="{required:true,minlength:2}" id="params-firstname" name="params[firstname]">
                </div>
            </div>
            <div class="field lastname required">
                <label for="params-lastname" class="label"><span><?php echo __('Last Name') ?></span></label>
                <div class="control">
                    <input type="text" class="input-text" data-validate="{required:true,minlength:2}" id="params-lastname" name="params[lastname]">
                    <div class="note">* <?php echo __('Please enter at least two letters of the name.') ?></div>
                </div>
            </div>
            <div class="field type required">
                <label class="label"><span><?php echo __('Type') ?></span></label>
                <div class="control"><?php echo $this->getTypeSelectHtml() ?></div>
            </div>
            <div class="actions">
                <input type="hidden" name="params[search]" value="type">
                <button type="submit" title="<?php echo __('Go') ?>" class="action search"><span><?php echo __('Search') ?></span></button>
            </div>
        </form>

        <form id="gr-quick-search-email-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="form giftregistry search">

            <div class="field email required">
                <?php echo $this->getBlockHtml('formkey')?>
                <label for="params_email" class="label"><span><?php echo __('Recipient Email') ?></span></label>
                <div class="control">
                    <input type="text" class="input-text required-entry validate-email" id="params_email" name="params[email]" />
                </div>
            </div>

            <div class="actions">
                <input type="hidden" name="params[search]" value="email">
                <button type="submit" title="<?php echo __('Go') ?>" class="action search"><span><?php echo __('Search') ?></span></button>
            </div>
        </form>

        <form id="gr-quick-search-id-form" action="<?php echo $this->getActionUrl() ?>" method="post" class="form giftregistry search">
            <div class="field id required">
                <?php echo $this->getBlockHtml('formkey')?>
                <label for="params_id" class="label"><span><?php echo __('Gift Registry ID') ?></span></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry" id="params_id" name="params[id]" />
                </div>
            </div>
            <div class="actions">
                <input type="hidden" name="params[search]" value="id">
                <button type="submit" title="<?php echo __('Go') ?>" class="action search"><span><?php echo __('Search') ?></span></button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
require(['jquery', "mage/mage"], function($){

    $('form[id^="gr-quick-search"]').mage('validation');

});
</script>
<?php endif; ?>
