<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Weee\Block\Item\Price\Renderer */
?>
<?php $_item = $this->getItem() ?>
<div class="pricing details<?php echo $this->displayBothPrices() ? ' complex' : ''; ?>">
    <?php if ($this->displayPriceExclTax() || $this->displayBothPrices()): ?>
        <div class="rate">
            <?php if ($this->displayBothPrices()): ?>
                <span class="label excl tax"><?php echo __('Excl. Tax'); ?></span>
            <?php else: ?>
                <span class="label display"><?php echo __('Price'); ?></span>
            <?php endif; ?>
            <span class="value display">
                <?php echo $this->formatPrice($this->getUnitDisplayPriceExclTax()) ?>
            </span>
        </div>

        <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
            <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
                <div class="rate weee">
                    <span class="label weee"><?php echo $tax['title']; ?></span>
                    <span class="value weee"><?php echo $this->formatPrice($tax['amount'],true,true); ?></span>
                </div>
            <?php endforeach; ?>

            <?php if ($this->displayFinalPrice()): ?>
                <div class="rate weee total">
                    <span class="label weee"><?php echo __('Total:'); ?></span>
                    <span class="value weee"><?php echo $this->formatPrice($this->getFinalUnitDisplayPriceExclTax()); ?></span>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>

<?php if ($this->displayPriceInclTax() || $this->displayBothPrices()): ?>
<?php $_incl = $this->getPriceInclTax($_item); ?>
    <div class="rate">
        <?php if ($this->displayBothPrices()): ?>
            <span class="label tax incl"><?php echo __('Incl. Tax'); ?></span>
        <?php else: ?>
            <span class="label display"><?php echo __('Price'); ?></span>
        <?php endif; ?>

        <span class="value display">
                <?php echo $this->formatPrice($this->getUnitDisplayPriceInclTax()) ?>
        </span>
    </div>
    <?php if ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item)): ?>
        <?php foreach ($this->helper('Magento\Weee\Helper\Data')->getApplied($_item) as $tax): ?>
            <div class="rate weee">
                <span class="label weee"><?php echo $tax['title']; ?></span>
                <span class="value weee"><?php echo $this->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
            </div>
        <?php endforeach; ?>

        <?php if ($this->displayFinalPrice()): ?>
            <div class="rate weee total">
                <span class="label weee"><?php echo __('Total:'); ?></span>
                <span class="value weee"><?php echo $this->formatPrice($this->getFinalUnitDisplayPriceInclTax()); ?></span>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
</div>
