<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<script type="text/javascript">
    //<![CDATA[
    (function($) {
        head.js("<?php echo $this->getSkinUrl('Mage_Page::js/cookies.js')?>",
            "<?php echo $this->getSkinUrl('Mage_PageCache::js/cookie.js')?>", function() {
                $.mage.noCacheCookie({
                    name: '<?php echo Mage_PageCache_Helper_Data::NO_CACHE_COOKIE ?>',
                    lifetime: <?php echo Mage::helper('Mage_PageCache_Helper_Data')->getNoCacheCookieLifetime() ?>,
                    expires: $.cookie.defaults.expires
                });
            });
    })(jQuery);
    //]]>
</script>
