<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/** @var $this \Magento\Core\Block\Template */
/** @var $helper \Magento\CatalogSearch\Helper\Data */
$helper = $this->helper('Magento\CatalogSearch\Helper\Data');
?>
<div class="block search">
    <div class="title"><strong><?php echo __('Search') ?></strong></div>
    <div class="content search">
        <form class="form minisearch" id="search_mini_form" action="<?php echo $helper->getResultUrl() ?>"
      method="get">
            <div class="field search">
                <label class="label" for="search"><?php echo __('Search') ?></label>
                <div class="control">
                    <input id="search" type="text" name="<?php echo $helper->getQueryParamName() ?>" value="<?php echo $helper->getEscapedQueryText() ?>" placeholder="<?php echo __('Search entire store here...') ?>" class="input-text" autocomplete="off"/>
                    <div id="search_autocomplete" class="search autocomplete"></div>
                    <a class="action advanced" href="<?php echo $helper->getAdvancedSearchUrl(); ?>"><?php echo __('Advanced Search'); ?></a>
                </div>
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo __('Search') ?>" class="action search"><span><?php echo __('Search') ?></span></button>
            </div>
            <script type="text/javascript">
            //<![CDATA[
            (function($) {
                head.js("<?php echo $this->getViewFileUrl('Magento_CatalogSearch::form-mini.js')?>", function() {
                    $('#search').catalogSearch({
                        formSelector: '#search_mini_form',
                        url: '<?php echo $helper->getSuggestUrl() ?>',
                        destinationSelector: '#search_autocomplete'
                        //placeholder: '<?php echo __('Search entire store here...') ?>',
                    });
                });
            })(jQuery);
            //]]>
            </script>
        </form>
    </div>
</div>


<?php /*
<form id="search_mini_form" action="<?php echo $helper->getResultUrl() ?>"
      method="get">
    <div class="form-search">
        <label for="search"><?php echo __('Search:') ?></label><input id="search" type="text" name="<?php echo $helper->getQueryParamName() ?>" value="<?php echo $helper->getEscapedQueryText() ?>" class="input-text" autocomplete="off"/>&nbsp;<button type="submit" title="<?php echo __('Search') ?>" class="button"><span><span><?php echo __('Search') ?></span></span></button><a href="<?php echo $helper->getAdvancedSearchUrl(); ?>"><?php echo __('Advanced Search'); ?></a>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
        (function($) {
            head.js("<?php echo $this->getViewFileUrl('Magento_CatalogSearch::form-mini.js')?>", function() {
                $('#search').catalogSearch({
                    formSelector: '#search_mini_form',
                    placeholder: '<?php echo __('Search entire store here...') ?>',
                    url: '<?php echo $helper->getSuggestUrl() ?>',
                    destinationSelector: '#search_autocomplete'
                });
            });
        })(jQuery);
        //]]>
        </script>
    </div>
</form>
*/ ?>
