<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if( sizeof($this->getTerms()) > 0 ): ?>
    <ul class="search terms">
        <?php foreach ($this->getTerms() as $_term): ?>
            <li><a href="<?php echo $this->getSearchUrl($_term) ?>" style="font-size:<?php echo $_term->getRatio()*70+75 ?>%;"><?php echo $this->escapeHtml($_term->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <div class="note-msg"><div><?php echo __('There are no search terms available.'); ?></div></div>
<?php endif; ?>
