<?
/**
 * @methods
 *  getTitle() - string
 *  getSaveUrl() - string
 *  getSections() - array
 *  getForm() - html
 */
?>
<table cellspacing="0" width="100%">
	<tr>
		<td class="content-left-nav">
			<h3><?=$this->getTitle()?></h3>
			<?=$this->getChildHtml('dwstree')?>
		</td>
		<td>
			<div class="content-header">
				<table cellspacing="0" class="grid-header"> 
						<tr>
								<td></td>
								<td class="form-buttons"><?=$this->getSaveButtonHtml()?></td>
						 </tr>
				</table>
			</div>
			<form action="<?=$this->getSaveUrl()?>" method="post" id="config_edit_form">
			<?=$this->getChildHtml('form')?>
			</form>
		</td>
	</tr>
</table>


<script type="text/javascript" language="javascript">
    var configForm = new varienForm('config_edit_form');
</script>