<?
/**
 * @methods
 *  getTitle() - string
 *  getSaveUrl() - string
 *  getSections() - array
 *  getForm() - html
 */
?><h3><?=$this->getTitle()?></h3>
<div style="border-left:17.2em solid #fff; margin-top:.65em; zoom:1;">
	<div class="entry-edit-container" style="float:right; position:relative; width:100%; zoom:1;">
	<div class="entry-edit" style="margin-left:2em;">
	
<div class="content-header" style="margin-top:-2.4em;" style="position:relative; zoom:1;">
    <table cellspacing="0" class="grid-header"> 
        <tr>
            <td></td>
            <td class="form-buttons"><?=$this->getSaveButtonHtml()?></td>
         </tr>
    </table>
</div>
    <form action="<?=$this->getSaveUrl()?>" method="post" id="config_edit_form">
    <?=$this->getChildHtml('form')?>
    </form>
</div>
</div>

<div class="content-left-nav">
    <?=$this->getChildHtml('dwstree')?>
</div>
</div>

<script type="text/javascript" language="javascript">
    var configForm = new varienForm('config_edit_form');
</script>