<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo $this->helper('enterprise_customerbalance')->__('Store Credit Balance')?></h4>
    </div>
    <div class="fieldset">
        <?php if ($this->shouldShowOneBalance()):?>
            <p><?php echo $this->helper('enterprise_customerbalance')->__('Total:')?> <?php echo $this->getOneBalanceTotal()?></p>
        <?php else:?>
            <?php echo $this->getChildHtml('grid')?>
        <?php endif; ?>
    </div>
</div>
