<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $entityValues = $this->getEntityValues() ?>

<?php if ($this->getEnabled() && count($entityValues)): ?>
<form action="<?php echo $this->getAddUrl();?>" method="post" id="add-cart-items-to-gift-registry" class="form giftregistry">
    <fieldset class="fieldset">
        <div class="field giftregistry">
            <div class="control">
                <select id="giftregistry_entity" name="entity" title="<?php echo __('Gift Registry') ?>" data-validate="{required:true}">
                    <?php foreach ($entityValues as $_entity):?>
                        <option value="<?php echo $_entity->getValue()?>" title="<?php echo $_entity->getTitle()?>"><?php echo $this->escapeHtml($this->helper('Magento\Core\Helper\String')->truncate($_entity->getTitle(), 40))?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>
        <button type="submit" class="action add">
            <span><?php echo __('Add All To Gift Registry ');?></span>
        </button>
    </fieldset>
</form>
<script type="text/javascript">
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function() {
                $('#add-cart-items-to-gift-registry').validation();
            });
    })(jQuery);
</script>
<?php endif; ?>
