<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="box-collateral box-tags">
    <h2><?php echo $this->__('Product Tags') ?></h2>
    <?php echo $this->getChildHtml('list_before')?>
    <?php if( $this->getCount() ): ?>
    <h3><?php echo $this->__('Other people marked this product with these tags:') ?></h3>
    <?php $_uniqueProductTagsId = $this->getUniqueHtmlId('product-tags_')?>
    <ul id="<?php echo $_uniqueProductTagsId ?>" class="product-tags">
        <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
    </ul>
    <script type="text/javascript">
        (function($) {$.mage.decorator.general($('#<?php echo $_uniqueProductTagsId?>').find('li'), ['first','last']);})(jQuery);
    </script>
    <?php endif; ?>
    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
        <div class="form-add">
            <label for="productTagName"><?php echo $this->__('Add Your Tags:') ?></label>
            <div class="input-box">
                <input type="text" class="input-text"  data-validate="{required:true}" name="productTagName" id="productTagName" />
            </div>
            <button type="submit" title="<?php echo $this->__('Add Tags') ?>" class="button">
                <span>
                    <span><?php echo $this->__('Add Tags') ?></span>
                </span>
            </button>
        </div>
    </form>
    <p class="note"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
    <script type="text/javascript">
      (function($) {
          $.mage.event.observe('mage.tag.initialize', function (e, o) {
              o.formSelector = '#addTagForm'
          });
          $.mage.load.js("<?php echo $this->getSkinUrl('jquery/jquery.validate.js')?>");
          $.mage.load.js("<?php echo $this->getSkinUrl('jquery/additional-methods.js')?>");
          $.mage.load.js("<?php echo $this->getSkinUrl('jquery/jquery.metadata.js')?>");
          $.mage.load.js("<?php echo $this->getSkinUrl('jquery/jquery.hook.js')?>");
          $.mage.load.js("<?php echo $this->getSkinUrl('mage/validation/validate.js')?>");
          $.mage.load.js("<?php echo $this->getSkinUrl('Mage_Tag::list.js')?>");
    })(jQuery);
    </script>
</div>
