<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Magento_Payment_Block_Catalog_Product_View_Profile
 */
?>
<?php if ($dateHtml = $this->getDateHtml()): ?>
<dl>
    <dt>
        <label for="<?php echo $this->getDateHtmlId() ?>"><?php echo __('Recurring Profile Start Date') ?></label>
    </dt>
    <dd>
        <?php echo $dateHtml ?>
    </dd>
</dl>
<?php endif; ?>
