<?if($_section=='subject'):?>
Welcome <?=$customer->getName()?>
<?else:?>
Welcome <strong><?=$customer->getName()?></strong>!

<p>Thank you very much for creating an account.</p>

<p>To officially log in when you're visiting our site, simply click on "Login" or "My Account" located at the top of every page, and then enter your e-mail address and the password you have chosen.</p>

<p>==========================================</br>
Use the following values when prompted to log in:</br>
E-mail: <?=$customer->getEmail()?></br>
Password: <?=$customer->getPassword()?></br>
==========================================</p>

When you log in to your account, you will be able to do the following:</br>

* Proceed through checkout faster when making a purchase</br>
* Check the status of orders</br>
* View past orders</br>
* Make changes to your account information</br>
* Change your password</br>
* Store up to 5 alternative shipping addresses (for shipping to multiple family members and friends!)</br>

If you have any questions about your account or any other matter, please feel free to contact us at 
<a href="mailto:magento@varien.com">magento@varien.com</a> or by phone at 1-111-111-1111.</br>
</br>
Thanks again!
<?endif?>