Welcome <strong>{$customer.name}</strong>!

Thank you very much for creating an account with McGruff Specialty Products Office.

To officially log in when you're visiting our site, simply click on "Login" or "My Account" located at the top of every page, and then enter your e-mail address and the password you have chosen.

==========================================
Use the following values when prompted to log in:
E-mail: {$customer.email_address}
Password: {$customer.password}
==========================================

When you log in to your account, you will be able to do the following:

* Proceed through checkout faster when making a purchase
* Check the status of orders
* View past orders
* Make changes to your account information
* Change your password
* Store up to 5 alternative shipping addresses (for shipping to multiple family members and friends!)

If you have any questions about your account or any other matter, please feel free to contact us at <a href="mailto:email@bcd.com">email@bcd.com</a> or by phone at 1-785-842-1414.

Thanks again!

Your internet buddies and best friends forever,

McGruff Specialty Products Office