<?php
/**
 * {license_notice}
 *
 * @category    Magento
 * @package     Magento_Core
 * @subpackage  integration_tests
 * @copyright   {copyright}
 * @license     {license_link}
 */

namespace Magento\Session;

class SessionManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Magento\Session\SessionManagerInterface
     */
    protected $_model;

    /**
     * @var \Magento\Session\SidResolverInterface
     */
    protected $_sidResolver;

    protected function setUp()
    {
        $objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();

        /** @var \Magento\Session\SidResolverInterface $sidResolver */
        $this->_sidResolver = $objectManager->get('Magento\Session\SidResolverInterface');

        /** @var \Magento\Core\Model\Session\AbstractSession _model */
        $this->_model = $objectManager->create(
            'Magento\Session\SessionManager',
            array(
                $objectManager->create('Magento\App\RequestInterface'),
                $this->_sidResolver,
                $objectManager->create('Magento\Session\Config\ConfigInterface'),
                $objectManager->create('Magento\Session\SaveHandlerInterface'),
                $objectManager->create('Magento\Session\ValidatorInterface'),
                $objectManager->create('Magento\Session\StorageInterface')
            )
        );
    }

    protected function tearDown()
    {
        $this->_model->destroy();
    }

    public function testGetData()
    {
        $this->_model->setData(array('test_key' => 'test_value'));
        $this->assertEquals('test_value', $this->_model->getData('test_key', true));
        $this->assertNull($this->_model->getData('test_key'));
    }

    public function testGetSessionId()
    {
        $this->assertEquals(session_id(), $this->_model->getSessionId());
    }

    public function testGetName()
    {
        $this->assertEquals(session_name(), $this->_model->getName());
    }

    public function testSetName()
    {
        $this->_model->setName('test');
        $this->assertEquals('test', $this->_model->getName());
    }

    public function testDestroy()
    {
        $data = array('key' => 'value');
        $this->_model->setData($data);

        $this->assertEquals($data, $this->_model->getData());
        $this->_model->destroy();

        $this->assertEquals(array(), $this->_model->getData());
    }

    public function testSetSessionId()
    {
        $sessionId = $this->_model->getSessionId();
        $this->_model->setSessionId($this->_sidResolver->getSid($this->_model));
        $this->assertEquals($sessionId, $this->_model->getSessionId());

        $this->_model->setSessionId('test');
        $this->assertEquals('test', $this->_model->getSessionId());
    }

    /**
     * @magentoConfigFixture current_store web/session/use_frontend_sid 1
     */
    public function testSetSessionIdFromParam()
    {
        $this->assertNotEquals('test_id', $this->_model->getSessionId());
        $_GET[$this->_sidResolver->getSessionIdQueryParam($this->_model)] = 'test-id';
        $this->_model->setSessionId($this->_sidResolver->getSid($this->_model));

        $this->assertEquals('test-id', $this->_model->getSessionId());

        /* Use not valid identifier */
        $_GET[$this->_sidResolver->getSessionIdQueryParam($this->_model)] = 'test_id';
        $this->_model->setSessionId($this->_sidResolver->getSid($this->_model));
        $this->assertEquals('test-id', $this->_model->getSessionId());
    }


    public function testGetSessionIdForHost()
    {
        $_SERVER['HTTP_HOST'] = 'localhost';
        $this->_model->start('test');
        $this->assertEmpty($this->_model->getSessionIdForHost('localhost'));
        $this->assertNotEmpty($this->_model->getSessionIdForHost('test'));
    }

    public function testIsValidForHost()
    {
        $_SERVER['HTTP_HOST'] = 'localhost';
        $this->_model->start('test');

        $reflection = new \ReflectionMethod($this->_model, '_addHost');
        $reflection->setAccessible(true);
        $reflection->invoke($this->_model);

        $this->assertFalse($this->_model->isValidForHost('test.com'));
        $this->assertTrue($this->_model->isValidForHost('localhost'));
    }

    /**
     * @param string $saveMethod
     * @param string $iniValue
     * @param array $params
     * @dataProvider sessionSaveMethodDataProvider
     * @magentoAppIsolation enabled
     */
    public function testSessionSaveMethod($saveMethod, $iniValue, array $params)
    {
        // depending on configuration some values cannot be set as default save session handlers.
        // in such cases warnings will be generated by php and test will fail
        $origErrorRep = error_reporting(E_ALL ^ E_WARNING);
        $origSessionHandler = ini_set('session.save_handler', $iniValue);
        if ($iniValue && (ini_get('session.save_handler') != $iniValue)) {
            ini_set('session.save_handler', $origSessionHandler);
            error_reporting($origErrorRep);
            $this->markTestSkipped("Can't  set '$iniValue' as session save handler");
        }
        ini_set('session.save_handler', $origSessionHandler);

        $objectManger = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();

        $params = array_merge(array('saveMethod' => $saveMethod), $params);
        /** @var \Magento\Core\Model\Session\Config $config */
        $config = $objectManger->create('Magento\Core\Model\Session\Config', $params);


        $sessionManager = $objectManger->create('Magento\Session\SessionManager', array('sessionConfig' => $config));
        $sessionManager->start();

        $this->assertEquals(ini_get('session.save_handler'), $iniValue);
    }

    /**
     * @return array
     */
    public function sessionSaveMethodDataProvider()
    {
        $cases = array(
            'db'           => array('db', 'user', array()),
            'eaccelerator' => array('eaccelerator', 'eaccelerator', array()),
            //'empty'        => array('', '', array()),
            //'dummy'        => array('dummy', '', array()),
        );

        if (defined('MEMCACHE_SESSION_SAVE_PATH')) {
            array_merge($cases, array(
                'memcache' => array('memcache', 'memcache', array('savePath' => MEMCACHE_SESSION_SAVE_PATH))
            ));
        }

        if (defined('MEMCACHED_SESSION_SAVE_PATH')) {
            array_merge($cases, array(
                'memcached' => array('memcached', 'memcached', array('savePath' => MEMCACHED_SESSION_SAVE_PATH))
            ));
        }

        return $cases;
    }

    /**
     * @param string $saveMethod
     * @dataProvider sessionSaveMethodWarningDataProvider
     * @magentoAppIsolation enabled
     */
    public function testSessionSaveMethodWarning($saveMethod)
    {
        $objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();

        //TODO We got no exception but Error/Warning
        try {
            /** @var \Magento\Core\Model\Session\Config $config */
            $objectManager->create('Magento\Core\Model\Session\Config', array('saveMethod' => $saveMethod));
            $this->fail('Expected warning is not thrown');
        } catch (\InvalidArgumentException $e) {
            //do nothing
        }
    }

    /**
     * @return array
     */
    public function sessionSaveMethodWarningDataProvider()
    {
        return array(
            'empty' => array('', '', array()),
            'dummy' => array('dummy', '', array()),
        );
    }
}
