<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->getQuote()->hasVirtualItems()): ?>
    <h2 class="section-title"><?php echo __('Other items in your order') ?></h2>
    <div class="col2-set">
        <div class="col-1 narrow"></div>
        <div class="col-2 wide">
            <h3><?php echo __('Items') ?> <span class="separator">|</span> <a href="<?php echo $this->getVirtualProductEditUrl() ?>"><?php echo __('Edit Items') ?></a></h3>
            <table class="data-table" id="unavailable-shipping-table">
                <col />
                <col width="1" />
                <thead>
                    <tr>
                        <th><?php echo __('Product Name') ?></th>
                        <th class="a-center"><?php echo __('Qty') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getVirtualQuoteItems() as $_item): ?>
                    <tr>
                        <td><?php echo $this->getItemHtml($_item) ?></td>
                        <td class="a-center"><?php echo $_item->getQty() ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <script type="text/javascript">(function($) {$('#unavailable-shipping-table').decorate('table')})(jQuery)</script>
        </div>
    </div>
<?php endif; ?>
