<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="discount">
        <h2><?php echo __('Discount Codes') ?></h2>
        <div class="discount-form">
            <label for="coupon_code"><?php echo __('Enter your coupon code if you have one.') ?></label>
            <input type="hidden" name="remove" id="remove-coupon" value="0" />
            <div class="input-box">
                <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo __('Apply Coupon') ?>" class="button apply-coupon" value="<?php echo __('Apply Coupon') ?>"><span><span><?php echo __('Apply Coupon') ?></span></span></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo __('Cancel Coupon') ?>" class="button cancel-coupon" value="<?php echo __('Cancel Coupon') ?>"><span><span><?php echo __('Cancel Coupon') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
            "<?php echo $this->getViewFileUrl('Magento_Checkout::js/discount-codes.js')?>", function() {
                $('#discount-coupon-form').discountCode({
                    couponCodeSelector: '#coupon_code', removeCouponSelector: '#remove-coupon',
                    applyButton: 'button.apply-coupon', cancelButton: 'button.cancel-coupon'
                });
            });
    })(jQuery);
//]]>
</script>
