<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\Info
 */
?>
<?php
$helper = $this->helper('Magento\Reward\Helper\Data');
$maxBalance = $this->getMaxBalance();
$minBalance = $this->getMinBalance();
$expireIn = $this->getExpireIn();
?>
<div class="block reward info">
    <div class="title">
        <strong><?php echo __('Reward points balance Information'); ?></strong>
        <a class="action more" href="<?php echo $helper->getLandingPageUrl()?>"><?php echo __('Learn more')?></a>
    </div>
    <div class="content">
        <p><?php echo __('Your balance is %1.', $helper->formatReward($this->getPointsBalance(), $this->getCurrencyBalance()))?></p>

        <p class="reward rates">
            <?php echo __('Current exchange rates:')?>
        <?php if ($this->getPtsToAmountRateAmount() || $this->getAmountToPtsRatePts()): ?>
            <?php if ($this->getPtsToAmountRateAmount()): ?>
            <span><?php echo __('Each %1 can be redeemed for %2.', $helper->formatReward($this->getPtsToAmountRatePts(), null, null, '<strong>%s</strong>'), '<strong>' . $helper->formatAmount($this->getPtsToAmountRateAmount()) . '</strong>')?></span>
            <?php endif;?>
            <?php if ($this->getAmountToPtsRatePts()): ?>
            <span><?php echo __('Each %1 spent will earn %2.', '<strong>' . $helper->formatAmount($this->getAmountToPtsRateAmount()) . '</strong>', $helper->formatReward($this->getAmountToPtsRatePts(), null, null, '<strong>%s</strong>'))?></span>
            <?php endif;?>
        <?php else:?>
            <span><?php echo __('None.')?></span>
        <?php endif;?>
        </p>
        <?php if ($maxBalance || $minBalance):?>
            <p class="reward limit">
                <strong><?php echo __('Balance limitations:')?></strong>
            <?php if ($maxBalance):?>
                <span><?php echo __('The balance is capped at %1.', $helper->formatReward($maxBalance))?></span>
                <?php if ($this->getIsMaxBalanceReached()):?>
                    <span class="warning"><?php echo __('Maximum balance is reached')?></span>
                <?php endif;?>
            <?php endif;?>
            <?php if ($minBalance):?>
                <span><?php echo __('Balance Redemption Threshold: %1.', $helper->formatReward($minBalance))?></span>
                <?php if (!$this->getIsMinBalanceReached()):?>
                    <span class="warning"><?php echo __('You do not have the minimum balance you need to redeem your rewards points.')?></span>
                <?php endif;?>
            <?php endif;?>
        <?php endif;?>
        <?php if ($expireIn):?>
            <p><?php echo __('Each earned reward points record expires in %1 days.', '<span>' . $expireIn . '</span>')?></p>
            <?php if ($this->getIsHistoryPublished()):?>
                <p><?php echo __('Refer to reward points history to see if and when a specific record expires.')?></p>
            <?php endif;?>
        <?php endif;?>
    </div>
</div>
