<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * @see \Magento\Reward\Block\Customer\Reward\Settings
 */
?>
<form class="form reward-settings" action="<?php echo $this->getUrl('reward/customer/saveSettings') ?>" method="post" id="form-validate">
    <?php echo $this->getBlockHtml('formkey')?>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Email Notification Settings'); ?></span></legend><br />
        <div class="field choice">
            <input type="checkbox" name="subscribe_updates" id="subscribe_updates" value="1" title="<?php echo __('Subscribe for balance updates') ?>"<?php if ($this->isSubscribedForUpdates()): ?> checked="checked"<?php endif; ?> />
            <label class="label" for="subscribe_updates"><span><?php echo __('Subscribe for balance updates') ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="subscribe_warnings" id="subscribe_warnings" value="1"<?php if ($this->isSubscribedForWarnings()): ?> checked="checked"<?php endif; ?>/>
            <label class="label" for="subscribe_warnings"><span><?php echo __('Subscribe for points expiration notifications') ?></span></label>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php echo __('Save Subscription Settings') ?>"><span><?php echo __('Save Subscription Settings') ?></span></button>
        </div>
    </div>
</form>
