<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="col2-set">
    <h2 class="sub-title"><?php echo __('Address Book') ?> <span class="separator">|</span> <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo __('Manage Addresses') ?></a></h2>
    <div class="col-1">
        <div class="info-box">
            <h3 class="box-title"><?php echo __('Default Billing Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo __('Edit Address') ?></a></h3>
            <address class="box-content">
                <?php echo $this->getPrimaryBillingAddressHtml() ?>
            </address>
        </div>
    </div>
    <div class="col-2">
        <div class="info-box">
            <h3 class="box-title"><?php echo __('Default Shipping Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo __('Edit Address') ?></a></h3>
            <address class="box-content">
                <?php echo $this->getPrimaryShippingAddressHtml() ?>
            </address>
        </div>
    </div>
</div>
