<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Rma\Block\Order\Button */
?>
<?php if ($this->helper('Magento\Rma\Helper\Data')->canCreateRma($this->getOrder())): ?>
    <a href="<?php echo $this->helper('Magento\Rma\Helper\Data')->getReturnCreateUrl($this->getOrder()) ?>" class="action return"><span><?php echo __('Return') ?></span></a>
<?php endif;?>
