<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var $this \Magento\Sales\Block\Order\Comments
 * @see \Magento\Sales\Block\Order\Comments
 */
?>
<?php if ($this->hasComments()):?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?php echo $this->getTitle() ?></h2>
        <dl class="order-about">
            <?php foreach ($this->getComments() as $_commentItem): ?>
                <dt><?php echo $this->formatDate($_commentItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?php echo $this->escapeHtml($_commentItem->getComment()) ?></dd>
            <?php endforeach; ?>
        </dl>
    </div>
<?php endif;?>
