<?if( $this->getCollection() && $this->count()):?>
    <div class="head">
        <h4><?=__('My Recent Reviews')?></h4>
        <a href="<?=$this->getAllReviewsUrl()?>"><?=__('View All')?></a>
    </div>
    <?$iterator = 0?>
    <?foreach ($this->getCollection() as $_review):?>
    <ol class="recent-reviews">
        <li <?if($iterator % 2 == 0):?>class="odd"<?endif;?>>
            <div class="count"><?=++$iterator?></div>
            <div class="content">
                <a href="<?=$this->getReviewUrl($_review->getId())?>"><?=$_review->getName()?></a>
                <div class="ratings">
                    <small><?=__('RATING')?>:</small>
                    <?if($_review->getSum()):?>
                        <div class="rating-box">
                            <div class="rating" style="width:<?=( $_review->getSum() / $_review->getCount() )?>%;"></div>
                        </div>
                    <?endif;?>
                 </div>
            </div>
        </li>
    </ol>
    <?endforeach;?>
<?endif;?>