<?if($this->getProductData()->getId()):?>
    <div class="page-head">
        <h3><?=__('Review Details')?></h3>
    </div>

    <div class="my-review-detail">
			<div class="product-image">
				<p><a href="<?=$this->getProductData()->getProductUrl()?>"><img src="<?=$this->getProductData()->getImageUrl()?>" alt="<?=$this->getProductData()->getName()?>" height="125" width="125"></a><br/>
				<?if( $this->getRating() && $this->getRating()->getSize()):?>
    				<small><?=__('Average Customer Rating')?>:</small></p>
    				<?=$this->getHelper('review/helper')->getSummaryHtml($this->getProductData())?>
				<?endif;?>
			</div>
			<div class="details">
				<h3><?=$this->getProductData()->getName()?></h3>
				<?if( $this->getRating() && $this->getRating()->getSize()):?>
				<strong><?=__('YOUR RATING:')?></strong>
					<table cellspacing="0" class="ratings-list">
					<?foreach ($this->getRating() as $_rating):?>
					<?if($_rating->getPercent()):?>
						<tr>
							<td class="label"><?=__($_rating->getRatingCode())?></td>
							<td><div class="rating-box">
								<div class="rating" style="width:<?=ceil($_rating->getPercent())?>%;"></div>
							</div></td>
						</tr>
					<?endif;?>
					<?endforeach;?>
					</table>
				<?endif;?>
				<strong><?=__('YOUR REVIEW')?></strong> ( <?=__('submitted on')?> <?=$this->dateFormat($this->getReviewData()->getCreatedAt())?>):
				<div class="description">
					<p><?=nl2br($this->getReviewData()->getDetail())?></p>
				</div>
			</div>
		</div>
		<div class="form-buttons"><a href="<?=$this->getBackUrl()?>" class="left">&laquo; <?=__('Back to My Reviews')?></a></div>
	</div>
<?endif;?>