<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @var $this \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if($this->isMsgVisible()): ?>
    <div class="availability only" title="<?php echo __('Only %1 left', ($this->getStockQtyLeft())) ?>">
        <?php echo __('Only %1 left', "<strong>{$this->getStockQtyLeft()}</strong>") ?>
    </div>
<?php endif ?>
