<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view"><?php echo Mage::helper('Enterprise_Reward_Helper_Data')->__('Reward Points Balance') ?></h4>
    </div>
    <fieldset>
        <?php echo $this->getChildHtml('grid') ?>
    </fieldset>
</div>
