<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="entry-edit rule-tree">
<?php echo $this->getFormHtml() ?>
</div>
<script type="text/javascript">
/*
    if ($('rule_conditions_fieldset')) {
        var conditionsForm = new VarienRulesForm('rule_conditions_fieldset', '<?php echo $this->getNewConditionChildUrl() ?>');
    }
    if ($('rule_actions_fieldset')) {
        var actionsForm = new VarienRulesForm('rule_actions_fieldset', '<?php echo $this->getNewActionChildUrl() ?>');
    }
*/
</script>
