<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="widget widget-banner">
    <?php $bannersContent =  $this->getBannersContent() ?>
    <ul>
    <?php foreach ($bannersContent as $bannerId => $content): ?>
        <li><?php echo $content?></li>
    <?php endforeach; ?>
    </ul>
</div>
