<?php
/**
 * {license_notice}
 *   
 * @copyright   {copyright}
 * @license     {license_link}
 */
namespace Magento\UrlRewrite\Service\V1\Data;

interface FilterDataInterface
{
    /**
     * @param int $entityId
     *
     * @return $this
     */
    public function setEntityId($entityId);

    /**
     * @param int|array $entityType
     *
     * @return $this
     */
    public function setEntityType($entityType);

    /**
     * @param string $requestPath
     *
     * @return $this
     */
    public function setRequestPath($requestPath);

    /**
     * @param int $storeId
     *
     * @return $this
     */
    public function setStoreId($storeId);

    /**
     * @param string|array $redirectType
     *
     * @return $this
     */
    public function setRedirectType($redirectType);

    /**
     * @param int $isAutoGenerated
     * @return $this
     */
    public function setIsAutoGenerated($isAutoGenerated);
}

 