<div class="entry-edit rule-tree" id="<?=$this->getForm()->getId()?>-container">
<?=$this->getFormHtml()?>
</div>

<script type="text/javascript">
    var conditionsForm = new VarienRulesForm('<?=$this->getForm()->getId()?>-container', '<?=$this->getNewConditionChildUrl()?>');
    var actionsForm = new VarienRulesForm('<?=$this->getForm()->getId()?>-container', '<?=$this->getNewActionChildUrl()?>');
</script>