<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/* @var $this Enterprise_Wishlist_Block_Customer_Wishlist_Management */
?>
<?php if ($this->getCurrentWishlist()): ?>
<div class="wishlist-management">
    <div class="sub-title">
        <h2><?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?><a href="#" data-wishlist-edit='{"url":"<?php echo $this->getEditUrl($this->getCurrentWishlist()->getId());?>", "name":"<?php echo Mage::helper('Magento_Core_Helper_Data')->quoteEscape($this->getCurrentWishlist()->getName(), true);?>", "isPublic":<?php echo $this->getCurrentWishlist()->getVisibility() ? 'true' : 'false';?>}' title="<?php echo __('Edit Wish List')?>" class="link-edit wishlist-edit"><?php echo __('Edit')?></a><span class="item-count">(<?php echo $this->getItemCount($this->getCurrentWishlist());?>)</span></h2>
    </div>
    <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
        <button type="button" id="wishlist-create-button" data-wishlist-create='{"url":"<?php echo $this->getCreateUrl();?>"}' title="<?php echo __('Create New Wish List') ?>" class="button btn-create"><span><span><?php echo __('Create New Wish List') ?></span></span></button>
    <?php endif;?>
    <?php if ($this->getCurrentWishlist()->getVisibility()): ?>
        <p class="note-msg msg-public"><?php echo __('This wishlist is publicly visible.'); ?></p>
        <?php else: ?>
        <p class="note-msg msg-private"><?php echo __('This wishlist is private. Only you can view this wishlist.');?></p>
    <?php endif; ?>
    <div class="table-caption">
        <div class="label"><?php echo __('Wish List:'); ?></div>
        <div id="wishlists-select" class="split-button">
            <strong><span title="<?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?>"><?php echo $this->escapeHtml($this->getCurrentWishlist()->getName());?></span></strong>
            <a class="change" href="#">(<span><?php echo __('Change') ?></span>)</a>
            <div class="list-container">
                <ul>
                    <?php foreach($this->getWishlists() as $wishlist): ?>
                        <?php if ($wishlist->getId() != $this->getCurrentWishlist()->getId()): ?>
                            <li><a title="<?php echo $this->escapeHtml($wishlist->getName());?>" href="<?php echo $this->getWishlistManagementUrl($wishlist);?>"><?php echo $this->escapeHtml($wishlist->getName());?></a></li>
                        <?php endif; ?>
                    <?php endforeach;?>
                    <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                        <li class="new"><span data-wishlist-create='{"url":"<?php echo $this->getCreateUrl();?>"}' title="<?php echo __('Create New Wish List')?>"><?php echo __('Create New Wish List')?></span></li>
                    <?php endif;?>
                </ul>
            </div>
        </div>
        <?php if($this->getCurrentWishlist()->getItemsCount()): ?>
            <div id="wishlists-move" class="split-button" data-wishlist-move='{"moveSelectedUrl":"<?php echo $this->getMoveSelectedUrl();?>", "moveItemUrl":"<?php echo $this->getMoveItemUrl();?>"}'>
                <strong><span <?php if ($this->getCurrentWishlist()->getId() != $this->getDefaultWishlist()->getId()): ?>data-wishlist-move-selected='{"wishlistId":"<?php echo $this->getDefaultWishlist()->getId();?>"}'<?php endif;?>><?php echo __('Move to Wish List');?></span></strong>
                <a href="#" class="change"><?php echo __('Move To:') ?></a>
                <div class="list-container">
                    <ul>
                        <?php foreach ($this->getWishlists() as $wishlist): ?>
                            <?php if ($wishlist->getId() !== $this->getCurrentWishlist()->getId()): ?>
                                <li><span data-wishlist-move-selected='{"wishlistId":"<?php echo $wishlist->getId();?>"}' title="<?php echo $this->escapeHtml($wishlist->getName());?>"><?php echo $this->escapeHtml($wishlist->getName());?></span></li>
                            <?php endif; ?>
                        <?php endforeach;?>
                        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                            <li class="new"><span data-wishlist-move-selected='{"new":true}' title="<?php echo __('Create New Wish List')?>" ><?php echo __('Create New Wish List')?></span></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
            <div id="wishlists-copy" class="split-button" data-wishlist-copy='{"copySelectedUrl":"<?php echo $this->getCopySelectedUrl();?>", "copyItemUrl":"<?php echo $this->getCopyItemUrl();?>"}'>
                <strong><span  <?php if ($this->getCurrentWishlist()->getId() != $this->getDefaultWishlist()->getId()): ?>data-wishlist-copy-selected='{"wishlistId":"<?php echo $this->getDefaultWishlist()->getId();?>"}'<?php endif;?>><?php echo __('Copy to Wish List');?></span></strong>
                <a href="#" class="change"><?php echo __('Copy To:') ?></a>
                <div class="list-container">
                    <ul>
                        <?php foreach ($this->getWishlists() as $wishlist): ?>
                            <?php if ($wishlist->getId() !== $this->getCurrentWishlist()->getId()): ?>
                                <li><span data-wishlist-copy-selected='{"wishlistId":"<?php echo $wishlist->getId();?>"}' title="<?php echo $this->escapeHtml($wishlist->getName());?>"><?php echo $this->escapeHtml($wishlist->getName());?></span></li>
                            <?php endif;?>
                        <?php endforeach;?>
                        <?php if ($this->canCreateWishlists($this->getWishlists())): ?>
                            <li class="new"><span data-wishlist-copy-selected='{"new":true}' title="<?php echo __('Create New Wish List')?>"><?php echo __('Create New Wish List')?></span></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        <?php endif;?>
    </div>
</div>
<?php endif; ?>
