<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Gift registry items template
 *
 * @see \Magento\GiftRegistry\Block\Items
 */
?>
<?php
    $_itemsCount = count($this->getItems());
?>
<div class="block giftregistry shared items">
    <div class="title"><strong><?php echo __('Gift Registry Items') ?></strong></div>
    <form action="<?php echo $this->getActionUrl() ?>" method="post" class="form giftregistry">
        <table id="shopping-cart-table" class="data table giftregistry cart">
            <thead>
                <tr>
                    <th class="col photo">&nbsp;</th>
                    <th class="col product"><?php echo __('Product Name') ?></th>
                    <th class="col registered"><?php echo __('Requested') ?></th>
                    <th class="col fulfilled"><?php echo __('Fulfilled') ?></th>
                    <th class="col remaining"><?php echo __('Remaining') ?></th>
                    <th class="col price"><span class="nobr"><?php echo __('Unit Price') ?></span></th>
                    <th class="col qty"><?php echo __('Qty') ?></th>
                </tr>
            </thead>
            <?php if ($_itemsCount): ?>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <button type="submit" title="<?php echo __('Add to Cart') ?>" class="action tocart"><span><?php echo __('Add to Cart') ?></span></button>
                    </td>
                </tr>
            </tfoot>
            <?php endif; ?>
            <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
            </tbody>
        </table>
    </form>
    <?php if (!$_itemsCount): ?>
        <p><?php echo __('This gift registry has no items.') ?></p>
    <?php endif; ?>
</div>