<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_wishlistItem = $this->getWishlistItem(); ?>
<?php $_wishlistSubmitUrl = $this->helper('Magento\Wishlist\Helper\Data')->getUpdateUrl($_wishlistItem); ?>
<div class="product addto links" data-role="add-to-links">
<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <a href="<?php echo $_wishlistSubmitUrl ?>" class="action towishlist updated"><span><?php echo __('Update Wish List') ?></span></a>
<?php endif; ?>
<?php $_product = $this->getProduct(); ?>
<?php $_compareUrl = $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddUrl($_product); ?>
<?php if ($_compareUrl) : ?>
    <a href="<?php echo $_compareUrl ?>" class="action tocompare"><span><?php echo __('Add to Compare') ?></span></a>
<?php endif; ?>
</div>
