<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="actions">
    <?php  $_order = $this->getOrder() ?>
    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order)) : ?>
        <a class="action reorder" href="<?php echo $this->getReorderUrl($_order) ?>">
            <span><?php echo __('Reorder') ?></span>
        </a>
    <?php endif ?>
    <a class="action print"
       href="<?php echo $this->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?php echo __('Print Order') ?></span>
    </a>
    <?php if($this->helper('Magento\Rss\Helper\Order')->isStatusNotificationAllow()): ?>
        <a href="<?php echo $this->helper('Magento\Rss\Helper\Order')->getStatusHistoryRssUrl($_order) ?>"
           class="action rss">
            <span><?php echo __('Subscribe to Order Status') ?></span>
        </a>
    <?php endif; ?>
    <?php echo $this->getChildHtml(); ?>
</div>