<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="no-display template" id="option_panel_type_text">
    <table class="dynamic-grid" cellpadding="0" cellspacing="0">
        <tr>
            <td>Price:<input type="text" name="product[options][{{option_id}}][price]" value="{{price}}"></td>
            <td>Price Type:<?php echo $this->getPriceTypeSelectHtml() ?></td>
            <td>SKU:<input type="text" name="product[options][{{option_id}}][sku]" value="{{sku}}"></td>
            <td>Max Characters:<input type="text" name="product[options][{{option_id}}][max_characters]" value="{{max_characters}}"></td>
        </tr>
    </table>
</div>
<script type="text/javascript">

var OptionTemplateText = '<table class="dynamic-grid" cellpadding="0" cellspacing="0">'+
        '<tr>'+
            '<td>Price:<input type="text" class="required-entry validate-zero-or-greater product-option-price" id="product_option_{{option_id}}_price" name="product[options][{{option_id}}][price]" value="{{price}}"></td>'+
            '<td>Price Type:<?php echo $this->getPriceTypeSelectHtml() ?>{{checkboxScopePrice}}</td>'+
            '<td>SKU:<input type="text" class="required-entry" name="product[options][{{option_id}}][sku]" value="{{sku}}"></td>'+
            '<td>Max Characters:<input type="text" class="required-entry validate-zero-or-greater" name="product[options][{{option_id}}][max_characters]" value="{{max_characters}}"></td>'+
        '</tr>'+
    '</table>';

if ($('option_panel_type_text')) {
    $('option_panel_type_text').remove();
}

</script>