<?php
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
?>
<?php /** @var $this \Magento\GiftWrapping\Block\Adminhtml\Order\Create\Info\Content */ ?>

<fieldset>
    <?php if ($this->isGiftWrappingForEntireOrder()): ?>
    <legend class="legend"><span><?php echo __('Gift Wrapping for the Entire Order'); ?></span></legend>
    <?php else: ?>
    <legend class="legend"><span><?php echo __('Other Gift Options') ?></span></legend>
    <?php endif; ?>
    <br />

    <?php require 'content.phtml'; ?>
</fieldset>
