                    <div>
                    <ul>
                        <li><a target="catalogMain" href="/adminhtml/producttags/producttags/">Pending Tags</a></li>
                        <li><a target="catalogMain" href="/adminhtml/customerpage/customerpage/">Customer Page</a></li>
                        <li><a target="catalogMain" href="/adminhtml/productpage/productpage/">Products Page</a></li>
                    </ul>
                    </div>
