<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="<?=$this->getHtmlId()?>">
<div class="entry-edit">
            <h4 class="icon-head head-edit-form fieldset-legend"><div class="left"><?=$this->__('Grid Massactions')?></div><div class="right"><?=$this->getApplyButtonHtml()?></div></h4>
            <div class="clear"></div>
            <fieldset>
                <span class="field-row">
                    <label><?=$this->__('Select action')?></label>
                    <select id="<?=$this->getHtmlId()?>-select">
                        <option value=""></option>
                        <?foreach($this->getItems() as $_item):?>
                            <option value="<?=$_item->getId()?>"><?=$_item->getLabel()?></option>
                        <?endforeach;?>
                    </select>
                </span>
                <form id="<?=$this->getHtmlId()?>-form" method="POST"><span id="<?=$this->getHtmlId()?>-form-hiddens"></span><span id="<?=$this->getHtmlId()?>-form-additional"></span></form>
            </fieldset>

        </div>

        <div class="no-display">
        <?foreach($this->getItems() as $_item):?>
            <div id="<?=$this->getHtmlId()?>-item-<?=$_item->getId()?>-block">
                <?=$_item->getAdditionalActionBlockHtml()?>
            </div>
        <?endforeach;?>
        </div>

<script type="text/javascript">
var <?=$this->getJsObjectName()?> = new varienGridMassaction('<?=$this->getHtmlId()?>', <?=$this->getGridJsObjectName()?>, <?=$this->getSelectedJson()?>, '<?=$this->getFormFieldNameInternal()?>', '<?=$this->getFormFieldName()?>');
<?=$this->getJsObjectName()?>.setItems(<?=$this->getItemsJson()?>);
</script>
</div>