<div class="content-header">
    <table cellspacing="0" class="grid-header">
    	<tr>
    		<td style="width:50%;"><h3 class="icon-head head-tax"><?=$header?></h3></td>
        	<td class="form-buttons">
            	<button class="scalable add" onclick="window.location.href='<?=$createUrl?>'">
            		<table cellspacing="0">
            			<tr>
            				<td class="tl"></td>
            				<td class="tr"></td>
            			</tr>
            			<tr>
            				<td class="ml"><span><?=__('Add New Tax Rule')?></span></td>
            				<td class="mr"></td>
            			</tr>
            			<tr>
            				<td class="bl"></td>
            				<td class="br"></td>
            			</tr>
            		</table>
            	</button>
        	</td>
    	</tr>
    </table>
</div>