<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_Rma_Block_Adminhtml_Rma_Edit_Tab_General
 */
?>
<div class="box-left">
    <?php echo $this->getChildHtml('request_details') ?>
</div>
<div class="box-right">
    <?php echo $this->getChildHtml('shipping_method') ?>
</div>
<div class="clear"></div>
<div class="box-left">
    <?php echo $this->getChildHtml('shipping_address') ?>
</div>
<div class="box-right">
    <?php echo $this->getChildHtml('return_address') ?>
</div>
<div class="clear"></div>
<div>
    <?php echo $this->getChildHtml('comments_history') ?>
</div>
