<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<script id="template-registrant" type="text/x-jQuery-tmpl">
    <input name="registrant[${_index_}][person_id]" value="" id="registrant:person_id${_index_}" type="hidden" />
    <div class="actions-toolbar">
        <div class="secondary">
            <button type="button" class="action remove" id="btn-remove${_index_}">
                <span>
                    <?php echo __('Remove') ?>
                </span>
            </button>
        </div>
    </div>
    <fieldset class="fieldset">
        <div class="field firstname required">
            <label for="registrant:firstname${_index_}" class="label"><span><?php echo __('First Name:') ?></span></label>
            <div class="control">
                <input name="registrant[${_index_}][firstname]" value="" type="text" class="input-text" data-validate="{required:true}" id="registrant:firstname${_index_}" />
            </div>
        </div>
        <div class="field lastname required">
            <label for="registrant:lastname${_index_}" class="label"><span><?php echo __('Last Name:') ?></span></label>
            <div class="control">
                <input name="registrant[${_index_}][lastname]" value="" type="text" class="input-text" data-validate="{required:true}" id="registrant:lastname${_index_}" />
            </div>
        </div>
        <div class="field email required">
            <label for="registrant:email${_index_}" class="label"><span><?php echo __('Email Address:') ?></span></label>
            <div class="control">
                <input name="registrant[${_index_}][email]" value="" title="<?php echo __('Email Address') ?>" id="registrant:email${_index_}" type="email" class="input-text" data-validate="{required:true,'validate-email':true}"  />
            </div>
        </div>

        <?php foreach ($this->getGroupedRegistrantAttributes() as $field => $data) : ?>
        <?php $isRequired = $this->isAttributeRequired($data); ?>
        <?php $isStatic = $this->isAttributeStatic($field); ?>
            <div class="field<?php echo ($isRequired ? ' required' : '') ?>">
                <label for="registrant:<?php if (!$isStatic):?>custom:<?php endif;?><?php echo $field ?>${_index_}" class="label"><span><?php echo __("%1", $data['label']); ?></span></label>
                <div class="control">
                    <?php echo $this->renderField($data, $field, '{{' . $field . '_value}}') ?>
                </div>
            </div>
        <?php endforeach; ?>
    </fieldset>
</script>

<fieldset class="fieldset recipients">
    <legend class="legend"><span><?php echo __('Recipients Information') ?></span></legend>
    <br />
    <div id="registrant-container"></div>
    <?php if ($this->getMaxRegistrant()): ?>
        <div id="max-registrant-message" style="display:none;" class="message notice limit">
            <span><?php echo __('Maximum %1 recipients.', $this->getMaxRegistrant()) ?></span>
        </div>
    <?php endif; ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <?php if ($this->getMaxRegistrant() > 1): ?>
                <button type="button" id="add-registrant-button" class="action add">
                    <span><?php echo __('Add Recipient') ?></span>
                </button>
            <?php endif; ?>
        </div>
    </div>
</fieldset>

<script type="text/javascript">
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#form-validate').mage('giftRegistry', {
        'rowParentElem': '<div></div>',
        'remEventSelector': 'button',
        'btnRemoveSelector': '.action.remove',
        'additionalRowClass': 'additional',
        'maxRows': '<?php echo $this->getMaxRegistrant() ?>',
        'formDataPost': {"formData": <?php echo json_encode($this->getRegistrantPresets($this->getEntity()->getId())); ?>}
    });

});
</script>
