<form method="post" action="<?=$baseUrl?>test/upload/simplesave" enctype="multipart/form-data">
    <p><input type="file" size="32" name="filename[]" value="" /></p>
    <p><input type="file" size="32" name="filename[2]" value="" /></p>
    <p><input type="file" size="32" name="filename[8]" value="" /></p>
    <input type="submit" />
</form>

<form method="post" action="<?=$baseUrl?>admin/media/upload/" enctype="multipart/form-data">
    <p><input type="file" size="32" name="upload_file" value="" /></p>
    <input type="submit" />
</form>
