<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var \Magento\Ui\Listing\View $this
 */

?>

<?php if (true): ?>
    <script>
        var allowLocalCache = true;
    </script>
    <script data-mage-init='{"Magento_Ui/js/listing/utils/provider": ""}' type="application/json">
        <?php
            echo $this->getRenderContext()
                ->getConfigurationBuilder()
                    ->toJson($this->getRenderContext()->getStorage(), $this->getName());
        ?>
    </script>
    <script data-mage-init='{"Magento_Ui/js/listing/grid": ""}' type="application/json">
        <?php echo $this->getConfigurationBuilder()->toJson($this->getConfiguration()); ?>
    </script>
    <?php echo $this->getChildHtml('listing_head'); ?>
    <div class="grid">
        <?php echo $this->getChildHtml('listing_before'); ?>
        <div data-bind="scope: '<?php echo $this->getParentName(); ?>:<?php echo $this->getName(); ?>'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
        <?php echo $this->getChildHtml('listing_after'); ?>
    </div>
    <div data-role="spinner" class="grid-loading-mask">
        <div class="grid-loader"></div>
    </div>
<?php else: ?>
    <div class="grid" data-mage-init='{"Magento_Ui/js/listing/utils/provider": ""}'>
        <?php echo $this->getChildHtml('listing_before'); ?>
        <table>
            <thead>
            <tr>
                <?php foreach ($this->getMeta()['fields'] as $name => $field): $field['name'] = $name; ?>
                    <th><?php echo $this->renderElementLabel($field['data_type'], $field); ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getCollectionItems() as $item): ?>
            <tr>
                <?php foreach ($this->getMeta()['fields'] as $name => $field): $field['name'] = $name; $field['data_object'] = $item; ?>
                <td><?php echo $this->renderElement($field['data_type'], $field); ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->getChildHtml('listing_after'); ?>
    </div>
<?php endif; ?>