<?php
/**
 * {license_notice}
 *
 * @category    Mage
 * @package     Mage_Captcha
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* @var $this Mage_Core_Block_Captcha_Zend */ ?>

<?php /* @var $captcha Mage_Core_Model_Captcha_Zend */ ?>
<?php $captcha = $this->getCaptchaModel() ?>
<li id="captcha-input-box-<?php echo $this->getFormId()?>">
    <label for="captcha" class="required"><em>*</em><?php echo $this->__('Please type the letters below')?></label>
    <div class="input-box captcha">
        <input name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" type="text" class="input-text required-entry" id="captcha" title="captcha" />
    </div>
</li>
<li>
    <div class="captcha-image" style="width:<?php echo $this->getImgWidth() - 2 ?>px" id="captcha-image-box-<?php echo $this->getFormId()?>">
        <img id="<?php echo $this->getFormId() ?>" width="100%" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>"/>
        <script type="text/javascript">
        //<![CDATA[
        var captcha = window.captcha == undefined ? new array(): window.captcha;
        captcha_<?php echo $this->getFormId()?> = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');
        //]]>
        </script>
        <img class="captcha-reload"
            src="<?php echo $this->getSkinUrl('Mage_Captcha::reload.png') ?>"
            alt="<?php echo $this->__('Reload captcha') ?>"
            onclick="captcha_<?php echo $this->getFormId()?>.refresh()">
        <?php if ($captcha->isCaseSensitive()) :?>
        <div class="captcha-note">
            <p><?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?></p>
        </div>
        <?php endif; ?>
    </div>
</li>

