<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<script id="template-registrant" type="text/x-jQuery-tmpl">
    <input name="registrant[${_index_}][person_id]" value="" id="registrant:person_id${_index_}" type="hidden" />

    <span class="action remove" id="btn-remove${_index_}"><?php echo __('Remove') ?></span>

    <div class="field firstname required">
        <label for="registrant:firstname${_index_}" class="label"><span><?php echo __('First Name:') ?></span></label>
        <div class="control">
            <input name="registrant[${_index_}][firstname]" value="" type="text" class="input-text" data-validate="{required:true}" id="registrant:firstname${_index_}" />
        </div>
    </div>
    <div class="field lastname required">
        <label for="registrant:lastname${_index_}" class="label"><span><?php echo __('Last Name:') ?></span></label>
        <div class="control">
            <input name="registrant[${_index_}][lastname]" value="" type="text" class="input-text" data-validate="{required:true}" id="registrant:lastname${_index_}" />
        </div>
    </div>
    <div class="field email required">
        <label for="registrant:email${_index_}" class="label"><span><?php echo __('Email Address:') ?></span></label>
        <div class="control">
            <input name="registrant[${_index_}][email]" value="" title="<?php echo __('Email Address') ?>" id="registrant:email${_index_}" type="text" class="input-text" data-validate="{required:true,'validate-email':true}"  />
        </div>
    </div>

    <?php foreach ($this->getGroupedRegistrantAttributes() as $field => $data) : ?>
    <?php $isRequired = $this->isAttributeRequired($data); ?>
    <?php $isStatic = $this->isAttributeStatic($field); ?>
        <div class="field<?php echo ($isRequired ? ' required' : '') ?>">
            <label for="registrant:<?php if (!$isStatic):?>custom:<?php endif;?><?php echo $field ?>${_index_}" class="label"><span><?php echo __("%1", $data['label']); ?></span></label>
            <div class="control">
                <?php echo $this->renderField($data, $field, '{{' . $field . '_value}}') ?>
            </div>
        </div>
    <?php endforeach; ?>
</script>


<fieldset class="fieldset recipients">
    <legend class="legend"><span><?php echo __('Recipients Information') ?></span></legend>

    <div id="registrant-container"></div>

    <div class="actions">
        <div class="secondary">
            <span id="max-registrant-message" style="display:none;">
                <?php if ($this->getMaxRegistrant()): ?>
                    <?php echo __('Maximum %1 recipients.', $this->getMaxRegistrant()) ?>
                <?php endif; ?>
            </span>
        </div>
        <div class="primary">
            <?php if ($this->getMaxRegistrant() > 1): ?>
                <button type="button" id="add-registrant-button" class="action secondary add">
                    <span><?php echo __('Add Recipient') ?></span>
                </button>
            <?php endif; ?>
        </div>
    </div>
</fieldset>

<script type="text/javascript">
    head.js("<?php echo $this->getViewFileUrl('jquery/jquery.tmpl.min.js')?>",
        "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
        "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
        "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
        "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
        "<?php echo $this->getViewFileUrl('Magento_Page::js/row-builder.js')?>",
        "<?php echo $this->getViewFileUrl('Magento_GiftRegistry::gift-registry.js')?>", function() {
            jQuery('#form-validate').giftRegistry({
                rowParentElem: '<fieldset></fieldset>',
                rowContainerClass: 'fieldset',
                remEventSelector: 'span',
                btnRemoveSelector: '.action.remove',
                maxRows: '<?php echo $this->getMaxRegistrant() ?>',
                formDataPost: {"formData": <?php echo json_encode($this->getRegistrantPresets($this->getEntity()->getId())); ?>}
            });
        });
</script>
