<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_order = $this->getOrder() ?>
<div class="grid">
  <div class="hor-scroll">
    <table cellspacing="0" class="data">
        <thead>
            <tr class="headings">
                <th class="col-product"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Product') ?></span></th>
                <th class="col-status"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Item Status') ?></span></th>
                <th class="col-price-original"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Original Price') ?></span></th>
                <th class="col-price"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Price') ?></span></th>
                <th class="col-ordered-qty"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Qty') ?></span></th>
                <th class="col-subtotal"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Subtotal') ?></span></th>
                <th class="col-tax-amount"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Tax Amount') ?></span></th>
                <th class="col-tax-percent"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Tax Percent') ?></span></th>
                <th class="col-discont"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Discount Amount') ?></span></th>
                <th class="col-total last"><span><?php echo $this->helper('Magento_Sales_Helper_Data')->__('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>