<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->getGcontentCaptchaToken() && $this->getGcontentCaptchaUrl()): ?>
<div class="messages">
    <div class="message error">
        <div><img src="<?php echo $this->getGcontentCaptchaUrl() ?>"> <input type="text" id="user_confirm"> <?php echo $this->getConfirmButtonHtml() ?></div>
    </div>
</div>
<?php endif; ?>
