<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this Magento_Catalog_Block_Product_View*/
?>
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = Mage::helper('Magento_Wishlist_Helper_Data')->getAddUrl($_product); ?>

<ul class="add-to-links" data-role="add-to-links">
<?php if (Mage::helper('Magento_Wishlist_Helper_Data')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></li>
<?php endif; ?>
<?php $_compareUrl = Mage::helper('Magento_Catalog_Helper_Product_Compare')->getAddUrl($_product); ?>
<?php if($_compareUrl) : ?>
    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo __('Add to Compare') ?></a></li>
<?php endif; ?>
</ul>
<script type="text/javascript">
head.js("<?php echo $this->getViewFileUrl('Magento_Wishlist::js/add-to-wishlist.js') ?>", function () {
    jQuery('[data-role="add-to-links"]').addToWishlist(
        <?php echo Mage::helper('Magento_Core_Helper_Data')->jsonEncode(array('productType' => $_product->getTypeId()))?>
    );
});
</script>
