<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Product description template
 *
 * @see Magento_Catalog_Block_Product_View_Description
 */
?>
<?php $_description = $this->getProduct()->getDescription(); ?>
<?php if ($_description): ?>
    <div class="std">
        <?php echo Mage::helper('Magento_Catalog_Helper_Output')->productAttribute($this->getProduct(), $_description, 'description') ?>
    </div>
<?php endif; ?>
