<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/**
 * @see Magento_Catalog_Block_Product_View
 */
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
$_finalPriceInclTax = Mage::helper('Magento_Tax_Helper_Data')->getPrice($_product, $_product->getFinalPrice(), true);

/** @var $_catalogHelper Magento_Catalog_Helper_Data */
$_catalogHelper = Mage::helper('Magento_Catalog_Helper_Data');

$_weeeTaxAmount = Mage::helper('Magento_Weee_Helper_Data')->getAmountForDisplay($_product);
if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, array(1,2,4))) {
    $_weeeTaxAttributes = Mage::helper('Magento_Weee_Helper_Data')->getProductWeeeAttributesForDisplay($_product);
}

?>
<?php if (count($_tierPrices) > 0): ?>
    <ul class="<?php echo ($this->getInGrouped() ? 'tier-prices-grouped product-pricing-grouped' : 'tier-prices product-pricing'); ?>">
    <?php if ($this->getInGrouped()): ?>
        <?php $_tierPrices = $this->getTierPrices($_product); ?>
    <?php endif; ?>
    <?php Mage::helper('Magento_Weee_Helper_Data')->processTierPrices($_product, $_tierPrices); ?>
    <?php foreach ($_tierPrices as $_index => $_price): ?>
        <li>
        <?php if ($_catalogHelper->canApplyMsrp($_product)): ?>
            <?php if ($this->getInGrouped()): ?>
                <?php echo __('Buy %1 for', $_price['price_qty']) ?>:
            <?php else: ?>
                <?php echo __('Buy %1', $_price['price_qty']) ?>
            <?php endif; ?>
        <?php else: ?>

        <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayBothPrices()): ?>
            <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 0)): ?>
                <?php echo __('Buy %1 for %2 (%3 incl. tax) each', $_price['price_qty'], $_price['formated_price_incl_weee_only'], $_price['formated_price_incl_weee']) ?>
            <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 1)): ?>
                    <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                    <?php if ($_weeeTaxAttributes): ?>
                    (<small>
                    <?php echo __('%1 incl tax', $_price['formated_price_incl_weee']); ?>
                    <?php $separator = ' + '; foreach ($_weeeTaxAttributes as $_attribute): ?>
                        <?php echo $separator; ?>
                        <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()); ?>
                    <?php endforeach; ?>
                    </small>)
                    <?php endif; ?>
                    <?php echo __('each') ?>
            <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 4)): ?>
                    <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                    <?php if ($_weeeTaxAttributes): ?>
                    (<small>
                    <?php echo __('%1 incl tax', $_price['formated_price_incl_weee']); ?>
                    <?php $separator = ' + '; foreach ($_weeeTaxAttributes as $_attribute): ?>
                        <?php echo $separator; ?>
                        <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()+$_attribute->getTaxAmount()); ?>
                    <?php endforeach; ?>
                    </small>)
                    <?php endif; ?>
                    <?php echo __('each') ?>
            <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 2)): ?>
                    <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price']); ?>
                    <?php if ($_weeeTaxAttributes): ?>
                    (<small>
                    <?php foreach ($_weeeTaxAttributes as $_attribute): ?>
                        <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()); ?>
                    <?php endforeach; ?>
                    <?php echo __('Total incl. Tax: %1', $_price['formated_price_incl_weee']); ?>
                    </small>)
                    <?php endif; ?>
                    <?php echo __('each') ?>
            <?php else: ?>
                    <?php echo __('Buy %1 for %2 (%3 incl. tax) each', $_price['price_qty'], $_price['formated_price'], $_price['formated_price_incl_tax']) ?>
            <?php endif; ?>
        <?php else: ?>
            <?php if (Mage::helper('Magento_Tax_Helper_Data')->displayPriceIncludingTax()): ?>
                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 0)): ?>
                        <?php echo __('Buy %1 for %2 each', $_price['price_qty'], $_price['formated_price_incl_weee']) ?>
                <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 1)): ?>
                        <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price_incl_weee']); ?>
                        <?php if ($_weeeTaxAttributes): ?>
                        (<small>
                        <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                            <?php echo $separator; ?>
                            <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()); ?>
                        <?php $separator = ' + '; endforeach; ?>
                        </small>)
                        <?php endif; ?>
                        <?php echo __('each') ?>
                <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 4)): ?>
                        <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price_incl_weee']); ?>
                        <?php if ($_weeeTaxAttributes): ?>
                        (<small>
                        <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                            <?php echo $separator; ?>
                            <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()+$_attribute->getTaxAmount()); ?>
                        <?php $separator = ' + '; endforeach; ?>
                        </small>)
                        <?php endif; ?>
                        <?php echo __('each') ?>
                <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 2)): ?>
                        <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price_incl_tax']); ?>
                        <?php if ($_weeeTaxAttributes): ?>
                        (<small>
                        <?php foreach ($_weeeTaxAttributes as $_attribute): ?>
                            <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()); ?>
                        <?php endforeach; ?>
                        <?php echo __('Total incl. Tax: %1', $_price['formated_price_incl_weee']); ?>
                        </small>)
                        <?php endif; ?>
                        <?php echo __('each') ?>
                <?php else: ?>
                        <?php echo __('Buy %1 for %2 each', $_price['price_qty'], $_price['formated_price_incl_tax']) ?>
                <?php endif; ?>
            <?php else: ?>
                <?php if (Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 0)): ?>
                        <?php echo __('Buy %1 for %2 each', $_price['price_qty'], $_price['formated_price_incl_weee_only']) ?>
                <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 1)): ?>
                        <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                        <?php if ($_weeeTaxAttributes): ?>
                        (<small>
                        <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                            <?php echo $separator; ?>
                            <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()); ?>
                        <?php $separator = ' + '; endforeach; ?>
                        </small>)
                        <?php endif; ?>
                        <?php echo __('each') ?>
                <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 4)): ?>
                        <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price_incl_weee_only']); ?>
                        <?php if ($_weeeTaxAttributes): ?>
                        (<small>
                        <?php $separator = ''; foreach ($_weeeTaxAttributes as $_attribute): ?>
                            <?php echo $separator; ?>
                            <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()+$_attribute->getTaxAmount()); ?>
                        <?php $separator = ' + '; endforeach; ?>
                        </small>)
                        <?php endif; ?>
                        <?php echo __('each') ?>
                <?php elseif(Mage::helper('Magento_Weee_Helper_Data')->typeOfDisplay($_product, 2)): ?>
                        <?php echo __('Buy %1 for %2', $_price['price_qty'], $_price['formated_price']); ?>
                        <?php if ($_weeeTaxAttributes): ?>
                        (<small>
                        <?php foreach ($_weeeTaxAttributes as $_attribute): ?>
                            <?php echo $_attribute->getName(); ?>: <?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_attribute->getAmount()); ?>
                        <?php endforeach; ?>
                        <?php echo __('Total incl. Tax: %1', $_price['formated_price_incl_weee_only']); ?>
                        </small>)
                        <?php endif; ?>
                        <?php echo __('each') ?>
                <?php else: ?>
                        <?php echo __('Buy %1 for %2 each', $_price['price_qty'], $_price['formated_price']) ?>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php endif; // Can apply MSRP ?>

        <?php if (!$this->getInGrouped()): ?>
            <?php if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
            || ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])): ?>
                <?php echo __('and') ?>&nbsp;<strong class="benefit"><?php echo __('save')?>&nbsp;<span class="percent tier-<?php echo $_index;?>"><?php echo $_price['savePercent']?></span>%
            <?php endif ?></strong>
        <?php endif; ?>

        <?php if ($_catalogHelper->isShowPriceOnGesture($_product)):?>
            <?php $popupId = 'msrp-popup-' . $_product->getId() . Mage::helper('Magento_Core_Helper_Data')->getRandomString(20); ?>
            <?php
            $addToCartUrl = $this->getProduct()->isSalable()
                ? $this->getAddToCartUrl($_product, array('qty' => $_price['price_qty']))
                : '';
            ?>
            <a href="#" id="<?php echo($popupId);?>" data-tier-price='{addToCartUrl:"<?php echo $addToCartUrl; ?>", name:"<?php echo $_product->getName() ?>", price:<?php echo json_encode($_price['real_price_html']) ?>, msrp:"<?php echo Mage::helper('Magento_Core_Helper_Data')->currency($_product->getMsrp(),true,false) ?>"<?php if (!$this->getInGrouped()): ?>, qty:"<?php echo $_price['price_qty']?>"<?php endif ?>}'><?php echo __('Click for price'); ?></a>
        <?php else: ?>
            <span class="msrp-price-hide-message">
                <?php echo $_catalogHelper->getMsrpPriceMessage($_product) ?>
            </span>
        <?php endif; ?>
        </li>
    <?php endforeach ?>
    </ul>
    <?php if ($_catalogHelper->isShowPriceOnGesture($_product)):?>
        <script type="text/javascript">
            (function($) {
                head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/tier-price.js') ?>", function () {
                    $('#product_addtocart_form').tierPrice({
                        inputQty: '#qty'
                    });
                });
            })(jQuery);
        </script>
    <?php endif;?>
<?php endif;?>
