<?php if( $this->getActionsCollection()->getSize() > 0 ):?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo $this->helper('enterprise_customerbalance')->__('Credit History')?></h4>
    </div>
    <div class="fieldset">
        <div class="clear"></div>
        <ul class="note-list">
        <?php foreach ($this->getActionsCollection() as $_action): ?>
            <li>
                <strong><?php echo $this->helper('core')->formatDate($_action->getDate(), 'medium') ?></strong>
                <?php echo $this->helper('core')->formatTime($_action->getDate(), 'medium') ?>
                <span class="separator">|</span><small>
                <strong class="subdue">
                    <?php echo $_action->getActionName()?></small></strong> <?php echo $this->helper('enterprise_customerbalance')->__('balance for Website: %s', $_action->getName())?>
                <span class="separator">|</span>
                <strong><?php echo $this->helper('enterprise_customerbalance')->__('Delta: ')?><?php echo $_action->getFormattedDelta()?></strong>

            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif;?>