<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Magento_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_Font */ ?>
<?php
/** @var $element Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_Font */
$element = $this->getElement();
?>

<fieldset class="<?php echo join(' ', $this->getClasses()) ?>" id="<?php echo $element->getHtmlId() ?>">
    <legend class="legend">
        <span><?php echo $element->getLegend(); ?></span>
    </legend>
    <?php echo $element->getChildrenHtml(); ?>
</fieldset>

