<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** former Mage\Backend\view\adminhtml\widget\form\renderer\fieldset\element.phtml */ ?>

<?php /** @var $this Magento_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_ColorPicker */ ?>
<?php
/** @var $element Magento_DesignEditor_Block_Adminhtml_Editor_Form_Element_ColorPicker */
$element = $this->getElement();
$note = $element->getNote() ? '<div class="note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox' || $element->getExtType() == 'radio';
$addOn = $element->getBeforeElementHtml() || $element->getAfterElementHtml();
?>

<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?php echo $this->getHtml() ?>
    <?php else: ?>
    <div <?php echo $this->getFieldAttributes() ?>>
        <?php if ($elementBeforeLabel): ?>
            <?php echo $this->getHtml() ?>
            <?php echo $element->getLabelHtml() ?>
            <?php echo $note ?>
        <?php else: ?>
            <?php echo $element->getLabelHtml() ?>
            <div class="control">
                <?php echo ($addOn) ? '<div class="addon">' . $this->getHtml() . '</div>' : $this->getHtml(); ?>
                <?php echo $note ?>
            </div>
        <?php endif; ?>
        <?php if ($element->getScopeLabel()): ?>
            <div class="field-service" value-scope="<?php echo $element->getScopeLabel()?>">
            </div>
        <?php endif;?>
    </div>
    <?php endif; ?>
<?php endif; ?>
