<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Magento_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /* former part of Mage\Backend\view\adminhtml\widget\form\renderer\element.phtml */ ?>

<?php /** @var $this Magento_DesignEditor_Block_Adminhtml_Editor_Form_Renderer_Checkbox */ ?>
<?php
/** @var $element \Magento\Data\Form\Element\Checkbox */
$element = $this->getElement();
?>


<?php if ($element->getNoSpan() !== true): ?>
<span class="field-row">
<?php endif; ?>
    <?php echo $element->getLabelHtml() ?>
    <?php echo $this->getHtml() ?>
<?php if ($element->getNoSpan() !== true): ?>
</span>
<?php endif?>
