            <!-- [start] bottom-links -->
            <div class="bottom-links">
                <ul>
                    <?=$this->getChildHtml('bottomLinks')?>
                </ul>
            </div>
            <!-- [end] bottom-links -->

            <!-- [start] footer-center -->
            <div class="footer-center">
            </div>
            <!-- [end] footer-center -->

            <!-- [start] copyright -->
            <div class="copyright">
                <?=$this->getCopyright()?>
            </div>
            <!-- [end] copyright -->