<?if($_section=='subject'):?>
Order #<?=$order->getId()?>
<?else:?>
    <?if($_type=='html'):?>
<strong>Dear <?=$name?></strong>

Thanks for your order!
<div class="content">
    <h1 class="page-heading">Order #<?=$order->getId()?> (<?=$order->getStatus()?>)</h1>
    <table cellspacing="0" width="100%">
        <thead>
            <tr>
                <th style="width:50%;"><h3>Billing Information</h3></th>
                <th style="width:50%;"><h3>Payment Method</h3></th></tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <address>
                        <?=$order->getBillingAddress()->toString('<b>{{firstname}} {{lastname}}</b><br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: {{telephone}}')?>
                    </address>
                </td>
                <td class="align-center">
                <?//=$payment?>
                </td>
            </tr>
        </tbody>
    </table>
    <p></p>
    <table cellspacing="0" width="100%">
        <thead>
            <tr>
                <th style="width:50%;"><h3>Shipping Information</h3></th>
                <th style="width:50%;"><h3>Shipping Method</h3></th></tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <address>
                        <?=$order->getShippingAddress()->toString('<b>{{firstname}} {{lastname}}</b><br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: {{telephone}}')?>
                    </address>
                </td>
                <td class="align-center">
                    <?=$order->getShippingDescription()?>
                </td>
            </tr>
        </tbody>
    </table>
    <p></p>
    <table cellspacing="6" width="100%" class="data-table">
        <thead>
            <tr>
                <th style="width:50%;">Items Order</th>
                <th class="align-center" style="width:10%;">Qty</th>
                <th class="align-center" style="width:20%;">Price</th>
                <th class="align-right" style="width:20%;">Ext. Price</th>
            </tr>
        </thead>
        <tbody>
            <?foreach($order->getAllItems() as $_item):?>     
            <tr>
                <td><?=$_item->getName()?></td>
                <td class="align-center"><?=sprintf('%d',$_item->getQty())?></td>
                <td class="align-center"><?=sprintf('$%.2f',$_item->getPrice())?></td>
                <td class="align-right"><?=sprintf('$%.2f', $_item->getRowTotal())?></td>
            </tr>   
            <?endforeach?> 
        </tbody>
    </table>
</div>
    <?else:?>
Dear <?=$name?>,

Thanks for your order!

This is what you ordered: 

{$order.products}

{$order.order_totals}

{if $order.shipping_address}

This is where it's being shipped:

{$order.shipping_address}
{/if}

This is the billing address:

{$order.billing_address}

{if $order.payment_method}
Payment method: {$order.payment_method}
{/if}

You placed the order on {$order.date_long}. Your order number is: {$order.visible_id}

You can review your full order at:

{$order.order_info_url}
{if $customer.no_reg}
You can view your order history by log in:
email: {$customer.email_address}
password: {$customer.password}
{/if}
Thank you for shopping at McGruff Specialty Products Office.  Please visit us again soon!

{$order.payment_footer}
    <?endif?>
<?endif?>