<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this \Magento\Wishlist\Block\Customer\Wishlist\Button */
?>
<?php if ($this->getWishlist()->getItemsCount() && $this->getWishlist()->getShared() < $this->getConfig()->getSharingEmailLimit()): ?>
    <button type="submit" name="save_and_share" title="<?php echo __('Share Wish List') ?>" class="action share">
        <span><?php echo __('Share Wish List') ?></span>
    </button>
<?php endif;?>
