<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 ?>

<?php /* @var $this \Magento\Adminhtml\Block\Catalog\Product\Composite\Fieldset\Configurable */ ?>
<?php $_product = $this->getProduct(); ?>
<?php $_attributes = $this->helper('Magento\Core\Helper\Data')->decorateArray($this->getAllowAttributes()); ?>
<?php $_skipSaleableCheck = $this->helper('Magento\Catalog\Helper\Product')->getSkipSaleableCheck(); ?>
<?php if (($_product->isSaleable() || $_skipSaleableCheck) && count($_attributes)):?>
<fieldset id="catalog_product_composite_configure_fields_configurable" class="fieldset">
    <legend class="legend"><span><?php echo __('Associated Products') ?></span></legend>
    <div class="product-options">
        <div class="field required">
        <?php foreach($_attributes as $_attribute): ?>
            <label class="label"><?php echo $_attribute->getLabel() ?></label>
            <div class="control<?php if ($_attribute->getDecoratedIsLast()):?> last<?php endif; ?>">
                <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    <option><?php echo __('Choose an Option...') ?></option>
                </select>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
</fieldset>
<script type="text/javascript">
    var config = <?php echo $this->getJsonConfig() ?>;
    if (window.productConfigure) {
        config.containerId = window.productConfigure.blockFormFields.id;
        if (window.productConfigure.restorePhase) {
            config.inputsInitialized = true;
        }
    }
    ProductConfigure.spConfig = new Product.Config(config);
</script>
<?php endif;?>
