<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /* @var $this \Magento\Adminhtml\Block\Catalog\Product\Composite\Fieldset\Options */ ?>
<?php $options = $this->helper('\Magento\Core\Helper\Data')->decorateArray($this->getOptions()); ?>
<?php if (count($options)): ?>

<?php echo $this->getChildHtml('options_js') ?>

<fieldset id="product_composite_configure_fields_options" class="fieldset <?php echo $this->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
    <legend class="legend"><span><?php echo __('Custom Options') ?></span></legend>
    <?php foreach($options as $option): ?>
        <?php echo $this->getOptionHtml($option); ?>
    <?php endforeach;?>
</fieldset>

<?php endif; ?>
