<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /* @var $this Magento_Adminhtml_Block_Catalog_Product_Composite_Fieldset_Qty */ ?>

<fieldset id="product_composite_configure_fields_qty" class="fieldset <?php echo $this->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
    <div class="field">
        <label class="label"><?php echo __('Quantity') ?></label>
        <div class="control">
        	<input id="product_composite_configure_input_qty" class="input-text" type="text" name="qty" value="<?php echo $this->getQtyValue() * 1 ?>">
        </div>
    </div>
</fieldset>
