<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /* former part of \Magento\Framework\Data\Form\Element\AbstractElement::getElementHtml() */ ?>

<?php /** @var $this \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\ColorPicker|\Magento\DesignEditor\Block\Adminhtml\Editor\Form\Renderer\Checkbox */ ?>
<?php /** @var $element \Magento\DesignEditor\Block\Adminhtml\Editor\Form\Element\ColorPicker */ ?>
<?php $element = $this->getElement(); ?>

<?php if ($element->getBeforeElementHtml()): ?>
    <label class="addbefore" for="<?php echo $element->getHtmlId() ?>"><?php echo $element->getBeforeElementHtml() ?></label>
<?php endif; ?>

<?php echo $this->getHtml() ?>

<?php if ($element->getAfterElementHtml()): ?>
    <label class="addafter" for="<?php echo $element->getHtmlId() ?>"><?php echo $element->getAfterElementHtml() ?></label>
<?php endif; ?>
