<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="login-box">
    <div class="registered-users">
        <h1><?php echo $this->__('Log in') ?></h1>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
            <h2><?php echo $this->__('Registered Users') ?></h2>
            <ul class="form-list">
                <li>
                    <label for="email"><?php echo $this->__('Enter your email') ?>:</label>
                    <input type="email" class="required-entry validate-email" name="login[username]" id="email" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" placeholder="<?php echo $this->__('Email Address') ?>" />
                </li>
                <li>
                    <label for="pass"><?php echo $this->__('Enter your password') ?>:</label>
                    <input type="password" class="required-entry validate-password" name="login[password]" id="pass" placeholder="<?php echo $this->__('Password') ?>" />
                </li>
                <?php if (Mage::helper('Mage_Core_Helper_Captcha')->isRequired('user_login')): ?>
                    <?php echo $this->getChildHtml('captcha') ?>
                <?php endif ?>
            </ul>
            <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot your password?') ?></a>
            <div class="login-button">
                <input type="submit" value="<?php echo $this->__('Log In') ?>" />
            </div>
        </form>
    </div>
    <div class="new-users">
        <h2><?php echo $this->__('New Customers') ?></h2>
        <a href="<?php echo $this->getCreateAccountUrl() ?>"><input type="submit" value="<?php echo $this->__('Create an Account') ?>" /></a>
        <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('login-form', true);
//]]>
</script>
