<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Backend_Block_System_Messages */ ?>

<?php $lastCritical = $this->getLastCritical();?>
<div id="system_messages" class="message-system<?php if ($lastCritical): ?> message-system-unread<?php endif; ?>">
    <div class="message-system-inner">
        <?php if ($lastCritical): ?>
            <ul class="message-system-list">
                <li class="error"><!--  warning  -->
                    <?php echo $lastCritical->getText();?>
                    <?php if ($lastCritical->getLink()):?> 
                        <a href="<?php echo $lastCritical->getLink();?>"><?php echo $this->__('Go there now');?></a>
                    <?php endif; ?>
                </li>
            </ul>
        <?php endif; ?>
        <div class="message-system-short">
            System Messages:
            <?php if ($this->getCriticalCount()): ?>
                <span class="error"><a href="#" title="Critical System Messages"><?php echo $this->getCriticalCount();?></a></span>
            <?php endif;?>
            <?php if ($this->getMajorCount()): ?>
               <span class="warning"><a href="#" title="Major System Messages"><?php echo $this->getMajorCount();?></a></span>
            <?php endif;?>
        </div>
        <div id="message-system-all" title="<?php echo $this->__('System messags');?>" data-mage-init="{systemMessageDialog:{autoOpen:false, width: 600, ajaxUrl: &quot;<?php echo $this->getMessagesUrl();?>&quot;}}"></div>
    </div>
</div>

