<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Magento_Rma_Block_Adminhtml_Rma_Edit_Tab_General_Shippingaddress
 */
?>
<?php if ($this->getOrderShippingAddress()) : ?>
    <div class="fieldset-wrapper">
        <div class="fieldset-wrapper-title">
            <span class="title"><?php echo Mage::helper('Magento_Rma_Helper_Data')->__('Order Shipping Address') ?></span>
        </div>
        <address><?php echo $this->getOrderShippingAddress() ?></address>
    </div>
<?php endif ?>
