<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     pro_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 */
?>
<form id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
    <div class="giftcard">
        <h2><?php echo $this->__('Gift Cards') ?></h2>
        <div id="giftcard_balance_lookup"></div>
        <span id="gc-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
        </span>
        <label for="giftcard-code"><?php echo $this->__('Enter the gift card code') ?></label>
        <div class="input-box"><input class="required-entry input-text" id="giftcard-code" name="giftcard_code" data-validate="{required:true}" value="" /></div>
        <div class="buttons-set">
            <button class="button" type="submit" value="<?php echo $this->__('Add Gift Card') ?>"><span><span><?php echo $this->__('Add Gift Card') ?></span></span></button>
            <button class="button check-gc-status" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></button>
        </div>

        <script type="text/javascript">
            (function($) {
                head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
                    "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
                    "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                    "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
                    "<?php echo $this->getViewFileUrl('Enterprise_GiftCardAccount::js/gift-card.js')?>", function() {
                        $('#giftcard-form').giftCard({
                            giftCardCodeSelector: '#giftcard-code',
                            checkStatus: 'button.check-gc-status',
                            giftCardStatusUrl: '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
                            giftCardStatusId: '#giftcard_balance_lookup',
                            giftCardSpinnerId: '#gc-please-wait'
                        }).validation();
                    });
            })(jQuery);
        </script>

    </div>
</form>
