<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
$countResultsEnabled = $this->isCountResultsEnabled();
$recommendations = $this->getRecommendations();
$recommendationsCount = count($recommendations);
if ($recommendationsCount):?>
<div class="block recommendations">
    <strong><?php echo __('Related search terms:');?></strong>
    <?php for($i=0;$i<$recommendationsCount;$i++) :?>
        <a href="<?php echo $recommendations[$i]['link']?>"><?php echo $recommendations[$i]['word']?></a>
        <?php if($countResultsEnabled):?>
            <span class="count"><?php echo $recommendations[$i]['num_results']?></span>
        <?php endif;?>
        <?php if ($i != $recommendationsCount-1) echo ","?>
    <?php endfor;?>
</div>
<?php endif; ?>
