<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Toolbar_Breadcrumbs */ ?>
<div>
    <span><?php echo $this->__('Current Location:'); ?></span>
    <?php $breadcrumbs = $this->getBreadcrumbs(); ?>
    <?php for ($i = 0, $breadcrumbCount = count($breadcrumbs); $i < $breadcrumbCount; $i++) : ?>
        <?php $breadcrumb = $breadcrumbs[$i]; ?>
        <?php if ($i < $breadcrumbCount - 1) : ?>
            <a href="<?php echo $breadcrumb['url']; ?>"><?php echo $breadcrumb['label']; ?></a>
            <span>/</span>
        <?php else : ?>
            <span><?php echo $breadcrumb['label']; ?></span>
        <?php endif; ?>
    <?php endfor; ?>
</div>
