<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Toolbar_HandlesHierarchy */ ?>
<div id="vde_handles_hierarchy" class="vde_toolbar_cell">
    <div class="vde_toolbar_cell_title">
        <?php echo $this->__('Page:'); ?>
        <span class="vde_toolbar_cell_value"><?php echo $this->getSelectedHandleLabel(); ?></span>
    </div>
    <div class="vde_toolbar_cell_content">
        <div id="vde_handles_tree"<?php if ($this->getSelectedHandle()) : ?> data-selected="li[rel='<?php echo $this->getSelectedHandle(); ?>']"<?php endif; ?>><?php echo $this->renderHierarchy(); ?></div>
    </div>
</div>
