<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div>
    <input type="checkbox" checked="checked" id="vde_highlighting"/>
    <label for="vde_highlighting"><?php echo $this->__('Highlight blocks'); ?></label>
</div>

<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('#vde_highlighting').on('click', null, function (event) {
            designEditor.highlight(jQuery(this).prop('checked'));
        });
    });
</script>
