<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_DesignEditor_Block_Toolbar_PageType */ ?>
<div id="vde_page_types_hierarchy">
    <?php echo $this->renderPageTypes(); ?>
</div>
<div class="vde_toolbar_cell">
    <div class="vde_toolbar_cell_title">
        <?php echo $this->__('Page Type'); ?>
        <span class="vde_toolbar_cell_value"><?php echo $this->getSelectedPageType(); ?></span>
    </div>
    <div class="vde_toolbar_cell_content">
        <button id="vde_page_types_control"><?php echo $this->__('Select a Page Type'); ?></button>
    </div>
</div>
<script type="text/javascript">
(function ($) {
    $(document).ready(function () {
        $("#vde_page_types_hierarchy").jstree({
            ui: {
                select_limit: 1,
                selected_parent_close: false
            }
        }).bind('select_node.jstree', function (e, data) {
            var selectedListItem = data.rslt.obj;
            $('#vde_page_types_control').text(selectedListItem.children('a').text());
            if ($(this).is(':visible')) {
                $(this).hide();
                window.location = selectedListItem.children('a').attr('href');
            }
        });
        $('#vde_page_types_control').bind('click', function (event) {
            var controlPos = $(this).offset();
            var controlHeight = $(this).outerHeight();
            $("#vde_page_types_hierarchy").css({
                left: controlPos.left,
                top: controlPos.top + controlHeight
            }).slideToggle();
        });
        <?php if ($this->getSelectedPageType()) : ?>
        $("#vde_page_types_hierarchy").bind('loaded.jstree', function (e, data) {
            var treeInstance = data.inst;
            treeInstance.select_node($(this).find('li[rel="<?php echo $this->getSelectedPageType(); ?>"]'));
        });
        <?php endif; ?>
    });
})(jQuery);
</script>
