<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php /** @var $this Mage_Core_Block_Template */ ?>
<div class="vde_toolbar_row">
    <?php $layout = $this->getLayout(); ?>
    <?php foreach ($this->getChildNames() as $name): ?>
    <div class="vde_toolbar_cell">
        <?php echo $layout->renderElement($name) ?>
    </div>
    <?php endforeach; ?>
</div>
