<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>
<?php $_product = $this->getProduct() ?>
<?php if($_product->isSaleable()): ?>
    <script type="text/javascript">
require([
    "jquery",
    "mage/mage"
], function($){
    //<![CDATA[
        $(document).ready(function() {
            $('#product_addtocart_form').mage('bundleOption', {
                "bundleConfig": <?php echo $this->getJsonConfig() ?>,
                "roundingMethod" : "<?php echo $this->getRoundingMethod() ?>",
                "bundleOptionQtyPrefix": "#bundle-option-",
                "bundleOptionQtySuffix": "-qty-input",
                "priceSelectors": {
                    "product-price": "#product-price-<?php echo $_product->getId()?>",
                    "bundle-price": "#bundle-price-<?php echo $_product->getId()?>",
                    "price-including-tax": "#price-including-tax-product-price-<?php echo $_product->getId()?>",
                    "price-excluding-tax": "#price-excluding-tax-product-price-<?php echo $_product->getId()?>"
                }
            });
        });
    //]]>
    
});
</script>
<?php endif; ?>
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="stock available" title="<?php echo __('Availability:') ?>">
            <span><?php echo __('In stock') ?></span>
        </p>
    <?php else: ?>
        <p class="stock unavailable" title="<?php echo __('Availability:') ?>">
            <span><?php echo __('Out of stock') ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>
<?php echo $this->getChildHtml('bundle_prices') ?>
