<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
    <table class="pager" cellspacing="0">
        <tr>
            <td>
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
            </td>
            <td class="sort-by">
                <strong><?php echo $this->__('Sort by') ?>:</strong> 
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <a href="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> class="active"<?php endif; ?>><?php echo $_order ?></a><span class="pipe">|</span>
                <?php endforeach; ?>
            </td>
            <?php if($this->getLastPageNum()>1): ?>
            <td>
                <strong><?php echo $this->__('Page:') ?></strong>
                <ol>
                <?php if (!$this->isFirstPage()): ?>
                    <li>
                        <a href="<?php echo $this->getPreviousPageUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>" alt="<?php echo $this->__('Previous') ?>"/></a>
                    </li>
                <?php endif ?>
                <?php foreach ($this->getPages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <li><span class="on"><?php echo $_page ?></span></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                    <?php endif ?>
                <?php endforeach;; ?>
                <?php if (!$this->isLastPage()): ?>
                    <li>
                        <a href="<?php echo $this->getNextPageUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>" alt="<?php echo $this->__('Next') ?>"/></a>
                    </li>
                <?php endif ?>
                </ol>
            </td>
            <?php endif; ?>
            <td class="a-right">
                <?php echo $this->__('Show') ?> <select onchange="setLocation(this.value)">
                <?php foreach (array(8=>8, 16=>16, 24=>24) as  $_key=>$_label): ?>
                    <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                        <?php echo $_label ?>
                    </option>
                <?php endforeach; ?>
                </select> <?php echo $this->__('per page') ?>
            </td>
            <?php if ($this->helper('rss/catalog')->getTagFeedUrl()): ?>
            <td class="a-right"><a href="<?php echo $this->helper('rss/catalog')->getTagFeedUrl() ?>" class="no-wrap link-feed"><?php echo $this->__('Subscribe to Feed') ?></a></td>
            <?php endif; ?>
        </tr>
    </table>
<?php endif ?>
