<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <?=$this->getMessagesBlock()->getGroupedHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend>Change Account Password</legend>
        <ul>
            <li>
                <div class="input-left">
                    <label for="current_password">Current Password <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry input-text" name="current_password" id="current_password"/>
                </div>
                        </li>
            <li>
                <div class="input-left">
                    <label for="password">New Password <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry validate-password input-text" name="password" id="password"/>
                </div>
                <div class="input-right">
                    <label for="confirmation">Confirm New Password <span class="required">*</span></label><br/>
                    <input type="password" class="required-entry validate-cpassword input-text" name="confirmation" id="confirmation"/>
                </div>
            </li>
        </ul>
    </fieldset>
    <div class="buttons-container">
        <p class="required">* Required Fields</p>
        <a href="<?=$baseUrl?>customer/account/" class="float-left">&laquo; Back</a>
        <input type="submit" class="input-button float-right" value="Continue"/>
    </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate');
    </script>