<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <?=$this->getMessagesBlock()->getGroupedHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend>Edit Personal Information</legend>
        <ul>
            <li>
                <div class="input-left">
                    <label for="firstname">First Name <span class="required">*</span></label><br/>
                    <input type="text" name="firstname" value="<?=$customer->getFirstname()?>" title="First Name"  class="required-entry input-text"/>
                </div>
                <div class="input-right">
                    <label for="lastname">Last Name <span class="required">*</span></label><br/>
                    <input type="text" name="lastname" value="<?=$customer->getLastname()?>" title="Last Name"  class="required-entry input-text"/>
                </div>
            </li>
            <li>
                <label for="email_address">Email <span class="required">*</span></label><br/>
                <input type="text" name="email" value="<?=$customer->getEmail()?>" title="Email Address" class="required-entry validate-email input-text"/>
            </li>
        </ul>
    </fieldset>
    <div class="clearfix"></div>
    <div class="buttons-container">
        <p class="required">* Required Fields</p>
        <a href="<?=$baseUrl?>customer/account/" class="float-left">&laquo; Back</a>
        <input type="submit" class="input-button float-right" value="Continue"/>
    </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
    </script>
