    <?=$this->getMessagesBlock()->getHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend>Retrieve your password here</legend>
        <p>Please enter your email below and we'll send you a new password.</p>
        <ul class="input-list">
            <li>
                <div class="input-left"><label for="email_address">Email Address <span class="required">*</span></label><br/>
                <input name="email" alt="email"  type="text" id="email_address" class="required-entry validate-email input-text"></div>
                <div class="clearfix"></div></li>
        </ul>
    </fieldset>
    <div class="form-buttons">
        <p class="required">* Required Fields</p>
        <a href="<?=$baseUrl?>customer/account/" class="left">&laquo; Back to Login</a>
        <button class="form-button" type="submit"><span>Submit</span></button>
    </div>        
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
    </script>