<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <?=$this->getMessagesBlock()->getGroupedHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend>Retrieve your password here</legend>
        <p>Please enter your email below and we'll send you a new password.</p>
        <ul class="input-list">
            <li>
                <div class="input-left"><label for="email_address">Email Address <span class="required">*</span></label><br/>
                <input name="email" alt="email"  type="text" id="email_address" class="required-entry validate-email input-text"></div>
                <div class="clearfix"></div></li>
        </ul>
    </fieldset>
    <div class="form-buttons">
        <p class="required">* Required Fields</p>
        <a href="<?=$baseUrl?>customer/account/" class="left">&laquo; Back to Login</a>
        <button class="form-button" type="submit"><span>Submit</span></button>
    </div>        
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
    </script>