	<?=$this->getMessagesBlock()->getHtml()?>
    <form action="<?=$this->getAction()?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend><?=__('Newsletter Subscriptions')?></legend>
        <ul>
            <li>
                <input type="checkbox" name="is_subscribed" value="1" title="<?=__('General Subscription')?>"  <?if($this->getIsSubscribed()):?> checked<?endif?>/> <label for="subscription"><?=__('General Subscription')?></label>
            </li>
        </ul>
    </fieldset>
    <div class="clearfix"></div>
    <div class="buttons-container">
        <a href="<?=$baseUrl?>customer/account/" class="float-left">&laquo; Back</a>
        <input type="submit" class="input-button float-right" value="Save"/>
    </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
    </script>
