<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="block dashboard orders">
<?php $_orders = $this->getOrders(); ?>
    <div class="order title">
        <strong><?php echo __('Recent Orders') ?></strong>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?>
            <a class="action view" href="<?php echo $this->getUrl('sales/order/history') ?>">
                <span><?php echo __('View All') ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="content">
    <?php echo $this->getChildHtml()?>
    <?php if( sizeof($_orders->getItems()) > 0 ): ?>
        <table class="data table orders recent" id="my-orders-table">
            <thead>
                <tr>
                    <th class="col id"><?php echo __('Order #') ?></th>
                    <th class="col date"><?php echo __('Date') ?></th>
                    <th class="col shipping"><?php echo __('Ship To') ?></th>
                    <th class="col total"><?php echo __('Order Total') ?></th>
                    <th class="col status"><?php echo __('Status') ?></th>
                    <th class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td class="col id"><?php echo $_order->getRealOrderId() ?></td>
                        <td class="col date"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
                        <td class="col shipping"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td class="col total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td class="col status"><em><?php echo $_order->getStatusLabel() ?></em></td>
                        <td class="col actions">
                            <a href="<?php echo $this->getViewUrl($_order) ?>" class="action view">
                                <span><?php echo __('View Order') ?></span>
                            </a>
                            <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order)) : ?>
                                <a href="<?php echo $this->getReorderUrl($_order) ?>" class="action order">
                                    <span><?php echo __('Reorder') ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p class="empty"><?php echo __('You have placed no orders.'); ?></p>
    <?php endif; ?>
    </div>
</div>
