<script type="text/javascript">
    var ruleForm = new varienForm('rule_edit_form');
    
<?if($_gridJsObject=$this->getLayout()->getBlock('promo.quote.grid')->getJsObjectName()):?>
    function registerRuleProduct(grid, element, checked){
    	var product_ids = $('rule_product_ids');
    	var ids_arr = product_ids.value!='' ? product_ids.value.split(',') : [];
    	var id = element.value;

        if (checked){
        	ids_arr[ids_arr.length] = id;
        	console.log(ids_arr);
        	ids_arr = ids_arr.uniq();
        } else {
			ids_arr = ids_arr.without(id);
        }
        console.log(ids_arr);
        product_ids.value = ids_arr.join(',');
        console.log(product_ids.value);
        grid.reloadParams = {'selected_products':product_ids.value}; // add ids to request
    }
    
    function ruleProductRowClick(grid, event){
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if(trElement){
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                <?=$_gridJsObject?>.setCheckboxChecked(checkbox[0], checked);
            }
        }
    }

    <?=$_gridJsObject?>.rowClickCallback = ruleProductRowClick;
    //<?=$_gridJsObject?>.initRowCallback = ruleProductRowInit;
    <?=$_gridJsObject?>.checkboxCheckCallback = registerRuleProduct;
<?endif;?>
</script>