<?php
/**
 *
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
namespace Magento\MultipleWishlist\Controller\Index;

use Magento\Framework\App\Action\NotFoundException;
use Magento\Customer\Model\Session;
use Magento\Framework\App\Action\Context;
use Magento\MultipleWishlist\Controller\IndexInterface;
use Magento\MultipleWishlist\Model\ItemManager;
use Magento\Wishlist\Controller\WishlistProviderInterface;

class Copyitem extends \Magento\Framework\App\Action\Action implements IndexInterface
{
    /**
     * @var WishlistProviderInterface
     */
    protected $wishlistProvider;

    /**
     * @var \Magento\Customer\Model\Session
     */
    protected $customerSession;

    /**
     * @var \Magento\MultipleWishlist\Model\ItemManager
     */
    protected $itemManager;

    /**
     * @var \Magento\Wishlist\Model\ItemFactory
     */
    protected $itemFactory;

    /**
     * @param Context $context
     * @param WishlistProviderInterface $wishlistProvider
     * @param Session $customerSession
     * @param ItemManager $itemManager
     * @param \Magento\Wishlist\Model\ItemFactory $itemFactory
     */
    public function __construct(
        Context $context,
        WishlistProviderInterface $wishlistProvider,
        Session $customerSession,
        ItemManager $itemManager,
        \Magento\Wishlist\Model\ItemFactory $itemFactory
    ) {
        $this->wishlistProvider = $wishlistProvider;
        $this->customerSession = $customerSession;
        $this->itemManager = $itemManager;
        $this->itemFactory = $itemFactory;
        parent::__construct($context); // TODO: Change the autogenerated stub
    }

    /**
     * Copy wishlist item to given wishlist
     *
     * @return void
     * @throws NotFoundException
     */
    public function execute()
    {
        $requestParams = $this->getRequest()->getParams();
        if ($this->customerSession->getBeforeWishlistRequest()) {
            $requestParams = $this->customerSession->getBeforeWishlistRequest();
            $this->customerSession->unsBeforeWishlistRequest();
        }

        $wishlist = $this->wishlistProvider->getWishlist(
            isset($requestParams['wishlist_id']) ? $requestParams['wishlist_id'] : null
        );
        if (!$wishlist) {
            throw new NotFoundException();
        }
        $itemId = isset($requestParams['item_id']) ? $requestParams['item_id'] : null;
        $qty = isset($requestParams['qty']) ? $requestParams['qty'] : null;
        if ($itemId) {
            $productName = '';
            try {
                /* @var \Magento\Wishlist\Model\Item $item */
                $item = $this->itemFactory->create();
                $item->loadWithOptions($itemId);

                $wishlistName = $this->_objectManager->get('Magento\Framework\Escaper')->escapeHtml($wishlist->getName());
                $productName = $this->_objectManager->get(
                    'Magento\Framework\Escaper'
                )->escapeHtml(
                    $item->getProduct()->getName()
                );

                $this->itemManager->copy($item, $wishlist, $qty);
                $this->messageManager->addSuccess(__('"%1" was copied to %2.', $productName, $wishlistName));
                $this->_objectManager->get('Magento\Wishlist\Helper\Data')->calculate();
            } catch (\InvalidArgumentException $e) {
                $this->messageManager->addError(__('The item was not found.'));
            } catch (\DomainException $e) {
                $this->messageManager->addError(__('"%1" is already present in %2.', $productName, $wishlistName));
            } catch (\Magento\Framework\Model\Exception $e) {
                $this->messageManager->addError($e->getMessage());
            } catch (\Exception $e) {
                $this->_objectManager->get('Magento\Framework\Logger')->logException($e);
                if ($productName) {
                    $message = __('We could not copy "%1".', $productName);
                } else {
                    $message = __('We could not copy the wish list item.');
                }
                $this->messageManager->addError($message);
            }
        }
        $wishlist->save();
        if ($this->customerSession->hasBeforeWishlistUrl()) {
            $this->getResponse()->setRedirect($this->customerSession->getBeforeWishlistUrl());
            $this->customerSession->unsBeforeWishlistUrl();
        } else {
            $this->getResponse()->setRedirect($this->_redirect->getRedirectUrl());
        }
    }
}
