<div class="home-spot">
    <p class="callout"><img src="<?=$this->getSkinUrl('images/home_main_callout.jpg')?>" alt=""/></p>
    <p class="callout"><img src="<?=$this->getSkinUrl('images/free_shipping_callout.jpg')?>" alt=""/></p>
    <div class="box best-selling">
        <h3>Best Selling Products</h3>
        <table cellspacing="0">
            <tr class="odd">
                <td><a href="#"><img src="<?=$this->getSkinUrl('images/best_selling_img04.jpg')?>" width="95" height="63" alt="" class="product-img"></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name">Blue Sandals isolated in a white background</a></p>
                    <p>See all <a href="#">Women's Shoes</a></p>
                   </div></td>
                <td><a href="#"><img src="<?=$this->getSkinUrl('images/best_selling_img06.jpg')?>" width="95" height="63" alt="" class="product-img"></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name">Blue Sandals isolated in a white background</a></p>
                    <p>See all <a href="#">Women's Shoes</a></p>
                   </div></td>
            </tr>
            <tr class="even">
                <td><a href="#"><img src="<?=$this->getSkinUrl('images/best_selling_img03.jpg')?>" width="95" height="63" alt="" class="product-img"></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name">Blue Sandals isolated in a white background</a></p>
                    <p>See all <a href="#">Women's Shoes</a></p>
                   </div></td>
                <td><a href="#"><img src="<?=$this->getSkinUrl('images/best_selling_img01.jpg')?>" width="95" height="63" alt="" class="product-img"></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name">Blue Sandals isolated in a white background</a></p>
                    <p>See all <a href="#">Women's Shoes</a></p>
                  </div></td>
            </tr>
            <tr class="odd">
                <td><a href="#"><img src="<?=$this->getSkinUrl('images/best_selling_img05.jpg')?>" width="95" height="63" alt="" class="product-img"></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name">Blue Sandals isolated in a white background</a></p>
                    <p>See all <a href="#">Women's Shoes</a></p>
                   </div></td>
                <td><a href="#"><img src="<?=$this->getSkinUrl('images/best_selling_img02.jpg')?>" width="95" height="63" alt="" class="product-img"></a>
                  <div class="product-description">
                    <p><a href="#" class="product-name">Blue Sandals isolated in a white background</a></p>
                    <p>See all <a href="#">Women's Shoes</a></p>
                   </div></td>
             </tr>
        </table>
       </div>
</div>