
<div class="box shop-by">
	<div class="head">
		<span class="corner"></span>
		<h3>Shop by</h3>
	</div>
	<div class="box-container">
		<h4>Currently Shopping By</h4>
		<div class="content">
			<ul class="widget-list">
				<li><a href="#" class="action"/>Remove</a><span class="label">Price:</span><br/><a 
					href="#">$10-$99</a> (3)</span></li>
				<li><a href="#" class="action">Remove</a><span class="label">Manufacturer:</span><br/><a 
					href="#">Kennwood</a> (4)</span></li>
			</ul>
			<p class="actions"><a href="#">Clear All</a></p>
		</div>
		<div class="narrow-by">
			<h4>More Shopping options</h4>
			<dl>
				<dt>Category</dt>
				<dd>
					<ol>
					<?foreach ($categories as $_node):?>
											<li><a href="<?=$baseUrl?>catalog/category/view/id/<?=$_node->getId()?>/" <?if (!empty($currentCategoryId) && $_node->getId()==$currentCategoryId):?> 
										class="active"<?endif?>><?=$_node->getName()?></a> (<?=$_node->getProductCount()?>)</li>
									<?endforeach?>
					</ul>
				</dd>
							<?if(!empty($manufacturers)):?>
				<dt>Brand</dt>
				<dd>
					<ol>
									<?foreach($manufacturers as $_item):?>
						<li><a href="<?=$baseUrl?>catalog/search/by/attr/manufacturer/value/<?=$_item['value']?>/"><?=$_item['label']?></a> (1)</li>
									<?endforeach?>
					</ol>
				</dd>
							<?endif?>
							<?if(!empty($types)):?>
				<dt>Type</dt>
				<dd>
					<ol>
									<?foreach($types as $_item):?>
						<li><a href="<?=$baseUrl?>catalog/search/by/attr/shoe_type/value/<?=$_item['value']?>/"><?=$_item['label']?></a> (1)</li>
									<?endforeach?>
					</ol>
				</dd>
							<?endif?>
				<dt>Color</dt>
				<dd>
					<ol>
						<li><a href="#">Red</a> (1)</li>
						<li><a href="#">Red</a> (1)</li>
						<li><a href="#">Red</a> (1)</li>
					</ol>
				</dd>
				<dt>Price</dt>
				<dd>
					<ul>
						<li><a href="#">$10 - $99</a> (1)</li>
						<li><a href="#">$10 - $99</a> (1)</li>
						<li><a href="#">$10 - $99</a> (1)</li>
					</ol>
				</dd>
			</dl>
		</div>
	</div>
</div>
<!-- [ends] .browse-by // -->
