<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this Enterprise_Rma_Block_Order_Button */
?>
<?php if(Mage::helper('Enterprise_Rma_Helper_Data')->canCreateRma($this->getOrder())): ?>
    <span class="separator">|</span>
    <a href="<?php echo Mage::helper('Enterprise_Rma_Helper_Data')->getReturnCreateUrl($this->getOrder()) ?>"><?php echo __('Return') ?></a>
<?php endif;?>
