<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-actions">
    <?php echo $this->getBackButtonHtml(); ?>
    <?php echo $this->getResetButtonHtml(); ?>
    <?php echo $this->getDeleteButtonHtml(); ?>
    <?php echo $this->getSaveButtonHtml(); ?>
</div>
<?php echo $this->getRenameFormHtml(); ?>
<script type="text/javascript">
require(['jquery', "mage/mage"], function(jQuery){

    jQuery('#<?php echo $this->getRenameFormId() ?>').mage('form').mage('validation');

});
</script>
