<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if ($this->getChildHtml()): ?>
<div class="fieldset-wrapper order-gift-options">
    <div class="fieldset-wrapper-title"><span class="title"><?php echo Mage::helper('Magento_Sales_Helper_Data')->__('Gift Options') ?></span></div>
	<?php echo $this->getChildHtml() ?>
</div>
<?php endif ?>
