<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme_Item */?>

<li style="height:300px; width:240px; margin:20px; float:left;">
    <?php echo $this->getThemeHtml() ?>
    <div style="margin:5px 20px;">
        <h4><sup><?php echo $this->getTheme()->getIsFeatured() ? 'F' : 'X'?></sup> <?php echo $this->getTheme()->getThemeTitle()?></h4>
        <?php echo $this->getLaunchButtonHtml() ?>
    </div>
</li>
