<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     Mage_DesignEditor
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php /** @var $this Mage_DesignEditor_Block_Adminhtml_Theme_List */ ?>

<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
</div>

<div class="entry-edit">
    <div class="fieldset">
        <div class="hor-scroll">
            <?php echo $this->getChildHtml('available_theme'); ?>
        </div>
    </div>
</div>
