<h1 class="page-heading">Administrator account</h1>
<form action="<?=$postAction?>" method="post" id="form-validate">
<fieldset class="group-select">
 <legend>Personal Information</legend>
    <h3>Personal Information</h3>
    <ul>
        <li>
            <div class="input-left">
                <label for="firstname">First Name <span class="required">*</span></label><br/>
                <input type="text" name="firstname" id="firstname" value="<?=$data->getFirstname()?>" title="First Name" class="required-entry input-text"/>
            </div>
            <div class="input-left">
                <label for="lastname">Last Name <span class="required">*</span></label><br/>
                <input type="text" name="lastname" id="lastname" value="<?=$data->getLastname()?>" title="Last Name" class="required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-left">
                <label for="email_address">Email <span class="required">*</span></label><br/>
                <input type="text" name="email" id="email_address" value="<?=$data->getEmail()?>" title="Email Address" class="validate-email required-entry input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
<fieldset class="group-select">
    <legend>Login Information</legend>
    <h3>Login Information</h3>
    <ul>
        <li>
            <div class="input-left">
                <label for="username">Username <span class="required">*</span></label><br/>
                <input type="text" name="username" id="username" value="<?=$data->getEmail()?>" title="User name" class="validate-email required-entry input-text"/>
            </div>
        </li>
        <li>
            <div class="input-left">
                <label for="password">Password <span class="required">*</span></label><br/>
                <input type="password" name="password" id="password" title="Password"  class="required-entry validate-password input-text"/>
            </div>
            <div class="input-right">
                <label for="confirmation">Confirm Password <span class="required">*</span></label><br/>
                <input type="password" name="confirmation" title="Password Confirmation" id="confirmation" class="required-entry validate-cpassword input-text"/>
            </div>
        </li>
    </ul>
</fieldset>
    <div class="buttons-container">
        <p class="required">* Required Fields</p>
        <input type="submit" class="input-button" value="Continue"/>
    </div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate');
    dataForm.setElementsRelation('country', 'state', '<?=$baseSecureUrl?>directory/json/childRegion/');
</script>