<h1 class="page-heading">License</h1>
<form action="<?=$postAction?>" method="post">
.....
<div class="float-right"><input type="checkbox" name="agree" value="1" id="agree"><label for="agree">It agree</label></div>
<div class="buttons-container">
    <a href="<?=$step->getPrevUrl()?>" class="float-left">&laquo; Back</a>
    <input type="submit" value="Continue" class="input-button">
</div>
</form>