
    <h1 class="page-heading">Edit Account Info</h1>
    <?=$this->getMessagesBlock()->getHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend>Edit Personal Information</legend>
        <ul>
            <li>
                <div class="input-left">
                    <label for="firstname">First Name <span class="required">*</span></label><br/>
                    <input type="text" name="firstname" value="<?=$data->getFirstname()?>" title="First Name"  class="required-entry input-text"/>
                </div>
                <div class="input-right">
                    <label for="lastname">Last Name <span class="required">*</span></label><br/>
                    <input type="text" name="lastname" value="<?=$data->getLastname()?>" title="Last Name"  class="required-entry input-text"/>
                </div>
            </li>
            <li>
                <div class="input-left"><label for="email_address">Email <span class="required">*</span></label><br/>
                <input type="text" name="email" value="<?=$data->getEmail()?>" title="Email Address" class="required-entry validate-email input-text"/></div>
            </li>
        </ul>
    </fieldset>
    <div class="clearfix"></div>
    <div class="buttons-container">
        <p class="required">* Required Fields</p>
        <a href="<?=$baseUrl?>customer/account/" class="float-left">&laquo; Back</a>
        <input type="submit" class="input-button float-right" value="Continue"/>
    </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
    </script>