
    <h1 class="page-heading">Password Forgotten</h1>
    <?=$messages->toHtml()?>
    <form action="<?=$action?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend>Retrieve your password here</legend>
        <p>Please enter your email below and we'll send you a new password.</p>
        <ul class="input-list">
            <li>
                <div class="input-left"><label for="email_address">Email Address <span class="required">*</span></label><br/>
                <input name="email" alt="email"  type="text" id="email_address" class="required-entry validate-email input-text"></div>
                <div class="clearfix"></div></li>
        </ul>
            </fieldset>
        <div class="buttons-container">
            <p class="required">* Required Fields</p>
            <a href="<?=$baseUrl?>customer/account/" class="float-left">&laquo; Back</a>
            <input type="submit" class="input-button float-right" value="Continue"/>
            <div class="clearfix"></div>
        </div>
    </fieldset>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
    </script>