<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     magento2_reference
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * @var $this Mage_Paypal_Block_Express_Shortcut
 */
?>
<?php
$labelPosition = '';
if ($this->isOrPositionBefore()) {
$labelPosition = ' before';
} elseif ($this->isOrPositionAfter()) {
$labelPosition = ' after';
}
?>

<div data-label="or" class="paypal checkout <?php echo $labelPosition ?> paypal-logo">
    <?php $shortcutHtmlId = $this->getShortcutHtmlId() ?>
    <input type="image" data-action="checkout-form-submit" data-checkout-url="<?php echo $this->getCheckoutUrl()?>"
           src="<?php echo $this->getImageUrl()?>"
           alt="<?php echo __('Checkout with PayPal');?>"
           title="<?php echo __('Checkout with PayPal');?>"/>
    <?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
    <?php if ($this->getIsInCatalogProduct()): ?>
        <input type="hidden" id="pp-checkout-url" name="return_url" value=""/>
        <?php endif; ?>

    <?php
    $confirmationUrl = $this->getConfirmationUrl();
    $isInCatalogProduct = $this->getIsInCatalogProduct();
endif; ?>
    <script type="text/javascript">
        (function($) {
            head.js(
                "<?php echo $this->getViewFileUrl('Mage_Paypal::js/paypal-checkout.js') ?>",
                function() {
                    $('.paypal-logo').paypalCheckout({
                        confirmMessage: "<?php echo Mage::helper('Mage_Core_Helper_Data')->jsQuoteEscape($this->getConfirmationMessage())?>",
                        confirmUrl: "<?php echo !empty($confirmationUrl) ? $confirmationUrl : false ?>",
                        isCatalogProduct: "<?php echo !empty($isInCatalogProduct) ? $isInCatalogProduct : false ?>",
                        paypalCheckoutSelector: '#pp-checkout-url',
                        productAddToCartForm: '#product_addtocart_form'
                    });
                });
        })(jQuery);
    </script>
</div>