<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Top menu
 *
 * @var $this \Magento\Doc\Ui\Element\Navigation
 */
?>

<?php $menu = $this->renderMenuHtml() ?>
<?php if ($menu): ?>
<nav class="navigation" role="navigation">
    <ul class="docmenu ui-menu" role="menu" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php echo $menu ?>
    </ul>
</nav>
<?php endif ?>
