<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/** @var $this Mage_Core_Block_Template */
/** @var $helper Mage_CatalogSearch_Helper_Data */
$helper = $this->helper('Mage_CatalogSearch_Helper_Data');
?>
<form id="search_mini_form" action="<?php echo $helper->getResultUrl() ?>" method="get">
    <input type="search" name="<?php echo $helper->getQueryParamName() ?>" id="search" placeholder="Search" maxlength="<?php echo $helper->getMaxQueryLength();?>"/>
    <div id="search_autocomplete" class="search-autocomplete"></div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $helper->__('Search') ?>');
    searchForm.initAutocomplete('<?php echo $helper->getSuggestUrl() ?>', 'search_autocomplete');
    //]]>
</script>
