<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * @see \Magento\Paypal\Block\Express\Review\Details
 */
?>
<table id="details-table" class="data-table">
    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
    <col width="1" />
    <col width="1" />
    <?php endif; ?>
    <thead>
        <tr>
            <th rowspan="<?php echo $rowspan ?>"><?php echo __('Product Name') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo __('Price') ?></th>
            <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo __('Qty') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo __('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?php echo $this->helper('Magento\Tax\Helper\Data')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('Magento\Tax\Helper\Data')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?php echo $this->helper('Magento\Tax\Helper\Data')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('Magento\Tax\Helper\Data')->getIncExcTaxLabel(true) ?></th>
            </tr>
        <?php endif; ?>
    </thead>
<?php echo $this->getChildHtml('totals'); ?>
    <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">(function($) {$('#details-table').decorate('table')})(jQuery)</script>
