<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="checkout-multishipping-payment-giftcardaccount">
<p class="note">
    <?php $_url = Mage::getUrl('checkout/cart'); ?>
    <?php echo __('To add or remove gift cards, <a href="%1">click here</a>.', $_url); ?><br />

    <?php if ((float)$this->getAppliedGiftCardAmount()): ?>
        <?php $amount = Mage::helper('Magento_Core_Helper_Data')->currency($this->getAppliedGiftCardAmount(), true); ?>
        <?php echo __('Gift Card amount applied to order: %1', $amount); ?>
    <?php endif; ?>

    <?php if ($this->isFullyPaidAfterApplication()): ?>
        <script type="text/javascript">
            head.js("<?php echo $this->getViewFileUrl('Enterprise_GiftCardAccount::js/payment-method.js')?>", function() {
                jQuery('#multishipping-billing-form').paymentMethod();
            });
        </script>
        <input type="hidden" name="payment[method]" value="free" />
    <?php endif; ?>
</p>
</div>
