<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
/** @var $this \Magento\Rma\Block\Email\Items */
?>
<table cellspacing="0" cellpadding="0" border="0" width="650">
    <thead>
    <tr>
        <th align="left" width="220" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Product Name:</th>
        <th align="left" width="80" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">SKU</th>
        <th align="left" width="95" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Condition</th>
        <th align="left" width="95" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Resolution</th>
        <th align="left" width="75" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Requested Qty</th>
        <th align="left" width="75" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Qty</th>
        <th align="left" width="85" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Status</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $color = '#CCCCCC';
    foreach($this->getCollection() as $item):
        if (!$color) {
            $color = '#CCCCCC';
        } else {
            $color = '';
        }
    ?>
    <tr>
        <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>">
            <strong><?php echo $this->escapeHtml($item->getProductName()) ?></strong>
            <?php $_options = $item->getOptions();
                if($_options): ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <dd><?php echo $_option['value'] ?></dd>
            <?php endforeach; ?>
            </dl>
            <?php endif; ?>
        </td>
        <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>">
            <?php echo $this->escapeHtml($item->getProductSku()) ?></span>
        </td>
        <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>">
            <?php echo $this->escapeHtml($this->getOptionAttributeStringValue($item->getCondition())) ?>
        </td>
        <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>">
            <?php echo $this->escapeHtml($this->getOptionAttributeStringValue($item->getResolution())) ?>
        </td>
        <td valign="top" align="center" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>">
            <?php echo $this->helper('Magento\Rma\Helper\Data')->parseQuantity($item->getQtyRequested(), $item) ?>
        </td>
        <td valign="top" align="center" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>">
            <?php echo $this->helper('Magento\Rma\Helper\Data')->getQty($item) ?>
        </td>
        <td valign="top" align="left" style="font-size:11px;padding:3px 9px;border-bottom:1px dotted <?php echo $color?>">
            <?php echo $this->escapeHtml($item->getStatusLabel()) ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
