<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head">
    <h3>Contact Us</h3>
</div>
<form action="<?=$this->getFormAction();?>" name="contactForm" id="contactForm" method="post">
    <fieldset class="group-select">
        <h4 class="legend">Contact Information</h4>
            <li>
                <div class="input-box">
                    <label for="firstname">Name <span class="required">*</span></label><br />
                    <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text">
                </div>

                <div class="input-box">
                    <label for="firstname">Email <span class="required">*</span></label><br />
                    <input name="email" id="email" title="Email" value="" class="required-entry input-text" type="text">
                </div>

                <div class="input-box">
                    <label for="firstname">Title</label><br />
                    <input name="title" id="title" title="Title" value="" class="input-text" type="text">
                </div>

                <div class="input-box">
                    <label for="firstname">Telephone</label><br />
                    <input name="telephone" id="telephone" title="Telephone" value="" class="input-text" type="text">
                </div>

                <div class="input-box">
                    <label for="firstname">Company</label><br />
                    <input name="company" id="company" title="Company" value="" class="input-text" type="text">
                </div>

                <div class="input-box">
                    <label for="firstname">Website URL</label><br />
                    <input name="website" id="website" title="Website URL" value="" class="input-text" type="text">
                </div>

                <div class="input-box">
                    <label for="firstname">Comment</label><br />
                    <textarea name="comment" id="comment" title="Comment" class="input-text" style="height:150px;width:525px;"></textarea>
                </div>
            </li>
    </fieldset>
    <div class="button-set">
        <p class="required">* Required Fields</p>
        <button class="form-button" type="submit"><span>Submit</span></button>
    </div>
</form>
<script type="text/javascript">
    var contactForm = new VarienForm('contactForm', true);
</script>
