<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php if( $this->getCount() ): ?>
<div class="collateral-box">
    <div class="head"><h4><?php echo $this->__('Product Tags') ?></h4></div>
        <?php echo $this->getChildHtml('list_before')?>
        <div class="tags-list">
            <?php echo $this->renderTags('<a href="%1$s">%2$s</a> <span>(%3$s)</span>') ?>
        </div>
</div>
<?php endif; ?>
