
    <h1 class="page-heading">Order #<?=$order->getOrderId()?> (<?=$order->getStatus()?>)</h1>
    <table cellspacing="0" width="100%">
        <thead>
            <tr>
                <th style="width:50%;"><h3>Billing Information</h3></th>
                <th style="width:50%;"><h3>Payment Method</h3></th></tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <address>
                        <?=$order->getAddressByType('billing')->toString('<b>{{firstname}} {{lastname}}</b><br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: 
												{{telephone}}')?>
                    </address>
                </td>
                <td>
                <?=$payment?>
                </td>
            </tr>
        </tbody>
    </table>
    <p></p>
    <table cellspacing="0" width="100%">
        <thead>
            <tr>
                <th style="width:50%;"><h3>Shipping Information</h3></th>
                <th style="width:50%;"><h3>Shipping Method</h3></th></tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <address>
                        <?=$order->getAddressByType('shipping')->toString('<b>{{firstname}} {{lastname}}</b><br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: 
												{{telephone}}')?>
                    </address>
                </td>
                <td>
                    <?=$order->getShippingDescription()?>
                </td>
            </tr>
        </tbody>
    </table>
    <p></p>
    <?$_items = $order->getEntitiesByType('item')?>
    <table cellspacing="0" width="100%" class="data-table">
        <thead>
            <tr>
                <th style="width:50%;">Items Order</th>
                <th class="align-center" style="width:10%;">Qty</th>
                <th class="align-center" style="width:20%;">Price</th>
                <th class="align-right" style="width:20%;">Ext. Price</th>
            </tr>
        </thead>
        <tfoot>
            <tr class="data-row-foot">
                <td class="align-right" colspan="4">
                    Grand Total:&nbsp;<strong><?=sprintf('$%.2f',$order->getGrandTotal())?></strong>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?foreach($_items as $_item):?>     
            <tr>
                <td><?=$_item->getName()?></td>
                <td class="align-center"><?=sprintf('%d',$_item->getQty())?></td>
                <td class="align-center"><?=sprintf('$%.2f',$_item->getPrice())?></td>
                <td class="align-right"><?=sprintf('$%.2f', $_item->getRowTotal())?></td>
            </tr>   
            <?endforeach?> 
        </tbody>
    </table>
    <div class="buttons-container">
			<a href="<?=$baseUrl?>customer/order/history/" class="float-left">&laquo; Back</a>
    </div>