<?php
/**
 * {license_notice}
 *
 * @category    Magento
 * @package     Magento_Cardgate
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var Magento_Cardgate_Block_Form_Ideal $this */
?>
<?php $methodCode = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $methodCode ?>" style="display:none;">
    <li>
        <div class="input-box">
            <?php echo $this->getSelectField(); ?>
        </div>
    </li>
</ul>
