<form action="<?=$uploadAction?>" method="POST" enctype="multipart/form-data" class="x-form">
<div class="data-form">
<div class="x-box-tl"><div class="x-box-tr"><div class="x-box-tc"></div></div></div>
<div class="x-box-ml"><div class="x-box-mr"><div class="x-box-mc">
    <fieldset>
    <legend>Product Image</legend>
    <img src="<?=$imagePreviewUrl?>" onerror="this.style.display='none'">
    <input type="file" name="image">
    <input type="submit" value="Upload">
    </fieldset>
</div></div></div>
<div class="x-box-bl"><div class="x-box-br"><div class="x-box-bc"></div></div></div>
</div>
</form>
