<div class="content-header">
    <table cellspacing="0" class="grid-header"> 
        <tr>
            <td style="width:30%;"><h3><?=$this->getHeader()?></h3></td>
            <td class="form-buttons">
       <table cellspacing="0" class="form-button">
				<tr>
					<td class="form-button-left"></td>
					<td class="form-button-right"><a href="#" id="add_address_button"><span id="add_new_address_button"><?=__('Add New Customer Address')?></span></a></td>
				</tr>
			</table>
			<table cellspacing="0" class="form-button">
				<tr>
					<td class="form-button-left"></td>
					<td class="form-button-right"><a href="#" onclick="customerForm.submit();return false;"><?=__('Save Customer')?></a></td>
				</tr>
			</table>
			<?if($this->getCustomerId()):?>
			<table cellspacing="0" class="form-button">
				<tr>
					<td class="form-button-left"></td>
					<td class="form-button-right"><a href="#" onclick="customerDelete();return false;"><span><?=__('Delete Customer')?></a></td>
				</tr>
			</table>
                <?endif;?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="customer_edit_form">
</form>
<script type="text/javascript" language="javascript">
    var customerForm = new varienForm('customer_edit_form');
    
    function customerEditShowButtons(data){
        customerForm.initFormElements();
        if(data.tab.id && data.tab.id=='customer_info_tabs_addresses'){
            Element.show($('add_address_button'));
        }
    }
    
    function customerEditHideButtons(data){
        if(data.tab && data.tab.id=='customer_info_tabs_addresses'){
            Element.hide($('add_address_button'));
        }
    }
    
    function customerDelete(){
        if(confirm('<?=__('are you sure?')?>')){
            location.href = '<?=$this->getDeleteUrl()?>'
        }
    }
    
    varienGlobalEvents.attachEventHandler('showTab', customerEditShowButtons);
    varienGlobalEvents.attachEventHandler('hideTab', customerEditHideButtons);
</script>