<?
/**
 * Template for Mage_Adminhtml_Block_Customer_Edit
 */
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header"> 
        <tr>
            <td style="width:30%;"><h3><?=$this->getHeader()?></h3></td>
            <td class="a-right">
            <?if($this->getCustomerId()):?>
                <?=$this->getDeleteButtonHtml()?>
            <?endif;?>
                <?=$this->getSaveButtonHtml()?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="customer_edit_form">
</form>
<script type="text/javascript" language="javascript">
    var customerForm = new varienForm('customer_edit_form');
    function customerDelete(){
        if(confirm('<?=__('are you sure?')?>')){
            location.href = '<?=$this->getDeleteUrl()?>'
        }
    }
</script>