<div class="head">
    <table cellspacing="0"> 
        <tr>
            <td style="width:30%;"><h3><?=$this->getHeader()?></h3></td>
            <td class="buttons">
                <a href="#" class="button" id="add_address_button"><span id="add_new_address_button"><?=__('add new customer address')?></span></a>
                <a href="#" class="button" onclick="customerForm.submit();return false;"><span><?=__('save customer')?></span></a>
                <?if($this->getCustomerId()):?>
                <a href="#" class="button" onclick="customerDelete();return false;"><span><?=__('delete customer')?></span></a>
                <?endif;?>
            </td>
        </tr>
    </table>
</div>
<form action="<?=$this->getSaveUrl()?>" method="POST" id="customer_edit_form">
</form>
<script type="text/javascript" language="javascript">
    var customerForm = new varienForm('customer_edit_form');
    
    function customerEditShowButtons(data){
        customerForm.initFormElements();
        if(data.tab.id && data.tab.id=='customer_info_tabs_addresses'){
            Element.show($('add_address_button'));
        }
    }
    
    function customerEditHideButtons(data){
        if(data.tab && data.tab.id=='customer_info_tabs_addresses'){
            Element.hide($('add_address_button'));
        }
    }
    
    function customerDelete(){
        if(confirm('<?=__('are you sure?')?>')){
            location.href = '<?=$this->getDeleteUrl()?>'
        }
    }
    
    varienGlobalEvents.attachEventHandler('showTab', customerEditShowButtons);
    varienGlobalEvents.attachEventHandler('hideTab', customerEditHideButtons);
</script>