<div class="content-header">
<table cellspacing="0" class="grid-header">
	<tr>
		<td style="width:50%;"><h3><?=__('Customers')?></h3></td>
		<td class="a-right">
			<button class="scalable" onclick="window.location='<?=$createUrl?>'">
			<table cellspacing="0">
				<tr>
					<td class="tl"></td>
					<td class="tr"></td>
				</tr>
				<tr>
					<td class="ml"><?=__('Add Customer')?></td>
					<td class="mr"></td>
				</tr>
				<tr>
					<td class="bl"></td>
					<td class="br"></td>
				</tr>
			</table>
		    </button>
		</td>
	</tr>
</table>
</div>
<div>
    <?=$this->getChildHtml('grid')?>
</div>
<script type="text/javascript">
function editCustomer(event){
    var element = Event.element(event);
    if(element.tagName != 'A')
    {
        var links = $(Event.findElement(event,'tr')).getElementsByClassName('edit-url');
        if(links.length > 0) {
            location.href = links[0].href;
        }
    }
}
varienGlobalEvents.attachEventHandler('gridRowClick', editCustomer);
</script>