                    <div class="head">
                        <table cellspacing="0"> 
                            <tr>
                                <td style="width:50%;"><h2>Minu Oh - Customer View</h2></td>
                                <td class="buttons"><strong class="button"><span>Save</span></strong></td>
                            </tr>
                        </table>
                    </div>
                    <div class="box-left customer-personal">
                        <h3>Personal Information</h3>
                        <div class="box">
                            <p><strong>Last Logged in:</strong> June, 16, 2007 ( Currently <strong>OFFLINE</strong> )</p>
                            <p><strong>Account Created:</strong> April 1, 2001</p>
                            <address>
                            <strong>Contact Information</strong><br/>Minu Oh ( <a href="mailto:minu@varien.com">minu@varien.com</a>)<br/>
                            3402  Motor Ave Suite B<br/>
                            Los Angeles, CA 90034<br/>
                            United States<br/>
                            <small><strong>T</strong> |</small> (310) 123-1234</address>
                        </div>
                    </div>
                    <div class="box-right sales-tally">
                        <h3>Sales Tally</h3>
                        <div class="box">
                            <table cellspacing="0" class="data">
                                <thead>
                                    <tr>
                                        <th>&nbsp;</th>
                                        <th>Lifetime Sales</th>
                                        <th>Average Sale</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="label">Site 1</td>
                                        <td>$1899.82</td>
                                        <td>$82.99</td>
                                    </tr>
                                    <tr class="even">
                                        <td class="label">Site 1</td>
                                        <td>$1899.82</td>
                                        <td>$82.99</td>
                                    </tr>
                                    <tr>
                                        <td class="label">Site 1</td>
                                        <td>$1899.82</td>
                                        <td>$82.99</td>
                                    </tr>
                                    <tr class="even">
                                        <td class="label">Site 1</td>
                                        <td>$1899.82</td>
                                        <td>$82.99</td>
                                    </tr>
                                    <tr>
                                        <td class="label">Site 1</td>
                                        <td>$1899.82</td>
                                        <td>$82.99</td>
                                    </tr>
                                    <tr class="even">
                                        <td class="label">Site 1</td>
                                        <td>$1899.82</td>
                                        <td>$82.99</td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td class="label"><big>Total</big></td>
                                        <td><big>$9000.82</big></td>
                                        <td><big>$400.99</big></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <br/>
                    <h3>Sales Stat</h3>
                    <dl class="accordion">
                        <dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Last 5 Orders</strong></dt>
                        <dd></dd>
                        <dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Wishlist</strong> (5 items)</dt>
                        <dd class="grid open">
                            <table cellspacing="0" class="data">
                                <thead>
                                    <tr>
                                        <th>Product ID</th>
                                        <th>Product Name</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>00212</td>
                                        <td>Some sort of product name goes here</td>
                                        <td class="price">$82.99</td>
                                    </tr>
                                    <tr class="even">
                                        <td>00212</td>
                                        <td>Some sort of product name goes here</td>
                                        <td class="price">$82.99</td>
                                    </tr>
                                    <tr>
                                        <td>00212</td>
                                        <td>Some sort of product name goes here</td>
                                        <td class="price">$82.99</td>
                                    </tr>
                                    <tr class="even">
                                        <td>00212</td>
                                        <td>Some sort of product name goes here</td>
                                        <td class="price">$82.99</td>
                                    </tr>
                                    <tr>
                                        <td>00212</td>
                                        <td>Some sort of product name goes here</td>
                                        <td class="price">$82.99</td>
                                    </tr>
                                    <tr class="even">
                                        <td>00212</td>
                                        <td>Some sort of product name goes here</td>
                                        <td class="price">$82.99</td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="2" class="a-right"><strong>Total</strong></td>
                                        <td><strong>$400.99</strong></td>
                                    </tr>
                                </tfoot>
                            </table></dd>
                        <dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Gift Registries</strong> (0 items)</dt>
                        <dd></dd>
                        <dt><a href="#"><img src="<?=$baseUrl?>skins/adminhtml/images/accordion_open.png" alt="" class="v-mid"/></a><strong>Shopping Cart</strong> (1 item)</dt>
                        <dd></dd>
                    </dl>
