<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?><br />
<?php if ($this->getInfo()->getLastTransId() == ''): ?>
    <?php echo Mage::helper('Phoenix_Moneybookers_Helper_Data')->__('Payment has not been processed yet.') ?><br />
<?php else: ?>
    <?php echo Mage::helper('Phoenix_Moneybookers_Helper_Data')->__('Moneybookers Transaction ID: %s', $this->escapeHtml($this->getInfo()->getLastTransId())) ?><br />
<?php endif; ?>
