<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart cart-shared">
    <div class="breadcrumbs">
        <ul>
            <li class="home">
                <a href="<?php echo $this->getContinueShoppingUrl() ?>" title="<?php echo $this->__('Continue Shopping') ?>"><?php echo $this->__('Continue Shopping') ?></a>
            </li>
            <li class="product"><strong><?php echo $this->__('Cart') ?></strong></li>
        </ul>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form id="shopping-cart-form" action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <table id="shopping-cart-table" class="data-table cart-table" cellspacing="0">
            <colgroup>
                <col width="60" />
                <col width="*" />
                <col width="80" />
                <col width="*" />
                <col width="30" />
            </colgroup>
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </tbody>
        </table>
    </form>
    <div class="remove-all-button">
        <a href="#"><?php echo $this->__('Remove All')?></a>
    </div>

    <div class="deals">
        <?php echo $this->getChildHtml('coupon') ?>
        <?php echo $this->getChildHtml('giftcards') ?>
    </div>

    <div class="cart-footer">
        <div class="totals">
            <?php echo $this->getChildHtml('totals'); ?>
        </div>
        <?php if(!$this->hasError()): ?>
            <ul class="checkout-types">
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li><?php echo $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <button type="submit" title="<?php echo $this->__('Update Cart') ?>" id="update-cart"><?php echo $this->__('Update Cart') ?></button>
    </div>
    <script type="text/javascript">
    document.observe("dom:loaded", function() {
        $("update-cart").observe("click", function() {
            $("shopping-cart-form").submit();
        });
    });
    </script>
</div>
