<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
 /* @var $this Mage_Adminhtml_Block_Catalog_Product_Edit_AttributeSet */
?>
<script id="product-template-selector-template" type="text/x-jquery-tmpl">
{{if !term && items.length && !$data.allShown()}}
<h5 class="title">Recent Items</h5>
{{/if}}
<ul data-mage-init="{&quot;menu&quot;:[]}">
    {{each items}}
    <li {{html optionData($value)}}><a href="#">${$value.label}</a></li>
    {{/each}}
</ul>
{{if !term && items.length && !$data.allShown()}}
<button data-mage-init="{actionLink:{event:&quot;showAll&quot;}}" class="action-show-all">
    <span>Show all Templates...</span>
</button>
{{/if}}
</script>
<script>
    jQuery(function ($) {
        $('#product-template-suggest')
            .mage('suggest',<?php echo Mage::helper('Mage_Core_Helper_Data')->jsonEncode($this->getSelectorOptions())?>)
            .on('suggestselect', function (e, ui) {
                if (ui.item.id) {
                    $('#product-edit-form').trigger('changeAttributeSet', ui.item);
                    $('#product-template-suggest-container .action-toggle.active ').trigger('click');
                }
            });
    });
</script>
