<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/giftmessage.js') ?>"></script>
<?php $_order = $this->getOrder() ?>
    <div id="order:messages">
        <?php echo $this->getChildHtml('messages') ?>
    </div>
    <input type="hidden" name="order_id" value="<?php echo $_order->getId() ?>"/>


<!--// Order Information-->
    <div class="box-left">
        <div class="entry-edit">
            <h4 class="icon-head head-order-date"><?php echo Mage::helper('sales')->__('Order Information') ?></h4>
            <fieldset>
             <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Order Create Date') ?></td>
                    <td class="input-ele"><strong><?php echo $this->formatDate($_order->getCreatedAt(), 'medium', true) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Order Status') ?></td>
                    <td class="input-ele"><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
                </tr>
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Purchased From') ?></td>
                    <td class="input-ele"><strong><?php echo $this->getOrderStoreName() ?></strong></td>
                </tr>
                <?php if($_order->getRelationChildId()): ?>
               <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Link to the new order') ?></td>
                    <td class="input-ele"><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                        <?php echo $_order->getRelationChildRealId() ?>
                    </a></td>
                </tr>
                <?php endif; ?>
                <?php if($_order->getRelationParentId()): ?>
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Link to the previous order') ?></td>
                    <td class="input-ele"><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                        <?php echo $_order->getRelationParentRealId() ?>
                    </a></td>
                </tr>
                <?php endif; ?>
                <?php if($_order->getRelationChildId()): ?>
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Link to the new order') ?></td>
                    <td class="input-ele"><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                        <?php echo $_order->getRelationChildRealId() ?>
                    </a></td>
                </tr>
                <?php endif; ?>
                <?php if($_order->getRelationParentId()): ?>
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Link to the previous order') ?></td>
                    <td class="input-ele"><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                        <?php echo $_order->getRelationParentRealId() ?>
                    </a></td>
                </tr>
                <?php endif; ?>
                </table>
            </fieldset>
        </div>
    </div>

<!--// Account Information-->
    <div class="box-right">
        <div class="entry-edit">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>
            <fieldset>
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Email') ?></td>
                    <td class="input-ele"><strong><?php echo $_order->getCustomerEmail() ?></strong><br/><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><?php echo Mage::helper('sales')->__('Send email to customer') ?></a></td>
                </tr>
                <tr>
                    <td class="label"><?php echo Mage::helper('sales')->__('Customer Group') ?></td>
                    <td class="input-ele"><strong><?php echo $this->getCustomerGroupName() ?></strong></td>
                </tr>
			</table>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>


<!--// Billing Address-->
    <div class="box-left">
        <div class="entry-edit">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
            <fieldset>
                <address><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
            </fieldset>
        </div>
    </div>


<!--// Shipping Address-->
    <div class="box-right">
        <div class="entry-edit">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
            <fieldset>
                <address><?php echo $_order->getShippingAddress()->getFormated(true) ?></address>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>


<!--// Payment Method-->
    <div class="box-left">
        <div class="entry-edit">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
            <fieldset>
                <?php echo $this->getPaymentHtml() ?>
            </fieldset>
        </div>
    </div>


<!--// Shipping Information-->
    <div class="box-right">
        <div class="entry-edit">
            <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping Information') ?></h4>
            <fieldset>
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label"><?php echo Mage::helper('sales')->__('Shipping Method') ?></td>
                        <td class="input-ele"><strong><?php echo $_order->getShippingDescription() ?></strong></td>
                    </tr>
                    <?php echo $this->getTrackingHtml() ?>
                </table>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>


<!--// Items Ordered-->
    <div class="entry-view">
        <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items Ordered') ?></h4>
    </div>

    
    <?php echo $this->getItemsHtml() ?>
    <div class="clear"></div>
    <br/>
    <?php echo $this->getGiftmessageHtml() ?>



<!--// Order History-->
    <div class="box-right">
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td width="60%" style="padding-right:6%">
                    <?php if($this->getChildHtml('history')): ?>
                    <?php echo $this->getChildHtml('history') ?><?php endif ?>
                </td>
                <td>
                    <div class="box  order-totals">
                        <?php echo $this->getChildHtml('totals') ?>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="clear"></div>
