<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
var giftMessagesController = {
    toogleRequired: function(source, objects)
    {
        if(!$(source).value.blank()) {
            objects.each(function(item) {
               $(item).addClassName('required-entry');
            });
        } else {
            objects.each(function(item) {
                if($(source).formObj && $(source).formObj.validator) {
                    $(source).formObj.validator.reset(item);
                }
                $(item).removeClassName('required-entry');
            });
        }
    },
    toogleGiftMessage: function(container) {
        if(!$(container).toogleGiftMessage) {
            $(container).toogleGiftMessage = true;
            $(this.getFieldId(container, 'edit')).show();
            $(container).getElementsByClassName('action-link')[0].addClassName('open');
            $(container).getElementsByClassName('default-text')[0].hide();
            $(container).getElementsByClassName('close-text')[0].show();
            this.toogleRequired(this.getFieldId(container, 'message'), [
                this.getFieldId(container, 'sender'),
                this.getFieldId(container, 'recipient')
            ]);
        } else {
            $(container).toogleGiftMessage = false;
            $(this.getFieldId(container, 'message')).formObj = $(this.getFieldId(container, 'form'));

            if(!$(this.getFieldId(container, 'form')).validator) {
                $(this.getFieldId(container, 'form')).validator = new Validation(this.getFieldId(container, 'form'));
            }

            if(!$(this.getFieldId(container, 'form')).validator.validate()) {
                return false;
            }

            new Ajax.Updater(container, $(this.getFieldId(container, 'form')).action, {
                parameters: Form.serialize($(this.getFieldId(container, 'form')), true),
                loaderArea: container
            });
        }

        return false;
    },
    saveGiftMessage: function(container) {
        this.toogleRequired(this.getFieldId(container, 'message'), [
            this.getFieldId(container, 'sender'),
            this.getFieldId(container, 'recipient')
        ]);

        $(this.getFieldId(container, 'message')).formObj = $(this.getFieldId(container, 'form'));

        if(!$(this.getFieldId(container, 'form')).validator) {
            $(this.getFieldId(container, 'form')).validator = new Validation(this.getFieldId(container, 'form'));
        }

        if(!$(this.getFieldId(container, 'form')).validator.validate()) {
            return;
        }

        new Ajax.Request($(this.getFieldId(container, 'form')).action, {
            parameters: Form.serialize($(this.getFieldId(container, 'form')), true),
            loaderArea: container
        });
    },
    getFieldId: function(container, name) {
        return container + '_' + name;
    }
};
</script>
<?$_order = $this->getOrder()?>
    <div id="order:messages">
        <?=$this->getChildHtml('messages')?>
    </div>
    <input type="hidden" name="order_id" value="<?=$_order->getId()?>"/>


<!--// Order Information-->
    <div class="box-left">
        <div class="entry-edit">
            <h4 class="icon-head head-order-date"><?=Mage::helper('sales')->__('Order Information')?></h4>
            <fieldset>
             <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Order Create Date')?></td>
                    <td class="input-ele"><strong><?=$this->formatDate($_order->getCreatedAt(), 'medium', true)?></strong></td>
                </tr>
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Order Status')?></td>
                    <td class="input-ele"><strong><span id="order_status"><?=$_order->getStatusLabel()?></span></strong></td>
                </tr>
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Purchased From')?></td>
                    <td class="input-ele"><strong><?=$this->getOrderStoreName()?></strong></td>
                </tr>
                <?if($_order->getRelationChildId()):?>
               <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Link to the new order')?></td>
                    <td class="input-ele"><a href="<?=$this->getViewUrl($_order->getRelationChildId())?>">
                        <?=$_order->getRelationChildRealId()?>
                    </a></td>
                </tr>
                <?endif;?>
                <?if($_order->getRelationParentId()):?>
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Link to the previous order')?></td>
                    <td class="input-ele"><a href="<?=$this->getViewUrl($_order->getRelationParentId())?>">
                        <?=$_order->getRelationParentRealId()?>
                    </a></td>
                </tr>
                <?endif;?>
                <?if($_order->getRelationChildId()):?>
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Link to the new order')?></td>
                    <td class="input-ele"><a href="<?=$this->getViewUrl($_order->getRelationChildId())?>">
                        <?=$_order->getRelationChildRealId()?>
                    </a></td>
                </tr>
                <?endif;?>
                <?if($_order->getRelationParentId()):?>
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Link to the previous order')?></td>
                    <td class="input-ele"><a href="<?=$this->getViewUrl($_order->getRelationParentId())?>">
                        <?=$_order->getRelationParentRealId()?>
                    </a></td>
                </tr>
                <?endif;?>
                </table>
            </fieldset>
        </div>
    </div>

<!--// Account Information-->
    <div class="box-right">
        <div class="entry-edit">
            <h4 class="icon-head head-account"><?=Mage::helper('sales')->__('Account Information')?></h4>
            <fieldset>
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Email')?></td>
                    <td class="input-ele"><strong><?=$_order->getCustomerEmail()?></strong><br/><a href="mailto:<?=$_order->getCustomerEmail()?>"><?=Mage::helper('sales')->__('Send email to customer')?></a></td>
                </tr>
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Customer Group')?></td>
                    <td class="input-ele"><strong><?=$this->getCustomerGroupName()?></strong></td>
                </tr>
			</table>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>


<!--// Billing Address-->
    <div class="box-left">
        <div class="entry-edit">
            <h4 class="icon-head head-billing-address"><?=Mage::helper('sales')->__('Billing Address')?></h4>
            <fieldset>
                <address><?=$_order->getBillingAddress()->getFormated(true)?></address>
            </fieldset>
        </div>
    </div>


<!--// Shipping Address-->
    <div class="box-right">
        <div class="entry-edit">
            <h4 class="icon-head head-shipping-address"><?=Mage::helper('sales')->__('Shipping Address')?></h4>
            <fieldset>
                <address><?=$_order->getShippingAddress()->getFormated(true)?></address>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>


<!--// Payment Method-->
    <div class="box-left">
        <div class="entry-edit">
            <h4 class="icon-head head-payment-method"><?=Mage::helper('sales')->__('Payment Information')?></h4>
            <fieldset>
                <?=$this->getPaymentHtml()?>
            </fieldset>
        </div>
    </div>


<!--// Shipping Information-->
    <div class="box-right">
        <div class="entry-edit">
            <h4 class="icon-head head-shipping-method"><?=Mage::helper('sales')->__('Shipping Information')?></h4>
            <fieldset>
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label"><?=Mage::helper('sales')->__('Shipping Method')?></td>
                        <td class="input-ele"><strong><?=$_order->getShippingDescription()?></strong></td>
                    </tr>
                    <?=$this->getTrackingHtml()?>
                </table>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>


<!--// Items Ordered-->
    <div class="entry-view">
        <h4 class="icon-head head-products"><?=Mage::helper('sales')->__('Items Ordered')?></h4>
    </div>

    
    <?=$this->getItemsHtml()?>
    <div class="clear"></div>
    <br/>
    <?=$this->getGiftmessageHtml()?>



<!--// Order History-->
    <div class="box-right">
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td width="60%" style="padding-right:6%">
                    <?if($this->getChildHtml('history')):?>
                    <?=$this->getChildHtml('history')?><?endif?>
                </td>
                <td>
                    <div class="entry-edit">
                        <h4 class=""><?=Mage::helper('sales')->__('Order Totals')?></h4>
                        <fieldset>
                        <table cellspacing="5" cellpadding="10" width="100%">
                            <col width="100"/>
                            <tbody>
                                <tr>
                                    <td><?=Mage::helper('sales')->__('Subtotal')?></td>
                                    <td class="a-right"><?=$_order->formatPrice($_order->getSubtotal())?>&nbsp;</td>
                                </tr>
                                <?if ($_order->getTaxAmount()):?>
                                <tr>
                                    <td><?=Mage::helper('sales')->__('Tax')?></td>
                                    <td class="a-right"><?=$_order->formatPrice($_order->getTaxAmount())?>&nbsp;</td>
                                </tr>
                                <?endif;?>
                                <?if ($_order->getShippingAmount()):?>
                                <tr>
                                    <td><?=Mage::helper('sales')->__('Shipping')?></td>
                                    <td class="a-right"><?=$_order->formatPrice($_order->getShippingAmount())?>&nbsp;</td>
                                </tr>
                                <?endif;?>
                                <?if ($_order->getDiscountAmount()):?>
                                <tr>
                                    <td><?=Mage::helper('sales')->__('Discount '.($_order->getCouponCode()?'('.$_order->getCouponCode().')':''))?></td>
                                    <td class="a-right"><?=$_order->formatPrice($_order->getDiscountAmount())?>&nbsp;</td>
                                </tr>
                                <?endif;?>
                                <?if ($_order->getGiftcertAmount()):?>
                                <tr>
                                    <td><?=Mage::helper('sales')->__('Gift Certificate')?></td>
                                    <td class="a-right"><?=$_order->formatPrice($_order->getGiftcertAmount())?>&nbsp;</td>
                                </tr>
                                <?endif;?>
                                <?if ($_order->getCustbalanceAmount()):?>
                                <tr>
                                    <td><?=Mage::helper('sales')->__('Customer Balance')?></td>
                                    <td class="a-right"><?=$_order->formatPrice($_order->getCustbalanceAmount())?>&nbsp;</td>
                                </tr>
                                <?endif;?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td class="label emph"><big><strong><?=Mage::helper('sales')->__('Grand Total')?></strong></big></td>
                                    <td class="a-right emph"><big><strong><?=$_order->formatPrice($_order->getGrandTotal())?></strong></big></td>
                                </tr>
                            </tfoot>
                        </table>
                    </fieldset>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="clear"></div>
