<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   default
 * @package    default_default
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="entry-edit" id="order_history_block">
    <h4 class=""><?=Mage::helper('sales')->__('Order History')?></h4>
    <fieldset>
        <ul>
        <?foreach ($this->getOrder()->getAllStatusHistory() as $_history):?>
            <li>
                <strong><?=$this->helper('core')->formatDate($_history->getCreatedAt(), 'medium')?></strong>
                <?=$this->helper('core')->formatTime($_history->getCreatedAt(), 'medium')?><span class="pipe"></span><?=$_history->getStatusLabel()?>
                <?if($_history->getComment()):?>
                    <br/><?=$_history->getComment()?>
                <?endif;?>
            </li>
        <?endforeach;?>
        </ul>
        <a href="#" onclick="$('history_form').show();this.hide();return false;"><?=Mage::helper('sales')->__('Add Comment')?></a>
        <div id="history_form" class="order-history-form" style="display:none">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=Mage::helper('sales')->__('Status')?></td>
                    <td>
                <select name="history[status]" class="select" id="history_status">
                <?foreach ($this->getStatuses() as $_code=>$_label):?>
                    <option value="<?=$_code?>"<?if($_code==$this->getOrder()->getStatus()):?> selected<?endif;?>><?=$_label?></option>
                <?endforeach;?>
                </select>
            </td>
            </tr>
            <tr>
                <td class="label"><?=Mage::helper('sales')->__('Comment')?></td>
                <td><textarea name="history[comment]" class="input-text" id="history_comment"></textarea></td>
            </tr>
            <tr>
                <td class="label">&nbsp;</td>
                <td><input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1"/>
                <label class="normal" for="history_notify"><?=Mage::helper('sales')->__('Notify Customer')?></label></td>
            </tr>
            <tr>
                <td class="label">&nbsp;</td>
                <td><?=$this->getChildHtml('submit_button')?></td>
            </tr>
          </table>
        </div>
        <div>
        </div>
    </fieldset>
    <script type="text/javascript">
    if($('order_status'))$('order_status').update('<?=$this->getOrder()->getStatusLabel()?>');
    </script>
</div>