<div class="content">
    <h1 class="page-heading">My Account</h1>
    <?=$messages->__toHtml()?>
    <ul>
        <li><a href="<?=$baseUrl?>customer/order/">My orders</a></li>
        <!--li><a href="<?=$baseUrl?>customer/favorite/">My Favorites</a></li-->
        <li><a href="<?=$baseUrl?>customer/account/edit/">Change account information</a></li>
        <li><a href="<?=$baseUrl?>customer/account/changepassword/">Change Password</a></li>
        <li><a href="<?=$baseUrl?>customer/address/">Address Book</a></li>
        <!--li><a href="<?=$baseUrl?>customer/account/newsletter/">Newsletter</a></li-->
    </ul>
    <div class="dotted-separator"></div>
</div>