<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see \Magento\Checkout\Block\Cart
 */
?>
<?php if(!$this->hasError()): ?>
<?php $methods = $this->getMethods('methods') ? : $this->getMethods('top_methods') ?>
<ul class="checkout methods items">
<?php foreach ($methods as $method): ?>
    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
    <li class="item"><?php echo $methodHtml; ?></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>
