<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<button title="<?php echo __('Delete Wish List') ?>" data-wishlist-delete='{"wishlistId":"<?php echo $this->getWishlistInstance()->getId();?>", "redirectUrl":"<?php echo $this->getRedirectUrl()?>", "deleteUrl":"<?php echo $this->getDeleteUrl();?>"}' class="button btn-share left"><span><span><?php echo __('Delete Wishlist') ?></span></span></button>
