<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<style type="text/css">
#contents_fieldset .input-text { width:200px; }
</style>
<div class="entry-edit">
    <?=$this->getFormHtml()?>

    <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__("Contents")?></h4>
    <fieldset id="contents_fieldset">
        <legend><?=$this->__("Contents")?></legend>
        <div id="contents_template" style="display:none">
            <span class="field-row">
                <?=$this->__("Role:")?> <select name="contents[role][]">
                    <optgroup label="Magento">
                    <?foreach ($this->getMageRoles() as $_value=>$_label):?>
                        <option value="<?=$_value?>"><?=$_label?></option>
                    <?endforeach?>
                    </optgroup>
                    <optgroup label="PEAR">
                    <?foreach ($this->getPearRoles() as $_value=>$_label):?>
                        <option value="<?=$_value?>"><?=$_label?></option>
                    <?endforeach?>
                    </optgroup>
                </select>
                <?=$this->__("Path:")?> <input class="input-text" name="contents[path][]"/>
                <?=$this->__("Type:")?> <select name="contents[type][]">
                    <option value="file"><?=$this->__("File")?></option>
                    <option value="dir"><?=$this->__("Recursive Dir")?></option>
                </select>
                <?=$this->__("Ignore:")?> <input class="input-text" style="width:100px" name="contents[ignore][]"/>
                <?=$this->getRemoveRowButtonHtml()?>
            </span>
        </div>
        <div id="contents_container">
            <?if ($this->getData('contents/role')):?>
            <?foreach ($this->getData('contents/role') as $_i=>$_dbField):?>
                <?if (0===$_i) continue;?>
                <span class="field-row">
                    <?=$this->__("Role:")?> <select name="contents[role][]">
                        <optgroup label="Magento">
                        <?foreach ($this->getMageRoles() as $_value=>$_label):?>
                            <option value="<?=$_value?>" <?=$this->getSelected('contents/role/'.$_i, $_value)?>><?=$_label?></option>
                        <?endforeach?>
                        </optgroup>
                        <optgroup label="PEAR">
                        <?foreach ($this->getPearRoles() as $_value=>$_label):?>
                            <option value="<?=$_value?>" <?=$this->getSelected('contents/role/'.$_i, $_value)?>><?=$_label?></option>
                        <?endforeach?>
                        </optgroup>
                    </select>
                    <?=$this->__("Path:")?> <input class="input-text" name="contents[path][]" value="<?=$this->getValue('contents/path/'.$_i)?>"/>
                    <?=$this->__("Type:")?> <select name="contents[type][]">
                        <option value="file" <?=$this->getSelected('contents/type/'.$_i, 'file')?>><?=$this->__("File")?></option>
                        <option value="dir" <?=$this->getSelected('contents/type/'.$_i, 'dir')?>><?=$this->__("Recursive Dir")?></option>
                    </select>
                    <?=$this->__("Ignore:")?> <input class="input-text" style="width:100px"  name="contents[ignore][]" value="<?=$this->getValue('contents/ignore/'.$_i)?>"/>
                    <?=$this->getRemoveRowButtonHtml()?>
                </span>
            <?endforeach?>
            <?endif?>
        </div>
        <?=$this->getAddRowButtonHtml('contents_container', 'contents_template', 'Add Contents Path')?>
    </fieldset>
</div>
