<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
    $_fullInfo = $this->helper('Magento\Tax\Helper\Data')->getCalculatedTaxes($_source);
    global $taxIter; $taxIter++;
?>

<?php if ($_fullInfo && $this->displayFullSummary()): ?>
        <?php foreach ($_fullInfo as $info): ?>
            <?php
                $percent    = $info['percent'];
                $amount     = $info['tax_amount'];
                $baseAmount = $info['base_tax_amount'];
                $title      = $info['title'];
            ?>
            <tr class="totals tax details details-<?php echo $taxIter; ?> <?php echo ($this->getIsPlaneMode()) ? ' plane' : '';?>">
                <td <?php echo $this->getLabelProperties()?>>
                    <?php echo $this->escapeHtml($title); ?>
                    <?php if (!is_null($percent)): ?>
                        (<?php echo (float)$percent; ?>%)
                    <?php endif; ?>
                    <br />
                </td>
                <td <?php echo $this->getValueProperties()?> rowspan="1">
                    <?php echo $_order->formatPrice($amount); ?>
                </td>
            </tr>
        <?php endforeach; ?>
<?php endif;?>

<?php if ($this->displayFullSummary() && $_fullInfo && !$this->getIsPlaneMode()): ?>
<tr class="totals-tax-summary">
<?php elseif ($this->displayFullSummary() && $_fullInfo && $this->getIsPlaneMode()): ?>
<tr class="totals-tax-summary plane">
<?php else: ?>
<tr class="totals-tax">
<?php endif; ?>
    <td <?php echo $this->getLabelProperties()?>>
        <?php if ($this->displayFullSummary()): ?>
            <div class="detailed"><?php echo __('Tax'); ?></div>
        <?php else: ?>
            <?php echo __('Tax'); ?>
        <?php endif;?>
    </td>
    <td <?php echo $this->getValueProperties()?>><?php echo $_order->formatPrice($_source->getTaxAmount()) ?></td>
</tr>
