<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Rss
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="head">
    <h4><?=$this->__('RSS Feeds')?></h4>
</div>
<div class="content">
<?$_feeds=$this->getCatalogFeeds();?>
<?if (count($_feeds)>0):?>
<ul class="bare-list">
    <?foreach ($_feeds as $code => $_feed):?>
        <li><a href="<?=$this->helper('rss')->getCatalogRssUrl($code)?>"><?=$_feed->label?></a></li>
    <?endforeach;?>
</ul>
<?else:?>
<div><?=$this->__('There is no %s.',$this->__('Rss Feeds'));?></div>
<?endif;?>
</div>
