
<p><img src="<?=$this->getCurrentImage()->setType(1)->getSourceUrl()?>" alt="" id="product-gallery-image"/></p>

<?if($_prevUrl = $this->getPreviusImageUrl()):?>
<a href="<?=$_prevUrl?>" class="left"><?=__('Prev')?></a>
<?endif;?>

<?if($_nextUrl = $this->getNextImageUrl()):?>
<a href="<?=$_nextUrl?>" class="right"><?=__('Next')?></a>
<?endif;?>

<script type="text/javascript">
Event.observe(window, 'load', function(){
    var demensions = $('product-gallery-image').getDimensions();
    window.resizeTo(demensions.width+100, demensions.height+160);
});
</script>