<?
/**
 * Product list template
 * 
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?$_productCollection=$this->getLoadedProductCollection()?>
<?if(!$_productCollection->getSize()):?>
<div class="note-msg">
    There are no products matching the selection you are currently shopping by
</div>
<?else:?>

<?=$this->getToolbarHtml()?>
<?// List mode?>
<?if($this->getMode()!='grid'):?>
<div class="listing-type-list catalog-listing">
<?foreach ($_productCollection as $_product):?>
    <div class="listing-item ">
        
        <?// Product Image?>
        <div class="product-image">
            <a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>">
                <img src="<?=$_product->getSmallImageUrl()?>" width="125" height="125" alt="<?=$this->htmlEscape($_product->getName())?>"/>
            </a>
        </div>
        
        <?// Product description?>
        <div class="product-shop">
            <h5><a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>"><?=$_product->getName()?></a></h5>
            <?=$this->getHelper('review/helper')->getSummaryHtml($_product)?>
            <?=$this->getHelper('catalog/product')->getPriceHtml($_product)?>
            <button class="form-button" onclick="setLocation('<?=$this->getAddToCartUrl($_product)?>')"><span>Add to Cart</span></button>
            <div class="clear"></div>
            <div class="description">
                <?=$_product->getDescription()?> 
                <a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>"><small>Learn More</small></a>
            </div>
            <p class="add-to">
                <a href="<?=$this->getAddToWishlistUrl($_product)?>" class="link-cart">Add to Wishlist</a>
                <?if($_compareUrl=$this->getAddToCompareUrl($_product)):?>
                <span class="pipe">|</span>
                <a href="<?=$_compareUrl?>">Add to Compare</a>
                <?endif;?>
            </p>
        </div>
    </div>
<?endforeach;?>
</div>


<?else:?>

<?// Grid Mode?>
<div class="listing-type-grid  catalog-listing"> <!-- the class name will change to .listing-type-cell if viewing in list mode -->
<?$_collectionSize = $_productCollection->count()?>
    <table cellspacing="0" class="generic-product-grid" id="product-list-table">
    <?$i=0; foreach ($_productCollection as $_product):?>
    <?if ($i++%3==0):?>
    <tr>
    <?endif?>
		<td>
            <p class="product-image">
                <a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>">
                    <img src="<?=$_product->getSmallImageUrl()?>" width="135" alt="<?=$this->htmlEscape($_product->getName())?>"/>
                </a>
            </p>
			<h5><a href="<?=$_product->getProductUrl()?>" title="<?=$this->htmlEscape($_product->getName())?>)"><?=$_product->getName()?></a></h5>
			<?=$this->getHelper('review/helper')->getSummaryHtml($_product, 'short')?>
			<?=$this->getHelper('catalog/product')->getPriceHtml($_product)?>
			<button class="form-button" onclick="top.location.href='<?=$this->getAddToCartUrl($_product)?>'"><span>Add to Cart</span></button>
			<div class="clear"></div>
			<p class="add-to">
                <strong>Add to:</strong><br/><a href="<?=$this->getAddToWishlistUrl($_product)?>" class="link-cart">Wishlist</a>
                <?if($_compareUrl=$this->getAddToCompareUrl($_product)):?>
                <span class="pipe">|</span>
                <a href="<?=$_compareUrl?>">Compare</a>
                <?endif;?>
			</p>
		</td>
    <?if ($i%3==0):?>
    </tr>
    <?endif?>
    <?endforeach?>
    <?for($i;$i%3!=0;$i++):?>
        <td class="empty-product">&nbsp;</td>
    <?endfor?>
    <?if ($i%3==0):?>
    </tr>
    <?endif?>
    </table>
	<script type="text/javascript">decorateTable('product-list-table')</script>
</div>

<?endif;?>
<?=$this->getToolbarHtml()?>
<?endif;?>