<?if($this->getItems()->getSize()):?>
<div class="box base-mini up-sell">
	<div class="head">
		<h4><span><?=__('Up-sell')?></span></h4>
	</div>
	<ol id="up-sell-products">
	 <?foreach($this->getItems() as $_item):?>
        <li>
			<div class="product-images">
				<a href="<?=$_item->getProductUrl()?>"><img src="<?=$_item->getSmallImageUrl()?>" alt="<?=$this->htmlEscape($_item->getName())?>" width="38" height="38"/></a>
			</div>
			<div class="product-details">
				<a href="#"><a href="<?=$_item->getProductUrl()?>"><?=$_item->getName()?></a>
				<?=$this->getHelper('catalog/product')->getPriceHtml($_item)?>
				<a href="<?=$this->getAddToCartUrl($_item)?>"><?=__('Add to Cart')?></a>
				<a href="<?=$this->getAddToWishlistUrl($_item)?>"><?=__('Wishlist')?></a>
			</div>
		</li>
	<?endforeach;?>
	</ol>
	<script type="text/javascript">decorateList('up-sell-products')</script>
</div>
<?endif?>