<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php $_product=$this->getProduct() ?>
<div class="product-info-box">
    <div class="product-essential">
    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form">

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shop">
            <h3 class="product-name"><?php echo $this->htmlEscape($_product->getName()) ?></h3>

            <?php if ($this->canEmailToFriend()): ?>
                <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a><br />
            <?php endif; ?>

            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>

            <h4><?php echo $this->__('Quick Overview') ?></h4>
            <div class="short-description"><?php echo nl2br($_product->getShortDescription()) ?></div>

            <div class="divider"></div>

            <fieldset>
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            </fieldset>

                <?php echo $this->getChildHtml('alert_urls') ?>

                <?php echo $this->getChildHtml('container1') ?>

                <?php echo $this->getChildHtml('product_type_data') ?>

                <div class="clear"></div>

            <script type="text/javascript">
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function() {
                    if(this.validator.validate()) {
                        this.form.submit();
                    }
                }.bind(productAddToCartForm);
            </script>
        </div>

    <div class="clear"></div>

    <?php echo $this->getChildHtml('container2') ?>

    </form>
    </div>

    <div class="product-collateral">
        <?php if($_additional = $this->getAdditionalData()): ?>
        <div class="collateral-box">
            <div class="head">
              <h4><?php echo $this->__('Product Description') ?></h4>
            </div>
            <div class="product-specs"><?php echo nl2br($_product->getDescription()) ?></div>
        </div>
        <div class="collateral-box attribute-specs">
            <div class="head">
                <h4><?php echo $this->__('Additional Information') ?></h4>
                <?php //echo $this->getChildHtml('product_options') ?>
            </div>
            <table cellspacing="0" class="data-table" id="product-attribute-specs-table">
            <?php foreach ($_additional as $_data): ?>
            <tr>
                <td class="label"><?php echo $_data['label'] ?></td>
                <td class="data"><?php echo $_data['value'] ?></td>
            </tr>
            <?php endforeach; ?>
            </table>
            <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
        </div>
        <?php endif; ?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
<?php $_product = $this->getProduct() ?>
<?php $_id = $_product->getId() ?>

<?php $simplePricesTax = ($this->helper('tax')->displayPriceIncludingTax() || $this->helper('tax')->displayBothPrices()); ?>

<?php $_minimalPriceValue = $_product->getMinimalPrice() ?>
<?php $_minimalPrice = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $simplePricesTax) ?>

<?php $_price = $this->helper('tax')->getPrice($_product, $_product->getPrice()) ?>
<?php $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice(), $simplePricesTax) ?>
<?php $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice()) ?>
<?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true) ?>

<?php
    $_request = Mage::getSingleton('tax/calculation')->getRateRequest(false, false, false);
    $_request->setProductClassId($_product->getTaxClassId());
    $_tax1 = Mage::getSingleton('tax/calculation')->getRate($_request);

    $_request = Mage::getSingleton('tax/calculation')->getRateRequest();
    $_request->setProductClassId($_product->getTaxClassId());
    $_tax2 = Mage::getSingleton('tax/calculation')->getRate($_request);
?>
<script type="text/javascript">
var optionsPrice = new Product.OptionsPrice(
    {
     'productId':<?php echo (isset($_id) ? $_id : '0') ?>,
     'price':<?php echo (isset($_price) ? $_price : '0') ?>,
     'regularPrice':<?php echo (isset($_regularPrice) ? $_regularPrice : '0') ?>,
     'minimalPrice':<?php echo (isset($_minimalPrice) ? $_minimalPrice : '0') ?>,
     'finalPrice':<?php echo (isset($_finalPrice) ? $_finalPrice : '0') ?>,
     'finalPriceInclTax':<?php echo (isset($_finalPriceInclTax) ? $_finalPriceInclTax : '0') ?>,
     'priceFormat':<?php echo Mage::helper('tax')->getPriceFormat() ?>,
     'includeTax':<?php echo ($this->helper('tax')->displayPriceIncludingTax() ? 'true' : 'false') ?>,
     'tax1':<?php echo $_tax1 ?>,
     'tax2':<?php echo $_tax2 ?>
    });
</script>
