<?
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<?=$this->getMessagesBlock()->getHtml()?>
<?$_product=$this->getProduct()?>
<div class="product-info-box">
	<div class="product-essential">
		<div class="product-img-box">
			<p class="main-product-img">
				<img id="image" src="<?=$_product->getImageUrl()?>" alt="<?=$_product->getName()?>"/>
			</p>
			<div class="image-zoom" id="track_outer">
                <img id="zoom_out" src="<?=$this->getSkinUrl('images/slider_btn_zoom_out.gif')?>" alt="Zoom out" class="btn-zoom-out"/>
				<div id="track">
					<div id="handle"></div>
				</div>
                <img id="zoom_in" src="<?=$this->getSkinUrl('images/slider_btn_zoom_in.gif')?>" alt="Zoom out" class="btn-zoom-in"/>
			</div>
    		<script type="text/javascript">
    			Event.observe(window, 'load', function() {
    				product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out');
    			});
    		</script>
        <?if ($this->getGalleryImages() && $this->getGalleryImages()->getSize()):?>
    		<div class="more-views">
    			<h4>More Views</h4>
    			<ul>
    			<?foreach ($this->getGalleryImages() as $_image):?>
    				<li>
    					<a href="#" onclick="popWin('<?=$this->getGalleryUrl($_image)?>', 'gallery', 'scrollbars=no,width=300,height=300');return false;">
    						<img src="<?=$_image->setType(2)->getSourceUrl();?>" width="68" alt=""/>
    					</a>
    				</li>
    			<?endforeach;?>
    			</ul>
    		</div>
	   <?endif;?>
	   </div>
	   <div class="product-shop">
	   <h3 class="product-name"><?=$_product->getName()?></h3>
            <?=$this->getHelper('review/helper')->getSummaryHtml($_product, null, 1)?>
            <form action="<?=$this->getUrl('checkout/cart/add')?>" method="post" id="product_addtocart_form">
            <input type="hidden" name="product" value="<?=$_product->getId()?>">
            <input type="hidden" name="related_product" id="related-products-field" value="">
            
            <?if($_product->isSuperConfig()):?>
                <?=$this->getChildHtml('super_config')?>
            <?endif;?>

            <?if($_product->getTierPriceCount()>1):?>
                <div class="product-pricing">
                    <ul class="bare">
                    <?foreach($_prices=$_product->getFormatedTierPrice() as $_price):?>
                        <li>Buy <?=$_price['price_qty']?> for <strong><?=$_price['price']?></strong></li>
                    <?endforeach?>
                    </ul>
                </div>
            <?endif;?>
            
            <?if($_product->isSuperGroup()):?>
                <?=$this->getChildHtml('super_group')?>
            <?endif;?>
            
            <?if(!$_product->isSuperGroup()):?>
                <p><small>Availability: In stock. Ships within 24hours.</small></p>
                <?=$this->getHelper('catalog/product')->getPriceHtml($_product)?>
                <fieldset class="add-to-cart-box">
                    <legend>Add items to cart </legend>
                    <span class="qty-box"><label for="qty">Qty:</label> 
                    <input name="qty" type="text" class="input-text qty" id="qty"/></span>
                    <button class="form-button" onclick="productAddToCartForm.submit()"><span>Add to Cart</span></button>
                    <strong>OR</strong>
                </fieldset>
                <div class="add-to-box">
                    <a href="<?=$this->getAddToWishlistUrl($_product)?>">Add to Wishlist</a><br/>
                    <?if($_compareUrl=$this->getAddToCompareUrl($_product)):?>
                    <a href="<?=$_compareUrl?>"><?=__('Add to Compare')?></a>
                    <?endif;?>
                </div>
            <?else:?>
                <p><small>Availability: In stock. Ships within 24hours.</small></p>
                <button class="form-button" onclick="productAddToCartForm.submit()"><span>Add to Cart</span></button> <strong>OR</strong>
                &nbsp;&nbsp;
                <a href="<?=$this->getAddToWishlistUrl($_product)?>">Add to Wishlist</a>
                <?if($_compareUrl=$this->getAddToCompareUrl($_product)):?>
                <span class="pipe">|</span>
                <a href="<?=$_compareUrl?>"><?=__('Add to Compare')?></a>
                <?endif;?>
            <?endif;?>
            </form>
    		<script type="text/javascript">
    			var productAddToCartForm = new VarienForm('product_addtocart_form');
    			productAddToCartForm.submit = function() {
    				if(this.validator.validate()) {
    					this.form.submit();
    				}
    			}.bind(productAddToCartForm);
    		</script>
            <div class="clear"></div>
            <div class="divider"></div>
		</div>
    </div>
		<div class="product-collateral">
            <div class="collateral-box">
			    <div class="head">
                    <h4>Product Description</h4>
                </div>
                <div class="product-specs"><?=$_product->getDescription()?></div>
            </div>
        <?=$this->getChildHtml('upsell_products')?>
		<?if($_additional = $this->getAdditionalData()):?>
		<div class="collateral-box attribute-specs">
			<div class="head">
				<h4>Product Attribute Specs</h4>
			</div>
			<table cellspacing="0" class="data-table" id="product-attribute-specs-table">
			<?foreach ($_additional as $_data):?>
			<tr>
				<td class="label"><?=$_data['label']?></td>
				<td class="data"><?=$_data['value']?></td>
			</tr>
			<?endforeach;?>
			</table>
			<script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
		</div>
		<?endif;?>
		<div class="collateral-box" id="customer-reviews">
		  <?=$this->getChildHtml('product_additional_data')?>
        </div>
	</div>
</div>
