<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('Magento_Wishlist_Helper_Data')->getAddUrl($_product); ?>

<ul class="add-to-links" data-role="add-to-links">
<?php if ($this->helper('Magento_Wishlist_Helper_Data')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></li>
<?php endif; ?>
<?php if ($this->canEmailToFriend()): ?>
    <li><a href="<?php echo $this->helper('Magento_Catalog_Helper_Product')->getEmailToFriendUrl($_product) ?>"><?php echo __('Email to Friend') ?></a></li>
<?php endif; ?>
</ul>
