<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product); ?>

<ul class="add-to-links" data-role="add-to-links">
<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <li><a href="#" data-post='<?php echo $_wishlistSubmitParams; ?>' onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a></li>
<?php endif; ?>
<?php if ($this->canEmailToFriend()): ?>
    <li><a href="<?php echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"><?php echo __('Email to Friend') ?></a></li>
<?php endif; ?>
</ul>
<script type="text/javascript">
    head.js("<?php echo $this->getViewFileUrl('Magento_Wishlist::js/add-to-wishlist.js') ?>", function () {
        jQuery('body').addToWishlist(
            <?php echo $this->helper('Magento\Core\Helper\Data')->jsonEncode(array('productType' => $_product->getTypeId()))?>
        );
    });
</script>
