<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_iphone
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Magento_Catalog_Block_Product_View */
?>
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = Mage::helper('Magento_Wishlist_Helper_Data')->getAddUrl($_product); ?>
<a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, '<?php echo $_wishlistSubmitUrl ?>'); return false;" class="link-wishlist" data-action="add-to-wishlist"><?php echo __('Add to Wishlist') ?></a>
