<?php
/**
 * {license_notice}
 *
 * @category    design
 * @copyright   {copyright}
 * @license     {license_link}
 */

/* @var $this \Magento\Reward\Block\Checkout\Payment\Additional */
?>
<?php if ($this->getCanUseRewardPoints()): ?>
    <div class="checkout onepage payment additional rewardpoints" id="reward_placer">
        <div class="field choice payment">
            <input type="checkbox" name="payment[use_reward_points]" value="1" id="use-reward-points"<?php echo $this->useRewardPoints()?' checked="checked"':'' ?> class="checkbox" />
            <label for="use-reward-points" class="label">
                <span>
                    <?php echo __('Use my reward points; %1 are available.', $this->helper('Magento\Reward\Helper\Data')->formatReward($this->getPointsBalance(), $this->getCurrencyAmount())); ?>
                </span>
            </label>
        </div>
    </div>

    <script type="text/javascript">
        (function($) {
            head.js(
                "<?php echo $this->getViewFileUrl('Magento_Customer::js/checkout-balance.js') ?>",
                function() {
                    $('#use-reward-points').checkoutBalance({
                        balance: <?php echo (float)$this->getCurrencyAmount(); ?>,
                        amountSubstracted: <?php if ($this->useRewardPoints()): ?>true<?php else: ?>false<?php endif; ?>,
                        usedAmount: <?php echo (float)$this->getQuote()->getBaseRewardCurrencyAmount(); ?>
                    });
                });
        })(jQuery);
    </script>
<?php endif; ?>
