<?
/**
 * Template for Mage_Block_Adminhtml_Widget_Grid
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 */
$numColumns = sizeof($this->getColumns());
?>
<?if($this->getCollection()):?>
    <?if($this->canDisplayContainer()):?>
        <?if($this->getGridHeader()):?>
        <div class="content-header">
            <table cellspacing="0" class="grid-header">
                <tr>
                    <td style="width:50%;"><h2><?=$this->getGridHeader();?></h2></td>
                </tr>
            </table>
        </div>
        <?endif?>
        <div id="<?=$this->getId()?>">
    <?else:?>
        <?=$this->getMessagesBlock()->getHtml();?>
    <?endif;?>
<?if($this->getPagerVisibility() || $this->getExportTypes() || $this->getFilterVisibility()):?>
    <table cellspacing="0" class="actions">
        <tr>
        <?if($this->getPagerVisibility()):?>
            <td class="pager">
            <?=__('Page')?>
            <?$_curPage  = $this->getCollection()->getCurPage()?>
            <?$_lastPage = $this->getCollection()->getLastPageNumber()?>
            <?if($_curPage>1):?>
                <a href="#" title="<?=__('Previus page')?>" onclick="<?=$this->getId()?>JsObject.setPage('<?=($_curPage-1)?>');return false;"><img src="<?=$this->getSkinUrl('images/pager_arrow_left.gif')?>" alt="Go to Previous page" class="arrow"/></a>
            <?else:?>
                <img src="<?=$this->getSkinUrl('images/pager_arrow_left_off.gif')?>" alt="Go to Previous page" class="arrow"/>
            <?endif;?>
            
            <input type="text" name="<?=$this->getVarNamePage()?>" value="<?=$_curPage?>" class="input-text page" onkeypress="<?=$this->getId()?>JsObject.inputPage(event, '<?=$_lastPage?>')"/>
            
            <?if($_curPage < $_lastPage):?>
                <a href="#" title="<?=__('Next page')?>" onclick="<?=$this->getId()?>JsObject.setPage('<?=($_curPage+1)?>');return false;"><img src="<?=$this->getSkinUrl('images/pager_arrow_right.gif')?>" alt="Go to Next page" class="arrow"/></a>
            <?else:?>
                <img src="<?=$this->getSkinUrl('images/pager_arrow_right_off.gif')?>" alt="Go to Previous page" class="arrow"/>
            <?endif;?>
            
            <?=__('of')?> &nbsp;<strong><?=$this->getCollection()->getLastPageNumber()?></strong>
            <span class="spacer">|</span>
            <?=__('View')?>
            <select name="<?=$this->getVarNameLimit()?>" onchange="<?=$this->getId()?>JsObject.loadByElement(this)">
                <option value="20"<?if($this->getCollection()->getPageSize()==20):?> selected<?endif;?>>20</option>
                <option value="30"<?if($this->getCollection()->getPageSize()==30):?> selected<?endif;?>>30</option>
                <option value="50"<?if($this->getCollection()->getPageSize()==50):?> selected<?endif;?>>50</option>
                <option value="100"<?if($this->getCollection()->getPageSize()==100):?> selected<?endif;?>>100</option>
                <option value="200"<?if($this->getCollection()->getPageSize()==200):?> selected<?endif;?>>200</option>
            </select>
            <?=__('per page')?><span class="spacer">|</span>
            <?=__('Total')?> <strong><?=$this->getCollection()->getSize()?></strong> 
            <?=__('records found')?>
        </td>
    <?endif?>
    <?if($this->getExportTypes()):?>
        <td class="export a-right">
            <img src="<?=$this->getSkinUrl('images/icon_export.gif')?>" alt="" class="v-middle"/>&nbsp; <?=__('Export to')?>:
            <select name="<?=$this->getId()?>_export" id="<?=$this->getId()?>_export">
            <?foreach ($this->getExportTypes() as $_type):?>
                <option value="<?=$_type->getUrl()?>"><?=$_type->getLabel()?></option>
            <?endforeach;?>
            </select>
            <?=$this->getExportButtonHtml()?>
        </td>
    <?endif;?>
        <td class="filter-actions a-right">
            <?=$this->getMainButtonsHtml()?>
        </td>
        </tr>
    </table>
<?endif;?>
<div class="grid">
<table cellspacing="0" class="data" id="<?=$this->getId()?>_table">
    <?foreach ($this->getColumns() as $_column):?>
    <col <?=$_column->getHtmlProperty()?>></col>
    <?endforeach;?>
    <thead>
        <tr class="headings">
        <?$i=0;foreach ($this->getColumns() as $_column):?>
            <th class="<?=$_column->getHeaderCssClass()?> <?=++$i==$numColumns?'last':''?>"><nobr><?=$_column->getHeaderHtml()?></nobr></th>
        <?endforeach;?>
        </tr>
        <?if ($this->getFilterVisibility()):?>
        <tr class="filter">
        <?$i=0;foreach ($this->getColumns() as $_column):?>
            <th class="<?=++$i==$numColumns?'last':''?>"><?=$_column->getFilterHtml()?></th>
        <?endforeach;?>
        </tr>
        <?endif?>
    </thead>
    <tbody>
    <?if ($this->getCollection()->getSize()>0):?>
    <?foreach ($this->getCollection() as $_index=>$_item):?>
        <tr id="<?=$this->getRowId($_item)?>">
        <?$i=0;foreach ($this->getColumns() as $_column):?>
            <td class="<?=$_column->getCssClass()?> <?=++$i==$numColumns?'last':''?>"><?=$_column->getRowField($_item)?></td>
        <?endforeach;?>
        </tr>
    <?endforeach;?>
    <?elseif ($this->getEmptyText()):?>
    	<tr>
    		<td class="empty-text <?=$this->getEmptyTextClass()?>" colspan="<?=$numColumns?>"><?=$this->getEmptyText()?></td>
    	</tr>
    <?endif;?>
    </tbody>
</table>
</div>
<?if($this->canDisplayContainer()):?>
</div>
<script type="text/javascript" language="javascript">
    <?=$this->getJsObjectName()?> = new varienGrid('<?=$this->getId()?>', '<?=$this->getGridUrl()?>', '<?=$this->getVarNamePage()?>', '<?=$this->getVarNameSort()?>', '<?=$this->getVarNameDir()?>', '<?=$this->getVarNameFilter()?>');
    <?=$this->getJsObjectName()?>.useAjax = '<?=$this->getUseAjax()?>';
    <?if($this->getRowClickCallback()):?>
    <?=$this->getJsObjectName()?>.rowClickCallback = <?=$this->getRowClickCallback()?>;
    <?endif;?>
</script>
<?endif;?>
<?endif?>
