<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/ ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <title><?php echo $this->__('Magento Admin') ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="icon" href="<?php echo $this->getBaseUrl() ?>favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="<?php echo $this->getBaseUrl() ?>favicon.ico" type="image/x-icon">
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>prototype/prototype.js"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>scriptaculous/scriptaculous.js"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>prototype/validation.js"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>mage/translate.js"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/hash.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/events.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/loader.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/grid.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/tabs.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/accordion.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/tools.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/bundle.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/uploader.js') ?>"></script>

    <script type="text/javascript">
        var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
        var BLANK_IMG = '<?php echo $this->getJsUrl() ?>spacer.gif';
        var BASE_URL = '<?php echo $this->getUrl('*') ?>';
        var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';
    </script>

    <style type="text/css" media="all">
        /*<![CDATA[*/ @import "<?php echo $this->getSkinUrl('styles.css') ?>"; /*]]>*/
    </style>
    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]>
        <script defer type="text/javascript" src="<?php echo $this->getJsUrl() ?>lib/ds-sleight.js"></script>
        <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>varien/iehover-fix.js"></script>
    <![endif]-->

    <link rel="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->getSkinUrl('menu.css') ?>"/>
<?php //if($this->getCanLoadCalendarJs()): ?>
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->getJsUrl() ?>calendar/calendar-win2k-1.css" title="win2k-1" />
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>calendar/calendar.js"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>calendar/lang/calendar-en.js"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>calendar/calendar-setup.js"></script>
<?php //endif; ?>

<?php if($this->getCanLoadExtJs()): ?>
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>extjs/ext-tree.js"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl() ?>extjs/ext-tree-checkbox.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getJsUrl() ?>extjs/resources/css/ext-all.css"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getJsUrl() ?>extjs/resources/css/ytheme-magento.css"/>
    <script type="text/javascript">
        Ext.BLANK_IMAGE_URL = '<?php echo $this->getJsUrl() ?>extjs/resources/images/default/s.gif';
        Ext.UpdateManager.defaults.loadScripts = false;
        Ext.UpdateManager.defaults.disableCaching = true;
    </script>
<?php endif; ?>
    <?php echo $this->getChildHtml('js_translate') ?>
<?php if($this->getCanLoadRulesJs()): ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/rules.js') ?>"></script>
<?php endif ?>
</head>
<body id="html-body" class="html-body-popup">
<![if !IE]><table cellspacing="0" width="100%"><tr><td><![endif]>
<div>
        <div class="middle-popup">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
                <?php if($this->getChildHtml('left')): ?>
                <div class="simple-container-left" id="page:main-container">
                    <div class="container <?php echo $this->getContainerCssClass() ?>" id="page:container">
                            <div class="main">
                                    <div class="content-container">
                                            <div class="content" id="content">
                                                <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                                                <?php echo $this->getChildHtml('content') ?>
                                            </div>
                                    </div>
                                    <div class="section-menu" id="page:left">
                                        <?php echo $this->getChildHtml('left') ?>
                                        <div class="bottom"></div>
                                    </div>
                            </div>
                    </div>
                </div>
                <?php else: ?>
                <div class="simple-container-popup" id="page:main-container">
                    <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
                <?php endif; ?>
        </div>


       </div>
<![if !IE]></td></tr></table><![endif]>
        <?php echo $this->getChildHtml('js') ?>

<?php echo $this->getChildHtml('profiler') ?>
<div id="loading-process" style="display:none">
    <p><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo $this->__('Loading...') ?>"/><br/><?php echo $this->__('Loading...') ?></p>
</div>
<div id="loading-mask" style="display:none">
    <p class="loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo $this->__('Loading...') ?>"/></p>
</div>
</body>
</html>