<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php echo $this->getChildHtml('login_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('checkout.onepage.login.extra')?>
<div class="col2-set<?php if (!$this->helper('Magento_Customer_Helper_Data')->isRegistrationAllowed() && !$this->getQuote()->isAllowedGuestCheckout()) echo ' login-only' ?>">
    <div class="col-1">
        <h4><?php echo __('Login') ?></h4>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <p><?php echo __('Already registered?') ?> <?php echo __('Please log in below:') ?></p>
            <ul class="form-list">
                <li>
                    <label for="login-email"><?php echo __('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text" id="login-email" name="login[username]" data-validate="{required:true, 'validate-email':true}" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password"><?php echo __('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text" id="login-password" name="login[password]" data-validate="{required:true, 'validate-password':true}"/>
                    </div>
                </li>
                <?php echo $this->getChildHtml('login.form.additional.info'); ?>
                <li class="note">
                    <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo __('Forgot your password?') ?></a>
                </li>
                <li class="buttons-set">
                    <button type="submit" class="button"><span><span><?php echo __('Login') ?></span></span></button>
                </li>
            </ul>
        </fieldset>
        </form>
    </div>
    <?php if ( $this->isAllowedGuestCheckout() || $this->helper('Magento_Customer_Helper_Data')->isRegistrationAllowed() ): ?>
    <div class="col-2">
        <h4>
            <?php if( $this->isAllowedGuestCheckout() && $this->helper('Magento_Customer_Helper_Data')->isRegistrationAllowed() ): ?>
                <?php echo __('Checkout as a Guest or Register') ?>
            <?php elseif ( $this->isAllowedGuestCheckout() && !$this->helper('Magento_Customer_Helper_Data')->isRegistrationAllowed() ): ?>
                <?php echo __('Checkout as a Guest') ?>
            <?php else: ?>
                <?php echo __('Register to Create an Account') ?>
            <?php endif; ?>
        </h4>
        <?php if( !$this->isAllowedGuestCheckout() && $this->helper('Magento_Customer_Helper_Data')->isRegistrationAllowed() ): ?>
            <p><strong><?php echo __('Register and save time!') ?></strong><br />
            <?php echo __('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo __('Fast and easy check out') ?></li>
                <li><?php echo __('Easy access to your order history and status') ?></li>
            </ul>
        <?php elseif( $this->isAllowedGuestCheckout() && $this->helper('Magento_Customer_Helper_Data')->isRegistrationAllowed() ): ?>
            <p><?php echo __('Register with us for future convenience:') ?></p>
        <?php endif ?>

        <?php if( $this->isAllowedGuestCheckout() ): ?>
            <ul class="form-list form-alt">
                <?php if( $this->isAllowedGuestCheckout() ): ?>
                <li>
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Magento_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
                    <label for="login:guest"><?php echo __('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <?php if( $this->helper('Magento_Customer_Helper_Data')->isRegistrationAllowed() ): ?>
                <li>
                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Magento_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                    <label for="login:register"><?php echo __('Register') ?></label>
                </li>
                <?php endif; ?>
            </ul>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
        <div class="buttons-set">
            <button type="button" class="button" data-checkout='{"isGuestCheckoutAllowed":true}'><span><span><?php echo ($this->isAllowedGuestCheckout() ? __('Continue') : __('Register')) ?></span></span></button>
        </div>
        <span class="please-wait" style="display:none;">
            <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo __('Loading next step...') ?>
        </span>
    </div>
    <?php endif; ?>
    <script type="text/javascript">
        (function($) {
            head.js(
                "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
                "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
                "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
                function() {
                    $('#login-form').validation();
                }
            )}
        )(jQuery);
    </script>
</div>
