<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="" id="co-shipping-form">
<fieldset>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="form-alt">
           <label for="shipping-address-select"><?php echo __('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box"><?php echo $this->getAddressesHtmlSelect('shipping') ?></div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <div class="fieldset">
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
                    <li class="fields"><?php echo $this->getLayout()->createBlock('Magento_Customer_Block_Widget_Name')->setObject($this->getAddress())
                            ->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?>
                    </li>
                    <li>
                        <label for="shipping:company"><?php echo __('Company') ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo __('Company') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </li>
            <?php $_streetValidationClass = $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('street'); ?>
                    <li>
                        <label for="shipping:street1" class="required"><em>*</em><?php echo __('Address') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo __('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('Magento_Customer_Helper_Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="add-field">
                        <div class="input-box">
                            <input type="text" title="<?php echo __('Street Address %1', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php endfor; ?>
                    <li class="fields">
                        <?php if ($this->helper('Magento_Customer_Helper_Address')->isVatAttributeVisible()) : ?>
                        <div class="field">
                            <label for="shipping:vat_id"><?php echo __('VAT Number'); ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo __('VAT Number'); ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </div>
                        <?php endif; ?>
                        <div class="field">
                            <label for="shipping:city" class="required"><em>*</em><?php echo __('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo __('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('city') ?>" id="shipping:city" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:region" class="required"><em>*</em><?php echo __('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo __('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo __('Please select region, state or province') ?></option>
                            </select>
                            <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo __('State/Province') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:postcode" class="required"><em>*</em><?php echo __('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo __('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em><?php echo __('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:telephone" class="required"><em>*</em><?php echo __('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo __('Telephone') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:fax"><?php echo __('Fax') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo __('Fax') ?>" class="input-text <?php echo $this->helper('Magento_Customer_Helper_Address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" />
                            </div>
                        </div>
                    </li>
                    <?php $addressAttributes = $this->getChildBlock('customer_form_shipping_address_user_defined_attributes');?>
                    <?php if ($addressAttributes): ?>
                        <?php $addressAttributes->setEntity($this->getAddress())->setEntityType('customer_address');?>
                        <?php $addressAttributes->setFieldIdFormat('shipping:%1$s')->setFieldNameFormat('shipping[%1$s]');?>
                        <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                    <?php endif;?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <li class="control">
                            <div class="input-box">
                                <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo __('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                            </div>
                            <label for="shipping:save_in_address_book"><?php echo __('Save in address book') ?></label>
                        </li>
                    <?php else:?>
                        <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                    <?php endif;?>
                    <li class="control">
                        <div class="input-box">
                            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        </div>
                        <label for="shipping:same_as_billing"><?php echo __('Use Billing Address') ?></label>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</fieldset>
<div class="buttons-set form-buttons" id="shipping-buttons-container">
    <p class="back-link"><a href="#"><small>&laquo; </small><?php echo __('Back') ?></a></p>
    <button type="button" class="button"><span><span><?php echo __('Continue') ?></span></span></button>
    <span id="shipping-please-wait" class="please-wait" style="display:none;"><img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo __('Loading next step...') ?></span>
</div>
<p class="required"><?php echo __('* Required Fields') ?></p>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('Magento_Checkout::js/region-updater.js') ?>",
            function() {
                $('#shipping\\:country_id').regionUpdater({
                    optionalRegionAllowed: <?php echo ($this->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                    regionListId: '#shipping\\:region_id',
                    regionInputId: '#shipping\\:region',
                    postcodeId: '#shipping\\:postcode',
                    regionJson: <?php echo $this->helper('Magento_Directory_Helper_Data')->getRegionJson() ?>,
                    defaultRegion: "<?php echo $this->getAddress()->getRegionId() ?>",
                    countriesWithOptionalZip: <?php echo $this->helper('Magento_Directory_Helper_Data')->getCountriesWithOptionalZip(true) ?>
                });
            });
    })(jQuery);
</script>
