ALTER TABLE `customer_address`
 DROP FOREIGN KEY `FK_ADDRESS_CUSTOMER`;

ALTER TABLE `customer_address` ADD CONSTRAINT `FK_ADDRESS_CUSTOMER` FOREIGN KEY `FK_ADDRESS_CUSTOMER` (`customer_id`)
    REFERENCES `customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;