<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title">
    <h1><?php echo $this->getFormHeader() ?></h1>
</div>
<span id="gr-please-wait" class="please-wait" style="display:none;">
    <img src="<?php echo $this->getViewFileUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo __('Please wait, loading...') ?>
</span>

<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form action="<?php echo $this->getActionUrl() ?>" method="post" id="gr-search-form">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo __('Search Options') ?></h2>
        <ul class="form-list">
            <li>
                <label for="params-type-id"><?php echo __('Gift Registry Type') ?></label>
                <div class="input-box">
                    <?php echo $this->getTypeSelectHtml() ?>
                </div>
                <p class="note"><?php echo __('For better search results, first choose a gift registry type. By default, we search all registry types.') ?></p>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="params_firstname" class="required"><em>*</em><?php echo __('First Name') ?></label>
                     <div class="input-box">
                        <input name="params[firstname]" id="params_firstname" type="text" value="<?php echo $this->getFormData('firstname') ?>" class="input-text required-entry" />
                    </div>
                </div>
                <div class="field">
                    <label for="params_lastname" class="required"><em>*</em><?php echo __('Last Name') ?></label>
                    <div class="input-box">
                        <input name="params[lastname]" id="params_lastname" type="text" value="<?php echo $this->getFormData('lastname') ?>" class="input-text required-entry" />
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="fieldset" id="gr-type-specific-fieldset" style="display:none;">
        <h2 class="legend"><?php echo __('Type Specific Options') ?></h2>
        <ul class="form-list">
            <li class="fields" id="gr-type-specific-options">
            </li>
        </ul>
    </div>

    <div class="buttons-set form-buttons">
        <input type="hidden" name="params[search]" value="type" />
        <button type="submit" class="button"><span><span><?php echo __('Search') ?></span></span></button>
    </div>
    <p class="required"><?php echo __('* Required Fields') ?></p>
</form>

<div class="divider"></div>

<form action="<?php echo $this->getActionUrl() ?>" method="post" id="gr-search-email-form">
    <div class="fieldset">
        <ul class="form-list">
            <li>
                 <label for="params_email" class="required"><em>*</em><?php echo __('Recipient Email') ?></label>
                 <div class="input-box">
                     <input name="params[email]" id="params_email" type="text" value="<?php echo $this->getFormData('email') ?>" class="input-text required-entry validate-email" />
                 </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set form-buttons">
        <input type="hidden" name="params[search]" value="email" />
        <button type="submit" class="button"><span><span><?php echo __('Search') ?></span></span></button>
    </div>
    <p class="required"><?php echo __('* Required Fields') ?></p>
</form>

<div class="divider"></div>

<form action="<?php echo $this->getActionUrl() ?>" method="post" id="gr-search-id-form">
    <div class="fieldset">
        <ul class="form-list">
            <li>
                 <label for="params_id" class="required"><em>*</em><?php echo __('Gift Registry ID') ?></label>
                 <div class="input-box">
                     <input name="params[id]" id="params_id" type="text" value="<?php echo $this->getFormData('id') ?>" class="input-text required-entry" />
                 </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set form-buttons">
        <input type="hidden" name="params[search]" value="id" />
        <button type="submit" class="button"><span><span><?php echo __('Search') ?></span></span></button>
    </div>
    <p class="required"><?php echo __('* Required Fields') ?></p>
</form>

<script type="text/javascript">
                (function($) {
                    head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
                        "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
                        "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
                        "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
                        "<?php echo $this->getViewFileUrl('Enterprise_GiftRegistry::advanced-search.js')?>", function() {
                            $('form[id^="gr-search"]').validation();
                            $('#params-type-id').advancedSearch({
                                url: '<?php echo $this->getAdvancedUrl() ?>',
                                selectedOption: '<?php echo ($this->getFormData('type_id') ? $this->getFormData('type_id') : null); ?>'
                            });
                        });
                })(jQuery);
</script>

<?php if ($this->getSearchResults() && $this->getSearchResults()->getSize()): ?>
<div class="fieldset">
    <h2 class="legend"><?php echo __('Search Results') ?></h2>
</div>
<?php echo $this->getChildHtml('pager') ?>
<table class="data-table" id="giftregistry-search-results">
    <thead>
        <tr>
            <th><?php echo __('Name') ?></th>
            <th><?php echo __('Location') ?></th>
            <th class="a-center"><?php echo __('Event') ?></th>
            <th class="a-center"><?php echo __('Type') ?></th>
            <th class="a-center"><?php echo __('Event Date') ?></th>
            <th class="a-center"></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->getSearchResults() as $item): ?>
        <tr>
            <td><?php echo $this->escapeHtml($item->getRegistrant()) ?></td>
            <td><?php echo $this->escapeHtml($item->getEventLocation()) ?></td>
            <td><?php echo $this->escapeHtml($item->getTitle()) ?></td>
            <td><?php echo $this->escapeHtml($item->getType()) ?></td>
            <td><?php echo $this->getFormattedDate($item) ?></td>
            <td><a href="<?php echo $this->getRegistryLink($item) ?>"><?php echo __('View') ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">(function($) {$('#giftregistry-search-results').decorate('table')})(jQuery)</script>
<?php echo $this->getChildHtml('pager') ?>
<?php elseif ($this->getSearchResults()): ?>
    <?php echo __('Your search returned no results.') ?>
<?php endif; ?>
