<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Currency') ?></h1>
</div>
<p><?php echo $this->__('Your current currency is: %s.', $currency->getCode()) ?></p>
<p><a href="<?php echo $this->getBaseUrl(); ?>"><?php echo $this->__('Continue &raquo;') ?></a></p>
