<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-online-visitors"><?php echo Mage::helper('Mage_Customer_Helper_Data')->__('Online Customers') ?></h3></td>
        </tr>
    </table>
</div>
<?php echo $this->getChildHtml('grid') ?>
