<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     base_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $this */

$productId = $this->getSaleableItem()->getId();

/** @var \Magento\Catalog\Pricing\Price\RegularPrice $priceModel */
$priceModel = $this->getPriceType('regular_price');

/** @var \Magento\Catalog\Pricing\Price\FinalPrice $finalPriceModel */
$finalPriceModel = $this->getPriceType('final_price');
?>
<?php
if (isset($_GET['showmeprice'])) {
    echo 'Regular Price :' . $this->getPriceType('regular_price')->getValue() . "<br />";
    echo 'Special Price :' . $this->getPriceType('special_price')->getValue(). "<br />";
    echo 'Group Price :' . $this->getPriceType('group_price')->getValue(). "<br />";
    echo 'Catalog Rule Price :' . $this->getPriceType('catalog_rule_price')->getValue(). "<br />";
    echo 'Tier Price :' . $this->getPriceType('tier_price')->getValue(). "<br />";
    echo 'Base Price :' . $this->getPriceType('base_price')->getValue(). "<br />";
    echo 'Final Price :' . $this->getPriceType('final_price')->getValue(). "<br />";
    echo  "<br />";
}
?>
<?php if ($this->showSpecialPrice()): ?>
    <p class="old-price">
        <?php echo $this->renderAmount($priceModel->getCustomAmount($priceModel->getValue(), true), [
            'display_label'     => __('Regular Price:'),
            'price_id'          => $this->getPriceId('old-price-'),
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </p>
    <p class="special-price">
        <?php echo $this->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price:'),
            'price_id'          => $this->getPriceId('product-price-'),
            'include_container' => false
        ]); ?>
    </p>
<?php else: ?>
    <?php echo $this->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $this->getPriceId('product-price-'),
        'include_container' => true
    ]); ?>
<?php endif; ?>

<?php if ($this->showMinimalPrice()): ?>
    <?php if ($this->getUseLinkForAsLowAs()):?>
        <a href="<?php echo $this->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php echo $this->renderAmountMinimal(); ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?php echo $this->renderAmountMinimal(); ?>
        </span>
    <?php endif?>
<?php endif; ?>
