<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Template for displaying product price at product view page, gift registry and wishlist
 *
 * @var $this \Magento\Catalog\Pricing\Render\PriceBox
 */
?>
<?php

/** @var Magento\Catalog\Pricing\Price\MsrpPriceInterface $priceType */
$priceType = $this->getPrice();

/** @var $product \Magento\Catalog\Model\Product */
$product = $this->getSaleableItem();
$productId = $product->getId();
$msrpPrice = '';
$priceElementIdPrefix = $this->getPriceElementIdPrefix() ? $this->getPriceElementIdPrefix() : 'product-price-';
?>

<?php if ($product->getMsrp()): ?>
    <?php $msrpPrice = $this->renderAmount($priceType, [
//        'display_label' => __('Regular Price:'),
        'price_id' => $this->getPriceId() ? $this->getPriceId() : 'old-price-' . $productId,
        'include_container' => false,
        'skip_adjustments' => true
    ]); ?>
    <span class="old-price"><?php echo $msrpPrice ?></span>
<?php endif; ?>

<?php if ($priceType->isShowPriceOnGesture()): ?>
    <?php $priceElementId = $priceElementIdPrefix . $productId . $this->getIdSuffix(); ?>
    <span id="<?php echo $this->getPriceId() ? $this->getPriceId() : $priceElementId ?>" style="display:none"></span>
    <?php $popupId = 'msrp-popup-' . $productId . $this->getRandomString(20); ?>
    <a href="#" id="<?php echo($popupId);?>"><?php echo __('Click for price'); ?></a>
<?php else: ?>
    <span class="msrp message">
     <?php echo $priceType->getMsrpPriceMessage() ?>
    </span>
<?php endif; ?>

<?php if ($this->getDisplayMsrpHelpMessage()): ?>
    <?php $helpLinkId = 'msrp-help-' . $productId . $this->getRandomString(20); ?>
    <a href="#" id="<?php echo $helpLinkId;?>" class="action show map">
        <span><?php echo __("What's this?"); ?></span>
    </a>
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('Magento_Catalog::js/msrp.js') ?>",
            function () {
                <?php if ($priceType->isShowPriceOnGesture()): ?>
                $('#<?php echo($popupId);?>').addToCart({
                    cartForm: "#product_addtocart_form_from_popup",
                    popupId: "#<?php echo $popupId;?>",
                    productName: '<?php echo $product->getName() ?>',
                    realPrice: <?php echo $this->jsonEncode($this->getRealPriceHtml()) ?>,
                    msrpPrice: <?php echo $this->jsonEncode($msrpPrice) ?>,
                    priceElementId: '<?php echo $priceElementId ?>',
                    closeButtonId: '#map-popup-close',
                    popupCartButtonId: "#map-popup-button"
                });
                <?php endif; ?>
                <?php if ($this->getDisplayMsrpHelpMessage()): ?>
                $("#<?php echo $helpLinkId;?>").addToCart({
                    helpLinkId: "#<?php echo $helpLinkId;?>",
                    productName: '<?php echo $product->getName() ?>',
                    closeButtonId: '#map-popup-close'
                });
                <?php endif; ?>
            });
    })(jQuery);
    //]]>
</script>



