<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/** @var \Magento\Pricing\Render\PriceBox $this */
$product = $this->getProduct();
/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $this->getPriceType('tier_price');
$tierPrices = $tierPriceModel->getApplicableTierPrices();
?>

<?php if (count($tierPrices) > 0) : ?>
    <ul class="<?php echo ($this->hasListClass() ? $this->getListClass() : 'prices tier items'); ?>">
    <?php foreach ($tierPrices as $index => $price) : ?>
        <?php
            echo $this->renderAmount($price['website_price'], [
                'price_id' => 'tier-price-' . $index,
                'include_container' => false
            ]);
        ?>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
