<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php
/** @var \Magento\Pricing\Render\PriceBox $this */

/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $this->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
?>
<?php if (count($tierPrices)) : ?>
    <ul class="<?php echo ($this->hasListClass() ? $this->getListClass() : 'prices tier items'); ?>">
    <?php foreach ($tierPrices as $index => $price) : ?>
        <li class="item">
            <?php
                echo __(
                    'Buy %1 for %2',
                    $price['price_qty'],
                    $this->renderAmount(
                        $price['price'],
                        [
                            'price_id'          => $index,
                            'id_suffix'         => '-' . $index,
                            'include_container' => true
                        ]
                    )
                );
            ?>&nbsp;<?php echo __('each') ?>
            <?php if ($this->getShowDetailedPrice() !== false): ?>
                <?php echo __('and') ?>&nbsp;<strong class="benefit">
                    <?php echo __('save')?>
                    <span class="percent tier-<?php echo $index ?>"><?php echo $tierPriceModel->getSavePercent($price['price']) ?></span>%
                </strong>
            <?php endif ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
