<title><?php echo htmlspecialchars($this->getTitle()) ?></title>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>"/>
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>"/>
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>"/>

<link rel="icon" href="<?php echo $this->getBaseUrl() ?>favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getBaseUrl() ?>favicon.ico" type="image/x-icon"/>

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->getJsUrl() ?>blank.html';
</script>

<?php echo $this->getAdditionalCssJs() ?>
<?php echo $this->getChildHtml() ?>

<?php echo $this->helper('core/js')->getTranslatorScript() ?>
