<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
 ?>
<script type="text/javascript">
require([
    "prototype",
    "Magento_Sales/order/create/form",
    "Magento_Catalog/catalog/product/composite/configure"
], function(){

    order.sidebarHide();
    Event.observe(window, 'load',  function() {
        if (window.productConfigure) {
            productConfigure.addListType('product_to_add', {
                urlFetch: '<?php echo $this->getUrl('sales/order_create/configureProductToAdd') ?>'
            });
            productConfigure.addListType('quote_items', {
                urlFetch: '<?php echo $this->getUrl('sales/order_create/configureQuoteItems') ?>'
            });
        }
    });

});
</script>
