<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */

/**
 * Downloadable product type
 *
 * @var $this \Magento\Downloadable\Block\Catalog\Product\View\Type
 */
?>
<?php $_product = $this->getProduct() ?>

<?php if($_product->getIsSalable()): ?>
    <p class="stock available" title="<?php echo __('Availability') ?>">
        <span><?php echo __('In stock') ?></span>
    </p>
<?php else: ?>
    <p class="stock unavailable" title="<?php echo __('Availability') ?>">
        <span><?php echo __('Out of stock') ?></span>
    </p>
<?php endif; ?>
<?php echo $this->getChildHtml() ?>