<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?$_invoice = $this->getInvoice()?>
<?$_order = $_invoice->getOrder()?>
<div class="box-left">
    <div class="entry-edit">
        <h4 class="icon-head head-edit-form"><?=$this->helper('sales')->__('Invoice Information')?></h4>
        <fieldset>
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?=$this->helper('sales')->__('Invoice State')?></label></td>
                <td class="input-ele"><strong><span id="invoice_state"><?=$this->getInvoice()->getStateName()?></span></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?=$this->helper('sales')->__('Invoice Date')?></label></td>
                <td class="input-ele"><strong><?=$this->formatDate($this->getInvoice()->getCreatedAt(), 'medium', true)?></strong></td>
            </tr>
            </table>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <div class="entry-edit">
        <h4 class="icon-head head-edit-form"><?=$this->helper('sales')->__('Order Information')?></h4>
        <fieldset>
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?=$this->helper('sales')->__('Order')?></label></td>
                <td class="input-ele"><a href="<?=$this->getOrderUrl()?>">
                    <?=$_order->getRealOrderId()?>
                </a></td>
            </tr>
            <tr>
                <td class="label"><label><?=$this->helper('sales')->__('Order Status')?></label></td>
                <td class="input-ele"><strong><span id="order_status"><?=$_order->getStatusLabel()?></span></strong></td>
            </tr>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <h4 class="icon-head head-billing-address"><?=$this->helper('sales')->__('Billing Address')?></h4>
        <fieldset>
            <address><?=$_order->getBillingAddress()->getFormated(true)?></address>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <h4 class="icon-head head-shipping-address"><?=$this->helper('sales')->__('Shipping Address')?></h4>
        <fieldset>
            <address><?=$_order->getShippingAddress()->getFormated(true)?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>


<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <h4 class="icon-head head-payment-method"><?=$this->helper('sales')->__('Payment Information')?></h4>
        <fieldset>
            <div><?=$this->getChildHtml('payment_info')?></div>
        </fieldset>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <h4 class="icon-head head-shipping-method"><?=$this->helper('sales')->__('Shipping Information')?></h4>
        <fieldset>
            <strong><?=$_order->getShippingDescription()?></strong>
            (<?=$_order->formatPrice($_order->getShippingAmount())?>)
        </fieldset>
    </div>
</div>
<div class="clear"></div>

<div class="entry-view">
    <h4 class="icon-head head-products"><?=$this->helper('sales')->__('Items Invoiced')?></h4>
</div>
<div id="invoice_item_container">
    <div class="grid">
        <table cellspacing="0" class="data" id="invoice_items_grid_table">
            <col/>
            <col width="100"/>
            <col width="70"/>
            <col width="90"/>
            <col width="90"/>
            <col width="100"/>
            <col width="100"/>
            <thead>
                <tr class="headings">
                    <th><?=$this->helper('sales')->__('Product')?></th>
                    <th><?=$this->helper('sales')->__('Price')?></th>
                    <th><?=$this->helper('sales')->__('Qty')?></th>
                    <th><?=$this->helper('sales')->__('Subtotal')?></th>
                    <th><?=$this->helper('sales')->__('Tax Amount')?></th>
                    <th><?=$this->helper('sales')->__('Discount Amount')?></th>
                    <th class="last"><?=$this->helper('sales')->__('Row Total')?></th>
                </tr>
            </thead>
            <tbody>
                <?$_items = $this->getInvoice()->getAllItems()?>
                <?$i=0;foreach ($_items as $_item):$i++?>
                    <tr class="<?=($i%2==0)?'even':'odd'?>">
                        <td>
                            <?=$_item->getName()?>
                            <div><strong><?=$this->helper('sales')->__('SKU')?>:</strong> <?=$_item->getSku()?></div>
                        </td>
                        <td class="price"><?=$this->formatPrice($_item->getPrice())?></td>
                        <td><?=$_item->getQty()*1?></td>
                        <td class="price"><?=$this->formatPrice($_item->getRowTotal())?></td>
                        <td class="price"><?=$this->formatPrice($_item->getTaxAmount())?></td>
                        <td class="price"><?=$this->formatPrice(-$_item->getDiscountAmount())?></td>
                        <td class="price last">
                            <?=$this->formatPrice($_item->getRowTotal()+$_item->getTaxAmount()-$_item->getDiscountAmount())?>
                        </td>
                    </tr>
                <?endforeach;?>
            </tbody>
        </table>
    </div>
</div>

<table cellspacing="0" cellpadding="0" width="100%">
    <tr>
        <td>&nbsp;</td>
        <td width="30%" style="padding-right:40px"><?=$this->getChildHtml('comments')?></td>
        <td width="10%"><div class="box order-totals"><?=$this->getChildHtml('totals')?></div></td>
    </tr>
</table>