<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Catalog advanced search form
 *
 * @see \Magento\CatalogSearch\Block\Advanced\Form
 */
?>
<?php $maxQueryLength= $this->helper('Magento\CatalogSearch\Helper\Data')->getMaxQueryLength();?>
<div class="page-title">
    <h1><?php echo __('Catalog Advanced Search') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSearchPostUrl() ?>" method="get" id="form-validate">
<div class="fieldset">
    <h2 class="legend"><?php echo __('Search Settings') ?></h2>
    <ul class="form-list" id="advanced-search-list">
        <?php $_counter=1; foreach ($this->getSearchableAttributes() as $_attribute): ?>
        <?php $_code = $_attribute->getAttributeCode() ?>
        <?php if ($_counter%2!=0): ?>
        <li class="fields">
        <?php endif; ?>
            <div class="field">
                <label for="<?php echo $_code ?>"><?php echo $this->getAttributeLabel($_attribute) ?></label>
                <div class="input-box">
                <?php switch($this->getAttributeInputType($_attribute)):
                    case 'number': ?>
                    <div class="range">
                        <input type="text" name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text" maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'less-than-equals-to':'#<?php echo $_code ?>_to'}" />
                        -
                        <input type="text" name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>" class="input-text"  maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'greater-than-equals-to':'#<?php echo $_code ?>'}" />
                    </div>
                    <?php break;
                    case 'price': ?>
                    <div class="range">
                        <input name="<?php echo $_code ?>[from]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text" type="text"  maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'less-than-equals-to':'#<?php echo $_code ?>_to'}" />
                        -
                        <input name="<?php echo $_code ?>[to]" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text" type="text"  maxlength="<?php echo $maxQueryLength;?>" data-validate="{number:true, 'greater-than-equals-to':'#<?php echo $_code ?>'}" />

                        (<?php echo $this->getCurrency($_attribute); ?>)
                    </div>
                    <?php break;
                    case 'select': ?>
                        <?php echo $this->getAttributeSelectElement($_attribute) ?>
                    <?php break;
                    case 'yesno': ?>
                        <?php echo $this->getAttributeYesNoElement($_attribute) ?>
                    <?php break;
                    case 'date': ?>
                    <div class="range">
                        <?php echo $this->getDateInput($_attribute, 'from') ?>
                        -
                        <?php echo $this->getDateInput($_attribute, 'to') ?>
                    </div>
                    <?php break;
                    default: ?>
                    <input type="text" name="<?php echo $_code ?>" id="<?php echo $_code ?>" value="<?php echo $this->escapeHtml($this->getAttributeValue($_attribute)) ?>" title="<?php echo $this->escapeHtml($this->getAttributeLabel($_attribute)) ?>"  class="input-text <?php echo $this->getAttributeValidationClass($_attribute) ?>"  maxlength="<?php echo $maxQueryLength;?>" />
                <?php endswitch; ?>
                </div>
            </div>
        <?php if ($_counter%2==0 || $_counter==count($this->getSearchableAttributes())): ?>
        </li>
        <?php endif; ?>
        <?php $_counter++; endforeach; ?>
    </ul>
    <?php /*<script type="text/javascript">(function($) {$('#advanced-search-list').decorate('list')})(jQuery)</script>*/ ?>
</div>
<div class="buttons-set form-buttons btn-only">
    <button type="submit" class="button" title="<?php echo __('Search') ?>"><span><span><?php echo __('Search') ?></span></span></button>
</div>
</form>
<script type="text/javascript">
    (function($) {
        head.js(
            "<?php echo $this->getViewFileUrl('jquery/jquery.validate.js') ?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js') ?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js') ?>",
            function() {
                $('#form-validate').validation({
                    errorPlacement: function (error, element) {
                        var parent = element.parent();
                        if (parent.hasClass('range')) {
                            parent.find(this.errorElement + '.' + this.errorClass).remove().end().append(error);
                        } else {
                            error.insertAfter(element);
                        }
                    },
                    messages: {
                        'price[to]': {'greater-than-equals-to': 'Please enter a valid price range.'},
                        'price[from]': {'less-than-equals-to': 'Please enter a valid price range.'}
                    }
                });
            });
    })(jQuery);
</script>
