<?php
/**
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<div style="padding:5px;">
<?php if (count($this->getCollection()->getItems()) > 0): ?>
    <?php foreach ($this->getCollection()->getItems() as $item): ?>
    <span><?php echo $item->getQueryText() ?></span><br />
    <?php endforeach; ?>
<?php else: ?>
<div class="a-center"><?php echo __('There are no search keywords.') ?></div>
<?php endif; ?>
</div>
