<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php $_product = $this->getProduct() ?>
<?php if ($_product->isSaleable()): ?>
<div class="add-to-cart">
    <?php if (!$_product->isGrouped()): ?>
    <label for="qty"><?php echo $this->__('Qty:') ?></label>
    <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>"
           title="<?php echo $this->__('Qty') ?>" class="input-text qty"/>
    <?php endif; ?>
    <button type="submit" title="<?php echo $this->__('Add to Gift Registry') ?>" class="button btn-cart btn-gr">
        <span><span><?php echo $this->__('Add to Gift Registry') ?></span></span></button>
</div>
<?php endif; ?>
<script type="text/javascript">
    (function ($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>", function () {
                $('#product_addtocart_form').validation({
                    /*
                     * @TODO the logic is duplicates logic inside app\code\Mage\Catalog\view\frontend\product\view\addtocart.phtml,
                     *     need to refactor this code and move methods "errorPlacement", "highlight" and "highlight" inside widget "validation"
                     */
                    errorPlacement: function (error, element) {
                        if (element.attr('data-validate') && element.attr('data-validate').indexOf('validate-one-checkbox-required-by-name') > 0) {
                            error.appendTo('#links-advice-container');
                        } else if (element.attr('data-validate')&& element.attr('data-validate').indexOf('validate-grouped-qty') > 0) {
                            $('#super-product-table').siblings(this.errorElement + '.' + this.errorClass).remove();
                            $('#super-product-table').after(error);
                        } else if (element.is(':radio, :checkbox')) {
                            element.closest('ul').after(error);
                        } else {
                            element.after(error);
                        }
                    },
                    highlight: function (element, errorClass) {
                        if ($(element).attr('data-validate') && $(element).attr('data-validate').indexOf('validate-required-datetime') > 0) {
                            $(element).parent().find('.datetime-picker').each(function() {
                                $(this).removeClass(errorClass);
                                if ($(this).val().length === 0) {
                                    $(this).addClass(errorClass);
                                }
                            });
                        } else if ($(element).is(':radio, :checkbox')) {
                            $(element).closest('ul').addClass(errorClass);
                        } else {
                            $(element).addClass(errorClass);
                        }
                    },
                    unhighlight: function (element, errorClass) {
                        if ($(element).attr('data-validate') && $(element).attr('data-validate').indexOf('validate-required-datetime') > 0) {
                            $(element).parent().find('.datetime-picker').removeClass(errorClass);
                        } else if ($(element).is(':radio, :checkbox')) {
                            $(element).closest('ul').removeClass(errorClass);
                        } else {
                            $(element).removeClass(errorClass);
                        }
                    }
                }).prop('action', '<?php echo $this->getAddToGiftregistryUrl() ?>');
            });
    })(jQuery);
</script>

