<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php $_product = $this->getProduct() ?>
<?php if ($_product->isSaleable() && $this->hasOptions()):?>
<div>
    <button  id="bundle-slide" class="button btn-gr btn-cart" type="button"><span><span><?php echo $this->__('Customize and Add to Gift Registry'); ?></span></span></button>
</div>
<?php endif;?>
