<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_modern
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
    <div class="form-subscribe">
        <div class="form-subscribe-header">
            <label for="newsletter"><?php echo $this->__('Newsletter Sign-up:') ?></label>
        </div>
        <div class="input-box">
            <input type="text" name="email" id="newsletter"
                   title="<?php echo $this->__('Sign up for our newsletter') ?>"
                   value="<?php echo $this->__('Enter your email address') ?>"
                   class="input-text" data-validate="{required:true, 'validate-email':true}"/>
        </div>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button">
            <span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    (function($) {
        head.js("<?php echo $this->getViewFileUrl('jquery/jquery.validate.js')?>",
            "<?php echo $this->getViewFileUrl('jquery/jquery.metadata.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation.js')?>",
            "<?php echo $this->getViewFileUrl('mage/validation/validation.js')?>",
            "<?php echo $this->getViewFileUrl('Mage_Newsletter::newsletter.js')?>", function() {
                $('#newsletter').newsletter({
                    formSelector: '#newsletter-validate-detail',
                    placeholder: '<?php echo $this->__('Enter your email address') ?>'
                });
            });
    })(jQuery);
    //]]>
</script>
