<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_modern
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
    <div class="form-subscribe">
        <div class="form-subscribe-header">
            <label for="newsletter"><?php echo $this->__('Newsletter Sign-up:') ?></label>
        </div>
        <div class="input-box">
           <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
        </div>
        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    new Varien.searchForm('newsletter-validate-detail', 'newsletter', '<?php echo $this->helper('Mage_Newsletter_Helper_Data')->__('Enter your email address') ?>');
//]]>
</script>
