<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */

/** @var $this Mage_Backend_Block_Template */
?>
<script type="text/javascript">
    (function ($) {
        $.widget("adminhtml.dialogRates", $.ui.dialog, {
            options: {
                itemRate: {},
                itemRateDefault: {}
            },
            _create: function(){
                $.ui.dialog.prototype._create.apply(this);
                this._getFormData(this.options.itemRateDefault);
            },
            open: function(){
                if(this._trigger('beforeOpen', null, this) === false){
                    return;
                }
                this._applyItem();
                $.ui.dialog.prototype.open.apply(this);

            },
            close: function(){
                $.ui.dialog.prototype.close.apply(this);
            },
            _applyItem: function(){
                var rate = this.options.itemRateDefault,
                        dialogElement = this.uiDialog;
                if (this.options.itemRate && !$.isEmptyObject(this.options.itemRate)) {
                    rate = this.options.itemRate;
                }
                $.each(rate, function(key, value){
                    dialogElement.find('[name="' + key + '"]').attr('value', value);
                });

            },
            updateItemRate: function(){
                this._getFormData(this.options.itemRate);
            },
            _getFormData: function(data){
                $.each(this.uiDialog.find(':input'), function(){
                    if (this.name) {
                        data[this.name] = this.value
                    }
                });
            }
        });

        $().ready(function () {
            var options = {toggleAddButton:false},
                taxRateField = $('#tax_rate').parent();

            $('#tax_rate').multiselect(options);

            taxRateField.find('.mselect-button-add').off('click');

            taxRateField.find('.mselect-list')
                .on('click.mselect-edit', '.mselect-edit', function () {
                    var that = $(this),
                        index = that.parent().index(),
                        select = that.closest('.mselect-list').prev(),
                        id = select.find('option').eq(index).attr('value'),
                        item;

                    for(var i = 0, c = taxRateCollection.length; i < c; i++) {
                        if (taxRateCollection[i].tax_calculation_rate_id == id) {
                            item = taxRateCollection[i];
                            break;
                        }
                    }
                    item.itemElement = that.prev();
                    $('#tax-rate-form')
                        .dialogRates({itemRate: item})
                        .dialogRates('open');
                })
                .on("click.mselect-delete", ".mselect-delete", function () {
                    var that = $(this),
                        index = that.parent().index(),
                        select = that.closest('.mselect-list').prev();

                    if (confirm('<?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Are you sure to delete Tax Rule'); ?>'))
                    that.parent().remove();
                    select.find('option').eq(index).remove();
                })
                .on('click.mselectAdd', '.mselect-button-add', function () {
                    $('#tax-rate-form')
                        .dialogRates({itemRate: {}})
                        .dialogRates('open');
                });

            $('#tax-rate-form').dialogRates({
                title: '<?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Tax Rate'); ?>',
                autoOpen: false,
                id: '<?php echo $this->getJsId() ?>',
                minWidth: 560,
                modal: true,
                resizable: false,
                buttons: [{
                    text: '<?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Cancel'); ?>',
                    id: '<?php echo $this->getJsId('close-button') ?>',
                    click: function() {
                        $(this).dialogRates("close");
                    }
                }, {
                    text: '<?php echo Mage::helper('Mage_Tax_Helper_Data')->__('Save'); ?>',
                    id: '<?php echo $this->getJsId('apply-button') ?>',
                    click: function() {
                        $(this).dialogRates("close");
                        $(this).closest('.ui-dialog-content').dialogRates('updateItemRate');
                        var itemRate = $(this).closest('.ui-dialog-content').dialogRates('option').itemRate;
                        if (itemRate && itemRate.tax_calculation_rate_id) {
                            itemRate.itemElement.find('span').html(itemRate.code);
                            var index = itemRate.itemElement.parent().index();
                            itemRate.itemElement.closest('.mselect-list').prev().find('option').eq(index)
                                    .html(itemRate.code);
                        } else {
                            taxRateField.find('.mselect-input').val(itemRate.code);
                            taxRateField.find('.mselect-save').trigger('mousedown');
                        }
                    }
                }]
            });
        })
    })(jQuery);
</script>
