<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
var roleId = '<?=$roleId?>';

var role = function () {
	return {
		deleteFromRole: function (uid) {
		    if( !confirm('<?=__('Are you sure you want to do it?')?>') ) {
		        return false;
		    }
			var req = new Ajax.Request('<?=$this->getUrl('*/permission_user/deleteuserfromrole')?>', {
				method:'post',
				parameters: {
					user_id: uid
				},
				onSuccess: function(transport){
					eval('var json = ' + transport.responseText);
					if (json.error) {
						alert(json.error_message);
						return false;
					}
                    <?=$this->_getJsObjectName()?>.reload();
				},
				onFailure: function() {
					alert('<?=__('Something went wrong...')?>');
				}
			});
		},

		addUser2Role: function () {
			var uid = $('users').value;
            $('addButton').disabled = true;
			var req = new Ajax.Request('<?=$this->getUrl('*/permission_user/adduser2role')?>', {
				method:'post',
				parameters: {
					role_id: roleId,
					user_id: uid,
					firstname: $('users').options[$('users').selectedIndex].text
				},
				onSuccess: function(transport){
                    $('addButton').disabled = false;
					eval('var json = ' + transport.responseText);
					if (json.error) {
						alert(json.error_message);
						return false;
					}
                    <?=$this->_getJsObjectName()?>.reload();
				},
				onFailure: function() {
					alert('Something went wrong...');
				}
			});
		}
	}
}();
</script>
<h4 class="icon-head head-edit-form fieldset-legend"><?=__('Role Users')?></h4>
<?=$this->_getGridHtml()?>
<select id="users">
	<?php foreach ($users as $user) { ?>
	<option value="<?=$user->getUserId();?>"><?=$user->getFirstname();?></option>
	<?php } ?>
</select>
<button class="scalable" id="addButton" onclick="role.addUser2Role();return false;">
	<table cellspacing="0">
		<tbody>
			<tr>
				<td class="tl"></td>
				<td class="tr"></td>
			</tr>
			<tr>
				<td class="ml"><?=__('Add')?></td>
				<td class="mr"></td>
			</tr>
			<tr>
				<td class="bl"></td>
				<td class="br"></td>
			</tr>
		</tbody>
	</table>
</button>
