<script type="text/javascript">
<!--
<?$myBlock = $this->getLayout()->getBlock('roleUsersGrid');?>

<?if( is_object($myBlock) && $myBlock->getJsObjectName() ):?>
    var warning = false;
    var inRoleUsers = $H(<?=$myBlock->_getUsers(true)?>);
    if (inRoleUsers.size() > 0) warning = true;
    $('in_role_user').value = inRoleUsers.toQueryString();

    function registerUserRole(grid, element, checked){
        if(checked){
            inRoleUsers[element.value] = 0;
        } else {
            inRoleUsers.remove(element.value);
        }
        $('in_role_user').value = inRoleUsers.toQueryString();
        grid.reloadParams = {'in_role_user[]':inRoleUsers.keys()};
    }

    function roleUsersRowClick(grid, event){
        var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if(trElement){
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                if (warning) {
                    alert("<?=__('Warning!\r\nThis action will remove this user from already assigned role')?>");
                    warning = false;
                }
                <?=$myBlock->getJsObjectName()?>.setCheckboxChecked(checkbox[0], checked);
            }
        }
    }

    function roleUsersRowInit(grid, row){
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        var position = $(row).getElementsByClassName('input-text')[0];
    }

<?=$myBlock->getJsObjectName()?>.rowClickCallback = roleUsersRowClick;
<?=$myBlock->getJsObjectName()?>.initRowCallback = roleUsersRowInit;
<?=$myBlock->getJsObjectName()?>.checkboxCheckCallback = registerUserRole;
<?=$myBlock->getJsObjectName()?>.rows.each(function(row){roleUsersRowInit(<?=$myBlock->getJsObjectName()?>, row)});

<?endif;?>
//-->
</script>