<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td style="width:50%;">
                <h3>
                  <?if($this->getUserId()):?>
                  <?=__('Edit User \'' . $userData->getFirstname() . ' ' . $userData->getLastname()) . '\''?>
                  <?else:?>
                  <?=__('Add New User')?>
                  <?endif;?>
                </h3>
            </td>
            <td class="form-buttons">
            <?=$this->getBackButtonHtml()?>
            <?=$this->getResetButtonHtml()?>
            <?=$this->getDeleteButtonHtml()?>
            <?=$this->getSaveButtonHtml()?>
   </table>
</div>
<form action="<?=$this->getUrl('*/*/saveuser')?>" method="POST" id="user_edit_form">
</form>
<script type="text/javascript" language="javascript">
    var userForm = new varienForm('user_edit_form');
</script>