<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     enterprise_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>
<?php
/**
 * Create account form template
 *
 * @see Magento_CustomerCustomAttributes_Block_Form_Renderer_Textarea
 */
/* @var $this Magento_Rma_Block_Form_Renderer_Textarea */
?>
<label for="items:<?php echo $this->getHtmlId()?>${_index_}"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getLabel() ?></label>
<div class="input-box">
    <textarea id="items:<?php echo $this->getHtmlId()?>${_index_}" name="items[${_index_}][<?php echo $this->getFieldName()?>]" rows="5" cols="25" class="input-text<?php echo $this->getHtmlClass(); ?>"><?php echo $this->getEscapedValue() ?></textarea>
</div>
