<?php
/**
 * {license_notice}
 *
 * @category   Magento
 * @package    Mage
 * @copyright  {copyright}
 * @license    {license_link}
 */

/**
 * Table names association between Magento1 and Magento2 for Enterprise Edition
 * key => Magento1 table name
 * value => Magento2 table name
 */

return array(
    'array(\'enterprise_rma/item\', \'datetime\')' => 'enterprise_rma_item_entity_datetime',
    'array(\'enterprise_rma/item\', \'decimal\')' => 'enterprise_rma_item_entity_decimal',
    'array(\'enterprise_rma/item\', \'int\')' => 'enterprise_rma_item_entity_int',
    'array(\'enterprise_rma/item\', \'text\')' => 'enterprise_rma_item_entity_text',
    'array(\'enterprise_rma/item\', \'varchar\')' => 'enterprise_rma_item_entity_varchar',
    'enterprise_banner/banner' => 'enterprise_banner',
    'enterprise_banner/catalogrule' => 'enterprise_banner_catalogrule',
    'enterprise_banner/content' => 'enterprise_banner_content',
    'enterprise_banner/customersegment' => 'enterprise_banner_customersegment',
    'enterprise_banner/salesrule' => 'enterprise_banner_salesrule',
    'enterprise_catalogevent/event' => 'enterprise_catalogevent_event',
    'enterprise_catalogevent/event_image' => 'enterprise_catalogevent_event_image',
    'enterprise_catalogpermissions/permission' => 'enterprise_catalogpermissions',
    'enterprise_catalogpermissions/permission_index' => 'enterprise_catalogpermissions_index',
    'enterprise_catalogpermissions/permission_index_product' => 'enterprise_catalogpermissions_index_product',
    'enterprise_cms/hierarchy_lock' => 'enterprise_cms_hierarchy_lock',
    'enterprise_cms/hierarchy_metadata' => 'enterprise_cms_hierarchy_metadata',
    'enterprise_cms/hierarchy_node' => 'enterprise_cms_hierarchy_node',
    'enterprise_cms/increment' => 'enterprise_cms_increment',
    'enterprise_cms/page_revision' => 'enterprise_cms_page_revision',
    'enterprise_cms/page_version' => 'enterprise_cms_page_version',
    'enterprise_customer/sales_order' => 'enterprise_customer_sales_flat_order',
    'enterprise_customer/sales_order_address' => 'enterprise_customer_sales_flat_order_address',
    'enterprise_customer/sales_quote' => 'enterprise_customer_sales_flat_quote',
    'enterprise_customer/sales_quote_address' => 'enterprise_customer_sales_flat_quote_address',
    'enterprise_customerbalance/balance' => 'enterprise_customerbalance',
    'enterprise_customerbalance/balance_history' => 'enterprise_customerbalance_history',
    'enterprise_customersegment/customer' => 'enterprise_customersegment_customer',
    'enterprise_customersegment/event' => 'enterprise_customersegment_event',
    'enterprise_customersegment/segment' => 'enterprise_customersegment_segment',
    'enterprise_customersegment/website' => 'enterprise_customersegment_website',
    'enterprise_giftcard/amount' => 'enterprise_giftcard_amount',
    'enterprise_giftcardaccount/giftcardaccount' => 'enterprise_giftcardaccount',
    'enterprise_giftcardaccount/history' => 'enterprise_giftcardaccount_history',
    'enterprise_giftcardaccount/pool' => 'enterprise_giftcardaccount_pool',
    'enterprise_giftregistry/data' => 'enterprise_giftregistry_data',
    'enterprise_giftregistry/entity' => 'enterprise_giftregistry_entity',
    'enterprise_giftregistry/info' => 'enterprise_giftregistry_type_info',
    'enterprise_giftregistry/item' => 'enterprise_giftregistry_item',
    'enterprise_giftregistry/item_option' => 'enterprise_giftregistry_item_option',
    'enterprise_giftregistry/label' => 'enterprise_giftregistry_label',
    'enterprise_giftregistry/person' => 'enterprise_giftregistry_person',
    'enterprise_giftregistry/type' => 'enterprise_giftregistry_type',
    'enterprise_giftwrapping/attribute' => 'enterprise_giftwrapping_store_attributes',
    'enterprise_giftwrapping/website' => 'enterprise_giftwrapping_website',
    'enterprise_giftwrapping/wrapping' => 'enterprise_giftwrapping',
    'enterprise_importexport/scheduled_operation' => 'enterprise_scheduled_operations',
    'enterprise_invitation/invitation' => 'enterprise_invitation',
    'enterprise_invitation/invitation_history' => 'enterprise_invitation_status_history',
    'enterprise_invitation/invitation_track' => 'enterprise_invitation_track',
    'enterprise_logging/event' => 'enterprise_logging_event',
    'enterprise_logging/event_changes' => 'enterprise_logging_event_changes',
    'enterprise_pci/admin_passwords' => 'enterprise_admin_passwords',
    'enterprise_reminder/coupon' => 'enterprise_reminder_rule_coupon',
    'enterprise_reminder/log' => 'enterprise_reminder_rule_log',
    'enterprise_reminder/rule' => 'enterprise_reminder_rule',
    'enterprise_reminder/template' => 'enterprise_reminder_template',
    'enterprise_reminder/website' => 'enterprise_reminder_rule_website',
    'enterprise_reward/reward' => 'enterprise_reward',
    'enterprise_reward/reward_history' => 'enterprise_reward_history',
    'enterprise_reward/reward_rate' => 'enterprise_reward_rate',
    'enterprise_reward/reward_salesrule' => 'enterprise_reward_salesrule',
    'enterprise_rma/item_eav_attribute' => 'enterprise_rma_item_eav_attribute',
    'enterprise_rma/item_eav_attribute_website' => 'enterprise_rma_item_eav_attribute_website',
    'enterprise_rma/item_entity' => 'enterprise_rma_item_entity',
    'enterprise_rma/item_form_attribute' => 'enterprise_rma_item_form_attribute',
    'enterprise_rma/rma' => 'enterprise_rma',
    'enterprise_rma/rma_grid' => 'enterprise_rma_grid',
    'enterprise_rma/rma_shipping_label' => 'enterprise_rma_shipping_label',
    'enterprise_rma/rma_status_history' => 'enterprise_rma_status_history',
    'enterprise_salesarchive/creditmemo_grid' => 'enterprise_sales_creditmemo_grid_archive',
    'enterprise_salesarchive/invoice_grid' => 'enterprise_sales_invoice_grid_archive',
    'enterprise_salesarchive/order_grid' => 'enterprise_sales_order_grid_archive',
    'enterprise_salesarchive/shipment_grid' => 'enterprise_sales_shipment_grid_archive',
    'enterprise_search/recommendations' => 'catalogsearch_recommendations',
    'enterprise_targetrule/customersegment' => 'enterprise_targetrule_customersegment',
    'enterprise_targetrule/index' => 'enterprise_targetrule_index',
    'enterprise_targetrule/index_crosssell' => 'enterprise_targetrule_index_crosssell',
    'enterprise_targetrule/index_related' => 'enterprise_targetrule_index_related',
    'enterprise_targetrule/index_upsell' => 'enterprise_targetrule_index_upsell',
    'enterprise_targetrule/product' => 'enterprise_targetrule_product',
    'enterprise_targetrule/rule' => 'enterprise_targetrule',
);
