<?php
/**
 * {license_notice}
 *
 * @category    design
 * @package     default_default
 * @copyright   {copyright}
 * @license     {license_link}
 */
?>

<?php if ($this->canDisplayGiftmessageForm()): ?>
<div id="gift_options_giftmessage" class="giftcard-form giftcard-send-form fieldset">
    <div class="field">
        <label for="current_item_giftmessage_sender"><?php echo Mage::helper('Mage_GiftMessage_Helper_Data')->__('From'); ?></label>
        <div class="control">
            <input type="text" class="input-text" name="current_item_giftmessage_sender" id="current_item_giftmessage_sender" />
        </div>
    </div>
    <div class="field">
        <label for="current_item_giftmessage_recipient"><?php echo Mage::helper('Mage_GiftMessage_Helper_Data')->__('To'); ?></label>
        <div class="control">
            <input type="text" class="input-text" name="current_item_giftmessage_recipient" id="current_item_giftmessage_recipient" />
        </div>
    </div>
    <div class="field">
        <label for="current_item_giftmessage_message"><?php echo Mage::helper('Mage_GiftMessage_Helper_Data')->__('Message'); ?></label>
        <div class="control">
            <textarea class="textarea" cols="15" rows="2" name="current_item_giftmessage_message" id="current_item_giftmessage_message"></textarea>
        </div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
var giftMessageSet = new GiftMessageSet();
//]]>
</script>
<?php endif; ?>
